### ISSUE TITLE
Using openMVG dll in VS Visual Studio Team Services

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1000]
Dear Pierre,
      Thanks for your outstanding work. Now I'm using openMVG as dll to develop a SfM GUI application, but I can't figue out how to using openMVG's CMake Build as programs in Visual Studio Team Services. When I check openMVG in Team Services and open it, it shows that I can only use the git to edit code in Visual Studio 2015. That drives me crazy, any suggestion?

Best regards,
Sherman

**Comment by pmoulon** [comment]
Dear @learnmano.
I don't know Visual Studio Team Services, I'm always using git in command line mode.

@rperrot Any idea on this?

I'm not sure to caught your question.
Does your question is about using OpenMVG as a third party in a project?
  - https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-in-cmake

or 
Does your question if about a VisualStudio problem to edit the code?

**Comment by rperrot** [comment]
I only used one time TS, only for a git test. It sounds like a big CI/CD server with additional tools (gant-like, backlog product management, ...)

One idea is to make CD of openMVG dll to provide up to date builds as container (as it could be done in docker) but sounds a like bit complicated and overkill to develop in this way. 

@learnmano I think it's better to compile the code locally and develop your tool inside openMVG source tree (in software dir for ex) or use it as a third party as @pmoulon proposed.

**Comment by learnmano** [comment]
Dear @pmoulon, 
       Yes, my question is about using OpenMVG as a third party in a project, but in a dll way, not in a static library way. I used openMVG as a third-party library dependcy before, and I also add some extra code to make it dll libraries, it seems that it works fine locally on my computer, but not so well on another computer, cause the path is different. I'll leave a response when I work it out. Can't thank you more for your time and patience.

**Comment by learnmano** [comment]
@rperrot Okay, I see. I'll compile the code locally and develop my tool inside openMVG source tree. Thank you for your advice, it's very helpful.

**Comment by pmoulon** [comment]
Please close the issue once you succeeded.
BTW, we would be happy to make the DLL build effective for Windows.
Any comment about your changes or a PR regarding this would be nice 😄

**Comment by learnmano** [comment]
Sorry for the delay, the problem is solved successfully. Because I don't how to use openMVG as a thirdparty library in the way the BUILD file said, so I change openMVG source code a little bit.
I start a new program in VS Visual Studio Team Services, and I use some openMVG software as a dll library. For example, as for openMVG_main_ComputeMatches, I add a new head file named main_ComputeMatches.h, and add some extra code like:
`#pragma once
#ifdef OPENMVGDLL_COMPUTEMATCHES_EXPORTS  
#define MVGCOMPUTEMATCHES_API __declspec(dllexport)   
#else  
#define MVGCOMPUTEMATCHES_API __declspec(dllimport)   
#endif 

class MVGCOMPUTEMATCHES_API CSfMComputeMatches
{
public:
	//change the main() function to compute_matches()
	int compute_matches(int argc, char **argv);

};`
Then I add two lines at the beginning in corresponding cpp file:
`#define OPENMVGDLL_COMPUTEMATCHES_EXPORTS
#include "main_ComputeMatches.h"`
After changing the absolute path to relative path, I just use openMVG as a thirdparty library, and it works fine, as for VS Visual Studio Team Services. Thank you all for your patience and enthusiasm. I close this issue, thank you very much.

**Comment by learnmano** [comment]
Sorry for the delay, the problem is solved successfully. Because I don't understand how to use openMVG as a thirdparty library in the way the BUILD file said, so I changed openMVG source code a little bit.
I start a new program in VS Visual Studio Team Services, and I use some openMVG software as a dll library. For example, as for openMVG_main_ComputeMatches, I add a new head file named main_ComputeMatches.h, and add some extra code like:
```
#pragma once
#ifdef OPENMVGDLL_COMPUTEMATCHES_EXPORTS
#define MVGCOMPUTEMATCHES_API __declspec(dllexport)
#else
#define MVGCOMPUTEMATCHES_API __declspec(dllimport)
#endif

class MVGCOMPUTEMATCHES_API CSfMComputeMatches
{
public:
//change the main() function to compute_matches()
int compute_matches(int argc, char **argv);

};
```
Then I add two lines at the beginning in corresponding cpp file:
```
#define OPENMVGDLL_COMPUTEMATCHES_EXPORTS
#include "main_ComputeMatches.h"
```
After changing the absolute path to relative path, I just use openMVG as a thirdparty library, and it works fine, as for VS Visual Studio Team Services. But I don't think it's very helpful for making the DLL build effective for Windows, cause this method is limited. Thank you all for your patience and enthusiasm. I close this issue, again, thank you very much.
