### ISSUE TITLE
ImageListing K matrix not taking effect

### ISSUE THREAD

**Issue by treyfortmuller** [openMVG/openMVG#1001]
I use openMVG_main_SfMInit_ImageListing to create a sfm_data.json file. I include the "-k" flag and specify a K matrix because I want the outputted json file to include my known camera intrinsics. The top of my output after calling my python script looks like this, it appears that the k matrix is included correctly:

```
You called : 
/home/trey.fortmuller/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/trey.fortmuller/PycharmProjects/SfM_test/sfm_in
--sensorWidthDatabase /home/trey.fortmuller/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/trey.fortmuller/PycharmProjects/SfM_test/sfm_out/sfm_matches
--focal -1
--intrinsics 350;0;240;0;350;360;0;0;1
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
```
But the json file that results has this intrinsics entry:

```
"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "width": 480,
                        "height": 718,
                        "focal_length": 611.7488789237668,
                        "principal_point": [
                            240.0,
                            359.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ]

```
It appears that the K matrix I specified is not included and that OpenMVG is estimating them.

Here is how I call `openMVG_main_SfMInit_ImageListing` in my python script:

```
print("INTRINSICS ANALYSIS")  # http://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/
pIntrisics = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),
                               "-i", input_dir,
                               "-o", matches_dir,
                               "-d", camera_file_params,
                               "-k", "350;0;240;0;350;360;0;0;1"])  # this doesn't seem to be taking effect
pIntrisics.wait()

```
Any ideas as to why the proper K matrix isn't showing up? I'm aware that I could always go and edit the file by hand, but I figured I may have found a bug or could be passing the argument incorrectly. I am using the master branch of the library.

**Comment by rperrot** [comment]
It's "normal" behavior, -k is used only in case you don't have Exif data. It seems that your images contains EXIF so this value is used in priority instead of -k 

You may use the -f to force focal point. 

@pmoulon We may check consistency in this tool (ppx/ppy are used but focal is not updated with -k)

**Comment by treyfortmuller** [comment]
@rperrot Perfect thank you for the explanation. My images do have EXIF data that I wasn't aware of. For consistencies sake, it would make sense to me to be able to force the K-matrix seeing as we can force the focal length.

**Comment by rperrot** [comment]
@treyfortmuller Yes, you're right, the option isn't clear for now and "normal" behaviour should be to use the option the user provide instead of the automatic discover. 

Thank you for your use that discover an unwanted behavior.
