### ISSUE TITLE
Lookup Of Camera Name in Sensor Width Database Could Be More Forgiving

### ISSUE THREAD

**Issue by mchildsCO76** [openMVG/openMVG#1002]
I have been testing OpenMVG for point cloud generation and ran across an issue with camera lookup in the sensor width database that I have improved.

The sample images at https://1drv.ms/u/s!Am5GkbZS_98XqJcY7pZBjtpooG3AGQ have a camera name of 'NEX-6' in the EXIF data. This corresponds with the existing more verbose entry in the sensor_width_database.txt file of 'Sony Alpha NEX-6;23.5'. Of course a new entry could just be added to the .txt file, but it seems it would be better to check for a unique sub-string match if no exact match could be found.

I have updated the ParseDatabase.hpp 'getInfo' function to do exactly that. If the exact lookup fails, the list of cameras is checked for a name that includes the provided camera name. If there is exactly one match (or multiple with the same sensor width), that matching Datasheet is used.

I have attached my updated ParseDatabase.hpp file for review. If it looks ok I can check it in. Note this is my first time updating a project in Github so any guidance is welcome.

Thanks,

Mike Childs
[ParseDatabase.hpp.zip](https://github.com/openMVG/openMVG/files/1177196/ParseDatabase.hpp.zip)

**Comment by rperrot** [comment]
Hi @mchildsCO76, 

Thank for your investigation, I think there was already a PR about something similar : 

https://github.com/openMVG/openMVG/pull/952

maybe as a first proposal, you could check if your needs are covered by this PR, and if not propose some modifications in the given thread.

**Comment by mchildsCO76** [comment]
If I understand #952 correctly it is for adding options to the command-line to pass in the camera information, correct? While that could be useful for cases where there is no EXIF information, I also like the change I added to make the existing lookup allow for more variants of the camera name. At least it works well on the one sample I have that wasn't already in the database.

This lookup could perhaps be improved even further by treating some characters as ignored for search purposes, like "- :|", etc. It would be nice if we could count on the EXIF names to be consistent and unique for each camera, but unfortunately it seems that isn't the case.

For my own application I would likely allow users to specify their camera parameters if no match is found and perhaps even track those in an online database so other users could be updated dynamically, at least if this becomes a real problem.

**Comment by rperrot** [comment]
> It would be nice if we could count on the EXIF names to be consistent and unique for each camera, but unfortunately it seems that isn't the case.

I think that's an issue related to the software used to get pictures from the device. They are not always consistent (at least the manufacturer one should be). Moreover using image processing software could modify/erase EXIF data and that's not openMGV related (we could not fix what others software break). 

The issue 952 is indeed related to additional parameters, and I think your proposition could be an additional command line parameter (something like --exif-extended-lookup) to allow the user to search for variation of the exif names. I prefer it to be a parameter and not the default behavior because I'm not sure that truncated name searching could give a wrong match (in your example, are we sure that NEX-6 is never a name of another brand ? What happen also when two names collide ?)

@pmoulon I think we already talked about this issue, I can't find the exact thread.

**Comment by mchildsCO76** [comment]
I have updated my local copy to add a -x [--exif-extended-lookup] command-line parameter to enable the new expanded lookup behavior.

The lookup first does the previous exact match check. If that fails, it looks for any camera model entries that contain the model name from EXIF. If only 1 entry contains the name that is used. If there are multiple entries that contain the model name, none are used unless they all happen to have the same sensor width, so there should be no problem with ambiguity.

I have attached the 2 updated source files if you want to review them. If you agree everything is fine do you want me to check them in or would you like to commit them yourself?
[OpenMVG Source Updates.zip](https://github.com/openMVG/openMVG/files/1188634/OpenMVG.Source.Updates.zip)

**Comment by rperrot** [comment]
Ok in order to integrate your code, you should make a PR (it allows simpler review and code integration). For that : 

- Fork the project 
- Do your modifications (in the develop branch) 
- Then make a PR (always relative to the develop branch)

**Comment by pmoulon** [comment]
Thank you for your feedback ;-)

As @rperrot said you can follow the contributing guide there: https://github.com/openMVG/openMVG/blob/master/CONTRIBUTING.md

**Comment by pmoulon** [comment]
Please do a PR if you want to contribute.

**Comment by mchildsCO76** [comment]
I ended up not actually needing this change at the end so it kind of fizzled out.
