### ISSUE TITLE
Recovering FoV

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#1006]
Hi,

Is there a way to estimate/recover the field of view of a camera with openMVG if we don't have information like the sensor width? I'm aware that traditionally, FoV can be calculated with the focal length and sensor width. However, if focal length is already estimated by openMVG during SfM, and if we have both the 3D locations of some features and their corresponding pixel locations in an image, can we then estimate the FoV using this 2D-3D correspondence?

**Comment by rperrot** [comment]
What you want is a kind of self calibration : 

http://users.cecs.anu.edu.au/~hartley/Papers/calibration/eccv94/calib.pdf

But if openMVG have successfully computed fov, you can directly extract it from K matrix.

**Comment by pmoulon** [comment]
- **Handle image with unknown intrinsics:**
  Often you can provide as input a focal guess and let the BA find a better focal value later on.
-> You can use -f with a value close to `1.2 * max(w,h)` on main_SfMInit_ImageListing

- **Recovering a focal length from 2D-3D correspondences** (as @rperrot said)
  You can use a robust `Absolute pose estimation` solver like the 6pt DLT implementation. It will find a K matrix and so a focal length for your camera. -> https://github.com/openMVG/openMVG/blob/master/src/openMVG/multiview/solver_resection_kernel.hpp#L106

**Comment by ssampang** [comment]
Thanks!
