### ISSUE TITLE
Adding distortion coefficients

### ISSUE THREAD

**Issue by foolsmate** [openMVG/openMVG#1010]
Hello,

Is there any other way to add customized distortion coefficients except by manually editing the sfm_data.json and replacing the disto_k3 params? I have been playing around with different camera calibration settings.

**Comment by pmoulon** [comment]
Hi @foolsmate 
For the moment not. You have to modify by hand the coefficient.

But you can take a look to:

- @hcjghr solution to initialize the camera parameters by using a regex here: https://github.com/openMVG/openMVG/issues/519

- or write a tiny script that allow to customize the json field ;-)
