### ISSUE TITLE
openMVG_main_openMVG2MESHLAB - how to use it ?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#1012]
Hi there,

When i use meshlab with a vertex-colored point cloud whose name is in the .mlp produced by openMVG_main_openMVG2MESHLAB.exe, I can see that the "colored point cloud" is not correctly aligned with the raster.

The colored point cloud is produced by openPMVS.
The .mlp is produced by openMVG_main_openMVG2MESHLAB.exe 
I am using 10 images only for the raster.

Is there some prior adjustments to do ?
I simply did:
openMVG_main_openMVG2MESHLAB.exe -i "path_to_robust.bin" -o .\ -p path_to_Mesh.ply

**Comment by pmoulon** [comment]
It's because the principal point optimized by OpenMVG is not in the middle of the images.
Meshlab does not support a principal point that is not in the middle of the image for the pinhole camera model they are using.

FYI, you can force OpenMVG to keep the principal point in the middle in the image at the SfM stage by using: `-f "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION"`

If you recompute your SFM with this setting and then reexport the scene everything must be ok. (You will have to recompute the mesh too)

**Comment by alvaro562003** [comment]
Thanks,
I am using the sequential pipeline.
I applied once : -f "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION"
and once : "-f", "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION|ADJUST_PRINCIPAL_POINT"


With the config : "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION":
On 4/9 images  the Dense reconstruction & the raster are perfectly aligned,
on 2/9 images  there is small misalignement
on  3/9 images there  is no alignment

All images are taken into account before pmvs, i read : #views: 62 #poses: 62

Did i miss something ?

**Comment by alvaro562003** [comment]
Sorry,  more contextual info.
9 images...means 9 images/raster in meshlab. Meshlab warns not to use more than 10 images.

**Comment by pmoulon** [comment]
With `-f "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION"` it should be aligned.
BTW, why do you need to check this alignement under Meshlab?

Did you plan to perform some post-processing under Meshlab?

**Comment by alvaro562003** [comment]
Yes exactly, i am doing post processing under meshlab.
First i create mesh using meshlab "screened poisson surface reconstruction".
To get a colored mesh, up to now, i used "vertex attribute transfer" to get color vertices.

But the quality of the color is low, and i wanted to try the meshlab raster to increase the quality.
Furthermore, the 3D tool for post-processing are using a texture file, that i do know how to produce with the color attached to the vertices.

**Comment by pmoulon** [comment]
Yes it's my tiny sample test scene.
Meshlab is not done to perform photogrammetry.

BTW, I would recommend you to use MVS tools if you want mesh and texture (see OPENMVG exporter for MVE or OpenMVS).

**Comment by alvaro562003** [comment]
by MVS tools do you mean openMVS tools?
sorry, i am cautious with all the nearly similar acronyms

**Comment by pmoulon** [comment]
`MVS` is the general acronym for `Multiple View Stereovision` => Computation of dense point clouds, surfaces.

So `MVS tools` can include (PMVS, MVE, OpenMVS, CMPMVS ...)

**Comment by alvaro562003** [comment]
Thank you for your answer
Sorry for my delayed reply. I took some holidays.
I solved my color quality issue still using meshlab.
