### ISSUE TITLE
Robust.ply camera positions not matching Export Frustums

### ISSUE THREAD

**Issue by treyfortmuller** [openMVG/openMVG#1013]
I am using `openMVG_main_ComputeStructureFromKnownPoses` to compute a structure knowing the intrinsic and extrinsic parameters. I export frustums to make sure I've got my camera position and rotation matrices entered in sfm_data.json correctly. The frustums look good (you can see the regular, circular motion of my camera rig):

![frustums](https://user-images.githubusercontent.com/5715025/28947183-5eb7a62e-7863-11e7-9b5f-9f1279b4f8c5.png)

But when I got to compute the structure from that same json file, my outputted .ply looks like this.

![points](https://user-images.githubusercontent.com/5715025/28947195-7930bfea-7863-11e7-96ec-f136624ceed7.png)

The green points representing camera centers are no longer in the configuration that they should be and there is only 4 of them rather than the 5 views I specified. Any ideas as to what could be happening here? Here is the output of `openMVG_main_ComputeStructureFromKnownPoses`:

```
COMPUTE SIFT FEATURES
 You called : 
/home/trey.fortmuller/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /home/trey.fortmuller/Desktop/sfm/SfM_test/sfm_out/sfm_matches/sfm_data.json
--outdir /home/trey.fortmuller/Desktop/sfm/SfM_test/sfm_out/sfm_matches
--describerMethod SIFT
--upright 0
--describerPreset ULTRA
--force 1
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 1
COMPUTE MATCHES
 You called : 
/home/trey.fortmuller/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /home/trey.fortmuller/Desktop/sfm/SfM_test/sfm_out/sfm_matches/sfm_data.json
--out_dir /home/trey.fortmuller/Desktop/sfm/SfM_test/sfm_out/sfm_matches
Optional parameters:
--force 1
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
STRUCTURE FROM KNOWN POSES
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 5
 #poses: 5
 #intrinsics: 1
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================

Compute frustum intersection
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***********
*****************************************
*
*
*
*
*
*
*
*
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
*
*
*
*
*
*
*
*
*
*

Structure estimation took (s): 0.

#landmark found: 60
...Generating SfM_Report.html
Point_cloud cleaning:
	 #3DPoints: 49
Bundle adjustment...

Bundle Adjustment statistics (approximated RMSE):
 #views: 5
 #poses: 4
 #intrinsics: 1
 #tracks: 49
 #residuals: 294
 Initial RMSE: 7.76481
 Final RMSE: 0.595128
 Time (s): 0.270932

Found a sfm_data scene with:
 #views: 5
 #poses: 4
 #intrinsics: 1
 #tracks: 49



```

**Comment by pmoulon** [comment]
1. Your camera moved since you asked for a BA at the end of `openMVG_main_ComputeStructureFromKnownPoses`

2. Do you mind to share your sfm_matches directory for let me know check (just zip it and drop it here)?
I don't need your images so I don't think it will be a problem.

**Comment by treyfortmuller** [comment]
Hi @pmoulon you're right, it was performing a bundle adjustment. But my call to `openMVG_main_ComputeStructureFromKnownPoses` looked like this:

```
print("STRUCTURE FROM KNOWN POSES")
pRecons = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeStructureFromKnownPoses"),

                            # switch between using the bin constructed from the global pipeline or our own poses in json
                            # "-i", reconstruction_dir + "/sfm_data.bin",
                            "-i", matches_dir + "/sfm_data.json",

                            "-m", matches_dir,
                            "-o", os.path.join(reconstruction_dir, "robust.ply"),
                            "-b", "OFF",  # perform a bundle adjustment on this data
                            "-r", "100.0"])  # maximum pixel reprojection error to use for triangulation (4.0 default)
pRecons.wait()
```

The bundle adjustment was turned off but it was performed anyway. When I comment out the -b flag and resort to the default, the bundle adjustment does not take place and my point cloud looks as expected.

![point_cloud](https://user-images.githubusercontent.com/5715025/28977698-01ed2d7a-78f8-11e7-8879-7ab6bc95bd6f.png)

Here is my matches bin file anyway:

[matches.e.zip](https://github.com/openMVG/openMVG/files/1201013/matches.e.zip)

**Comment by pmoulon** [comment]
I need the full matches directory (all the directory) not only the match file.

**Comment by treyfortmuller** [comment]
[sfm_matches.zip](https://github.com/openMVG/openMVG/files/1205304/sfm_matches.zip)

**Comment by pmoulon** [comment]
Hi,
First of all, I notice that the following:
- Seems like you already used SIFT with the ULTRA preset in order to try to obtain more features matches.

- according your matches you have two connected component:
![geometric_matches](https://user-images.githubusercontent.com/3235050/29057336-ee80ff54-7c09-11e7-8a1f-bcf4fc40225e.png)
-> Do you know if you expect matches between all the images or not?
-> Since the cameras are not rigidly linked (thanks to some 3d points) it explains why the BA make some camera move independently to each other.

- Please notice that the `-b` option is a switch option. In order to activate it you do `-b`. If not present, no BA will be performed.

I called this command line in order to ask to triangulate the matches.e.bin file:
```
openMVG_main_ComputeStructureFromKnownPoses -i /home/pierre/Pictures/Datasets/treyfortmuller/sfm_matches/sfm_data.json -m /home/pierre/Pictures/Datasets/treyfortmuller/sfm_matches/ -o /home/pierre/Pictures/Datasets/treyfortmuller/sfm_matches/triangulation.ply -f /home/pierre/Pictures/Datasets/treyfortmuller/sfm_matches/matches.e.bin -d
```
and I obtain:
```
======================================
Robust triangulation of the match file
======================================

Building tracks...
Filtering tracks...
------------------
-- Tracks Stats --
 Tracks number: 203
 Images Id: 
0, 1, 2, 3, 4, 
------------------
TrackLength, Count
	2	192
	3	11

====================================
Robust triangulation of the tracks
 - tracks computed from a match file
====================================
Robust triangulation progress:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************....*****************************

#landmark found: 34
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 5
 #poses: 5
 #intrinsics: 1
 #tracks: 34
```

If you want to go further, I would suggest:
- to double check your internal and external calibration
- Test your camera rig with a feature rich environment in order to better see the structure.

- Do you mind to share also your images? (you can share them privately by mail if you want)

**Comment by treyfortmuller** [comment]
Thank you for the feedback! Is there a way to rigidly link the cameras such that I can perform a BA on only the 3d points generated? The linked components look basically correct, I would expect adjacent frames to share matches but not all the frames to share matches based on the rotation of my camera rig. Structure definitely improves with more frames and with a more feature rich environment (with 11 frames instead of 5 I am able to generate upwards of 1000 points).

What difference does including the match bin file with the `"-f"` flag make for `openMVG_main_ComputeStructureFromKnownPoses`? I don't notice a major difference in my point cloud by including it. Also, the `"-d"` flag you included isn't in the documentation for this binary, what does it do?

![structfromknown](https://user-images.githubusercontent.com/5715025/29098245-402ab07c-7c53-11e7-8a14-d7f3e9ee7279.png)

I believe the autofocus of the webcam I am using to create my dataset makes the focal length variable and ruins my intrinsics so I will be switching cameras to avoid this.

**Comment by pmoulon** [comment]
If you want to fix the camera poses for the BA step you can change the value Extrinsic_Parameter_Type::ADJUST_ALL to Extrinsic_Parameter_Type::NONE here https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeStructureFromKnownPoses.cpp#L347 It will force the camera motion to stay constant.

The `-d` make a direct triangulation of the match file (keep track of length two).
Without this option the triangulation are made using the algorithm explained here https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeStructureFromKnownPoses/#openmvg-main-computestructurefromknownposes (So find correspondences along the epipolar lines and triangulate them).

**Comment by pmoulon** [comment]
Can we close the issue?

**Comment by pmoulon** [comment]
Did you was able to generate the desired output?
