### ISSUE TITLE
unable to run OpenMVG

### ISSUE THREAD

**Issue by Nish160** [openMVG/openMVG#1017]
I want to run complete openMVS+openMVG pipeline on a given set of images , but I am not able to run the entire pipeline following these instructions:https://github.com/cdcseacave/openMVS/wiki/Usage
On running it shows the following error:
![screenshot from 2017-08-08 15-35-58](https://user-images.githubusercontent.com/30828701/29067353-d2bab48c-7c21-11e7-8945-e6643c50db1d.png)

'Invalid input database: /home/nishima/OpenMVG/openMVG_Build/Linux-x86_64-RELEASE/sensor_width_camera_database.txt, please specify a valid file.'
I have checked the sensor_width_camera_database.txt file it doesn't contains my camera brand, model which is DJI,FC330(present in image properties)
I guess this may be the cause of error.

I also tried running only OpenMVG as follows:
But it still shows the same error
I am not able to resolve the issue.please help.

**Comment by rperrot** [comment]
Does the file /home/nishima/OpenMVG/openMVG_Build/Linux-x86_64-RELEASE/sensor_width_camera_database.txt exists ? (with that exact path). 

> I have checked the sensor_width_camera_database.txt file it doesn't contains my camera brand, model which is DJI,FC330(present in image properties)

This may effectively be an issue but the error should not be here and with that message.

**Comment by Nish160** [comment]
No, the file doesn't exist at that path.
After searching through the repository I could get the file at : /home/nishima/OpenMVG/openMVG/src/openMVG/exif/sensor_width_database

Also,I have built both openMVS and openMVG in Ubuntu16.04 virtual machine using vmware

**Comment by rperrot** [comment]
Ok. What's the content of your script (the issue may be here) ?

**Comment by pmoulon** [comment]
I think you encounter a path issue after having copied some files to one VR to another.

**Comment by Nish160** [comment]
@rperrot   Here's the script part that I have changed:
![screenshot from 2017-08-09 09-50-30](https://user-images.githubusercontent.com/30828701/29105108-2e90685e-7cba-11e7-868c-bd4f96ba7157.png)
I have used this script from:
https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py

I have only made changes where the OpenMVS and OpenMVG bin paths have to be specified to refer to their locations on my system.
But even after building and compiling OpenMVG, it didnt contain any bin folder, So I specified following path:
OPENMVS_BIN = "/home/nishima/openMVS_build/bin"
OPENMVG_BIN = "/home/nishima/OpenMVG/openMVG_Build/Linux-x86_64-RELEASE"

maybe the problem lies here

**Comment by jpwhitney** [comment]
I've had similar issues with the script, I elected to copy the camera width database into the directory specified by (in your picture) line 58.

Alternatively you could direct the script to look for the sensor_width_database.txt file where it is located on your system.

**Comment by rperrot** [comment]
The issue is here : https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py#L55

Change the directory to your camera db directory : 

/home/nishima/OpenMVG/openMVG/src/openMVG/exif/sensor_width_database

We recommend the user to use our pipelines (located in your build/software/SfM/ directory), they are largely tested and known to work out of the box.

**Comment by Nish160** [comment]
@jpwhitney  and @rperrot Thanks .Now that problem is resolved.
But as I mentioned before the sensor_width_database.txt file doesn't contains camera model or sensor width of my images.
Thus on running now even after using the pipelines suggested by @rperrot , I get the following errors:
![screenshot from 2017-08-09 12-44-59](https://user-images.githubusercontent.com/30828701/29109524-cf2ebffa-7cd2-11e7-8417-c359e099c564.png)
I realize that I have to add my camera model and sensor width to the sensor_width_database.txt file ,but how to do that.Any specific format to follow??
for example: 
I have provided a sample image with its properties:
 
![screenshot from 2017-08-09 12-49-23](https://user-images.githubusercontent.com/30828701/29109597-1e70d648-7cd3-11e7-8515-3f2d0e222c1c.png)

Camera:DJI PHANTOM 4 
http://www.dji.com/phantom-4/info#specs
sensor width has to be mentioned in mm or inches?
It would be highly appreciated if you specify me the exact lines to add to the sensor_width_database.txt file and also any further changes required due to this.
Thanks

**Comment by rperrot** [comment]
You should add the following lines at the end of the file sensor_width_camera_database.txt : 

```
DJI FC330;6.17
FC330;6.17
```

**Comment by Nish160** [comment]
Thanks @rperrot .
With these changes I am able to run the complete pipeline now and have got pretty good results. Thanks again.

Actually I want to intercept this pipeline and give my own mesh(CAD model- highly detailed) for texturing in between.
Basically I want to give my CAD model to TextureMesh module of OpenMVS, while the other inputs remaining the same , so that I can get a fully textured CAD model.
Any idea how to do that?

**Comment by pmoulon** [comment]
You can align your CAD model by using GCP (Ground Control Points).
1. Pick some particular point on your CAD model and extract their 3D coordinates.
2. Use the OpenMVG GCP app to link image correspondences to your 3D points
3. Align and rescale the SfM reconstruction to your CAD model coordinates thanks to the app.

See [here](http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/)

**Comment by ahananq** [comment]
> @rperrot Here's the script part that I have changed:
> ![screenshot from 2017-08-09 09-50-30](https://user-images.githubusercontent.com/30828701/29105108-2e90685e-7cba-11e7-868c-bd4f96ba7157.png)
> I have used this script from:
> https://github.com/cdcseacave/openMVS_sample/blob/master/MvgMvs_Pipeline.py
> 
> I have only made changes where the OpenMVS and OpenMVG bin paths have to be specified to refer to their locations on my system.
> But even after building and compiling OpenMVG, it didnt contain any bin folder, So I specified following path:
> OPENMVS_BIN = "/home/nishima/openMVS_build/bin"
> OPENMVG_BIN = "/home/nishima/OpenMVG/openMVG_Build/Linux-x86_64-RELEASE"
> 
> maybe the problem lies here

Respected Nish160

If you were able to run this successfully. do you still have this whole script ?
