### ISSUE TITLE
Can OpenMVG be reconstruction of images with different resolutions?

### ISSUE THREAD

**Issue by DaytimeAH** [openMVG/openMVG#1022]
I have added two kinds of intrinsics, but in the SfM process will be registered on the issue.
Different resolution images can not be fused.
Separate images with a certain resolution can be registered.
Please help, thanks.

                         "width": 4032,
                        "height": 3024,
                        "focal_length": 3381.4242504510185,
                        "principal_point": [
                            2016.0,
                            1512.0
                        ],
                        "disto_k3": [
                            0.27043684570759247,
                            -1.8399434604404039,
                            3.9766377913108872

                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 2,
                "ptr_wrapper": {
                    "id": 2147483695,
                    "data": {
                        "width": 3840,
                        "height": 2160,
                        "focal_length": 3433.6070893587457,
                        "principal_point": [
                            1919.5,
                            1079.5
                        ],
                        "disto_k3": [
                            0.29717157478222633,
                            -2.4931471522485045,
                            7.0091780164034398
                        ]
                    }
                }
            }
        }
    ],                                                                                                           
IncrementalSfM Report：
![image](https://user-images.githubusercontent.com/12272195/29300535-8fa2c036-81a8-11e7-848e-ce02337533b6.png)

GlobalSfM Report：
![image](https://user-images.githubusercontent.com/12272195/29300872-f57c7eea-81aa-11e7-9a2b-98966fa4d32d.png)

**Comment by rperrot** [comment]
I don't understand your exact question : 
- Yes openMVG could be used with different resolution 
- Do you use images with the same camera ? (ie: does your images are cropped ?)
- Do you have any warning about camera width not in database ?

**Comment by DaytimeAH** [comment]
thank you for your reply, @rperrot 
- Do you use images with the same camera ? (ie: does your images are cropped ?)
   Yes, I use images with the same camera(IPhone 7) and the images are unmodified. 
   There are two origins of images： one is from directly photographing the object，while another is to 
   analysize the video of the object. images from the two origins have different resolutions.
- Do you have any warning about camera width not in database ?
   No, I don't use the sensor_width_database. I use my own calibration's data

**Comment by pmoulon** [comment]
Can you share your image dataset and your sfm_data.json file?

Since Incremental and GlobalSfm did not make the same part in 3D (each one make a different intrinsic group to work) perhaps your feature matching between those two image group is working well.

Did you look to the image matching graph -> `putative_matches.svg` file in matches that have been produced if you have graphviz, else you can look to the file `PutativeAdjacencyMatrix.svg`?

**Comment by DaytimeAH** [comment]
@pmoulon Thank you for your reply
I can work for the two image group at present by using the "exhaustive pairwise matching"

**Comment by pmoulon** [comment]
Please, Can you close the issue since we solved it?
