### ISSUE TITLE
TriangulateNViewAlgebraic ? porting issue from OpenMVG 1.0 to 1.2 

### ISSUE THREAD

**Issue by qtnext** [openMVG/openMVG#1023]
Hi,

I am porting an application from OpenMVG 1.0 to 1.2 and I have the following issue with TriangulateNViewAlgebraic  :  AssignEvaluator.h:816: erreur : C2338:YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES

It seems now we need to Mat3X to put the collection of 2D Points in each frame ? it was before a Mat2X. What I need to put in the Mat3X because I have only x and y coordinate ?

Best regards

**Comment by qtnext** [comment]
Do I need to do this instead : 
Mat3X xs(3, nviews);
and convert my 2D point with  mypoint.homogeneous()   ?

**Comment by pmoulon** [comment]
Hi @qtnext,
You guess right in your last comment.

I updated the API to gain more flexibility. Now you can use directly the bearing vector or your camera coordinates point as homogeneous coordinates.

So you can use:
- `xcam.homogeneous()` if xcam is already in the camera coordinates,
- `K.inverse() * xima.homogeneous()` if xima is in image coordinate
- `cam(xima)` if you have a camera and you want compute the bearing vector from a point in image coordinate.

**Comment by qtnext** [comment]
Thanks. Before with the 1.0 version, we were using image coordinate to pass to TriangulateNViewAlgebraic and it was working. is it new to do K.inverse() * xima.homogeneous() or it was mandatory also previously ?

**Comment by pmoulon** [comment]
Sorry, I lack some explanation:

It depends how you use the function:
```(
  const Mat3X &x,
  const std::vector< Mat34 > &Ps, ...
)```

- If you use P= [KR|t] you must use image coordinate
- If you use P= [R|t] you must use camera coordinate (since points have been already converted)

**Comment by qtnext** [comment]
thanks :)

**Comment by pmoulon** [comment]
Please close the issue when you have been able to fix your issue.

**Comment by qtnext** [comment]
Yes it's fixed :) just one related questions : what is the difference between TriangulateNViewAlgebraic and TriangulateNView ?

**Comment by pmoulon** [comment]
It minimize a different criteria: (see the formulas [here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/multiview/triangulation_nview.cpp))

**Comment by qtnext** [comment]
To triangulate a point from different cameras, we have changed from initially TriangulateNViewAlgebraic by TriangulateNView and we have now a big error (more than 5 pixels reprojections and before less than 1) . Is it normal ?

**Comment by pmoulon** [comment]
Can you provide a minimal input that I can look at?
