### ISSUE TITLE
Errors when use the Image_describer in macOS10.12 and Qt Creator

### ISSUE THREAD

**Issue by WindWang2** [openMVG/openMVG#1026]
I am using the openMVG as the third party library for my own project, when I test the sample of _multiview_robust_fundamental provided_ by the **_openMVG_** to check my settings . But the code can be build but failed to run. Then I debug line to line, I found that the code failed to detect the sift points. And the sample codes builded by cmake is OK to run. Please help me.
```
...
std::unique_ptr<Image_describer> image_describer
            (new SIFT_Anatomy_Image_describer);
std::map<IndexT, std::unique_ptr<features::Regions> > regions_perImage;
image_describer->Describe(imageL, regions_perImage[0]); // fail at this line
...
```
The error information is as follows
`mvgtest(59289,0x7fffbbf783c0) malloc: *** error for object 0xc048779e40010555: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`
The Qt creator's pro file is as follows
```
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt
TEMPLATE = app
SOURCES += multiview_robust_essential.cpp
QMAKE_MAC_SDK = macosx10.12
INCLUDEPATH += /usr/local/include/openMVG/third_party
INCLUDEPATH += /usr/local/include/eigen3
INCLUDEPATH += /Users/kevin/Desktop/Photogrammetry/MVG/openMVG/src
INCLUDEPATH += /Users/kevin/Desktop/Photogrammetry/MVG/openMVG/src/dependencies
INCLUDEPATH += /Users/kevin/Desktop/Photogrammetry/MVG/openMVG/src/dependencies/cereal/include
INCLUDEPATH += /Users/kevin/Desktop/Photogrammetry/MVG/openMVG/src/openMVG
LIBS += -L/usr/local/lib
LIBS += -L/Users/kevin/Desktop/Photogrammetry/MVG/install/lib
LIBS += -lopenMVG_features \
    -lopenMVG_geometry \
    -lopenMVG_image \
    -lopenMVG_kvld \
    -lopenMVG_lInftyComputerVision \
    -lopenMVG_linearProgramming \
    -lopenMVG_matching \
    -lopenMVG_matching_image_collection \
    -lopenMVG_multiview \
    -lopenMVG_numeric \
    -lopenMVG_sfm \
    -lopenMVG_system \
    -lstlplus
```

**Comment by pmoulon** [comment]
It it fails it's certainly because image_describer is not allocated. Can you check if it is the case or not?

```
std::unique_ptr<Image_describer> image_describer
            (new SIFT_Anatomy_Image_describer);
std::map<IndexT, std::unique_ptr<features::Regions> > regions_perImage;
if (!image_describer) {
  std::cerr << "Cannot allocate the Image_describer" << std::endl;
 return EXIT_FAILURE;
}
image_describer->Describe(imageL, regions_perImage[0]); // fail at this line
```

If we hit the error message we will try to understand what's going on.

**Comment by WindWang2** [comment]
@pmoulon
Thank you for your reply, I follow the instruction in build.md(cmake then make), all is ok, the sample program run normally. But when I use the openMVG as the third_party, put all the include and lib in makefile(or like qt creator as above), the program will failed at the image_describer. So I can sure the problem is the settings of my makefile or qt project. But I have no idea of the problem, since I put all the includes and libs in the settings.

**Comment by pmoulon** [comment]
I'm currently working on making the compilation flag transitive in order to be sure that external client code will follow the same compilation rules.
It must be ready in a branch in the coming days.

Please can you check what I suggested?
```
if (!image_describer) {
  std::cerr << "Cannot allocate the Image_describer" << std::endl;
 return EXIT_FAILURE;
}
```

Did you try to make your new projects using CMake only?

**Comment by WindWang2** [comment]
I check the code you provide, _image_describer_  is initialled and allocated normally. I then debug line by line, I find the error appear in ComputeDogs `bool ComputeDogs(const Octave & octave)` in file _sift_KeypointExtractor.hpp_,  Until the octave_level is 4, the error information above will appear in the follow loop when its' first loop finished(when s=0 finished).     
```
for (int s = 0; s <  m_Dogs.slices.size(); ++s)
    {
      const image::Image<float> &P = octave.slices[s+1];
      const image::Image<float> &M = octave.slices[s];
      m_Dogs.slices[s] = P - M;
    }
``` 
I will learn how to use CMake, if I find something about this, I will report to you. Thank you very much.

**Comment by WindWang2** [comment]
I have solved this problem, it seems like compiler's settings is default to disable.
I add the two line to my project settings, It works.
```
QMAKE_CXXFLAGS += -msse4.1
QMAKE_CXXFLAGS += -mavx2
```
I'm not fimiliar with C++, I don't know the reason behind this. 
Anyway, thank you for your help.

**Comment by rperrot** [comment]
(an idea to understand your issue - though it may not explain everything). 

In openMVG compilation, we test the features your CPU is supporting (SSE, AVX, ...) and compile openMVG with that features. When using openMVG as a third party, you must use the same CPU features (SSE, AVX, ...), by default compilers do not do optimisation and disable extra CPU features, that's why you must add the following lines to your .project. 

BTW @pmoulon made some enhancement to transmit theses flags automatically to your cmake project (and then to your .project).

**Comment by pmoulon** [comment]
@WindWang2 Please, Can you close the issue?

**Comment by WindWang2** [comment]
@pmoulon，I’m not familiar with GitHub, thank you very much for your help.

**Comment by pmoulon** [comment]
You're welcome
