### ISSUE TITLE
Question about new method of removing background

### ISSUE THREAD

**Issue by bkjohnson** [openMVG/openMVG#1027]
I've started trying to implement a new way of removing non-essential "background" points from the cloud, but I wanted to check and see if this is possible before I put a lot more time into actually implementing the algorithm.

Here is the `cloud_and_poses.ply` file with a lot of points that I don't care about:
![image](https://user-images.githubusercontent.com/2008881/28503243-bbf7fd8c-6fc8-11e7-9795-5e699feb4d40.png)

I would like my algorithm to remove most of these points and only keep the ones that I do care about.  I've done a rough job of this manually and this is what it looks like:
![image](https://user-images.githubusercontent.com/2008881/29389638-f7ac869a-82b0-11e7-807a-38e3773a387d.png)

I used Meshlab to export this as a .ply and since `cloud_and_poses.ply` and `sfm_data.bin` are saved in [pretty much the same way](https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/software/SfM/main_IncrementalSfM.cpp#L241) I thought I might be able to rename my modified file as a .bin and carry on with the OpenMVS things but this didn't work.  I'm assuming the file export/conversion from Meshlab messed things up so I can't manually verify if this will work or not which is why I'm asking here.

My images create a rough circle around the subject, and here is a rough idea of the algorithm I have in mind:

1. Using the poses, apply a 3D [RANSAC](https://en.wikipedia.org/wiki/Random_sample_consensus) algorithm to estimate the plane that the poses lie on.
2. Project all of the poses onto this plane & connect each of them to their nearest neighbor to form a 2D polygon
3. For each point in the point cloud:
    + Project the point onto the plane
    + If the projection of the point is outside of the polygon:
        + remove it
    + else:
        + keep it

Ideally the result of this would be a drastically reduced point cloud that only contains points that are "inside" the boundaries of your poses so that you end up with a mesh like this:
![image](https://user-images.githubusercontent.com/2008881/29390577-d091a3aa-82b6-11e7-92f7-2a8acbf723c7.png)

Using the proposed algorithm, would something like this be possible?  If so I'll start working on it and if it ends up being good enough I'll submit a PR.

**Comment by pmoulon** [comment]
It will reduce the SfM point cloud but MVS will still use all the possible pixel and will produce a larger mesh than the thing you expect.

Or if you do ReconstructMesh and then RefineMesh it can work. I mean you must skip the dense point cloud computation.

I like your idea about filtering the point that are inside the polygon defined by the camera path.

Your algorithm to select the point "inside" the polygon defined by the camera should be ok.

Here my notes and comments:

> Using the poses, apply a 3D RANSAC algorithm to estimate the plane that the poses lie on.
- You will have difficulties to guess which threshold you should use. I would recommend to use LMeds or a direct Least Square Formulation. OpenMVG provide you the tool to do that. A kernel computing a hyperplane from 3 points and a cost functor computing the distance of a point to the hyperplane is trivial to implement. -> **I can help on this point by writing a robust plane estimator.**

> Project all of the poses onto this plane & connect each of them to their nearest neighbor to form a 2D polygon
- I already planned to add a 2D convex_hull computation to openMVG/geometry. It will be more stable and efficient than chaining the point and computing all the distance exhaustively. The code should be ready soon. -> **I can help on this point by providing the convex_hull computation code.**

> For each point in the point cloud:
   Project the point onto the plane
     If the projection of the point is outside of the polygon:
        remove it
      else:
         keep it

For this last point you can think in 3D. Let take your plane and your 2d polygon. From the segment of your polygon and your plane equation you can build a series of Hyperplane to define a visual hull that define the region (a 3d cylinder in your case) you want to keep. Once your hyperplane are defined you can use the existing filtering function of OpenMVG.

Here some pseudo code:
```
openMVG::geometry HalfPlaneObject my_visual_hull;
// Use a loop to add all the hyperplanes (defining the boundary of the 3D region you want to keep)
my_visual_hull.planes.push_back(...);

// Filter SfM_Data 3d point according the visual_hull
for (auto & iterLandMark : sfm_data.structure) //can be parallelized
{
  if (my_visual_hull.contains(iterLandMark.second.X))
   // keep the point
  else
   // the point is outside of your visual_hull
}
```

**Comment by pmoulon** [comment]
Another way to constraint the visibility for MVS is to produce mask once your have reduced the count of point projection per the image.

I.E. You can use the convex_hull of the 3d point reprojection by image in order to define mask for the MVS stage.

**Comment by bkjohnson** [comment]
Why must I skip dense point cloud computation?  If I do this algorithm at the end (i.e. after densify, reconstruct, refine & texture) wouldn't it work the same way, only with a lot more data to deal with?  It's too bad MVS will ignore the reduced point cloud, I was hoping to make things run a little faster.

Also thank you for offering to help with the code!  The hyperplane idea is pretty neat - my original idea was to use a cylinder like you mentioned but I couldn't think of a way to make it work which is why I came up with the 2D projection approach.

**Comment by pmoulon** [comment]
1- You can apply this type of filtering on the result of OpenMVS too.

Since the dense point cloud computation does not consider the input geometry (initial 3d points) it will continue to generate the full possible volume.

**Comment by bkjohnson** [comment]
I see.  So is there anything I should do to help with the plane estimator?

**Comment by pmoulon** [comment]
Hi,

1. As you can see here I already pushed some code to perform robust plane estimator there: https://github.com/openMVG/openMVG/issues/1032

- You can start experimenting by feeding it with the camera position and see the results.

Note: As you can see [here](https://travis-ci.org/openMVG/openMVG/builds/267034372), the compilation and unit test run fines expect on Linux clang. I have to check why before merging the feature to the develop branch.

2. 2D Convex_hull computation code.

I will push it soon. WIP.

**Comment by bkjohnson** [comment]
Ok I'll try installing it tomorrow and seeing what it can do.  Thanks!

**Comment by pmoulon** [comment]
I pushed the convex_hull computation in another branch ;-) for testing, you can merge it to your own branch in order to test and use the two API functions.

**Comment by bkjohnson** [comment]
Awesome!  It may be a few days before I get a chance to actually test it.  I'm working on an app and server for [a project](botanize.net) but once the server is ready to process the images and save the model appropriately I can start testing the plane estimation and convex hull computation.

**Comment by pmoulon** [comment]
I gave a second though about the filtering. And if you always have a single height circle like acquisition you can try the following.

```
For every 3d points
 for every camera
   compute the point depth in this camera
    if depth > 0 -> positive_depth++
    else negative_depth++
 end for every camera
 if negative_depth > X // X could be 3 or 4
  delete the point
```

Basically the idea is that if some points are not facing all the camera plane, you reject them. Note: It will work only for circle like shape.

**Comment by bkjohnson** [comment]
What advantage would the nested loop structure have over the other approach?  It seems like it wouldn't be as efficient.

**Comment by pmoulon** [comment]
The depth filtering idea should do the trick in your case since the trajectory is along a circle shape.
It is just simpler to test and code since all the features your need are already there.
