### ISSUE TITLE
Compute and use feature and descriptor data without file operations. 

### ISSUE THREAD

**Issue by kejianwei** [openMVG/openMVG#1030]
Hi, all,
I want to use openMVG to compute and match features for my project, but unlike main_ComputeFeatures.cpp and main_ComputeMatches.cpp, I don't want the program to save and read files(feature and descriptor files) . I looked into  main_ComputeFeatures.cpp and noticed that the computed feature and descriptors data can be access by regions.get().  See the below two lines

line 440 auto regions = image_describer->Describe(imageGray, mask);
line 441 image_describer->Save(regions.get(), sFeat, sDesc);

To my understanding, variable "regions" in line 440 is a type of unique_ptr <openMVG::features::Regions>.  regions.get() is a pointer to Regions(openMVG::features::Regions *). 
When line 440 is executed, the call stack is main.cpp-> SIFT_Image_describer.Describe->SIFT_Image_describer.DescribeSIFT. In DescribeSIFT, feature and descriptors data are stored in Features() and Descriptors(). I tried to use variable "rigions' in main.cc to get Feat and Desc data, "rigions.get()->Features();regions.get()->Descriptors", but compiler prompts that ‘class std::unique_ptr<openMVG::features::Regions>’ has no member named ‘Descriptors’

I wonder how to use regions to get the feat and dest data, or are there other ways to do so?

Thank you.

**Comment by pmoulon** [comment]
Since the image_describer is abstract the computed regions are abstract.

So you can do this:
```
// Compute features and descriptors and export them to files
auto regions = image_describer->Describe(imageGray, mask);
image_describer->Save(regions.get(), sFeat, sDesc);

regions->Descriptors().size(); // NOK since regions is abstract

const SIFT_Regions* casted_regions = dynamic_cast<SIFT_Regions*>(regions.get());
std::cout << casted_regions->Descriptors().size() << std::endl; // OK
// So here you must know which regions type you are using.
```

Or use directly the Image_describer by this implementation in order to get directly the casted  regions by bypassing the virtual Describe function.
```
std::unique_ptr<SIFT_Image_describer> image_describer;
image_describer.reset(new SIFT_Image_describer
        (SIFT_Image_describer::Params(), !bUpRight));

auto regions = image_describer->DescribeSIFT(imageGray, mask); //You bypass the virtual 
 generic Describe method
image_describer->Save(regions.get(), sFeat, sDesc);

regions->Descriptors().size(); // Ok regions are not abstract
regions->Features().size();
```

**Comment by pmoulon** [comment]
@kejianwei  Any feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity.
