### ISSUE TITLE
Creating sparse depth maps from two views.

### ISSUE THREAD

**Issue by smmmmi** [openMVG/openMVG#1033]
Hi,
Can anyone suggest how I can use the pipeline (or even the .ply outputs I currently have) to make depth maps from the camera positions?
The output will be an image the same size as input, but on the feature-point location it will have the depth as the value.

**Comment by pmoulon** [comment]
Hi, If I understand it right you want the depth of the point in each view?

You can easily do that by calling `pose.Depth(X);`
See https://github.com/openMVG/openMVG/blob/master/src/openMVG/geometry/pose3.hpp#L132

So the best way to do it, consist in writing a new binary that will export float image with the computed depth for each 3d points.
