### ISSUE TITLE
How to build a real time pattern based 3d reconstruction system?

### ISSUE THREAD

**Issue by robin32205** [openMVG/openMVG#1041]
Hi,
If I want to enhance the efficiency of SfM and make it faster, could a pattern based (or simply based on the list of known camera poses and its normal direction) available here depend on OpenMVG?

BR

**Comment by rperrot** [comment]
What do you mean by pattern ? Something placed in the "real" scene ?

**Comment by pmoulon** [comment]
Hi, this ticket is related to this question: https://github.com/openMVG/openMVG/issues/870#issuecomment-325255145

The question was about doing something in the spirit of [Qlone](https://www.qlone.pro/).

The idea is to simplify the pose computation process by using a pattern based approach (QR code like (Aruco?)).

PS: if you already know your camera poses, OpenMVG can triangulate your match file and perform a BA. (see main_ComputeStructureFromKnownPoses)

**Comment by robin32205** [comment]
@rperrot Yes in real scene! 
@pmoulon yeah, a QR code like pattern is preferred. But just like Qlone, the scanned target could not cover the pattern from every camera poses. so maybe the available patterns have to be around the target.
BTW, how can I use the main_ComputeStructureFromKnownPoses for known poses? and where can I put the known poses data in? And If I want to do so, do I still have to process the main_IncrementalSfM before that? 

thanks a lot!

**Comment by pmoulon** [comment]
`main_ComputeStructureFromKnownPoses` is using the poses, intrinsics and views defined in a sfm_data scene.
So you can init your own sfm_data.json scene using the OpenMVG API save it and then use `main_ComputeStructureFromKnownPoses`. You can then send to this binary your features and matches computed by `ComputeFeatures` and `ComputeMatches`.

**Comment by robin32205** [comment]
Here is my procedure:
1. Use "-P" in main_SfMInit_ImageListing to insert "center" data (where I put the known camera positions) in sfm_data.json.
2. Compute features.
3. List Matching Pairs & Compute matches.
4. Structure from Known Poses with "Direct_triangulation"
and then I get info:
```
Loaded a sfm_data scene with:
 #views: 60
 #poses: 0
 #intrinsics: 2
 #tracks: 0
```
It seems that I get some wrong poses here, how can I fix that within my procedure?

**Comment by pmoulon** [comment]
The `-P` option only associate a approximate camera position prior.
If you want to use Structure from Known Poses with "Direct_triangulation" you must set the complete camera poses (known rotation and translation) by updating the extrinsic/poses field in the SfM_data.

**Comment by robin32205** [comment]
oh I see, I will try that first! thank you.

**Comment by robin32205** [comment]
Hi, if I want to input rotation of poses, should I open the "Pose rotation prior" in initial image listing in the sfm_view_priors.hpp, and compute the pose_rotation_ for it? Is that the only way for input rotation data?

**Comment by pmoulon** [comment]
You must update the camera poses:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data.hpp#L37

**Comment by robin32205** [comment]
thank you very much for your help and sorry for reply late, I got your point. 
btw, how do you think about the 3D scanning algorithm in Sony's new Xperia?
Could OpenMVG achieve the level that kind of algorithm?
(sorry this is not the problem about the issue.... XP)

**Comment by pmoulon** [comment]
Sony's new Xperia capture is using some data that OpenMVG does not have (IMU) and the process is using an ordered image sequence.

OpenMVG can use any un-ordered image sequence.

If you use a pattern and set from this pattern the camera position you can then triangulate an existing match file.
