### ISSUE TITLE
[Question]compile error: expected constructor, destructor, or type conversion before ‘namespace’

### ISSUE THREAD

**Issue by jakexie** [openMVG/openMVG#1042]
I update openmvg to the latest version, then I get the error:
```
In file included from /home/super/program/openMVG/src/openMVG/features/regions_factory_io.hpp:17:0,
                 from /home/super/program/openMVG/src/openMVG/features/regions.cpp:18:
/home/super/program/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:100:3: error: expected constructor, destructor, or type conversion before ‘namespace’
   namespace cereal {                                         \
   ^
/home/super/program/openMVG/src/openMVG/features/regions_factory_io.hpp:22:1: note: in expansion of macro ‘CEREAL_REGISTER_TYPE_WITH_NAME’
 CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Float_Regions, "AKAZE_Float_Regions");
 ^
make[2]: *** [openMVG/features/CMakeFiles/openMVG_features.dir/regions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [openMVG/features/CMakeFiles/openMVG_features.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

**Comment by pmoulon** [comment]
Can you give more detail about your configuration?
- OS, Compiler and version.

Build CI is ok with Linux GCC/clang and OSX Clang and Windows VisualStudio 2015.

Are you sure that C++11 feature are well activated for your compiler?

**Comment by jakexie** [comment]
@pmoulon Thanks!
Configuration:
     OS: linux mint 17.3 -> based on ubuntu 14.04
     Gcc version :4.9.2
The cmake result :
```
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Eigen 3.3.1 found (include: /home/super/program/openMVG/src/third_party/eigen)
-- Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.3.1) does not exactly match the version of Eigen Ceres was compiled with (3.2.0). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
-- Flann 1.8.4 found (include: /home/super/program/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.9.3 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.15.11 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Clp/src)
-- Osi 0.106.10 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: /home/super/program/openMVG/src/third_party/lemon/lemon)
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
CMake Warning (dev) at third_party/ceres-solver/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    Ceres_VERSION
    Ceres_VERSION_MAJOR
    Ceres_VERSION_MINOR
    Ceres_VERSION_PATCH
    Ceres_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.


   ===============================================================
   Ceres-solver configuration.
   ===============================================================
-- Detected Ceres version: 1.12.0 from /home/super/program/openMVG/src/third_party/ceres-solver/include/ceres/version.h
-- Eigen 3.3.1 found (include: /home/super/program/openMVG/src/third_party/eigen)
-- Found Eigen version 3.3.1: /home/super/program/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found BLAS library: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- Enabling CERES_NO_SUITESPARSE in Ceres config.h
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================
abort: repository /home/owner/program/openMVG/src not found!
abort: repository /homeowner/program/openMVG/src not found!
-- 
-- Configured Eigen 3.3.1
-- 
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  software/CMakeLists.txt:14 (find_package)


CMake Warning at software/CMakeLists.txt:14 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Svg" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake"

  



** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation


** OpenMVG version: 1.2.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- EIGEN: 3.3.1 (internal)
-- CERES: 1.11.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.3 (external)
-- LIBPNG: 1.2.50 (external)
-- LIBJPEG (external)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/owner/program/openMVG_BUILD
```

**Comment by pmoulon** [comment]
On my computer I have Linux Mint too with gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1).

Can you tell me which cmake version do you have?

The first difference I see between your cmake log and the one of the CI is this one:
```
-- Failed to find Ceres - Found Eigen dependency, but the version of Eigen found (3.3.1) does not exactly match the version of Eigen Ceres was compiled with (3.2.0). This can cause subtle bugs by triggering violations of the One Definition Rule. See the Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule for more details
```
- you can check the build CI log and the cmake report there: https://travis-ci.org/openMVG/openMVG/jobs/252281578

Do you have any ceres or Eigen library already installed on your computer?

**Comment by jakexie** [comment]
@pmoulon Cmake version on my computer is 3.5.1.
Ceres version is 1.12.0 based on 3.2.8/3.2.0.
I set the path of ceres and eigen to "/usr/local/cere_eigen3.2.8" and "/usr/local/eigen-3.2.8/include/eigen3" and the error is still there. 
`In file included from /home/super/program/openMVG/src/openMVG/features/regions_factory_io.hpp:17:0,
                 from /home/super/program/openMVG/src/openMVG/features/regions.cpp:18:
/home/super/program/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:100:3: error: expected constructor, destructor, or type conversion before ‘namespace’
   namespace cereal {                                         \
   ^
/home/super/program/openMVG/src/openMVG/features/regions_factory_io.hpp:22:1: note: in expansion of macro ‘CEREAL_REGISTER_TYPE_WITH_NAME’
 CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Float_Regions, "AKAZE_Float_Regions");
 ^
In file included from /usr/local/eigen-3.2.8/include/eigen3/Eigen/Core:309:0,
                 from /usr/local/eigen-3.2.8/include/eigen3/Eigen/Dense:1,
                 from /home/super/program/openMVG/src/openMVG/numeric/eigen_alias_definition.hpp:17,`

What should i do if i want to set the internal Ceres and eigen of openMVG as default in cmake?
the cmake result :
```
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Eigen 3.2.8 found (include: /usr/local/eigen-3.2.8/include/eigen3)
-- Found required Ceres dependency: Eigen version 3.2.8 in /usr/local/eigen-3.2.8/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.12.0 installed in: /usr/local/cere_eigen3.2.8
-- Flann 1.8.4 found (include: /home/super/program/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.9.3 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.15.11 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Clp/src)
-- Osi 0.106.10 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: /home/super/program/openMVG/src/third_party/lemon/lemon)
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
abort: repository /home/owner/program/openMVG/src not found!
abort: repository /home/owner/program/openMVG/src not found!
-- 
-- Configured Eigen 3.3.1
-- 
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  software/CMakeLists.txt:14 (find_package)


CMake Warning at software/CMakeLists.txt:14 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Svg" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake"

  



** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation


** OpenMVG version: 1.2.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- EIGEN: 3.2.8 (internal)
-- CERES: 1.12.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.3 (external)
-- LIBPNG: 1.2.50 (external)
-- LIBJPEG (external)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/owner/program/openMVG_BUILD
```

**Comment by jakexie** [comment]
@pmoulon Oh! I add comment on this line(src/CMakeLists:255), but the error is still there. ~~~~~cry~~~~~
```
#find_package(Ceres QUIET HINTS ${CERES_DIR_HINTS})
if (NOT Ceres_FOUND)
  set(OpenMVG_USE_INTERNAL_CERES ON)
```
the cmake result:
`-- target changed from "auto" to "haswell"
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Eigen 3.3.1 found (include: /home/super/program/openMVG/src/third_party/eigen)
-- Flann 1.8.4 found (include: /home/super/program/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.9.3 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.15.11 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Clp/src)
-- Osi 0.106.10 found (include: /home/super/program/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: /home/super/program/openMVG/src/third_party/lemon/lemon)
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
-- Detected Ceres version: 1.12.0 from /home/super/program/openMVG/src/third_party/ceres-solver/include/ceres/version.h
-- Eigen 3.3.1 found (include: /home/super/program/openMVG/src/third_party/eigen)
-- Found Eigen version 3.3.1: /home/super/program/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found BLAS library: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- Enabling CERES_NO_SUITESPARSE in Ceres config.h
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================
abort: repository /home/super/program/openMVG/src not found!
abort: repository /home/super/program/openMVG/src not found!
-- 
-- Configured Eigen 3.3.1
-- 
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  software/CMakeLists.txt:14 (find_package)


CMake Warning at software/CMakeLists.txt:14 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Svg" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake"

  



** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation


** OpenMVG version: 1.2.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- EIGEN: 3.3.1 (internal)
-- CERES: 1.11.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.3 (external)
-- LIBPNG: 1.2.50 (external)
-- LIBJPEG (external)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/super/program/openMVG_BUILD`

**Comment by rperrot** [comment]
Did you make a full clean of the build directory after your change (ie: a violent rm -rf build_dir) then re-re-run the cmake (some variables may have been cached and change is not always effective) ?

**Comment by jakexie** [comment]
@pmoulon @rperrot Thanks!!  it's ok! I clone a new repository from github and it works perfectly good. (I still don't know why the old one not working).

**Comment by rperrot** [comment]
Maybe pull was not successful (I think dependencies were not updated according to the branch of the repository).
