### ISSUE TITLE
[graph] Rewrite a faster graph::ListTriplet function

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1043]
- Change the algorithm to have a lower complexity and use less memory.
- Update the algorithm to do not depends any longer on the lemon graph library.

Rather than iterating first on Nodes and then edges belonging to a node to find triplets.
The new algorithm will iterate along the edges and find triplet using find intersection of the adjacency list of the edge's vertices.
- Using std::set to handle the adjacency list and using std::set_intersection to find triplet make the search really efficient.
- Reducing the adjacency list once all triplets belonging to an edge have been found makes the algorithm even faster as long we explore the graph edges.

--
- The new algorithm is more compact and easier to read than the previous one :smile_cat: 
- Using `Pairs` and c++11 initializer list make the triplet_finder_test far more readable.

--
On some graphs the new algorithm is up to two times faster.

**Comment by rperrot** [comment]
Does this mean that lemon is no longer a dependency (of whole openMVG process ?)

**Comment by pmoulon** [comment]
No, only this step have been made lemon less.
Actually, MST, CC and Biedge graph algorithm still rely on Lemon.
I should find some time to integrate your graph class.

**Comment by rperrot** [comment]
Ok. There is still a need for a graph library. (And don't worry for the integration, we have time).
