### ISSUE TITLE
Question : Incremental SfM for multiple spherical panoramas

### ISSUE THREAD

**Issue by prozhuchen** [openMVG/openMVG#1046]
Hi @pmoulon, 

In this [issue](https://github.com/openMVG/openMVG/issues/832), you mentioned that you have added a spherical camera model and given a sample that estimates the relative pose for two spherical panoramas. I am wondering whether the code of incremental SfM for multiple spherical panoramas is available. If there are some samples, could you please give me the URL? 

Thanks

**Comment by Joeppie** [comment]
Hello @prozhuchen I believe you may be referring to  the sample 
[multiview_robust_essential_spherical/robust_essential_spherical.cpp](
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_essential_spherical/robust_essential_spherical.cpp)

not 100% sure though.

**Comment by prozhuchen** [comment]
Hi @Joeppie ,

thanks for your answer . I saw that before , but it compute the relative pose just between two spherical images. So I am wondering  how to compute for multiple spherical panoramas.

**Comment by pmoulon** [comment]
@prozhuchen Extending the existing Incremental SfM pipeline in order to support the Spherical camera model should be easy. Any help on this is welcomed.

**Comment by prozhuchen** [comment]
@pmoulon OK, I will try it. Thanks for you

**Comment by pmoulon** [comment]
@prozhuchen you can sync with @yuyou to work together on the feature!
BTW, can we close the issue.

**Comment by pmoulon** [comment]
PS: you can refer to this paper for some bibliography. [Structure from Motion using full spherical panoramic cameras](http://alain.pagani.free.fr/papers/Pagani2011_OMNIVIS.pdf)

**Comment by prozhuchen** [comment]
@Joeppie

**Comment by pmoulon** [comment]
Note: The support of spherical image for Incremental is coming soon https://github.com/openMVG/openMVG/issues/1133 🎉
