### ISSUE TITLE
convex_hull function ComputeConvexHull crash 

### ISSUE THREAD

**Issue by wangniancai** [openMVG/openMVG#1048]
try to run the convex_hull_test, found the function ComputeConvexHull crash everytime

**Comment by pmoulon** [comment]
Please, Can you share the unit test report and detail about your configuration?

- Linux GCC, Linux Clang and Windows VS2015 (32/64bits) CI test are working.

**Comment by wangniancai** [comment]
sorry， compile with windows VS2015  （64bits）Release_AVX ,

**Comment by pmoulon** [comment]
Can you run the binary and log here the result.
It run fines for me.
```
>openMVG_test_convex_hull.exe


 Launching Test : class ConvexHull_Random_Point_ConvexHull_Test



         TEST -> [OK]



 Launching Test : class ConvexHull_OnePoint_Test



         TEST -> [OK]



 Launching Test : class ConvexHull_Line_Test



         TEST -> [OK]



 Launching Test : class ConvexHull_Empty_Test



         TEST -> [OK]


---------
[TEST SESSION RESULTS]
---------
There were no test failures
```

**Comment by pmoulon** [comment]
@wangniancai Any feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity.
BTW, the code will be tested by the continuous integration in debug and release mode for VS 2015 (x86 and x64)
Merged by https://github.com/openMVG/openMVG/commit/1ed5734f70a1af5e66bfbdd62790ad670a61c831
