### ISSUE TITLE
[robust_estimation] Add a GMS Filter (Grid-based Motion Statistics filter) [CVPR2017]

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1049]
Add an implementation of [1]

- Implementation is based on the CVPR2017 paper [code](https://github.com/JiawangBian/GMS-Feature-Matcher)

Changes are:
- rewrite the matcher in order to use some c++11 features (more compact implementation)
- Fix error encountered when the points are out of the grid bounds
- Use more explicit variable names
- Add a Doxygen documentation

- Add a unit test and a demo sample

```
[1]  @inproceedings{bian2017gms,
  title={GMS: Grid-based Motion Statistics for Fast, Ultra-robust Feature Correspondence},
  author={JiaWang Bian and Wen-Yan Lin and Yasuyuki Matsushita and Sai-Kit Yeung and Tan Dat Nguyen and Ming-Ming Cheng},
  booktitle={IEEE Conference on Computer Vision and Pattern Recognition},
  year={2017}
}
```

Note: Since the motion are computed by tiny grid the more features the images have, the better the results will be (Left Distance ratio matches, Right Distance ratio matches + GMS filter).
SIFT_ULTRA:
```
openMVG_sample_image_matching_gmsfilter -t SIFT
1418 #Features on image A
3258 #Features on image B
366 #matches with Distance Ratio filter
228 #matches kept by the GMS Filter
```
![g8706](https://user-images.githubusercontent.com/3235050/30245992-497e6ff8-95ec-11e7-9045-d3e4481515ef.png)

AKAZE_ULTRA:
```
3422 #Features on image A
5454 #Features on image B
572 #matches with Distance Ratio filter
477 #matches kept by the GMS Filter
```
![g12801](https://user-images.githubusercontent.com/3235050/30245983-0b6ebc68-95ec-11e7-9d4d-842310246e29.png)

**Comment by s-wtnb** [comment]
Using a filter after matching seems like the same (filtering) process twice.
So, is it possible to use this GMS filter instead of the distance ratio?
Or is it more efficient to use a filter after eliminating by distance ratio?

**Comment by pmoulon** [comment]
> Using a filter after matching seems like the same (filtering) process twice.
No GMS is a filter, it does not compute corresponding points. It filters existing corresponding point set.

>So, is it possible to use this GMS filter instead of the distance ratio?
Not yet, but soon it will be possible. Please let us the time to implement it.

>Or is it more efficient to use a filter after eliminating by distance ratio?
I invite you to read: "Image Matching Benchmark" https://arxiv.org/pdf/1709.03917.pdf in order to make your own conclusion.

**Comment by pmoulon** [comment]
@s-wtnb The sample is now update with an option to choose between 1-1 matching or matching with distance ratio before the GMS filter.

```
$ ./openMVG_sample_image_matching_gmsfilter -t AKAZE_MLDB -d
5223 #matches Found
3343 #Features on image A
5223 #Features on image B
929 #matches kept by the GMS Filter
```
![03_gmsmatches_akaze_mldb_929](https://user-images.githubusercontent.com/3235050/30788703-efdce9ec-a19f-11e7-952a-84b79e0db109.png)

```
$ ./openMVG_sample_image_matching_gmsfilter -t AKAZE_MLDB -d
612 #matches Found
3343 #Features on image A
5223 #Features on image B
499 #matches kept by the GMS Filter
```
![03_gmsmatches_akaze_mldb_499](https://user-images.githubusercontent.com/3235050/30788702-efd4fef8-a19f-11e7-8433-dadc795c4e3f.png)

**Comment by s-wtnb** [comment]
Thank you for introducing "Image Matching Benchmark" and adding 1-1 matching.
In this case of AKAZE, using distance ratio reduces the number of matches but seems to be widely matched.

I will try out other features such as ORB in the paper of GMS filter.

**Comment by pmoulon** [comment]
For sure any detector-descriptor couple can be used. As you will notice in the paper "Image Matching Benchmark".
I used here the existing internal Detector/Descriptor of OpenMVG. Since the idea is that GMS need "dense" feature extraction in order to compute motion statistics using the preset filter on the Image_describer provide decent results.

Using ORB will allow you to extract even more features. Notice that in the GMS paper they resize the image in order to ensure that for the given number of asked feature they will have a sufficient image feature coverage.

**Comment by happyfrank** [comment]
I use GMS as filter to match my spherical image feature. the result was not better than sift ratio. It always got error like this. I think it's not stable than ratio.
![20171219144853_pano jpg_20171219145558_pano](https://user-images.githubusercontent.com/12987532/37574314-f14fd2ae-2b5a-11e8-8be7-acb448b73669.jpg)

**Comment by willard-yuan** [comment]
@happyfrank I also found the performance is not satisfied when the background clutters.

**Comment by pmoulon** [comment]
@happyfrank Which method did you use to match the feature before running GMS?

GMS is looking for coherent motion within a given neighborhood so in very noisy or dense feature situation he can still find invalid results.
Also the threshold factor https://github.com/openMVG/openMVG/commit/e3a0bde5e9c676d1cb663a38f7e74c771324d69a#diff-3685f080be5357eeda75c894224e8142R62 in the original paper is too permissive.You can try different value and see the one that fit your need.

**Comment by happyfrank** [comment]
@pmoulon I use the orb feature and opencv BFMatcher matcher(NORM_HAMMING)
I change the threshold factor. also change the feature to use SIFT. the result was not better than SIFT and ratio.  
I think it could be better using GMS after SIFT+ratio(0.8 or higher).
