### ISSUE TITLE
[image] Read_JPG_ImageHeader has memory leak.

### ISSUE THREAD

**Issue by jby1993** [openMVG/openMVG#1052]
when I use openMVG::image::ReadImageHeader for .jpg files, I found there is memory leaking.
Then I add jpeg_finish_decompress(&cinfo); in Read_JPG_ImageHeader function, the leaking disappeared. I don't know what I did is right or not.

**Comment by rperrot** [comment]
where did you add this line ?

**Comment by pmoulon** [comment]
@jby1993 Thank you for your feedback. Appreciated.

I think we need to call those functions:
```
jpeg_finish_compress(&cinfo);
jpeg_destroy_compress(&cinfo);
```
Can you try it and provide feedback to tell if the leak is not longer here?

@rperrot It must be added here:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io.cpp#L743

**Comment by pmoulon** [comment]
Seems like `jpeg_finish_decompress(&cinfo);` must not be called since we didn't read any pixel.
Only `jpeg_destroy_decompress(&cinfo);` have to be called.

**Comment by pmoulon** [comment]
@jby1993 Can you tried the fix done in the branch develop_image_io_read_jpg_header_memory_leak and tell me if the memory leak is gone?

**Comment by jby1993** [comment]
@pmoulon I use the fix, and don't find memory leak again. Thanks!

**Comment by pmoulon** [comment]
Thanks.
I will merge it to develop to be integrated in the next release.

**Comment by pmoulon** [comment]
Merged by https://github.com/openMVG/openMVG/commit/4a85ee324b0f2c603e47e6c611639d524e8e1315
