### ISSUE TITLE
Error installing with install prefix

### ISSUE THREAD

**Issue by LinusVanElswijk** [openMVG/openMVG#1054]
When I try to install openMVG with an install prefix, 
`DCMAKE_INSTALL_PREFIX:STRING="/home/user/openMVG_Build/openMVG_install`,
I get the following error while running cmake install:

```
...
-- Installing: /usr/local/include/openMVG/third_party/eigen/Eigen/Cholesky
CMake Error at third_party/eigen/Eigen/cmake_install.cmake:44 (file):
  file INSTALL cannot copy file
  "/home/user/openMVG/src/third_party/eigen/Eigen/Cholesky" to
  "/usr/local/include/openMVG/third_party/eigen/Eigen/Cholesky".
Call Stack (most recent call first):
  third_party/eigen/cmake_install.cmake:37 (include)
  third_party/cmake_install.cmake:65 (include)
  cmake_install.cmake:85 (include)
 
Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

Should CMake even be trying to copy files into `/usr/local/` if I set the install prefix to `/home/user/openMVG_Build/openMVG_install`?

**Comment by pmoulon** [comment]
I don't have this error on my side. 
Can you try again with a clean cmake cache?
and be sure to close the `"`
-> `-DCMAKE_INSTALL_PREFIX:STRING="/home/user/openMVG_Build/openMVG_install"`

**Comment by Joeppie** [comment]
I believe, as  Pierre suggests, you are failing to correctly invoke CMake.

I've personally developed and ran the following script in linux mint to donwload and install a fresh OpenMVG: https://github.com/Joeppie/prepdev/blob/master/5_install_openmvg.sh If you run it with 
You can check how I put the CMAKE arguments into a shell script there, or even use it as is.

> Should CMake even be trying to copy files into /usr/local/ if I set the install prefix to /home/user/openMVG_Build/openMVG_install?

I just verified that my script installs to `/home/user/openMVG_Build/openMVG_install', not the /usr/local.
So probably not, provided you *correctly* passed the cmake argument.

**Comment by LinusVanElswijk** [comment]
I found the cause of the error. Apparently a previous install of openMVG was not cleaned up correctly and there were some leftover files in the `/usr/local/include/openMVG/third_party/eigen/` directory.

Removing the `/usr/local/include/openMVG/` directory solved the issue.

**Comment by pmoulon** [comment]
Can you close the issue?
