### ISSUE TITLE
[matching] Create a RegionMatcherFactory

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1056]
Replace the class `Matcher_Regions_Database` by a factory:
```
std::unique_ptr<RegionsMatcher> RegionMatcherFactory
(
  matching::EMatcherType matcher_type,
  const features::Regions & regions
);
```

Since the actual Match function is doing distance ratio filtering. I propose here to rename `Match(...)` to `MatchDistanceRatio(...)`

**Comment by rhiestan** [comment]
If I may, I'd like to suggest to allow the user of openMVG library to add their own matching algorithm. Currently I am trying out new matching algorithms, and for this I either have to change openMVG source code (which I don't want, since I don't want to add dependencies to other libraries to openMVG) or to copy-paste much of the openMVG code into my own.

**Comment by pmoulon** [comment]
Actually user can provide their own features, their owns matches thanks to the Feature and Matches provider and even provide pairs of image to match.

I'm totally ok to try to make the API more flexible to authorize more. Can you elaborate in order to find a better design that we can collaborate on?

On the other side, implementing your own matching should be really trivial. Since once the features are loaded, you can run your own loop or algorithm to match the descriptor and then log the matches as PairWiseMatches.

**Comment by rhiestan** [comment]
If I want to create my own matcher, I basically have to copy and paste the code in Matcher_Regions::Match (loop over all camera combinations) and openMVG::matching::RegionsMatcherT::Match (filter, remove duplicates). That's not much, this is true, but it would be easy to allow an external matcher implementation to be used.
I will make a PR in the next few days to show you what I mean.

**Comment by pmoulon** [comment]
- [ ] Extend the existing interface to perform:
- Match: `1-1` matching
- MatchDistanceRatio: `1-2NN + distance ratio`

**Comment by pmoulon** [comment]
> I will make a PR in the next few days to show you what I mean.

Any update on this @rhiestan ?

**Comment by rhiestan** [comment]
I'm sorry for the confusion. I found out how to achieve it without code change to OpenMVG since RegionsMatcherT is a template. At first I didn't realize this and thought I needed to copy a lot of code from OpenMVG. But then I saw it, and edited my answer.
