### ISSUE TITLE
Setting max_num_iterations in Bundle Adjustment

### ISSUE THREAD

**Issue by Joeppie** [openMVG/openMVG#1057]
Hello, my colleague and I have found that we may have the need to increase the amount of allowed iterations in Ceres.

I'm not sure how useful it is to add an issue for this, but it may be of use to others who run SFM+BA as well.

For this purpose, in my fork I have added a simple integer field `max_num_iterations` to the `openMVG::sfm::Optimize_Options`, which defaults to the currently hardcoded value of 500. This value is copied over into `max_num_ierations` of the `ceres::Solver::Options`

The change is inside here:
https://github.com/Joeppie/openMVG/commit/54c66e12ae1d52a5eef09d71cf07b01d0a82739b

**Comment by rjanvier** [comment]
closed by 7f322652e3ccf2d25e40a955b5adb610f86fa243
