### ISSUE TITLE
openMVG_main_SfM_Localization reports Invalid regions

### ISSUE THREAD

**Issue by is03wlei** [openMVG/openMVG#1058]
-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: xxx/yyy.jpg
*
Invalid regions.

I copied reconstruction_sequential and matches from others. 
I don't have original images. Does it matter?

**Comment by pmoulon** [comment]
Having the original image does not matters.
Please check that you have used the right path for the `--match_dir` option.

**Comment by is03wlei** [comment]
Thanks. Some files from matches are missing.

**Comment by pmoulon** [comment]
Can we close the issue?
Since some matches file are missing it's certainly because the copy have been done partially.
