### ISSUE TITLE
How to do clustering using openMVG? I have 8500(24MP) aerial images.

### ISSUE THREAD

**Issue by ManishSahu53** [openMVG/openMVG#1059]
I have 8500 (24MP) aerial images. I tried to do reconstruction earlier using only 250 images but it failed saying out of memory. Also the point cloud it generated was too big to open for my PC. I have noticed that recently openMVG has included an option of clustering. So I searched  but couldn't find much on how to apply this clustering. Can anyone help me with the process?

**Comment by pmoulon** [comment]
1. Does your images have GPS information?
- if yes you can reduce the number of image to match by using a selection of the image pair that depends of the distance: https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#to-speed-up-the-pairwise-feature-matching-step

2. You can perform first a reconstruction that use subsampled images (1/4 of the resolution) and then use the found sfm_data camera poses with your high resolution images matches to triangulate them and perform a BA at the full image resolution.

3. For the matching step you can limit the number of image descriptor you keep in memory by using the [-c option](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L93). It makes the process slower but allow to manage to handle larger dataset.

>  I tried to do reconstruction earlier using only 250 images but it failed saying out of memory. Also the point cloud it generated was too big to open for my PC.

- How it can failed but still produce a point cloud. If you have a results its not a failure. Can you elaborate what you understand by failure.

PS: we have also a clustering method that allow to split a SFM scene (camera poses + landmarks) in chunks for MVS processing -> main_ComputeClusters.

**Comment by ManishSahu53** [comment]
- I could create point cloud but it failed in 3D Meshing step. The meshing step gave me error regarding out of memory.

1. Yes all of them have GPS information
2. Ok. I will try to do the second recommendation by limiting image descriptor in the memory. Will this store this data in harddisk if it reaches the maximum limit?
3. subsampling of images to eg 1/4 resolution will do uptill bundle adjustment. For point cloud and mesh, I would still have to face this memory problem. Isn't it?

Yes I saw this Compute Clusters update. This is really expressive tool to scale the reconstruction. But I am confused how to implement this in my project. Should I use it before sparse cloud generation step or before point cloud step? I couldnt find any examples also. I am planning to use MVE or openMVS for MVS process. Could you recommend me how much RAM will I be needed? Is there any way to calculate this mathematically?
Thanks

**Comment by pmoulon** [comment]
> I could create point cloud but it failed in 3D Meshing step.

- Do you mean that you already processed the Scene with one SfM pipeline?

If the answer is yes you can call `main_ComputeClusters` on your sfm_data.bin file to cluster the scene in many chunk that you will be able to process independently.

3. Yes you will still have the problem for MVS if you want to process it at full scale. I did not catch that you already processed the SfM in your first post.

> Can i use clusters in the aerotriagulation step?

- No. Not yet, but you can cut your image dataset in many chunk according their GPS info.

> how much RAM will I be needed?

- If you want to process the scene as a whole you will need quite a lot. If you process by chunk it should be ok.

**Comment by ManishSahu53** [comment]
1. I have processed only a part of my dataset(~270 images) out of 8500. That upto only point cloud. Meshing part gave me an error of out of memory. 

2. Can you suggest me how to do aerotriangualtion step of 85000 images(24MP each, each geotagged). 

3. Dividing the images and then processing has a problem of lossing integrity. At edeges there will be sudden difference in point cloud and in mesh. I have tried this dividing approach. Can you suggest me how to do this without dividing images?

4. Also is it only bottle neck of RAM? or bundle adjustment process also. Because I have read that bundle adjustment process poorly and takes a lot of time when image dataset is huge?

5. Can i insert distortion parameters manually in openMVG? I have calibrated my camera manually using checkboard.

**Comment by ManishSahu53** [comment]
I have figured it out.
I used main_computeClusters with my robust.bin sfm data and then processed with MVE. I could do it with the ~270 images. Now I think using this way I can do it for 8500 images too. I will post my project updates  here once I finish 8500 images.
Thanks for help and creating this awesome software.

**Comment by pmoulon** [comment]
Thank you for your feedback @ManishSahu53 .
Really looking forward your coming results with for the whole scene. Seems like you have a very large project 😄

**Comment by ManishSahu53** [comment]
[update] I am processing 2200 images out of 8500. Got error as "killed" in global sfm. It seems it is out of memory. Also incremental sfm is also not working.

**Comment by pmoulon** [comment]
At which stage of the pipeline it died (rotation averaging, translation averaging).
We can still process your dataset on downsampled images and then perform the BA on the full size images from the computed camera poses.

**Comment by ManishSahu53** [comment]
I have made this python file for running openMVG+MVS. 
I got error in this line : pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_GlobalSfM"),  "-i", matches_dir+"/sfm_data.json", "-m", matches_dir, "-o", reconstruction_dir,"-P"] )
I could not sfm_data.bin file and this process ended as "process killed"

[SFM.txt](https://github.com/openMVG/openMVG/files/1378467/SFM.txt)

**Comment by pmoulon** [comment]
The openMVG_main_GlobalSfM log would be interesting to see.
Please rerun and export the console output to a file.
`Your script &> my_log_file.txt`

**Comment by ManishSahu53** [comment]
OK. I will rerun that project and get back the log. In the meanwhile I tried to run same command in 56 GB ram (earlier 16GB) server. Looks like I didnt recieve any error of killed this time. Below is the sfm_data.bin result screenshot. However I found out two things
1. SFM was done till there was continuity in images. In image there was a gap so sfm is not computed after the disjoint.
2. SFM robust taking too much time. I left the system for about 10 hours still the sfm robust is running at the server. CPU usage was 100% (8cores) throughout the running time. So I stopped the robust sfm process.

![image](https://user-images.githubusercontent.com/27155127/31534255-cb18967e-b013-11e7-86de-7f8ceb4191ca.png)

**Comment by ManishSahu53** [comment]
[Update]
I am processing 1775 images (24MP each). 

![image](https://user-images.githubusercontent.com/27155127/36164812-84ab39ce-1113-11e8-90af-127bda08654c.png)

Results doesnt look good. 
My Pipeline - 
1. I have entered focal length data already. 
2. SIFT features kept at High. 
3. Performed Global SFM.

Possible solutions-
1. Splitting images into number of small parts. 
2. Performing Incremental SFM(though I doubt it will work with these number of images)

Here is SFM report. 
[SfMReconstruction_Report.html.zip](https://github.com/openMVG/openMVG/files/1720967/SfMReconstruction_Report.html.zip)

**Comment by ManishSahu53** [comment]
Solution 1 (Dividing into number of small parts)
1. I divided whole images into 9 parts. ~200 images each.
2. SFM results seems good enough.
3. Sfm Report attached. 
[SFM Report.zip](https://github.com/openMVG/openMVG/files/1722917/SFM.Report.zip)

![image](https://user-images.githubusercontent.com/27155127/36190951-f294b10a-1180-11e8-98a4-5570ca420959.png)

**Comment by ManishSahu53** [comment]
I am closing this issue because this is related to clustering not large dataset processing.
