### ISSUE TITLE
Can I get image from camera and output the camera poses and cloud points?

### ISSUE THREAD

**Issue by HyuanTan** [openMVG/openMVG#1066]
Hi, the Incremental/Sequential SfM and Global SfM calculate the  camera poses and cloud points using images saving previous, can I get the image from camera and calculate the  camera poses and cloud points use Incremental/Sequential SfM in real-time? If it can, any suggestion？

Thanks in advance for your help and thanks for this great tools!

**Comment by pmoulon** [comment]
@HyuanTan 
There is not real time implementation yet.
Feel free to help and contribution to make it true.

We already have implemented some [Visual Tracking tools](https://www.youtube.com/watch?v=lLNUDf_tMH8) but not yet the SLAM backend.

**Comment by WenyinWei** [comment]
Hello @pmoulon , I am considering implementing a kind of RGB camera real-time SLAM, whose RGB-D version has been almost finished by [MaskFusion](https://github.com/martinruenz/maskfusion), and their demonstration is really awesome. However, the lack of RGB image processing pipeline make it restricted at inside-room scene. I want to combine these four repos to make it happen, they are OpenMVG, OpenMVS, Open3D and MaskFusion. Would you like it?

**Comment by WenyinWei** [comment]
@pmoulon Hey, would you mind telling me your plan to implement real-time SfM? I am glad to contribute.
