### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by rnunziata** [openMVG/openMVG#1067]
I downloaded egain 3.3.3 installed it in a local directory and pointed to in in the CMakeLists.txt file 

```
set(EIGEN_ROOT,"/home/rjn/opencv3-p3-code/3dreconstruction/eigen-eigen-ce5a455b34c0/build/myinstall")
set(EIGEN_INCLUDE_DIR,"/home/rjn/opencv3-p3-code/3dreconstruction/eigen-eigen-ce5a455b34c0/build/myinstall")

FIND_PACKAGE(Eigen ${SYSTEM_PACKAGE_REQUIRED})
if(EIGEN_FOUND)
	INCLUDE_DIRECTORIES(${EIGEN_INCLUDE_DIRS})
	ADD_DEFINITIONS(${EIGEN_DEFINITIONS} -D_USE_EIGEN)
	SET(_USE_EIGEN TRUE)
endif()

```
But I am still getting this odd error: Any thoughts on how to fix?

`/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:822:30: error: invalid use of incomplete type ‘struct Eigen::internal::enable_if<false, SEACAVE::TPoint3<float>*>’`

**Comment by pmoulon** [comment]
`SEACAVE::TPoint3` is not defined in OpenMVG but in OpenMVS.

BTW, in order to specify an external Eigen library to OpenMVG you can do this in the cmake command line:
`-DEIGEN_INCLUDE_DIR_HINTS="YOUREIGENPATH"`

**Comment by rnunziata** [comment]
sorry ... I posted this in wrong thread. Thank for the info.
