### ISSUE TITLE
[Question] Sfm Data Export, Feature 2D location in image.

### ISSUE THREAD

**Issue by ghalmets** [openMVG/openMVG#1070]
Hello,
first of all thank you for the nice toolbox.

I was wondering if the Observation that are exported using sfm_data_io_baf are real observations based on the Feature extractor or "virtual" (reprojected) observations based on {the 3D feature, camera pose and camera model}.

If the latter, why? This information is redundant giving all the data. In opposite, the original feature location cannot be recovered. Is there a way to directly export the original 2D observation location? 

Cheers,
Georg

**Comment by pmoulon** [comment]
Hi,
SfM_Data store the raw feature location.
As you can see here they are not modified: https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_io_baf.hpp#L104

Perhaps we can update the doc here https://openmvg.readthedocs.io/en/latest/openMVG/sfm/sfm/ since it was not clear for you.

**Comment by pmoulon** [comment]
BTW, I would like recommend you to use the json export if you need to parse a file with the data.
Or use the OpenMVG API and read the sfm_data.bin.

**Comment by ghalmets** [comment]
Hi, thank you for the quick reply. 
actually I have checked the code already and I originally adapted it to export the data into the BAL format. 
After I have exported the data I displayed the detected features matches of two images (view i, view n) and figured out that they sometimes simply do not show the same feature (=image region) at approx 5 out of 90 views, moreover the matches are completely wrong. 

I modified the code to export the observation information using the simple peace of code at the end of my comment.

I attached my Debug Info and the two images. According to the data, the feature with the ID 0, was observed in view 1 and 4 at the exactly same location, even the 3 digits match what is actually impossible (cf. first 2 lines at the top of the image I've attached). According to the reconstruction the views have a similar pose (although its obviously not the same pose). However, it would explain a lot if the observations are virtual calculated giving the really similar pose, the same 3D feature and the same intrinsic camera values.

If this is not the case as you have explained, where could this error come from?
Thank you and all the best, 
Georg

![view1_view4_same_feature_location](https://user-images.githubusercontent.com/20701317/31032648-220eaea8-a55d-11e7-8487-17220867704d.png)

`const Landmarks & landmarks = sfm_data.GetLandmarks();
		//Export Features
		unsigned int i=0;
		for (const auto & iterLandmarks : landmarks )
		{
			// Export visibility information
			// X Y Z #observations id_cam id_pose x y ...
			const double * X = iterLandmarks.second.X.data();

			//Export Observation
			const Observations & obs = iterLandmarks.second.obs;
			for ( const auto & iterOb : obs )
			{
				const IndexT view_key = iterOb.first;
				const View * v = sfm_data.GetViews().at(view_key).get();

				double uv[2];
				uv[0]= iterOb.second.x(0);
				uv[1]= iterOb.second.x(1);
				std::cout<<"[feature_id,view_id, [u,v], pose_id, [pose], image_path]: "
                                <<i<<" , "
                                <<v->id_view<<" , "
                                <<"["<<uv[0]<<" ,  "<<uv[1]<<"]"<<", "
                                 << v->id_pose;

				const double * rotation = poses.at(v->id_pose).rotation().data();
				const double * center = poses.at(v->id_pose).center().data();
				std::cout<<", [ "<<center[0]<<" , "
					   <<center[1]<<" , "
					   <<center[2]<<" , "
					  <<rotation[0]<<" , "
					 <<rotation[1]<<" , "
					<<rotation[2]<<" , "
				        <<rotation[3]<<" , "
				        <<rotation[4]<<" , "
				        <<rotation[5]<< " ], "
				        << v->s_Img_path<<std::endl;
			}
			i++;
		}`

**Comment by pmoulon** [comment]
As you see here the point positions that are exported by the GlobalSfM triangulation are the raw feature positions:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/global/sfm_global_engine_relative_motions.cpp#L359

Please does not use `feature_id`, every track have already a unique ID store in `iterLandmarks.first`

**Comment by pmoulon** [comment]
You can also check the pairwise matches by using the binary `exportMatches` in order to see if the pairwise matches are ok.

**Comment by ghalmets** [comment]
Thank you, I will check the exportMatches to see if they are okay and rewrite my code to use the key. If that also doesn't help, I will try to use the json export to check if the wrong feature location is also in there.
 I will leave a message as soon I have new results. 

Cheers, Georg

**Comment by ghalmets** [comment]
Hi,

Problem solved!

Short update:
I found the same wrong data points in the Json file.

However, I pulled in the newest changes, recompiled everything. Reran the global_reconstruction and the json file as well as my BAL exports look perfect now.

Cheers, Georg
