### ISSUE TITLE
[Question] Specify sequence of images

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1073]
Hi

Is there any way to specify the sequence of images in openMVG.?

**Comment by pmoulon** [comment]
Can you elaborate?

I did not got your point, I mean do you speak about images names in the sfm_data or image pairs for matching.

By default `SfMInit_ImageListing` use the alphabetical order of the images of the specified directory.

**Comment by Ntweat** [comment]
Image pairs for matching. 
I am using videos to reconstruct the 3D model. Instead of having it match with all frames is there a way for it to match with just consecutive frames. 

Explanation: 
1. I had discussed with you about cars, I was able to reconstruct cars when they have one license plate (just at back or front) but when they have license plates on both ends, due to a large number of similar features on license plates they get matched and get overlapped. 

2. I am also trying to reconstruct internal of buildings and from drone videos. I was thinking instead of it matching with all the frames if we can give it the sequence it would save time.

**Comment by pmoulon** [comment]
Just look to the option of `main_ComputeMatches`:
- you have an option call `-v` to specify the contiguous matching range you want to do.
- or you can also specify a file with the pair number you want to match.
- If you have drone video with GPS settings I advise you to use https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#to-speed-up-the-pairwise-feature-matching-step

The other thing about this contiguous option is that you can loose loop closure between the start and the end or some large loop longer than the overlapping value your choose.

**Comment by Ntweat** [comment]
Thanks! I will try it out.!

I am trying to develop an automated pipeline for all kinds of users:
1. Who want scaled models (use of QR code)
2. Process 30 seconds videos (of objects like a box, toy cup)
3. Process long 10 minute videos  (interior of buildings, cars, etc)

**Comment by Ntweat** [comment]
Hi @pmoulon 

I need help understanding a few things.  I took closed loop videos of a corridor and around a building. 
When openMVG finish I notice the following:

1. cameraPath_translation_averaging.ply  does not have a closed loop. It always has an open loop.
2. cloud_and_poses.ply and colorized.ply both have closed loops. 

Can you tell me the reason?

**Comment by pmoulon** [comment]
> cameraPath_translation_averaging.ply. It always has an open loop.
- This is the path computed after motion averaging. If the graph is corrupted by outlier motions that have not been discarded sometimes the path is not perfect and it will be corrected by the BA.

> cloud_and_poses.ply and colorized.ply both have closed loops.
- It's because the BA and the selected matches was able to recover the error made at the motion averaging stage.

**Comment by pmoulon** [comment]
Can we close the issue?

**Comment by Ntweat** [comment]
Thanks :)
