### ISSUE TITLE
[SFM_data] Camera Pose?

### ISSUE THREAD

**Issue by ghalmets** [openMVG/openMVG#1077]
Hi,
I have another question regarding the camera pose of the sfm_data format.
As far as I understood the Pipeline exports C and R representing the Center and rotation as described here: [Link](http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/)
Right?

If the pose is accessed directly via something like 
`const double * R = poses.at(view->id_pose).rotation().data();`

is R ROW Major, 

R[0] R[1] R[2]
R[3] R[4] R[5]
R[6] R[7] R[8]

or COLUMN Major ordered?
R[0] R[3] R[6]
R[1] R[4] R[7]
R[2] R[5] R[8]

Thx,
Georg

**Comment by pmoulon** [comment]
OpenMVG is using the default Eigen alignement, so if you access the matrix with the data pointer you will have the data as column major.
https://github.com/openMVG/openMVG/blob/master/src/openMVG/numeric/eigen_alias_definition.hpp#L82


Ref: -> "The default in Eigen is column-major." https://eigen.tuxfamily.org/dox/group__TopicStorageOrders.html

BTW, if you have some doubt you can export the sfm-data file as a json file by using ConvertSfMDataFormat and see the rotation matrix value as ASCII.

**Comment by ghalmets** [comment]
Thank you for the quick reply, now everything works. It took me a while to figure out what the exported information is actually representing. 

Just a minor suggestion: Would it be possible to directly link the information about the [camera pose](http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/)  to the information regarding the [Sfm_data format](http://openmvg.readthedocs.io/en/latest/software/SfM/SfM_OutputFormat/), including the hint that it contains C and R not t and R and maybe with a hint if its ROW/COLUMN Major?

Imho simply exporting the *.bin to *.json and checking the ascii values does not resolve the question if the exported data is ordered row or column major.

Thank you again,
Georg

**Comment by pmoulon** [comment]
Thank you for your suggestion to improve the documentation.
Btw, if you look to the export in the code you can easily understand what info is exported:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/geometry/pose3_io.hpp#L17

Lets close this issue when the documentation will be enhanced!
