### ISSUE TITLE
[Question] PnP(P3P) example

### ISSUE THREAD

**Issue by MiaoDX** [openMVG/openMVG#1079]
Hei, thanks for this wonderful library!

I have one question, there are example codes with real images for Homography, Fundamental, Essential  (robust estimation) matrices. I am wondering, how to use the PnP module in this lib? I see some tests in [multiview/solver_resection_kernel_test.cpp](https://github.com/openMVG/openMVG/blob/master/src/openMVG/multiview/solver_resection_kernel_test.cpp). But how about some example with real image (both RBG and depth)? 

Since I do not know what pre-processing are needed, like do I need to normalize the data, do I need to prune the missed depth value (like depth image from Kinect) and how... (Simply put, I would rather a execuable file, lazy me :))

Or, do I miss something?

Looking forward for your reply!

**Comment by pmoulon** [comment]
Hi @MiaoDX 
THank you for your kind word about OpenMVG. Appreciated.

Why do you want to use P3P with RGBD data?
Can you elaborate?

The input of P3P solvers in OpenMVG is corresponding 3d points and 2d image positions.
You can choose to use known camera intrinsic for P3P or in case of unknown intrinsics you can use the 6pt DLT formulation.

The more detailed code is here:
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/localization/SfM_Localizer.cpp

**Comment by MiaoDX** [comment]
Thanks!

I am doing pose estimation, a single reference RGB image and RGB+(corresponding)Depth as testing images. Since the PnP can give `absolute` pose estimation (with scale), so I am trying to use that with the RANSAC framework in OpenMVG.

And the link is pretty self-explanatory, I will try to do that.

**Comment by pmoulon** [comment]
Feel free to ask more question or to close this issue when you succeed it.
