### ISSUE TITLE
SfMWebGLViewer: compile error gcc 7.2 (Fedora 26)

### ISSUE THREAD

**Issue by sgielkens** [openMVG/openMVG#1081]
Bonjour Pierre,

First of all, thanks for the continuously improving project!

I checked the open issues but I did not see the following issue. A compile error occurs in src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:

`/builddir/build/BUILD/openMVG-master/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:381:98: error: 'OPENMVG_SFM_WEBGL_SRC_PATH' was not declared in this scope
   const std::string inputFilename1 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_SRC_PATH ) + inputFolder , inputName );
                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/openMVG-master/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:381:98: note: suggested alternative: 'OPENMVG_SFM_SFM_VIEW_HPP'
   const std::string inputFilename1 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_SRC_PATH ) + inputFolder , inputName );
                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                  OPENMVG_SFM_SFM_VIEW_HPP
/builddir/build/BUILD/openMVG-master/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:382:98: error: 'OPENMVG_SFM_WEBGL_INSTALL_SHARED_PATH' was not declared in this scope
   const std::string inputFilename2 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_INSTALL_SHARED_PATH ) +  inputFolder , inputName );
`

It happens for version 1.2 and HEAD of the master branch (6ce820b2844a98941a5d2543050f4e278a323800).

With kind regards,  Serge Gielkens

**Comment by pmoulon** [comment]
Bonjour Serge,
@rperrot Any idea?

**Comment by rperrot** [comment]
Does the issue come only with gcc 7.2 ?

**Comment by sgielkens** [comment]
Hi Romuald.

Thanks for the quick response.

I just checked gcc 6.4 (Fedora 25). The compilation results with the same error as gcc 7.2 :-(

Is this enough testing or do you need the result from another gcc version as well?

With kind regards,  Serge Gielkens

**Comment by rperrot** [comment]
Thank's, I'll try to reproduce your issue with gcc 6.4. 

Could you please give us the instruction used to produce this error ? (options passed to cmake and gcc)

**Comment by sgielkens** [comment]
Hi Romuald,

This is the cmake command:

cmake -DCMAKE_BUILD_TYPE=RELEASE \
        -DCLP_INCLUDE_DIR_HINTS=/usr/include/coin/ \
        -DOSI_INCLUDE_DIR_HINTS=/usr/include/coin/ \
        -DCOINUTILS_INCLUDE_DIR_HINTS=/usr/include/coin \
        -DCERES_DIR_HINTS=/usr/lib64/cmake/Ceres \
        -DEIGEN_INCLUDE_DIR_HINTS=/usr/include/eigen3 \
        -DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann \
        -DLEMON_INCLUDE_DIR_HINTS=/usr/include/lemon \
        -DOpenMVG_BUILD_TESTS=ON \
        -DOpenMVG_BUILD_EXAMPLES=OFF \
        -DOpenMVG_USE_OCVSIFT=OFF \
        -DOpenMVG_USE_OPENCV=ON \
        -DCMAKE_INSTALL_PREFIX="/usr" \
        ../src

This is the generated compiler command:

/usr/bin/c++  -DOPENMVG_USE_AVX2 -DOPENMVG_USE_OPENMP -I/usr/include/eigen3 -I/builddir/build/BUILD/openMVG-1.2/src -I/builddir/build/BUILD/openMVG-1.2/src/dependencies -I/builddir/build/BUILD/openMVG-1.2/src/dependencies/cereal/include -I/usr/include/flann -I/builddir/build/BUILD/openMVG-1.2/build/software/SfMWebGLViewer  -march=skylake -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mfma -mbmi2 -mavx2 -mno-sse4a -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -fopenmp -O3   -std=c++11 -o CMakeFiles/openMVG_main_openMVG2WebGL.dir/openMVG_main_openMVG2WebGL.cpp.o -c /builddir/build/BUILD/openMVG-1.2/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp

If you need any information about versions of used libraries, I will gladly provide them.

With kind regards,  Serge

**Comment by rperrot** [comment]
I'm sorry I can't reproduce your issue with gcc6.4 on my machine (OSX). 

What is the version of cmake ? 

Just a stupid thing, can you type Release instead of RELEASE in your cmake command ?

**Comment by sgielkens** [comment]
The version of cmake is 3.9.1 (for both Fedora 25 and 26). 

I used Release, but the compile error remains unfortunately.

One thing that popped up in my mind. I use as much Fedora packages as possible. So I do not use the following bundled directories by removing them:

- rm -fr src/third_party/ceres-solver
- rm -fr src/third_party/eigen
- rm -fr src/third_party/flann
- rm -fr src/third_party/jpeg
- rm -fr src/third_party/lemon
- rm -fr src/third_party/png
- rm -fr src/third_party/tiff
- rm -fr src/third_party/zlib

Could there be an issue?

**Comment by rperrot** [comment]
I don't think so, the issue is in my opinion cmake related. 

The errors are some variables that are not passed to the cpp file. However they are defined in https://github.com/openMVG/openMVG/blob/master/src/software/SfMWebGLViewer/config.h.in, this file is generated by cmake (here : https://github.com/openMVG/openMVG/blob/master/src/software/SfMWebGLViewer/CMakeLists.txt#L3) and is finally included here https://github.com/openMVG/openMVG/blob/master/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp#L17

Could you check if the config.h is well generated in the corresponding build directory ?

**Comment by sgielkens** [comment]
I checked the following file in the build directory:

software/SfMWebGLViewer/config.h

Its content:

`// This file is part of OpenMVG, an Open Multiple View Geometry C++ library.

// Copyright (c) 2017 Romuald Perrot.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#ifndef _OPENMVG_MAIN_OPENMVG_TO_WEBGL_CONFIG_H_
#define _OPENMVG_MAIN_OPENMVG_TO_WEBGL_CONFIG_H_

#define OPENMVG_SFM_WEBGL_INSTALL_SHARED_PATH "/usr/share/openMVG/webgl"
#define OPENMVG_SFM_WEBGL_SRC_PATH "/builddir/build/BUILD/openMVG-1.2/src/software/SfMWebGLViewer"


#endif`

That seems correct to me, or am I mistaken? Unless the cpp file could not find it. I wiil check this tomorrow.

**Comment by rperrot** [comment]
Yes, it seems correct. 

Maybe there's an another directory that contains a config.h and is included instead of this one. 

Just to make a test, could you rename the file config.h.in to something else (config-path.h.in for example), make the modifications in the CMakeLists (rename config.h.in and config.h to config-path.h.in and config-path.h) and in the cpp file (replace the include config.h to config-path.h).

**Comment by sgielkens** [comment]
Hi Romuald,

I took the direct way and replaced in the cpp file the include file by its contents. Et voilà, compilation succeeded. Then I took a closer  look at the generated c++ command (see message above) and this is the problem:

` -I/usr/include/flann -I/builddir/build/BUILD/openMVG-1.2/build/software/SfMWebGLViewer `

Flann supplies also config.h. When I placed the content of your include config.h in it, the compilation succeeded as well. This proves that /usr/include/flann/config.h is found and used instead of yours. 

I have no idea why it happens on my system and not on yours. Is the order of include directories different (other cmake version), does your system not have /usr/include/flann/config.h? What do you think?

With kind regards,  Serge

**Comment by pmoulon** [comment]
Perhaps the internal flann does not have the same config as yours.

What happens if you restore the third_party dir and force to use the internal flann?
- So do not define this for cmake `-DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann `

**Comment by sgielkens** [comment]
Indeed, when keeping src/third_party/flann, the compilation succeeds. I see the difference in include directories of the generated c++ command:

`-I/builddir/build/BUILD/openMVG-1.2/src/third_party/flann/src/cpp -I/builddir/build/BUILD/openMVG-1.2/build/software/SfMWebGLViewer`

It is the subdirectory flann of include dir src/third_party/flann/src/cpp  which contains config.h. In other words, the cpp file will not detect the flann/config.h and compiles without error. 

I see that the third_party CMakeLists.txt defines this include dir:

include_directories(${PROJECT_SOURCE_DIR}/src/cpp)

This explains what happens. Now I have to think how to solve this as I am reluctant to use software which is already available as an official package.

**Comment by sgielkens** [comment]
Bonsoir,

If i apply this patch, the compilation succeeds:

`--- src/cmakeFindModules/FindFlann.cmake        2017-10-09 20:22:27.296604896 +0200
+++ src/cmakeFindModules/FindFlann.cmake.org    2017-10-09 20:38:23.972096765 +0200
@@ -2,7 +2,7 @@
 #                  Find Flann Library
 #----------------------------------------------------------
 
-FIND_PATH(FLANN_DIR flann.hpp
+FIND_PATH(FLANN_DIR flann/flann.hpp
     HINTS "${FLANN_ROOT}" "$ENV{FLANN_ROOT}" "${FLANN_INCLUDE_DIR_HINTS}"
     PATHS "$ENV{PROGRAMFILES}/flann" "$ENV{PROGRAMW6432}/flann"
     PATH_SUFFIXES flann
@@ -18,7 +18,7 @@
         MARK_AS_ADVANCED(FLANN_DIR)
 
         # Extract Flann version from config.h
-        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/config.h)
+        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/flann/config.h)
         IF (NOT EXISTS ${FLANN_VERSION_FILE})
                 FLANN_REPORT_NOT_FOUND(
                   "Could not find file: ${FLANN_VERSION_FILE} "`

Naturally I use -DFLANN_INCLUDE_DIR_HINTS=/usr/include in the cmake command.

Now the flann include dir is /usr/include just as in the case when I would use src/third_party/flann. In other words, this is in accordance with src/third_party/flann/cmake/FindFlann.cmake:

`find_path(FLANN_INCLUDE_DIR flann/flann.hpp
    HINTS ${PC_FLANN_INCLUDEDIR} ${PC_FLANN_INCLUDE_DIRS})`

What is your opinion?

**Comment by sgielkens** [comment]
Hmm, markdown got confused by # signs. Somewhat better preview of patch:

`-- src/cmakeFindModules/FindFlann.cmake        2017-10-09 20:22:27.296604896 +0200
+++ src/cmakeFindModules/FindFlann.cmake.org    2017-10-09 20:38:23.972096765 +0200
@@ -2,7 +2,7 @@
\#                  Find Flann Library
 \#----------------------------------------------------------
 
-FIND_PATH(FLANN_DIR flann.hpp
+FIND_PATH(FLANN_DIR flann/flann.hpp
     HINTS "${FLANN_ROOT}" "$ENV{FLANN_ROOT}" "${FLANN_INCLUDE_DIR_HINTS}"
     PATHS "$ENV{PROGRAMFILES}/flann" "$ENV{PROGRAMW6432}/flann"
     PATH_SUFFIXES flann
@@ -18,7 +18,7 @@
         MARK_AS_ADVANCED(FLANN_DIR)
 
\        # Extract Flann version from config.h
\-        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/config.h)
\+        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/flann/config.h)
         IF (NOT EXISTS ${FLANN_VERSION_FILE})
                 FLANN_REPORT_NOT_FOUND(
                   "Could not find file: ${FLANN_VERSION_FILE} "
`

**Comment by pmoulon** [comment]
Just a tip.
For long piece of code you have to use 3 time the `

Like this:
"\`\`\`"
code
"\`\`\`"

i.e
```
code
here
````

**Comment by sgielkens** [comment]
Thanks. Much better indeed:

```
--- src/cmakeFindModules/FindFlann.cmake        2017-10-09 20:22:27.296604896 +0200
+++ src/cmakeFindModules/FindFlann.cmake.org    2017-10-09 20:38:23.972096765 +0200
@@ -2,7 +2,7 @@
 #                  Find Flann Library
 #----------------------------------------------------------
 
-FIND_PATH(FLANN_DIR flann.hpp
+FIND_PATH(FLANN_DIR flann/flann.hpp
     HINTS "${FLANN_ROOT}" "$ENV{FLANN_ROOT}" "${FLANN_INCLUDE_DIR_HINTS}"
     PATHS "$ENV{PROGRAMFILES}/flann" "$ENV{PROGRAMW6432}/flann"
     PATH_SUFFIXES flann
@@ -18,7 +18,7 @@
         MARK_AS_ADVANCED(FLANN_DIR)
 
         # Extract Flann version from config.h
-        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/config.h)
+        SET(FLANN_VERSION_FILE ${FLANN_INCLUDE_DIRS}/flann/config.h)
         IF (NOT EXISTS ${FLANN_VERSION_FILE})
                 FLANN_REPORT_NOT_FOUND(
                   "Could not find file: ${FLANN_VERSION_FILE} "

```

**Comment by pmoulon** [comment]
What did happen if you just try:
`-DFLANN_INCLUDE_DIR_HINTS=/usr/include` instead of `-DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann`?

**Comment by sgielkens** [comment]
That was my first guess but did not work. That resulted again in:

`FLANN_DIR:PATH=/usr/include/flann`

And consequently in:

`OpenMVG_INCLUDE_DIRS:PATH=/builddir/build/BUILD/openMVG-1.2/src;/builddir/build/BUILD/openMVG-1.2/src/dependencies;/builddir/build/BUILD/openMVG-1.2/src/dependencies/cereal/include;/usr/include;/usr/include/eigen3;/usr/include/flann`

So the wrong config.h in /usr/include/flann was used.

**Comment by pmoulon** [comment]
Can you make a PR with your fix?

**Comment by sgielkens** [comment]
I just made a PR.

**Comment by pmoulon** [comment]
Just link the PR here https://github.com/openMVG/openMVG/pull/1103 and close the ticket.
The PR will be used to track this issue.
