### ISSUE TITLE
Documentation on openMVG_main_ComputeClusters

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#1083]
I wasn't able to find any docs on `openMVG_main_ComputeClusters`. Do they exist? It would be helpful :)

**Comment by pmoulon** [comment]
What do you want to know?

Default help about the command line argument are not enough:
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/clustering/main_ComputeClusters.cpp#L182

**Comment by ssampang** [comment]
Currently I'm wondering:
1. In what scenarios do you recommend we use it
2. When to use it (what stage of the pipeline)
3. What effects it can have
4. The units for the upper and lower bound arguments

**Comment by rperrot** [comment]
Trying to answer your questions : 

1. It is usually required to split a huge SfM reconstruction into smaller ones. The idea is that some MVS tools (openMVS for ex), requires lot of memory and a whole scene may not fit into memory. In that case, you split in smaller parts then you process them separately
2. You may use it after SfM reconstruction is done (so after incremental or global executable)
3. It splits a SfM scene into smaller clusters
4. It's in the order of number of pose (ie: min/max number of camera in each cluster).

**Comment by ssampang** [comment]
Thanks@

**Comment by pmoulon** [comment]
Side effect of splitting:
- since the chunks does not have camera overlap, the 3d point cloud can have a partial overlap in the chunk borders.
-> We are working on a solution for this: https://github.com/openMVG/openMVG/pull/1078

Side note:
Since you seems to look for alternative to process your dataset faster. Note that if you want a faster processing with GPS dataset you can often obtain a sparser graph thanks to the approximate image GPS location -> https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#to-speed-up-the-pairwise-feature-matching-step

**Comment by ssampang** [comment]
I've moved feature matching to GPU, so the bottleneck I'm facing now is largely in the SFM stage. Specifically, the time needed for SfM doesn't scale linearly with the # of frames (for me it becomes unfeasible* once I pass ~300-400 frames), and so I'm looking for ways to a) minimize the time overall and alternatively b) do some intelligent clustering to minimize the number of frames that the SFM stage has to operate on.

*unfeasible is a relative term, and is largely dependent on the needs of my company 😄

**Comment by pmoulon** [comment]
Did you tried GlobalSfM on your datasets?
- this pipeline should scale better on your data
- if you have GPS prior it will be used too.

**Comment by ssampang** [comment]
I have not. I still need to understand the possible effects of switching to using GlobalSfM. Do you know of any literature I can read to learn more about this? My main concerns are possible side effects such as failure on videos that would have succeeded with IncrementalSfM (which I believe is known to be more robust?), or possible decrease in quality.

**Comment by ssampang** [comment]
For reference, #1037 has a great explanation.
