### ISSUE TITLE
Segmentation fault (core dumped), when using openMVG as third party library

### ISSUE THREAD

**Issue by programsji** [openMVG/openMVG#1086]
This is my cmake file

```
CMAKE_MINIMUM_REQUIRED(VERSION 3.1)

# If a C++11 compiler is available, then set the appropriate flags
  set(CMAKE_CXX_STANDARD 11)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)

project(myapp C CXX)
set(CMAKE_BUILD_TYPE "Release")

find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
add_executable(aproj main.cpp)
target_link_libraries(aproj ${OPENMVG_LIBRARIES})
```

Please let me know if I am missing anything

**Comment by programsji** [comment]
I am using it on Ubuntu. and my example code is this : 
`// This file is part of OpenMVG, an Open Multiple View Geometry C++ library.

// Copyright (c) 2012, 2013 Pierre MOULON.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#include "openMVG/features/feature.hpp"
#include "openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp"
#include "openMVG/features/svg_features.hpp"
#include "openMVG/image/image_io.hpp"
#include "openMVG/image/image_concat.hpp"
#include "openMVG/matching/regions_matcher.hpp"
#include "openMVG/matching/svg_matches.hpp"
//
#include "third_party/stlplus3/filesystemSimplified/file_system.hpp"

#include <cstdlib>
#include <string>
#include <iostream>

using namespace openMVG;
using namespace openMVG::image;
using namespace openMVG::matching;
using namespace std;

int main() {

  Image<RGBColor> image;
  string jpg_filenameL = "/home/me/Desktop/images/1.JPG";
  string jpg_filenameR = "/home/me/Desktop/images/2.JPG";
  std::cout<<"Chhane";
  Image<unsigned char> imageL, imageR;
  ReadImage(jpg_filenameL.c_str(), &imageL);
  ReadImage(jpg_filenameR.c_str(), &imageR);
  std::cout<<"LAGA";
  //--
  // Detect regions thanks to an image_describer
  //--
  using namespace openMVG::features;
  std::unique_ptr<Image_describer> image_describer(new SIFT_Anatomy_Image_describer);
  std::map<IndexT, std::unique_ptr<features::Regions> > regions_perImage;

  image_describer->Describe(imageL, regions_perImage[0]);
  image_describer->Describe(imageR, regions_perImage[1]);

  return 1;
}`

**Comment by pmoulon** [comment]
Can you try with the branch develop from OpenMVG?

The compilation flag forwarding must be done in the correct way now.
See: https://github.com/openMVG/openMVG/issues/1028

**Comment by programsji** [comment]
ok,I will let you know.

**Comment by programsji** [comment]
Thanks
