### ISSUE TITLE
Build error including "sfm_data.hpp" while using openMVG as thirdparty library.

### ISSUE THREAD

**Issue by srivathsanmurali** [openMVG/openMVG#1092]
Hi,
I am trying to use to openMVG as a third party library.

When I include "sfm_data.hpp", it includes "sfm_view.hpp"

"sfm_view.hpp" seems to include third_party filesystem.hpp in its header which is breaking my build as third_party headers are in openMVG/third_party.
https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/openMVG/sfm/sfm_view.hpp#L16

Is it possible to replace "third_party" to "openMVG/third_party" when installing the files.
Hope you can help me out.

**Comment by pmoulon** [comment]
Hi @srivathsanmurali,
Are you using cmake to use OpenMVG as a third party.
The include dir path must be adapted automatically here: https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L590
and so the file must be found in the include dir.

BTW, the best way to deal with this issue would be to work on using the CMAKE `INTERFACE` configuration (I need to work on this point):
https://github.com/openMVG/openMVG/blob/develop/src/third_party/lemon/lemon/CMakeLists.txt#L58

**Comment by srivathsanmurali** [comment]
If I am not wrong,
https://github.com/openMVG/openMVG/blob/0813c7acf60d8c9df18be223a6707bbd43e501cd/src/CMakeLists.txt#L590-L595
this code snippet only changes the paths in the $(OpenMVG_INCLUDE_DIRS) set that have in thirdparty to appear in openMVG/third_party. It doesn't change the content of the files.

My issue is that in the sfm_view.hpp, it looks for the "file_systems.hpp".
https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/openMVG/sfm/sfm_view.hpp#L16
Upon on installation, it must be
``` c++
#include "openMVG/third_party/stlplus3/filesystemSimplified/file_system.hpp" 
```
A way I would go about doing it is, replace third_party to openMVG/third_party in each of the files in $(OpenMVG_INCLUDE_DIRS)

**Comment by srivathsanmurali** [comment]
FYI:
I am installing openMVG in /usr/local and using find_package(openMVG) in my project.

**Comment by pmoulon** [comment]
I'm not for modifying the include path in the installed files.
I will have a look soon and come back to you.

**Comment by pmoulon** [comment]
I just tried in a fresh VM:
- clone OpenMVG develop branch
- compile it and install it
- try to compile openMVG_main_ComputeFeatures by using OpenMVG as a third_party and it is working. Note: this code include the file sfm_data.hpp.

Are you sure you did not got any previous OpenMVG version installed that can create a conflict?
I mean: Are you able to see `Found OpenMVG version: 1.2.0` at cmake configuration time for your project?

**Comment by srivathsanmurali** [comment]
So, cmake does find openMVG version 1.2.0.
![screenshot_20171012_091851](https://user-images.githubusercontent.com/7250584/31483920-9e0f90d2-af2e-11e7-9e9c-8bda2fb8d380.png)

When I try to compile. it raises an error that because the third_party header is not found.
![screenshot_20171012_092328black](https://user-images.githubusercontent.com/7250584/31484353-4574fc08-af30-11e7-9a68-f545603b49e8.png)

I am not sure what I mistake I am making in the setup.

**Comment by pmoulon** [comment]
Are you using master or develop branch?

**Comment by srivathsanmurali** [comment]
I am using master branch. I could try with develop branch

**Comment by srivathsanmurali** [comment]
Hi,
I was able to solve the problem by moving the "file_system.hpp" include to other files which included sfm_view.hpp. I think keeping such API headers clean from third_party headers would be better.

I have started a PR #1105 which show my changes.

I also found some source files which didn't include file_system.hpp but were using stl_plus features as it was included in sfm_view.hpp. (I think these kind of inclusions could be made explicit in source files.)

**Comment by pmoulon** [comment]
Now that #1105 is merged. Can we close the issue?

**Comment by pmoulon** [comment]
Thx for your PR!

**Comment by srivathsanmurali** [comment]
Yup I am gonna close this issue.
