### ISSUE TITLE
Compilation failed: Incorrect `std::map` template parameters.

### ISSUE THREAD

**Issue by tomas789** [openMVG/openMVG#1094]
After update to Xcode 9, I'm unable to build openMVG. I'm experiencing this issue only when building on OS X with Xcode 9. No problems when building on Ubuntu box. It produced two error messages

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/tomaskrejci/Developer/openMVG/src/software/SfM/io_readGT.hpp:158:24: note: in instantiation of template class 'std::__1::map<unsigned long, openMVG::cameras::PinholeCamera, std::__1::less<unsigned long>,
      Eigen::aligned_allocator<std::__1::pair<unsigned long, openMVG::cameras::PinholeCamera> > >' requested here
          map_camerasGT.insert({std::distance(vec_camfilenames.cbegin(), iter), cam});
```

and 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/tomaskrejci/Developer/openMVG/src/software/SfM/main_evalQuality.cpp:116:70: note: in instantiation of template class 'std::__1::map<unsigned long, openMVG::cameras::PinholeCamera, std::__1::less<unsigned long>,
      Eigen::aligned_allocator<std::__1::pair<unsigned long, openMVG::cameras::PinholeCamera> > >' requested here
         Eigen::aligned_allocator<std::pair<size_t, PinholeCamera>>> map_Cam_gt;
```

I'm not sure how this relates to C++ standard but default value for `Allocator` template parameter of `std::map` is `std::allocator<std::pair<const Key, T>`. On the other hand, in openMVG, first item in pair is not const. When I add it, everything builds properly. 

Sidenote: I'm experiencing the same issue with other libraries too. This is probably related to some changes introduced in Xcode 9.

**Comment by pmoulon** [comment]
Thanks for the report.
Fun fact, I fix that yesterday in the develop branch and it will be merged in the next version release.
see https://github.com/openMVG/openMVG/commit/cb24555e57ad396d7c39891b1c2ae90d75d3f03b#diff-3cf5e3f03e323ea9a32915006a11bdfe and https://github.com/openMVG/openMVG/commit/cb24555e57ad396d7c39891b1c2ae90d75d3f03b#diff-71e01120423fef1774dbe33b2c21323a

**Comment by tomas789** [comment]
Awesome! Next time, I'll play with develop branch instead.

**Comment by pmoulon** [comment]
No worries. FYI, the develop branch contains all the WIP features that we plan to be release in the next OpenMVG version.

Master branch is only updated when a new version is done in develop.
