### ISSUE TITLE
[Question] Best option for camera parameters

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1099]
Hi
openMVG has many ways to give it camera parameters and then it also does self-calibrations.
I was wondering what would be the best way of giving openMVG the initial parameters.

1. Let it read the meta data of the images.
2. Give it intrinsic parameters from openCV
3. Give it focal length
4. Give approx focal length f =1.2*max(w,h)
or any I missed.

I am currently using option 4 as I am using video frames. But which would be the best way to get most accurate results.

**Comment by pmoulon** [comment]
The general idea is that the more precise intrinsic you will provide, the best results you will obtain.

2. require a calibration and it is perhaps not optimal for your pipeline

4. should be fine for most of the case.
Something you can try is to perform SfM in a two step process.
a. Run SfM with some approximate focal length.
b. Use the found calibration to enhance your geometric match set and run again SfM.
  - to do so, Run again ComputeMatches but with the sfm_data file from the previous SfM. The estimated distortion coefficient and the refined focal length will be used and so you can obtain better correspondences. Then you run SfM again with the new matches.X.bin file.

**Comment by Ntweat** [comment]
I am creating a general purpose pipeline. Want to give it an option that if a person can provide the intrinsics then it can use, so wanted to know if that would make a difference in the accuracy of the model before I implement it.

**Comment by pmoulon** [comment]
You can test it by yourself on some dataset:
- Do an autocalibration for an approximate focal length.
- And then process some other dataset that have used the same camera setting.You can update the sfm_data.json with your previously precomputed parameter just after calling SfMInitImageListing.

I don't know  your roadmap, but you can also see to prioritize and see what you must do first.
