### ISSUE TITLE
Link at README.md page is invalid.

### ISSUE THREAD

**Issue by tomas789** [openMVG/openMVG#1108]
Link in main `README.md` points to `BUILD` file which does not exist. It should point to `BUILD.md` instead.
Sorry for pinpointing those minor things I reported lately. OpenMVG is a great tool and I think this will improve an experience for others.

**Comment by pmoulon** [comment]
Thanks. We have fixed this in the develop branch and so it will be updated for the next release.
See here: https://github.com/openMVG/openMVG/commit/e25f044cb5880a37c31a3e3e68a500cbe682dffb#diff-04c6e90faac2675aa89e2176d2eec7d8

New commits comes to master only when a new released is out.
