### ISSUE TITLE
focal in Kmatrix

### ISSUE THREAD

**Issue by 5kyfly** [openMVG/openMVG#1110]
In openMVG ,intrinsic parameters [-k|–intrinsics] Kmatrix: “f;0;ppx;0;f;ppy;0;0;1”.
You use focalpix(f) repesent k[0,0]and k[1,1] but I think they aren't equal.
fx isn't equal to fy precisely.
Kmatrix could be "fx;0ppx;0;fy;ppy;0;0;1".
How can I change Kmatrix?

**Comment by pmoulon** [comment]
OpenMVG suppose that the camera is having square pixel and so the focal is the same for the x and y direction.
