### ISSUE TITLE
Intrinsics priority over exif in SfMInitImageListing

### ISSUE THREAD

**Issue by robert128** [openMVG/openMVG#1111]
Hello,

I have frames from a video camera that have little exif data, so I thought I was helping out by adding the model to the jpegs.  I also added the model to the camera width database to match.  Meanwhile, I have calibrated the camera, so I have intrinsic parameters and use them on the command line with -k.  When I run openMVG_main_SfMInit_ImageListing, it returns with "Focal length is missing".  Looking at the code, it appears that if the model is there, but the -f focal_pixels is not, the tool attempts to read the focal length from the exif data and compute from there.  It does this regardless of the -k option which clobbers the 'focal' value provided by the Kmatrix.  I think as long as the intrinsics are given, they should have priority over the exif data and the computations from them.

I deleted the exif data from my pictures and solved my problem (and saved myself the effort for the future).

Thanks for the fine software

**Comment by hcjghr** [comment]
Hi @robert128,

I was facing similar problems and I made a simple adjustment to prioritize user-provided intrinsics (-k > -f > exif). I've just made a PR to add it to develop branch but you can get it for now at [https://github.com/hcjghr/openMVG/tree/develop_init_order](https://github.com/hcjghr/openMVG/tree/develop_init_order).

Hope it helps!

**Comment by robert128** [comment]
Thanks, glad the fix is ready to go!

**Comment by pmoulon** [comment]
Fixed included in OpenMVG v1.3 https://github.com/openMVG/openMVG/commit/665ffc948d6848f1e43ff235456cc3673bacc426
