### ISSUE TITLE
Cannot find BUILD instructions link. Multiple build errors using vs12

### ISSUE THREAD

**Issue by pathi** [openMVG/openMVG#1112]
Hi, I am trying to build OpenMVG using vs12 on a windows 10 machine, I tried to get the code using git clone, ran submodule initializations. Cmake seems to be generating a decent solution folder, but however, when compiling, I get multiple compilation errors, mainly saying "typename cannot be used outside a template declaration".
I wonder whether I am doing anything wrong here in the building process, as I could not find the working link defined on the Github website.

**Comment by pmoulon** [comment]
Hi,
You will need to have Visual Studio >= 2015
https://github.com/openMVG/openMVG/blob/master/BUILD.md

VS2013 does not have a full support of all the C++11 features.
