### ISSUE TITLE
Robust relative pose estimation fails when the images are almost the same.

### ISSUE THREAD

**Issue by MiaoDX** [openMVG/openMVG#1119]
It seem that, when the two images are almost the same, to make it a more special case, the input images are just the same, the code [openMVG_Samples/multiview_robust_essential/robust_essential.cpp](https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/multiview_robust_essential/robust_essential.cpp) fails to do the estimation. The failure comes from the function `estimate_Rt_fromE` in [#L141 of file sfm/pipelines/sfm_robust_model_estimation.cpp#L141](https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/sfm_robust_model_estimation.cpp#L141).

It make scene that when two images are the same, the code will not produce any meaningful results, but how can we estimate two images when they are very similar? Since the code close the door without open another window.

For example, when we do pose estimation with PnP, when the two images are very close, we can get pretty precious relative pose estimation. But how can we do it with 5-points(robustRelativePose)?

Or, do I miss something?

Looking forward to your reply!

**Comment by pmoulon** [comment]
I think that you are close to a degenerate solution here.
BTW, the solver works for time to time on very small baseline.

The other thing is that I'm using a criteria to check which solution of the best 2 solution is better to keep. In your case (zero baseline) perhaps this criteria cancel all the possible relative pose.

You can try to set the parameter `positive_depth_solution_ratio ` to 1.0
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sfm_robust_model_estimation.cpp#L32
and see if you have the desired result or not.

Note that absolute pose estimation (PnP) is not the same problem as relative pose. PnP does not have the same degenerated cases.

**Comment by MiaoDX** [comment]
Aha, thanks a lot, I removed this check by copying the funtions out. The results are not always statisfcing.

But now I know what the porblem is, searched `degenerate` for a while, it seems that I did not notice this well-known problem before. Even David Nist´er discussed this in his [An Efficient Solution to the Five-Point Relative Pose Problem](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.86.8769&rep=rep1&type=pdf) paper.

I will try to find some solutions to this in the literatures, if you have any guidences please hit on me, or you can close this issue since I get enough informaiton. Thanks again for this great lib and kind reply!

**Comment by pmoulon** [comment]
I would advise you to take a look to:
L Kneip, R Siegwart, and M Pollefeys. Finding the exact rotation between two images independently of the translation. In Proceedings of the European Conference on Computer Vision (ECCV), Firenze, Italy, October 2012

Fisher Yu and David Gallup, 3D Reconstruction from Accidental Motion. CVPR 2014

J. Ventura, Structure from Motion on a Sphere. ECCV 2016

BTW, often you can run the OpenMVG Global SfM on a sequence of images with very short baseline and still obtain decent results.
