### ISSUE TITLE
preprocessed Images vs original images

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#1123]
Hi,

By preprocessing images before calling openMVG/openMVS i get sometimes significantly better results for the geometry of the reconstruction. However, the image preprocessing changes (ie degrades) the colors and then 3D model texture.

Is there a way to use preprocessed images for openMVG and use the original images for openMVS ?

Thank you

**Comment by ManishSahu53** [comment]
I guess you are trying to downsample images for SFM and then using original resolution images for MVS reconstruction? I am also planning to do this. Maybe you can try this
1. Downsample images(pre-process)
2. run openMVG
3. replace the downsample images with original images.
4. run openMVG2openMVS conversion command.
Let me know if that work?

**Comment by pmoulon** [comment]
What do you mean by preprocessing?

If you mean that the images have the same size and that you just changed the color balance or perform some leveling operation, you can directly replaces your image directory before calling the exporter. So OpenMVG will un-distort your initial images and not your preprocessed one.

If you want to do not overwrite the initial image, you can just use symbolic link, and change the symbolic link to either point to the original image or the modified image at any step of the pipeline.

**Comment by s-wtnb** [comment]
In my case, preprocessing(image downsized) is to reduce the time it takes to obtain features.
In that case, need to change the focal length(etc)?

**Comment by pmoulon** [comment]
You just need to rescale the focal length and the image size.
The distortion is computed in the camera plane so you don't need to rescale it.

We can also think about implementing a Image_describer decorator that rescale the image before extraction and that upscale the computed feature location afterwards. So with this design, no need to change anything ;-)

**Comment by s-wtnb** [comment]
For example, set the image size from 6000 x 4000 to 3000 x 2000, the focal length is half as well?
(not consider using the original image with MVS)

**Comment by alvaro562003** [comment]
@pmoulon,
Sorry, i should have been more precise with the word "preprocess"
In my case, i am increasing contrast using retinex filter. The images have the same size.

I understand, i run the complete openMVG process with the preprocessed images and before calling the exporter "openMVG_main_openMVG2openMVS",  i have to replace the preprocessed images by the raw/original ones in the "images" directory.

Perfect, crystal clear.
Thank you

**Comment by hcjghr** [comment]
Hi,

yes that is exactly the way. Don't forget that the name of the preprocessed and original images should be the same as otherwise "the switch" wont work. I know its obvious but it never hurts to emphasis it :)

Hope it works!

**Comment by alvaro562003** [comment]
thank you hcjghr,
By the way, what are the very "efficient filters" that increase the number of salient points for AKAZE or SIFT?

**Comment by ManishSahu53** [comment]
@pmoulon,
I dont think we have to manually change focal length. Since focal length is stored in exif in mm. so focal length in pixel  = (focal_mm / sensor_width_mm) * image_width_in_pixel. So this is automatically taken care. Isnt it?

**Comment by alvaro562003** [comment]
@pmoulon and   @hcjghr
i tested and it works well
thank you

**Comment by pmoulon** [comment]
@alvaro562003 would you like to share some result (screenshot of your reconstruction) with and without preprocessing?

Did you saw this paper: http://ict-bridget.eu/publications/FastFeatureMatching.pdf "Fast feature matching for detailed point cloud generation"

**Comment by alvaro562003** [comment]
Yes, i will do it asap.

**Comment by pmoulon** [comment]
On the other hand it would be also interesting to see how it compares with the default preset configuration on main_ComputeMatches (NORMAL/HIGH/ULTRA)?

Certainly the retinex is changing the local image gradient profile and so make it more flat and so provide a better uniform response map for the feature extraction.
