### ISSUE TITLE
Possible floating point truncation error

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#1124]
I have a set of frames from a DJI drone flying above a few city blocks. From one angle, the openMVG SfM pipeline seems to work fine:
<img width="1070" alt="screen shot 2017-10-23 at 4 59 06 pm" src="https://user-images.githubusercontent.com/1335633/31918827-83b8c288-b813-11e7-9f16-bc72947a503c.png">
The flight path seems accurate:
<img width="1064" alt="screen shot 2017-10-23 at 5 01 32 pm" src="https://user-images.githubusercontent.com/1335633/31918904-d83532ce-b813-11e7-9019-0b16664066f7.png">
However, from certain angles, you can see that the points seem to be clustering/binning into specific lines:
<img width="510" alt="screen shot 2017-10-23 at 5 02 53 pm" src="https://user-images.githubusercontent.com/1335633/31918949-23235c34-b814-11e7-9b87-4d245e6d83b4.png">

Consequently, this causes a segfault error in MVE.

**Comment by pmoulon** [comment]
Can you provide detail about the pipeline you used?
- sequential, global?
- position prior, no position prior?

**Comment by ssampang** [comment]
Sequential + no position prior.

One thing I did notice that seemed abnormal was that the model was not centered on the origin:
<img width="471" alt="screen shot 2017-10-24 at 10 38 56 am" src="https://user-images.githubusercontent.com/1335633/31958808-bfc75a5c-b8a7-11e7-971e-4aa35c210f77.png">
Usually, the models openMVG outputs are far more centered than this, but I'm not sure if this is particularly relevant to whatever is causing this issue.

**Comment by erikreed** [comment]
The binning I believe is just from meshlab, not the actual data. I have notes on it here: https://github.com/openMVG/openMVG/pull/961#issuecomment-323207051 -- one fix is to use that PR to normalize coordinates to 0,0,0 instead of ECEF coordinates, which end up using a lot of digits.

**Comment by ssampang** [comment]
It's not from meshlab. I'm aware that meshlab has the same problem, but this particular model has the issue in CloudCompare as well. 

Also, as you imply, the issue shows up when the model is registered in true world coordinates (ecef or lla). In this case, the model is already normalized.

**Comment by ManishSahu53** [comment]
Make sure you have added sensor details in the openMVG for your DJI becuase its not already added in database. Bowl (curve) effect can be be removed if you do this.

**Comment by pmoulon** [comment]
> the model was not centered on the origin

It can be due to the BA and usage of very far points.

Would you mind to share your dataset, or only the necessary data (no images, but only the *.feat, the match file and the sfm_data.json file)

**Comment by ssampang** [comment]
Sure, here's the dataset: https://drive.google.com/file/d/1JN6mReE49rRJpLflPVoJ00Rq5zeZ7udy/view?usp=sharing

**Comment by pmoulon** [comment]
I just tried your dataset.
Default setting for the Sequential pipeline with `-f 1920`

And the result is this one:
![snapshot00](https://user-images.githubusercontent.com/3235050/34552134-95936a90-f0d4-11e7-9391-6bf0ce05299c.png)
I did not observe any binning effect (I looked from many camera angle within meshlab).
[robust_colorized.ply.zip](https://github.com/openMVG/openMVG/files/1602571/robust_colorized.ply.zip)
