### ISSUE TITLE
How are the SIFT and float AKAZE descriptors layout in the binary .desc files?

### ISSUE THREAD

**Issue by pogilon** [openMVG/openMVG#1125]

**Comment by pmoulon** [comment]
A classic binary serialization is used:
see here to use the existing API functions https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/openMVG/features/descriptor.hpp#L165

https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/openMVG/features/descriptor.hpp#L190
