### ISSUE TITLE
Qns: openMVG ComputeMatches Robust_model_estimation

### ISSUE THREAD

**Issue by irenekaea** [openMVG/openMVG#1126]
I am trying to reproduce openMVG main_ComputeMatches.cpp in my own program but I am getting segmentation fault whenever I called Robust_model_estimation function. Anyone can help me please? Thanks

```    using RegionProvider = openMVG::sfm::Regions_Provider;
    // Load and store all regions in memory
    std::shared_ptr<RegionProvider> regions_provider = std::make_shared<RegionProvider>();

    // Show the progress on the command line
    C_Progress_display progress;

    if(!regions_provider->load(sfm_data_, matchesDirectory_, region_type, &progress))
    {
      ERROR_MSG("Error: Invalid region", std::string{"ImageList.cpp - ComputeMatches()"});
    }
    
    // If matches already exists reload them (Not doing it first)
    // Else compute putative matches using exhaustive pairwise matching
    
    // From matching mode compute the pair list that have to be matched
    openMVG::Pair_Set pairs; // Computing putative matches
    pairs = openMVG::exhaustivePairs(sfm_data_.GetViews().size());
    // Photometric matching of putative pairs
    collectionMatcher->Match(sfm_data_, regions_provider, pairs, map_PutativesMatches, &progress);
    // Export putative matches
    if(!Save(map_PutativesMatches, std::string{"../release/matches.putative.bin"}))
    {
      ERROR_MSG("Error: Failed to save putative matches", std::string{"ImageList.cpp - matches.putative.bin"});
    }

    using FeaturesProvider = openMVG::sfm::Features_Provider;
    std::shared_ptr<FeaturesProvider> features_provider = std::make_shared<FeaturesProvider>();

    if(!features_provider->load(sfm_data_, matchesDirectory_, region_type))
    {
      ERROR_MSG("Error: Failed to load features", std::string{"ImageList.cpp - features_provider"});
    }

    using ImageCollectionGeometricFilter = openMVG::matching_image_collection::ImageCollectionGeometricFilter;
    std::unique_ptr<ImageCollectionGeometricFilter> geom_filter_ptr(new ImageCollectionGeometricFilter(&sfm_data_, regions_provider));

    openMVG::matching::PairWiseMatches map_GeometricMatches;

    geom_filter_ptr->Robust_model_estimation(
      openMVG::matching_image_collection::GeometricFilter_FMatrix_AC(4.0, imax_iteration)
      , map_PutativesMatches, false, distance_ratio, &progress);  // False is for the guided matching
```

**Comment by irenekaea** [comment]
So I went to the gdb and found this, can anyone help me on how to fix it? the function generatefeatures() will work fine if robust_model_estimation ain't called tho.

` - Generating features and descriptions
55	    for(const auto& elem : sfm_data_.views)
(gdb) next
57	      const openMVG::sfm::View * view = elem.second.get();
(gdb) next
58	      const std::string feat = stlplus::create_filespec(matchesDirectory_, stlplus::basename_part(view->s_Img_path), "feat");
(gdb) next
59	      const std::string desc = stlplus::create_filespec(matchesDirectory_, stlplus::basename_part(view->s_Img_path), "desc");
(gdb) next
61	      if(!stlplus::file_exists(feat))
(gdb) next
63	        openMVG::image::ReadImage(view->s_Img_path.c_str(), &imageGray);
(gdb) next
64	        if(image_describer->Describe(imageGray, region_type))
(gdb) next

Program received signal SIGSEGV, Segmentation fault.
0x00000000005e20d0 in void Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<float, -1, -1, 1, -1, -1>, Eigen::Matrix<float, -1, -1, 1, -1, -1>, Eigen::internal::assign_op<float, float> >(Eigen::Matrix<float, -1, -1, 1, -1, -1>&, Eigen::Matrix<float, -1, -1, 1, -1, -1> const&, Eigen::internal::assign_op<float, float> const&) ()
`

**Comment by pmoulon** [comment]
Seems like related to a compilation flag related to the CPU intrinsics.
Can you try with the `develop` branch?
- the compilation flag must not be inherited for this branch.

**Comment by irenekaea** [comment]
I've tried using the develop branch and tried using eigen 3.2 instead but none of them solve the problem regarding the seg fault of dense assignment loop.

**Comment by pmoulon** [comment]
@irenekaea How do you link OpenMVG to your program (by using cmake)?

As you see here some person experienced the same problem with the master branch, but not with the develop branch (https://github.com/openMVG/openMVG/issues/1074#issuecomment-333708002)

**Comment by irenekaea** [comment]
Yes I link using cmake, I will try again.

**Comment by irenekaea** [comment]
Yes I link using cmake, I will try again.

**Comment by irenekaea** [comment]
So I've tried using internal eigen from the develop and master branch both. It solved the eigen segmentation fault issue, but then another issue arises where it seg fault when i use openMVG::image::Image<unsigned char> for the function openMVG::image::ReadImage to read a colored image. I referred to issue #1086 and using the develop branch does not solve the program. I've tried ReadImage using openMVG::image::RGBColor, it is working well though but I want to use image_describer which only takes in unsigned char. I used openMVG::image::Convert to convert between RGBColor and unsigned char but this will cause image_describer->Describe to seg fault.

**Comment by irenekaea** [comment]
So I went to gdb and found the line that causing the seg fault is at line 380 of image_io.hpp 

`openMVG::image::ReadImage<unsigned char> (path=0x79c6f0 "../images/test.jpg", 
    im=0x7fffffffd9c0) at /usr/local/include/openMVG/image/image_io.hpp:368
368	{
(gdb) step
369	  std::vector<unsigned char> ptr;
(gdb) next
371	  const int res = ReadImage( path, &ptr, &w, &h, &depth );
(gdb) step
372	  if ( res == 1 && depth == 1 )
(gdb) step
377	  else if ( res == 1 && depth == 3 )
(gdb) step
380	    RGBColor * ptrCol = reinterpret_cast<RGBColor*>( &ptr[0] );
(gdb) step
std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (
    this=0x7fffffffd880, __n=0) at /usr/include/c++/5/bits/stl_vector.h:780
780	      { return *(this->_M_impl._M_start + __n); }
`

still trying to figure out why

**Comment by irenekaea** [comment]
So I found out the problem lies in line 384 of image_io.hpp which caused me unable to read jpg into Image<unsigned char>, now I'm going to convert pixel type manually to see what's the cause. 

`73	        openMVG::image::ConvertPixelType(imageGray, &convert);
(gdb) continue
Continuing. Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xc61002) at malloc.c:2951
2951	malloc.c: No such file or directory.
`

**Comment by pmoulon** [comment]
Did the unit test ran fine on your computer?

Tip: Do cmake with `-DOpenMVG_BUILD_TESTS=ON` and run `make`, and `make test`

**Comment by irenekaea** [comment]
Yes I ran but all passed, I think this only happens when used as third party lib?

**Comment by pmoulon** [comment]
So if test ran fine, it's definitively just a story of compilation flag.

If you want give a try to disable all optimization in OpenMVG you can use this flag for cmake:
`-DTARGET_ARCHITECTURE=generic`

I will look on my side too next week if I can reproduce your error.

**Comment by irenekaea** [comment]
I'll try again. Thanks !

**Comment by irenekaea** [comment]
I've just tried, it's my compilation issue, the develop branch is okay. I followed what  #1086 and solved the problem. Thank you so much!!!!

**Comment by irenekaea** [comment]
Previously the test have some issue because i used external eigen though but after changing to internal eigen it's fine. Thank you!

**Comment by pmoulon** [comment]
Despite you could hit a compilation flag issue, the best is to always use the same Eigen version for external   and your project. Have fun!
