### ISSUE TITLE
How to handle EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION_INITIALIZER_LIST

### ISSUE THREAD

**Issue by saedrna** [openMVG/openMVG#1127]
Hi,

I am upgrading to the current version of openMVG in windows for MSVC. And I have encountered a major problem with `EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION_INITIALIZER_LIST` as below,

- first, I have in my code some structure like `std::vector<Vector2d>`, and as this is specialized in openMVG, it won't compile. The code will compile only if I put the openmvg header to the top of all includes.
- second, even it compiles, it also create problems at runtime, there is an assertion failure in Eigen for aligned free

```
/** \internal Frees memory allocated with aligned_malloc. */
EIGEN_DEVICE_FUNC inline void aligned_free(void *ptr)
{
  #if (EIGEN_DEFAULT_ALIGN_BYTES==0) || EIGEN_MALLOC_ALREADY_ALIGNED
    std::free(ptr);
  #else
    handmade_aligned_free(ptr);
  #endif
}
```

I am not quite sure if it's the Eigen issue of openMVG issue. My environment is below

- OS : windows 10
- Platform: MSVC 2017 x64
- Eigen: latest 3.3.4
- openMVG: latest master

Han

**Comment by saedrna** [comment]
I think I have figured out where is the problem. It maybe related with 'EIGEN_MAX_ALIGN_BYTES' . For AVX it is defined to 32, which is how my openmvg compiled. But my app is not with AVX. I will test this when I am free.

**Comment by pmoulon** [comment]
Any news about that?

You can also compile OpenMVG without CPU intrinsic instruction by using that in the CMAKE step: `-DTARGET_ARCHITECTURE=generic`

**Comment by pmoulon** [comment]
@saedrna Any feedback?

**Comment by saedrna** [comment]
@pmoulon , I forgot to update this...

My feeling was right, this is because the new version has used AVX, and I just disable AVX in cmake-gui and recompile, it works for MSVC 2017 x64. And no problem with the Eigen specialization, because in this way, Eigen default to use the same allocator as vector or other stl containers.

By the way, the newer version really compiles much faster!!!

**Comment by pmoulon** [comment]
> By the way, the newer version really compiles much faster!!!

Yep, we work hard on this!
