### ISSUE TITLE
Create bundler

### ISSUE THREAD

**Issue by HelliceSaouli** [openMVG/openMVG#1129]
Hello. 
is it possible to create a bundler starting with images and their camera parameters ( vision.Middelburry dino dataset)

**Comment by pmoulon** [comment]
Sure, it's easy as just providing the K matrix or the pixel focal lenght to the openMVG_main_SfMInit_ImageListing binary.

See the -k option for the K matrix.
or the -f option for the pixel focal length (the focal used in the K matrix).

**Comment by HelliceSaouli** [comment]
Thank you for the quick reply sir.
my next questions are : 
1- can I use this bundler in MVE
2-what is the coordinate system openMVG outputing. is scene coordinate system. and how did you hundled the middelburry evaluation because the ask the output must be in the scene coordinate they offer .

**Comment by pmoulon** [comment]
1. Yes, see https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/
2. Every SfM reconstruction is up to scale. Feel free to compute the 6DoF registration to fit the OpenMVG reconstruction to the Middleburry coordinate system. Just compute the rigid transform that make the corresponding camera position as close as possible

**Comment by HelliceSaouli** [comment]
I didn't get the second point. Can you please elaborate more on it ?

**Comment by pmoulon** [comment]
Since I did not get it. Feel free to you elaborate your second point if this answer is not good.

I mean if you want to compute how accurate the calibration is you can compute the camera distance once you fit one reconstruction into the other one coordinate system.

I mean you have two camera position set.
The one from openMVG, the one from Middleburry.
You can compute by least square the rigid transformation to fit one to the another coordinate system. Then you compute the inter camera distance and obtain a metric to see how far form the MiddleBurry Ground Truth your are.

**Comment by HelliceSaouli** [comment]
ok I get it but this is not what I want. I want to do this : [structure from known pose](http://openmvg.readthedocs.io/en/latest/software/SfM/ComputeStructureFromKnownPoses/) the problem is it requires initial features and i don't have it. I want to give the sofware the ground truth camera matrices K and [R|t] and it compute for me features (full bundler)

**Comment by pmoulon** [comment]
You can compute the features with OpenMVG.

1. Use the openMVG API to setup the initial system (Views, Intrinsics, Poses)
2 Compute the features
3 Compute the matches
4 Triangulate the pairwise matching thanks to `openMVG_main_ComputeStructureFromKnownPoses`

**Comment by HelliceSaouli** [comment]
Done this and it worked fine . now i'm trying to convert to mve format and i'm not getting the prebundle.sfm file is this supposed to happen?

**Comment by HelliceSaouli** [comment]
I Fixed the problem seems like I messed up when I created matches because I played with parameters.
Note you have to update some of your documentation to match the tutorial.py otherwise first comers like me will get a bit confused

**Comment by pmoulon** [comment]
Feel free to point what was wrong in the documentation in order to improve it!
