### ISSUE TITLE
[Question] Export as NVM

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1131]
Can I export data from openMVG as NVM for hpmvs (https://github.com/alexlocher/hpmvs) ?

**Comment by pmoulon** [comment]
Sure, you have to use the main_openMVG2NVM binary to convert the OpenMVG project to a NVM project https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2NVM.cpp

**Comment by Ntweat** [comment]
Thank you!!
