### ISSUE TITLE
Update to use bearing vector instead of point position

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1133]
Update OpenMVG to use bearing vectors (directional feature ray) rather than feature point positions.

This update bring plenty of novelties:

[cameras]
- Fix a sign error in the Spherical model (reconstruction was flipped along the X axis)
- Update some the bearing vector computation function to deal with matrices instead of vector (ability to handle many point at once)
    
[multiview] Update multiview relative pose computation module to use bearing vectors
  - multiview::MotionFromEssential exports now Poses instead of [R|t] couples (less object to manipulate).
  - update fundamental::kernel::EncodeEpipolarEquation to use bearing vectors.
  - Code factorization for fundamental::kernel::EncodeEpipolarEquation.
  - Update the FivePoint relative pose estimation to use bearing vectors.
  - Update some multiview function to use Mat2X or Mat3X instead of Mat in order to have a more explicit API.
- estimate_Rt_fromE => RelativePoseFromEssential
    
[sfm]
- Update triangulation routines in order to use bearing vector and camera poses.
- TriangulateNViewAlgebraic is faster than before (reduced size of the A matrix)
    
[samples]
 - Update the samples robust_essential_spherical to use either the 8point or the 5point essential algorithm to compute the essential matrix.
    
[misc.]
- Essential matrix ACKernelAdaptorEssential uses FivePointSolver instead of FivePointKernel.

**The main outcome of this is a more expressive API and the fact that now Incremental SfM can be performed with spherical images!**

**Comment by happyfrank** [comment]
Hello,  @pmoulon When OpenMVG v1.3 gonna release? We are very looking forward to seeing it. ^v^

**Comment by pmoulon** [comment]
@happyfrank OpenMVG v1,3 is released. Have fun!
