### ISSUE TITLE
[Question] Using snapshot of a model

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1136]
Hi 

I am trying to recreate a model by taking snapshots of it and passing it to openMVG. 
For focal length, I am using f =1.2*max(w,h)
But it is never able to converge. 
Any ideas how to fix it? I have tried with over 900 images as well

**Comment by pmoulon** [comment]
Did you check if you have feature matches between your image collection?
- you can use openMVG_main_exportMatches binary to see them

If you don't have nice matches you can extract more point per image by using the -p option on main_ComputeMatches.

Else feel free to share a subsection of your image dataset to let us have a look.

**Comment by Ntweat** [comment]
Thank I will try it 👍
