### ISSUE TITLE
How to determine the weight of GPS？

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#1138]
Hi @pmoulon , I have a question about  setting the weight of  GPS  in the process of bundle adjustment.
For example , when the accuracy of the image's GPS is about 5 to 10 meters,  what values  should be  set for the weights of the images's GPS?

**Comment by pmoulon** [comment]
@hcjghr Do you mind to provide an answer here?

You can set the weight relative to the accuracy. I mean that latitude and longitude are certainly more accurate than the altitude and so you can set your weight to reflect this situation.
