### ISSUE TITLE
Cannot open input file in Windows-AMD64-Release\Release\*.lib

### ISSUE THREAD

**Issue by HaiDang2001VN** [openMVG/openMVG#1140]
Hello @pmoulon , I cloned the openMVG yesterday and make it with CMake (I chose to build additional `BUILD_EXAMPLES`, `BUILD_SHARED` and `USE_OPENCV`, `USE_OCVSIFT`, `USE_OPENMP`).
Today, I build it with Visual Studio 2017 (ver 15) and Compiler report the Error List to me:
[https://drive.google.com/file/d/1YkXYVGqezq1cM6GKCkNBBfHS0ENwy3yo/view?usp=sharing](url)
I have searched and found out that the `LNK1120` errors followed `LNK2001` and `LNK2019`, which caused by the undefined symbol in `.obj` file. So the error here just all of `LNK1181` errors, but I don't know how to fix it.
Could you please help me with this, @pmoulon ?
Thanks in advance.

**Comment by pmoulon** [comment]
Hi see link error.
Please can you unable the `BUILD_SHARED`? (this mode is only supported on Linux for the moment.)

**Comment by pmoulon** [comment]
Closed due to inactivity. @HaiDang2001VN Feel free to re-open the issue.
