### ISSUE TITLE
Trying to build openMVG under OS X 10.8 without success

### ISSUE THREAD

**Issue by SchmollTroll** [openMVG/openMVG#1141]
Hi there,

I'm trying to build openMVG but unfortunately without success by following the build instructions for OS X.
Additionally I installed the ports corresponing to the linux apt-get list (port install libpng jpeg tiff xorg-libXxf86vm xorg-libXi xorg-libXrandr graphviz).
Since I'm not very familiar with these build outputs I attached it here.

Thanks for your work!!!

[openMVG_Build-Log.txt](https://github.com/openMVG/openMVG/files/1457768/openMVG_Build-Log.txt)

**Comment by pmoulon** [comment]
The error seems related to the fact that your compiler cannot locate `#include <type_traits>`

@rperrot Any idea?

```
2017-11-09 14:22:06.590 xcodebuild[4010:4503]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-5069/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:76
Details:  Failed to load dependencies output contents from ``/Users/dimo/Downloads/2017-11-09/TEST/openMVG_Build/third_party/ceres-solver/internal/ceres/openMVG.build/Release/ceres.build/Objects-normal/x86_64/block_random_access_dense_matrix.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “block_random_access_dense_matrix.d” couldn’t be opened because there is no such file." UserInfo=0x7fb3bcf0b080 {NSFilePath=/Users/dimo/Downloads/2017-11-09/TEST/openMVG_Build/third_party/ceres-solver/internal/ceres/openMVG.build/Release/ceres.build/Objects-normal/x86_64/block_random_access_dense_matrix.d, NSUnderlyingError=0x7fb3bec02100 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/dimo/Downloads/2017-11-09/TEST/openMVG_Build/third_party/ceres-solver/internal/ceres/openMVG.build/Release/ceres.build/Objects-normal/x86_64/block_random_access_dense_matrix.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fb3bdb559f0>{name = (null), num = 14}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
In file included from /Users/dimo/Downloads/2017-11-09/TEST/openMVG/src/third_party/ceres-solver/internal/ceres/block_evaluate_preparer.cc:34:
In file included from /Users/dimo/Downloads/2017-11-09/TEST/openMVG/src/third_party/ceres-solver/internal/ceres/block_sparse_matrix.h:38:
In file included from /Users/dimo/Downloads/2017-11-09/TEST/openMVG/src/third_party/ceres-solver/internal/ceres/sparse_matrix.h:38:
In file included from /Users/dimo/Downloads/2017-11-09/TEST/openMVG/src/third_party/ceres-solver/include/ceres/internal/eigen.h:34:
/Users/dimo/Downloads/2017-11-09/TEST/openMVG/src/third_party/eigen/Eigen/Core:273:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
```

**Comment by rperrot** [comment]
Could you please send me some informations ? 
-> Which OS version 10.10 ? 10.11 ? 10.12 ? 
-> Which openMVG version ? official 1.2 or develop ?

**Comment by rperrot** [comment]
Note, I can't reproduce your issue on latter version of OSX (tried the same compilation line). Maybe compiler is too old (no c++11 support ?) or cmake does not generate correct includes ?

**Comment by SchmollTroll** [comment]
Thaks for your answers, I try to give you all information I have (or better: know  :-P)

> Which openMVG version ? official 1.2 or develop ?
I think it's the official one. I get it with "git clone --recursive https://github.com/openMVG/openMVG.git"

> Does it compile with standard make (ie: without -G Xcode ?)
No, I get the following error lines:
[ 35%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/block_evaluate_preparer.cc.o
In file included from /Users/dimo/Downloads/2017-11-15/OpenMVG/openMVG/src/third_party/ceres-solver/internal/ceres/block_evaluate_preparer.cc:34:
In file included from /Users/dimo/Downloads/2017-11-15/OpenMVG/openMVG/src/third_party/ceres-solver/internal/ceres/block_sparse_matrix.h:38:
In file included from /Users/dimo/Downloads/2017-11-15/OpenMVG/openMVG/src/third_party/ceres-solver/internal/ceres/sparse_matrix.h:38:
In file included from /Users/dimo/Downloads/2017-11-15/OpenMVG/openMVG/src/third_party/ceres-solver/include/ceres/internal/eigen.h:34:
/Users/dimo/Downloads/2017-11-15/OpenMVG/openMVG/src/third_party/eigen/Eigen/Core:273:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
make[2]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/block_evaluate_preparer.cc.o] Error 1
make[1]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/all] Error 2
make: *** [all] Error 2

But here I see that ceres-solver seems to be needed. Ceres-solver refused to build with MacPorts - I opened a ticket there.

> Maybe compiler is too old (no c++11 support ?)
This seems to be checked by cmake  ( -- Checking for C++11 compiler / -- Checking for C++11 compiler - available) but I also tried to modify the CMakeLists.txt with this line "set(CMAKE_CXX_FLAGS "-stdlib=libc++")" after the "cmake_minimum_required" - without success.


That said please don't spend too much time for this - I'll lift one of my Macs to a newer OS and try this again. Thanks and best regards...

**Comment by rperrot** [comment]
```That said please don't spend too much time for this - I'll lift one of my Macs to a newer OS and try this again. Thanks and best regards...

Ok, thanks for your feedback. Tell us if it works on newer platform.

**Comment by pmoulon** [comment]
@SchmollTroll Any success on your updated system?

**Comment by SchmollTroll** [comment]
Sorry for being late with my answer.
I've updated to 10.11 ElCapitan and for now it seems it build ok, the only thing needed was cmake via MacPorts.
So, thanks for your great work and best wishes for the new year :-)

**Comment by pmoulon** [comment]
Can you close the issue?

**Comment by SchmollTroll** [comment]
Closed.
