### ISSUE TITLE
Why does the coordinates shift from camera position?

### ISSUE THREAD

**Issue by s-wtnb** [openMVG/openMVG#1142]
![default](https://user-images.githubusercontent.com/25291845/32638421-7e7e6d84-c602-11e7-88d2-e319e562f634.jpg)

This is an image of enlarged point of cloud_and_poses.ply.
Point cloud coordinates are shifted from the camera position with or without GPS information.
The same result for master and develop branch was.

[cloud_and_poses.zip](https://github.com/openMVG/openMVG/files/1459757/cloud_and_poses.zip)

**Comment by pmoulon** [comment]
The point cloud seems ok:
![image](https://user-images.githubusercontent.com/3235050/32640795-3e4e5b8a-c57f-11e7-823e-0e9246c0820f.png)

In order to understand more why the point cloud is shifted so much, perhaps you can share the features, the matches and the sfm_data.json.

Can you elaborate about the SfM pipeline you used and settings (Sequential, Global)?

**Comment by s-wtnb** [comment]
files other than images
https://drive.google.com/open?id=1j7ya6FLyzfMjdPeogu6o1cCriSZ5yo8x

```
openMVG_main_SfMInit_ImageListing -i -d -o (-P)
openMVG_main_ComputeFeatures -i -o -m AKAZE_FLOAT (-u)
openMVG_main_ComputeMatches -i -o
openMVG_main_IncrementalSfM -i -m -o (-f ADJUST_ALL / NONE)
```
() were tested, but everything moves.

**Comment by pmoulon** [comment]
Can you share me the sfm_data.json without pose prior information?
- openMVG_main_SfMInit_ImageListing -i -d -o 

In the archive I see only the one with pose prior.

**Comment by s-wtnb** [comment]
`openMVG_main_SfMInit_ImageListing -i -d -o`
[sfm_data.zip](https://github.com/openMVG/openMVG/files/1473472/sfm_data.zip)

Camera is DJI FC 550, so I add "DJI;FC 550;17.3" to sensor_width_camera_database.txt and use it.

**Comment by pmoulon** [comment]
![snapshot00](https://user-images.githubusercontent.com/3235050/34553309-8feaeefe-f0db-11e7-9e88-c1695514c9d6.png)

Reconstruction using `openMVG_main_IncrementalSfM -i -m -o`on your last sfm_data.json ran fine for me.

**Comment by s-wtnb** [comment]
Thank you for reconstruction.
I checked the data, but the camera position still seems to be shifted.
The position of the camera should overlap on the point cloud if it is true.

![reconstruction](https://user-images.githubusercontent.com/25291845/34600389-91787506-f23a-11e7-97e0-ebd3f69abbef.jpg)

**Comment by pmoulon** [comment]
How do you know the GT camera position?
The point cloud look nice, so I don't think the cameras poses are as wrong as you said.

Did you try to register the last reconstruction I made to your image GPS position? This way we will see if there is a big shift or not.
