### ISSUE TITLE
Bad MSVC preprocessor definition /bigobj

### ISSUE THREAD

**Issue by rwiesenfarth** [openMVG/openMVG#1146]
Compiling OpenMVG on Windows with MSVC creates a compiler command line including '/D "/bigobj"' instead of the intended '/bigobj'

Although the build succeeds, IntelliSense marks the first char in every .cpp file with an error (see attachment).

I have a working fix for this and will provide a pull request.

![openmvg_bigobj_error](https://user-images.githubusercontent.com/21051884/32732731-c4001dfc-c88d-11e7-8fb6-5f75f1b3a37e.png)

**Comment by pmoulon** [comment]
I took a deeper look and in fact the /bigobj is needed only in Debug mode for the target openMVG_sfm and openMVG_matching:

I'm testing it right now there:
https://github.com/openMVG/openMVG/commit/b81a36cdb46a45525cfc3a99fad7802f81b2655b#diff-51a7011e2497130a3d10c187652e3772R46
https://github.com/openMVG/openMVG/commit/b81a36cdb46a45525cfc3a99fad7802f81b2655b#diff-c4e7d384906636d63dabada049b55348R42

**Comment by pmoulon** [comment]
Can be closed since this issue is now fixed by https://github.com/openMVG/openMVG/commit/c054265a0d2ad22fd87d6bdb2f0cb276e8ac079c
