### ISSUE TITLE
[software/ui]Adjacency matches viewer

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1153]
Hi,
    Thanks for your precious time and impressive work. By clicking on a pair one can see the images and the matches, now, I want to zoom/scaling these matches, so the matching results can be seen more concretely. Any suggestion?
    Thanks in advance.

Sherman

**Comment by pmoulon** [comment]
You can use the binary exportMatches. It will export pairwise SVG file that you can open with Inkscape or any Internet viewer (chrome, mozilla...). You will be able to zoom in those individual matches view.

BTW, you can also help us to add functionality to the Adjacency matches viewer to add the zoom feature ;-)

**Comment by learnmano** [comment]
Thanks very much for replying so quickly, I want to add the zoom feature, but I checked the code and found that it's displayed as a .svg file in Qt. My idea is dragging an area using the mouse and the selected area become bigger, so we can see more detailed matches. The problem is that I don't know how to choose the matches in the selected area. 
Any suggestions?
Thanks.
Sherman

**Comment by pmoulon** [comment]
I'm not a QT expert, but for sure you can inherit from the view and implement a custom mouse selection.

**Comment by learnmano** [comment]
Thanks for your reply. I got something done by myself, and as you suggested, I implement my own  custom mouse selection and display the match results using Qt features.
Problem solved, thanks very much.
Sherman
