### ISSUE TITLE
Error exists when using the output of openMVG to PMVS

### ISSUE THREAD

**Issue by 945540968** [openMVG/openMVG#1158]
After i transformed the output of openMVG into PMVS, i ran PMVS. And then, i tied to finish texture mapping using meshlab. Unfortunately, i failed......
But i didn't know why? there existed no problem when i ran the program !
Then i used a software called VisualSFM to finish dense reconstruction, and used meshlab to do texture mapping. Finially, i succeed! 
So i guess the problem exists in the PMVS's input, which is transfomed from openMVG to PMVS.
I compared the result of openMVG->PMVS and the result of VisualSFM's  dense reconstruction, then i find there exists a constant value shift in rotate matrix.
Can anybody help me?

**Comment by rperrot** [comment]
Having a shift in rotate matrix is not an issue.

It's an issue if relative orientation between cameras is largely different between sfm softwares. 

What's wrong with PMVS ? no output ? segfault ? weird result ?

**Comment by 945540968** [comment]
I don't know why i can't finish dense reconstruction.
The result VisualSFM:
![fy6d9_e6 lb6d cto4576v](https://user-images.githubusercontent.com/33658092/33227137-97e01f6c-d1d7-11e7-8a01-7c9a5e82b495.png)
The result openMVG->PMVS:
![6pk_pxkzflqx hecum2 yv](https://user-images.githubusercontent.com/33658092/33227141-b43e026e-d1d7-11e7-8880-f4b5044cd7ea.png)
I find some difference when i try show the position of these cameras using meshlab.
What's more, there exists some difference in list.txt file.
this is the list.txt file of VisualSFM(it shows the path of image in “visualize” folder):
[list.txt](https://github.com/openMVG/openMVG/files/1502803/list.txt)
this is the list.txt file of openMVG->PMVS(it shows the path of image in another folder):
[list.txt](https://github.com/openMVG/openMVG/files/1502804/list.txt)
My discover are above all.

**Comment by pmoulon** [comment]
For me the two reconstruction (SfM and point cloud) looks correct.

If meshlab crash it is perhaps because it does not find the images.
Did you try to look if meshlab find the image for each raster for the OpenMVG meshlab project?

**Comment by 945540968** [comment]
Hi,pmoulon! Is list.txt produced in the process of transforming the output of openMVG into openMVS?
I don't know why openMVG's list.txt file show the path of another folder, while the VisualSFM's show the path of "visuallize" folder. Is the difference important?

**Comment by pmoulon** [comment]
Hi,

list.txt is just a file that tell in which order the camera link to an image. So you can choose the convention you want, if it point the right image.

Note:
list.txt is not produced for OpenMVS, since OpenMVS have its own `.mvs` format.

**Comment by 945540968** [comment]
Hi pmoulon, i have two questions:
1、After i used openMVG_main_openMVG2PMVS, the program produced the list.txt file as following:
![image](https://user-images.githubusercontent.com/33658092/33361311-7efce686-d512-11e7-9930-918480f7238e.png)
Can you tell me what the second and third columns are?
2、I can't finish texture mapping using meshlab with your list.txt file like above. But after i change the list.txt file into following, i succeed!
![image](https://user-images.githubusercontent.com/33658092/33361470-3e3ea304-d513-11e7-8947-ebe365f1db44.png)
I don't know why, is the interface between openMVG and PMVS improper?

**Comment by 945540968** [comment]
Need i modify your program to produce a proper list.txt file accepted by meshlab?

**Comment by pmoulon** [comment]
I already imported and processed OpenMVG scene within Meshlab with success.
If you want use a project with Meshlab please use the openMVG2Meshlab exporter! and not the PMVS one.

**Comment by Datoow** [comment]
Dear Owner，could you tell us where we can learn how to use the openMVG2Meshlab exporter, please？

**Comment by pmoulon** [comment]
You can run the command line and the various parameter will show up.
When used It will create a meshlab project file (mpl).

**Comment by Datoow** [comment]
Wow, thanks for your response. After we try, it showed, 
![image](https://user-images.githubusercontent.com/32037503/33363031-954d270a-d519-11e7-8d04-37afc60a9403.png)
Then in outdir, I couldn‘t find any files. 
Did we run this command line by mistake?

**Comment by pmoulon** [comment]
Sorry for my late answer.

The command line seems ok.

You must be aware that you can tweak the frustum size in meshlab.
