### ISSUE TITLE
Exception in ComputeStructureFromKnownPoses

### ISSUE THREAD

**Issue by roby23** [openMVG/openMVG#1160]
Hello, I came up with a problem in ComputeStructureFromKnownPoses if I run it without provided matching. Just:

`openMVG_main_ComputeStructureFromKnownPoses.exe -i <input_sfm_data> -o <output_sfm_data> -m <matches_dir> -b`

When I run it on a my dataset I get a "vector subscript out of range" exception.
I did some debug and it happens in guided_matchng.hpp, line 338. 
Basically the bucket index is out of range because l_pt results in {inf, -inf} (line 329). I don't know why it happens.
I attach my matches folder and the sfm_data.json, just change the root_path in the sfm_data.json file to try to replicate the error.

[dataset.zip](https://github.com/openMVG/openMVG/files/1506012/dataset.zip)

**Comment by pmoulon** [comment]
By debugging the :footprints:, it seems like the undistortion of a given point is not correct and so the algorithm does not handle it.

Here some fix you can try:
1. only use the Radial3 camera model for your scene,
2. Test if the undistorted point is valid (quick fix)
3. Fix the specific case where the undistortion is not working.

Here how to perform the point 2 (the quick fix you can try).
You can change in `guided_matching.hpp`
`if (line_to_endPoints(line, widthR, heightR, x0, x1))`
to
 `if ((line.array().isFinite() == 1).all() && line_to_endPoints(line, widthR, heightR, x0, x1))`

and it will run fine:
![snapshot00](https://user-images.githubusercontent.com/3235050/33300447-30508222-d3a5-11e7-939a-f352aa41ec24.png)

Feel free to help for a long term fix (solution 3)

**Comment by pmoulon** [comment]
@roby23 Any feedback?

**Comment by roby23** [comment]
Yes, I just used the quick fix (2) and now it works. 
Any hints on the long term fix? Where should I test if the undistortion is not working?

Many thanks

**Comment by pmoulon** [comment]
Long term fix:
- see if we can improve the undistortion of this camera model?
  -> do you want to help on this....
  - we can also imagine that one day this function return an optional Vec2 point. So we can test success or failure and use the undistorted point in case of success.

**Comment by pmoulon** [comment]
Closed due to inactivity.
@roby23 Feel free to re open if you want to help on this.
