### ISSUE TITLE
Using Pose Priors with Ground Control

### ISSUE THREAD

**Issue by BigAloz** [openMVG/openMVG#1161]
Pierre,

I have an issue when using ground control with Pose Priors

1. bool Bundle_Adjustment_Ceres::Adjust   -within this function

A transformation is computed to improve the conditioning
i.e.
 if (options.use_motion_priors_opt && sfm_data.GetViews().size() > 3)
...etc

In this function two transformation are computed
          // Apply the found transformation to the SfM Data Scene
          openMVG::sfm::ApplySimilarity(sim, sfm_data);

 Then another one after the centroid is found
        openMVG::sfm::ApplySimilarity(sim_to_center, sfm_data, true);
 
The first transformation does not transform the Priors or the control points
- I understand why the Priors aren't transformed as they are transformed seperately in the function.

However the Control Points aren't and this make the adjustment fall over.
I have had to add a seperate additional transformation to account for this.
for (auto & iterControlPoint : sfm_data.control_points)
{
	iterControlPoint.second.X = sim(iterControlPoint.second.X);
}

I am not sure whether I have found a bug or whether I am just doing something wrong (again).

Regards,

Alan

**Comment by pmoulon** [comment]
You're right it can bring confusion.

What about extending the API with an ENUM to replace the boolean in order to choose what is moved?

So this way you can fined tune what do you want to move (by combining them).

```
LANDMARK,
CONTROL_POINT,
POSE
```

**Comment by pmoulon** [comment]
@BigAloz Any comment regarding my suggestion?
