### ISSUE TITLE
[Question] Parameters for benchmarking

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1162]
Hi

I am trying to benchmark many sparse point tools such as openMVG, colmap, MVE, etc  along with dense point tools such as openMVS, SMVS, CMVS/PMVS, etc

I was wondering what parameters can I use for the benchmarking for both.

**Comment by pmoulon** [comment]
From OpenMVG (SFM side), you can only play with the pipeline and the matches (feature extraction presets).

Pipeline
- Incremental
- Global

Feature preset (ComputeMatches):
- NORMAL/HIGH/ULTRA

**Comment by Ntweat** [comment]
Sorry.

I meant to ask parameters for benchmarking.. Like number of camera pose estimates, completeness of model etc

**Comment by pmoulon** [comment]
You can take a look to the paper that perform benchmarking task...
https://github.com/openMVG/awesome_3DReconstruction_list#mvs---point-cloud---surface-accuracy

**Comment by Ntweat** [comment]
Thank you

**Comment by pmoulon** [comment]
SfM side:
- Number or camera
- position accuracy
- orientation accuracy (rotation)

MVS Side:
- surface completness
- proximity of the true surface
- ...

**Comment by Ntweat** [comment]
During a preliminary analysis, I am finding that incremental pipeline is giving more camera pose estimates than global. 

Why is that? 

Also, COLMAP is giving more accurate pose estimates than openMVG.  
I have sent a dataset, it has both the above points

**Comment by pmoulon** [comment]
I invite you to read [here](https://github.com/openMVG/openMVG/issues/1037#issuecomment-324448137) about the difference between incremental SfM and Global SfM

Which process did you use to compare the pose accuracy?
How much more accurate COLMAP is for your given dataset?
Did you check that if the number of feature is similar?
Are you sure you compare the SfM tools in the same settings (grouped vs. ungrouped intrinsics)?
  - I mean having the intrinsic grouped or not can lead to some differences depending of the camera settings you used.

I see nothing after your comment:
>I have sent a dataset, it has both the above points

**Comment by pmoulon** [comment]
Did you check if the pipeline have more or less the same of features extracted per image?

Please remember that cars are hard object to do in photogrammetry since they are not lambertian (reflective object are hard to handle).

**Comment by Ntweat** [comment]
I used the same SIFT parameters for all pipelines.  All of them gave more or less same features. 

openMVG Global and Incremental had the same features as the next stage (compute_matches) the pipeline changes. 

I know cars/vehicles are tough, I am very close to getting good results, with openMVG Incremental pipeline. The issues are only in few objects like the car I sent. Otherwise, openMVG Incremental is out performing COLMAP.
