### ISSUE TITLE
Odd problem when using openMVG as third party library and including headers relate to features

### ISSUE THREAD

**Issue by CanCanZeng** [openMVG/openMVG#1164]
my problem is like the problem in issue #1063

I use develop branch, the demo provided by opemMVG runs well, and I can compile and run main_SfMInit_ImageListing.cpp in my own project, but it cannot work for main_ComputeFeatures.cpp

I further find that if I include headers relate to features such as "openMVG/features/sift/SIFT_Anatomy_Image_Describer_io.hpp", problem happen, I cannot read sfm_data.json type file. In debug mode I find the problem may happen around openMVG_install/include/openMVG_dependencies/cereal/include/cereal/external/rapidjson/document.h line 947, bool IsString() const { return (data_.f.flags & kStringFlag) != 0; }.

I tried the method in #1154 , it still doesn't work. 

Can somebody help me?

**Comment by pmoulon** [comment]
Hi, Thanks for your feedback.
Can you tell me if you have a compilation issue or a running time issue?
Can you tell which platform are you using?

**Comment by CanCanZeng** [comment]
no compilation issue, and everything runs well if i do not include heads like SIFT_Anatomy_Image_Describer_io.hpp. 

I use Ubuntu14.04 and I compiled the project by cmake.

one more strang thing is that I can create a SfM_Data type data and compute features and save them in SfM_Data variable, just cannot read or write it from .json file even when I use openMVG as third party library and includes feature related head files.

by the way I added the -DTARGET_ARCHITECTURE=generic option when compiling openMVG

**Comment by CanCanZeng** [comment]
I use Ubuntu14.04 on a desktop and gcc 4.8.5, g++ 4.8.5

** OpenMVG version: 1.3.0
** Build Shared libs: OFF
** Build OpenMVG tests: ON
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- CEREAL: (internal)
-- EIGEN: 3.3.4 (internal)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.3 (external)
-- LIBPNG: 1.2.50 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: 0.107.8 (internal)
-- LEMON: 1.3 (internal)

**Comment by pmoulon** [comment]
Thank you for your complimentary information.
I will try to take a look to this during the coming days.

**Comment by pmoulon** [comment]
I tried to reproduce your problem but I did not got any runtime issue.
I compiled OpenMVG develop branch and setup it.
Then I create a file with the content of main_ComputeFeatures.cpp and compile it by using OpenMVG as a third party.
I was able to read an existing sfm_data.json and compute features for it.

**Comment by CanCanZeng** [comment]
OK，thank you for your reply, I'll try on other computers.

**Comment by CanCanZeng** [comment]
I found that this problem won't happen in other computer, then I compiled openMVG on my laptop again, I found this problem when I use cmake:
![webwxgetmsgimg](https://user-images.githubusercontent.com/26817559/33980268-1cea05e6-e0e3-11e7-852b-0d10fcb01593.jpg)
these two error are the only difference between my laptop and desktop.

**Comment by pmoulon** [comment]
It must be fixed in the master and develop branch now!
