### ISSUE TITLE
[Question] openMVG_main_ComputeFeatures upright 

### ISSUE THREAD

**Issue by s-wtnb** [openMVG/openMVG#1167]
need the upright option when processing photos taken with UAV facing the ground?

**Comment by pmoulon** [comment]
The upright option is more used in the case of a camera mounted of a car.
Since your UAV can rotate, I don't think using the option will help in your case.

**Comment by s-wtnb** [comment]
Is that the upright option can be used for photos with only one direction?

**Comment by pmoulon** [comment]
yes

**Comment by s-wtnb** [comment]
thanks!
