### ISSUE TITLE
Multiple build errors using vs2015

### ISSUE THREAD

**Issue by WeinaVenus** [openMVG/openMVG#1168]
Hi, I am trying to build OpenMVG using vs2015 on a windows 10 machine, I tried to get the code using git clone, ran submodule initializations. Cmake seems to be generating a decent solution folder, but however, when compiling, I get multiple compilation errors, mainly saying "typename cannot be used outside a template declaration" and "LINK: fatal error LNK1104:cannot open the file'..\..\Windows-AMD64-Release/Debug/openzMVG_features.lib'."
I wonder whether I am doing anything wrong here in the building process.

**Comment by Yannnnnnnnnnnn** [comment]
you should run the BUILD ALL first.

**Comment by Yannnnnnnnnnnn** [comment]
or you have to compile openMVG_feature first

**Comment by pmoulon** [comment]
@WeinaVenus Can you share the VS error log.

As you can see here the actual develop branch compiles fine on VS 2015/2017
https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.776

**Comment by WeinaVenus** [comment]
@Yannnnnnnnnnnn @pmoulon Thank you very much for your advice. It helped me a lot and solved the problem.
