### ISSUE TITLE
[Question] Cropped video frames

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#1169]
Hi

I am trying to use cropped video frames for openMVG pipeline.
How can it be done? 

Explanation:
If someone wants to create an object a neural network segments out the object and passes the images to openMVG. Images are not of same dimensions so I dont think I can use f=1.2*max(w,h)

**Comment by pmoulon** [comment]
By cropped did you mean:
- that you cut a video to frames
- that you cut a partial part of the image (it is not good for SfM because the resulting image does not follow the pinhole image assumption).

I think you can keep the original image, create the binary mask for your object using your neural network and then provide the focal length for each image (f=1.2*max(w,h)).
=> OpenMVG can support:
- a mask per image
- a different focal value per image

**Comment by Ntweat** [comment]
I am already cutting videos frame by frame.

The problem is that when creating a model, the object of interest is not clear. Example if I take a video of a toy, the openMVG/MVS pipeline creates the whole environment and the features on the toy are not clear.

One way I found was to crop the images before processing. This works brilliantly when we have the EXIF data of the images.   (Example the dataset I sent to you which works with incremental sfm) But can't work for video frames, as I don't have the EXIF data (Even manually putting EXIF data in the frames doesnt work).

**Comment by pmoulon** [comment]
When you don't have EXIF data you can specify an approximate focal length by using the option -f on `main_SfMInit_ImageListing`.
You can use 1.2*max(w,h) as a good approximation.

>Even manually putting EXIF data in the frames doesn't work).
It should, it certainly because you are not setting the right field (camera model, camera maker and focal length)

**Comment by Ntweat** [comment]
I have been using that option and works pretty well. 
The problem with cropped images is that all each image has a different (w,h)

I have used 1.2*max(w,h) even with scaled images (using the new dimensions) it always gives good results.

**Comment by pmoulon** [comment]
Feel free to modify main_SfMInit_ImageListing to apply the 1.2 focal rule to each image independently ;-)

**Comment by Ntweat** [comment]
Thanks!! 
Will try..
WHich will be easier editing main_SfMInit_ImageListing or editing the file it generates?

**Comment by pmoulon** [comment]
Both are easy:
- edit main_SfMInit_ImageListing,
- or do not group the camera and parse the json to modify the focal value for each intrinsic group.
