### ISSUE TITLE
running openMVG_main_SfMInit_ImageListing

### ISSUE THREAD

**Issue by perthvr** [openMVG/openMVG#1173]
Hi 
Newbie question (both to linux and openmvg I'm afraid ) whenever i try to run the imagelisting command  it reports back as command not found. I am running it from within the linux release folder (as that is where the command is located)  I have checked pathways for camera text file and output and input directory locations and they are correct. i am doing something wrong possibly there is something I have to alter in envirnoment variables (include bin somwhere) or perhaps the openmvg dependencies . part of my code showing the locations of the images -i  /../omvgtest/images
cheers and thanks Sally

**Comment by pmoulon** [comment]
Can you show us how you try to run it?

What happen if you try to do that. (Here what I have)
```
$ ./Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing 
Usage: ./Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
[-i|--imageDirectory]
[-d|--sensorWidthDatabase]
...
```

**Comment by perthvr** [comment]
[-i|--imageDirectory]
[-d|--sensorWidthDatabase]
[-o|--outputDirectory]
[-f|--focal] (pixels)
[-k|--intrinsics] Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"
[-c|--camera_model] Camera model type:
	 1: Pinhole
	 2: Pinhole radial 1
	 3: Pinhole radial 3 (default)
	 4: Pinhole brown 2
	 5: Pinhole with a simple Fish-eye distortion
	 7: Spherical camera
[-g|--group_camera_model]
	 0-> each view have it's own camera intrinsic parameters,
	 1-> (default) view can share some camera intrinsic parameters

[-P|--use_pose_prior] Use pose prior if GPS EXIF pose is available[-W|--prior_weights] "x;y;z;" of weights for each dimension of the prior (default: 1.0)
[-m|--gps_to_xyz_method] XZY Coordinate system:
	 0: ECEF (default)
	 1: UTM

Invalid command line parameter.

when i run usage

**Comment by perthvr** [comment]
sally@sally-Alienware-15-R3:~/Linux-x86_64-RELEASE$ sudo openMVG_main_SfMInit_ImageListing -d /../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i /../omvgtest/images -o /../omvgtest/matches
sudo: openMVG_main_SfMInit_ImageListing: command not found

**Comment by perthvr** [comment]
I also tried the python script but lost my way fairly quickly with "@OPENMVG_SOFTWARE_SFM_BUILD_DIR@" I tried to look up  what @dir_name@ might mean in python but to no avail
thanks sally

**Comment by perthvr** [comment]
yeh thanks for your response  I have worked it out I did 2 things changed the permissions on openMVG directory and also ran the command from the directory level above home. I really dont know which worked however. Hopefully i do a little better on the next commands
