### ISSUE TITLE
cmake error  ： ceres

### ISSUE THREAD

**Issue by scholltan** [openMVG/openMVG#1174]
===============================================================
   Ceres-solver configuration.
   ===============================================================
CMake Error at third_party/ceres-solver/cmake/ReadCeresVersionFromSource.cmake:53 (message):
  Failed to extract Ceres major version from
  E:/openMVG/src/third_party/ceres-solver/include/ceres/version.h
Call Stack (most recent call first):
  third_party/ceres-solver/CMakeLists.txt:63 (read_ceres_version_from_source)

and ceres-dir not found， added the path，but output the same error

**Comment by pmoulon** [comment]
I don't know what's going on there.
Build is ok on windows in the CI:
https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.784

Please, Can you share your cmake output?

**Comment by scholltan** [comment]
in the CI, which version u usded? is the branch master?

**Comment by pmoulon** [comment]
master and develop branch are tested and build fine.

**Comment by pmoulon** [comment]
@scholltan Did you find a fix for your problem?

**Comment by scholltan** [comment]
sorry for late reply,  I changed to linux and everything goes well.......
