### ISSUE TITLE
Sfm_Localizer : Localize & RefinePose

### ISSUE THREAD

**Issue by qtnext** [openMVG/openMVG#1177]
We use LocaLize to find the pose with 2D-3D correspondance. It works fine but I want to improve the result and avoid bad pose  when 3D points are not so fare (avoid to find a silly lens). 

Can I replace Localize by RefinePose to provide initial pose or it will not works ?

**Comment by pmoulon** [comment]
What do you mean by (avoid to find a silly lens)?
 - Does you mean that the BA find a bad distortion model?
  - If this is the case you can try to localize a simpler camera model (one radial distortion factor)

> Can I replace Localize by RefinePose to provide initial pose or it will not works ?

Can you elaborate?

**Comment by qtnext** [comment]
Hi,

we don't need to correct distortion : only find lens and center of lens and the pose. I want to help the algo with an estimated position of the camera and lens because we have an approximate pose & lens to help to to converge to most correct result.

**Comment by pmoulon** [comment]
Since the class is already supporting this what not do the following:
- setup your camera intrinsic and the initial pose for this view with your initial guess (add a pose and a camera model with your data to the existing sfm_data).
- then call the bool RefinePose function with the corresponding data
```
(
    cameras::IntrinsicBase * intrinsics,
    geometry::Pose3 & pose,
    Image_Localizer_Match_Data & matching_data,
    bool b_refine_pose,
    bool b_refine_intrinsic
  );
```

**Comment by qtnext** [comment]
Thanks for the answer. that's my question : I was guessing I need to use RefinePose instead of Localize to do the same job when I have an initial guess:) so I suppose it's ok to do this :)

**Comment by pmoulon** [comment]
Else you can run a BA with the data of your camera and its visibility (tiny sfm_data extracted from the scene) (you just refine the camera pose) and then update the pose.

**Comment by pmoulon** [comment]
@qtnext Can you close the issue if you got a working solution?
