### ISSUE TITLE
building issue - (missing CMakeLists.txt)

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1178]
Hi everyone, I'm new to openMVG. I'm trying to build openMVG following the instructions for Linux. There seems to be some steps missing in the instruction:

$ git clone --recursive https://github.com/openMVG/openMVG.git
$ cd openMVG
$ ls
 AUTHORS BUILD  docs  logo  README  src  ...
$ cd ..
$ mkdir openMVG_Build
$ cd openMVG_Build

After this, the directory openMVG_Build is empty. Then how can I do cmake after this? Where is the CMakeLists.txt? Thank you very much!

**Comment by pmoulon** [comment]
As explained here you will find the CMakeLists.txt in the src directory
https://github.com/openMVG/openMVG/blob/master/BUILD.md#linux-compilation

**Comment by pmoulon** [comment]
`$ cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . ../openMVG/src/` will do the trick ;-)

**Comment by squashking** [comment]
Thank you. sorry for this silly question.

**Comment by pmoulon** [comment]
No worries
