### ISSUE TITLE
Global SFM reports "Invalid matches file" error

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1180]
Hi, I have tried Incremental SFM and Global SFM. The former seems to work fine but the latter reports an error: Invalid matches file. I followed every steps in the instruction. Did I miss some steps or do something wrong? Thank you!

**Comment by pmoulon** [comment]
Did you have any file called matches.f.txt or matches.e.txt in the matching directory?

**Comment by squashking** [comment]
@pmoulon there is matches.f.bin in the matching directory. No  matches.f.txt or matches.e.txt in the directory.

**Comment by pmoulon** [comment]
Sorry I meant matches.X.bin files.
Global SfM expect matches.e.bin file (you can obtain it by running ComputeMatches with the option `-g e`).
You can also provide the match file of your choice to GlobalSfM by using the option `--match_file 
 <path>/matches.f.bin`.

**Comment by squashking** [comment]
@pmoulon Thank you very much!
