### ISSUE TITLE
OpenMVG-MVS Pipeline with game engine : Unity

### ISSUE THREAD

**Issue by himanshusagar** [openMVG/openMVG#1184]
Hey,
I am trying to check out openmvg-mvs pipeline with images captured via 'rendered to texture' of Unity Game Engine. 

As per [this](https://github.com/openMVG/openMVG/issues/1017), Do I need to add unity camera specs in sensor_width_database.txt? ,If yes, How should I do that? What else is required?
Thanks in Advance.

Sample Image : 
![screenshot_via_camera_2](https://user-images.githubusercontent.com/19569164/34192306-45f0ef06-e573-11e7-9e27-d0624f98fbed.png)

Meta Data of Image : 

![capture](https://user-images.githubusercontent.com/19569164/34192366-9e04c42e-e573-11e7-8229-8fcfe168da96.PNG)

Log from MvgMvs_Pipeline.py 
# Using input dir  :  /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/images
#       output_dir :  /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output
# First step  :  0
# Last step :  11
#0. Intrinsics analysis
 You called : 
/home/himanshu/graphics/openMVG7Install/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/images
--sensorWidthDatabase /home/himanshu/graphics/openMVG7Install/openMVG_Build/Linux-x86_64-RELEASE/sensor_width_camera_database.txt
--outputDirectory /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 135
usable #File(s) listed in sfm_data: 135
usable #Intrinsic(s) listed in sfm_data: 0
#1. Compute features
 You called : 
/home/himanshu/graphics/openMVG7Install/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/matches/sfm_data.json
--outdir /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 4

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 1
#2. Compute matches
 You called : 
/home/himanshu/graphics/openMVG7Install/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/matches/sfm_data.json
--out_dir /home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************************************************************
 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*********************************************************Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
#3. Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
*
*

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 1883
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 47, 49, 53, 57, 59, 60, 61, 62, 63, 64, 65, 67, 68, 70, 71, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 90, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 
------------------
TrackLength, Occurrence
	2	1153
	3	397
	4	187
	5	88
	6	31
	7	22
	8	3
	9	1
	14	1

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
#4. Colorize Structure

The input SfM_Data file "/home/himanshu/graphics/openMVSProjects/UnityEvaluation/RegularSampling/output/reconstruction_sequential/sfm_data.bin" cannot be read.

**Comment by Yannnnnnnnnnnn** [comment]
You can add some parameter in the script, I give you an example below

change the following code:
print ("1. Intrinsics analysis")
pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params,"-f","400"] )
pIntrisics.wait()

**Comment by Yannnnnnnnnnnn** [comment]
The script is a simple tool to use the openMVG/software, you can change it to fit your own needs.

**Comment by himanshusagar** [comment]
Well, since images have no metadata(exif), Does that mean I'll have to specify all options which can be read from metadata(exif) as arguments just like @Yannnnnnnnnnnn  did in above comment?
Can you tell me what options will they be? for e.g one is -f option in openMVG_main_SfMInit_ImageListing?
I want to run Mvg_MvgMvs_Pipeline.py.

**Comment by pmoulon** [comment]
As I say often, and as you noticed it, one critical thing in SfM is the availability or intrinsic data.
The community shared to you the right information.

Since in your case image does not have any, you can specify a approximate focal length (with the `-f X` X should be like 1.2*max(w,h)). It will provide a sufficiently approximate focal length to start with. You can use this option in openMVG_main_SfMInit_ImageListing.

Just look in your script where the call is made to `openMVG_main_SfMInit_ImageListing` and you will add the -f parameter. That's it.

**Comment by Yannnnnnnnnnnn** [comment]
@himanshusagar that's the same for you in MvgMvs_Pipeline.py, the example is blow:

[   "Intrinsics analysis",
os.path.join(OPENMVG_BIN,"openMVG_main_SfMInit_ImageListing"),
["-i", "%input_dir%", "-o", "%matches_dir%", "-d", "%camera_file_params%","-f","400"] ],

**Comment by himanshusagar** [comment]
I truly appreciate the help provied by community (specially @pmoulon ) since he mentioned reason for changing f parameter which indeed helped me learn.
