### ISSUE TITLE
how to visualize camera pose in the reconstructed results?

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1186]
Hi, after implementing Incremental SFM, I got the .ply results which can be visualized in Meshlab. I would like to visualize the camera poses as well (e.g., shown as view frustums). Is there any method to do this?
Thank you very much!

**Comment by cogitas3d** [comment]
1) You can export to Bundler and open in Blender with this addon: http://koelzk.crispy-cow.de/article/9/importing-bundler-scenes-to-blender.

2) You can export to OpenMVS and open with their viewer.
