### ISSUE TITLE
No performance gain from more recent instruction set

### ISSUE THREAD

**Issue by giacomodabisias** [openMVG/openMVG#1187]
Hello.

I was using an older branch of OpenMVG which did not have the optimization flags present in the cmake file. Specifically I am talking about AXV, AVX2, SSE....

I then checked out the latest version and noticed that now there is also the support for AVX512.
I decided to make a test to see how much improvement I would get using all the possible optimized instruction sets, so I created a clean ubuntu machine with AVX512 support (and also avx, avx2, see...), built both versions of openMVG (one with optimized instructions, one without) and then tried to run the SfM_GlobalPipeline.py script on 100 images. I got exactly the same timings for both tests, so I am wondering why there is no performance improvement. Usually the improvement should be significant.

Any ideas?

**Comment by pmoulon** [comment]
Here you speak about compiler optimization flag.
So if the compiler is not capable of vectorizing OpenMVG code it is not our fault.

Did you generate the solution in two different directory since SfM_GlobalPipeline.py point to binaries on disk?

Else if something is wrong you are more than welcome to help!

**Comment by giacomodabisias** [comment]
Hi, yes to separate folders.
I thought that the vectorized operations where added in the openMVG code. Is that the case? Or are you suggesting that the compiler does not support those instruction sets?

Thanks

**Comment by pmoulon** [comment]
I meant that most of the operation that could be vectorized are the linear algebra operation.
For those operation we rely on Eigen. It means that either we are not using optimally Eigen or that the compiler does not succeed to generate the good instruction.

Which version did you tried to compare (v1.0 towards 1.3)?

**Comment by giacomodabisias** [comment]
I see, will investigate more then.

Thanks
