### ISSUE TITLE
Use reference instead of a temporary in the function named MatchesPairToMat 

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#1188]
@pmoulon 
In file Geometric_Filter_utils.hpp, the function named MatchesPairToMat use temporary variables instead of reference vairables.  The codes are as follows.
`  // Load features of Inth and Jnth images
  const features::PointFeatures
    feature_I = features_provider->feats_per_view.at(pairIndex.first),
    feature_J = features_provider->feats_per_view.at(pairIndex.second);`
The variables feature_I  and feature_J both  are temporary variables which will make a copy from features_provider->feats_per_view.at(pairIndex.first). 
I suppose adding a reference & operator and the changed codes are as follows.
`  // Load features of Inth and Jnth images
  const features::PointFeatures
  & feature_I = features_provider->feats_per_view.at(pairIndex.first),
   & feature_J = features_provider->feats_per_view.at(pairIndex.second);`

**Comment by pmoulon** [comment]
You are right!

Thx you. You can propose a PR for it and I can fix it on my side. Up to you!

Regards.
