### ISSUE TITLE
Error MSB3073 occurred when I try to build INSTALL on VS2015

### ISSUE THREAD

**Issue by zouh520sdo** [openMVG/openMVG#1191]
I try to build the lasted openMVG on VS2015. I successfully built ALL_BUILD, but I didn't found any dll or lib files. So I tried to build INSTALL, but Error MSB3073 occurred.

This is one of those error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
C:\Software\Cmake\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	

Anyone know how to solve these?

**Comment by pmoulon** [comment]
You must run Visual in administrator mode or choose to install OpenMVG in a directory that is not in the system (different than Program Files).
You can  customize this installation path in cmake with the string path variable `CMAKE_INSTALL_PREFIX`

**Comment by zouh520sdo** [comment]
@pmoulon Thank you! That is the issue.

**Comment by pmoulon** [comment]
Can you please close the issue?
