### ISSUE TITLE
build issues on missing pthreads

### ISSUE THREAD

**Issue by jiywang3** [openMVG/openMVG#1193]
My build can find pthread, but not pthreads. I am using gcc 5.3.0. Any help is appreciated.

Here is the section from cmake:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found

Here are the error messages:
Determining if the pthread_create exist failed with the following output:
Change Dir: .../openMVG_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_a0dfe/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_a0dfe.dir/build.make CMakeFiles/cmTC_a0dfe.dir/build
gmake[1]: Entering directory `.../openMVG_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a0dfe.dir/CheckSymbolExists.c.o
/opt/ncbi/gcc/5.3.0/bin/gcc   -march=sandybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi    -o CMakeFiles/cmTC_a0dfe.dir/CheckSymbolExists.c.o   -c .../openMVG_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_a0dfe
.../cmake-3.10.1-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a0dfe.dir/link.txt --verbose=1
/opt/ncbi/gcc/5.3.0/bin/gcc  -march=sandybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi     -rdynamic CMakeFiles/cmTC_a0dfe.dir/CheckSymbolExists.c.o  -o cmTC_a0dfe
CMakeFiles/cmTC_a0dfe.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_a0dfe] Error 1
gmake[1]: Leaving directory `.../openMVG_build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_a0dfe/fast] Error 2

File .../openMVG_build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: .../openMVG_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_68d3e/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_68d3e.dir/build.make CMakeFiles/cmTC_68d3e.dir/build
gmake[1]: Entering directory `.../openMVG_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_68d3e.dir/CheckFunctionExists.c.o
/opt/ncbi/gcc/5.3.0/bin/gcc   -march=sandybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_68d3e.dir/CheckFunctionExists.c.o   -c .../cmake-3.10.1-Linux-x86_64/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_68d3e
.../cmake-3.10.1-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_68d3e.dir/link.txt --verbose=1
/opt/ncbi/gcc/5.3.0/bin/gcc  -march=sandybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_68d3e.dir/CheckFunctionExists.c.o  -o cmTC_68d3e -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_68d3e] Error 1
gmake[1]: Leaving directory `.../openMVG_build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_68d3e/fast] Error 2

**Comment by pmoulon** [comment]
@rperrot Any idea?

**Comment by rperrot** [comment]
Something related to : 

https://stackoverflow.com/a/39547577

?

**Comment by jiywang3** [comment]
I tried to add the following and it didn't change anything from the output:

set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
find_package(Threads REQUIRED)
if(CMAKE_USE_PTHREADS_INIT)
    set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} "-pthread")
endif (CMAKE_USE_PTHREADS_INIT)

target_link_libraries( .. ${CMAKE_THREAD_LIBS_INIT} )

**Comment by jiywang3** [comment]
I installed openMVG successfully in ubuntu 16.
