### ISSUE TITLE
SfM localization does not work with scenes using AKAZE_MLDB features

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#1205]
I have an issue with the SFM localization code within OpenMVG: it seems to fail only when using AKAZE_MLDB features. 

If I reconstruct a scene with SIFT, or AKAZE FLOAT features, and then try to localize an image within this scene, it works perfectly, but when I try to use AKAZE_MLDB as the main detection mechanism with the same set of images, reconstruction works fine but localization fails: it always reports "Points validated by robust Resection" as 0.

Furthermore, while debugging through Visual Studio, I can see that matching between the query image and the existing scene does work, so the algorithm should have enough tracked feature points but strangely, the PNP kernel seems to be failing. This is happening with both PNP algorithms (KNEIP_11 and KE_2017). Would be great if someone else can test this!

**Comment by pmoulon** [comment]
Thanks for the feedback.
I will try and take a look.

**Comment by pmoulon** [comment]
@saihv I tried and for me it worked fine.

I took the images from https://github.com/openMVG/ImageDataset_SceauxCastle
Make a reconstruction with (AKAZE_MLDB)
 and {100_7100.JPG,100_7101.JPG,100_7102.JPG,100_7103.JPG,100_7106.JPG,100_7107.JPG,100_7108.JPG,100_7109.JPG,100_7110.JPG} and then try to localize {100_7104.JPG, 100_7105.JPG} and everything went well.

See the log below

```
-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------


- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Init retrieval database ... 
Retrieval database initialized with:
#landmarks: 5428
#descriptors: 15864
SfM::localization => try with image: 100_7104.JPG
#regions detected in query image: 5284
- use UNknown intrinsics for the resection. Then create a Pinhole_Intrinsic_Radial_K3 camera.
#3D2d putative correspondences: 1075
  nfa=-885.352 inliers=778/1075 precisionNormalized=0.00952622 precision=239.603 (iter=2 ,sample=299,203,588,1067,1029,1071,)
  nfa=-2446.67 inliers=929/1075 precisionNormalized=0.000429631 precision=50.8839 (iter=3 ,sample=156,348,358,716,386,210,)
  nfa=-2613.01 inliers=936/1075 precisionNormalized=0.000303314 precision=42.7542 (iter=8 ,sample=1047,278,928,699,649,912,)
  nfa=-3358.58 inliers=946/1075 precisionNormalized=5.35837e-05 precision=17.97 (iter=11 ,sample=994,940,691,92,249,468,)
  nfa=-3417.77 inliers=930/1075 precisionNormalized=3.84477e-05 precision=15.2219 (iter=13 ,sample=616,343,204,612,212,939,)
  nfa=-3428.07 inliers=958/1075 precisionNormalized=5.18465e-05 precision=17.6763 (iter=24 ,sample=758,466,473,377,812,492,)
  nfa=-3457.88 inliers=945/1075 precisionNormalized=4.15021e-05 precision=15.8149 (iter=47 ,sample=1006,936,229,275,645,221,)
  nfa=-3520.2 inliers=947/1075 precisionNormalized=3.64549e-05 precision=14.8221 (iter=60 ,sample=416,237,695,705,1051,382,)
  nfa=-3610.87 inliers=934/1075 precisionNormalized=2.49134e-05 precision=12.2532 (iter=69 ,sample=464,922,801,264,77,224,)
  nfa=-3652.26 inliers=945/1075 precisionNormalized=2.57216e-05 precision=12.4504 (iter=123 ,sample=906,142,221,982,1041,742,)
  nfa=-3789.98 inliers=959/1075 precisionNormalized=2.1803e-05 precision=11.4628 (iter=228 ,sample=16,470,975,567,834,218,)

-------------------------------
-- Robust Resection 
-- Resection status: 1
-- #Points used for Resection: 1075
-- #Points validated by robust Resection: 959
-- Threshold: 11.4628
-------------------------------

Bundle Adjustment statistics (approximated RMSE):
 #views: 1
 #poses: 1
 #intrinsics: 1
 #tracks: 959
 #residuals: 1918
 Initial RMSE: 2.80342
 Final RMSE: 0.845019
 Time (s): 0.0101159

SfM::localization => try with image: 100_7105.JPG
#regions detected in query image: 4535
- use UNknown intrinsics for the resection. Then create a Pinhole_Intrinsic_Radial_K3 camera.
#3D2d putative correspondences: 895
  nfa=-276.099 inliers=407/895 precisionNormalized=0.0129153 precision=278.988 (iter=0 ,sample=729,122,810,747,117,867,)
  nfa=-2052.86 inliers=742/895 precisionNormalized=0.000282076 precision=41.2302 (iter=1 ,sample=339,437,473,141,217,242,)
  nfa=-2215.17 inliers=793/895 precisionNormalized=0.000310688 precision=43.2708 (iter=2 ,sample=380,518,829,28,794,413,)
  nfa=-2453.96 inliers=775/895 precisionNormalized=0.000123402 precision=27.2705 (iter=5 ,sample=634,753,249,338,341,95,)
  nfa=-2557.64 inliers=742/895 precisionNormalized=5.80517e-05 precision=18.7042 (iter=6 ,sample=710,398,109,64,288,44,)
  nfa=-2612.76 inliers=767/895 precisionNormalized=6.88922e-05 precision=20.3759 (iter=14 ,sample=79,663,23,48,453,479,)
  nfa=-2720.05 inliers=738/895 precisionNormalized=3.28963e-05 precision=14.0801 (iter=21 ,sample=412,136,579,592,796,502,)
  nfa=-2915.74 inliers=755/895 precisionNormalized=2.2985e-05 precision=11.7694 (iter=36 ,sample=666,325,55,871,457,426,)
  nfa=-2949.25 inliers=778/895 precisionNormalized=2.91616e-05 precision=13.2568 (iter=64 ,sample=633,789,38,725,684,71,)
  nfa=-2957.74 inliers=750/895 precisionNormalized=1.86998e-05 precision=10.6158 (iter=209 ,sample=50,800,181,346,581,416,)
  nfa=-3000.56 inliers=766/895 precisionNormalized=2.09096e-05 precision=11.2255 (iter=314 ,sample=84,837,619,817,690,305,)

-------------------------------
-- Robust Resection 
-- Resection status: 1
-- #Points used for Resection: 895
-- #Points validated by robust Resection: 766
-- Threshold: 11.2255
-------------------------------

Bundle Adjustment statistics (approximated RMSE):
 #views: 1
 #poses: 1
 #intrinsics: 1
 #tracks: 766
 #residuals: 1532
 Initial RMSE: 3.11389
 Final RMSE: 0.821677
 Time (s): 0.00798465

 Total poses found : 2/2
```

Can you share your log?

**Comment by saihv** [comment]
@pmoulon Thanks for checking. Seems like an issue only on my end then. I tried what you mentioned (I am on the master branch), I am encountering two problems:

1. Localization is failing on the images with an error

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```
2. Also, according to your log, there are about 700-1000 tracks on the localized images, which means the map is quite dense: but in my case, after running the IncrementalSFM pipeline, I am getting only 200 points in the 3D map. Are you running a different pipeline?

```
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 9 from 9 input images.
-- #Tracks, #3D points: 197
-------------------------------
```

**Comment by pmoulon** [comment]
Do you want share your data and the command line you used there openmvg-team[AT]googlegroups.com so I can have a look.

**Comment by pmoulon** [comment]
@saihv any update on this?

**Comment by saihv** [comment]
@pmoulon So sorry about the late reply, I was on travel: but I figured out that the mapping problem I had was because of an issue with inputting the intrinsics. So now, with the Sceaux Castle dataset, I have a fully built map with about 10000 features. 

I have sent an email to openmvg-team with the commandline inputs as well as some of the output I got. I am still unable to localize using openMVG_main_SfM_Localization binary.

**Comment by pmoulon** [comment]
Now that the intrinsic are fixed, everything is working, please consider to close the issue.

**Comment by nikhilsawlani** [comment]
@pmoulon I had a similar issue I was able to Localize in Castle dataset, but when I used my dataset (images from my phone) and tried localization then it was not able to find any pose 
here is command line log
`
E:\New folder\Windows-AMD64-Release\Release>openMVG_main_SfM_Localization.exe -i E:\reconsamsung\reconstruction_sequential\sfm_data.bin -m E:\reconsamsung\matches -u E:\output2 -o E:\output2 -q E:\samsungcam -c 1

-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------


- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Init retrieval database ...
Retrieval database initialized with:
#landmarks: 3757
#descriptors: 10026
 Total poses found : 0/0`

I tried both SFM sequential and global

**Comment by pmoulon** [comment]
If you try to run incremental SfM with your initial imageset and the query images, does all the images are localized?
