### ISSUE TITLE
tools to visualize photometric/geometric matches correspondences

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1207]
Hi, I see in the Docs [https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/ ](url) there are tools to visualize photometric/geometric matches correspondences. But I cann't seem to find it. Could anyone please tell me what tool it is? Thanks a lot!

**Comment by pmoulon** [comment]
You can use the binary `openMVG_main_exportMatches` or if you have compiled OpenMVG with Qt UI examples you can use the adjacency matrix viewer `ui_openMVG_MatchesViewer` https://github.com/openMVG/openMVG/issues/831

**Comment by squashking** [comment]
@pmoulon Thanks for the quick answer. I ran openMVG_main_exportMatches and got some .svg files. And I don't know how to use ui_openMVG_MatchesViewer. What I  expect is to see correspondences between images (e.g. drawing correspondence lines across images). Any methods to do that? thank you!

**Comment by pmoulon** [comment]
the SVG files show the correspondences between the features per image pair. You can open the SVG files with your internet browser (Chrome, Firefox...).

ui_openMVG_MatchesViewer allow to choose which pair to display see https://github.com/openMVG/openMVG/issues/831

**Comment by squashking** [comment]
@pmoulon Thank you! The .svg files show only correspondence lines but not the original images (i.e., I can only see some lines with transparent background). And the ui_openMVG_MatchesViewer shows empty. I tried ui_openMVG_MatchesViewer with sfm_data.json, matches.f.bin and matches.e.bin, but all show nothing.

**Comment by squashking** [comment]
@pmoulon I tried using Inkscape to open the .svg file and it popped up a message "Broken links have been changed to point to existing files." But it can show the images. It seems there are some hidden links changed. I don't know why.

**Comment by pmoulon** [comment]
Please use your internet browser. Inkscape have some trouble to use some linked files.

Regarding ui_openMVG_MatchesViewer be sure to use the sfm_data.json file that is in the matches directory (where the feature are stored).

**Comment by squashking** [comment]
@pmoulon I try using browser again and it works now but yesterday browser didn't shows images (only shows lines) .  But ui_openMVG_MatchesViewer  still does not work. This is how I use it: ui_openMVG_MatchesViewer  /path/to/sfm_data.json  It shows an empty dialogue, no images or lines. Am I using it correctly? Thank you!

**Comment by pmoulon** [comment]
For ui_openMVG_MatchesViewer you launch it without arguments.
Then do `File/open`,  then give the path of the json files that is in a match directory (i.e. /path/to/matches/sfm_data.json), then the path of the match file (i.e. /path/to/matches/matches.f.bin)

**Comment by squashking** [comment]
@pmoulon Now I see the problem. When I launch ui_openMVG_MatchesViewer , the software does not have "File/open" or similar menus at all. There are only some tabs like "select", "drag" etc.

**Comment by pmoulon** [comment]
You don't have the File menu:
![image](https://user-images.githubusercontent.com/3235050/34968888-d078b232-fa20-11e7-8e4b-73f23fa47450.png)

Note: If you are on mac, it should be on the Application bar.

**Comment by squashking** [comment]
![screenshot from 2018-01-17 09-52-09](https://user-images.githubusercontent.com/34270290/35016367-5872a6ce-fb6c-11e7-8843-47aad271fb25.png)
I'm using Linux. As you can see, there is no "File" menu.

**Comment by pmoulon** [comment]
@rperrot Any idea?
-> Does ubuntu hide the menu in another menu bar as MacOS does?

**Comment by rperrot** [comment]
I think there's an issue with unity (@rjanvier have similar issue on one of the other gui tool) on ubuntu

**Comment by rperrot** [comment]
@squashking any feedback on this issue ?

**Comment by NikolausDemmel** [comment]
Hm... I just tried this on Ubuntu 16.04. with Unity desktop, and I do see the File menu.

![screenshot from 2018-01-25 11-52-58](https://user-images.githubusercontent.com/479562/35384679-6714d552-01c6-11e8-8dce-fc242181ca06.png)

But I have another issue. When I click on a match, it looks like it tries to use the svg file content as a file name 😕 

```
Read #Pair: 55
Cannot open file '<?xml version="1.0" standalone="yes"?>
<!-- SVG graphic -->
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'
width="5664px" height="2128px" preserveAspectRatio="xMinYMin meet" viewBox="0 0 5664 2128" version="1.1">
<image x="0" y="0" width="2832px" height="2128px" opacity="1" xlink:href="/work/ssd/demmeln/slam/dba/openMVG/build-src-Desktop-RelWithDebInfo/software/SfM/ImageDataset_SceauxCastle/images/100_7100.JPG"/>
<image x="2832" y="0" width="2832px" height="2128px" opacity="1" xlink:href="/work/ssd/demmeln/slam/dba/openMVG/build-src-Desktop-RelWithDebInfo/software/SfM/ImageDataset_SceauxCastle/images/100_7110.JPG"/>
<polyline points="1730.51,1066.34,4036.08,530.454" stroke="rgb(255,0,72)" stroke-width="2" fill="none"/>
<polyline points="2000.27,1093.01,3648.28,632.704" stroke="rgb(195,0,255)" stroke-width="2" fill="none"/>
<polyline points="1691.91,1099.63,3993.09,589.565" stroke="rgb(242,0,255)" stroke-width="2" fill="none"/>

[...]

<circle cx="4461.39" cy="1504.89" r="4" stroke="rgb(0,127,255)" stroke-width="2" fill="none"/>
<circle cx="1085.75" cy="1764.78" r="4" stroke="rgb(0,255,225)" stroke-width="2" fill="none"/>
<circle cx="3065.49" cy="1486.05" r="4" stroke="rgb(0,255,225)" stroke-width="2" fill="none"/>
</svg>', because: File name too long
```

**Comment by NikolausDemmel** [comment]
> But I have another issue. When I click on a match, it looks like it tries to use the svg file content as a file name

PS: This is on master.

**Comment by pmoulon** [comment]
This issue is fixed in the develop branch thanks to @hcjghr 
https://github.com/openMVG/openMVG/commit/5acc481e518705d063047478c51417021d7e9c25

Please checkout and use develop ;-)

**Comment by NikolausDemmel** [comment]
That works! And the file menu is still there for me. Thanks!

**Comment by pmoulon** [comment]
I'm closing the issue since all the question have been covered there ;-)
- behavior on Ubuntu Unity
- bug fixes
