### ISSUE TITLE
Questions about openMVG_main_ComputeStructureFromKnownPoses

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1214]
Hi, in my application the camera intrinsics and poses are already known. I'm wondering how to use openMVG_main_ComputeStructureFromKnownPoses. My questions: 
1. Is it called before running GlobalSFM/IncrementalSFM or after? (not sure if it does reconstruction itself or just outputs a json file. From the docs it seems to only output a json file）. Is the input file sfm_data.json computed after SfMInit_ImageListing?
2. What is the format of the camera poses in the input json file? Is it like the following:
"extrinsics": [
        {
            "key": 0,
            "value": {
                "rotation": [
                    [r11,  r12,  r13 ],
                    [r21,  r22,  r23 ],
                    [r31,  r32,  r33 ]
                ],
                "center": [cx, cy, cz]
            }
        },....
      }
If it is like the above, What is the rotation and center (or translation) with respect to?  What is the reference? 
Thank you very much!

Many thanks!

**Comment by pmoulon** [comment]
I would advise you use the OpenMVG API to fill the sfm_data structure and then save it.
So this way you will not be confused by the data format.

You are right the extrinsics are formated the way you shown.
Camera poses are saved this way:
- rotation are saved row-wise
- center depict the camera position in the world.

So if you setup existing camera poses the pipe become:
1. set and fill your scene (sfm_data.json) with views, intrinsics and poses
2. Compute Features
3. Compute Matches
4. ComputeStructureFromKnownPoses (You can called the option to triangulate a match file (matches.f.bin))

So as conclusion ComputeStructureFromKnownPoses can take a sfm_data json with poses and a matches file and perform the track building and triangulation.

**Comment by squashking** [comment]
@pmoulon Thanks. But what are rotation and translation with respect to? I assume there is one camera view which has 0 rotation and 0 translation, and other views have rotation and translation with respect to that view. Is it right? Or the translation and rotation of all views are with respect to a world origin?

**Comment by pmoulon** [comment]
The translation and rotation of all views are with respect to the world origin.
So you can choose any coordinate system of your choice (I mean you don't need to setup a view at (0,0,0)).

**Comment by squashking** [comment]
@pmoulon ok. Thank you very much!

**Comment by squashking** [comment]
@pmoulon ok. Sorry to ask one more question about the extrinsics. Is the value for camera center in pixel or in meter?

**Comment by pmoulon** [comment]
SFM is always up to scale.
The only way to have a reconstruction at the right scale is to use some scaling priors. To do that you can use GCPs or GPS priors.

If you are using camera priors like GPS information you can have scaled coordinates in meters thanks to the ECEF coordinates system.

**Comment by squashking** [comment]
@pmoulon so even if I write the focal length in pixel, I don't have to write the camera center values in pixel as well, is it correct? Thank you!

**Comment by pmoulon** [comment]
That's right.
This is because the baseline (the distance between the camera) are only determined up to scale by the Essential matrix decomposition.
