### ISSUE TITLE
Distortion model: radial (3)

### ISSUE THREAD

**Issue by ccastilloro** [openMVG/openMVG#1215]
Hi! I was looking at the different distortion models in the manual and the source. In the manual I found:

> – The camera model type that will be used for views with unknown intrinsic:
> * 1: Pinhole
> * 2: Pinhole radial 1
> * 3: Pinhole radial 3 (default)
> * 4: Pinhole radial 3 + tangential 2
> * 5: Pinhole fisheye

In the code:
 Camera_Intrinsics.hpp 	--> 1
Camera_Pinhole_Brown.hpp 	--> 4
Camera_Pinhole_Fisheye.hpp 	--> 5
Camera_Pinhole_Radial.hpp 	--> 2

I could not find Radial 3 model. Would you mind telling me the name of the this distortion function (Radial3)?

Thanks a lot!

Carlos

**Comment by rperrot** [comment]
It's in the Camera_Pinhole_Radial.hpp file

**Comment by ccastilloro** [comment]
Excellent! Thanks!
