### ISSUE TITLE
TriangulateNView with distortion

### ISSUE THREAD

**Issue by MatillaMartin** [openMVG/openMVG#1217]
I have detected a checker externally to openMVG on multiple images and would like to triangulate its position. How can I triangulate these features, using a sfm_data.bin scene (already computed) using `TriangulateNView` but taking into account the intrinsic lens distortion for each camera?

The distortion is already computed, and is saved in sfm_data intrinsics.

Is there any other way to simply project pixels to 3D from 2 views using an already created scene?

Should I build a set of observations and send it through `SfM_Data_Structure_Computation_Blind` in `sfm_data_triangulation.cpp`?

The main objective is to scale the scene (I know the size of the checker)

**Comment by MatillaMartin** [comment]
I guess I can use TriangulateNView with cam->get_projective_equivalent(pose), and cam->get_ud_pixel(itObs->second.x)); to undistort my observations!

**Comment by pmoulon** [comment]
You are right about the function to use.
You can take a look to:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_triangulation.cpp#L44

I would advise you to use directory the pose and the `()` operator on the intrinsics to get the bearing vector.

**Comment by pmoulon** [comment]
@MatillaMartin Please, can you close the issue if you got your answer?

**Comment by MatillaMartin** [comment]
Sure! To wrap up, I ended up using the solution in https://github.com/openMVG/openMVG/issues/1102, which is more robust
