### ISSUE TITLE
[logger] Prepare OpenMVG to use a centralized LOGGER

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1223]
Add and use macro to LOG message with severity.

It will provide a uniform way to report information/status to the user and a better reporting of semantic of the message (INFO, WARNING, ERROR).

- [x] Add severity based logging macro OPENMVG_LOG_INFO, OPENMVG_LOG_WARNING, OPENMVG_LOG_ERROR
- [x] Add conditional and severity base logging macro OPENMVG_LOG_INFO_IF, OPENMVG_LOG_WARNING_IF, OPENMVG_LOG_ERROR_IF

Remaining task:
- [ ] test to use a header only logger system in order to have a thread safe logging. Alternative could be:
  - [spdlog](https://github.com/gabime/spdlog)
  - [easyloggingpp](https://github.com/muflihun/easyloggingpp)
  - [loguru](https://github.com/emilk/loguru)

**Comment by srivathsanmurali** [comment]
@pmoulon Any chance we could have an option to log to a file instead of std::cerr ? 
I would be open to helping out when I got some time :D

**Comment by pmoulon** [comment]
I would be happy to have some help experimenting some of the the framework I have listed (I started to add the `help_wanted` tag to some task).
Feel free to try to use any of the alternative I have listed.

**Comment by srivathsanmurali** [comment]
@pmoulon I have some experience using easyloggingpp will try to test it out and run some tests on it this weekend. If you are fine with that.

**Comment by pmoulon** [comment]
Sure, appreciated!

**Comment by srivathsanmurali** [comment]
@pmoulon Sorry got really busy with work. Haven't had too much progress in it. Can push my work today. But its still not complete.

Sorry about this.

**Comment by pmoulon** [comment]
No worries. I was just checking ;-) Let me know when you will have more time to work on this.
