### ISSUE TITLE
Question about Increntmental and Global SfM

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1225]
Thanks to your explanation, I basically learn the difference between Incremental and Global SfM.
When I look at the awesome 3D reconstruction list, I know that there are more approaches like Hierarchical SfM, Multi-Stage SfM and Non Rigid SfM. 
Now, would you please tell me these SfM methods are employed in openMVG or not?  Are there some branches for these SfM routine, please?
Sincerely,
Sherman

**Comment by pmoulon** [comment]
OpenMVG has implementation for:
- Incremental SfM https://hal-enpc.archives-ouvertes.fr/file/index/docid/769266/filename/moulon_monasse_marlet_adaptive_sfm_accv2012.pdf
- Global SfM https://hal-enpc.archives-ouvertes.fr/hal-00873504/document
- Hierarchichal (WIP that you test here: https://github.com/openMVG/openMVG/pull/1038)
