### ISSUE TITLE
What is the best way to get frames from a video?

### ISSUE THREAD

**Issue by DavidGilHidalgo** [openMVG/openMVG#1226]
I'm trying to get the best frames from a video.
I'm interested in getting frames that exceed a movement threshold.
What would be the best algorithm to achieve this?
Thanks

**Comment by pmoulon** [comment]
You can run feature tracking (KLT) and keep frames that have a average feature motion above a threshold.

**Comment by DavidGilHidalgo** [comment]
Hi, thanks for the answer.
I'm already using KTL but can't control whether a scene returns to the beginning, for example. 
I'd like to know how to detect loops in video motion to discard that part of frames.

**Comment by pmoulon** [comment]
In order to detect loop closure you must run feature matching and detection.
If you want to avoid exhaustive matching you can use https://github.com/dorian3d/DLoopDetector

**Comment by DavidGilHidalgo** [comment]
All right, I'll test it. Thank you very much and greetings!

**Comment by pmoulon** [comment]
Feel free to close the issue when you have all the answer to your question.
