### ISSUE TITLE
openMVG as third_party lib

### ISSUE THREAD

**Issue by yonelay11** [openMVG/openMVG#1227]
Now i successful install openMVG(develop branch) under this instructions https://github.com/openMVG/openMVG/blob/master/BUILD.md. I want to use openMVG as third_party lib. But, I don't know how to do and how to use. So, Firstly, I tried to test another people example like https://github.com/openMVG/openMVG/issues/1086. But, I face this error. 
**CMake Error at C:/Users/Yone/openMVG/OpenMVGConfig.cmake:47 (message):
  Failed to find OPENMVG - OpenMVG install root: C:/Users/Yone/openMVG.
  Cannot find openMVG include files.
Call Stack (most recent call first):
  C:/Users/Yone/openMVG/OpenMVGConfig.cmake:83 (OPENMVG_REPORT_NOT_FOUND)
  CMakeLists.txt:12 (find_package)

CMake Error at C:/Users/Yone/openMVG/OpenMVGConfig.cmake:48 (else):
  A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
  C:/Users/Yone/openMVG/OpenMVGConfig.cmake:83 (OPENMVG_REPORT_NOT_FOUND)
  CMakeLists.txt:12 (find_package)
**
Please Let me know how to solve this and how to use and where I made wrong.

**Comment by yonelay11** [comment]
When installing openMVG in https://github.com/openMVG/openMVG/blob/master/BUILD.md, said Perform make and make install. But I didn't do that. Where can I type this make and make install. I use window 10, cmake and visual studio 2015.
![openmvg1](https://user-images.githubusercontent.com/34397817/35769627-b377d258-0948-11e8-9db5-31a1afc592f9.png)

**Comment by pmoulon** [comment]
Please follow the instruction there:
https://github.com/openMVG/openMVG/blob/master/BUILD.md#windows-compilation

On windows, you can use cmake-gui and then choose your solution generator to fit Visual Studio 2015

**Comment by yonelay11** [comment]
Yes, firstly I tried to this one. Then, I used openMVG as third_party lib as I mentioned before. They show this error message **CMake Error at C:/Users/Yone/openMVG/OpenMVGConfig.cmake:47 (message):
Failed to find OPENMVG - OpenMVG install root: C:/Users/Yone/openMVG.
Cannot find openMVG include files.
Call Stack (most recent call first):
C:/Users/Yone/openMVG/OpenMVGConfig.cmake:83 (OPENMVG_REPORT_NOT_FOUND)
CMakeLists.txt:12 (find_package)

CMake Error at C:/Users/Yone/openMVG/OpenMVGConfig.cmake:48 (else):
A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
C:/Users/Yone/openMVG/OpenMVGConfig.cmake:83 (OPENMVG_REPORT_NOT_FOUND)
CMakeLists.txt:12 (find_package)**
Let me know where can I modified. Sorry for my question and I'm a new to openMVG user.

**Comment by yonelay11** [comment]
Now, I'm Ok with this error. Thank you and sorry for my burden.

**Comment by pmoulon** [comment]
-> https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-in-cmake
