### ISSUE TITLE
Compilation issue: call to "MatchesPairToMat" is ambiguous

### ISSUE THREAD

**Issue by KristianZarn** [openMVG/openMVG#1233]
I am trying to combine individual SfM steps into a single file in hopes to automate and further extend the process. I am basically copying the lines of code that I need from `openMVG_main_*.cpp` files. But i ran into compilation issues during _Filtering of putative matches_ step. 

The error seems to be, that the call to function `MatchesPairToMat` from file `openMVG/matching_image_collection/F_ACRobust.hpp` is ambiguous (This error seems to come from the library code and not from my file). 

Note: The library itself compiled without problems, and I already did many successful reconstructions using `openMVG_main_*` files.

Screenshot from clion:
![screenshot from 2018-02-17 23-17-03](https://user-images.githubusercontent.com/6253845/36346130-f19f8a9e-1438-11e8-82e6-a9a06de45afc.png)

This is my code so far:
[CMakeLists.txt](https://github.com/openMVG/openMVG/files/1734202/CMakeLists.txt)
[main.txt](https://github.com/openMVG/openMVG/files/1734203/main.txt)

Compilation output file:
[output.txt](https://github.com/openMVG/openMVG/files/1734204/output.txt)

**Comment by pmoulon** [comment]
According the output compilation log it seems related to includes:

```
F_ACRobust.hpp:127:36: error: invalid use of incomplete type ‘using element_type = struct openMVG::sfm::Regions_Provider {aka struct openMVG::sfm::Regions_Provider}’
         regionsI = regions_provider->get(iIndex),

note: forward declaration of ‘using element_type = struct openMVG::sfm::Regions_Provider {aka struct openMVG::sfm::Regions_Provider}’
   struct Regions_Provider;
```
Please ensure to include the Regions provider.
`#include "openMVG/sfm/pipelines/sfm_features_provider.hpp"`

**Comment by KristianZarn** [comment]
Thank you for your quick reply.
I added the include line that you suggested, but I am still getting the same error as before.

Note: now I am including both `sfm_regions_provider.hpp` and `sfm_features_provider.hpp`

**Comment by pmoulon** [comment]
I did not got the time to look to your issue deeply yet.
I will try during the week end.

**Comment by pmoulon** [comment]
Sorry I did not got the time to look to it.
You can force a cast of some function parameter to make the function call not ambiguous.

**Comment by KristianZarn** [comment]
I solved it now. The issue was in the order of includes. The solution was to include

`#include "openMVG/sfm/pipelines/sfm_regions_provider.hpp"` **before** 
`#include "openMVG/matching_image_collection/F_ACRobust.hpp"`

If the includes are switched, then i get the error.
