### ISSUE TITLE
using openMVG_main_GlobalSfM out of the openMVG pipeline

### ISSUE THREAD

**Issue by rfale** [openMVG/openMVG#1242]
Hello Pierre,

I'm interested in using the openMVG_main_GlobalSfM tool, starting from a set of image points correspondences generated by an external application leveraging some domain specific logic i.e. not using the standard features detection and matches of the library.

From the documentation it seems possible:
Require: internal camera calibration (possibly from EXIF data)
Require: pairwise geometry consistent point correspondences
Ensure: 3D point cloud
Ensure: camera poses

I can build the sfm_data for views and intrinsic (estimate) but i don't know how to provide the list of the correspondences.

Can you provide feedback if the task is doable and/or suggest how to proceed?
Thanks in advance for your help.

**Comment by pmoulon** [comment]
The task is doable.
Sorry if it is not well documented but some help are provided here https://github.com/openMVG/openMVG/issues/1228#issuecomment-363234777 and some people succeed to do it.

**Comment by rfale** [comment]
Thanks Pierre,

You are right, the response can be found by browsing other similar solved issues.

I could do it just just doing that. To facilitate others, here the full procedure i followed:

1) create a directory (e.g. named matches) and copy in it any previously generated image_describer.json (here the one I used: 
[image_describer.zip](https://github.com/openMVG/openMVG/files/1777468/image_describer.zip)

2) create a file in the same directory named sfm_data.json with at least the sfm_data_version, views and intrinsics sections (the format of the file can be almost easily gathered form any previous example, just pay attention to:
	- the ids for the polymorphic_id descriptors, the corresponding names, and the ptr_wrapper id, which seems necessary just for the de-serializer internal use (see also #821 ) 
	- in the view section it is required to fill the filename values. It is not important that the image files axist, but the name seams to be used to to build the the features data filenames (see next)
	Here the one I used: [sfm_data.zip](https://github.com/openMVG/openMVG/files/1777462/sfm_data.zip) 
(I used a very poor serializer on my app side, so the LF characters are missing, but the library does not care)
3) Create the files for the features data (in the same directory as the others): the files must be named as the image file valued in the views section of sfm_data, substituting  the extension with ".feat".
	- the format of the *.feat files is the following:
	X Y scale orientation
	where X Y are the coordinates of the features in the image coordinate system (the standard one assumed when setting the Intrinsic values in the sfm_data file)
	scale and orientation are not relevant if not going to use the library matcher, so they can be set to any value (I used 1 0). Here my example: 
[features.zip](https://github.com/openMVG/openMVG/files/1777471/features.zip)
(see also #533 )
4) Create the file matches.e.txt (in the same directory as the others).
	The file reports for pairwise matches for each of the view pairs where the matches are known.
	The format of the file is:
	ViewIDx ViewIDy
	total number of matches between View_x and View_y
	feature_id_view_x feature_id_view_y
	feature_id_view_x feature_id_view_y
	....
	ViewIDx ViewIDz
	total number of matches between View_x and View_z
	feature_id_view_x feature_id_view_z
	feature_id_view_x feature_id_view_z
	....
	ViewIDAny ViewIDANyOther
	...
	where the feature_id of a view is the line number of the feature in the corresponding feature file.
	here my example [matches.e.txt.zip](https://github.com/openMVG/openMVG/files/1777470/matches.e.txt.zip)
(note: this example can be misleading because is a very special case where there is full matching for each feature in each view and the order of the matching features is the same in each view) 

5) Create a directory to store the results (e.g. out_Global_Reconstruction)
6) run the global sfm tool: (e.g. openMVG_main_globalSFM.exe -i sfm/matches/sfm_data.json -m sfm/matches/ -o sfm/out_Global_Reconstruction/)
7) see the results (see how to visualize SFM results? #1179 for info about the result output)
8) Optionally convert the  out_Global_Reconstruction\sfm_data.bin to an sfm_data.json to get direct access to the extrinsics and the structure of the scene, using openMVG_main_ConvertSfM_DataFormat.exe -i sfm/out_Global_Reconstruction/sfm_data.bin -o sfm/out_Global_Reconstruction/sfm_data.json


Thanks again for this outstanding library.
