### ISSUE TITLE
ComputeStructureFromKnownPoses for Spherical camera

### ISSUE THREAD

**Issue by happyfrank** [openMVG/openMVG#1245]
First, thanks for provide this great feature. I think that is what I really want.

Today I test ComputeStructureFromKnownPoses for Spherical camera by following this pipeline [https://github.com/openMVG/openMVG/issues/1214](url)

    1 set and fill your scene (sfm_data.json) with views, intrinsics and poses
    2 Compute Features
    3 Compute Matches
    4 ComputeStructureFromKnownPoses (You can called the option to triangulate a match file (matches.f.bin))

```
./openMVG_main_ComputeStructureFromKnownPoses -i ~/testdata/result/matches/sfm_data.json -f ~/testdata/result/matches/matches.f.bin  -m ~/testdata/result/matches -o ~/testdata/result/reconstruction_sequential
```
At the result I can't get the structure.

Debug message:
```
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 8
 #poses: 8
 #intrinsics: 1
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================
can't find linker symbol for virtual table for `C_Progress_display' value
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

Structure estimation took (s): 9846.

#landmark found: 0
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 8
 #poses: 8
 #intrinsics: 1
 #tracks: 0
```
[testdata](https://drive.google.com/open?id=15WK8ut42t-QBSinjlmJp_0HoLd7GKrTF)

In my application the Spherical camera intrinsics and poses was already known through SLAM algorithm.
So I'm wondering Can I use openMVG_main_ComputeStructureFromKnownPoses for adjust the camera pose. then the camera poses can be more accurate?

Thanks, Wish you have a nice day. ^v^

**Comment by DHNicoles** [comment]
@happyfrank Hi, I was looking for how to import the known poses of 360camera into the sfm_data.json file, but I couldn't find it.  Is there an example of using ComputeStructureFromKnownPoses for a spherical camera?

**Comment by pmoulon** [comment]
@happyfrank I would now recommend to use IncremetalSfM2 that allow to use existing camera poses and triangulate a match file. See here https://github.com/openMVG/openMVG/issues/1892
