### ISSUE TITLE
[multiview] Add an orthographic essential matrix solver

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1246]
Add an implementation of the 3pt Orthographic essential matrix solver from [1].

This solver works best for planar scene or for long focal camera. It can be used to filter pairwise correspondences for UAV field acquisition in a very effective maner (the solver is fast and use only 3pt).

[1] **Two-View Orthographic Epipolar Geometry: Minimal and Optimal Solvers**, Magnus Oskarsson,  Journal of Mathematical Imaging and Vision, 2017.

**Comment by pmoulon** [comment]
@rjanvier Thx for this contribution. Let's wait the CI status ;-)
@mitjap, @ManishSahu53, @igorti Can be of interest for a blazing fast pre-filter ;-)
- How to use it?
   - ComputeMatches `-g o`,
   - then you can supply the computes matches to any SfM pipeline -m <PATH>/matches.o.bin

Todo: Add the ref in https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/bibliography.rst

**Comment by igorti** [comment]
Thanks, @pmoulon, I'll give it a try and let you know about results!
