### ISSUE TITLE
How does OpenMVG choose the origin of the world coordinate system?

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1247]
Hi, OpenMVG outputs camera poses with respect to a world coordinate system, I would like to know, what is the world origin or how does OpenMVG choose the origin of the world coordinate system? Is it an arbitrarily chosen position? I cannot get any clues from the docs. Thank you!

**Comment by pmoulon** [comment]
One camera is set with an identity transform by each SfM pipeline and then the BA can move the scene freely.

**Comment by squashking** [comment]
@pmoulon Sorry, I don't understand. Do you mean one camera center is chosen as the world origin? I convert the sfm_data.bin file into json file and open it, but I cannot see any camera is with identity transform (Identity rotation matrix) or 0 translation.

**Comment by pmoulon** [comment]
As I said, during the process, at one time a camera is set with identity transform and then BA will move the scene and so the entire scene will move.

-> If you want every time to have one camera with identity transform you can apply a pose.inverse() to the scene and set one camera as identity.

**Comment by squashking** [comment]
@pmoulon sorry I'm not familiar with the sfm process. you said each time one camera is set with identity transform, so when sfm finishes, there should be one camera with identity transform, right? But from the output I cannot see any camera with identity transform. where is the origin then? Is the origin a deterministic one or can be different for different runs of sfm? Thank you!

**Comment by ShreyanshGoyal17** [comment]
> As I said, during the process, at one time a camera is set with identity transform and then BA will move the scene and so the entire scene will move.
> 
> -> If you want every time to have one camera with identity transform you can apply a pose.inverse() to the scene and set one camera as identity.

@pmoulon How and where does one apply the pose.inverse() to the scene and set one camera as identity? Furthermore, how will that affect the results (other camera poses)?
I am planning to fix my first camera itself as identity so I can have the all the other camera poses with respect to that cam.
