### ISSUE TITLE
Eigen Scalling the 3D coordinate

### ISSUE THREAD

**Issue by mohit-thakur-721** [openMVG/openMVG#1259]
HI, 
In My 3D coordinates the values are too small because of that I think there are precision errors too. My data contains the drone images of locality  from 100 ft heights. But when I see the 3D coordinate I found that the values are really small. I don't want to apply any Real coordinate on this model, but I want that there should be less precision error.

For this I have an idea of changing the homogeneous Factor of Eigen homogeneous method. this factor is by default 1. If I reduce the value of this factor to .1 then My 3D coordinate will be scaled by 10 times before the incremental error apply on this.

I have tried to modify some of the Eigen files but because of lazy expression handling in Eigen the effect of my changes were not applied on entire solution specially where this homogeneous value is multiplied by other vector.

Can any one suggest me how to correctly update the homogeneous factor of Eigen. 
Or any other method two uniformly increase the Scale of my coordinate before the Triangulation and Bundle Adjustment.

**Comment by mohit-thakur-721** [comment]
Hi, I have scaled my coordinate by an alternative approach, which is as follow:
I have updated the sequential_sfm.cpp and recreated the relative pose (the second pose of initial pair) after the call of API robustRelativePose. In the newly created pose I have scaled the centre value by 10 times. And wow this works exactly same as I want. all my 3D coordinate are scaled by 10 times and camera poses also.

**Comment by pmoulon** [comment]
Can you close the issue.

FYI, you can also rescale the sfm_data reconstruction at any time by using this function:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_transform.hpp#L24

**Comment by mohit-thakur-721** [comment]
Hi,

Thanks for answering. 

>FYI, you can also rescale the sfm_data reconstruction at any time by using this function:
>https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_transform.hpp#L24
This is the apply similarity method which I can apply after computing whole sfm_data. and also for this I need to compute the similarity matrix too.
What I wanted to scale the coordinate system which is generated by OpenMVG. I know my approach is not good this time, for this I need to investigate how the open MVG decide the distance between cameras of initial pair.
