### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xuhuanzhimeng** [openMVG/openMVG#1261]
I use cmake and then build the release project. 
I meet many error while building.
The following error appear many times. 

D:\openMVG\src\openMVG/matching/metric.hpp(100): error C2899: cannot use the type name outside the template declaration
D:\openMVG\src\openMVG/geometry/pose3.hpp(106): error C2899: cannot use the type name outside the template declaration
LINK : fatal error LNK1181: cannot open input file“..\..\Windows-AMD64-Release\Release\openMVG_features.lib”
D:\openMVG\src\openMVG/multiview/rotation_averaging_common.hpp(55): error C2958: the left “[”(found at “d:\openmvg\src\openmvg\multiview\rotation_averaging_common.hpp(55)”)was not matched correctly
D:\openMVG\src\openMVG/multiview/rotation_averaging_common.hpp(55): error C2143: Syntax error: lack“]”(in front of “}”)
D:\openMVG\src\openMVG/multiview/rotation_averaging_common.hpp(55): error C2143: Syntax error: lack“;”(in front of “}”)
D:\openMVG\src\openMVG/multiview/rotation_averaging_common.hpp(55): error C2059: Syntax error:“]”

Totally more than 100 errors. Finally 29 projects successful and 52 failed . I wonder what's the matter?

**Comment by Yannnnnnnnnnnn** [comment]
Do you use Visual Studio VS2015(or higher) to compile the code?

**Comment by xuhuanzhimeng** [comment]
Of course , I use 
Microsoft Visual Studio Professional 2015
edition 14.0.23107.0 D14REL
I wonder do I have the necessity to install another edition and try again?

**Comment by Yannnnnnnnnnnn** [comment]
I think maybe you can put out your cmake information here for us to look into.

**Comment by xuhuanzhimeng** [comment]
The C compiler identification is MSVC 19.0.23026.0
The CXX compiler identification is MSVC 19.0.23026.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
target changed from "" to "auto"
Detected CPU: ivy-bridge
Performing Test check_c_compiler_flag__arch_AVX
Performing Test check_c_compiler_flag__arch_AVX - Success
Performing Test check_cxx_compiler_flag__arch_AVX
Performing Test check_cxx_compiler_flag__arch_AVX - Success
Checking for C++11 compiler
Checking for C++11 compiler - available
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
Eigen 3.3.4 found (include: D:/openMVG/src/third_party/eigen)
Flann 1.8.4 found (include: D:/openMVG/src/third_party/flann/src/cpp/flann)
CoinUtils 2.10.13 found (include: D:/openMVG/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.16.10 found (include: D:/openMVG/src/dependencies/osi_clp/Clp/src)
Osi 0.107.8 found (include: D:/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
Lemon  found (include: D:/openMVG/src/third_party/lemon/lemon)
Found PythonInterp: D:/python/python.exe (found version "3.6.4") 
Could NOT find Wget (missing: WGET_EXECUTABLE) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE) 
Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of long long
Check size of long long - done
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Looking for stdlib.h
Looking for stdlib.h - found
Looking for assert.h
Looking for assert.h - found
Looking for fcntl.h
Looking for fcntl.h - found
Looking for io.h
Looking for io.h - found
Looking for jbg_newlen
Looking for jbg_newlen - not found
Looking for mmap
Looking for mmap - not found
Looking for search.h
Looking for search.h - found
Looking for string.h
Looking for string.h - found
Looking for unistd.h
Looking for unistd.h - not found

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
Detected Ceres version: 1.13.0 from D:/openMVG/src/third_party/ceres-solver/include/ceres/version.h
Eigen 3.3.4 found (include: D:/openMVG/src/third_party/eigen)
-- Found Eigen version 3.3.4: D:/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
-- Did not find LAPACK library, disabling LAPACK support.
-- Did not find BLAS library, disabling LAPACK support.
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
Performing Test COMPILER_HAS_CXX11_FLAG
Performing Test COMPILER_HAS_CXX11_FLAG - Success
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Performing Test HAVE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS
Performing Test HAVE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS - Success
Creating configured Ceres config.h output directory: D:/openMVGbuild/third_party/ceres-solver/config/ceres/internal
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================
CMake Warning at third_party/eigen/CMakeLists.txt:67 (message):
  EIGEN_INCLUDE_INSTALL_DIR is deprecated.  Use INCLUDE_INSTALL_DIR instead.



Configured Eigen 3.3.4

CMake Warning at openMVG_Samples/describe_and_match_GUI/CMakeLists.txt:4 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/VO/AlternativeVO/CMakeLists.txt:6 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/CMakeLists.txt:14 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


** Qt5 not found, GUI modules will not be build
Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation


** OpenMVG version: 1.3.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI: 0.107.8 (internal)
LEMON: 1.3 (internal)


Configuring done

That's cmake information. I only found that "qt5" was not found and other information are normal(I think). And I didn't change any value. I press confiure again and generate and then open Project,change the target to Release and compile,then those error came.

**Comment by Yannnnnnnnnnnn** [comment]
One more quesiton, do u select win10 SDK when you install the VS2015?
![](http://img.blog.csdn.net/20171204172419093?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMjM0ODc3NA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

I tried my openMVS just now and the only difference is:
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.

**Comment by xuhuanzhimeng** [comment]
I don't select the win10 SDK. Just now I try to update win10 sdk and found "Can’t start SecondaryInstaller error"
Maybe my vs2015 is not complete. I will try to install another one and try again!

**Comment by xuhuanzhimeng** [comment]
I use another vs2015 installer and still "Secondary Installer Setup Failed". And openMVG still can't be correctly compiled. I wonder if the problem causes the openMVG compiling error. My vs2015 can work in a simple program.

**Comment by Yannnnnnnnnnnn** [comment]
I have met this problem before and my solution is what I had told u above.
This problem is caused, as you mentioned,  by the incomplete VS2015. 
We know that the VS2015 doesn't install VC++ by default, so it becomes very common to forget select all the components VC++ need. 
You have to select the win10 SDK, otherwise you cannot compile some code correctly, even though some simple programs are okay.

By the way, I dont't know what is "Secondary Installer Setup Failed".

**Comment by pmoulon** [comment]
Perhaps due to the many installation your c++ compiler is in a strange state.
Can you try in a windows VM with a fresh install?
