### ISSUE TITLE
FindFlann.cmake missing linker flag -llz4.

### ISSUE THREAD

**Issue by bartoszek** [openMVG/openMVG#1265]
I stumble on a problem with [src/cmakeFindModules/FindFlann.cmake](https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/cmakeFindModules/FindFlann.cmake)
It uses custom, cmake script, where [openMVG/src/third_party/flann/cmake/FindFlann.cmake](https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/third_party/flann/cmake/FindFlann.cmake) uses `pkg-config`.
On my system, `flann` requires `-llz4` flag (flann:v1.9.1) which gets included when using `pkg-config` based `FindFlann.cmake` (the `FLANN_DEFINITIONS` variable).
Could we combine those two, first import `pkg-config` and check if it finds `flann` and if not resolve to `find_path()`
_refers to: openmvg#branch=develop_

_Also `fast` is missing from `target_link_libraries` in `software/VO`_
_Also `lemon` insted of `emon` is used in `software/colorHarmonize/CMakeLists.txt`_

**Comment by pmoulon** [comment]
Feel free to help on this.

**Comment by pmoulon** [comment]
> Also fast is missing from target_link_libraries in software/VO
Also lemon insted of emon is used in software/colorHarmonize/CMakeLists.txt

The CI does not complain about that.
Did you use a special setup?

**Comment by bartoszek** [comment]
> fast should not be a problem.

Yes, there was my mistake. I drop all caches and `openmvg` rebuilds fine, without `fast.patch`. But ...

_colorHarmonize_
> The CI does not complain about that.
Did you use a special setup?

I'm using system `coin-or-lemon` package (v1.3.1) which provides both static and shared lib. When building with `lemon(internal)` there is no error, with `lemon(external)` i got this error form `make`:
```
/usr/bin/ld: cannot find -llemon
collect2: error: ld returned 1 exit status
make[2]: *** [software/colorHarmonize/CMakeFiles/openMVG_main_ColHarmonize.dir/build.make:134: Linux-x86_64-RELEASE/openMVG_main_ColHarmonize] Error 1
make[1]: *** [CMakeFiles/Makefile2:3782: software/colorHarmonize/CMakeFiles/openMVG_main_ColHarmonize.dir/all] Error 2
```
In `colorHarmonize/CMakeFiles/openMVG_main_ColHarmonize.dir/link.txt` there is a correct flag `-lemon` and also an incorrect one `-llemon`.
Can't figure out what is going wrong, but changing `lemon` to `emon` in `software/colorHarmonize/CMakeLists.txt` seams to fixes the issue.

**Comment by StefanBruens** [comment]
Current flann provides a proper CMake Config file, which provides `flann::flann` and `flann::flann_cpp` targets. This automatically adds transitive dependencies like liblz4 when using e.g. `flann::flann` in target_link_libraries.

https://github.com/flann-lib/flann/commit/7a6db721c490b85c007042e6a0f871183f3003b5

Option 1: Drop FindFlann.cmake, just use proper cmake targets
Option 2: Add a `find_package(Flann CONFIG QUIET)` call to the top of FindFlann.cmake, and set matching variables for backwards compatibility.
