### ISSUE TITLE
openMVG, main_pano_converter.cpp

### ISSUE THREAD

**Issue by Huang88888888Fei** [openMVG/openMVG#1276]
How to set the parameter: image_resolution and nb_split, to make the image distortion minimal?
Chinese Meaning: 如何设置参数（图像分辨率和切片数量），使得全景图像的畸变最小化？

**Comment by Yannnnnnnnnnnn** [comment]
Because the FOV of converted images is fixed around 120 degrees. So if you want to minimize the distortion, you have one choice: update the code and lower the FOV(main_pano_converter.cpp line 117).
The resolution and nb_split has nothing to do with the image distortion.
Here some test.(They have the same resolution and nb_split)
FOV 120:
![1_0](https://user-images.githubusercontent.com/17909171/38497061-576a05a4-3c32-11e8-9b39-88383e881e80.jpg)
FOV 60:
![1_0](https://user-images.githubusercontent.com/17909171/38497067-5face10a-3c32-11e8-9baa-76583a022115.jpg)

**Comment by pmoulon** [comment]
@Huang88888888Fei Can you explain where do you see image distortion?
Since we are generating the pinhole images by projecting the spherical image to the pinhole image plane, every produced images are without any spherical distortion.

**Comment by Huang88888888Fei** [comment]
@Yannnnnnnnnnnn Thanks for your answer! But I do not find the way updating the code to lower the FOV(main_pano_converter.cpp line 117). Maybe the versions of our OpenMVG are different. Could you please say a little more detailed or cut a picture? Thank you!

**Comment by Huang88888888Fei** [comment]
@pmoulon 
[test.zip](https://github.com/openMVG/openMVG/files/1892783/test.zip)
You can see that people in the picture(test/testout/1_2.jpg) is malformation.

**Comment by Yannnnnnnnnnnn** [comment]
@pmoulon I supposed he was talking about perspective distortion. @Huang88888888Fei Right?

**Comment by Huang88888888Fei** [comment]
@Yannnnnnnnnnnn @pmoulon Hmmm...I just think that picture is a little strange. So I am try to find a way to adjust the paramter to make the pictures more like monocular picture. Because I want to input the pictures into SLAM.  Therefore, I want to know how to calculate the best paramters(like image_resolution and nb_split or FOV) according to the original panoramic picture. Thank you!

**Comment by Yannnnnnnnnnnn** [comment]
What do you mean "more like monocular picture" ?_?
As the code makes the width=height, so that the vertical fov equas the horizontal fov. You can update these to meet your need.

**Comment by Huang88888888Fei** [comment]
@Yannnnnnnnnnnn I mean the picture 1_2.jpg is so strange that it is not like a monocular picture. You can see the face of the people is uncoordinated. But if we use a monocular camera, it can not be like that.
![1_2](https://user-images.githubusercontent.com/38203112/38539062-1e255c2a-3cc9-11e8-8bfd-3fc6cba66138.jpg)

**Comment by Huang88888888Fei** [comment]
@Yannnnnnnnnnnn @pmoulon So, according to the original panoramic picture, how to set the parameters is the best? Thank you!
