### ISSUE TITLE
.ply file format

### ISSUE THREAD

**Issue by yonelay11** [openMVG/openMVG#1277]
Hello ,
May I ask something help for my project.
I want to use the .ply that are generated from openMVG in PCL pointCloudSegmentation to segment. But, when I reading .ply file in PCL library, there has no coordinates values of x,y,z and they show all values are zeros. These .ply output can be viewed in MeshLab, it is Ok and show the point clouds. But,in PCL, it can't show anything.  I don't know where they miss. Please help me. I'm looking forward to your reply.

**Comment by pmoulon** [comment]
Do you have any way to debug in PCL?

If you want you can also export the 3D from the sfm_data file.
1. Use ConvertSfMDataFormat to convert from the sfm_data.bin to sfm_data.json.
2. Use the json reader of your choice to read the 3D landmark position and send them to PCL.

**Comment by yonelay11** [comment]
Thank for your quickly reply. I will try it

**Comment by yonelay11** [comment]
Hi,
I tried as your suggestion. But, I don't know how to extract 3D points from .json file.

**Comment by yonelay11** [comment]
Now, I successfully export .ply file into PCL library. This is very helpful for me. Thank you !!!

**Comment by pmoulon** [comment]
Great!
