### ISSUE TITLE
'global view selection failed'  help me!!

### ISSUE THREAD

**Issue by ltj95** [openMVG/openMVG#1279]
I had done  '<<mvg2mve2'  and got a file "MVE"  ,but when I am doing this step '<<sfmrecon'  and '<<dmrecon -s2' ,the code had no error ,but it shows me 'global view selection failed'.Now i have no idea  who canhelp me????
 
another question is, in the file  "match" ,the 'cloud＿and＿poses.ply 's  memory is smaller than tha last  'resection.ply' . why？ I just used 70 pictures.
现在遇到一个问题，我生成的match文件夹中的cloud＿and＿poses.ply比最后一个'resection.ply'内存小，点变少了。现在我在做<<sfmrecon 和<<dmrecon -s2时也就是降采样，程序没有报错，但是运行过程中显示global view selection failed ,有大佬知道怎么解决吗？ ？   救急

**Comment by Yannnnnnnnnnnn** [comment]
There is no need to use sfmrecon anymore, the openMVG has done this part job.

**Comment by ltj95** [comment]
thk for comment .I think it's not a question,I had ever done reconstruction successfully.now i can't solve the issue 'global view selection failed' can you help me?

**Comment by Yannnnnnnnnnnn** [comment]
Have you tried other dataset([Castle](https://github.com/openMVG/ImageDataset_SceauxCastle))?
I think maybe the dataset you use is not suitable to do mvs.

**Comment by pmoulon** [comment]
@ltj95 Any feedback?
