### ISSUE TITLE
openmvg-team google group

### ISSUE THREAD

**Issue by FreakTheMighty** [openMVG/openMVG#128]
Is it possible to subscribe to the openmvg-team google group? I can't seem to find it.

**Comment by MaxNe** [comment]
Is it possible to import external depth maps into the pipeline of openmvg?
I would like to use these external depth maps instead of the generated depth maps in MVS

**Comment by pmoulon** [comment]
I don't understand exactly what you want to do?

Load depth map on camera position found by openMVG?
or 
Use depth map during the SfM process?
