### ISSUE TITLE
OpenMVG shouldn't install eigen

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1282]
It installs eigen into the root:
```
/eigen3/Eigen/Cholesky
/eigen3/Eigen/CholmodSupport
/eigen3/Eigen/Core
/eigen3/Eigen/Dense
```
It shouldn't do this.
```devel``` branch.

**Comment by pmoulon** [comment]
Can you tell me if you are using the internal or the external Eigen (this information is displayed at the end of the configure log of cmake)?

A safe guard is used here to check if we need to: https://github.com/openMVG/openMVG/blob/develop/src/third_party/CMakeLists.txt#L108
As you see we ask Eigen to install in `${CMAKE_INSTALL_PREFIX}/include/openMVG/third_party/eigen`. 

As we has detected here Eigen has a trouble overwriting the value that you set in some case:
https://github.com/openMVG/openMVG/pull/1118#issuecomment-343679981

Any help on this is more than welcomed.

**Comment by yurivict** [comment]
```EIGEN: 3.3.4 (internal)```

**Comment by yurivict** [comment]
It also installs these libs that are built from the dependency projects:
```
lib/libceres.a
lib/libcxsparse.a
lib/libeasyexif.a
lib/libfast.a
lib/liblemon.a
lib/liblib_CoinUtils.a
lib/liblib_Osi.a
lib/liblib_OsiClpSolver.a
lib/liblib_clp.a
```

```lib/libceres.a```, for example, can conflict with the ```ceres-solver``` package.

**Comment by pmoulon** [comment]
It's seems that in your case you are not using external libraries fro ceres and lemon and Osi.

Can you share your cmake log to help me see if cmake is telling (internal or external)?
