### ISSUE TITLE
openMVG_main_ComputeStructureFromKnownPoses error: Unknown sfm_data export format

### ISSUE THREAD

**Issue by squashking** [openMVG/openMVG#1283]
Hi, in my application cameras are calibrated so the intrinsics and poses are known. I would like to use openMVG_main_ComputeStructureFromKnownPoses for 3D reconstruction. I'm not sure whether I used it correctly. My pipeline is:
1. openMVG_main_SfMInit_ImageListing 
    In this step, I obtained sfm_data.json, and I added camera poses ("extrinsics") to the file
2. openMVG_main_ComputeFeatures
3. openMVG_main_ComputeMatches
4. openMVG_main_ComputeStructureFromKnownPoses  -i   path/to/sfm_data.json   -m   path/to/matches/directory   -o   path/to/output/directory
I got a message in step 4: Unknown sfm_data export format:
And SFM stopped.

My questions:
Is my pipeline correct? What could be the reason? Thank you very much!

**Comment by squashking** [comment]
@pmoulon Could you please tell me if my pipeline is correct? Thank you very much!

**Comment by pmoulon** [comment]
It seems ok. Did you check that you have valid features and matches?
You can use the binary exportMatches and exportKeypoints to check visually the output...

**Comment by squashking** [comment]
@pmoulon Yes. there seem to be valid features and matches. For each view there are a .feat and a .desc file. Also I checked the visual output of exportMatches and exportKeypoints, both seem to be fine. But openMVG_main_ComputeStructureFromKnownPoses only produces two files: residuals_histogram.svg and SfMStructureFromKnownPoses_Report.html. Below is the whole ouput:

Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 6
 #poses: 6
 #intrinsics: 6
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************
***************************************
*
*
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*******************************************
*********
*
*

Structure estimation took (s): 5.

#landmark found: 7
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 6
 #poses: 6
 #intrinsics: 6
 #tracks: 7
Unknown sfm_data export format: 
Unknown sfm_data export format:

Did I do something wrong? Thank you very much!

**Comment by squashking** [comment]
@pmoulon I have found out the reason. I should specify a path with a file name for "-o" instead of just a path without a file name. 
But now I have another question. I first ran IncrementalSfM, and got good reconstruction results. Then I used the intrinsics and extrinsics values to populate a scene description file (sfm_data.json) , and executed the pipeline for openMVG_main_ComputeStructureFromKnownPoses, But I got very poor results. In theory, given the same estimated intrinsics and extrinsics, the results from StructureFromKnownPoses and IncrementalSfM should be close, right?

**Comment by pmoulon** [comment]
Please note that `StructureFromKnownPoses` and `IncrementalSfM` does not use the same algorithm for computing the matches.

If you want to obtain more or less the same track with `StructureFromKnownPoses` you can triangulate a match file. The default option does not use any match file and triangulate tracks of length > 3.

See the help of the binary:
```
[Triangulation mode]:
 [No Provided Matches -> Triangulation of guided epipolar geometry matches (default mode)]
	[-p|--pair_file] path to a pairs file (only those pairs will be considered to compute the structure)
	[-f|--match_file] path to a matches file (loaded pair indexes will be used)
 [Provided Matches -> Robust triangulation of the match file (activated by -d)]
	[-d|--direct_triangulation] Robustly triangulate the tracks computed from the file given by [--f|--match_file]
	[-f|--match_file] path to a matches file (loaded pair indexes will be used)
```

**Comment by squashking** [comment]
@pmoulon  do you mean running it like this:
openMVG_main_ComputeStructureFromKnownPoses -i /path/to/sfm_data.json -f /path/to/matches.f.bin  -o /path/to/results.ply
I tried running the above command but got error message:
****Invalid regions files for the view: **/path/to/image.jpg*...

Am I running in the right way? Thank you very much!

**Comment by squashking** [comment]
@pmoulon I first did reconstruction and exported the camera poses using IncrementalSfM, and then used the camera poses for StructureFromKnownPoses. I triangulated the match file as you said, but I got a much worse reconstruction result than using IncrementalSfM, not "more or less the same track" as you said. Is it because ComputeStructureFromKnownPoses keeps only the 3d points that are seen by at least 3 cameras? I read your post in another thread which mentioned this. Is there a way to get the same result as IncrementalSfM using ComputeStructureFromKnownPoses?

**Comment by pmoulon** [comment]
To have all the track triangulated with `ComputeStructureFromKnownPoses` you should use the option:
`-d -f <path_to_match_file>`

**Comment by squashking** [comment]
@pmoulon I used the -f option but still got very poor result. Here is how I ran the command:
openMVG_main_ComputeStructureFromKnownPoses -i /path/to/matches/sfm_data.json -m /path/to/matches/ -f /path/to/matches/matches.f.bin -o /path/to/out_results/sfm_data.bin
Then I converted sfm_data.bin to ply format and saw very poor result. But the result from IncrementalSfM is good. I don't know what is wrong.

**Comment by squashking** [comment]
@pmoulon sorry, it turns out that i didn't turn on the -d option.
