### ISSUE TITLE
Noob at getting build samples 

### ISSUE THREAD

**Issue by benadame1** [openMVG/openMVG#1291]
I am a total noob at this but I would like to know how to get a build sample and actually run it on my computer. My build has succeeded when i did the mac compilation  but when i try to use this sample it get this error on terminal does anyone know the issue?
benjamins-MacBook-Pro:~ benjaminadame$ cd openMVG_Build/software/SfM/
benjamins-MacBook-Pro:SfM benjaminadame$ python SfM_SequentialPipeline.py ~/home/user/data/ImageDataset_SceauxCastle/images ~/home/user/data/ImageDataset_SceauxCastle/Castle_Incremental_Reconstruction
('Using input dir  : ', '/Users/benjaminadame/home/user/data/ImageDataset_SceauxCastle/images')
('      output_dir : ', '/Users/benjaminadame/home/user/data/ImageDataset_SceauxCastle/Castle_Incremental_Reconstruction')
Traceback (most recent call last):
  File "SfM_SequentialPipeline.py", line 45, in <module>
    os.mkdir(output_dir)
OSError: [Errno 2] No such file or directory: '/Users/benjaminadame/home/user/data/ImageDataset_SceauxCastle/Castle_Incremental_Reconstruction'
benjamins-MacBook-Pro:SfM benjaminadame$ 

So sorry if it is a dumb question and there is an explainable answer to this that i just haven't though of.

**Comment by pmoulon** [comment]
Hi @benadame1 
This is a know issue. Please open the file SfM_SequentialPipeline.py and remove the last `Release` in the line `OPENMVG_SFM_BIN`.
Tell me if it fix the issue or not?

**Comment by benadame1** [comment]
It did not fix the issue.

**Comment by benadame1** [comment]
Do you mean to remove the last release meaning the whole line or just the second time where it says release because i removed the second word and it still came out with the same error.


OPENMVG_SFM_BIN = "/Users/benjaminadame/openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/"

**Comment by pmoulon** [comment]
What is happening if you are using:
`OPENMVG_SFM_BIN = "/Users/benjaminadame/openMVG_Build/Darwin-x86_64-RELEASE/"`

**Comment by benadame1** [comment]
The same exact thing

**Comment by pmoulon** [comment]
Can you look where the binaries (openMVG_main_SfMInit_ImageListing, openMVG_main_ComputeFeatures) are built?
This is the path that have to be specified there.

**Comment by benadame1** [comment]
They are all built, so the path has to be specified to one of these builds?

**Comment by pmoulon** [comment]
Yes, the path should point to the folder name that contains those binaries.

**Comment by benadame1** [comment]
I changed the path still gives me the same error.

**Comment by benadame1** [comment]
OPENMVG_SFM_BIN = "/Users/benjaminadame/openMVG_Build/software/SfM/openMVG.build/Release"

**Comment by pmoulon** [comment]
You have to change the path in your python file.

**Comment by benadame1** [comment]
I changed the path still didn't work, however i ran the $python
tutorial_demo.py and it cloned a folder but then it gave me this error

The input SfM_Data file
"/Users/benjaminadame/openMVG_Build/software/SfM/tutorial_out/reconstruction_global/sfm_data.bin"
cannot be read.

benjamins-MacBook-Pro:SfM benjaminadame$

**Comment by pmoulon** [comment]
Can you share the output log when you run a script so this way we can better understand what's going on?

**Comment by benadame1** [comment]
Beside the sample, is it possible to test my own photos that I take of
something. And use the same py script?

**Comment by pmoulon** [comment]
Yes the Sequential and Global python script are made for this.
See https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#openmvg-sfm-pipelines-demo

BTW, if the python scripts does not run you can still launch the command line by hand.

**Comment by pmoulon** [comment]
Seems the same error as before. The path `OPENMVG_SFM_BIN ` seems incorrect and point where your binaries are compiled.

Please ensure that you have the `openMVG_main_SfMInit_ImageListing ` binary compiled
