### ISSUE TITLE
There are some errors when using openmvg-develop as a library

### ISSUE THREAD

**Issue by InomnipotentComedy** [openMVG/openMVG#1293]
**I wrote this test code below.**

`#include <iostream>
#include "openMVG/sfm/sfm.hpp"

using namespace std;

int main(int argc, char **argv) {
    std::cout << "Hello, OpenMVG" << std::endl;
    return 0;
}`

`cmake_minimum_required(VERSION 3.0)
project(helloopenmvg)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_PREFIX_PATH "/home/owen/Libs/openMVG_develop_install")
include_directories("/usr/include/eigen3")
include_directories("/home/owen/Libs/openMVG_develop_install/include/openMVG")
find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
add_executable(helloopenmvg main.cpp)
target_link_libraries(helloopenmvg ${OPENMVG_LIBRARIES})`

**But there are some errors when I build and execute the code. Please help me to handle this problem that had puzzled me for several days. Thank you very much in advance.**  

/home/owen/SfM/useOpenMVG/Hello_1/HelloOpenMVG/build> make -j2 helloopenmvg
-- OpenMVG Find_Package
-- Found OpenMVG version: 1.3.0
-- Installed in: /home/owen/Libs/openMVG_develop_install
-- Used OpenMVG libraries: openMVG_camera;openMVG_exif;openMVG_features;openMVG_geodesy;openMVG_geometry;openMVG_graph;openMVG_image;openMVG_kvld;openMVG_lInftyComputerVision;openMVG_matching;openMVG_matching_image_collection;openMVG_multiview;openMVG_sfm;openMVG_system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/owen/SfM/useOpenMVG/Hello_1/HelloOpenMVG/build
Scanning dependencies of target helloopenmvg
[ 50%] Building CXX object CMakeFiles/helloopenmvg.dir/main.cpp.o
[100%] Linking CXX executable helloopenmvg
/usr/bin/ld: cannot find -lopenMVG_camera
/usr/bin/ld: cannot find -lopenMVG_exif
/usr/bin/ld: cannot find -lopenMVG_features
/usr/bin/ld: cannot find -lopenMVG_geodesy
/usr/bin/ld: cannot find -lopenMVG_geometry
/usr/bin/ld: cannot find -lopenMVG_graph
/usr/bin/ld: cannot find -lopenMVG_image
/usr/bin/ld: cannot find -lopenMVG_kvld
/usr/bin/ld: cannot find -lopenMVG_lInftyComputerVision
/usr/bin/ld: cannot find -lopenMVG_matching
/usr/bin/ld: cannot find -lopenMVG_matching_image_collection
/usr/bin/ld: cannot find -lopenMVG_multiview
/usr/bin/ld: cannot find -lopenMVG_sfm
/usr/bin/ld: cannot find -lopenMVG_system
collect2: error: ld returned 1 exit status
CMakeFiles/helloopenmvg.dir/build.make:94: recipe for target 'helloopenmvg' failed
make[3]: *** [helloopenmvg] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/helloopenmvg.dir/all' failed
make[2]: *** [CMakeFiles/helloopenmvg.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/helloopenmvg.dir/rule' failed
make[1]: *** [CMakeFiles/helloopenmvg.dir/rule] Error 2
Makefile:162: recipe for target 'helloopenmvg' failed
make: *** [helloopenmvg] Error 2
*** Failure: Exit code 2 ***

**Comment by pmoulon** [comment]
Thx you for your feedback @InomnipotentComedy 
I and @mitjap are currently updating OpenMVG to use more modern CMake rules and be driven by targets rather than by using a global variable.

I and @mitjap will update the documentation accordingly soon.

But the following should resolve your issue:
```
find_package(OpenMVG REQUIRED)
add_executable(helloopenmvg main.cpp)
target_link_libraries(helloopenmvg OpenMVG::openMVG_sfm)
```

So now as you see you just specify the OpenMVG libraries you want to use and includes will be included by transitivity thanks to CMake rules.

Depending of your needs you will have to use 1 or more OpenMVG::openMVG_X libraries.

Tell me if it works!

**Comment by InomnipotentComedy** [comment]
**Thank you very much for the reply quickly. I've tried, but another error about eigen appears.**

/home/owen/SfM/useOpenMVG/Hello_1/HelloOpenMVG/build> make -j2 helloopenmvg
-- OpenMVG Find_Package
-- Found OpenMVG version: 1.3.0
-- Installed in: /home/owen/Libs/openMVG_develop_install
-- Used OpenMVG libraries: openMVG_camera;openMVG_exif;openMVG_features;openMVG_geodesy;openMVG_geometry;openMVG_graph;openMVG_image;openMVG_kvld;openMVG_lInftyComputerVision;openMVG_matching;openMVG_matching_image_collection;openMVG_multiview;openMVG_sfm;openMVG_system
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "OpenMVG::openMVG_sfm" includes non-existent path
    "/home/owen/Libs/openMVG_develop_install/include/openMVG/third_party/eigen/"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.

**Comment by pmoulon** [comment]
- Does the directory `/home/owen/Libs/openMVG_develop_install/include/openMVG/third_party/eigen/` exists on your computer?
- Can you share the cmake log when you configure OpenMVG ?

**Comment by mitjap** [comment]
@pmoulon this is the issue with Eigen I told you about. Eigen want to install itself to `/eigen` (I think) on first install, but on subsequent installs it will install properly. Commit https://github.com/openMVG/openMVG/commit/b51afc89b391b255fdda02bff67ff62c68212a09 fixed this behavior on `master` branch, but these changes were later overridden on `develop`. 

@InomnipotentComedy can you try to run `cmake --build . --target install` again and check if Eigen is properly installed.

**Comment by InomnipotentComedy** [comment]
@pmoulon Sorry for the late reply. In the path `/home/owen/Libs/openMVG_develop_install/include/openMVG/third_party/` there isn't the eigen folder. 
But I didn't know how to find out cmake log. Sorry for my stupid.

**Comment by InomnipotentComedy** [comment]
@mitjap **Could you explain the exact command line for me please. Whether in the OpenMVG/build to type command**
 `cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:STRING="YourInstallPath" --build . ../src/`
**and**
`--target install`
**Sorry for the naive question.**

**Comment by mitjap** [comment]
Go to OpenMVG build directory and enter these commands:
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="YourInstallPath" ../src/`
`cmake --build . --target install` <- will probably fail on install due to Eigen
so try again
`cmake --build . --target install`

**Comment by InomnipotentComedy** [comment]
@mitjap @pmoulon Thank you developers very much. The test program goes well. So glad to communicate with you. Thank you again (:grinning:

**Comment by InomnipotentComedy** [comment]
Another problem appears. When I `#include <openMVG_dependencies/cereal/include/XXX/XXX>`, e.g. `#include <cereal/archives/json.hpp>`, there will display `No such file or directory`.
So `cereal::make_nvp` also cannot work. If there are some clues, please tell me. Thank you very much.

**Comment by mitjap** [comment]
I'm looking at how openMVG installs cereal to openMVG_depencencies folder
and it seems includes should be like this  `<openMVG_dependencies/cereal/
include/cereal/archive/json.hpp>`

**Comment by InomnipotentComedy** [comment]
When I try to use the code of **main_SfMInit_ImageListing** to test, another error appears as below.
`/home/owen/SfM/useOpenMVG/test_ORB_vs_SIFT_3/build> make -j2
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Could NOT find OpenMP (missing:  OpenMP_CXX_FLAGS) 
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.3.0
-- Installed in: /home/owen/Libs/openmvg_develop_install
-- Used OpenMVG libraries: openMVG_camera;openMVG_exif;openMVG_features;openMVG_geodesy;openMVG_geometry;openMVG_graph;openMVG_image;openMVG_kvld;openMVG_lInftyComputerVision;openMVG_matching;openMVG_matching_image_collection;openMVG_multiview;openMVG_sfm;openMVG_system
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/owen/SfM/useOpenMVG/test_ORB_vs_SIFT_3/build
[ 50%] Linking CXX executable test_orb_vs_sift_3
/home/owen/Libs/openmvg_develop_install/lib/libopenMVG_multiview.a(projection.cpp.o): In function `void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> >, long>(Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> > const&, long, long, bool)':
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x7b): undefined reference to `omp_get_num_threads'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x28b): undefined reference to `GOMP_parallel'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x3be): undefined reference to `GOMP_parallel'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x3d1): undefined reference to `omp_get_max_threads'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x461): undefined reference to `omp_get_max_threads'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x49d): undefined reference to `GOMP_parallel'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x4ea): undefined reference to `GOMP_parallel'
/home/owen/Libs/openmvg_develop_install/lib/libopenMVG_multiview.a(projection.cpp.o): In function `Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>::run(long, long, long, double const*, long, double const*, long, double*, long, double, Eigen::internal::level3_blocking<double, double>&, Eigen::internal::GemmParallelInfo<long>*)':
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x8f): undefined reference to `omp_get_thread_num'
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x9d): undefined reference to `omp_get_num_threads'
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x3f0): undefined reference to `GOMP_critical_start'
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x42a): undefined reference to `GOMP_critical_end'
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x478): undefined reference to `GOMP_critical_start'
projection.cpp:(.text._ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE[_ZN5Eigen8internal29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EE3runElllPKdlS4_lPdldRNS0_15level3_blockingIddEEPNS0_16GemmParallelInfoIlEE]+0x4a7): undefined reference to `GOMP_critical_start'
/home/owen/Libs/openmvg_develop_install/lib/libopenMVG_multiview.a(projection.cpp.o): In function `void Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> >, long>(Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> > const&, long, long, bool) [clone ._omp_fn.0]':
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b._omp_fn.0[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x8): undefined reference to `omp_get_thread_num'
projection.cpp:(.text._ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b._omp_fn.0[_ZN5Eigen8internal16parallelize_gemmILb1ENS0_12gemm_functorIdlNS0_29general_matrix_matrix_productIldLi0ELb0EdLi0ELb0ELi0EEENS_5BlockINS5_INS_3MapINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_6StrideILi0ELi0EEEEELin1ELin1ELb0EEELin1ELin1ELb0EEESD_SD_NS0_19gemm_blocking_spaceILi0EddLin1ELin1ELin1ELi1ELb0EEEEElEEvRKT0_T1_SK_b]+0x10): undefined reference to `omp_get_num_threads'
collect2: error: ld returned 1 exit status
CMakeFiles/test_orb_vs_sift_3.dir/build.make:124: recipe for target 'test_orb_vs_sift_3' failed
make[2]: *** [test_orb_vs_sift_3] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_orb_vs_sift_3.dir/all' failed
make[1]: *** [CMakeFiles/test_orb_vs_sift_3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
*** Failure: Exit code 2 ***
`

**Comment by pmoulon** [comment]
Recent commit in develop should fix the issues
