### ISSUE TITLE
convert (.ply) into sfm_data.json or (.bin)

### ISSUE THREAD

**Issue by yonelay11** [openMVG/openMVG#1295]
Hello,
I want to know Is there any way to convert (.ply) into sfm_data.json or (.bin) file format.

**Comment by pmoulon** [comment]
Where  your PLY comes from.
Please note that most of the stage from OpenMVG already print the sfm_data and the PLY corresponding file.

Else ConvertSfMDataFormat allows you to convert a sfm_data.(bin/json/xml) to PLY
