### ISSUE TITLE
SfM using precalibration images

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1297]
First of all, I appreciate all your work and I learned a lot thanks to all of you.

Following openMVG and openMVS routine, I ran a test data set that includes 12 UAV images of a playground, and I got some results. 

Now, I have got the images calibrated using the Camera Calibration Toolbox for Matlab: http://www.vision.caltech.edu/bouguetj/calib_doc/ 

The images are calibrated but not rectified. So I only have the distortion information.

So, I wonder if there is any possibility to use the calibration result to carry out SfM pipeline? If there is, could I have some document for this? If there is not, could you please give me some advice to how to do it?

Thanks in advance.

Best wishes,

Xueman

**Comment by pmoulon** [comment]
You can set the distortion factor in the sfm_data.json file once it have been initialized (ImageListing) and then run (feature extraction, matching and SfM).

Please ensure that your are using the right camera model and that the parameter definition matches.

**Comment by learnmano** [comment]
I am so appreciated for your time and patience, I'll do it very soon and see how it works. I will close this issue once I get the result.

**Comment by learnmano** [comment]
Hi, 
I just want to appreciate your help and it does work.

For anyone encounter the similar problem:
After ImageListing step with using disto_t2 model, I set the distortion factor in the sfm_data.json file replacing the disto_t2 values with my calibration results, which includes 3 redial distortions and 2 tangential distortions, then I continue the rest routine of the Incremental SfM. It turns out that the result is getting better.

This is result before the calibration:
![before](https://user-images.githubusercontent.com/9348938/39293823-8204c280-496c-11e8-8415-ec781a170d8d.png)

And this is the result after the calibration:
![after](https://user-images.githubusercontent.com/9348938/39293824-8223f6f0-496c-11e8-8b0e-21d53cab7d8e.png)

Thanks ever so much again for your time and patience, it helps me a lot. Thank you.

**Comment by pmoulon** [comment]
Thank you for sharing the result of your experiment. Appreciated!
