### ISSUE TITLE
Couldn't process Geodesy with -P option

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1298]
First of all, thanks ever so much for your help and work.

I could get results using standard SfM pipeline without GPS prior, however, when I add the -P option following the document Geodesy: Usage of GPS prior: http://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/
And I imitated the example, but I just cannot get the results. Neither Incremental SfM nor Global SfM.

Could you please give me some advice?

I write the .py file conbined openMVG and openMVS imitating the other guy does, and this is my .py file without GPS prior:

[SfM_SequentialPipelinev2.txt](https://github.com/openMVG/openMVG/files/1941633/SfM_SequentialPipelinev2.txt)

This is my .py file with GPS prior:

[SfM_SequentialPipelinev2GPSprior.txt](https://github.com/openMVG/openMVG/files/1941658/SfM_SequentialPipelinev2GPSprior.txt)

And when I run the GPS prior python script, I found that the colorized,ply seems empty, and I couldn't get any dense .ply file. The part of log information is as follows:

7. Export to openMVS

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
 platforms: 1
  platform ( 0 ) cameras: 1
  12 images (3 calibrated)
  9 Landmarks
8. Densify point cloud
16:12:33 [App     ] Build date: May 26 2017, 18:38:57
16:12:33 [App     ] CPU: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
16:12:33 [App     ] RAM: 5.96GB Physical Memory 128.00TB Virtual Memory
16:12:33 [App     ] OS: Windows 10+ x64
16:12:33 [App     ] SSE & AVX compatible CPU & OS detected
16:12:33 [App     ] Command line: --input-file F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS/scene.mvs
16:12:33 [App     ] Camera model loaded: platform 0; camera  0; f 30.128x30.128; poses 3
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0001.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0002.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0003.JPG'
16:12:33 [App     ] Image loaded   3: DJI_0004.JPG
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0005.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0006.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0007.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0008.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0009.JPG'
16:12:33 [App     ] warning: uncalibrated image 'F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS\DJI_0010.JPG'
16:12:33 [App     ] Image loaded  10: DJI_0011.JPG
16:12:33 [App     ] Image loaded  11: DJI_0012.JPG
16:12:33 [App     ] Scene loaded from interface format (5ms):
        12 images (3 calibrated) with a total of 34.33 MPixels (11.44 MPixels/image)
        9 points, 0 vertices, 0 faces
16:12:34 [App     ] Preparing images for dense reconstruction completed: 12 images (403ms)
16:12:34 [App     ] error: reference image   3 has no good images in view
16:12:34 [App     ] error: reference image  10 has no good images in view
16:12:34 [App     ] error: reference image  11 has no good images in view
16:12:34 [App     ] Selecting images for dense reconstruction completed: 0 images (0ms)
Fused depth-maps 0 (100%, 0ms)
16:12:34 [App     ] Depth-maps fused and filtered: 0 depth-maps, 0 depths, 0 points (-2147483648%) (0ms)
16:12:34 [App     ] Densifying point-cloud completed: 0 points (406ms)
16:12:34 [App     ] Scene saved (1ms):
        12 images (3 calibrated)
        0 points, 0 vertices, 0 faces
16:12:34 [App     ] MEMORYINFO: {
16:12:34 [App     ]     PageFaultCount 30380
16:12:34 [App     ]     PeakWorkingSetSize 79.20MB
16:12:34 [App     ]     WorkingSetSize 14.28MB
16:12:34 [App     ]     QuotaPeakPagedPoolUsage 118.35KB
16:12:34 [App     ]     QuotaPagedPoolUsage 118.26KB
16:12:34 [App     ]     QuotaPeakNonPagedPoolUsage 7.70KB
16:12:34 [App     ]     QuotaNonPagedPoolUsage 7.31KB
16:12:34 [App     ]     PagefileUsage 9.75MB
16:12:34 [App     ]     PeakPagefileUsage 76.35MB
16:12:34 [App     ] } ENDINFO
9. Reconstruct the mesh
16:12:34 [App     ] Build date: May 26 2017, 18:38:57
16:12:34 [App     ] CPU: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
16:12:34 [App     ] RAM: 5.96GB Physical Memory 128.00TB Virtual Memory
16:12:34 [App     ] OS: Windows 10+ x64
16:12:34 [App     ] SSE & AVX compatible CPU & OS detected
16:12:34 [App     ] Command line: F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS/scene_dense.mvs
16:12:34 [App     ] Scene loaded (1ms):
        12 images (3 calibrated) with a total of 2.15 MPixels (0.72 MPixels/image)
        0 points, 0 vertices, 0 faces
Points inserted 0 (100%, 0ms)
10. Texture the mesh
16:12:44 [App     ] Build date: May 26 2017, 18:38:57
16:12:44 [App     ] CPU: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
16:12:44 [App     ] RAM: 5.96GB Physical Memory 128.00TB Virtual Memory
16:12:44 [App     ] OS: Windows 10+ x64
16:12:44 [App     ] SSE & AVX compatible CPU & OS detected
16:12:44 [App     ] Command line: F:/openMVG/playground/images/20180419v2\reconstruction_sequential\MVS/scene_dense_mesh.mvs

And the whole log information is saved as txt:

[log-GPS.txt](https://github.com/openMVG/openMVG/files/1941734/log-GPS.txt)

Thanks in advance. Any help is warmly welcomed.

**Comment by pmoulon** [comment]
In your case I would advise you to run SfM (Global or Incremental) without the `-P` option, then run rigid registration http://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/#rigid-registration-sfm.

As precised in some issue in OpenMVS. MVS frameworks does not like GPS coordinates since they are very large. It gives precision issues.

**Comment by learnmano** [comment]
Thanks so much, I'll run the rigid registration and see how it works.

**Comment by learnmano** [comment]
Dear Moulon,

I looked through the GPS issues and I got this: [https://github.com/openMVG/openMVG/issues/822](url)

And I cannot process the MVS steps with GPS prior, so I give up the GPS prior in OpenMVS. 

Thanks for your time and kindness.

Yours,

Xueman
