### ISSUE TITLE
Question: i m searching a way for producing a hash from SURF descriptors(OpenCV).

### ISSUE THREAD

**Issue by publicocean0** [openMVG/openMVG#1301]
can this library produce a hashcode for SURF Descriptors?

**Comment by pmoulon** [comment]
What do you mean by Hashcode?

The existing CascadeHashing is working with any descriptor, but the parameters are tuned to work best on SIFT like descriptor.

**Comment by publicocean0** [comment]
I m thinking to use  for face identification in a huge database. Maybe i could create a hashcode for each descriptor(associated to a image-> face). I m not so expert in image algorithms but  i could query the similar images and then i can verify if a face is similar to one present in db.

**Comment by pmoulon** [comment]
You can solve this with Image matching or image/descriptor similarities.
You can try to use the existing Image collection retrieval algorithm from OpenMVG.
Or you can look to large scale image retrieval method (Bags of words or VLAD (Aggregation of Local Descriptions))
