### ISSUE TITLE
How to remove some matches manually, please?

### ISSUE THREAD

**Issue by learnmano** [openMVG/openMVG#1303]
Dear Moulon,

First of all, thanks ever so much for your help and work.

I want to remove some objests such as people and cars, when I reconstruct a playground. When I export the matches, I find that there are several matches between people and cars from different images. I wonder how can I remove some matches that I have known their pixel coordinates.

Thanks in advance. Any help or advice is warmly welcomed.

Best wishes,

Xueman

**Comment by pmoulon** [comment]
You can create a mask for some image.
OpenMVG supports per image feature masking (https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L290)

If you want to see less outlier you can also consider using the tracks that have more observations. Tracks with 2 observations are often less robust than tracks with more than 4 views.

**Comment by learnmano** [comment]
Thank you for your prompt reply.

In that context, I'd like to create a mask for each image. I have some pixel coordinates stored in XML files on my own and I want to remove these "boundboxes" during the matching procedure. I would be very appreciate it if you can tell me a little bit more about how to create a mask (a PNG image I suppose, if it is wrong, please tell me) from the coordinates that I got, and what the difference between the global mask and the local mask.

Thank you in advance.

Best wishes,

Xueman

**Comment by learnmano** [comment]
Just to update, I created a mask for each image, named as the document says, and it works. I will upload the result when I have enough time.

**Comment by learnmano** [comment]
Hi there, so sorry for the delay to update. I created a mask for each image, and proceed the SfM process. In the end, it works slightly different from the result with no mask. 

Thank you for your information and time.

Best regards,
Xueman
