### ISSUE TITLE
Can I export the matches as a matching text file?

### ISSUE THREAD

**Issue by gmiguelr87** [openMVG/openMVG#1304]
Hello!
First of all congratulations and thank you everyone for this great library and related community.
I'm new, so apologize if this is not the right place for the question I want to ask (and also for my English), as it's not a problem as such, but a doubt.
I have been working with the library and I have a simple question, but I couldn't find information about it. I would like to export the putative matches between images as a .txt ascii file. Is it possible using the .desc and .feat files generated by openMVG_main_ComputeMatches so that I can obtain the image coordinate (x,y) of each homologous point in the different images in which it has been found?
Thank you!

**Comment by pmoulon** [comment]
Hi,
You have many possibilities to do that:

1. Change the bin to txt in the `ComputeMatches` binary (but only point index will be exported and not the point coordinates.)
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L173

2. Or modify the `exportMatches`
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_exportMatches.cpp
with this code to export every corresponding matches as "xL yL ; xR yR"
```
const auto& left_features = feats_provider->getFeatures(view_I->id_view);
const auto& right_features = feats_provider->getFeatures(view_J->id_view);
for (const auto match_it : vec_FilteredMatches) {
    // Get back linked features
    const features::PointFeature & L = left_features[match_it.i_];
    const features::PointFeature & R = right_features[match_it.j_];
    std::cout << L.x() << " " << L.y() << " ; " << R.x() << " " << R.y() << "\n";
}
```

**Comment by gmiguelr87** [comment]
Thank you so much for your quick response!

Is there no way to do that with the binaries released using parameters?
If not, I will try the second option when I have a little time.

Thank you again!

**Comment by ccastilloro** [comment]
Hi, Pierre. I was also interested in exporting the matches to a text file so that I can do on them further processing. The thing is I'm not knowledgeable on C compiling. Is there any easy option to accomplish that not involving a background on C programming?

Thanks a lot!

**Comment by ccastilloro** [comment]
Hi, Pierre. Somehow it seems I could manage to compile the code in VS 2015. Mi question is:
Where exactly should we include the lines in exportMatches.cpp to allow for txt matches export:

_const auto& left_features = feats_provider->getFeatures(view_I->id_view);
const auto& right_features = feats_provider->getFeatures(view_J->id_view);
for (const auto match_it : vec_FilteredMatches) {
    // Get back linked features
    const features::PointFeature & L = left_features[match_it.i_];
    const features::PointFeature & R = right_features[match_it.j_];
    std::cout << L.x() << " " << L.y() << " ; " << R.x() << " " << R.y() << "\n";
}_

Could you specify if we need to remove something or just paste this extract in a specific line. I do not want to mess around with the code.
Thanks a lot.

**Comment by pmoulon** [comment]
@gmiguelr87 You can remove the irrelevant surface in meshlab or cloudcompare.

@ccastilloro You can create a file and use the copy the cout line to export to your file stream.

**Comment by garimss** [comment]
hi @pmoulon, How are you? I see you are very much responsive. I have a questions here again. You are telling to @ccastilloro to create a file.

Do you mean create a new file inside https://github.com/openMVG/openMVG/blob/master/src/software/SfM/

and paste the below code there 

const auto& left_features = feats_provider->getFeatures(view_I->id_view);
const auto& right_features = feats_provider->getFeatures(view_J->id_view);
for (const auto match_it : vec_FilteredMatches) {
// Get back linked features
const features::PointFeature & L = left_features[match_it.i];
const features::PointFeature & R = right_features[match_it.j_];
std::cout << L.x() << " " << L.y() << " ; " << R.x() << " " << R.y() << "\n";
}_

Or it needs to be included inside the folder D:\git_hub\ralph\openMVG\src\software\SfM\export\main_exportMatches.cpp

I am also trying to export matched points (id + coordinates) for further use in deep learning model to train.

**Comment by pmoulon** [comment]
I would advise you to modify `main_exportMatches.cpp` it will be easier.
If you need to export the id, just add `match_it.i_` or `j_`in the `std::cout` ;-)
