### ISSUE TITLE
GCP UI

### ISSUE THREAD

**Issue by MarcoMazzo** [openMVG/openMVG#1308]
Hi,
can windows user access to the ui for the gcp selection? i'm using the 1.3 release, i need to build it my own?
thanks
Marco

**Comment by pmoulon** [comment]
Hi,
You are right, you need to build your own,
I did not precompile QT based binaries because it creates package more complex to deliver (QT image plug-ins...).

You just have to install QT and tell cmake where your QT is.
https://github.com/openMVG/openMVG/blob/master/BUILD.md#windows-compilation

**Comment by MarcoMazzo** [comment]
Hi,
sorry if i reply in this closed issue, maybe could be helpfull also for other new to compiling like me...
I've installed [qt5.11 opensource](http://download.qt.io/archive/qt/5.11/5.11.0/qt-opensource-windows-x86-5.11.0.exe)
then i clone project from github
then i open Cmake GUI select paths and configure... it tell me not found Qt5... and I fill all the Qt5 paths that in my case I found in C:\Qt\Qt5.11.0\5.11.0\msvc2017_64\lib\cmake... now i have this configuration and i ask you if it is correct:

> Checking for C++11 compiler
> Checking for C++11 compiler - available
> Eigen 3.3.4 found (include: C:/openMVG/src/third_party/eigen)
> Flann 1.8.4 found (include: C:/openMVG/src/third_party/flann/src/cpp/flann)
> CoinUtils 2.10.13 found (include: C:/openMVG/src/dependencies/osi_clp/CoinUtils/src)
> Clp 1.16.10 found (include: C:/openMVG/src/dependencies/osi_clp/Clp/src)
> Osi 0.107.8 found (include: C:/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
> Lemon 1.3 found (include: C:/openMVG/src/third_party/lemon/lemon)
> Could NOT find Wget (missing: WGET_EXECUTABLE) 
> Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE) 
> Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
> Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
> Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
> Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
> 
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.3.4 found (include: C:/openMVG/src/third_party/eigen)
> -- Found Eigen version 3.3.4: C:/openMVG/src/third_party/eigen
> 
>    ===============================================================
>    Disabling the use of Eigen as a sparse linear algebra library.
>    This does not affect the covariance estimation algorithm 
>    which can still use the EIGEN_SPARSE_QR algorithm.
>    ===============================================================
> 
> -- Building without LAPACK.
> -- Building without SuiteSparse.
> -- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
> -- Google Flags disabled; no tests or tools will be built!
> -- Compiling minimal glog substitute into Ceres.
> -- Using minimal glog substitute (include): internal/ceres/miniglog
> -- Building with OpenMP.
> Looking for C++ include unordered_map
> Looking for C++ include unordered_map - found
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
> -- Found unordered_map/set in std namespace.
> Looking for C++ include memory
> Looking for C++ include memory - found
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
> -- Found shared_ptr in std namespace using <memory> header.
> -- Building Ceres as a static library.
> Enabling CERES_NO_LAPACK in Ceres config.h
> Enabling CERES_NO_SUITESPARSE in Ceres config.h
> Enabling CERES_USE_OPENMP in Ceres config.h
> Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
> Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
> -- Do not build any example.
>    ===============================================================
>    Ceres-solver configuration end.
>    ===============================================================
> CMake Warning at third_party/eigen/CMakeLists.txt:67 (message):
>   EIGEN_INCLUDE_INSTALL_DIR is deprecated.  Use INCLUDE_INSTALL_DIR instead.
> 
> 
> 
> Configured Eigen 3.3.4
> 
> CMake Deprecation Warning at openMVG_Samples/describe_and_match_GUI/CMakeLists.txt:8 (cmake_policy):
>   The OLD behavior for policy CMP0025 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> ** Found Qt5, GUI modules will be build
> CMake Deprecation Warning at software/ui/SfM/control_points_registration/CMakeLists.txt:12 (cmake_policy):
>   The OLD behavior for policy CMP0020 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
> Sphinx need to be installed to generate the sphinx documentation
> Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> Doxygen need to be installed to generate the doxygen documentation
> 
> 
> ** OpenMVG version: 1.3.0
> ** Build Shared libs: OFF
> ** Build OpenMVG tests: ON
> ** Build OpenMVG softwares: ON
> ** Build OpenMVG documentation: ON
> ** Build OpenMVG samples applications: ON
> ** Build OpenMVG openGL examples: OFF
> ** Enable code coverage generation: OFF
> ** Enable OpenMP parallelization: ON
> ** Build OpenCV+OpenMVG samples programs: OFF
> ** Use OpenCV SIFT features: OFF
> 
> 
> CEREAL: (internal)
> EIGEN: 3.3.4 (internal)
> CERES: 1.13.0 (internal)
> FLANN: 1.8.4 (internal)
> LIBTIFF:  (internal)
> LIBPNG:  (internal)
> LIBJPEG (internal)
> CLP: 1.16.10 (internal)
> COINUTILS: 2.10.13 (internal)
> OSI: 0.107.8 (internal)
> LEMON: 1.3 (internal)
> 
> 
> Configuring done
> Generating done

**Comment by MarcoMazzo** [comment]
I've tried with this configuration, setting up release 64 in VisualStudio 2017, and compiling "ALL_BUILD". At the end it finished with 0 errors and 2832 advices 
========== Compilazione: 163 completate, 0 non riuscite, 0 aggiornate, 0 ignorate ==========
I'm doing it right?
becouse when i try to open "ui_openMVG_control_points_registration.exe" pop up this 
![2018-06-06 10_22_49-problema risolto - problema_ impossibile trovare il punto d ingresso aiutatemi](https://user-images.githubusercontent.com/7794058/41026292-73d79444-6974-11e8-849f-0eec12d8fca7.png)
can you help me?
Thanks
Marco

**Comment by pmoulon** [comment]
CMake behavior looks ok.
Compilation went fine since you was able to launch the software.
For me the error comes from a missing DLL in the path.
Please be sure that QT DLL are in your windows PATH.

**Comment by MarcoMazzo** [comment]
I found my own problem:
I had a copy of MicMac software installed that inside the bin folder i notice now have Qt libraries and other stuff... this folder is in my windows PATH and it was above the Qt string, so maybe it goes in conflict... now i removed MicMac and the PATH and openMVG GUI now works fine!
Hope that can be helpfull
Bye
Marco
