### ISSUE TITLE
Question regarding estimated poses with GPS priors not align with the world coord system

### ISSUE THREAD

**Issue by stanathong** [openMVG/openMVG#1309]
I have been playing with OpenMVG so far and I have to say you have made such a great documentation to accompany with. Thanks very much!

I used OpenMVG to obtain the camera poses for my image sequence, then tried to create the virtual top down view of the images by computing the homography from the returned R, C and K, which is `H=K[R|t]`. I found the output from OpenMVG being not aligned with the world coordinate system and faced some scale problems. See the pic below.

![openmvg_pose](https://user-images.githubusercontent.com/8308557/40166450-13ededb0-59ae-11e8-9c71-62585a50f4f4.jpg)

The left image is obtained by using the pose from [OpenSfM](https://github.com/mapillary/OpenSfM) and this projected image does align with the world coord system. The image on the right is produced from OpenMVG, which has some sort of wrong pointing direction though GPS priors given. 

The input to my pipeline is an image sequence with GPS exif. Here, I have run `openMVG_main_SfMInit_ImageListing` with parameters "-P", "-m=1" and pass my intrinsics matrix as input, followed by
```
openMVG_main_ComputeFeatures
openMVG_main_ComputeMatches
openMVG_main_IncrementalSfM
```

I was wondering if there is anything missing in my pipeline?

Also, I have tried running ImageListing without "-P" but failed to obtain poses for all images in the sequence. I even tried running on a small set of images without "-P" and then in the end run `openMVG_main_geodesy_registration_to_gps_position` but the result is not accurate. 

Since GPS data are given as priors, that will give a good approximation for estimating camera pose in the optimisation process. But I didn't seem to get the expected results. What would you suggest me in this case as I think I might not have fully understood OpenMVG functions? Thank very much for your help.

**Comment by stanathong** [comment]
I believe this is what you use GPS pose prior in the optimisation: https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_BA_ceres.cpp

I haven't fully traced the code but believe that the yours `cam_R` is rotation factor and `cam_t` is translation. Doesn't this code miss transposing the R matrix?
Since `C = -transpose(R)*t`, but this line `const Vec3T cam_R_transpose(-cam_R);` simply negates the matrix?

Please can you have a look as I might not understand the way R matrix is defined in OpenMVG.

```
    using Vec3T = Eigen::Matrix<T,3,1>;
    Eigen::Map<const Vec3T> cam_R(&cam_extrinsics[0]);
    Eigen::Map<const Vec3T> cam_t(&cam_extrinsics[3]);
    const Vec3T cam_R_transpose(-cam_R); // <--- rather transpose?

    Vec3T pose_center;
    // Rotate the point according the camera rotation
    ceres::AngleAxisRotatePoint(cam_R_transpose.data(), cam_t.data(), pose_center.data());
    pose_center = pose_center * T(-1);

    Eigen::Map<Vec3T> residuals_eigen(residuals);
    residuals_eigen = weight_.cast<T>().cwiseProduct(pose_center - pose_center_constraint_.cast<T>());

```

**Comment by stanathong** [comment]
@pmoulon 
Thanks very much for your reply. 
The exif data contains lat/lon coordinates and I passed to the function `openMVG_main_SfMInit_ImageListing` with `-m=1`, which I expect they are converted to UTM.

Would you mind passing me your email address? I could only be able to share via google drive. Thanks very much.

**Comment by pmoulon** [comment]
Sure, I sent to you an email.

**Comment by KeoChi** [comment]
Hi, do you solve this problem?  I have a similar situation. I run the [ openmvg example](https://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/#for-sfm-to-xyz-gps-registration). Then I can get a series of coordinates(**R, C**). In addition, I use the same dataset and run the [OpenSfM](https://github.com/mapillary/OpenSfM). I found that the coordinates of openMVG are different from the coordinates of OpenSfM.
  **the coordinates of openMVG:**
   NVM_V3
    15
     views/view_0000/undistorted.png 2828.41 -0.0284033 -0.65547 0.752973 -0.0508347 **311527 5.16982e+06** 775.821 0 0
views/view_0001/undistorted.png 2828.41 -0.0029235 0.707104 -0.705228 0.0514691 **311592 5.16981e+06** 776.235 0 0
views/view_0002/undistorted.png 2828.41 -0.0134556 0.708565 -0.70432 0.0410844 311658 5.16981e+06 775.728 0 0
views/view_0003/undistorted.png 2828.41 -0.0220201 0.716488 -0.695567 0.0484377 311720 5.1698e+06 777.362 0 0
views/view_0004/undistorted.png 2828.41 -0.00222362 -0.650289 0.757779 -0.0537549 311786 5.1698e+06 779.509 0 0
views/view_0005/undistorted.png 2828.41 0.0236733 -0.702937 0.708517 -0.0576473 311851 5.16979e+06 776.744 0 0
views/view_0006/undistorted.png 2828.41 0.00659805 0.75847 -0.64949 0.0533139 311917 5.16979e+06 780.35 0 0
views/view_0007/undistorted.png 2828.41 0.0201748 -0.669579 0.739679 -0.0642816 311978 5.16978e+06 777.345 0 0
views/view_0008/undistorted.png 2828.41 0.00705998 -0.699566 0.712337 -0.0559698 312041 5.16977e+06 777.488 0 0
views/view_0009/undistorted.png 2828.41 0.00263284 -0.684053 0.728308 -0.0404105 312108 5.16976e+06 777.109 0 0
views/view_0010/undistorted.png 2828.41 0.0190529 0.688009 0.725409 -0.00789131 312084 5.16972e+06 775.466 0 0
views/view_0011/undistorted.png 2828.41 0.0726316 0.70733 0.703119 -0.00576989 312024 5.16973e+06 782.802 0 0
views/view_0012/undistorted.png 2828.41 0.0456025 0.694803 0.717716 -0.00726615 311955 5.16973e+06 779.278 0 0
views/view_0013/undistorted.png 2828.41 0.041862 0.677549 0.734264 -0.00567016 311890 5.16974e+06 778.856 0 0
views/view_0014/undistorted.png 2828.41 0.0436861 0.695969 0.716732 -0.003833 311826 5.16975e+06 780.015 0 0

 **the coordinates of OpenSfM:**
 NVM_V3
  15
   undistorted/IMG_1197.JPG.png 2890.10954687 0.0826556208117532 0.6964248554429296 0.7128212364816792 -0.006808369132795763 **161.75036243788787 -38.08078224880706** 782.1770670778079 0 0
undistorted/IMG_1195.JPG.png 2890.10954687 0.005383086238386895 -0.6948595666051018 0.7185471642546644 -0.028830154725576956 **243.50597216264197 -0.773152296434148** 775.4763203536615 0 0
undistorted/IMG_1200.JPG.png 2890.10954687 0.04812654282267662 0.6845650695840381 0.7273595968124228 0.0015869172025431454 **-37.01271972796879 -26.060956021243115** 781.1237014076653 0 0
undistorted/IMG_1199.JPG.png 2890.10954687 0.048114145267357494 0.6661619124966426 0.7442508233560863 -0.0020117896993687807 27.387188764206744 -32.53164806584642 779.7038423776323 0 0
undistorted/IMG_1188.JPG.png 2890.10954687 0.003359136521828171 -0.7197398243056512 0.6928799429502014 -0.04336687869357829 -206.85083960168473 28.01900868681791 775.8150224592896 0 0
undistorted/IMG_1190.JPG.png 2890.10954687 0.008751096188673422 0.6616731205625193 -0.7480120401783047 0.050892903128476406 -78.57043695295478 20.2878690388956 780.9844746671959 0 0
undistorted/IMG_1192.JPG.png 2890.10954687 0.009583419381882221 0.7680037754391269 -0.6386610314740345 0.04680219931499289 53.03650655678723 14.345032038819706 781.5420839732235 0 0
undistorted/IMG_1187.JPG.png 2890.10954687 0.009336847663884575 0.7182943674848449 -0.6934695730303891 0.055371257853672244 -273.0646216116574 31.048873012715998 775.2214343163998 0 0
undistorted/IMG_1196.JPG.png 2890.10954687 0.031003834948026648 0.6772089114063834 0.7350813054951988 -0.009073414008596141 221.49929137209045 -47.36397732212142 773.7054482977553 0 0
undistorted/IMG_1194.JPG.png 2890.10954687 0.007678761051282569 -0.7102097137147473 0.7024426719651499 -0.04601621210394589 177.16706426457034 5.004362714553416 777.1028724604312 0 0
undistorted/IMG_1198.JPG.png 2890.10954687 0.05380419800921059 0.6837843731362954 0.7276754297419965 -0.0057016033701101625 92.81794784870522 -36.38217200895332 779.587587195844 0 0
undistorted/IMG_1191.JPG.png 2890.10954687 0.0187616470866294 -0.7136787877632818 0.6981850366103719 -0.05336893430361125 -12.78071063675971 16.179290411782667 778.2165366635787 0 0
undistorted/IMG_1189.JPG.png 2890.10954687 0.013398007803644054 -0.7273305067795964 0.6844120408940482 -0.04889770520047296 -144.43825717957566 23.51114502596309 778.2012620207774 0 0
undistorted/IMG_1193.JPG.png 2890.10954687 0.01923222203746967 -0.6806843372671814 0.7301771830007731 -0.05603780919785556 114.42954551317365 7.744868800048437 777.877059127987 0 0
undistorted/IMG_1186.JPG.png 2890.10954687 0.04316347482092726 0.6673278749487491 -0.7414416287076061 0.05545027481611412 -338.8677312079341 35.08963244272903 773.3500107762569 0 0
   
   The X\Y coordinates of openMVG are bigger than The X\Y coordinates of OpenSfM.
  @pmoulon @stanathong  Can you explain this reason? Can you give some advise?

**Comment by stanathong** [comment]
If I wasn't mistaken, the camera positions produce by OpenSfM are subtracted with the reference position (which is the mean position across all the camera - check reference_lla.json from your output). 

I found OpenMVG poses are as accurated as OpenSfM and align well to the UTM (or ECEF)  coordinates. However, the problem I found was that when you use GPS data in the camera pose estimation process, OpenMVG failed to optimise poses for the whole images i.e. after the optimisation is done, only a fraction of images are estimated camera poses.

**Comment by KeoChi** [comment]
@stanathong Thank you for your reply! I only used 15 images, not all images. What should I do in OpenMVG that can make the coordinates of openMVG are consistent with the coordinates of OpenSfM. Because I want to use openMVG intead of the OpenSfM in [ODM](https://github.com/OpenDroneMap/ODM). Looking forward to your suggestions!

**Comment by stanathong** [comment]
@KeoChi 
As I said in the above reply, the poses computed from OpenSfM were normalised i.e. the position returned from OpenSfM is X,Y,Z which in fact should be X+offset, Y+offset, Z+offset, as produced by OpenMVG. To get those offset value, look for reference_lla.json from the output of OpenSfM. Then you can subtract those offset out of the pose produced by OpenMVG. That way could make the results from OpenMVG to be close to those from OpenSfM.

However, do bear in mind that the final results in the world coordinate system should be those output from OpenMVG or OpenSfM+offset.
