### ISSUE TITLE
Add new points to matching

### ISSUE THREAD

**Issue by DavidGilHidalgo** [openMVG/openMVG#1313]
Hi.
I would like to know if it is possible to add points to the matching generated by OpenMVG.
I have a file with 4 points and their coordinates in each picture, I tried to generate the matching file in ASCII format to add these points.
I have obtained the file matches.X.txt and matches.putative.txt.
The problem is I don't understand these files. I've seen comments like [these](https://github.com/openMVG/openMVG/issues/734#issuecomment-273678782) 

but I can't understand the link between numbers and matching.

For example, the first 5 lines of my matches.e.txt file are as follows:
0 1 
248 
1212 1452 
1358 1563 
1365 1557

Thank you very much for the answers.

**Comment by DavidGilHidalgo** [comment]
@pmoulon Thanks for the answer. I've already modified the matching file. Now I'm having trouble exporting the file to binary. I don't know what file I have to put in sMatchFile

**Comment by pmoulon** [comment]
You can use OpenMVG API:
See Load, Save https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/indMatch_utils.hpp

Just provide `txt` ot `bin` for the extension and you are all set
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/indMatch_utils.cpp#L38
