### ISSUE TITLE
Fragmented faces in texture mapping cause blurriness and texture error

### ISSUE THREAD

**Issue by otepmong** [openMVG/openMVG#1315]
Hello,

In the OpenMVS TextureMesh program, we noticed many texture regions of the generated model containing either a small number of faces (or a single face), or an 'island' where a group of faces are mapped to one image, but all surrounding faces are mapped to a different image. Please see the screenshot below, on the left, using MeshLab to show texture seams.

![oldnewbluelaxt](https://user-images.githubusercontent.com/7981417/40542971-369b0dfa-5fd7-11e8-8c82-cc2bcc086865.png)

We have been working on an option to remap these islands to the surrounding texture region by modifying the label selections after labels are extracted from the inference step in SceneTexture.cpp:FaceViewSelection(), but before texture patches are actually created in GenerateTexture().  We've had reasonable success (right side of screenshot).

Additional improvements we are working on require that for a given face, finding all of its valid labels. We were thinking of iterating through the face's data in FaceDataViewArr facesDatas, but are not sure how a view ID and a face's label are connected (if at all). We would greatly appreciate If you have any hints/pointers to the class relationships!

Also, we would be happy to submit the code back to you if you think it would be useful to others.

Thank you in advance..

**Comment by pmoulon** [comment]
Please post this in the OpenMVS issue ;-)
