### ISSUE TITLE
Is it possible to use openMVG+openMVS for animation and movement reconstruction? 

### ISSUE THREAD

**Issue by ls0h** [openMVG/openMVG#1324]
Hello!

I have 7 USB cameras and can get synced sequence of images from them.
Positions of cameras are fixed. 
I want to get a sequence of aligned .ply files or something like that and to reconstruct movement of an object in 3D space.
My reconstruction is working this way: MVG+MVS for frame 0 from all cameras, frame 1 from all cameras, etc....
For now, the sequence of .ply is not aligned at all, scenes have different rotations and positions.
openMVG and openMVS are not using any information from previous frames.
So, it is a lot of work to merge scenes in 3D space.

Is it possible to share data between frames?
How can I align positions of many .ply files by positions of cameras?

Thanks!
P.S. Sorry for bad English.

**Comment by pmoulon** [comment]
Hi @ls0h 

You can do it.

What I would advise in your case is to calibrate the camera location using a textured object and then reuse it for all your image sequences to triangulate the feature matches.

Doing this this way you will have a consistent 3D coordinate system for all your reconstructions.

**Comment by caokui1221** [comment]
> Hi @ls0h
> 
> You can do it.
> 
> What I would advise in your case is to calibrate the camera location using a textured object and then reuse it for all your image sequences to triangulate the feature matches.
> 
> Doing this this way you will have a consistent 3D coordinate system for all your reconstructions.

Hello, Pierre. Could you provide more details about how to calibrate the camera location using a textured object? Thank you.
