### ISSUE TITLE
Help with error: "There is no defined intrinsic data in order to compute an essential matrix for the initial pair."

### ISSUE THREAD

**Issue by snowzurfer** [openMVG/openMVG#1325]
When running the sequential pipeline with certain image sets, the pipeline stops at the stage linked below with the error
```
There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
```

https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L226

Although I get an idea of why, could someone help me understand why that is happening and how to prepare my data set to avoid this? Thanks.

**Comment by pmoulon** [comment]
Your camera model is not registered in the camera database.
If all your images have the same size, you can specify an approximate focal length to SfM_InitImageListing by using the `-f` option.
The value to use as an argument can be `1.2 * max(image_width, image_height)`

**Comment by lchristian56-marco** [comment]
when i can change your option in the code tutorial_demo.py or when ?
Your camera model is not registered in the camera database.
If all your images have the same size, you can specify an approximate focal length to SfM_InitImageListing by using the -f option.
The value to use as an argument can be 1.2 * max(image_width, image_height) please help me

**Comment by pmoulon** [comment]
You can modify the python file here: https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/tutorial_demo.py.in#L49
default is ` "-o", matches_dir, "-d", camera_file_params, "-c", "3"])`
You can add your new options at the end
` "-o", matches_dir, "-d", camera_file_params, "-c", "3", "-f", "<YOUR NUMBER>"])`
