### ISSUE TITLE
How to write CMakeList.txt under ubuntu16.04 and use openMVG as a third party library

### ISSUE THREAD

**Issue by TianQi-777** [openMVG/openMVG#1328]
I compile under the ubuntu16.04 system. I want to use openMVG as a third party library under ubuntu16.04. Is there a related tutorial?

**Comment by pmoulon** [comment]
See here: https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-in-cmake

**Comment by TianQi-777** [comment]
Thank you very much, I will try again.
