### ISSUE TITLE
openMVG on antergos, error on compilling

### ISSUE THREAD

**Issue by cabezacabra** [openMVG/openMVG#1329]
Hi, i'm trying to install openMVG on Antergos and when i am compilling i get the some errors:
<pre><b>/usr/include/c++/8.1.1/bits/stl_map.h:151:17:</b>   se requiere desde ‘<b>class std::map&lt;std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt;, Eigen::aligned_allocator&lt;Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt;</b>’
<b>/home/dani/openMVG/src/software/SfM/io_readGT.hpp:144:65:</b>   se requiere desde aquí
<b>/usr/include/c++/8.1.1/bits/stl_tree.h:452:21:</b> <font color="#EF2929"><b>error: </b></font>falló la aserción estática: comparison object must be invocable with two arguments of key type
       static_assert(<font color="#EF2929"><b>__is_invocable&lt;_Compare&amp;, const _Key&amp;, const _Key&amp;&gt;{}</b></font>,
                     <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
In file included from <b>/home/dani/openMVG/src/software/SfM/main_evalQuality.cpp:16</b>:
<b>/home/dani/openMVG/src/third_party/cmdLine/cmdLine.h:163:43:</b> <font color="#AD7FA8"><b>aviso: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
     void process(int&amp; argc, char* argv[]) <font color="#AD7FA8"><b>throw</b></font>(std::string) {
                                           <font color="#AD7FA8"><b>^~~~~</b></font>
make[2]: *** [software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/build.make:63: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/main_evalQuality.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7202: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/all] Error 2
</pre>
Ty for the help

**Comment by pmoulon** [comment]
- Can you tell me which GCC version do you have?
- Can you try to compile the develop branch?
  - the error about `throw` is fixed there.
  - the error about the file `io_readGT.hpp` should also be fixed there.

**Comment by cabezacabra** [comment]
I have gcc 8.1.1+20180 and sure i try but i dont know how to do it with develop, i have to download it as zip? Sry i'm a newbie in this kind of things.
Ty for your help

**Comment by pmoulon** [comment]
The community is here to help:
https://github.com/openMVG/openMVG/blob/master/BUILD.md#build-instructions

-> I would recommend this:
`$ git clone --recursive https://github.com/openMVG/openMVG.git -b develop`
and then follow the cmake, make steps

**Comment by cabezacabra** [comment]
Oh ok, tyvm ill try right now

**Comment by cabezacabra** [comment]
:S the same
<pre>/usr/include/c++/8.1.1/bits/stl_tree.h: En la instanciación de ‘<b>class std::_Rb_tree&lt;std::__cxx11::basic_string&lt;char&gt;, std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt;, std::_Select1st&lt;std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt;, Eigen::aligned_allocator&lt;Eigen::Matrix&lt;double, 3, 3&gt; &gt;, std::allocator&lt;std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt; &gt;</b>’:
<b>/usr/include/c++/8.1.1/bits/stl_map.h:151:17:</b>   se requiere desde ‘<b>class std::map&lt;std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt;, Eigen::aligned_allocator&lt;Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt;</b>’
<b>/home/dani/openMVG/src/software/SfM/io_readGT.hpp:144:65:</b>   se requiere desde aquí
<b>/usr/include/c++/8.1.1/bits/stl_tree.h:452:21:</b> <font color="#EF2929"><b>error: </b></font>falló la aserción estática: comparison object must be invocable with two arguments of key type
       static_assert(<font color="#EF2929"><b>__is_invocable&lt;_Compare&amp;, const _Key&amp;, const _Key&amp;&gt;{}</b></font>,
                     <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
make[2]: *** [software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/build.make:63: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/main_evalQuality.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7490: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
</pre>

**Comment by pmoulon** [comment]
Go to the file `/home/dani/openMVG/src/software/SfM/io_readGT.hpp` at line 144 and replace the line. Then try to compile again.

**Comment by cabezacabra** [comment]
Ty, well we advance a little bit, but sill got some errors
<pre>/usr/include/c++/8.1.1/bits/stl_tree.h: En la instanciación de ‘<b>class std::_Rb_tree&lt;std::__cxx11::basic_string&lt;char&gt;, std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt;, std::_Select1st&lt;std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt;, std::less&lt;int&gt;, Eigen::aligned_allocator&lt;std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt; &gt;</b>’:
<b>/usr/include/c++/8.1.1/bits/stl_map.h:151:17:</b>   se requiere desde ‘<b>class std::map&lt;std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt;, std::less&lt;int&gt;, Eigen::aligned_allocator&lt;std::pair&lt;const std::__cxx11::basic_string&lt;char&gt;, Eigen::Matrix&lt;double, 3, 3&gt; &gt; &gt; &gt;</b>’
<b>/home/dani/openMVG/src/software/SfM/io_readGT.hpp:144:109:</b>   se requiere desde aquí
<b>/usr/include/c++/8.1.1/bits/stl_tree.h:452:21:</b> <font color="#EF2929"><b>error: </b></font>falló la aserción estática: comparison object must be invocable with two arguments of key type
       static_assert(<font color="#EF2929"><b>__is_invocable&lt;_Compare&amp;, const _Key&amp;, const _Key&amp;&gt;{}</b></font>,
                     <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
make[2]: *** [software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/build.make:63: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/main_evalQuality.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7490: software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
</pre>

**Comment by pmoulon** [comment]
I will try to take a look to all of them.
Perhaps the best for me would be to reproduce your dev env (do you can point me to an iso of your Linux distribution?)

**Comment by cabezacabra** [comment]
Sure, here you have it https://antergos.com/try-it/ should be the same i made a fresh install 2 days ago

**Comment by pmoulon** [comment]
Can you try again to pull the `develop` branch and compile?
- I tried in a antergos VM and it was running fine for me with the last pushed fix ;-)

**Comment by cabezacabra** [comment]
It worked, tyvm for all your help, you're awesome
