### ISSUE TITLE
Running  openMVG_main_SfMInit_ImageListing , is there more dataset for testing?

### ISSUE THREAD

**Issue by TianQi-777** [openMVG/openMVG#1330]
I want to run openMVG_main_SfMInit_ImageListing with the test dataset(ImageDataset_SceauxCastle).At the beginning, I can't find sensor_width_camera_database.txt , then I found it on openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt , is there a description of the data storage format(sensor_width_camera_database.txt)? If I want to run my series of pictures by myself, how do I get the information of sensor_width_camera_database.txt ,is there any other related dataset?
I just started the 3D reconstruction. I want to input a series of pictures and their related poses (I don't know what the storage format of the pose is). I hope to output the dense reconstruction via the openMVG library.
Hope that the author can provide a little help, thank you very much.

**Comment by pmoulon** [comment]
Hi @TianQi-777,

The file format of `sensor_width_camera_database.txt ` is `CAMERA_NAME;CAMERA_SENSOR_WIDTH`

The goal of `openMVG_main_SfMInit_ImageListing ` binary is to initial the SfM project. If all your image dataset have the same image size and their are from an unkown camera, you can specify by hand an approximate focal length by using this rule: `-f X`. X would be computed as something like (1.2 * max(image_width, image_height)).

Default output format is BINARY -> the sfm_data.bin.
You can convert this file to JSON and parse the camera poses, the 3D point, the camera intrinsic values...
See `openMVG_main_ConvertSfM_DataFormat` (-i sfm_data.bin -o sfm_data_json.json). You will be able to find the camera poses as rotation matrices and camera centers.

**Comment by TianQi-777** [comment]
Thanks for replying, I will try again.

**Comment by TianQi-777** [comment]
Hello @pmoulon,
When I was running openMVG_main_SfMInit_ImageListing, **I had a problem about K.txt.**
First of all, I **successfully compiled all the code** under ubuntu 16.04.(”make test“ is OK)
My file storage path is as follows:
ImageDirectory:XX/ImageDataset_SceauxCastle-master/images
SensorWidthDatabase:YY/sensor_width_camera_database.txt
OutputDirectory:ZZ
Intrinsics:XX/ImageDataset_SceauxCastle-master/images/K.txt

********************************************************************************************************
**1.First try(with K.txt)**
**Run in the terminal:**
./openMVG_main_SfMInit_ImageListing **-i** XX/ImageDataset_SceauxCastle-master/images **-d** YY/sensor_width_database/sensor_width_camera_database.txt **-o** ZZ **-k** XX/ImageDataset_SceauxCastle-master/images/K.txt

**<Terminal display>**
You called : 
./openMVG_main_SfMInit_ImageListing
--imageDirectory /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/images
--sensorWidthDatabase /home/tq/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/output
--focal -1
--intrinsics /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/images/K1.txt
--camera_model 3
--group_camera_model 1

 Missing ';' character

Invalid K matrix input

*********************************************************************************************************
**2.Second try(without K.txt)**
**Run in the terminal:**
./openMVG_main_SfMInit_ImageListing **-i** XX/ImageDataset_SceauxCastle-master/images **-d** YY/sensor_width_database/sensor_width_camera_database.txt **-o** ZZ

**<Terminal display>**
Warning & Error messages:
K.txt: Unkown image file format.
Readme.txt: Unkown image file format.

************************************************************************************************************
**3.Third try(Direct input -k 2905.88;0;1416;0;2905.88;1064;0;0;1)**
**Run in the terminal:**
./openMVG_main_SfMInit_ImageListing **-i** XX/ImageDataset_SceauxCastle-master/images **-d** YY/sensor_width_database/sensor_width_camera_database.txt **-o** ZZ **-k** **2905.88;0;1416;0;2905.88;1064;0;0;1**

**<Terminal display>**
 Missing ';' character

Invalid K matrix input
0：未找到命令
1416：未找到命令
0：未找到命令
2905.88：未找到命令
1064：未找到命令
0：未找到命令
0：未找到命令
1：未找到命令

************************************************************************************************************
**4.Fourth try(Change the format of K.txt)**
**Original**:2905.88 0 1416 
0 2905.88 1064
0 0 1
**Modification**:2905.88;0;1416;0;2905.88;1064;0;0;1

**Run in the terminal:**
./openMVG_main_SfMInit_ImageListing **-i** XX/ImageDataset_SceauxCastle-master/images **-d** YY/sensor_width_database/sensor_width_camera_database.txt **-o** ZZ **-k** XX/ImageDataset_SceauxCastle-master/images/K.txt


**<Terminal display>**
 You called : 
./openMVG_main_SfMInit_ImageListing
--imageDirectory /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/images
--sensorWidthDatabase /home/tq/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/output
--focal -1
--intrinsics /home/tq/a3_dataset/ImageDataset_SceauxCastle-master/images/K.txt
--camera_model 3
--group_camera_model 1

 Missing ';' character

Invalid K matrix input
***************************************************************************************************************
How should I enter K.txt correctly?
**Another problem** is that I found that sensor_width_camera_database.txt has stored a lot of camera parameters.**Is it a common file? We do not need to modify it?** For example, if my camera is Acer CL-5300, do I need to delete other camera parameters and only keep "Acer CL-5300; 5.75"
Looking forward to your reply : )

**Comment by TianQi-777** [comment]
Hey @pmoulon ,
I have solved the problem of openMVG_main_SfMInit_ImageListing, the main reason is because images and K.txt(or Readme.txt) **can not be placed in the same folder**. When detecting images, an error will occur because the storage format of image and K.txt(or Readme.txt) is different.

Now that I can successfully run **openMVG_main_SfMInit_ImageListing**, its result should look **correct**. Some of the output(sfm_data.json) looks like this:
***************************************************************************************************
...........................**(Some of the output(sfm_data.json))**
       {
            "key": 10,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483659,
                    "data": {
                        "local_path": "",
                        "filename": "100_7110.JPG",
                        "width": 2832,
                        "height": 2128,
                        "id_view": 10,
                        "id_intrinsic": 0,
                        "id_pose": 10
                    }
                }
            }
        }
..........................
*****************************************************************************************************
I can also successfully run **openMVG_main_ComputeFeatures**, but its output does not seem correct,
*****************************************************************************************************
**The terminal shows the following:**
- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
××××××××××××××××××××××××××××
Task done in (s): 15
*****************************************************************************************************
**image_describer.json full content is as follows:**
{
    "image_describer": {
        "polymorphic_id": 2147483649,
        "polymorphic_name": "SIFT_Image_describer",
        "ptr_wrapper": {
            "valid": 1,
            "data": {
                "params": {
                    "first_octave": 0,
                    "num_octaves": 6,
                    "num_scales": 3,
                    "edge_threshold": 10.0,
                    "peak_threshold": 0.03999999910593033,
                    "root_sift": true
                },
                "bOrientation": true
            }
        }
    },
    "regions_type": {
        "polymorphic_id": 2147483650,
        "polymorphic_name": "SIFT_Regions",
        "ptr_wrapper": {
            "valid": 1,
            "data": {
                "value0": [],
                "value1": []
            }
        }
    }
}
****************************************************************************************************
I don't think it's complete, I feel that the output is too small, causing the subsequent match to fail。
Then, I can successfully run **openMVG_main_ComputeMatches**. There is no error in the program, but his **output is almost empty**:
****************************************************************************************************
**The terminal shows the following:**
- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
****************************************************************************************************
I feel that there is **a problem with the openMVG_main_ComputeFeatures step**. Because the program can run normally, I do not know how to solve it and hope you can help me.

**Comment by TianQi-777** [comment]
Hello, I have solved all the problems, and I was able to successfully run all the demo.The problem with openMVG_main_ComputeMatches is that the file path is saved in the wrong place, which should strictly follow the file save path (such as images(files) and matches(files)) in the tutorial.

In addition, I found an error in the tutorial.
$ openMVG_main_ComputeStructureFromKnownPoses -i Dataset/out_Reconstruction/sfm_data.json -o Dataset/out_Reconstruction/robustFitting.json
Should be changed to
$ openMVG_main_ComputeStructureFromKnownPoses -i Dataset/out_Reconstruction/sfm_data.json -o Dataset/out_Reconstruction/robustFitting.json -m Dataset/matches

Finally,thank you for your open source code.

**Comment by pmoulon** [comment]
@TianQi-777 Happy that you solved your issue.
Sorry for my late answer. Can you indicate me which tutorial file is wrong please?

**Comment by TianQi-777** [comment]
Missing the -m parameter in the **Information and usage** section of the [openMVG_main_ComputeStructureFromKnownPoses](http://openmvg.readthedocs.io/en/latest/software/SfM/ComputeStructureFromKnownPoses/) tutorial :

The original tutorial example is:
```
$ openMVG_main_ComputeStructureFromKnownPoses -i Dataset/out_Reconstruction/sfm_data.json -o Dataset/out_Reconstruction/robustFitting.json
```

The correct tutorial should be:
```
$ openMVG_main_ComputeStructureFromKnownPoses -i Dataset/out_Reconstruction/sfm_data.json -o Dataset/out_Reconstruction/robustFitting.json -m Dataset/matches
```
