### ISSUE TITLE
Visualizing GPS coordinates using Geodesy

### ISSUE THREAD

**Issue by vishaal-sridhar** [openMVG/openMVG#1336]
http://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/

So I followed the use-case script from the Geodesy page on my images. I was able to do the global reconstruction and then tried running OpenMVS with the sfm_data.bin generated in the global reconstruction. However, it doesn't show the GPS coordinates. I would like to visualize the points like the example image (image at bottom of the Geodesy page) showed in Geodesy documentation page. Any help would be appreciated, thanks.

**Comment by pmoulon** [comment]
To view the GPS position you need to use the `-P` option or else use the binary `registration_to_exif_gps_position` that will export the GPS position https://github.com/openMVG/openMVG/blob/master/src/software/Geodesy/registration_to_exif_gps_position.cpp#L147 (and then you load 2 PLY files in your PLY viewer).

**Comment by vishaal-sridhar** [comment]
I did use the -P option during the openMVG_main_SfMInit_ImageListing and openMVG_main_GlobalSfM steps. I am just not sure where to go from here. Do I need to run the registration_to_exif_gps_position on the sfm_data.bin or something else? Thanks again.

**Comment by pmoulon** [comment]
Yes, you need to use the sfm_data.bin
