### ISSUE TITLE
Geodesy Dataset Not Available

### ISSUE THREAD

**Issue by vishaal-sridhar** [openMVG/openMVG#1337]
So I wanted to try out Geodesy to replicate the results on the Geodesy documentation page. But the link to the dataset used (Swiss Quarry) is no longer valid. Can you send me the updated link to that or email me the dataset so I can try to replicate the results? Thank you very much.

**Comment by pmoulon** [comment]
Take a look here:
https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst#use-case-command-line-used-for-a-flat-uav-survey
There is a link with the dataset address ;-)

**Comment by pmoulon** [comment]
It is now fixed.
