### ISSUE TITLE
Structure of the feature files (.desc)

### ISSUE THREAD

**Issue by TheToadAlly** [openMVG/openMVG#1338]
Dear all,

I want to understand how the binary file containing the features work. My question is two fold : 

1. Why are the descriptor 0 everywhere at some point (ie all descriptors are 0 after a certain feature)?  
2. Aren't the Sift features saved as unsigned char ?

I ran the SfM pipeline on the Sceaux dataset and I used the openMVG function to open one .desc file as follow : 

```	
        std::string desc_path = "pathToDescFile.desc";

	// Define a descriptor and a container of descriptors
	static const int DESC_LENGTH = 128;
	using Desc_T = Descriptor<float, DESC_LENGTH>;
	using Descs_T = std::vector<Desc_T, Eigen::aligned_allocator<Desc_T>>;

	//Read
	Descs_T vec_descs;
	loadDescsFromBinFile(desc_path, vec_descs);

	//Print output
	std::cout<<"Number of features : "<<vec_descs.size()<<std::endl;
	for (int i = 3134; i < 3139; ++i)
	  {
	  	std::cout<<"Feature "<<i<<"/"<<vec_descs.size()<<"\n\n"<<std::endl;
	        for (int j = 0; j < 128; ++j)
	               std::cout<<"Bin "<<j<<"/127 : "<<(vec_descs[i][j])<<"\t";
	  	std::cout<<"\n"<<std::endl;
	  }
```

For one particular feature, I observe the following result : 

`
Bin 0/127 : 0.523744	Bin 1/127 : 7.86415e-18	Bin 2/127 : 6.49961e-36	Bin 3/127 : 43529.1	Bin 4/127 : 1.02999e-39	Bin 5/127 : 3.07825	Bin 6/127 : 1.10694e-34	Bin 7/127 : 9.8994e-09	Bin 8/127 : 6.68644e+29	Bin 9/127 : 2.9448e-20	Bin 10/127 : 1.21752e-22	Bin 11/127 : 671939	Bin 12/127 : 2.78564e-39	Bin 13/127 : 1.1266e-05	Bin 14/127 : 6.49721e-36	Bin 15/127 : 1.07182e-14	Bin 16/127 : 9.8021e+18	Bin 17/127 : 3.8525e-34	Bin 18/127 : 3.16283e-11	Bin 19/127 : 2.73666e+06	Bin 20/127 : 2.63532e-35	Bin 21/127 : 3.87659e+09	Bin 22/127 : 1.67415e-33	Bin 23/127 : 0.20026	Bin 24/127 : 1.34218e+08	Bin 25/127 : 2.35138e-38	Bin 26/127 : 8.26961e-09	Bin 27/127 : 2.93757e-23	Bin 28/127 : 8.53787e-30	Bin 29/127 : 2.33236e-18	Bin 30/127 : 1.67101e-36	Bin 31/127 : 0.000147849	Bin 32/127 : 0	Bin 33/127 : 0	Bin 34/127 : 0	Bin 35/127 : 0	Bin 36/127 : 0	Bin 37/127 : 0	Bin 38/127 : 0	Bin 39/127 : 0	Bin 40/127 : 0	Bin 41/127 : 0	Bin 42/127 : 0	Bin 43/127 : 0	Bin 44/127 : 0	Bin 45/127 : 0	Bin 46/127 : 0	Bin 47/127 : 0	Bin 48/127 : 0	Bin 49/127 : 0	Bin 50/127 : 0	Bin 51/127 : 0	Bin 52/127 : 0	Bin 53/127 : 0	Bin 54/127 : 0	Bin 55/127 : 0	Bin 56/127 : 0	Bin 57/127 : 0	Bin 58/127 : 0	Bin 59/127 : 0	Bin 60/127 : 0	Bin 61/127 : 0	Bin 62/127 : 0	Bin 63/127 : 0	Bin 64/127 `

I'm surprised by the magnitude of each bin. I thought using a float descriptors was the mistake, but the decoding fails for unsigned char.

Moreover bins become 0 at some point and remain so for all the rest of the features. The explanation I came up with is that the scale of the feature point detected is very small (we detected noise) and thus the descriptor is 0. Not convinced by that explanation though.

Cheers

**Comment by pmoulon** [comment]
Hi,

As you see here the default SIFT descriptor is based on 128 `unsigned char`. 
https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/regions_factory.hpp#L19

Can you try the following:
```
SIFT_Regions:: DescsT vec_descs;
loadDescsFromBinFile(desc_path, vec_descs);
```

**Comment by TheToadAlly** [comment]
Hi,

Thank you, it works. I also had to to convert the output to an unsigned int as it would otherwise display the ASCII representation of the ASCII table.
I guess the zero output was a bug that came from reading the descriptors as floats.

Cheers

**Comment by pmoulon** [comment]
Yep, you have to cast the output `static_cast<int>(val)` or `(int)val` ;-)
