### ISSUE TITLE
Error when building as shared libraries on linux

### ISSUE THREAD

**Issue by elmirjagudin** [openMVG/openMVG#1339]
If cmake build option OpenMVG_BUILD_SHARED is set to ON, the build will fail with following error:

```
Scanning dependencies of target openMVG_main_evalQuality
[ 87%] Building CXX object software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/main_evalQuality.cpp.o
[ 87%] Linking CXX executable ../../Linux-x86_64-Debug/openMVG_main_evalQuality
/usr/bin/x86_64-linux-gnu-ld: CMakeFiles/openMVG_main_evalQuality.dir/main_evalQuality.cpp.o: undefined reference to symbol '_ZN7openMVG5image15ReadImageHeaderEPKcPNS0_11ImageHeaderE'
/home/ubuntu/openMVG/build/Linux-x86_64-Debug/libopenMVG_image.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/build.make:103: recipe for target 'Linux-x86_64-Debug/openMVG_main_evalQuality' failed
make[2]: *** [Linux-x86_64-Debug/openMVG_main_evalQuality] Error 1
CMakeFiles/Makefile2:3599: recipe for target 'software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/all' failed
make[1]: *** [software/SfM/CMakeFiles/openMVG_main_evalQuality.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

cmake was run with following arguments:

```
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DOpenMVG_BUILD_SHARED=ON \
    <path-to-src>
```

This is building 'develop' branch, at commit 4c7367cdd296cc967511bad4fcdba070004ab9b5, on a Ubuntu 16.04/18.04 system.

For the record, one workaround is set the OpenMVG_BUILD_SOFTWARES build option to OFF, e.g. use this command to generate make files:

```
cmake \
    -DOpenMVG_BUILD_SHARED=ON \
    -DOpenMVG_BUILD_SOFTWARES=OFF \
    <path-to-src>
```

**Comment by elmirjagudin** [comment]
I still get the same error on develop_cmake_fixes branch.

I tried building at f5eaaed5b7abbdcb7b4f752b4689a85e82d1edd4 commit.

**Comment by elmirjagudin** [comment]
I poked around cmake files a bit more, and I'm guessing that there are two more missing link libraries for targets under software.

I tested building with following patch:  https://github.com/elmirjagudin/openMVG/commit/ddc3e2f59fa933136a5d5c3ef5bcad18cc5ef1b9

and it seems to work.

I can make a PR with that patch, if it's helpful.

**Comment by pmoulon** [comment]
It builds fine for me with the shared option (which OS are you using?).
Feel free to make a PR.

**Comment by pmoulon** [comment]
@elmirjagudin I push your fix. Please tell me if it works for you.

**Comment by elmirjagudin** [comment]
Yes, the https://github.com/openMVG/openMVG/commit/9782e7316745e46229762bab3225fa0a830f7bd2 commit fixes the issue.

I can now sucessfully build as shared libs. I'm building on Ubuntu 16.04, btw.

Thanks!

**Comment by pmoulon** [comment]
Great!
Thx for your feedback.
