### ISSUE TITLE
openMVG/image/image_container.hpp

### ISSUE THREAD

**Issue by WANGLXUE** [openMVG/openMVG#1340]
System: Ubuntu 16.04
GCC version: 4.8 / 5.4 both tried

Problem:
while: #include<openMVG/image/image_container.hpp>
get:  
       /usr/local/include/openMVG/image/image_container.hpp:30:11: error: expected nested-name-specifier before ‘Tpixel’
and more.

###
While I am trying to include other headers, other problem appears too.
The cmake, make and make install go very smooth without even any warning.
But I can't make it work.
Does any one could help me with it.
Really thanks.

**Comment by rperrot** [comment]
Could you please explain more in details your issue ? (ie: what did you do to get this error ? what was the result of the configuration ? of the building ?)

**Comment by WANGLXUE** [comment]
Dear Romuald Perrot:

Thanks ! I will close this soon.
I have solved this problem with gcc and g++ 7.
I have tried from gcc 4.8 to gcc 6. Until gcc and g++ 7,  problem is solved.

Sincerely,a
WANG

2018-06-26 1:46 GMT+09:00 Romuald Perrot <notifications@github.com>:
