### ISSUE TITLE
file name instead of camera name

### ISSUE THREAD

**Issue by bonaime** [openMVG/openMVG#1341]
Hi, 
I have a NIKON COOLPIX W300
```
exiftool -T  -make -model DSCN0039.JPG
NIKON CORPORATION       COOLPIX W300
```
I have added
NIKON COOLPIX W300;6.16

Then I have the following warnings

Warning & Error messages:
DSCN0030" model "COOLPIX W300" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DSCN0031" model "COOLPIX W300" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DSCN0032" model "COOLPIX W300" doesn't exist in the database
Please consider add your camera model and sensor width in the database.```

OpenMVG_main_SfMInit_ImageListing is using the image name instead of the brand name ! 

I just tried with last master and develop version withthe same results on Ubuntu

**Comment by pmoulon** [comment]
Can you try to add `COOLPIX W300;6.16`?
Only the model name should be used.

**Comment by bonaime** [comment]
Ok It is working better !
