### ISSUE TITLE
Views and Poses

### ISSUE THREAD

**Issue by NikolausDemmel** [openMVG/openMVG#1342]
In `SfM_Data` there is the distinction between views and poses.

As far as I understand a view corresponds to an image, i.e. there is a 1-to-1 relation between views and images. 

For intrinsics it makes sense that there is not a 1-to-1 relation, since multiple images might be associated with the same intrinsics, if it is known that they are taken from the same camera. 

However, is there ever a case where there is NO 1-to-1 relation between views and poses? Might there be a view without a pose, or more than one pose? If there is always a 1-to-1 relation, are pose and view id identical, or might they be different?

**Comment by pmoulon** [comment]
SfM_Data is designed to provide the ability to have shared intrinsics or poses.
The user after just do what he wants.
So the viewId and the poseId could be different. It all depends on what the user wants to do.

Does it is answer your question? (If not perhaps the next line will provide more detail)

You can see here that I used this feature in the past to make SfM on camera rig (where the sub_poses was known) https://github.com/openMVG/openMVG/issues/580

**Comment by NikolausDemmel** [comment]
It makes sense to have them separate as you say. I was mostly wondering if there is a use-case already in openMVG that makes use of the distinction.

Multiple views sharing the same pose in a rigid multi-camera rig is a very reasonable use case where this is needed.

Thanks @pmoulon, that clears it up.

cc @gaoxiang12
