### ISSUE TITLE
Getting single GPS location

### ISSUE THREAD

**Issue by vishaal-sridhar** [openMVG/openMVG#1343]
I have recreated the sample dataset from the Geodesy page and was able to overlay the camera locations and GPS locations on the model. However, what I want to do now is gather a single "central" location from all the GPS points. For example, if you have 20 GPS locations of the Quarry model (from Geodesy page), how can you extract 1 central GPS location which can be used to identify the location of the Quarry? 
Thanks for any help.

**Comment by pmoulon** [comment]
Hi,
If your scene is geo-registered, you can compute the mean position of the cameras (Create an Eigen array with the camera location, compute the mean). And then use this function `ecef_to_lla` https://github.com/openMVG/openMVG/blob/master/src/openMVG/geodesy/geodesy.hpp. It will provide you back the lat,lon,alt value.

If you want you can also just sample one 3d point of the quarry and compute its lat,lon,alt equivalent thanks to the depicted function.

**Comment by vishaal-sridhar** [comment]
All the images are geo tagged. What's the process for computing the mean? I have never done this before so I am not sure how to make an array with the camera locations and compute the mean.

**Comment by pmoulon** [comment]
You can set all the GPS coordinate in a Eigen array as it is done here:
https://github.com/openMVG/openMVG/blob/develop/src/software/Geodesy/registration_to_exif_gps_position.cpp#L155
And then you compute the rowwise mean.
