### ISSUE TITLE
Mac OS "OpenCV was not found." during cmake

### ISSUE THREAD

**Issue by themantalope** [openMVG/openMVG#1348]
Hi All,

Trying to build `openMVG` with the `OpenCV` examples. I have successfully built  `OpenCV` on my and have the build folder available. However whenever I run `cmake` for `openMVG` I get an error stating that "OpenCV was not found".

Here is the `cmake` command I'm using:

```bash
cmake -D CMAKE_BUILD_TYPE=RELEASE -D OpenMVG_BUILD_TESTS=ON -D OpenMVG_BUILD_EXAMPLES=ON -D OpenCV_DIR:PATH="/Users/<user>/Documents/ProgrammingProjects/PythonProjects/opencv_custom_builds/opencv/build" -D OpenMVG_USE_OPENCV=ON -G "Xcode" . ../openMVG/src/
```

The version of `OpenCV` on my machine is `4.0.0-pre` so it's possible that something in their build process has changed. I also built `OpenCV` with the additional modules (including modules for 2D feature extractors)

My understanding of `cmake` is crude, but the `find_package` function on line 381 should be looking for a `Find<package>.cmake` file in the build directory supplied, correct? In my build directory, I don't see a `FindOpenCV.cmake` file.

```cmake
# ==============================================================================
# OpenCV
# ==============================================================================
# - only external and enabled only if OpenMVG_USE_OPENCV is set to ON
# ==============================================================================
if (OpenMVG_USE_OPENCV)
  find_package( OpenCV 3.0 QUIET )
  if (NOT OpenCV_FOUND)
    message(STATUS "OpenCV was not found. Disabling OpenCV support.")
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OPENCV OFF)
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OCVSIFT OFF)
  endif (NOT OpenCV_FOUND)
endif (OpenMVG_USE_OPENCV)
```

Additionally, with the way in which the `find_package` file is used here, is it looking for `OpenCV` with version exactly equal to 3.0, or will it accept OpenCV that is greater than or equal to 3.0?

EDIT:

Changing the `openMVG` `CMakeLists.txt` file as suggested in #750  allowed the `cmake` to execute as expected and the project to build successfully.

**Comment by pmoulon** [comment]
Thanks for your feedback,
Can you please list again the code snippet you used (the modification you made)?

Seems like your are building a non official OpenCV version (4.X), and that's why the default code is not working for you ;-)

CMake does not need all the time `FindOpenCV.cmake` in your repo, since you can provide your custom path for CMake to look into to find a built package.

**Comment by themantalope** [comment]
Hi @pmoulon! Here is the code that was changed.

Original code:

```cmake
# ==============================================================================
# OpenCV
# ==============================================================================
# - only external and enabled only if OpenMVG_USE_OPENCV is set to ON
# ==============================================================================
if (OpenMVG_USE_OPENCV)
  find_package( OpenCV 3.0 QUIET )
  if (NOT OpenCV_FOUND)
    message(STATUS "OpenCV was not found. Disabling OpenCV support.")
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OPENCV OFF)
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OCVSIFT OFF)
  endif (NOT OpenCV_FOUND)
endif (OpenMVG_USE_OPENCV)
```
Updated code (as per issue #750):

```cmake
# ==============================================================================
# OpenCV
# ==============================================================================
# - only external and enabled only if OpenMVG_USE_OPENCV is set to ON
# ==============================================================================
if (OpenMVG_USE_OPENCV)
  FIND_PACKAGE( OpenCV)
  if (NOT OpenCV_FOUND OR OpenCV_VERSION VERSION_LESS "3.0.0")
    message(STATUS "OpenCV was not found. Disabling OpenCV support.")
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OPENCV OFF)
    UPDATE_CACHE_VARIABLE(OpenMVG_USE_OCVSIFT OFF)
  endif (NOT OpenCV_FOUND)
endif (OpenMVG_USE_OPENCV)
```

**Comment by pmoulon** [comment]
Thx this is fixed now!
