### ISSUE TITLE
How discover sensor with for my camera

### ISSUE THREAD

**Issue by nopaixx** [openMVG/openMVG#1352]
Hello, i can not found how to know sensor with for my camera...

Currently i have Richo Tetha SC and on web page i can see

Focal Length (35mm equivalent): | 7.3mm

Focal Length (actual): | 1.3mm

Sensor size: | 28.0735mm2 (6.17mm x 4.55mm)

¿what is the correct value?

**Comment by ahmadyan** [comment]
What do you mean "know sensor"? 

If you are looking for a actual focal length, you can read it from the exif file. PTAL at the exifParsing.cpp in OpenMVG or openMVG_main_exif_Parsing demo. The `Exif_IO_EasyExif` class will also gives you the 35mm eq. focal length, resolution, and bunch of other goodie goodies. You can also get the sensor brand name and model as well. However, these are only the numbers reported by the camera maker and might be inaccurate. 

https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/exif_IO_EasyExif.hpp

**Comment by pmoulon** [comment]
Your camera is a spherical camera.
Depending if you want to use the equirectangular panoramas or the fish eye images the sensor width will be needed or not.

If you want to use the spherical pano see here https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm

For the 2 cameras on board the sensor size dimension I'm referring for all the camera is the sensor width, so in your case the 6.17.

Feel free to ask more question and tell us if you plan to use the spherical pano or the fish eye images.

**Comment by pmoulon** [comment]
@nopaixx any feedback?

**Comment by pmoulon** [comment]
Closing due to lack of feedback.

**Comment by KyriakosZantis** [comment]
Hello,sorry to bother you but i am trying to run the openMVG for a spherical sfm. I modified tutorial_demo.py to run according to the link above, but it keeps crashing with the error below:

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0
Invalid input image graph for global SfM

I attached the tutorial_demo file.the output on my Windows 10 console and the 10 panorama images i am trying to sfm. i dont know if i am doing something wrong. 


![a 1](https://user-images.githubusercontent.com/9951771/46954819-3b1b8380-d09a-11e8-812c-689ba4f58c50.jpg)
![a 2](https://user-images.githubusercontent.com/9951771/46954821-3b1b8380-d09a-11e8-8a70-b5f37c416b25.jpg)
![a 3](https://user-images.githubusercontent.com/9951771/46954823-3b1b8380-d09a-11e8-87fd-74af59bfabf0.jpg)
![a 4](https://user-images.githubusercontent.com/9951771/46954824-3b1b8380-d09a-11e8-8238-dd76089a9623.jpg)
![a 5](https://user-images.githubusercontent.com/9951771/46954825-3b1b8380-d09a-11e8-9d11-7d212b03352c.jpg)
![a 6](https://user-images.githubusercontent.com/9951771/46954827-3bb41a00-d09a-11e8-9b8f-129858c08b89.jpg)
![a 7](https://user-images.githubusercontent.com/9951771/46954829-3bb41a00-d09a-11e8-9fa0-7c7a36d56cda.jpg)
![a 8](https://user-images.githubusercontent.com/9951771/46954830-3bb41a00-d09a-11e8-8fc3-dad5f5de6e1d.jpg)
![a 9](https://user-images.githubusercontent.com/9951771/46954831-3bb41a00-d09a-11e8-985a-1b8cd71d3c4d.jpg)
![a 10](https://user-images.githubusercontent.com/9951771/46954833-3c4cb080-d09a-11e8-8d04-607735eb9f71.jpg)

[ouput.txt](https://github.com/openMVG/openMVG/files/2478975/ouput.txt)

[tutorial_demo.txt](https://github.com/openMVG/openMVG/files/2478980/tutorial_demo.txt)

**Comment by pmoulon** [comment]
Hi,
The problem could come from the car print that stays fixed in all the images.
I would advise you to add a mask.png image to mask the car in the image for feature extraction (car in black and the other part in white).

**Comment by KyriakosZantis** [comment]
i cropped the images and keep the panoramas for the middle and up.It keeps showing the same error.Should i remove the other cars too?the red one and the black one?Adding a mask.png is it feature of your program? Thanks you so much for your response
