### ISSUE TITLE
How to export features and 3D positions after reconstruction

### ISSUE THREAD

**Issue by themantalope** [openMVG/openMVG#1353]
Hi All,

I'm thrilled I've discovered the openMVG repo. It's a great project! I've been able to successfully run the samples and I was wondering if there is some method that would allow one to export the final 3D locations and the values of the features in the 3D model. Something along the lines of 

```
feature_locations.table
| feature_id | x | y | z |
| 0 | ~ | ~ |~ |
...

feature_values.table
| feature_id | feature_values... |
| 0 | ~~~~~~~ |
....
```

**Comment by pmoulon** [comment]
Thanks for your excitement about the project.
Openmvg is powerful 😀

In your case the binary ConvertSfMDataFormat will be interesting for you.
You can convert a sfmdata.bin to a sfmdata.json by using the argument i and o with the json for the output.

Then for every 3d point you will have the image visibility and image feature positions.

Give it a try and let me know if it provides what you need 😀

**Comment by themantalope** [comment]
@pmoulon Thanks for the reply! I tried that with the sample code in `tutorial_demo.py`. I was able to find (what I think) are the 3D coordinates of a particular feature point and the `observations` from various images that correspond to that feature point. What I wasn't able to find where the actual values of the feature descriptors themselves. For example, I converted the the `sfm_data.bin` in the `reconstruction_global` directory to a json, and I get some lines in the file that look like this:

```json
"key": 1682,
            "value": {
                "X": [
                    -0.03137051229412246,
                    -0.10412993776558363,
                    1.1462400616035707
                ],
                "observations": [
                    {
                        "key": 0,
                        "value": {
                            "id_feat": 6680,
                            "x": [
                                1353.02001953125,
                                817.3629760742188
                            ]
                        }
                    },
                    {
                        "key": 1,
                        "value": {
                            "id_feat": 5150,
                            "x": [
                                1199.0400390625,
                                817.0250244140625
                            ]
                        }
                    }
                ]
```

The `observations` I understand to be (SIFT) features computed from various images of the scenes, with their corresponding `id_feat` and 2D position within the images. What I wasn't able to find were the corresponding feature descriptors for each `id_feat`. Which files will those be in? I looked the various `.bin` files in the other directories in the tutorial but I wasn't able to find them.

**Comment by pmoulon** [comment]
id_feat corresponding to the id in the feature and descriptor file.
So once Feature and descriptors are loaded you can look for them.
You can see from here https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_exportMatches.cpp#L149 that we are using the feature provider and get back the feature as the id_feat.

**Comment by themantalope** [comment]
@pmoulon Thanks for the reply. I have a few more questions regarding the structure of `sfm_data` when it is output as a `json` file.

Let's use the structure in the original comment. My understanding of the top level `key` (with value `1682`) is the 1682nd point in the final 3D model. `X` represents the final `(x,y,z)` positions of the point, and the array of `observations` are the corresponding features from various views that correspond to that 3D point. For each `JSON` object within the `observations` list, my understanding is the `key` value corresponds to the index of the view from which it came, and the `id_feat` is the feature index from that view. So for example, the first `JSON` object came from view `0`, and it was the `6680`th feature within that view. Is that the correct interpretation?

Secondly, for other people who might be interested, I added the following lines of code to [`openMVG_main_ComputeFeatures`](https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/software/SfM/main_ComputeFeatures.cpp#L328) below line 328:

```C++
if(regions){
    const std::string sRegions_json=stlplus::create_filespec(sOutDir,stlplus::basename_part(sView_filename),"json");
    std::ofstream stream(sRegions_json);
    cereal::JSONOutputArchive archive(stream);
    archive(cereal::make_nvp("regions", regions));
    stream.close();
}
```

This more or less output exactly what I was looking for - a `json` file with a list of the features (array of `(x,y,size,angle)`) and the corresponding descriptors. Here is an example of one of the files:

(Ex file `100_7100.json`)

```json
{
    "regions": {
        "polymorphic_id": 2147483649,
        "polymorphic_name": "AKAZE_Float_Regions",
        "ptr_wrapper": {
            "valid": 1,
            "data": {
                "value0": [
                    {
                        "value0": 275.80792236328127,
                        "value1": 34.85037612915039,
                        "value2": 4.800000190734863,
                        "value3": 348.890625
                    },
                    {
                        "value0": 305.26531982421877,
                        "value1": 35.24677276611328,
                        "value2": 4.800000190734863,
                        "value3": 323.98895263671877
                    },
...

                 ],
                "value1": [
                    {
                        "value0": {
                            "value0": -0.009638749063014984,
                            "value1": 0.009552089497447014,
                            "value2": 0.025195574387907983,
                            "value3": 0.02882898971438408,
                            "value4": 0.07767782360315323,
                            "value5": -0.039123572409152988,
                            "value6": 0.11141122877597809,
                            "value7": 0.08590235561132431,
                            "value8": 0.13056744635105134,
                            "value9": -0.01006151270121336,
                            "value10": 0.17675845324993134,
                            "value11": 0.2264498621225357,
                            "value12": -0.006768225226551294,
                            "value13": 0.05741145461797714,
                            "value14": 0.12523595988750459,
                            "value15": 0.1406746357679367,
                            "value16": 0.008279831148684025,
                            "value17": -0.006162391044199467,
                            "value18": 0.04663017392158508,
                            "value19": 0.04841107875108719,
                            "value20": 0.11253339797258377,
                            "value21": 0.13979852199554444,
                            "value22": 0.18137507140636445,
                            "value23": 0.2805526554584503,
                            "value24": 0.04060790687799454,
                            "value25": -0.04813073202967644,
                            "value26": 0.22994455695152284,
                            "value27": 0.27417364716529848,
                            "value28": 0.09319326281547547,
                            "value29": -0.14917899668216706,
                            "value30": 0.1953427642583847,
                            "value31": 0.18306593596935273,
                            "value32": 0.029435541480779649,
                            "value33": -0.026204513385891916,
                            "value34": 0.04370538890361786,
                            "value35": 0.034920260310173038,
                            "value36": 0.0973583459854126,
                            "value37": -0.14753545820713044,
                            "value38": 0.14207473397254945,
                            "value39": 0.22180446982383729,
                            "value40": -0.06091159209609032,
                            "value41": -0.09390408545732498,
                            "value42": 0.1389305740594864,
                            "value43": 0.15848232805728913,
                            "value44": 0.03213450312614441,
                            "value45": -0.03583655133843422,
                            "value46": 0.0594199039041996,
                            "value47": 0.052173666656017306,
                            "value48": 0.007725922856479883,
                            "value49": 0.010279063135385514,
                            "value50": 0.02705066278576851,
                            "value51": 0.029089927673339845,
                            "value52": 0.05358273908495903,
                            "value53": 0.30516234040260317,
                            "value54": 0.10565882176160813,
                            "value55": 0.3294772803783417,
                            "value56": -0.033764444291591647,
                            "value57": 0.15389017760753632,
                            "value58": 0.05863067880272865,
                            "value59": 0.17254826426506043,
                            "value60": 0.002965678693726659,
                            "value61": 0.025843368843197824,
                            "value62": 0.017415978014469148,
                            "value63": 0.04634775593876839
                        }
                    },
```

In this case I used the `AKAZE` floating point descriptors (hence the length of each descriptor as a 64-dimensional vector of `floats`).

I just want to make sure that I have the correct interpretation of the various `keys` and `id_feats`. It should be fairly straight forward to hash all the descriptors from each view and match them later.

**Comment by pmoulon** [comment]
>  Is that the correct interpretation?

Your understanding is right.

Serializing the `regions` as a single blob can be a good idea (it makes things simple).

I have made the decision to use separate files for features and descriptors since sometimes you don't need to reload the descriptor in memory.
So the design have been made in order to maximize size in memory and add the ability to load only what we need using the correct abstract `provider` interface.

**Comment by themantalope** [comment]
@pmoulon of course - makes a lot of sense to break things up and selectively load outputs. The descriptor files, while space saving in their format were hard to read with other libraries/languages. Thanks for the help!

**Comment by pmoulon** [comment]
Thx for your feedback.
OpenMVG is generic and so we let the user do what he wants. You can use the existing or as you said log the feature & descriptor in one big file (it's up to you).
Loading the binary descriptor in other language should be doable from the existing files (https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/descriptor.hpp#L165)

**Comment by themantalope** [comment]
@pmoulon Ah thanks for pointing that out. For others who may be interested, you can write your own method to get the byte data in this manner:

Read the first `std::size_t` bytes of the file (typically for a 64-bit operating system, this is a `long` integer). This is the number of descriptors in the file. You also need some prior information about which descriptor type you used, but you can figure this out based on the data in the `image_describer.json` file. For my example. I used the OpenCV AKAZE floating point descriptors, so each descriptor in the file is a 64-dimensional vector of floats.  A simple python method to get the data is as follows:

```python
import numpy as np

with open("image.desc","rb") as f_binary:
    data = f_binary.read() #read all the data into memory

n_bytes_in_size_t = np.uintp(0).itemsize
n_desc = np.frombuffer(data[0:n_bytes_in_size_t],dtype=np.uintp)[0]

descriptor_size=64 #known a priori in this example

descriptors = np.frombuffer(data[n_bytes_in_size_t:],dtype=np.float32)
descriptors = descriptors.reshape((n_desc, descriptor_size))

```
