### ISSUE TITLE
Hello can i use this library to panoramic images?

### ISSUE THREAD

**Issue by raehyuk** [openMVG/openMVG#1356]
Hello Thanks for nice library :) 

can i use openMVG to build 3d reconstruction from panoramic images?

**Comment by pmoulon** [comment]
Hi, Just look to the documentation and you will get started: https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm

**Comment by BYTERHIT** [comment]
I follow the https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm. but when I use "openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs" . I got "- PROCESS VIEWS -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
Abort trap: 6"
why is that ? How to solve it ?

**Comment by pmoulon** [comment]
Can you provide more detail about your dataset, and the output of OpenMVG binaires?
Here I cannot say if your openMVG sfm_data.bin scene contains any valid data.

**Comment by BYTERHIT** [comment]
![9](https://user-images.githubusercontent.com/6222897/62844002-caacb580-bcf0-11e9-8f8f-16e874a1dba9.jpg)
![8](https://user-images.githubusercontent.com/6222897/62844003-cb454c00-bcf0-11e9-80d1-bdc83cebf03f.jpg)
![7](https://user-images.githubusercontent.com/6222897/62844004-cb454c00-bcf0-11e9-9703-d5315bad61d7.jpg)
![6](https://user-images.githubusercontent.com/6222897/62844006-cbdde280-bcf0-11e9-8d03-d41d4071b2e6.jpg)
![5](https://user-images.githubusercontent.com/6222897/62844007-cbdde280-bcf0-11e9-89e6-f91f54e48010.jpg)
![4](https://user-images.githubusercontent.com/6222897/62844008-cc767900-bcf0-11e9-9de4-4182c3508900.jpg)
![3](https://user-images.githubusercontent.com/6222897/62844009-cc767900-bcf0-11e9-9d07-24e7e6674704.jpg)
![2](https://user-images.githubusercontent.com/6222897/62844010-cd0f0f80-bcf0-11e9-92ad-3d3968df143f.jpg)
![13](https://user-images.githubusercontent.com/6222897/62844011-ce403c80-bcf0-11e9-962b-9cdb9b470f1d.jpg)
![12](https://user-images.githubusercontent.com/6222897/62844014-ced8d300-bcf0-11e9-89e2-dae15e5de6a2.jpg)
![11](https://user-images.githubusercontent.com/6222897/62844015-ced8d300-bcf0-11e9-8aef-745103bc133b.jpg)
![10](https://user-images.githubusercontent.com/6222897/62844016-d0a29680-bcf0-11e9-9ecd-49a56d77af92.jpg)
![1](https://user-images.githubusercontent.com/6222897/62844017-d0a29680-bcf0-11e9-8c59-41564918f736.jpg)
this is my source images. 
[recons_dir.zip](https://github.com/openMVG/openMVG/files/3490917/recons_dir.zip)
this is my reconstruction result.

**Comment by BYTERHIT** [comment]
> Can you provide more detail about your dataset, and the output of OpenMVG binaires?
> Here I cannot say if your openMVG sfm_data.bin scene contains any valid data.

I post the dataset and the result as above. Thank you for you help!

**Comment by pmoulon** [comment]
Got the problem.
OpenMVS cannot process Spherical images, you need to convert the scene from Spherical to Pinhole and OpenMVG can do that for you -> see here: https://github.com/openMVG/Image_datasets/tree/master/360_dataset -> openMVG_main_openMVGSpherical2Cubic

Note that indoor space are almost feature less and so, dense reconstruction does not work great in those environment.

Let me know the result you will obain (feel free to share a screenshot of the dense point cloud, mesh...)

**Comment by BYTERHIT** [comment]
do you have email. I post the result to you. I try two dataset. the first one is in the same room as I posted, the second one I took picture from another place. But I get bad results. the result is too big to upload here( over 10MB).

**Comment by pmoulon** [comment]
You can share to openmvg-team[AT]googlegroups.com

**Comment by BYTERHIT** [comment]
I have send the dataset to openmvg-team@googlegroups.com. Could you please check your e-mails?

**Comment by pmoulon** [comment]
Sure I will try to take a look at your data next week.

**Comment by BYTERHIT** [comment]
> Sure I will try to take a look at your data next week.

did you have any results?

**Comment by pmoulon** [comment]
The room is pretty white. Since there is not so much feature, it will be hard to have better results.

As you can see the SfM process is ok, all the camera are found at the same height (tripod). The floor and ceiling seems quite flat too:
![image](https://user-images.githubusercontent.com/3235050/65925792-1998d200-e3a7-11e9-8ba1-b5cce3a514e8.png)

If you want perfect texture on white wall you will need to project a pattern.
