### ISSUE TITLE
openMVG2openMVS toward the inside out

### ISSUE THREAD

**Issue by dytmh** [openMVG/openMVG#1361]
openMVG2WebGL The model is up

openMVG2openMVS use openmvs Viewer look, the model is down

why?

![wx20180723-174534](https://user-images.githubusercontent.com/4333197/43069664-40945c06-8ea0-11e8-9b91-886d484d8951.png)

**Comment by dytmh** [comment]
![wx20180723-174729](https://user-images.githubusercontent.com/4333197/43069741-7dba211a-8ea0-11e8-8fe7-957c1362e4a7.png)

**Comment by pmoulon** [comment]
The SfM process should start with the Y axis up but later on the BundleAdjustment is free to change the axis.
Here I just think that the convention for axis is different from OpenMVG and OpenMVS viewer.
Note that often computer vision set Z axis for camera depth and classic 3D set the Z axis for vertical.
