### ISSUE TITLE
Calibrating Multi-Camera System

### ISSUE THREAD

**Issue by otepmong** [openMVG/openMVG#1362]
While working with cdcseacave on openMVS and the fragmented faces and texture error, we identified two issues contributing to the texture error.  One of them is the inaccuracy of the camera poses and its dependency on the pattern of the object being scanned.  

We have a fixed camera position system, and have been working on pre-calculating the camera poses for OpenMVG for more accurate results.   We have tried the OpenCV multi camera calibration (https://docs.opencv.org/3.4/d2/d1c/tutorial_multi_camera_main.html), 
but have not gotten good results and also need a more automated method.  However, we did find that OpenCV aruco pattern detection (https://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html) works well in our system. Is there a way to add an option to OpenMVG to use the aruco marker detected corners + IDs as the feature/match results from the ComputeFeature/ComputeMatches stages?

![aruco_markers](https://user-images.githubusercontent.com/7981417/43236688-58842a98-903b-11e8-93e3-fdca37be5957.png)

**Comment by FlachyJoe** [comment]
See #1239

**Comment by pmoulon** [comment]
I would suggest you to create the matches from your aruco marker and then run SfM on the created matches.

1. Detect your aruco marker per image
2. Match your aruco corner marker and build tracks in the SfM_Data:: Landmarks structure.
3. Create matches and features from the tracks
4. Run SfM on the match file.

**Comment by pmoulon** [comment]
Any comments?

**Comment by otepmong** [comment]
Pierre,
We are still working on this issue.  Our system is somewhat unstable.  Importing camera poses works intermittently.   Import camera poses back to itself (set of images that generate that camera poses) seem to work fine. But when we tried doing the same with different set of images from same cameras, it does not work consistently.  We will give you more information, please stay tuned.
Thank you for checking in.

**Comment by TaoJiangMas** [comment]
Is there any example that use our own maker to make reconstruction with openMVG and openCV.
