### ISSUE TITLE
Hello ! I am curious about coordinate frame.

### ISSUE THREAD

**Issue by raehyuk** [openMVG/openMVG#1363]
Hello, Thanks for this wonderful software.

I searched documentation about coordinate frame but couldn`t find it.

Could you let me know how about coordinate frame . (i.e. how is the world origin defined)

**Comment by raehyuk** [comment]
Sorry I got the answer while searching history.

**Comment by caokui1221** [comment]
@raehyuk hello, could you tell me how is the world origin defined? I have not found a answer in history. Thanks!
