### ISSUE TITLE
ceres-solver didn't release memory

### ISSUE THREAD

**Issue by wx7531774** [openMVG/openMVG#1366]
Hi,
   Thanks for the great work, I have been working your incremental pipeline, and I find that the the memory that bundle adjustment of ceres apply is increasing as the whole process goes. Then, I debug step by step, each time BA, ceres::solve is recalled to solve the large linear equation system, this is the step lot of memory is used, however, after this computing, the memory is not released, when dealing with large number of image, the whole program is crushed. Is there any suggestion to deal with it..?

**Comment by rperrot** [comment]
This is an interesting thing, to help us investigate on this issue, could you please give us more details ? 
- what version of openMVG (develop or a release ?)
- what os is used ? 

you seems to have made some investigation, could you share it with us ? (what functions are involved in this issue for ex ?). We have to see if the issue is openMVG related or ceres related.

**Comment by wx7531774** [comment]
I use the version of release under windows with visual studio 15 x64. After adding some new images, funtion SequentialSfMReconstructionEngine::BundleAdjustment() is recalled, and inside it, the funtion of bundle_adjustment_obj.Adjust(sfm_data_, ba_refine_options) is again used. And, then, the function of ceres::Solve(ceres_config_options, &problem, &summary) will take a while to do refinement, and lots of memories are used, after this function, these appplied memories should be released, however, it didn't. And I tested my ceres individually, I find this problem doesn't happen. So, I may consider it is due to Openmvg..

**Comment by rperrot** [comment]
Thanks for all the details, we will investigate. 

@pmoulon any idea ?

**Comment by wx7531774** [comment]
Hi, I pull the new version, and I find the problem is solved. The old version I used is download on about May 2017
