### ISSUE TITLE
get nothing after Densify point cloud with manually scene.mvs,but get right result with download scene.mvs

### ISSUE THREAD

**Issue by bigTailHao** [openMVG/openMVG#1367]
@FlachyJoe @pmoulon @petern3 @Meekohi @rory             
![image](https://user-images.githubusercontent.com/30993706/43504584-97a54594-9596-11e8-87e2-e5b983026e14.png)
I can manually make sfm_data.bin with official data,but get nothing after Densify point cloud. However,get the right result with the download sfm_data.bin. I debug openMVS, find there is different version id between them.              I would like to get the exe of openMVG and the parampter of openMVS to run it.

**Comment by rperrot** [comment]
Could you please provide us more detail about your issue ? 

- versions of openMVG/openMVS ? 

Is your issue related to openMVG or openMVS (I have difficulty to understand it).

**Comment by pmoulon** [comment]
Closed to inactivity
