### ISSUE TITLE
openMVG_main_IncrementalSfM crashes in bundle adjustment

### ISSUE THREAD

**Issue by surveyorWb** [openMVG/openMVG#1368]
Hello,
I tested OpenMVG/OpenMVS with some smaller projects (30 images) and it worked fine.
Now I'm testing a bigger project (95 images) and it crashes in bundle adjustment.

My computer:
CPU: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
RAM: 125.83GB Physical Memory 29.81GB Virtual Memory
OS: Linux 4.13.0-46-generic (x86_64)
SSE & AVX compatible CPU & OS detected
MapSMtoCores for SM 6.1 is undefined; default to use 128 cores/SM
CUDA device 0 initialized: Quadro P5000 (compute capability 6.1; memory 15.88GB)

last step of computing:

 Robust Resection of view: 66
  nfa=-7598.47 inliers=5668/6667 precisionNormalized=0.00872946 precision=363.938 (iter=0 ,sample=5431,904,6039,5567,850,6459,)
  nfa=-8097.59 inliers=5120/6667 precisionNormalized=0.00406018 precision=248.203 (iter=0 ,sample=5431,904,6039,5567,850,6459,)
  nfa=-8097.59 inliers=5120/6667 precisionNormalized=0.00406018 precision=248.203 (iter=0 ,sample=5431,904,6039,5567,850,6459,)
  nfa=-8491.05 inliers=6546/6667 precisionNormalized=0.0144849 precision=468.805 (iter=2 ,sample=3417,5119,3037,3987,2399,2328,)
  nfa=-11479.9 inliers=6174/6667 precisionNormalized=0.00326792 precision=222.674 (iter=5 ,sample=4243,5878,3829,3523,2138,3005,)
  nfa=-22245.4 inliers=6619/6667 precisionNormalized=0.000130751 precision=44.5407 (iter=18 ,sample=5872,156,3691,3623,5966,2934,)
  nfa=-25899.5 inliers=6608/6667 precisionNormalized=3.57095e-05 precision=23.277 (iter=23 ,sample=4285,5753,5720,2009,4386,1520,)

-- Robust Resection 
-- Resection status: 1
-- #Points used for Resection: 6667
-- #Points validated by robust Resection: 6608
-- Threshold: 23.277

Bundle Adjustment statistics (approximated RMSE):
 #views: 1
 #poses: 1
 #intrinsics: 1
 #tracks: 6608
 #residuals: 13216
 Initial RMSE: 2.24143
 Final RMSE: 0.924764
 Time (s): 0.0409961

*** Error in `/home/my_Computer/prog/mvg_mvs/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_IncrementalSfM': double free or corruption (out): 0x00005557a75d0160 ***

Can anybody help?

**Comment by rperrot** [comment]
Which version of openMVG are you using ? a release one ? the develop branch ? 

I saw only a segfault with only one pose, does it crash at the beginning of the incremental step ?

**Comment by surveyorWb** [comment]
Sorry, I cannot check it now. I will answer after I‘m back from a journey.
