### ISSUE TITLE
Can't link Ceres Library

### ISSUE THREAD

**Issue by ryuuji06** [openMVG/openMVG#1370]
Hello,

I'm using Ubuntu and I successfully built OpenMVG, I could run the apps

openMVG_main_SfMInit_ImageListing, ...
openMVG_main_IncrementalSfM, ...
etc

and could compile some codes using it as shared libraries.

But, when I use Bundle Adjustment I'm having a problem while linking the Ceres Library (apparently no problems with code). I got the same problem trying to compile the source file "main_IncrementalSfM.cpp". The Error I got is copied below.

Can someone help me?

[100%] Linking CXX executable ../main
/usr/local/lib/libopenMVG_sfm.a(sfm_data_BA_ceres.cpp.o): In function `openMVG::sfm::Bundle_Adjustment_Ceres::Adjust(openMVG::sfm::SfM_Data&, openMVG::sfm::Optimize_Options const&)':
sfm_data_BA_ceres.cpp:(.text+0x5440): undefined reference to `ceres::Solver::Summary::Summary()'
/usr/local/lib/libceres.a(reorder_program.cc.o): In function `ceres::internal::MaybeReorderSchurComplementColumnsUsingSuiteSparse(ceres::OrderedGroups<double*> const&, ceres::internal::Program*)':
reorder_program.cc:(.text+0x193): undefined reference to `cholmod_free_sparse'
/usr/local/lib/libceres.a(reorder_program.cc.o): In function `ceres::internal::(anonymous namespace)::OrderingForSparseNormalCholeskyUsingSuiteSparse(ceres::internal::TripletSparseMatrix const&, std::vector<ceres::internal::ParameterBlock*, std::allocator<ceres::internal::ParameterBlock*> > const&, ceres::OrderedGroups<double*> const&, int*)':
reorder_program.cc:(.text+0xd13): undefined reference to `cholmod_free_sparse'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparseCholesky::~SuiteSparseCholesky()':
suitesparse.cc:(.text+0x72): undefined reference to `cholmod_free_factor'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::CreateSparseMatrix(ceres::internal::TripletSparseMatrix*)':
suitesparse.cc:(.text+0x179): undefined reference to `cholmod_triplet_to_sparse'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::CreateSparseMatrixTranspose(ceres::internal::TripletSparseMatrix*)':
suitesparse.cc:(.text+0x292): undefined reference to `cholmod_triplet_to_sparse'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::BlockAMDOrdering(cholmod_sparse_struct const*, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> >*)':
suitesparse.cc:(.text+0x5e8): undefined reference to `cholmod_amd'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparseCholesky::Solve(double const*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x7a6): undefined reference to `cholmod_free_dense'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::ApproximateMinimumDegreeOrdering(cholmod_sparse_struct*, int*)':
suitesparse.cc:(.text+0x812): undefined reference to `cholmod_amd'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::ConstrainedApproximateMinimumDegreeOrdering(cholmod_sparse_struct*, int*, int*)':
suitesparse.cc:(.text+0x835): undefined reference to `cholmod_camd'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::Cholesky(cholmod_sparse_struct*, cholmod_factor_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x108e): undefined reference to `cholmod_factorize'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::AnalyzeCholesky(cholmod_sparse_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x1460): undefined reference to `cholmod_analyze'
suitesparse.cc:(.text+0x1472): undefined reference to `cholmod_print_common'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::AnalyzeCholeskyWithNaturalOrdering(cholmod_sparse_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x1663): undefined reference to `cholmod_analyze'
suitesparse.cc:(.text+0x1675): undefined reference to `cholmod_print_common'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::AnalyzeCholeskyWithUserOrdering(cholmod_sparse_struct*, std::vector<int, std::allocator<int> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x1dc5): undefined reference to `cholmod_analyze_p'
suitesparse.cc:(.text+0x1dd7): undefined reference to `cholmod_print_common'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::CreateDenseVector(double const*, int, int)':
suitesparse.cc:(.text+0x308f): undefined reference to `cholmod_zeros'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::SuiteSparse()':
suitesparse.cc:(.text+0x11): undefined reference to `cholmod_start'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::~SuiteSparse()':
suitesparse.cc:(.text+0x21): undefined reference to `cholmod_finish'
/usr/local/lib/libceres.a(suitesparse.cc.o): In function `ceres::internal::SuiteSparse::Solve(cholmod_factor_struct*, cholmod_dense_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
suitesparse.cc:(.text+0x6e0): undefined reference to `cholmod_solve'
/usr/local/lib/libceres.a(dynamic_sparse_normal_cholesky_solver.cc.o): In function `ceres::internal::DynamicSparseNormalCholeskySolver::SolveImplUsingSuiteSparse(ceres::internal::CompressedRowSparseMatrix*, double*)':
dynamic_sparse_normal_cholesky_solver.cc:(.text+0x704): undefined reference to `cholmod_free_dense'
dynamic_sparse_normal_cholesky_solver.cc:(.text+0x714): undefined reference to `cholmod_free_factor'
/usr/local/lib/libceres.a(lapack.cc.o): In function `ceres::internal::LAPACK::SolveInPlaceUsingQR(int, int, double const*, int, double*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
lapack.cc:(.text+0x92): undefined reference to `dgels_'
/usr/local/lib/libceres.a(lapack.cc.o): In function `ceres::internal::LAPACK::EstimateWorkSizeForQR(int, int)':
lapack.cc:(.text+0x89d): undefined reference to `dgels_'
/usr/local/lib/libceres.a(lapack.cc.o): In function `ceres::internal::LAPACK::SolveInPlaceUsingCholesky(int, double const*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
lapack.cc:(.text+0x1095): undefined reference to `dpotrf_'
lapack.cc:(.text+0x10bf): undefined reference to `dpotrs_'
/usr/local/lib/libceres.a(blas.cc.o): In function `ceres::internal::BLAS::SymmetricRankKUpdate(int, int, double const*, bool, double, double, double*)':
blas.cc:(.text+0x74): undefined reference to `dsyrk_'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:126: recipe for target '../main' failed
make[2]: *** [../main] Error 1
make[2]: Leaving directory '/home/ryuuji/programming/openmvg_tests/test09/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make[1]: Leaving directory '/home/ryuuji/programming/openmvg_tests/test09/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/ryuuji/programming/openmvg_tests/test09/build'

**Comment by pmoulon** [comment]
Since like openMVG detects your installed openMVG but the suitesparse library is not forwarded.
- This dependency should come with ceres.

Can you share the output when you ran CMAKE?
Which version of Ceres, OpenMVG are you using?
 - can you try to use the last version in the develop branch.

**Comment by pmoulon** [comment]
Any comment?

**Comment by ryuuji06** [comment]
Now, I've just rebuilt openMVG and it just worked.

If the problem was with Ceres version, it was probabily because I also built (actually tried to) OpenMVS, and one of its requirements was Ceres - version 1.10 or higher.

Then, what should I do to be able to use it with both OpenMVG and OpenMVS?

**Comment by pmoulon** [comment]
You can use a pre-built and installed version of ceres on your system and use it for OpenMVG and OpenMVS.

OpenMVG should detect your installed ceres version and use it.

**Comment by ryuuji06** [comment]
I see ... I have re-installed Ceres when I tried to built OpenMVS, that must be why the error occured.
And OpenMVG will also do the same to the others third-party libraries, right?

Well, thank you for the help, @pmoulon.

**Comment by pmoulon** [comment]
Right, OpenMVG should detect the installed library and use them, else you can specify to OpenMVG where to look to find them.
