### ISSUE TITLE
SFM results are different everytime, why ?

### ISSUE THREAD

**Issue by LuffySSR** [openMVG/openMVG#1371]
nothing have been changed, output file removed before running the program, but the results are different each time

**Comment by pmoulon** [comment]
Some steps are using threading (BA with Ceres) and reproducibility is not guarantee there. 
If you want have the same results every time you can configure to run with only one thread.

**Comment by LuffySSR** [comment]
May this leads to so different results? The output .ply file sometimes 238b, and sometimes more than 3kKb....  and how to configue?

**Comment by pmoulon** [comment]
You can set your system to use one thread by using one of this command line (linux or windows):
`set OMP_NUM_THREADS 1`
`export OMP_NUM_THREADS 1`
It will be slower but you will have reproducible results.

You can also check that the initial pair is the same for your scene.
If you are eager to help reproducibility feel free to help.

**Comment by LuffySSR** [comment]
I have set my linux system to use one thread by 
`set OMP_NUM_THREADS 1`
but it does not work.  
I have test three times, got three different results... the pmvs_options.txt.ply are 1112Kib, 238b and 998Kib respectively.
The initialPair.ply have little difference.

**Comment by LuffySSR** [comment]
The problem seems have been solved.  I set it in a wrong way. Thx  @pmoulon
