### ISSUE TITLE
Build with suitesparse on macos

### ISSUE THREAD

**Issue by NikolausDemmel** [openMVG/openMVG#1374]
I wanted to check the performance difference between cxsparse and suitesparse and thus installed `suite-sparse` from homebrew. Now I get a conflict of headers when building openMVG with suitesparse enabled.

```
cmake -DSUITESPARSE=ON ../openMVG/src/

[...]

make

[...]

[ 39%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/dynamic_sparse_normal_cholesky_solver.cc.o
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:44:
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/suitesparse.h:44:
In file included from /usr/local/include/SuiteSparseQR.hpp:17:
In file included from /usr/local/include/cholmod.h:83:
/usr/local/include/SuiteSparse_config.h:85:8: error: redefinition of 'SuiteSparse_config_struct'
struct SuiteSparse_config_struct
       ^
/tmp/openMVG/src/third_party/ceres-solver/../cxsparse/Include/SuiteSparse_config.h:85:16: note: previous definition is here
typedef struct SuiteSparse_config_struct
               ^
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:44:
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/suitesparse.h:44:
In file included from /usr/local/include/SuiteSparseQR.hpp:17:
In file included from /usr/local/include/cholmod.h:83:
/usr/local/include/SuiteSparse_config.h:96:41: error: redefinition of 'SuiteSparse_config' as different kind of symbol
extern struct SuiteSparse_config_struct SuiteSparse_config ;
                                        ^
/tmp/openMVG/src/third_party/ceres-solver/../cxsparse/Include/SuiteSparse_config.h:92:3: note: previous definition is here
} SuiteSparse_config ;
  ^
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:44:
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/suitesparse.h:44:
In file included from /usr/local/include/SuiteSparseQR.hpp:17:
In file included from /usr/local/include/cholmod.h:83:
/usr/local/include/SuiteSparse_config.h:102:7: error: conflicting types for 'SuiteSparse_malloc'
void *SuiteSparse_malloc    /* pointer to allocated block of memory */
      ^
/tmp/openMVG/src/third_party/ceres-solver/../cxsparse/Include/SuiteSparse_config.h:94:7: note: previous declaration is here
void *SuiteSparse_malloc    /* pointer to allocated block of memory */
      ^
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:44:
In file included from /tmp/openMVG/src/third_party/ceres-solver/internal/ceres/suitesparse.h:44:
In file included from /usr/local/include/SuiteSparseQR.hpp:17:
In file included from /usr/local/include/cholmod.h:83:
/usr/local/include/SuiteSparse_config.h:124:7: error: conflicting types for 'SuiteSparse_free'
void *SuiteSparse_free      /* always returns NULL */
      ^
/tmp/openMVG/src/third_party/ceres-solver/../cxsparse/Include/SuiteSparse_config.h:102:7: note: previous declaration is here
void *SuiteSparse_free      /* always returns NULL */
      ^
4 errors generated.
make[2]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/dynamic_sparse_normal_cholesky_solver.cc.o] Error 1
make[1]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/all] Error 2
make: *** [all] Error 2
```

Is this expected to work?

**Comment by NikolausDemmel** [comment]
PS: The issue seems to related to the fact that there are two `SuiteSparse_config.h` with different content and different include guards:

```
cat src/third_party/cxsparse/Include/SuiteSparse_config.h

[...]

#ifndef _SUITESPARSECONFIG_H
#define _SUITESPARSECONFIG_H

[...]

typedef struct SuiteSparse_config_struct
{
    void *(*malloc_memory) (size_t) ;           /* pointer to malloc */
    void *(*realloc_memory) (void *, size_t) ;  /* pointer to realloc */
    void (*free_memory) (void *) ;              /* pointer to free */
    void *(*calloc_memory) (size_t, size_t) ;   /* pointer to calloc */

} SuiteSparse_config ;

```

```
cat /usr/local/include/SuiteSparse_config.h

[...]

#ifndef SUITESPARSE_CONFIG_H
#define SUITESPARSE_CONFIG_H

[...]

struct SuiteSparse_config_struct
{
    void *(*malloc_func) (size_t) ;             /* pointer to malloc */
    void *(*calloc_func) (size_t, size_t) ;     /* pointer to calloc */
    void *(*realloc_func) (void *, size_t) ;    /* pointer to realloc */
    void (*free_func) (void *) ;                /* pointer to free */
    int (*printf_func) (const char *, ...) ;    /* pointer to printf */
    double (*hypot_func) (double, double) ;     /* pointer to hypot */
    int (*divcomplex_func) (double, double, double, double, double *, double *);
} ;

[...]
```

**Comment by NikolausDemmel** [comment]
On my Ubuntu 16.04 machine, where the build with suitesparse seems to work, the system-wide header (`/usr/include/suitesparse/SuiteSparse_config.h`) also has different include guard and content, but the problem does not seem to arise.

The versions indicated in these config headers are:
 - OpenMVG cxsparse (`src/third_party/cxsparse/Include/SuiteSparse_config.h`): 4.0.2
 - Ubuntu 16.04 (`/usr/include/suitesparse/SuiteSparse_config.h`): 4.4.1
 - macos homebrew (`/usr/local/include/SuiteSparse_config.h`):  5.3.0

**Comment by pmoulon** [comment]
The best case scenario to use ceres with suitesparse is to compile your own ceres and tell OpenMVG to use an external ceres. This way internal cxsparse and ceres will not be compiled and OpenMVG will rely only on the provided ceres and its configuration.

**Comment by NikolausDemmel** [comment]
Ok, thanks. Maybe I'll also try to compile it withing OpenMVG, but disable cxsparse when enabling suitesparse. I don't need both.

I'll report back how that goes.

**Comment by pmoulon** [comment]
Forgot to mention, if you want to use VCPKG to build ceres and it's sparse backend, everything is documented here:
https://github.com/openMVG/openMVG/blob/develop/BUILD.md#vcpkg

**Comment by NikolausDemmel** [comment]
> Forgot to mention, if you want to use VCPKG to build ceres and it's sparse backend, everything is documented here:
https://github.com/openMVG/openMVG/blob/develop/BUILD.md#vcpkg

Thanks. This looks interesting (haven't used vcpkg before), but I find it also very convenient to use the internal ceres version, in particular changing some small things in ceres and recompiling works very smoothly that way.

I commented out the internal cxsparse and compiled with suitesparse from homebrew without any issues.

If you want, I could supply a cmake patch that disables the internal cxsparse when `SUITESPARSE=ON` is detected. Maybe only for OSX (since on Linux, at least Ubuntu 16.04, it seems to work fine with both).

**Comment by NikolausDemmel** [comment]
> Can you share if you will see any difference between the two sparse solver?
>
> In the past I did not see such a difference in timing, but thing could have change...

I haven't measured and for the smaller scale experiments I'm running currently it is not really noticeable. I use dense-schur most of the time anyway.

I just read somewhere (in the docs?) that supposedly suite-sparse > cxsparse > eigen for sparse matrix algorithms and therefore enabled suitesparse in cmake, which was fine on Ubuntu but lead to a sudden and unexpected build failure on macos after installing suite-sparse.

Maybe it doesn't matter too much unless your bottleneck is really in the sparse matrix factorization (which it might be for large-scale BA, but one should measure, you are right).

In any case I guess it would be good to handle this gracefully in cmake, no?

**Comment by pmoulon** [comment]
Normally if you are using an external ceres the internal CXSparse should not be used:
https://github.com/openMVG/openMVG/blob/master/src/third_party/CMakeLists.txt#L70

Perhaps there is a cmake issue in another place... Let me know if you want to help on this?
