### ISSUE TITLE
Cannot find openMVG   include files appear as used in third party

### ISSUE THREAD

**Issue by yonelay11** [openMVG/openMVG#1380]
I already installed openMVG develop. When this are used as a third party, they show this 
**** **Selecting Windows SDK version  to target Windows 10.0.17134.
CMake Error at C:/Users/Arr Rang/openMVG/openMVG_install/share/openMVG/cmake/OpenMVGConfig.cmake:42 (message):
  Failed to find OPENMVG - OpenMVG install root: C:/Users/Arr
  Rang/openMVG/openMVG_install/share/openMVG/cmake.  Cannot find openMVG
  include files.
Call Stack (most recent call first):
  C:/Users/Arr Rang/openMVG/openMVG_install/share/openMVG/cmake/OpenMVGConfig.cmake:74 (OPENMVG_REPORT_NOT_FOUND)
  CMakeLists.txt:4 (find_package)

Configuring incomplete, errors occurred!
See also "D:/YONE/Code_Test/openMVG_Project/Build/CMakeFiles/CMakeOutput.log".
See also "D:/YONE/Code_Test/openMVG_Project/Build/CMakeFiles/CMakeError.log".**
Please give me instruction how to fix this issue. Thank You

**Comment by sushil-bharati** [comment]
How are you configuring your CMake flags in Windows? Can you share a screenshot? Also, can you post your error log files. Make sure you have all the path correctly fed to CMake before building.

**Comment by yonelay11** [comment]
Hello,Now this error is OK and
![cmake](https://user-images.githubusercontent.com/34397817/44772573-3d7e5880-ab94-11e8-94f3-0c9e1011df3a.png)
 I used CMake-GUI as in figure. And then, I tried small  code for testing. After #include, nothing is appear such as "openMVG/features/svg_features.hpp". I don't know Why. I think there is no automatically link libraries and include files. Here is my CMakeLists.txt.
******cmake_minimum_required(VERSION 2.8)
project(AC_Ransac_Test)

find_package (OpenMVG REQUIRED)
include_directories($ {OPENMVG_INCLUDE_DIRS})

#AC_Ransac_Test with SfM
add_executable(AC_Ransac_Test AC_Ransac_Test.cpp)
target_link_libraries(AC_Ransac_Test ${OPENMVG_LIBRARIES})**
Please advice me where should I fix this issues.

**Comment by sushil-bharati** [comment]
which editor are you using?
