### ISSUE TITLE
openMVG_main_ComputeMatches 'neato' is not recognized

### ISSUE THREAD

**Issue by alanjt** [openMVG/openMVG#1390]
When I run openMVG_main_ComputeMatches I get the following output, which includes the error message
"'neato' is not recognized as an internal or external command, operable program or batch file."

Is this important?, the results appear OK.

TIA
Alan

-----------------------------------------------------
C:\Users\Alan\Documents\TSR2\Photogrametry\oMVGFrontCockpitClipCalib>C:\Users\Alan\Documents\Photogrametry\openMVG\install\bin\openMVG_main_ComputeMatches -r .8 -i matches\sfm_data.json -o matches
 You called :
C:\Users\Alan\Documents\Photogrametry\openMVG\install\bin\openMVG_main_ComputeMatches
--input_file matches\sfm_data.json
--out_dir matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
         PREVIOUS RESULTS LOADED; #pair: 4560
'neato' is not recognized as an internal or external command,
operable program or batch file.

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

**Comment by pmoulon** [comment]
Neato is an optional dependency that is used to display the graph. You can install it through Graphviz.

So it's fine not having it ;-)
