### ISSUE TITLE
resection using P3P return pose using KRT_fromP

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#1401]
Hi,
I don't understand subject quiet well, but I think something odd in the code, so correct me if I'm wrong.
In resection function in incremental pipeline, SfM_Localizer::Localize return pose by this code 
```
resection_data.projection_matrix = P;
      Mat3 K, R;
      Vec3 t;
      KRt_From_P(P, &K, &R, &t);
pose = geometry::Pose3(R, -R.transpose() * t);
```
while models are created at P3PSolver_Ke by this code
```
for (const auto & rot_trans_it : rotation_translation_solutions) {
      Mat34 P;
      P_From_KRt( Mat3::Identity(),          // intrinsics
                  std::get<0>(rot_trans_it), // rotation
                  std::get<1>(rot_trans_it), // translation
                  &P);
      models->push_back(P);
}
```
so I think in case of using P3P, P should be R|T not K(R|T) since computation of KRt_From_P will result a K matrix which is not identity and will change value of R,T

**Comment by pmoulon** [comment]
Hi,
Both solver are using bearing vectors as input (camera to feature rays) and so later on we assume that P should be using a K Identity matrix. It is what you see here.

`KRt_From_P` should return an identity matrix and you can test it.

**Comment by RamadanAhmed** [comment]
Thank you for quick reply, I will test it
