### ISSUE TITLE
"Invalid regions files for the view" during ComputeMatches

### ISSUE THREAD

**Issue by fasterthan** [openMVG/openMVG#1404]
Hello, I am trying to run `openMVG_main_ComputeMatches` on my image dataset but when I do I receive the following error message:
```
[david@hmd Photogrammetry]$ openMVG_main_ComputeMatches -g e -i OpenMVG/sfm_data.json -o OpenMVG/matches -f 1
 You called : 
openMVG_main_ComputeMatches
--input_file OpenMVG/sfm_data.json
--out_dir OpenMVG/matches
Optional parameters:
--force 1
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: KeckCAVES_G16/IMG_0179.JPG
*Invalid regions files for the view: Invalid regions files for the view: KeckCAVES_G16/IMG_0183.JPG
KeckCAVES_G16/IMG_0180.JPGInvalid regions files for the view: KeckCAVES_G16/IMG_0185.JPG
Invalid regions files for the view: KeckCAVES_G16/IMG_0184.JPGInvalid regions files for the view: KeckCAVES_G16/IMG_0186.JPG
Invalid regions files for the view: KeckCAVES_G16/IMG_0181.JPG

*
Invalid regions files for the view: KeckCAVES_G16/IMG_0182.JPG

Invalid regions.
```

Any help in the matter is greatly appreciated.

**Comment by rjanvier** [comment]
Hi,
Maybe there is simply no *.feat/*.desc file into your `OpenMVG/matches`.

**Comment by fasterthan** [comment]
> Hi,
> Maybe there is simply no _.feat/_.desc file into your `OpenMVG/matches`.

Hi @rjanvier, thanks for your response.

I'm not sure what you mean. In a directory I created called `features` are `.feat` and `.desc` files for each image in my dataset, as well as a file called `image_describer.json`. There is nothing in my `matches` directory.

**Comment by rjanvier** [comment]
Then you should target your `features` directory with the `-o` flag, not `OpenMVG/matches`.

**Comment by pmoulon** [comment]
The pipeline expect to have the `.feat`, `.desc` and `image_describer.jso` in the same folder as the `sfm_data.json`.

So you can create symbolic links to those files in your `OpenMVG ` folder, or just use the same forlder as out parameter for InitImageListing and ComputeFeatures

**Comment by fasterthan** [comment]
> Then you should target your `features` directory with the `-o` flag, not `OpenMVG/matches`.

This solved the issue. Thank you everyone for the support.

**Comment by yolingen23** [comment]
> gurturk@gurturk:~$ openMVG_main_ComputeMatches -i /home/gurturk/Desktop/openMVG/deneme4/matches/sfm_data.json -o /home/gurturk/Desktop/deneme5/aa/ -g e
 You called : 
openMVG_main_ComputeMatches
--input_file /home/gurturk/Desktop/openMVG/deneme4/matches/sfm_data.json
--out_dir /home/gurturk/Desktop/deneme5/aa/
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096068.JPG
***Invalid regions files for the view: Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096072.JPG
**Invalid regions files for the view: */home/gurturk/Desktop/deneme3/G0096069.JPG/home/gurturk/Desktop/deneme3/G0096073.JPGInvalid regions files for the view: Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096071.JPG
***Invalid regions files for the view: */home/gurturk/Desktop/deneme3/G0096070.JPG

***Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096074.JPG***
/home/gurturk/Desktop/deneme3/G0096067.JPG*
***
******
Invalid regions.
gurturk@gurturk:~$ openMVG_main_ComputeMatches -i /home/gurturk/Desktop/openMVG/deneme4/matches/sfm_data.json -o /home/gurturk/Desktop/openMVG/deneme5/aa/ -g e
 You called : 
openMVG_main_ComputeMatches
--input_file /home/gurturk/Desktop/openMVG/deneme4/matches/sfm_data.json
--out_dir /home/gurturk/Desktop/openMVG/deneme5/aa/
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096072.JPG
***Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096069.JPG
Invalid regions files for the view: Invalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096071.JPGInvalid regions files for the view: /home/gurturk/Desktop/deneme3/G0096070.JPG
*Invalid regions files for the view: **/home/gurturk/Desktop/deneme3/G0096073.JPG
***Invalid regions files for the view: */home/gurturk/Desktop/deneme3/G0096068.JPG
/home/gurturk/Desktop/deneme3/G0096067.JPG***
**Invalid regions files for the view: */home/gurturk/Desktop/deneme3/G0096074.JPG
*
**********
Invalid regions.



@pmoulon  I'm hvae the same problem. Can you explain in more detail your last mention? 

> So you can create symbolic links to those files in your OpenMVG folder, or just use the same folder as out parameter for InitImageListing and ComputeFeatures

**Comment by pmoulon** [comment]
OpenMVG reuse past loaded region if there is any in the match/out folder.
You can either try the `-f 1` option to force OpenMVG to recompute the features and do not try to load existing one or remove everything except the sfm_data.json file in your out folder.

**Comment by yolingen23** [comment]
> gurturk@gurturk:~$ openMVG_main_ComputeMatches -i /home/gurturk/Desktop/openmvg_matches/sfm_data.json -o /home/gurturk/Desktop/new/ -f 1
 You called : 
openMVG_main_ComputeMatches
--input_file /home/gurturk/Desktop/openmvg_matches/sfm_data.json
--out_dir /home/gurturk/Desktop/new/
Optional parameters:
--force 1
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches



its done thank you very much @pmoulon

**Comment by Z-Jeff** [comment]
When I run "openMVG_main_ComputeMatches -i output/matches/sfm_data.json -o output/matches", it occurs "Invalid regions files for the view".
But there is no error when I run "openMVG_main_ComputeMatches -i output/matches/sfm_data.json -o output/matches/".
Really strange, **/** makes different.
Use "-o output/mathces/" instead of "-o output/mathces"!

**Comment by pmoulon** [comment]
@Z-Jeff Which OS system are you using?
Could be this function reporting a different folder https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeMatches.cpp#L152

**Comment by dalnoguer** [comment]
Hello,

I am running into a similar issue as described above. I create the sfm_data.json, then compute features and when trying to compute matches the following error pops up.

```
base ❯ openMVG_main_ComputeMatches -i /home/dnoguer/openmvg/DIR-eeqnyUlOuV/matches/sfm_data.json -o /home/dnoguer/openmvg/DIR-eeqnyUlOuV/matches -f 1
INFO: [main_ComputeMatches.cpp:114]  You called :
openMVG_main_ComputeMatches
--input_file /home/dnoguer/openmvg/DIR-eeqnyUlOuV/matches/sfm_data.json
--output_file /home/dnoguer/openmvg/DIR-eeqnyUlOuV/matches
--pair_list
Optional parameters:
--force 1
--ratio 0.8
--nearest_matching_method AUTO
--cache_size unlimited
--preemptive_feature_used/count 0 / 200
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7094865573.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7096265560.png
INFO: [loggerprogress.hpp:79] [- Regions Loading -] 10%
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7096065563.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7095065571.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7095865564.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7096665556.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7097265550.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7096865559.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7097465547.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7097665545.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7095265569.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7095665566.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7095465568.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7094665575.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7096465558.png
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: /home/dnoguer/openmvg/DIR-eeqnyUlOuV/images/img_DIR-eeqnyUlOuV-7097065557.png
ERROR: [main_ComputeMatches.cpp:195] Cannot load view regions from: /home/dnoguer/openmvg/DIR-eeqnyUlOuV.
```

I have double checked that keypoint locations make sense by exporting keypoints. Also, .feat .desc and image_describer.json are in the same matches directory. Any idea what am I missing?

Thanks in advance :)

**Comment by pmoulon** [comment]
Hello @dalnoguer,
OpenMVG 2.0 API changes slightly, you can notice here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/SfM_SequentialPipeline.py.in#L62
-o needs now to be a file path, and not a folder.
API update allow to customize the output file and be more generic

**Comment by dalnoguer** [comment]
Great, thanks for the quick response 👍

**Comment by pmoulon** [comment]
You are welcome ;-)

**Comment by sikongwen** [comment]
PS C:\Users\86132> G:\openMVG\build6\Windows-AMD64-Release\Release\openMVG_main_SfM -i F:\ADV\360\dataset_out\matches\sfm_data.json -m F:\ADV\360\dataset_out\matches\matches.f.bin -o F:\ADV\360\dataset_out\reconstruction
INFO: [main_SfM.cpp:157]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
ERROR: [sfm_features_provider.hpp:62] Invalid feature files for the view: F:\ADV\360\photo\0_0000.jpg
ERROR: [sfm_features_provider.hpp:62] Invalid feature files for the view: F:\ADV\360\photo\0_00011.jpg
ERROR: [sfm_features_provider.hpp:62] Invalid feature files for the view: F:\ADV\360\photo\0_0001.jpg
INFO: [loggerprogress.hpp:79] [- Features Loading -] 10%
ERROR: [sfm_features_provider.hpp:62] Invalid feature files for the view: F:\ADV\360\photo\0_00010.jpg
ERROR: [main_SfM.cpp:452] Cannot load view corresponding features in directory: F:\ADV\360\dataset_out\matches\matches.f.bin.

**An error occurred while running openMVG_main_SfM. The .feat, .desc, matches.f.bin, and image_describer.json are all in the same match directory. I'm at a loss on how to fix this and would greatly appreciate any help from experts.**
