### ISSUE TITLE
Adding window bundle adjustment

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#1407]
Hi, 
I was trying to modify sequential pipeline of openMVG to only optimize a sliding window of poses(to decrease time taken by bundle adjustment).
But the problem happen after nearly 600 poses, resection estimate pose of camera in incorrect position and after that bundle adjustment failed to correct pose.
I tried openMVG pipeline and it works great but it takes long time in bundle adjustment. 
My modification is in this gist [WindowBundleAdjustment.cpp](https://gist.github.com/RamadanAhmed/c72301abf4be22b2b76b962e015f5574) 
So if anyone can help, I will be glad

**Comment by pmoulon** [comment]
The best way to solve this would just be to set some Camera poses as fix parameter in the ceres problem.

**Comment by RamadanAhmed** [comment]
I tried to fix the parameter but it still take long time in bundle adjustment due to large number of 3d points, also since I use a video I think I should optimize 3d points that exists in the window

**Comment by RamadanAhmed** [comment]
I will try it, but does it make difference to add only non-constant points and camera and optimize them , or add all points and cameras, and only portion of them will be optimized ??

**Comment by pmoulon** [comment]
Please try and let us know.

You need to have constant and non constant-point. You want to keep some parameter as fix to be sure that your optimization will not drift for the data set as const.
