### ISSUE TITLE
Tests fail on Ubuntu 16.04 with cuda 10.0

### ISSUE THREAD

**Issue by abhinavkulkarni** [openMVG/openMVG#1408]
Hi,

I have a fresh installation of `Ubuntu 16.04` with `cuda 10.0` and the tests because of segmentation fault.
I am not quite sure if `cuda` version matters because if my understanding is correct, `openMVG` does not (yet) use the GPU explicitely. The build fails without specifying `BUILD_CUDA_LIB` option as well.

You can find the recording of the terminal session here: [script-1539140788.log](https://github.com/openMVG/openMVG/files/2462985/script-1539140788.log)

Here is the recording of `BUILD_TYPE=RELEASE`, `-DENABLE_CXX11=ON` and `VERBOSE=1`: [script-1539141863.log](https://github.com/openMVG/openMVG/files/2463034/script-1539141863.log)

I have tried installing with single core command (`cmake --build . --target install`), but I get the same result.

```
~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

~$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
Thanks.

**Comment by rperrot** [comment]
Can you ensure that the test success with CUDA off ?

**Comment by abhinavkulkarni** [comment]
@rperrot: Same result with `-DBUILD_CUDA_LIB=OFF`: [script-1539195292.log](https://github.com/openMVG/openMVG/files/2465929/script-1539195292.log)

**Comment by rperrot** [comment]
I don't know why CUDA could be an issue here. 

We have to investigate more about your issues. 

Could you do :
$ CTEST_OUTPUT_ON_FAILURE=1 make test 

in order to have more info about what fails ?

**Comment by abhinavkulkarni** [comment]
@pmoulon: I reinstalled `ceres` and can confirm that the problems have gone away. Thank you very much for your support!
