### ISSUE TITLE
TRYING TO BUILD A SHORTER VERSION OF OPENMVG

### ISSUE THREAD

**Issue by ryuuji06** [openMVG/openMVG#1411]
Hello,

I'm using openMVG (version 1.3.0) as third party library in my project, and as I'm only detecting features and exporting .feat and .desc files, I only need libraries IMAGE and FEATURES. Therefore, I want to build only these two libraries (in order to make building faster as I'll have to do it in lots of computers).

First, I edited openMVG/src/CMakeLists.txt to keep only what is essential in my project, I succesfully built and installed it, but when compiling my project, it failed at linking by undefined reference to GOMP (described below).

Then, I edited openMVG/src/CMakeLists.txt again, this time removing gradually what I don't need. It already fails, with the same error, when I remove libraries MULTIVIEW and SFM (openMVG successfully built, but it failled when linking my project), and I can't find out where is the problem.

OBS: my project builds and links normally with the usual openMVG.

------------------------------------
------ LINKING ERROR ------
------------------------------------

[100%] Linking CXX executable ../main
/usr/local/lib/libopenMVG_features.a(AKAZE.cpp.o): In function `openMVG::features::AKAZE::Feature_Detection(std::vector<openMVG::features::AKAZEKeypoint, std::allocator<openMVG::features::AKAZEKeypoint> >&) const':
AKAZE.cpp:(.text+0x461): undefined reference to `GOMP_parallel'
...
AKAZE.cpp:(.text+0x1085): undefined reference to `GOMP_loop_dynamic_start'
AKAZE.cpp:(.text+0x179e): undefined reference to `GOMP_loop_dynamic_next'
AKAZE.cpp:(.text+0x17b0): undefined reference to `GOMP_loop_end_nowait'
...

---------------------------------------------------------
---- EDITION OF SRC/CMAKELISTS.TXT ----
---------------------------------------------------------

(I commented the respective libraries in src/openMVG/CMakeLists.txt)
add_subdirectory(openMVG)

set(OpenMVG_LIBRARIES
  openMVG_image
  openMVG_features
  openMVG_geometry
  openMVG_matching
  openMVG_matching_image_collection
  openMVG_kvld
  openMVG_multiview (COMMENTED)
  openMVG_lInftyComputerVision
  openMVG_system
  openMVG_sfm (COMMENTED)
  lemon)

**Comment by ryuuji06** [comment]
It worked with the current version of openMVG! Thank you!

This openMVG version is slightly different when using it with cmake. It doesn't have the usual OPENMVG_INCLUDE_DIRS and OPENMVG_LIBS, I have to choose the libs to link, and I had to add to include path to dependencies, in my case:

/usr/local/include/openMVG_dependencies/cereal/include

**Comment by pmoulon** [comment]
I think we fixed that in OpenMVG develop branch https://github.com/openMVG/openMVG/pull/1388

**Comment by pmoulon** [comment]
Glad it work. Happy experimenting!
