### ISSUE TITLE
OPENMVG_INCLUDE_DIRS and OPENMVG_LIBRARIES not defined

### ISSUE THREAD

**Issue by ywjia** [openMVG/openMVG#1412]
I recently re-build openMVG on Ubuntu 16.04, following the instructions at https://github.com/openMVG/openMVG/blob/master/BUILD.md, as shown in the script below:

git clone --recursive https://github.com/openMVG/openMVG.git
mkdir openMVG_build
cd openMVG_build
cmake   -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/home/user_name/openMVG_build/openMVG_install \
        -D OpenMVG_BUILD_SHARED=OFF \
        -D OpenCV_DIR=/home/user_name/OpenCV/build \
        -D OpenMVG_USE_OPENCV=ON \
        -D OpenMVG_BUILD_TESTS=ON \
        -D OpenMVG_BUILD_EXAMPLES=ON ../openMVG/src
make -j8
make -j8 test
sudo make install

No error occurred during the process and all the tests passed. However, to use the openMVG libraries in other projects, I realized that the two variables: 

OPENMVG_INCLUDE_DIRS 
OPENMVG_LIBRARIES

are not defined. Indeed, in OpenMVGConfig.cmake, only OPENMVG_FOUND and OPENMVG_VERSION are defined, but now the include and libraries.

Any help would be greatly appreciated.

**Comment by pmoulon** [comment]
Since the new version we are asking the user to directly use the library name:
See here https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake

**Comment by ywjia** [comment]
Thanks a lot for the quick reply. I followed the page you mentioned above, but it is still not working.
Here is a simple test case. Please take a look. Thanks again.


Here is CMakeLists.txt:

cmake_minimum_required(VERSION 3.1.0)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive -std=c++11")
project(transform_3d)
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
set(OpenMVG_DIR "/home/user_name/openMVG_build/openMVG_install/share/openMVG/cmake")
find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
set(DEPENDENCIES ${OpenCV_LIBS} ${OPENMVG_LIBRARIES})
add_executable(transform_3d transform_3d.cpp)
target_link_libraries(transform_3d ${DEPENDENCIES})




Here is transform_3d.cpp

#include <opencv2/opencv.hpp>
#include <opencv2/xfeatures2d.hpp>
#include <opencv2/xfeatures2d/nonfree.hpp>
#include "opencv2/video/tracking.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"
#include "../openMVG_build/openMVG_install/include/openMVG/types.hpp"
#include "../openMVG_build/openMVG/geometry/rigid_transformation3D_srt.hpp"
using namespace std;
using namespace cv;
using namespace openMVG;
int main(int argc, char * argv[]) 
{
    int image_number = 6;
    std::vector<std::vector<KeyPoint>> keypoints_A(image_number);
    std::vector<cv::Mat> descriptors_A(image_number);
    Mat3 Rc;
    Vec3 tc; 
    return EXIT_SUCCESS;
}



Here is the output from cmake ../; make

-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "3.4.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.4.0
-- Installed in: /home/user_name/openMVG_build/openMVG_install
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user_name/test/build
Scanning dependencies of target transform_3d
[ 50%] Building CXX object CMakeFiles/transform_3d.dir/transform_3d.cpp.o
In file included from /home/user_name/test/transform_3d.cpp:7:0:
/home/user_name/test/../openMVG_build/openMVG_install/include/openMVG/types.hpp:14:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
CMakeFiles/transform_3d.dir/build.make:62: recipe for target 'CMakeFiles/transform_3d.dir/transform_3d.cpp.o' failed
make[2]: *** [CMakeFiles/transform_3d.dir/transform_3d.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/transform_3d.dir/all' failed
make[1]: *** [CMakeFiles/transform_3d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ywjia** [comment]
Also, without the following line in CMakeLists.txt

set(OpenMVG_DIR "/home/user_name/openMVG_build/openMVG_install/share/openMVG/cmake")

I got the following error:

CMake Error at /home/user_name/openMVG_build/OpenMVGConfig.cmake:42 (message):
  Failed to find OPENMVG - OpenMVG install root: /home/user_name/openMVG_build.
  Cannot find openMVG include files.

**Comment by pmoulon** [comment]
You need to update your
`target_link_libraries(transform_3d ${DEPENDENCIES})`
to something like `target_link_libraries(transform_3d ${DEPENDENCIES} OpenMVG::openMVG_geometry)`

**Comment by ywjia** [comment]
Thanks.

When I add the following line to "transform_3d.cpp"

#include "openMVG/sfm/sfm_landmark_io.hpp"

I got the following error:

In file included from /home/user_name/test/transform_3d.cpp:16:0:
/home/user_name/openMVG_build/openMVG_install/include/openMVG/sfm/sfm_landmark_io.hpp:14:46: fatal error: cereal/cereal.hpp: No such file or directory
compilation terminated.

What I am missing, please?

**Comment by ywjia** [comment]
I noticed that cereal/cereal.hpp is located in "openMVG_install/openMVG_dependencies/cereal/include/"
but when I add the following lines to the code

#include "openMVG_dependencies/cereal/include/cereal/macros.hpp"
#include "openMVG_dependencies/cereal/include/cereal/cereal.hpp"

I got the following error

In file included from /home/user_name/test/transform_3d.cpp:2:0:
/home/user_name/openMVG_build/openMVG_install/include/openMVG_dependencies/cereal/include/cereal/cereal.hpp:42:29: fatal error: cereal/macros.hpp: No such file or directory
compilation terminated.

Thanks.

**Comment by pmoulon** [comment]
We made a fix recently for cereal in the develop branch https://github.com/openMVG/openMVG/pull/1388.

You can now add `cereal ` in target link libraries and you will be able to use cereal as `#include "cereal/cereal.hpp>`

**Comment by ywjia** [comment]
Thanks for the help. Solved.
