### ISSUE TITLE
OpenMVG 3D reconstruction alignment issue

### ISSUE THREAD

**Issue by kriuse** [openMVG/openMVG#1415]
I'm trying to create a 3d model from set of images using openMVG and OpenMVS .My camera set up is fixed but it is uncalibrated .I'm trying to create 3d of different objects from the same set up.I'm providing different image set for each reconstruction.But the problem is each time that is each reconstruction of objects is having different orientation or alignment.But I need orientation or alignment to be consistent for each reconstruction .What can I do for this?Please provide a solution as soon as possible

**Comment by rperrot** [comment]
Since you know that your cameras are the same, try to align the cameras from one reconstruction to the other model (using ICP).

**Comment by kriuse** [comment]
Can you please elaborate the idea of using ICP.?

**Comment by rperrot** [comment]
Using ICP you compute the transformation that maps the cameras from one point cloud to the cameras of the other point cloud. You do that for all your sets using a point cloud as a reference. 

Using this method you can maps all the point clouds to a reference frame. 

Other solution : if you know some topology about your camera setup (all aligned at the same height, rig aligned in a specific topology : circle, sphere, ... ), you can compute orientation wrt to a virtual perfect scene.

<digression>
Note about your sentence : "Please provide a solution as soon as possible". Keep in mind that you are on a OpenSource project with people providing their spare time to it. Devs cannot ensure support like if it was a paid one. We do our best to provide some support but we cannot answer to injunctions.  
</digression>

**Comment by pmoulon** [comment]
@kriuse OpenMVG can do what you want (Use a fix camera setup).

1. Perform the full SfM pipeline with a textured object. -> Here we will obtain the calibration of your camera rig.
2. Reuse the found camera location for another set of images.
- Export your sfm_data.bin to sfm_data.json with ConvertSfMData binary. Keep the view, the intrinsics and the cameras poses (-V -I -E)
- Update the views name to target your new images.
- Call ComputeFeatures and ComputeMatches
- Then call IncrementalSfM2 that will use the know camera poses. Here only the found tracks will be triangulated and then your reconstruction will be at the same location.

**Comment by kriuse** [comment]
Hi @pmoulon ,
            I tried your solution to solve my alignment issue. I tried another solution ,instead of using IncrementalSfM2  I used ComputeStructureFromKnownPoses and that also worked.

**Comment by caokui1221** [comment]
Hello @pmoulon @kriuse 
I called  IncrementalSfM2 and then convert the sfm_data.bin to scene.mvs by openMVG2openMVS binary, it works well and get the output file "scene.mvs". But when I call DensifyPointCloud binary to obtain dense point cloud, it failed:
...
terminate called after throwing an instance of 'std::bad_alloc' what():  std::bad_alloc
Aborted (core dumped)
...
But if I use  IncrementalSfM, the whole pipeline openMVG+openMVS works. So could you give me some advise? I know it would better I turn to openMVS github for help, but I would appreciate if you can give me some help. 
Thanks for your time.
