### ISSUE TITLE
[Question] Convert initial OpenCV pose and calibration to SfmData

### ISSUE THREAD

**Issue by klaheeman** [openMVG/openMVG#1424]
Hello,

I have an initial estimation of camera calibration and pose computed with OpenCV from several planar markers. I see two or three markers in each frame, and I would like to compute an optimized pose.
1) how to convert pose and matches from OpenCV to OpenMVG? Is there already code for this? (pinhole camera, aspect ratio = 1, I have feature tracks).

2) which pipeline should I use, incremental, global, or what?

**Comment by klaheeman** [comment]
Thanks. I would just create the structure, or do I need to use factories/builders/etc? The"observation" structure contains an id, what's that for?

Regarding pipelines, global or incremental? Why would I choose one or the other?

**Comment by klaheeman** [comment]
I populated SfmDAta with views, poses, intrinsics and landmarks. 
When I start the incremental pipeline, it crashes (access violation).

Do I need to add featureProvider and matchProvider? I have already filled the "observations" in sfm with 2d points and initial estimates of 3d points. 

The two methods I use to convert OpenCV estimate to SFmDAta and launch BA are as follows:

`// converte matching tracking, pose iniziali e intrinsic 
// in struttura di input per bundle adjustment
void ConvertToSfm(
	FrameDescriptor* descriptors, 
	Mat* poseRotations, Mat* poseTranslations,
	int descCount,
	Mat* faceRotations, Mat* faceTranslations, 
	Mat& intrinsic,
	openMVG::sfm::SfM_Data& sfm) {
	for (int i = 0; i < descCount; i++)
	{
		shared_ptr<openMVG::sfm::View> view(new openMVG::sfm::View());
		sfm.views[i] = view;
		view->id_view = i;
		view->id_intrinsic = i;
		view->id_pose = i;
		view->ui_height = 774;
		view->ui_width = 774;
		
		//openMVG::geometry::Pose3 pose(;
		
		sfm.poses[i] = ConvertPose(poseRotations[i], poseTranslations[i]);
	//	shared_ptr<openMVG::cameras::Pinhole_Intrinsic> intrinsic(new openMVG::cameras::Pinhole_Intrinsic())
		sfm.intrinsics[i] = shared_ptr<openMVG::cameras::Pinhole_Intrinsic>(ConvertIntrinsic(intrinsic));
		FrameDescriptor& frameDesc = descriptors[i];
		for (int faceIndex = 0; faceIndex < frameDesc.faces.size(); faceIndex++)
		{
			int globalId = frameDesc.globalFaceId[faceIndex];
			const vector<vector<Vec3f>>& currFace3d = frameDesc.faces3d[faceIndex];
			const vector<vector<Point2f>>& currFace2d = frameDesc.faces[faceIndex];

			for (int faceRowIndex = 0; faceRowIndex < currFace3d.size(); faceRowIndex++)
			{
				const vector<Vec3f>& currLine3d = currFace3d[faceRowIndex];
				const vector<Point2f>& currLine2d = currFace2d[faceRowIndex];

				for (int faceColIndex = 0; faceColIndex < currLine3d.size(); faceColIndex++)
				{
					// todo parametri numero colonne righe faccia
					Vec3f currPt3d = currLine3d[faceColIndex];
					Point2f currPt2d = currLine2d[faceColIndex];

					// id globale ordinamento di tutti i pallini
					int trackId = globalId * 11 * 30 + currPt3d[1] * 11 + currPt3d[0];
					// usa conversione coordinate globali per punto da faccia globalId a faccia zero
					Mat matVec = VecToMat(currPt3d);
					Mat converted = faceRotations[globalId] * matVec + faceTranslations[globalId];
					sfm.structure[trackId].X = ConvertVec(converted);
					sfm.structure[trackId].obs[i].id_feat = trackId;
					sfm.structure[trackId].obs[i].x = openMVG::Vec2(currPt2d.x, currPt2d.y);

				}
			}
		}
	}
}

void BundleAdjustment(openMVG::sfm::SfM_Data& sfmData) {
	
	openMVG::sfm::SequentialSfMReconstructionEngine sfmEngine(
		sfmData,
		"C:/testDAta/calibtest/sfmOutput",
		"C:/testDAta/calibtest/sfmOutput/Reconstruction_Report.html"
	);

	// Configure the features_provider & the matches_provider
	//sfmEngine.SetFeaturesProvider(feats_provider.get());
	//sfmEngine.SetMatchesProvider(matches_provider.get());

	// Configure reconstruction parameters
	openMVG::cameras::Intrinsic_Parameter_Type refineType =
		openMVG::cameras::Intrinsic_Parameter_Type::ADJUST_FOCAL_LENGTH |
		openMVG::cameras::Intrinsic_Parameter_Type::ADJUST_PRINCIPAL_POINT;

	sfmEngine.Set_Intrinsics_Refinement_Type(refineType);
	sfmEngine.SetUnknownCameraType(openMVG::cameras::EINTRINSIC::PINHOLE_CAMERA);
	sfmEngine.Set_Use_Motion_Prior(true);
	sfmEngine.Process();
}`

**Comment by klaheeman** [comment]
I checked sfm source code, and it appears that I should actually fill in the featureprovider and matchprovider. @pmoulon is that correct?
So I would fill
- intrinsics 
- poses
- views
in the SfmDAta, whereas I can discard my tracks and just use pairwise matches? Seems a pity to throw away existing information, but how would I enter the tracks otherwise?

**Comment by klaheeman** [comment]
I tried to use the mvg ceres problem setup code directly. Looks ok until the point the ceres solver is called, then it goes kaboom. 

I basically tried to reuse only this part of MVG:

```cpp

/// Bundle adjustment to refine Structure; Motion and Intrinsics
bool BundleAdjustment(
	openMVG::sfm::SfM_Data& sfm_data_, 
	openMVG::cameras::Intrinsic_Parameter_Type refinementOptions,
	bool useMotionPriors
){
	Bundle_Adjustment_Ceres::BA_Ceres_options options;
	if (sfm_data_.GetPoses().size() > 100 &&
		(ceres::IsSparseLinearAlgebraLibraryTypeAvailable(ceres::SUITE_SPARSE) ||
			ceres::IsSparseLinearAlgebraLibraryTypeAvailable(ceres::CX_SPARSE) ||
			ceres::IsSparseLinearAlgebraLibraryTypeAvailable(ceres::EIGEN_SPARSE))
		)
		// Enable sparse BA only if a sparse lib is available and if there more than 100 poses
	{
		options.preconditioner_type_ = ceres::JACOBI;
		options.linear_solver_type_ = ceres::SPARSE_SCHUR;
	}
	else
	{
		options.linear_solver_type_ = ceres::DENSE_SCHUR;
	}
	Bundle_Adjustment_Ceres bundle_adjustment_obj(options);
	
	const Optimize_Options ba_refine_options
	(refinementOptions,
		Extrinsic_Parameter_Type::ADJUST_ALL, // Adjust camera motion
		Structure_Parameter_Type::ADJUST_ALL, // Adjust scene structure
		Control_Point_Parameter(),
		useMotionPriors
	);
	//bundle_adjustment_obj.ceres_options().bVerbose_ = true;
	return bundle_adjustment_obj.Adjust(sfm_data_, ba_refine_options);
}
```




Is there some sample data that I can use to run the sfm incremental pipeline executable, just to check everything is properly compiled and there is no issue with my system setup?

Thanks!

**Comment by klaheeman** [comment]
Ok, now I switched back to the incremental pipeline as I had crashes down in ceres while solving the simple BA iterations, which I assumed were due to my incorrect setup of some ceres prerequisites. 
I have thus filled the features and matches in the featureprovider and matchprovider to comply with the implementation of sfm. All seems to start well when I run process, but then it crashes. I narrowed that down to sfm_robust_model_estimation.cpp. The calculation of bearings fails:

```cpp
// Compute the bearing vectors
  const Mat3X
    bearing1 = (*intrinsics1)(x1),
    bearing2 = (*intrinsics2)(x2);
```
The actual access violation occurs in the matrix multiplication, all involved matrices look sane:

```cpp
/**
    * @brief Get bearing vectors from image coordinates
    * @return bearing vectors
    */
    Mat3X operator () ( const Mat2X& points ) const override
    {
		std::cout << "points.col=" << points.cols() << " points.rows=" << points.rows() << std::endl;
		Mat3X homPts = points.colwise().homogeneous();
		std::cout << "hompoints.col=" << homPts.cols() << " hompoints.rows=" << homPts.rows() << std::endl;
		std::cout << "kinv=" << Kinv_ << std::endl;
               
		return Kinv_ * homPts; // kaboom
    }
```
All tests in my OpenMVG build are passing, but the issue seems definitely related to a wrong build or build setup. I have CUDA in my system, but have not configured any openMVG flags related to that. OpenMP is enabled by default as I see; I am generating the build with VisualStudio 2017 community.

Maybe this deserves an issue by itself?

**Comment by pmoulon** [comment]
I provided some answer here: https://github.com/openMVG/openMVG/issues/1431
Can you display what Kinv_ contains?

**Comment by klaheeman** [comment]
Hello,

I have attached the Kinv_ content in [openMVG/issues/1431], together with the point coordinates.

@pmoulon In order to close this thread, can you comment on my approach to port the OpenCV estimate to openMVG? Namely, whether it's the right approach to disregard the sfmData.Structure and just fill the matches and features in the matchprovider and featureprovider. Besides, it appears that the initial pose and intrinsics of the camera I filled in the sfmData are not used?
