### ISSUE TITLE
Implementation of new image describer method in openMVG

### ISSUE THREAD

**Issue by Garyqwt** [openMVG/openMVG#1425]
Hi, I'm trying to implement daisy image describer method in openMVG. I'm wondering where I should start with and which class I should modify or create. Thanks!

**Comment by s-wtnb** [comment]
source folder for detector & descriptor
https://github.com/openMVG/openMVG/tree/master/src/openMVG/features

DAISY is descriptor, I think that it is good to write in the same way as the LIOP class.
https://github.com/openMVG/openMVG/tree/master/src/openMVG/features/liop

**Comment by Garyqwt** [comment]
Hi, I'm wondering if I need to write the whole structure like SIFT. Also, how is the LIOP descriptor implemented in openMVG? Is it implemented in AKAZE image describer? Thanks!

**Comment by pmoulon** [comment]
1. How is implemented the LIOP descriptor -> the implementation try to be as close as possible of the paper https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/liop/liop_descriptor.hpp#L19

2. As you see here AKAZE keypoint + LIOP descriptor is already accessible via the API with a minor addition. See https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/akaze/image_describer_akaze.hpp#L25.
  
    - If you want you can use it from main_ComputeFeatures by doing `-m AKAZE_LIOP`. You will also need to add the corresponding factory creation here: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L207

3. If you want to implement Daisy descriptor I would advise as @s-wtnb said to add some code in https://github.com/openMVG/openMVG/tree/master/src/openMVG/features
