### ISSUE TITLE
compilation problem Ubuntu 14.04 

### ISSUE THREAD

**Issue by angelini75** [openMVG/openMVG#143]
First of all, sorry for repeating this issue. I know that there are already related issues like this, but I couldn't find the same problem when compiling. 
I don't have too much experience with compilers, so sorry again. 

OS Ubuntu 14.04 64-bit. gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

~/openMVG_Build$ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
-- Detected CPU: ivy-bridge
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenGL.cmake:161 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  dependencies/glfw/CMakeLists.txt:68 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by kate-li** [comment]
I have also encontered this problem, thanks a lot

**Comment by poanchen** [comment]
I have also encountered this problem and the solution above works for me. Thanks a lot.

**Comment by Asplund86** [comment]
I also had this problem using GLFW. Now with your help its solved. Thanks alot!
