### ISSUE TITLE
Why using translation instead of center in optimization

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#1430]
I think implementation of most of cost function (pinhole_*, pose_center) could use center instead of translation and it will de-couple optimization of rotation when using pose_center so it will be easier to apply constraint on rotation.

**Comment by pmoulon** [comment]
Actually, I don't think the parametrization will change anything.
You will also note that the existing parametrization already support to optimize rotation and translation only, or both.

Please, can you elaborate more?

**Comment by RamadanAhmed** [comment]
No, I'm not talking about parametrization, I want to optimize rotation and position for example PoseCenterConstraintCostFunction
```
template <typename T>
			bool operator()(const T*const cam_extrinsics, // R_t
			                T* residuals) const {
				using Vec3T = Eigen::Matrix<T, 3, 1>;
				Eigen::Map<const Vec3T> cam_R(&cam_extrinsics[0]);
				Eigen::Map<const Vec3T> cam_t(&cam_extrinsics[3]);
				const Vec3T cam_R_transpose(-cam_R);
				Vec3T pose_center; // Rotate the point according the camera rotation
				ceres::AngleAxisRotatePoint(cam_R_transpose.data(), cam_t.data(), pose_center.data());
				pose_center = pose_center * T(-1);
				Eigen::Map<Vec3T> residuals_eigen(residuals);
				residuals_eigen = weight_.cast<T>().cwiseProduct(pose_center - pose_center_constraint_.cast<T>());
				return true;
			}
```
after optimization rotation and translation will change, while using this center like this

```
template <typename T>
			bool operator()(const T*const cam_extrinsics, // R_t
			                T* residuals) const {
				using Vec3T = Eigen::Matrix<T, 3, 1>;
				Eigen::Map<const Vec3T> cam_R(&cam_extrinsics[0]);
				Eigen::Map<const Vec3T> pose_center(&cam_extrinsics[3]);
				pose_center = pose_center * T(-1);
				Eigen::Map<Vec3T> residuals_eigen(residuals);
				residuals_eigen = weight_.cast<T>().cwiseProduct(pose_center - pose_center_constraint_.cast<T>());
				return true;
			}
```
after optimization rotation will remain constant and position will change

**Comment by RamadanAhmed** [comment]
Why this even matter for me ? I'm applying constraint on Pose rotation (same way as Pose center) when I add it to ceres problem and enable both position and rotation , reconstructed structure is always wrong. but if one of them is enabled while other is not, it works just fine.
so i guess this might be the reason for the problem
