### ISSUE TITLE
Compile openMVG on VS2015 64bit

### ISSUE THREAD

**Issue by Eric-lsl** [openMVG/openMVG#1439]
Hi,
I just compiled openMVG using Cmake, and it seems ok. But when I compile the openMVG "ALL_BUILD" in VS 2015 (64bit, release), I get 135 succeeded and 42 failed. Most of the failed are "openMVG_image.lib(image_io.obj) : error LNK2019: unresolved external symbol......".
So, could anyone me give me a help to solve the problem?
Thanks in advance.

The results of Cmake are posted for reference.
```
-----------------------------------------------------
Checking for C++11 compiler
Checking for C++11 compiler - available
Eigen 3.3.4 found (include: C:/D/SoftwareInstall/openMVG_source/src/third_party/eigen)
Flann 1.8.4 found (include: C:/D/SoftwareInstall/openMVG_source/src/third_party/flann/src/cpp/flann)
CoinUtils 2.10.13 found (include: C:/D/SoftwareInstall/openMVG_source/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.16.10 found (include: C:/D/SoftwareInstall/openMVG_source/src/dependencies/osi_clp/Clp/src)
Osi 0.107.8 found (include: C:/D/SoftwareInstall/openMVG_source/src/dependencies/osi_clp/Osi/src/Osi)
Lemon 1.3 found (include: C:/D/SoftwareInstall/openMVG_source/src/third_party/lemon/lemon)
Could NOT find Wget (missing: WGET_EXECUTABLE) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE) 
Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
Detected Ceres version: 1.13.0 from C:/D/SoftwareInstall/openMVG_source/src/third_party/ceres-solver/include/ceres/version.h
Eigen 3.3.4 found (include: C:/D/SoftwareInstall/openMVG_source/src/third_party/eigen)
-- Found Eigen version 3.3.4: C:/D/SoftwareInstall/openMVG_source/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Building without LAPACK.
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================

Configured Eigen 3.3.4

** Found Qt5, GUI modules will be build
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation


** OpenMVG version: 1.4.0
** Build Shared libs: OFF
** Build OpenMVG tests: ON
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.0.9 (external)
LIBPNG: 1.6.34 (external)
LIBJPEG (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI: 0.107.8 (internal)
LEMON: 1.3 (internal)


Configuring done
Generating done
```

**Comment by Eric-lsl** [comment]
> As you see [here](https://ci.appveyor.com/project/pmoulon/openmvg/builds/19504889) VS2015 is building ok.
> I would do as @rperrot suggested, be sure that you have initialized all JPEG, PNG, TIFF librairies cmake variables, or force OpenMVG to use the internal versions.

I have installed JPEG, PNG, TIFF librairies using git like this:
$ git clone https://github.com/Microsoft/vcpkg
and then double click "bootstrap-vcpkg.bat" file.
But the libraries I got are X86 as they are in the ..\vcpkg\installed\x86-windows directory, could they be used in my 64bit machine?

**Comment by Eric-lsl** [comment]
Also, I have just compiled OpenMVG with Cmake, and another bug pops up for me:
*************
CMake Error at C:/Users/Shilong Liu/vcpkg/installed/x86-windows/share/ceres/CeresConfig.cmake:271 (get_filename_component):
  get_filename_component unknown component
  Liu/vcpkg/installed/x86-windows/lib/glog.lib
Call Stack (most recent call first):
  CMakeLists.txt:260 (find_package)
*************
The bug did not pop up before. I am not good at Cmake. So, how could fix this bug?
Thanks.

**Comment by pmoulon** [comment]
Here what I would try:

1. I would recommend you to do not use yet VCPKG. You can remove the directory `C:/Users/Shilong Liu/vcpkg/installed` and then re-run cmake on a clean output directory.

2. FYI: You can configure a TRIPLET to force VCPKG to build x86 or x64 bits libraries.

3. If you want to keep VCPKG files but force OpenMVG to use internal JPEG, TIFF and PNG libraries.
You can comment those three lines: https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L164

**Comment by Eric-lsl** [comment]
> Here what I would try:
> 
> 1. I would recommend you to do not use yet VCPKG. You can remove the directory `C:/Users/Shilong Liu/vcpkg/installed` and then re-run cmake on a clean output directory.
> 2. FYI: You can configure a TRIPLET to force VCPKG to build x86 or x64 bits libraries.
> 3. If you want to keep VCPKG files but force OpenMVG to use internal JPEG, TIFF and PNG libraries.
>    You can comment those three lines: https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L164

Thanks pmoulon! 
I compiled openMVG as you suggested, and finally I got the Release lib and Debug lib without error.
However, when openMVG is used for loading images, an error pops up. The code and the error are posted below.

---code---
#include "openMVG/image/image_io.hpp"

#include <cstdio>
#include <iostream>
#include <string>

using namespace openMVG;
using namespace openMVG::image;
using std::string;

int main() {
	Image<RGBColor> image; 
	const std::string jpg_filename = "";
	ReadImage(jpg_filename.c_str(), &image);
}

---error---
1>------ Build started: Project: ThreeDReconstruction, Configuration: Debug x64 ------
1>Build started 2018/11/5 15:57:14.
1>     1>
1>InitializeBuildStatus:
1>         Touching "x64\Debug\ThreeDRe.95774383.tlog\unsuccessfulbuild".
1>       ClCompile:
1>         main.cpp
1>     1>
1>c:\program files\openmvg_debug\include\openmvg\image\image_container.hpp(12): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.24
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

So, how could I fix the error?

**Comment by Eric-lsl** [comment]
Also, how could I test if openMVG is installed correctly?

**Comment by Eric-lsl** [comment]
I have fix the error that file 'Eigen/Dense' cannot been open by adding the install directory of eigen to the project.
But I still don't know how to test if openMVG is installed correctly.

**Comment by rperrot** [comment]
Try to build tests and run them. If no errors occurs thats OK !

**Comment by Eric-lsl** [comment]
I do as what you suggested, and they run correctly. Thanks rperrot.

**Comment by yonelay11** [comment]
Hello @Eric-lsl ,,
I want to ask how do you fix your error **fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory**.? I also face this error too. Please Help me. Thank you in advance.

**Comment by pmoulon** [comment]
@yonelay11 Can you share the output of your CMake initialization?
I would like to see if you have this output log `EIGEN: 3.3.4 (internal)`
