### ISSUE TITLE
openMVG vs Colmap result

### ISSUE THREAD

**Issue by williamlai3a** [openMVG/openMVG#1441]
Hi,

I am trying to run MvgMvs pipeline on a set of my own photos taken from a drone.
Below is the match graph:
![whatsapp image 2018-11-09 at 9 27 45 am](https://user-images.githubusercontent.com/642314/48238237-3336d100-e405-11e8-839a-fc6c137dc234.jpeg)

openMVG somehow only construct sparse point cloud on the largest match using globalSfm:
![whatsapp image 2018-11-09 at 9 29 06 am](https://user-images.githubusercontent.com/642314/48238239-35009480-e405-11e8-8e9e-8049b81a1a81.jpeg)

However, when I try to use Colmap with the same input, Colmap is able to use all estimated camera pose for reconstruction
![whatsapp image 2018-11-09 at 9 29 10 am](https://user-images.githubusercontent.com/642314/48238244-36ca5800-e405-11e8-8e50-d25ebdda0922.jpeg)

May I ask if there is any flag / parameters / config that can ask openMVG to produce comparable result with Colmap, i.e. globally register/match the point clouds reconstructed using individual disconnected match subgraphs?

Thanks!

**Comment by pmoulon** [comment]
You can tweak the feature parameter.
See the option `-p` on `main_ComputeFeatures`.
You can add `-p HIGH -f 1` and run again and your two cluster will certainly have better matches.

**Comment by williamlai3a** [comment]
> You can tweak the feature parameter.
> See the option `-p` on `main_ComputeFeatures`.
> You can add `-p HIGH -f 1` and run again and your two cluster will certainly have better matches.

Hi @pmoulon ,

Thanks for your quick reply.
I am already using -p ULTRA for computing these features.
Any options / config I can play with during the match?

Thanks!

**Comment by pmoulon** [comment]
You can use the ANNL2 matcher in ComputeMatches.
Also you can use the Incremental SfM pipeline. It is possible that there is a weak image connection between your 2 cluster that is broken by the triplet estimation of the GlobalSfM engine.

In order I would try `-m SIFT -p HIGH` and then `-m AKAZE_FLOAT -p HIGH` -> Both of them with the ANNL2 matcher.

**Comment by williamlai3a** [comment]
@pmoulon Thanks! I tried and it can successfully generate a similar match matrix with Colmap!

**Comment by dblatner** [comment]
@pmoulon , I'm interested in the reasons behind your recommendation. What is the purpose of running AKAZE after SIFT all using ANNL2 matcher? Did you just try this approaches or is there another reason?

**Comment by pmoulon** [comment]
I recommend to use `ANNL2` matcher to avoid the approximation made by the `CASCADE_HASHER` matcher.
Then I recommended to test either with SIFT and AKAZE. AKAZE is working better on image that are a bit blurry than SIFT.
Basically I gave suggestion to help William to have the best `view-graph` in order to keep a single connected component.
