### ISSUE TITLE
Change set of instructions in compilation

### ISSUE THREAD

**Issue by DavidGilHidalgo** [openMVG/openMVG#1447]
I have compiled openMVG on windows with Visual Studio 2017.
Everything works OK, but when I copy the executables to another server, they fail.
The main difference between the machines is the set of instructions that the CPU accepts. 
The remote server only accepts MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EMT64T and AES instruction sets.
From Visual Studio I have the option to compile with SSE and SSE2, but some executables don't work. 
I don't understand why. IncrementalSfm runs correctly, but IncrementalSfm2 fails.
I accept any kind of help.
Thank you very much.

**Comment by RamadanAhmed** [comment]
I think its the same issue [#1385](https://github.com/openMVG/openMVG/issues/1385)
you should set the target architecture in cmake and use the fix in develop branch commit [@89e894b](https://github.com/openMVG/openMVG/commit/89e894b8774afd8b9b588ee2c94ca7b81f524267) 
I hope this solve your problem

**Comment by DavidGilHidalgo** [comment]
Thanks for the answers, I finally got the executables to run on the server, following the steps indicated.
Thank you very much for your help.
