### ISSUE TITLE
OpenMVG run very slow on Android

### ISSUE THREAD

**Issue by liujeremy** [openMVG/openMVG#1451]
I tried to use openmvg on Android, but it runs very slowly, and the memory usage is very high, reaching 1G or more, the program is easy to crash.

**Comment by pmoulon** [comment]
Do you have OpenMP support in order to use multiple thread?
Which steps are using a lot of memory?

**Comment by liujeremy** [comment]
Thank you for your reply！
Yes, I have OpenMP support. I run the features_siftPutativeMatches sample on the android device, but I replaced the test image, and my test image is about 7M in size, and the Describe method uses a lot of memory.

**Comment by pmoulon** [comment]
I would advise you to use smaller images, you can downscale them.
Default feature extraction method (SIFT, AKAZE) are not designed to run efficiently on a phone. You can use less memory hungry one if you want.

**Comment by liujeremy** [comment]
Ok, thanks!
