### ISSUE TITLE
structure from known pose

### ISSUE THREAD

**Issue by Henrywh15** [openMVG/openMVG#1454]

**Comment by pmoulon** [comment]
Hi,
1. You should initialize a sfm_data scene with your views (image path and id, the camera intrinsic and the camera poses)
2. Then you compute the features
3. Then you run SfmIncremental2 or ComputeStructureFromKnowPoses binaries.

I can explain a bit more in the coming days.
Or feel free to share some sample data

**Comment by Henrywh15** [comment]
Thank you for your reply.It would be great if you can explain a bit more，I still feel confused about the detail process.

**Comment by pmoulon** [comment]
1. Use ImageListing binary to initialize a scene with your image that OpenMVG can understand (generate a sfm_data.json)
2. Run ComputeFeatures
3. Update the sfm_data.json with poses data (can be done with a python script that load your camera robot poses and update the OpenMVG's sfm_data.json file)
