### ISSUE TITLE
openMVG_main_openMVG2PMVS: No command found

### ISSUE THREAD

**Issue by zsyfight** [openMVG/openMVG#1457]
I get the error in my terminal when i run the line with:
**openMVG_main_openMVG2PMVS -i tutorial_out/reconstruction_global -o tutorial_out/reconstruction_global**
it shows "No command found‘ in the terminal, what's wrong with it? anyone know that? thank you for your answers.

**Comment by LamboAventador** [comment]
@zsyfight Did you solve it ? I got the same problem.

**Comment by zsyfight** [comment]
Yes, actually the "openMVG_main_openMVG2PMVS"  is an executable file , so when you run it in linux command lines you should use  its "absolute path" to run it or you can copy the executable file "openMVG_main_openMVG2PMVS" to you current path and then to run it.

**Comment by zsyfight** [comment]
@LamboAventador  Yes, actually the "openMVG_main_openMVG2PMVS" is an executable file , so when you run it in linux command lines you should use its "absolute path" to run it or you can copy the executable file "openMVG_main_openMVG2PMVS" to you current path and then to run it.
