### ISSUE TITLE
Intrinsic matrix calculating

### ISSUE THREAD

**Issue by JimZhou-001** [openMVG/openMVG#1458]
Hello,

Thank you for providing such a good SfM system.

I find openMVG will read EXIF information to calculate the intrinsic matrix. But is it accurate? And during the SfM process, will this matrix be refined? If yes, I want to know how to do that. The intrinsic matrix can be caculated by decomposing the fundamental matrix, right? Dose openMVG use this method?

Looking forward to your reply.

Thank you very much!

**Comment by eroswade** [comment]
hi JimZhou. 
happy new year. 
But is it accurate?   NOBP,  because of the manufacture process contains some mismatch.  strictly, every camera is not 'accurate'. 
And during the SfM process, will this matrix be refined? YES. see the main_IncrementalSfM.cpp [-f|--refineIntrinsics] Intrinsic parameters refinement option.

**Comment by pmoulon** [comment]
Thanks @eroswade.

1. As I said often, photogrammetry accuracy depends greatly on Intrinsic accuracy. OpenMVG is flexible enough to use your own calibration from the start of use a guess. By default OpenMVG is using the sensor size and the focal length stored in the EXIF metadata, it provide a OK value to start from that the SfM process will refine later.

2. If you have already the calibration factor, feel free to configure them in the sfm_data.json and OpenMVG will use them

3. The decomposition of the fundamental matrix to provide a Focal Length will be less accurate than using an approximation, but if you want to contribute this method to OpenMVG feel free to do it.
Note that for this you should assume that the image are coming from the same camera, this is not always the case.

**Comment by xiaoteng-whu** [comment]
> Thanks @eroswade.
> 
> 1. As I said often, photogrammetry accuracy depends greatly on Intrinsic accuracy. OpenMVG is flexible enough to use your own calibration from the start of use a guess. By default OpenMVG is using the sensor size and the focal length stored in the EXIF metadata, it provide a OK value to start from that the SfM process will refine later.
> 2. If you have already the calibration factor, feel free to configure them in the sfm_data.json and OpenMVG will use them
> 3. The decomposition of the fundamental matrix to provide a Focal Length will be less accurate than using an approximation, but if you want to contribute this method to OpenMVG feel free to do it.
>    Note that for this you should assume that the image are coming from the same camera, this is not always the case.

Hi @pmoulon 
I am wondering your arguement 3: the focal length decomposed by fundamental matrix is often less than an approximation. the "an approximation" means focal from EXIF metadata, or using focal = 1.2* max(w,h)??
best,
