### ISSUE TITLE
5 intrinsics 

### ISSUE THREAD

**Issue by zzxp** [openMVG/openMVG#1460]
Hi @pmoulon 
I need your help.My dataset consists of images from 5 aerial cameras, I think that Images from the same camera should share the same intrinsic, so  I write 5 intrinsics in the "openMVG_main_SfMInit_ImageListing", as shown in the next, but when I load the sfm_data.json, there is something wrong happened, The input SfM_Data file cannot be read, 

 "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483650,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483674,
                    "data": {
                        "width": 5472,
                        "height": 3648,
                        "focal_length": 5833.3333,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 2,
                "ptr_wrapper": {
                    "id": 2147483675,
                    "data": {
                        "width": 5472,
                        "height": 3648,
                        "focal_length": 5833.3333,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 2,
                "ptr_wrapper": {
                    "id": 2147483676,
                    "data": {
                        "width": 5472,
                        "height": 3648,
                        "focal_length": 5833.3333,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 2,
                "ptr_wrapper": {
                    "id": 2147483677,
                    "data": {
                        "width": 5472,
                        "height": 3648,
                        "focal_length": 5833.3333,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 2,
                "ptr_wrapper": {
                    "id": 2147483678,
                    "data": {
                        "width": 5472,
                        "height": 3648,
                        "focal_length": 5833.3333,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],

**Comment by pmoulon** [comment]
If your image are sharing the same intrinsic you should have only one camera model and make all the view pointing to the same camera ID.

It is done by default in SfmInitImageListing if you are using the grouping option.

See: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L160 and https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L468

**Comment by pmoulon** [comment]
So please just use
```SfmInitImageListing -i <IMG_PATH> -g 1 -f 5833.3333 -o <PATH>```

**Comment by zzxp** [comment]
thank you pmoulon,I find that if I use"-g 1", every image has a intrinsic ,the result is not what I want, so I change somewhere in "openMVG_main_SfMInit_ImageListing", "i" mean the index of image group, than I use "-g 0",it worked.

else
			{
				View v((*iter_image), views.size(), i, views.size(), width, height);

				// Add intrinsic related to the image (if any)
				if (intrinsic == nullptr)
				{
					//Since the view have invalid intrinsic data
					// (export the view, with an invalid intrinsic field value)
					v.id_intrinsic = UndefinedIndexT;
				}
				else
				{
					// Add the defined intrinsic to the sfm_container
					//intrinsics[v.id_intrinsic] = intrinsic;
					intrinsics[i] = intrinsic;
				}

				// Add the view to the sfm_container
				views[v.id_view] = std::make_shared<View>(v);
			}

**Comment by pmoulon** [comment]
If your problem is solved, can you close the issue?
