### ISSUE TITLE
how to use calib_toobox result?

### ISSUE THREAD

**Issue by eroswade** [openMVG/openMVG#1461]
i know how to use opencv . after read #1389 
but i using camera calibration toolbox on matlab. 
as blow shows that it's have two focal and an alpha_c
![image](https://user-images.githubusercontent.com/10239298/50627754-010e9f00-0f70-11e9-84cc-1f6c233f7ee4.png)

as fomular 

![image](https://user-images.githubusercontent.com/10239298/50627835-5ba7fb00-0f70-11e9-8847-5622316696b8.png)

but in openMVG_main_SfMInit_ImageListing, it will ignor alpha_c*fc(1), fc(2) after checkIntrinsicStringValidity

is there any hints?

**Comment by pmoulon** [comment]
We are assuming square pixel in OpenMVG, that what you have the same focal in X and Y direction.
We also assume that we don'thave any scew and so alpha_c is set to 0 ;-)

**Comment by eroswade** [comment]
@pmoulon how to input relation pose?

        {
            "key": 15,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483664,
                    "data": {
                        "local_path": "",
                        "filename": "15.jpg",
                        "width": 1900,
                        "height": 1450,
                        "id_view": 15,
                        "id_intrinsic": 1,
                        "id_pose": 15
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "Pinhole_brown_2",
                "ptr_wrapper": {
                    "id": 2147483665,
                    "data": {
                        "width": 2000,
                        "height": 1500,
                        "focal_length": 6624.070862,
                        "principal_point": [
                            1008.853968,
                            1132.158299 
                        ],
                        "disto_k3": [
                            -0.159685,
                            0.037437,
                            0.000000
                        ],
                        "disto_t2":[
                            -0.000708,
                            -0.000551
                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1,
                "polymorphic_name": "Pinhole_brown_2",
                "ptr_wrapper": {
                    "id": 2147483666,
                    "data": {
                        "width": 1900,
                        "height": 1450,
                        "focal_length": 6611.032072,
                        "principal_point": [
                            964.687952,
                            983.651464
                        ],
                        "disto_k3": [
                            -0.175989,
                            0.298818,
                            0.0
                        ],
                        "disto_t2":[
                            -0.000545,
                            0.000033
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []

there are two intrinsics, with a relation pose. 
how to input extrinsics?
otherwise, main_IncrementalSfM2 will show the error: 
" The input SfM_Data file "XXXX" cannot be read"

**Comment by eroswade** [comment]
OK,  in imagelist, contains a param called id_pose
    {
        "key": 15,
        "value": {
            "polymorphic_id": 1073741824,
            "ptr_wrapper": {
                "id": 2147483664,
                "data": {
                    "local_path": "",
                    "filename": "15.jpg",
                    "width": 1900,
                    "height": 1450,
                    "id_view": 15,
                    "id_intrinsic": 1,
                    "id_pose": 15
                }
            }
        }
    }
which can point to EXTRINSICS. 
but still don't know how to input the relation pose

i'm using Dinosaur dataset from 
https://www.cse.wustl.edu/~furukawa/research/mview/index.html
