### ISSUE TITLE
Image input format for openMVG

### ISSUE THREAD

**Issue by tusharrain28** [openMVG/openMVG#1462]
I read that openMVG can work upon ppm/pgm, jpeg, png, tiff. But can I directly use an RGB buffer as the input without the need of encoding it in a particular format?

**Comment by pmoulon** [comment]
If you want to use a RGB buffer you can implement your own reader or just convert your image to an existing supported format

See https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io.hpp and https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io.cpp
