### ISSUE TITLE
camera pose in main_IncrementalSfM2

### ISSUE THREAD

**Issue by eroswade** [openMVG/openMVG#1467]
i'm still working on main_IncrementalSfM2. 
[sfm_data.txt](https://github.com/openMVG/openMVG/files/2739832/sfm_data.txt)
as my sfm_data.json. i changed my id_pose to 1 and 2. (subpose)
run as command 
`..\openmvg\openMVG_main_IncrementalSfM2 -i E:\Work\reconstructino\Dinosaur\matches\sfm_data.json -m E:\Work\reconstructino\Dinosaur\matches\ -o E:\Work\reconstructino\Dinosaur\Reconstruction -c 4 -S "MAX_PAIR" -f NONE`

here is my question. 

1.  there have 8 pair of camera poses.
2.  only have 2 rig camera. 
3.  there must be have 8 camera poses with 2 subpose, for 16 images.
4. so that they can match together. 

as my set. there are only 2 pose. 
in SequentialSfMReconstructionEngine2::Process(), after Triangulation(). 
output the depth cloud. it's only contains 1 pose and 2 subpose. 

how to set the 'right' sfm_data.json?

**Comment by pmoulon** [comment]
id_pose should be unique. We don't share extrinsic camera properties in OpenMVG.

If you have a rig, try to run the pipeline as it is.
