### ISSUE TITLE
Feedback on proces, it looks only the first image is processed

### ISSUE THREAD

**Issue by skinkie** [openMVG/openMVG#1469]
I have tried multiple step-by-step guides with respect to the openMVG, the spherical (on Ricoh Theta images), Usage of GPS prior and Python chains for different kinds of images in this case Oblique imagery. If I can get this all to work, I promise to write a manual/tutorial for it. I would like to focus om something that in my perspective should be relatively easy to match. I ran the python sequence script which does not return results. When exporting the webgl from the steps below, it only looks as if only the first image is processed, the fence is found. Consider:

http://stefan.konink.de/openMVG/images/1.jpg
http://stefan.konink.de/openMVG/images/2.jpg
http://stefan.konink.de/openMVG/images/3.jpg

Of the Camera (I assume) I know:
Camera = Nikon D810
Sensor width = 35.9mm
F = 131.689mm

The resolution of the image are:
7360x4912

Therefore using the formula at: https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata
7360 * 131.689 / 35.9 = 26998

I also know that all the three images have partial overlap and are taken in a sequence, even have external GPS information, but no exif is available to reflect that, so I am going for the "normal naive" method, where I provide that image 1 overlaps with 2 and 3.
```
mkdir -p /tmp/images
cd /tmp/images
wget http://stefan.konink.de/openMVG/images/1.jpg
wget http://stefan.konink.de/openMVG/images/2.jpg
wget http://stefan.konink.de/openMVG/images/3.jpg
openMVG_main_SfMInit_ImageListing -i /tmp/images -o /tmp/matches -f 26998 -c 3 -g 1
openMVG_main_ComputeFeatures -i /tmp/matches/sfm_data.json -o /tmp/matches -m SIFT -p NORMAL
openMVG_main_ComputeMatches -i /tmp/matches/sfm_data.json -o /tmp/matches -g f -v 2
```

Now I assume I have to run these commands because I have 3 images, but since the python code only runs it once, in automatic mode, this might not be required (I show this later).
```
openMVG_main_IncrementalSfM -i /tmp/matches/sfm_data.json -m /tmp/matches -o /tmp/reconstruction -a 1.jpg -b 2.jpg
openMVG_main_IncrementalSfM -i /tmp/matches/sfm_data.json -m /tmp/matches -o /tmp/reconstruction -a 2.jpg -b 3.jpg
openMVG_main_ComputeStructureFromKnownPoses -i /tmp/reconstruction/sfm_data.bin -m /tmp/matches -f /tmp/matches/matches.f.bin  -o /tmp/reconstruction/robust.bin
openMVG_main_ComputeSfM_DataColor -i /tmp/reconstruction/robust.bin -o /tmp/reconstruction/robust_colorized.ply 
/opt/lidar/bin/openMVG_main_openMVG2WebGL -i /tmp/reconstruction/robust.bin -o webgl
```

In this image I only recognize the very first image, no images there after. Also when I tried to add multiple images in this stream.
http://stefan.konink.de/openMVG/webgl/

**What goes wrong:**
```
openMVG_main_GlobalSfM -i /tmp/matches/sfm_data.json -m /tmp/matches -o /tmp/reconstruction
```
```
-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.
```
**Edit:** seems to be this requires a -V of greater than 2
https://github.com/openMVG/openMVG/issues/1047#issuecomment-331501223

If you have made it to here, I thought, maybe I made my example too simple, and the video option might cancel out if it only has 3 images, and doesn't find anything more because for 2.jpg it would require 3.jpg and 4.jpg. So there we go...
```
cd /tmp/images
wget http://stefan.konink.de/openMVG/images/4.jpg
wget http://stefan.konink.de/openMVG/images/5.jpg
wget http://stefan.konink.de/openMVG/images/6.jpg
openMVG_main_SfMInit_ImageListing -i /tmp/images -o /tmp/matches -f 26998 -c 3 -g 1
openMVG_main_ComputeFeatures -i /tmp/matches/sfm_data.json -o /tmp/matches -m SIFT -p NORMAL
openMVG_main_ComputeMatches -i /tmp/matches/sfm_data.json -o /tmp/matches -g f -v 2
```
When trying to combine 3.jpg with 4.jpg:
"/!\ Robust estimation failed to compute E for this pair"

```
openMVG_main_ComputeStructureFromKnownPoses -i /tmp/reconstruction/sfm_data.bin -m /tmp/matches -f /tmp/matches/matches.f.bin  -o /tmp/reconstruction/robust.bin
openMVG_main_openMVG2WebGL -i /tmp/reconstruction/robust.bin -o webgl2
```
http://stefan.konink.de/openMVG/webgl2/

When removing the matches and starting over, something happens which I did not see before before writing it all out, and looks very interesting.

http://stefan.konink.de/openMVG/webgl3/

Now if I would have images not taken by this camera, but with an unrelated camera and lens. What would be the best strategy to combine those?

**Comment by skinkie** [comment]
Adding all photo's also give some interesting artifacts.
http://stefan.konink.de/openMVG/webgl4/
http://stefan.konink.de/openMVG/potree/

**Comment by pmoulon** [comment]
Sorry for the late answer. I will look to your issue during the week.

**Comment by rperrot** [comment]
> Now if I would have images not taken by this camera, but with an unrelated camera and lens. What would be the best strategy to combine those?

One first thing to ensure is to be able to provide camera width parameters for these camera in the database. 

You may also try to use different -p options for openMVG_main_ComputeFeatures (namely -p HIGH and -p ULTRA), it would be longer to process but it provides more features and may help to disambiguate some image matches (that may be one of your issue). 

> Adding all photo's also give some interesting artifacts.

Interesting. Did you try the -f option in openMVG_main_GlobalSfM (or openMVG_main_IncrementalSfM) to disable some intrinsic refinement options ? (Can you show us what is the computed intrinsic in sfm_data ? That can explain some artifacts)

**Comment by pmoulon** [comment]
Closed due to inactivity. Feel free to repoen
