### ISSUE TITLE
Can not open the images in openMVG_sample_features_siftPutative

### ISSUE THREAD

**Issue by yonelay11** [openMVG/openMVG#1471]
Firstly, I tried the **openMVG_sample_features_siftPutative.exe** with the demo images /imageData/StanfordMobileVisualSearch/Ace_0.png. It has no problem and well. Next, I tried this sample with my own two input images. But, they show "Couldn't open D:\HDD\CodeTest\openMVG\/imageData/der_Hass_2/IMG_0139.png fopen returned 0" and this warning "**libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data**" was also shown. I want to know where am I wrong.

**Comment by pmoulon** [comment]
1. Did you try to open your image and check if it's a PNG with compression?
2. Did you try to convert your png image to TIFF or JPG (just to test)?
