### ISSUE TITLE
std::length_error   when   loading       *.desc   files

### ISSUE THREAD

**Issue by GING-xj** [openMVG/openMVG#1472]
There was nothing wrong when I was loading _*.feat file_ but when I was using the class  **Regions**  to **Load**   _*.desc files_   in my program and it called the function 
**inline bool loadDescsFromBinFile(const std::string & sfileNameDescs,DescriptorsT & vec_desc),**
and the variable **cardDesc** in that function changed from 0 to 3688764969737794609, then it gave me the **std::length_error**.
I am confused because I write my program according to the function **load** in **sfm_regions_provider.hpp** and it seems that my input is right. Could you please help me with this problem?
And here is the code (on Ubuntu 16.04) , the problem will happen if I call **regions_ptr->Load(featFile,descFile)**:

        for(openMVG::sfm::Views::const_iterator iter=sfm_data.GetViews().begin(); iter!=sfm_data.GetViews().end();++iter)
        {
            const std::string sImageName = stlplus::create_filespec(sfm_data.s_root_path, iter->second->s_Img_path);
            const std::string basename = stlplus::basename_part(sImageName);
            const std::string featFile = stlplus::create_filespec(matches_dir_string, basename, ".feat");
            const std::string descFile = stlplus::create_filespec(matches_dir_string, basename, ".desc");

            //Load feature and describer from existing file
            std::unique_ptr<openMVG::features::Regions> regions_ptr;
            regions_ptr.reset(regions_type->EmptyClone());

            //std::length_error
            if (!regions_ptr->Load(featFile, descFile))
            {
                std::cerr << "Invalid regions files for the view: " << sImageName << std::endl;
                return EXIT_FAILURE;
            }

            /*
            * Some other code is omitted here
            * */
        }

**Comment by GING-xj** [comment]
I think I find where is the problem.I find the type of _*.desc files_ I read was **plain text document**, then I find some other *.desc files on my computer and they are **Binary files**. Actually, I don't remember when I get these files using _OpenMVG_.Is it because I use different versions of _OpenMVG_ and get different types of _*.desc files?_

**Comment by rperrot** [comment]
Maybe different versions (pre/post cereal but it's quite old things) or options. The safer way is to be sure to have same versions.
