### ISSUE TITLE
sfm_data.bin can't generate for single image in ImageDataset_SceauxCastle

### ISSUE THREAD

**Issue by sidis8066** [openMVG/openMVG#1473]
Hi I tried To generate the SfM_GlobalPipeline.py by single image but it throws error at generating sfm_data.bin i tried by giving image taken from varient cameras 
can you tell me the process to generate for new data.
![1a](https://user-images.githubusercontent.com/46783536/51909338-67150780-23f2-11e9-8342-13fc7e17bbd1.png)
![1b](https://user-images.githubusercontent.com/46783536/51909339-67150780-23f2-11e9-8c61-57be9cf8de2e.png)
![1c](https://user-images.githubusercontent.com/46783536/51909340-67150780-23f2-11e9-8efc-8245a813eb7c.png)

**Comment by rperrot** [comment]
You cannot infer scene from a single image (SfM methods can't do that). Reconstruction process needs at least 3 images (but it's usually not enough).
