### ISSUE TITLE
Reference for TriangulateNViewAlgebraic

### ISSUE THREAD

**Issue by srikanthmg85** [openMVG/openMVG#1475]
@pmoulon could you provide(and also add in the code) the reference for theory behind TriangulateNViewAlgebraic implementation. Its not referenced in the code.

**Comment by maorp** [comment]
https://en.wikipedia.org/wiki/Line%E2%80%93line_intersection#In_three_dimensions_2

**Comment by pmoulon** [comment]
Closing this thread.
We have implemented some new 2view tri method and make them easily accessible from the command line
See https://github.com/openMVG/openMVG/issues/1623
