### ISSUE TITLE
overriding recipe for target triangulation.o error at compilation time

### ISSUE THREAD

**Issue by jean59** [openMVG/openMVG#1477]
Hello,

i've got few errors when i want to compile openMVG (still in my own IDE).
Pipelines work fine, and i would like, now, to extract from them some code, for a better understanding of the process of triangulation.

So i include openMVG source directories in my IDE, beside my code, and i compile all together.

at the compilation time, there is two triangulation.o detected:
1. from openMVG/multiview/triangulation.cpp
2. from openMVG/linearProgramming/lInfinityCV/triangulation.cpp

i think it generates this error i don't come trough: "overriding recipe for target triangulation.o error "

**Comment by pmoulon** [comment]
I'm afraid that here the issue is with your build system. (Try rename the `lInfinityCV/triangulation.cpp` to `lInfinityCV/triangulation2.cpp`)
If you link a compiled version of OpenMVG you should not have this issue.

**Comment by pmoulon** [comment]
I would advise to first do not use the linearProgramming module if you want do some testing

**Comment by jean59** [comment]
I renamed as you suggested "openMVG/linearProgramming/lInfinityCV/triangulation.cpp" to "2\. openMVG/linearProgramming/lInfinityCV/triangulation2.cpp", and the compilation ended with no error.

thanks a lot.

**Comment by pmoulon** [comment]
You're welcome!
