### ISSUE TITLE
Configure CMake to build OpenMVG with Lapack on Windows 10

### ISSUE THREAD

**Issue by eranagajenia** [openMVG/openMVG#1482]
I am trying to build a Visual Studio solution of OpenMVG via CMake under Windows 10.
Doing it without LAPACK makes no problem, but when I want to add LAPACK, I constantly get a message saying that LAPACK or BLAS libraries were not found.
The Ceres Solver is then built without LAPACK and therefore without SuiteSparse.

1) I have tried to download BLAS and LAPACK lib and dll files for windows and added the folder to the Path environment variable, but it still did not work.
2) In CMake, I have tried to add an entry like: LAPACK_DIR .... and the appropriate folder. Also did not work.

I need to understand: 
Does OpenMVG already contain everything needed (LAPACK and BLAS)?
And then, what could I be doing wrong?
Or do I need to install them separately? In this case, do you have the right link to give me for such libraries under Windows?

Thanks.

**Comment by rperrot** [comment]
I don't understand exactly what is your problem. 

Can you give us the exact error(s) ? 

Eigen act as a blas replacement (http://eigen.tuxfamily.org/index.php?title=FAQ#How_does_Eigen_compare_to_BLAS.2FLAPACK.3F) for blas/lapack. There is no need to install blas/lapack in order to use openMVG.

**Comment by RamadanAhmed** [comment]
if I understand you correctly, you need to build ceres with suitesparse, I recommend to you to use vcpkg it will simplify building all libraries need by openMVG

**Comment by eranagajenia** [comment]
Thanks to both of you for your help.

Romuald, you're right OpenMVG doesn't need BLAS/LAPACK to work, I just heard they provide significant acceleration.

Ahmed, thanks, I am now running it with SuiteSparse.
By the way, I didn't know about VCPKG, very useful application!
