### ISSUE TITLE
access is denied

### ISSUE THREAD

**Issue by amitgupta7339** [openMVG/openMVG#1485]
I have done by cMake but one error is coming access is denied allbuild . How to resolve that one?

**Comment by pmoulon** [comment]
Can you share the command lines you used, and the log?

**Comment by amitgupta7339** [comment]
pop up is coming access is denied.

**Comment by pmoulon** [comment]
Are you running on Windows or Linux?

**Comment by amitgupta7339** [comment]
Windows.
some steps i did.
1) I downloaded the code from git as well as dependencies like cereal,osiclp,glfw.
2) i gave the path of src and Build path in CMake .
3)After that openMVG solution file created.I builded all files.When i run a file from sample folder its show access is denied pop up.

**Comment by pmoulon** [comment]
Can you try to run the openMVG binary from the command line?

**Comment by amitgupta7339** [comment]
Can you tell how to run?I mean command to run that file

**Comment by pmoulon** [comment]
See here to open a terminal https://www.quora.com/How-do-I-open-terminal-in-windows
Then you can `cd <Binary path>` and then call your binary

**Comment by amitgupta7339** [comment]
I have done all 7 steps mentioned in Readme file. Can you tell me what is the next step?

**Comment by WenyinWei** [comment]
There are three python files in your /path/to/your/build/folder/software/SfM/. The python files are SfM_SequentialPipeline.py, SfM_GlobalPipeline.py and tutorial_demo.py. 

Following the [documentation](https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/) to run them.

**Comment by nikhilsawlani** [comment]
@pmoulon @WenyinWei I had a similar issue butI was able to run from terminal SfM_SequentialPipeline.py, SfM_GlobalPipeline.py, and tutorial_demo.py. and now when trying to run openMVG_main_SFM_Localization.cpp project in visual studio I'm getting the "Access denied error openMVG\x64\Debug\All_build"
please can you help to resolve it

**Comment by pmoulon** [comment]
I would recommend you to use the Release build.
If you run from VisualStudio you should set the project as active target. Here you try to launch the all-build target that is a build routine and not a binary.
