### ISSUE TITLE
Alignment of meshes

### ISSUE THREAD

**Issue by UannaFF** [openMVG/openMVG#1487]
Hello, I'm trying to get the right extrinsics to perform an alignment of meshes. I create the 4x4 matrix with R and T, when I use this, i end up getting something like:
![top00](https://user-images.githubusercontent.com/5957673/54041930-4302ce00-41c9-11e9-952b-dd330b5dde5d.png)

It seems not to be working with the extrinsics I get from the sfm_data.json. Experimenting a while I applied the inverse of the matrix instead and it seemed to align good for rotation but the translation is off.

![snapfromthefront01](https://user-images.githubusercontent.com/5957673/54042131-b0166380-41c9-11e9-97e0-38b5cf2908a5.png)
![snap from the top00](https://user-images.githubusercontent.com/5957673/54042133-b1e02700-41c9-11e9-8ade-e44e1492bd84.png)

**Comment by pmoulon** [comment]
Can you elaborate from where the R and T are coming from?

Please note that in the `sfm_data.json` poses are stored as `[R|C]`. `C` is the camera center location in the global world coordinates. Perhaps you have a confusion between `t`and `C = -transpose(R) * t`

**Comment by UannaFF** [comment]
Yes, I think I'm confused with this. Because I'm building the extrinsic matrix with the information gotten from the json in the following way:

[Rotation|Center]
0 0 0 1

Because I thought that represented the camera to world matrix, but it's always off. Do I need to use the t instead of the center?

**Comment by pmoulon** [comment]
Closing due to lack of feedback
@UannaFF Feel free to reopen the thread.
I hope you find a fix
