### ISSUE TITLE
lack of LG phones in the regard3d camera database

### ISSUE THREAD

**Issue by cw90000** [openMVG/openMVG#1489]
The database has no LG phones listed in it.
It looks like the phone I need to use is  Sony IMX258

https://www.sony-semicon.co.jp/products_en/IS/sensor1/img/products/ProductBrief_IMX258_20151015.pdf

according to Android Central:

https://www.androidcentral.com/lg-g6-camera-details

It also isn't listed.  It looks like thee database hasn't been updated since 2016  

I tried inserting the line:

LG;LG g6;5.6 but I still can't get Regard3d to triangulate.  

I get the error:  focal length is known for too few pictures

**Comment by pmoulon** [comment]
Hi,

Consider to add `LG;LG g6;5.6` and `LG;g6;5.6`

Else you can use the option `-f X` and using X equal as `1.2 * max(w,h)` of your image.
