### ISSUE TITLE
Microsoft C++ 异常: std::length_error,in graph_builder.hpp,when calculating image matching

### ISSUE THREAD

**Issue by cugcsu** [openMVG/openMVG#1490]
I want to calculate the image matches,but  I get an error when building the graph.
In main_ComputeMatches.cpp
`graph::indexedGraph putativeGraph(set_ViewIds, pairs);`
and in graph_builder.hpp
`template <typename IterableNodes, typename IterablePairs>
  indexedGraph( const IterableNodes & nodes, const IterablePairs & pairs )
  {
    
    node_map_id.reset(new map_NodeMapIndex(g));

    std::set<IndexT> node_set (nodes.begin(), nodes.end());
    //A-- Create a node graph for each element of the set
    std::map<IndexT, GraphT::Node> id_to_node;
    for ( const auto & node_it : node_set)
    {
      const GraphT::Node n = g.addNode();
      ( *node_map_id ) [n] = node_it;
      id_to_node[node_it] = n;
    }

    //B-- Add weighted edges from the pairs object
    for (const auto & pair_it : pairs)
    {
      g.addEdge( id_to_node[pair_it.first], id_to_node[pair_it.second] );
    }
  }`
At the first line of code `node_map_id.reset(new map_NodeMapIndex(g))`
An error occurred

0x00007FF80444A388 处(位于 XXX.exe 中)有未经处理的异常: Microsoft C++ 异常: std::length_error，位于内存位置 0x0000008634EFF6F0 处。

**Comment by pmoulon** [comment]
Did you find a solution to your issue?

**Comment by FishHe** [comment]
I have the same problem.

**Comment by FishHe** [comment]
I met the same problem with VS2019 x64, and the main problem seems related to Lemon.
Change the codes here can solve this:
"lemon\bits\vector_map.h"
```
    VectorMap(const GraphType& graph) {
      Parent::attach(graph.notifier(Item()));
      auto size = Parent::notifier()->maxId() + 1;
      container.resize(size);
    }

    VectorMap(const GraphType& graph, const Value& value) {
      Parent::attach(graph.notifier(Item()));
      auto size = Parent::notifier()->maxId() + 1;
      container.resize(size, value);
    }
```

**Comment by Idawid** [comment]
The patch from @FishHe works. I had the same problem.
