### ISSUE TITLE
Solve.h

### ISSUE THREAD

**Issue by amitgupta7339** [openMVG/openMVG#1492]
getting error Solve function call in robust_estimator_ACRansacKernelAdaptator.h file.How to handle this?

**Comment by pmoulon** [comment]
Can you elaborate and give some context?
- what is failing?

**Comment by amitgupta7339** [comment]
I am running robust_fundamental_guided.cpp file. In this file have a method  ACRansacOut = ACRANSAC(kernel, vec_inliers, 1024, &F,Square(4.0), // Upper bound of authorized threshold true); whose calling file robust_estimator_ACRansacKernelAdaptator.hpp there have one more method **Solve** .In this method passing 3 parameters but in defination of this function Solve.h file only taking 2 parameters.

**Comment by pmoulon** [comment]
Don't know exactly what's going on. Do you have a conflict with an old OpenMVG that is installed on your system?

**Comment by pmoulon** [comment]
Closing due to lack of feedback.
Feel free to re-open
