### ISSUE TITLE
Cannot convert scene with openMVG_main_openMVG2openMVS by using 360 image data

### ISSUE THREAD

**Issue by fjordyo0707** [openMVG/openMVG#1494]
Hi,
I am using Theta ricohS to reconstruct the 3D scene, and I follow the steps from Spherical SfM [here](https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm).
Now I already finished the openMVG part, and want to use openMVS to mesh the point cloud. However, when I execute  openMVG_main_openMVG2openMVS, it shows up this message.
`terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at`
![2019-03-28 20-27-59 的螢幕擷圖](https://user-images.githubusercontent.com/33324251/55157767-36561200-5198-11e9-9eff-a26c8bcd9a99.png)
I cannot figure out the problem. Is it related to the intrinsic matrix since the 360 images don't have ones? 

BTW, is it possible to recontruct the 360 scene using openMVS and openMVG? With openMVS, is there any speical tips or .exe file which need to notice?

**Comment by pmoulon** [comment]
Hi,
Unfortunately, there is no MVS system that can use spherical images.

If you want to build a 3D model from 360 images, you can still extract pinholes images from the 360 images and then proceed with the classical pipeline.
See `main_pano_converter` https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/image_spherical_to_pinholes/main_pano_converter.cpp

See demo here: https://github.com/openMVG/openMVG/issues/621
