### ISSUE TITLE
AKAZE is very slow

### ISSUE THREAD

**Issue by roby23** [openMVG/openMVG#1495]
Is it normal that AKAZE (both FLOAT and MLDB) runs incredibly slow?

Detecting features with SIFT takes 2-3 minutes for all the images, with AKAZE it takes several minutes (like 10) for a single image

**Comment by rperrot** [comment]
Yes, AKAZE is slower than SIFT or SURF. The method to compute the octaves is computationally more expensive to proceed (non linear diffusion scheme). The good point is that you generally get much more features.

**Comment by pmoulon** [comment]
You can consider running ComputeFeatures in multithread mode `-n XCORE`. It will make the process faster than just relying on all the thread for a single image.

**Comment by pmoulon** [comment]
I'm going to close this issue since we gave explanations to your question.
If you want to help to profile AKAZE code and help us to make it faster, feel free to help.
