### ISSUE TITLE
Some doubts about angular error computing

### ISSUE THREAD

**Issue by JimZhou-001** [openMVG/openMVG#1496]
Hello, thank you for providing such a good tool. I'm interested in learning 3D computer vision and reading the code of OpenMVG.

In function **EvaluteToGT** which lies in [openMVG/src/software/SfM/tools_precisionEvaluationToGt.hpp](https://github.com/openMVG/openMVG/blob/835f1e585377a55d4143548fa9181438f5d23889/src/software/SfM/tools_precisionEvaluationToGt.hpp#L138), I find you compute angular error as arccos(trace(R)/3). Here R is the rotation matrix. Source code is like this:
`const double angularErrorDegree = R2D(getRotationMagnitude(R1 * R2T.transpose()));`

But as we know, cos(theta)=(trace(R)-1)/2. Here theta is the rotational angle.

I'd like to know why do you use arccos(trace(R)/3). Looking forward to your reply.

**Comment by pmoulon** [comment]
There are multiple approximations to compute the angle from a rotation matrix.
I'm using one of the multiples that are existing.

Feel free to compare the two representation for various rotation matrices and see how the output varies.

**Comment by JimZhou-001** [comment]
> There are multiple approximations to compute the angle from a rotation matrix.
> I'm using one of the multiples that are existing.
> 
> Feel free to compare the two representation for various rotation matrices and see how the output varies.

Thank you very much for your quick reply. But I didn't find any supports for your method. Would you mind recommending any books or papers aout it? And expecting for baseline error (position error) and angular error, are there any other methods to evaluate SfM results? Thanks.

**Comment by pmoulon** [comment]
You are right, I went perhaps to fast in my implementation.

I'm measuring how much the matrix differ from Identity ([cosine measure between two matrices](https://en.wikipedia.org/wiki/Cosine_similarity)).

Your method is measuring the angle by using the Rodriguez’ formula:

```Calculate the trace, i.e., the sum of the diagonal elements of the rotation matrix: Tr(R)=1+2 cos(theta)```

In order to evaluate SfM accuracy: you need to rely on the parameter you are estimation: position and camera orientation, so I don't see any other ways to assert the precision of the system...

**Comment by woodknight** [comment]
The function used is named "getRotationMagnitude". I think cos(theta)=(trace(R)-1)/2 serves the name better.
