### ISSUE TITLE
gflags-static isues

### ISSUE THREAD

**Issue by BigAloz** [openMVG/openMVG#1498]
Hello,
I have been running openMVG on a Ubuntu linux machine for some time now without any problems. However I have recently come across a compilation problems.

**From CMake**
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Found required Ceres dependency: gflags

**Falls over in compilation**
 74%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_main_GlobalSfM
/usr/bin/ld: cannot find -lgflags-static

I have tried 
1. re-installing everything from scratch (including ceres)
2. sudo apt-get install libgflags-dev

I am at a loss as to what to do next. I assume I need to set a path somewhere

Any advice

Regards,

Alan

**Comment by pmoulon** [comment]
1. Can you check that when you call cmake on OpenMVG repository, it is displayed ceres EXTERNAL?
2. Can you check if when you build ceres it was using gflags?
 - on some distribution when you use glog you must also link gflags. Perhaps the ceres cmake file exported when you are installing ceres does not reflect that.

-> As a temporary solution you can do:
add `gflags` to this line https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/CMakeLists.txt#L33

**Comment by BigAloz** [comment]
Thanks,

I ended upgraded my version of Unbuntu to 19.04 and recompiled everything and is fine now.
I guess something got mixed up on my original OS.

Regards,

Alan
