### ISSUE TITLE
RANSAC()  transform my specified kernel to lineKernel  : (

### ISSUE THREAD

**Issue by dhcpp** [openMVG/openMVG#1501]
Hi, I want to get more 2D-2Dview tracks in main_ComputeMatches(), but I found that the default geometric filter would filters lots of corresponding features. So I have two questions:

1. how to modify openMVG::robust::ACRANSAC in order to compute more corresponding points?

   

2. i use RANSAC instead of ACRANSAC from #1428, and i meet some question:

   First: main_ComputeMatches.cpp; i add function for RANSAC geometric filter.

```

      fundamental::kernel::SevenPointKernel kernel(xI, xJ);
      
      std::vector<uint32_t> vec_inliers;
      Mat3 F;
      size_t inlier_count = 0;

      std::cout << "start : RANSAC()" << std::endl;
      F = RANSAC<fundamental::kernel::SevenPointKernel, ScorerEvaluator<fundamental::kernel::SevenPointKernel> >(
        kernel,
        ScorerEvaluator<fundamental::kernel::SevenPointKernel>( 4.0 ),
        &vec_inliers,
        &inlier_count,
        1e-2
      );

```

​	Second: In roubust_estimator_Ransac.cpp, I extracted data in kernel like:

```
      const Mat
      x1 = ExtractColumns(kernel.x1_, sample),
      x2 = ExtractColumns(kernel.x2_, sample);
```

​	
​	Third: when i compile this project, Error. RANSAC()  transform my specified kernel to lineKernel 

```
Scanning dependencies of target openMVG_test_robust_estimator_Ransac
[ 69%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/robust_estimator_Ransac_test.cpp.o
In file included from /home/dh/Downloads/openMVG/src/openMVG/robust_estimation/robust_estimator_Ransac_test.cpp:11:0:
/home/dh/Downloads/openMVG/src/openMVG/robust_estimation/robust_estimator_Ransac.hpp: In instantiation of ‘typename Kernel::Model openMVG::robust::RANSAC(const Kernel&, const Scorer&, std::vector<unsigned int>*, size_t*, double) [with Kernel = openMVG::robust::LineKernel; Scorer = openMVG::robust::ScorerEvaluator<openMVG::robust::LineKernel>; typename Kernel::Model = Eigen::Matrix<double, 2, 1>; size_t = long unsigned int]’:
/home/dh/Downloads/openMVG/src/openMVG/robust_estimation/robust_estimator_Ransac_test.cpp:33:83:   required from here
/home/dh/Downloads/openMVG/src/openMVG/robust_estimation/robust_estimator_Ransac.hpp:96:26: error: ‘const struct openMVG::robust::LineKernel’ has no member named ‘x1_’
       x1 = ExtractColumns(kernel.x1_, sample),
                          ^
/home/dh/Downloads/openMVG/src/openMVG/robust_estimation/robust_estimator_Ransac.hpp:97:26: error: ‘const struct openMVG::robust::LineKernel’ has no member named ‘x2_’
       x2 = ExtractColumns(kernel.x2_, sample);
                          ^
openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/build.make:62: recipe for target 'openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/robust_estimator_Ransac_test.cpp.o' failed
make[2]: *** [openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/robust_estimator_Ransac_test.cpp.o] Error 1
CMakeFiles/Makefile2:4742: recipe for target 'openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/all' failed
make[1]: *** [openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

Thanks！

**Comment by pmoulon** [comment]
Here some answers:
1. You can just set the default threshold to be larger `ScorerEvaluator<fundamental::kernel::SevenPointKernel>( 4.0 ),` -> `ScorerEvaluator<fundamental::kernel::SevenPointKernel>( 16.0 ),`
2. The error is pretty explicit:
`‘const struct openMVG::robust::LineKernel’ has no member named ‘x2_’`
You are trying to access to a variable that does not exists.

I would like to recommend you to try option 1 first and then try to make your own code.

**Comment by dhcpp** [comment]
> Here some answers:
> 
>     1. You can just set the default threshold to be larger `ScorerEvaluator<fundamental::kernel::SevenPointKernel>( 4.0 ),` -> `ScorerEvaluator<fundamental::kernel::SevenPointKernel>( 16.0 ),`
> 
>     2. The error is pretty explicit:
>        `‘const struct openMVG::robust::LineKernel’ has no member named ‘x2_’`
>        You are trying to access to a variable that does not exists.
> 
> 
> I would like to recommend you to try option 1 first and then try to make your own code.

This is useful. Thanks your solution very much！！

**Comment by pmoulon** [comment]
You are welcome.
