### ISSUE TITLE
GlobalSfM leads to double free or corruption(out)

### ISSUE THREAD

**Issue by WANGLXUE** [openMVG/openMVG#1503]
Problem listed:

 Global translations computation: 
   - Ready to compute 11 global translations.
     from #relative translations: 105
Track stats
------------------
-- Tracks Stats --
 Tracks number: 4182
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
------------------
TrackLength, Occurrence
	3	1533
	4	904
	5	603
	6	428
	7	325
	8	225
	9	91
	10	55
	11	18
Blind triangulation progress:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********************************************************
*
*
#removed tracks (invalid triangulation): 0
  Triangulation took (s): 0
double free or corruption (out)
Aborted (core dumped)

I checked similar problem #341. 
For the result, I have the scene model as a .ply file. But I can not find the .bin file which I needed for my next step use. I have recompiled several times under ubuntu18.04 with gcc and g++7.
Is there any solution I can find to solve this.
Thanks again for your useful library.

**Comment by pmoulon** [comment]
Did you tried to enable and run the unit tests?

**Comment by WANGLXUE** [comment]
Thanks first. I compiled it with test and then run the test. About the sfm part, 4 failures occurs. And they are:

The following tests FAILED:
	 71 - openMVG_test_sfm_data_BA (Child aborted)
	 75 - openMVG_test_global_SfM (Child aborted)
	 76 - openMVG_test_sequential_SfM (Child aborted)
	 77 - openMVG_test_sequential_SfM2 (Child aborted)
Errors while running CTest

But I don't know the cause. Is it because of the dependency, g++ version or ubuntu version.
I am using ubuntu18.04 with g++ gcc 7. Actually there are several warnings about osi_clp dependencies.

**Comment by WANGLXUE** [comment]
It is an error like a UFO.
I passed all the tests in another note PC.  I am sure that I do the same steps just as you suggested.
And I tried the sfm pipline. It works well now.
Thanks for your kindly help.

**Comment by pmoulon** [comment]
Glad to hear you don't have the issue on another PC.
Happy testing and reconstructing!!
