### ISSUE TITLE
[SfM/export] Spherical sfm_data to Cubic sfm_data for MVS (experimental)

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1505]
Add a binary that export a sfm_data with spherical images to a corresponding sfm_data with cubic images.

Goal:

- Allow the possibility to launch a MVS tool on the Spherical SfM scene results.

Note: This is an experimental feature, looking for the help of the community to enhance the WIP prototype and add geometry (landmark projection).

**Comment by skinkie** [comment]
@pmoulon is this the reason that I am receiving the stuff below on the export of spherical images to openmvs?

```
openMVG_main_openMVG2openMVS -i reconstruction/sfm_data.bin -d openmvs -o openmvs/Scene.mvs

- PROCESS VIEWS -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

And no reconstruction options after exporting to mve?
```
openMVG_main_openMVG2MVE2 -i reconstruction/sfm_data.bin -o mve
Note:  this program writes output in MVE file format.
Creating directory:  mve/MVE
Writing bundle (24 cameras, 25808 features): to synth_0.out...
Exporting views...
Creating directory:  mve/MVE/views

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

dmrecon -s2 mve/MVE/
MVE Depth Map Reconstruction (built on Apr 16 2019, 00:02:32)
Initializing scene with 24 views...
Initialized 24 views (max ID is 23), took 2ms.
Reading Photosynther file (24 cameras, 25808 features)...
Reconstructing all views...

Reconstructing mve/MVE/

  ........................

Reconstruction took 0ms.
Saving views back to disc...
Saving views to MVE files... done.
```

**Comment by skinkie** [comment]
As a user I would expect the following from this tool. Spherical images embed contextual information in compare to individual images that have no undergone calibrated stitching. The existing pipeline supports the recovery of a good structure. An example is below available. This image is constructed from 24 pano's following each other passing by a bus stop.

![busstop](https://user-images.githubusercontent.com/502394/56286755-cdb8e000-611a-11e9-9395-7c84432d8351.png)

Using this output in other tools is problematic. For example openMVG_main_ComputeStructureFromKnownPoses and openMVG_main_openMVG2openMVS. As user I would like use these tools, either by supporting the images natively. Or able to transfer the context found in the reconstructed sfm_data.bin towards a pinhole based file.

**Comment by pmoulon** [comment]
Thank you for your feedback. Appreciated.

Please note that the `openMVGSpherical2Cubic` binary is an experiment, it means that this is a WIP binary. We are working on adding more content to the export in order to support various pipeline later (multithread cubic export and feature link between the frames is coming).

Regarding openMVG_main_ComputeStructureFromKnownPoses:
You can still export the Cubic scene and then: -> computeFeatures -> and run:
- ComputeStructureFromKnownPoses (using the features you computed on the cubic images)
- or ComputeMatches and ComputeStructureFromKnownPoses (to use the matching)

**Comment by skinkie** [comment]
@pmoulon I understand it an experiment. But I think it is good that developers is general get use cases which have realistic end goals, then an experiment is more appreciated by the community. The problem I had with cubic scene and compute features was that much less features were found in compare to the spherical images. Is this what I should expect?

**Comment by pmoulon** [comment]
Sharing WIP features is also a good way to test if the community embrace or not the initiative and if the community is ready to help and provide constructive feedback (as we do now).
- OpenMVG is always transparent about features, we create issues, we push WIP code in a branch and give a heads-up in the issue when the feature is ready for test. OpenSource is build on interaction, so at some stage you have WIP feature that are improving in time (free time of the community).

> I had with cubic scene and compute features was that much less features were found in compare to the spherical images. Is this what I should expect?

- It could be because the export is done as a lower resolution, or because all the images are not registered. Using the spherical camera model give a strong prior for triangulation, when you have multiple images the link is weak for triangulation.

**Comment by skinkie** [comment]
Is it technically possible project the entire scene with features into a cubic presentation? As a form of multiple 'undistorted images'? Even if this is outside of the scope of the current experiment.

**Comment by pmoulon** [comment]
Yes, this is possible.
We have 3Dlandmark and camera representation, so you can project the 3D point on the new camera representation (the cubic pinhole)...
Actually, the next push for this demo will have the reprojection, but not yet the feature saved on disk.
But it should be trivial to add.

**Comment by fjordyo0707** [comment]
Greetings, @pmoulon 
I am facing some similar problems, I have used Theta Ricoh360 to generate points cloud, and hope I can reproject the points to one camera pose in order to get a sparse depth map of a panorama image.

My thought is projecting the point cloud on a sphere and warping it to an equi-panorama.  But I am not sure the specific steps what I need to do. Could you give me some advice or guildeline?

**Comment by pmoulon** [comment]
@fjordyo0707, Sure.
You need to create a Spherical camera at the location of your choice and then use the Project function.
```
const Vec2 x = spherical_camera.project(pose(X));
//Compute the depth X - pose.center() and then store it at x location in your float buffer if the point is closer than the previous one stored.
```

**Comment by tdsuper** [comment]
Hi @pmoulon, has this feature been finished or tested?

**Comment by pmoulon** [comment]
@tdsuper Stay tuned, this feature is WIP. We will post some screenshot and more information soon.
Please keep track of the update in the corresponding branch: https://github.com/openMVG/openMVG/tree/develop_spherical_to_cubic

**Comment by tdsuper** [comment]
Hi @pmoulon , do you have some timeline? 

Currently, I can estimate the parameters for spherical images using spherical SfM given [here](https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm). However, after I transformed the spherical SfM data to cubic format and exported the parameters to COLMAP, colmap would ignore some images as they have no source images.  

I have also tried OpenMVS, it says "empty initial point-cloud". 

Finally, I turned to PMVS. It also can not give any results. Then I changed useVisData in options file in PMVS directory to 0, it can give a dense reconstruction. But the result is not very good. 

Is it because this feature is WIP? Or are there any problems in my other steps?

**Comment by pmoulon** [comment]
The actual branch does not export the structure (3D points and image reprojection), that's why PMVS and OpenMVS told you that you don't have any point cloud.
There is a PR working on this point that you can check https://github.com/openMVG/openMVG/pull/1509

I'm in the process of reviewing it and add multithread export of the cubic face. So, please just let us some time to finish to implement the feature and we will be happy if you can help us testing it to fix bug if there is any.

**Comment by tdsuper** [comment]
I will be happy to help testing this feature. 

Actually, I have rewritten [Bundler](http://www.cs.cornell.edu/~snavely/bundler/) and used [PMVS](https://www.di.ens.fr/pmvs/) to reconstruct scene from a collection of spherical images. But as you know, these two systems are released a few years ago. I want to try some state-of-the-art methods. Then I find OpenMVG and COLMAP. I expect the combination of OpenMVG and COLMAP would give much better reconstruction results. Thanks!

**Comment by pmoulon** [comment]
Hey team, I uploaded some dataset to play with [here](https://github.com/openMVG/Image_datasets/tree/master/360_dataset)

You will find 2 datasets and the instructions to export the scene to a compatible format for PMVS/OpenMVS...

@skinkie @tdsuper @fjordyo0707 Feel free to test and provide feedback ;-) in order to check if there is any remaining bug to fix.

360_Flat demo:
![Flat](https://github.com/openMVG/Image_datasets/raw/master/360_dataset/360_Flat/images/R0010217.JPG)
<img width="764" alt="Screen Shot 2019-05-09 at 9 10 16 AM" src="https://user-images.githubusercontent.com/3235050/57473902-c41c2700-7245-11e9-9f1f-c490065d1caf.png">

**Comment by tdsuper** [comment]
Hi @pmoulon , thanks for the update of the code and the sharing of the dataset. I have not tested your steps and don't know whether the picture shows the output of SfM or MVS. Using the dataset, I have run my own solution mentioned [here](https://github.com/openMVG/openMVG/issues/1505#issuecomment-490316635) and get the following result.

![image](https://user-images.githubusercontent.com/213596/57500340-a74f2480-7315-11e9-8127-8c812a966dce.png)

My result is better in completeness, but also has more noises like the corridor. I want to improve my reconstruction result and would like to make contributions to the community.

**Comment by pmoulon** [comment]
I shared the output of the MVS step. Note the fact that I did not played with the parameter of the MVS step and so I could perhaps have a more dense point cloud by tweaking them.

If you want make a contribution to the community feel free to help to improve either OpenMVG or PMVS (https://github.com/pmoulon/CMVS-PMVS)

**Comment by fjordyo0707** [comment]
Hi @pmoulon ,
Thanks for finishing this feature.
I have try on my data with 1 [indoor](https://www.dropbox.com/s/gl3p0ouz6qkjog0/MyHome.zip?dl=0) (24 images) and 1 [outdoor](https://www.dropbox.com/s/zwyi9havytm6ive/CSIE.zip?dl=0) (32 images).
I followed your command to produce. The outputs seem not as well as the data you provide.
The objects aren't complete. Here are the screenshot of the .ply file.  
![myhome](https://user-images.githubusercontent.com/33324251/57780506-f6a0b500-775a-11e9-8574-bd8073e1387d.png)
![Screenshot_20190515_213253](https://user-images.githubusercontent.com/33324251/57780511-fa343c00-775a-11e9-8a32-fab64c72b84f.png)

I hope I can construct the better quality of scene.
Do you have any suggestion?

**Comment by pmoulon** [comment]
@fjordyo0707 I think it is due to the visibility. We are exporting the visibility between the cubic faces only if there is a visible 3D points between images.
Sphere/panoramic images see all around so they can share more visibility than cubic faces.

Can you try to run openMVG2PMVS and then run PMVS without visibility (vis 0)?

Thank you for sharing your test data (appreciated).

**Comment by li9uan** [comment]
I think if we follow the cubic map road, this is the right logic. The ultimate solution would be performing dense stereo directly on the panorama images.

**Comment by pmoulon** [comment]
@fjordyo0707  I obtain similar results as you with OpenMVS.
Here the overlay of the SfM point cloud and the Dense point cloud from OpenMVS
![snapshot_images200](https://user-images.githubusercontent.com/3235050/57826364-d6bbc200-7757-11e9-9444-d0ff39af85ab.png)
![snapshot_images300](https://user-images.githubusercontent.com/3235050/57826365-d6bbc200-7757-11e9-937f-f20f1f9edc01.png)

Observations:
- dense point cloud is generated only from surface that are close enough to the camera
- I did not got the time yet to try to use PMVS

**Comment by fjordyo0707** [comment]
@pmoulon Thanks for the testing! I will find some time to try PMVS. 
I have successfully projected the point cloud to the sphere. Currently, I am tracing your code and gonna project it to the cube. Hope this feature can finish as soon as possible.

**Comment by pmoulon** [comment]
[] Merging the branch develop_spherical_to_cubic to develop
