### ISSUE TITLE
sensor_width_camera_database.txt missing ，the camera internal parameters use the default settings

### ISSUE THREAD

**Issue by zyxrrr** [openMVG/openMVG#1512]
Hello!
If sensor_width_camera_database.txt missing , the camera internal parameters use default settings, such as image width or height, maybe better!
Can you help increase this feature?
Thank You!

**Comment by pmoulon** [comment]
If there is not valid information for the camera, we cannot invent it.
By default, the cameras that do not have parameter will be calibrated by using a 6 point solver and the BA will help refine the camera intrinsic parameters.

Note that if you assume that the camera is having a default Field of View and start from there as an initial guess. You can set `-f 1.2 * max(w,h)` in InitImageListing if you all the images are from the same camera.

Or feel free to update the missing information in the dataset that suits your camera.

**Comment by zyxrrr** [comment]
OK!
Thank You!
