### ISSUE TITLE
Commerical Use as Third party

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#1514]
Hi,
Is using openMVG as third party can be disclosed or should be open to the public

**Comment by rjanvier** [comment]
Hi, from what I understand, you have to disclose any change you made to the library itself but not things you build upon the library. Please refer to the MPL2 license to know your right and obligations. Please also be aware that if you build something upon openmvg with eigen and without EIGEN_MPL2_ONLY defined, LGPL will apply on the whole library.

**Comment by pmoulon** [comment]
See here: https://choosealicense.com/licenses/mpl-2.0/
You have to cite you are using the library and cite the authors (can be one file).
So if you use OpenMVG as it is, you just need a citation.
If you modify OpenMVG you have to share back to the community (bug fix, new feature).

- As @rjanvier said, you have to compile OpenMVG with the `EIGEN_MPL2_ONLY ` flag
- Be aware that SIFT is under a patent, but OpenMVG provides feature alternative you can use, or you can use your own feature detector.

**Comment by RamadanAhmed** [comment]
Thank you both @rjanvier and @pmoulon for illustration, it helps so much
