### ISSUE TITLE
Unbuntu18.0.4 the problem when make

### ISSUE THREAD

**Issue by neverwalkingalone** [openMVG/openMVG#1516]
-- Install configuration: "RELEASE"
-- Installing: /usr/local/include/openMVG_dependencies
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot make directory
  "/usr/local/include/openMVG_dependencies": Permission denied

Makefile:117: recipe for target 'install' failed
make: *** [install] Error 1

how can i solve this problem

**Comment by RamadanAhmed** [comment]
sudo make install or change the directory of installation

**Comment by src-r-r** [comment]
Do you think it would be advisable to open a PR to install under `${CMAKE_INSTALL_PREFIX}`?

https://github.com/openMVG/openMVG/blob/7fd19fc22419a35481d39d2946f77e1dc00df37c/src/CMakeLists.txt#L219 makes me nervous. 😅 

Doesn't seem very flexible, either.

**Comment by pmoulon** [comment]
@src-r-r if you specify your path in cmake command line it will be valid see here https://github.com/openMVG/openMVG/blob/develop/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake
