### ISSUE TITLE
constexpr is not known to CXX compiler

### ISSUE THREAD

**Issue by tdsuper** [openMVG/openMVG#1517]
Currently, I am trying to build OpenMVG on win7 64bit with CMake 3.2.3 and Visual Studio Community 2015. After specifying the source and build directory, the configuration is successful. But when I want to generate the solution files, CMake reports errors "the compiler feature cxx_constexpr is not known to CXX compiler". What should I do to deal with this problem? Thanks!

**Comment by tdsuper** [comment]
Everything is ok after I have updated CMake to version 3.14.3. :)

**Comment by pmoulon** [comment]
Great to hear that updating CMake helped. :tada:
