### ISSUE TITLE
The database doesn't include NIKON D750

### ISSUE THREAD

**Issue by neverwalkingalone** [openMVG/openMVG#1522]
what should i do to add the camera model and sensor width in the database

**Comment by pmoulon** [comment]
You must add your camera in the database here https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt#L1601

**Comment by pmoulon** [comment]
Adding `Nikon Coolpix D750;35.9` should do the trick
