### ISSUE TITLE
Help with big baseline dataset

### ISSUE THREAD

**Issue by UannaFF** [openMVG/openMVG#1526]
Hello, i'm trying to do reconstruction of a scene where a camera moves horizontally and images have big baseline between each other, in the end, the connectivity is represented like this:

![image](https://user-images.githubusercontent.com/5957673/58026469-e0a64200-7b16-11e9-8e59-831cfb7e9bac.png)

Which means that one image has visibility to the previous image and next image, overlap is around 30% for each side.

I'm trying to do sequential reconstruction but I only get the position from 2 views(first two). I guess the problem is, I don't have information in common from the initialized map and the next image being added, given that the matches with the middle image are not represented as 3D points. Is there a way to achieve reconstruction in this case?

My results are:

Performing only openMVG
1. Intrinsics analysis
 You called : 
/home/anigomez/work/openMVG/build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /data/work/data/qopius/carrefour/1
--sensorWidthDatabase /home/anigomez/work/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /data/work/output/qopius/carrefour/1/matches
--focal 3936
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*******Width and height: 2464 - 3280
*********
focal: 3936

SfMInit_ImageListing report:
listed #File(s): 7
usable #File(s) listed in sfm_data: 7
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
 You called : 
/home/anigomez/work/openMVG/build/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /data/work/output/qopius/carrefour/1/matches/sfm_data.json
--outdir /data/work/output/qopius/carrefour/1/matches
--describerMethod AKAZE_FLOAT
--upright 0
--describerPreset HIGH
--force 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 62
3. Compute matches
 You called : 
/home/anigomez/work/openMVG/build/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /data/work/output/qopius/carrefour/1/matches/sfm_data.json
--out_dir /data/work/output/qopius/carrefour/1/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching 1
--pair_list 
--nearest_matching_method ANNL2
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: sequence pairwise matching
Using ANN_L2 matcher

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 18

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 9921
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 
------------------
TrackLength, Occurrence
	2	9884
	3	34
	4	3

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
A-Contrario initial pair residual: 97.7846

Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 1329
 #residuals: 5316
 Initial RMSE: 1.39988
 Final RMSE: 1.11356
 Time (s): 0.164578

=========================
 MSE Residual InitialPair Inlier:

SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	1264
	-- Residual min:	2.02188e-06
	-- Residual median:	0.0674603
	-- Residual max:	 18.8168
	-- Residual mean:	 0.874787
=========================

-------------------------------
-- Robust Resection of view: 2
  nfa=-3.03786 inliers=4/5 precisionNormalized=1.70414e-06 precision=5.13816 (iter=1 ,sample=2,1,4,)
  nfa=-3.53899 inliers=4/5 precisionNormalized=4.55886e-07 precision=2.65756 (iter=2 ,sample=3,4,1,)
  nfa=-3.53899 inliers=4/5 precisionNormalized=4.55886e-07 precision=2.65756 (iter=14 ,sample=1,4,3,)
  nfa=-3.53899 inliers=4/5 precisionNormalized=4.55886e-07 precision=2.65756 (iter=21 ,sample=4,1,3,)

-------------------------------
-- Robust Resection 
-- Resection status: 0
-- #Points used for Resection: 5
-- #Points validated by robust Resection: 4
-- Threshold: 2.65756
-------------------------------

-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 2 from 7 input images.
-- #Tracks, #3D points: 1220
-------------------------------

SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	1220
	-- Residual min:	2.02188e-06
	-- Residual median:	0.0451552
	-- Residual max:	 3.99626
	-- Residual mean:	 0.800576

Histogram of residuals:
0	|	2675
0.4	|	343
0.799	|	337
1.2	|	401
1.6	|	343
2	|	274
2.4	|	230
2.8	|	128
3.2	|	85
3.6	|	63
4

 Total Ac-Sfm took (s): 0
...Generating SfM_Report.html
...Export SfM_Data to disk.
4. Do Sequential/Incremental reconstruction
Using frame origin: 0.00484014 0.00229646  0.0356027
...Export SfM_Data to disk.
5. Colorize Structure

Compute scene structure color
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 7
 #poses: 2
 #intrinsics: 1
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

Structure estimation took (s): 0.

#landmark found: 0
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 7
 #poses: 2
 #intrinsics: 1
 #tracks: 0

Compute scene structure color
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

- PROCESS VIEWS -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

- UNDISTORT IMAGES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
 #platforms: 1
  platform ( 0 ) #cameras: 1
  7 images (2 calibrated)
  1220 Landmarks

I'm putting the zip file available here with the first 5 images in case you have some time to help me, thank you in advance. 
[dataset.zip](https://github.com/openMVG/openMVG/files/3198198/dataset.zip)

**Comment by pmoulon** [comment]
Having a graph based on triplets is better to perform SfM, since you can propagate the scale factor of the reconstruction in a better way than having a single link graph.

Did you try to start from different seed (image index) just to try to see if one is providing a better reconstruction (more connectivity)? -> option -a -b on SfMIncremental

**Comment by pmoulon** [comment]
Also I noticed that your images would have a better fit if you use the Homography constraint at matching time (mostly planar object).
here you are in a case where you have few overlap, compute a homography and compute the motion between camera from the homography decomposition.
