### ISSUE TITLE
Use openMVG as a thirdparty library with Makefile 

### ISSUE THREAD

**Issue by BrennoCaldato** [openMVG/openMVG#1527]
Is there an example of how to link openMVG as a third-party library without cmake, using only Makefile? What libraries should I include?

Thanks

**Comment by pmoulon** [comment]
If the lib is installed it is easy, you look for the module you need and you link the corresponding one.
`openMVG_X`. i.e: image -> `openMVG_image`
I would advise you to use cmake, it makes things simpler.

**Comment by BrennoCaldato** [comment]
Thanks, it worked partially! 
I'm trying to port the image_localizer When I include `<openMVG/sfm/sfm.hpp>` with the `-lopenMVG_sfm` library it gives me the following error 

```
In file included from /usr/local/include/openMVG/sfm/sfm.hpp:40:0,
                 from tests/../image_localizer.h:8,
                 from tests/test_image_localizer.cpp:2:
/usr/local/include/openMVG/sfm/pipelines/sfm_features_provider.hpp:21:53: fatal error: third_party/progress/progress_display.hpp: No such file or directory
compilation terminated.
../Makefile.common:156: recipe for target 'tests/test_image_localizer.o' failed
make: *** [tests/test_image_localizer.o] Error 1
```

**Comment by pmoulon** [comment]
It is because you need to add multiple include folder.
You should have a include/openMVG/openMVG-dependencies ... to add (where the progress_display.hpp is installed)
CMake is doing the job for you (importing targets and include directories).

**Comment by BrennoCaldato** [comment]
Solved by adding 
`FLAGS+=-I/usr/local/include/openMVG/
FLAGS+=-I/usr/local/include/openMVG_dependencies/
FLAGS+=-I/usr/local/include/openMVG_dependencies/cereal/include/`

Thanks
