### ISSUE TITLE
Questions about feature point extraction

### ISSUE THREAD

**Issue by neverwalkingalone** [openMVG/openMVG#1530]
How to get how many feature points are extracted from each picture

**Comment by neverwalkingalone** [comment]
I want to know the number of feature points extracted per image.what should i do

**Comment by pmoulon** [comment]
You can display it by modifying the binary called exportKeypoints
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/export/main_exportKeypoints.cpp

Using the feature provider will load all the features related to your scene and then you can iterate
