### ISSUE TITLE
Update documentation for vcpkg

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#1531]
Hi,
There is now a pre-built package of openmvg on vcpkg
`vcpkg install openmvg[core,openmp,opencv]`
so I think you should point it out in documentation for people use the library as 3rd party(will ease the process)

**Comment by pmoulon** [comment]
@cenit @saedrna @Rastaban Thank you for your contribution.
Appreciated!
We will update the doc on our repo.
OpenMVG will be even easier to use!

**Comment by cenit** [comment]
@pmoulon you're welcome :)
also for us it would be wonderful if some patches could be integrated upstream, in case you were interested!

**Comment by pmoulon** [comment]
Feel free to push PR to the repo.

**Comment by pmoulon** [comment]
Update the doc about using the native port or use a custom build.
Thx you.

**Comment by RamadanAhmed** [comment]
btw I think OpenMVGConfig.cmake.in should be modified to handle file structure in vcpkg to be able to use openMVG as third party 
problem happen in this [line](https://github.com/openMVG/openMVG/blob/835f1e585377a55d4143548fa9181438f5d23889/src/cmakeFindModules/OpenMVGConfig.cmake.in#L63) it should be like this
`get_filename_component(CURRENT_ROOT_INSTALL_DIR
  ${CMAKE_MODULE_PATH}/../../ ABSOLUTE)`
I have edited the port file to be able to use it
Also, if possible to make head_ref in vcpkg port to point to develop because there is many useful updates happen in develop and we don't want to miss it out

**Comment by cenit** [comment]
@RamadanAhmed to point to head in vcpkg it's enough to pass --head when installing port. Apart from that, it is explicitly avoided to point to a moving target, since it makes impossible to fix a release
