### ISSUE TITLE
when I use openMVG_main_ComputeStructureFromKnownPoses ,something wrong had happened

### ISSUE THREAD

**Issue by neverwalkingalone** [openMVG/openMVG#1532]
openMVG_main_ComputeStructureFromKnownPoses -i 桌面/MVGC/sfm_data.json -m 桌面/MVGC/sfm_data.json -o 桌面/MVGC/robustiFitting.json
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: 桌面/Church/P1180147.JPG
*Invalid regions files for the view: 桌面/Church/P1180144.JPG
*Invalid regions files for the view: 桌面/Church/P1180143.JPG
Invalid regions files for the view: 桌面/Church/P1180142.JPG
Invalid regions files for the view: 桌面/Church/P1180145.JPG
*Invalid regions files for the view: 桌面/Church/P1180141.JPG
Invalid regions files for the view: 桌面/Church/P1180146.JPG
*Invalid regions files for the view: 桌面/Church/P1180148.JPG

Invalid regions.
what should i do to solve it? thx

**Comment by pmoulon** [comment]
-m is not pointing to a folder.
Try with `m 桌面/MVGC`
