### ISSUE TITLE
Calculating Roll Pitch Yaw angles with computer vision

### ISSUE THREAD

**Issue by AlejandroAlv96** [openMVG/openMVG#1535]
I'm supposed to calculate the Roll, Pitch, Yaw camera movement angles using computer vision and opencv libraries. I need to do it for my final bachelor's project, so I you have an idea, please let me know. Thank you all!!

**Comment by nguyengiang41** [comment]
I think that your question is not very clear to respond. It depends on many things...

What is your source data ? What data exactly you have to compute Roll Pitch Yaw ? 
How you define your Roll Pitch Yaw ? Could you describe your system?

**Comment by AlejandroAlv96** [comment]
> I think that your question is not very clear to respond. It depends on many things...
> 
> What is your source data ? What data exactly you have to compute Roll Pitch Yaw ?
> How you define your Roll Pitch Yaw ? Could you describe your system?

Oh, sorry for my bad explanation. I'll explain better my project:
I need to know the rotation movement of the quadcopter on the x, y, z axes, that is, the roll pitch and yaw of the quadcopter. I need to do it using computer vision algorithms, that is, treat the camera images and obtain the rotation movements in the three axes. However I have no idea how to do it through the opencv.
To verify that I calculate well the data that I obtain, I have incorporated an IMU to the camera that gives directly the angles of roll pitch and yaw that rotates the quadcopter.
As for the data I receive, all the information I have supposedly obtained from the images of the camera.
Please give me any ideas you may have. It will surely be useful for me.
Greetings and thank you.

**Comment by nguyengiang41** [comment]
> how to do it through the opencv
Hmmm, I think we are in the openMVG project here.

>  I have incorporated an IMU to the camera that gives directly the angles of roll pitch and yaw that rotates the quadcopter.
I don't know so much about IMU but I think that you need a frame conversion (changes of the coordinate system) to compare the quadcopter rotation given by Computer Vision algorithm with the one given by your IMU. If you compute your quadcopter's rotation based on images, you will obtain rotation in the vision reference frame, which is different with rotation given by IMU in navigation frame ... So I think you need firstly a conversion. 

> all the information I have supposedly obtained from the images of the camera...
Let me resume your problem: you need to compute a quadcopter 's body rotation by a video/image flux given by a camera attached to it. 
If you need a real-time application: go with Visual Odometry.
If you don't care about the processing time : go with SfM/Photogrammetry. 
All of these things could be done by openMVG. 
You have an implemented SfM pipeline that you could use directly to test on your quadcopter image's flux. (have a look at [OpenMVG Documentation SfM Pipeline](https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/)). For a quick test, just gives all of your images and you could obtain the rotation matrix for each image as a result.
