### ISSUE TITLE
problem with control points registration ui

### ISSUE THREAD

**Issue by ecvz** [openMVG/openMVG#1536]
I'm trying to use the ui for control points registration which is working but crashes when I try to perform the registration. 

Here is the error:
Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = 1; bool InnerPanel = true; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.

**Comment by pmoulon** [comment]
Thx for the feedback.

Can you try the develop branch (I think we made a fix for it)?

**Comment by ecvz** [comment]
Thank you for the quick reply.
I'm doing some tests on different SfM pipelines for a research paper comparing the photogrammetric approach to the computer vision one. As openMVG is one of the few in its genre to feature a control points registration it's interesting to test it against photogrammetric softwares.
Unfortunately the develop branch seems to produce the same error:
ui_openMVG_control_points_registration: /usr/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = 1; bool InnerPanel = true; Eigen::Index = long int]: Assertion "(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))" failed.
Killed
Also tried to debug the core dump, if can be useful this is the stack:
![Screenshot_20190601_022935](https://user-images.githubusercontent.com/51246648/58742004-d2162f80-8420-11e9-9ba4-c033ad431171.png)
Any thoughts?

**Comment by rjanvier** [comment]
it's indeed a bug. I've found the culprit here: 
https://github.com/openMVG/openMVG/blob/835f1e585377a55d4143548fa9181438f5d23889/src/software/ui/SfM/control_points_registration/MainWindow.cpp#L286-L288

If your GCP numbering is not continuous or even some GCP fail to triangulate it will trigger the error here
https://github.com/openMVG/openMVG/blob/835f1e585377a55d4143548fa9181438f5d23889/src/software/ui/SfM/control_points_registration/MainWindow.cpp#L308-L313. We need to reindex the data to take into account "bad path". @pmoulon could I propose a fix?

**Comment by pmoulon** [comment]
@rjanvier Sure, we should iterate over and not use the index ;-)

**Comment by ecvz** [comment]
Following the hint from @rjanvier  I renamed all the points accordingly:
![Screenshot_20190607_024050](https://user-images.githubusercontent.com/51246648/59075019-b3a3ae80-88ce-11e9-951b-6748f26e46ff.png)
They come from an already processed dataset and the coordinates are correct, I also double checked the images coordinates.
and this is what I got after the registration:
ui_openMVG_control_points_registration 
QDragManager::drag in possibly invalid state
Current viewed image:  "DJI_0188.JPG"
.....
Current viewed image:  "DJI_0438 2.JPG"
kf5.kio.widgets: No node found for item that was just removed: QUrl("file:///media/erik/DATI/lavori/CARLETON/projects/Bagan/processing/Loka/photogrammetric_reconstruction/OpenMVG/AERIAL25+30_pinhole/SIFT/ANN/AC/00000015_Resection.ply")
ui_openMVG_control_points_registration: /usr/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = 1; bool InnerPanel = true; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
Annullato (core dump creato)

Is the problem with the qt widgets relevant?

**Comment by pmoulon** [comment]
If you can share some data for debuging it could be nice.
Can you save your data and share them to us (we just need your *.feat, your sfm_data.bin and your updated control_points)?

**Comment by rjanvier** [comment]
Maybe a point failed to triangulate it can trigger the same error.

**Comment by rjanvier** [comment]
@ecvz could you try with this branch?
https://github.com/rjanvier/openMVG/tree/develop_fix_1536

**Comment by ecvz** [comment]
I tried the @rjanvier fix and it seems to work fine. Many thanks.
I'm uploaded the data for debugging.
I added @rjanvier and @pmoulon as collaborators now, but I can add other users if necessary.
Unfortunately this it's closed project and I don't have the permission for sharing the data pubblicly.
I have other dataset I can share pubblicly if needed, but they are unprocessed now. I'm very happy to process them and create SfM data pubblicly available if it can be useful for debugging and testing the software.

Thank you very much for the help.

**Comment by rjanvier** [comment]
Thanks. I'm glad to help.
I though about it and my "numbering trick" didn't work https://github.com/openMVG/openMVG/issues/1536#issuecomment-499721821 because you start the numbering at 1 and not 0 so this was definitely the issue.
please let us know if you have some other problems.

**Comment by ecvz** [comment]
I tried to register the same project with the non sequential numbering I used at the very beginning (1202, 1203, 2012, 2013, 2014, 3307) and is working too.
Thanks to your fix I'm able to complete the test. Should I close the issue?

**Comment by rjanvier** [comment]
Thanks for the feedback. the fix is not merged yet. Don’t worry, we will close this once merged.

**Comment by pmoulon** [comment]
Thank you for the fix and the deep testing you have done. I need to review and merge the PR and then will close the issue.
