### ISSUE TITLE
stop after initial match pair selection when using the incremental sfm for UAV images

### ISSUE THREAD

**Issue by json87** [openMVG/openMVG#1537]
Hi, 
  thanks for providing the toolkit for sfm orientation. Recently, I used it to reconstruct a UAV dataset and found that it stoped after the selection of the initial image pair, as shown below.

![TIM截图20190602083510](https://user-images.githubusercontent.com/17582213/58755215-76779f00-8511-11e9-9146-13fd987a0ecc.png)

what should I do to resume camera poses and 3D points.
 Thanks!

**Comment by pmoulon** [comment]
It seems that the initial pair was rejected because the system didn't trust it (too much imprecision).

Can you try to run the Global pipeline on your dataset?
