### ISSUE TITLE
Resection not working properly

### ISSUE THREAD

**Issue by tkhan1994** [openMVG/openMVG#1538]
Hi,

I'm trying to build a 3d model of my campus using the incremental SfM pipeline. For some reason, after a certain resection, I lose the dense point cloud (not entirely) and it is also not present in the final cloud_and_poses.ply. Any clue what I could be doing wrong. I'm attaching the images for reference,

<img width="715" alt="Screen Shot 2019-06-05 at 4 30 28 AM" src="https://user-images.githubusercontent.com/34044382/58953226-aeb5f200-874a-11e9-96a5-c6cfe47bf90e.png">

<img width="723" alt="Screen Shot 2019-06-05 at 4 31 06 AM" src="https://user-images.githubusercontent.com/34044382/58953283-d4db9200-874a-11e9-8f81-b59c8ee721d7.png">

The first image corresponds to 00000103_Resection.ply and the second one is for 00000104_Resection.ply.

Thanks

**Comment by rjanvier** [comment]
Hi, In fact you do not loose it and It works "perfectly" well.
Here, in the "104" poinst cloud the triangulation and BA process (so after the resection) add either some outliers or some tracks (in RED) that are far away from the rest of the scene (in GREEN).
![omvg_far_away](https://user-images.githubusercontent.com/1537100/58953994-35dd8700-8798-11e9-9489-1be61cb425c0.png)

CloudCompare do not adapt the scale according to the density of information but according to your bounding box. Please try either to zoom in the GREEN part or to segment in this part on CloudCompare (and then click on the "1:1" button in the left)  and you'll see something like the 103 point cloud.

**Comment by rjanvier** [comment]
please nots you indeed seem to have an incorrectly oriented camera (between the GREEN zone and the RED zone) So it could be a resection failure that cause badly triangulated tracks. Are you using the master branch or the develop branch? Could you please send us (in txt format) the log of your reconstruction?

**Comment by tkhan1994** [comment]
I'm not sure which branch I'm using can you please elaborate on that a bit more? Also, where can I find the log file, do I have to specify it before running the pipeline? Again I'm sorry for asking these questions, it's my first time using openMVG.

**Comment by tkhan1994** [comment]
I was able to find these html files (in zip format) though.


[reports.zip](https://github.com/openMVG/openMVG/files/3257303/reports.zip)

**Comment by rjanvier** [comment]
1/ For the "branch" issue: how do you get/compile and run openMVG?
2/ Thanks, these files are fine. In a general matter you do not seems to have so much common points between your images. Try to extract more by using the `HIGH` preset within `openMVG_main_ComputeFeatures` e.g `openMVG_main_ComputeFeatures [other needed flags here] -p HIGH `

**Comment by tkhan1994** [comment]
I got it using the following the instructions (listed below):
$ git clone --recursive https://github.com/openMVG/openMVG.git
$ cd openMVG
$ ls
 AUTHORS BUILD  docs  logo  README  src  ...
$ cd ..
$ mkdir openMVG_Build
$ cd openMVG_Build

Then I built it and I run it using the SfM_SequentialPipeline.py file after performing a few modifications. I also wanted to ask if there is any other way to discard a bad camera/image from the dataset? I'll re-run the pipeline again using more features. Thanks a lot for your help.

**Comment by rjanvier** [comment]
in your source directory just run `git checkout develop` then go to your build directory and rebuild/install openMVG. There are a few modifications in the develop branch that could make some differences.
Also, regarding your dataset (regular groups with small baselines, naming) are you using rigidly coupled cameras?

**Comment by tkhan1994** [comment]
I've reinstalled it, regarding the images, they were taken from a drone which was mounted with 2 cameras. One camera was on top (as an eye would see) and the other was on the bottom taking pictures of the floor. So, there isn't much overlap between the two and yes they are rigidly coupled. Take a look at the images below for further clarification.

![set-1_00000000_cam-1](https://user-images.githubusercontent.com/34044382/58963159-871e5400-8761-11e9-87e8-cdb744c57af2.jpg)
![set-1_00000000_cam-2](https://user-images.githubusercontent.com/34044382/58963160-871e5400-8761-11e9-8ef7-2dd72b11f385.jpg)
![set-1_00000001_cam-1](https://user-images.githubusercontent.com/34044382/58963162-871e5400-8761-11e9-8f4c-383bbe5766b7.jpg)
![set-1_00000001_cam-2](https://user-images.githubusercontent.com/34044382/58963163-871e5400-8761-11e9-824a-f662972a426f.jpg)

**Comment by rjanvier** [comment]
In this case you'd rather use this branch https://github.com/openMVG/openMVG/tree/develop_subposes. it could handle rigidly coupled cameras but I guess it's a bit out of sync the develop branch and even the master branch.

**Comment by tkhan1994** [comment]
Works perfect!
Is there any way I can extract the final 3D point coordinates and the camera intrinsics and extrinsics from the results?

**Comment by pmoulon** [comment]
You can by converting the sfm_data.bin file to a JSON or XML file.
For this you can use `openMVG_main_ConvertSfM_DataFormat -i <path>/sfm_data.bin -o <path>/sfm_data.json`
Then you can look at the JSON fields intrinsics, extrinsics and structure (X are the points of the point cloud).

**Comment by tkhan1994** [comment]
Thanks, I have one more question though, is there any way I can evaluate the 3D point cloud without ground truth points? I talked with a professor today and he said that this can be done by checking if planar structures like walls are indeed planar in the final reconstruction. Can you kindly provide insight if you think there are other/better ways of doing this?

**Comment by pmoulon** [comment]
OpenMVG provides a way to register the model to know GCP (Ground Control Points) https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

To check if walls are indeed planar, you can often see from the SfM point cloud if the reconstruction is accurate, or use dense point cloud computation (PMVS, OpenMVS) and see the results.

Looking to  your image https://user-images.githubusercontent.com/34044382/58953226-aeb5f200-874a-11e9-96a5-c6cfe47bf90e.png and your average RMSE (SfM Scene RMSE: 0.594434) with most of the camera with a median RMSE < 0.2 you should have quite a good reconstruction (see the values reported in SfMReconstruction_Report.html)

**Comment by tkhan1994** [comment]
Is there a link where I can find the code of CASCADEHASHINGL2?

**Comment by pmoulon** [comment]
Take a look in src openmvg matching
https://github.com/openMVG/openMVG/tree/master/src/openMVG/matching and lok for cascade hasher and cascade hashing. Do you want close the issue?
