### ISSUE TITLE
Understanding Values in the SfM reconstruction report

### ISSUE THREAD

**Issue by tkhan1994** [openMVG/openMVG#1542]
I can't seem to understand the values in the SfM reconstruction report. Could you please help me with that?

**Comment by tkhan1994** [comment]
I don't specifically understand the terms

Dataset Info
SfM Scene RMSE
Track Length Statistics

**Comment by pmoulon** [comment]
RMSE (Root Mean Square Error)
Track Length Statistics: Explain if points are seen across multiple images.

Looking to the code that generate the report can help https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_report.cpp#L26

More info about tracks: https://hal-enpc.archives-ouvertes.fr/hal-00769267/file/moulon_monasse_poster_CVMP12.pdf
