### ISSUE TITLE
project function not producing correct result

### ISSUE THREAD

**Issue by jiangjiayao** [openMVG/openMVG#1543]
I'm building a process that can automatically generate virtual tour from a set of spherical images. I first ran SfM per [this instruction](https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm), I then find the ground plane height Y_floor, replace Y value in camera centers with Y_floor, use project function to find relative direction between camera centers, then assign hotspots in Krpano. 

The process works fine with some testing datasets, [successful example](https://make.vt360.cn/home/preview?pid=212), but ran into some problem now.

I follow the above process on several indoor spherical images with AKAZE_FLOAT & HIGH settings, the ply model and the camera poses look good, but the hotspots are wrong. Original data [here](https://drive.google.com/open?id=1q-TrQyt_7-h47CJQDXO2cgNTKNvkQiok). Ply model [here](https://drive.google.com/open?id=1-xPB9HyjjInVzCdoDwxBjqeN8t9x4hVj). Final tour [here](https://make.vt360.cn/home/preview?pid=236).

I have no idea what went wrong, can anyone please help? Thanks in advance.

**Comment by pmoulon** [comment]
Thx you for sharing your experiment and asking for feedback.

I would check where your ground plane Y is estimated for your problematic dataset and check if the Y axis is pointing in the same direction as your other testing dataset.

**Comment by jiangjiayao** [comment]
Thanks for the input. @pmoulon  

The Y(height, sorry I'm using MeshLab coordinates) for correct and problematic ones are both pointing at the same direction. 

However, switch X to negative Z and Z to X did the trick. So basically I have to rotate the problematic ply model 90 degree counter clock wise to get the same orientation as the correct ones. 

This might be a silly question but how come the orientation varies, and is there any indicator from openMVG output tells it?

Appreciate any help in advance!

**Comment by YouYue123** [comment]
@jiangjiayao How you manage to extract the ground plane height?

Are you using cloud_and_pose.ply to do it?
