### ISSUE TITLE
Estimating relative pose between two images

### ISSUE THREAD

**Issue by AlejandroAlv96** [openMVG/openMVG#1544]

**Comment by AlejandroAlv96** [comment]
Hi everyone,
I'm doing my final bachelors project and I'm supposed to estimate the relative pose between two different frames taken by one monocular camera. I need to do it with OpenCV. I think I need to calculate the rotation matrix between two images but I don't know how. 
Please could anybody help me?

**Comment by pmoulon** [comment]
Note that here we don't support question related to OpenCV. OpenCV is having is own github.

How to compute a relative pose between two image using OpenMVG is shown here https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_essential/robust_essential.cpp
