### ISSUE TITLE
Can not solve room-inside SfM problem

### ISSUE THREAD

**Issue by WenyinWei** [openMVG/openMVG#1545]
Hello all,

It seems that incremental SfM and SfM2 are not so good at solving inside SfM problem as the following shows. Do you have any suggestion for the reconstruction?

For such desktop snaps like the following, I took 14 photos:
![IMG_20190615_164749](https://user-images.githubusercontent.com/33152225/59551368-fcccc000-8faa-11e9-82ca-79313fb0a653.jpg)
![IMG_20190615_164732](https://user-images.githubusercontent.com/33152225/59551370-022a0a80-8fab-11e9-945d-27d21d7b723a.jpg)

But the result is not so good and even unacceptable.(IncrementalSfM2 is better than SfM1)

![image](https://user-images.githubusercontent.com/33152225/59551329-76b07980-8faa-11e9-8a3a-e25c2b8ffc5b.png)

The points look like at one plane. That's terrible.

The same result happens for the "bird data" from Kalin Kolev and Daniel Cremers, University of Bonn, Germany.

![0016](https://user-images.githubusercontent.com/33152225/59551419-c04d9400-8fab-11e9-9d1c-0bc572de28a8.jpg)

**Comment by WenyinWei** [comment]
I found for most of datasets, the result of incremental SfM will give a point cloud located in the same plane. It is really strange. They are accurately(and wrong accurately) on the same plane. 

The drawback is missing when the dataset is some images around a construction.

**Comment by gaoshuai** [comment]
Hi, Wei, I think you can try Homography matrix filtering for the matching process. Btw, small baselines between views would incur big errors for 3D reconstruction, so images acquisition needed to be careful.

**Comment by WenyinWei** [comment]
Hello gaoshuai, nice to see your reply. I have tried eliminating the image number to increase the baseline and turned ComputeMatches to -g h mode to change its filtering. But all these methods seem to fail. Would you like to have a try? TUM has a famous MultiView Dataset https://vision.in.tum.de/data/datasets/3dreconstruction . Seems that OpenMVG doesn't work well for the dataset.

**Comment by pmoulon** [comment]
As usual, I recommend this path to debug things:
1. check that you provide accurate intrinsics (focal length)
2. check you have nice matches (check adjacency match matrix in the match folder, or matches with exportMatches binary)
3. Those tiny objects (as the bird), does not often have a lot of features.
4. Indoor environments are often featureless (white wall), so it becomes harder to find corresponding points between pair of images.

I think your first dataset should work ok. You can share it if you want.

**Comment by WenyinWei** [comment]
The focal length is 4.2 mm according to my camera parameters. I set it at the Image Listing step by "-f", "4.2". The GeometricAdjacencyMatrix would look like this 
![image](https://user-images.githubusercontent.com/33152225/59566638-55788780-9095-11e9-883f-157adac5e8e5.png).

Yes, the bird seems to be a not so good object and indoor environment maybe really difficult for feature points correspondence-based algorithm. A more accurate algorithm utilizing the point neighborhood info is needed.

**Comment by pmoulon** [comment]
Got it, you need to provide the focal length in pixel with the `-f` option
See how to do that -> https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata
Else you can approximate the value by doing Fpixel = 1.3 * max(w,h)
It will approximate the focal length for square pixel and a fov of 90 degree.

**Comment by WenyinWei** [comment]
Thanks for @pmoulon , the reconstruction point cloud looks well now. The focal length before is too low to make all points located near the original point.

![image](https://user-images.githubusercontent.com/33152225/59567291-506c0600-909e-11e9-9d6a-4aac5d638c6b.png)

**Comment by pmoulon** [comment]
Yay!! Keep in mind the 1.2.3 4 rules to debug your reconstruction. Hapoy to see that the point cloud and camera location looks good now
