### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ghost** [openMVG/openMVG#1546]
Dear All: is there any way to be installed openMVG / openMVS on anaconda like opencv? Best, Ghasem

**Comment by WenyinWei** [comment]
No, I have not found openMVG python library. It only has C++ version now.

**Comment by pmoulon** [comment]
OpenMVG is quite easly to install:
https://github.com/openMVG/openMVG/blob/develop/BUILD.md#checking-out-the-project-and-build-it
https://github.com/openMVG/openMVG/blob/master/BUILD.md

As @WenyinWei said, OpenMVG is developed in C++. We have some python script to show how to use the various binaries to make the pipeline easier to call on a folder of images.
