### ISSUE TITLE
Invalid matches file in openMVG_main_GlobalSfM

### ISSUE THREAD

**Issue by Freeverc** [openMVG/openMVG#1548]
**I don't know why. It shows "Invalid matches file" when executing "openMVG_main_GlobalSfM"
My executing process is as follows**

freeverc@freeverc-ubuntu:~$ openMVG_main_SfMInit_ImageListing -i /home/freeverc/Dataset/images0 -d /home/freeverc/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o /home/freeverc/Dataset/sfmOut
 You called : 
openMVG_main_SfMInit_ImageListing
--imageDirectory /home/freeverc/Dataset/images0
--sensorWidthDatabase /home/freeverc/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/freeverc/Dataset/sfmOut
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 28
usable #File(s) listed in sfm_data: 28
usable #Intrinsic(s) listed in sfm_data: 1
freeverc@freeverc-ubuntu:~$ openMVG_main_ComputeFeatures -i /home/freeverc/Dataset/sfmOut/sfm_data.json -o /home/freeverc/Dataset/sfmOut -p HIGH
 You called : 
openMVG_main_ComputeFeatures
--input_file /home/freeverc/Dataset/sfmOut/sfm_data.json
--outdir /home/freeverc/Dataset/sfmOut
--describerMethod SIFT
--upright 0
--describerPreset HIGH
--force 0
--numThreads 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 112
freeverc@freeverc-ubuntu:~$ openMVG_main_ComputeMatches -i /home/freeverc/Dataset/sfmOut/sfm_data.json -o /home/freeverc/Dataset/sfmOut -r .8
 You called : 
openMVG_main_ComputeMatches
--input_file /home/freeverc/Dataset/sfmOut/sfm_data.json
--out_dir /home/freeverc/Dataset/sfmOut
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Segmentation fault (core dumped)
freeverc@freeverc-ubuntu:~$ openMVG_main_ComputeMatches -i /home/freeverc/Dataset/sfmOut/sfm_data.json -o /home/freeverc/Dataset/sfmOut -r .8 -n ANNL2
 You called : 
openMVG_main_ComputeMatches
--input_file /home/freeverc/Dataset/sfmOut/sfm_data.json
--out_dir /home/freeverc/Dataset/sfmOut
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method ANNL2
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using ANN_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 141

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 3

 Export Adjacency Matrix of the pairwise's geometric matches
freeverc@freeverc-ubuntu:~$ openMVG_main_GlobalSfM -i /home/freeverc/Dataset/sfmOut/sfm_data.json -m /home/freeverc/Dataset/sfmOut -o /home/freeverc/Dataset/sfmOut

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.

**Comment by pmoulon** [comment]
Default recommandation wants to use a `matches.e.bin`, by default the pipeline of ComputeMatches produce a matches.f.bin. 
You can either rename your matches.f.bin or use the `-g e` option on ComputeMatches.
