### ISSUE TITLE
why POINT_TO_LINE's MultError = 0.5, rather 1

### ISSUE THREAD

**Issue by zjulsy** [openMVG/openMVG#1549]
in "robust_estimator_ACRansacKernelAdaptator.hpp"，POINT_TO_LINE's MultError = 0.5,  POINT_TO_POINT‘s = 1。
but in relavant paper , it should be POINT_TO_LINE's MultError = 1,  POINT_TO_POINT‘s = 2。

thanks, in advance

**Comment by zjulsy** [comment]
MultError is the dimention of measurement. 
$$
log_{10}NFA(M,k)=log_{10}N_{out}(n-N_{sample})+log_{10}{n \choose k}+log_{10}{k \choose N_{sample}}\\+(k-N_{sample})( d*log_{10}(e_k(M)） + log_{10}(\alpha_0) )
$$

**Comment by pmoulon** [comment]
This is because there is a `/2` that is factorized in the formula between the paper and the implementation.
