### ISSUE TITLE
Automatic InitialPairChoice {feature request}

### ISSUE THREAD

**Issue by dcd2** [openMVG/openMVG#155]
When working with large datasets, it often takes fractions of an hour or even several hours to calculate tie points. When running openMVG_main_IncrementalSfM, one eventually arrives at the a manual decision point similar to below:

---
## IncrementalReconstructionEngine::InitialPairChoice

 The best F matrix validated pair are displayed
##  Choose one pair manually by typing the two integer indexes

(9,10)        59200 matches
(3,4)        55300 matches
(4,5)        45900 matches
(0,1)        34300 matches
(2,3)        32600 matches
(10,12)        31000 matches
(7,8)        26600 matches
(5,6)        26600 matches
(6,7)        26400 matches
(2,4)        24700 matches

 type INITIAL pair Indexes: X enter Y enter
9
10

Instead of relying on human interaction for selected the initial pair, would it be possible to add an optional argument for openMVG_main_IncrementalSfM to select the initial pair based on some sort of criterion? 

For example, if I'm running openMVG on a large dataset overnight, it doesn't make sense for the program to stop and ask me what to do. Since there's no time estimate in the calculation, I can't determine when I should be in front of the computer to enter in the initial pair. Even if there was a time estimate, the manual selection question may occur at some point in the day when I'm not in front of the computer.

I think a better solution would be to provide an optional argument in openMVG_main_IncrementalSfM so that the initial pair is selected based on a priori grounds (e.g., based on the highest number of matches, select the first pair in the list, the last pair in the list, the lowest number of matches, etc.).

I'm actually wondering why one has to manually select from the list of pairs? I always select the pair that has the highest number of matches. Maybe there's a rationale for this selection process that I'm missing? Is there some instability in the image pair matching that can't be identified until an initial pair is selected? If so, could the algorithm just run through all or some of the pairs until a solution is reached?

**Comment by pranny** [comment]
This is a great feature. I would love to see automatic initial pair selection in coming releases. I am trying to work on something like @mitjap did in his fork. However, his repo is quite old and I am new to MVG and openMVG APIs. Please help me in creating a patch that works for current version of openMVG. Thanks.

**Comment by pmoulon** [comment]
This task will be soon covered! https://github.com/openMVG/openMVG/issues/399

**Comment by jpwhitney** [comment]
@pmoulon I realize this is an old thread but could you elaborate on this comment?

>Often choosing the first pair will work if your image acquisition was good (never take poses that share a common nodal point).

  I'm trying to establish some image acquisition protocols and I think this could be key.

**Comment by pmoulon** [comment]
@jpwhitney 
My comment was about the fact that a lot of initial pairs can be used as seed for the reconstruction.
So if you turn around your object with more or less regular angles, all contiguous pair will be ok.
In the case of unordered image it's more hard for the user to choose by hand the initial pair.
