### ISSUE TITLE
union_find problem

### ISSUE THREAD

**Issue by zjulsy** [openMVG/openMVG#1550]
in sfm_data_filters.cpp, some functions uses union_find maybe wrong. such as bool IsTracksOneCC(const SfM_Data & sfm_data)

they use union_find.union(i, j), then count the number of CC as following:
```
  // Count the number of CC
  const std::set<unsigned int> parent_id(uf_tree.m_cc_parent.cbegin(), uf_tree.m_cc_parent.cend());
  return parent_id.size() == 1;
```

but error is showed as below:
```
#include <iostream>
#include "test_f.h"

#include <openMVG/tracks/union_find.hpp>
using namespace std;
using namespace openMVG;

int main()
{
     UnionFind uf;
     uf.InitSets(5);

     uf.Union(0, 1);
     uf.Union(1,2);
     uf.Union(3,4);
     uf.Union(1,3);

    for(int i=0; i<5; ++i)
    {
        cout << uf.m_cc_parent[i] << " ";
        // 0 0 0 0 3
}
}
```
so, there is a error. we cannot use  parent_id.size() to judge whether it is a CC

**Comment by pmoulon** [comment]
Thank you for your feedback and your code sample.
Appreciated.

You are right, perhaps we are using the API in a wrong way since your case is involving noncontiguous index.

-> Can you try with contiguous index?
```
uf.Union(0,1);
uf.Union(1,2);
uf.Union(1,3);
uf.Union(3,4);
```

Also with your pair configuration; can you try the following:

```for(int i=0; i<5; ++i)
    {
        // Do not do that -> cout << uf.m_cc_parent[i] << " ";
        // 0 0 0 0 3

        // and use this instead
        const uint32_t & track_id = uf.Find(i);
        cout << track_id << " ";
   }```

Let's investigate this and double check ;-)

**Comment by zjulsy** [comment]
contiguous index :
```c++
     uf.Union(0, 2);
     uf.Union(0, 3);
     uf.Union(1, 4);
     uf.Union(2, 4);
```
the result is : 0, 0, 0, 0, 1

the problem code  is that : 
```c++
  // Return the representative set id of I nth component
  unsigned int Find
  (
    unsigned int i
  )
  {
    // Recursively set all branch as children of root (Path compression)
    if (m_cc_parent[i] != i)
        m_cc_parent[i] = Find(m_cc_parent[i]);
     return m_cc_parent[i];
  }

  // Replace sets containing I and J with their union
  void Union
  (
    unsigned int i,
    unsigned int j
  )
  {
    i = Find(i);
    j = Find(j);
    if (i == j)
    { // Already in the same set. Nothing to do
      return;
    }

    // x and y are not already in same set. Merge them.
    // Perform an union by rank:
    //  - always attach the smaller tree to the root of the larger tree
    if (m_cc_rank[i] < m_cc_rank[j])
    {
      m_cc_parent[i] = j;
      m_cc_size[j] += m_cc_size[i];
    }
    else
    {
      m_cc_parent[j] = i;
      m_cc_size[i] += m_cc_size[j];
      if (m_cc_rank[i] == m_cc_rank[j])
        ++m_cc_rank[i];
    }
  }
```
uf.Union(2, 4) will make m_cc_parent[m_cc_parent[4]] from 1 to 0. but leave [m_cc_parent[4] unchanged.
so, we can have a final check using find(i) function for all [0, n-1]

**Comment by pmoulon** [comment]
So I took a second look to the code, and I think OpenMVG is using the union_find code correctly (at least for track generation).

```
openMVG::tracks::TracksBuilder tracksBuilder;
tracksBuilder.Build(map_triplet_matches);
tracksBuilder.Filter(3); // This function is performing the path compression (calling Find for every item)
tracksBuilder.ExportToSTL(tracks);
```

But you are right and `bool IsTracksOneCC(const SfM_Data & sfm_data)` was not calling the path compression (hopefully this function was not used in the pipeline but only for some unit test).

I'm gonna push an additional unit_test suite for union_find that will remind us and the community to use Find() before tracking the Connected Component id of every `tracked` item.

Thank you for your feedback and deep looking to this.

**Comment by pmoulon** [comment]
Thank you @zjulsy. Appreciated your feedback and code sharing in order to fix the issue.
The problem should be fixed and I double check, union_find is used correctly for feature tracking (Filter) is called each time.

Please review the code and close the issue once you agree with the changes.

**Comment by zjulsy** [comment]
thanks.
