### ISSUE TITLE
Creating OrthoPhotos

### ISSUE THREAD

**Issue by eokeeffe** [openMVG/openMVG#1553]
Heya, I've got some work done on creating orthophotos, both individual and
full mosaics. Hoping to have the code usable for everyone using openMVG.

I've been trying to use the structure observations from the gps rectified sfm_data_adjusted.json
file as artificial ground control points in GDAL,
 
from what I can see there's the track id, which I don't use, but I take the known ground coordinate as X then using the key from the observations to organise the known u,v points to X ground coordinates.

When I use the ECEF coordinate system (EPSG code 4798), I can get the images in the same system, but they don't overlap correctly.

I was wondering if I'm using the correct information.
I read the sfm_data_adjusted.json in Python (easier for GDAL operations)
and process the GCPs using the below code

    for structure in data['structure']:

        X = structure['value']['X']

        observations = structure['value']['observations']

        for observation in observations:

            key = observation['key']

            pixel_locations = observation['value']['x']

            if(key in tie_points.keys()):

                tie_points[key].append([X,pixel_locations])

            else:

                tie_points[key] = [[X,pixel_locations]]
`

Anything you can recommend on ?

**Comment by rjanvier** [comment]
>  I can get the images in the same system, but they don't overlap correctly

Could you please send us and example? 
what GDAL can do, is it a warping function? it's ok if your scene is almost flat, but it should not be optimal with some perspective. Also, It's worth mentioning you should use undistorded images. In this optic you should also work with undistorded image coordinates.

**Comment by eokeeffe** [comment]
Here are the TIF files, I've tried both inserting GCP points into the GDAL object and using GCPtoGeoTransform to get the geotransform from the GCP points and insert that into the GDAL object.
Both have resulted in much the same result.
I've tried using undistorted images, using the undistortion coefficients from openmvg to correct the images, but this still leaves the current result.
 
[temp1.zip](https://github.com/openMVG/openMVG/files/3344875/temp1.zip)

**Comment by rjanvier** [comment]
@eokeeffe sorry, but unfortunately it seems there is nothing into your zip file.

**Comment by eokeeffe** [comment]
Apologies, forgot the -R during zip
[temp.zip](https://github.com/openMVG/openMVG/files/3354907/temp.zip)

**Comment by rjanvier** [comment]
![capt](https://user-images.githubusercontent.com/1537100/60620053-71d92b80-9dda-11e9-9eba-26736c6edf66.png)
is it roughly what you get?

**Comment by eokeeffe** [comment]
That's the same output I have yes. I've tried a few methods to rectify, but I've run into a wall with this.
I've tried to rectify the images with the collinearity equation, but those results are about the same.

**Comment by rjanvier** [comment]
Could you send me the exact commands you used to reconstruct your scene with openMVG?
If you have any residual information from the methods you used from GDAL it could help us to understand too.
(as a side not, I think you forgot to undistort your 2d points as well, but i reallyt don't think it will fill the gap you have).
thanks you.

**Comment by eokeeffe** [comment]
I'll need to get the scripts, I followed the flow described in using the gps information in the geodesy rectification function, then using the output sfm_data_adjusted.bin, convert that to json format.

I'll upload the reconstruction file first

**Comment by eokeeffe** [comment]
Here's the scripts used

the openMVG script is reconstruct.py
the script where I extract information from sfm_data_adjusted.json is get_projections.py

[scripts.zip](https://github.com/openMVG/openMVG/files/3358615/scripts.zip)
