### ISSUE TITLE
Problem with disorganized images in matches

### ISSUE THREAD

**Issue by Livan89** [openMVG/openMVG#1554]
Hi.
When generating a 3d model I have the problem that if the images are disorganized, it only matches a group of them. For example, suppose I'm taking pictures around a human head; if I take 20 photos starting from the face, looking in front of the nose, moving to the right side until exactly the back, I stop and go back to the front, doing 20 photos but this time on the left side ending where I finished the previous sequence; In this case, only the left side or the right side is generated. Any suggestions to give me? What happens to me this is normal?

**Comment by pmoulon** [comment]
It is because the automatic process was not able to link all the picture together. It could be due to a lack of overlap between the images.

Faces are also a bit tricky because often there is not so much texture.
Tip: You can extract more feature per image by using the option `-p HIGH` on main_ComputeMatches it should help you a bit.

**Comment by Livan89** [comment]
Thank you pmoulon for your reply. 

Really in the examples I have had problem have usually been with more than 20 images and I have taken special care that each part to rebuild in 3D appears in at least 4 images. 

Does the process of pairing the key points in an image with all others occur in the ComputeMatching process or the IncrementalSfm process? Let's say I've taken 15 photos, does the pairing process try to pair each image with the remaining 14?

Thank you very much for your excellent work and help.

**Comment by Livan89** [comment]
> 
> 
> It is because the automatic process was not able to link all the picture together. It could be due to a lack of overlap between the images.
> 
> Faces are also a bit tricky because often there is not so much texture.
> Tip: You can extract more feature per image by using the option `-p HIGH` on main_ComputeMatches it should help you a bit.

Thank you Pierre for your reply. 

Really in the examples I have had problem have usually been with more than 20 images and I have taken special care that each part to rebuild in 3D appears in at least 4 images. 

Does the process of pairing the key points in an image with all others occur in the ComputeMatching process or the IncrementalSfm process? Let's say I've taken 15 photos, does the pairing process try to pair each image with the remaining 14?

Thank you very much for your excellent work and help.

**Comment by gaoshuai** [comment]
@Livan89 I have a experience of reconstructing a 3D flower using 20 images with textured background , but it failed. The reason is that there is so many wrong matches due to the background features of images, so I masked most part of the background and then using the option -p HIGH as suggested by pmoulon , and it succeed! So you can try.

**Comment by pmoulon** [comment]
Using a textured background can help (newspaper in the background), or placing some dots on the face.

See here https://translate.google.com/translate?sl=pt&tl=en&js=y&prev=_t&hl=pt-BR&ie=UTF-8&u=https://docs.google.com/document/d/e/2PACX-1vTbdYwzTcMkqXs9aFb_NYW1-qt_UGP5gKZdBOJFmYhkaAaD9S5-W78InL4CVEZt7_RdI5eDW72BZ8CU/pub&edit-text

**Comment by Livan89** [comment]
> @Livan89 I have a experience of reconstructing a 3D flower using 20 images with textured background , but it failed. The reason is that there is so many wrong matches due to the background features of images, so I masked most part of the background and then using the option -p HIGH as suggested by pmoulon , and it succeed! So you can try.

Hello, thank you very much for your response and your suggestions. Suppose I want to create a toy model and take 20 photos around the toy, at the background of each image appear different buildings, can this influence false coincidences that hinder the construction of my model?

When you mention that you masked the background, do you mean image processing tools or did you change the place where you took the photos to soften the texture?

Greetings and many thanks.

I'm sorry for my English, it's not my native language.

**Comment by gaoshuai** [comment]
Q1：yes, you can check the matches.
Q2: I masked the background as the instruction: https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeFeatures/

It will succeed but it is time consuming for generating the masked image.

**Comment by pmoulon** [comment]
@Livan89 Using a textured background is often the simplest solution (newspaper) for toys imagery

**Comment by Livan89** [comment]
> Q1：yes, you can check the matches.
> Q2: I masked the background as the instruction: https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeFeatures/
> 
> It will succeed but it is time consuming for generating the masked image.


Hello, once again, thank you for your help. I have been reading all the documentation I have found about masks, but I am not clear about whether the masks are generated automatically with some of the Compute_features processes, or if the mask of each image I have to create manually one by one.

Greetings and my apologies for the repeated doubts in this subject.

**Comment by Livan89** [comment]
> Q1：yes, you can check the matches.
> Q2: I masked the background as the instruction: https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeFeatures/
> 
> It will succeed but it is time consuming for generating the masked image.

Hello, in the answer you give me to question 1, about the coincidences, you tell me that I can check them. Is there any way to check visually these coincidences between images?

I am totally new to this and I am trying to learn at an accelerated pace, but perhaps what is obvious to you, for me, is a little less simple, so I apologize for my questions.

**Comment by pmoulon** [comment]
You can use the adjacency matrix that is exported in the match folder, or uses the exportMatches binary that will export SVG files that will allow you to see all the match that OpenMVG is considering as good.

**Comment by Livan89** [comment]
> You can use the adjacency matrix that is exported in the match folder, or uses the exportMatches binary that will export SVG files that will allow you to see all the match that OpenMVG is considering as good.


Hi pmoulon.

Thank you very much for answering. Currently the files that I generate are those that appear in the image that I am attaching, these files are generated from ComputeMatches, until now I had not used the ExportMatches, with the parameters that I have to pass I have some doubts. I imagine that the [-i | --input_file file] refers to sfm_data.json; the [-m | --sMatchFile filename] I'm not sure of its meaning. I also attach what the GeometricAdjacencyMatrix.svg file returns from an example.

Thank you very much for all the information you give me, it is very useful and constructive.

Good day

![File_gen](https://user-images.githubusercontent.com/50906087/61520200-f39d9b80-aa0d-11e9-9b8c-b6059f20308f.jpg)
![Matrix](https://user-images.githubusercontent.com/50906087/61520202-f39d9b80-aa0d-11e9-843c-8c12ce0ee935.jpg)

**Comment by pmoulon** [comment]
You can also install graphviz on your computer, and the match graph will be exported in your match folder.
I.e for https://github.com/openMVG/ImageDataset_SceauxCastle ![geometric_matches](https://user-images.githubusercontent.com/3235050/65900541-1122a600-e36b-11e9-821c-0ef610554db3.png)
