### ISSUE TITLE
sphere camera model and solve pnp

### ISSUE THREAD

**Issue by saedrna** [openMVG/openMVG#1557]
Hi,

Is it possible to use spherical camera model for space resection (solve PNP) in openmvg? I don't find documentation for this.

Thanks,
Han

**Comment by pmoulon** [comment]
Yes it is possible and this is already used in the pipeline if you do SfM with Spherical cameras.
You can use https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/localization/SfM_Localizer.hpp#L89 for this.

**Comment by saedrna** [comment]
Thanks!
