### ISSUE TITLE
converting .desc and .feat files

### ISSUE THREAD

**Issue by tkhan1994** [openMVG/openMVG#1558]
Hi

Is there any way I can convert the above mention file formats to .txt? I need to perform
some further processing and require the SIFT descriptors for that.

Thanks

**Comment by pmoulon** [comment]
You can use the API for that.
https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/descriptor.hpp#L125

https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/feature.hpp#L146

**Comment by tkhan1994** [comment]
Could you please explain a bit about how exactly I would be using this?

**Comment by tkhan1994** [comment]
Got it to work but am getting output files of size zero. Can you take a look at my code below to see if I'm doing something wrong?


`
#include "descriptor.hpp"

int main(){
  std::vector<openMVG::features::Descriptor<float,128>> test;
  bool a = openMVG::features::loadDescsFromFile("IMG_0583.desc", test);
  bool b = openMVG::features::saveDescsToFile("IMG_0583.txt", test);
}
`

**Comment by tkhan1994** [comment]
When I convert the .desc file to txt I get weird descriptors, by weird I mean the values are not whole numbers. Could you please explain why this is happening?

An example descriptor
```
2.22214e+14 1.91915e-12 7.43267e-13 1.16671e-34 1.85825e-40 6.86599e-36 0 0 1.03504e-11 5.77857e+13 9.39852e-27 0.00022547 1.01283e-40 8.4353e+08 3.25942e-42 1.50463e-36 1.69324e-24 4.37117e-20 1.30433e-41 3.19204e-09 2.81325e-41 39.5156 9.04118e-42 7.47387e-27 1.82808e-10 7.20857e-36 9.93281e-18 1.41959e-10 1.03689e-39 2.21899 2.55404e-38 1.46613e-19 4.05637e-37 9.32732e-41 5.46649e-25 2.68599e-38 2.09618e-24 3.10412e-09 9.05963e-15 0.000702666 3.79097e-37 3.72013e-40 4.89369e-16 1.45681e-25 2.44387e-18 6.41225e-10 9.39512e-18 1.3509e-28 6.01853e-36 1.44194e-42 7.08482e+14 7.30589e-30 2.40208e-06 7.43858e+14 42770.2 10761.6 0 0 10240.8 4.30576e-34 864.893 0.154401 6.37565e-07 0.190606 1.00738e-11 2.78309 0.0398275 1.32297e-19 3.34428e-17 8.49531e+14 7.72542e-15 3.39979e-08 4.14666e-17 1.11794e-17 2.15312e-15 3.94601e-20 3.56367e-17 1.50122e-07 2.4287e-38 3.9443e-31 3.07325e+09 1.09628e-17 4.9191e-11 9.66087e-18 6.85795e-25 7.46759e-21 1.45875e-42 9.62965e-35 0.727128 6.48808e-22 2.25922e-30 3.83926e-17 2.92159e-38 2.44503e-35 0 0 2.07188e-33 2.7326e-12 4.62793e-40 2.04591e+14 1.4013e-45 2.9781e-29 0 0 0.00317604 2.53399e-12 0.000702443 9.50668e+14 2.78338e-29 0.00306815 3.62096e-42 1.50463e-36 1.24078e-05 0.000729115 8.36181e+14 2.18105e-15 1.48462e-10 4.4292e+13 9.40803e-38 8.56474e-09 8.80146e-21 0.00017183 2.40125e-06 1.38959e-16 2.58595e-15 0.000576574 1.11356e-28 1.8727e-18 
```

**Comment by tkhan1994** [comment]
Got it! was using <float, 128> instead of <unsigned char, 128> for the vector type.

**Comment by pmoulon** [comment]
Glad you got it working. 

For reference for future users:

- OpenMVG features and descriptor couples are linked together here: https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/regions_factory.hpp
So for sift it is using https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/scalar_regions.hpp#L23 => `using DescriptorT = Descriptor<T, L>;`
