### ISSUE TITLE
How to run Ground control point UI

### ISSUE THREAD

**Issue by joshuajano** [openMVG/openMVG#1559]
Hello, can anyone guide me? i am using Ubuntu 16.04 and also i have downloaded the openMVG from github. Now, i want to test Ground control point example (https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP), but i do not know which code that i must run to show the GUI. 
Thank you so much.
Best regards,

Joshua

**Comment by pmoulon** [comment]
You are right we could update the documentation with the name of the binary `ui_openMVG_control_points_registration`. You need QT5 on your machine to make OpenMVG build it.

**Comment by joshuajano** [comment]
thank you for your guidance. I have downloaded and installed QT5 in my virtual machine.
Next, i tried to run ui_openMVG_control_points_registration.cpp file using terminal. First, i run "qmake -project" to create .pro file. Futhermore, i run "make" on my terminal and the error message appears.
In file included from moc_GraphicsView.cpp:9:0,
                 from ui_openMVG_control_points_registration_automoc.cpp:2:
../../../../../openMVG/src/software/ui/SfM/control_points_registration/GraphicsView.hpp:13:23: fatal error: QMainWindow: No such file or directory
compilation terminated.
Makefile:742: recipe for target 'ui_openMVG_control_points_registration_automoc.o' failed
make: *** [ui_openMVG_control_points_registration_automoc.o] Error 1

I tried to figure out the solution, but still did not work.
The last, i run "g++" in terminal ("g++ ui_openMVG_control_points_registration_automoc.cpp") but the error message like:
++ ui_openMVG_control_points_registration_automoc.cpp 
In file included from moc_GraphicsView.cpp:9:0,
                 from ui_openMVG_control_points_registration_automoc.cpp:2:
../../../../../openMVG/src/software/ui/SfM/control_points_registration/GraphicsView.hpp:13:23: fatal error: QMainWindow: No such file or directory
compilation terminated. 

do you have a solution ? Thanks Mr. Pierre

**Comment by pmoulon** [comment]
The app should be built with CMake and classic build.
You don't have to run qmake.

See https://github.com/openMVG/openMVG/blob/master/BUILD.md#compiling-on-linux

**Comment by joshuajano** [comment]
so, if i did not need to run qmake, you mean i must run just like 
g++ openMVG_control_points_registration_automoc.cpp? if yes, this error message will appear: 
In file included from moc_GraphicsView.cpp:9:0,
                 from ui_openMVG_control_points_registration_automoc.cpp:2:
../../../../../openMVG/src/software/ui/SfM/control_points_registration/GraphicsView.hpp:13:23: fatal error: QMainWindow: No such file or directory
compilation terminated.

**Comment by pmoulon** [comment]
I don't understand which path did you use to build OpenMVG.
All you have to run is `cmake` and then `make`.

You should not have to call g++ or qmake yourself.
Cmake will generate the right solution files that you gonna be able to build.

**Comment by joshuajano** [comment]
i am sorry for the miss understanding,
i will explain more detail about it. i have followed the instruction from https://github.com/openMVG/openMVG/blob/master/BUILD.md#linux and also followed this command mkdir openMVG_Build && cd openMVG_Build so i built in openMVG_Build folder. Futhermore, i have run cmake -DCMAKE_BUILD_TYPE=RELEASE ../openMVG/src/ and cmake --build . --target install in openMVG_Build folder and also "make test" and "ctest --output-on-failure -j" command. I thought this process has been successful (https://github.com/openMVG/openMVG/issues/1455). 

Now, i want to run GUI for ground control point (GCP) which is located in /home/joshuajano/openMVG_Build/software/ui/SfM/control_points_registration/. As you said, i must run ui_openMVG_control_points_registration and i assume that it is similar to ui_openMVG_control_points_registration_automoc.cpp. 

My question is how to run the code to show GUI or am i missing .exe file? 
Note: I already have QT5.

thank you.

**Comment by pmoulon** [comment]
If you have QT5 and do not have the control_point_registration binary it could be due to a cmake configuration.
Can you share the output of cmake here in order to see if there is something wrong (one QT module required and not detected)...?

**Comment by joshuajano** [comment]
I think so, because when i tried to run CMake, there are something output said failed and not found, i will let you know.
This is the output of CMake:
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Eigen 3.3.4 found (include: /home/joshuajano/openMVG/src/third_party/eigen)
-- Flann 1.8.4 found (include: /home/joshuajano/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.10.13 found (include: /home/joshuajano/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.16.10 found (include: /home/joshuajano/openMVG/src/dependencies/osi_clp/Clp/src)
-- Osi 0.107.8 found (include: /home/joshuajano/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: /home/joshuajano/openMVG/src/third_party/lemon/lemon)
-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
-- Detected Ceres version: 1.13.0 from /home/joshuajano/openMVG/src/third_party/ceres-solver/include/ceres/version.h
-- Eigen 3.3.4 found (include: /home/joshuajano/openMVG/src/third_party/eigen)
-- Found Eigen version 3.3.4: /home/joshuajano/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found BLAS library: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Disabling Schur specializations (faster compiles)
-- Building with OpenMP.
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- Enabling CERES_NO_SUITESPARSE in Ceres config.h
-- Enabling CERES_RESTRICT_SCHUR_SPECIALIZATION in Ceres config.h
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================
-- 
-- Configured Eigen 3.3.4
-- 
** Found Qt5, GUI modules will be build


** OpenMVG version: 1.4.0
** Build Shared libs: OFF
** Build OpenMVG tests: ON
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- CEREAL: (internal)
-- EIGEN: 3.3.4 (internal)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.8 (external)
-- LIBPNG: 1.6.32 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: 0.107.8 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/joshuajano/openMVG_Build

Thank you for your attention

**Comment by joshuajano** [comment]
If there are anything missing libraries,  please let me know.

**Comment by pmoulon** [comment]
We can read `** Found Qt5, GUI modules will be build` so the app should build fine and be install, when you are calling `cmake --build . --target install`.
Please double check that you have the app `ui_openMVG_control_points_registration` installed and ready to use.

**Comment by joshuajano** [comment]
sorry for late reply, 
i have re run cmake --build . --target install and this a whole folders in openMVG_Build
![image](https://user-images.githubusercontent.com/34101139/61921045-ba79a400-af96-11e9-8329-2ccde5acfc73.png)

**Comment by joshuajano** [comment]
and if i want to run the app, i just need to go to software/ui/SfM/control_points_registration right?
![image](https://user-images.githubusercontent.com/34101139/61921168-222fef00-af97-11e9-95bf-573590e8be96.png)

inside this folder, i found this
![image](https://user-images.githubusercontent.com/34101139/61921218-51466080-af97-11e9-9e1f-c20cfe0dc441.png) 
so i went to ui_openMVG_control_points_registration_autogen. right?

**Comment by pmoulon** [comment]
Yes, what happened when you launch `make` there?

**Comment by joshuajano** [comment]
The HTML pages are in htmlDoc.
[  0%] Built target doc
[ 10%] Built target lib_CoinUtils
[ 12%] Built target lib_Osi
[ 21%] Built target lib_clp
[ 21%] Built target lib_OsiClpSolver
[ 22%] Built target openMVG_stlplus
[ 23%] Built target openMVG_lemon
[ 23%] Built target main_svgSample
[ 32%] Built target openMVG_cxsparse
[ 55%] Built target openMVG_ceres
[ 55%] Built target openMVG_easyexif
[ 56%] Built target openMVG_fast
[ 56%] Built target openMVG_exif
[ 58%] Built target openMVG_features
[ 59%] Built target openMVG_numeric
[ 59%] Built target openMVG_image
[ 59%] Built target openMVG_linearProgramming
[ 63%] Built target openMVG_multiview
[ 65%] Built target openMVG_lInftyComputerVision
[ 67%] Built target openMVG_geometry
[ 68%] Built target openMVG_matching
[ 68%] Built target openMVG_kvld
[ 68%] Built target openMVG_matching_image_collection
[ 68%] Built target openMVG_multiview_test_data
[ 68%] Built target openMVG_robust_estimation
[ 68%] Built target openMVG_system
[ 72%] Built target openMVG_sfm
[ 73%] Built target openMVG_sample_cameras_undistoBrown
[ 73%] Built target openMVG_sample_robust_estimation_Homography
[ 73%] Built target openMVG_sample_multiview_robustHomography
[ 73%] Built target openMVG_sample_multiview_robustHomography_guided
[ 73%] Built target openMVG_sample_multiview_robustFundamental
[ 74%] Built target openMVG_sample_multiview_robustFundamental_guided
[ 74%] Built target openMVG_sample_multiview_robustEssential
[ 74%] Built target openMVG_sample_multiview_robustEssential_spherical
[ 75%] Built target openMVG_sample_multiview_robustEssential_ba
[ 75%] Built target openMVG_main_exif_Parsing
[ 77%] Built target vlsift
[ 77%] Built target openMVG_sample_main_features_repeatability_dataset
[ 77%] Built target openMVG_sample_features_affine
[ 77%] Built target openMVG_sample_features_kvld
[ 78%] Built target openMVG_sample_features_siftPutative
[ 78%] Built target openMVG_sample_image_matching
[ 79%] Built target openMVG_sample_image_matching_gmsfilter
[ 80%] Automatic MOC for target openMVG_sample_describe_and_match_GUI
[ 80%] Built target openMVG_sample_describe_and_match_GUI_autogen
[ 80%] Built target openMVG_sample_describe_and_match_GUI
[ 80%] Built target openMVG_sample_geodesy_show_exif_gps_position
[ 81%] Built target openMVG_sample_pano_converter
[ 82%] Automatic MOC for target openMVG_sample_image_undistort
[ 82%] Built target openMVG_sample_image_undistort_autogen
[ 82%] Built target openMVG_sample_image_undistort
[ 82%] Built target openMVG_sample_pano_spherical_to_cubic
[ 83%] Built target openMVG_main_evalQuality
[ 83%] Built target openMVG_main_ChangeLocalOrigin
[ 83%] Built target openMVG_main_SfMInit_ImageListing
[ 84%] Built target openMVG_main_MatchesToTracks
[ 85%] Built target openMVG_main_ConvertList
[ 85%] Built target openMVG_main_FrustumFiltering
[ 85%] Built target openMVG_main_ComputeSfM_DataColor
[ 85%] Built target openMVG_main_ListMatchingPairs
[ 85%] Built target openMVG_main_ComputeFeatures
[ 86%] Built target openMVG_main_IncrementalSfM
[ 87%] Built target openMVG_main_ComputeMatches
[ 87%] Built target openMVG_main_GlobalSfM
[ 87%] Built target openMVG_main_SplitMatchFileIntoMatchFiles
[ 87%] Built target openMVG_main_ConvertSfM_DataFormat
[ 87%] Built target openMVG_main_ComputeStructureFromKnownPoses
[ 87%] Built target openMVG_main_IncrementalSfM2
[ 87%] Built target openMVG_main_PointsFiltering
[ 87%] Built target domset
[ 87%] Built target openMVG_main_ComputeClusters
[ 87%] Built target openMVG_main_openMVG2PMVS
[ 88%] Built target openMVG_main_ExportUndistortedImages
[ 88%] Built target openMVG_main_openMVG2CMPMVS
[ 89%] Built target openMVG_main_openMVG2openMVS
[ 89%] Built target openMVG_main_openMVGSpherical2Cubic
[ 90%] Built target openMVG_main_openMVG2Agisoft
[ 90%] Built target openMVG_main_openMVG2MVSTEXTURING
[ 90%] Built target openMVG_main_exportKeypoints
[ 91%] Built target openMVG_main_openMVG2NVM
[ 92%] Built target openMVG_main_openMVG2MESHLAB
[ 92%] Built target openMVG_main_openMVG2Colmap
[ 93%] Built target openMVG_main_exportMatches
[ 93%] Built target openMVG_main_openMVG2MVE2
[ 93%] Built target openMVG_main_exportTracks
[ 93%] Built target openMVG_main_ExportCameraFrustums
[ 94%] Built target openMVG_main_SfMInit_ImageListingFromKnownPoses
[ 94%] Built target openMVG_main_SfM_Localization
[ 94%] Built target openMVG_main_geodesy_registration_to_gps_position
[ 95%] Built target openMVG_main_ColHarmonize
[ 95%] Automatic MOC for target openMVG_main_AlternativeVO
[ 95%] Built target openMVG_main_AlternativeVO_autogen
[ 97%] Built target openMVG_main_AlternativeVO
[ 97%] Automatic MOC for target ui_openMVG_MatchesViewer
[ 97%] Built target ui_openMVG_MatchesViewer_autogen
[ 99%] Built target ui_openMVG_MatchesViewer
[ 99%] Automatic MOC for target ui_openMVG_control_points_registration
[ 99%] Built target ui_openMVG_control_points_registration_autogen
[100%] Built target ui_openMVG_control_points_registration
[100%] Built target openMVG_main_openMVG2WebGL

**Comment by pmoulon** [comment]
See the `ui_openMVG_control_points_registration` is built. So if you look for it in the build folder or do make install you will be able to use it

**Comment by joshuajano** [comment]
yes, you ui_openMVG_control_points_registration is built. But, when i tried to find ui_openMVG_control_points_registration, i didn't find it. Based on the message, i assumed this folder ui_openMVG_control_points_registration_autogen and this folder ui_openMVG_control_points_registration will be built separately. But, when i run make i didn't find ui_openMVG_control_points_registration in this path /openMVG_Build/software/ui/SfM/control_points_registration and also inside ui_openMVG_control_points_registration_autogen.
![image](https://user-images.githubusercontent.com/34101139/62096263-02156e00-b2be-11e9-9cb6-ca8d7268e6a7.png)
![image](https://user-images.githubusercontent.com/34101139/62096276-1194b700-b2be-11e9-84ba-1b26504f44ab.png)
or maybe it was built in another directory?

**Comment by pmoulon** [comment]
You should have a folder called openmvg_build/Linux... The binary shoud be in it.

**Comment by joshuajano** [comment]
oo i see, like this
![image](https://user-images.githubusercontent.com/34101139/62103390-52e59080-b2d7-11e9-9c85-7b41ea474a7c.png)

but, how do I run it until the GUI appears?

**Comment by pmoulon** [comment]
Double click on it, or run it from the command line.

**Comment by joshuajano** [comment]
Thank you so much. I think the main problem is on my virtual machine. When i tried to double click on it, it didn't work, after i tried to fix the others branch of the problem, it works. Thank you so much, sorry for bothering you. I will close this issue.

**Comment by pmoulon** [comment]
Happy to hear that you get it running. Have fun experimenting!
