### ISSUE TITLE
SFM for stationary cameras

### ISSUE THREAD

**Issue by saedrna** [openMVG/openMVG#1561]
Hi,

Does the SFM pipeline of openMVG support images from stationary positions, e.g. only rotations on a tripod? The problem is that I want to estimate the pure rotation of each image.

I believe in this case, the translation in the pose should be fixed and the 3D unkown points should be parametrized to a unit sphere.

Is this feature already supported in openMVG?

Thanks,
Han

**Comment by csp256** [comment]
Does your tripod rotate about your focal point?

**Comment by saedrna** [comment]
@csp256 not necessary, but we can assume this, because it is small.

**Comment by pmoulon** [comment]
If you have only a rotation, you can compute a Homography and then use the known intrinsic matrix to find back the rotation.

FYI: Rotation only motion is a degenerate case for Structure from Motion (since you don't have a motion tht creates parallax)

**Comment by pmoulon** [comment]
If you are rotating with an arm like distance, Global SfM could provide some ok results see [Panoramic Structure from Motion via Geometric Relationship Detection](https://arxiv.org/pdf/1612.01256.pdf)

**Comment by saedrna** [comment]
@pmoulon Thanks, I will try if Global SFM is OK!
