### ISSUE TITLE
How do you check final 3d Output?

### ISSUE THREAD

**Issue by garimss** [openMVG/openMVG#1563]
![5](https://user-images.githubusercontent.com/16250644/61360989-2a5e9f00-a8b2-11e9-92b6-966dbf6cf19e.png)
I get this after running the SFM but how to check final reconstruction. When I click on any of 3d file, it says model can't load.

**Comment by nguyengiang41** [comment]
Hi,
You could try to visualize ply file with CloudCompare or Meshlab.


Le mer. 17 juil. 2019 à 10:46, Garima Agrawal <notifications@github.com> a
écrit :

**Comment by pmoulon** [comment]
The best files to watch are `colorized.ply` (color point cloud) or cloud_and_poses.ply (sfm output without color.)

**Comment by garimss** [comment]
thanks @pmoulon . I can see the difference. Still, I am trying my best to construct 3d of a leg, but it is failing many times not constructing. and many times it only take one pair and asking me manually pick the pair. So in this case, it only take points in 2 images and rest it just ignore which does not produce good 3d picture. Do you have any suggestions here to produce better 3d and get all images acknowledged by model.

**Comment by pmoulon** [comment]
What is important for photogrammetry is features.
You can try to detect more point per image by using the option `-p HIGH` on main_ComputeFeatures.
It often helps with skin-like material.

Try to make the image as sharp as possible.
