### ISSUE TITLE
what is K.txt? Why can't I run on my own images?

### ISSUE THREAD

**Issue by garimss** [openMVG/openMVG#1564]
(base) D:\git_hub\ralph\openMVG\build\software\SfM>python SfM_SequentialPipeline.py D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\XRV1\images D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output
Using input dir  :  D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\XRV1\images
      output_dir :  D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output
1. Intrinsics analysis
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\XRV1\images
--sensorWidthDatabase D:/git_hub/ralph/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database\sensor_width_camera_database.txt
--outputDirectory D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
k.txt: Unkown image file format.

SfMInit_ImageListing report:
listed #File(s): 12
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 0
2. Compute features
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeFeatures
--input_file D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\matches\sfm_data.json
--outdir D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
3. Compute matches
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeMatches
--input_file D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\matches\sfm_data.json
--out_dir D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********************************************
******
*
*
*

 - PUTATIVE MATCHES -
         PREVIOUS RESULTS LOADED; #pair: 0
'neato' is not recognized as an internal or external command,
operable program or batch file.

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
'neato' is not recognized as an internal or external command,
operable program or batch file.
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 0
 Images Id:

------------------
TrackLength, Occurrence

5. Colorize Structure

The input SfM_Data file "D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential\sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential\sfm_data.bin" cannot be read.

obust.bin" cannot be read.:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential

**Comment by pmoulon** [comment]
What you need to see here is that you have no intrinsic data for your images (see the log `usable #Intrinsic(s) listed in sfm_data: 0` at InitImageListing stage).

So I would advise you to add your camera to the Camera Sensor database `D:/git_hub/ralph/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database\sensor_width_camera_database.txt`
Or using the `-f <FOCAL_LEGTH_IN_PIXEL>` on InitImageListing stage. https://github.com/openMVG/openMVG/issues/669#issuecomment-258584371

For your information K.txt is provided in the sample folder just to provide an Intrinsic camera matrix for reference and if someone wants to use the imagery for another purpose.

**Comment by garimss** [comment]
@pmoulon thanks a lot for your time. It is working now. This error is gone. but I am still facing bellow errors in in few cases:

Colorize Structure
The input SfM_Data file "D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential\sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses
The input SfM_Data file "D:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential\sfm_data.bin" cannot be read.
obust.bin" cannot be read.:\git_hub\ralph\Newfolder\openMVG\build\software\SfM\output\reconstruction_sequential

**Comment by garimss** [comment]
Hi @pmoulon 

I am keep trying with different set of images to construct the lower leg 3d. Do you thing, there is any issue with code or images I am using.

please see the full below running process for both files --> SfM_SequentialPipeline.py & SfM_GlobalPipeline.py

(base) D:\git_hub\ralph\openMVG\build\software\SfM>python SfM_SequentialPipeline.py D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2
Using input dir  :  D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg
      output_dir :  D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2
1. Intrinsics analysis
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg
--sensorWidthDatabase
--outputDirectory D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
--focal 3500
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
IMG-0011.mat: Unkown image file format.
IMG-0011.sift: Unkown image file format.
IMG-0012.mat: Unkown image file format.
IMG-0012.sift: Unkown image file format.
IMG-0013.mat: Unkown image file format.
IMG-0013.sift: Unkown image file format.
IMG-0014.mat: Unkown image file format.
IMG-0014.sift: Unkown image file format.
IMG-0015.mat: Unkown image file format.
IMG-0015.sift: Unkown image file format.
IMG-0016.mat: Unkown image file format.
IMG-0016.sift: Unkown image file format.
IMG-0017.mat: Unkown image file format.
IMG-0017.sift: Unkown image file format.
IMG-0018.mat: Unkown image file format.
IMG-0018.sift: Unkown image file format.
IMG-0019.mat: Unkown image file format.
IMG-0019.sift: Unkown image file format.
IMG-0020.mat: Unkown image file format.
IMG-0020.sift: Unkown image file format.
IMG-0021.mat: Unkown image file format.
IMG-0021.sift: Unkown image file format.
IMG-0022.mat: Unkown image file format.
IMG-0022.sift: Unkown image file format.


SfMInit_ImageListing report:
listed #File(s): 36
usable #File(s) listed in sfm_data: 12
usable #Intrinsic(s) listed in sfm_data: 12
2. Compute features
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeFeatures
--input_file D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches\sfm_data.json
--outdir D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 31
3. Compute matches
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeMatches
--input_file D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches\sfm_data.json
--out_dir D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0
'neato' is not recognized as an internal or external command,
operable program or batch file.

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
'neato' is not recognized as an internal or external command,
operable program or batch file.
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 545
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
------------------
TrackLength, Occurrence
        2       414
        3       85
        4       26
        5       13
        6       6
        7       1

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*********************************************
*******
*

----------------------------------------------------
SequentialSfMReconstructionEngine::ChooseInitialPair
----------------------------------------------------
 Pairs that have valid intrinsic and high support of points are displayed:
 Choose one pair manually by typing the two integer indexes
----------------------------------------------------

(6,7)           119 matches
(5,6)           76 matches
(7,9)           64 matches
(4,5)           56 matches
(5,8)           49 matches
(5,7)           46 matches
(6,8)           46 matches
(7,8)           41 matches
(0,1)           40 matches
(3,4)           36 matches

 type INITIAL pair ids: X enter Y enter
5
7

Putative starting pair is: (5,7)
A-Contrario initial pair residual: 211.147

Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 2
 #tracks: 58
 #residuals: 232
 Initial RMSE: 1.65949
 Final RMSE: 1.42409
 Time (s): 0.0016425


=========================
 MSE Residual InitialPair Inlier:



SequentialSfMReconstructionEngine::ComputeResidualsMSE.
        -- #Tracks:     58
        -- Residual min:        0.000573104
        -- Residual median:     0.603078
        -- Residual max:         9.65554
        -- Residual mean:        1.2095
=========================

-------------------------------
-- Robust Resection of view: 6
  nfa=-63.253 inliers=34/44 precisionNormalized=0.000924772 precision=106.435 (iter=0 ,sample=28,11,10,)
  nfa=-79.9931 inliers=44/44 precisionNormalized=0.00249587 precision=174.855 (iter=1 ,sample=25,0,11,)
  nfa=-83.9995 inliers=42/44 precisionNormalized=0.00129354 precision=125.881 (iter=7 ,sample=27,12,38,)
  nfa=-84.8703 inliers=44/44 precisionNormalized=0.00189784 precision=152.475 (iter=8 ,sample=26,20,30,)
  nfa=-89.1372 inliers=37/44 precisionNormalized=0.000300876 precision=60.7102 (iter=25 ,sample=43,8,36,)
  nfa=-98.3009 inliers=37/44 precisionNormalized=0.000161703 precision=44.5069 (iter=28 ,sample=40,10,18,)
  nfa=-100.877 inliers=36/44 precisionNormalized=0.000102711 precision=35.4712 (iter=29 ,sample=21,40,17,)
  nfa=-101.868 inliers=36/44 precisionNormalized=9.58389e-05 precision=34.2641 (iter=36 ,sample=21,43,8,)
  nfa=-103.394 inliers=37/44 precisionNormalized=0.0001145 precision=37.4516 (iter=94 ,sample=42,18,12,)
  nfa=-104.153 inliers=37/44 precisionNormalized=0.000108755 precision=36.5001 (iter=186 ,sample=40,41,8,)
  nfa=-104.725 inliers=37/44 precisionNormalized=0.000104617 precision=35.7989 (iter=220 ,sample=34,42,20,)
  nfa=-104.828 inliers=37/44 precisionNormalized=0.000103887 precision=35.6738 (iter=331 ,sample=40,34,20,)

-------------------------------
-- Robust Resection
-- Resection status: 1
-- #Points used for Resection: 44
-- #Points validated by robust Resection: 37
-- Threshold: 35.6738
-------------------------------

Bundle Adjustment statistics (approximated RMSE):
 #views: 1
 #poses: 1
 #intrinsics: 1
 #tracks: 37
 #residuals: 74
 Initial RMSE: 8.74814
 Final RMSE: 8.51499
 Time (s): 0.0013907


Bundle Adjustment statistics (approximated RMSE):
 #views: 12
 #poses: 3
 #intrinsics: 12
 #tracks: 191
 #residuals: 834
 Initial RMSE: 5.29932
 Final RMSE: 0.543032
 Time (s): 0.253411


Bundle Adjustment statistics (approximated RMSE):
 #views: 12
 #poses: 3
 #intrinsics: 12
 #tracks: 141
 #residuals: 618
 Initial RMSE: 0.428178
 Final RMSE: 0.368859
 Time (s): 0.222446


-------------------------------
-- Robust Resection of view: 4
  nfa=-12.1005 inliers=13/16 precisionNormalized=0.00398774 precision=221.02 (iter=0 ,sample=12,13,10,)
  nfa=-13.0473 inliers=13/16 precisionNormalized=0.00320663 precision=198.195 (iter=0 ,sample=12,13,10,)
  nfa=-19.7873 inliers=16/16 precisionNormalized=0.0043385 precision=230.536 (iter=1 ,sample=10,6,5,)
  nfa=-26.8586 inliers=15/16 precisionNormalized=0.000630529 precision=87.8862 (iter=2 ,sample=0,7,10,)
  nfa=-33.4439 inliers=16/16 precisionNormalized=0.000386107 precision=68.7736 (iter=3 ,sample=14,12,4,)
  nfa=-36.1598 inliers=16/16 precisionNormalized=0.000238622 precision=54.0659 (iter=5 ,sample=9,2,15,)
  nfa=-41.6334 inliers=16/16 precisionNormalized=9.0429e-05 precision=33.283 (iter=14 ,sample=15,2,14,)
  nfa=-41.6334 inliers=16/16 precisionNormalized=9.0429e-05 precision=33.283 (iter=209 ,sample=14,2,15,)
  nfa=-41.7071 inliers=16/16 precisionNormalized=8.9255e-05 precision=33.0662 (iter=247 ,sample=2,15,12,)
  nfa=-41.7071 inliers=16/16 precisionNormalized=8.9255e-05 precision=33.0662 (iter=279 ,sample=12,15,2,)

-------------------------------
-- Robust Resection
-- Resection status: 1
-- #Points used for Resection: 16
-- #Points validated by robust Resection: 16
-- Threshold: 33.0662
-------------------------------

Bundle Adjustment statistics (approximated RMSE):
 #views: 1
 #poses: 1
 #intrinsics: 1
 #tracks: 16
 #residuals: 32
 Initial RMSE: 8.62463
 Final RMSE: 8.2392
 Time (s): 0.0005734


Bundle Adjustment statistics (approximated RMSE):
 #views: 12
 #poses: 4
 #intrinsics: 12
 #tracks: 168
 #residuals: 740
 Initial RMSE: 2.88089
 Final RMSE: 0.530936
 Time (s): 0.424598


Bundle Adjustment statistics (approximated RMSE):
 #views: 12
 #poses: 4
 #intrinsics: 12
 #tracks: 30
 #residuals: 166
 Initial RMSE: 0.633227
 Final RMSE: 0.394633
 Time (s): 0.133979


-------------------------------
-- Robust Resection of view: 8
  nfa=1.83687 inliers=7/8 precisionNormalized=0.10593 precision=1139.14 (iter=0 ,sample=4,1,0,)
  nfa=1.52742 inliers=6/8 precisionNormalized=0.0459462 precision=750.227 (iter=1 ,sample=1,3,4,)
  nfa=-1.25857 inliers=7/8 precisionNormalized=0.0178302 precision=467.354 (iter=4 ,sample=2,7,4,)
  nfa=-1.25857 inliers=7/8 precisionNormalized=0.0178302 precision=467.354 (iter=143 ,sample=2,4,7,)
  nfa=-1.25857 inliers=7/8 precisionNormalized=0.0178302 precision=467.354 (iter=310 ,sample=4,2,7,)

-------------------------------
-- Robust Resection
-- Resection status: 0
-- #Points used for Resection: 8
-- #Points validated by robust Resection: 7
-- Threshold: 467.354
-------------------------------

-------------------------------
-- Robust Resection of view: 9
  nfa=-0.0202499 inliers=4/4 precisionNormalized=0.0189879 precision=482.288 (iter=0 ,sample=0,1,2,)
  nfa=-0.482899 inliers=4/4 precisionNormalized=0.00654369 precision=283.126 (iter=4 ,sample=0,3,1,)
  nfa=-0.482899 inliers=4/4 precisionNormalized=0.00654369 precision=283.126 (iter=5 ,sample=1,0,3,)
  nfa=-0.482899 inliers=4/4 precisionNormalized=0.00654369 precision=283.126 (iter=43 ,sample=1,3,0,)

-------------------------------
-- Robust Resection
-- Resection status: 0
-- #Points used for Resection: 4
-- #Points validated by robust Resection: 4
-- Threshold: 283.126
-------------------------------

-------------------------------
-- Robust Resection of view: 3

-------------------------------
-- Robust Resection
-- Resection status: 0
-- #Points used for Resection: 3
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------

-------------------------------
-- Robust Resection of view: 10

-------------------------------
-- Robust Resection
-- Resection status: 0
-- #Points used for Resection: 3
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------


-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 4 from 12 input images.
-- #Tracks, #3D points: 30
-------------------------------



SequentialSfMReconstructionEngine::ComputeResidualsMSE.
        -- #Tracks:     30
        -- Residual min:        2.26259e-05
        -- Residual median:     0.216544
        -- Residual max:         2.38488
        -- Residual mean:        0.3536

Histogram of residuals:
0       |       88
0.238   |       34
0.477   |       17
0.715   |       12
0.954   |       5
1.19    |       5
1.43    |       3
1.67    |       0
1.91    |       0
2.15    |       1
2.38


 Total Ac-Sfm took (s): 116
...Generating SfM_Report.html
...Export SfM_Data to disk.
5. Colorize Structure

Compute scene structure color
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 12
 #poses: 4
 #intrinsics: 12
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************
**************************
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*********
*******************************************
*
*
*
*

Structure estimation took (s): 0.

#landmark found: 6
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 12
 #poses: 4
 #intrinsics: 12
 #tracks: 6

obust.bin" cannot be read.:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\reconstruction_sequential

(base) D:\git_hub\ralph\openMVG\build\software\SfM>python SfM_GlobalPipeline.py D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2
Using input dir  :  D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg
      output_dir :  D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2
1. Intrinsics analysis
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory D:\git_hub\ralph\openMVG\build\software\SfM\natanielleg
--sensorWidthDatabase -f
--outputDirectory D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

Invalid input database: -f, please specify a valid file.
2. Compute features
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeFeatures
--input_file D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches\sfm_data.json
--outdir D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
3. Compute matches
 You called :
D:/git_hub/ralph/openMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeMatches
--input_file D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches\sfm_data.json
--out_dir D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
         PREVIOUS RESULTS LOADED; #pair: 66
'neato' is not recognized as an internal or external command,
operable program or batch file.

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

 Export Adjacency Matrix of the pairwise's geometric matches
'neato' is not recognized as an internal or external command,
operable program or batch file.
4. Do Global reconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 4
Connected component of size: 1
Connected component of size: 1
Connected component of size: 1
Connected component of size: 1

- Relative pose computation -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Relative motion computation took: 1(ms)
'neato' is not recognized as an internal or external command,
operable program or batch file.
'neato' is not recognized as an internal or external command,
operable program or batch file.
GlobalSfM:: Rotation Averaging failure!
5. Colorize Structure

The input SfM_Data file "D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\reconstruction_global\sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "D:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\reconstruction_global\sfm_data.bin" cannot be read.

obust.bin" cannot be read.:\git_hub\ralph\openMVG\build\software\SfM\nat-leg-2\reconstruction_global

**Comment by pmoulon** [comment]
Are you sure about your focal length value, the initial residual seems very high `A-Contrario initial pair residual: 211.147`?

**Comment by garimss** [comment]
Hi Pmoulon, I am not sure about focal length. but I just tried with random f I guess.
I am not able to get perfect 3d yet. I wonder if we can use mask images here or need pictures with background information as well?

**Comment by garimss** [comment]
@pmoulon can you guide me on the attached images how to make perfect 3d out of it. I tried by myself but I do get  few points on final ply 
 but nothing is visible. I am really keen to learn openMVG.
[Images.zip](https://github.com/openMVG/openMVG/files/3479558/Images.zip)

**Comment by pmoulon** [comment]
I check your images, here some observations
- some images are blurry, the sharper your image will be, the better the reconstruction will be (focus issue)
- resolution (513 × 288), using a higher resolution could help to have better 3D

The best setting for such an application would be to have your patient standing in front of a textured wall and turn around the leg with a camera on a tripod. Shooting 8-12 images with very sharp images would be sufficient and should provide better results.
