### ISSUE TITLE
[regression in 1.5] Installs eigen when eigen is already installed

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1566]
These files are now installed:
```
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/openMVG/third_party/eigen/Eigen/Cholesky
Error: Missing: include/openMVG/third_party/eigen/Eigen/CholmodSupport
Error: Missing: include/openMVG/third_party/eigen/Eigen/Core
Error: Missing: include/openMVG/third_party/eigen/Eigen/Dense
```

Eigen3 is already installed. Please don't install it again.
Please use Eigen3 supplied in the system.

**Comment by pmoulon** [comment]
It seems that on your system, the existing Eigen was not detected.
Can you share the cmake log, OpenMVG display if it is using the internal or the external libraries?
I would like to understand in your case if the external one was used?

example on a fresh empty system:
```CEREAL: (internal)
EIGEN: 3.3.4 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)
```

**Comment by yurivict** [comment]
I can't reproduce this any more.

Thank you for your help!
