### ISSUE TITLE
How can I export matches from a pair of images and their corresponding coordinates

### ISSUE THREAD

**Issue by garimss** [openMVG/openMVG#1567]
I would like to know how to extract the matches and their coordinates.

I have tried the previous method given by @pmoulon at #1304 but it is still giving .bin format. 

and How to get coordinates, still not sure. I am stuck.

@pmoulon can you share the full modified code for .cpp file to get matches and coordinates for each image and for final 3d.

**Comment by pmoulon** [comment]
See the answer here https://github.com/openMVG/openMVG/issues/1304#issuecomment-514873458

**Comment by pmoulon** [comment]
moved your [previous message](https://github.com/openMVG/openMVG/issues/1121#event-2513846237) here since it was not posted in the right place.

> @rperrot and & @pmoulon Hi, I am wondering how to extract matched points and with coordinates. And also How to build tracks. Sorry for being demanding. I am just a newbie here. And trying to solve a 3d leg problem where I need to get exact matches and may be with few best matches and than have to extract the point information.

> Also wondering is by using tracks I can visualize image by image matches. But not sure how do use the code.

> There is no specific guideline given. I am curious to know the method to use the code given on https://openmvg.readthedocs.io/en/latest/openMVG/tracks/tracks/

> Is this code needed to be include in .cpp files and build over and than run through SFM or just need to add this code in sequential or/& Global pipeline code.

> I will appreciate your quick response. Thanks
