### ISSUE TITLE
Adding color to 3D Points

### ISSUE THREAD

**Issue by tkhan1994** [openMVG/openMVG#1568]
Hi,
Is it possible to add custom colors to individual 3D points in the sfm_data.json file and then convert it to a .ply file for visualization?
Thanks

**Comment by rennu** [comment]
Hi,

Is this what you are looking for: [openMVG_main_ComputeSfM_DataColor](https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeSfM_DataColor/)?

**Comment by tkhan1994** [comment]
Unfortunately no, I want to add custom colors to individual 3D points (not their real colors). Thanks anyway though.

**Comment by tkhan1994** [comment]
Got it, had to understand the structure of the colorized.ply file and edit it accordingly.
Thanks
