### ISSUE TITLE
wrongly generated scene.mvs

### ISSUE THREAD

**Issue by shuanglangshuanglang** [openMVG/openMVG#1572]
windows 10 visual studio 2017
i did what the pipeline said,but when exported to mvs , the generated scene.mvs cant be opened by viewer ,i was wondering what's going wrong OTZ
thanks!

**Comment by shuanglangshuanglang** [comment]
heres my project...due to the reason that only files less than 25mb could be uploaded via exploror so the folder"images" is empty and originnaly the SceauxCastle pictures should be in the images folder 

https://github.com/shuanglangshuanglang/example

much obliged!

**Comment by shuanglangshuanglang** [comment]
heres how i used the sfm pipe line and export the result to scene.mvs



cd c:/openmvg_mvs
mkdir example
cd example
mkdir images
mkdir matches
mkdir outReconstruction

cd C:\openMVG_MVS\openMVG_Build\Windows-AMD64-\Debug

openMVG_main_SfMInit_ImageListing -i C:\openMVG_MVS\example\images -d C:\openMVG_MVS\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camera_database.txt -o C:\openMVG_MVS\example\matches

openMVG_main_ComputeFeatures -i C:\openMVG_MVS\example\matches\sfm_data.json -o C:\openMVG_MVS\example\matches

openMVG_main_ComputeMatches -i C:\openMVG_MVS\example\matches\sfm_data.json -o C:\openMVG_MVS\example\matches

openMVG_main_IncrementalSfM -i C:\openMVG_MVS\example\matches\sfm_data.json -m C:\openMVG_MVS\example\matches\ -o C:\openMVG_MVS\example\outReconstruction

openMVG_main_ComputeSfM_DataColor -i C:\openMVG_MVS\example\outReconstruction\sfm_data.bin -o C:\openMVG_MVS\example\outReconstruction\sfm_data_color.ply

openMVG_main_ComputeStructureFromKnownPoses -i C:\openMVG_MVS\example\outReconstruction\sfm_data.bin -o C:\openMVG_MVS\example\outReconstruction\robustFitting.json -m C:\openMVG_MVS\example\matches

openMVG_main_ComputeSfM_DataColor -i C:\openMVG_MVS\example\outReconstruction\robustFitting.json -o C:\openMVG_MVS\example\outReconstruction\robust_colorized.ply

openMVG_main_openMVG2openMVS -i C:\openMVG_MVS\example\outReconstruction\sfm_data.bin -o C:\openMVG_MVS\example\MVS\scene.mvs -d C:\openMVG_MVS\example\MVS


then the generated scene.mvs could not be opened by viewer..
when i drag the scene.mvs to the viewer and it just reports 
Debug Error!
abort() has been called

**Comment by shuanglangshuanglang** [comment]
@pmoulon sorry to bother you but could this be the the version issue? dont know how to check which step of the pipeline is wrong, would be very grateful if you could help! downloaded windows 1.5 this morning and redo all the sfm pipelines but still the error still exists (cant open generated mvs file in the viewer of openmvs)

**Comment by pmoulon** [comment]
1. I would advise you to build and run OpenMVG in Release mode. It seems you are using the debug version.
2. Do you use the last OpenMVS version... If it's a version issue you could try to update `https://github.com/openMVG/openMVG/blob/master/src/software/SfM/export/InterfaceMVS.h` with the last version https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Interface.h and see if it fix you issue

**Comment by shuanglangshuanglang** [comment]
@pmoulon Ahhhhhh thanks very much and i think i figured out what the problems is...... when i use the cmake 
`cmake . ..\src -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=C:\openMVG_MVS\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCG_ROOT="C:\openMVG_MVS\VCG"`
**at first , i didnt add `-G "Visual Studio 15 2017 Win64"`**
**So actually im using win32 OpenMVG but the OpenMvs is win64**,thats why i cant open the generated mvs file in the viewer.........
now i use win64 OpenMVG and win64 OpenMVS the generated mvs file could be opened in the viewer.
for people who might need step by step procedure in chinese , heres the blog i write , with every steps and code.....
https://blog.csdn.net/weixin_43149897/article/details/98174555
And thanks again for pmolon's time for checking this issue! Have a nice day! :）
may i close this issue?

**Comment by pmoulon** [comment]
Sure you can close the issue. Happy to see that you was able to find the error ;-)
