### ISSUE TITLE
CXX11 add_ceres_cxx11_requirements_to_target error 

### ISSUE THREAD

**Issue by happyfrank** [openMVG/openMVG#1574]
https://github.com/openMVG/openMVG/blob/606d1c9e82123dd50de282128151a50bf42262fc/src/third_party/ceres-solver/internal/ceres/CMakeLists.txt#L223

ceres -> openMVG_ceres

**Comment by pmoulon** [comment]
Do you mind do a PR?

**Comment by happyfrank** [comment]
Of course. ^v^

**Comment by pmoulon** [comment]
Thank you. Let's wait the output of the CI build before merging.
