### ISSUE TITLE
Use output of openMVG to PMVS in Meshlab with texture

### ISSUE THREAD

**Issue by sealiutree7** [openMVG/openMVG#1577]
Sorry, I don't know whether this question is stupid or not. I've read all I can find but I'm still confused.
I'm trying to use OpenMVG->CMVS-PMVS->Meshlab (to do Poisson Reconstruction),
and everything works perfectly until want to complete this step:
First, this is the result after doing Poisson Reconstruction
![1](https://user-images.githubusercontent.com/36202154/62560193-1a355080-b8af-11e9-926c-f7fa83adebb8.jpg)
and the result still good. Then I use "Filter->Texture->Parameterization+texture form registered rasters" or  "Filter->Texture->Parameterization form registered rasters"+"Filter->Texture->Project active rasters color to current mesh,filling the texture" (I've tried both ways) like this:
![3](https://user-images.githubusercontent.com/36202154/62560699-34bbf980-b8b0-11e9-9849-2bd2458c77fe.jpg)

The result seems weird:
![2](https://user-images.githubusercontent.com/36202154/62561027-e529fd80-b8b0-11e9-9293-ad3b8ba3ec71.jpg)

I also tried another way to finish this work (VisualSfM->CMVS-PMVS->Meshlab), and the result seems good:
![4](https://user-images.githubusercontent.com/36202154/62561760-6afa7880-b8b2-11e9-8765-a5d122b3251f.jpg)

I have no idea why the texture result will be so different since the CMVS-PMVS data from VisualSFM and OpenMVG almost the same. If you have any idea or I did something wrong, please don't refuse to offer your kind advice! Thanks so much.

**Comment by pmoulon** [comment]
Thank you for your interest in OpenMVG and sharing your process and screenshots.

Here some notes and observation I can mention:
1. VisualSfM does not optimize the camera projection center.
2. Can you try with a dataset that we know better https://github.com/openMVG/ImageDataset_SceauxCastle
3. I would advise you to use OpenMVG + OpenMVS, you will have better results than a Poisson  reconstruction
https://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/

**Comment by sealiutree7** [comment]
> Thank you for your interest in OpenMVG and sharing your process and screenshots.
> 
> Here some notes and observation I can mention:
> 
> 1. VisualSfM does not optimize the camera projection center.
> 2. Can you try with a dataset that we know better https://github.com/openMVG/ImageDataset_SceauxCastle
> 3. I would advise you to use OpenMVG + OpenMVS, you will have better results than a Poisson  reconstruction
>    https://openmvg.readthedocs.io/en/latest/software/MVS/OpenMVS/

Thanks for your replay and a lot of your time.
I use the SceauxCastle dataset to do the experiment and the result will be like this:

(1) OpenMVG->CMVS-PMVS->Meshlab
With "Filter->Texture->Parameterization+texture form registered rasters" 
![h1](https://user-images.githubusercontent.com/36202154/62572914-67bdb780-b8c7-11e9-99a7-d6286af47037.jpg)

With "Filter->Texture->Parameterization form registered rasters"+"Filter->Texture->Project active rasters color to current mesh,filling the texture"
![h2](https://user-images.githubusercontent.com/36202154/62572990-8a4fd080-b8c7-11e9-9355-ccc7a9390787.jpg)

(2) VisualSfM->CMVS-PMVS->Meshlab
With "Filter->Texture->Parameterization+texture form registered rasters"
![sh1](https://user-images.githubusercontent.com/36202154/62573046-b10e0700-b8c7-11e9-9939-7ffa9f1071b4.jpg)

With "Filter->Texture->Parameterization form registered rasters"+"Filter->Texture->Project active rasters color to current mesh,filling the texture"
![sh2](https://user-images.githubusercontent.com/36202154/62573060-ba976f00-b8c7-11e9-9ada-4263735f9c74.jpg)

In (1) result seems there is an offset (I don't know how to describe this situation) between the texture and the model. Is this may be caused by the first point you mentioned and do I have a chance to solve it? Thanks a lot again.

Thanks so much for your advice, too! I'll try OpenMVG + OpenMVS later. (I would like to realize a method of a paper which use the Poisson reconstruction method and that is the reason I implement the pipeline now. :) )

**Comment by pmoulon** [comment]
The thing you can do also tells OpenMVG to do not optimize the camera principal point.
- You can add this option to the SfM Incremental/Global binary`-f ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION` and the principal point will remain in the middle of the image and perhaps fix your issue because it seems that Meshlab texture projection does not support a variable principal point.

**Comment by sealiutree7** [comment]
Thanks for your guidance, it successfully solved the problem and everything works well now!
Attached are the experiment result:
![OpenMVG_CMVSPMVS+Meshlab](https://user-images.githubusercontent.com/36202154/62711227-3a8a1a00-ba2b-11e9-87c4-c75e1126c7a2.jpg)

![OpenMVG_CMVSPMVS+Meshlab2](https://user-images.githubusercontent.com/36202154/62711609-ed5a7800-ba2b-11e9-9f39-41c086a3e7d9.jpg)

Sorry because I'm new to this field and a little confused about a few points. Would you mind explaining the advantage to optimize the camera principal point here? Is it help us to get a better estimation of camera parameter result or for other reason?  Thank you very much indeed.

sincerely

**Comment by pmoulon** [comment]
What we made here, is ask OpenMVG to keep the camera principal point in the center of the image, because Meshlab camera model does not support a different position than the center.

By default, OpenMVG optimizes all the camera parameter (Focal, Principal point, and camera distortion) in order to support what really happens with your camera sensor and optics (they are never perfectly aligned). In most of the case forcing the principal point to stay in the middle of the image will not `damage` the reconstruction too much (as you saw reconstruction looks correct) but it can make the reconstruction a bit less accurate.

BTW, if you look for accuracy I strongly advise you to take a look to OpenMVS rather than using Poisson Surface Reconstruction. You will have less smoothing artifact.

**Comment by pmoulon** [comment]
Please close the issue if you have all the answer you need.

**Comment by sealiutree7** [comment]
Understood, thank you so much!
