### ISSUE TITLE
Use as external library with OpenMVGConfig.cmake seems outdated

### ISSUE THREAD

**Issue by rfabbri** [openMVG/openMVG#1578]
I tried using OpenMVG as a third-party to my other Cmake project (based on VXL).
The `BUILD.md` says to install OpenMVG on a custom/separate install folder.
So I built `OpenMVG` on `openMVG-bin`, then make-installed on `openMVG-install` inside it.

My project's CMake goes like this
```Cmake
  find_package(OpenMVG REQUIRED)
  include_directories( ${OPENMVG_INCLUDE_DIRS} )
  add_executable(program ${program_sources})
  target_link_libraries(program
    openMVG_multiview            # the one I need
    other_libs
  )
```
Then it finds OpenMVG but still complains about not finding "include files".
I figured that there is a problem with the `OpenMVGConfig.cmake` file which wasn't updated since last year, and it was assuming a completely random path for the installed files.

I am sending a pull request for a first fix. But then, if this is correct, it should serve as basis for a better long-term solution. Thank you for OpenMVG!

**Comment by rfabbri** [comment]
A first fix: https://github.com/openMVG/openMVG/pull/1579

**Comment by pmoulon** [comment]
Thank for your comments.

Include folder should come with the target since we are using modern CMake. You should not have to add `include_directories( ${OPENMVG_INCLUDE_DIRS} )`.

Please try the modern approach: https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake

```find_package(OpenMVG REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main
  PRIVATE
    OpenMVG::openMVG_sfm
    OpenMVG::openMVG_matching
    ...
)```
The old one is perhaps broken due to the recent change for the modern CMake.

**Comment by rfabbri** [comment]
Hi, can you still take a quick look at my pull request? The file `OpenMVGTargets.cmake` seems to be produced at a different location than OpenMVG expects.

> Include folder should come with the target since we are using modern CMake. You should not have to add `include_directories( ${OPENMVG_INCLUDE_DIRS} )`.
> 
> Please try the modern approach: https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake
> 

The instructions in that `BUILD.md` have the `include_directories`, but good to know.

> ```
> add_executable(main main.cpp)
> target_link_libraries(main
>   PRIVATE
>     OpenMVG::openMVG_multiview
>     OpenMVG::openMVG_matching
>     ...
> )```
> The old one is perhaps broken due to the recent change for the modern CMake.
> ```

**Comment by rfabbri** [comment]
I figured out how things work. I had to follow the instructions at the bottom of `BUILD.md` closely. The details are different than what I'm used to in other projects.
Please discard the pull request.

**Comment by dagata-mining** [comment]
For anyone using CLION and building in a 3rd party Librairie make sure you change your OpenMVG_DIR value in the cmake-build-debug/CMakeCache.txt so for example : OpenMVG_DIR:PATH=/home/dagata/openMVG_Build/openMVG_install/share/openMVG/cmake
