### ISSUE TITLE
OpenMVG not building with GCC 5 on Mac OS

### ISSUE THREAD

**Issue by rfabbri** [openMVG/openMVG#1580]
I get these errors:
```
[100%] Built target openMVG_main_ColHarmonize
In file included from /Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/main_openMVG2openMVS.cpp:16:0:
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h: In instantiation of 'bool MVS::ARCHIVE::Save(MVS::ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp = long unsigned int]':
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h:255:14:   required from here
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h:121:2: error: request for member 'serialize' in '(long unsigned int&)(& obj)', which is of non-class type 'long unsigned int'
  const_cast<_Tp&>(obj).serialize(a, a.version);
  ^
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h: In instantiation of 'bool MVS::ARCHIVE::Load(MVS::ARCHIVE::ArchiveLoad&, _Tp&) [with _Tp = long unsigned int]':
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h:263:14:   required from here
/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/software/SfM/export/InterfaceMVS.h:126:2: error: request for member 'serialize' in 'obj', which is of non-class type 'long unsigned int'
  obj.serialize(a, a.version);
  ^
make[2]: *** [software/SfM/export/CMakeFiles/openMVG_main_openMVG2openMVS.dir/main_openMVG2openMVS.cpp.o] Error 1
make[2]: Target `software/SfM/export/CMakeFiles/openMVG_main_openMVG2openMVS.dir/build' not remade because of errors.
```

This is my cmake config line:
```bash
CC=gcc CXX=g++ ccmake -DCMAKE_INSTALL_PREFIX:STRING=$PWD/openMVG_install ../openMVG/src

$ gcc --version
gcc (MacPorts gcc5 5.5.0_4) 5.5.0
```
I simply commented out `MVG2openMVS`-related code and OpenMVG builds (GCC on Mac OS). I can look into it later. I need gcc5 as it provides some fast optimizations for a minimal problem code I am planning to contribute.

**Comment by pmoulon** [comment]
Thank you for the feedback.

GCC5 is building fine on Travis -> https://github.com/openMVG/openMVG/blob/master/.travis.yml#L32

I don't know what is happening on your platform but if you have a bit of time to fix it we will welcome it ;-)

**Comment by rfabbri** [comment]
OK,

So the fix was simple but I don't know what is the best way to commit into OpenMVG. In https://github.com/openMVG/openMVG/blob/606d1c9e82123dd50de282128151a50bf42262fc/src/software/SfM/export/InterfaceMVS.h#L223 
there is an explicit instantiation of `Load` for integral types, although it is used for `size_t` in serialization. But on Macs, for any compiler of interest (not just `clang` as in the code), size_t appears to be `unsigned long` while the previous instantiations for `uint32_t` and `uint64_t` expand to `unsigned` and `unsingned long long`, respectively, so `unsigned long` is missing. 

Many solutions work, but the question is which one is best for `OpenMVG`. 

1. The quick solution is to add an explicit instantiation ARCHIVE_DEFINE_TYPE(size_t), but will break platforms where the type is duplicate to some `uint`.
2. Use `std::is_same` or something from C++11, to avoid duplicate instantiation errors, but not sure yet how is this standard accepted in throughout OpenMVG.
3. Remove `#ifdef __clang__` on the aforementioned link to always explicit instantiate for `unsigned long` on Macs. Will have to watch Travis to see if this heuristic holds for all compilers of interest.
4. Simply cast every serialization of `size_t` to `uint64_t` when using `Load` or `Save` on a size value as in: https://github.com/openMVG/openMVG/blob/606d1c9e82123dd50de282128151a50bf42262fc/src/software/SfM/export/InterfaceMVS.h#L263

Option 4) might be more portable anyways - imagine another OS trying to de-serialize a `unsigned long long`.

This is all very simple, but care has to be taken since OpenMVG is widely used.

**Comment by pmoulon** [comment]
Thank you for the fix, I move the issue to be handled for the next release ;-)

**Comment by rfabbri** [comment]
The pull request fixing this issue seems to work. This issue will be closed automatically if the PR is accepted.

**Comment by pmoulon** [comment]
Yeah! Build is working https://travis-ci.org/openMVG/openMVG/builds/604771539

**Comment by pmoulon** [comment]
Solved by https://github.com/openMVG/openMVG/commit/a81c9f95b6d36ac2040aef29c65aa8ae3816d651
