### ISSUE TITLE
How to get the depthmaps of cubic images

### ISSUE THREAD

**Issue by wang9964** [openMVG/openMVG#1582]
Hi.
If I have the depthmap of spherical image, how can I get the depthmaps of cubic images created by main_openMVGSpherical2Cubic.
Thanks.

**Comment by pmoulon** [comment]
You can follow the instruction given here: https://github.com/openMVG/Image_datasets/tree/master/360_dataset
You can option dense point cloud/depth maps with OpenMVS -> `DensifyPointCloud `

**Comment by wang9964** [comment]
@pmoulon Thank you for your reply.  I mean I have the depth of every pixel of a spherical image, and I split the sphere to 6 pinhole images, and I want to get the depth of pinhole image from spherical depth. I try to sample the depth like shperical2cubic, but maybe I make some mistake.
This is my result, the corner of sphere:
![无标题](https://user-images.githubusercontent.com/37893895/62842486-3557f400-bce5-11e9-8905-e7bc4d56fee7.png)
Corresponding pinhole:
![image](https://user-images.githubusercontent.com/37893895/62842537-70f2be00-bce5-11e9-88b4-74998d271e12.png)

**Comment by wang9964** [comment]
I guess my pinhole camera model is wrong, I am trying another. When I have a good result, I will reply and close the issue.

**Comment by pmoulon** [comment]
You can use the existing sample and pick the depth from your depth map as we are doing to resample the RGB image.
You can resample a floating point image with this function:
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/image_spherical_to_cubic/main_pano_spherical_to_cubic.cpp#L48
Why do you think you have the wrong pinhole camera model (Are you not using OpenMVG code for this)?

**Comment by wang9964** [comment]
I found the reason that our depth is not from camera center to real world, and it is from surface of sphere, so It can't be used directly on cubic image.
Thank you very much, and I will close the issue.
