### ISSUE TITLE
how to provide  own cnn features descriptor and point to sfm.bin,and how to match them

### ISSUE THREAD

**Issue by vgg4resnet** [openMVG/openMVG#1583]
the cnn features seem to be more accurater than traditional feature descriptor sometimes,like super points,geodesc ,HPatches? is there any details  I have to pay attention to  when replacing  traditional descriptor ? And when matching pairs ,any difference from traditional descriptor 。do you  have that kind of interfaces?

**Comment by pmoulon** [comment]
OpenMVG is feature agnostic, I mean you can add your own descriptor and OpenMVG will be able to match them.

1. Add your feature/descriptor type in https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/regions_factory.hpp if your type does not exits
2. Implement your feature extractor that should inherit from ImageDescriber https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/image_describer.hpp#L30 (see SIFT, or AKAZE https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/akaze/image_describer_akaze.hpp)
3. Implement IO for the Interface https://github.com/openMVG/openMVG/blob/master/src/openMVG/features/akaze/image_describer_akaze_io.hpp
4. Use the describer in the ComputeFeature module (add your ImageDescriber instance)
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L189
5. If you want you can also test the repeatability and that your ImageDescriber is correct by using https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/features_repeatability/main_repeatability_dataset.cpp

**Comment by pmoulon** [comment]
@rjanvier and me would be happy to provide help on any PR for this

**Comment by vgg4resnet** [comment]
ok，thank you，I will try it

**Comment by pmoulon** [comment]
Any progress?
