### ISSUE TITLE
Questions about reconstructing a series of models

### ISSUE THREAD

**Issue by caokui1221** [openMVG/openMVG#1584]
Hello, @pmoulon ,
I plan to reconstruct a series of models(or called animation), like [ #1324](https://github.com/openMVG/openMVG/issues/1324#issue-328781707)  .
I have 5 cameras and fix their positions, then they record a moving target(eg. a dancing man) and get 5 synced sequence of images.  Regardless of the computational complexity , I will try to perform sfm on every frame. (MVG+MVS for frame 0 from all cameras, frame 1 from all cameras, etc.... ).
Firstly, I need to fix camera setup because BA will change the cameras position during every MVG(I hope I understand correctly).  So I took your advice in [#1415](https://github.com/openMVG/openMVG/issues/1415#issuecomment-435737478), this is what I did:
1. For frame 0 from all 5 cameras, I performed a full sfm and it worked well.   For frame 1 from all 5 cameras, I will use the intrinsics and camera poses which is calculated from sfm of frame0 , then just need to  triangulate and then the rest of reconstruction will be at the same location.
2. Convert the output file sfm_data.bin of the frame0 reconstruction to sfm_data.json uses `openMVG_main_ConvertSfM_DataFormat -i -V -I -E ` to keep the view, the intrinsics and the cameras pose.
3. Calculate features and matches of  frame 1 from all 5 cameras.
4. Call `openMVG_main_IncrementalSfM2 -i sfm_data.json -m  -o `, but the camera position in the output file sfm_data.bin is different from that of the frame0, so the model  is not aligned with the one reconstructed by frame0.
It is strange that, I called `openMVG_main_ComputeStructureFromKnownPoses` ,it works well, and the views, intrinsics and poses are same to the output of frame0.

What puzzles me is that:
1.  Why is there a problem while using SfMv2?Is the parameter setting incorrect？
2. Is there a better solution that can reduce the amount of computation ? If I perform MVS(dense→mesh→texture) for every MVG output , it will be very time-consuming. Can I use MVS+MVG to reconstruct a texture model from frame0, and then track the feature points of frame0 to complete the reconstruction of the subsequent model （such as optical flow）?Because there is continuity and similarity between frames of a video sequence.

Sorry for bad English, I will add details in time if you need.
Thanks for you time and help.

**Comment by caokui1221** [comment]
Hi, @pmoulon ,maybe I am not clear enough. I will add details immediately if you need.
Thank you again.

**Comment by caokui1221** [comment]
Hello, how is it going?

**Comment by pmoulon** [comment]
Sorry I was away for some weeks.

Here some comments:
1. `openMVG_main_IncrementalSfM2` is performing a bundle adjustment. But `openMVG_main_ComputeStructureFromKnownPoses` is not doing one by default https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeStructureFromKnownPoses.cpp#L98

You are right, it could be perhaps worth it to add a option to have more access towards what the BA will do (add option for REFINE_CAMERA_MOTION|REFINE_CAMERA_ROTATION)

2. Can you elaborate?
