### ISSUE TITLE
Camera rotation and Translation

### ISSUE THREAD

**Issue by fukexue** [openMVG/openMVG#1588]
Hello, what is the reference for the global rotation and translation of your code output through the SFM pipeline? Because I see that the rotation of the image of the first camera is not a unit array, and translation is not a zero vector. How can I translate it into rotation as a unit array and translation as a zero vector?

**Comment by fukexue** [comment]
Can the first camera coordinate system coincide with the world coordinate system when the SFM solution in this library is completed?

**Comment by caokui1221** [comment]
既然是武汉的，我就直接上中文吧...
BA会adjust整个场景，包括structure和camera，所以在BA之后，点云和相机的坐标就是“随机”的了。你可以在meshlab中看到世界坐标系在哪儿。如果想要对齐模型，可以写一个转换矩阵，把模型和相机移动到你想要的位置。

**Comment by pmoulon** [comment]
By default OpenMVG starts with a pair of camera and then add more images to the scene. On the first construction of the 3D point cloud, one camera will be identity but then the Bundle Adjustment can make the `reference` move from [Id|0].

If you want to fix back a given camera as [Id|0] you can do it by using https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_transform.hpp#L24 with a Similarity that will be the `pose.inverse()` of the camera that you want to keep as reference. We could add a tiny binary that would allow doing that with any reference view of the choice of the user.
