### ISSUE TITLE
SfM pipeline problem using GPS prior

### ISSUE THREAD

**Issue by zjbaby** [openMVG/openMVG#1589]
I've a set of UAV images with GPS information,  I can reconstruct a good 3D model without GPS information. but if I use the GPS information to geo-referenced, I get some problems:
**case (一)**、if I using the pipeline like that: 
(1) openMVG_main_SfMInit_ImageListing -P -i .. -o .. -d ..
(2) openMVG_main_ComputeFeatures -i .. -o ..
(3) openMVG_main_ListMatchingPairs -G -n 8 -i .. -o pair_list.txt
(4) openMVG_main_ComputeMatches -i .. -l pair_list.txt  -g e -o ..
(5) **openMVG_main_GlobalSfM -P** ...
(6) openMVG_main_openMVG2openMVS -i sfm_data.bin -o scene.mvs
(7) DensifyPointCloud -i scene.mvs
(8) ReconstructMesh -i scene_dense.mvs
(9) RefineMesh -i scene_dense_mesh.mvs
(10) TextureMesh
I run correcttly without throw error, but the result of step (7) is **much worse** than I don't use GPS information。

**case(二)**、if I using the pipeline like this: 
(1) openMVG_main_SfMInit_ImageListing -i .. -o .. -d ..
(2) openMVG_main_ComputeFeatures -i .. -o ..
(3) openMVG_main_ComputeMatches -i .. -o ..
(4) openMVG_main_IncrementalSfM ...
(5) **openMVG_main_geodesy_registration_to_gps_position** -i sfm_data.bin -o sfm_data_adjust.bin
(6) openMVG_main_openMVG2openMVS -i sfm_data_adjust.bin -o scene.mvs
(7) DensifyPointCloud -i scene.mvs
(8) ReconstructMesh -i scene_dense.mvs
(9) RefineMesh -i scene_dense_mesh.mvs
(10) TextureMesh
**I can get a better scene_dense.ply in step (7) than the model constructed by case (一),  but I get an error in step (8)**:
Cleaned mesh: 1267196 vertices, 2534049 faces
**terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc
Aborted(core dumped)**

I try to replace the step (8) with this command in case (二):
(8) ReconstructMesh -i scene_dense.mvs -d 4
I can run step (8) normally,  but the result of step (9) is mush worse than I don't use GPS information, and I encount an error in step (10):

**why and how to improve it**?

**Comment by gaoshuai** [comment]
@zjbaby interesting. I guess it is due to the poor GPS accuracy. Although GPS prior could reduce the matching computation and provide the absolute position, it couldn't impove BA result especially if the GPS accuracy is limited(RTK should be better). So with a poor POSE, it is doomed to a worse MVS result.

**Comment by zjbaby** [comment]
@gaoshuai 
Thank you for your apply, I see.

**Comment by zjbaby** [comment]
@gaoshuai 
Hi, I try another dataset that with better GPS accuracy(RTK used),  but I still get the same problems as I discribed in issue.
Can you give me some advice how to improve it,  thank you very much!

**Comment by whuaegeanse** [comment]
Take care of the coordinate system of the GPS of the images you imported.

**Comment by pmoulon** [comment]
Note that here you obtain the worst result on the MVS side.
MVS is not good when you are manipulating large coordinates. 
Did you have ever consider rescaling (downscale the scene and rescale it later just to see if you have the same issue)?

@zjbaby Can you report the statistics about the SfM to GPS fitting reported by openMVG_main_geodesy_registration_to_gps_position in both case (GPS and RTK)?
We should expect the RTK case to give a better fitting.
You should have some value exported after `3D Similarity fitting error`

**Comment by zjbaby** [comment]
> Take care of the coordinate system of the GPS of the images you imported.

My images' GPS coordinate system is WGS84

**Comment by zjbaby** [comment]
> Note that here you obtain the worst result on the MVS side.
> MVS is not good when you are manipulating large coordinates.
> Did you have ever consider rescaling (downscale the scene and rescale it later just to see if you have the same issue)?
> 
> @zjbaby Can you report the statistics about the SfM to GPS fitting reported by openMVG_main_geodesy_registration_to_gps_position in both case (GPS and RTK)?
> We should expect the RTK case to give a better fitting.
> You should have some value exported after `3D Similarity fitting error`

Thank you for your reply, I'll try the rescaling method later, And the reports as follows:
**A dataset with low accuracy GPS data, It's statistics:**
Registration report:
 #corresponding SFM - GPS data: 51

Found transform:
 scale: 40.1108
 rotation:
0.0492516 -0.929423  0.365715
-0.558749 -0.329141 -0.761226
 0.827873 -0.166851 -0.535525
 translation: -2265527.299719002  5014630.755799257  3214307.942628212

3D Similarity fitting error (in target coordinate system units):
	 min: 0.066378236
	 mean: 0.447843254
	 median: 0.412674099
	 max: 1.171266675

**And another dataset with with rtk-GPS，It's statistics:**
Registration report:
 #corresponding SFM - GPS data: 61

Found transform:
 scale: 133.869
 rotation:
 -0.895452   0.113941    0.43033
 -0.445144  -0.236951   -0.86354
0.00357448  -0.964817   0.262898
 translation: -2748790.594016611  5087161.319945565  2683114.909462790

3D Similarity fitting error (in target coordinate system units):
	 min: 0.003546894
	 mean: 0.034485910
	 median: 0.029679770
	 max: 0.106896721

**Comment by pmoulon** [comment]
The residual fitting looks good.

You can look this trick https://github.com/openMVG/openMVG/issues/1655 to rescale the scene before launching MVS

Closing due to lack of feedback
