### ISSUE TITLE
3D model construction known only ground-truth camera translation

### ISSUE THREAD

**Issue by simutk** [openMVG/openMVG#1591]
Hello,

if my question is strange, I apologize. And, I'm sorry for my poor English. I only know the ground-truth camera translation. Ground-truth camera rotation couldn't measure. In this case, is it possible to construct a good 3D model using only camera translation as known parameter?

**Comment by pmoulon** [comment]
By default OpenMVG does not have the mechanism to support GT camera translation.

But I see two way to hack around this:
- I would simulate the know GT translation by setting up this info as GPS prior to OpenMVG.
or
- Use Global SfM and add here a function to insert your known camera world position -> https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/global/sfm_global_engine_relative_motions.cpp#L137. So this way, global rotations would be computed and then your translation would be used as input for the next stage.
