### ISSUE TITLE
about Incremental SfM v2

### ISSUE THREAD

**Issue by CanCanZeng** [openMVG/openMVG#1595]
Hi @pmoulon , does SfM v2 only suite for large scale dataset? I tried SfM v1 and SfM v2 on my own dataset with 60 images, and found that v1 can reconstruct rather well while v2 produce a inferior result with less time. I use the revised script _SfM_SequentialPipeline.py_ provided in openMVG, the only difference is changing ` openMVG_main_IncrementalSfM` to ` openMVG_main_IncrementalSfM2`.
I used the released V1.5 windows binary.

Below is the screen shot of my result, the first one is produced by v1 and second is produced by v2.
![image](https://user-images.githubusercontent.com/26817559/63206246-59e80d80-c0e3-11e9-8d8f-4cad0b4f9c00.png)

![image](https://user-images.githubusercontent.com/26817559/63206251-91ef5080-c0e3-11e9-9ad2-beb74b67da74.png)

The green dot line is the camera positions, actually the trace produced by v1 is right and v2 seems to localize some image inaccurately.

More weird is that when I change the SIFT extraction option to HIGH, the result of v2 become even worse, see below
![image](https://user-images.githubusercontent.com/26817559/63206320-daf3d480-c0e4-11e9-9de8-06e05e0527b1.png)

So, where I did wrong?

_Originally posted by @CanCanZeng in https://github.com/openMVG/openMVG/issues/1241#issuecomment-522201567_

**Comment by pmoulon** [comment]
Hi,
Seems like some resection are done in a wrong way or BA is failing.

I would advise you to use `openMVG_main_IncrementalSfM2` if you have a nice idea about the camera internal parameter. Can you try this:
- Calibrate your camera using `openMVG_main_IncrementalSfM` then using the found camera parameter for `openMVG_main_IncrementalSfM2` (you can copy paste the camera details in the JSON file)
