### ISSUE TITLE
Question: measurements

### ISSUE THREAD

**Issue by Edward334** [openMVG/openMVG#1596]
Hi, I got a question: I have successfully created a 3D model (also textured it using openMVS). When I open the .ply model in Meshlab, I can use the measuring tool to get some sort of measurements in what I think is an arbitrary "unit" and I was wondering if there is any way of getting those measurements in feet or meters. 

I imagine that having the focal length in mm and in pixels should be enough... but I did not find anything in openMVG that addresses that. (not saying there isn't, I just didn't find it)

Thanks!

**Comment by whuaegeanse** [comment]
1. Use GPS from exif of images or from exterior pose file when creating SfM project.

- Make sure that the image has GPS information in EXIF；
- Using app named openMVG_main_SfMInit_ImageListing;

2. Use GCPs and it's observations projected in multiview images after performing SfM.

-Measure ground control points and their corresponding image point observations and perform  Ground Control Points registration using the corresponding software in openMVG.

**Comment by pmoulon** [comment]
focal length in mm is not enough.
Every SfM reconstruction is up to scale, so you need at least a known measurement to bring back the real scale (GPS, or known distance (GCP https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/ ))

FYI: This is due to the Essential Matrix decomposition, where you have a scale ambiguity for the translation.

**Comment by laitassou** [comment]
Hi,
I had the same question about making measurements from 3D model. But I have question about building 3D model from few (8 to 10 images) of house.
I tested using openMVG and open MVS but failed to to generate mesh 3D

Any help

**Comment by laitassou** [comment]
I have a general question:
is it possible to generate 3d model of house form few photos (8/10) using tools line openMVG, meshroom or other ?

Thank you

**Comment by pmoulon** [comment]
Photogrammetry unfortunately needs quite a lot of images to reconstruct an object.
For rescaling a model you can either rely on GPS position for your image, or add marker in your scene (more accurate), or rescale it with a known dimension by using GCP.

**Comment by laitassou** [comment]
Thank you pmoulon for answer, I just see that hover.tv builds 3D models of house using few images, do you think they use other techniques than photogrammetry ?
