### ISSUE TITLE
"Process Killed" for unknown reason {answer: lack of enough memory}

### ISSUE THREAD

**Issue by dcd2** [openMVG/openMVG#160]
Hi Pierre,

I'm working with a large dataset of approximately 600 images (6000x4000) taken from a Sony NEX-7. I get the following output after several hours:

 You called : 
/home/terra/OpenMVG_SourceAndBuild/software/SfM/openMVG_main_computeMatches
--imadir /home/terra/share240GB/sfm_input/Mines/6-20-2014/09h00m/
--outdir /home/terra/share240GB/sfm_output/matches
--distratio 0.6
--octminus1 0
--peakThreshold 0.04
--geometricModel f

EXTRACT FEATURES

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

---

Killed

What are the reasons for a openMVG_main_computeMatches to be "Killed"? Not enough memory? I've tried a run on a smaller set of imagery and it runs fine, and outputs as expected. Just curious why the error is occurring on the larger set.

**Comment by blackdeng** [comment]
Is there any recommended system specifications, for example, 4GB RAM can handle how many pictures with a certain size?
