### ISSUE TITLE
Quantitative evaluation of dense point clouds on DTU dataset

### ISSUE THREAD

**Issue by rann1018** [openMVG/openMVG#1600]
Hi, I got a problem. I complete openMVG and reconstruct dense point clouds using openMVS. I want to evaluate the accuracy of these points on DTU dataset. However, I found that the provided Matlab code by DTU dataset cannot give a result because the scale of the point clouds is totally different. The scale of openMVG is pretty small. Can you give me some advice to solve the problem?
Thanks a lot!

**Comment by pmoulon** [comment]
You can provide the GT DTU camera position to OpenMVS by using the OpenMVG DTU dataset importer https://github.com/openMVG/openMVG/blob/master/src/software/SfM/import/main_SfMInit_ImageListingFromKnownPoses.cpp#L79 or else if you need SfM I would advise you to run a rescaling either of the OpenMVG camera poses or the OpenMVS output by computing a similarity between the openMVG camera trajectory and the real camera poses. See here how to compare two corresponding camera trajectories https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_evalQuality.cpp#L160

**Comment by rann1018** [comment]
> You can provide the GT DTU camera position to OpenMVS by using the OpenMVG DTU dataset importer https://github.com/openMVG/openMVG/blob/master/src/software/SfM/import/main_SfMInit_ImageListingFromKnownPoses.cpp#L79 or else if you need SfM I would advise you to run a rescaling either of the OpenMVG camera poses or the OpenMVS output by computing a similarity between the openMVG camera trajectory and the real camera poses. See here how to compare two corresponding camera trajectories https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_evalQuality.cpp#L160

Thanks a lot for your reply. I have successfully loaded DTU dataset scan1 and rebuilt the sparse and dense point clouds. However, I found that the recovering points are not accurate and I dont know why. 
I use the following commands pipeline:
1 openMVG_main_SfMInit_ImageListingFromKnownPoses 
2 openMVG_main_ComputeFeatures
3 openMVG_main_ComputeMatches
4 openMVG_main_ComputeStructureFromKnownPoses
5 openMVG_main_openMVG2openMVS
6 DensifyPointCloud 
Is there anything wrong or if I need to add some extra steps? Looking forwards to your suggestion.
Thanks again!

**Comment by pmoulon** [comment]
What do you mean by inaccurate,can you elaborate?

I would recommend you to call the mesh tool of OpenMVS `ReconstructMesh` and optionally`RefineMesh` in order to see a mesh and not a point cloud (noise will be reduced)

**Comment by raphaelsulzer** [comment]
Hi,

I am also working with the DTU dataset right now and am running into problems.
After looking at the corresponding implementation at https://github.com/openMVG/openMVG/blob/master/src/software/SfM/import/io_readGTDTUMVS.hpp
I am not sure if the ground truth poses provided in DTU folder SampleSet/MVS Data/Calibration/cal18/pos_00X.txt are correctly parsed into the sfm_data.json file.

Initially they are loaded into std::vector<cameras::PinholeCamera> cameras_data_ correctly, but then in the LoadImages there are other poses parsed to the SfM_Data sfm_data_ object (which is eventually parsed to the sfm_data.json file).

Can you confirm that this is really correct?

E.g. camera 0 should have pose

  2607.43   -3.8449   1498.18   -533937
 -192.077   2862.55   681.798   23434.7
-0.241605 -0.030951  0.969881   22.5401

but ends up with the following pose in the sfm_data.json file (for which I am not yet sure where it is coming from):

    "extrinsics": [
        {
            "key": 0,
            "value": {
                "rotation": [
                    [
                        0.9702626846754227,
                        0.00747991117225925,
                        0.2419387808006323
                    ],
                    [
                        -0.014742870234980426,
                        0.9994929147415034,
                        0.02822341507983126
                    ],
                    [
                        -0.24160498857365474,
                        -0.030950998536218988,
                        0.9698809541309361
                    ]
                ],
                "center": [
                    190.8334619493169,
                    -1.1601863796148245,
                    24.26100588178266
                ]
            }
        }

**Comment by pmoulon** [comment]
DTU pose show projection matrices P = K[R|t] if I remember well, so once you take out K that will be the intrinsic calibration matrice and so defined in the PinholeCamera focal length and the principal point I believe we have the right camera position. Note also that `t = -RC`

Tip: You can also use ConvertSfmDataFormat and set for output `-o test.ply` to see if the camera positions are correct.

**Comment by raphaelsulzer** [comment]
Indeed that was my misunderstanding. Everything is working as it should. Thanks for the explanation and the extra tip and sorry for doubting :)

**Comment by pmoulon** [comment]
No worries, it is always good to check and now you know one more capability of the tool ;-) (SfM_data to PLY)
