### ISSUE TITLE
Errors while running CTest

### ISSUE THREAD

**Issue by qixiaomu77** [openMVG/openMVG#1601]
94% tests passed, 5 tests failed out of 83

Total Test time (real) =  21.46 sec

The following tests FAILED:
	 73 - openMVG_test_sfm_data_BA (SEGFAULT)
	 78 - openMVG_test_global_SfM (SEGFAULT)
	 79 - openMVG_test_sequential_SfM (SEGFAULT)
	 80 - openMVG_test_sequential_SfM2 (SEGFAULT)
	 81 - openMVG_test_stellar_SfM (SEGFAULT)

**Comment by pmoulon** [comment]
Probably related to your ceres. Can you force to use the internal one from the Cmakelist.Txt  by removing the line find_package (ceres) to test this hypothesis.

**Comment by qixiaomu77** [comment]
i try to change ceres,but it doesn't work.
-- CEREAL: (internal)
-- EIGEN:  (external)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.6 (external)
-- LIBPNG: 1.2.54 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)

Total Test time (real) =  23.06 sec

The following tests FAILED:
	 73 - openMVG_test_sfm_data_BA (SEGFAULT)
	 78 - openMVG_test_global_SfM (SEGFAULT)
	 79 - openMVG_test_sequential_SfM (SEGFAULT)
	 80 - openMVG_test_sequential_SfM2 (SEGFAULT)
	 81 - openMVG_test_stellar_SfM (SEGFAULT)

**Comment by pmoulon** [comment]
Can you try do the same with Eigen?
Be sure to compile from scratch.

Can you tell more about which platform you are using?

**Comment by qixiaomu77** [comment]
the platform is ubuntu16.04

**Comment by qixiaomu77** [comment]
when i write the cmake --build . --target install sentence,it get error  1. Someone said it doesn't matter, is it true?

[100%] Building CXX object software/SfMWebGLViewer/CMakeFiles/openMVG_main_openMVG2WebGL.dir/openMVG_main_openMVG2WebGL.cpp.o
[100%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_main_openMVG2WebGL
[100%] Built target openMVG_main_openMVG2WebGL
Install the project...
-- Install configuration: "RELEASE"
-- Up-to-date: /usr/local/include/openMVG_dependencies
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot set permissions on
  "/usr/local/include/openMVG_dependencies"


Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by qixiaomu77** [comment]
i  try do the same with eigen ,it success.thank you

100% tests passed, 0 tests failed out of 83

**Comment by pmoulon** [comment]
So the conflict was certainly about using an external ceres that have been compiled with a different Eigen version.

Regarding the install target. Installation requires admin/sudo rights.
If you want install without sudo you still can, but you will have to install in a non-system folder by using `DCMAKE_INSTALL_PREFIX:STRING ` in the cmake command line as explained here https://github.com/openMVG/openMVG/blob/master/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake

**Comment by qixiaomu77** [comment]
Does ceres has anything with Eigen? I am a new guy.So I have many things that I don't understand. Thank you.

**Comment by pmoulon** [comment]
Yes, Ceres is using Eigen for matrix manipulation and some linear algebra.
See http://ceres-solver.org/installation.html#dependencies
