### ISSUE TITLE
3-D Point Cloud Data

### ISSUE THREAD

**Issue by Rahma-15** [openMVG/openMVG#1604]
Hi,

I am trying to find where the 'structure' file containing the 3-D point cloud is stored after reconstruction is done in SfM pipeline. 
Also is there a way to display the 3-D ply file WITH the coordinates ?
Any help will be appreciated !

**Comment by pmoulon** [comment]
The `structure` or point cloud is stored in the sfm_data.bin file.
The PLY version can be exported by using `ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data.ply`

You can also export the data to JSON using `ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data.json` load it with the PYTHON and display the 3d structure with the app of your choice.

For coordinates, there is not easy way, you can try CLOUD COMPARE that allow you to do point picking and it will display the 3d coordinates of the picked point.
