### ISSUE TITLE
Cannot build openMVG as a Windows Dynamic Library (DLL)

### ISSUE THREAD

**Issue by dumom01** [openMVG/openMVG#1605]
Is there any plan to support build for Windows as a dynamic library?
Did you ever try, or do you have any clue to help us?
Thank you

**Comment by pmoulon** [comment]
Yes, building openMVG in shared mode is possible. See OpenMVG_BUILD_SHARED https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L20

**Comment by dumom01** [comment]
But, there is no dllexport (or DEF file)?

**Comment by pmoulon** [comment]
You should have the dll files in the build folder
