### ISSUE TITLE
Best practice to keep images in memory for an sfm_data or sfm_view structure

### ISSUE THREAD

**Issue by dzermas** [openMVG/openMVG#1606]
Thank you for all the work you guys have put into this library.

I am wondering what is the best way to hold the images in memory instead of reading them from disk every time they are needed. My project's input is a video stream and I generate keyframes using optical flow to achieve a good baseline between my keyframes. The goal is to have a near real-time SfM prototype.

I noticed that the ```sfm_view.hpp``` structure has a 
```
// image path on disk
std::string s_Img_path;
```
but no actual image container.

What needs to be added for a compatible ```sfm_view_in_memory.hpp``` structure to look like this:
```
struct ViewInMemory
{
  // image in memory
  image::Image<unsigned char> in_memory_image;

  // Id of the view
  IndexT id_view;

  // Index of intrinsics and the pose
  IndexT id_intrinsic, id_pose;

  // image size
  IndexT ui_width, ui_height;

  // Constructor (use unique index for the view_id)
  View(
    const image::Image<unsigned char> & image_in_memory = <something default>,
    IndexT view_id = UndefinedIndexT,
    IndexT intrinsic_id = UndefinedIndexT,
    IndexT pose_id = UndefinedIndexT,
    IndexT width = UndefinedIndexT, IndexT height = UndefinedIndexT)
    :in_memory_image(image_in_memory), id_view(view_id), id_intrinsic(intrinsic_id),
    id_pose(pose_id), ui_width(width), ui_height(height)
    {}

  virtual ~View() = default;

  /**
  * Serialization out
  * @param ar Archive
  */
  template <class Archive>
  void save( Archive & ar ) const;

  /**
  * @brief Serialization in
  * @param ar Archive
  */
  template <class Archive>
  void load( Archive & ar );
};
```

**Comment by pmoulon** [comment]
I would use a cache.

OpenMVG can use a cache for the features. See https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sfm_regions_provider_cache.hpp

Perhaps you your reuse this.
The best design I would recommend is to add a `View_Provider` class and then add a `View_Provider_Cache`.

Here some tips:
- Are you aware of those experiments: https://github.com/openMVG/openMVG/tree/master/src/software/VO

- Also if you want help OpenMVG on this, first test the video matching mode, then help us to implement a window based BA.

**Comment by dzermas** [comment]
@pmoulon Thank you for the reply. 

I am not familiar with openMVG enough to be confident in creating a ```View_Provider``` class that will be acceptable for the project.

I plan on starting by testing your OpenCV KLT tracker while saving the keyframes on disk. 

Extracting features, constructing matches, even creating tracks from matches will be a good introduction.

I will be closing the issue till I get some progress on this topic. Thanks!

**Comment by pmoulon** [comment]
Thank you for your feedback. Feel free to post here any progress, comments, questions ;-)
