### ISSUE TITLE
Illegal while running Ctest

### ISSUE THREAD

**Issue by 1liza** [openMVG/openMVG#1607]
7% tests passed, 77 tests failed out of 83

Total Test time (real) =   8.80 sec

The following tests FAILED:
	  1 - openMVG_test_Camera_Pinhole (ILLEGAL)
	  2 - openMVG_test_Camera_Pinhole_Radial (ILLEGAL)
	  3 - openMVG_test_Camera_Pinhole_Brown (ILLEGAL)
	  4 - openMVG_test_Camera_Pinhole_Fisheye (ILLEGAL)
	  5 - openMVG_test_Camera_Spherical (ILLEGAL)
	  6 - openMVG_test_Camera_Subset_Parametrization (ILLEGAL)
	  7 - openMVG_test_Camera_IO (ILLEGAL)
	  8 - openMVG_test_kmeans (ILLEGAL)
	  9 - openMVG_test_exif_IO (ILLEGAL)
	 10 - openMVG_test_ParseDatabase (ILLEGAL)
	 11 - openMVG_test_features (ILLEGAL)
	 12 - openMVG_test_image_describer (ILLEGAL)
	 13 - openMVG_test_akaze (ILLEGAL)
	 14 - openMVG_test_mser (ILLEGAL)
	 15 - openMVG_test_sift (ILLEGAL)
	 16 - openMVG_test_tbmr (ILLEGAL)
	 17 - openMVG_graph_test_connectedComponent (ILLEGAL)
	 19 - openMVG_test_image (ILLEGAL)
	 20 - openMVG_test_image_drawing (ILLEGAL)
	 21 - openMVG_test_image_integral (ILLEGAL)
	 22 - openMVG_test_image_io (ILLEGAL)
	 23 - openMVG_test_image_filtering (ILLEGAL)
	 24 - openMVG_test_image_resampling (ILLEGAL)
	 25 - openMVG_test_linearProgramming (ILLEGAL)
	 26 - openMVG_lInftyCV_test_triangulation (ILLEGAL)
	 27 - openMVG_lInftyCV_test_resection (ILLEGAL)
	 28 - openMVG_lInftyCV_test_resection_robust (ILLEGAL)
	 29 - openMVG_lInftyCV_test_global_translations_fromTriplets (ILLEGAL)
	 30 - openMVG_lInftyCV_test_global_translations_fromTij (ILLEGAL)
	 31 - openMVG_lInftyCV_test_tijsAndXis (ILLEGAL)
	 32 - openMVG_lInftyCV_test_tijsAndXis_outlier (ILLEGAL)
	 33 - openMVG_geodesy_test_geodesy (ILLEGAL)
	 34 - openMVG_test_convex_hull (ILLEGAL)
	 35 - openMVG_test_rigid_transformation3D_srt (ILLEGAL)
	 36 - openMVG_test_plane_estimation_kernel (ILLEGAL)
	 37 - openMVG_test_half_space_intersection (ILLEGAL)
	 38 - openMVG_test_frustum_intersection (ILLEGAL)
	 39 - openMVG_test_frustum_box_intersection (ILLEGAL)
	 40 - openMVG_test_matching (ILLEGAL)
	 41 - openMVG_test_matching_filters (ILLEGAL)
	 42 - openMVG_test_indMatch (ILLEGAL)
	 43 - openMVG_test_metric (ILLEGAL)
	 45 - openMVG_test_triangulation (ILLEGAL)
	 46 - openMVG_test_triangulation_nview (ILLEGAL)
	 47 - openMVG_test_solver_affine (ILLEGAL)
	 48 - openMVG_test_solver_essential_eight_point (ILLEGAL)
	 49 - openMVG_test_solver_essential_five_point (ILLEGAL)
	 50 - openMVG_test_solver_essential_three_point (ILLEGAL)
	 51 - openMVG_test_solver_fundamental_kernel (ILLEGAL)
	 52 - openMVG_test_solver_homography_kernel (ILLEGAL)
	 53 - openMVG_test_solver_resection_kernel (ILLEGAL)
	 54 - openMVG_test_solver_translation_knownRotation_kernel (ILLEGAL)
	 55 - openMVG_test_rotation_averaging (ILLEGAL)
	 56 - openMVG_test_translation_averaging (ILLEGAL)
	 57 - openMVG_test_extract_columns (ILLEGAL)
	 58 - openMVG_test_numeric (ILLEGAL)
	 59 - openMVG_test_poly (ILLEGAL)
	 60 - openMVG_test_lm (ILLEGAL)
	 61 - openMVG_test_l1_solver (ILLEGAL)
	 62 - openMVG_test_rand_sampling (ILLEGAL)
	 63 - openMVG_test_robust_estimator_lineKernel (ILLEGAL)
	 64 - openMVG_test_robust_estimator_MaxConsensus (ILLEGAL)
	 65 - openMVG_test_robust_estimator_Ransac (ILLEGAL)
	 66 - openMVG_test_robust_estimator_ACRansac (ILLEGAL)
	 67 - openMVG_test_gms_filter (ILLEGAL)
	 68 - openMVG_test_tracks (ILLEGAL)
	 70 - openMVG_test_global_quantile_gain_offset_alignment (ILLEGAL)
	 71 - openMVG_test_progress (ILLEGAL)
	 72 - openMVG_test_sfm_data_io (ILLEGAL)
	 73 - openMVG_test_sfm_data_BA (ILLEGAL)
	 74 - openMVG_test_sfm_data_utils (ILLEGAL)
	 75 - openMVG_test_sfm_data_filters (ILLEGAL)
	 77 - openMVG_test_sfm_data_triangulation (ILLEGAL)
	 78 - openMVG_test_global_SfM (ILLEGAL)
	 79 - openMVG_test_sequential_SfM (ILLEGAL)
	 80 - openMVG_test_sequential_SfM2 (ILLEGAL)
	 81 - openMVG_test_stellar_SfM (ILLEGAL)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8

-- CEREAL: (internal)
-- EIGEN: 3.3.4 (internal)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.6 (external)
-- LIBPNG: 1.2.54 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)

** OpenMVG version: 1.5.0
** Build Shared libs: OFF
** Build OpenMVG tests: ON
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF

Ubuntu 16.4 amd64
cmake 3.5.1

There is no error when build or install, why it shows illegal, I did exactly as BUILD shows.
I'm new using Ubuntu and Cmake, and has been stuck for days
Really need some help and really thankful!!!!!

**Comment by pmoulon** [comment]
Thx you for sharing the cake output.

I think about two potential issue:
- a bad compiler optimization for your platform
- an issue with multiple libraries

Can you try to comment this line https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L103 and build again from scratch?

**Comment by pmoulon** [comment]
Closing due to lack of feedback?
Feel free to re-open.
