### ISSUE TITLE
How to do sfm with GPU

### ISSUE THREAD

**Issue by takumi0628** [openMVG/openMVG#1611]
I can do sfm with CPU. But I want to do use GPU if I can.
So I want to tel me about two things.
1, Whether the GPU can be used in sfm.
2, If I can use GPU, I want to tell me how to set cmake.

**Comment by pmoulon** [comment]
GPU is not used by default in OpenMVG but you can easily add your own GPU code to it if you want.
Here are the stage where you could think about plugging existing GPU code:
- Feature extraction (using -n <NB_THREAD> on main_ComputeFeatures is always quite fast already)
- Feature matcher (but Cascade Hashing could be faster than Brute Force GPU matching)
- Bundle Adjustment method (See "Multicore Bundle Adjustment for GPU and CPU" - GPL license)

GPU for the other stages (resection, ransac, tracking) is not commonly ported to GPU.
