### ISSUE TITLE
ComputeFeatures's Mask doesn't work well

### ISSUE THREAD

**Issue by yuyabu** [openMVG/openMVG#1615]
I try to mask option of ConputeFeatures.

https://openmvg.readthedocs.io/en/latest/software/SfM/ComputeFeatures/

I want to delete some part of castle in 3D files.
 but it doesn't work well.

I prepared openMVG's sample castle photos and mask images.

![image](https://user-images.githubusercontent.com/23971274/66980515-1d895b80-f0ec-11e9-8f00-77f696ac5499.png)

https://github.com/yuyabu/openMVG_mask_sample/tree/master/input

Looking at the stdout log, the prepared mask image seems to be used,

```
Warning & Error messages:
100_7100_mask.png is a mask image
100_7101_mask.png is a mask image
100_7102_mask.png is a mask image
100_7103_mask.png is a mask image
100_7104_mask.png is a mask image
100_7105_mask.png is a mask image
100_7106_mask.png is a mask image
100_7107_mask.png is a mask image
100_7108_mask.png is a mask image
100_7109_mask.png is a mask image
100_7110_mask.png is a mask image
```
 
but in the final output 3D file, 
the part I wanted to mask was not masked.

here is result

![image](https://user-images.githubusercontent.com/23971274/66980456-efa41700-f0eb-11e9-8d82-4dcc3b4c4c9b.png)

https://github.com/yuyabu/openMVG_mask_sample/tree/master/result/mvs

I use these commands and parameters

```
$LIB/openMVG/bin/openMVG_main_SfMInit_ImageListing -i $WORK_DIR/input -o $WORK_DIR/result/matches -d /home/yabushita/psc/conf/sensor_width_camera_database.txt
$LIB/openMVG/bin/openMVG_main_ComputeFeatures -i $WORK_DIR/result/matches/sfm_data.json -o $WORK_DIR/result/matches  -f 1 
$LIB/openMVG/bin/openMVG_main_ComputeMatches -i $WORK_DIR/result/matches/sfm_data.json -o $WORK_DIR/result/matches -f 1
$LIB/openMVG/bin/openMVG_main_IncrementalSfM2 -i $WORK_DIR/result/matches/sfm_data.json -m $WORK_DIR/result/matches -o $WORK_DIR/result/reconstruction_sequential
$LIB/openMVG/bin/openMVG_main_openMVG2openMVS -d $WORK_DIR/tmp/undistorted_images -i $WORK_DIR/result/reconstruction_sequential/sfm_data.bin -o $WORK_DIR/result/mvs/scene.mvs
$BUILD_DIR/openMVS_with_eigin_latest/bin/DensifyPointCloud -w $WORK_DIR/tmp $WORK_DIR/result/mvs/scene.mvs 
$BUILD_DIR/openMVS_with_eigin_3.2/bin/ReconstructMesh -w $WORK_DIR/tmp $WORK_DIR/result/mvs/scene_dense.mvs 
$BUILD_DIR/openMVS_with_eigin_3.2/bin/TextureMesh -w $WORK_DIR/tmp  $WORK_DIR/result/mvs/scene_dense_mesh.mvs
```

full is in `script.sh` int that repository(becaouse of avoid some library(eigan,openMP etc) issue, I use `LIB`,`BUILD_DIR` varriable.)

Please let me know if there is anything missing from commands or options or files etc regarding mask.

**Comment by happyfrank** [comment]
ComputeFeatures's Mask just for extructing image features. Not for reconstruction 3D mesh(openMVS).
You can see this [issue](https://github.com/cdcseacave/openMVS/issues/144) for the detail.

**Comment by yuyabu** [comment]
@happyfrank 

thanks.
I'm sorry for my poor survey.

It seems that openMVS is not support for masking, 
and I checked my openMVG's output, the part I want to mask was completely masked.

![image](https://user-images.githubusercontent.com/23971274/66996619-035f7580-f10c-11e9-99eb-051c8533f93c.png)


I check openMVS.
thanks.
