### ISSUE TITLE
Can't find Ground control points gui

### ISSUE THREAD

**Issue by Rahma-15** [openMVG/openMVG#1616]
Hi i am using windows 10, I built openMVG in cmake, it seems to have everything else but I am having trouble finding the GCP gui. The release folder doesn't have it. 
Alternatively if there is any other tool for me to scale my 3-D model manually or otherwise please let me know. Appreciate any help !

**Comment by pmoulon** [comment]
You need QT installed in order to be sure that OpenMVG will build the UI tool and the GCP ui.
- Do you have QT installed?

To rescale a model you can use Meshlab or CloudCompare.

**Comment by rockokw** [comment]
Hmmm, for future travelers, I found two GUIs:
**openMVG_sample_describe_and_match_GUI
ui_openMVG_control_points_registration**

**Comment by Rahma-15** [comment]
**Hi, i finally got around to installing QT 5.4.1 and rebuilding in Cmake and Visual studio.

Cmake output:**

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
The C compiler identification is MSVC 19.16.27032.1
The CXX compiler identification is MSVC 19.16.27032.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
target changed from "" to "auto"
Detected CPU: sandy-bridge
Performing Test check_c_compiler_flag__arch_AVX
Performing Test check_c_compiler_flag__arch_AVX - Success
Performing Test check_cxx_compiler_flag__arch_AVX
Performing Test check_cxx_compiler_flag__arch_AVX - Success
Checking for C++11 compiler
Checking for C++11 compiler - available
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
CMake Warning (dev) at CMakeLists.txt:252 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Eigen_ROOT is set to:

    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
Flann 1.8.4 found (include: C:/Users/rnawab/Desktop/openMVG_DIR/openMVG/src/third_party/flann/src/cpp/flann)
CoinUtils 2.10.13 found (include: C:/Users/rnawab/Desktop/openMVG_DIR/openMVG/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.16.10 found (include: C:/Users/rnawab/Desktop/openMVG_DIR/openMVG/src/dependencies/osi_clp/Clp/src)
You are attempting to build without Osi. Please use cmake variable -DOSI_INCLUDE_DIR_HINTS:STRING="PATH" or OSI_INCLUDE_DIR_HINTS env. variable to a valid Osi path. Or install last Osi version.
Lemon  found (include: C:/Users/rnawab/Desktop/openMVG_DIR/openMVG/src/third_party/lemon/lemon)
Found PythonInterp: C:/Users/rnawab/AppData/Local/Programs/Python/Python37/python.exe (found version "3.7.4") 
Could NOT find Wget (missing: WGET_EXECUTABLE) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE) 
Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of long long
Check size of long long - done
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Looking for stdlib.h
Looking for stdlib.h - found
Looking for assert.h
Looking for assert.h - found
Looking for fcntl.h
Looking for fcntl.h - found
Looking for io.h
Looking for io.h - found
Looking for jbg_newlen
Looking for jbg_newlen - not found
Looking for mmap
Looking for mmap - not found
Looking for search.h
Looking for search.h - found
Looking for string.h
Looking for string.h - found
Looking for unistd.h
Looking for unistd.h - not found

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
Detected Ceres version: 1.13.0 from C:/Users/rnawab/Desktop/openMVG_DIR/openMVG/src/third_party/ceres-solver/include/ceres/version.h
CMake Warning (dev) at third_party/ceres-solver/CMakeLists.txt:112 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/ceres-solver/CMakeLists.txt:180 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Eigen_ROOT is set to:

    C:\Users\rnawab\Downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Eigen 3.2.10 found (include: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8)
-- Found Eigen version 3.2.10: C:/Users/rnawab/Downloads/eigen-eigen-b9cd8366d4e8/eigen-eigen-b9cd8366d4e8

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

Looking for sgemm_
Looking for sgemm_ - not found
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
-- Did not find LAPACK library, disabling LAPACK support.
-- Did not find BLAS library, disabling LAPACK support.
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
Performing Test COMPILER_HAS_CXX11_FLAG
Performing Test COMPILER_HAS_CXX11_FLAG - Success
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Performing Test HAVE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS
Performing Test HAVE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS - Success
Creating configured Ceres config.h output directory: C:/Users/rnawab/Desktop/openMVG_DIR/build_openMVG/third_party/ceres-solver/config/ceres/internal
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================

Configured Eigen 3.3.4

** Found Qt5, GUI modules will be build
Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation


** OpenMVG version: 1.5.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


CEREAL: (internal)
EIGEN: 3.2.10 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)


Configuring done
Generating done

**I then built the solution in visual studio however i still can't find Ground Control Points gui.**

Appreciate any help !

**Comment by Rahma-15** [comment]
In visual Studio i get these errors while building:

fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_features.lib
fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_geometry.lib
fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_multiview.lib
etc,

I am not sure why this is happening
