### ISSUE TITLE
2D Coordinates?

### ISSUE THREAD

**Issue by tkhan1994** [openMVG/openMVG#1621]
Hi,

I used openMVG a while ago for a project (3d reconstruction) and have not been using lately.
I noticed that the resulting sfm_data.json file contains the corresponding 2D coordinates for
3D points in the cloud. Why are those coordinates in decimals? How can I get the pixel in the
original image using those decimal values?

Thanks

**Comment by pmoulon** [comment]
Coordinates are stored in the original image resolution. They are decimal since feature points are detected with subpixel accuracy.

**Comment by tkhan1994** [comment]
What would be the best way of rounding them to get the underlying pixel?

**Comment by pmoulon** [comment]
Since subpixel coordinates move a point in a [-0.5;+0.5] range, I would just cast the value from floating point to int.
