### ISSUE TITLE
[multiview] 2 View triangulation

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1623]
- [x] Add more 2 view triangulation routines
  - `Triangulation: Why Optimize?` - BMVC 2019
    - [x] Optimal LInfinity Angular triangulation
    - [x] Optimal L1 Angular triangulation
  - `Closed-Form Optimal Triangulation Based on Angular Errors` - ICCV19
    - [x] Inverse Depth Weighted Midpoint method
- [x] Add unit test

- [x] Refactor the 2 view triangulation routines to use the same parameters and ease usage of each method in the SfM pipeline

- [ ] Benchmark the generic routine (time, #points, ..)
  - [x] Added a time to ComputeStructureFromKnowPoses

- [x] Use the new generic routine in the SfM pipelines
  - [x] openMVG/sfm/sfm_data_triangulation.cpp
  - [x] openMVG/sfm/pipelines/sequential/sequential_SfM.cpp
  - [x] ...

- [x] Make the 2view triangulation solver customizable from the command line

- [x] Update Sphinx doc with paper references

Thx you @rjanvier for your contribution to this.

**Comment by pmoulon** [comment]
@rjanvier Feel free to review https://github.com/openMVG/openMVG/commit/39fa4250eeea4ff09fdc1747feb5268693d99453

**Comment by rjanvier** [comment]
I leave a few comments on the last commit. Maybe we should test the case were cheirality is not ok. What do you think?

**Comment by pmoulon** [comment]
Cheirality is now checked for every 2view solver, with various method but at least we have a test.

**Comment by rjanvier** [comment]
Yes, I agree but my point was to provide a test case were cheirality is not ok in **unitary test**, sorry for the lack of accuracy in my wording.

**Comment by pmoulon** [comment]
@rjanvier you can now use the various 2view triangulation algorithm from the command line; see https://github.com/openMVG/openMVG/commit/2243f3875e7de8e710aeed9161a433ad976cfadc#diff-9a318b755e5ca96f84fe6df73d503cdcR98

The customization is available for the sequential SfM engine and for ComputeStructureFromKnownPoses ;-)

**Comment by rjanvier** [comment]
thanks a lot @pmoulon. I made two additionals comments. I will test this integration this WE. I think we can also replace DLT triangulation in other places (relative structure from motion) or at least add the cheirality test here (https://github.com/openMVG/openMVG/blob/2bf6e0822229c17494a1ef2277e08fa5bed7f986/src/openMVG/sfm/pipelines/relative_pose_engine.cpp#L172). What do you think?

**Comment by pmoulon** [comment]
@rjanvier We are getting quite close. The new generic routine is now used everywhere.

**Comment by happyfrank** [comment]
Dear @pmoulon and @rjanvier, thanks for provide this useful feature. I have a question.For your testing,

**Comment by happyfrank** [comment]
Dear @pmoulon and @rjanvier, thanks for providing this useful feature. I have a question. For your testing. which trangulation method is better for 360 images. 0.0

**Comment by rjanvier** [comment]
Hi @happyfrank. Thank you for your interest. From short experiments we run for now, I would suggest to use LinfinityAngular for pure 360 datasets, but IDW should be fine too. From a general point of view, do not expect so much differences between methods.  I would only suggest to avoid using L1Angular because it has the poorest behavior under the L2 reprojection error which is used in many places of the pipelines (BA, triangulation validation). Happy testing, do not hesitate to report back your own experiments here.

**Comment by pmoulon** [comment]
@happyfrank Thank you for your comment.
- This feature branch bring new state of the art Triangulation method, but it also bring more abstraction to OpenMVG. The main consequence is that we will have faster triangulation routines  and let more space to the community to test new triangulation method with ease on large SfM scene.

**Comment by happyfrank** [comment]
Dear @pmoulon and @rjanvier That's all right. Thank you very much. ^v^
