### ISSUE TITLE
Failed to run openMVG_main_IncrementalSfM on MacOS Catalina

### ISSUE THREAD

**Issue by punkyzhu** [openMVG/openMVG#1624]
Hi,
I am running openMVG on MacOS Catalina, the latest version of the MacOS. Unfortunately, I always got errors when running "openMVG_main_IncrementalSfM" command using dataset of SceauxCastle. The output was like the following:

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*[1]    94088 segmentation fault  ./openMVG_main_IncrementalSfM -i  -m  -o 

Usually "segmentation fault" would be a serious problem regarding memory invoking, I guess. Does anyone get this situation before? And any suggestions on this issue?

Thanks in advance.

**Comment by pmoulon** [comment]
Can you share your cmake config output?
I would like to see if you are using an internal or external Ceres.

**Comment by punkyzhu** [comment]
Hi, pmoulon,

I'm out of my office right now. The entire cmaking process can only be recalled on my office desktop machine. But I did all cmaking procedure just following the BUILD.md doc, and all procedure was very smooth without any errors. 

I will pose the cake config output on Monday when I'm back to my working machine. 

Thanks for your quick response.

**Comment by punkyzhu** [comment]
hi, pmoulon,

This is the output while done the config procedure:

-----------------------------------
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
clang detected: using std::unordered_map for Hash_Map
-- target changed from "" to "auto"
-- Detected CPU: ivy-bridge
-- Performing Test check_c_compiler_flag__march_ivybridge
-- Performing Test check_c_compiler_flag__march_ivybridge - Success
-- Performing Test check_cxx_compiler_flag__march_ivybridge
-- Performing Test check_cxx_compiler_flag__march_ivybridge - Success
-- Performing Test check_c_compiler_flag__msse2
-- Performing Test check_c_compiler_flag__msse2 - Success
-- Performing Test check_cxx_compiler_flag__msse2
-- Performing Test check_cxx_compiler_flag__msse2 - Success
-- Performing Test check_c_compiler_flag__msse3
-- Performing Test check_c_compiler_flag__msse3 - Success
-- Performing Test check_cxx_compiler_flag__msse3
-- Performing Test check_cxx_compiler_flag__msse3 - Success
-- Looking for C++ include pmmintrin.h
-- Looking for C++ include pmmintrin.h - found
-- Performing Test check_c_compiler_flag__mssse3
-- Performing Test check_c_compiler_flag__mssse3 - Success
-- Performing Test check_cxx_compiler_flag__mssse3
-- Performing Test check_cxx_compiler_flag__mssse3 - Success
-- Looking for C++ include tmmintrin.h
-- Looking for C++ include tmmintrin.h - found
-- Performing Test check_c_compiler_flag__msse4_1
-- Performing Test check_c_compiler_flag__msse4_1 - Success
-- Performing Test check_cxx_compiler_flag__msse4_1
-- Performing Test check_cxx_compiler_flag__msse4_1 - Success
-- Looking for C++ include smmintrin.h
-- Looking for C++ include smmintrin.h - found
-- Performing Test check_c_compiler_flag__msse4_2
-- Performing Test check_c_compiler_flag__msse4_2 - Success
-- Performing Test check_cxx_compiler_flag__msse4_2
-- Performing Test check_cxx_compiler_flag__msse4_2 - Success
-- Performing Test check_c_compiler_flag__mavx
-- Performing Test check_c_compiler_flag__mavx - Success
-- Performing Test check_cxx_compiler_flag__mavx
-- Performing Test check_cxx_compiler_flag__mavx - Success
-- Looking for C++ include immintrin.h
-- Looking for C++ include immintrin.h - found
-- Performing Test check_c_compiler_flag__mno_sse4a
-- Performing Test check_c_compiler_flag__mno_sse4a - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4a
-- Performing Test check_cxx_compiler_flag__mno_sse4a - Success
-- Performing Test check_c_compiler_flag__mno_fma
-- Performing Test check_c_compiler_flag__mno_fma - Success
-- Performing Test check_cxx_compiler_flag__mno_fma
-- Performing Test check_cxx_compiler_flag__mno_fma - Success
-- Performing Test check_c_compiler_flag__mno_bmi2
-- Performing Test check_c_compiler_flag__mno_bmi2 - Success
-- Performing Test check_cxx_compiler_flag__mno_bmi2
-- Performing Test check_cxx_compiler_flag__mno_bmi2 - Success
-- Performing Test check_c_compiler_flag__mno_avx2
-- Performing Test check_c_compiler_flag__mno_avx2 - Success
-- Performing Test check_cxx_compiler_flag__mno_avx2
-- Performing Test check_cxx_compiler_flag__mno_avx2 - Success
-- Performing Test check_c_compiler_flag__mno_xop
-- Performing Test check_c_compiler_flag__mno_xop - Success
-- Performing Test check_cxx_compiler_flag__mno_xop
-- Performing Test check_cxx_compiler_flag__mno_xop - Success
-- Performing Test check_c_compiler_flag__mno_fma4
-- Performing Test check_c_compiler_flag__mno_fma4 - Success
-- Performing Test check_cxx_compiler_flag__mno_fma4
-- Performing Test check_cxx_compiler_flag__mno_fma4 - Success
-- Performing Test check_c_compiler_flag__mno_avx512f
-- Performing Test check_c_compiler_flag__mno_avx512f - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512f
-- Performing Test check_cxx_compiler_flag__mno_avx512f - Success
-- Performing Test check_c_compiler_flag__mno_avx512vl
-- Performing Test check_c_compiler_flag__mno_avx512vl - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vl
-- Performing Test check_cxx_compiler_flag__mno_avx512vl - Success
-- Performing Test check_c_compiler_flag__mno_avx512pf
-- Performing Test check_c_compiler_flag__mno_avx512pf - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512pf
-- Performing Test check_cxx_compiler_flag__mno_avx512pf - Success
-- Performing Test check_c_compiler_flag__mno_avx512er
-- Performing Test check_c_compiler_flag__mno_avx512er - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512er
-- Performing Test check_cxx_compiler_flag__mno_avx512er - Success
-- Performing Test check_c_compiler_flag__mno_avx512cd
-- Performing Test check_c_compiler_flag__mno_avx512cd - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512cd
-- Performing Test check_cxx_compiler_flag__mno_avx512cd - Success
-- Performing Test check_c_compiler_flag__mno_avx512dq
-- Performing Test check_c_compiler_flag__mno_avx512dq - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512dq
-- Performing Test check_cxx_compiler_flag__mno_avx512dq - Success
-- Performing Test check_c_compiler_flag__mno_avx512bw
-- Performing Test check_c_compiler_flag__mno_avx512bw - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512bw
-- Performing Test check_cxx_compiler_flag__mno_avx512bw - Success
-- Performing Test check_c_compiler_flag__mno_avx512ifma
-- Performing Test check_c_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_c_compiler_flag__mno_avx512vbmi
-- Performing Test check_c_compiler_flag__mno_avx512vbmi - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi - Success
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations]
-- Flann 1.8.4 found (include: /Users/GZhu/Downloads/OpenMVG/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.10.13 found (include: /Users/GZhu/Downloads/OpenMVG/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.16.10 found (include: /Users/GZhu/Downloads/OpenMVG/openMVG/src/dependencies/osi_clp/Clp/src)
-- You are attempting to build without Osi. Please use cmake variable -DOSI_INCLUDE_DIR_HINTS:STRING="PATH" or OSI_INCLUDE_DIR_HINTS env. variable to a valid Osi path. Or install last Osi version.
-- Lemon  found (include: /Users/GZhu/Downloads/OpenMVG/openMVG/src/third_party/lemon/lemon)
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.7") 
-- Found Wget: /usr/local/bin/wget  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Ghostscript: /usr/local/bin/gs  
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Warning at third_party/flann/CMakeLists.txt:75 (message):
  OpenMP NOT found


CMake Warning at openMVG_Samples/describe_and_match_GUI/CMakeLists.txt:4 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/VO/AlternativeVO/CMakeLists.txt:7 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/CMakeLists.txt:14 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation


** OpenMVG version: 1.5.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- CEREAL: (external)
-- EIGEN: 3.3.7 (external)
-- CERES: 1.14.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.10 (external)
-- LIBPNG: 1.6.37 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
----------------------------------------------------

When I post this issue last weekend I used the internal CEREAL to config. I installed the external CEREAL by homebrew when I got a hint from you. That's why you can see that the config log shows I used external CEREAL. But still, I got the same error message when running "openMVG_main_IncrementalSfM" command.

Now I am trying to update my Xcode from 11.0 to 11.2, matching the latest Catalina. I hope it will solve this problem, because I complied openMVG on my laptop (Mackbook pro) with almost the same environment, and succeeded.  The only difference between my desktop machine and laptop is that I updated Xcode to 11.2 version on the laptop.

**Comment by punkyzhu** [comment]
hi, pmoulon,

After updating xcode form 11.0 to 11.2, I successfully ran "openMVG_main_IncrementalSfM" command without any errors. 

Thanks for your hints.

Next, I will try openMVS to see if I can get the final results.

**Comment by pmoulon** [comment]
@punkyzhu As I suspected you were using an external Ceres and Eigen. This configuration gives sometimes strange behavior because Ceres could has been compiled with another Eigen version and so cause crashes.

Happy that you system is not working. Have fun with SfM and MVS ;-)
