### ISSUE TITLE
Understanding of tracks and Union-Find

### ISSUE THREAD

**Issue by tudipffmgt** [openMVG/openMVG#1630]
Hi,

I am trying to understand your code for finding tracks in images using the union-find data structure. I am using my own feature matching methods and currently I can store the matches in any data format. At the moment I am getting feature points in integer and float.
E.g. I have seven images and find matches between (1-2, 1-3, 1-4, ..., 2-3,.... 6-7).
For my understanding I need to compare the image coordinates x and y of found matches in image 1, 2, 3...(computationally expensive) to be able to build tracks.
Where are you doing this comparison in your code? I was not able to find in tracks.hpp.

**Comment by pmoulon** [comment]
As explained in the paper `Unordered feature tracking made fast and easy` CVMP 2012 and the [poster](http://imagine.enpc.fr/~moulonp/publis/poster_CVMP12.pdf), we use an index for computing the tracks `{ImageId, FeatureId}`. Using this index allow to have a unique identifier for each feature we can use to use the Union-Find algorithm. 

I would suggest you to use the data structure from OpenMVG and this way you would be able to leverage all the OpenMVG pipeline. 1. Customize your feature extractor to fit OpenMVG data structure. 2. Add you Region type 3. Use all existing OpenMVG architecture and obtain track and SfM from your data in a easy way.

**Comment by tudipffmgt** [comment]
Thank you for your quick reply. I read the paper and the poster but how do you know the ID of similar features. Let's say in image pair 1-2 I have the feature in image 1 with ID 5 and coordinates x=100, y=100. Then I do a feature matching for the image pair 1-3 and the feature in image 1 has the ID 305 and similar coordinates. So I need to merge the IDs 5 and 305 to one ID and I would get my track. Are you comparing the coordinates during insertion?

**Comment by pmoulon** [comment]
Yes, we are merging IDs, you can take a look to the source code. You will see how IDs are computed and merged.
I don't look to coordinated during insertion, but I do look for some conflicts

1. Build feature IDs https://github.com/openMVG/openMVG/blob/master/src/openMVG/tracks/tracks.hpp#L96.
2. Merge features IDs https://github.com/openMVG/openMVG/blob/master/src/openMVG/tracks/tracks.hpp#L108
3. Filter tracks https://github.com/openMVG/openMVG/blob/master/src/openMVG/tracks/tracks.hpp#L124

**Comment by tudipffmgt** [comment]
Ok, I think I understand. Thanks for helping :)

**Comment by pmoulon** [comment]
You're welcome ;-)
