### ISSUE TITLE
Use internal libs by default instead of external

### ISSUE THREAD

**Issue by argentum2f** [openMVG/openMVG#1638]
Is there a way to tell cmake to use all the internal libs that are available by default, instead of defaulting to external libs when they are found?

**Comment by pmoulon** [comment]
You can compile and run OpenMVG in a fresh docker (so no other libs will be found).
There is official way to rely on internal package, you could try to comment the `find_package` instruction and see how it goes
Like here https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L163

**Comment by pmoulon** [comment]
@argentum2f Any feedback?

**Comment by pmoulon** [comment]
Closing due to lack of feedback
