### ISSUE TITLE
No defined intrinsic data ... (again)

### ISSUE THREAD

**Issue by nkindt** [openMVG/openMVG#1643]
Hi,

not the first issue mentioning "There is no defined intrinsic data in order to compute an essential matrix for the initial pair" and while some of the suggestions helped others, it didn't really help in my case. I have a bunch of images which are plain images not taken by any camera (thus no exif) and openMVG seems to choke on that. The "-f 1.2 * max_dim" workaround gives me an options to pick a x, y from several points, after which it errors out and fails too (tutorial_demo runs fine).

If this is so difficult to overcome, would it make sense to fallback to some sensible default data in case the camera could not be identified and continue rather then aborting with an unclear message? Or maybe there is a way to provide an entry in the camera database for something default (if nothing could be located pick default values from db and continue). Either way, nothing works for me at the moment and it would help if the tool can automate this somehow in case no such data is available.

Thanks

**Comment by pmoulon** [comment]
Hello @nkindt 
What matter for us is to explain to the community that having calibrated camera for photogrammetry is important.
Do you know your camera model?
- if yes, we could add your camera sensor size to the camera database...
- if no, we have to try to provide a focal guess and let the bundle adjustment recover a plausible value.

The thing I don't understand is the following:
- do you have only images without intrinsic data?
- or do you have some with intrinsic data and some without?

Feel free to share your dataset to openmvg-team[AT]googlegroups.com, we can take a look together to have the best reconstruction.

We are thinking about adding a default camera focal factor, but we should still warn users about PHOTOGRAMMETRY rules (camera calibration is an important part of the process to ensure quality).

**Comment by nkindt** [comment]
Hi Pierre,

thanks for the details!

Unfortunately i have images without any camera information. I did an EXIF transplant from another image to the data set and that did work well enough (not sure if i just got lucky here). I like the idea of any default value but i do also understand the importance of correct calibration. A mix between the two would be ideal and openMVG could act as a swiss-army knife for image reconstruction.

Would it be possible to do the "1.2 * max_dim" thing automatically for now if no camera gets detected? That seems like a good starting point to at least not have any errors (just to see what the program outputs).

Thanks!

**Comment by pmoulon** [comment]
@nkindt For the moment we don't have the automatical `focal_factor` thing in place, because we want to educate the community that to do photogrammetry, providing initial focal length is really helping for accuracy.

I think we will implement an automatic `focal_factor` that user could customize (depending on if they are aware of their camera aperture angle), but even if we put a warning message about the fact that many image are using this default focal, I'm afraid user will not care.

The other point is that some dataset, have calibrated and un-calibrated camera.
We still want to support this setup (SfM will start with a seed from the calibrated camera and then resect and find the calibration for the uncalibrated camera)

**Comment by nkindt** [comment]
Hi Pierre,

thanks for clarification on the philosophy of openMVG. I understand the problem and will close this one for now. As a last thing then, maybe i could suggest to output some information the -f workaround directly in the shell if things go wrong so users would not need to browse the issues on github for this (making openMVG more self-contained sortof). If this fails too then grinding through the issues and digging deeper is of course the only option left.

Something like - 
"Failed ... please try with the -f 1.2 * max_dim" option instead ..."

**Comment by pmoulon** [comment]
Thx you @nkindt. Appreciated you suggested a doc update. I'm gonna try this to add it next week.
