### ISSUE TITLE
is:issue is:open mono 360 camera to da 3D reconstruction?is it possible? if yes how?need help

### ISSUE THREAD

**Issue by tub-sgg** [openMVG/openMVG#1647]
is:issue is:open mono 360 camera to da 3D reconstruction?is it possible? if yes how?need help

**Comment by pmoulon** [comment]
Yes it is doable and we even doc and image sample for ithttps://github.com/openMVG/Image_datasets/tree/master/360_dataset

**Comment by tub-sgg** [comment]
this one seems not work @pmoulon

**Comment by pmoulon** [comment]
Provided dataset and command line are working and are tested.
If you tried the same command line on your data (that have a FishEye lens) it is normal that it does not work since the command line specify the spherical camera model.

**Comment by tub-sgg** [comment]
here is the dataset and the command line   https://github.com/openMVG/openMVG/issues/1648 @pmoulon

**Comment by pmoulon** [comment]
Going to close this issue, since your created another one for your dataset.
