### ISSUE TITLE
since no one helps me I close this one

### ISSUE THREAD

**Issue by tub-sgg** [openMVG/openMVG#1648]

**Comment by pmoulon** [comment]
Please paste here all the command line you are using.
We want to check that you were using the right camera model (FishEye) and that you are specifying a correct Focal Length.

Also you are using a 360 camera. It would be better to do SFM on the panoramic images, rather than just using the fisheye image you are capturing.

In another post you were mentioning that you calibrated your camera, can you describe here how you have done the calibration. I explained to you in another post how to use precalibrated value.

1. Check your assumptions
- which kind of images and lens I have
- photogrammetry needs approximate valid focal length
- FishEye lens have large distortion field, using precalibrated value can help the SfM process
2. Test OpenMVG on the provided dataset 
- tutorial sfm python script
- learn how open mvg is working (configure the scene with ImageListing, Computing the Features, the matches, process SfM)
3. Try OpenMVG on your own dataset

**Comment by tub-sgg** [comment]
1st: for  openMVG_main_SfMInit_ImageListing -d
/home/alex/Documents/openMVG/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
-i
/home/alex/Documents/test_openMVG/original_images
-o
/home/alex/Documents/test_openMVG/output1
-f 1
-c 7
2nd: openMVG_main_ComputeFeatures:
-i
/home/alex/Documents/test_openMVG/output1/sfm_data.json
-o
/home/alex/Documents/test_openMVG/output2
-m
AKAZE_FLOAT
3rd: openMVG_main_ComputeMatches
-i
/home/alex/Documents/test_openMVG/output1/sfm_data.json
-o
/home/alex/Documents/test_openMVG/output2/
-g
a
last: openMVG_main_IncrementalSfM
-i
/home/alex/Documents/test_openMVG/output1/sfm_data.json
-m
/home/alex/Documents/test_openMVG/output2/
-o
/home/alex/Documents/test_openMVG/output3

this is the whole conmmand I used to reconstruct  @pmoulon

**Comment by tub-sgg** [comment]
the panorama? you mean I need to convert each image to a panorama ? In openMVG is there existing methods to do this??? @pmoulon

**Comment by tub-sgg** [comment]
[cali.zip](https://github.com/openMVG/openMVG/files/3923277/cali.zip)
this is the dataset I test @pmoulon

**Comment by tub-sgg** [comment]
as calibration I mentioned , I just used a chessboard and use the function inside OenCV library to get the intrinsic matrix and distortion parameters(k0 k1 k2 k3) this is the principle I used
<img width="1002" alt="屏幕快照 2019-12-04 下午7 18 54" src="https://user-images.githubusercontent.com/44619635/70169361-efc39a80-16ca-11ea-8906-ca1941d64830.png">

**Comment by pmoulon** [comment]
Does Kodak provide tools to convert your camera image to panoramic images?

**Comment by tub-sgg** [comment]
yes, It provides a tool  @pmoulon

**Comment by tub-sgg** [comment]
![image](https://user-images.githubusercontent.com/44619635/70171862-dbce6780-16cf-11ea-81c8-b6bf335a1c4c.png)
you mean this one??

**Comment by pmoulon** [comment]
Just to clarify things:
- OpenMVG should be able to process your fisheye image
- OpenMVG should be able to process also the panoramic image that your camera can produce

I don't have time now to process your dataset but I think you should be able to have a way to recenter the panoramic image to have the thing you were looking at at the center of the panoramic image.

**Comment by tub-sgg** [comment]
ok . thanks but always fail in the end when I tried using fisheye images and now I am trying to using panoramic images following the sam steps to check whether it does work or not @pmoulon

**Comment by tub-sgg** [comment]
even I tried panoramic images still failed Need to find the reason............ @pmoulon

**Comment by pmoulon** [comment]
Be sure to start from clean (files in the matche directory you are using are reused).
So if you change a parameter use either the -f option on ComputeFeature and ComputeMatches or delete the past folders.

**Comment by tub-sgg** [comment]
even I tried your dataset and followed strictly  https://github.com/openMVG/Image_datasets/blob/master/360_dataset/README.md
I tried the 360_school dataset
still got such problem :
<img width="489" alt="屏幕快照 2019-12-04 下午9 25 11" src="https://user-images.githubusercontent.com/44619635/70178503-b4ca6280-16dc-11ea-943a-a51b8bfd9d8f.png">  @pmoulon

**Comment by pmoulon** [comment]
Did you try the tutorial sfm python script or the unit test of the library?

**Comment by tub-sgg** [comment]
I  used the library to test your dataset, got same error like my own dataset @pmoulon

**Comment by pmoulon** [comment]
Can you share the output of your cmake configure for OpenMVG?
I want to see if openMVG is using an internal or external ceres. You could have a conflict between some Eigen library that creates the bug every-time OpenMVG run a BundleAdjustment.

**Comment by tub-sgg** [comment]
-- Detected CPU: ivy-bridge
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.1
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Flann 1.8.4 found (include: /home/alex/Documents/openMVG/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.10.13 found (include: /home/alex/Documents/openMVG/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.16.10 found (include: /home/alex/Documents/openMVG/openMVG/src/dependencies/osi_clp/Clp/src)
-- You are attempting to build without Osi. Please use cmake variable -DOSI_INCLUDE_DIR_HINTS:STRING="PATH" or OSI_INCLUDE_DIR_HINTS env. variable to a valid Osi path. Or install last Osi version.
-- Lemon 1.3 found (include: /home/alex/Documents/openMVG/openMVG/src/third_party/lemon/lemon)
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Could NOT find Qt5Svg (missing: Qt5Svg_DIR)
CMake Warning at software/CMakeLists.txt:14 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Svg" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake"

  



** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation


** OpenMVG version: 1.5.0
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- CEREAL: (internal)
-- EIGEN: 3.3.7 (external)
-- CERES: 1.14.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.34 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/Documents/openMVG/openMVG_Build
this is the CMake configure @pmoulon

**Comment by tub-sgg** [comment]
I used external ceres library,It meanS i need to use internal one? @pmoulon

**Comment by tub-sgg** [comment]
today I checked the dataset and every command lines I just run your dataset
still result and still problem:
/home/alex/Documents/openMVG/openMVG/src/build_debug/Linux-x86_64-DEBUG/openMVG_main_IncrementalSfM -i /home/alex/Documents/test_openMVG/output1/sfm_data.json -m /home/alex/Documents/test_openMVG/output2/ -o /home/alex/Documents/test_openMVG/output3 -a R0010210.JPG -b R0010211.JPG -c 5 -f ADJUST_ALL
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 5581
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
------------------
TrackLength, Occurrence
	2	2969
	3	1213
	4	573
	5	310
	6	196
	7	119
	8	78
	9	41
	10	33
	11	49

A-Contrario initial pair residual: 0.316219

Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 827
 #residuals: 3308
 Initial RMSE: 29.2166
 Final RMSE: 4.43732
 Time (s): 9.34275


=========================
 MSE Residual InitialPair Inlier:



SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	227
	-- Residual min:	0.176734
	-- Residual median:	0.499713
	-- Residual max:	 0.819683
	-- Residual mean:	 0.498997
=========================

-------------------------------
-- Robust Resection of view: 2
  nfa=-166.457 inliers=101/110 precisionNormalized=0.00393462 precision=337.218 (iter=0 ,sample=89,15,99,)
  nfa=-514.893 inliers=106/110 precisionNormalized=2.17895e-06 precision=7.93566 (iter=0 ,sample=89,15,99,)
  nfa=-530.305 inliers=106/110 precisionNormalized=1.50917e-06 precision=6.60432 (iter=1 ,sample=25,53,97,)
  nfa=-556.183 inliers=107/110 precisionNormalized=9.45934e-07 precision=5.22865 (iter=2 ,sample=32,82,106,)
  nfa=-559.346 inliers=105/110 precisionNormalized=6.0904e-07 precision=4.19548 (iter=9 ,sample=58,30,64,)
  nfa=-568.754 inliers=106/110 precisionNormalized=5.70169e-07 precision=4.05939 (iter=10 ,sample=23,64,101,)
  nfa=-582.714 inliers=108/110 precisionNormalized=5.75149e-07 precision=4.07708 (iter=22 ,sample=85,49,82,)
  nfa=-594.196 inliers=108/110 precisionNormalized=4.20589e-07 precision=3.48649 (iter=27 ,sample=58,102,21,)
  nfa=-597.886 inliers=107/110 precisionNormalized=3.03868e-07 precision=2.96348 (iter=29 ,sample=80,67,96,)

-------------------------------
-- Robust Resection 
-- Resection status: 1
-- #Points used for Resection: 110
-- #Points validated by robust Resection: 107
-- Threshold: 2.96348
-------------------------------
**double free or corruption (out)**

**Process finished with exit code 134 (interrupted by signal 6: SIGABRT)** @pmoulon 
I do not know why

**Comment by csp256** [comment]
> since no one helps me I close this one

Just wow. 

For what its worth, Pierre is the most ridiculously helpful FOSS maintainer I've ever worked with.

**Comment by tub-sgg** [comment]
Ja, Pierre is very nice.He has already helped me a lot. I just think my question is too naive somehow. 
so I close this question @csp256

**Comment by rockokw** [comment]
It's okay to feel that way about your question but I don't think it is a good idea to erase the history. Pierre made a bunch of replies, but now no one in the future can understand his comments nor learn from them.
