### ISSUE TITLE
How to input camera position to generate the point cloud?

### ISSUE THREAD

**Issue by garion308** [openMVG/openMVG#1650]
i have 8 cameras that i know the exact position of and the angle of view of the cameras. Is it possible to use that information to speed up the process of generating the point cloud? If so, how do i do it?

**Comment by pmoulon** [comment]
You need to create an empty sfm_data.json file for your scene using SfmInitImageListing.
Then you can added camera poses using python or a text editor (rotation\Camera center) in the sfm_data.json.

Once you have setup your scene correctly, you can compute features, matches and then use ComputeStructureFromKnowPoses to triangulate your match file.
See here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeStructureFromKnownPoses.cpp#L88

**Comment by pmoulon** [comment]
You can also see many data importer here  https://github.com/openMVG/openMVG/tree/develop/src/software/SfM/import if it can help understand the SFM_DATA structure used by openMVG.

**Comment by pmoulon** [comment]
Closing due to lack of feedback
