### ISSUE TITLE
histogram.hpp, Not such file or directory

### ISSUE THREAD

**Issue by belosthomas** [openMVG/openMVG#1651]
Hello,

It seems that one of the header file are not installed correctly (when doing sudo make install) : 
`/usr/local/include/openMVG/robust_estimation/robust_estimator_ACRansac.hpp:50:10: erreur fatale: third_party/histogram/histogram.hpp : Aucun fichier ou dossier de ce type
`

Thomas.

**Comment by pmoulon** [comment]
Hi,
As you can see here the histogram folder is installed here https://github.com/openMVG/openMVG/blob/develop/src/third_party/CMakeLists.txt#L103

Can you try to add `"/usr/local/include/openMVG/third_party"` in your include folder for a quick test?

Nit: I should add histogram as a openMVG CMAKE INTERFACE.

**Comment by belosthomas** [comment]
Sorry the file is actually installed correctly.
By replacing : 
`#include "third_party/histogram/histogram.hpp"`
by 
`#include "openMVG/third_party/histogram/histogram.hpp"`
in robust_estimator_ACRansac.hpp, it fixed the problem.

**Comment by pmoulon** [comment]
should we close this ticket?
- or consider action items?
  - replace the include path (not ideal)
  - create a CMake INTERFACE for histogram lib in order to have header include transitively propagated (better)

**Comment by belosthomas** [comment]
#1653
