### ISSUE TITLE
openMVG can support Cubemap model to reconstruct 3D model?

### ISSUE THREAD

**Issue by tub-sgg** [openMVG/openMVG#1656]
openMVG can support Cube map model to reconstruct 3D model?

**Comment by pmoulon** [comment]
We don't enforce the cube rig consistency but can still run SfM and MVS with it.
Use the `-f` option to provide a focal length and you should be good to go

Note that you can provide spherical panorama to OpenMVG and then export the scene as cubes for MVS https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/export/main_openMVGSpherical2Cubic.cpp

**Comment by pmoulon** [comment]
Closing due to lack of feedback
