### ISSUE TITLE
OpenMVG.sln does not compile on Visual Studio (Windows)

### ISSUE THREAD

**Issue by JohnMath3w** [openMVG/openMVG#1667]
Windows 10, CMake 3.16.2, Visual Studio 16.4.2 2019

I generated the Visual Studio OpenMVG.sln file from CMake GUI and ran it on Release mode but it throws the following error: 
`1>------ Build started: Project: openMVG_kvld, Configuration: Release x64 ------
1>kvld.cpp
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG/matching/kvld/algorithm.h(56,19): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG/matching/kvld/algorithm.h(56,18): warning C4244: 'initializing': conversion from 'double' to 'const int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG/matching/kvld/algorithm.h(57,19): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG/matching/kvld/algorithm.h(57,18): warning C4244: 'initializing': conversion from 'double' to 'const int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG/matching/kvld/kvld.h(44,19): warning C4305: 'initializing': truncation from 'double' to 'float'
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG\matching\kvld\kvld.cpp(50,27): warning C4244: '=': conversion from 'double' to 'T', possible loss of data
1>        with
1>        [
1>            T=float
1>        ]
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG\matching\kvld\kvld.cpp(215,103): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG\matching\kvld\kvld.cpp(216,103): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\PerfitWorkingDirectory\openMVG\src\openMVG\matching\kvld\algorithm.h(107): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'd:\agent\_work\5\s\src\vctools\Compiler\Utc\src\p2\main.c', line 166)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>  CL!CloseTypeServerPDB()+0x25ceb4
1>  CL!CloseTypeServerPDB()+0x25ceb4
1>  CL!CloseTypeServerPDB()+0x25cba7
1>  CL!CloseTypeServerPDB()+0x25c802
1>  CL!CloseTypeServerPDB()+0x25c67f
1>  CL!CloseTypeServerPDB()+0x25c7f6
1>  CL!CloseTypeServerPDB()+0x16a71a
1>  CL!CloseTypeServerPDB()+0x635ba
1>  CL!CloseTypeServerPDB()+0x1033bd
1>  CL!CloseTypeServerPDB()+0x113d88
1>  CL!CloseTypeServerPDB()+0x1120a2
1>  CL!CloseTypeServerPDB()+0x110e56
1>  CL!InvokeCompilerPassW()+0x5bea7
1>  CL!beginthreadex()+0x142
1>  CL!BaseThreadInitThunk()+0x14
1>  CL!RtlUserThreadStart()+0x21
1>Done building project "openMVG_kvld.vcxproj" -- FAILED.
2>------ Build started: Project: openMVG_main_ColHarmonize, Configuration: Release x64 ------
3>------ Build started: Project: openMVG_sample_features_kvld, Configuration: Release x64 ------
3>LINK : fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_kvld.lib'
3>Done building project "openMVG_sample_features_kvld.vcxproj" -- FAILED.
2>LINK : fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_kvld.lib'
2>Done building project "openMVG_main_ColHarmonize.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 88 up-to-date, 0 skipped ==========`

The internal compiler error is on line 107 in file algorithm.h

When I run the same solution in debug mode, the build gets completed, but the application errors out saying Access Denied for ALL_BUILD.

Thanks in advance!

**Comment by pmoulon** [comment]
Is it the last VStudio?
Build is running fine VS 14 & 15 see here https://ci.appveyor.com/project/pmoulon/openmvg

I would suggest re-running the compilation of the target matching by hand and see if the error is happening again (perhaps you got an error when the build is multithreaded)

**Comment by JohnMath3w** [comment]
Ran for VS 15 just now, the build completed without errors but the execution errors out saying 
`Unable to start program, System cannot find file specified (build/Release/ALL_BUILD)`
The specified folder is an empty folder.
build/Win32/Release has two log file folders

**Comment by pmoulon** [comment]
`ALL_BUILD` is the target to just compile.
To run the binaries, you have to run them in a command line or change the compile target in VS.

See here how to use the python script that can run the OpenMVG toolchain on your image folder https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

**Comment by JohnMath3w** [comment]
Thank you so much, I know it was a dumb question. Thank you for being patient with me :) The python script was what I was looking for.

**Comment by pmoulon** [comment]
There is no dumb question and the community is here to help! Have fun with photogrammetry and don't hesitate to share here a screenshot of one of your reconstruction ;-)

**Comment by lexvandersluijs** [comment]
For other people who have this issue and have found this thread, there are two solutions in the issue 1765 mentioned by cenit in the previous comment.

**Comment by Jake-The-D0g** [comment]
I'm having a similar issue like that of #1667 where I have done everything up to the point that I just need to compile the the solution but I keep getting an access denied image

![image](https://user-images.githubusercontent.com/118870209/219273559-dc34d982-a2fd-4334-a67e-b457b89d6256.png)

I'm very new to this stuff, but I did set the target to Release and debug and got the same results, is there a work around for this or is there a fix that I might have missed?
