### ISSUE TITLE
About the Spherical camera

### ISSUE THREAD

**Issue by tub-sgg** [openMVG/openMVG#1669]
Hi Pierre,
I am doing 3D reconstruction from spherical camera. when I read the code about the part: bool SequentialSfMReconstructionEngine::Resection(const uint32_t viewIndex). In this part. Why is the spherical type not considered?

https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp

switch (cam_type_)
      {
        case PINHOLE_CAMERA:
          optional_intrinsic =
            std::make_shared<Pinhole_Intrinsic>
            (view_I->ui_width, view_I->ui_height, focal, principal_point(0), principal_point(1));
        break;
        case PINHOLE_CAMERA_RADIAL1:
          optional_intrinsic =
            std::make_shared<Pinhole_Intrinsic_Radial_K1>
            (view_I->ui_width, view_I->ui_height, focal, principal_point(0), principal_point(1));
        break;
        case PINHOLE_CAMERA_RADIAL3:
          optional_intrinsic =
            std::make_shared<Pinhole_Intrinsic_Radial_K3>
            (view_I->ui_width, view_I->ui_height, focal, principal_point(0), principal_point(1));
        break;
        case PINHOLE_CAMERA_BROWN:
          optional_intrinsic =
            std::make_shared<Pinhole_Intrinsic_Brown_T2>
            (view_I->ui_width, view_I->ui_height, focal, principal_point(0), principal_point(1));
        break;
        case PINHOLE_CAMERA_FISHEYE:
            optional_intrinsic =
                std::make_shared<Pinhole_Intrinsic_Fisheye>
            (view_I->ui_width, view_I->ui_height, focal, principal_point(0), principal_point(1));
        break;
        default:
          std::cerr << "Try to create an unknown camera type." << std::endl;
          return false;
      }

**Comment by pmoulon** [comment]
Simply because we don't have to consider the Spherical camera here, since the intrinsic was already existing. This code is only used when you are doing the resection with a intrinsic that is having an unknown camera model

**Comment by tub-sgg** [comment]
thanks a lot for so quick reply
