### ISSUE TITLE
GlobalSfM:: Translation Averaging failure!

### ISSUE THREAD

**Issue by ericdonatyy** [openMVG/openMVG#1670]
Hi @pmoulon ; 
I am encountering this problem at the Global-SFM step. Is it because of statistical values high?

Statistics about global rotation evaluation:

	 min: 0.000536982
	 mean: 2.18139
	 median: 0.0964527
	 max: 109.451

-------------------------------
 Relative translations computation: 
-------------------------------
#Triplets: 785

Relative translations computation (edge coverage algorithm)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
TRIPLET COVERAGE TIMING:
-------------------------------
-- #Relative triplet of translations estimates: 0 computed from 785 triplets.
-- resulting in 0 translations estimation.
-- time to compute triplets of relative translations: 65 seconds.
-------------------------------

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0

-------------------------------
 Global translations computation: 
   - Ready to compute 0 global translations.
     from #relative translations: 0
GlobalSfM:: Translation Averaging failure!

**Comment by pmoulon** [comment]
Global rotations seem ok (median error < 1 degree, but you are right the mean is a bit higher than usual: 2 degrees).
It could be because your intrinsic data is not accurate enough.

You could try first to calibrate your camera using Incremental SfM and reuse the same camera intrinsic to run the Global SfM pipeline.

**Comment by ericdonatyy** [comment]
i am newbie for incremental sfm.I did not use any optional parameters while doing this step. but  I previously used focal length(openMVG_main_SfMInit_ImageListing ) and  openMVG_main_ComputeMatches using pair.txt. As a result, I encountered this error ??  
can you help me with incremental sfm step?

> openMVG_main_IncrementalSfM    -i /openMVG/er/matches/sfm_data.json -m /openMVG/er/matches/ -o /openMVG/er/son
> Sequential/Incremental reconstruction
>  Perform incremental SfM (Initial Pair Essential + Resection).
> 
> 
> - Features Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 
> Invalid matches file.

**Comment by pmoulon** [comment]
You must have a matches.f.bin file in your match folder.
You can either rename the matches.e.bin to matches.f.bin or make a symbolic link to it.

**Comment by ericdonatyy** [comment]
Thank you for your support. 

How can I use the files I have produced from Incremental SFM in Global SFM. Briefly, do I currently calibrate my file with Incremental SFM? so I can't find intrinsic calibration data.

> You could try first to calibrate your camera using Incremental SfM and reuse the same camera intrinsic to run the Global SfM pipeline.

**Comment by pmoulon** [comment]
@ericdonatyy The next step is to reuse the intrinsic parameter you found with IncrementalSfM
1. Use ConverSfm_DataFormat to retrieve the calibration of the camera:
- Run `openMVG_main_ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data.json -V -I -E` and look for the intrinsic parameters in the sfm_data.json file. Copy the part about the parameter to your matches/sfm_data.json (all the part from data to the end, your parameter should be refined so you will have disto_k3 with variables that are not 0)
```
"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "width": 2832,
                        "height": 2128,
                        "focal_length": 2884.2617914205145,
                        "principal_point": [
                            1416.0,
                            1064.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
```

2. Run GlobalSfm on the updated sfm_data.json file, the existing calibration will be used and it should lead to better results.

**Comment by ericdonatyy** [comment]
Thank you very much @pmoulon. it is done. 
                        "focal_length": 1872.9265495174485,
                        "principal_point": [
                            1990.8271812996787,
                            1546.8751405160898
                        ],
                        "disto_k3": [
                            -0.2242889030460022,
                            0.058742525277517169,
                            -0.007413463177291698
                        ]
These are the instincts results I have achieved from Incremental SFM. I applied GLOBAL SFM using these results and it worked fine this time.

Bundle Adjustment statistics (approximated RMSE):
 #views: 71
 #poses: 71
 #intrinsics: 1
 #tracks: 59696
 #residuals: 716620
 Initial RMSE: 0.571476
 Final RMSE: 0.560355
 Time (s): 3.80589


 Total Ac-Global-Sfm took (s): 664
...Generating SfM_Report.html
...Export SfM_Data to disk.

Finally, I would like to consult you on a few things.

1. Can I always use these results on this camera? For example `-f 1872.9265495174485`

2.I cannot reach the point cloud that I obtained from GLOBAL SFM. My output file looks pretty small.

**Comment by pmoulon** [comment]
1. If you are always using the same camere, Yes. You will even have better results if you initialize with -f and then edit the json file and add all the right parameter (disto and principal point data)

2. Sometimes the point cloud of the object is very small, since some outlier point remains and are very far from the scene. I would use this tip in meshlab to navigate (double click on the point cloud to center and then zoom). And you can look to the camera trajectory by using  `$openMVG_main_ConvertSfM_DataFormat -i <PATH>/sfm_data.bin -o <PATH>/my_camera_trajectory.ply -E`

**Comment by ericdonatyy** [comment]
thank you very much for your support @pmoulon 
As far as I understand, I can get camera pose and orientation results for now. 

 So do I need to do these ( 
> openMVG_main_ComputeSfM_DataColor, 
>  openMVG_main_ComputeStructureFromKnownPoses, openMVG_main_ExportUndistortedImages
) processes to get the point cloud after this step?

**Comment by pmoulon** [comment]
From OpenMVG SfM results you can run various MVS pipeline to compute the point cloud:
See here https://openmvg.readthedocs.io/en/latest/software/MVS/MVS/
I would recommend PMVS or OpenMVS to start

**Comment by ericdonatyy** [comment]
Thank you very much.

**Comment by pmoulon** [comment]
You're welcome. Have experimenting!

**Comment by 20191100017** [comment]
@pmoulon Hello!I met the same problem in the global SFM, met in the global SFM invalid file matching, I've replaced sfm_data according to you the given approach. The parameters of the json continue to run global SFM matching results or invalid file, but can you tell me how to solve this problem, I use a set of images is the https://github.com/openMVG/ImageDataset_SceauxCastle

**Comment by 20191100017** [comment]
@pmoulon Hello!I met the same problem in the global SFM, met in the global SFM invalid matches file , I according to you is to replace the given parameters of sfm_data.json,continue running global SFM and the result will  invalid matches file. can you tell me how to solve this problem, I use a set of images is the https://github.com/openMVG/ImageDataset_SceauxCastle.

**Comment by 20191100017** [comment]
openMVG_main_SfMInit_ImageListing 
openMVG_main_ComputeFeatures 
openMVG_main_ComputeMatches 
openMVG_main_IncrementalSfM 
openMVG_main_ConvertSfM_DataFormat 
openMVG_main_GlobalSfM
 @pmoulon Hello!I'm running in that order. Any questions?

**Comment by pmoulon** [comment]
@20191100017 
Note that the match file should be name matches.e.bin because you ran ComputeMatches with `-g e`
Did you check this?
See here. https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/SfM_GlobalPipeline.py.in#L58

**Comment by 20191100017** [comment]
@pmoulon Hello!I am a beginner. I implemented it under Windows system. When I started running incremental SFM, I successfully reconstructed the sparse point cloud of the object, no problem.When I tried global SFM, the following error occurred while running openMVG_main_GlobalSfM,


D:\OpenSourceCodeCompile\OpenMVG\openMVG_build_vs\Windows-AMD64-Release\Release>openMVG_main_GlobalSfM -i D:\OpenSourceCodeCompile\OpenMVG\example\matches\sfm_data.json -m D:\OpenSourceCodeCompile\OpenMVG\example\matches\ -o D:\OpenSourceCodeCompile\OpenMVG\example\outReconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.

D:\OpenSourceCodeCompile\OpenMVG\openMVG_build_vs\Windows-AMD64-Release\Release>

**Comment by 20191100017** [comment]
Then, Using the above method, I first perform incremental SFM, then run openMVG_main_ConvertSfM_DataFormat, and replace the resulting parameter into the previous SFm_data.JSON
 "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "width": 2832,
                        "height": 2128,
                        "focal_length": 2990.6138195758937,
                        "principal_point": [
                            1465.5067718846336,
                            1109.6045267003004
                        ],
                        "disto_k3": [
                            -0.24909028508734458,
                            0.28637742489066728,
                            0.10792773567647782
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

But when I run openMVG_main_GlobalSfM with the replaced parameter, I get the same result
D:\OpenSourceCodeCompile\OpenMVG\openMVG_build_vs\Windows-AMD64-Release\Release>openMVG_main_ConvertSfM_DataFormat -i D:\OpenSourceCodeCompile\OpenMVG\example\outReconstruction\sfm_data.bin -o D:\OpenSourceCodeCompile\OpenMVG\example\outReconstruction\sfm_data.json -V -I -E

D:\OpenSourceCodeCompile\OpenMVG\openMVG_build_vs\Windows-AMD64-Release\Release>openMVG_main_GlobalSfM -i D:\OpenSourceCodeCompile\OpenMVG\example\matches\sfm_data.json -m D:\OpenSourceCodeCompile\OpenMVG\example\matches\ -o D:\OpenSourceCodeCompile\OpenMVG\example\outReconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Invalid matches file.

D:\OpenSourceCodeCompile\OpenMVG\openMVG_build_vs\Windows-AMD64-Release\Release>
I don't know where the problem is, please help me!Thank you so much!

**Comment by 20191100017** [comment]
You are really wonderful. You can solve my problem at once. Thank you very much!I'm a beginner and I'd like to ask you a few questions1. If I want to improve algorithms within openMVG, such as sift algorithm or blend incremental SFM and global SFM into a hybrid SFM, where should I modify it, or what should I do first?2. If the reconstruction of the object is a relatively small, such as surface more smooth metal parts in filming the physical picture than most, will lead to less image matching feature points, also has a larger error, the execution of incremental SFM, there will be a problem, often will be more than an object into a sparse point cloud, global SFM can effectively solve this problem?3. I find that the size of the 3D model after reconstruction will become extremely small, and there is a huge error with the size of the object itself. Is there an algorithm that can restore the size as much as possible?If not, do you think an algorithm like this is possible?The key question to address in implementing this algorithm is what, can you recover from the matrix generated during the reconstruction process?I haven't done in-depth research in this field, so the question May be silly. I hope you won't take it amiss. Thank you again!

**Comment by 20191100017** [comment]
@pmoulon Hello, I would like to ask how the incremental SFM calibrates the camera focus and radial distortion. The camera focus calculated through the camera information in EXIF and the "ImageListing" pipe is different from the focal length after executing the incremental SFM, which focal length is more accurate?Is the "ImageListing" pipe just an estimated camera focus?
