### ISSUE TITLE
 What is sensor size used for?

### ISSUE THREAD

**Issue by Koudaistudent** [openMVG/openMVG#1671]
I am a Japanese student.
I use Google Translate. Sorry for the strange English.

I want to perform SfM based on images taken with an infrared camera. However, an error occurs because the sensor size is not known.

What is the sensor size used for?

**Comment by pmoulon** [comment]
Hello @Koudaistudent Thank you for your interest and for asking a question to understand what's going on with this.

The sensor size is used to compute the focal length of the camera (the focal length defines the perspective projection).

See here for more details about the computation details:
https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata

If you have no idea about your sensor size you can still provide a focal guess using the option `-f X` to SfmInitImageListing. X should be equal to `1.2 * max(w,h)`. Doing so we will assume that your lens is having more or less a 90-degree FoV.

If you want detailed support on a subset of your imagery you can also contact `openmvg-team[AT]googlegroups.com`

**Comment by pmoulon** [comment]
Please close the issue if you got the answer to your question, or else feel free to ask more questions.

**Comment by Koudaistudent** [comment]
Thx
