### ISSUE TITLE
problem building docker

### ISSUE THREAD

**Issue by srs7** [openMVG/openMVG#1672]
I am trying to build the docker following the guideline, but when I run 
`sudo docker build . -t openmvg` 
It stops with this error message:

> Step 5/7 : RUN cd /opt/openMVG && git submodule update --init --recursive
 ---> Running in 22c8224eb664
fatal: not a git repository: /openMVG/.git/modules/src/dependencies/cereal
Unable to find current revision in submodule path 'src/dependencies/cereal'

Any idea to help me solve this?

Thanks so much!

**Comment by pmoulon** [comment]
-> Do you have access to internet on your machine and did you use git clone `not download on github`?
Submodule links are defined here: https://github.com/openMVG/openMVG/blob/develop/.gitmodules

Else if you have already check out the repo with git clone recursive, you can ignore the `&& git submodule update --init --recursive` part and just comment it out.

**Comment by srs7** [comment]
I had internet access and I cloned it, so I check the second option, and it worked. 

Thanks so much for the quick response

**Comment by pmoulon** [comment]
Great! Have fun with OpenMVG!
