### ISSUE TITLE
Output Extrinsics Data form SFM Reconstruction 

### ISSUE THREAD

**Issue by sealiutree7** [openMVG/openMVG#1677]
Hi, thank you for sharing the amazing library with us and everything you have done. 
I wonder if it is possible to get all the extrinsic matrix with all the input pictures in the final sfm_data.bin? (Since I have thirty input images and I want to get each image's extrinsic matrix in my sfm_data.bin)  
I am new in this field and sorry for my basic question.
Thank you so much again.

Sincerely,
Edwin

**Comment by rockokw** [comment]
Using `openMVG_main_ConvertSfM_DataFormat`, you can convert the sfm_data between the following formats: .json, .bin, .xml, .ply, .baf

JSON is probably your best bet if you're using a language like Python.

**Comment by sealiutree7** [comment]
Thank you for your reply and your time deeply. Because when I got my final sfm output, I only  got a part of the extrinsic matrix correspond to the input images. 
For example, if I have thirty input images,
in sfm_data.json (the file converted from sfm_data.bin used the funtion "openMVG_main_ConvertSfM_DataFormat"
) the _"views"_ will have 30 _"key"_ which count from _"key": 0_ to "_key": 29_.
However, the "extrinsics" may only have "_key": 0_ to _"key": 4_ and "_key": 18_ to _"key": 29_ which loss the data from "_key": 5_ to _"key": 17_, and this cause loss some of the extrinsic matrix correspond to the input images.  I wonder whether is there a method can force to produce all the extrinsic matrix correspond to the input images in the final sfm data?
Thank you so much for your help again.

Sincerely,
Edwin

**Comment by pmoulon** [comment]
@sealiutree7 Did you look to the log of the SfM process?
- It seems that all the camera has not been localized.
You should have a log telling the number of views and poses at the end of the process.

We are willing to help to see what's going on with your dataset. It could be that not enough matches are shared between the images, or could be something else.

**Comment by sealiutree7** [comment]
Hi, really thank you for your help and your time again. 
Here is the number of views and poses at the end of the process is shown below:
(I totally used twenty-nine images as input images, and here is the [input images](https://drive.google.com/open?id=1SlMsbq9L1jzd-MRaHL2BoI3dFeNdlYM4), the [matches folder](https://drive.google.com/open?id=1eEFETd3t0GqgM-5IpBLRuNN-mrSm4okv) and the [final Reconstruction folder](https://drive.google.com/open?id=1tSSftXLlcdK-RT4UbFri3xrrVLCjoCcy))
> ...
> -------------------------------
> -- Robust Resection of view: 18
>   nfa=-41.409 inliers=19/21 precisionNormalized=0.000292917 precision=58.8719 (iter=0 ,sample=8,3,7,)
>   nfa=-67.3207 inliers=21/21 precisionNormalized=3.05059e-05 precision=18.9989 (iter=1 ,sample=14,20,0,)
>   nfa=-70.4117 inliers=21/21 precisionNormalized=2.05041e-05 precision=15.576 (iter=5 ,sample=16,5,7,)
>   nfa=-71.6218 inliers=18/21 precisionNormalized=1.47253e-06 precision=4.17415 (iter=7 ,sample=7,20,0,)
>   nfa=-73.9959 inliers=21/21 precisionNormalized=1.29196e-05 precision=12.364 (iter=18 ,sample=15,6,12,)
>   nfa=-74.0546 inliers=21/21 precisionNormalized=1.28219e-05 precision=12.3172 (iter=280 ,sample=16,6,11,)
>   nfa=-75.2206 inliers=21/21 precisionNormalized=1.10287e-05 precision=11.4235 (iter=313 ,sample=20,11,16,)
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 1
> -- #Points used for Resection: 21
> -- #Points validated by robust Resection: 21
> -- Threshold: 11.4235
> -------------------------------
> 

> Bundle Adjustment statistics (approximated RMSE):
>  #views: 1
>  #poses: 1
>  #intrinsics: 1
>  #tracks: 21
>  #residuals: 42
>  Initial RMSE: 3.14297
>  Final RMSE: 2.35302
>  Time (s): 0.0006143
> 
> 
> Bundle Adjustment statistics (approximated RMSE):
>  #views: 29
>  #poses: 15
>  #intrinsics: 1
>  #tracks: 2834
>  #residuals: 13860
>  Initial RMSE: 0.552413
>  Final RMSE: 0.543437
>  Time (s): 0.139847

**
> 
> 
> -------------------------------
> -- Robust Resection of view: 5
>   nfa=-8.43458 inliers=6/7 precisionNormalized=3.74276e-05 precision=21.0571 (iter=0 ,sample=1,0,6,)
>   nfa=-15.4988 inliers=7/7 precisionNormalized=8.61277e-06 precision=10.1013 (iter=0 ,sample=1,0,6,)
>   nfa=-15.8749 inliers=7/7 precisionNormalized=6.91267e-06 precision=9.04954 (iter=1 ,sample=1,5,4,)
>   nfa=-15.8763 inliers=7/7 precisionNormalized=6.90728e-06 precision=9.04602 (iter=4 ,sample=5,6,4,)
>   nfa=-16.1478 inliers=7/7 precisionNormalized=5.89038e-06 precision=8.35364 (iter=9 ,sample=0,5,1,)
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 7
> -- #Points validated by robust Resection: 7
> -- Threshold: 8.35364
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 6
>   nfa=-4.08659 inliers=4/4 precisionNormalized=1.51061e-06 precision=4.23039 (iter=0 ,sample=0,1,2,)
>   nfa=-5.19184 inliers=4/4 precisionNormalized=8.69588e-09 precision=0.320967 (iter=1 ,sample=1,2,3,)
>   nfa=-5.19319 inliers=4/4 precisionNormalized=8.30023e-09 precision=0.31358 (iter=9 ,sample=3,0,2,)
>   nfa=-5.19319 inliers=4/4 precisionNormalized=8.30023e-09 precision=0.31358 (iter=20 ,sample=3,2,0,)
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 4
> -- #Points validated by robust Resection: 4
> -- Threshold: 0.31358
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 7
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------

> -------------------------------
> -- Structure from Motion (statistics):
> -- #Camera calibrated: 15 from 29 input images.
> -- #Tracks, #3D points: 2830
> -------------------------------
> 
> SequentialSfMReconstructionEngine::ComputeResidualsMSE.
>         -- #Tracks:     2830
>         -- Residual min:        1.71978e-05
>         -- Residual median:     0.331696
>         -- Residual max:         3.91646
>         -- Residual mean:        0.520781
> 
> Histogram of residuals:
> 0       |       7613
> 0.392   |       3035
> 0.783   |       1512
> 1.17    |       807
> 1.57    |       464
> 1.96    |       233
> 2.35    |       100
> 2.74    |       53
> 3.13    |       18
> 3.52    |       8
> 3.92

>  Total Ac-Sfm took (s): 5
> ...Generating SfM_Report.html
> ...Export SfM_Data to disk.

If not have enough matches shared between the images, then the system won't compute the corresponding poses? And I was wondering if you could give me some advice about how to get a better dataset if I want to reconstruct the blocks just like the images in [input images](https://drive.google.com/open?id=1SlMsbq9L1jzd-MRaHL2BoI3dFeNdlYM4)
which may cause the dataset doesn't have enough matches?

Sorry for my basic questions and thank you for your reading and patient.

Sincerely,
Edwin

**Comment by pmoulon** [comment]
Lego blocks are somehow a bit "featureless".

Here what you can try:

Command lines option:
- Option `-p HIGH` on ComputeFeatures to detect more points per images
- Use option `-n ANNL2` on COmputeMatches to have more accurate matches
- Use option `'-n 8` on ComputeFeatures to use 8 thread to compute the Features (faster)

-> It worked for me
```
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 29 from 29 input images.
-- #Tracks, #3D points: 19511
-------------------------------
```
![image](https://user-images.githubusercontent.com/3235050/74275757-52d43d80-4cc9-11ea-95fd-dbe25314b1e9.png)

-> As you can see there are very few points on the LEGO structure, most of the points are on the ground.

One side of the object seems capture with more sharpness:
![image](https://user-images.githubusercontent.com/3235050/74275855-8020eb80-4cc9-11ea-915f-a467f965af32.png)


Image capture tricks:
- Take your pictures with a tripod (some images are blurry)
- Add a newspaper page under your object to bring more features to the scene

**Comment by sealiutree7** [comment]
It also worked for me and I truly appreciate all your help on this matter. Further to this question, there is an idea occurred to me, if combine different feature extraction methods will help to improve the situation when the object is somehow a bit featureless? Or it may not be so helpful due to the object's featureless feature? Sorry for the question that may not be so related to the software now.
And thank you so much for everything you have done again.

Sincerely,
Edwin

**Comment by sealiutree7** [comment]
Hi, sorry for my stupid question. May I also ask why we use the  **ANNL2** algorithm but not the default one in this situation can help to get better matches here? Is it about the characteristic of the algorithm itself?  
I am new to this field and really want to more about it. And thank you so much again.

Sincerely,
Edwin

**Comment by pmoulon** [comment]
> combine different feature extraction methods will help to improve the situation when the object is somehow a bit featureless?

It all depends on the kind of objects or material of your scene. I would have a better bet on the number of feature extracted (-p preset option on ComputeFeatures) than having multiple kinds of features

> ANNL2

The default matcher (Cascade Hasher) is fast, but it is doing approximations (a cascade of hash), so in the end the matches are mostly ok but not as accurate as BruteForce or ANNL2.
Speed vs accuracy -> trade-off has to be made

**Comment by sealiutree7** [comment]
I got it and really thank you so much for your reply. There is a question I also wondering about why option 

> -p HIGH or ULTRA

on ComputeFeatures will help to get more features than the normal one, are they use a different algorithm or chose differently parameters in the formula? May I ask what the difference between the choice or the method they use respectively?

Sorry for my many questions, and thank you for your patient to answer deeply.

Sincerely,
Edwin

**Comment by pmoulon** [comment]
Yes, those preset set different thresholds used at feature detection time as you can see here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp#L110
