### ISSUE TITLE
how to insert GPS data of the cameras to generate a real 3D model 

### ISSUE THREAD

**Issue by tub-sgg** [openMVG/openMVG#1678]
As I know ,the software meshroom is using this opensource,but it does not support GPS data.Can I insert the position data of cameras to generate some point cloud data and then we can use meshroom or another software to generate meshmodel?

**Comment by pmoulon** [comment]
There is no interoperability between meshroom and openMVG.
Meshroom/AliceVision chooses to update the sfm_data class and did not keep any conversion tool so there is no backward compatibility.

But, I think you can manage to do with some manual work by using ConvertSfmDataFormat (bin -> json), copy the poses data from openMVG's sfm_data to Meshroom sfm_data and then recompute the 3D structure in Meshroom (ComputeStructureFromKnownPoses).

**Comment by pmoulon** [comment]
Or else you use OpenMVG+OpenMVS, OpenMVS results will be as good as meshroom output

**Comment by tub-sgg** [comment]
Sorry for long time to reply. Have you any specific steps how to add gps data for camera to do 3D reconstruction using openMVG+openMVS??

**Comment by tub-sgg** [comment]
It means I have position of camera like this
 "coordinate":{"latitude":52.51410196457803,"longitude":13.324751559501777,"altitude":279},"fovVertical":20},{"position":{"x":3772967.4439871632,"y":893625.9088578201,"z":5055637.736542444},"rotation":{"x":102.28666282472362,"y":-76.37421957147387,"z":-168.04906377567363},.How can I import this files to sfm?

**Comment by tub-sgg** [comment]
Or do you have some examples offered for this case?

**Comment by pmoulon** [comment]
Seems like you have GPS data, OpenMVG supports GPS data of your image natively.

If you already know the camera location and orientation, then you can import the scene directly by setting the right camera poses in the SfM_data.json file.

**Comment by tub-sgg** [comment]
thanks for your reply. and you mean I need to  use openMVG_main_SfMInit_ImageListing  and specify  -d ..  -o ..  -i  and there are several options,but in the tutorial threre are only about [-f|–focal] (value in pixels)
[-k|–intrinsics] Kmatrix: “f;0;ppx;0;f;ppy;0;0;1”
[-c|–camera_model] Camera model type:
1: Pinhole
2: Pinhole radial 1
3: Pinhole radial 3 (default)
[-g|–group_camera_model]
0-> each view have it’s own camera intrinsic parameters
1-> (default) view can share some camera intrinsic parameters

but when I check the code there are -P and -m optionals. And you mean I need to use these?However there are not more details about these options in the tutorial https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/.
I want to known how to exactly use these -P and -m options.

And there is another questions,Now I have the position of each camera, so I need to specify the extrinsic parameter  in the SfM_data.json file manually?like here
 "intrinsics": [],
    "extrinsics": [        ],
    "structure": [],
    "control_points": []

**Comment by wufan176** [comment]
Hi, I want to know if I use GPS data in SFM and use OPENMVG+OPENMVS, can I finally get a real-size model?

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen

**Comment by harshitsinghcode** [comment]
hello, I'm also getting trouble in mixing the GPS data that is the actual coordinates of the camera into 3 d reconstruction in order to fix the scaling!
