### ISSUE TITLE
How to add my own features to openMVG?

### ISSUE THREAD

**Issue by RufusBarma** [openMVG/openMVG#1679]
I have a photogrammetric system which calculates distance between points on image. The system based on artificial features. I can get openMVGs features due to openMVG_main_exportKeypoints, but how can I add my features to openMVG before compute matches?

What is structure of openMVGs features?  How can I push my features to openMVGs features?
I just want to edit *.feat but it's binary, so I should load data, add my features and  back to openMVG.

**Comment by pmoulon** [comment]
I would recommend you to use OpenMVG API.
So use the existing OpenMVG data structure and IO API to log your feature in OpenMVG format.
You can see here the addition of features and descriptors to regions https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp#L194

Or, you can load the SIFT computed features and append your own ones.

Can you elaborate exactly what you want to do:
- do you want to calibrate a scene (recover the camera position) and then triangulate some points that you knew the positions in the images and their correspondences?
- or do you want to do something different?

**Comment by RufusBarma** [comment]
Thank you for your answer and link. I will try to use OpenMVG API.
I want to add 3d model for result of a photogrammetric system, becouse now I have only photos with points and distance between them. I want to see this in 3d.

**Comment by pmoulon** [comment]
Closing the issue for now. Feel free to re0open if needed
