### ISSUE TITLE
Is it possible to add new 2D points for 3D triangulation?

### ISSUE THREAD

**Issue by jugoca** [openMVG/openMVG#1681]
Hello,

Is it possible to add manually new 2D matched points over the already existing ones in order to get them triangulated on the resulting point cloud using some component of openMVG? I am currently using a code to triangulate extra 3D points departing from several 2D pixel observations and the camera transformation matrices provided by openMVG's sfm_data_result_json file:

![Captura](https://user-images.githubusercontent.com/53514861/74943546-d510e000-53f4-11ea-866a-63928e8e34f6.PNG)

It does not work properly for some cases and it seems to be because of the difference on the mathematical methods used to obtain the cameras rotation and traslation (the way that my code receives this information and the way that openMVG produces it). That is the reason why I am asking you for a way to get these points automatically triangulated and included on mvg triangulation process.

Regards.

**Comment by pmoulon** [comment]
You have to check that you are providing Rotation and Camera Center.
You can use ConvertSfMDataFormat -i sfm_data.json -o pose.ply -E to see if you have the right camera centers.

Regarding your question on triangulating point based on their 2D correspondences, yes it is doable, you only need to add the observations in the structure json field and then call the triangulation engine of OpenMVG

**Comment by jugoca** [comment]
Hi @pmoulon,
Thanks for your reply. According to the solution you propose, what values should I introduce in "X" field, related to the 3D coordinates? I only have 2D observation coordinates.
![imagen](https://user-images.githubusercontent.com/53514861/76067369-85ebb300-5f8f-11ea-80c9-96d2987d81ad.png)

**Comment by pmoulon** [comment]
Just put a default value (0,0,0) for example.

**Comment by monschine** [comment]
Hi @pmoulon, 
when I manually define all the observations in a json format file, how could I call the triangulation engine of OpenMVG ?
So ComputeFeatures & ComputeMatches would be manually done, and taking into account that the 2D observation coordinates would be from spherical images.

Could we know some how if the given coordinates have a better or morse matching index ?

Thanks in advance and kind regards

**Comment by gmiguelr87** [comment]
> Just put a default value (0,0,0) for example.

Hi @pmoulon 
I'm interested in this topic too. I have tried to do what you say (set the coordinate in the structure to 0,0,0) and then use openMVG_main_ComputeSfM_DataColor to get the point cloud back, but it still shows up with coordinate 0,0,0.
I'm not sure if the triangulation engine you're referring to is exactly that. Can you please confirm it?
Thank you very much for everything!

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
