### ISSUE TITLE
I want to know why set  fx=fy in the optimization？

### ISSUE THREAD

**Issue by pjzultimate** [openMVG/openMVG#1682]
Hi,all:
when i see the cost fuction in the code ,i find that the focal length of intrinsic is set Fx=Fy in the cost function. so ,i want to know why do it. thonk you very much!

**Comment by pmoulon** [comment]
OpenMVG Pinhole camera model is having only a single value for the focal length since we assume we have square pixels.

**Comment by pmoulon** [comment]
@pjzultimate Any feedback?
