### ISSUE TITLE
fatal error LNK1181: cannot open input file '..\..\Windows-AMD64-\Release\openMVG_features.lib

### ISSUE THREAD

**Issue by Rahma-15** [openMVG/openMVG#1683]
Hi,

I am trying to build OpenMVG in visual studio, however i keep on getting this error. I am using Visual studio 2017. using release mode and win32, I have tried with x64 too, but i get the same error. 

I am not sure what is wrong, Thanks in advance !

**Comment by Rahma-15** [comment]
https://github.com/openMVG/openMVG/issues/1616#issue-509323517

**Comment by Rahma-15** [comment]
I built the whole thing again, and have the following errors now (LINK2019), I am using QT v5.14.0, 

1>------ Build started: Project: openMVG_main_AlternativeVO, Configuration: Debug x64 ------
2>------ Build started: Project: openMVG_sample_describe_and_match_GUI, Configuration: Debug x64 ------
2>Automatic MOC for target openMVG_sample_describe_and_match_GUI
1>Automatic MOC for target openMVG_main_AlternativeVO
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol __imp_RoInitialize referenced in function WinMain
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol __imp_RoGetActivationFactory referenced in function "public: __cdecl AppContainer::AppContainer(void)" (??0AppContainer@@QEAA@XZ)
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsCreateStringReference referenced in function "private: void __cdecl Microsoft::WRL::Wrappers::HStringReference::CreateReference(wchar_t const *,unsigned int,unsigned int)" (?CreateReference@HStringReference@Wrappers@WRL@Microsoft@@AEAAXPEB_WII@Z)
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsDeleteString referenced in function "public: void __cdecl Microsoft::WRL::Wrappers::HString::Release(void)" (?Release@HString@Wrappers@WRL@Microsoft@@QEAAXXZ)
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsGetStringRawBuffer referenced in function "public: wchar_t const * __cdecl Microsoft::WRL::Wrappers::HString::GetRawBuffer(unsigned int *)const " (?GetRawBuffer@HString@Wrappers@WRL@Microsoft@@QEBAPEB_WPEAI@Z)
2>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol RoOriginateError referenced in function "public: static void __cdecl Microsoft::WRL::ErrorHelper<0>::OriginateError(long,struct HSTRING__ *)" (?OriginateError@?$ErrorHelper@$0A@@WRL@Microsoft@@SAXJPEAUHSTRING__@@@Z)
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol __imp_RoInitialize referenced in function WinMain
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol __imp_RoGetActivationFactory referenced in function "public: __cdecl AppContainer::AppContainer(void)" (??0AppContainer@@QEAA@XZ)
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsCreateStringReference referenced in function "private: void __cdecl Microsoft::WRL::Wrappers::HStringReference::CreateReference(wchar_t const *,unsigned int,unsigned int)" (?CreateReference@HStringReference@Wrappers@WRL@Microsoft@@AEAAXPEB_WII@Z)
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsDeleteString referenced in function "public: void __cdecl Microsoft::WRL::Wrappers::HString::Release(void)" (?Release@HString@Wrappers@WRL@Microsoft@@QEAAXXZ)
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol WindowsGetStringRawBuffer referenced in function "public: wchar_t const * __cdecl Microsoft::WRL::Wrappers::HString::GetRawBuffer(unsigned int *)const " (?GetRawBuffer@HString@Wrappers@WRL@Microsoft@@QEBAPEB_WPEAI@Z)
1>qtmaind.lib(qtmain_winrt.obj) : error LNK2019: unresolved external symbol RoOriginateError referenced in function "public: static void __cdecl Microsoft::WRL::ErrorHelper<0>::OriginateError(long,struct HSTRING__ *)" (?OriginateError@?$ErrorHelper@$0A@@WRL@Microsoft@@SAXJPEAUHSTRING__@@@Z)
1>C:\Users\rnawab\Desktop\openMVG_DIR\out_dir\Windows-AMD64-\Debug\openMVG_main_AlternativeVO.exe : fatal error LNK1120: 6 unresolved externals
2>C:\Users\rnawab\Desktop\openMVG_DIR\out_dir\Windows-AMD64-\Debug\openMVG_sample_describe_and_match_GUI.exe : fatal error LNK1120: 6 unresolved externals
1>Done building project "openMVG_main_AlternativeVO.vcxproj" -- FAILED.
2>Done building project "openMVG_sample_describe_and_match_GUI.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 94 up-to-date, 0 skipped ==========

**Comment by pmoulon** [comment]
Can you try to compile in release mode?

@rperrot Any idea?

**Comment by rperrot** [comment]
Do you have mixed platforms ? (ie: compilaton in x86 and linking in x64 or conversly ?) Can you ensure that the platform you're compiling is the same as Qt ? (ie: make sure you use the x64 version of Qt).

**Comment by Rahma-15** [comment]
I Built it again, So i used x64 in Cmake, And Release in Visual Studio 2017,
For QT I gave the PATH to x64 folder, 'C:\Qt\Qt5.14.0\5.14.0\winrt_x64_msvc2017\lib\cmake' and still get errors


[VS_out.txt](https://github.com/openMVG/openMVG/files/4257546/VS_out.txt)

**Comment by rperrot** [comment]
Are you sure about the winrt variant of qt ? (it seems related to a wrong qt target with respect to your actual platform). Can you test without the rt variant ?

**Comment by Rahma-15** [comment]
Can you please tell me which version i should use?, the folder has msvc, mingw and winrt, sorry i am new to this. 

![Capture](https://user-images.githubusercontent.com/53687076/75381733-4ba35700-58a7-11ea-86db-d6d2d03a750f.PNG)

**Comment by rperrot** [comment]
I think msvc2017_64

**Comment by Rahma-15** [comment]
I rebuilt it by using msvc2017_64 but get the same error.

[VSout.txt](https://github.com/openMVG/openMVG/files/4258039/VSout.txt)

**Comment by rperrot** [comment]
Can you make sure:
1) You are using the latest version of VS (with all updates)
2) You rebuilt entierly (from scratch) in a new clean directory with R/W access.
3) You use the internal openMVG version of eigen. 

You have som trouble with the VS compiler :
> 52>c:\users\rnawab\downloads\eigen-eigen-b9cd8366d4e8\eigen-eigen-b9cd8366d4e8\eigen\src\core\densestorage.h(128): fatal error C1001: An internal error has occurred in the compiler.
52>(compiler file 'd:\agent\_work\3\s\src\vctools\compiler\utc\src\p2\main.c', line 187)

**Comment by Rahma-15** [comment]
It works ! I removed EIGEN that I was using for building openMVS previously and it gave no errors this time.
Thank you so much !

**Comment by seuwanglang** [comment]
@rperrot  hello. is qt necessary for  openmvg

**Comment by pmoulon** [comment]
@seuwanglang QT is not necessary for openmvg. It is an optional dependency that can be used to build some optional GUI demo or applications
