### ISSUE TITLE
Initial structure of long route when using global sfm with GPS

### ISSUE THREAD

**Issue by XudongYong** [openMVG/openMVG#1686]
Hi @pmoulon ,

When I use about 1000 uncalibrated images and related GPS info captured by UAV as input and try to reconstruct the structure with global SfM, I find the initial structure is warped (see initial_structure.ply below), and then during BA, when adding GPS constraints the structure is broken into many pieces with lots of outliers (see outlier_removed.ply below)

![structure](https://user-images.githubusercontent.com/17871648/75433970-ccd41a00-598b-11ea-9c99-81540a4614a3.jpg)

According to other related issues, I have known that this problem is mainly caused by radial distortion (see "Critical Configurations for Radial Distortion Self-Calibration"), and using correct distortion parameters or calibrated images as input can solve this problem (see following pic), but as you know, each camera has its own distortion parameters, so it may break current pipeline if we want to get a better result with camera calibrated each time. 

![calibratedImg](https://user-images.githubusercontent.com/17871648/75435190-a616e300-598d-11ea-88f1-bdbd5b5c35ba.jpg)

So, for this issue, do you think it is possible to use GPS previously when generating initial_structure.ply, or do you have other suggestions?

Thanks!

**Comment by pmoulon** [comment]
It all depends on your GPS quality.
In your case, it seems quite reliable and could be used as supervision for translation averaging but I'm afraid that the initial_structure was wrong due to a combination of invalid R and t.

Since you have UAV image I would use the ListPair filtering to only keep the local image to match to each other, process SfM as usual and then performed a rigid registration.

Another option could be to ensure you share the same camera model and perform a SfM step and then make each camera having its own parameter set and refine.

**Comment by pmoulon** [comment]
Another option since you have contiguous data could be to divide your data in N chunks and then merge them

**Comment by XudongYong** [comment]
Thanks for your reply, @pmoulon !

_[In your case, it seems quite reliable and could be used as supervision for translation averaging but I'm afraid that the initial_structure was wrong due to a combination of invalid R and t.]_
Actually, our GPS quality is reliable. In my opinion, the root cause of this problem is the bad initial_structure due to the combination of invalid R and t, which is caused by image distortion. After that, excuting similarity transformation and BA cannot adjust such a bad initial_strucuture.  So, I think to solve this problem, improve the quality of initial_structure is the key point.

_[Since you have UAV image I would use the ListPair filtering to only keep the local image to match to each other, process SfM as usual and then performed a rigid registration.]_
I have done this thing before and use 8 neighbors to improve matching speed and accuracy, but after process GlobalSfM, the GPS info has been used and the final cloud point is terrible, so I have no idea the usage of rigid registration here.

_[Another option could be to ensure you share the same camera model and perform a SfM step and then make each camera having its own parameter set and refine.]_
Yes, all pics are captured from a same camera, and I use the default camera model pinhole3. But the only thing to clarify here is I don't input the camera initial parameter during SfMInit.

_[Another option since you have contiguous data could be to divide your data in N chunks and then merge them]_
This is a good solution because I have tested this case before. For my whole 1000+ images, I divide them into many chunks and each chunk includes 100 images. Then, run each chunk and merge them according to GPS. The final result is better but it introduces a merging issue, that is, there is no relateship between adjacent chunk expect for GPS, and some gaps or realted rotation exist. So my further question is, how to keep the relationship of each chunk when merging their point clouds generated iteratively in GlobalSfM?

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
