### ISSUE TITLE
Adjust only camera rotation using Bundle Adjustment API

### ISSUE THREAD

**Issue by nguyengiang41** [openMVG/openMVG#1687]
Hi Dr Pierre Moulon,
First of all, thank you for sharing the OpenMVG library. Very flexible, easy to use and active support. 
I have a problem that I can not figure out, so I need your help to clarify it. 
I initialized a scene with known pose (rotation matrix, camera center) and camera calibration (F, PP, Disto). 
I would like to run a bundle adjustment on this scene, but only want to refine the camera rotation. 
So, I use  sfm::Bundle_Adjustment_Ceres API in openMVG, with sfm::Extrinsic_Parameter_Type::ADJUST_ROTATION option to do this. But in the output, the camera center always change with the adjusted rotation.
 I tried to figure out in the source code and I found that openMVG update always both (rotation, camera center) together (Ex in sfm_data_BA_ceres.cpp)
```

if (options.extrinsics_opt != Extrinsic_Parameter_Type::NONE)
    {
      for (auto & pose_it : sfm_data.poses)
      {
        const IndexT indexPose = pose_it.first;

        Mat3 R_refined;
        ceres::AngleAxisToRotationMatrix(&map_poses.at(indexPose)[0], R_refined.data());
        Vec3 t_refined(map_poses.at(indexPose)[3], map_poses.at(indexPose)[4], map_poses.at(indexPose)[5]);
        // Update the pose
        Pose3 & pose = pose_it.second;
        pose = Pose3(R_refined, -R_refined.transpose() * t_refined); // -> update R_refined and new camera center C
      }
    }

```
So, it means that when camera rotation change, the camera center coordinate express in world frame is changed also, unless the sfm::Extrinsic_Parameter_Type::ADJUST_ROTATION is enabled. 

Could you clarify me at this point ? How could I do if I just want to refine a camera rotation only ?

Thank you and have a nice day.

**Comment by pmoulon** [comment]
Thank you for your feedback and your kinds words about OpenMVG.
Appreciated that you are looking first to understand what could be wrong in the code and clearly point where the issue could be.

You're right it seems that the behavior is not the one you would expect.
We are using ceres constant parametrization to set either the rotation or translation parameters to constant, but as you have pointed, since we update the entire pose and use `t` and not `C` in the BA, despite the TRANSLATION is set has fixed, here the rotation changed will affect `C`.

Do you want to push a PR with a putative fix so we can test this and fix it for the community?
I would something like the following:

```
#loop for (auto & pose_it : sfm_data.poses)
const IndexT indexPose = pose_it.first;
Pose3 & pose = pose_it.second;
// Get back parameters (they could be refined or constant)
Mat3 R_refined;
ceres::AngleAxisToRotationMatrix(&map_poses.at(indexPose)[0], R_refined.data());
Vec3 t_refined(map_poses.at(indexPose)[3], map_poses.at(indexPose)[4], map_poses.at(indexPose)[5]);
if (options.extrinsics_opt == Extrinsic_Parameter_Type::ADJUST_TRANSLATION)
{
  pose = Pose3(R_refined, -R_refined.transpose() * t_refined);
}
if (options.extrinsics_opt == Extrinsic_Parameter_Type::ADJUST_ROTATION)
{
  pose.rotation() = R_refined;
}
```

let me know if it is working.

Perhaps we also need to do a BITWISE compare:
`!(options.extrinsics_opt & (int) Extrinsic_Parameter_Type::ADJUST_ROTATION)` rather than using == directly...

Let's also add some unit test to check this...

**Comment by nguyengiang41** [comment]
Yeah sure, happy to contribute. 
Could you explain how to push a PR for the review via Github ? I never do it before
Thanks

**Comment by pmoulon** [comment]
@nguyengiang41 
To contribute, you need to modify your fork:

```
$ git branch develop_ba_rotation_only
$ git checkout develop_ba_rotation_only
# do your modification and commit and push them 
# Then go on github and create your pull_request to the develop branch of OpenMVG
````

**Comment by nguyengiang41** [comment]
@pmoulon Got it. Will get back to you soon

**Comment by pmoulon** [comment]
@nguyengiang41 Let me know if you need any help

**Comment by nguyengiang41** [comment]
@pmoulon I created a branch, commit and try to push by "git push" or "git push --set-upstream origin develop_ba_rotation_only", but don't have permission. 
How could I deal with ? 




How could I come over it ?

**Comment by pmoulon** [comment]
You must make the modification in you FORK and then create a Pull Request
https://help.github.com/en/github/getting-started-with-github/fork-a-repo
1. FORK
2. Update your FORK (create a branch, nake your modification, add your the commits there & push to your FORK)
3. Go on Github within your fork, and create a pull request to request to update some change from your FORK to the upstream project

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
