### ISSUE TITLE
how can i save 7DoF between the SfM camera center position & the image GPS datum?

### ISSUE THREAD

**Issue by FengLQy** [openMVG/openMVG#1688]
```
// Initialize the scene
//  Pose prior for each view will be set thanks to the GPS data
openMVG_main_SfMInit_ImageListing \
  -P \
  -d sensor_width_camera_database.txt \
  -i /media/pierre/SenseFly/Quarry/geotagged-images/ \
  -o /media/pierre/SenseFly/Quarry/quary_output/

thread_count=8
openMVG_main_ComputeFeatures \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches \
  -n $thread_count

// Limit the number of pairs that will be used for matching
// -> limit to pose neighborhood thanks to the pose center prior location
openMVG_main_ListMatchingPairs \
  -G \
  -n 8 \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches/pair_list.txt

openMVG_main_ComputeMatches \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -l /media/pierre/SenseFly/Quarry/quary_output/matches/pair_list.txt \
  -g e \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches/

openMVG_main_GlobalSfM \
  -P \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -m /media/pierre/SenseFly/Quarry/quary_output/matches/ \
  -o /media/pierre/SenseFly/Quarry/quary_output/global_reconstruction
```

i have run to this, but i want to get the R|t and scale， how can i get it ?

**Comment by pmoulon** [comment]
When you are using the GPS prior, your SfM camera positions are always in the datum of the GPS.

If you use SfM without Prior and then compute a rigid registration, there you will be able to export the parameters.
See here: https://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/#for-sfm-to-xyz-gps-registration
You can export to disk or the console the found rigid registration here https://github.com/openMVG/openMVG/blob/develop/src/software/Geodesy/registration_to_exif_gps_position.cpp#L191

**Comment by FengLQy** [comment]
all right, Thank you for your reply. But when i using the GPS prior, The camera Point reduce， how i solve it ?/home/zhoufeng/图片/2020-03-04 15-49-07屏幕截图.png

**Comment by FengLQy** [comment]
thank you for your reply. But if i using the GPS prior, i find the camera Point cloud is reduce. can you give me some advice. thank you!

**Comment by pmoulon** [comment]
What do you mean by reduce?

- If you want the sR+t data from SfM to GPS I would use the rigid registration and export the transform to disk

So process without -P for initImageListing, still keep the pair_list.txt to reduce the matching time and then process SfM. Once SfM is done I would register and log to disk the transform

**Comment by FengLQy** [comment]
I mean that using the GPS prior the camera views will decrease. for example, if i use 300 images, and the camera views is 300, but the camera points in meshlab are not 300.  can you give me some advice. thanks a lot.

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
