### ISSUE TITLE
Clarification on identity pose

### ISSUE THREAD

**Issue by csparker247** [openMVG/openMVG#1700]
I've been working on importing pose priors from a custom camera rig, and I want to make sure that I've correctly propagated the rotation matrices for my cameras. The [camera documentation](https://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/) doesn't really clarify the camera orientation w.r.t the world frame as far as I can tell, but I've seen in another issue that the OpenMVG camera system is Z forward and Y up. I interpret this to mean that a camera with identity rotation:

1. Faces in the Z+ direction
2. The top of the image from that camera is oriented in the Y+ direction
3. The horizontal axis of the image from that camera moves from left: X+ to right: X-

An identity camera frustum would essentially look like this, where the red face is the top of the frustum:
![default_frustum00](https://user-images.githubusercontent.com/1434526/77252465-5fce4000-6c2a-11ea-9018-9729b4679c2e.png)

In my tests, it appears as though rotation is also left-handed, though I'm admittedly not convinced of this point.

Any help or clarification on this would be useful! Thanks!

**Comment by pmoulon** [comment]
Hello,

When you are trying to import your own camera pose I often recommend using https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/export/main_ExportCameraFrustums.cpp in order to see if your cameras are correctly oriented.

Feel free to make our export tool better for you and the community.

**Comment by pmoulon** [comment]
As you said Y should point up, Z Front.
You can also see here some synthetic dataset we are using for many unit test https://github.com/openMVG/openMVG/blob/develop/src/openMVG/multiview/test_data_sets.cpp#L82

**Comment by csparker247** [comment]
Thanks! I may open a PR that adds colors to the exported frustum. That would have been very helpful when I was debugging my rotations.

**Comment by pmoulon** [comment]
Thank you!
I was also thinking to add a mode to export X,Y,Z unit colored lines using the `edge` element from PLY but I never made it.

**Comment by csparker247** [comment]
Sounds good! I've added that to for discussion in the PR I just opened. I think that closes this issue out. Thanks!
