### ISSUE TITLE
Correct way to Triangulate 3D Position using Fixed Cameras and Sequential Images

### ISSUE THREAD

**Issue by Wolfffff** [openMVG/openMVG#1701]
Hello!

I am trying to setup a pipeline for 3D depth estimation of moving objects using openMVG and I'm running into a few issues. My current setup is 3 cameras as seen below(though scale isn't necessarily correct). I can already gather synchronized videos from the cameras, but I am having issues reconstructing the movement from them. I have the calibration of each individual camera(all the same) and a rough estimate(within 1m or so) of the location of each. I also have known correspondences between triplets of images at a given time (tracking of a moving object in each of frames).

With that, what is the best way for me to link the correspondences between each of the three images and also leverage the fact that I know the groupings? I know that I can edit my sfm_data.json and set each pose to the same value(1,2,3 in this case) and set each set of intrinsics, but I don't know how to integrate the fact I have known correspondences. Should I be using only custom tracks from my known correspondences? or custom including anything I can find and appending my known correspondences?  Currently, each time I try to run through the incremental SFM pipeline, I get no matches between cameras -- only within. 

On another note, is this generally the correct way to approach this problem? I'm trying to get a good grasp and would appreciate any advice!

![triangle](https://user-images.githubusercontent.com/22243650/77391139-59e17780-6d6e-11ea-890c-3ec6e1f10bbb.png)

Thanks so much!

**Comment by pmoulon** [comment]
1. Since the angle between your camera is large, I totally believe that some point would not be visible between the 3 views. I mean they could be recognized by a human, but perhaps SIFT is not able to cope with the baseline.

2. Does your camera are looking down to the scene, or does they are looking for the side?
```
-------       or 
\         /            ->.  obj.  <-
   obj
```

3. Inject know tracks would be doable (just need to add the interface)


4. You could calibrate your system once using many frames with a textured object, then reuse this calibration and triangulate your known object even if seen from 2 cameras.

-> So general advise:
- either bring your own calibration and just triangulate your observations (even if 2 view will be ok)
- or Calibrate your system (incorporate your scale), and then triangulate your observation (even if 2 view will be ok)

Sorry for the later answer.
Feel free to continue the discussion.

**Comment by Wolfffff** [comment]
Thank you so much for the response!

The cameras are looking  from the side.

As far as bringing my own calibration, that's totally doable for the initial setup, but I'm a bit worried about if my cameras get moved(they're being left in the field for relatively long periods).  If they are moved, I could recalibrate using later (manually annotated) correspondences(this would only be at the fine scale given that the cameras move very little).

So my thoughts are, and I would appreciate feedback of course -- 

1.  Calibrate cameras in pairs using checkerboards or try to calibrate all 3 at once using a 3D calibration object. Do you happen to know of a good reference for using 3d calibration objects? I'm struggling to find any good literature on it.

2. Refine this using the known correspondences I have from videos. That is, implement an interface for injecting my own tracks. Do you have any notes on what the best way to do this is?

Another few quick questions: what is the best way to establish that images are from different cameras and sequential? So camera 1 has images 1,2,3,4,...,n, camera 2 has 1,2,3,4,...,n, and so forth. When setting up my sfm_data I can set the pose for each but I don't known how to utilize the fact that the images are paired. Given that the matching tries each pair(I think), do I need to integrate that information? Can I?

**Comment by Sentient07** [comment]
Hi @Wolfffff @pmoulon . I am trying to solve the exact same problem as mentioned in the first comment. Do you have a solution for this? More precisely, my question is, 

> So camera 1 has images 1,2,3,4,...,n, camera 2 has 1,2,3,4,...,n, and so forth. When setting up my sfm_data I can set the pose for each but I don't known how to utilize the fact that the images are paired. Given that the matching tries each pair(I think), do I need to integrate that information? Can I?

Thanks in advance! 

Regards

**Comment by pmoulon** [comment]
Sorry, I did not get time to reply to the question. Feel free to reopen if we can assist
