### ISSUE TITLE
using geometric_model

### ISSUE THREAD

**Issue by Lsz-20** [openMVG/openMVG#1704]
There is something wrong when I using：openMVG_main_ComputeMatches：-g h

I can run -g f/e with openMVS well，but when I transform into geometric_model and using IncrementalSfM it shows：

----------------------------------------------------SequentialSfMReconstructionEngine::ChooseInitialPair
----------------------------------------------------
 Pairs that have valid intrinsic and high support of points are displayed:
 Choose one pair manually by typing the two integer indexes
----------------------------------------------------
(5,60)          54 matches
(18,19)         48 matches
(56,57)         45 matches
(1,55)          42 matches
(3,58)          41 matches
(10,11)         39 matches
(8,9)           39 matches
(2,3)           36 matches
(3,57)          32 matches
(7,8)           31 matches

 type INITIAL pair ids: X enter Y enter
and I choose（5,60）
when I finish this it can't run DensifyPointCloud well and show：error: reference image  xxx has not enough images in view
Is it because more data is needed？
Thanks

**Comment by pmoulon** [comment]
So it would mean that the SfM graph seems note dense enough for computing neighbor images.

- Did you compare the cloud_and_poses.ply you obtained using `-g f` and `-g h`?

It seems that using the Homography filter given weak pairs for SfM with your scene (40ish match per pair)... Does your scene is planar?

**Comment by pmoulon** [comment]
Linking your two old issues for clarity:
- https://github.com/openMVG/openMVG/issues/1693
- https://github.com/openMVG/openMVG/issues/1696

**Comment by Lsz-20** [comment]
> 因此，这意味着SfM图看起来足够密集，足以计算相邻图像。
> 
> * 您是否比较了使用`-g f`和获得的cloud_and_poses.ply `-g h`？
> 
> 似乎使用同构滤波器为场景提供了SfM弱对（每对40匹配）...您的场景是平面的吗？

I looked at both cloud_and_poses.ply ,-g h has very few points,this should be the reason for the inability to follow up.Is my data not enough?
Thanks

**Comment by Lsz-20** [comment]
Thanks for your reply,I used the correct steps I asked for earlier

**Comment by Lsz-20** [comment]
I think there's something wrong with the data ，geometric_model's requirements seem even higher than others.
