### ISSUE TITLE
Return skylake-avx512 architecture detection back

### ISSUE THREAD

**Issue by Nikolay-Po** [openMVG/openMVG#1705]
Hi! Have spend 1.5 hours to find the reason why the build is performed for Core2Duo CPU instead of SkyLake with AVX512. Quite odd issue. Cause I found: #1664.
Have inserted back the lines `     elseif(_cpu_model EQUAL 85) # 55
        set(TARGET_ARCHITECTURE "skylake-avx512")
` into OptimizeForArchitecture.cmake file to let this script make it's work properly.
For next time, if possible, please, insert a user warning with clear information to console output, something like this:
`UserWarning("skylake-avx512 disabled due to unstable detection on Tracis-CI, see OpenMVG issue #1664")`

Thanx

**Comment by pmoulon** [comment]
Thank you for your feedback.
Note that you are using the develop branch, I would like to find a better to fix this.

- If you have any idea about why on Travis some CPU is identified but cannot be used for compilation, please let me know.
I thought about forcing a given target on Travis and others but then your CI is limited to one architecture... :-(
