### ISSUE TITLE
is there an first-image-visibility assumption on the triangulation for `compute structure from known poses`?

### ISSUE THREAD

**Issue by jasonlovescoding** [openMVG/openMVG#1706]
Hi, thanks for your amazing work. 
I'm trying to make use of the strcture from known poses component to build a point cloud for the data collected by a drone flight. I followed the steps recommended in [this issue](https://github.com/openMVG/openMVG/issues/1214). The images are captured by a grayscale camera on the drone, and the poses & camera intrinsics are provided. I computed the imagelist, features and matches, modified the 'extrinsics' field in the json file based on the given poses, and fed the match.f.bin into compute structure from known poses. 
The generated .ply file visualized by meshlab is something like this:
![Screenshot from 2020-04-01 00-53-09](https://user-images.githubusercontent.com/12913794/78100594-33958a80-73b3-11ea-8986-1a3069f57278.png)
![Screenshot from 2020-04-01 01-00-46](https://user-images.githubusercontent.com/12913794/78101036-3e045400-73b4-11ea-8d12-3b3d95ba5522.png)
I believe the green is the trajectory of the drone (went straight forward and made a back turn to the right). But the point cloud seems to be limited within a 'cone' where each point needs to be visible from the first image. Looking into the generate report, the views after making the turn have very low number of observations. (There are not many visible points for them)
My question is, is that an assumption in the triangulation that a point should be visible for the first frame? If I want to build a point cloud that covers more surroundings of the trajectory (for instance I might want more points also surrounding the trajectory after making the turn, which is like looking in the opposite direction as the 'cone' we have now), what steps should I take?
Thanks in advance!

---
P.S. an interesting thing I found is that if I do not pass the match file to the computation from known poses, I end up getting somewhat more observations, though the visualized result is still a one-directional cone. I think I might at least need two 'cone's in opposite directions. Is there something else I might need to do here?

**Comment by pmoulon** [comment]
Sorry, I saw I never replied to this. Let me close it, but feel free to re-open if you need assistance
