### ISSUE TITLE
Different results from using API and executable for computeFeatures

### ISSUE THREAD

**Issue by ziyuedang** [openMVG/openMVG#1707]
Hi, 

I am currently trying to output the octave and slice associated with each key point within the feature computation process.

I used the code below and acquired the keypoints and their attributes, however, I noticed the number of keypoints output here is slightly different from what I get from directly using main_ComputeFeatures.exe.
` vector<Keypoint> keypoints;
keypoints.reserve(5000);
cerr << "Octave computation started" << std::endl;
uint8_t octave_id = 0;
while (octave_gen.NextOctave(octave))
{
cerr << "Computed octave : " << std::to_string(octave_id) << std::endl;
vector<Keypoint> keys;
SIFT_KeypointExtractor keypointDetector(0.04f / octave_gen.NbSlice(), 10.0f, 5);
keypointDetector(octave, keys);
Sift_DescriptorExtractor descriptorExtractor;
descriptorExtractor(octave, keys);
move(keys.begin(), keys.end(), back_inserter(keypoints));
++octave_id;
}`

I tested this on 9 images, for 2 images, the API and .exe have the same number of keypoints, for 6 images, there is a 1 point difference between the API and .exe, for the last one image, there is a 3 point difference.

This seems odd to me since it's not a consistent difference. Then I tried again using just the image_describer, which gives the **same results as the SIFT keypoint API** (different from the executable):

`Image<unsigned char> in;
int res = ReadImage(imageFile.c_str(), &in);
const string sFeat = "test.feat";
const string sDesc = "test.desc";
Image<unsigned char>* mask = nullptr;
unique_ptr<Image_describer> image_describer(new SIFT_Anatomy_Image_describer(SIFT_Anatomy_Image_describer::Params()));
auto regions = image_describer->Describe(in, mask);
image_describer->Save(regions.get(), sFeat, sDesc);
`

Any insights on why this is happening?

Thank you!

**Comment by pmoulon** [comment]
I wonder if it could be due to threading...
Could you try to set OpenMP thread to 1 or X and compare if you have different results?
See here https://software.intel.com/en-us/mkl-windows-developer-guide-setting-the-number-of-threads-using-an-openmp-environment-variable

**Comment by ziyuedang** [comment]
I tried both setting the environment variable "OMP_NUM_THREADS" to 1 and X. Nothing changed unfortunately.

**Comment by ziyuedang** [comment]
@pmoulon I tried this with AKAZE instead of SIFT ANATOMY, out of the 9 images, only 1 image has different numbers of features for the executable and the API (1 point difference), all the other images acquired same results. Seems very random and I still don't have a clue.

**Comment by pmoulon** [comment]
When you change the threading count, did you actually notice it was using one thread?
- Happy to hear that things are ok now and thanks for having shared your path to success
It seems a strange issue...

**Comment by ziyuedang** [comment]
@pmoulon Yes, the complied executable was using one thread for sure. Maybe in my project, the API didn't inherent the openMP threading correctly for some reason?

**Comment by pmoulon** [comment]
Depending of your OS, you have to use `export` or `set` to set an environment variable value.
Have fun playing with OpenMVG
