### ISSUE TITLE
computer crashes, mesh doesnt open 

### ISSUE THREAD

**Issue by penguinsar** [openMVG/openMVG#1711]
hello,

i'm very new to this platform and also to meshroom. Iv'e made a mesh and after saving it, my computer crashed. now i can't seem to open the mesh again. i went to the textured folder and try to open the obj file there. it open the 3d viewer but nothing shows up. i tried also to open it throw the meshroom software- again, nothing shows up. anyone can help me understand what's seems to be the issue?

thank you!

**Comment by pmoulon** [comment]
Please go to Meshroom github issues.
