### ISSUE TITLE
visual interface 

### ISSUE THREAD

**Issue by Lsz-20** [openMVG/openMVG#1712]
The relevant files like '.ply' can be successfully opened through meshlab.Now I want to create a visual interface which can open'.ply' or '.svg'.What platform should I use to implement this?
Can I use opengl in Qt?
Thanks

**Comment by pmoulon** [comment]
Qt is having a native SVG reader and display interface.
Qt can also display easily 3D points (you can choose to have OpenGL back end or not).

**Comment by Lsz-20** [comment]
Thanks for your advice (*^__^*)
