### ISSUE TITLE
how to compute pose?

### ISSUE THREAD

**Issue by Shen001** [openMVG/openMVG#1714]
here is a problem,maybe not very about your perfect tools.
my pose comes from a tool called "ContextCapture",but a photo's pose is a rotation data includes "omega/phi/kappa" and a center data includes"x/y/z".so maybe you know how to transform rotation angle to rotation matrix? i am confused about this, thanks.

**Comment by pmoulon** [comment]
Hello, @Shen001,
I believe COntextCapture is having a documentation guide explaining the camera model they are using and how to compute the rotation matrix from those angular values.

Once you find this doc it will be trivial to set the rotation matrix and the camera center (world coordinates) in OpenMVG sfm_data.json file.

**Comment by Shen001** [comment]
thanks for your reply，i need learn more~

**Comment by pmoulon** [comment]
Did you figure it out?
You should find what you need here https://docs.bentley.com/LiveContent/web/ContextCapture%20Help-v9/en/GUID-2D452A8A-A4FE-450D-A0CA-9336DCF1238A.html

**Comment by Shen001** [comment]
yes，maybe the number should be "double" instead of “float”...
