### ISSUE TITLE
Problems with dots that only appear in two images

### ISSUE THREAD

**Issue by Daniel8810** [openMVG/openMVG#1716]
Good afternoon.

I have a problem with generating a 3d model. It is a model that one of its parts appears only in two images is not generated in the sparse. The rest of the model appears between 3 and 4 images but that part that only appears in two images is not generated. When looking at the matching made I see that those two images did find matches between them.

Could something be done to make the sparse generate points in that part?

Greetings, thank you very much.
![matching](https://user-images.githubusercontent.com/64086799/79876375-40723080-83eb-11ea-8957-5889ed9ba45f.jpg)
![sparse](https://user-images.githubusercontent.com/64086799/79876380-41a35d80-83eb-11ea-9426-e6e737804dcb.jpg)

**Comment by pmoulon** [comment]
Did you try to run a densification pipeline (like PMVS or OpenMVS) and set the right configuration there to keep points visible only on 2 images.

Feel free to share your image so we could take a look and try to understand why the points are not triangulated in that area.

Can you explain which command line did you use?

**Comment by Daniel8810** [comment]
Hello good day.

Yes, I have tried to generate the model by densifying with OpenMVS and with the correct parameters so that the points that are only visible in two images appear.

In my opinion the biggest problem is in the generation of the sparse in the sfm, that these points are not triangulated, even when it finds coincidences between them.

For sfm I used the following configuration:
openMVG_main_IncrementalSfM.exe -i sfm_data.json -m features -o ./sfm

With openMVS: DensifyPointCloud.exe -i sparse.mvs -o cloud_dense.mvs --number-views 0 --number-views-fuse 2 --estimate-colors 1 --estimate-normals 1 --resolution-level 1 - -max-threads 0

Greetings and thank you very much.

![1](https://user-images.githubusercontent.com/64086799/80345051-cf0e0400-8868-11ea-91e9-15b1bde9353d.jpg)
![2](https://user-images.githubusercontent.com/64086799/80345056-cfa69a80-8868-11ea-969b-e0fc5c1d7c1a.jpg)
![3](https://user-images.githubusercontent.com/64086799/80345057-d03f3100-8868-11ea-822d-ba61efe1df83.jpg)
![4](https://user-images.githubusercontent.com/64086799/80345060-d0d7c780-8868-11ea-8461-4c58d1172b1c.jpg)
![5](https://user-images.githubusercontent.com/64086799/80345061-d0d7c780-8868-11ea-9581-c9e39477fbfd.jpg)

**Comment by Daniel8810** [comment]
Hello good day.

Yes, I have tried to generate the model by densifying with OpenMVS and with the correct parameters so that the points that are only visible in two images appear.

In my opinion the biggest problem is in the generation of the sparse in the sfm, that these points are not triangulated, even when it finds coincidences between them.

For sfm I used the following configuration:
openMVG_main_IncrementalSfM.exe -i sfm_data.json -m features -o ./sfm

With openMVS: DensifyPointCloud.exe -i sparse.mvs -o cloud_dense.mvs --number-views 0 --number-views-fuse 2 --estimate-colors 1 --estimate-normals 1 --resolution-level 1 - -max-threads 0

Greetings and thank you very much.
![1](https://user-images.githubusercontent.com/64086799/80346276-c8808c00-886a-11ea-9e02-b02f281dce6d.jpg)
![2](https://user-images.githubusercontent.com/64086799/80346281-c9192280-886a-11ea-9ff7-6741a21632b3.jpg)
![3](https://user-images.githubusercontent.com/64086799/80346285-c9b1b900-886a-11ea-9ade-2eef3492c386.jpg)
![4](https://user-images.githubusercontent.com/64086799/80346288-ca4a4f80-886a-11ea-9aa8-529d281b26e4.jpg)
![5](https://user-images.githubusercontent.com/64086799/80346289-ca4a4f80-886a-11ea-8a41-14a5f250a0a7.jpg)
