### ISSUE TITLE
A problem about file saving of openMVG

### ISSUE THREAD

**Issue by anorlo** [openMVG/openMVG#1717]
Hi, thanks for your sharing!
I wrote a detection and description code and I want to test the performance in 3D reconstruction.  I have worked for about 4 days, but I still have no idea about how to get the same format results as openMVG. I am a newcomer to this area. Do you have any suggestions in order to make my result can suit openMVS properly? 
Thanks!

**Comment by pmoulon** [comment]
You can either write your own importer or export your detection and description to OpenMVG data structure.

See here:
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/sfm_regions_provider.hpp
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/sfm_features_provider.hpp

Or else just write a conversion tool that will convert your data to .feat and .desc by exporting openMVG::Regions -> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/regions_factory.hpp#L19
See here where features and descriptors are added to the Region container https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp#L194
Here to save them to a file https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeFeatures.cpp#L329

You can also take inspiration from the OpenCV interface here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeFeatures_OpenCV.cpp

**Comment by anorlo** [comment]
I am so glad your reply that fast!
I will try as your saying. 
Thanks again!

**Comment by anorlo** [comment]
Sorry to interrupt again.
I though the .feat file is defined by 
`SIOPointFeature feat((*i_kp).pt.x, (*i_kp).pt.y, (*i_kp).size, (*i_kp).angle);`
I found that in the examples .feat files the (*i_kp).size, (*i_kp).angle are always less than 10. 
But in my codes, which is based on python, the parameters size and angle are all more than one hundred. 
Is there something wrong?
Thank you for your patient!

**Comment by pmoulon** [comment]
It depends on the feature detector you are using.
OpenMVG will use only the x and y coordinates for SfM, so don't worry about the size/scale and angle. Dummy or real value will be ok.
