### ISSUE TITLE
Fedora build fails (undefined reference)

### ISSUE THREAD

**Issue by Majstor** [openMVG/openMVG#1720]
Hi,

I can't build the last openMVG on my Fedora 31, see compilation errors :
```
[ 80%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_sample_image_undistort
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/main.cc.o : dans la fonction « image_undistort_gui::MainWindow::~MainWindow() » :
main.cc:(.text._ZN19image_undistort_gui10MainWindowD2Ev[_ZN19image_undistort_gui10MainWindowD5Ev]+0xc) : référence indéfinie vers « vtable for image_undistort_gui::MainWindow »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/main.cc.o : dans la fonction « non-virtual thunk to image_undistort_gui::MainWindow::~MainWindow() » :
main.cc:(.text._ZN19image_undistort_gui10MainWindowD2Ev[_ZN19image_undistort_gui10MainWindowD5Ev]+0x8c) : référence indéfinie vers « vtable for image_undistort_gui::MainWindow »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/main.cc.o : dans la fonction « image_undistort_gui::MainWindow::~MainWindow() » :
main.cc:(.text._ZN19image_undistort_gui10MainWindowD0Ev[_ZN19image_undistort_gui10MainWindowD5Ev]+0xc) : référence indéfinie vers « vtable for image_undistort_gui::MainWindow »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/main.cc.o : dans la fonction « non-virtual thunk to image_undistort_gui::MainWindow::~MainWindow() » :
main.cc:(.text._ZN19image_undistort_gui10MainWindowD0Ev[_ZN19image_undistort_gui10MainWindowD5Ev]+0x83) : référence indéfinie vers « vtable for image_undistort_gui::MainWindow »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/MainWindow.cc.o : dans la fonction « image_undistort_gui::MainWindow::MainWindow(QWidget*) » :
MainWindow.cc:(.text+0x2b97) : référence indéfinie vers « vtable for image_undistort_gui::MainWindow »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/MainWindow.cc.o : dans la fonction « image_undistort_gui::MainWindow::onExportImage() » :
MainWindow.cc:(.text+0x2ce1) : référence indéfinie vers « image_undistort_gui::MainWindow::staticMetaObject »
/usr/bin/ld : CMakeFiles/openMVG_sample_image_undistort.dir/MainWindow.cc.o : dans la fonction « image_undistort_gui::MainWindow::onOpenImage() » :
MainWindow.cc:(.text+0x2fc1) : référence indéfinie vers « image_undistort_gui::MainWindow::staticMetaObject »
collect2: erreur: ld a retourné le statut de sortie 1
gmake[2]: *** [openMVG_Samples/image_undistort_gui/CMakeFiles/openMVG_sample_image_undistort.dir/build.make:163: Linux-x86_64-RELEASE/openMVG_sample_image_undistort] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3727: openMVG_Samples/image_undistort_gui/CMakeFiles/openMVG_sample_image_undistort.dir/all] Error 2
gmake: *** [Makefile:150: all] Error 2
```

**Comment by pmoulon** [comment]
Bonjour @Majstor 

Seems to be an issue with QT, can you try again without building the QT samples?

Add `-DOpenMVG_BUILD_GUI_SOFTWARES=OFF` in your make command line

**Comment by Majstor** [comment]
Bonjour @pmoulon,
Thanks, that builds. Is it possible to investigate why Qt gui does compilation failed ?

**Comment by pmoulon** [comment]
@rperrot Any idea about this QT linking error?

**Comment by rperrot** [comment]
Got the same issue on my computer. I'm still trying to figure the issue. I'm trying to think about an issue with recent cmake because of this : 

`CMake Warning (dev) in openMVG_Samples/image_undistort_gui/CMakeLists.txt:
  Policy CMP0100 is not set: Let AUTOMOC and AUTOUIC process .hh files.  Run
  "cmake --help-policy CMP0100" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the header file(s):

    "/Users/rperrot/Prog/Reconstruction/local_openmvg/openMVG/src/openMVG_Samples/image_undistort_gui/MainWindow.hh"
    "/Users/rperrot/Prog/Reconstruction/local_openmvg/openMVG/src/openMVG_Samples/image_undistort_gui/QImageInterface.hh"
    "/Users/rperrot/Prog/Reconstruction/local_openmvg/openMVG/src/openMVG_Samples/image_undistort_gui/QImageInterface.hh"
    "/Users/rperrot/Prog/Reconstruction/local_openmvg/openMVG/src/openMVG_Samples/image_undistort_gui/MainWindow.hh"

  from processing by AUTOMOC and AUTOUIC.  If any of the files should be
  processed, set CMP0100 to NEW.  If any of the files should not be
  processed, explicitly exclude them by setting the source file property
  SKIP_AUTOGEN:

    set_property(SOURCE file.hh PROPERTY SKIP_AUTOGEN ON)`

**Comment by rperrot** [comment]
The moc file is empty, that's the issue, all the symbols are defined in it.

**Comment by rperrot** [comment]
Manually executing moc on the given header gives a valid file. Still thinking about a cmake issue.

**Comment by rperrot** [comment]
Ok, got it on mac. 

@Majstor can you add this : 

```
cmake_policy( SET CMP0100 NEW )
```
To the CMakeLists.txt file ?

**Comment by Majstor** [comment]
OK nice that works

**Comment by rperrot** [comment]
Ok, thanks for your answer.

@pmoulon We need to add this policy to the main CMakeLists.txt, or at least in the samples.

**Comment by pmoulon** [comment]
Issue is now solved, see commit.
