### ISSUE TITLE
A question about：geometric_matches.svg

### ISSUE THREAD

**Issue by Lsz-20** [openMVG/openMVG#1722]
I can only find 'geometric_matches.svg' when I use Homography Matrix and GlobalSfM，when I use others，there is only 'geometric_matches'，when I opened it through a web page, it wasn't displayed graphically....
Thanks to answer!

**Comment by YouYue123** [comment]
The geometric_matches is in graphviz DOT language. You can open that through any client which supports graphviz

**Comment by Lsz-20** [comment]
Thanks for your advise
