### ISSUE TITLE
Re-optimize computed positions

### ISSUE THREAD

**Issue by mattangus** [openMVG/openMVG#1723]
Great work! This library has been very helpful.

Is there any way to "start where we left off" but with lower stopping criteria? Let's say for example that I have a series of images in a loop. I run the incremental pipeline and the results look good, except there are a few inconsistencies with the loop closure.  I have already changed the following values in `sfm_data_BA_ceres.cpp`:

```
ceres_config_options.parameter_tolerance
ceres_config_options.function_tolerance
ceres_config_options.gradient_tolerance
ceres_config_options.max_solver_time_in_seconds
```

What I would like to do is update these values when I see that the loop closure didn't work and re-run the pipeline but without having to go through the whole pipeline. I'm just trying to reduce the computation time. Is this possible?

**Comment by mattangus** [comment]
Would it be sufficient to write a small program to load the computed `sfm_data` and call `SequentialSfMReconstructionEngine::BundleAdjustment` a number of times with new stopping criteria?

**Comment by pmoulon** [comment]
Hello @mattangus,
Yes it would be sufficient.
You can also run https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_IncrementalSfM2.cpp with the mode `EXISTING_POSE `. It will load your poses, re-triangulate and perform a BundleAdjustment

**Comment by mattangus** [comment]
Great! The small loop seems to be working. I'll try using `EXISTING_POSE` later.

Thanks!
