### ISSUE TITLE
Question about incremental SFM seed 

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1724]
Hi,

I realized the SFM result can be very different with different seed initial pair. I got an image set which contains 10 images. With the good initial seed, it can link all of them. But with the bad initial seed, it only links 2 of them.

May I know what the general principle to choose the initial seed?

**Comment by YouYue123** [comment]
Found out the result in 
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L341

The initial selection is based on a pair that have the largest baseline (mean angle between its bearing vectors)

**Comment by pmoulon** [comment]
Hello @YouYue123,
Yes our criteria to start a reconstruction is based on baseline.
We also have a N-view seed in IncrementalSfMv2 that you can test 
- Use STELLAR https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_IncrementalSfM2.cpp#L109

**Comment by YouYue123** [comment]
STELLAR is an interesting idea. Will IncrementalSfMv2 also support manual initial pair as well?
