### ISSUE TITLE
How to get most matches pair as initial pair for incremental SFM

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1725]
Hi,

Continued for my last issue #1724 , I would like to try to use the most matches in pair as incremental but I could not find a way to export match amount between each pair. 

The **openMVG_main_exportMatches** only exports SVG file.

**Comment by pmoulon** [comment]
Hello @YouYue123 
As you can see here, the number of match for the pair is encoded in the filename https://github.com/open-anatomy/SfM_gui_for_openMVG/blob/master/src/software/SfM/main_exportMatches.cpp#L197
You can also use the OpenMVG API and load the match file and save it in ASCII if you need (.txt)

**Comment by YouYue123** [comment]
Thanks for the response!
