### ISSUE TITLE
[Help] Idea to get the camera height related to ground floor plane

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1726]
I am working to get the camera height related to ground floor.

My idea to detect the lowest horizontal plane on the **cloud_and_poses.ply**

I would like to know 

- whether this will be a good idea

- how true is cloud_and_poses.ply to show the ground plane

- is there any way I can get similar information during the reconstruction pipeline

**Comment by pmoulon** [comment]
You could try to detect the most dominant plane for sure and hoping it will be the floor.
If you know that your camera is Upright, I would do a sampling along the Y-axis by projecting the point and identify where you have the most of the point concentration.

- else you annotate the 3D plane with 3 point in 2 images and compute the camera to plane orthogonal distance

**Comment by YouYue123** [comment]
For this point "else you annotate the 3D plane with 3 point in 2 images and compute the camera to plane orthogonal distance" could you elaborate more? Or could you also explain me the mathematic model behind this?
