### ISSUE TITLE
OSX Catalina generate sfm_data.bin issue

### ISSUE THREAD

**Issue by ColinFirth5566** [openMVG/openMVG#1728]
I followed the README file and compile OpenMVG successfully.

I tried to run the dataset here : https://github.com/openMVG/Image_datasets

but the results show:

Using input dir  :  /Users/colinfirth/Desktop/3DR/openMVG/input/360_dataset/360_Flat/images/
      output_dir :  /Users/colinfirth/Desktop/3DR/openMVG/output/
1. Intrinsics analysis
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory 
/Users/colinfirth/Desktop/3DR/openMVG/input/360_dataset/360_Flat/images/
--sensorWidthDatabase /Users/colinfirth/Desktop/3DR/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /Users/colinfirth/Desktop/3DR/openMVG/output/matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 2
usable #File(s) listed in sfm_data: 2
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /Users/colinfirth/Desktop/3DR/openMVG/output/matches/sfm_data.json
--outdir /Users/colinfirth/Desktop/3DR/openMVG/output/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 7
3. Compute matches
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /Users/colinfirth/Desktop/3DR/openMVG/output/matches/sfm_data.json
--out_dir /Users/colinfirth/Desktop/3DR/openMVG/output/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
	#nodes: 2
	#cc: 1
	#singleton: 0
	Node degree statistics:	min: 1, max: 1, mean: 1, median: 1

 Export Adjacency Matrix of the pairwise's geometric matches
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 584
 Images Id:
0, 1,
------------------
TrackLength, Occurrence
	2	584

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
5. Colorize Structure

The input SfM_Data file "/Users/colinfirth/Desktop/3DR/openMVG/output/reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/Users/colinfirth/Desktop/3DR/openMVG/output/reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "/Users/colinfirth/Desktop/3DR/openMVG/output/reconstruction_sequential/robust.bin" cannot be read.

------------------------------------------------------------------------------
I checked the issue here : 
1 ) . https://github.com/openMVG/ImageDataset_SceauxCastle/issues/2

and here is my sfm_data.json file,

{
    "sfm_data_version": "0.3",
    "root_path": "/Users/colinfirth/Desktop/3DR/openMVG/input/360_dataset/360_Flat/images/",
    "views": [
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "R0010220.JPG",
                        "width": 5376,
                        "height": 2688,
                        "id_view": 1,
                        "id_intrinsic": 0,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "R0010219.JPG",
                        "width": 5376,
                        "height": 2688,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "width": 5376,
                        "height": 2688,
                        "focal_length": 1141.4197232387056,
                        "principal_point": [
                            2688.0,
                            1344.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

----------------------------------------------------------

It seems extrinsics, structure are not generated successfully.

Could anyone provide any suggestion on this issue?

Thanks.

**Comment by pmoulon** [comment]
Please note that you are using 360 images and so you must use the 360 camera model `-c 7`.
See here https://github.com/openMVG/Image_datasets/blob/master/360_dataset/README.md

Default settings for OpenMVG are configured for rectilinear/pinholes images (https://github.com/openMVG/ImageDataset_SceauxCastle)

**Comment by ColinFirth5566** [comment]
Hi pmoulon,

I downloaded the dataset to my input folder and run, but still get the same output (https://github.com/openMVG/ImageDataset_SceauxCastle)

(base)  ~/Desktop/3DR/openMVG/output   develop ● python /Users/colinfirth/Desktop/3DR/openMVG_build/software/SfM/SfM_SequentialPipeline.py /Users/colinfirth/Desktop/3DR/openMVG/input/images/ /Users/colinfirth/Desktop/3DR/openMVG/output/

Using input dir  :  /Users/colinfirth/Desktop/3DR/openMVG/input/images/
      output_dir :  /Users/colinfirth/Desktop/3DR/openMVG/output/
1. Intrinsics analysis
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /Users/colinfirth/Desktop/3DR/openMVG/input/images/
--sensorWidthDatabase /Users/colinfirth/Desktop/3DR/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /Users/colinfirth/Desktop/3DR/openMVG/output/matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
.DS_Store: Unkown image file format.


SfMInit_ImageListing report:
listed #File(s): 12
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /Users/colinfirth/Desktop/3DR/openMVG/output/matches/sfm_data.json
--outdir /Users/colinfirth/Desktop/3DR/openMVG/output/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
3. Compute matches
 You called :
/Users/colinfirth/Desktop/3DR/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /Users/colinfirth/Desktop/3DR/openMVG/output/matches/sfm_data.json
--out_dir /Users/colinfirth/Desktop/3DR/openMVG/output/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
	 PREVIOUS RESULTS LOADED; #pair: 55

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
	#nodes: 11
	#cc: 1
	#singleton: 0
	Node degree statistics:	min: 8, max: 10, mean: 9, median: 10

 Export Adjacency Matrix of the pairwise's geometric matches
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 6159
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
------------------
TrackLength, Occurrence
	2	3024
	3	1122
	4	668
	5	425
	6	259
	7	234
	8	200
	9	147
	10	66
	11	14

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*5. Colorize Structure

The input SfM_Data file "/Users/colinfirth/Desktop/3DR/openMVG/output/reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/Users/colinfirthg/Desktop/3DR/openMVG/output/reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "/Users/colinfirth/Desktop/3DR/openMVG/output/reconstruction_sequential/robust.bin" cannot be read.


----------------------------------------------------------------------------


According to above error msg, sfm_data.bin still cannot find.

Also in that dataset, I saw there is intrinsic K information

2905.88 0 1416 
0 2905.88 1064
0 0 1

How to I add this information to the openmvg?
Is it in /Users/colinfirth/Desktop/3DR/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt ?

Thanks for your explanation!
