### ISSUE TITLE
Camera pose scale is not consistent in the same incremental SFM scene

### ISSUE THREAD

**Issue by YouYue123** [openMVG/openMVG#1732]
Hi,

I am running an incremental SFM with spherical image for an outdoor building block. The reconstruction is successful. But I found that the camera pose centre scale is not consistent. 

This is the final result:

![Screenshot 2020-05-02 at 3 53 40 PM](https://user-images.githubusercontent.com/8738486/80866115-53a7ba80-8c8d-11ea-9985-48bb2c2eb4eb.png)

The camera pose I annotated in the above image is actually **containing another path with a different scale**. By zooming in you can find the dot looks like this. This path is actually as long as the rest of the path.

![Screenshot 2020-05-02 at 3 53 20 PM](https://user-images.githubusercontent.com/8738486/80866138-79cd5a80-8c8d-11ea-9a71-5b983556b1c8.png)

I thought by Incremental SFM and Bundle adjustment, the scale within one scene should be consistent. May I know what's the possible reason to cause this problem?

Thanks

**Comment by pmoulon** [comment]
It seems that one of the camera pose estimation was wrong and created a `sub scene` inside the larger one.

In order to reduce this effect, you can try to extract more feature point per image (`-p HIGH`) or you can remove the problematic images and try to run SfM again to add them back
