### ISSUE TITLE
How to use known pixel matching points as parameters of sfm

### ISSUE THREAD

**Issue by jjhlc** [openMVG/openMVG#1735]
i have use one camera to acquire scene images with marked points at multiple locations, and the corresponding pixels can be obtained according to the marked points, so how can I use corresponding pixels to run openMVG_main_IncrementalSfM or openMVG_main_GlobalSfM

**Comment by pmoulon** [comment]
I think you want to relate to Ground Control Points...
If I guess right you can see here https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

Else please elaborate a bit.

If you want to run SfM only with the marked point, you need to export your points to OpenMVG feat files and match files and then run SfM.
