### ISSUE TITLE
is there a way to include GCPs in the bundle adjustment?

### ISSUE THREAD

**Issue by AbegNext** [openMVG/openMVG#1736]

**Comment by pmoulon** [comment]
Yes.
- https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/
You can also import your own data by using the JSON interface of sfm_data that OpenMVG is using.

**Comment by AbegNext** [comment]
Thank you @pmoulon. I meant to ask if it is possible to include the GCPs during the bundle adjustment itself as a constraint. The URL you mentioned talks about registration after the structure has been computed.
