### ISSUE TITLE
Tracked 2D Features as parameters for SfM?

### ISSUE THREAD

**Issue by JChan2787** [openMVG/openMVG#1739]
Greetings! I have a set of 2D features that are tracked throughout a span of n-image frames done in OpenCV. Can I use that data to perform camera motion estimation in OpenMVG? From what I've read in the documentation, it seems the camera motion estimation part is possible through the usage of the SfM pipeline. However, I'm not seeing anywhere on how to set your own data as parameters. Per the tutorial, all that's required is to run one of the desired python scripts, and then passing in the locations for your source image inputs and output. 

If such a thing is possible for the use case I have described, can you please outline the steps on how to feed my own 2D points and calibrated camera matrix? 

I hope I worded my question clearly, I'm still reading the source and documentation. 

Thank you.

**Comment by pmoulon** [comment]
What I would do is to use OpenMVG pipeline as it is with your image data if you can.
You can provide your input focal length with -f X option on SfMInitImageListing.

Then depending on the results, you can investigate if you can build a better reconstruction from your tracks.

Else to use you own data you have to:
1. convert your point data to .feat file
2. convert your track to pairwise matches matches.f.txt
3. run SfM on it

I think it could be valuable for OpenMVG to build a tutorial for such application.
Would you be willing to help us to build this tutorial?

**Comment by JChan2787** [comment]
Hi, thank you for the speedy response. I'd be happy to contribute in the creation of such a tutorial! But I feel like it's currently way out of my depth as I'm still poking through the library and learning the ins-and-outs (I have so many questions). For starters, where should I look on how to format my track data to a .feat file?

**Comment by pmoulon** [comment]
Let me try to find some time later in the week to add more reference here.
You can read this https://github.com/openMVG/openMVG/wiki/OpenMVG-data-structures
You must use OpenMVG API to write a .feat file for each image you have or a python script.

If you want run OpenMVG with default parameters on your dataset (while waiting) https://github.com/openMVG/openMVG/wiki/OpenMVG-on-your-image-dataset

**Comment by drchillout** [comment]
Hey there! Im also interested into the solution here.
In my project im creating my own features and match them. All done with opencv(ORB). 
At the end i want to use the SFM from openmvg but like JChan im struggling to understand how to use my own Data in openmvg.

My approach to this moment, was to use openmvg normally with my images and then change the data with my data from my project:
- sfm_data.json - shouldnt be a problem. 
- .feat - looking at the Doc (x,y,s,o) but is orientation from 0-360 degree and is it ok if the size is always same?
- .desc how do i generate one with my descriptors?
- matches.f.txt - are here stored the IDs of each feature Point matching another? Meaning every featurepoint has an ID
Are there any other changes to do?
