### ISSUE TITLE
How to specify camera parameters instead of estimates

### ISSUE THREAD

**Issue by ayu1121** [openMVG/openMVG#1742]
Known exact internal parameters are used，The actual Z value of point cloud should be about 50cm, but the measurement result is about 120.

**Comment by pmoulon** [comment]
Every SfM reconstruction is up to scale.
To bring back the scale you should use some known dimension either by using GPS prior or GCPs or rescale the point cloud in Meshlab/CouldCompare.

https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/
