### ISSUE TITLE
OS X Build - Fatal Error: 'png.h' file not found

### ISSUE THREAD

**Issue by noamsuissa** [openMVG/openMVG#1745]
Initially, after following the steps to build the project on Mac OS X, the build succeeded after executing these two commands:
```
$ cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" . ../openMVG/src/
$ xcodebuild -configuration Release
```
When I encountered an issue when trying to run the tutorial.py script, I attempted to remove mono as was instructed in #1349 . 

When I try to rebuild the project, I now get:
```
/Users/noamsuissa/Documents/openMVG/src/openMVG/image/image_io.cpp:16:12: fatal error: 
      'png.h' file not found
  #include "png.h"
           ^~~~~~~
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/noamsuissa/Documents/openMVG_Build/openMVG/image/openMVG.build/Release/openMVG_image.build/Objects-normal/x86_64/image_io.o openMVG/image/image_io.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Any help would be greatly appreciated.

**Comment by rperrot** [comment]
Did you tried this : 

https://github.com/openMVG/openMVG/issues/1349#issuecomment-403272147

?
