### ISSUE TITLE
 By using linerar Programming can we  solve the Triangulation with the noised data?

### ISSUE THREAD

**Issue by gaihaisong** [openMVG/openMVG#1747]
I wang to solve the triangulation with the noised or outlier data by using the Linerar Programming but there is no such a solution only the solution that tijsAndXis_From_xi_Ri_noise which is to get the 3D Point and the translation by known Rotation and piexl data .Did this algorithm  not exist ?

**Comment by pmoulon** [comment]
Sorry for the late answer.
If you want only to triangulate a 3D point you can use https://github.com/openMVG/openMVG/blob/develop/src/openMVG/linearProgramming/lInfinityCV/triangulation.hpp

**Comment by pmoulon** [comment]
Closing due to lack of feedback
