### ISSUE TITLE
Incremental_sfm information

### ISSUE THREAD

**Issue by Livan89** [openMVG/openMVG#1748]
Good afternoon, colleagues.

Before running the sfm_incremental process I have the matches found between the images, then according to those matches I perform the calibration of the different cameras.

I would like to know if it is possible to have, in addition to the data provided by the sfm, the data of each image, how many matches it discarded with other images and the reason why those matches were discarded. For example, image A has 300 matches with image B, and of those 300 matches 20 were discarded or stopped for an X reason.

Thanks and appreciate any help.

**Comment by pmoulon** [comment]
You could compute from the SfM data visibility information how many matches are kept by pair and compare to the initial number of match in the pair file.
See https://github.com/openMVG/openMVG/blob/5ea386112d7337ee2a91e37b628548f63e1abd6c/src/openMVG/sfm/sfm_data.hpp#L44

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
