### ISSUE TITLE
VS2015-error-LNK1104-cannot open file 'openMVG_matching.lib'

### ISSUE THREAD

**Issue by yangninghua** [openMVG/openMVG#1750]
Hello, I used VS2015 to compile MVG, and there is no problem with Release. But there is an error in the Debug mode, what is the reason for this?

![image](https://user-images.githubusercontent.com/32252319/82675053-cd243e80-9c76-11ea-8568-16a5a1a9ae64.png)

The following are my Release compilation results and Debug compilation results：

Debug:

![image](https://user-images.githubusercontent.com/32252319/82675204-11174380-9c77-11ea-9a84-f037184c697a.png)

Release：

![image](https://user-images.githubusercontent.com/32252319/82675237-196f7e80-9c77-11ea-9c03-48d79d1912fa.png)

**Comment by yangninghua** [comment]
git clone --recursive https://github.com/openMVG/openMVG.git

**Comment by yangninghua** [comment]
I checked the log of the official compilation success. Is it because the version I am using is too new?
https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.776/job/18bkfpfb8f8civkn/tests

So I decided to try another version

**Comment by yangninghua** [comment]
git checkout 606d1c9e82123dd50de282128151a50bf42262fc

it is good！！success

**Comment by pmoulon** [comment]
Happy to hear you got a build running.
