### ISSUE TITLE
Should I remove the distortion before calculate multiview relativepose or reconstruct sparse cloud points?

### ISSUE THREAD

**Issue by SZNero** [openMVG/openMVG#1751]
Should I remove the distortion before calculate multiview relativepose or reconstruct sparse cloud points?

**Comment by pmoulon** [comment]
No it is not required.
But note that you can send undistorted image if you have then and choose the appropriate camera model.

**Comment by SZNero** [comment]
i used the brown_T2 camera model,and choose the features by hands,so the features just had the position and without the description in two views.And i know the matching points.
the code about robustRelativePose 

![image](https://user-images.githubusercontent.com/11623487/82857709-5fad3200-9f44-11ea-87de-49c57c977077.png)

so i doubt that should i change the code  '<cpp>' bearing = (*intrinsics)(x)'</cpp>' to '<cpp>' bearing = intrinsics->get_ud_pixel(x)'</cpp>'   .

**Comment by SZNero** [comment]
when do TriangulateDLT function, i also using the points without distortion.

**Comment by pmoulon** [comment]
Depending of your usage, you must undistort before:
See here we are un-distort the. feature location before calling the localization engine https://github.com/openMVG/openMVG/blob/5ea386112d7337ee2a91e37b628548f63e1abd6c/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L944
