### ISSUE TITLE
Structure from Known Poses produce 0 landmarks

### ISSUE THREAD

**Issue by xiechun-teamlab** [openMVG/openMVG#1752]
### Issue
Hi, 
I installed openMVG and ran the turorial_demo.py. It seems like the pipeline worked fine until "4. Structure from Known Poses (robust triangulation)". The **colud_and_poses.ply** and **colorized.ply** in the output folder looked fine, but the robust.ply contains only camera positions but no landmarks.
The console output around Structure from Known Poses is as below:

> 4. Structure from Known Poses (robust triangulation)
> Compute Structure from the provided poses
> 
> \- Regions Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> \***************************************************
> Loaded a sfm_data scene with:
>  #views: 11
>  #poses: 11
>  #intrinsics: 1
>  #tracks: 0
> \=============================================================
> Robust triangulation of the tracks
>  \- Triangulation of guided epipolar geometry matches
> \=============================================================
> 
> Compute frustum intersection
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> \***************************************************
> Compute pairwise fundamental guided matching:
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> \***************************************************
> Per triplet tracks validation (discard spurious correspondences):
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> \***************************************************
> Tracks to structure conversion:
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> 
> Structure estimation took (s): 0.
> 
> #landmark found: 0
> ...Generating SfM_Report.html
> Found a sfm_data scene with:
>  #views: 11
>  #poses: 11
>  #intrinsics: 1
>  #tracks: 0

I tried the default dataset and my own dataset, the problems are the same.
One strange thing I noticed is that there are no "*****" under the progress bar of  "Tracks to structure conversion:". It seems that this step was skipped without giving any error, but I am not sure.

### System Environment
MacOS 10.15.4
openMVG version: v1.6
CMAKE_CXX_COMPILER: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CMAKE_C_COMPILER:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc

### Dependencies
CEREAL: (external)
EIGEN: 3.3.7 (external)
CERES: 1.14.0 (external)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.1.0 (external)
LIBPNG: 1.6.37 (external)
LIBJPEG (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)

Do you have any idea how to solve this problem?
Thanks in advance.

**Comment by pmoulon** [comment]
Hello @xiechun-teamlab,
Thank you for your feedback.


This is, unfortunately, a known issue on Mac. If you want to help us track what is wrong you help is welcomed.

Please note that this stage is optional and note required to perform a reconstruction. It is just here to demonstrate the additional capability of the library.
Note also that you can triangulate the point in various mode, by default we run the epipolar matching, but you can also triangulate the matches (this mode is not failing on Mac see the mode with matches file [here](https://github.com/openMVG/openMVG/issues/1283#issuecomment-386176459)).

**Comment by xiechun-teamlab** [comment]
Hi @pmoulon ,
Thank you for replying.
So can we say that the problem happens somewhere inside the code below

```
void SfM_Data_Structure_Estimation_From_Known_Poses::run(
  SfM_Data & sfm_data,
  const Pair_Set & pairs,
  const std::shared_ptr<Regions_Provider> & regions_provider,
  const ETriangulationMethod triangulation_method
)
{
  sfm_data.structure.clear();

  match(sfm_data, pairs, regions_provider);
  filter(sfm_data, pairs, regions_provider);
  triangulate(sfm_data, regions_provider, triangulation_method);
}
```

**Comment by pmoulon** [comment]
I would say it most likely happen in match or filter.
triangulate is known to work fine whatever the platform

**Comment by xiechun-teamlab** [comment]
Thank you. I will close this issue and let you know once I have any update.
