### ISSUE TITLE
Using openMVG as 3rd-party library on Mac gives linking error of cereal

### ISSUE THREAD

**Issue by xiechun-teamlab** [openMVG/openMVG#1753]
Hi,

I built openMVG on my Mac and want to use it as a 3rd-party library in my program. 
Then I wrote a simple helloworld program and added openMVG as a dependency. The project was configured using CMake. When I compile the program it gave linking error:

> ld: library not found for -lcereal
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

It looks strange to me because as I know cereal is a header-only library, so there is nothing for the  compiler to use -l to link to. After I removed "-lcereal" from the compile command the program compiled with no error. However every time I reconfigure the project it comes back.

Do you know why "-lcereal" option is automatically added to the compile command? Is it a bug or I did something wrong?

Thank you.

### My simple CMakeList.txt

> cmake_minimum_required(VERSION 3.0.0)
> project(TMSExpCalibration VERSION 0.1.0)
> 
> find_package(OpenMVG REQUIRED)
> find_package(OpenCV COMPONENTS core imgcodecs imgproc features2d flann calib3d highgui REQUIRED)
> 
> add_executable(TMSExpCalibration main.cpp)
> 
> target_link_libraries(${PROJECT_NAME}
>     OpenMVG::openMVG_camera
>     OpenMVG::openMVG_exif
>     OpenMVG::openMVG_features
>     OpenMVG::openMVG_image
>     OpenMVG::openMVG_matching
>     OpenMVG::openMVG_matching_image_collection
>     OpenMVG::openMVG_multiview
>     OpenMVG::openMVG_numeric
>     OpenMVG::openMVG_robust_estimation
>     OpenMVG::openMVG_sfm
>     ${OpenCV_LIBS}
> )
> 
> include_directories(${PROJECT_NAME} ${OpenCV_INCLUDE_DIRS})

### System Environment
MacOS 10.15.4
openMVG version: v1.6
CMAKE_CXX_COMPILER: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CMAKE_C_COMPILER:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc

### Dependencies
CEREAL: (external)
EIGEN: 3.3.7 (external)
CERES: 1.14.0 (external)
FLANN: 1.8.4 (internal)
LIBTIFF: 4.1.0 (external)
LIBPNG: 1.6.37 (external)
LIBJPEG (external)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI: (internal)
LEMON: 1.3 (internal)

**Comment by pmoulon** [comment]
Hi, this is because your machine is already having cereal setup.

You can either force OpenMVG to use its internal cereal version (by commenting this line https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L228) or add this to your make `find_package(cereal QUIET CONFIG)`

Can you try one of this option and let me know how it goes?
and then we can take a look why it happens...

**Comment by xiechun-teamlab** [comment]
Thank you for replying.
I added` find_package(cereal QUIET CONFIG)` to my make and it compiled successfully.
I assumed this would be done automatically by `find_package(OpenMVG REQUIRED)`, as I do not have to explicitly add the other dependencies of openMVG.

**Comment by xiechun-teamlab** [comment]
Hi @pmoulon,
I got another issue when creating my program. When I use openMVG::sfm::Load() to load a SfM_Dada from a file (either .json or .bin), the program report a segmentation fault error:

> TMSExpCalibration(24316,0x10cd4edc0) malloc: *** error for object 0x7ffee72b0598: pointer being freed was not allocated
> TMSExpCalibration(24316,0x10cd4edc0) malloc: *** set a breakpoint in malloc_error_break to debug

While when I run turorial_demo.py everything works fine. Is it caused by the way I link to cereal? How can I solve this?

Thanks.

My source code:

`#include <iostream>
#include <string>
#include "tms_utility.hpp"

#include "opencv2/opencv.hpp"
#include "openMVG/sfm/sfm_data.hpp"
#include "openMVG/sfm/sfm_data_io.hpp"
#include <cereal/archives/json.hpp>

namespace tms
{
    namespace global
    {
        std::string features_dir;
        std::string graycode_dir;
    } // namespace global

} // namespace tms

using namespace openMVG::sfm;
int main(int, char **)
{
    tms::global::features_dir = "./matches/";
    tms::global::graycode_dir = "./data/graycode/";

    std::cout << "TMS Experiment\n";

    SfM_Data sfm_data;
    std::string kSfmDataFn = "/Users/xiechun/OpenMVG/build/software/SfM/tutorial_out/reconstruction_sequential/sfm_data.bin";
   
    if (!Load(sfm_data, kSfmDataFn, ESfM_Data(VIEWS | INTRINSICS))) #segmentation fault
    {
        std::cerr << std::endl
                  << "The input file \"" << kSfmDataFn << "\" cannot be read" << std::endl;
        return EXIT_FAILURE;
    }
    
    tms::utility::MakeCameraData(sfm_data);
    
}
`

**Comment by pmoulon** [comment]
include `#include <cereal/archives/json.hpp>` should not be necessary.
I'm thinking about compilation specifics.
Can you try to build openMVG with `-DTARGET_ARCHITECTURE=core2` or `generic` and see if you still have the issue?

Things should work ok on Ubuntu docker. Mac clang is sometimes giving some difficulties.

**Comment by xiechun-teamlab** [comment]
I am now trying to build openMVG with docker, however` internal compiler error` was reported during compiling.

The compile output:

> [  0%] Building CXX object third_party/vectorGraphics/CMakeFiles/main_svgSample.dir/main.cpp.o
> [  0%] Building CXX object third_party/CppUnitLite/CMakeFiles/CppUnitLite.dir/Failure.cpp.o
> [  0%] Building CXX object third_party/easyexif/CMakeFiles/openMVG_easyexif.dir/exif.cpp.o
> [  1%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/file_system.cpp.o
> [  1%] Building CXX object third_party/CppUnitLite/CMakeFiles/CppUnitLite.dir/SimpleString.cpp.o
> [  1%] Building CXX object third_party/CppUnitLite/CMakeFiles/CppUnitLite.dir/Test.cpp.o
> [  2%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_easyexif.a
> [  2%] Linking CXX executable ../../Linux-x86_64-RELEASE/main_svgSample
> [  2%] Built target openMVG_easyexif
> [  3%] Building CXX object third_party/CppUnitLite/CMakeFiles/CppUnitLite.dir/TestRegistry.cpp.o
> [  3%] Built target main_svgSample
> Scanning dependencies of target openMVG_fast
> [  3%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/fast.c.o
> [  4%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/fast_10.c.o
> [  4%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/portability_fixes.cpp.o
> Scanning dependencies of target openMVG_numeric
> [  4%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_numeric.dir/nullspace.cpp.o
> [  4%] Building CXX object third_party/CppUnitLite/CMakeFiles/CppUnitLite.dir/TestResult.cpp.o
> [  4%] Linking CXX static library ../../Linux-x86_64-RELEASE/libCppUnitLite.a
> [  4%] Built target CppUnitLite
> Scanning dependencies of target openMVG_exif
> [  4%] Building CXX object openMVG/exif/CMakeFiles/openMVG_exif.dir/exif_IO_EasyExif.cpp.o
> [  4%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/wildcard.cpp.o
> [  5%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_stlplus.a
> [  5%] Built target openMVG_stlplus
> Scanning dependencies of target openMVG_system
> [  5%] Building CXX object openMVG/system/CMakeFiles/openMVG_system.dir/timer.cpp.o
> [  5%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/fast_11.c.o
> [  5%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_system.a
> [  5%] Built target openMVG_system
> [  5%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_exif.a
> Scanning dependencies of target openMVG_graph_test_connectedComponent
> [  5%] Built target openMVG_exif
> [  5%] Building CXX object openMVG/graph/CMakeFiles/openMVG_graph_test_connectedComponent.dir/connectedComponent_test.cpp.o
> Scanning dependencies of target openMVG_graph_test_triplet_finder
> [  5%] Building CXX object openMVG/graph/CMakeFiles/openMVG_graph_test_triplet_finder.dir/triplet_finder_test.cpp.o
> [  5%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/fast_12.c.o
> [  6%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/fast_9.c.o
> [  6%] Building CXX object third_party/fast/CMakeFiles/openMVG_fast.dir/nonmax.c.o
> [  6%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_fast.a
> [  6%] Built target openMVG_fast
> Scanning dependencies of target openMVG_test_robust_estimator_lineKernel
> [  6%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_lineKernel.dir/robust_estimator_lineKernel_test.cpp.o
> [  7%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_graph_test_triplet_finder
> [  7%] Built target openMVG_graph_test_triplet_finder
> Scanning dependencies of target openMVG_test_robust_estimator_ACRansac
> [  8%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_ACRansac.dir/robust_estimator_ACRansac_test.cpp.o
> [  8%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_graph_test_connectedComponent
> [  8%] Built target openMVG_graph_test_connectedComponent
> [  8%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_numeric.dir/numeric.cpp.o
> [  8%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_numeric.a
> [  8%] Built target openMVG_numeric
> Scanning dependencies of target openMVG_test_rand_sampling
> [  9%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_rand_sampling.dir/rand_sampling_test.cpp.o
> Scanning dependencies of target openMVG_test_robust_estimator_MaxConsensus
> [  9%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_MaxConsensus.dir/robust_estimator_MaxConsensus_test.cpp.o
> [  9%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_rand_sampling
> [  9%] Built target openMVG_test_rand_sampling
> Scanning dependencies of target openMVG_test_robust_estimator_Ransac
> [ 10%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_test_robust_estimator_Ransac.dir/robust_estimator_Ransac_test.cpp.o
> [ 10%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_robust_estimator_lineKernel
> [ 10%] Built target openMVG_test_robust_estimator_lineKernel
> Scanning dependencies of target openMVG_test_tracks
> [ 11%] Building CXX object openMVG/tracks/CMakeFiles/openMVG_test_tracks.dir/tracks_test.cpp.o
> [ 11%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_robust_estimator_ACRansac
> [ 11%] Built target openMVG_test_robust_estimator_ACRansac
> Scanning dependencies of target openMVG_test_union_find
> [ 11%] Building CXX object openMVG/tracks/CMakeFiles/openMVG_test_union_find.dir/union_find_test.cpp.o
> [ 11%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_tracks
> [ 11%] Built target openMVG_test_tracks
> Scanning dependencies of target openMVG_test_progress
> [ 11%] Building CXX object openMVG/system/CMakeFiles/openMVG_test_progress.dir/progress_test.cpp.o
> [ 11%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_union_find
> [ 11%] Built target openMVG_test_union_find
> Scanning dependencies of target openMVG_test_dynamic_bitset
> [ 12%] Building CXX object openMVG/stl/CMakeFiles/openMVG_test_dynamic_bitset.dir/dynamic_bitset_test.cpp.o
> [ 12%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_robust_estimator_MaxConsensus
> [ 12%] Built target openMVG_test_robust_estimator_MaxConsensus
> Scanning dependencies of target openMVG_test_split
> [ 12%] Building CXX object openMVG/stl/CMakeFiles/openMVG_test_split.dir/split_test.cpp.o
> [ 12%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_progress
> [ 12%] Built target openMVG_test_progress
> Scanning dependencies of target vlsift
> [ 12%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/generic.c.o
> In file included from /usr/include/stdio.h:862:0,
>                  from /opt/openMVG/src/nonFree/sift/vl/generic.c:480:
> In function 'snprintf',
>     inlined from 'vl_configuration_to_string_copy' at /opt/openMVG/src/nonFree/sift/vl/generic.c:536:12:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: warning: '__builtin___snprintf_chk': specified bound between 18446744071562067968 and 18446744073709551615  exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
>    return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>         __bos (__s), __fmt, __va_arg_pack ());
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [ 12%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_dynamic_bitset
> [ 13%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/imopv_sse2.c.o
> [ 13%] Built target openMVG_test_dynamic_bitset
> [ 13%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/sift.c.o
> [ 13%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/imopv.c.o
> [ 13%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_robust_estimator_Ransac
> [ 13%] Built target openMVG_test_robust_estimator_Ransac
> [ 13%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/mathop_sse2.c.o
> [ 13%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_split
> [ 14%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/host.c.o
> In file included from /usr/include/stdio.h:862:0,
>                  from /opt/openMVG/src/nonFree/sift/vl/host.c:356:
> In function 'snprintf',
>     inlined from 'vl_static_configuration_to_string_copy' at /opt/openMVG/src/nonFree/sift/vl/host.c:529:14:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: warning: '__builtin___snprintf_chk': specified bound between 18446744071562067968 and 18446744073709551615  exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
>    return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>         __bos (__s), __fmt, __va_arg_pack ());
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Scanning dependencies of target openMVG_test_Camera_IO
> [ 14%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/mathop.c.o
> [ 14%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_IO.dir/Camera_IO_test.cpp.o
> [ 14%] Built target openMVG_test_split
> [ 14%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/random.c.o
> Scanning dependencies of target openMVG_test_Camera_Subset_Parametrization
> [ 15%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Subset_Parametrization.dir/Camera_Subset_Parametrization_test.cpp.o
> Scanning dependencies of target openMVG_test_Camera_Spherical
> [ 15%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Spherical.dir/Camera_Spherical_test.cpp.o
> [ 16%] Linking C static library ../../Linux-x86_64-RELEASE/libvlsift.a
> [ 16%] Built target vlsift
> Scanning dependencies of target openMVG_test_Camera_Pinhole_Radial
> [ 16%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole_Radial.dir/Camera_Pinhole_Radial_test.cpp.o
> [ 16%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Spherical
> [ 16%] Built target openMVG_test_Camera_Spherical
> Scanning dependencies of target openMVG_test_Camera_Pinhole
> [ 16%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole.dir/Camera_Pinhole_test.cpp.o
> [ 17%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Pinhole_Radial
> [ 17%] Built target openMVG_test_Camera_Pinhole_Radial
> [ 17%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Subset_Parametrization
> Scanning dependencies of target openMVG_test_Camera_Pinhole_Brown
> [ 17%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole_Brown.dir/Camera_Pinhole_Brown_test.cpp.o
> [ 17%] Built target openMVG_test_Camera_Subset_Parametrization
> Scanning dependencies of target openMVG_test_Camera_Pinhole_Fisheye
> [ 17%] Building CXX object openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole_Fisheye.dir/Camera_Pinhole_Fisheye_test.cpp.o
> [ 17%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Pinhole
> [ 17%] Built target openMVG_test_Camera_Pinhole
> Scanning dependencies of target openMVG_features
> [ 17%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/akaze/AKAZE.cpp.o
> [ 17%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Pinhole_Fisheye
> [ 18%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_Pinhole_Brown
> [ 18%] Built target openMVG_test_Camera_Pinhole_Fisheye
> [ 18%] Built target openMVG_test_Camera_Pinhole_Brown
> Scanning dependencies of target openMVG_test_exif_IO
> [ 18%] Building CXX object openMVG/exif/CMakeFiles/openMVG_test_exif_IO.dir/exif_IO_test.cpp.o
> Scanning dependencies of target openMVG_test_ParseDatabase
> [ 19%] Building CXX object openMVG/exif/sensor_width_database/CMakeFiles/openMVG_test_ParseDatabase.dir/ParseDatabase_test.cpp.o
> [ 19%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_exif_IO
> [ 19%] Built target openMVG_test_exif_IO
> Scanning dependencies of target openMVG_image
> [ 19%] Building CXX object openMVG/image/CMakeFiles/openMVG_image.dir/image_io.cpp.o
> [ 20%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_Camera_IO
> [ 20%] Linking CXX executable ../../../Linux-x86_64-RELEASE/openMVG_test_ParseDatabase
> [ 20%] Built target openMVG_test_ParseDatabase
> [ 21%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/akaze/image_describer_akaze.cpp.o
> [ 21%] Built target openMVG_test_Camera_IO
> Scanning dependencies of target openMVG_linearProgramming
> [ 21%] Building CXX object openMVG/linearProgramming/CMakeFiles/openMVG_linearProgramming.dir/linearProgrammingOSI_X.cpp.o
> [ 21%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_image.a
> [ 21%] Built target openMVG_image
> Scanning dependencies of target openMVG_multiview
> [ 21%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/conditioning.cpp.o
> [ 21%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_linearProgramming.a
> [ 21%] Built target openMVG_linearProgramming
> Scanning dependencies of target openMVG_geodesy_test_geodesy
> [ 21%] Building CXX object openMVG/geodesy/CMakeFiles/openMVG_geodesy_test_geodesy.dir/geodesy_test.cpp.o
> [ 21%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/fast/fast_detector.cpp.o
> [ 21%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/feature.cpp.o
> [ 21%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_geodesy_test_geodesy
> [ 21%] Built target openMVG_geodesy_test_geodesy
> Scanning dependencies of target openMVG_geometry
> [ 22%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/Similarity3.cpp.o
> [ 22%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/liop/liop_descriptor.cpp.o
> [ 22%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/essential.cpp.o
> [ 23%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/mser/mser.cpp.o
> [ 23%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/mser/mser_region.cpp.o
> [ 23%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/Similarity3_Kernel.cpp.o
> [ 23%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/regions.cpp.o
> Scanning dependencies of target openMVG_test_extract_columns
> [ 24%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_test_extract_columns.dir/extract_columns_test.cpp.o
> [ 25%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/motion_from_essential.cpp.o
> [ 25%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/box.cpp.o
> [ 25%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_extract_columns
> [ 25%] Built target openMVG_test_extract_columns
> Scanning dependencies of target openMVG_test_l1_solver
> [ 26%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_test_l1_solver.dir/l1_solver_test.cpp.o
> [ 27%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/convex_hull.cpp.o
> [ 27%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/projection.cpp.o
> [ 27%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/frustum.cpp.o
> [ 27%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/svg_features.cpp.o
> [ 27%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/half_space_intersection.cpp.o
> [ 28%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/tbmr/tbmr.cpp.o
> [ 28%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/rotation_averaging_l1.cpp.o
> [ 28%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_l1_solver
> [ 28%] Built target openMVG_test_l1_solver
> Scanning dependencies of target openMVG_test_numeric
> [ 28%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_test_numeric.dir/numeric_test.cpp.o
> [ 28%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_features.a
> [ 28%] Built target openMVG_features
> Scanning dependencies of target openMVG_test_poly
> [ 28%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_test_poly.dir/poly_test.cpp.o
> [ 29%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_numeric
> [ 29%] Built target openMVG_test_numeric
> [ 29%] Building CXX object openMVG/geometry/CMakeFiles/openMVG_geometry.dir/rigid_transformation3D_srt.cpp.o
> [ 30%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_poly
> [ 30%] Built target openMVG_test_poly
> Scanning dependencies of target openMVG_test_lm
> [ 31%] Building CXX object openMVG/numeric/CMakeFiles/openMVG_test_lm.dir/lm_test.cpp.o
> Scanning dependencies of target openMVG_robust_estimation
> [ 32%] Building CXX object openMVG/robust_estimation/CMakeFiles/openMVG_robust_estimation.dir/gms_filter.cpp.o
> [ 32%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/rotation_averaging_l2.cpp.o
> [ 32%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_robust_estimation.a
> [ 32%] Built target openMVG_robust_estimation
> Scanning dependencies of target openMVG_test_global_quantile_gain_offset_alignment
> [ 32%] Building CXX object openMVG/color_harmonization/CMakeFiles/openMVG_test_global_quantile_gain_offset_alignment.dir/global_quantile_gain_offset_alignment_test.cpp.o
> [ 32%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_lm
> [ 32%] Built target openMVG_test_lm
> [ 33%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_global_quantile_gain_offset_alignment
> [ 34%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_affine.cpp.o
> [ 34%] Built target openMVG_test_global_quantile_gain_offset_alignment
> Scanning dependencies of target openMVG_matching
> [ 34%] Building CXX object openMVG/matching/CMakeFiles/openMVG_matching.dir/indMatch_utils.cpp.o
> [ 34%] Building CXX object openMVG/matching/CMakeFiles/openMVG_matching.dir/regions_matcher.cpp.o
> [ 34%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_essential_eight_point.cpp.o
> [ 34%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_essential_five_point.cpp.o
> [ 35%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_geometry.a
> [ 35%] Built target openMVG_geometry
> [ 35%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_essential_kernel.cpp.o
> Scanning dependencies of target openMVG_test_features
> [ 35%] Building CXX object openMVG/features/CMakeFiles/openMVG_test_features.dir/features_test.cpp.o
> [ 36%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_essential_three_point.cpp.o
> [ 37%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_test_features
> [ 37%] Built target openMVG_test_features
> Scanning dependencies of target openMVG_test_image_describer
> [ 37%] Building CXX object openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/image_describer_test.cpp.o
> [ 37%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_fundamental_kernel.cpp.o
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
> make[2]: *** [openMVG/matching/CMakeFiles/openMVG_matching.dir/regions_matcher.cpp.o] Error 4
> openMVG/matching/CMakeFiles/openMVG_matching.dir/build.make:86: recipe for target 'openMVG/matching/CMakeFiles/openMVG_matching.dir/regions_matcher.cpp.o' failed
> CMakeFiles/Makefile2:2837: recipe for target 'openMVG/matching/CMakeFiles/openMVG_matching.dir/all' failed
> make[1]: *** [openMVG/matching/CMakeFiles/openMVG_matching.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 37%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_homography_kernel.cpp.o
> [ 37%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_resection_kernel.cpp.o
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
> make[2]: *** [openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/image_describer_test.cpp.o] Error 4
> openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/build.make:62: recipe for target 'openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/image_describer_test.cpp.o' failed
> CMakeFiles/Makefile2:1123: recipe for target 'openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/all' failed
> make[1]: *** [openMVG/features/CMakeFiles/openMVG_test_image_describer.dir/all] Error 2
> [ 38%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_resection_p3p_ke.cpp.o
> [ 38%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_resection_p3p_kneip.cpp.o
> [ 38%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_resection_p3p_nordberg.cpp.o
> [ 38%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_resection_up2p_kukelova.cpp.o
> [ 39%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/translation_averaging_common.cpp.o
> [ 39%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/translation_averaging_solver_l2_chordal.cpp.o
> [ 39%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/translation_averaging_solver_softl1.cpp.o
> [ 40%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/triangulation.cpp.o
> [ 40%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/triangulation_nview.cpp.o
> [ 40%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_multiview.a
> [ 40%] Built target openMVG_multiview
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
> The command '/bin/sh -c mkdir /opt/openMVG_Build;   cd /opt/openMVG_Build;   cmake -DCMAKE_BUILD_TYPE=RELEASE     -DCMAKE_INSTALL_PREFIX="/opt/openMVG_Build/install"     -DOpenMVG_BUILD_TESTS=ON     -DOpenMVG_BUILD_EXAMPLES=OFF     -DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann     -DLEMON_INCLUDE_DIR_HINTS=/usr/include/lemon     -DCOINUTILS_INCLUDE_DIR_HINTS=/usr/include     -DCLP_INCLUDE_DIR_HINTS=/usr/include     -DOSI_INCLUDE_DIR_HINTS=/usr/include     ../openMVG/src;     make -j 4;' returned a non-zero code: 2
> xiechun@LAB-N1833 openMVG %

**Comment by pmoulon** [comment]
Please add more RAM to your docker instance or build it with less thread (make -j4 -> make -j2)

![image](https://user-images.githubusercontent.com/3235050/83781984-1a73b900-a644-11ea-9f82-ed07d8ad027b.png)

**Comment by xiechun-teamlab** [comment]
> include `#include <cereal/archives/json.hpp>` should not be necessary.
> I'm thinking about compilation specifics.
> Can you try to build openMVG with `-DTARGET_ARCHITECTURE=core2` or `generic` and see if you still have the issue?
> 
> Things should work ok on Ubuntu docker. Mac clang is sometimes giving some difficulties.

Hi @pmoulon ,

Thanks a lot for your help.
`-DTARGET_ARCHITECTURE=core2` seems not a valid option on my system, and `-DTARGET_ARCHITECTURE=generic` did not solve the issue.

But I finally got everything work on Mac by installing gcc9 and using it to recompile openMVG and all its dependencies.

looks like Clang is the source of pain.

**Comment by pmoulon** [comment]
Happy that gcc9 is having good behavior.
