### ISSUE TITLE
No points in final ply file when using own camera pose

### ISSUE THREAD

**Issue by houhaol** [openMVG/openMVG#1755]
Hello, thanks for your great work on this tool.
I tried to use my own camera pose to generate the point cloud. But it failed. I read all other issues about the procedure and explanation you given. I'd like to confirm with you about that. 
1. Intrinsics analysis
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "k", "808.7213745117188;0.0; 540.0;0.0; 808.7213745117188; 540.0;0.0; 0.0; 1.0", "-g", "0"`
Here we can set -k arbitrarily and -g as 0 to ensure each image has own camera intrinsic parameters.

2. Edit the sfm_data.json file. 
Here is the json file i edit.
[sfm_data.txt](https://github.com/openMVG/openMVG/files/4741438/sfm_data.txt)
 I'm very unsure whether my pose json file is correct. But seems no error pop out. Also, i tried the ExportCameraFrustums and the generated the camera pose point cloud make sense.

3. Compute features
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-m", "SIFT"` 

4. Compute matches
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir`

5. Do Sequential/Incremental reconstruction
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_IncrementalSfM"),  "-i", matches_dir+"/sfm_data.json", "-m", matches_dir, "-o", reconstruction_dir`

**Output:**

> SequentialSfMReconstructionEngine::ChooseInitialPair
> ----------------------------------------------------
>  Pairs that have valid intrinsic and high support of points are displayed:
>  Choose one pair manually by typing the two integer indexes
> ----------------------------------------------------
> 
> (13,26)         235 matches
> (12,18)         188 matches
> (12,22)         182 matches
> (14,29)         170 matches
> (6,12)          168 matches
> (18,22)         157 matches
> (18,35)         148 matches
> (22,26)         143 matches
> (3,26)          141 matches
> (12,35)         137 matches
> 
>  type INITIAL pair ids: X enter Y enter
> 13
> 26
> 
> Putative starting pair is: (13,26)
> A-Contrario initial pair residual: 0.123633
> 
> Bundle Adjustment statistics (approximated RMSE):
>  #views: 2
>  #poses: 2
>  #intrinsics: 2
>  #tracks: 125
>  #residuals: 500
>  Initial RMSE: 0.091935
>  Final RMSE: 0.0743902
>  Time (s): 0.103947
> 
> 
> =========================
>  MSE Residual InitialPair Inlier:
> =========================

It let me choose the initial pair. I selected the first one but **no sfm_data.bin** under reconstruction folder. Then i select second one pair. Now one sfm_data.bin showed up. 
**Output:**

> SequentialSfMReconstructionEngine::ChooseInitialPair
> ----------------------------------------------------
>  Pairs that have valid intrinsic and high support of points are displayed:
>  Choose one pair manually by typing the two integer indexes
> ----------------------------------------------------
> 
> (13,26)         235 matches
> (12,18)         188 matches
> (12,22)         182 matches
> (14,29)         170 matches
> (6,12)          168 matches
> (18,22)         157 matches
> (18,35)         148 matches
> (22,26)         143 matches
> (3,26)          141 matches
> (12,35)         137 matches
> 
>  type INITIAL pair ids: X enter Y enter
> 12
> 18
> 
> Putative starting pair is: (12,18)
> A-Contrario initial pair residual: 0.0953276
> 
> Bundle Adjustment statistics (approximated RMSE):
>  #views: 2
>  #poses: 2
>  #intrinsics: 2
>  #tracks: 113
>  #residuals: 452
>  Initial RMSE: 2.25072
>  Final RMSE: 0.0410462
>  Time (s): 0.0733835
> 
> 
> =========================
>  MSE Residual InitialPair Inlier:
> 
> 
> 
> SequentialSfMReconstructionEngine::ComputeResidualsMSE.
>         -- #Tracks:     1
>         -- Residual min:        0.00038715
>         -- Residual median:     0.00237818
>         -- Residual max:         0.00299165
>         -- Residual mean:        0.00154775
> =========================
> 
> -------------------------------
> -- Robust Resection of view: 6
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 38
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 23
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 22
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------
> 
> -------------------------------
> -- Robust Resection of view: 37
> 
> -------------------------------
> -- Robust Resection
> -- Resection status: 0
> -- #Points used for Resection: 1
> -- #Points validated by robust Resection: 0
> -- Threshold: 0
> -------------------------------
> 
> 
> -------------------------------
> -- Structure from Motion (statistics):
> -- #Camera calibrated: 2 from 39 input images.
> -- #Tracks, #3D points: 1
> -------------------------------
> 
> 
> 
> SequentialSfMReconstructionEngine::ComputeResidualsMSE.
>         -- #Tracks:     1
>         -- Residual min:        0.00038715
>         -- Residual median:     0.00237818
>         -- Residual max:         0.00299165
>         -- Residual mean:        0.00154775
> 
> Histogram of residuals:
> 0       |       2
> 0.00026 |       0
> 0.000521        |       0
> 0.000781        |       0
> 0.00104 |       0
> 0.0013  |       0
> 0.00156 |       0
> 0.00182 |       1
> 0.00208 |       0
> 0.00234 |       0
> 0.00299
> 
> 
>  Total Ac-Sfm took (s): 2
> ...Generating SfM_Report.html
> ...Export SfM_Data to disk.

6. Structure from Known Poses (robust triangulation)
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeStructureFromKnownPoses"),  "-i", reconstruction_dir+"/sfm_data.bin", "-m", matches_dir, "-d", "-f", os.path.join(matches_dir, "matches.f.bin"), "-o", os.path.join(reconstruction_dir,"robust.bin")`

> - Regions Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Loaded a sfm_data scene with:
>  #views: 39
>  #poses: 2
>  #intrinsics: 39
>  #tracks: 0
> =============================================================
> Robust triangulation of the tracks
>  - Triangulation of guided epipolar geometry matches
> =============================================================
> Compute pairwise fundamental guided matching:
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Per triplet tracks validation (discard spurious correspondences):
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> Tracks to structure conversion:
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> 
> Structure estimation took (s): 0.
> 
> #landmark found: 0
> ...Generating SfM_Report.html
> Found a sfm_data scene with:
>  #views: 39
>  #poses: 2
>  #intrinsics: 39
>  #tracks: 0
> 

Here no landmark found and no points generated. i'm quite confused which step i made a mistake. I quite suspect it would be my camera pose json file. 

Also, i found it shows two pose, 39 intrinsic. Actually, my camera location is fixed but with different rotation.   

Could you help me and give me some hints? Really appreciate.  

Houhao

**Comment by pmoulon** [comment]
You must use openMVG_main_IncrementalSfM2 see here
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_IncrementalSfM2.cpp#L108
`-S EXISTING_POSE`

> Actually, my camera location is fixed but with different rotation.
If you have only a rotating camera you will not be able to do SfM, you will need some camera translation.

**Comment by lianghouhao** [comment]
> You must use openMVG_main_IncrementalSfM2 see here
> https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_IncrementalSfM2.cpp#L108
> `-S EXISTING_POSE`
> 
> > Actually, my camera location is fixed but with different rotation.
> > If you have only a rotating camera you will not be able to do SfM, you will need some camera translation.

Thanks for your reply. 
I switched to openMVG_main_IncrementalSfM2 method as you said, like that
`os.path.join(OPENMVG_SFM_BIN, "openMVG_main_IncrementalSfM2"),  "-i", matches_dir+"/sfm_data.json", "-m", matches_dir, "-o", reconstruction_dir, "-S", "EXISTING_POSE"`

But still no points were tracked. The terminal output:

> Sequential/Incremental reconstruction (Engine 2)
> 
> 
> - Features Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Initialization status : Success
> 
> Track stats
> ------------------
> -- Tracks Stats --
>  Tracks number: 945
>  Images Id:
> 0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 26, 27, 29, 30, 31, 32, 33, 34, 35, 37, 38,
> ------------------
> TrackLength, Occurrence
>         2       329
>         3       151
>         4       119
>         5       81
>         6       59
>         7       50
>         8       36
>         9       33
>         10      40
>         11      23
>         12      9
>         13      9
>         14      4
>         15      1
>         25      1
> 
> 
> 
> -------------------------------
> -- Starting Structure from Motion (statistics) with:
> -- #Camera calibrated: 39 from 39 input images.
> -- #Tracks, #3D points: 0
> -------------------------------
> 
> Bundle Adjustment statistics (approximated RMSE):
>  #views: 39
>  #poses: 39
>  #intrinsics: 39
>  #tracks: 0
>  #residuals: 0
>  Initial RMSE: -nan
>  Final RMSE: -nan
>  Time (s): 8.7303e-05
> 
> 
> 
> -------------------------------
> -- Structure from Motion (statistics):
> -- #Camera calibrated: 39 from 39 input images.
> -- #Tracks, #3D points: 0
> -- #Poses loop used: 0
> -------------------------------
> 
>  Total Ac-Sfm took (s): 0
> ...Generating SfM_Report.html
> ...Export SfM_Data to disk.

#3D points tracked is still 0. Do you have any ideas about the reason?

**Comment by pmoulon** [comment]
Are you sure that the camera position you are sending to OpenMVG are good?
- you can check with calling exportCameraFrustum binary

I also notice that your images have very few tracks, you could try extract more point at `openMVG_main_ComputeFeatures ` stage by adding `-p HIGH`

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
