### ISSUE TITLE
Convert RGB cv::Mat to openMVG::Image

### ISSUE THREAD

**Issue by a-mohsen** [openMVG/openMVG#1758]
I want to convert cv::Mat to openMVG::Image.
I checked this issue
https://github.com/openMVG/openMVG/issues/872
But it only mentioned the grayscale images.
Is there anyway to convert OpenCV RGB image and vice versa (from Image to Mat)?

**Comment by pmoulon** [comment]
You can directly copy the pixel arrays.

Here some snippets that should help you, we can create a dedicated section on the WIKI for future usage:
```
    // Color CV to OpenMVG
    {
      cv::Mat cv_image;
      cv_image = cv::imread( image_filename );
      Image<RGBColor> openmvg_image;
      openmvg_image.resize(cv_image.cols, cv_image.rows);
      cv::cvtColor(cv_image, cv_image, CV_BGR2RGB);
      memcpy(openmvg_image.data(), static_cast<unsigned char*>(cv_image.data), cv_image.cols * cv_image.rows * 3);
      WriteImage("rgb_cv_to_openmvg.png", openmvg_image);
    }
// GRAY
  {
    // CV to OpenMVG
    {
      cv::Mat cv_image;
      cv_image = cv::imread( image_filename, CV_LOAD_IMAGE_GRAYSCALE );
      Image<uint8_t> openmvg_image;
      openmvg_image.resize(cv_image.cols, cv_image.rows);
      cv::cv2eigen(cv_image, *(Image<uint8_t>::Base*)&openmvg_image);
      WriteImage("gray_cv_to_openmvg.png", openmvg_image);
    }
    // OpenMVG to CV
    {
      Image<uint8_t> openmvg_image;
      ReadImage(image_filename.c_str(), &openmvg_image);
      cv::Mat cv_image;
      cv::eigen2cv(openmvg_image.GetMat(), cv_image);
      cv::imwrite("gray_openmvg_to_cv.png", cv_image);
    }
  }

```

**Comment by a-mohsen** [comment]
Thank you so much!
But can I use `eigen2cv` with RGB images ?
because when I tried the above, I got this error
`/usr/local/include/opencv2/core/traits.hpp:366:8: error: 'type' is not a member of 'cv::DataType<openMVG::image::Rgb<unsigned char> >'`

**Comment by pmoulon** [comment]
Eigen2cv works only for single type (char, float, double, ...), not for compound type (aka RGB).
In the example I shared to you I show how to copy the raw pixel array

**Comment by a-mohsen** [comment]
I got it.
Thank you so much.
