### ISSUE TITLE
SIFT patent expired

### ISSUE THREAD

**Issue by tompollok** [openMVG/openMVG#1759]
In the code it says that SIFT is patented. See related post in opencv https://github.com/opencv/opencv/issues/16736

https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/sift/sift_KeypointExtractor.hpp

**Comment by pmoulon** [comment]
Thank you for your comment.
You are right we could update the mention and say that now the patent has expired
I will mark this issue as an item we want to consider for the next version.

**Comment by tompollok** [comment]
maybe the nonfree folder then is also not needed anymore?

https://github.com/openMVG/openMVG/tree/develop/src/nonFree

**Comment by pmoulon** [comment]
Sift patent has expired on `2020-03-06`
- [ ] Fix src\openMVG\features\sift accordingly
