### ISSUE TITLE
Apple Clang 11 segfault: stack_not_16_byte_aligned_error

### ISSUE THREAD

**Issue by csparker247** [openMVG/openMVG#1764]
I've been getting segfaults when running any of the SfM reconstruction binaries on macOS Catalina. However, whenever I'd compile debug binaries, the segfaults would go away. Recently, I compiled `RelWithDebInfo` binaries, got the segfault, and could stack trace it. The result was:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00007fff6e78070a libdyld.dylib`stack_not_16_byte_aligned_error
libdyld.dylib`stack_not_16_byte_aligned_error:
->  0x7fff6e78070a <+0>: movdqa %xmm0, (%rsp)
    0x7fff6e78070f <+5>: int3   
    0x7fff6e780710 <+6>: nop    

libdyld.dylib`_dyld_fast_stub_entry:
    0x7fff6e780711 <+0>: pushq  %rbp
Target 0: (openMVG_main_GlobalSfM) stopped.
```

This is a [fairly common issue](https://github.com/Homebrew/homebrew-core/issues/44776) that's shown up in many other open source projects since the Catalina compilers were released. It appears to be a caused by [a bad combination](https://developer.apple.com/forums/thread/121887?answerId=380349022#380349022) of AVX instructions, O2 optimization, and AppleClang11 adding `-fstack-trace` to things by default. The optimization flags, of course, explain why I was only seeing this on Release builds.

The standard workaround for this issue is to add `-fno-stack-trace` to the CXX_FLAGS. I've been building OpenMVG in another CMake project using `ExternalProject_Add`, so for my purposes, I'm passing the appropriate command line flag:
```
cmake -DCMAKE_CXX_FLAGS=-fno-stack-check ..
```

It might be good to add this to the OpenMVG project, though, using `add_compile_options` or `target_compile_options`:

```cmake
if(NOT ${CMAKE_BUILD_TYPE} STREQUAL "Debug")
if(${CMAKE_CXX_COMPILER_ID} STREQUAL "AppleClang")
if (${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER_EQUAL 11)
    message(STATUS "AppleClang 11+ detected. Disabling stack check.")
    add_compile_options(-fno-stack-check)
endif()
endif()
endif()
```

If this is something you think should be integrated, let me know and I can open a pull request.

**Comment by pmoulon** [comment]
Thank you for your feedback.
Appreciated.

I don't have any issue with Catalina and `Apple clang version 11.0.3 (clang-1103.0.32.59)` on my side.

Let's see if other people encounter the same issue and if we need to integrate your fix to the project.

**Comment by pmoulon** [comment]
Note: `target_compile_options` would help to propagate the flag to anyone using the library as a 3rd party project

**Comment by csparker247** [comment]
> I don't have any issue with Catalina and `Apple clang version 11.0.3 (clang-1103.0.32.59)` on my side.

Very interesting! I only have version 11.0.0, and macOS is not offering me any updates. I only use the command line tools though and not full Xcode, so maybe that has something to do with not having a more recent version. 

This implies that they've patched their toolkit at some point, so this fix could be updated with bounds on the version. It might also be so niche, though, that it's not worth integrating. It may be enough to just point affected parties to this issue and have them add the appropriate CXX_FLAG. 

I'll look into why I don't have a newer AppleClang. If this can be fixed by a simple reinstall of the CLT, this hardly seems like something your project should have to maintain.

**Comment by csparker247** [comment]
I've confirmed that uninstalling and reinstalling the CL Tools gives me `Apple clang version 11.0.3 (clang-1103.0.32.62)`.  Additionally, I do not get segfaults on Release builds using this version of clang. Why I wasn't being offered this version of clang as an update, we may never know.

Anyway, I feel like this is something you probably don't need to integrate, so I'll go ahead and close this. Thanks!
