### ISSUE TITLE
Manually clean sfm result by gui like Meshlab and then export back to sfm_data.bin

### ISSUE THREAD

**Issue by deHsien** [openMVG/openMVG#1766]
I would like to remove redundant points in the final sfm_data.bin.  
openMVG_main_PointsFiltering (#997, #987, #863) doesn't meet my expectation.  
Therefore, I want to manually clean redundant points through gui like Meshlab and then export back to sfm_data.bin for the following mvs stages.  
Can this be achieved?

**Comment by rjanvier** [comment]
Not yet. On my opinion, it could be a nice addition you could try to add to CloudCompare (throught the plugin interface)

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
