### ISSUE TITLE
Is it possible to run algorithm with the following camera calibration information?

### ISSUE THREAD

**Issue by Hiltona99** [openMVG/openMVG#1772]
I am trying to run the openMVG pipeline on a dataset that does not have any exif data. But I have the following information about the camera:

[INTERNAL]
NX   =        752  # Image dimension in pixel X(U)
NY   =        560  # Image dimension in pixel Y(V)
FC_U = 861.988806  # Focal length in pixel (U)
FC_V = 865.407108  # Focal length in pixel (V)
CC_U = 437.854624  # Principle point in pixel (U)
CC_V = 308.865083  # Principle point in pixel (V)
SKEW =   0.000000  # Skew factor
KC_1 =  -0.313006  # Distortion factor
KC_2 =   0.265111  # Distortion factor
KC_3 =   0.002803  # Distortion factor
KC_4 =   0.002722  # Distortion factor
KC_5 =   0.000000  # Distortion factor

[EXTERNAL]
TC_X =   0.000000  # Translation X [mm]
TC_Y =   0.000000  # Translation Y [mm]
TC_Z =   0.000000  # Translation Z [mm]
RC11 =   1.000000  # Rotation matrix
RC12 =   0.000000
RC13 =   0.000000
RC21 =   0.000000
RC22 =   1.000000
RC23 =   0.000000
RC31 =   0.000000
RC32 =   0.000000
RC33 =   1.000000

HEIGHT = 0.0000  # Height [m]

Is it possible to determine the sensor width of the camera from this information or some other solution to be able to use this dataset? I have no other knowledge about the camera used.

**Comment by csparker247** [comment]
`openMVG_main_SfMInit_ImageListing` uses the sensor width and the recorded focal length to calculate the focal length in pixels. You have everything you need to initialize either a Radial3 intrinsic or a BrownT2 intrinsic. 

If your dataset is in one of [the formats supported by openMVG_main_SfMInit_ImageListingFromKnownPoses](https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/import/main_SfMInit_ImageListingFromKnownPoses.cpp#L77), you can use that app.

If all of your images were taken with the same camera, then the easiest way to import the focal length is to use the `--focal` flag on `SfMInit_ImageListing`. The value you give is assumed to be focal length in pixels. The creates an `sfm_data.json` like so:
```json
{
    "sfm_data_version": "0.3",
    "root_path": ".",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "test_image.jpg",
                        "width": 2448,
                        "height": 2048,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "width": 2448,
                        "height": 2048,
                        "focal_length": 865.0,
                        "principal_point": [
                            1224.0,
                            1024.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}
```

Once this file is created, you can update the `principal_point` and `disto_k3` fields to match your file. Note that the radial (k3) parameters in your camera calibration file are probably the KC_1, KC_2, and KC_5 values. If you want to use all 5 distortion values, add the `--camera_model 4` flag to your SfMInit. You'll then get an intrinsic with 5 parameters which you will fill, in order, with your KC values:

```json
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_brown_t2",
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "value0": {
                            "width": 2448,
                            "height": 2048,
                            "focal_length": 865.0,
                            "principal_point": [
                                1224.0,
                                1024.0
                            ]
                        },
                        "disto_t2": [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ]
```

If your images were taken with more than one camera, it gets trickier. You can write and contribute [your own importer](https://github.com/openMVG/openMVG/tree/develop/src/software/SfM/import). Alternatively (shameless self-promotion), I just released [a Python package](https://pypi.org/project/PySfMUtils/) that I wrote to help me solve a similar problem with my own data. You'd have to write the logic around parsing your configuration files for each image, but the export to OpenMVG is handled for you.
