### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by MaryElna** [openMVG/openMVG#1776]
Hi,
I want to appreciate for developing of this useful application,
but I haven't succeeded to install it in my ubuntu16.04.06  system yet
the error occurs  after  type and run "cmake --build . --target install" command

![image](https://user-images.githubusercontent.com/60619370/89097711-5b910b00-d3f2-11ea-9654-c436f90591c0.png)

![image](https://user-images.githubusercontent.com/60619370/89097727-8a0ee600-d3f2-11ea-9ab4-84b899e1cea6.png)

(openMVG/multiview/CMakeFiles/openMVG_multiview.dir/build.make:134: recipe for target 'openMVG/multiview/CMakeFiles/openMVG_multiview.dir/rotation_averaging_l1.cpp.o' failed
make[2]: *** [openMVG/multiview/CMakeFiles/openMVG_multiview.dir/rotation_averaging_l1.cpp.o] Error 1
CMakeFiles/Makefile2:2696: recipe for target 'openMVG/multiview/CMakeFiles/openMVG_multiview.dir/all' failed
make[1]: *** [openMVG/multiview/CMakeFiles/openMVG_multiview.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2)

Im looking forward for your helpful commands
Best Regards

**Comment by pmoulon** [comment]
It seems that you are using a local ceres and that it is using some CXX standard that is not activated in OpenMVG.
By default OpenMVG activate c++11
Integer_sequence is c++14 -> https://en.cppreference.com/w/cpp/utility/integer_sequence

You can try to change here from `11` to `14` -> https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L122

**Comment by pmoulon** [comment]
Closing due to lack of feedback
