### ISSUE TITLE
Merge two sfm_data.bin

### ISSUE THREAD

**Issue by tangeroo** [openMVG/openMVG#1777]
Hi,
  Thank you for the excellent work.
  I have got two sfm_data.bin. They have same images and only landmarks and features are different, how can I merge these two files to one.
  Thank you.

**Comment by pmoulon** [comment]
Hello @tangeroo,
Today we don't have any implementation to do that.

You could implement the merge function of the files in c++ using OpenMVG data structure or using Python if you use the sfm_data.json (sfm_data converter).

If the camera poses are the same within the two files:
- Then you just need to merge the landmark according to the visibility information
  - need to merge the tracks that shares the tuples (idView & idFeat)-> can be done efficiently by using map<> or union find
- Retriangulate eventually to update the 3D position of the landmarks

If the camera poses are different, you need:
-  need to merge the landmark according to the visibility information
  - need to merge the tracks that shares the tuples (idView & idFeat)-> can be done efficiently by using map<> or union find
- need to map the two sfm_data coordinate together by computing a rigid transform between the common camera ids (you can use existing OpenMVG for that)
- Retriangulate to update the 3D position of the landmarks

Let us know if this make sense.
I remember one thread trying to do it ... but I cannot see it, users shared some code in the Github thread.
