### ISSUE TITLE
About ui_openMVG_MatchesViewer

### ISSUE THREAD

**Issue by ayu1121** [openMVG/openMVG#1778]
When clicking, only matching lines can be displayed, and images used for matching will not be displayed. The terminal 

couldn't create image from  "image/0042.PNG"
couldn't create image from  "image/0044.PNG"

How to solve this problem.
thank you

**Comment by rperrot** [comment]
Do you have the issue only on a couple of image or this all images ? Did you compile Qt with PNG files ? Is there any warning related to imageformat (qt warnings) at compilation/execution ?

**Comment by ayu1121** [comment]
All images are wired without background. Do PNG images need special compilation? Where is it? There is no QT warning when executing
