### ISSUE TITLE
Distributed System Approach

### ISSUE THREAD

**Issue by jchen706** [openMVG/openMVG#1779]
I wonder if openMVG can be customized to more than one computer approach, i looked at the main cluster's, wonder anyone had any experience with doing the point cloud in a distributed systems approach like divide the set of images into clusters of images and do features, point cloud and pipeline to openMVS and then merge at the end of the openMVS pipeline at the texture Mesh for 3D reconstruction?

**Comment by rperrot** [comment]
We have a clustering approach that can split result of SfM (a single sfm_data) into multiple sets (ie: multiple sfm_data) that can be used later for openMVS or any other tools. 

Check it here : 

https://github.com/openMVG/openMVG/tree/develop/src/software/SfM/clustering

We do not have yet distributed SfM Approach in the main branch. There is some work here, but still not usable in production : 

https://github.com/openMVG/openMVG/issues/1015

**Comment by AIBluefisher** [comment]
I would be like to commit my distributed implementation to OpenMVG. But it needs a period of time and also some experiments.

**Comment by rperrot** [comment]
Feel free to open a new pull request with your existing code (if it works
on some samples). Even if it's not fully finished, the community is here to
help finishing the code to make it more robust and faster.

Thanks for your contribution.

**Comment by AIBluefisher** [comment]
That’s good. But it's really a big project. As I have implemented a distributed matching pipeline and distributed SfM pipeline, and also a map reduce implementation for really distributed system. So, it needs some time to transfer the code. Can we have a discussion on how to complete this work? What do you think of? @pmoulon @rperrot

**Comment by rperrot** [comment]
Ok, I understand. I think it's preferable to open multiple PR, one per feature : distributed matching, distributed sfm, ... .

**Comment by pmoulon** [comment]
I would agree with @rperrot if we can succeed to make each PR corresponding to individual features it would be the best.
- One other possibility is creating a new repo in our OpenMVG community for some tools if you are using OpenMVG as a third party library

**Comment by AIBluefisher** [comment]
@pmoulon Could I have your personal email? As there are some details I want to have a talk. You can find my email on my Github main page.
