### ISSUE TITLE
GCP UI not displayed 

### ISSUE THREAD

**Issue by MaryElna** [openMVG/openMVG#1780]
Hi, despite of what said in  #1559,  I cant run GCP ui with double click on ui_openMVG_control_points_registration!

![image](https://user-images.githubusercontent.com/60619370/90021938-21afe680-dcc7-11ea-8e0e-868605807a81.png)

**Comment by pmoulon** [comment]
Can you try to open it from the command line to see if you have other debug messages?

**Comment by MaryElna** [comment]
yes, Thats right,It opens from command line 
Thanks
