### ISSUE TITLE
Include header file in C++ project error

### ISSUE THREAD

**Issue by LilyWangL** [openMVG/openMVG#1782]
I use VCPKG install openmvg successfully. When I include _openMVG/sfm/sfm_data_io_baf.hpp_ in C++ project, I get error: `fatal error C1083: Cannot open include file: 'third_party/stlplus3/filesystemSimplified/file_system.hpp': No such file or directory`. I found these codes in _src/third_party/CMakeLists.txt_:
```
install(
  DIRECTORY ./${inDirectory}
  DESTINATION ${CMAKE_INSTALL_PREFIX}/include/openMVG/third_party/
  COMPONENT headers
  FILES_MATCHING PATTERN "*.hpp" PATTERN "*.h"
)
```
The directory _third_party_ will be installed to _include/openMVG/_. Could anyone help to confirm this issue? Thanks.

**Comment by pmoulon** [comment]
The file file_system.hpp should be exported, but it seems that its installation location is not propagated as an include.
Can you try to manually add the location of the ${CMAKE_INSTALL_PREFIX}/include/openMVG to your cmake and see if it works?

**Comment by JackBoosY** [comment]
But that's only a workaround right? I think openMVG should consider to fix this issue.

**Comment by pmoulon** [comment]
Sure, my idea was to identify the source of the issue and be sure about the possible fix to apply.
Please note that the VCPKG configuration could be a bit different from the native OpenMVG project (3rd libraries can be used in different ways and so create different behavior we never saw before).

Let's try to see if it is happening for the native project and fix it where it happens

**Comment by LilyWangL** [comment]
Yeah, I test manually add the location of the _${CMAKE_INSTALL_PREFIX}/include/openMVG_ to my C++ project, the error `fatal error C1083: Cannot open include file: 'third_party/stlplus3/filesystemSimplified/file_system.hpp': No such file or directory` disappeared.
