### ISSUE TITLE
Is it possible to provide my own matches data?

### ISSUE THREAD

**Issue by IdanVT** [openMVG/openMVG#1783]
Hi to all,
First I want to say this is an amazing project.

I have a set of images (~500) from different angles (X ,Y ,Z) , I know (From calibration screen) ~100 features that I know how to match them in all images.
I want to create my own match data and provide it to openMVG_main_IncrementalSfM.
It's mean I want to find a way to create all files from the matches dir by myself.
There is any guide that can help me?

**Comment by pmoulon** [comment]
There is no guide yet, but we (the community) should work on doing one.
Basically you have to create the .feat and the matches.X.txt -> those files could be ASCII
I will try to give more details here soon
