### ISSUE TITLE
Global SfM terminated without result

### ISSUE THREAD

**Issue by MaryElna** [openMVG/openMVG#1784]
Hi,
I want to run Global SfM pipeline on some aerial photos , the program stops without any appropriate results, so  whats your comment to fix this problem?
Best Regards  

VirtualBox:~/openMVG_Build/software/SfM$ python SfM_GlobalPipeline.py ~/OpenMVG_test/test/images/orginal ~/OpenMVG_test/test/output  
('Using input dir  : ', '/home/ma/OpenMVG_test/test/images/orginal')
('      output_dir : ', '/home/ma/OpenMVG_test/test/output')
1. Intrinsics analysis
 You called : 
/home/ma/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/ma/OpenMVG_test/test/images/orginal
--sensorWidthDatabase /home/ma/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/ma/OpenMVG_test/test/output/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
DJI_T20072" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20073" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20074" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20075" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20086" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20087" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20088" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20089" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20090" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20242" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20243" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20244" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_T20245" model "FC6310S" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

SfMInit_ImageListing report:
listed #File(s): 13
usable #File(s) listed in sfm_data: 13
usable #Intrinsic(s) listed in sfm_data: 0
2. Compute features
 You called : 
/home/ma/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /home/ma/OpenMVG_test/test/output/matches/sfm_data.json
--outdir /home/ma/OpenMVG_test/test/output/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 76
3. Compute matches
 You called : 
/home/ma/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /home/ma/OpenMVG_test/test/output/matches/sfm_data.json
--out_dir /home/ma/OpenMVG_test/test/output/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 14

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
	#nodes: 13
	#cc: 13
	#singleton: 13
	Node degree statistics:	min: 1, max: 0, mean: -243001397, median: 32666

 Export Adjacency Matrix of the pairwise's geometric matches
4. Do Global reconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0
Invalid input image graph for global SfM
5. Colorize Structure

The input SfM_Data file "/home/ma/OpenMVG_test/test/output/reconstruction_global/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/home/ma/OpenMVG_test/test/output/reconstruction_global/sfm_data.bin" cannot be read.

The input SfM_Data file "/home/ma/OpenMVG_test/test/output/reconstruction_global/robust.bin" cannot be read.

**Comment by pmoulon** [comment]
You have this error because the camera model `FC6310S` is not in the camera sensor database under the name you have in your EXIF data.
Just try to add a line below this one https://github.com/openMVG/openMVG/blob/develop/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt#L1338
`FC6310S;13.2`
and you should be good.

**Comment by MasaruPutut** [comment]
How do you know the width of camera sensor? it's in mm or cm?
I use my Realme Narzo to take get dataset..

**Comment by rperrot** [comment]
It's always in mm, it's value is sometimes indicated in the datasheet of the builder of the device or if it's a generic sensor it is listed in some of the sensor database available in some websites (dxomark for example).
