### ISSUE TITLE
Best settings to handle reflections

### ISSUE THREAD

**Issue by mattangus** [openMVG/openMVG#1787]
Hi,

I've been using this software for some time now! I'm wondering if anyone can give some advice for the best settings for handling reflections in windows. For example the image below, the features extracted are often the intersection of an edge in the reflection and an edge behind the window. The reconstruction it okay but the is quit a bit of error (especially in the rotation). Is there another feature extractor that is better suited for this? Thanks!

![image](https://user-images.githubusercontent.com/5302804/90898499-a03f0f00-e3be-11ea-840d-c34b89701032.png)

**Comment by mattangus** [comment]
Thanks for your suggestion! That seemed to help a little but after playing around with it, turns out there are a number of times where the vehicle is stopped (no translation or rotation) that were causing the problem. Is there currently any way to detect that and ignore images?

**Comment by rperrot** [comment]
> turns out there are a number of times where the vehicle is stopped (no translation or rotation) that were causing the problem

So you mean that you give openMVG multiple "almost" identical images ? You need to give different images as input. You can compute optical flow between pairs of successives images and when motion is lower than a threshold you discard them.

**Comment by mattangus** [comment]
That's exactly what I mean. Great idea! I will do that, thanks for your help 😁
