### ISSUE TITLE
What causes singleton nodes?

### ISSUE THREAD

**Issue by Hiltona99** [openMVG/openMVG#1789]
The algorithm is terminating in the incrementalSfm step and I believe it is due to the the nodes for the matches being singleton nodes. What causes them to be singletons and how can i fix it?

Here is the output from the algorithm:

 You called : 
/Users/andrewhlton/openMVG/Darwin-x86_64-RELEASE/Release/openMVG_main_SfMInit_ImageListing
--imageDirectory /Users/andrewhlton/3d_reconstruction/python_background_sub/full_jpgs_2
--sensorWidthDatabase /Users/andrewhlton/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /Users/andrewhlton/3d_reconstruction/python_background_sub/full_output_2/sfm/matches
--focal 861.989
--intrinsics 
--camera_model 4
--group_camera_model 0

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 3
usable #File(s) listed in sfm_data: 3
usable #Intrinsic(s) listed in sfm_data: 3

You called : 
/Users/andrewhlton/openMVG/Darwin-x86_64-RELEASE/Release/openMVG_main_ComputeFeatures
--input_file /Users/andrewhlton/3d_reconstruction/python_background_sub/full_output_2/sfm/matches/sfm_data.json
--outdir /Users/andrewhlton/3d_reconstruction/python_background_sub/full_output_2/sfm/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0

You called : 
/Users/andrewhlton/openMVG/Darwin-x86_64-RELEASE/Release/openMVG_main_ComputeMatches
--input_file /Users/andrewhlton/3d_reconstruction/python_background_sub/full_output_2/sfm/matches/sfm_data.json
--out_dir /Users/andrewhlton/3d_reconstruction/python_background_sub/full_output_2/sfm/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method HNSWL2
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using HNSWL2 matcher

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
	#nodes: 3
	#cc: 3
	#singleton: 3
	Node degree statistics:	min: -1760643808, max: 32767, mean: -346538208, median: 32766

Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 0
 Images Id: 

------------------
TrackLength, Occurrence

Terminates here.

**Comment by pmoulon** [comment]
Seeing singletons at the image matching steps basically means that no coherent feature matches and geometric models have been found in your image sequences.

You can try to extract more features per image and see if it helps by using `-p HIGH -f 1` on openMVG_main_ComputeFeatures

**Comment by Hiltona99** [comment]
Thank you @pmoulon this has solved my issue.

**Comment by pmoulon** [comment]
🎉  Have fun with OpenMVG ;-)
