### ISSUE TITLE
[openSUSE] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by kevinsmia1939** [openMVG/openMVG#1790]
Hello,

I am trying to package openMVG 1.6 to openSUSE Tumbleweed.
The build repo is here on open build service: https://build.opensuse.org/package/show/home:andythe_great:branches:graphics/openMVG
So I am trying to run some samples using the command below.

I'm aware that there is not much info to work on, could you suggest how to debug this?

Thank you.

```
openMVG_main_SfMInit_ImageListing -d /home/kev/Desktop/openmvg-test/sensor_width_camera_database.txt -i /home/kev/Desktop/openmvg-test/CognacGardenBuilding/ -o /home/kev/Desktop/openmvg-test/output/
```
Error I got

```
 -i /home/kev/Desktop/openmvg-test/CognacGardenBuilding/ -o /home/kev/Desktop/openmvg-test/output/
 You called : 
openMVG_main_SfMInit_ImageListing
--imageDirectory /home/kev/Desktop/openmvg-test/CognacGardenBuilding/
--sensorWidthDatabase /home/kev/Desktop/openmvg-test/sensor_width_camera_database.txt
--outputDirectory /home/kev/Desktop/openmvg-test/output/
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Illegal instruction (core dumped)
```

Install dependencies to build openMVG shown below.
```
blas-devel
cereal-devel
clang
doxygen
gcc
gcc-c++
ghostscript
glpk-devel
graphviz
lapack-devel
pkgconfig(Coin)
pkgconfig(Qt5Core)
pkgconfig(Qt5OpenGL)
pkgconfig(Qt5Svg)
pkgconfig(Qt5Widgets)
pkgconfig(eigen3)
pkgconfig(libjpeg)
pkgconfig(libpng16)
pkgconfig(libtiff-4)
pkgconfig(xi)
pkgconfig(xrandr)
pkgconfig(xxf86vm)
```

PC spec
```
Operating System: openSUSE Tumbleweed 20200824
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.0-1-default
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000
```

**Comment by lexvandersluijs** [comment]
Just a quick note, maybe it helps get you on the right track. Considering that this processor is from 2012 (https://ark.intel.com/content/www/us/en/ark/products/65719/intel-core-i7-3770-processor-8m-cache-up-to-3-90-ghz.html), and that it doesn't support the AVX2 instruction set, perhaps the program was compiled with AVX2 instructions (or another instruction set which is not supported) which cannot run on your CPU. 

It's just a thought, not a solution, but perhaps it helps.

**Comment by pmoulon** [comment]
FYI you can compile OpenMVG in `-DTARGET_ARCHITECTURE=generic`, this way you will support most of the processor but lose some potential speed up you can have. If you know the kind of architecture you target you can use `core2` ... or some other.

See here what we do for the snap build https://github.com/openMVG/openMVG/blob/develop/dist/snap/snapcraft.yaml#L148

**Comment by kevinsmia1939** [comment]
> FYI you can compile OpenMVG in `-DTARGET_ARCHITECTURE=generic`, this way you will support most of the processor but lose some potential speed up you can have. If you know the kind of architecture you target you can use `core2` ... or some other.
> 
> See here what we do for the snap build https://github.com/openMVG/openMVG/blob/develop/dist/snap/snapcraft.yaml#L148

Adding -DTARGET_ARCHITECTURE=generic works thanks.

**Comment by pmoulon** [comment]
Happy to hear 🎉
