### ISSUE TITLE
Is it possible to refine the camera intrinsics by using GCPs?

### ISSUE THREAD

**Issue by shercode24** [openMVG/openMVG#1791]
I have performed the Global SfM process on my dataset and have used the GUI to set a few Ground Control Points that i know the coordinates of. Now I would like to know if it's possible to refine the camera intrinsics by removing possible nonlinear deformations with the help of the known GCPs? The outputfile of the GCP registration still uses the same intrinsics as before and I haven't found an other option to readjust the intrinsics with the help of GCPs. Is that possible with Open MVG?

**Comment by pmoulon** [comment]
Yes it is possible. Bundle adjustment will use all your data
