### ISSUE TITLE
Reconstruction with stereo images

### ISSUE THREAD

**Issue by karthikarvind1295** [openMVG/openMVG#1794]
Hey guys. 
I am new to openMVG
I am currently working on reconstruction with stereo images. Does openMVG support reconstruction with stereo images ? Or should i just compute the SfM for any one of the image captured by the stereo camera ?

**Comment by pmoulon** [comment]
We don't support the RIG configuration yet.
But you can provide either one image of the rig, or both and you will still have an output

**Comment by karthikarvind1295** [comment]
Thanks a lot for your reply. How can i provide both the images into the system ? I used Develop_subposes branch for this, but after generating the sfm_data.json file, the Compute_matches executable is not working. Is there a way to give image pairs in the "develop" branch ?
