### ISSUE TITLE
Point cloud and 2D image pixel correspondence 

### ISSUE THREAD

**Issue by ywang0218** [openMVG/openMVG#1796]
Hi
   After generating a 3D point cloud from a series of images, is it possible to find the pixel/image coordinate that corresponds to on specific point in the point cloud?
Thanks in advance

**Comment by pmoulon** [comment]
Yes they are saved in the sfm_data.bin file.
-> see [here](https://github.com/openMVG/openMVG/wiki/OpenMVG-data-structures) "Landmarks 3D Structure (3D points and their visibility information)"
You can convert this file to a json file using the ConvertSfMData format binary.
And then you can find the information you look for here
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L44
-> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_landmark.hpp#L23

**Comment by ywang0218** [comment]
> Yes they are saved in the sfm_data.bin file.
> -> see [here](https://github.com/openMVG/openMVG/wiki/OpenMVG-data-structures) "Landmarks 3D Structure (3D points and their visibility information)"
> You can convert this file to a json file using the ConvertSfMData format binary.
> And then you can find the information you look for here
> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L44
> -> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_landmark.hpp#L23

Thanks so much for your reply. I converted the bin file to json and found the correspondence. One more question here, what is the scale in the 3D point cloud? Our goal is to find the corresponding real-world location of a feature in the image, for instance, if there is a window on the third floor of a building, how can I extract the global coordinate of the window? It would be great if I can scale the 3D point cloud to real world scale, is that feasible in this repo?

**Comment by pmoulon** [comment]
SfM reconstructions are up to scale of the reality.
If you want to make them metric, you have to use GCP or GPS coordinates.
See here for the GCP https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/ (rescaling a model given some known measurements)
