### ISSUE TITLE
Cppcheck warns about wrong include path

### ISSUE THREAD

**Issue by cgringmuth** [openMVG/openMVG#1797]
There is something wrong with the cmake setup. It does compile, but it is still a bug. Cmake adds `-I/filesystemSimplified/` as include path. This path does not exists and cppcheck correctly warns about this issue.

![image](https://user-images.githubusercontent.com/1169481/93589993-09aa4180-f9ae-11ea-984e-43a24fb62ae1.png)

If you check the generated flags for `openMVG_sfm` for instance you get (it is true for many packages):
```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# compile CXX with /usr/lib/ccache/c++
CXX_FLAGS =  -march=skylake -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mfma -mbmi2 -mavx2 -mno-sse4a -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -fopenmp -O3   -march=skylake -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mfma -mbmi2 -mavx2 -mno-sse4a -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -fopenmp -DOPENMVG_USE_AVX2 -pthread -std=c++11

CXX_DEFINES = -DGFLAGS_IS_A_DLL=0 -DOPENMVG_USE_OPENMP

CXX_INCLUDES = \
    -I/usr/include/eigen3  \
    -I/tmp/tmp.EuAhPyqny1/openMVG/src  \
    -I/tmp/tmp.EuAhPyqny1/openMVG/src/dependencies/cereal/include  \
    -I/tmp/tmp.EuAhPyqny1/openMVG/src/third_party/lemon  \
    -I/tmp/tmp.EuAhPyqny1/openMVG_Build/third_party/lemon  \
    -I/tmp/tmp.EuAhPyqny1/openMVG/src/third_party/flann/src/cpp  \
    -I/tmp/tmp.EuAhPyqny1/openMVG/src/third_party/stlplus3  \
    -I/filesystemSimplified 
```
(output is slightly formatted to better see the issue)
you see the last include is not correct. Gcc seems just to ignore it. Any future compiler might complain. Additionally, this underlying bug could cause problems in unexpected situations. 

I tried to fix it, but my cmake debugging knowledge is not good enough to trace this bug. It is always complicate to debug cmake.

**Comment by pmoulon** [comment]
Thank you for your feedback. Appreciated.

What you see has been automatically generated by this https://github.com/openMVG/openMVG/blob/develop/src/third_party/stlplus3/CMakeLists.txt#L34
or made a strange combination with this:
https://github.com/openMVG/openMVG/blob/develop/src/third_party/stlplus3/CMakeLists.txt#L16

We can take a look and try to see what have we done wrong

**Comment by pmoulon** [comment]
@cgringmuth Any change you can help us take a look about what is wrong there?

**Comment by cgringmuth** [comment]
@pmoulon currently I'm busy with relocation. I can have a look when I'm settled and the error was not fixed yet. :)

**Comment by pmoulon** [comment]
@cgringmuth Let me know if you have some time now to look to this!

**Comment by cgringmuth** [comment]
I checked it and seems to be resolved.
