### ISSUE TITLE
Build fails: undefined reference to LZ4_compress_HC_continue

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1798]
```
ld: error: FreeBSD-amd64-Release/libopenMVG_matching.so.1.4: undefined reference to LZ4_compress_HC_continue [--no-allow-shlib-undefined]
ld: error: FreeBSD-amd64-Release/libopenMVG_matching.so.1.4: undefined reference to LZ4_decompress_safe [--no-allow-shlib-undefined]
ld: error: FreeBSD-amd64-Release/libopenMVG_matching.so.1.4: undefined reference to LZ4_decompress_safe_continue [--no-allow-shlib-undefined]
ld: error: FreeBSD-amd64-Release/libopenMVG_matching.so.1.4: undefined reference to LZ4_resetStreamHC [--no-allow-shlib-undefined]
ld: error: FreeBSD-amd64-Release/libopenMVG_matching.so.1.4: undefined reference to LZ4_setStreamDecode [--no-allow-shlib-undefined]
```

Versions  1.4 and 1.6
FreeBSD 12 and 13
clang-10 and clang-11

Log: http://beefy18.nyi.freebsd.org/data/head-amd64-default/p549079_s365919/logs/openmvg-1.4_2.log (IPv6 URL)

**Comment by pmoulon** [comment]
Do you know if this is due to FLANN or to the image library?

**Comment by yurivict** [comment]
It seems that you have a missing ```-llz4``` flag when the ```libopenMVG_matching.so``` library was built.

**Comment by yurivict** [comment]
Adding ```-lz4``` to ```LDFLAGS``` fixes this failure. I did this as a workaround in the FreeBSD port.

**Comment by rperrot** [comment]
That's for your support.

**Comment by yurivict** [comment]
But did you fix this in the project? My fix is a workaround in the port to somehow get it to build.

**Comment by pmoulon** [comment]
Actually I think the issue is only happening if you are using an external FLANN but not if you are using the internal version.
- Our internal build is using FLANN in header only mode
- The external build seems to be configured to use Z4 compression. So the fix would be located around using here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching/CMakeLists.txt#L42, but as you see we are already using `FLANN_LIBRARIES `. So the question is why `FLANN_LIBRARIES` on FREEBSD is not containing z4 despite it is required?

**Comment by yurivict** [comment]
When you are using only an external header and it uses some other library - you should add its ```-l{lib}``` to your build.

**Comment by pmoulon** [comment]
But my point is that we don't use the feature of the other library and when used in header only, the compression is not a requirement.
The point I'm wondering is that why z4 is not inside `FLANN_LIBRARIES ` because it should be...

**Comment by yurivict** [comment]
The problem is indeed in flann.

Thank your for your help.

**Comment by pmoulon** [comment]
Thank you for making the FreeBSD build port. Communities can only be built with people building the software and making it accessible. We appreciate all your comments.

**Comment by yurivict** [comment]
Thank you!

**Comment by yurivict** [comment]
It still breaks even with flann's .pc file returnin gthe correct LDFLAGS now.

Log: http://beefy17.nyi.freebsd.org/data/head-i386-default/p549877_s366096/logs/errors/openmvg-1.4_4.log

See the line ```[398/560]``` there that builds ```libopenMVG_matching.so```. It doesn't have -llz4. It looks like you don't include ```FLANN_LIBS``` in this target.

**Comment by pmoulon** [comment]
As you can see here I'm using `FLANN_LIBRARIES`  (CMAKE default suggest LIBRARY_NAME_LIBRARIES) but perhaps it is defined differently in the pc package https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching/CMakeLists.txt#L45

**Comment by rperrot** [comment]
FLANN is however included in the link line : /usr/local/lib/libflann_cpp.so, we don't rely on pkg-config  but on cmake to find FLANN. 

The solution is to find a way to include the correct dependencies in the .cmake file : 

https://github.com/openMVG/openMVG/blob/develop/src/cmakeFindModules/FindFlann.cmake

**Comment by elhabchiali** [comment]
> Adding `-lz4` to `LDFLAGS` fixes this failure. I did this as a workaround in the FreeBSD port.

Hi, where can i add this LDFLAGS, i'm trying to compile it on a raspberry and i have the same issue.

**Comment by pmoulon** [comment]
You can add it to the list here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching/CMakeLists.txt#L31
