### ISSUE TITLE
camera model

### ISSUE THREAD

**Issue by qingjiuling** [openMVG/openMVG#1800]
Hi,When I use the dataset in demo or dateset mentioned in Wiki to run the model, I can get SFM_ data.bin File enen without k.txt, but I can't find the file when using the pictures took myself or found on the Internet. Where can I find the camera model supported by the model,

**Comment by pmoulon** [comment]
The number is the sensor width that you can find in your camera sheet description.
But for your information you can also use an approximate focal length see here https://github.com/openMVG/openMVG/issues/669

**Comment by qingjiuling** [comment]
Thank you
