### ISSUE TITLE
Question about 2D observations in sfm_data

### ISSUE THREAD

**Issue by HieuPhan33** [openMVG/openMVG#1804]
Hi, I'm trying to find the 3D location of some specified pixels in a certain image.

From the document, I know that the ```structure``` in ```Sfm_data``` stores the 3D-2D correspondences.
Based on my understanding, the 2D observations should contain pixel coordinates and _which 2D images_ they belong to.

![image](https://user-images.githubusercontent.com/32691090/94275134-ee30cf00-ff89-11ea-80bb-e4e4ebc4fc2a.png)

I guess that the ```x``` value in the ```observation``` field represents the pixel coordinates. But I couldn't see which image they refer to.
Could you please advise?

Thanks

**Comment by pmoulon** [comment]
Key refers to the View, so here the point is at least viewed by view 1 and 2
