### ISSUE TITLE
GCP GUI - How to open from docker

### ISSUE THREAD

**Issue by HieuPhan33** [openMVG/openMVG#1805]
Hi,
I'm using docker build for OpenMVG.
I don't know how to open a UI GCP to retrieve correct scales as https://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/
Where is the app located in the project directory?

Thanks

**Comment by pmoulon** [comment]
Sorry for the late answer.
App should be in build/software/ui/SfM)/control_points_registration/
