### ISSUE TITLE
IncrementalSfM or GlobalSfM terminated when the field "a-contractor initial pair residual" appears

### ISSUE THREAD

**Issue by chengyifa** [openMVG/openMVG#1806]
@pmoulon @rperrot 
sorry to bother you !
The work is terminated when the field "a-contractor initial pair residual" appears,I check the matching graph(geometric_matches.svg) is normal ,as flows:
![geometric_matches](https://user-images.githubusercontent.com/72006117/94400946-75ee2780-019c-11eb-856d-61d85ac581b3.png)

But SFM work is over here. Is it my machine problem？
![sfm](https://user-images.githubusercontent.com/72006117/94401109-a6ce5c80-019c-11eb-8d6c-5521f946f855.png)

**Comment by rperrot** [comment]
Does any openMVG process stil running ? (ie: is there a segfault ?)
