### ISSUE TITLE
Use refined intrinsics

### ISSUE THREAD

**Issue by ffabi** [openMVG/openMVG#1808]
Hello, can you help me out with saving the refined intrinsic?

In the step of IncrementalSfM, I left the `refineIntrinsics` parameter on default, but I noticed that the `sfm_dat.json` file is not updated with the refined intrinsic parameters. I would like to overwrite or at least print the new values.

Keep up the good work!

**Comment by pmoulon** [comment]
Hello @ffabi 
SfM binaries is exporting the sfm_data in binary for speed and space (sfm_data.bin). You can convert this binary file to json, XML or PLY(for visualization) using the binary ConvertSfMData_format.

Thank you for your nice words about OpenMVG ;-)

**Comment by ffabi** [comment]
Thank you, works well!

**Comment by pmoulon** [comment]
Great! Have fun!
