### ISSUE TITLE
Order of data in JSON matters?

### ISSUE THREAD

**Issue by tjdahlke** [openMVG/openMVG#1809]
Some finicky JSON reading behavior using any of the openMVG executables:

If I run:

`openMVG_main_ExportUndistortedImages -i` [input_sfm_data.json](https://github.com/openMVG/openMVG/files/5358213/input_sfm_dataJSON.txt) `-o ./`

I have no problems. But if I run:

`openMVG_main_ExportUndistortedImages -i` [input_sfm_data_bad.json](https://github.com/openMVG/openMVG/files/5358214/input_sfm_dataJSON_bad.txt) `-o ./`

I get this:

`JSON Parsing failed - provided NVP (width) not found`

The only difference between the two files is the order of the elements under `data` in the intrinsics, namely `fisheye` and `value0`. This is an issue because a lot of other JSON utilities write out JSON data in alphabetical order, meaning making modifications with other JSON utilities and then writing the result makes it unreadable by openMVG in some cases. Am I the only one who's run across this before?

THIS WORKS:
```
"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "fisheye",
                "ptr_wrapper": {
                    "data": {
                        "value0": {
                            "width": 1991,
                            "height": 1080,
                            "focal_length": 907.0775561924764,
                            "principal_point": [
                                1003.7284767183824,
                                559.916561396705
                            ]
                        },
                        "fisheye": [
                            -0.034130749003648038,
                            -0.010700197569093987,
                            0.009306193801237418,
                            -0.002779332588455298
                        ]
                    },
                    "id": 2147483682
                }
            }
        }
    ],
```
THIS DOESNT:

```
"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "fisheye",
                "ptr_wrapper": {
                    "data": {
                        "fisheye": [
                            -0.034130749003648038,
                            -0.010700197569093987,
                            0.009306193801237418,
                            -0.002779332588455298
                        ],
                        "value0": {
                            "width": 1991,
                            "height": 1080,
                            "focal_length": 907.0775561924764,
                            "principal_point": [
                                1003.7284767183824,
                                559.916561396705
                            ]
                        }
                    },
                    "id": 2147483682
                }
            }
        }
    ],
```
If I remove the `value0` level, making it just:

```
"data" : 
          {
            "focal_length" : 907.07755619247644,
            "height" : 1080,
            "principal_point" : 
            [
              1003.7284767183824,
              559.91656139670499
            ],
            "width" : 1991,
            "fisheye" : 
            [
              -0.034130749003648035,
              -0.010700197569093987,
              0.0093061938012374175,
              -0.0027793325884552982
            ]
          },
```

I get this error:
`rapidjson internal assertion failure: IsObject()
The input SfM_Data file "tmp_camera_data.json" cannot be read.`

Any advice / help on this issue would be appreciated!

**Comment by tjdahlke** [comment]
Still unresolved. I ended up trying to change the order of the JSON file data so `value0` was always written before `fisheye`. The underlying problem regarding openMVG JSON reading is still an issue.

**Comment by pmoulon** [comment]
It could be due to the library we are using (Cereal).

@rjanvier noticed that we got something inconsistent in the API, he proposed a fix here... Can you look if it helps on your issue https://github.com/openMVG/openMVG/pull/1770
