### ISSUE TITLE
Too big error in the optimized intrinsics after Global SFM.

### ISSUE THREAD

**Issue by qingzhengzhuma** [openMVG/openMVG#1815]
Thanks to all, OpenMVG is really a great work in the community! Recently I use OpenMVG to reconstruct a scene, but I find sometimes the optimized intrinsics are much different for the same camera even in similar scenes. Here is my configuration:

operating system : windows 10 x64
camera platform : dji
image dimension: 5472*3648
feature extract : colmap,max feature num 12000
feature match : colmap spatial matching, nearest neighbors 15
use GPS prior : yes
geometric filter : fundamental matrix
focal length initialization : 3600
camera model : PINHOLE_CAMERA_RADIAL3

after optimization :[f cx cy k1 k2 k3]
scene1 intrinsic : 3975.27 2726.07 1814.53 0.0074035 0.00558371 0.0103871 
sence2 intrinsic : 5648.01 2776.04 1833.45 0.0294073 -0.0154363 0.175315 

this two scenes was take in the same place with the same camera, when I merge the two in mesh lab, there is an obvious gap between the sparse point clouds in z axis.

![image](https://user-images.githubusercontent.com/10589386/96563132-2f4fa100-12f4-11eb-9eb3-73e8349f48c6.png)

![image](https://user-images.githubusercontent.com/10589386/96562345-404be280-12f3-11eb-912b-ceb2cdb67dd6.png)

I hope  GlobalSFM could rebuild the true scene without too much error(scene1 is acceptable because most of other scenes taken by this camera get similar intrinsic) , can anyone give me some tips to tackle this problem?

[scene1.zip](https://github.com/openMVG/openMVG/files/5407586/scene1.zip)
[scene2.zip](https://github.com/openMVG/openMVG/files/5407588/scene2.zip)

**Comment by qingzhengzhuma** [comment]
With PINHOLE_CAMERA_BROWN model I solved the problem, now the two scenes can be merged nicer and the extrinsic elements are more precise.
![image](https://user-images.githubusercontent.com/10589386/96568942-1ac2d700-12fb-11eb-82ad-938ed6d2ff37.png)

**Comment by pmoulon** [comment]
Happy to hear you were able to merge the scene correctly
