### ISSUE TITLE
Projection Matrices/Extrinsic Parameters for Triangulation

### ISSUE THREAD

**Issue by ConnorM17** [openMVG/openMVG#1817]
In my lab I have 4 cameras positioned in arc to capture a volume where a person will walk through. The cameras have manually adjusted lens that I have calibrated using a ChArUco board (chessboard calibration). Currently, I have intrinsic parameters for each of the cameras (intrinsic matrix [focal lengths, camera center], and distortion coefficients [k1, k2, k3]).

I am wondering how I should use OpenMVG to obtain the projection matrices between the cameras in this case where each camera has its own already defined intrinsic parameters.

**Comment by rperrot** [comment]
You can pass your intrinsic settings using the --intrinsics option of openMVG_main_SfMInit_ImageListing executable. You cannot pass distortion coef directly (ie: using the provided executables) they will be recomputed by openMVG. 

Check the source of main_SfMInit_ImageListing.cpp (src/software/SfM) if you want more details about the implementation.

**Comment by pmoulon** [comment]
Closed due to inactivity. Feel free to reopen if needed
