### ISSUE TITLE
Air strip and the structure get bent.

### ISSUE THREAD

**Issue by qingzhengzhuma** [openMVG/openMVG#1819]
I'm using OpenMVG(global SFM) to rebuild a farmland which is a relatively flat scene, but after the reconstruction, the optimized air strip and structure get bent.
![image](https://user-images.githubusercontent.com/10589386/97675356-22883580-1aca-11eb-95fb-ecf0e040bcb6.png)
bent air strip
![image](https://user-images.githubusercontent.com/10589386/97675472-58c5b500-1aca-11eb-892c-0812720421af.png)
bent structure
SFM method : global
operating system : windows 10 x64
camera platform : dji
image dimension: 5472*3648
feature extract : colmap,max feature num 12000
feature match : colmap spatial matching, nearest neighbors 10
use GPS prior : yes
geometric filter : fundamental matrix
focal length initialization : 3600
camera model : PINHOLE_CAMERA_BROWN

I also tried incremental sfm2, this error remained. the distortion of input image is a little obvious:
![100_0037_0010](https://user-images.githubusercontent.com/10589386/97677496-4dc05400-1acd-11eb-9a6d-049b72fff2c6.JPG)

 Could anyone help me?

**Comment by qingzhengzhuma** [comment]
@rperrot sorry, the result you see is created by global SFM.

**Comment by qingzhengzhuma** [comment]
since the data was with RTK, I set the priorWeight to 10;10;10, it got better result, then i set the priorWeight to 100;100;100, the optimized air strip almost no longer get bent and so is the sparse pointcloud.
![image](https://user-images.githubusercontent.com/10589386/98069831-af503c00-1e9a-11eb-82c5-a1ca1658fb9b.png)
![image](https://user-images.githubusercontent.com/10589386/98069971-2c7bb100-1e9b-11eb-8e8d-01e53b62d3cf.png)
because this scene is farmland, i think it's more reliable to be not bent.
I also tried undistort the image before feature extraction, but it didn't work.

**Comment by pmoulon** [comment]
Often this problem arises due to compensation of the distortion and the motion of the camera.

Often adapting your flight path in two-layer of capture is sufficient to overcome the issue, see here https://github.com/openMVG/openMVG/issues/1423#issuecomment-435733995

**Comment by pmoulon** [comment]
Happy to see that the GPS weighting helped in your case :tada:

**Comment by qingzhengzhuma** [comment]
Thanks so much for your time,@pmoulon, i'm gona read the papers mentioned in #1423.
