### ISSUE TITLE
openMVG_main_SfM_Localization:Total poses found: 0/0

### ISSUE THREAD

**Issue by NEU-LC** [openMVG/openMVG#1823]
Hello, the log shows total poses found:0/0 when I run the sample of openMVG_main_SfM_Localization in Ubuntu 16.04LTS. The log as follows:
```
-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------


- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Init retrieval database ... 
Retrieval database initialized with:
#landmarks: 1980
#descriptors: 4690
Total poses found : 0/0
```
The 360_Flat dataset is used by SfM_SequentialPipeline.py and openMVG_main_SfM_Localization.  And the Terminal code is
```sh
python SfM_SequentialPipeline.py ../../../Image_datasets-master/360_dataset/360_Flat/images ../../../Image_datasets-master/Castle_Global_Reconstruction

./Linux-x86_64-RELEASE/openMVG_main_SfM_Localization -i /home/user/thirdPart/openMVG/Image_datasets-master/Castle_Global_Reconstruction/reconstruction_sequential/sfm_data.bin -m /home/user/thirdPart/openMVG/Image_datasets-master/Castle_Global_Reconstruction/matches -o ./ -q /home/user/thirdPart/openMVG/Image_datasets-master/360_dataset/360_Flat/images/R0010211.JPG

```
May I ask where is the problem?

**Comment by pmoulon** [comment]
Hello it seems that you are using 360 images, did you specify in the command line you want to use the 360 camera model?

**Comment by NEU-LC** [comment]
> Hello it seems that you are using 360 images, did you specify in the command line you want to use the 360 camera model?

Thank you for your reply. Ummm, I don't set the camera model in the command line. Please what should I operate? And if I want to use my own dataset to run the localization sample, is it the same operation as on the 360 datasets,

**Comment by jxm042022** [comment]
Hi, first time user. Running into the same problem with localization. Am using the default Castle data from the main branch on Windows.  From issue #1205, seems it should be straight forward. What is wrong with my procedure ? Thanks!
Here are the steps.
1)cd C:\Proj\openMVG\build\software\SfM
2)python SfM_SequentialPipeline.py .\ImageDataset_SceauxCastle\images .\ImageDataset_SceauxCastle
Good result with 5971 tracks with residualsMSE mean 0.26
3)..\..\Windows-AMD64-Release\Release\openMVG_main_SfM_Localization.exe -i .\ImageDataset_SceauxCastle\reconstruction_sequential\sfm_data.bin -m .\ImageDataset_SceauxCastle\matches -o .\ImageDataset_SceauxCastle\Output -q .\ImageDataset_SceauxCastle\images\100_7104.JPG
Log: 
-----------------------------------------------------------
  Images localization in an existing SfM reconstruction:
-----------------------------------------------------------

INFO: [loggerprogress.hpp:79] [- Regions Loading -] 100%
INFO: [SfM_Localizer_Single_3DTrackObservation_Database.cpp:60] Init retrieval database ...
INFO: [SfM_Localizer_Single_3DTrackObservation_Database.cpp:67] Retrieval database initialized with:
#landmarks: 5971
#descriptors: 19717
 Total poses found : 0/0

**Comment by jxm042022** [comment]
Found the solution from #1920!
