### ISSUE TITLE
cv2eigen error

### ISSUE THREAD

**Issue by Techhooli** [openMVG/openMVG#1827]
I have check the issue #1758, but your code not work. cv2eigen will generate an error like "unhandled exception".  I use MatrixXd instead of Image<uint8_t>, it works. So I guess the Image<uint8_t> is the reason. How to do it?

    // CV to OpenMVG
    {
      cv::Mat cv_image;
      cv_image = cv::imread( image_filename, CV_LOAD_IMAGE_GRAYSCALE );
      Image<uint8_t> openmvg_image;
      openmvg_image.resize(cv_image.cols, cv_image.rows);
      cv::cv2eigen(cv_image, *(Image<uint8_t>::Base*)&openmvg_image);
      WriteImage("gray_cv_to_openmvg.png", openmvg_image);
    }

**Comment by Techhooli** [comment]
I found ReadImage is so slowly, it will waste 6 seconds when reading 3000*2000 pixels image. So I try to use cvMat, and then convert to your variable type...

**Comment by pmoulon** [comment]
- Speed: are you compiling in Release?
- The code I shared was working on my computer
- Since we are using ::Base, we are accessing the underlying MatrixX
- You can try to see in debug what is going in in cv2eigen

**Comment by Techhooli** [comment]
Thank you for your replay. I have test cv2eigen. It works when I add rowmajor parameter in some opencv head files. Its (cv::imread and cv:: cv2eigen) speed is tripal better than ReadImage. But I found when I add some opencv libraries. The SfmInit_ImageListing doesn't work. The reason is ReadImageHeader(sImageFilename.c_str(), &imgHeader) can not read image. I think some conflicts have happened between opencv library and openmvg library. I am soling this problem. It is very interesting. I will check the inner code of yours.

**Comment by Techhooli** [comment]
Your work is perfect. I have learn your library for more than one month. I must say I have learned a lot from your work. I want to learn more deeply. Do you have some papers or some other materials? even through I have found some online. ha-ha... : )

**Comment by pmoulon** [comment]
You can take a look to https://github.com/openMVG/awesome_3DReconstruction_list
