### ISSUE TITLE
camera pose

### ISSUE THREAD

**Issue by HuangTY96** [openMVG/openMVG#1829]
hi 

this is my sfm_data.json
"extrinsics": [
        {
            "key": 0,
            "value": {
                "rotation": [
                    [
                        0.0850112588057704,
                        0.5941605943864319,
                        -0.7998414055015034
                    ],
                    [
                        0.1671550173412519,
                        0.782865880772557,
                        0.599316454721422
                    ],
                    [
                        0.9822587673591435,
                        -0.18464615024573467,
                        -0.03276451045758933
                    ]
                ],
                "center": [
                    -0.02434891378826601,
                    0.35092669777022836,
                    0.6528638156957916
                ]
            }
        },
1. I am not sure if this R means [r11,r12,r13],[r21,r22,r23],[r31,r32,r33]?
2. if I want to transform C to t, does t = dot(-R,C)?

**Comment by yuancaimaiyi** [comment]
@HuangTY96 you are right !

**Comment by pmoulon** [comment]
Closed due to inactivity. Feel free to reopen if needed
