### ISSUE TITLE
How to play around with open MVG binaries on Windows 

### ISSUE THREAD

**Issue by Harry-Yagami** [openMVG/openMVG#1830]
Following your inputs from #781 I have successfully installed openmvg on windows, Built the binaries and pipeline using CMake +Visual studio. Now I have sfm_data.bin and a bunch of .ply files exported by Sequential pipeline. First of all, thanks a lot @pmoulon  for  #781
 
Now my goal is to convert sfm_data.bin to scene.mvs using BINARIES .But I dont know where and how to run those binaries .All the documentation/examples you have given in openmvg Docs were of linux. Please help me out.

Inshort I need a way to run Binaries in commandPrompt, like

$ openMVG _main_openMVG2openMVS -i /path/to/reconstriction/my/folder/sfm_data.bin -o /path/to/target/MVS/folder/scene.mvs

**Comment by Harry-Yagami** [comment]
![image](https://user-images.githubusercontent.com/30416277/101636551-83077c80-3a51-11eb-8747-b6b029b1c1ad.png)

**Comment by pmoulon** [comment]
YOu can find windows pre-build binaries here https://github.com/openMVG/openMVG/releases/tag/v1.6 (see Assets).
THen you just have to run the command line and use the same syntax as on Linux example.
