### ISSUE TITLE
who knows the Meaning of parameters in the sensor_width_database?

### ISSUE THREAD

**Issue by qilin2008201** [openMVG/openMVG#1833]
I want to add my mobile phone model to the sensor_width_database, but I don't know the meaning of the parameters in it.

**Comment by rperrot** [comment]
The first parameter is the name of the camera. This name is not standard : it can be a model name or a brand followed by a model name. You can find the exact name of your camera in the exif data. openMVG indicates the name it found in a line like that : 

"model "XXX" doesn't exist in the database"
where XXX is the model name.

The second one is the sensor width (in mm). It can be found in various places : specs of your phone (as presented by the manufacturer) or in some of the database available online.

**Comment by pmoulon** [comment]
Closed due to inactivity. Feel free to reopen if needed
