### ISSUE TITLE
A spherical dataset is tested twice, one failed but one pass

### ISSUE THREAD

**Issue by HuangTY96** [openMVG/openMVG#1834]
I have a spherical dataset, and test it twice using same code, but one failed, one pass.
this is command line I use:
```
# Initialize the scene (spherical camera model)
openMVG_main_SfMInit_ImageListing -i dataset_in -o dataset_out/matches -f 1 -c 7

# Compute of the features (you can add -n <THREAD_COUNT> to be faster)
openMVG_main_ComputeFeatures -i dataset_out/matches/sfm_data.json -o dataset_out/matches -m SIFT -p ULTRA

# Compute the image matches (notice the angular mode, more adapted for spherical images)
openMVG_main_ComputeMatches -i dataset_out/matches/sfm_data.json -o dataset_out/matches -g a

# Compute of the camera motion and structure of the scene
openMVG_main_IncrementalSfM -i dataset_out/matches/sfm_data.json -m dataset_out/matches -o dataset_out/reconstruction
```

I paste two log here.
**log1(fail):**
SequentialSfMReconstructionEngine
Dataset info:Views count: 32
Essential Matrix.
-------------------------------
-- Robust Essential matrix: <2,30> images: 00003.png,00031.png
-- Threshold: 22.1696
-- Resection status: OK
-- Nb points used for robust Essential matrix estimation: 307
-- Nb points validated by robust estimation: 23
-- % points validated: 0.0749186
-------------------------------
Residual of the robust estimation (Initial triangulation). Thresholded at: 22.1696
Histogram of residuals
 –  o  +  ←  ↓  ↑  → AB1015520025250
Resection of Image index: <4> image: 00005.png
-------------------------------
-- Robust Resection of camera index: <4> image: 00005.png
-- Threshold: 178.554
-- Resection status: FAILED
-- Nb points used for Resection: 6
-- Nb points validated by robust estimation: 6
-- % points validated: 1
-------------------------------
Resection of Image index: <3> image: 00004.png
-------------------------------
-- Robust Resection of camera index: <3> image: 00004.png
-- Threshold: 67.0439
-- Resection status: FAILED
-- Nb points used for Resection: 5
-- Nb points validated by robust estimation: 5
-- % points validated: 1
-------------------------------
Resection of Image index: <29> image: 00030.png
-------------------------------
-- Robust Resection of camera index: <29> image: 00030.png
-- Threshold: 94.2924
-- Resection status: FAILED
-- Nb points used for Resection: 5
-- Nb points validated by robust estimation: 5
-- % points validated: 1
-------------------------------
Resection of Image index: <0> image: 00001.png
-------------------------------
-- Robust Resection of camera index: <0> image: 00001.png
-- Threshold: 38.0215
-- Resection status: FAILED
-- Nb points used for Resection: 4
-- Nb points validated by robust estimation: 4
-- % points validated: 1
-------------------------------
Resection of Image index: <1> image: 00002.png
-------------------------------
-- Robust Resection of camera index: <1> image: 00002.png
-- Threshold: 264.199
-- Resection status: FAILED
-- Nb points used for Resection: 4
-- Nb points validated by robust estimation: 4
-- % points validated: 1
-------------------------------
Resection of Image index: <28> image: 00029.png
-------------------------------
-- Robust Resection of camera index: <28> image: 00029.png
-- Threshold: 652.558
-- Resection status: FAILED
-- Nb points used for Resection: 4
-- Nb points validated by robust estimation: 4
-- % points validated: 1
-------------------------------
Resection of Image index: <10> image: 00011.png
-------------------------------
-- Robust Resection of camera index: <10> image: 00011.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 3
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <24> image: 00025.png
-------------------------------
-- Robust Resection of camera index: <24> image: 00025.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 3
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <26> image: 00027.png
-------------------------------
-- Robust Resection of camera index: <26> image: 00027.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 3
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <27> image: 00028.png
-------------------------------
-- Robust Resection of camera index: <27> image: 00028.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 3
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <11> image: 00012.png
-------------------------------
-- Robust Resection of camera index: <11> image: 00012.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <5> image: 00006.png
-------------------------------
-- Robust Resection of camera index: <5> image: 00006.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <7> image: 00008.png
-------------------------------
-- Robust Resection of camera index: <7> image: 00008.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <6> image: 00007.png
-------------------------------
-- Robust Resection of camera index: <6> image: 00007.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <15> image: 00016.png
-------------------------------
-- Robust Resection of camera index: <15> image: 00016.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <17> image: 00018.png
-------------------------------
-- Robust Resection of camera index: <17> image: 00018.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <20> image: 00021.png
-------------------------------
-- Robust Resection of camera index: <20> image: 00021.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <21> image: 00022.png
-------------------------------
-- Robust Resection of camera index: <21> image: 00022.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <22> image: 00023.png
-------------------------------
-- Robust Resection of camera index: <22> image: 00023.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <23> image: 00024.png
-------------------------------
-- Robust Resection of camera index: <23> image: 00024.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <25> image: 00026.png
-------------------------------
-- Robust Resection of camera index: <25> image: 00026.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <31> image: 00032.png
-------------------------------
-- Robust Resection of camera index: <31> image: 00032.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 2
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <12> image: 00013.png
-------------------------------
-- Robust Resection of camera index: <12> image: 00013.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <8> image: 00009.png
-------------------------------
-- Robust Resection of camera index: <8> image: 00009.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <9> image: 00010.png
-------------------------------
-- Robust Resection of camera index: <9> image: 00010.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <13> image: 00014.png
-------------------------------
-- Robust Resection of camera index: <13> image: 00014.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <16> image: 00017.png
-------------------------------
-- Robust Resection of camera index: <16> image: 00017.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <18> image: 00019.png
-------------------------------
-- Robust Resection of camera index: <18> image: 00019.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <14> image: 00015.png
-------------------------------
-- Robust Resection of camera index: <14> image: 00015.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Resection of Image index: <19> image: 00020.png
-------------------------------
-- Robust Resection of camera index: <19> image: 00020.png
-- Threshold: 0
-- Resection status: FAILED
-- Nb points used for Resection: 1
-- Nb points validated by robust estimation: 0
-- % points validated: 0
-------------------------------
Structure from Motion process finished.
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 0 from 32 input images.
-- #Tracks, #3D points: 0
-------------------------------

**log2(pass):**
SequentialSfMReconstructionEngine
Dataset info:Views count: 32
Essential Matrix.
-------------------------------
-- Robust Essential matrix: <2,13> images: 00003.png,00014.png
-- Threshold: 21.7348
-- Resection status: OK
-- Nb points used for robust Essential matrix estimation: 657
-- Nb points validated by robust estimation: 122
-- % points validated: 0.185693
-------------------------------
Residual of the robust estimation (Initial triangulation). Thresholded at: 21.7348
Histogram of residuals
 –  o  +  ←  ↓  ↑  → AB101015520025252500
Resection of Image index: <15> image: 00016.png
-------------------------------
-- Robust Resection of camera index: <15> image: 00016.png
-- Threshold: 68.2646
-- Resection status: OK
-- Nb points used for Resection: 75
-- Nb points validated by robust estimation: 64
-- % points validated: 0.853333
-------------------------------
Resection of Image index: <5> image: 00006.png
-------------------------------
-- Robust Resection of camera index: <5> image: 00006.png
-- Threshold: 20.6255
-- Resection status: OK
-- Nb points used for Resection: 224
-- Nb points validated by robust estimation: 134
-- % points validated: 0.598214
-------------------------------
Resection of Image index: <14> image: 00015.png
-------------------------------
-- Robust Resection of camera index: <14> image: 00015.png
-- Threshold: 8.0754
-- Resection status: OK
-- Nb points used for Resection: 1967
-- Nb points validated by robust estimation: 1746
-- % points validated: 0.887646
-------------------------------
Resection of Image index: <8> image: 00009.png
-------------------------------
-- Robust Resection of camera index: <8> image: 00009.png
-- Threshold: 33.236
-- Resection status: OK
-- Nb points used for Resection: 1004
-- Nb points validated by robust estimation: 789
-- % points validated: 0.785857
-------------------------------
Resection of Image index: <10> image: 00011.png
-------------------------------
-- Robust Resection of camera index: <10> image: 00011.png
-- Threshold: 16.0171
-- Resection status: OK
-- Nb points used for Resection: 1914
-- Nb points validated by robust estimation: 1477
-- % points validated: 0.771682
-------------------------------
Resection of Image index: <9> image: 00010.png
-------------------------------
-- Robust Resection of camera index: <9> image: 00010.png
-- Threshold: 13.0579
-- Resection status: OK
-- Nb points used for Resection: 2816
-- Nb points validated by robust estimation: 2255
-- % points validated: 0.800781
-------------------------------
Resection of Image index: <7> image: 00008.png
-------------------------------
-- Robust Resection of camera index: <7> image: 00008.png
-- Threshold: 12.8347
-- Resection status: OK
-- Nb points used for Resection: 3033
-- Nb points validated by robust estimation: 2453
-- % points validated: 0.80877
-------------------------------
Resection of Image index: <12> image: 00013.png
-------------------------------
-- Robust Resection of camera index: <12> image: 00013.png
-- Threshold: 15.7259
-- Resection status: OK
-- Nb points used for Resection: 2880
-- Nb points validated by robust estimation: 2477
-- % points validated: 0.860069
-------------------------------
Resection of Image index: <4> image: 00005.png
-------------------------------
-- Robust Resection of camera index: <4> image: 00005.png
-- Threshold: 14.3842
-- Resection status: OK
-- Nb points used for Resection: 2261
-- Nb points validated by robust estimation: 1726
-- % points validated: 0.763379
-------------------------------
Resection of Image index: <3> image: 00004.png
-------------------------------
-- Robust Resection of camera index: <3> image: 00004.png
-- Threshold: 12.3123
-- Resection status: OK
-- Nb points used for Resection: 2865
-- Nb points validated by robust estimation: 2113
-- % points validated: 0.737522
-------------------------------
Resection of Image index: <6> image: 00007.png
-------------------------------
-- Robust Resection of camera index: <6> image: 00007.png
-- Threshold: 11.051
-- Resection status: OK
-- Nb points used for Resection: 4827
-- Nb points validated by robust estimation: 3862
-- % points validated: 0.800083
-------------------------------
Resection of Image index: <11> image: 00012.png
-------------------------------
-- Robust Resection of camera index: <11> image: 00012.png
-- Threshold: 17.4345
-- Resection status: OK
-- Nb points used for Resection: 3937
-- Nb points validated by robust estimation: 3238
-- % points validated: 0.822454
-------------------------------
Resection of Image index: <16> image: 00017.png
-------------------------------
-- Robust Resection of camera index: <16> image: 00017.png
-- Threshold: 11.6602
-- Resection status: OK
-- Nb points used for Resection: 2964
-- Nb points validated by robust estimation: 2153
-- % points validated: 0.726383
-------------------------------
Resection of Image index: <0> image: 00001.png
-------------------------------
-- Robust Resection of camera index: <0> image: 00001.png
-- Threshold: 18.9774
-- Resection status: OK
-- Nb points used for Resection: 3239
-- Nb points validated by robust estimation: 2286
-- % points validated: 0.705773
-------------------------------
Resection of Image index: <1> image: 00002.png
-------------------------------
-- Robust Resection of camera index: <1> image: 00002.png
-- Threshold: 15.051
-- Resection status: OK
-- Nb points used for Resection: 4375
-- Nb points validated by robust estimation: 3283
-- % points validated: 0.7504
-------------------------------
Resection of Image index: <18> image: 00019.png
-------------------------------
-- Robust Resection of camera index: <18> image: 00019.png
-- Threshold: 24.9242
-- Resection status: OK
-- Nb points used for Resection: 2390
-- Nb points validated by robust estimation: 1702
-- % points validated: 0.712134
-------------------------------
Resection of Image index: <19> image: 00020.png
-------------------------------
-- Robust Resection of camera index: <19> image: 00020.png
-- Threshold: 28.2246
-- Resection status: OK
-- Nb points used for Resection: 2584
-- Nb points validated by robust estimation: 1807
-- % points validated: 0.699303
-------------------------------
Resection of Image index: <17> image: 00018.png
-------------------------------
-- Robust Resection of camera index: <17> image: 00018.png
-- Threshold: 5.88158
-- Resection status: OK
-- Nb points used for Resection: 4122
-- Nb points validated by robust estimation: 3200
-- % points validated: 0.776322
-------------------------------
Resection of Image index: <20> image: 00021.png
-------------------------------
-- Robust Resection of camera index: <20> image: 00021.png
-- Threshold: 9.99176
-- Resection status: OK
-- Nb points used for Resection: 3010
-- Nb points validated by robust estimation: 2251
-- % points validated: 0.747841
-------------------------------
Resection of Image index: <21> image: 00022.png
-------------------------------
-- Robust Resection of camera index: <21> image: 00022.png
-- Threshold: 14.8916
-- Resection status: OK
-- Nb points used for Resection: 3249
-- Nb points validated by robust estimation: 2496
-- % points validated: 0.768236
-------------------------------
Resection of Image index: <22> image: 00023.png
-------------------------------
-- Robust Resection of camera index: <22> image: 00023.png
-- Threshold: 15.1868
-- Resection status: OK
-- Nb points used for Resection: 3196
-- Nb points validated by robust estimation: 2455
-- % points validated: 0.768148
-------------------------------
Resection of Image index: <23> image: 00024.png
-------------------------------
-- Robust Resection of camera index: <23> image: 00024.png
-- Threshold: 12.1429
-- Resection status: OK
-- Nb points used for Resection: 2815
-- Nb points validated by robust estimation: 2178
-- % points validated: 0.773712
-------------------------------
Resection of Image index: <24> image: 00025.png
-------------------------------
-- Robust Resection of camera index: <24> image: 00025.png
-- Threshold: 16.9284
-- Resection status: OK
-- Nb points used for Resection: 2929
-- Nb points validated by robust estimation: 2241
-- % points validated: 0.765108
-------------------------------
Resection of Image index: <25> image: 00026.png
-------------------------------
-- Robust Resection of camera index: <25> image: 00026.png
-- Threshold: 7.08379
-- Resection status: OK
-- Nb points used for Resection: 2959
-- Nb points validated by robust estimation: 2195
-- % points validated: 0.741805
-------------------------------
Resection of Image index: <26> image: 00027.png
-------------------------------
-- Robust Resection of camera index: <26> image: 00027.png
-- Threshold: 8.12696
-- Resection status: OK
-- Nb points used for Resection: 3050
-- Nb points validated by robust estimation: 2204
-- % points validated: 0.722623
-------------------------------
Resection of Image index: <27> image: 00028.png
-------------------------------
-- Robust Resection of camera index: <27> image: 00028.png
-- Threshold: 5.02231
-- Resection status: OK
-- Nb points used for Resection: 3123
-- Nb points validated by robust estimation: 2346
-- % points validated: 0.751201
-------------------------------
Resection of Image index: <28> image: 00029.png
-------------------------------
-- Robust Resection of camera index: <28> image: 00029.png
-- Threshold: 5.33436
-- Resection status: OK
-- Nb points used for Resection: 3517
-- Nb points validated by robust estimation: 2642
-- % points validated: 0.751208
-------------------------------
Resection of Image index: <31> image: 00032.png
-------------------------------
-- Robust Resection of camera index: <31> image: 00032.png
-- Threshold: 16.2368
-- Resection status: OK
-- Nb points used for Resection: 3298
-- Nb points validated by robust estimation: 2718
-- % points validated: 0.824136
-------------------------------
Resection of Image index: <29> image: 00030.png
-------------------------------
-- Robust Resection of camera index: <29> image: 00030.png
-- Threshold: 7.22664
-- Resection status: OK
-- Nb points used for Resection: 3239
-- Nb points validated by robust estimation: 2554
-- % points validated: 0.788515
-------------------------------
Resection of Image index: <30> image: 00031.png
-------------------------------
-- Robust Resection of camera index: <30> image: 00031.png
-- Threshold: 11.6823
-- Resection status: OK
-- Nb points used for Resection: 3008
-- Nb points validated by robust estimation: 2516
-- % points validated: 0.836436
-------------------------------
Structure from Motion process finished.
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 32 from 32 input images.
-- #Tracks, #3D points: 61853
-------------------------------
Histogram of reprojection-residuals

**Comment by pmoulon** [comment]
Some steps are involving some random generation number (RANSAC). It could be generating something bad in one of the instances you ran.

In one case the initial two-view reconstruction to bootstrap the reconstruction seems to have failed and certainly produced a degenerative model

**Comment by pmoulon** [comment]
Closed due to inactivity. Feel free to reopen if needed
