### ISSUE TITLE
Scale of result model

### ISSUE THREAD

**Issue by otakarkuchar** [openMVG/openMVG#1839]
Hey, I would like to ask you.
I used the same data for SW Alicona mex and for openMVG.

I look great result from openMVG, but I have one problem, the model from openMVG its much more smaller than form Alicona...
Why scale is different? Which values I should insert to Exif of image to control this scale? Do you use Exif information? I know, that I can control it by Focal length in pixels.. 
Thank you for your help

**Comment by rperrot** [comment]
The reconstruction of openMVG is correct up-to scale, and there is no possibility to provide correct scaling without a distance information. 

The only solution is to scale the scene by yourself given that you know the distance between two reconstructed points (distance between two windows, height of a building, ...). Applying simple proportionality rule will give you the correct scale.

**Comment by otakarkuchar** [comment]
Thank you so much for reply,
Is it possible to setup some proportionality rule during creating reconstruction or affect by some value on reconstruction? 

Thank you so much

**Comment by rperrot** [comment]
No, that's not possible.
