### ISSUE TITLE
Build successful, but unable to run tutorial_demo.py. No sensor_width_database.txt file?

### ISSUE THREAD

**Issue by EvanLavizadeh** [openMVG/openMVG#1841]
When running:
`python3 tutorial_demo.py`

I get:
```
bash-4.2$ python3 tutorial_demo.py 
Cloning into 'ImageDataset_SceauxCastle'...
remote: Enumerating objects: 17, done.
remote: Total 17 (delta 0), reused 0 (delta 0), pack-reused 17
Unpacking objects: 100% (17/17), done.
Checking out files: 100% (14/14), done.
Using input dir  :  /home/evan/photogrammetry/openMVG_build-main/software/SfM/ImageDataset_SceauxCastle/images
      output_dir :  /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out
1. Intrinsics analysis
 You called : 
/home/evan/photogrammetry/openMVG_build-main/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/evan/photogrammetry/openMVG_build-main/software/SfM/ImageDataset_SceauxCastle/images
--sensorWidthDatabase /home/evan/photogrammetry/openMVG_build-main/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

Invalid input database: /home/evan/photogrammetry/openMVG_build-main/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt, please specify a valid file.
2. Compute features
 You called : 
/home/evan/photogrammetry/openMVG_build-main/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures
--input_file /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json
--outdir /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 1
--numThreads 0


The input file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json" cannot be read
2. Compute matches
 You called : 
/home/evan/photogrammetry/openMVG_build-main/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json
--out_dir /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches
Optional parameters:
--force 1
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method ANNL2
--guided_matching 0
--cache_size unlimited

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json" cannot be read.
3. Do Incremental/Sequential reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json" cannot be read.
5. Colorize Structure

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/reconstruction_sequential/sfm_data.bin" cannot be read.
4. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/reconstruction_sequential/sfm_data.bin" cannot be read.
2. Compute matches (for the global SfM Pipeline)
 You called : 
/home/evan/photogrammetry/openMVG_build-main/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches
--input_file /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json
--out_dir /home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json" cannot be read.
3. Do Global reconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/matches/sfm_data.json" cannot be read.
5. Colorize Structure

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/reconstruction_global/sfm_data.bin" cannot be read.
4. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "/home/evan/photogrammetry/openMVG_build-main/software/SfM/tutorial_out/reconstruction_global/sfm_data.bin" cannot be read.
```

I'm not sure if this is the source of subsequent errors:
`Invalid input database: /home/evan/photogrammetry/openMVG_build-main/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt, please specify a valid file.
`
So, the only files in /home/evan/photogrammetry/openMVG_build-main/openMVG/exif/sensor_width_database are
-CMakeFiles
-cmake_install.cmake
-Makefile

There is no sensor_width_camera_database.txt. What is this file exactly? Is this file supposed to appear during build? Why isn't it here?

**Comment by pmoulon** [comment]
Hi, natively the script must point toward the file from your github checkout and not in the build folder.

If you get a precompiled archive, just look where the files here and adjust the path accordingly in the tutorial_demo.py file

**Comment by lauraset** [comment]
Hi, @pmoulon. I encountered another issue. Everything works fine, but there's no "sfm_data.bin" file. Here is the information:

D:\openMVS\build\openMVG\software\SfM>python tutorial_demo.py
Using input dir  :  D:\openMVS\build\openMVG\software\SfM\ImageDataset_SceauxCastle\images
      output_dir :  D:\openMVS\build\openMVG\software\SfM\tutorial_out
1. Intrinsics analysis
 You called :
D:/openMVS/build/openMVG/Windows-AMD64-Release/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory D:\openMVS\build\openMVG\software\SfM\ImageDataset_SceauxCastle\images
--sensorWidthDatabase D:/openMVS/openMVG/src/openMVG/exif/sensor_width_database\sensor_width_camera_database.txt
--outputDirectory D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches
--focal 2905.88
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 11
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
 You called :
D:/openMVS/build/openMVG/Windows-AMD64-Release/Release\openMVG_main_ComputeFeatures
--input_file D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches/sfm_data.json
--outdir D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 1
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 12
2. Compute matches
 You called :
D:/openMVS/build/openMVG/Windows-AMD64-Release/Release\openMVG_main_ComputeMatches
--input_file D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches/sfm_data.json
--out_dir D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches
Optional parameters:
--force 1
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method ANNL2
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using ANN_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 2
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
        #nodes: 11
        #cc: 1
        #singleton: 0
        Node degree statistics: min: 10, max: 10, mean: 10, median: 10

 Export Adjacency Matrix of the pairwise's geometric matches
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
3. Do Incremental/Sequential reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 6655
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
------------------
TrackLength, Occurrence
        2       3094
        3       1347
        4       705
        5       488
        6       279
        7       261
        8       219
        9       168
        10      73
        11      21

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
A-Contrario initial pair residual: 25.3718
5. Colorize Structure

The input SfM_Data file "D:\openMVS\build\openMVG\software\SfM\tutorial_out\reconstruction_sequential/sfm_data.bin" cannot be read.
4. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "D:\openMVS\build\openMVG\software\SfM\tutorial_out\reconstruction_sequential/sfm_data.bin" cannot be read.
2. Compute matches (for the global SfM Pipeline)
 You called :
D:/openMVS/build/openMVG/Windows-AMD64-Release/Release\openMVG_main_ComputeMatches
--input_file D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches/sfm_data.json
--out_dir D:\openMVS\build\openMVG\software\SfM\tutorial_out\matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model e
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
         PREVIOUS RESULTS LOADED; #pair: 55
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0
Graph statistics:
        #nodes: 11
        #cc: 1
        #singleton: 0
        Node degree statistics: min: 6, max: 10, mean: 8, median: 9

 Export Adjacency Matrix of the pairwise's geometric matches
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
3. Do Global reconstruction

-----------------------------------------------------------
Global Structure from Motion:
-----------------------------------------------------------
Open Source implementation of the paper:
"Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."
Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
------------------------------------------------------------

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
Connected component of size: 11

- Relative pose computation -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************5. Colorize Structure

The input SfM_Data file "D:\openMVS\build\openMVG\software\SfM\tutorial_out\reconstruction_global/sfm_data.bin" cannot be read.
4. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "D:\openMVS\build\openMVG\software\SfM\tutorial_out\reconstruction_global/sfm_data.bin" cannot be read.

**Comment by pmoulon** [comment]
Can you remove the matches folder and try again?

**Comment by lauraset** [comment]
I tried, but it still doesn't work. I use windows10 + vs2015 + openmvg 1.6 + cmake. Is the version of openmvg is too high?

**Comment by pmoulon** [comment]
Did you try to compile OpenMVG with the unit test and run them to see if something is wrong?

**Comment by lauraset** [comment]
Hi, pmoulon, what is the unit test?

**Comment by pmoulon** [comment]
Unit test are small program that assert that the library is compiled and execute correctly on your local machine.
It helps to track regression and help long term development (see Test Driven Development).
Set OpenMVG_BUILD_TESTS  to ON with CMAKE
Then build the test target

**Comment by lauraset** [comment]
Is this information right?
```
D:\openMVS\build\openMVG\Windows-AMD64-Release\Release>openMVG_test_sequential_SfM2.exe


 Launching Test : class SEQUENTIAL_SFM2_STELLAR_Known_Intrinsics_Test


- Relative pose computation -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************
***************************************
*
*

D:\openMVS\build\openMVG\Windows-AMD64-Release\Release>openMVG_test_global_SfM.exe


 Launching Test : class GLOBAL_SFM_RotationAveragingL2_TranslationAveragingSoftL1_Test


CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
Connected component of size: 6

- Relative pose computation -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************************
**********
*
```

**Comment by pmoulon** [comment]
You should be able to launch all the test from Visual Studio by compiling the TESTS target and you will see a report if there is failure

**Comment by lauraset** [comment]
ok. I will try it. thank you, pmoulon

**Comment by pmoulon** [comment]
You're welcome, it is could possible that you have a strange configuration that make ceres and openmvg not using the same version of Eigen.
You can also share here the CMAKE output of your CMAKE configure step, it could perhaps helps us to identify something strange

**Comment by lauraset** [comment]
Thank you, pmoulon. I changed to ubuntu 16.04 system, and succeed now. I also think the versions of ceres and openmvg are not the same when I use window 10 system. Thank you for your help.
