### ISSUE TITLE
[software] Add an image collection matching benchmark

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#1845]
This benchmark allows comparing the different image-regions-matcher.

- By default Brute-force L2 is considered as GT
- And we are comparing `"hnsw_l1", "hnsw_l2", "ann_l2", "cascade_l2", "fast_cascade_l2"` to it.

- Statistics on time and retrieval accuracy (overlapping of retrieved features matches {a,b},{},... for pairs {i,j}.)
  - accuracy measure as overlap of `[{i,j}, {{a,b},...}]` to the GT

# Evaluation on multiple image dataset

| Testing behavior (time vs accuracy) on 5 dataset (each having 100ish images): |
|-|
| ![image](https://user-images.githubusercontent.com/3235050/105130430-de3e7d00-5a9b-11eb-8c8e-cd55edeeb6c8.png) |
|Early conclusion: <br> **Accuracy**: HNSWL2 > ANNL2 > CascadeL2 > FastCascadeL2 <br> **Speed**: FastCascadeL2 >  HNSWL2 > CascadeL2 > ANNL2 |

Running it on image dataset with fewer features could show different behavior where BFL2 could be faster (since ANN methods need to index the reference feature space before any search operation).

Kudos to @rjanvier for drafting this binary and helping us better understand the trade-off between accuracy vs. speed of our image matcher!

CC @vadixidav (FYI, you can skim this post quickly) => It would be very fun to experiment with https://github.com/rust-cv/hnsw to match the OpenMVG features stored as binary in the *.desc ;-)

=> A similar experiment could be done on binary matches ;-) => Feel free to help us do that!

**Comment by vadixidav** [comment]
@pmoulon I would love to give that a try. I have wanted a standardized test dataset for so long. Love the work you are doing. I will let you know when I get a chance to set that up.
