### ISSUE TITLE
Possible eigen unaligned memory access

### ISSUE THREAD

**Issue by mitjap** [openMVG/openMVG#1846]
I might have found a potential issue with unaligned Eigen objects and `std::vector`.

I think the issue is with `Half_plane`  and `Half_planes` definitions https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG/geometry/half_space_intersection.hpp#L27
There are some `std::vector` specializations https://github.com/openMVG/openMVG/blob/74deb33d12bf275a3b3a9afc833f4760be90f031/src/openMVG/numeric/eigen_alias_definition.hpp#L142 that solve this kind of issues but do not include `Eigen::Hyperplane` type. The solution would be to add specialization or use `using Half_plane = Eigen::Hyperplane<double, 3, DontAlign>` as type definition.

**Comment by pmoulon** [comment]
We are calling this just before https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG/geometry/half_space_intersection.hpp#L14 so I think we should be safe.

Did you encounter any compilation or running time issue?

**Comment by mitjap** [comment]
You are right. I completely missed this call. I did not encounter any issues, just got suspicious when I was looking at the code.

**Comment by pmoulon** [comment]
No worries. It is better to double-check!
