### ISSUE TITLE
extracted camera rotations not quite right

### ISSUE THREAD

**Issue by leeliop** [openMVG/openMVG#1849]
I use **openMVG_main_ConvertSfM_DataFormat** to extract camera extrinsics for positioning camera objects in Blender - but when I decompose the rotation matrices for each camera into euler angles, the camera objects don't quite line up with the imported mesh or cloud files, and causes problems with subsequent operations. When I import the camera frustrums I can see that the centerline of my camera objects are not matching the centreline of the frustrum models and seem off by a few degrees

Does anyone know if this is an issue with my interpretation of the data or perhaps a sequence problem whereby I have extracted the camera rotations before/after some kind of adjustment?

**Comment by pmoulon** [comment]
Please use this project to import sfm_data.json results to Blender https://github.com/openMVG/openMVG/issues/1585

**Comment by leeliop** [comment]
> Please use this project to import sfm_data.json results to Blender #1585

Thank for the quick response

I will try that - although I am still interested in the error I am making if anyone knows

**Comment by leeliop** [comment]
camera rotations could not be directed imported from extrinsics in json as principal point adds x/y shift to camera FOV

it is possible to turn off the principal point adjustment for anyone else struggling
