### ISSUE TITLE
cannot seem to combine refine instrinsic options

### ISSUE THREAD

**Issue by leeliop** [openMVG/openMVG#1850]
my goal is to disable the principle point instrinsics

when I use openMVG_main_IncrementalSfM with "-f ADJUST_DISTORTION" for example - the process completes successfully

when I attempt to combine options using " -f ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION " i get a return from the executable:

openMVG_main_IncrementalSfM err=b"'F:' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"_

thank you for this amazing software btw

**Comment by pmoulon** [comment]
Please use `-f "ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION"`
I think your quotes are not at the right place

**Comment by pmoulon** [comment]
@leeliop Did the comment solve your issue? Feel free to reopen the issue
