### ISSUE TITLE
Help with generating disparity map from 2 stereo images

### ISSUE THREAD

**Issue by younesr1** [openMVG/openMVG#1853]
Hello, is there functionality in this library to generate a disparity map from 2 stereo images? If so, is there an example I can look at? Are there any functions I should look into?

**Comment by pmoulon** [comment]
You can take a look here for disparity computation
http://www.ipol.im/pub/art/2015/123/

Or for rectification of stereo images:
https://www.ipol.im/pub/art/2011/m_qer/

**Comment by pmoulon** [comment]
OpenMVG does not have a disparity map computation module, but you can triangulate point from 2 images
