### ISSUE TITLE
issue of  compilation openmvg on windows 

### ISSUE THREAD

**Issue by seuwanglang** [openMVG/openMVG#1856]
when  i  build  ALLINSTALL of  openmvg  in  debug and  release  ，140errors come out  saying tha can not open file  named  "Eigen\Dense".  i am so new in programming and apologize  in advance for  ask so siily question.

**Comment by pmoulon** [comment]
Hello @seuwanglang Could it be a permission issue. Since the files are copied in Program Files, does running VSCode in admin is solving the issue?

There is no silly question ;-)

**Comment by seuwanglang** [comment]
> Hello @seuwanglang Could it be a permission issue. Since the files are copied in Program Files, does running VSCode in admin is solving the issue?
> 
> There is no silly question ;-)

**Comment by seuwanglang** [comment]
hello，i had run vis2015 in admin. but it did not work

**Comment by pmoulon** [comment]
Do you use an internal Eigen or external (it should be listed when you run CMAKE)?

**Comment by pmoulon** [comment]
Closing related issue

**Comment by Camuvingian** [comment]
I am having this same issue. Eigen was resolved well during configuration, but the build fails. Any ideas?

**Comment by pmoulon** [comment]
Hi @Camuvingian what is the build error you see?
- at build time or at install time?
-> if it is as install time it could be due to you needing to run VSCOde as admin to be able to install in program files

**Comment by Camuvingian** [comment]
EIGEN_DIR not found. I have eigen placed he
![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png)
re. 
I have set 
```
Eigen3_DIR=C:/opt/eigen-3.4.0
EIGEN_DIR=C:/opt/eigen-3.4.0
```
via the Cmake GUI. 
I have also set environment variable 
EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0

The CMake configure seems to pickup Eigen okay 

```
   ===============================================================
   Ceres-solver configuration.
   ===============================================================
Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
-- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
```

But, on building ALL_BUILD I see the following errors 

>37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory

which happens for many many projects. In my eigen3.4.4 directory I see the relevant file

![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)

I am not sure why the build cannot locate the Eigen headers?

**Comment by Camuvingian** [comment]
In the projects that fail I see Additional Include Directories "C:\include\eigen3;C:\Dev\C++\openMVG\src;%(AdditionalIncludeDirectories)" - not sure where C:\include\eigen3 comes from??

**Comment by Camuvingian** [comment]
For now I have places eigen3.4.4 in the expected directory. But would be good to establish what in the cmake config is causing this path to get picked up...

**Comment by pmoulon** [comment]
BTW, why the provided Eigen does not make you happy?

**Comment by Camuvingian** [comment]
Not sure why the build config is picking up the wrong directory in this case.

**Comment by insomniaacoma** [comment]
> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?
maybe not helpful, but the proper env variable to be set should be EIGEN_ROOT


> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?



> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?

**Comment by insomniaacoma** [comment]
> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?



> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?



> EIGEN_DIR not found. I have eigen placed he ![image](https://user-images.githubusercontent.com/4823601/167100330-8093968c-856e-4792-a70d-49b0f6ea61c8.png) re. I have set
> 
> ```
> Eigen3_DIR=C:/opt/eigen-3.4.0
> EIGEN_DIR=C:/opt/eigen-3.4.0
> ```
> 
> via the Cmake GUI. I have also set environment variable EIGEN_INCLUDE_DIR_HINTS=C:/opt/eigen-3.4.0
> 
> The CMake configure seems to pickup Eigen okay
> 
> ```
>    ===============================================================
>    Ceres-solver configuration.
>    ===============================================================
> Detected Ceres version: 1.13.0 from C:/Dev/C++/openMVG/src/third_party/ceres-solver/include/ceres/version.h
> Eigen 3.4.0 found (include: C:/opt/eigen-3.4.0/)
> -- Found Eigen version 3.4.0: C:/opt/eigen-3.4.0/
> ```
> 
> But, on building ALL_BUILD I see the following errors
> 
> > 37>C:\Dev\C++\openMVG\src\openMVG/numeric/eigen_alias_definition.hpp(17,10): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
> 
> which happens for many many projects. In my eigen3.4.4 directory I see the relevant file
> 
> ![image](https://user-images.githubusercontent.com/4823601/167101975-14406f5a-7ced-48bb-9f4c-06ce5ee405ab.png)
> 
> I am not sure why the build cannot locate the Eigen headers?

maybe not helpful, but the proper env variable to be set should be EIGEN_ROOT
