### ISSUE TITLE
hello，does anybody tell me how exactly install openmvg on win64 vs2015，i had try many ways but did not work

### ISSUE THREAD

**Issue by seuwanglang** [openMVG/openMVG#1859]

**Comment by pmoulon** [comment]
Duplicate of https://github.com/openMVG/openMVG/issues/1856
Can you share your cmake and VS studio log there?

**Comment by pmoulon** [comment]
If you need an existing OpenMVG version, there is a pre-compiled version ready to use here https://github.com/openMVG/openMVG/releases/tag/v1.6

**Comment by seuwanglang** [comment]
@pmoulon thank you so much, i have already solve the problems.

**Comment by pmoulon** [comment]
I will so close both issues
