### ISSUE TITLE
Which paper is the Localization module based on? Is there any relevant information

### ISSUE THREAD

**Issue by wangni-bupt** [openMVG/openMVG#1865]

**Comment by wangni-bupt** [comment]
I have learned that 2D-3D matching is carried out, which way is adopted? The relevant description in the library is Multiview Module, is that right?

If I want to understand more, what should I look for

**Comment by pmoulon** [comment]
I'm using a very naive approach described here:
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/pipelines/localization/SfM_Localizer_Single_3DTrackObservation_Database.cpp#L43

For each input image, we extract features with the same parameters:
- We compute the closest descriptor in the database (2d to track Id association)
- For each track we retrieve the 3D point that was computed for those tracks
- We estimate a robust pose with Ransac and P3P

If you want to know more I would advise:
- to read or watch the material here https://sites.google.com/view/lsvpr2017/home or the most recent version

**Comment by wangni-bupt** [comment]
Thank you very much. It's very helpful

**Comment by pmoulon** [comment]
I'm closing the issue, feel free to reopen if you have more questions
