### ISSUE TITLE
How to localize set of equirectangular panoramas w/ manually mapped keypoints?

### ISSUE THREAD

**Issue by Degot** [openMVG/openMVG#1867]
Hello, I have 10 outdoor equirectangular panoramas and manually mapped ~20 keypoints in each. Panoramas were done in different light conditions/seasons -> manual mapping was done.  
Is it possible to use OpenMVG to find position, rotation of each panorama?
What are the required steps/algorythm ?

Thank you.

**Comment by pmoulon** [comment]
Hello @Degot ,
Basically here you have establish the correspondences between the panorama, now you want to recover the camera location from those correspondences.

Basically you would have to write some files that OpenMVG expect (.feat, matches.f.txt) and then run SFM
The process is explained there https://github.com/openMVG/openMVG/issues/1739#issuecomment-628377920

If you are willing to share the data, we could work on this as a tutorial for the community
openmvg-team[AT]googlegroups.com

Just by curiosity did you try to match the image with OpenMVG:
https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm
- You can use exportMatches to visualize the putatives or the geometric matches

**Comment by pmoulon** [comment]
@Degot Any feedback?

**Comment by monschine** [comment]
@pmoulon, taking a look at the .feat files, I just saw that not only the xy coordinate is saved but also the scale and orientation values, if we would provide the points manually, can we just set a random value to the scale and orientation or we need to provide some specific value ?

**Comment by monschine** [comment]
Thanks @pmoulon , one last question is how we should generate the .desc file when the features are manually set ?
By computing features and just replacing the .feat file by the one manually generated and keeping the .desc ?
