### ISSUE TITLE
Linker Tools Error LNK2001

### ISSUE THREAD

**Issue by irenjie** [openMVG/openMVG#1868]
I get an error when use **readImage**() function   
**_Linker Tools Error LNK2001,unresolved external symbol "symbol"_**    

I dont know why.**build** incorrect  or other reasons?

**Comment by pmoulon** [comment]
Can you specify your platform (win, linux) and share the output of the cmake configuration?

**Comment by pmoulon** [comment]
Did you follow this instruction to use OpenMVG in your project:
https://github.com/openMVG/openMVG/blob/develop/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake

Basically you see the link error since you are not linking openMVG_image library to your compilation
