### ISSUE TITLE
improve camera poses of camera array 

### ISSUE THREAD

**Issue by markxma1** [openMVG/openMVG#1885]
Hi, I am trying to find the position of the cameras in the camera array (4 cameras are tied to an aluminum profile and won't move from each other) but some have wrong positions. There is only one way to assign a camera to a group and calibrate it as a group (and get the position of the cameras in the group and the group position separately).

I think so in order to improve the position of each camera with the help of other cameras.

**Comment by pmoulon** [comment]
We don't have a rig camera refinement yet but feel free to help to add this step.
THe best to calibrate your rig would be to use a checkerboard and use a calibration toolbox like Kalibr (https://github.com/ethz-asl/kalibr)

**Comment by daisatojp** [comment]
I think it's related to https://github.com/openMVG/openMVG/issues/580

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
