### ISSUE TITLE
Combining SLAM poses with openMVG

### ISSUE THREAD

**Issue by fightmoney** [openMVG/openMVG#1887]
Hello,
I'm trying to run openMVG dense reconstruction with camera poses pre-computed with ORB-SLAM3.
How to put poses into the system?

**Comment by pmoulon** [comment]
I would suggest you to initialize a sfm_data.json from the output of ORB-SLAM3.
You can use OpenMVG API to do that and take inspiration from the importer there https://github.com/openMVG/openMVG/tree/develop/src/software/SfM/import
Let me know if it is helpful

**Comment by RamadanAhmed** [comment]
I think what you should use is a depth/disparity estimation using deep learning or any semi-global matching technique and apply transformation using camera pose to the point cloud you get from the image Just to keep the realtime behavouir of slam. In that case you need filterning techniques to filter overlapped points.

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
