### ISSUE TITLE
How to use the OpenMVG API to fill the sfm_data structure with Spherical camera

### ISSUE THREAD

**Issue by DHNicoles** [openMVG/openMVG#1893]
hi @pmoulon ,  I was looking for how to **import the known poses of 360camera into the sfm_data.json** file, but I couldn't find it. Is there an example of using ComputeStructureFromKnownPoses for a spherical camera?

I have read the source code here, maybe I missed something ？
`io_loadImages.hpp   
 io_readGTETH3D.hpp     
 io_readGTKitti.hpp       
io_readGTStrecha.hpp
io_readGTDTUMVS.hpp  
io_readGTInterface.hpp  
io_readGTMiddleBury.hpp  
main_SfMInit_ImageListingFromKnownPoses.cpp`

Please help me, thank you.

**Comment by pmoulon** [comment]
Redirecting you here: https://github.com/openMVG/openMVG/issues/1892#issuecomment-845644482
But basically you have to do the same as the readGTX but just initialize a spherical camera... or start from an existing JSON file and just complete it with a Python script.

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
