### ISSUE TITLE
Problem with "uncalibrated image" - from 49, only 26 photos works

### ISSUE THREAD

**Issue by cogitas3d** [openMVG/openMVG#1894]
Hey there!

I'm doing some studies of face scanning using OpenMVG+OpenMVS. In this study we use a protocol with 49 photos (http://ortogonline.com/doc/pt_br/OrtogOnLineMag/1/Nariz.html).

Usually it works well, but some photos made with Iphone RX had problems with down captures.

![Captura de tela_2021-05-22_12-08-37](https://user-images.githubusercontent.com/2422483/119233397-dac50c00-baf6-11eb-98d8-427ab4dc9dd1.png)

We have three levels of photos, but only two was used to make the dense cloud. From 49 photos only 26 was used. I open the PLY openMVG file and Iwe can see the two levels.

One of the OpenMVG outputs:

> #landmark found: 4020
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 49
 #poses: 26
 #intrinsics: 1
 #tracks: 4020

One of outputs of OpenMVG:

> 12:14:55 [App     ] warning: uncalibrated image 'undistorted_images/26.jpg'

And:

> 	49 images (26 calibrated) with a total of 119.60 MPixels (4.60 MPixels/image)
	5952 points, 0 vertices, 0 faces
12:14:55 [App     ] Preparing images for dense reconstruction completed: 49 images (113ms)
12:14:55 [App     ] Selecting images for dense reconstruction completed: 26 images (10ms)

I test it on Metashape with the same photos:

![Captura de tela_2021-05-22_12-14-55](https://user-images.githubusercontent.com/2422483/119233504-79516d00-baf7-11eb-847f-af0bb99902df.png)

And it works, even in MVE+SMVS. But we would like to make it work on OpenMVG+OpenMVS, because th time and the texture are really good.

I research on Issues and on documentation about the error and some possibilities to solve it, but in all code changes the problem (only 26 photos used) continues.

Is it possible do something to solve this?

Thank you and a big hug!

**Comment by rperrot** [comment]
Hi, 

Did you try : 
- increasing number of features ? (using preset HIGH or ULTRA ?)
- using another feature detector (I remember an other user employed AKAZE on faces)

What method of reconstruction did you used ? global ? incremental/sequential ? 

Yours.

**Comment by cogitas3d** [comment]
Dear @rperrot 

Thank you very much to answer.

increasing number of features ? (using preset HIGH or ULTRA ?) --> **YES**
using another feature detector (I remember an other user employed AKAZE on faces) --> **YES**
What method of reconstruction did you used ? global ? incremental/sequential ? --> **I try with the two options**.

**Comment by pmoulon** [comment]
I wonder if the 3 stack of images are connected in the image graph.
If you have graphviz installed on you system, a file should allow you to see the visual graph (if images are connected) -> geometric_matches.svg.

If you see there only one component in the graph, we should be able to register all the images.

Did you try to run IncrementalSfM2 on this dataset, either from scratch or with the output of your first pass.

**Comment by cogitas3d** [comment]
Dear master @pmoulon,

Sure!

![Captura de tela_2021-05-26_07-45-25](https://user-images.githubusercontent.com/2422483/119654384-68a23f00-bdf6-11eb-8384-02edac49cea9.png)

All .SVG files:
[All_SVGs.zip](https://github.com/openMVG/openMVG/files/6546410/All_SVGs.zip)

Thank you!

**Comment by pmoulon** [comment]
So yes here we see that there is two connected component.
What you could try is to rerun matching by using the camera model you found with the SFM reconstruction that worked.
To do so, you will have to set the sfm_data.bin from your incremental reconstruction as input of your ComputeMatches binary

**Comment by pmoulon** [comment]
Hi @cogitas3d , sorry for checking so late... any follow-up or help we can provide?
