### ISSUE TITLE
make test  -- error: 	 57 - openMVG_test_translation_averaging (Subprocess aborted) 	 75 - openMVG_test_sfm_data_BA (Subprocess aborted) 	 80 - openMVG_test_global_SfM (Subprocess aborted) 	 81 - openMVG_test_sequential_SfM (Subprocess aborted) 	 82 - openMVG_test_sequential_SfM2 (Subprocess aborted) 	 83 - openMVG_test_stellar_SfM (Subprocess aborted)

### ISSUE THREAD

**Issue by lixz10111** [openMVG/openMVG#1897]

**Comment by pmoulon** [comment]
Hello @lixz10111 Most of the time this error is due to a different version of Eigen used by Ceres and OpenMVG.
Can you check the log of CMAKE configure and see if you are using the same version of Eigen for both libraries (Ceres and OpenMVG)?

**Comment by lixz10111** [comment]
> Hello @lixz10111 Most of the time this error is due to a different version of Eigen used by Ceres and OpenMVG.
> Can you check the log of CMAKE configure and see if you are using the same version of Eigen for both libraries (Ceres and OpenMVG)?

my CMAKE is:
-- CEREAL: (internal)
-- EIGEN:  (external)
-- CERES: 2.0.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.34 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)
and eigen version is 3.3.4

**Comment by lixz10111** [comment]
> Hello @lixz10111 Most of the time this error is due to a different version of Eigen used by Ceres and OpenMVG.
> Can you check the log of CMAKE configure and see if you are using the same version of Eigen for both libraries (Ceres and OpenMVG)?

hi,  pmoulon , my cmake is:
-- CEREAL: (internal)
-- EIGEN: (external)
-- CERES: 2.0.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.34 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: (internal)
-- LEMON: 1.3 (internal)
and eigen version is 3.3.4
 which eigen verison and ceres version is I need. pelease tell me ,thank you

**Comment by pmoulon** [comment]
Seems like you are using the same version for Ceres and Eigen.
Can we try to force OpenMVG to be built with the internal Ceres to understand better the issue?
- Can you comment this line and try compile again https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L268

**Comment by lixz10111** [comment]
@pmoulon, hi, friend,  I try compile again in [https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L268](url), error is same, build/software/SfM/tutorial_out/reconstruction_global/sfm_data.bin" cannot be read．
so, which eigen verison and ceres version is I need. pelease tell me ,thank you aggain

**Comment by pmoulon** [comment]
But does OpenMVG unit test ran fine with this last change?

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
