### ISSUE TITLE
 how 　visualization　sfm_data.bin

### ISSUE THREAD

**Issue by lixz10111** [openMVG/openMVG#1899]
Hi, friend, I run python tutorial_demo.py and obtain sfm_data.bin, how visualization sfm_data.bin

**Comment by A1ecm** [comment]
If you check in the matches folder that is created there should be a sfm_data.json

**Comment by hwang051785** [comment]
You can use binary "openMVG_main_ConvertSfM_DataFormat" to convert it into "sfm_data.json", then you can check it using python. Note that you need to add optional arguments -V -I -E since converting the whole structure into ".json" will produce a huge file.

**Comment by pmoulon** [comment]
You have PLY files that are exported (cloud_and_poses.ply) that you can open with Meshlab, CCViewer or CloudCompare.
Else as @hwang051785  pointed you can use the `openMVG_main_ConvertSfM_DataFormat` to convert a sfm_data.bin to a sfm_data.json or sfm_data.ply. So then you can read the file in your own app or load it in a 3d viewer

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
