### ISSUE TITLE
How to limit the number of match points

### ISSUE THREAD

**Issue by Jiatutu** [openMVG/openMVG#1901]
If too many points are matched, the SFM process will be too slow. So, can I control the number of match points.

**Comment by pmoulon** [comment]
You can use the https://github.com/openMVG/openMVG/blob/develop_2.0/src/software/SfM/main_ComputeMatches.cpp#L109 `--preemptive_feature_count X` on main_ComputeMatches it will use only the X largest scale keypoints detected.
Else you can downsize your image, perform SfM and then copy the poses from one scene to another and retriangulate  matches on your large images

**Comment by pmoulon** [comment]
You can play with the code and adapt this value and parameter to be a percentage if you want too

**Comment by Jiatutu** [comment]
> You can use the https://github.com/openMVG/openMVG/blob/develop_2.0/src/software/SfM/main_ComputeMatches.cpp#L109 `--preemptive_feature_count X` on main_ComputeMatches it will use only the X largest scale keypoints detected.
> Else you can downsize your image, perform SfM and then copy the poses from one scene to another and retriangulate matches on your large images
when i downsize my image, how can i do the SFM, and when recover the size, Could you be more specific?

**Comment by pmoulon** [comment]
Let me try to document this in the wiki later this week

**Comment by pmoulon** [comment]
See here demo to use [VLAD](https://github.com/openMVG/Image_datasets/tree/main/Drone#using-vlad-similarity-image-pair-selection-demo----no-gps-consideration) or [Pre-emptive feature matching](https://github.com/openMVG/Image_datasets/tree/main/Drone#using-preemptive-matching-for-image-pair-selection-demo----no-gps-consideration)
