### ISSUE TITLE
ui_openMVG_MatchesViewer seems not working properly

### ISSUE THREAD

**Issue by hwang051785** [openMVG/openMVG#1903]
Hi Pierre,

I am trying to use the binary "ui_openMVG_MatchesViewer" to visualize the match results computed from the SceauxCastle example. I follow #831  https://github.com/openMVG/openMVG/issues/831 with no success

More specifically, I run the ui_openMVG_MatchesViewer, then load "sfm_data.bin" and "matches.f.bin", after that I got the error message "Invalid feature files for the view".

No error during the sequential pipeline. The sparse point cloud is perfect and can be visualized by Meshlab.

This issue can be well reproduced.

Thank you for more insights on this,

Jack

**Comment by hwang051785** [comment]
More information regarding the running environment: Windows 10 with Qt5.9.9 and compiled with MSVS 2017.

**Comment by pmoulon** [comment]
Please consider use the sfm_data.json that is in the same folder as the matches...
or copy your sfm_data.bin to the same folder as the matches... I think we are evaluating on the fly the path and making this assumption..

**Comment by hwang051785** [comment]
> Please consider use the sfm_data.json that is in the same folder as the matches...
> or copy your sfm_data.bin to the same folder as the matches... I think we are evaluating on the fly the path and making this assumption..

Thanks, Pierre. Yes, when I use the initial sfm_data.json from the same folder as the match file, the issue is gone. So the reason behind that is the "hidden" path requirement/assumption. One more last question: what is the purpose of the "openGL" and "anti-aliasing" buttons on the top-right side?  

I think I can close it since the problem is solved.
