### ISSUE TITLE
How do I properly use GlobalSFM with IncrementalSfM2

### ISSUE THREAD

**Issue by 3XH6R** [openMVG/openMVG#1904]
How do I properly use the export of GlobalSFM with IncrementalSfM2 to process the remaining images?

**Comment by pmoulon** [comment]
GlobalSfM will give you a sfm_data.bin that you can provide as an input to IncrementalSfM2 and in this last binary, you use the mode where you use known poses `--sfm_initializer EXISTING_POSE`

**Comment by 3XH6R** [comment]
Thank you
-i %reconstruction_dir%/sfm_data.bin -m %matches_dir% -o %reconstruction_dir% --sfm_initializer EXISTING_POSE --match_file %matches_dir%/matches.e.bin

From start to SFM bin:---------
GlobalSFM		65s 12/36
SFM2			75s 36/36
GlobalSFM+SFM2	76s 36/36

Same type of results on a 145 image dataset. How big should a dataset be to see time saved?
