### ISSUE TITLE
usage in unity

### ISSUE THREAD

**Issue by Ademord** [openMVG/openMVG#1905]
Hello, I am new to this project and the Multiple View Geometry world. I am thinking of training an RL agent to reconstruct a scene based on some sort of confidence level of the reconstruction (which would be the reward for the agent), and I ran into this repo. I am doing RL with Unity and MLAgents and was wondering if you could help me out on how could I use openMVG either in Python? I am trying to google but I can't seem to find anything? and in C#?
Thanks in advance

**Comment by pmoulon** [comment]
OpenMVG is mainly written in python, we have some script that allow to run OpenMVG binaries using Python, but this is not a python wrapper.
If you want help us write Python wrapper, feel free to join and help us on this adventure!

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
