### ISSUE TITLE
Understanding repo branches

### ISSUE THREAD

**Issue by manurare** [openMVG/openMVG#1906]
Hi,

I am interested in using functionalities present in two different branches: `develop2.0` and `develop2.0_fixed_extrinisics_in_ba`. Do they overlap? I mean if I clone `develop2.0_fixed_extrinisics_in_ba` does it have everything in `develop2.0` plus the extension on BA?

Thanks

**Comment by pmoulon** [comment]
Yes, develop2.0_fixed_extrinisics_in_ba  is merged in develop2.0
By looking to the last commit in develop2.0_fixed_extrinisics_in_ba   you can see that the commit is included in two branches
![image](https://user-images.githubusercontent.com/3235050/122657618-0d741b80-d11a-11eb-95b0-9a831b82aaba.png)
