### ISSUE TITLE
Input of Jacobians

### ISSUE THREAD

**Issue by Skopfy** [openMVG/openMVG#1907]
Hello,

want to find out the following: 
What are the exact functions which get derived by ceres? 
E.g: 
Q(u) = fx * X/Z + cx
Q(v) = fy * Y/Z + cy
After which symbol is which column of the jacobian derived?
E.g.:
col                : 0    1   2    3   4  5   6 7 8  9  10 11 12
Deriv symbol: Rx Ry Rz Tx Ty Tz u v cx cy X   Y   Z 
I already found out by using Ceres::Problem.evaluate(...., jacobi) how to print the jacobi computed by OpenMVG. 
The result seems to be 2x15 (non zero values) Jacobians for K3 Cam Model and 2x9  for no cam model. 
Also looked at the cam functors written at  [1](https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG/sfm/sfm_data_BA_ceres_camera_functor.hpp), but I still cannot fathom which functions exactly get derived.
My goal would be to redirect the output of OpenMVG before the Bundle adjustment to the GPU where the Jacobians get computed.
(i dont change anything in OpenMVG before that step, i.e. featrue detection , matching stay as they are.
)
Best Regards and Thanks for this wonderful repository!

**Comment by pmoulon** [comment]
Thank you for your comment about our repo.
Ceres functors for residual computation are defined here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data_BA_ceres_camera_functor.hpp
Depending of your camera model the jacobian will be more or less complex.
I would start with the most basic pinhole (no disto) for your test

**Comment by pmoulon** [comment]
Closing due to last of activity. Feel free to reopen.
