### ISSUE TITLE
Low number of features compared to Meshroom/Alicevision on low resolution images.

### ISSUE THREAD

**Issue by tmurphy0** [openMVG/openMVG#1909]
Hi,

On low resolution images (640x480), OpenMVG computes about 1/10th the number of features compared to Meshroom. The following table is with `--describerPreset ULTRA` in OpenMVG and `normal` in Meshroom. The rest is the default SfM_SequentialPipeline.py.

image set | image size | #images | #features OpenMVG | #features Meshroom | #features/image OpenMVG | #features/image Meshroom
------------- | -------------- | ------------ | --------------------------- | ---------------------------- |------------------------------------- | --------------------
buddha | 2736x1540 | 67 | 1373188 | 1340000 | 20495 | 20000
castle | 2832x2128 | 11 | 800638 | 220000 | 72785 | 20000
custom1 | 640x480 | 10 | 6747 | 56134 | **675** | **5613**
custom2 | 640x480 | 71 | 54476 | 343167 | **767** | **4833**

(#features obtained by `cat *.feat | wc -l`)

I thought Meshroom forked OpenMVG so I was expecting similar results. How come they so different and is there a way to increase the number of features on OpenMVG to be more similar to Meshroom? 

The reason I'm asking is because I think this might be the reason I've seen cases where OpenMVG is unable to do a reconstruction while Meshroom can. Thanks!

**Comment by pmoulon** [comment]
Hello @tmurphy0 
Take a look to the value defined in the preset, you will see that AliceVision and OpenMVG does not use the same default value for the SIFT parameters, or even not the same SIFT implementation.
I think Alicevision is also using some bucketing.

Matching can also play a keep role here, you can switch to HNSWL2on ComputeMatches. For some dataset CascadeHashing does not respond as good as some other.

**Comment by pmoulon** [comment]
@tmurphy0 Any feedback, please reopen if you do so...
