### ISSUE TITLE
Different ways to use known poses

### ISSUE THREAD

**Issue by tmurphy0** [openMVG/openMVG#1913]
There seem to be 3 ways to incorporate known poses into a reconstruction
1. As a pose prior in `sfm_data.views `
2. Setting `sfm_data.poses` and then running `IncrementalSfm2` with `SfMSceneInitializer` instead of `SfMSceneInitializerMaxPair`
3. using `ComputeStructureFromKnownPoses`

What's the difference between these and which one should I use in which case? It seems (2) and (3) will do at most one bundle adjustment, while (1) will do multiple. So is the idea to use (1) when the poses might be a little noisy, while (2) and (3) are for poses that come from a previous reconstruction?

Also, is (1) supposed to take both prior centers and rotations into account? I currently only see it using the prior centers, not the rotations.

**Comment by pmoulon** [comment]
Hello @tmurphy0 and thank you for your interest and question.

- You are right 1 is only working with the center prior, I was expecting support from the community to develop and add rotation prior.
- While 2 and 3 are for poses from a previous reconstruction, or coming from a GT dataset (see here https://github.com/openMVG/openMVG/tree/develop/src/software/SfM/import)

> What's the difference between these and which one should I use in which case?

1. is currently used for GPS position prior.
2. can be used to extend an existing reconstruction (i.e global SfM reconstruct 80% of camera, and IncrementaSfM2 will add the remaining weak camera) or to triangulate point from a scene where you know the cameras (SfMImport)
3. can find the corresponding points using the existing geometry (epipolar guided matching) and then merge points in tracks, or triangulate a matching file

Let me know if you need more detail, or if you think a wiki page on this topic would be valuable

**Comment by pmoulon** [comment]
@tmurphy0 any feedback?

**Comment by Airplane5** [comment]
Hello @pmoulon !
I wanna ask a question described below about prior pose information.
/*
1) It seems that openMVG-2.0 can read prior pose from sfm_data, but version of my openMVG is 1.x. For some reason, changing openMVG to 2.0 may cause much more trouble. So I want to know  how to solve 2).
2) I input some prior pose from txt format and add a function to store those in a std::map<image_name,Pose3>.
In the same time, I load a sfm_data.json without GT pose. By checking image_name, I want to add Pose3 into sfm_data.views , but I don't know which function or head file can add those information.
*/
I know we can transform View to ViewPrior, but now how to inverse is really a problem for me.
Just need a head file or function name to look up, thank you very much.

**Comment by Airplane5** [comment]
sorry for last garrulous reply.
In a word, how to merge pose that from txt file into sfm_data.view.
Thank you again!

**Comment by pmoulon** [comment]
You will need to write your own converter.
First use SfMInitListing then use a small python script that will populate pose information by mapping your information from your txt file to the sfm_data file.
