### ISSUE TITLE
find_package getting error on thirdparty/Eigen Any solution please?

### ISSUE THREAD

**Issue by philopkid** [openMVG/openMVG#1917]
I cant figure this error.

CMake Error at cmakeFindModules/FindEigen.cmake:53 (MESSAGE):
You are attempting to build without Eigen.  Please use cmake variable
-DEIGEN_INCLUDE_DIR_HINTS:STRING="PATH" or EIGEN_INCLUDE_DIR_HINTS env.
variable to a valid Eigen path.  Or install last Eigen version.
Call Stack (most recent call first):
CMakeLists.txt:263 (find_package)

**Comment by pmoulon** [comment]
Hello:
1. Can you add in the command line -DEIGEN_INCLUDE_DIR_HINTS:<the full path of Eigen that is inside the OpenMVG third party folder>?

**Comment by philopkid** [comment]
Ive already solved it. Tnx for the reply but that is not the answer to the problem. Ive been looking at the wrong way/direction. Turned out it was easy. The only problem is no comprehensive instruction/documentation. I had to read everything about the whole programs and the use of toolchains and learning cmake syntax and command. which is my first time cross-compiling. Im still trying to learn cmake from scratch.

**Comment by pmoulon** [comment]
Feel free to help us update the documentation

**Comment by philopkid** [comment]
What i mean is to integrate it in cmakelist. When I finished it. I'll add some to the documentation. Im still trying to learn the whole cmake syntax.

**Comment by pmoulon** [comment]
Thx. Will close this thread for now

**Comment by neelgajera** [comment]
@philopkid  how to solve this Error ??
