### ISSUE TITLE
intrinsic change

### ISSUE THREAD

**Issue by wangni-bupt** [openMVG/openMVG#1918]
I used the same phone to shoot different images, and the final intrinsic parameters were very different, what was the reason？
 "focal_length": 3627.9039758691944,
                        "principal_point": [
                            5775.214678214678,
                            3540.253186140406
                        ],
                        "disto_k3": [
                            0.06402922204424923,
                            -0.04491527400498934,
                            0.008529034176757239
                        ]
"focal_length": 4251.315045286024,
                        "principal_point": [
                            3161.5509755133409,
                            1190.7246243804326
                        ],
                        "disto_k3": [
                            -0.06922816661023888,
                            -0.4371889572083001,
                            1.0673980928956109
                        ]
I am trying to operate with the point cloud provided by OpenMVG, but I am confused by the inconsistency of intrinsic

**Comment by pmoulon** [comment]
Can you tell us more about your settings (are you sure all the images were taken with the same focal length and resolution settings)?
- OpenMVG by default will group images to the same camera if they share the same focal and width, height

Please share your initial sfm_data.json or try to use force grouping on InitImageListing by using -g 1

**Comment by wangni-bupt** [comment]
{
    "sfm_data_version": "0.3",
    "root_path": "/home/private/3dobject/image3",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174806.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174808.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 1,
                        "id_intrinsic": 0,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174810.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 2,
                        "id_intrinsic": 0,
                        "id_pose": 2
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483652,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174812.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 3,
                        "id_intrinsic": 0,
                        "id_pose": 3
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174815.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 4,
                        "id_intrinsic": 0,
                        "id_pose": 4
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483654,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174817.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 5,
                        "id_intrinsic": 0,
                        "id_pose": 5
                    }
                }
            }
        },
        {
            "key": 6,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483655,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174819.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 6,
                        "id_intrinsic": 0,
                        "id_pose": 6
                    }
                }
            }
        },
        {
            "key": 7,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483656,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174822.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 7,
                        "id_intrinsic": 0,
                        "id_pose": 7
                    }
                }
            }
        },
        {
            "key": 8,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483657,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174824.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 8,
                        "id_intrinsic": 0,
                        "id_pose": 8
                    }
                }
            }
        },
        {
            "key": 9,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483658,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174827.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 9,
                        "id_intrinsic": 0,
                        "id_pose": 9
                    }
                }
            }
        },
        {
            "key": 10,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483659,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174829.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 10,
                        "id_intrinsic": 0,
                        "id_pose": 10
                    }
                }
            }
        },
        {
            "key": 11,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174832.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 11,
                        "id_intrinsic": 0,
                        "id_pose": 11
                    }
                }
            }
        },
        {
            "key": 12,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483661,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174834.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 12,
                        "id_intrinsic": 0,
                        "id_pose": 12
                    }
                }
            }
        },
        {
            "key": 13,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483662,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174836.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 13,
                        "id_intrinsic": 0,
                        "id_pose": 13
                    }
                }
            }
        },
        {
            "key": 14,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483663,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174838.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 14,
                        "id_intrinsic": 0,
                        "id_pose": 14
                    }
                }
            }
        },
        {
            "key": 15,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483664,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174851.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 15,
                        "id_intrinsic": 0,
                        "id_pose": 15
                    }
                }
            }
        },
        {
            "key": 16,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483665,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174853.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 16,
                        "id_intrinsic": 0,
                        "id_pose": 16
                    }
                }
            }
        },
        {
            "key": 17,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483666,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174856.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 17,
                        "id_intrinsic": 0,
                        "id_pose": 17
                    }
                }
            }
        },
        {
            "key": 18,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483667,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174857.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 18,
                        "id_intrinsic": 0,
                        "id_pose": 18
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483668,
                    "data": {
                        "width": 5920,
                        "height": 2664,
                        "focal_length": 2169.6,
                        "principal_point": [
                            2960.0,
                            1332.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []

**Comment by wangni-bupt** [comment]
{
    "sfm_data_version": "0.3",
    "root_path": "/home/private/3dobject/image3",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174806.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174808.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 1,
                        "id_intrinsic": 0,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174810.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 2,
                        "id_intrinsic": 0,
                        "id_pose": 2
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483652,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174812.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 3,
                        "id_intrinsic": 0,
                        "id_pose": 3
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174815.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 4,
                        "id_intrinsic": 0,
                        "id_pose": 4
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483654,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174817.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 5,
                        "id_intrinsic": 0,
                        "id_pose": 5
                    }
                }
            }
        },
        {
            "key": 6,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483655,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174819.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 6,
                        "id_intrinsic": 0,
                        "id_pose": 6
                    }
                }
            }
        },
        {
            "key": 7,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483656,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174822.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 7,
                        "id_intrinsic": 0,
                        "id_pose": 7
                    }
                }
            }
        },
        {
            "key": 8,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483657,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174824.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 8,
                        "id_intrinsic": 0,
                        "id_pose": 8
                    }
                }
            }
        },
        {
            "key": 9,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483658,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174827.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 9,
                        "id_intrinsic": 0,
                        "id_pose": 9
                    }
                }
            }
        },
        {
            "key": 10,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483659,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174829.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 10,
                        "id_intrinsic": 0,
                        "id_pose": 10
                    }
                }
            }
        },
        {
            "key": 11,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174832.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 11,
                        "id_intrinsic": 0,
                        "id_pose": 11
                    }
                }
            }
        },
        {
            "key": 12,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483661,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174834.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 12,
                        "id_intrinsic": 0,
                        "id_pose": 12
                    }
                }
            }
        },
        {
            "key": 13,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483662,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174836.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 13,
                        "id_intrinsic": 0,
                        "id_pose": 13
                    }
                }
            }
        },
        {
            "key": 14,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483663,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174838.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 14,
                        "id_intrinsic": 0,
                        "id_pose": 14
                    }
                }
            }
        },
        {
            "key": 15,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483664,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174851.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 15,
                        "id_intrinsic": 0,
                        "id_pose": 15
                    }
                }
            }
        },
        {
            "key": 16,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483665,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174853.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 16,
                        "id_intrinsic": 0,
                        "id_pose": 16
                    }
                }
            }
        },
        {
            "key": 17,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483666,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174856.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 17,
                        "id_intrinsic": 0,
                        "id_pose": 17
                    }
                }
            }
        },
        {
            "key": 18,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483667,
                    "data": {
                        "local_path": "",
                        "filename": "IMG_20210804_174857.jpg",
                        "width": 5920,
                        "height": 2664,
                        "id_view": 18,
                        "id_intrinsic": 0,
                        "id_pose": 18
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483668,
                    "data": {
                        "width": 5920,
                        "height": 2664,
                        "focal_length": 2169.6,
                        "principal_point": [
                            2960.0,
                            1332.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

**Comment by wangni-bupt** [comment]
Thank you for your reply. I think I found a problem. I tested the different descriptors provided by OpenMVG and found that the internal parameters didn't change much, but when I used openMVG_main_ComputeFeatures_OpenCV to extract the ORB features, I found that the intrinsic changed a lot.

My guess is that rebuilding with an ORB is poor, and  can leave the intrinsic unchanged.But I don't know if it's right

**Comment by pmoulon** [comment]
Ok, so now I better understand your question and comment.
- Intrinsics parameters are correctly grouped, as you see you have only one intrinsic camera field

Having good matches is critical in Structure From Motion and as much as important as good calibration.
We start here from a focal estimation and try to refine it with BundleAdjustment.
It is possible that using ORB features, the BundleAdjustment minimization is less stable and so parameters are changing more (compensating each other).

Note that you can FIX the intrinsic if you want in the SFM command line parameters (if you know them and they are accurate).
So you can calibrate once, and then reuse the existing calib for other projects

**Comment by wangni-bupt** [comment]
Thank you very much for your reply. I think I have understood.

**Comment by pmoulon** [comment]
Got it. Have fun with OpenMVG!
