### ISSUE TITLE
Is there a wrong typing?

### ISSUE THREAD

**Issue by qingzhengzhuma** [openMVG/openMVG#1921]
https://github.com/openMVG/openMVG/blob/8b0bc84f92e8f1a3871d997fb64b0d31c5802ab6/src/openMVG/multiview/translation_averaging_solver_softl1.cpp#L120
I think it should be std::vector<double> vec_translations(nb_poses*3, 1.0);
it works in almost all cases, it will fail when the matching graph degenerate to a list, which apparently won't happen in global sfm. Besides, it wastes memory in most cases, because nb_poses is less than relative_info_count in almost all cases.

**Comment by pmoulon** [comment]
Thank you for this report.
You are right, do you want submit a Pull Request for the fix?

Nite: we could also replace this: https://github.com/openMVG/openMVG/blob/8b0bc84f92e8f1a3871d997fb64b0d31c5802ab6/src/openMVG/multiview/translation_averaging_solver_softl1.cpp#L229 with a direct copy with a Eigen::Map

**Comment by qingzhengzhuma** [comment]
Okay, I'll try.

**Comment by pmoulon** [comment]
Thank you!

**Comment by qingzhengzhuma** [comment]
I've finished the work, but I couldn't push it to my repo since I don't have a PAT. After generating my PAT, I don't know how to make it work, because the login prompt doesn't show again.
