### ISSUE TITLE
Cannot find the reference paper or book on the EGeometricModel=ESSENTIAL_MATRIX_ANGULAR 

### ISSUE THREAD

**Issue by xiaoteng-whu** [openMVG/openMVG#1922]
Hi, 
these days, we note that the model, EGeometricModel=ESSENTIAL_MATRIX_ANGULAR.  but there is no detail on it.  for example, which page of which book does it refer to?  we have checked the error distance of epipolar geometry, but cannot find it. 

inside it, one more thing is about the openMVG:: AngularError::Error, which is computed by asin() not acos(). it also made us confused.
[https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG/multiview/solver_essential_eight_point.cpp](url)

**Comment by pmoulon** [comment]
This representation is covered in my PhD Thesis (in French) on page 79
https://pastel.archives-ouvertes.fr/tel-00996935v2/document 

We are using ASIN to constraint the output to be in the specified range

**Comment by xiaoteng-whu** [comment]
many thanks for your reply. 
one more question is about the spherical camera model mentioned on page 80 in your Ph.D. Thesis. you just use it as one representation to derive angular error, or you use this model because of dealing with panoramic images. 

in other words, the option "EGeometricModel=ESSENTIAL_MATRIX_ANGULAR" is for only the panoramic images, or also for general cases ? thanks again~

**Comment by pmoulon** [comment]
Yeah the representation of the angular error is generic, but the specialization made in ACRansac is configured for panoramic image.
You can still try it with PINHOLE images, it was working fine from what I remember, but some False Positive will still be returned.
Rejecting pair of images with few correspondences should help.

Let us know how your experimentation goes?

**Comment by xiaoteng-whu** [comment]
certainly, 
we will do some tests and then give some feedback.
please let this issue open.

**Comment by pmoulon** [comment]
Thank you!

**Comment by pmoulon** [comment]
@xiaoteng-whu any feedback on experimentation?

**Comment by xiaoteng-whu** [comment]
Hi, sorry for so late reply, we have got some experimental results, see the following table. 

  
![image](https://user-images.githubusercontent.com/60441449/132952039-0afa1cee-3ee1-48e9-8dc6-7268d88c88db.png)

where we used "Essential-E" and "Essential-EA" to filter putative matches on dataset castle-30, respectively. it can be seen that the number of matches of EA is always larger than that of E. and for some pairs, they show big differences.  

on the other hand, we also winder the use of "EA" for normal cases, because, in theory, the angular distance is not sensitive to the pixel distance. for example, the pixel threshold of "E" is default of 4.0; in comparison, the angular threshold of "EA" is default 4 degrees, which means that only those observations with very large deviations will be considered as outliers.

so, we roughly think that EA is not suitable for normal cases.  Please note that, because of the language issues, we did not read your reference paper carefully.  so we cannot guarantee that the above conclusions are correct.

**Comment by xiaoteng-whu** [comment]
@pmoulon just a reminder

**Comment by pmoulon** [comment]
Sorry for the late answer. Thank you for having ran the experiment and sharing the result.
