### ISSUE TITLE
Build error Linux

### ISSUE THREAD

**Issue by jankos1195** [openMVG/openMVG#1927]
Error during building after command: **cmake --build . --target install**

[ 64%] Built target openMVG_image
[ 64%] Built target openMVG_linearProgramming
[ 64%] Building CXX object openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_fundamental_kernel.cpp.o
In file included from /usr/local/include/eigen3/Eigen/Eigenvalues:36,
                 from /usr/local/include/eigen3/Eigen/Dense:7,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/numeric/eigen_alias_definition.hpp:17,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/multiview/conditioning.hpp:32,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/multiview/two_view_kernel.hpp:35,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/multiview/solver_fundamental_kernel.hpp:35,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/multiview/solver_fundamental_kernel.cpp:30:
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h: In instantiation of ‘void Eigen::internal::tridiagonalization_inplace(MatrixType&, DiagonalType&, SubDiagonalType&, CoeffVectorType&, bool) [with MatrixType = Eigen::Matrix<double, -1, -1, 0, 9, 9>; DiagonalType = Eigen::Matrix<double, -1, 1>; SubDiagonalType = Eigen::Matrix<double, -1, 1>; CoeffVectorType = Eigen::Matrix<double, -1, 1>]’:
/usr/local/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:458:39:   required from ‘Eigen::SelfAdjointEigenSolver<MatrixType>& Eigen::SelfAdjointEigenSolver<MatrixType_>::compute(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, 9> >, Eigen::Matrix<double, -1, 9>, 0>; MatrixType_ = Eigen::Matrix<double, -1, 9>]’
/usr/local/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:181:7:   required from ‘Eigen::SelfAdjointEigenSolver<MatrixType_>::SelfAdjointEigenSolver(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, 9> >, Eigen::Matrix<double, -1, 9>, 0>; MatrixType_ = Eigen::Matrix<double, -1, 9>]’
/home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/multiview/solver_fundamental_kernel.cpp:138:61:   required from here
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:434:55: error: no matching function for call to ‘Eigen::internal::tridiagonalization_inplace_selector<Eigen::Matrix<double, -1, -1, 0, 9, 9>, -1, false>::run(Eigen::Matrix<double, -1, -1, 0, 9, 9>&, Eigen::Matrix<double, -1, 1>&, Eigen::Matrix<double, -1, 1>&, Eigen::Matrix<double, -1, 1>&, bool&)’
   tridiagonalization_inplace_selector<MatrixType>::run(mat, diag, subdiag, hcoeffs, extractQ);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:447:12: note: candidate: ‘template<class DiagonalType, class SubDiagonalType> static void Eigen::internal::tridiagonalization_inplace_selector<MatrixType, Size, IsComplex>::run(MatrixType&, DiagonalType&, SubDiagonalType&, Eigen::internal::tridiagonalization_inplace_selector<MatrixType, Size, IsComplex>::CoeffVectorType&, bool) [with DiagonalType = DiagonalType; SubDiagonalType = SubDiagonalType; MatrixType = Eigen::Matrix<double, -1, -1, 0, 9, 9>; int Size = -1; bool IsComplex = false’
       void run(MatrixType& mat, DiagonalType& diag, SubDiagonalType& subdiag, CoeffVectorType& hCoeffs, bool extractQ)
            ^~~
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:447:12: note:   template argument deduction/substitution failed:
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:434:55: note:   cannot convert ‘hcoeffs’ (type ‘Eigen::Matrix<double, -1, 1>’) to type ‘Eigen::internal::tridiagonalization_inplace_selector<Eigen::Matrix<double, -1, -1, 0, 9, 9>, -1, false>::CoeffVectorType&’ {aka ‘Eigen::Matrix<double, -1, 1, 0, 8, 1>&’}
   tridiagonalization_inplace_selector<MatrixType>::run(mat, diag, subdiag, hcoeffs, extractQ);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [openMVG/multiview/CMakeFiles/openMVG_multiview.dir/build.make:206: openMVG/multiview/CMakeFiles/openMVG_multiview.dir/solver_fundamental_kernel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2693: openMVG/multiview/CMakeFiles/openMVG_multiview.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by jankos1195** [comment]
For branch develop_2.0:

[ 59%] Building CXX object openMVG/exif/CMakeFiles/openMVG_exif.dir/exif_IO_EasyExif.cpp.o
[ 59%] Linking CXX static library ../../Linux-armv7l-RELEASE/libopenMVG_exif.a
[ 59%] Built target openMVG_exif
Scanning dependencies of target openMVG_features
[ 59%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/akaze/AKAZE.cpp.o
[ 59%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/akaze/image_describer_akaze.cpp.o
In file included from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/matching/metric.hpp:12,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/features/binary_regions.hpp:17,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/features/regions_factory.hpp:12,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/features/akaze/image_describer_akaze.hpp:13,
                 from /home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/features/akaze/image_describer_akaze.cpp:7:
/home/pi/Project_Tools/OpenMVG/openMVG/src/openMVG/matching/metric_simd.hpp:20:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [openMVG/features/CMakeFiles/openMVG_features.dir/build.make:76: openMVG/features/CMakeFiles/openMVG_features.dir/akaze/image_describer_akaze.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2444: openMVG/features/CMakeFiles/openMVG_features.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by johnwlambert** [comment]
I'm seeing the same error on mac when I pull the latest:

```
[ 51%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSolve.cpp.o
In file included from /Users/johnlam/Downloads/openMVG/src/openMVG/multiview/solver_fundamental_kernel.cpp:30:
In file included from /Users/johnlam/Downloads/openMVG/src/openMVG/multiview/solver_fundamental_kernel.hpp:35:
In file included from /Users/johnlam/Downloads/openMVG/src/openMVG/multiview/two_view_kernel.hpp:35:
In file included from /Users/johnlam/Downloads/openMVG/src/openMVG/multiview/conditioning.hpp:32:
In file included from /Users/johnlam/Downloads/openMVG/src/openMVG/numeric/eigen_alias_definition.hpp:17:
In file included from /usr/local/include/eigen3/Eigen/Dense:7:
In file included from /usr/local/include/eigen3/Eigen/Eigenvalues:36:
/usr/local/include/eigen3/Eigen/src/Eigenvalues/./Tridiagonalization.h:434:3: error: no matching function for call to 'run'
  tridiagonalization_inplace_selector<MatrixType>::run(mat, diag, subdiag, hcoeffs, extractQ);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:458:13: note: in instantiation of function template specialization 'Eigen::internal::tridiagonalization_inplace<Eigen::Matrix<double, -1, -1, 0, 9, 9>, Eigen::Matrix<double, -1, 1, 0>, Eigen::Matrix<double, -1, 1, 0>, Eigen::Matrix<double, -1, 1, 0>>' requested here
  internal::tridiagonalization_inplace(mat, diag, m_subdiag, m_hcoeffs, computeEigenvectors);
            ^
/usr/local/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:181:7: note: in instantiation of function template specialization 'Eigen::SelfAdjointEigenSolver<Eigen::Matrix<double, -1, 9, 0>>::compute<Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, 9, 0>>, Eigen::Matrix<double, -1, 9, 0>, 0>>' requested here
      compute(matrix.derived(), options);
      ^
/Users/johnlam/Downloads/openMVG/src/openMVG/multiview/solver_fundamental_kernel.cpp:137:42: note: in instantiation of function template specialization 'Eigen::SelfAdjointEigenSolver<Eigen::Matrix<double, -1, 9, 0>>::SelfAdjointEigenSolver<Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, 9, 0>>, Eigen::Matrix<double, -1, 9, 0>, 0>>' requested here
    Eigen::SelfAdjointEigenSolver<MatX9> solver
                                         ^
/usr/local/include/eigen3/Eigen/src/Eigenvalues/./Tridiagonalization.h:447:12: note: candidate function template not viable: no known conversion from 'Eigen::Matrix<double, -1, 1, 0>' to 'Eigen::internal::tridiagonalization_inplace_selector<Eigen::Matrix<double, -1, -1, 0, 9, 9>, -1, false>::CoeffVectorType &' (aka 'Matrix<double, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> &') for 4th argument
      void run(MatrixType& mat, DiagonalType& diag, SubDiagonalType& subdiag, CoeffVectorType& hCoeffs, bool extractQ)
           ^
```

**Comment by pmoulon** [comment]
Could you tell me which version of Eige are you using?
It seems a new error... that never appeared in the CI

**Comment by xiaobiaozhu** [comment]
The same error, with Ubuntu 20.04. I am using Eigen 3.3.7 .

**Comment by johnwlambert** [comment]
Hi @pmoulon, thanks for taking a look. I can reproduce the error in Github Actions CI for macOS:

https://github.com/johnwlambert/openMVG/runs/3499790994?check_suite_focus=true

Using the workflow here: https://github.com/johnwlambert/openMVG/blob/develop/.github/workflows/build-latest.yml
and the script here: https://github.com/johnwlambert/openMVG/blob/develop/build-macos.sh

Eigen version in that CI is 3.4.

**Comment by pmoulon** [comment]
@johnwlambert @xiaobiaozhu The Eigen error must now be fixed in the Develop branch.

@jankos1195 For the "#include <immintrin.h>" error => What is your system?
It seems We can disable the metric_simd for some system or at least make it more robust for some system where this file would not be present

**Comment by johnwlambert** [comment]
Thanks @pmoulon, I can build it now successfully on my mac.

**Comment by qianqiuzzz** [comment]
@jankos1195 have you solve your problem?how to solve it?

**Comment by jankkosinski** [comment]
@qianqiuzzz sorry mate, it was quite a long time ago and I don't remember. I don't have that project anymore to check 😞

**Comment by adskjldjlska** [comment]
i meet the question in windows . using the latest version
