### ISSUE TITLE
Different results in Windows and Ubuntu

### ISSUE THREAD

**Issue by dngkatn** [openMVG/openMVG#1928]
Thank you for sharing a good project. 
I am reconstructing the Spherical image that I took with insta OneX2. 
The reconstruction result using the window library is similar to the result of the image you entered, and the mesh is also very well dressed. 
But the result of Ubuntu is different. 
When I run the "DensifyPointCloud $dataset_out/reconstruction/cubic/scene.mvs".
I save about 88,000 points information in Windows, but about 1/10 points in Ubuntu. 
As a result, only one portion of the image entered is output as a result of reconstruction. 
What am I wrong? I want to know why the results of Windows and Ubuntu are different.
![ubuntu](https://user-images.githubusercontent.com/31524341/131053655-e52c7b83-bd91-4245-9d9a-9749daed45ad.PNG)
[ubuntu]
![windows](https://user-images.githubusercontent.com/31524341/131054378-1731373f-90c9-44dd-8f1f-0e15744ae32a.jpg)
[windows]

Thank you.

**Comment by pmoulon** [comment]
@dngkatn Any feedback?
Please compare first the SFM output (OpenMVG output)

**Comment by dngkatn** [comment]
@rperrot Thank you for answering me! @pmoulon I stopped this project for a while. I will check the results of OpenMGV and share them as soon as possible. Thanks.
