### ISSUE TITLE
Remove poses points from SfM output

### ISSUE THREAD

**Issue by MohammadMDSA** [openMVG/openMVG#1929]
Is it possible to remove green dots showing camera positions from output ply file?

**Comment by pmoulon** [comment]
If you have your sfm_data.bin handy it is easy. You can use ConvertSfMData_Format -i sfm_data.bin -o point_cloud.ply -S

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen

**Comment by BW-Zhang05** [comment]
> If you have your sfm_data.bin handy it is easy. You can use ConvertSfMData_Format -i sfm_data.bin -o point_cloud.ply -S

Hello, ConvertSfMData_Format  is not useable in openMVG v2.0. So what should i do in new version?
