### ISSUE TITLE
[Sample] Robust estimation of the relative pose between spherical images

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#193]
Add an implementation of the Acontrario essential matrix estimation between spherical images.

Based on [1]
It demonstrates:
- usage of angular errors within the AContrario-RANSAC (do not require a priori precision threshold),
- essential matrix estimation from spherical bearing vectors,
- triangulation from spherical image,
- cheirality check from spherical bearing vectors and 3D points.

[1]"Robust and accurate calibration of camera networks". PhD.
Author: Pierre MOULON
Chapter 4.4.2 Application to estimation of relative orientation between two spherical camera.

**Comment by haopo2005** [comment]
Hi,
I have some questions about your above essential matrix.
1. Dose the translation extracted  from essential matrix between two spherical images is real distance or unit distance or random distance?
2.how  can the essential matrix be computed without any camera intrinics information?

**Comment by pmoulon** [comment]
Hi @haopo2005,
1. The translation is computed at a scale of the reality,
2. I suppose that the focal is given by the unit sphere (so unit focal length)

**Comment by haopo2005** [comment]
Is the scale of the reality fixed for each image pair?
e.g. these images are taken at different locations.

**Comment by pmoulon** [comment]
The found translation must be unit norm, so the scale to the reality is different for each image pair.

**Comment by haopo2005** [comment]
Thank you.
Do I need to take all images on the same plane?
What if some images were taken from the stairs?

**Comment by pmoulon** [comment]
The motion can be arbitrary.
So you can take panorama at different stair levels.

**Comment by haopo2005** [comment]
Hi,
I'd like to know which direction(right hand or left hand) of coordinate system should be followed when computing essential matrix?
one:
x(left),y(up),z(insdie)
two:
x(forward),z(up),y(right)

you can see these two coordinate below:
![qq 20170112182936](https://cloud.githubusercontent.com/assets/9463657/21886048/1b9b96d8-d8f5-11e6-9a71-8302ebc480ba.png)
![qq 20170112182926](https://cloud.githubusercontent.com/assets/9463657/21886049/1b9dc156-d8f5-11e6-87cf-b1cf0ed2624a.png)


In the end, how many matched feature points is OK with the algorithm？I have above 8 points, but not quite much. I'm worried about the robustness
