### ISSUE TITLE
Trying to compile for mac osx, but im very new so i need help

### ISSUE THREAD

**Issue by sansink14** [openMVG/openMVG#1933]
Heya, 
I've been trying to compile openMVG, I've downloaded cmake but it returned errors that I don't really understand. I think I have all the parts that I need, but if anybody could point me in the right direction that would be great thanks.

I moved some files to get this so cmake was happy, 
[CMakeLists.txt](https://github.com/openMVG/openMVG/files/7149396/CMakeLists.txt)

and it gave me this error:

CMake Error at CMakeLists.txt:51 (file):
  file STRINGS file "/Users/san/openMVG/src/openMVG/openMVG/version.hpp"
  cannot be read.

CMake Error at CMakeLists.txt:56 (message):
  Failed to retrieve the OpenMVG version from the source code.  Missing
  OPENMVG_VERSION_MAJOR.

It also spit out these files that could tell people anything,
[CMakeError.log](https://github.com/openMVG/openMVG/files/7149399/CMakeError.log)
[CMakeOutput.log](https://github.com/openMVG/openMVG/files/7149400/CMakeOutput.log)

thanks for reading,  hope that was all the information that you needed to solve this.

**Comment by pmoulon** [comment]
Did you git clone openMVG or download it from github?

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
