### ISSUE TITLE
Is there a parallel version of the global SFM used by open MVG？

### ISSUE THREAD

**Issue by qwh9896** [openMVG/openMVG#1935]
Through the experimental part of references（Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion）, we find that there is a parallel version of global SFM. Can this solve the problem of low efficiency to a certain extent?
Where can I find the relevant information？

**Comment by pmoulon** [comment]
Hello, did you check that OpenMP is activated or did you check if multiple cores were used on your machine?

How many images are you using as input?

**Comment by qwh9896** [comment]
> Hello, did you check that OpenMP is activated or did you check if multiple cores were used on your machine?
> 
> How many images are you using as input?

Thank you for your reply. After checking, our OpenMP has indeed been activated. We need to process about 39000 images. The problem we encounter now is that we have handled it for more than two months and the program has not been run. Later, in the process of reviewing the paper, we found the experimental part of the gsfm method you used, In the experimental results, the ourp (labeled: oursp means our parallel version) experimental results appear, so let's ask how to implement the parallel version of the method.

**Comment by pmoulon** [comment]
Got it, yes the code as it is is the parallel version.
Since your dataset is huge 40k images, you must have a very dense graph, such large graph could be perhaps handle better using graph simplification, or hierarchical method.
For your information: we have some idea in the pipe that we plan to release for larger dataset, but we still need more testing.

**Comment by qwh9896** [comment]
> 明白了，是的，代码是并行版本。
> 由于您的数据集是巨大的 40k 图像，您必须有一个非常密集的图，这样的大图可能可以使用图简化或分层方法更好地处理。
> 供您参考：我们计划为更大的数据集发布一些想法，但我们仍然需要更多的测试。
