### ISSUE TITLE
Super large scale image processing

### ISSUE THREAD

**Issue by qwh9896** [openMVG/openMVG#1937]
For very large-scale image sfm process problem，Hierarchical SfM or Multi-Stage SfM ，which treatment method is more recommended？

**Comment by pmoulon** [comment]
Does your dataset have GPS priors?
- If you want to have a simpler graph you can try to reduce the number of features per images for matching (and eventually for SfM) by using the preemptive option in the branch develop2.0

We are more than willing to help you successfully process such a large dataset, the more we understand the data you have the better guidance we can provide

**Comment by qwh9896** [comment]
> 你的数据集有 GPS 先验吗？
> 
> * 如果你想要一个更简单的图形，你可以尝试通过使用分支 develop2.0 中的抢占选项来减少每个图像的匹配（并最终用于 SfM）的特征数量
> 
> 我们非常愿意帮助您成功处理如此大的数据集，我们对您的数据了解得越多，我们就能提供更好的指导

First of all, thank you for your reply. Yes, our data have GPS priors. However, we hope to ensure the accuracy and texture of the final product as much as possible during the experiment, so we hope to keep the matching points as much as possible. Therefore, I feel that the above scheme you provide seems inappropriate. In addition, as for our data, our test data includes 40000 pieces and 17000 pieces of 6000x4000 UAV data. The test results show that the former only completes the optimization of translation, the program crashes and does not complete the follow-up processing;the latter runs for about a week, but the accuracy of the final result does not seem to be satisfactory.By the way,we use global SFM for processing.

**Comment by pmoulon** [comment]
So if translations is optimized, it means you can already take a look at the camera position that is found:
- Can you take a look at the file cameraPath_translation_averaging.ply
- It seems that then, we crash (not sure if it is at the track triangulation or BA though => Do you have a file `initial_structure.ply`)

I will try to post some details about processing DRONE dataset and share a DRONE dataset this weekend.
Let's continue to work iteratively to see how we could process your dataset either by blocks and perhaps implement a merging routine to OpenMVG...

**Comment by whuaegeanse** [comment]
@pmoulon @qwh9896 
When dealing with large-scale data, perhaps we should pay more attention to HSfM.

Here are some papers.

1. [Robust hierarchical structure from motion for large-scale unstructured image sets](https://www.sciencedirect.com/science/article/abs/pii/S0924271621002574)
2. [Graph-based parallel large scale structure from motion](https://www.sciencedirect.com/science/article/abs/pii/S003132032030340X)
3. [Block Partitioning and Merging for Processing Large-Scale Structure From Motion Problems in Distributed Manner](https://www.researchgate.net/publication/333886724_Block_Partitioning_and_Merging_for_Processing_Large-Scale_Structure_From_Motion_Problems_in_Distributed_Manner)

**Comment by qwh9896** [comment]
> A long time ago, @sebastienchappuis wrote some kind of HyperSfm. You could check it's PR here : #1038

Thank you very much for your reply. I think we will try to follow up this mode

**Comment by qwh9896** [comment]
> @pmoulon @qwh9896 When dealing with large-scale data, perhaps we should pay more attention to HSfM.
> 
> Here are some papers.
> 
> 1. [Robust hierarchical structure from motion for large-scale unstructured image sets](https://www.sciencedirect.com/science/article/abs/pii/S0924271621002574)
> 2. [Graph-based parallel large scale structure from motion](https://www.sciencedirect.com/science/article/abs/pii/S003132032030340X)
> 3. [Block Partitioning and Merging for Processing Large-Scale Structure From Motion Problems in Distributed Manner](https://www.researchgate.net/publication/333886724_Block_Partitioning_and_Merging_for_Processing_Large-Scale_Structure_From_Motion_Problems_in_Distributed_Manner)
> 
> I think parper 1 provides a systematic way to improve the stability of HSfM. Maybe we should work together to make a more robust and efficient HSfM based on openMVG. Of course, parper 2-3 also provide good ideas, which are worth learning from.

Thank you very much. I will read these documents carefully

**Comment by pmoulon** [comment]
Closing due to lack of feedback, feel free to re-open as needed
