### ISSUE TITLE
Questions about spherical camera coordinate system

### ISSUE THREAD

**Issue by johnwlambert** [openMVG/openMVG#1938]
Hi @pmoulon, thanks for the excellent library.

What is the camera coordinate system for a reconstruction from equirectangular projection images? i.e. how do x, y, z map to the panorama pixels? I may have missed this in the documentation.

I noticed that other libraries like OpenSfM seem to return multiple connected components after incremental SfM. Wanted to confirm that OpenMVG only returns a single connected component for incremental SfM.

**Comment by pmoulon** [comment]
Hello @johnwlambert ,
If I remember well it is Y up, Z Front, X right.
If you want see if by yourself you can play with the https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/multiview_robust_essential_spherical/robust_essential_spherical.cpp and do `Rotation * Vec3(1,0,0)` ; `Rotation * Vec3(0,1,0)`; `Rotation * Vec3(0,0,1)` perhaps add a scale factor and then reproject the 3d point in the image domain so you would see where they project

OpenMVG will always return the largest connected component after incremental SfM.
If you want to process the remaining connected component you can do so by removing the views that has been found and recall Incremental SfM

**Comment by pmoulon** [comment]
Closing the issue, feel free to reopen if needed or ask feedback if needed

**Comment by johnwlambert** [comment]
Hi @pmoulon, thanks for your reply.

I do think that the spherical camera coordinate system is an essential piece of documentation that would be really helpful to add for any users :- ) If you or the other maintainers have time, I think you all are probably in a better position to confirm the axes with the reprojection / scale factor experiments you mentioned since you are more familiar with the intermediate implementation conventions used in the library : - )
