### ISSUE TITLE
[Matching] Cascade Hashing

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#194]
Implementation of Cascade Hashing for fast matching of SIFT descriptor [1].
Added in the nonFree openMVG module since the original source code is free for research. For commercial usage please contact [1] author's.

  - [x] add basic implementation
    - Updates from openMVG contributors:
      -  use less memory
        - do not copy raw descriptors,
        - allocate temp buffer to only the required memory.
      - allow parallel matching,
      - make code multi platform.

Observation after usage:
  - The code produce similar results to ANN with a distance ratio of 0.6.
  - For higher distance ratio (i.e. 0.8) there is more false positive but also more true positive. False positives are often filtered by robust essential/fundamental matrix filtering.
  - On some scenes Cascade Hashing is slower than ANN (since all keypoints fall nearly in the same bucket).
  - openMVG cascade hashing code can be customized to be used on other descriptor type.

[1] Fast and Accurate Image Matching with Cascade Hashing for 3D Reconstruction.
Authors: Jian Cheng, Cong Leng, Jiaxiang Wu, Hainan Cui, Hanqing Lu.
Conference: CVPR 2014.

**Comment by naveenjafer** [comment]
@pmoulon Is there any reference to the paper from which fast cascade hashing has been implemented? I tried searching but couldnt get anything much on it.

**Comment by pmoulon** [comment]
@naveenjafer In OpenMVG any paper implementation contains the bibliography reference paper.
See here https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/matcher_cascade_hashing.hpp#L24

https://www.researchgate.net/publication/282266942_Cheng_Fast_and_Accurate_2014_CVPR_paper
