### ISSUE TITLE
Regarding camera position

### ISSUE THREAD

**Issue by dorian567** [openMVG/openMVG#1941]
I believe that in this estimation, you are producing the relative distance between the camera and the object. What specific point on the object are you using to get the position of the camera?

**Comment by pmoulon** [comment]
Hello @dorian567 I think we have some missing context here.
If you want to know more about what OpenMVG is using to perform SfM you can read more in our [tutorials](https://docs.google.com/presentation/d/1eEd12oUeKRckuymHHfauclpc62QGpGRI67B02wcKA0I/edit).

Basically, photogrammetry is using point correspondences between images to figure out the relative motion of cameras and guess the structure of the scene.

**Comment by pmoulon** [comment]
Feel free to re-open and ask more details
