### ISSUE TITLE
Possible path error and absent executable in the dataset demo

### ISSUE THREAD

**Issue by catmasteryip** [openMVG/openMVG#1948]
I have followed the [guideline](https://github.com/openMVG/openMVG/blob/master/BUILD.md) to compile openMVG 
also followed [#1727](https://github.com/openMVG/openMVG/issues/1727#issuecomment-805833619) to skip the `'ceres/types.h' file not found` error
then followed this to run the demo [ImageDataset_SceauxCastle](https://github.com/openMVG/openMVG/wiki/OpenMVG-on-your-image-dataset) on sample.
Then I encounter the following error:
`No such file or directory: '.../openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/openMVG_main_SfMInit_ImageListing': '.../openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/openMVG_main_SfMInit_ImageListing`
I checked and see the executables situate one level higher at .../openMVG_Build/Darwin-x86_64-RELEASE instead.
The demo then can be successfully run, until another error about some absent executable popped up:
`No such file or directory: '.../openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeStructureFromKnownPoses': '.../openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeStructureFromKnownPoses'`
What would be the reason and fix?

**Comment by pmoulon** [comment]
Issue should be fixed in develop
