### ISSUE TITLE
ComputeMatches PairWiseMatches Error

### ISSUE THREAD

**Issue by wakil1** [openMVG/openMVG#1955]
After running computeMatches /openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeMatches -i /matc/sfm_data.json -o /matc/ -f 1, 

I get the following error 

<img width="834" alt="Screen Shot 2021-10-29 at 11 39 20 AM" src="https://user-images.githubusercontent.com/59300535/139463502-68b3bc2a-df12-4b4f-b742-0ae85e70b732.png">

Any help will be apperciated, thanks

**Comment by wakil1** [comment]
thanks for reccomendation that python script is much better, however in the last portion I get an error saying 


ERROR: [sequential_SfM.cpp:110] Unable to choose an initial pair, since there is no defined intrinsic data.
INFO: [sequential_SfM.cpp:173] Cannot find a valid initial pair - stop reconstruction.
7. Colorize Structure
ERROR: [main_ComputeSfM_DataColor.cpp:69] The input SfM_Data file "imageValues/reconstruction_sequential/sfm_data.bin" cannot be read.


I am assuming this has to do with focal length based on other issues, but my images have their given focal length installed already. I tried manually changing the focal length inside the "openMVG_main_SfMInit_ImageListing" in the script to pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-f", "1000"] ) but I got a very bad result.

**Comment by pmoulon** [comment]
@wakil1 How did you computed the 1000 value -> https://github.com/openMVG/openMVG/issues/669#issuecomment-258584371

**Comment by wakil1** [comment]
my max height was 946 and multiplied it by 1.2(1183), then i played with the values and for that specific example it was 1000

**Comment by pmoulon** [comment]
Do you know the type of camera you are using (does the lens is more or less like a classic one or more like a fish eye one)?

Seems like your image graph is highly connected (do you have a very narrow baseline between your camera)?

**Comment by wakil1** [comment]
I do not have the info for the type of camera I am using, however when I run the code in regard3d it is able to see the focal length embedded inside the image info.

**Comment by pmoulon** [comment]
More than happy to help, do you want to share what exiftool says for your image metadata?

**Comment by wakil1** [comment]
sorry for the late reply, thank you for helping out. Here is what the image metadata gives me: 
<img width="622" alt="Screen Shot 2021-11-04 at 1 13 57 PM" src="https://user-images.githubusercontent.com/59300535/140387084-350f814f-682d-497f-bdf6-b614318d569e.png">

**Comment by pmoulon** [comment]
I see you have no information about the camera model, maker?

**Comment by pmoulon** [comment]
Closing due to lack of feedback, feel free to re-open as needed
