### ISSUE TITLE
User Camera K ,distcoeff, Camera poses

### ISSUE THREAD

**Issue by issamdakir** [openMVG/openMVG#1957]
Hi guys,
Thank you so much for this extra photogrammetry library.

I m using opencv to get Camera K matrix (3x3) and D : (distortion coefficient array of 5 values).
There is an optional -k argument in openMVG_main_SfMInit_ImageListing step, but i don't know how to add the D parameter?

For other purposes i use aruco markers and opencv to get camera poses.
If i have camera poses as (4x4) matrices can i use this data in openMVG reconstruction pipeline.

Thank you guys
Merci beaucoup Mr. Pierre Moulon

**Comment by pmoulon** [comment]
Hi @issamdakir,
The best to import your camera model value is to use the binary as it is and then edit the sfm_data.json from python or via text edit.
So you can use the -c 3 and then update the focal length and principal point to match and add your distortion parameters factors in the sfm_data.json

**Comment by issamdakir** [comment]
Merci cher Docteur Moulon


Le mar. 2 nov. 2021 à 20:17, Pierre Moulon ***@***.***> a
écrit :
