### ISSUE TITLE
Convert to MVE

### ISSUE THREAD

**Issue by wakil1** [openMVG/openMVG#1958]
Im trying to convert my dataset to MVE however I get the error: 

/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_openMVG2MVE2  -i /openMVG_Build/software/SfM/valuesToUse/reconstruction_sequential/sfm_data.bin -o /openMVG_Build/software/SfM/valuesToUse/reconstruction_sequential/OutRecon

INFO: [main_openMVG2MVE2.cpp:290] Note:  this program writes output in MVE file format.
INFO: [main_openMVG2MVE2.cpp:69] [Creating directory: /openMVG_Build/software/SfM/valuesToUse/reconstruction_sequential/OutRecon/MVE]
INFO: [main_openMVG2MVE2.cpp:90] Writing bundle (556 cameras, 8 features): to synth_0.out...

INFO: [main_openMVG2MVE2.cpp:149] Exporting views...
INFO: [main_openMVG2MVE2.cpp:155] [Creating directory:  /openMVG_Build/software/SfM/valuesToUse/reconstruction_sequential/OutRecon/MVE/views]
ERROR: [image_io.cpp:110] Couldn't open home/image/0418.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0418.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0541.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0541.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0415.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0415.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0419.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0419.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0420.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0420.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0542.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0542.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0540.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0540.jpg
ERROR: [image_io.cpp:110] Couldn't open home/image/0417.jpg fopen returned 0
Unable to read the input image as a RGB image:
home/image/0417.jpg

Any suggestions will be helpful thankyou!

**Comment by pmoulon** [comment]
Hello @wakil1, seems like a `/` is missing before `home`

Reading the code here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/export/main_openMVG2MVE2.cpp#L179 I would invite you to take a look and see if the path is good in your input sfm_data file ... from my understanding the root_path here would not have a starting `/`

**Comment by pmoulon** [comment]
Perhaps you are not launching the binary from the same input folder as you ran SfM, and so image cannot be found
