### ISSUE TITLE
openMVG_main_IncrementalSfM: command not found

### ISSUE THREAD

**Issue by elliestath** [openMVG/openMVG#1959]
Hello,

I am running openMVG on a docker image using your dockerfile (last pull today).
Everything works as expected till I run the command openMVG_main_IncrementalSfM where I get the error "command not found".
I indeed went to the bin folder openMVG_Build/openMVG_Build/install/bin/ and saw that this bin file as well as the one for Global SfM is missing. 
Any hint on this?

Thanks

**Comment by pmoulon** [comment]
Hello @elliestath, OpenMVG 2.0 is using now a single openMVG_main_SfM binary to run all the sfm pipeline (incremental, incrementalV2 and Global). See https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_SfM.cpp

Using is as before (see the tutorial or incremental and global python samples exported in build/software/SfM)

**Comment by elliestath** [comment]
yes, hadn't noticed the change, thank you very much!

**Comment by Tomxx7** [comment]
Hi Guys! I am facing the same problem and I am seeing the solution that you provided. Can you help me with how I can encapsulate this code with my image dataset and run it for 3D reconstruction?

**Comment by pmoulon** [comment]
@Tomxx7 How can we best help you, the python script provided in the repo are running the command line with the right arguments. So can you elaborate?
