### ISSUE TITLE
2.0: Fails to use external cereal

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1963]
The code [checks](https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L241) for ```cereal``` target. Such target isn't found but ```cereal_FOUND``` is set. ```cereal_FOUND``` is the variable that it should check.

The code also [unconditionally checks](https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L103) that the ```cereal``` submodule is present even when external ```cereal``` can be used.

**Comment by pmoulon** [comment]
Thank you for reporting, we can definitely do better.
Do you want to help and make a PR?
