### ISSUE TITLE
OpenMVG main ColHarmonize Reference paper

### ISSUE THREAD

**Issue by WF946773243** [openMVG/openMVG#1965]
Recently, I was doing the Color adjustment of the image based on feature points. I referred to the reference paper of Global multiple-view Color Consistency of OpenMVG for Color adjustment. I download the free two pages. Do you have a complete reference? Or can you recommend me some other papers on global color adjustment based on feature points? Thank you.

**Comment by pmoulon** [comment]
We have only published a short paper for this multiple-view consistency paper.
I would advise you to take a look to `3.3 Global Optimization of Color Distribution` in [Color correction for image-based modeling in the large](http://tianweishen.com/files/pub/accv2016color.pdf) where they use a similar formulation as us with a robust norm and tested on larger scale dataset
