### ISSUE TITLE
Problems with random results

### ISSUE THREAD

**Issue by Livan89** [openMVG/openMVG#1966]
Hi.

I understand that for the correct calibration of cameras in the 3D generation, the use of RANSAC methods is necessary. But this causes the problem that when processing a set of images with the same parameters in the SFM process, the results of generating 3D points in space are different. It can even happen that for the same set of images in an iteration the model is generated correctly and in another case it is failed. Is there a solution to eliminate the randomness and that if I repeat the process over and over again with the same values ​​and data the results are the same?

Thank you.

**Comment by pmoulon** [comment]
One solution is to do not use OpenMP or force OpenMP to be on one thread. This way you will have reproducibility on the random number generator value in the RANSAC loops.

See and use 1 for the thread count
http://portal.nacad.ufrj.br/online/intel/mkl/common/mkl_userguide/GUID-B13E207A-FC51-4973-9676-B40545599272.htm

See [here](https://groups.google.com/g/ceres-solver/c/F_bbG_5afnY?pli=1) another discussion on Ceres deterministic behavior

**Comment by Livan89** [comment]
@pmoulon  Thank you very much, I found your answer very helpful. I will try the suggestion you give me. 

I close the issue. 

Thank you.
