### ISSUE TITLE
Ground Sampling Distance calculation using openMVG output

### ISSUE THREAD

**Issue by eokeeffe** [openMVG/openMVG#1969]
I'm trying to find a way of calculating the GSD in meters of a scene using the outputs from openMVG sfm_data.json 
From most of the content I've been able to find online points to using the sensor dimensions in mm.

I can extract height (meters), Focal length (this is in pixels yes?), image width (pixels) from the sfm_data.json (converted from sfm_data.bin) .

Is there anyway of finding the GSD without prior knowledge of the sensor dimensions?

Please and thank you

**Comment by pmoulon** [comment]
To compute the GSD you will need the distance from the camera to the object.
So I would say that if you have a calibrated pattern in your scene and use it to rescale the scene, or use control points you would be able to evaluate a GSD value.

I could be wrong.

@rjanvier will perhaps have a better answer here?

**Comment by nguyengiang41** [comment]
you can evaluate an"average gsd". You could compute average distance from
camera position and all 3d points (3d landmarks in sfmdata). Then, you
compute distance between 2 ground point which corresponds with 2
consecutive pixel on image ( principal points and its neighbor). This is
the GSD value.

**Comment by pmoulon** [comment]
@nguyengiang41 you would assume the scene is metric (either by using gcp, gps rescaling or other rescaling) right?

**Comment by nguyengiang41** [comment]
yes, the scene must be metric by the way.

**Comment by eokeeffe** [comment]
Thanks for the method to use, I'm going to code this up and check it against a known SFM scene with known GSD .
If the results pan out I'll share the code :)

**Comment by nguyengiang41** [comment]
@eokeeffe more precise in my respond above :  you could take just 3D points in camera field of view (and occlusion) to compute the "average distance" from camera to scene. Then, you compute coordinates of 2 ground points which corresponds with 2 consecutive pixel on image ( principal points and its neighbor) by forward projection method (from 2D pixel on image to 3D point on ground), with the "depth" value = "average distance". Distance between these 2 ground points is GSD.

**Comment by eokeeffe** [comment]
@nguyengiang41  The second method using the forward projection of the image boundaries worked a treat!

The first method (average of camera heights and ground point heights) I was generating a GSD of 0.01364 m/px where the real value was 0.03646 m/px .
 
The second method using the forward projection gave 
vertical GSD :       0.03637 m/px
horizontal GSD :   0.02797 m/px
so taking the max GSD gave 0.03637 m/px which is in line with the known GSD 0.03646 m/px

:D

**Comment by shubham9436** [comment]
@eokeeffe could you share the code for the second method using the forward projection?
