### ISSUE TITLE
Invalid regions files for the view during "openMVG_main_ComputeMatches"

### ISSUE THREAD

**Issue by lzn1273180880** [openMVG/openMVG#1973]
Hello! Sorry for disturbance.
I received an error when I'm calling `.\openMVG_main_ComputeMatches.exe -i F:\openMSV\test\sfm_data.json -o F:\openMSV\test` like this:
![image](https://user-images.githubusercontent.com/94612909/144054035-12f21b6e-7a48-402a-8570-0408eb7dbde7.png)
I noticed that there were some solutions like [https://github.com/openMVG/openMVG/issues/1404](url) and [https://github.com/openMVG/openMVG/issues/1955](url) but I've tried, and there's no difference.
I indeed get `.feat` and `.desc`  and `image_describer.jso` in my output folder, which is in the same folder as the `sfm_data.json` as mentioned above `F:\openMSV\test`.
Was there something wrong when I'm compiling openMVG?
How can I do to slove?
Thx.

**Comment by lzn1273180880** [comment]
Please help me out if you are free

**Comment by lzn1273180880** [comment]
I retried it today, errors occurred as well but there is something difference.
![image](https://user-images.githubusercontent.com/94612909/144207855-ec399b1b-150c-41e9-af8e-520d6658c1aa.png)
This time I just received errors about `100_7100.JPG` and `100_7101.JPG`, I wonder if my path is set correctly.
![image](https://user-images.githubusercontent.com/94612909/144208387-23469619-267a-4e02-9bfb-564d93a868f1.png)
![image](https://user-images.githubusercontent.com/94612909/144208414-d33e3b43-55df-4b2a-aec3-1f206d094208.png)
But the folder I set is indeed includes `.feat` `.desc` `image_describer.json` and `sfm_data.json` that pipline expects.

**Comment by pmoulon** [comment]
The API in openMVG 2.0 changes slightly. You have now to specify a file for the matches output. Try to use  ’-o F:\openMSV\test\matches.putatives.bin`

See here https://github.com/openMVG/openMVG/blob/8f61623e80c1461a7a0a202f3203101e71f21430/src/software/SfM/SfM_SequentialPipeline.py.in#L62
If you don't specify pairs by default exhaustive will be done.

**Comment by lzn1273180880** [comment]
Thank you so much for reply!
And now the problem solved, I'm sorry for my neglect of the source code `SfM_SequentialPipeline.py`.
Thx again.

**Comment by pmoulon** [comment]
You are welcome. Feel free to leverage the python pipeline that allow to run openMVG toolchain on an image folder with ease.

**Comment by ZJArry** [comment]
zjarry@zjarry-virtual-machine:~/桌面/textjianzhu$ openMVG_main_ComputeMatches -i output/matches/sfm_data.json -o output/matches
INFO: [main_ComputeMatches.cpp:114]  You called : 
openMVG_main_ComputeMatches
--input_file output/matches/sfm_data.json
--output_file output/matches
--pair_list 
Optional parameters:
--force 0
--ratio 0.8
--nearest_matching_method AUTO
--cache_size unlimited
--preemptive_feature_used/count 0 / 200
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: image/001.JPG
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: image/002.JPG
ERROR: [main_ComputeMatches.cpp:195] Cannot load view regions from: output.

**the same problem, do you know how to solve it?**

**Comment by ZJArry** [comment]
I solved it. https://github.com/openMVG/openMVG/blob/8f61623e80c1461a7a0a202f3203101e71f21430/src/software/SfM/SfM_SequentialPipeline.py.in#L62 There are the steps in the SequentialPipeline.py

**Comment by koutarou-jp** [comment]
D:\openMVG\openMVG_cmake_output\Windows-AMD64-\Release>openMVG_main_ComputeMatches -i matches/sfm_data.json -o matches

I executed the command like this, but the following error occurred.

ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: images\_20211224-144248.jpg
ERROR: [sfm_regions_provider.hpp:124] Invalid regions files for the view: images\_20211224-144250.jpg
ERROR: [main_ComputeMatches.cpp:195] Cannot load view regions from: .

What command changes do I need to make?

[openMVG / src / software / SfM / SfM_SequentialPipeline.py.in](https://github.com/openMVG/openMVG/blob/8f61623e80c1461a7a0a202f3203101e71f21430/src/software/SfM/SfM_SequentialPipeline.py.in#L62)

I also checked this, but I didn't quite understand it.

D:\openMVG\openMVG_cmake_output\Windows-AMD64-\Release>openMVG_main_ComputeMatches -i matches/sfm_data.json -p  matches/D:\openMVG\openMVG_cmake_output\Windows-AMD64-\Release\matches -o matches/matches.putative.bin
Isn't it the above change?

I would appreciate it if you could give me an example of the command.

I'm sorry for my poor English.

**Comment by koutarou-jp** [comment]
The directory looks like this
![image](https://user-images.githubusercontent.com/105185114/167335151-b2bea772-c28c-4761-923a-5c2077190326.png)

**Comment by lzn1273180880** [comment]
@koutarou-jp Hi, there is a `tutorial.py` script in the directory of `openMVG/src/software/SfM`, note that it is not `openMVG_Build`.
You can simply learn how to use openMVG in the script.

**Comment by koutarou-jp** [comment]
tutorial.py
...
pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-c", "3"] )
...

The command I type first

openMVG_main_SfMInit_ImageListing -i images -o matches -d sensor_width_camera_database.txt -c 3

Is this understanding correct?

**Comment by lzn1273180880** [comment]
you can try@koutarou-jp , the differences have been well shown in the script.
Or you can directly modify the script to use your dataset.
