### ISSUE TITLE
About large-scale bundle adjustment

### ISSUE THREAD

**Issue by qwh9896** [openMVG/openMVG#1975]
In the experiment, we found that the bundle adjustment of openmvg will take a lot of time to optimize R. Therefore, I would like to know which literature solution is the bundle adjustment adopted by openmvg, and whether there are any suggestions for improvement in this part?

**Comment by pmoulon** [comment]
It seems that you are referring to the case where we refine parameters in multiple bundle adjustments with the Global SfM pipeline.

We don't have any particular specific other than leveraging Ceres API for Bundle Adjustment.
There are ways to refine some specifics for Ceres that we are not using (like ceres::ParameterBlockOrdering) but we did not see a lot of improvement when we tried them (could be some bad usage of the API from our side).

Notice also that the more track and the longer they are, the most time-consuming some BA steps will be.
A trick to speed up BA could be to split long track in smaller ones or reduce your track set that you are sending for BA

**Comment by qwh9896** [comment]
> 

First of all, thank you for your timely reply. In addition, I would like to know what is the necessity for us to optimize the internal and external parameters of the camera step by step for the BA stage of global SFM. Why can't we optimize all camera parameters at one time? Also, have you tried to test SBA, PBA and other BA methods?

**Comment by qwh9896** [comment]
> 您似乎指的是我们使用 Global SfM 管道在多个捆绑调整中细化参数的情况。
> 
> 除了利用 Ceres API 进行捆绑调整之外，我们没有任何特定的细节。 有一些方法可以改进我们没有使用的 Ceres 的一些细节（例如 ceres::ParameterBlockOrdering），但是当我们尝试它们时我们没有看到很多改进（可能是我们这边 API 的一些错误使用）。
> 
> 还要注意，轨道越多，时间越长，一些 BA 步骤将是最耗时的。 加速 BA 的一个技巧可能是将长轨道拆分为较小的轨道或减少您发送给 BA 的轨道集


Can I use multithreading technology to accelerate global rotation and bundle adjustment?

**Comment by qwh9896** [comment]
> It seems that you are referring to the case where we refine parameters in multiple bundle adjustments with the Global SfM pipeline.
> 
> We don't have any particular specific other than leveraging Ceres API for Bundle Adjustment. There are ways to refine some specifics for Ceres that we are not using (like ceres::ParameterBlockOrdering) but we did not see a lot of improvement when we tried them (could be some bad usage of the API from our side).
> 
> Notice also that the more track and the longer they are, the most time-consuming some BA steps will be. A trick to speed up BA could be to split long track in smaller ones or reduce your track set that you are sending for BA

We notice that openmvg provides two methods for calculating global rotation, L1 and L2. What is the difference between the two methods? And how different are the two methods in efficiency and accuracy?

**Comment by pmoulon** [comment]
Closing since you the question on rotation and translation averaging solvers is moved here https://github.com/openMVG/openMVG/issues/1986
