### ISSUE TITLE
openMVG_main_IncrementalSfM: command not found

### ISSUE THREAD

**Issue by vabook** [openMVG/openMVG#1976]
When I run the command of openMVG_main_IncrementalSfM ,it occurs error:openMVG_main_IncrementalSfM: command not found.
But I run the other commands ,such as openMVG_main_ComputeMatches and openMVG_main_ComputeFeatures,it works well,
what should I do? 
Thank you all in advance.

**Comment by pmoulon** [comment]
See [here](https://github.com/openMVG/openMVG/issues/1959#issuecomment-962396514).

OpenMVG 2.0 binary names change to enhance flexibility

**Comment by CDluznie** [comment]
Hi.
I tried to apply the SfM pipeline  for equirectangular image as specified [here] (../blob/develop/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm)
It may not be up to date since it use `openMVG_main_IncrementalSfM`.

**Comment by CDluznie** [comment]
`openMVG_main_IncrementalSfM` is also used in [360_dataset](../../Image_datasets/tree/main/360_dataset)

**Comment by pmoulon** [comment]
Updated the doc for OpenMVG and Image_datasets repos.
