### ISSUE TITLE
Is there a zero-copy way to create a openMVG::image::Image?

### ISSUE THREAD

**Issue by wrosecrans** [openMVG/openMVG#1982]
If I already have an image in memory, and I want to make an openMVG image to use with the API, is there any way to "wrap" my existing image data to make a weak/non-owning image without copying it into the openMVG class?

If not, what's the quickest/easiest way to copy the image into the openMVG class without having to do something silly like round-trip it to disk?  The only example in the docs at https://openmvg.readthedocs.io/en/latest/openMVG/image/image/ for populating the image is with the ReadImage function.

**Comment by pmoulon** [comment]
Hello. We don't have zero copy. The fastest way to transfer in memory image would be tu map your data to an eigen map and then to initialize the image with it. Similar to what is done with the eigen2cv and cv2eigen function from opencv.
