### ISSUE TITLE
Unable to convert sfm_perspective_data.bin to OpenMVS 

### ISSUE THREAD

**Issue by ca1773130n** [openMVG/openMVG#1984]
# To reproduce:
- Input: about 1100 equirectangular panoramic images
~~~
openMVG_main_SfMInit_ImageListing -i ./images -o . -c 7
openMVG_main_ComputeFeatures -i ./sfm_data.json -o ./matches --numThreads 72
openMVG_main_ComputeMatches -i ./sfm_data.json -o ./matches -g a
openMVG_main_IncrementalSfM -i ./sfm_data.json -m ./matches -o ./reconstruction -c 7
openMVG_main_openMVGSpherical2Cubic -i ./reconstruction/sfm_data.bin -o ./reconstruction/cubic
openMVG_main_openMVG2openMVS -i ./reconstruction/cubic/sfm_data_perspective.bin -o ./reconstruction/cubic/scene.mvs -d ./reconstruction/cubic/openmvs_images
~~~
# Result:
- Error occured when trying openMVG_main_openMVG2openMVS
~~~
Error while trying to deserialize a polymorphic pointer. Could not find type id 36
The input SfM_Data file "reconstruction/cubic/sfm_data_perspective.bin" cannot be read.
~~~
The exception is from the cereal library and the size of the sfm_data_perspective.bin file is about 600MB.
I couldn't find the same issue like this here.
Any advice will be appreciated.

**Comment by ca1773130n** [comment]
@pmoulon 
Thanks for the reply. Below is the file exported by the command.
[Google Drive](https://drive.google.com/file/d/1IFh4PplScZsaxazfxRMt1stPKn3g2wy0/view?usp=sharing
)

**Comment by pmoulon** [comment]
Thank you for sharing. So from this test at least we know that the file was being able to be read by one OpenMVG binary.
Let's figure out now why an issue arise in `openMVG_main_openMVG2openMVS`

**Comment by ca1773130n** [comment]
@pmoulon 
You're right. Maybe I could debug the loading process of ```openMVG_main_ConvertSfM_DataFormat``` and ```openMVG_main_openMVG2openMVS```. I will share the result later. Thanks.

**Comment by pmoulon** [comment]
Any feedback with continuation of your test?

**Comment by satyajit-ink** [comment]
the issue is back

```
❯ ../OpenMVG-v2.1/openMVG/build/Linux-x86_64-Release/openMVG_main_ConvertSfM_DataFormat -i VID_20240711_151112_00_314_openmvg/reconstruction/cubic/sfm_data_perspective.bin -o VID_20240711_151112_00_314_openmvg/reconstruction/cubic/sfm_data_perspective_test.json -V -I -E
ERROR: [sfm_data_io_cereal.cpp:217] Error while trying to deserialize a polymorphic pointer. Could not find type id 43
ERROR: [main_ConvertSfM_DataFormat.cpp:79] The input SfM_Data file "VID_20240711_151112_00_314_openmvg/reconstruction/cubic/sfm_data_perspective.bin" cannot be read.
```
