### ISSUE TITLE
Why does ANNL2, BRUTEFORCEHAMMING not work and only FASTCASCADEHASHINGL2 will have a successful match

### ISSUE THREAD

**Issue by wangni-bupt** [openMVG/openMVG#1987]
- PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using ANN_L2 matcher
Using the OPENMP thread interface

- Matching -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0

- Geometric filtering -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task done in (s): 0
Graph statistics:
	#nodes: 23
	#cc: 23
	#singleton: 23
	Node degree statistics:	min: 6, max: 0, mean: 1, median: 0

 Export Adjacency Matrix of the pairwise's geometric matches
3. Do Incremental/Sequential reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 0
 Images Id: 

------------------
TrackLength, Occurrence

**Comment by pmoulon** [comment]
Please can you describe which feature detector did you use for computeFeatures and let us know if unit tests run fine on your machine?

**Comment by wangni-bupt** [comment]
I used all the feature points I could use, and none of them matched properly. Therefore, I directly reinstalled the entire OpenMVG library, and the previous make test was all correct. I don't know if there was a dependency problem, but this problem was solved after reinstalling the latest version.

**Comment by wangni-bupt** [comment]
Ubuntu 20.04.1, But it should have nothing to do with the machine, because it recovered after reinstallation

**Comment by pmoulon** [comment]
Thank you for your reply
