### ISSUE TITLE
RSME observation. Doubt about the contribution of this value. 

### ISSUE THREAD

**Issue by Livan89** [openMVG/openMVG#1988]
Hi @pmoulon.

In the sfm process, the RMSE is obtained as a result of the reprojection errors of each generated point. How reliable is this value? 

I have processed models that have been very accurate with some noise around them and the RMSE value is 0.62; however, I have generated other models with very bad calibration, with very few points generated in the sparse, these points scattered and also with cameras in wrong positions in 3D space; this model I describe had a RMSE of 0.44. 

Is this possible, and can I rely on the values to evaluate that a model is correctly generated from studying the RMSE value?

Thank you very much.

**Comment by pmoulon** [comment]
Unfortunately, the RMSE is just a residual error, in some cases, some parameters can compensate each other and lead to local minima.

If you are interested in careful examination of RMSE I would recommend you to add control points to rescale your scene and constraint it to real scale. This way you would know if something is wrong, or you could compute the scene parameters uncertainty (covariance).

**Comment by Livan89** [comment]
Thank you @pmoulon .

I have done the suggestion you give me, I have added control points and the RMSE results seem very reliable. 

Thank you very much again and happy new year. 

I close issue.

**Comment by pmoulon** [comment]
Glad you were able to try
