### ISSUE TITLE
Build error Linux #1927 same on Windows10

### ISSUE THREAD

**Issue by jsemeda** [openMVG/openMVG#1990]
Can someone please explain how to fix this same error on Windows? I do not understand what the fix is here. I am using Visual Studio 2019. Thanks

**Comment by pmoulon** [comment]
It should be fixed with the version in develop.
Do you still have the compiling error?

**Comment by jsemeda** [comment]
Yes that fixed it, thanks. I have a different error though ...
bundle_adjuster.obj : error LNK2001: unresolved external symbol "class std::set<class google::LogSink *,struct std::less<class google::LogSink *>,class std::allocator<class google::LogSink *> > google::log_sinks_global" (?log_sinks_global@google@@3V?$set@PEAVLogSink@google@@U?$less@PEAVLogSink@google@@@std@@V?$allocator@PEAVLogSink@google@@@4@@std@@A)
1>bal_problem.obj : error LNK2001: unresolved external symbol "class std::set<class google::LogSink *,struct std::less<class google::LogSink *>,class std::allocator<class google::LogSink *> > google::log_sinks_global" (?log_sinks_global@google@@3V?$set@PEAVLogSink@google@@U?$less@PEAVLogSink@google@@@std@@V?$allocator@PEAVLogSink@google@@@4@@std@@A)

**Comment by pmoulon** [comment]
I believe you are still using an external Ceres or that you are trying to compile Ceres example files...
bundle_adjuster.obj should not come from OpenMVG by itself, so please ensure you don't activate Ceres example compilation
