### ISSUE TITLE
How to handle images from two UTM zones?

### ISSUE THREAD

**Issue by qingzhengzhuma** [openMVG/openMVG#1991]
Hey, I have an image set, but the gps prior is taking from two UTM zones, after the transform of lla_to_utm, the cartesian coordinates get splitted into two cluster, is there any idea to handle this situation?

**Comment by pmoulon** [comment]
Hello, sorry for the late answer.
Do you have 1 or two connected component after image matching?
This information should be displayed at the ComputeGeometricMatches stage.

You could try to increase the number of features per images and see if it helps (-p HIGH on mainComputeFeatures)

**Comment by qingzhengzhuma** [comment]
Thanks for reply. Matching stage is fine, the problem is that sfm get failed or with a lot of images are removed after ba with gps prior. I think with images from different UTM zones, all gps priors consist a  nonuniform cartesian coordinate system. if I disabled  gps prior, everything is fine.

**Comment by qingzhengzhuma** [comment]
Now I choose priors from the only one UTM zone with most images to use, and it works.
