### ISSUE TITLE
Help with linux SfM pipeline

### ISSUE THREAD

**Issue by crumplecup** [openMVG/openMVG#1992]
Trying to work through the Sceaux Castle example (git cloned into /home/bob/castle/) with the following code:

```
> openMVG_main_SfMInit_ImageListing -i /home/bob/castle/images/ -d /home/bob/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o /home/bob/castle/matches/
> openMVG_main_ComputeFeatures -i /home/bob/castle/matches/sfm_data.json -o /home/bob/castle/matches/
> openMVG_main_ComputeMatches -i /home/bob/castle/matches/sfm_data.json -o /home/bob/castle/matches/
> openMVG_main_SfM -i /home/bob/castle/matches/sfm_data.json -m /home/bob/castle/matches/ -o /home/bob/castle/recon/ -s INCREMENTAL
```
I get the message:
```
ERROR: [main_SfM.cpp:409] Cannot load the match file.
```
Running ComputeMatches produces a series of .feat and .desc files in matches/ associated with the 11 source images, as well as:
image_describer.json
preemptive_pairs.txt
PutativeAdjacencyMatrix.svg
putative_matches [graphviz DOT graph]
putative_matches.svg

I am working from openmvg.readthedocs.io, and where they are out-of-date and I am (ineffectually) relying on --help files.  Any advice is appreciated.

**Comment by pmoulon** [comment]
It is most likely that the online doc is not uptodate.
You need to call FIlterMatches now.
Try follow the guidance in the python files shared in SfM folder https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/SfM_SequentialPipeline.py.in#L65

Sorry we will try to update the doc...

**Comment by crumplecup** [comment]
Thank you for the timely reply.  Documentation is a grind, no apology needed.

The command sequence in the python file you referenced works as expected on Sceaux Castle.  I have tried it on my own photos yet but I am excited to get started!
