### ISSUE TITLE
Cannot use OpenMVG as a third party library dependency in Ubuntu 20.04

### ISSUE THREAD

**Issue by ChenMa2017** [openMVG/openMVG#1999]
I installed the OpenMVG in Ubuntu 20.04 following the instruction at https://github.com/openMVG/openMVG/blob/master/BUILD.md.

The outputs of two tests :
$ make test
$ ctest --output-on-failure -j,
are " 100% tests past, 0 tests failed out of 85 ".

I copied the CMakeLists commands from the instruction. 

And my CMakeLists.txt is : 

cmake_minimum_required(VERSION 3.0.0)
project(main VERSION 0.1.0)

include(CTest)
enable_testing()

find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
add_executable(main main.cpp)
target_link_libraries(main ${OPENMVG_LIBRARIES})
#
message(STATUS "mvg dirs:" ${OPENMVG_INCLUDE_DIRS}  )
message(STATUS "mvg libs:" ${OPENMVG_LIBRARIES} )

#
set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)

The output of CMake is

 -- OpenMVG Find_Package
 -- ----
 -- Found OpenMVG version: 2.0.0
 -- Installed in: /usr/local 
 -- ----
 -- mvg dirs:
 -- mvg libs:
 -- Configuring Done
 -- Generating Done . 

The two messages are empty.

In the file "/build/CMakeFiles/main.dir/build.make", the external object files for target main are empty.
"main_EXTERNAL_OBJECTS =  "

In the file "/build/CMakeFiles/main.dir/link.txt", it is "/bin/x86_64-linux-gnu-g++-9 -g -rdynamic CMakeFiles/main.dir/main.cpp.o -o main ". There is no libraries added. 

In the file "/build/.cmake/api/v1/reply/cache-v2-d5de67d4af576c8ed53c.json", there is some information about OpenMVG
		{         "name" : "OpenMVG_DIR",
		         "properties" : 
			[{        "name" : "HELPSTRING",
			          "value" : "The directory containing a CMake configuration file for OpenMVG."}],
			"type" : "PATH",
			"value" : "/usr/local/share/openMVG/cmake"}.

And in the main.cpp, there is one error after "# include <openMVG/image/image_io.hpp>" . 
It says "#include errors detected based on information provided by the configuration Provider setting."

I tried to load one image using : 
 " Image <Rgb<double> > rgb_img_32bit;
   bool bRet = openMVG::image::ReadImage("test.png", &rgb_img_32bit); "
It says "undefined reference to `int openMVG::image::ReadImage<openMVG::image::Rgb<double> >(char const*, openMVG::image::Image<openMVG::image::Rgb<double> >*)'" .
It seems that the linker does find the libraries.

Did I do something wrong in the CMakeLists? 
How can I know whether I installed the OpenMVG corrected?

**Comment by pmoulon** [comment]
See here https://github.com/openMVG/openMVG/blob/develop/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake
You have to set the library name you are using, include will comes transitively with them

**Comment by ChenMa2017** [comment]
Hi Pmoulon， 
    Thanks very much for your quick reply!
    Do you mean using 
                  target_link_libraries(main  PRIVATE OpenMVG::openMVG_image)
    instead of
                  target_link_libraries(main ${OPENMVG_LIBRARIES}  )  
   ?
Thanks!

**Comment by pmoulon** [comment]
Yes, we can work together on improving the API

**Comment by ChenMa2017** [comment]
After I use this command, the CMake says: 
[cmake]   Target "main" links to target "OpenMP::OpenMP_CXX" but the target was not
found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

The CMake can find the OpenMVGConfig.cmake file. 
And this file output : 
[cmake] -- OpenMVG Find_Package
[cmake] -- ----
[cmake] -- Found OpenMVG version: 2.0.0
[cmake] -- Installed in: /usr/local 

But when I used  
message(STATUS "mvg dirs:" ${OPENMVG_INCLUDE_DIRS}  )
message(STATUS "mvg libs:" ${OPENMVG_LIBRARIES} ),
the  ${OPENMVG_INCLUDE_DIRS}  and ${OPENMVG_LIBRARIES} are empty.
Did I do something incorrect?

**Comment by pmoulon** [comment]
It is most likely that the approach with OPENMVG_X is broken
I would advise to use the `modern target-based approach`  cited here and clearly state the library you want to use (include will come transitively) https://github.com/openMVG/openMVG/blob/develop/BUILD.md#using-openmvg-as-a-third-party-library-dependency-with-cmake

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
