### ISSUE TITLE
What is the rational behind using the median of errors to scale the loss function when using motion prior?

### ISSUE THREAD

**Issue by melhashash** [openMVG/openMVG#2001]
I am referring to this line.

https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L455

Why the width/scale of Huber loss is set to ` Square(pose_center_robust_fitting_error)`?

**Comment by pmoulon** [comment]
When we use GPS we have almost no idea about the accuracy of the system and measurements the user has used.
So using the median of fitting error is a kind of robust way to filter some outlier GPS measurements if there are any.
Perhaps the value is too small and could be adjusted to a better value.

As you are certainly aware not all GPS values get in a flight will have the same confidence/accuracy. So we are doing our best here to deal with possible outliers measures that we have observed in some of datasets we tried.
