### ISSUE TITLE
Export symbols in CMake

### ISSUE THREAD

**Issue by RamadanAhmed** [openMVG/openMVG#2002]
I wonder why there isn't an export header generated using `GenerateExportHeader` which can be used in Windows and Linux to export only required parts of the library.
If there is a possibility of adding something like that I'm willing to work on that issue

**Comment by pmoulon** [comment]
Hello, I was not aware of this functionality ''GenerateExportHeader"
Feel free to give it a try and see how it could help the project

**Comment by pmoulon** [comment]
Closing it for now... Feel free to reopen this as a PR for the project ;-)
