### ISSUE TITLE
How to multiply similarity3?

### ISSUE THREAD

**Issue by dhcode-cpp** [openMVG/openMVG#2004]
Hello:

I have trouble in transforming coordinate conversion, and I need your help.

In Similarity3.cpp, how to multiply similarity3?

```
Pose3 Similarity 3::operator () ( const Similarity 3 &sim ) const
{
 ?
}
```
Looking forward to your reply, thanks!!!

**Comment by pmoulon** [comment]
This function is implemented already.

You should do result = pose(pose2);

More context here #1288
