### ISSUE TITLE
Using other Sequential SfM resection solver type 

### ISSUE THREAD

**Issue by KibaekJeong** [openMVG/openMVG#2005]
In sequential SfM, I see that resection method is defined to be DLT_6POINTS. 
Is it possible to change this into solver like P3P_KE_CVPR17 ?? 
If yes, does anyone have experience on this ? and got better result on SfM?

**Comment by pmoulon** [comment]
Dlt 6 points will be use only if you have an unknown focal length for your images. Else P3P_NORDBERG_ECCV18 is used (see here https://github.com/openMVG/openMVG/blob/a75c6058df07befc6e1ad85b7d7aa2fb814c5e5b/src/openMVG/multiview/solver_resection.hpp#L22)

**Comment by pmoulon** [comment]
You can choose from the command line the function you want to use https://github.com/openMVG/openMVG/blob/a75c6058df07befc6e1ad85b7d7aa2fb814c5e5b/src/software/SfM/main_SfM.cpp#L248 but you must have approximate intrinsic defined for the view
