### ISSUE TITLE
About the efficiency of sfm or openMVG

### ISSUE THREAD

**Issue by lzn1273180880** [openMVG/openMVG#2006]
Hello! How are you doing recently?
I have questions about how efficient is the openMVG and how long does it take when you are trying to reconstruct a 3D model using openMVG , simultaneously I am trying to improve the efficiency of openMVG , do you have any hints on it?
By the way , I am trying to use the screenshots of video shot by my device to construct a model , is it practicable?
Thank you so much.

**Comment by lzn1273180880** [comment]
By the way my CPU is R7 4800HS with 16GB memory and RTX 2060 graphic card.

**Comment by pmoulon** [comment]
Hi,
OpenMVG default could not be best optimized to run SfM and feature extraction and matching on your machine.
Can you tell more about the typical size of dataset you want to handle?

Tips:
- Use the -n X on ComputeFeature with X the number of thread of your machine
- Use less feature per images if you can (see preemptive matching)
- If you process video content you could use Matching of consecutive pair (see GeneratePairs)

>  the screenshots of video shot by my device
Can you tell us a bit more about what type of image you have (frame of a video)

**Comment by lzn1273180880** [comment]
Now we are planning to rent a cloud server to help us compute features, maybe more threads will help to improve efficiency.
Our dataset size is about 50MB-60MB with 17-20 photos in it, those photos are screenshots from the video without exif info, so we just run `focal_multiplier` by default. Does `focal_multiplier` have a negative impact on efficiency?
Best wishes.

**Comment by lzn1273180880** [comment]
What does openMVG need while computing features？
Single core performance or the number of theads？

**Comment by tmxftw** [comment]
Hi @lzn1273180880, I am similarly using openCV to extract frames from a video before inserting Exif data. I am using piexif to convert the metadata dict into bytes before inserting it into each extracted frame. I have found that openMVG requires, 271 (Image input equipment manufacturer), 272 (Image input equipment model), and 37386 (Focal length).

```
# form new exif dict and bytes from extracted metadata
zeroth_ifd = {271: b'samsung', 272: b'SM-G973F'}
exif_ifd = {37386: (432,100)}

# bytes to be inserted formed
exif_dict = {"0th": zeroth_ifd, "Exif": exif_ifd}
exif_bytes = piexif.dump(exif_dict)

# Start of metadata editing
for image_path in image_list:
    piexif.insert(exif_bytes, image_path)
```

I am using my Samsung S10 to record the videos and the focal length I inserted is copied from images taken with my phone's 1x zoom camera. Not sure if this helps

**Comment by lzn1273180880** [comment]
> Hi @lzn1273180880, I am similarly using openCV to extract frames from a video before inserting Exif data. I am using piexif to convert the metadata dict into bytes before inserting it into each extracted frame. I have found that openMVG requires, 271 (Image input equipment manufacturer), 272 (Image input equipment model), and 37386 (Focal length).
> 
> ```
> # form new exif dict and bytes from extracted metadata
> zeroth_ifd = {271: b'samsung', 272: b'SM-G973F'}
> exif_ifd = {37386: (432,100)}
> 
> # bytes to be inserted formed
> exif_dict = {"0th": zeroth_ifd, "Exif": exif_ifd}
> exif_bytes = piexif.dump(exif_dict)
> 
> # Start of metadata editing
> for image_path in image_list:
>     piexif.insert(exif_bytes, image_path)
> ```
> 
> I am using my Samsung S10 to record the videos and the focal length I inserted is copied from images taken with my phone's 1x zoom camera. Not sure if this helps
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

> yeah, I got this 1 month ago, but I still appreciate you so much!  I also used piexif to add exif info into the screenshots, it worked well but seemed like `*.png` file were not supported by piexif. I may find another package to solve it, if u find more practical way please contact any time, thank you so much again.

**Comment by tmxftw** [comment]
Hi @lzn1273180880, I am not sure about the current status of your project, however, I would like to ask you if you were able to follow the tips given by pmoulon?

> Tips:
> 
> * Use the -n X on ComputeFeature with X the number of thread of your machine
> * Use less feature per images if you can (see preemptive matching)
> * If you process video content you could use Matching of consecutive pair (see GeneratePairs)

I am still new to all this, hence I am not sure how to exactly follow these tips. 
1. I understand that in order to use multi-thread during ComputeFeature, I would need to have compiled openMVG with openMP activated right as according to this [reply](https://github.com/openMVG/openMVG/issues/1730#issuecomment-622314727)
2. I am unsure how to edit preemptive matching as well as the usage of contiguous pair generation mode.

I tried to change the original SfM_GlobalPipeline.py file to use additional arguments by including '"-m" , 'CONTIGUOUS', '-c', 3' like so:
```
print ("3. Compute matching pairs")
pPairs = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_PairGenerator"), "-i", matches_dir+"/sfm_data.json", "-o" , matches_dir + "/pairs.bin" , "-m" , 'CONTIGUOUS', '-c', 3])
pPairs.wait()
```
However this is the output when I ran SfM_GlobalPipeline.py:
```
3. Compute matching pairs
 You called:
/openMVG/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_PairGenerator
--input_file       : /home/user/Downloads/datasets/video_datasets/blk41_redpipe_2/frames/result/matches/sfm_data.json
--output_file      : /home/user/Downloads/datasets/video_datasets/blk41_redpipe_2/frames/result/matches/pairs.bin
Optional parameters
--pair_mode        : EXHAUSTIVE
--contiguous_count : -1
```

Could you or @pmoulon help me know how to : 
1. change the pair generation from exhaustive to contiguous
2. use preemptive matching

**Comment by lzn1273180880** [comment]
Hi @tmxftw, from my experience, you could simply use `-n` flag to set the max threads of your machine. And some of the parts are mainly mono-thread, but when you use `-n` flag correctly you can get a decent speed basically.
For the preemptive matching part you could see `openMVG_main_ComputeMatches` but I don't really set that, I'm sorry.

**Comment by lzn1273180880** [comment]
@tmxftw On a side note, the exif info could be missing due to `focal_multiplier`, but I suppose it has a bad impact on the speed in a certain extend...? The speed of running was slower than the normal  running at that time when the `focal_multiplier` worked. I'm not sure about it, but it does help a lot when the sensor width is unknown, if you use it please tell me your result of test and the speed, thank you.

**Comment by lzn1273180880** [comment]
@pmoulon Maybe the author could give us more details about it.

**Comment by tmxftw** [comment]
Hi @lzn1273180880, I have rebuilt my docker container with openMP and managed to enable multi-thread processing, and there is a noticable speed difference. I also managed to change the pair generation search method to contiguous. Thanks for the help and advice.

**Comment by lzn1273180880** [comment]
Nice job! Congratulations to you, I still haven't try to use contiguous pair, could you please tell me where to set it?

**Comment by tmxftw** [comment]
@lzn1273180880 I frequently use the python scripts for the sequential and global pipelines. I edited the python script to become this:

```
print ("3. Compute matching pairs")
pPairs = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_PairGenerator"), "-i", matches_dir+"/sfm_data.json", "-o" , matches_dir + "/pairs.bin" , "-m" , "CONTIGUOUS", "-c", "3"])
pPairs.wait()
```
by adding `"-m" , "CONTIGUOUS", "-c", "3"`

**Comment by lzn1273180880** [comment]
Hi, glad to hear your reply again @pmoulon.
So far we have decently done our job using OpenMVG, but I still have a question.  I am wondering if it is a flaw for the SFM algorithm to reconstruct an object that is self-rotating? When the background is unchanging but the object is rotating, it seems like a hard situation for SFM to reconstruct it. The images will be like:
![1](https://user-images.githubusercontent.com/94612909/159449040-b043bd02-8ed0-4705-9b05-31c4c09baaea.jpg)
![2](https://user-images.githubusercontent.com/94612909/159449151-b3bc8821-7ee1-4d6a-a062-0c87028597a5.jpg)
I suppose the error appeared in the step 'Select an edge from connected graph G' after calculating the Tracks(that's how we call in our language), can you tell me the principle?
On a side note, we would like to help solve this situation from the source code, but we have no idea where to start with so far.

**Comment by alexs7** [comment]
@pmoulon Hello, I have compiled OpenMVG with OpenMP support, but the `openMVG_main_SfM` binary still uses one CPU core. Is there anything else I have to enable ?
