### ISSUE TITLE
Moving objects (turntable)

### ISSUE THREAD

**Issue by Karric** [openMVG/openMVG#2007]
Is openMVG a strict photogrammetric framework? Does it require the object to be perfectly stationary? I have some turntable videos I'd like to do sfm on, but the object rotates and maybe flex a bit (plants), thus alignment is not 100% in every view. Historically, photogrammetry wouldn't work with this kind of data set.

**Comment by pmoulon** [comment]
Hello Karric,
I would say it all depends on feature matching.
If your background is static you could try to remove it by using masking (either automatic or pseudo manual) and then run SfM.

OpenMVG supports global masking or per image masking. (either one mask for all images, or a mask per image)


Feel free to share to us a dataset and we can see what we can do.
