### ISSUE TITLE
Build issue on Mac OS (omp.h not found)

### ISSUE THREAD

**Issue by Karric** [openMVG/openMVG#2008]
> [ 10%] Built target lib_CoinUtils
> [ 12%] Built target lib_Osi
> [ 21%] Built target lib_clp
> [ 22%] Built target lib_OsiClpSolver
> [ 23%] Built target openMVG_stlplus
> [ 23%] Built target main_svgSample
> [ 33%] Built target openMVG_cxsparse
> [ 33%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/block_evaluate_preparer.cc.o
> In file included from /Users/jason/git/openMVG/src/third_party/ceres-solver/internal/ceres/block_evaluate_preparer.cc:34:
> In file included from /Users/jason/git/openMVG/src/third_party/ceres-solver/internal/ceres/block_sparse_matrix.h:38:
> In file included from /Users/jason/git/openMVG/src/third_party/ceres-solver/internal/ceres/sparse_matrix.h:38:
> In file included from /Users/jason/git/openMVG/src/third_party/ceres-solver/include/ceres/internal/eigen.h:34:
> /Users/jason/git/openMVG/src/third_party/eigen/Eigen/Core:70:10: fatal error: 'omp.h' file not found
> #include <omp.h>
>          ^~~~~~~
> 1 error generated.
> make[2]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/block_evaluate_preparer.cc.o] Error 1
> make[1]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/all] Error 2
> make: *** [all] Error 2

Various SO posts implied that Apple did something weird with the clang compiler and that some of these built in files no longer come with macOS.

I used `brew install libomp` and updated the files below to directly point to a new omp.h file but that didn't seem to do anything:

- OpenMPCheckVersion.cpp
- OpenMPTryFlag.cpp
- OpenMPCheckVersion.c
- OpenMPTryFlag.c

Let me know if there's anything else I can do to get this working. Will try docker approach in the meantime.

**Comment by rfabbri** [comment]
Hi why did you close this issue?

**Comment by rfabbri** [comment]
PR #2008 fixes this. If you can , please try it out.
