### ISSUE TITLE
How to eliminate inaccurate 3D points?

### ISSUE THREAD

**Issue by melhashash** [openMVG/openMVG#2009]
Hello,

The image below shows a side view of the reconstruction for an aerial dataset.

There are many outliers (points under the ground) in the resultant reconstruction using the default settings of the sequential SfM pipeline.

![image](https://user-images.githubusercontent.com/14876749/153542540-19450f78-1117-470b-95f6-dc07635e943e.png)

**Comment by pmoulon** [comment]
Hello @melhashash ,
thank you for sharing your experience, a screenshot to illustrate the problem.

Such problem could happen when a lot of image are either concentrated at a similar position, or aligned.
When you triangulate feature with small angles between their bearing vector, the estimated 3D points are less accurate.

Often, such `outliers` will not be an issue if you try to densify the point cloud with OpenMVS, PMVS, ...

If you want to remove them, you can either set the minimal angle for triangulation rejection to be higher or reject points that are not seen on X views.
Those parameters should be accessible on the 'Triangulation engine'.

Hoping it helps, else nice jobs, the reconstruction seems quite good (did you use GPS priors for matching, SfM)?

**Comment by melhashash** [comment]
Hello @pmoulon,

Yes, I used GPS priors for both matching and SfM.
