### ISSUE TITLE
Could I get some code information of matching point from this library ?

### ISSUE THREAD

**Issue by BaeSukkyoung** [openMVG/openMVG#2012]
Could I get some code information of matching point from this library ?
Matching point is that overlapped parts in photos for 3D modeling.

**Comment by pmoulon** [comment]
Code, documentation, and binary are pretty easy to read.
Can you elaborate on which specific section you want more info.

OpenMVG can use any feature/descriptor thanks to its FeatureRegion concept, and then we can use various matcher thanks to inheritance.
