### ISSUE TITLE
Out of plane pointcloud for running SfM with known Hololens poses

### ISSUE THREAD

**Issue by RishabhBajaj25** [openMVG/openMVG#2013]
I have been trying to use your library to reconstruct a scene using dataset collected from the Microsoft hololens2. I wrote a short script to import the poses from the Hololens and then running `ComputeStructureFromKnownPoses`. However, it returned a pointcloud where the points seem to be out of plane.

When I ran the same images but let openMVG decide the poses using `GlobalSfM`, I get excellent results. My educated guess is that there is a difference in the coordinate system and conventions that Microsoft and openMVG use, in terms of rotation matrices, translation vectors and perhaps internal matrices as well. 

When I investigated the sfm_data.json for both cases, some of the differences in the rotation matrices were obvious. However, when I modified my pose importer script for `ComputeStructureFromKnownPoses`, so that I import the rotation matrices to look like the ones present in sfm_data.json from open_MVG using `GlobalSfM` the reconstructed scene disappeared. 

Can you help me understand the coordinate system and other conventions that open MVG follows so that I can correct my pose importer script?

**In both cases, the camera positions seem to be correct. However, there is a difference between the two in terms of the orientation and the scale.**

I am attaching a few screenshots for more context:

1. Scene reconstructed by `GlobalSfM` when I first open it in meshlab (Note that the scene is upside down):
a)
![image](https://user-images.githubusercontent.com/70211310/155212603-2e829432-0e71-44e8-90f1-a187795a9efd.png)
b) Same scene from different viewpoints
![image](https://user-images.githubusercontent.com/70211310/155212638-d6eca8ab-2717-4aa0-9be4-b2cd372d9722.png)
![image](https://user-images.githubusercontent.com/70211310/155212784-c5934e22-1b16-4984-9325-dd0ca6a28634.png)

2. Scene reconstructed by `ComputeStructureFromKnownPoses` using poses determined by Hololens2:
a) When first opened in Meshlab: 
![image](https://user-images.githubusercontent.com/70211310/155212961-5507f744-4bf4-4c79-b186-9be9956d109e.png)

**Comment by pmoulon** [comment]
Indeed it seems that the camera poses does not seems to make OpenMVG Happy.
Please use the https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/export/main_ExportCameraFrustums.cpp binary to check your camera orientation.
- Double-check your camera orientation & camera translation. Please notice that OpenMVG uses camera centers.
- Double-check intrinsic values

OpenMVG uses Z in front of the camera (camera looking direction)

**Comment by RishabhBajaj25** [comment]
Hi Pierre,
Thanks for your response. I actually did use the frustums to debug but could not land at any useful interpretation since the frustums look good for both cases. The intrinsic values are closeby too.

1. Camera frustums for `ComputeStructureFromKnownPoses`:
![image](https://user-images.githubusercontent.com/70211310/155243216-ecec2fb1-eddf-4347-bfda-d53625666fb3.png)

2. Camera Frustums for `GlobalSFM`:
![image](https://user-images.githubusercontent.com/70211310/155243280-6746ddd8-200f-4b70-98b7-831c1c6b4a72.png)

**Comment by RishabhBajaj25** [comment]
Additionally, it would be great help if you could help clarify how the rotation and centers are created for openMVG in sfm_data.json

**Comment by RishabhBajaj25** [comment]
Turns out that there was a bug in my code while importing poses from the file generated by Hololens, the pointcloud looks much better now but still has a few outliers: 
![image](https://user-images.githubusercontent.com/70211310/155615196-45295498-cb54-43c5-b73f-35cbb59da708.png)

For this case, I did not rearrange the rotation matrices to resemble the order of openMVG. I believe I still get somewhat of a correct result owing to the fact that translations (centers) are also calculated accordingly.

**Comment by pmoulon** [comment]
Great to hear that you found the conversion bug!
