### ISSUE TITLE
Automated Scaling of Point Clouds

### ISSUE THREAD

**Issue by tmxftw** [openMVG/openMVG#2016]
Hi,

I am trying to find a way to automatically output an accurately scaled with real-life dimensions point cloud. Since scaling requires real world dimensions, I assume the easier way is to use something standardised like aruco markers.

I have read issues #1320 and #1239 which seems to show a way to do scaling with aruco markers in openmvg using the .bin file produced by openMVG_main_IncrementalSfM. I suspect this file is no longer part of the source code as I can't find it anymore, hence my attempt to recreate the scaling through these avenues were halted.

Thank you in advance!

**Comment by pmoulon** [comment]
You can either use GCP that you click manually and define the distance between those points, or try to use other code samples that use Aruco. If you feel like adventurous we would be happy to receive a contribution tutorial on this

**Comment by tmxftw** [comment]
Thanks for replying!

Upon future reading, I found a paper that scales the point cloud using GNSS data, [Link to paper](https://www.mdpi.com/2075-163X/11/12/1301/pdf) . That said, I am wondering if such an idea can be implemented on openMVG using the sequential reconstruction pipeline, before dense point cloud construction using openMVS. 

My idea is that with an accelerometer, the motion of the camera can be tracked. These relative motions can be cross-checked with the estimated camera positions by the reconstruction pipeline, and use as the true values to enable scaling of the point cloud.

Any pointers to get this would be amazing!

**Comment by pmoulon** [comment]
OpenMVG does already support GPS positional constraint as prior or just as rescaling

**Comment by tmxftw** [comment]
Hi @pmoulon as opposed to using GPS positional constraints which would be harder, because I am using my phone to capture the images indoors, I am thinking of an alternative solution through the use of scale bars.

My idea is to include a scale bar near the object of interest and including it in the scene, via greater emphasis on the scale bar initially. Once the features of the scale bar is extracted during ComputeFeatures, I wish to use the extracted features as a means to scale the image. What I have realised is, by multiplying Extrinsics and Structure of SfM_data.json by a scalar, I can effectively scale the final dense point cloud. Hence, I wish to use the extracted features of the scale bar as a means to obtain the scalar.

If the first few images are emphasizing the scale bar, is there a way to know which points/features belong the scale bar?
Upon knowing which points/features belong to the scale bar, the projected length of the scale bar can be calculated, and used to divide the known length of the scale bar. Thus obtaining the appropriate scalar to multiply SfM_data with, before converting into scene.mvs for dense point cloud reconstruction by OpenMVS

I hope you can guide me along for this automated scaling!

**Comment by tmxftw** [comment]
![image](https://user-images.githubusercontent.com/88308298/168015237-0854aec0-d1da-401a-b4b6-e717ea4d4abb.png)

I plotted the first two columns of a .feat file to visualise it, guessing it was the xy coordinates of the extracted features in the image.However, I am unsure what the last 2 columns stand for. Could you help to explain it for me, @pmoulon ?

![image](https://user-images.githubusercontent.com/88308298/168015667-09ddde1e-f0b9-4e6a-af04-3b037976ee5a.png)

**Comment by pmoulon** [comment]
Looking to the code, it is `X,Y, Scale, Orientation`
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/feature.cpp#L79
