### ISSUE TITLE
Hello ! apt-get install xorg-dev libglu1-mesa-dev

### ISSUE THREAD

**Issue by 459737087** [openMVG/openMVG#2018]
when I try to install it 
apt-get install xorg-dev libglu1-mesa-dev
it goes wrong 
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-common_2.4.105-3~20.04.2_all.deb  404  Not Found [IP: 192.168.1.2 6666]
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm2_2.4.105-3~20.04.2_amd64.deb  404  Not Found [IP: 192.168.1.2 6666]
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-amdgpu1_2.4.105-3~20.04.2_amd64.deb  404  Not Found [IP: 192.168.1.2 6666]
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-intel1_2.4.105-3~20.04.2_amd64.deb  404  Not Found [IP: 192.168.1.2 6666]
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-radeon1_2.4.105-3~20.04.2_amd64.deb  404  Not Found [IP: 192.168.1.2 6666]
E: 无法下载 http://mirrors.aliyun.com/ubuntu/pool/main/libd/libdrm/libdrm-nouveau2_2.4.105-3~20.04.2_amd64.deb  404  Not Found [IP: 192.168.1.2 6666

**Comment by pmoulon** [comment]
Hi, what is your linux distrib (which ubuntu)?
- Note that those dependencies are optional, you do not need them to run the command line tools

**Comment by 459737087** [comment]
ubuntu 20.04

**Comment by pmoulon** [comment]
From what I see the package xorg-dev is present on https://packages.ubuntu.com/focal/xorg-dev see here https://packages.ubuntu.com/search?keywords=xorg-dev
Not that you can still use OpenMVG with the command line
