### ISSUE TITLE
Correct Way to Initialise Pose

### ISSUE THREAD

**Issue by RishabhBajaj25** [openMVG/openMVG#2021]
Hello,

As per a few readings, I concur that to initalise sfm with initial pose, we have to run `openMVG_main_IncrementalSfM2`. Can anybody please confirm with the correct settings to be used with these? I have a sfm_data.json file which i ran with known poses using `openMVG_main_ComputeStructureFromKnownPoses`. How do I use these intrinsics to intialise the SfM reconstruction? 

Below are the settings that I see for `IncrementalSfM2`. Can anybody who has used this before help me figure the exact settings out? 
Thanks!
![image](https://user-images.githubusercontent.com/70211310/156048138-d49d2d6b-9e4d-4d3a-8d88-e602247c60d9.png)

**Comment by pmoulon** [comment]
With OpenMVG2.0 all the SfM engine has been merged in the binary main_SfM.
It seems you are using a previous OpenMVG version.

If your scene has poses openMVG_main_IncrementalSfM2 you can use  `--sfm_initializer EXISTING_POSE`
