### ISSUE TITLE
Mac M1 Cmake compiling error

### ISSUE THREAD

**Issue by lvaight** [openMVG/openMVG#2024]
Hi all,
I'm trying to build the openMVG environment on Mac, using the following command:

1. git clone --recursive https://github.com/openMVG/openMVG.git
2. mkdir openMVG_Build
3. cd openMVG_Build
4. cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
5. cmake --build . --target install

then I got these error message:

(python38) ➜  openMVG_Build cmake --build . --target install
[  0%] Building HTML documentation with Sphinx
正在运行 Sphinx v4.2.0
WARNING: html_static_path 指向的 '_static' 不存在
加载 pickled环境... 完成
构建 [mo]： 0 个 po 文件的目标文件已过期
构建 [html]： 0 个源文件的目标文件已过期
更新环境: 已添加 0，0 已更改，0 已移除
查找当前已过期的文件... 没有找到
没有过期的目标文件。
构建 成功, 1 警告。

HTML 页面保存在 htmlDoc 目录。
[  0%] Built target doc
[  3%] Built target glfw
[ 11%] Built target lib_CoinUtils
[ 12%] Built target lib_Osi
[ 19%] Built target lib_clp
[ 20%] Built target lib_OsiClpSolver
[ 20%] Built target CppUnitLite
[ 21%] Built target openMVG_stlplus
[ 27%] Built target openMVG_jpeg
[ 29%] Built target openMVG_zlib
[ 31%] Built target openMVG_png
[ 36%] Built target openMVG_tiff
[ 36%] Built target main_svgSample
[ 36%] Built target openMVG_easyexif
[ 37%] Built target openMVG_fast
[ 37%] Built target openMVG_numeric
[ 38%] Built target openMVG_test_Camera_Pinhole
[ 39%] Built target openMVG_test_Camera_Pinhole_Radial
[ 39%] Built target openMVG_test_Camera_Pinhole_Brown
[ 39%] Built target openMVG_test_Camera_Pinhole_Fisheye
[ 39%] Built target openMVG_test_Camera_Spherical
[ 39%] Built target openMVG_test_Camera_Subset_Parametrization
[ 39%] Built target openMVG_test_Camera_IO
[ 41%] Built target openMVG_features
[ 42%] Built target openMVG_matching
[ 42%] Built target openMVG_test_kmeans
[ 42%] Built target openMVG_exif
[ 42%] Built target openMVG_test_exif_IO
[ 43%] Built target openMVG_test_ParseDatabase
[ 44%] Built target openMVG_test_features
[ 44%] Built target openMVG_test_image_describer
[ 44%] Built target openMVG_image
[ 44%] Linking CXX executable ../../../Darwin-arm64-RELEASE/openMVG_test_akaze
Undefined symbols for architecture arm64:
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in libopenMVG_png.a(pngrutil.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Darwin-arm64-RELEASE/openMVG_test_akaze] Error 1
make[1]: *** [openMVG/features/akaze/CMakeFiles/openMVG_test_akaze.dir/all] Error 2
make: *** [all] Error 2

I have no idea with this problem, what can I do to solve this?

**Comment by csparker247** [comment]
I just came across this issue. Since nothing was posted here, my solution was to use an external `libpng` and not the built-in one. OpenMVG defaults to using external if it's found, so `brew install libpng` should be sufficient.

**Comment by pmoulon** [comment]
Thx you @csparker247 to list your fix to the community!

**Comment by dhcode-cpp** [comment]
other solution is:

use internal png , in  ``./openMVG/src/third_party/png/pngpriv.h``

set #define PNG_ARM_NEON_OPT 0 

no optimized by neon
