### ISSUE TITLE
Build Error on Mac

### ISSUE THREAD

**Issue by songjingrui** [openMVG/openMVG#2026]
Hi all,
I'm trying to build the openMVG environment on Mac, using the following command:

git clone --recursive https://github.com/openMVG/openMVG.git
mkdir openMVG_Build
cd openMVG_Build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
cmake --build . --target install

While,I got this mistake, How can I solve this?

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/songjingrui/openMVG_Build/third_party/ceres-solver/internal/ceres/openMVG.build/Release/openMVG_ceres.build/Objects-normal/x86_64/wall_time.o /Users/songjingrui/openMVG/src/third_party/ceres-solver/internal/ceres/wall_time.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'openMVG_ceres' from project 'openMVG')
(1 failure)

**Comment by pmoulon** [comment]
Closing due to lack of feedback
