### ISSUE TITLE
why the focal length displayed in the picture information is inconsistent with that in the file?

### ISSUE THREAD

**Issue by wujilingfeng** [openMVG/openMVG#2027]
![Screenshot from 2022-03-14 17-43-17](https://user-images.githubusercontent.com/35684738/158146488-d379ef50-1987-4cf0-ad13-d41b40ed136b.png)
![Screenshot from 2022-03-14 17-44-49](https://user-images.githubusercontent.com/35684738/158146778-9c5d179c-fbc0-4ede-a9f7-c3d801fd22b5.png)
why the focal length displayed in the picture information is inconsistent with that in the file?
Is there a conversion relationship here?

I have some pictures with focal length information such as 9mm, so I don't know how to write it in file.

![Screenshot from 2022-03-14 18-04-14](https://user-images.githubusercontent.com/35684738/158150333-6fd866cf-3a6b-464b-8712-0eb5efaf4710.png)

**Comment by 3XH6R** [comment]
![untitled](https://user-images.githubusercontent.com/32020441/158243495-cf5bd46f-dd37-4a7b-a529-9de34e3f0ed8.png)

**Comment by wujilingfeng** [comment]
Now, I konw the The information recorded in the file is the sensor width, Is there any way to give the sensor width from image info?

**Comment by pmoulon** [comment]
So if you know the sensor width and have a camera name, you can add your camera data to the sensor database.
Else you can compute the focal length in pixel with the formula shared above and directly submit it to SfMInitImageListing with the `-f X` X would be your pixel focal value.

**Comment by pmoulon** [comment]
Closing due to lack of feedback
