### ISSUE TITLE
[spherical sfm] main_ComputeMatches Unrecognized option -g

### ISSUE THREAD

**Issue by wu375** [openMVG/openMVG#2028]
Hi. Thanks for the awesome software. It helps a lot!

So I am trying to follow instructions [here](https://github.com/openMVG/Image_datasets/tree/main/360_dataset) and [here](https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfM.rst) to do sfm on the 360_Flat dataset. But there was some errors: first, the new version of main_ComputeMatches gives **unrecognized option -g**, and second, main_SfM gives **ERROR: [main_SfM.cpp:409] Cannot load the match file.**

Could you provide some instructions on this?

If possible, could you also briefly describe (or paste some links to) the underlying algorithm? Do you convert the spherical images to cubic first and then do sfm? Thanks!

**Comment by pmoulon** [comment]
Hi @wu375 ,
We have update the API a bit with OpenMVG 2.0 and I forgot to update the doc.
You can use the -g option on GeometricFilter.

See [here](https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/SfM_SequentialPipeline.py.in#L66) for a parallel and how to adapt the existing command line.

I will try to update the instructions soon ;-)

**Comment by wu375** [comment]
Thank you!

**Comment by ert485** [comment]
> I will try to update the instructions soon ;-)

Upvote - I ran into this error too 😅
