### ISSUE TITLE
How to build openMVG_control_points_registration without GUI?

### ISSUE THREAD

**Issue by cogitas3d** [openMVG/openMVG#2029]
Dear friends,

I follow a discuss on #1239 and I saw a tutorial called [photogrammetry_example_seashell](https://github.com/edanvoye/photogrammetry_example_seashell) from @edanvoye 

I converted the original Windows code to Linux, but I cannot found the executable "openMVG_control_points_registration" on build directory, only "ui_openMVG_control_points_registration", but the executable do not create the file "sfm_data_aligned.bin", it only open the GUI and do anything more.

I tried to build with GUI option OFF, but after finish to build I didnt saw the "openMVG_control_points_registration".

Is it possible solve this?

**Comment by edanvoye** [comment]
PR #1239 exposed a new executable to call ControlPointsRegistration from the command line, I do not think it was ever merged in the main branch.

**Comment by cogitas3d** [comment]
Solved here:

https://github.com/edanvoye/photogrammetry_example_seashell/issues/1#issuecomment-1074539684
