### ISSUE TITLE
Colorize Structure error when I run py ./SfM_GlobalPipeline.py images matches_global

### ISSUE THREAD

**Issue by 1z2z** [openMVG/openMVG#2034]
D:\OpenMVG\build\software\SfM>py ./SfM_GlobalPipeline.py images matches_global
Using input dir  :  images
      output_dir :  matches_global
1. Intrinsics analysis
INFO: [main_SfMInit_ImageListing.cpp:197]  You called : D:/OpenMVG/build/Windows-AMD64-/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory images
--sensorWidthDatabase D:/OpenMVG/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database\sensor_width_camera_database.txt
--outputDirectory matches_global\matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1
--use_pose_prior 0
--prior_weights 1.0;1.0;1.0
--gps_to_xyz_method 0
INFO: [loggerprogress.hpp:79] [- Listing images -] 100%
INFO: [main_SfMInit_ImageListing.cpp:478] SfMInit_ImageListing report:
listed #File(s): 11
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
INFO: [main_ComputeFeatures.cpp:121]  You called :
D:/OpenMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeFeatures
--input_file matches_global\matches/sfm_data.json
--outdir matches_global\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0

INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 100%
INFO: [main_ComputeFeatures.cpp:344] Task done in (s): 0
3. Compute matching pairs
 You called:
D:/OpenMVG/build/Windows-AMD64-/Release\openMVG_main_PairGenerator
--input_file       : matches_global\matches/sfm_data.json
--output_file      : matches_global\matches/pairs.bin
Optional parameters
--pair_mode        : EXHAUSTIVE
--contiguous_count : -1

Loading scene.Computing pairs.
Saving pairs.
4. Compute matches
INFO: [main_ComputeMatches.cpp:114]  You called :
D:/OpenMVG/build/Windows-AMD64-/Release\openMVG_main_ComputeMatches
--input_file matches_global\matches/sfm_data.json
--output_file matches_global\matches/matches.putative.bin
--pair_list matches_global\matches/pairs.bin
Optional parameters:
--force 0
--ratio 0.8
--nearest_matching_method AUTO
--cache_size unlimited
--preemptive_feature_used/count 0 / 200
INFO: [loggerprogress.hpp:79] [- Regions Loading -] 100%
INFO: [main_ComputeMatches.cpp:217]  - PUTATIVE MATCHES -
INFO: [main_ComputeMatches.cpp:226]      PREVIOUS RESULTS LOADED; #pair: 55
INFO: [main_ComputeMatches.cpp:366] #Putative pairs: 55
INFO: [graph_stats.hpp:53] Graph statistics:
        #nodes: 11
        #cc: 1
        #singleton: 0
        Node degree statistics: min: 10, max: 10, mean: 10, median: 10
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
5. Filter matches
INFO: [main_GeometricFilter.cpp:132]  You called :
D:/OpenMVG/build/Windows-AMD64-/Release\openMVG_main_GeometricFilter
--input_file:        matches_global\matches/sfm_data.json
--matches:           matches_global\matches/matches.putative.bin
--output_file:       matches_global\matches/matches.e.bin
Optional parameters:
--input_pairs
--output_pairs
--force              false
--geometric_model    e
--guided_matching    0
--cache_size         unlimited
INFO: [loggerprogress.hpp:79] [- Regions Loading -] 100%
INFO: [loggerprogress.hpp:79] [- Geometric filtering -] 20%
INFO: [loggerprogress.hpp:79] [- Geometric filtering -] 40%
INFO: [loggerprogress.hpp:79] [- Geometric filtering -] 60%
INFO: [loggerprogress.hpp:79] [- Geometric filtering -] 80%
INFO: [loggerprogress.hpp:79] [- Geometric filtering -] 100%
INFO: [graph_stats.hpp:53] Graph statistics:
        #nodes: 11
        #cc: 1
        #singleton: 0
        Node degree statistics: min: 2, max: 10, mean: 7, median: 8
INFO: [main_GeometricFilter.cpp:384] Task done in (s): 0
INFO: [main_GeometricFilter.cpp:387]
 Export Adjacency Matrix of the pairwise's geometric matches
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
6. Do Global reconstruction
INFO: [main_SfM.cpp:135]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
INFO: [connectedComponent.hpp:99] CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
INFO: [connectedComponent.hpp:118] Connected component of size: 11
INFO: [loggerprogress.hpp:79] [- Relative pose computation -] 30%
INFO: [loggerprogress.hpp:79] [- Relative pose computation -] 40%
INFO: [loggerprogress.hpp:79] [- Relative pose computation -] 60%
INFO: [loggerprogress.hpp:79] [- Relative pose computation -] 70%
INFO: [loggerprogress.hpp:79] [- Relative pose computation -] 100%
INFO: [relative_pose_engine.cpp:224] Relative motion computation took: 307(ms)
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
INFO: [sfm_global_engine_relative_motions.cpp:195]
-------------------------------
 Global rotations computation:
  #relative rotations: 43
  #global rotations: 11
INFO: [GlobalSfM_rotation_averaging.cpp:245] Statistics about rotation triplets:
         min: 0.0977172
         mean: 0.901497
         median: 0.753205
         max: 3.47817
0       |       4
0.174   |       14
0.348   |       13
0.522   |       14
0.696   |       12
0.87    |       11
1.04    |       4
1.22    |       4
1.39    |       6
1.57    |       4
1.74    |       1
1.91    |       4
2.09    |       0
2.26    |       0
2.43    |       1
2.61    |       0
2.78    |       1
2.96    |       1
3.13    |       0
3.3     |       1
3.48

Triplets filtering based on unit cycle rotation composition error:
#Triplets before: 95
#Triplets after: 95
INFO: [GlobalSfM_rotation_averaging.cpp:251]
 #Edges removed by triplet inference: 0
INFO: [connectedComponent.hpp:99] CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
INFO: [connectedComponent.hpp:118] Connected component of size: 11
INFO: [sfm_global_engine_relative_motions.cpp:212] Found #global_rotations: 11
Timing: 0 seconds
INFO: [sfm_global_engine_relative_motions.cpp:241]
Relative/Global degree rotations residual errors {0,1.52079}:
0       |       9
0.076   |       12
0.152   |       9
0.228   |       7
0.304   |       1
0.38    |       3
0.456   |       0
0.532   |       0
0.608   |       0
0.684   |       0
0.76    |       0
0.836   |       0
0.912   |       0
0.989   |       0
1.06    |       0
1.14    |       0
1.22    |       0
1.29    |       0
1.37    |       0
1.44    |       1
1.52

INFO: [sfm_global_engine_relative_motions.cpp:247]
Relative/Global degree rotations residual errors {0,5}:
0       |       32
0.25    |       9
0.5     |       0
0.75    |       0
1       |       0
1.25    |       0
1.5     |       2
1.75    |       0
2       |       0
2.25    |       0
2.5     |       0
2.75    |       0
3       |       0
3.25    |       0
3.5     |       0
3.75    |       0
4       |       0
4.25    |       0
4.5     |       0
4.75    |       0
5

INFO: [sfm_global_engine_relative_motions.cpp:254]
Statistics about global rotation evaluation:
         min: 0.0193012
         mean: 0.231683
         median: 0.157376
         max: 1.52079

'neato' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
INFO: [GlobalSfM_translation_averaging.cpp:305]
-------------------------------
 Relative translations computation:
-------------------------------
INFO: [GlobalSfM_translation_averaging.cpp:364] #Triplets: 95
INFO: [loggerprogress.hpp:79] [Relative translations computation (edge coverage algorithm)] 30%
INFO: [loggerprogress.hpp:79] [Relative translations computation (edge coverage algorithm)] 40%
INFO: [loggerprogress.hpp:79] [Relative translations computation (edge coverage algorithm)] 60%
INFO: [loggerprogress.hpp:79] [Relative translations computation (edge coverage algorithm)] 70%
INFO: [loggerprogress.hpp:79] [Relative translations computation (edge coverage algorithm)] 100%
INFO: [GlobalSfM_translation_averaging.cpp:581] TRIPLET COVERAGE TIMING:
-------------------------------
-- #Relative triplet of translations estimates: 35 computed from 95 triplets.
-- resulting in 105 translations estimation.
-- time to compute triplets of relative translations: 0 seconds.
-------------------------------
INFO: [connectedComponent.hpp:99] CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
INFO: [connectedComponent.hpp:118] Connected component of size: 11
INFO: [GlobalSfM_translation_averaging.cpp:107]
-------------------------------
 Global translations computation:
   - Ready to compute 11 global translations.
     from #relative translations: 105
INFO: [sfm_global_engine_relative_motions.cpp:390]
------------------
-- Tracks Stats --
 Tracks number: 2873
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
------------------
TrackLength, Occurrence
        3       1072
        4       568
        5       374
        6       232
        7       212
        8       176
        9       168
        10      62
        11      9

INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 10%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 20%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 30%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 40%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 50%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 60%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 70%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 80%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 90%
INFO: [loggerprogress.hpp:79] [Blind triangulation progress] 100%
INFO: [sfm_global_engine_relative_motions.cpp:402]
#removed tracks (invalid triangulation): 0
INFO: [sfm_global_engine_relative_motions.cpp:404] Triangulation took (s): 0
INFO: [sfm_data_BA_ceres.cpp:496]
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 2873
 #residuals: 27746
 Initial RMSE: 7.9864
 Final RMSE: 1.84867
 Time (s): 0.307698
--
 Used motion prior: 0
INFO: [sfm_data_BA_ceres.cpp:496]
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 2873
 #residuals: 27746
 Initial RMSE: 1.84867
 Final RMSE: 1.38758
 Time (s): 0.320819
--
 Used motion prior: 0
INFO: [sfm_data_BA_ceres.cpp:496]
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 2873
 #residuals: 27746
 Initial RMSE: 1.38758
 Final RMSE: 1.03114
 Time (s): 0.164119
--
 Used motion prior: 0
INFO: [sfm_global_engine_relative_motions.cpp:488] Outlier removal (remaining #points):
         initial structure size #3DPoints: 2873
                 pixel residual filter  #3DPoints: 2855
                 angular filter         #3DPoints: 2855
INFO: [sfm_data_BA_ceres.cpp:496]
Bundle Adjustment statistics (approximated RMSE):
 #views: 11
 #poses: 11
 #intrinsics: 1
 #tracks: 2850
 #residuals: 27472
 Initial RMSE: 0.351992
 Final RMSE: 0.339942
 Time (s): 0.108165
--
 Used motion prior: 0
INFO: [main_SfM.cpp:549]  Total Sfm took (s): 2
INFO: [main_SfM.cpp:551] ...Generating SfM_Report.html
INFO: [main_SfM.cpp:556] ...Export SfM_Data to disk.
7. Colorize Structure
Wrong JPEG library version: library is 90, caller expects 62
ERROR: [image_io.cpp:142] Error JPG: Failed to decompress.
Wrong JPEG library version: library is 90, caller expects 62
ERROR: [image_io.cpp:142] Error JPG: Failed to decompress.
ERROR: [sfm_data_colorization.cpp:102] Cannot open provided the image.

Can you help me out? thank you very much

**Comment by pmoulon** [comment]
The error you see is "Wrong JPEG library version: library is 90, caller expects 62"
It means that something was wrong at compilation, the compiler used include from a folder different than the one of the object definition.

I would recommend you to force OpenMVG to use an external JPEG build, that can be done by providing the path of JPEG_DIR in the cmake options
