### ISSUE TITLE
Pipeline Options

### ISSUE THREAD

**Issue by tmxftw** [openMVG/openMVG#2035]
Upon review of the cpp files and sequential and global pipeline scripts, I noticed there there are many different options for us to use. I am trying to test the different options to find the best options to use for my project.

I have several questions regarding these options:
1. Force, upright, and cache are options which i do not understand, so I hope that somebody will be able to explain it
2. ComputeMatches.cpp has several nearest_matching_methods for either Scalar based or Binary based region descriptors. I believe that regions are either scalar or binary depending on the option used in ComputeFeatures, which has different describer methods [SIFT, SIFT_ANATOMY, AKAZE_FLOAT, AKAZE_MLDB]. May I know which describer methods returns scalar or binary region descriptors?
3. ComputeMatches.cpp has another option, Pre-emptive matching, I dont understand the significance of this option either.
4. GeometricFilter.cpp has guided_matching which I don't understand either

If anybody could chime in, that would be great!

**Comment by pmoulon** [comment]
Hi @tmxftw 
Thank you for the reminder that we can always do better for documentation.

Please note that we try to document as best as we can new features (I e see preemptive matching here https://github.com/openMVG/openMVG/issues/1661)

See here for a hopefully comprehensive review of OpenMVG image matching pipeline https://www.linkedin.com/posts/pierre-moulon_openmvg-v20-rainbow-trout-is-out-whats-activity-6861444983413714944-16Hm

Regarding descriptors (only akaze mldb is binary as today)

Guided matching:
- retrieve correspondences that are valid according the found geometric model (will samples matches along the epiploar line vs using the entire image) - (I would recommend using this only if you have accurate camera calibration (intrinsics and distortion))

**Comment by tmxftw** [comment]
Hi @pmoulon thanks for the reply! I understand better now. Based on issue #1661 's usage of force, I assume force only has to be flagged as '1' if the function is used again during the pipeline. Could you confirm if my understanding of force is correct?

Also, with regards to preemptive matching, in #1661, the following code was used.
```
1. Pre-emptive matching (pair selection)
$ openMVG_main_ComputeMatches
 -i <PATH/matches/sfm_data.json> -o  <PATH/matches>
 -P
 -n BRUTEFORCEL2
 --preemptive_feature_count 100
 -g M

2. Matching on the pre-emptive selected pairs
$ openMVG_main_ComputeMatches
 -i <PATH/matches/sfm_data.json> -o  <PATH/matches>
 --pair_list <PATH/matches/pairs.txt>
 -f 1
```
Should -P be flagged without anything after it? or will the following code achieve the same outcome? Where I simply shifted 100, the number of preemptive feature counts to after -P, and substituting "--pair_list" to "-p" in the second part of the code.

```
1. Pre-emptive matching (pair selection)
$ openMVG_main_ComputeMatches
 -i <PATH/matches/sfm_data.json> -o  <PATH/matches>
 -P 100
 -n BRUTEFORCEL2
 -g M

2. Matching on the pre-emptive selected pairs
$ openMVG_main_ComputeMatches
 -i <PATH/matches/sfm_data.json> -o  <PATH/matches>
 -p <PATH/matches/pairs.txt>
 -f 1
```

**Comment by pmoulon** [comment]
Yes P should be postfixed with a number of features.
See here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeMatches.cpp#L69
