### ISSUE TITLE
OpenBLAS warning when using OpenMP.

### ISSUE THREAD

**Issue by Airplane5** [openMVG/openMVG#2037]
I am trying to use openMP to BA parallely. There is an repeated warning when running.
The warning:
`
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
`
code below
SubGraphBA equals Adjust() in sfm_data_ba_ceres.cpp, which builds the ba problem and solves it.
`
if(Ceres_options_.bMultiThread_)
        {
            std::cout<<"[Sub graph BA] Multi-thread.\n";
            omp_set_num_threads(Ceres_options_.nb_threads_);
        #pragma omp parallel
            for(int i=0;i<vSfMData.size();i++)
            {
                SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
            } 
        }
        else
        {
            std::cout<<"[Sub graph BA] Mono-thread.\n";
            for(int i=0;i<vSfMData.size();i++)
            {
                SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
            }         
        }
`

I tried following indication in warning, rebuilding OpenBLAS with `make USE_OPENMP=1` and rebuilded eigen too. But warning still exists.

What should I do to prevent this warning?

**Comment by Airplane5** [comment]
`
if(Ceres_options_.bMultiThread_)
{
    std::cout<<"[Sub graph BA] Multi-thread.\n";
    omp_set_num_threads(Ceres_options_.nb_threads_);
#pragma omp parallel
    for(int i=0;i<vSfMData.size();i++)
    {
        SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
    } // end for sub-graph BA
}
`

**Comment by Airplane5** [comment]
if(Ceres_options_.bMultiThread_)
{
    std::cout<<"[Sub graph BA] Multi-thread.\n";
    omp_set_num_threads(Ceres_options_.nb_threads_);
#pragma omp parallel
    for(int i=0;i<vSfMData.size();i++)
    {
        SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
    } // end for sub-graph BA
}

**Comment by Airplane5** [comment]
if(Ceres_options_.bMultiThread_)
{
    std::cout<<"[Sub graph BA] Multi-thread.\n";
    omp_set_num_threads(Ceres_options_.nb_threads_);
#pragma omp parallel
    for(int i=0;i<vSfMData.size();i++)
    {
        SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
    } // end for sub-graph BA
}

**Comment by Airplane5** [comment]
if(Ceres_options_.bMultiThread_)
{
    std::cout<<"[Sub graph BA] Multi-thread.\n";
    omp_set_num_threads(Ceres_options_.nb_threads_);
#pragma omp parallel
    for(int i=0;i<vSfMData.size();i++)
    {
        SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
    } // end for sub-graph BA
}

**Comment by Airplane5** [comment]
```
if(Ceres_options_.bMultiThread_)
    {
        std::cout<<"[Sub graph BA] Multi-thread.\n";
        omp_set_num_threads(Ceres_options_.nb_threads_);
    #pragma omp parallel
        for(int i=0;i<vSfMData.size();i++)
        {
            SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
        } 
    }
    else
    {
        std::cout<<"[Sub graph BA] Mono-thread.\n";
        for(int i=0;i<vSfMData.size();i++)
        {
            SubGraphBA(&vSfMData[i],options,i,costFunctionv[i],solutionv[i],vError[i]);
        }          
    }
```

**Comment by Airplane5** [comment]
```
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
```

**Comment by Airplane5** [comment]
Last night, I found all 8 cpus are fully operated, but program still runs a long time with repeated warning and it doesn't stop now.
BTW, I am testing the program with BAL-final-1936 data, the initial rmse is 80 which I think it's incredible.
I want to know if the initial rmse value reasonable?

**Comment by pmoulon** [comment]
Could be due to nested parallelization.
I'm not sure if you want run multiple BA in parallel or if you want one BA to run faster,
If it is the later, perhaps the best would be to ask the ceres community.
If it is the first one, I would set ceres to run on one thread, and run multiple BA in parallel

**Comment by Airplane5** [comment]
Sorry to bother you for such a easy problem.
I found the cause but forget to add reply. It's just as what  your reply said.
Thank you so much!

**Comment by pmoulon** [comment]
Thank you for your reply ;-) Happy that you found a solution to your problem
