### ISSUE TITLE
Understanding the meaning of ResidualsMSE in the terminal

### ISSUE THREAD

**Issue by whistlefancy** [openMVG/openMVG#2039]
Thanks for such an excellent open source project like openMVG, but as a beginner I have a question: what does ResidualsMSE in the terminal and SfM Scene RMSE in the SFM report represent respectively? Which is the reprojection error of SFM? Looking forward to a reply, thank you.
![image](https://user-images.githubusercontent.com/73679440/161373921-1a7ab4a9-86d8-439f-8cbd-847c0467ed1f.png)

![image](https://user-images.githubusercontent.com/73679440/161374030-23c9311f-bc73-4706-9890-e22d2be914e4.png)

**Comment by pmoulon** [comment]
RMSE -> Root Mean Square Error -< in our case we are looking to the residual value (distance between the image observation and the projection of the 3D points)
Residual error is expressed as ||x - P(X)||
RMSE -> https://www.statisticshowto.com/probability-and-statistics/regression-analysis/rmse-root-mean-square-error/

**Comment by EC2049** [comment]
Sorry for reopening a closed post but, why is the RMSE value in the terminal output different from that on the generated report?
