### ISSUE TITLE
Poor Correspondence By openMVG_main_exportMatches

### ISSUE THREAD

**Issue by FishWoWater** [openMVG/openMVG#2042]
Hi! Thanks for your nice project and it helps me a lot !

I have one question when exporting the matches correspondence 

I just run `python SfM_SequentialPipeline.py images out` on my custom dataset

use `openMVG_main_exportKeypoints -i sfm_data.bin -o keypoints -d ../matches` to export keypoints 

use `openMVG_main_exportMatches -i sfm_data.bin -o matches -d ../matches -m ../matches/preemptive_pairs.txt` to export matches

It seems the extracted features are ok and final colorized pointcloud is good as well 

![image](https://user-images.githubusercontent.com/37951601/161685953-e5348e25-100d-4fef-a044-235585863ee7.png)

![image](https://user-images.githubusercontent.com/37951601/161686038-68317d6a-634a-4a63-aef0-19ecb11085f7.png)

but the exported matches are quite strange (few matches and incorrect matches)
![image](https://user-images.githubusercontent.com/37951601/161686166-9efdcaeb-3a78-411a-ad47-cf580ff45ac3.png)

I am not sure whether I use the `exportMatches` command correctly or is there anything wrong elsewhere

Appreciate if you could help me :)

**Comment by 3XH6R** [comment]
openMVG_main_exportMatches `-m matches.f.bin`
use the output from openMVG_main_GeometricFilter

**Comment by FishWoWater** [comment]
@3XH6R Thanks, it works.

**Comment by pmoulon** [comment]
@FishWoWater FYI, you submitted a pair file and not a match file.

**Comment by FishWoWater** [comment]
@pmoulon 
Hi~   If I know as a prior which two images will have good matches, how can I specify this? It seems that `--pair_list` in `computeMatches` can do this.  

Besides, if my dataset contains two subsets of images, which are captured from the oppsite views (one view is behind the object, and  the other one is in front of the object, the two views have no overlap but they look similar in terms of the appearance), can I reconstruct the two parts separately and merge them into one point cloud later? 

Thanks for your help, wish you a good day :)

**Comment by pmoulon** [comment]
Hello @FishWoWater ,
Yes pair_list is a good way to send images you know that should match and also ignore try to match some that you know should not overlap.

For the moment we don't have a process to merge reconstruction that shares some similar views, but it should be doable with not too much programming.

**Comment by FishWoWater** [comment]
Thanks for your help

**Comment by pmoulon** [comment]
SVG files can be previewed in Chrome (Just change the zoom if the image are too big)
Else you can open it in Inkscape (We use SVG export so you can zoom and keep vectorial graphics to see the keypoint location and matches points)

**Comment by lzn1273180880** [comment]
@pmoulon 
Yeah, I see. I just have to modify the `href` tag to use my local images since I copy it from my cloud server.
Thank you!

**Comment by pmoulon** [comment]
Sure always happy to help!

**Comment by Z-Jeff** [comment]
The correct usage is 
`openMVG_main_exportMatches -i sfm_data.bin -o matches -d ../matches -m ../matches/matches.f.bin`
Here is my visulization:

![2022-11-27 21-08-53屏幕截图](https://user-images.githubusercontent.com/30492923/204137001-f52c3787-6500-4300-bfe0-a977c5582d29.png)
