### ISSUE TITLE
Probably bug in src/openMVG/spherical/image_resampling.hpp

### ISSUE THREAD

**Issue by borsh** [openMVG/openMVG#2044]
Line 86:   pinhole_images.resize(6);
Line 88:   for (int i_rot = 0; i_rot < rotations.size(); ++i_rot)
Line 90:     pinhole_images[i_rot] = SphericalToPinhole(

Probably rotations.size() may be greater than 6 ?

Also in src/openMVG_Samples/image_spherical_to_pinholes/main_pano_converter.cpp

Line 115: const openMVG::cameras::Pinhole_Intrinsic pinhole_camera = spherical::ComputeCubicCameraIntrinsics(image_resolution);

Probably forgot to pass fov as a second parameter

**Comment by pmoulon** [comment]
Thank you for your feedback, those point are not issue in the actual code but can be good to update for better genericity.

A. 
`spherical/image_resampling.hpp `
line86 can be changed to `pinhole_images.resize(rotations.size());`

B. 
`main_pano_converter.cpp`
line 115 -> Fov is used in the current develop branch -> https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG_Samples/image_spherical_to_pinholes/main_pano_converter.cpp#L114

Feel free to make a PR to fix the possible bug in A. if the API is used a bit differently than today.

**Comment by pmoulon** [comment]
Made  commit to fix this here 63f52b1204b6329b615c38c54776a2e818c95510
