### ISSUE TITLE
file cannot create directory: /eigen3/Eigen.

### ISSUE THREAD

**Issue by lakshjsn** [openMVG/openMVG#2045]
After executing the command : cmake --build . --target install, the following question arises

CMake Error at third_party/eigen/Eigen/cmake_install.cmake:49 (file):
  file cannot create directory: /eigen3/Eigen.  Maybe need administrative
  privileges.

May I ask how to solve this problem

**Comment by pmoulon** [comment]
DId you try prefix with sudo?

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen.

**Comment by pengxutao** [comment]
hello, I encountered the same problem as you, did you solve it?

**Comment by pmoulon** [comment]
Seems like your sudo did not work since it says you still does not have administrative privilege.
