### ISSUE TITLE
ComputeStructureFromKnownPoses | bundle_adjustment and SFM report

### ISSUE THREAD

**Issue by 3XH6R** [openMVG/openMVG#2047]
Context:
Downscaled images> ran to end of SfM> converted data format to json> feature extraction of full res images> copied poses from downscaled to full res sfm_data.json> ran ComputeStructureFromKnownPoses mode A with f and b.

For some scenes the output looks fine but on others it's either empty or loses most of the cameras.
Increasing the residual_threshold to 100+ starts bringing back some cameras but increases processing time.

The SFM report exported doesn't correctly display the reconstructed poses and has very low observations.

Dataset: [Airport taken by senseFly](https://www.sensefly.com/education/datasets/?dataset=1422)

<details><summary>Without BA</summary>

![image](https://user-images.githubusercontent.com/32020441/163079464-29c70c55-0e47-4168-a9d5-2afefdeb484d.png)
</details>
<details><summary>With BA</summary>

![image](https://user-images.githubusercontent.com/32020441/163080133-40109fbe-e697-4495-8b5f-1fdc4ee79338.png)
</details>
<details><summary>Downscaled cloud and poses</summary>

![image](https://user-images.githubusercontent.com/32020441/163079876-1049fb20-8a60-4db1-bc7e-54ee018acd5d.png)
</details>

```Batch
@echo off
pwsh "C:\Users\3XH6R\Documents\powershell scripts\downscale.ps1" %1 0.25 16
"C:\Users\3XH6R\Documents\Photogrammetry\MvgMvsPipeline.py" %1\downscaled %1\downscaled --1 p NORMAL --steps 0 1 2 3 4 6 5
"C:\Users\3XH6R\Documents\Photogrammetry\MvgMvsPipeline.py" %1 %1 --1 p NORMAL --steps 0 1
openMVG_main_ConvertSfM_DataFormat -i %1\downscaled\sfm\sfm_data.bin -o %1\downscaled\sfm\sfm_data.json -E
pwsh "C:\Users\3XH6R\Documents\powershell scripts\sfm_data_poses.ps1" %1
openMVG_main_ComputeStructureFromKnownPoses -i %1\sfm\matches\sfm_data.json -m %1\sfm\matches -o %1\sfm\sfm_data.bin -f %1\downscaled\sfm\matches\matches.e.bin -b
```

**Comment by pmoulon** [comment]
If you run with different image size you need to scale also the intrinsic camera parameters (in your case scale the focal and principal points) so the projection will remain correct.

**Comment by 3XH6R** [comment]
Changed the HighRes(left) focal_length and principal_point to the LowRes(right), the scene is empty.
Also tried disto_k3, width, and height.
![image](https://user-images.githubusercontent.com/32020441/163110734-1c43d729-95d0-4ef9-bfbb-04c147e49cda.png)

**Comment by 3XH6R** [comment]
It's working now with the scale, though some cameras were lost.
554/557 -> 545/557
Next thing is figuring out how to iterate through all intrinsics and separating principal_point values.
Though it would be easier for users to input an optional scale factor into ComputeStructureFromKnownPoses.

**Comment by pmoulon** [comment]
Please @3XH6R do not change the Title or Initial message after the fact since our user will not be able to understand in the discussion thread...
