### ISSUE TITLE
Are there any other speed combinations for general datasets?

### ISSUE THREAD

**Issue by 3XH6R** [openMVG/openMVG#2048]
Apart from:
- Masking images
- Threads in ComputeFeatures
- Limited pairs using VLAD to speed up matching and SfM
- HNSWL2 for robustness and speed
- GLOBAL SfM for a fast start followed by INCREMENTALV2 SfM to resolve remaining poses
- ComputeStructureFromKnownPoses using downscaled SfM and high res features with bundle adjustment for general speed up

Using half of the dataset then adding in the rest?
Using INCREMENTALV2 EXISTING_POSE  instead of ComputeStructureFromKnownPoses?

**Comment by pmoulon** [comment]
Please @3XH6R do not change the Title or Initial message after the fact since our user will not be able to understand in the discussion thread...
