### ISSUE TITLE
Colorized PointCloud

### ISSUE THREAD

**Issue by fcastan** [openMVG/openMVG#205]
In main_IncrementalSfM, the PointCloud is no more colorized by default.
"[-c|--coloredPointCloud 0(default) or 1]\n"

Is there a good reason to disable it? IMO, it's better to add all information by default.

**Comment by pmoulon** [comment]
Now SfM always produce uncolored point cloud.
Output can be colored thanks to https://github.com/openMVG/openMVG/issues/264
