### ISSUE TITLE
Why arc sine is used in AngularError computation instead of arc cosine? 

### ISSUE THREAD

**Issue by navid-mahmoudian** [openMVG/openMVG#2058]
Hello,

First of all, thank you very much for providing this very useful library.

I was checking your code for the computation of essential matrix using bearing vectors, and I noticed that in file the  [solver_essential_eight_point.cpp](https://github.com/openMVG/openMVG/blob/5e98d504bb76ba2d1d07ae80ac2acb10b3d6f97d/src/openMVG/multiview/solver_essential_eight_point.cpp), when you want to compute the AnglarError, you are using std::asin function instead of arc cosine. To be more precise, when you are computing
 `const double angleVal = (x2.transpose() * Em1);`
Here, I guess you are computing the inner product between the two vectors, which is equivalent to the cosine of the angle between the two vectors. So, it is not clear to me, why in the **next line** `std::asin` is used to compute the angle?
`return std::abs(std::asin(angleVal));`

**Comment by pmoulon** [comment]
Hello @navid-mahmoudian It is most likely perhaps a mistake, as you can see here https://pastel.archives-ouvertes.fr/tel-00996935v2/document on page 80 for the formula (4.21), indeed I cited acos.
Can you try fix this in the code and make some test regarding the behavior?

**Comment by rjanvier** [comment]
I think it's perfectly fine to use arcsin. Here, it's the angulat epipolar error, not the angular reprojection error. For full reference see [Pagani et al. 2011 sec. 2.2.2](http://alain.pagani.free.fr/papers/Pagani2011_OMNIVIS.pdf)
