### ISSUE TITLE
HELP!!! openMVG2openMVS.cpp ERROR!

### ISSUE THREAD

**Issue by lzn1273180880** [openMVG/openMVG#2059]
Hello, I'm using OpenMVG compiled in Ubuntu 20.04, everything works fine until the last step.
I received error like this:
`ERROR: [main_openMVG2openMVS.cpp:50] Cannot access to one of the desired output directory`
`ERROR: [main_openMVG2openMVS.cpp:300] The output openMVS scene file cannot be written`
I don't know how to solve it, I tried to use `sudo` when I'm compiling OpenMVG but it didn't work.
A little bit hurry, looking forward to your reply.
Thank you so much.

**Comment by lzn1273180880** [comment]
Every files have been written into the directory I specified except the `scene.mvs` :(

**Comment by 3XH6R** [comment]
What's the command you're using?

**Comment by lzn1273180880** [comment]
![2022-05-05 16-28-00屏幕截图](https://user-images.githubusercontent.com/94612909/166887889-2f7b74f1-4f05-467b-a2fd-6449ec446254.png)
These are all the generated files but the `scene.mvs` is not included, I'm so confused.

**Comment by lzn1273180880** [comment]
problem solved, but another problem occurred when doing openMVS.
![1](https://user-images.githubusercontent.com/94612909/166890118-47b2f20b-7f74-4b21-9411-e9729c971e9c.png)
do you have any solution about it?

**Comment by pmoulon** [comment]
What do you use the `../` in the path, why dont you directly use the direct path as scene/openMVS/scene.mvs
This error show that OpenMVG can't open your images because he expect some images to tbe on disk at RELEASE/....

**Comment by lzn1273180880** [comment]
Thank you.
I wrote a python script to help me run openMVG and openMVS automatically, so I use relative path instead of absolute path. I'm sure that images dataset and `scene.mvs` are in the same directory.
This python script runs well in another Linux system but I have no idea why it cannot run well in this Linux system. It's a brand new system without any other environment and I completely followed the `build` guidance.

**Comment by lzn1273180880** [comment]
Im curious about the error `failed loading image header`, I never meet this before.

**Comment by pmoulon** [comment]
I pretty sure the code display this message because openMVS expect to see some files at a different location

**Comment by lzn1273180880** [comment]
Yeah, I think so.
OpenMVS was supposed to find `undistorted_images`  in the same directory as `scene.mvs` like this but it didn't, Im not sure how to solve it. Should I specify the path manually?
![54ac869ae563b0771d18bf46fcf0aee](https://user-images.githubusercontent.com/94612909/167054349-0577ffc6-8c58-485a-b0f6-c65c00347c28.jpg)

**Comment by lzn1273180880** [comment]
Thanks for replying to me.
Problem solved by reinstalling the whole system...I used a newer ubuntu22.04 to build openMVG and openMVS and finally nothing went wrong.

**Comment by anasel01** [comment]
> problem solved, but another problem occurred when doing openMVS. ![1](https://user-images.githubusercontent.com/94612909/166890118-47b2f20b-7f74-4b21-9411-e9729c971e9c.png) do you have any solution about it?
plz how did you solved the problem : ERROR: [main_openMVG2openMVS.cpp:367] The output openMVS scene file cannot be written
