### ISSUE TITLE
Global SfM | Linear global translation (LiGT) did not reconstruct a dataset correctly

### ISSUE THREAD

**Issue by 3XH6R** [openMVG/openMVG#2066]
Testing its current state with some of the datasets I had, it ran into an issue processing a downscaled dataset of a komainu statue.
Used VLAD limited to 10 pairs, guided matching, and high feature extraction.
1040 images at 1620x1080/1080x1620

Dataset: https://www.mediafire.com/file/kjy28tcpt8fm5k2/japan_statue_downscaled.7z/file from RealityCapture site
Built from https://github.com/pose-only-vision/openMVG commit a9995e575b4ef31a903faca29f903054830a29b3
![LiGT](https://user-images.githubusercontent.com/32020441/168520503-edf666eb-5c72-41ee-92a4-c71e6069e00e.png)
![SAM_0989_GPR](https://user-images.githubusercontent.com/32020441/168521121-314fc7e8-439a-4cbd-bf55-330c21126a66.jpg)

**Comment by 3XH6R** [comment]
![Screenshot 2022-05-15 at 22-25-49 SFM report](https://user-images.githubusercontent.com/32020441/168525148-40074017-ca06-4eea-858e-a20ae167e489.png)

**Comment by 3XH6R** [comment]
1040 images at 6480x4320/4320x6480 | Normal feature extraction and Vlad n 6
Reconstructed correctly

**Comment by pmoulon** [comment]
Thank you for testing @3XH6R
The columns issue is often due to a visualization artifact or export with two less precision (do you open the files on Meshlab or CloudCompare) -- it happens sometimes when the scene is very small after BA?

What does `G:1022 -> Iv2:1040` represents?

**Comment by 3XH6R** [comment]
I use Meshlab for quick viewing. Yea, it happens when the coordinates are either too large or small after SfM processing with and without BA.
GLOBAL, INCREMENTALV2, and poses reconstructed.

**Comment by pmoulon** [comment]
Thank you for early testing the feature and confirming that it worked on your dataset.
Some other interesting updates will come soon. stay tuned ;-)
