### ISSUE TITLE
why the sfm_data.bin can not be read

### ISSUE THREAD

**Issue by lzl050** [openMVG/openMVG#2069]
PS D:\3d\openMVG> ./openMVG_main_ComputeSfM_DataColor.exe -i D:\3d\build\reconstrution\sfm_data.bin -o  D:\3d\build\colored.ply

The input SfM_Data file "D:\3d\build\reconstrution\sfm_data.bin" cannot be read.

**Comment by pmoulon** [comment]
Sorry we can't really help you if you don't provide more information, such as the error message you have in debug mode, or you sfm_data.bin file
