### ISSUE TITLE
Split main_computeMatches

### ISSUE THREAD

**Issue by fabiencastan** [openMVG/openMVG#207]
We are working to allow the split of the matching step in multiple commands.
We would like to generate multiple files instead of the global "matches.*.txt". The idea is to generate one file per image containing the matching with all other images (with a bigger lexicographic order).

The goal is to allow to compute that step on multiple computers in parallel.

**Comment by pmoulon** [comment]
Thanks to the Matches_Provider abstract class you can now manage the matches in the way you want.
I mean you can write your MultipleFiles_Matches_Provider, that will read your matches.X.txt files and concat them in a single PairwiseMatches object.
