### ISSUE TITLE
Build Error with latest Repo

### ISSUE THREAD

**Issue by Moj-Dev** [openMVG/openMVG#2072]
Here is the error I got after building the latest repository. I'd appreciate it if any could help on this.

[  0%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinAlloc.cpp.o
[  1%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinBuild.cpp.o
[  1%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinDenseFactorization.cpp.o
[  1%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinDenseVector.cpp.o
[  1%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinError.cpp.o
[  2%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFactorization1.cpp.o
[  2%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFactorization2.cpp.o
[  2%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFactorization3.cpp.o
[  3%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFactorization4.cpp.o
[  3%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFileIO.cpp.o
[  3%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinFinite.cpp.o
[  3%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinIndexedVector.cpp.o
[  4%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinLpIO.cpp.o
[  4%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinMessage.cpp.o
[  4%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinMessageHandler.cpp.o
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinMessageHandler.cpp: In member function ‘CoinMessageHandler& CoinMessageHandler::operator<<(double)’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinMessageHandler.cpp:834:35: warning: format not a string literal and no format arguments [-Wformat-security]
      sprintf(messageOut_,format_+2);
                                   ^
[  5%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinModel.cpp.o
[  5%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinModelUseful.cpp.o
[  5%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinModelUseful2.cpp.o
[  5%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinMpsIO.cpp.o
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinMpsIO.cpp: In member function ‘int CoinMpsIO::readConicMps(const char*, int*&, int*&, int*&, int&)’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinMpsIO.cpp:5814:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if ( cardReader_->whichSection (  ) == COIN_NAME_SECTION )
   ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinMpsIO.cpp:5816:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     if ( cardReader_->whichSection (  ) == COIN_CONIC_SECTION ) {
     ^~
[  6%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinOslFactorization.cpp.o
[  6%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinOslFactorization2.cpp.o
[  6%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinOslFactorization3.cpp.o
[  7%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPackedMatrix.cpp.o
[  7%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPackedVector.cpp.o
[  7%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPackedVectorBase.cpp.o
[  7%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinParam.cpp.o
[  8%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinParamUtils.cpp.o
[  8%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPostsolveMatrix.cpp.o
[  8%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPrePostsolveMatrix.cpp.o
[  9%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveDoubleton.cpp.o
[  9%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveDual.cpp.o
[  9%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveDupcol.cpp.o
[  9%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveEmpty.cpp.o
[ 10%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveFixed.cpp.o
[ 10%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveForcing.cpp.o
[ 10%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveHelperFunctions.cpp.o
[ 11%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveImpliedFree.cpp.o
[ 11%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveIsolated.cpp.o
[ 11%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveMatrix.cpp.o
[ 11%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveMonitor.cpp.o
[ 12%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolvePsdebug.cpp.o
[ 12%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveSingleton.cpp.o
[ 12%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveSubst.cpp.o
[ 13%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveTighten.cpp.o
[ 13%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveTripleton.cpp.o
[ 13%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveUseless.cpp.o
[ 13%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinPresolveZeros.cpp.o
[ 14%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinRational.cpp.o
[ 14%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinSearchTree.cpp.o
[ 14%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinShallowPackedVector.cpp.o
[ 15%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinSimpFactorization.cpp.o
[ 15%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinSnapshot.cpp.o
[ 15%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinStructuredModel.cpp.o
[ 15%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinWarmStartBasis.cpp.o
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinWarmStartBasis.cpp: In member function ‘bool CoinWarmStartBasis::fixFullBasis()’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinWarmStartBasis.cpp:494:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
       if (status==CoinWarmStartBasis::basic)
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinWarmStartBasis.cpp:496:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  numberBasic--;
  ^~~~~~~~~~~
[ 16%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinWarmStartDual.cpp.o
[ 16%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinWarmStartPrimalDual.cpp.o
[ 16%] Building CXX object dependencies/osi_clp/CoinUtils/src/CMakeFiles/lib_CoinUtils.dir/CoinWarmStartVector.cpp.o
[ 17%] Linking CXX static library ../../../../Linux-x86_64-RELEASE/liblib_CoinUtils.a
[ 17%] Built target lib_CoinUtils
[ 17%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiAuxInfo.cpp.o
[ 17%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiBranchingObject.cpp.o
[ 17%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiChooseVariable.cpp.o
[ 18%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiColCut.cpp.o
In file included from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.cpp:10:0:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp: In member function ‘virtual bool OsiColCut::infeasible(const OsiSolverInterface&) const’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:304:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutUbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:306:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newLb > newUb )
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:315:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutLbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:317:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newUb < newLb )
       ^~
[ 18%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiCut.cpp.o
[ 18%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiCuts.cpp.o
In file included from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiCuts.hpp:14:0,
                 from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiCuts.cpp:13:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp: In member function ‘virtual bool OsiColCut::infeasible(const OsiSolverInterface&) const’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:304:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutUbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:306:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newLb > newUb )
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:315:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutLbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:317:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newUb < newLb )
       ^~
[ 19%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiNames.cpp.o
[ 19%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiPresolve.cpp.o
[ 19%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiRowCut.cpp.o
[ 19%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiRowCutDebugger.cpp.o
In file included from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiCuts.hpp:14:0,
                 from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiRowCutDebugger.hpp:16,
                 from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiRowCutDebugger.cpp:19:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp: In member function ‘virtual bool OsiColCut::infeasible(const OsiSolverInterface&) const’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:304:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutUbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:306:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newLb > newUb )
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:315:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutLbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:317:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newUb < newLb )
       ^~
[ 20%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiSolverBranch.cpp.o
[ 20%] Building CXX object dependencies/osi_clp/Osi/src/Osi/CMakeFiles/lib_Osi.dir/OsiSolverInterface.cpp.o
In file included from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiCuts.hpp:14:0,
                 from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiSolverInterface.cpp:21:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp: In member function ‘virtual bool OsiColCut::infeasible(const OsiSolverInterface&) const’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:304:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutUbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:306:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newLb > newUb )
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:315:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutLbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Osi/src/Osi/OsiColCut.hpp:317:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newUb < newLb )
       ^~
[ 20%] Linking CXX static library ../../../../../Linux-x86_64-RELEASE/liblib_Osi.a
[ 20%] Built target lib_Osi
[ 20%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/CbcOrClpParam.cpp.o
[ 20%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpCholeskyBase.cpp.o
[ 21%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpCholeskyDense.cpp.o
[ 21%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpCholeskyTaucs.cpp.o
[ 21%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpConstraint.cpp.o
[ 22%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpConstraintLinear.cpp.o
[ 22%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpConstraintQuadratic.cpp.o
[ 22%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDualRowDantzig.cpp.o
[ 22%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDualRowPivot.cpp.o
[ 23%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDualRowSteepest.cpp.o
[ 23%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDummyMatrix.cpp.o
[ 23%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDynamicExampleMatrix.cpp.o
[ 24%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpDynamicMatrix.cpp.o
[ 24%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpEventHandler.cpp.o
[ 24%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpFactorization.cpp.o
[ 24%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpGubDynamicMatrix.cpp.o
[ 25%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpGubMatrix.cpp.o
[ 25%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpHelperFunctions.cpp.o
[ 25%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpInterior.cpp.o
[ 26%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpLinearObjective.cpp.o
[ 26%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpLsqr.cpp.o
[ 26%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpMatrixBase.cpp.o
[ 26%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpMessage.cpp.o
[ 27%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpModel.cpp.o
[ 27%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpNetworkBasis.cpp.o
[ 27%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpNetworkMatrix.cpp.o
[ 28%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpNode.cpp.o
[ 28%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpNonLinearCost.cpp.o
[ 28%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpObjective.cpp.o
[ 28%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPackedMatrix.cpp.o
[ 29%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPdco.cpp.o
[ 29%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPdcoBase.cpp.o
[ 29%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPlusMinusOneMatrix.cpp.o
[ 30%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPredictorCorrector.cpp.o
[ 30%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPresolve.cpp.o
[ 30%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPrimalColumnDantzig.cpp.o
[ 30%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPrimalColumnPivot.cpp.o
[ 31%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpPrimalColumnSteepest.cpp.o
[ 31%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpQuadraticObjective.cpp.o
[ 31%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSimplex.cpp.o
[ 32%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSimplexDual.cpp.o
[ 32%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSimplexNonlinear.cpp.o
[ 32%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSimplexOther.cpp.o
[ 32%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSimplexPrimal.cpp.o
[ 33%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/ClpSolve.cpp.o
[ 33%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/Clp_C_Interface.cpp.o
[ 33%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/IdiSolve.cpp.o
[ 34%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/Idiot.cpp.o
[ 34%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/MyEventHandler.cpp.o
[ 34%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/MyMessageHandler.cpp.o
[ 34%] Building CXX object dependencies/osi_clp/Clp/src/CMakeFiles/lib_clp.dir/unitTest.cpp.o
[ 35%] Linking CXX static library ../../../../Linux-x86_64-RELEASE/liblib_clp.a
[ 35%] Built target lib_clp
[ 36%] Building CXX object dependencies/osi_clp/Clp/src/OsiClp/CMakeFiles/lib_OsiClpSolver.dir/OsiClpSolverInterface.cpp.o
In file included from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiCuts.hpp:14:0,
                 from /home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/Clp/src/OsiClp/OsiClpSolverInterface.cpp:33:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiColCut.hpp: In member function ‘virtual bool OsiColCut::infeasible(const OsiSolverInterface&) const’:
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiColCut.hpp:304:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutUbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiColCut.hpp:306:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newLb > newUb )
       ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiColCut.hpp:315:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ( cutLbs.isExistingIndex(colIndx) )
     ^~
/home/mojtaba/3DReconstruction/openMVG/src/dependencies/osi_clp/./Osi/src/Osi/OsiColCut.hpp:317:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       if ( newUb < newLb )
       ^~
[ 36%] Linking CXX static library ../../../../../Linux-x86_64-RELEASE/liblib_OsiClpSolver.a
[ 36%] Built target lib_OsiClpSolver
[ 37%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/file_system.cpp.o
[ 37%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/portability_fixes.cpp.o
[ 37%] Building CXX object third_party/stlplus3/CMakeFiles/openMVG_stlplus.dir/filesystemSimplified/wildcard.cpp.o
[ 37%] Linking CXX static library ../../Linux-x86_64-RELEASE/libopenMVG_stlplus.a
[ 37%] Built target openMVG_stlplus
[ 37%] Building CXX object third_party/vectorGraphics/CMakeFiles/main_svgSample.dir/main.cpp.o
[ 37%] Linking CXX executable ../../Linux-x86_64-RELEASE/main_svgSample
CMakeFiles/main_svgSample.dir/main.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) [clone .isra.45]':
main.cpp:(.text+0x83): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
main.cpp:(.text+0xb4): undefined reference to `std::__throw_logic_error(char const*)'
CMakeFiles/main_svgSample.dir/main.cpp.o: In function `svg::svgDrawer::drawText(float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:
.
.
.

.
.
.
main.cpp:(.text.startup+0x160e): undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text.startup+0x1615): undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text.startup+0x162f): undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >'
main.cpp:(.text.startup+0x163f): undefined reference to `std::ios_base::~ios_base()'
CMakeFiles/main_svgSample.dir/main.cpp.o: In function `_GLOBAL__sub_I_main':
main.cpp:(.text.startup+0x167c): undefined reference to `std::ios_base::Init::Init()'
main.cpp:(.text.startup+0x1683): undefined reference to `std::ios_base::Init::~Init()'
CMakeFiles/main_svgSample.dir/main.cpp.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
third_party/vectorGraphics/CMakeFiles/main_svgSample.dir/build.make:96: recipe for target 'Linux-x86_64-RELEASE/main_svgSample' failed
make[2]: *** [Linux-x86_64-RELEASE/main_svgSample] Error 1
CMakeFiles/Makefile2:1528: recipe for target 'third_party/vectorGraphics/CMakeFiles/main_svgSample.dir/all' failed
make[1]: *** [third_party/vectorGraphics/CMakeFiles/main_svgSample.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pmoulon** [comment]
What is your compiler? Cmake configure step should say it to you. It looks like here some C++11 stuff is not found

**Comment by Moj-Dev** [comment]
g++ (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by pmoulon** [comment]
Can you compile without compiling samples, else can you update your compiler?
We are using 9.4.0 on Github Actions

**Comment by Moj-Dev** [comment]
I've updated to version 9.4.0 and the problem is solved. Thanks.
