### ISSUE TITLE
360 video openMVG and openMVS SfM [ERROR]

### ISSUE THREAD

**Issue by MeUsushi** [openMVG/openMVG#2082]
Hi
i am trying to Sfm from 360 video (11K) in windows10.
I prepare 25 picutures named [img_001t.jpg] [img_002t.jpg] .....[img_025t.jpg]
then I Refer to [https://github.com/openMVG/Image_datasets/tree/main/360_dataset]

I cannot get good result
cmd said
```
C:\SfmTest\360\Image_datasets_2nd\360_dataset>C:\Git\build64\Windows-AMD64-\Release\openMVG_main_SfM.exe -i C:/SfmTest/360/Image_datasets_2nd/360_dataset/360_Flat/images_out/matches/sfm_data.json -m C:/SfmTest/360/Image_datasets_2nd/360_dataset/360_Flat/images_out/matches -o C:/SfmTest/360/Image_datasets_2nd/360_dataset/360_Flat/images_out/reconstruction
INFO: [main_SfM.cpp:136]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
INFO: [loggerprogress.hpp:79] [- Features Loading -] 20%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 40%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 60%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 80%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
INFO: [sequential_SfM.cpp:278] Track building
INFO: [sequential_SfM.cpp:281] Track filtering
INFO: [sequential_SfM.cpp:283] Track export to internal struct
INFO: [sequential_SfM.cpp:309]
------------------
-- Tracks Stats --
 Tracks number: 24234
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
------------------
TrackLength, Occurrence
        2       15382
        3       3211
        4       1521
        5       842
        6       568
        7       407
        8       264
        9       263
        10      195
        11      165
        12      133
        13      100
        14      98
        15      87
        16      69
        17      64
        18      73
        19      62
        20      60
        21      55
        22      53
        23      68
        24      130
        25      364

INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 10%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 20%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 30%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 40%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 50%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 60%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 70%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 80%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 90%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 100%
INFO: [sequential_SfM.cpp:495] Putative starting pair info:
index:(6,24)
view basename:(img_007t,img_025t)
INFO: [sequential_SfM.cpp:538] Relative pose a-contrario upper_bound residual is: 0.377474
INFO: [sfm_data_BA_ceres.cpp:496]
Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 847
 #residuals: 3388
 Initial RMSE: 6.99105
 Final RMSE: 5.39395
 Time (s): 0.110985
--
 Used motion prior: 0
INFO: [sequential_SfM.cpp:648]
=========================
 MSE Residual InitialPair Inlier:

INFO: [sequential_SfM.cpp:733]
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
        -- #Tracks:     2
        -- Residual min:        0.397265
        -- Residual median:     0.501337
        -- Residual max:         0.594015
        -- Residual mean:        0.498967
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 5
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 12
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 14
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 15
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 16
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 1
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 17
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 19
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 20
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 23
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 2
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 11
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 10
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 13
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 4
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 9
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 22
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 21
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:932] -- Trying robust Resection of view: 0
INFO: [SfM_Localizer.cpp:303]
-------------------------------
-- Robust Resection statistics:
-- Resection status: 0
-- #Points used for Resection: 1
-- #Points validated by robust Resection: 0
-- Threshold: 0
-------------------------------
INFO: [sequential_SfM.cpp:733]
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
        -- #Tracks:     2
        -- Residual min:        0.397265
        -- Residual median:     0.501337
        -- Residual max:         0.594015
        -- Residual mean:        0.498967
INFO: [sequential_SfM.cpp:235]
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 2 from 25 input images.
-- #Tracks, #3D points: 2
-------------------------------

Histogram of residuals:
0       |       1
0.0197  |       0
0.0393  |       1
0.059   |       0
0.0787  |       0
0.0984  |       4
0.118   |       0
0.138   |       0
0.157   |       1
0.177   |       0
0.594

INFO: [main_SfM.cpp:557]  Total Sfm took (s): 0
INFO: [main_SfM.cpp:559] ...Generating SfM_Report.html
INFO: [main_SfM.cpp:564] ...Export SfM_Data to disk.
```
please help
thank you

**Comment by pmoulon** [comment]
Seems like you have two few correspondences between your image to have a rigid reconstruction
Did you extract feature with the `-p HIGH` option, it should help?

**Comment by MeUsushi** [comment]
Thank you for your answer.
so, I tried extract features with the -p HIGH option.
like
C:\ReleaseV1.6.Halibut.WindowsBinaries_VS2017\openMVG_main_ComputeFeatures.exe -i C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches/sfm_data.json -o C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches -f 1 -p HIGH

I got new match files.
but, I tried openMVG_main_SfM.exe again, I got new Error
CMD said

C:\SfmTest\360\Image_datasets\360_dataset\360_Flat>C:\Git\build64\Windows-AMD64-\Release\openMVG_main_SfM.exe -i C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches/sfm_data.json -m C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches -o C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/reconstruction
INFO: [main_SfM.cpp:136]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
INFO: [loggerprogress.hpp:79] [- Features Loading -] 20%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 40%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 60%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 80%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
INFO: [sequential_SfM.cpp:278] Track building
INFO: [sequential_SfM.cpp:281] Track filtering
INFO: [sequential_SfM.cpp:283] Track export to internal struct
INFO: [sequential_SfM.cpp:309]
------------------
-- Tracks Stats --
 Tracks number: 52079
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
------------------
TrackLength, Occurrence
        2       32839
        3       6885
        4       3121
        5       1841
        6       1191
        7       911
        8       666
        9       531
        10      426
        11      356
        12      296
        13      247
        14      241
        15      202
        16      187
        17      159
        18      157
        19      121
        20      138
        21      156
        22      148
        23      196
        24      252
        25      812

INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 10%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 20%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 30%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 40%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 50%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 60%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 70%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 80%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 90%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 100%
INFO: [sequential_SfM.cpp:495] Putative starting pair info:
index:(11,12)
view basename:(2,20)
ERROR: [sequential_SfM.cpp:534]  /!\ Robust estimation failed to compute E for this pair: {11,12}

please help x(

**Comment by MeUsushi** [comment]
Thank you for your answer.
so, I tried extract features with the -p HIGH option.
like
C:\ReleaseV1.6.Halibut.WindowsBinaries_VS2017\openMVG_main_ComputeFeatures.exe -i C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches/sfm_data.json -o C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches -f 1 -p HIGH

I got new match files.
but, I tried openMVG_main_SfM.exe again, I got new Error
CMD said

C:\SfmTest\360\Image_datasets\360_dataset\360_Flat>C:\Git\build64\Windows-AMD64-\Release\openMVG_main_SfM.exe -i C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches/sfm_data.json -m C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/matches -o C:/SfmTest/360/Image_datasets/360_dataset/360_Flat/images_out/reconstruction
INFO: [main_SfM.cpp:136]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
INFO: [loggerprogress.hpp:79] [- Features Loading -] 20%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 40%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 60%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 80%
INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
INFO: [sequential_SfM.cpp:278] Track building
INFO: [sequential_SfM.cpp:281] Track filtering
INFO: [sequential_SfM.cpp:283] Track export to internal struct
INFO: [sequential_SfM.cpp:309]
------------------
-- Tracks Stats --
 Tracks number: 52768
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
------------------
TrackLength, Occurrence
        2       32637
        3       7294
        4       3393
        5       1885
        6       1258
        7       940
        8       672
        9       577
        10      440
        11      347
        12      301
        13      239
        14      223
        15      207
        16      186
        17      147
        18      181
        19      114
        20      143
        21      154
        22      140
        23      195
        24      274
        25      821

INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 10%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 20%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 30%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 40%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 50%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 60%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 70%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 80%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 90%
INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 100%
INFO: [sequential_SfM.cpp:495] Putative starting pair info:
index:(9,24)
view basename:(img_010t,img_025t)
ERROR: [sequential_SfM.cpp:534]  /!\ Robust estimation failed to compute E for this pair: {9,24}

please help x(

**Comment by pmoulon** [comment]
If you know two images that are close to each other, just chose those two.
- The bootstrap process is more optimized for classic pinhole image and so it is less robust for spherical images.

Just try different pair of images on the main_SfM binary, it will work for one.

**Comment by MeUsushi** [comment]
mmm......
I got next error [Could not find the initial pairs]...
Can I find pair images?
My pictures are outside picutures and walking a straight road.
Are they difficult for DfM?

**Comment by MeUsushi** [comment]
I can get success!!
Thank you so much

**Comment by pmoulon** [comment]
Happy that it worked out.
Feel free to share screenshot of your reconstruction here ;-)
