### ISSUE TITLE
Spherical camera

### ISSUE THREAD

**Issue by json87** [openMVG/openMVG#2089]
Hi, thanks for providing the excellent tool set.

Recently, I am interesting in processing spherical images by using openMVG. Thus, I want to know what's the main difference between normal cameras, such as pinhole, and spherical cameras in the SFM workflow.

Thanks.

**Comment by rperrot** [comment]
The main difference is that pinhole camera needs a focal. Spherical doesn't because they are modelised as a unit sphere.

**Comment by json87** [comment]
@rperrot 
Thanks. I will have a further research on this topic. At the same time, I found that some command parameters have been changed, which is different from the manual in this website 

https://github.com/openMVG/Image_datasets/tree/main/360_dataset

**Comment by json87** [comment]
@rperrot 
I have found that some cmd arguments have changed in the newest version.
Thanks.

**Comment by rperrot** [comment]
Could you sum up them in order to help us to correct the documentation, plz ?

**Comment by json87** [comment]
I have tested the following commands and obtained desired results.

`:: Initialize the scene (spherical camera model)
openMVG_main_SfMInit_ImageListing -i images -o openmvg/matches -f 1 -c 7

:: Compute features (you can add -n <THREAD_COUNT> to be faster)
openMVG_main_ComputeFeatures -i openmvg/matches/sfm_data.json -o openmvg/matches -p HIGH

:: Make match pairs (exhaustive mode)
openMVG_main_ListMatchingPairs -i openmvg/matches/sfm_data.json -o openmvg/matches/matching_pairs.txt -E

:: Compute initial matches
openMVG_main_ComputeMatches -i openmvg/matches/sfm_data.json -o openmvg/matches/matches_putative.bin -p openmvg/matches/matching_pairs.txt -n HNSWL1

:: Compute refined matches (notice the angular mode, more adapted for spherical images)
openMVG_main_GeometricFilter -i openmvg/matches/sfm_data.json -o openmvg/matches/matches_refined.bin -m openmvg/matches/matches_putative.bin -g a

:: Compute of the camera motion and structure of the scene
openMVG_main_SfM -i openmvg/matches/sfm_data.json -M openmvg/matches/matches_putative.bin -o openmvg/reconstruction -s INCREMENTAL

:: Convert spherical images to cubic images
openMVG_main_openMVGSpherical2Cubic -i openmvg/reconstruction/sfm_data.bin -o openmvg/reconstruction/cubic

:: Convert the scene from OpenMVG to COLMAP data format
openMVG_main_openMVG2Colmap -i openmvg/reconstruction/cubic/sfm_data_perspective.bin -o openmvg/reconstruction/cubic/colmap_sparse`

**Comment by pmoulon** [comment]
Closing the issue since a path to success has been found

**Comment by Camuvingian** [comment]
I have the following three images, and I cannot for the life of me get the pipeline above to produce results, can anyone help me? 

```sh
.\openMVG_main_SfMInit_ImageListing.exe -i C:\VRPM\OpenMVG\Att1\Input\ -o C:\VRPM\OpenMVG\Att1\Matches\ -f 1 -c 7
.\openMVG_main_ComputeFeatures.exe -i C:\VRPM\OpenMVG\Att1\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att1\Matches\ -p HIGH -n 16
.\openMVG_main_ListMatchingPairs.exe -i C:\VRPM\OpenMVG\Att1\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att1\Matches\matching_pairs.txt
.\openMVG_main_ComputeMatches.exe -i C:\VRPM\OpenMVG\Att1\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att1\Matches\matches_putative.bin -p C:\VRPM\OpenMVG\Att1\Matches\matching_pairs.txt -n HNSWL1
.\openMVG_main_GeometricFilter.exe -i C:\VRPM\OpenMVG\Att1\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att1\Matches\matches_refined.bin -m C:\VRPM\OpenMVG\Att1\Matches\matches_putative.bin -g a
.\openMVG_main_SfM.exe -i C:\VRPM\OpenMVG\Att1\Matches\sfm_data.json -M C:\VRPM\OpenMVG\Att1\Matches\matches_refined.bin -o C:\VRPM\OpenMVG\Att1\Recon\ -s INCREMENTAL
```

Nothing gets written to the Recon directory apart from "Reconstruction_Report.html" which contains

```html
<html><head>
<link rel="stylesheet" type="text/css" href="http://jsxgraph.uni-bayreuth.de/distrib/jsxgraph.css" />
<link rel="stylesheet" type="text/css" href="http://imagine.enpc.fr/~moulonp/style.css" /><script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jsxgraph/0.93/jsxgraphcore.js"></script>
<title>SequentialReconstructionEngine SFM report.</title>
</head>
<h1>SequentialSfMReconstructionEngine</h1>
<hr>Dataset info:Views count: 6<br></html>
```

Can anyone point me in the right direction here?

**Comment by json87** [comment]
@Camuvingian I think you should test the workflow by using the 360 dataset from the following website

https://github.com/openMVG/Image_datasets/tree/main/360_dataset/360_Flat/images

**Comment by Camuvingian** [comment]
I will try this now. Thanks for getting back to me. I would like to establish why this will not work for my own images however. Single SFM on each pair works.

**Comment by Camuvingian** [comment]
@json87 do you see the output
```sh
INFO: [graph_stats.hpp:53] Graph statistics:
        #nodes: 11
        #cc: 1
        #singleton: 0
        Node degree statistics: min: 10, max: 10, mean: 10, median: 10
**'neato' is not recognized as an internal or external command,
operable program or batch file.**
```
This seems like a solver fail?

**Comment by Camuvingian** [comment]
Likewise:

```
.\openMVG_main_SfM.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -M C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin -o C:\VRPM\OpenMVG\Att4\Recon\ -s INCREMENTAL
```
Output:
```
INFO: [main_SfM.cpp:135]
-----------------------------------------------------------
 Structure from Motion:
-----------------------------------------------------------
INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
INFO: [sequential_SfM.cpp:278] Track building
INFO: [sequential_SfM.cpp:281] Track filtering
INFO: [sequential_SfM.cpp:283] Track export to internal struct
INFO: [sequential_SfM.cpp:309]
------------------
-- Tracks Stats --
 Tracks number: 13067
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
------------------
TrackLength, Occurrence
        2       7280
        3       2718
        4       1318
        5       706
        6       342
        7       247
        8       160
        9       106
        10      92
        11      98

INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 20%
```
This also has not completed - I have no idea why. 

@pmoulon any chance you could offer any insight to what I am doing wrong? I have the binaries from the latest release. https://github.com/openMVG/openMVG/releases/tag/v2.0

**Comment by json87** [comment]
> 

It is normal as the command 'neato' does not exist.

**Comment by json87** [comment]
I have run the pipeline again and found no problems.

![image](https://user-images.githubusercontent.com/17582213/188856844-7549aeee-b94f-4f83-b02a-c8b088c4ba8b.png)

**Comment by Camuvingian** [comment]
This is my output - the image files are in the `C:\VRPM\OpenMVG\Att4\Input\` directory:

### 1. Initialize.

```
.\openMVG_main_SfMInit_ImageListing.exe -i C:\VRPM\OpenMVG\Att4\Input\ -o C:\VRPM\OpenMVG\Att4\Matches\ -f 1 -c 7
```

> INFO: [main_SfMInit_ImageListing.cpp:197]  You called : C:\Dev\OpenMVG\ReleaseV2.0.Rainbow-Trout.WindowsBinaries_VS2019\openMVG_main_SfMInit_ImageListing.exe
> --imageDirectory C:\VRPM\OpenMVG\Att4\Input\
> --sensorWidthDatabase
> --outputDirectory C:\VRPM\OpenMVG\Att4\Matches\
> --focal 1
> --intrinsics
> --camera_model 7
> --group_camera_model 1
> --use_pose_prior 0
> --prior_weights 1.0;1.0;1.0
> --gps_to_xyz_method 0
> INFO: [loggerprogress.hpp:79] [- Listing images -] 100%
> INFO: [main_SfMInit_ImageListing.cpp:478] SfMInit_ImageListing report:
> listed #File(s): 11
> usable #File(s) listed in sfm_data: 11
> usable #Intrinsic(s) listed in sfm_data: 1

Produces file(s):

> C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json

### 2. Compute Features.

```
.\openMVG_main_ComputeFeatures.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att4\Matches\ -p HIGH -n 16
```

> INFO: [main_ComputeFeatures.cpp:121]  You called :
> C:\Dev\OpenMVG\ReleaseV2.0.Rainbow-Trout.WindowsBinaries_VS2019\openMVG_main_ComputeFeatures.exe
> --input_file C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json
> --outdir C:\VRPM\OpenMVG\Att4\Matches\
> --describerMethod SIFT
> --upright 0
> --describerPreset HIGH
> --force 0
> --numThreads 16
> 
> INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 100%
> INFO: [main_ComputeFeatures.cpp:344] Task done in (s): 6

Produces file(s):

> C:\VRPM\OpenMVG\Att4\Matches\image_describer.json
> C:\VRPM\OpenMVG\Att4\Matches\<imageFileName>.feat/desc [22 files]

### 3. List Matching Pairs.

```
.\openMVG_main_ListMatchingPairs.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att4\Matches\matching_pairs.txt -E
```

> INFO: [main_ListMatchingPairs.cpp:87]
>
> Compute a view pair list file for main_ComputeMatches:
>  - various pair modes are available to adapt to user dataset
>    configuration.
>
> INFO: [main_ListMatchingPairs.cpp:127]  You called :
> C:\Dev\OpenMVG\ReleaseV2.0.Rainbow-Trout.WindowsBinaries_VS2019\openMVG_main_ListMatchingPairs.exe
> --input_file C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json
> --output_file C:\VRPM\OpenMVG\Att4\Matches\matching_pairs.txt
> Optional parameters:
> --exhaustive_mode ON
> --video_mode OFF
> --gps_mode OFF
> 
> INFO: [main_ListMatchingPairs.cpp:165] Loaded a sfm_data scene with:
>  #views: 11
> INFO: [main_ListMatchingPairs.cpp:311] Exported 55 view pairs
> from a view graph that have 55 relative pose pairs.

Produces File(s):

> C:\VRPM\OpenMVG\Att4\Matches\matching_pairs.txt
> C:\VRPM\OpenMVG\Att4\Matches\imatching_pairs.txt.svg

### 4. Compute Matches.

```
.\openMVG_main_ComputeMatches.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin -p C:\VRPM\OpenMVG\Att4\Matches\matching_pairs.txt -n HNSWL1
```

> INFO: [main_ComputeMatches.cpp:114]  You called :
> C:\Dev\OpenMVG\ReleaseV2.0.Rainbow-Trout.WindowsBinaries_VS2019\openMVG_main_ComputeMatches.exe
> --input_file C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json
> --output_file C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin
> --pair_list C:\VRPM\OpenMVG\Att4\Matches\matching_pairs.txt
> Optional parameters:
> --force 0
> --ratio 0.8
> --nearest_matching_method HNSWL1
> --cache_size unlimited
> --preemptive_feature_used/count 0 / 200
> INFO: [loggerprogress.hpp:79] [- Regions Loading -] 100%
> INFO: [main_ComputeMatches.cpp:217]  - PUTATIVE MATCHES -
> INFO: [main_ComputeMatches.cpp:268] Using HNSWL1 matcher
> INFO: [main_ComputeMatches.cpp:317] Running matching on #pairs: 55
> INFO: [Matcher_Regions.cpp:41] Using the OPENMP thread interface
> INFO: [loggerprogress.hpp:79] [- Matching -] 20%
> INFO: [loggerprogress.hpp:79] [- Matching -] 40%
> INFO: [loggerprogress.hpp:79] [- Matching -] 60%
> INFO: [loggerprogress.hpp:79] [- Matching -] 80%
> INFO: [loggerprogress.hpp:79] [- Matching -] 100%
> INFO: [main_ComputeMatches.cpp:363] Task (Regions Matching) done in (s): 6
> INFO: [main_ComputeMatches.cpp:366] #Putative pairs: 55
> INFO: [graph_stats.hpp:53] Graph statistics:
>         #nodes: 11
>         #cc: 1
>         #singleton: 0
>         Node degree statistics: min: 10, max: 10, mean: 10, median: 10
> 'neato' is not recognized as an internal or external command,
> operable program or batch file.

Produces File(s): 

> C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin
> C:\VRPM\OpenMVG\Att4\Matches\preemptive_pairs.txt
> C:\VRPM\OpenMVG\Att4\Matches\PutativeAdjacencyMatrix.svg
> C:\VRPM\OpenMVG\Att4\Matches\putative_matches

### 5. Geometric Filter.

```
.\openMVG_main_GeometricFilter.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -o C:\VRPM\OpenMVG\Att4\Matches\matches_refined.bin -m C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin -g a
```

> INFO: [main_GeometricFilter.cpp:130]  You called :
> C:\Dev\OpenMVG\ReleaseV2.0.Rainbow-Trout.WindowsBinaries_VS2019\openMVG_main_GeometricFilter.exe
> --input_file:        C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json
> --matches:           C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin
> --output_file:       C:\VRPM\OpenMVG\Att4\Matches\matches_refined.bin
> Optional parameters:
> --input_pairs
> --output_pairs
> --force              false
> --geometric_model    a
> --guided_matching    0
> --cache_size         unlimited
> INFO: [loggerprogress.hpp:79] [- Regions Loading -] 100%

Produces File(s):

**_No new files. No matches_refined.bin produced._** 

### 6. SFM

```
.\openMVG_main_SfM.exe -i C:\VRPM\OpenMVG\Att4\Matches\sfm_data.json -M C:\VRPM\OpenMVG\Att4\Matches\matches_putative.bin -o C:\VRPM\OpenMVG\Att4\Recon -s INCREMENTAL
```

> INFO: [main_SfM.cpp:135]
> -----------------------------------------------------------
>  Structure from Motion:
> -----------------------------------------------------------
> INFO: [loggerprogress.hpp:79] [- Features Loading -] 100%
> INFO: [sequential_SfM.cpp:278] Track building
> INFO: [sequential_SfM.cpp:281] Track filtering
> INFO: [sequential_SfM.cpp:283] Track export to internal struct
> INFO: [sequential_SfM.cpp:309]
> ------------------
> -- Tracks Stats --
>  Tracks number: 13064
>  Images Id:
> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
> ------------------
> TrackLength, Occurrence
>         2       7265
>         3       2721
>         4       1316
>         5       710
>         6       350
>         7       246
>         8       158
>         9       106
>         10      93
>         11      99
> 
> INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 20%

Produces File(s):

**_NO FILES PRODUCED_**

using GLOBAL, same result - no files.

**Comment by json87** [comment]
@Camuvingian I used the major version of this software, please make sure the right version first.

**Comment by Camuvingian** [comment]
Sorry for all the questions and thanks for your time here. To be clear, by "master version" do you mean the main branch "default" - this is what I have built and _still_ I cannot get the output you have shown.

**Comment by pmoulon** [comment]
Seems strange that the openMVG_main_GeometricFilter returned nothing

What does openMVG_main_GeometricFilter output for your configuration
```
INFO: [main_GeometricFilter.cpp:107] Usage: .../openMVG_main_GeometricFilter
[-i|--input_file]       A SfM_Data file
[-m|--matches]          (Input) matches filename
[-o|--output_file]      (Output) filtered matches filename

[Optional]
[-p|--input_pairs]      (Input) pairs filename
[-s|--output_pairs]     (Output) filtered pairs filename
[-f|--force]            Force to recompute data
[-g|--geometric_model]
  (pairwise correspondences filtering thanks to robust model estimation):
   f: (default) fundamental matrix,
   e: essential matrix,
   h: homography matrix.
   a: essential matrix with an angular parametrization,
   u: upright essential matrix with an angular parametrization,
   o: orthographic essential matrix.
[-r|--guided_matching]  Use the found model to improve the pairwise correspondences.
[-c|--cache_size]
  Use a regions cache (only cache_size regions will be stored in memory)
  If not used, all regions will be load in memory.
INFO: [main_GeometricFilter.cpp:128] Invalid command line parameter.
```

It seems that `-g a` did not work for you

FYI @json87 meant to compile by yourself the last version of openMVG

**Comment by pmoulon** [comment]
Also the output of Geometric filter should be provided to SfM.
So in your case if you export matches_refined.bin with GeometricFilter you should provide `-M C:\VRPM\OpenMVG\Att4\Matches\matches_refined.bin` to SfM (File that you don't have for some reason)
