### ISSUE TITLE
[QUESTION] about computation time duration

### ISSUE THREAD

**Issue by pyp22** [openMVG/openMVG#209]
Hi Pierre, Hi all,

i'd need some comparison for computation time duration for NuxSFM so i used your Sceaux castle images. I wrote a quick bash script with a time_Duration() and got those results:

------------------------------------------
STEP 1: Process Intrisics analysis - openMVG_main_CreateList took: 00:00:00:00.077
STEP 2: Process compute matches - openMVG_main_computeMatches took: 00:00:07:35.455436
STEP 3: Process Incremental Reconstruction -  openMVG_main_IncrementalSfM took: 00:00:06:10.370961
STEP 4: Process Export to CMVS-PMVS - openMVG_main_openMVG2PMVS took: 00:00:00:00.355
STEP 5: Process CMVS-PMVS took: 00:00:01:08.68965

--------------------
The whole detection and 3D reconsruction process took: 00:00:14:55.895797

Less than a quarter to an hour running openMVG on a AMD 8 cores 64 bits CPU. This is my dev machine. Does it make sens to you?

 I own some other machines (I7 950) on which i will test that as soon as my vbox img distro will be available to compare results.

Another question pse if you don't mind (i know this an issue forum only :: snif ...) but i remarked that the Computation Process Matching (openMVG_main_computeMatches) runs MONO threaded and i don't understand why.

Excuse me for my last question but i always ask some stupid ones when i don't understand something (i'm Musographer :) ))

Kindest regards 

Pierre 

PS : merci pour votre conférence à tous les 2! Je vous embauche pour des confs quand vous voulez pour faire de la vulgarisation scientifique et technique sur l'imagerie numérique :)

**Comment by pmoulon** [comment]
MPI will not be considered soon but some binaries that can be run on many computer will be created in the future, the running scripts will be provided too.
