### ISSUE TITLE
SfMInit_ImageListing initialised in the wrong order?

### ISSUE THREAD

**Issue by 4CJ7T** [openMVG/openMVG#2090]
I'm processing a dataset at half resolution then running ComputeStructureFromKnownPoses on full resolution features.
Half resolution scene looks fine but after ComputeStructureFromKnownPoses it's scattered.
It's weird, the id_intrinsic of the first view started at 1 instead of 0 for the downscaled dataset. I've never ran into that issue on any other dataset, what do you think happened?

Dataset for testing: https://www.mediafire.com/file/ld98qehjvpx74bs/xjrn-0h22.7z/file

**Comment by pmoulon** [comment]
Each time the input sfm_data file must match the images you are using.
So I would invite you to edit or mix your SFM_DATA found with half resolution and replace the valid fields that would support the large resolution images.

If you need help scripting this we could add a short demo that shows how to do that.
Basically, you would have to update the intrinsics the match, and copy the poses to the sfm_data file corresponding to the full res images.

**Comment by 4CJ7T** [comment]
👍
