### ISSUE TITLE
libCommon.so: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by Abonaventure** [openMVG/openMVG#2093]
when I make -j16 && sudo make install, come across the follows:

/usr/bin/ld: CMakeFiles/RefineMesh.dir/RefineMesh.cpp.o: undefined reference to symbol '_ZN7SEACAVE5Timer13GetTimeFactorEv'
/usr/bin/ld: /mnt/d/slam14/openMVS/openMVS_build/lib/libCommon.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [apps/RefineMesh/CMakeFiles/RefineMesh.dir/build.make:98: bin/RefineMesh] Error 1
make[1]: *** [CMakeFiles/Makefile2:563: apps/RefineMesh/CMakeFiles/RefineMesh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by pmoulon** [comment]
Refine mesh is part of OpenMVS and not OpenMVG.
