### ISSUE TITLE
openMVG vs ORBSLAM3

### ISSUE THREAD

**Issue by navid-mahmoudian** [openMVG/openMVG#2096]
Hello,

In the discussion part, I asked the same question, but since there was no response, I decided to create an issue (sorry for the duplication). Would you be able to explain what the differences, pros, and cons are between openMVG and  [ORBSLAM3](https://github.com/UZ-SLAMLab/ORB_SLAM3)? The difference between SFM and ORBSLAM3's SLAM in terms of technical bricks is not clear to me.

**Comment by pmoulon** [comment]
See the thread here https://github.com/openMVG/openMVG/discussions/2095
