### ISSUE TITLE
How to solve the incremental SFM by openmvg?

### ISSUE THREAD

**Issue by LUANDONG123** [openMVG/openMVG#2097]
I have download the openmvg and know pnp bundle adjustment,I didnt konw how to add the image and increase the landmark.I need the help

**Comment by pmoulon** [comment]
If you download the pre-existing package you basically have to follow the instruction to run the provided python script that run the OpenMVG binaries for you: https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfM.rst#openmvg-sfm-pipelines-demo
