### ISSUE TITLE
 no matching function for call to ‘find_if(std::__cxx11::basic_string<char>::const_iterator, std::__cxx11::basic_string<char>::const_iterator, <unresolved overloaded function type>)’

### ISSUE THREAD

**Issue by vip96300** [openMVG/openMVG#2109]
[build] In file included from /usr/local/include/openMVG/exif/sensor_width_database/ParseDatabase.hpp:17,
[build]                  from /home/huanghongfei/workspace/simulation-3d/./_openMVG/SfM/main_SfMInit_ImageListing.cpp:11,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:18:
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp: In member function ‘bool Datasheet::operator==(const Datasheet&) const’:
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:62:76: error: no matching function for call to ‘find_if(std::__cxx11::basic_string<char>::const_iterator, std::__cxx11::basic_string<char>::const_iterator, <unresolved overloaded function type>)’
[build]    62 |         if ( std::find_if(db_sub_model.begin(), db_sub_model.end(), isdigit) != db_sub_model.end() )
[build]       |                                                                            ^
[build] In file included from /usr/include/c++/9/algorithm:62,
[build]                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:39,
[build]                  from /usr/include/boost/log/core/core.hpp:19,
[build]                  from /usr/include/boost/log/core.hpp:20,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/Logger.h:15,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:13:
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note: candidate: ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’
[build]  3960 |     find_if(_InputIterator __first, _InputIterator __last,
[build]       |     ^~~~~~~
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/openMVG/exif/sensor_width_database/ParseDatabase.hpp:17,
[build]                  from /home/huanghongfei/workspace/simulation-3d/./_openMVG/SfM/main_SfMInit_ImageListing.cpp:11,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:18:
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:62:76: note:   couldn’t deduce template parameter ‘_Predicate’
[build]    62 |         if ( std::find_if(db_sub_model.begin(), db_sub_model.end(), isdigit) != db_sub_model.end() )
[build]       |                                                                            ^
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:72:65: error: no matching function for call to ‘find_if(std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, <unresolved overloaded function type>)’
[build]    72 |         std::find_if(rhs_model.begin(), rhs_model.end(), isdigit) != rhs_model.end();
[build]       |                                                                 ^
[build] In file included from /usr/include/c++/9/algorithm:62,
[build]                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:39,
[build]                  from /usr/include/boost/log/core/core.hpp:19,
[build]                  from /usr/include/boost/log/core.hpp:20,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/Logger.h:15,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:13:
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note: candidate: ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’
[build]  3960 |     find_if(_InputIterator __first, _InputIterator __last,
[build]       |     ^~~~~~~
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/openMVG/exif/sensor_width_database/ParseDatabase.hpp:17,
[build]                  from /home/huanghongfei/workspace/simulation-3d/./_openMVG/SfM/main_SfMInit_ImageListing.cpp:11,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:18:
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:72:65: note:   couldn’t deduce template parameter ‘_Predicate’
[build]    72 |         std::find_if(rhs_model.begin(), rhs_model.end(), isdigit) != rhs_model.end();
[build]       |                                                                 ^
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:87:77: error: no matching function for call to ‘find_if(std::__cxx11::basic_string<char>::const_iterator, std::__cxx11::basic_string<char>::const_iterator, <unresolved overloaded function type>)’
[build]    87 |             std::find_if(rhs_sub_model.begin(), rhs_sub_model.end(), isdigit) != rhs_sub_model.end();
[build]       |                                                                             ^
[build] In file included from /usr/include/c++/9/algorithm:62,
[build]                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:39,
[build]                  from /usr/include/boost/log/core/core.hpp:19,
[build]                  from /usr/include/boost/log/core.hpp:20,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/Logger.h:15,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:13:
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note: candidate: ‘template<class _IIter, class _Predicate> _IIter std::find_if(_IIter, _IIter, _Predicate)’
[build]  3960 |     find_if(_InputIterator __first, _InputIterator __last,
[build]       |     ^~~~~~~
[build] /usr/include/c++/9/bits/stl_algo.h:3960:5: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/openMVG/exif/sensor_width_database/ParseDatabase.hpp:17,
[build]                  from /home/huanghongfei/workspace/simulation-3d/./_openMVG/SfM/main_SfMInit_ImageListing.cpp:11,
[build]                  from /home/huanghongfei/workspace/simulation-3d/src/ReconstructPipeline.cpp:18:
[build] /usr/local/include/openMVG/exif/sensor_width_database/datasheet.hpp:87:77: note:   couldn’t deduce template parameter ‘_Predicate’
[build]    87 |             std::find_if(rhs_sub_model.begin(), rhs_sub_model.end(), isdigit) != rhs_sub_model.end();
[build]       |                                                                             ^

**Comment by vip96300** [comment]
i using ubuntu20.04 and standard c++ 14

**Comment by pmoulon** [comment]
C++11 should be the minimum required.
As we don't identify this issue with the current CI (GithubActions), can you list which GCC and G++ version are you using in your distribution?

Since the compiler complains about const iterators, car you try to change
`std::find_if(db_sub_model.begin(), db_sub_model.end(), isdigit) != db_sub_model.end() `
to
`std::find_if(db_sub_model.cbegin(), db_sub_model.cend(), isdigit) != db_sub_model.cend() `

**Comment by vip96300** [comment]
$bash gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by vip96300** [comment]
$bash gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu120.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu120.04.1)

**Comment by vip96300** [comment]
> $bash gcc -v Using built-in specs. COLLECT_GCC=gcc COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper OFFLOAD_TARGET_NAMES=nvptx-none:hsa OFFLOAD_TARGET_DEFAULT=1 Target: x86_64-linux-gnu Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu120.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu Thread model: posix gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu120.04.1)

**Comment by vip96300** [comment]
> 



> C++11 should be the minimum required. As we don't identify this issue with the current CI (GithubActions), can you list which GCC and G++ version are you using in your distribution?
> 
> Since the compiler complains about const iterators, car you try to change `std::find_if(db_sub_model.begin(), db_sub_model.end(), isdigit) != db_sub_model.end() ` to `std::find_if(db_sub_model.cbegin(), db_sub_model.cend(), isdigit) != db_sub_model.cend() `

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by pmoulon** [comment]
Let's see if we can make it pass for the compiler with changing the iterator to const_iterators

**Comment by vip96300** [comment]
thanks for your reply ,let me try

> C++11 should be the minimum required. As we don't identify this issue with the current CI (GithubActions), can you list which GCC and G++ version are you using in your distribution?
> 
> Since the compiler complains about const iterators, car you try to change `std::find_if(db_sub_model.begin(), db_sub_model.end(), isdigit) != db_sub_model.end() ` to `std::find_if(db_sub_model.cbegin(), db_sub_model.cend(), isdigit) != db_sub_model.cend() `

thanks for your reply,let me try it

**Comment by vip96300** [comment]
> Let's see if we can make it pass for the compiler with changing the iterator to const_iterators

i tring change .begin() to .cbegin() and it's not working,maybe is my enviroment has some problem
