### ISSUE TITLE
[question] global sfm only output  some svg file

### ISSUE THREAD

**Issue by julian-wang** [openMVG/openMVG#211]
Hi, this is my first time to use openMVG. I try to make global sfm following the pipline of document. But there are only cleanedGraph cleanedGraph.svg etc in outGlobalSfM directory. I cannot find images,cameras,clouds directory.

I use the images from ImageDataset_SceauxCastle and execute the following commands:
```
./openMVG_main_CreateList -i ../../ImageDataset/images/ -o ../../ImageDataset/matches/ -d ../../../../CameraSensorSizeDatabase/

./openMVG_main_computeMatches -g e -p 0.01 -i ../../ImageDataset/images/ -o ../../ImageDataset/matches/

./openMVG_main_GlobalSfM -i ../../ImageDataset/images/ -m ../../ImageDataset/matches/ -o ../../ImageDataset/outGlobalSfM
```

**Thanks a lot!**

**Comment by pmoulon** [comment]
Hi,
You have made an error at the first step:
You must set the file for the -d option => -d ../../../../CameraSensorSizeDatabase/cameraGenerated.txt

I think it will work better once you will have done that.
Check that the file matches/lists.txt is not empty.

Regards,
Pierre

**Comment by julian-wang** [comment]
I got it. **Thanks a lot!** 
Maybe you should modify the document format to show complete command.

**Comment by pmoulon** [comment]
It's already documented, the command line already contains the cameraGenerated.txt information.
http://openmvg.readthedocs.org/en/latest/software/SfM/intrinsicGroups/
