### ISSUE TITLE
undefined reference to `vl_constructor',undefined reference to `vl_sift,how to link the sift libraries

### ISSUE THREAD

**Issue by vip96300** [openMVG/openMVG#2112]
/usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:96: undefined reference to `vl_destructor'
[build] /usr/bin/ld: _openMVG/SfM/lib_openMVG_SFM.a(main_ComputeFeatures.cpp.o): in function `openMVG::features::SIFT_Image_describer::DescribeSIFT(openMVG::image::Image<unsigned char> const&, openMVG::image::Image<unsigned char> const*)':
[build] /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:150: undefined reference to `vl_sift_new'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:161: undefined reference to `vl_sift_process_first_octave'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:171: undefined reference to `vl_sift_detect'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:177: undefined reference to `vl_sift_update_gradient'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:196: undefined reference to `vl_sift_calc_keypoint_orientations'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:200: undefined reference to `vl_sift_calc_keypoint_descriptor'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:214: undefined reference to `vl_sift_process_next_octave'
[build] /usr/bin/ld: /usr/local/include/openMVG_dependencies/nonFree/sift/SIFT_describer.hpp:217: undefined reference to `vl_sift_delete'

**Comment by vip96300** [comment]
how to using openMVG_dependencies and link the libraries

**Comment by Yangyp29** [comment]
I encountered the same issue as you did. How did you resolve it？
