### ISSUE TITLE
Using robust_essential_spherical to get relative camera pose seems werid?

### ISSUE THREAD

**Issue by CBS5181** [openMVG/openMVG#2113]
Hi, thanks for providing the excellent tool set.
Recently, I tried to use robust_essential_spherical to get the relative camera pose.
When I printed out the relative pose (Pose3), I had some problems with the result.

```cpp
// Setup poses camera data
const Pose3 pose0 = tiny_scene.poses[tiny_scene.views[0]->id_pose] = Pose3(Mat3::Identity(), Vec3::Zero());
const Pose3 pose1 = tiny_scene.poses[tiny_scene.views[1]->id_pose] = relative_pose;
std::cout << relative_pose.asMatrix() << std::endl;
```

1. Pose01 is always at (0, 0, 0). Correct me if I’m wrong, but I think pose2 is only transformed with translation from relative pose?

2. If I’m not mistaken,  I think the result of relative_pose.asMatrix(), [R|T],  is Mat3::Identity() as Rotation and Vec3::Zero() as Translation when using two identical spherical panoramic images. However, the result is
![image](https://user-images.githubusercontent.com/35103220/191580244-a9b70aad-407e-4cce-b5a9-82bc3b508299.png)
![image](https://user-images.githubusercontent.com/35103220/191580356-71d1316b-93d4-48a1-bf80-5f63a727fb1d.png)
And I check the .ply file with Meshlab found that it scaled the vertices of point cloud up (10^13) so the translation make no difference to pose1 (0, 0, 0)
![image](https://user-images.githubusercontent.com/35103220/191582362-ee648889-ce24-4250-b7ca-876420b00b2a.png)
So, when I use robust_essential_spherical, it seems to have the scaling problem, right?
Is there any method to fix this scale problem?

3. If I only have eight match points (not use SIFT), how should I change the code? Because the solver of robust_essential_spherical doesn't seem to support it.

Thanks.

**Comment by pmoulon** [comment]
Thank you for your feedback.

You are right relative pose estimation always configures one camera as Identity.

It seems that you have a very few displacement between your cameras.
Scale is always up to a scale factor to the reality and also note that some case could be close to degenerate cases (very small translation vs just rotation)

I would advise you to use for inplane solver (using only 3pt as input | if gravity is known or using upright images) or the 5pt solver
See here https://github.com/openMVG/openMVG/blob/develop/src/openMVG_Samples/multiview_robust_essential_spherical/robust_essential_spherical.cpp#L181

3pt solver ThreePointUprightRelativePoseSolver https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/multiview/solver_essential_three_point.hpp#L53

Maybe I could consider updating the tutorial with a parameter to help choose the SOLVER.
Do you think you can do this update, or do you want me to make a PR for it and let you test it?

**Comment by CBS5181** [comment]
Hi @pmoulon , thanks for your response.
I am relatively new to these methods and not familiar with openMVG API. 
Could you please make a PR for it and I will test it.

Also, I have some questions.
1. What is the meaning for upright image? Does it mean floor at the bottom of the panoramic image and ceiling at the top? (if indoor)

2. Scale is always up to a scale factor to the reality. Therefore, it seems that I should do some calculations for the "scale factor" for the solution out of openMVG to get real world values. Could you give me some advice about this?

Thanks.

**Comment by pmoulon** [comment]
1. Yes it means ceiling on top
2. You can use either some known dimension to scale your reconstruction, or automate it with fiducial markers.

I will probably make the PR next week.

**Comment by CBS5181** [comment]
Hi @pmoulon, thanks for your response.
How’s the PR going?

Also, I have some questions.
I read the ACRANSAC source code and found that it got samples with a random generator. 
I wondered if there is a way to fix some of the samples chosen on my own and get the others randomly? (e.g. Eight Points with 4-fixed and 4-random) or weight the samples with higher / lower confidence in matching by human-in-the-loop?

I will be grateful for any help you can provide.

**Comment by pmoulon** [comment]
Made a PR here https://github.com/openMVG/openMVG/tree/develop_spherical_relative_pose_solvers
You can now specify the solver you want to use with --solver X X could be either of 8points, 5 points, 3points

Regarding weighting samples, feel free to try to hack the sample generator and force to always use some id of your choice
