### ISSUE TITLE
build shared libraries on windows fail

### ISSUE THREAD

**Issue by KarenChang1988** [openMVG/openMVG#2117]
** OpenMVG version: 2.0.0
** Build Shared libs: ON
** Build OpenMVG tests: OFF
** Build OpenMVG softwares: ON
** Build OpenMVG GUI softwares: OFF
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF
** Use LiGT for global translation estimation: ON

CEREAL: (internal)
EIGEN: 3.4.0 (internal)
CERES: 1.13.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.16.10 (internal)
COINUTILS: 2.10.13 (internal)
OSI:  (internal)
LEMON: 1.3 (internal)

**When OpenMVG_BUILD_SHARED is set to ON
Build openMVG_multiview and openMVG_sfm will fail using VS2017 with the internal ceres on windows.
The error message is as follows**

`LNK2001	 unresolved external symbol "__declspec(dllimport) bool __cdecl ceres::IsSparseLinearAlgebraLibraryTypeAvailable(enum ceres::SparseLinearAlgebraLibraryType)" (__imp_?IsSparseLinearAlgebraLibraryTypeAvailable@ceres@@YA_NW4SparseLinearAlgebraLibraryType@1@@Z)`

`LNK2001	 unresolved external symbol "__declspec(dllimport) public: __cdecl ceres::Problem::Problem(void)" (__imp_??0Problem@ceres@@QEAA@XZ)`

**Comment by pmoulon** [comment]
I'm sorry to hear about that.
It builds fine on the CI with GithubActions but I must not do SHARED build there.

Not exactly sure what is happening since in the CMAKELIST we have the right library include (ceres is listed as dependencies).
Wonder if the issue is PRIVATE vs PUBLIC on those library requirements

**Comment by pmoulon** [comment]
Any luck on your side trying something different?

**Comment by KarenChang1988** [comment]
I will try it again, thank you

**Comment by HerryJessica** [comment]
@KarenChang1988  I encountered the same problem when compiling the shared library. How did you solve it?
