### ISSUE TITLE
Failed SFM from indoor 360 data set

### ISSUE THREAD

**Issue by monschine** [openMVG/openMVG#2120]
Hi, 

I just compiled the latest release of openMVG, and playing around with the library.
First thanks for such a great tool, it's amazing !

I have generated the following dataset for testing purposes [dataset](https://github.com/monschine/entrada_min)
Images are quite big as they are created with a Ricoh Theta Z1

I have followed the [instructions](https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm) about the spherical sfm

Firstly I adapted a bit the code to the new conventions and namings, I created a bash file to execute it providing the input folder
 

```path2OpenMVG=/Users/jo/Documents/openMVG_Build/Darwin-x86_64-RELEASE
cd $1

mkdir matches
mkdir reconstruction
mkdir reconstruction/m

#Initialize the scene (spherical camera model)
openMVG_main_SfMInit_ImageListing -i $1 -o $1/matches -f 1 -c 7

#Compute of the features (you can add -n <THREAD_COUNT> to be faster)
openMVG_main_ComputeFeatures -i $1/matches/sfm_data.json -o $1/matches -m AKAZE_FLOAT -p HIGH

#Compute a view pair list file
openMVG_main_PairGenerator -i $1/matches/sfm_data.json -o $1/matches/pair_list.txt -m CONTIGUOUS --contiguous_count 2

#Compute the image matches (notice the angular mode, more adapted for spherical images Not accepted anymore as argument)
openMVG_main_ComputeMatches -i $1/matches/sfm_data.json -o $1/matches/matches.f.txt --pair_list $1/matches/pair_list.txt

#Compute a pair list based on matches
openMVG_main_ListMatchingPairs -i $1/matches/sfm_data.json -o $1/matches/match_pair_list.txt -E

#Export the matches to visualize
openMVG_main_exportMatches -i $1/matches/sfm_data.json -d $1/matches -m $1/matches/matches.f.txt -o $1/reconstruction/m

#Compute of the camera motion and structure of the scene
openMVG_main_SfM -i $1/matches/sfm_data.json -m $1/matches/ -o $1/reconstruction/ -s INCREMENTAL --match_file $1/matches/matches.f.txt -a $2 -b $3 --resection_method 0 --triangulation_method 3 --camera_model 5
```

Seems like most of the code just works fine and features are defined and matches found, but when I perform the SFM I get the next error 

```INFO: [loggerprogress.hpp:79] [Selection of an initial pair] 100%
INFO: [sequential_SfM.cpp:495] Putative starting pair info:
index:(2,3)
view basename:(R0012887,R0012888)
ERROR: [sequential_SfM.cpp:534]  /!\ Robust estimation failed to compute E for this pair: {2,3}
```

On the other hand I have manually executed all the relations from pano to pano using the openMVG_sample_multiview_robustEssential_spherical which by changing the value of D2R(4.0) as suggested [here](https://github.com/openMVG/openMVG/issues/2062#issuecomment-1123462270), and proved that the relations between panos are fine

Any hint on how to achieve a good SFM results would be most welcome.

Thanks in advance

**Comment by pmoulon** [comment]
Hi. I would most likely recommend you to make your view graph a bit denser and not just match the next 2 views. 
Also OpenMVG api in v2 has been changed a little bit. You now need to call GeometricFilter binary (this is where you will see the -g a option available.

I will try to run your dataset on my side later in the week and let you know what I can see there.

**Comment by pmoulon** [comment]
Can you provide me access to your dataset repo so I can test to see what output I have on my side?

**Comment by monschine** [comment]
Hi @pmoulon, now the dataset repo is public.
Thanks

**Comment by pmoulon** [comment]
Here is what I get from your dataset - top view (I used "-m", "SIFT", "-p", "HIGH" on ComputeFeatures):
![image](https://user-images.githubusercontent.com/3235050/197244022-d7e25d19-3aa0-4bf7-b80a-8bbc5553e529.png)

**Comment by monschine** [comment]
Hi @pmoulon thanks for testing and posting your results

on my side I'm not able to get them like this and I only get poses located, here is exactly the calls I do :

```
openMVG_main_SfMInit_ImageListing -i ./dataset -o ./dataset/matches -f 1 -c 7
openMVG_main_ComputeFeatures -i ./dataset/matches/sfm_data.json -o ./dataset/matches -m SIFT -p HIGH -u 1
openMVG_main_PairGenerator -i ./dataset/matches/sfm_data.json -o ./dataset/matches/pair_list.txt
openMVG_main_ComputeMatches -i ./dat
aset/matches/sfm_data.json -o ./dataset/matches/matches.f.txt -p ./dataset/matches/pair_list.txt -n ANNL2
openMVG_main_GeometricFilter -i ./dataset/matches/sfm_data.json -m ./dataset/matches/matches.f.txt -g a -o ./dataset/matches/matches_filter.f.txt
openMVG_main_ListMatchingPairs -i ./dataset/matches/sfm_data.json -o ./dataset/matches/match_pair_list.txt -E
openMVG_main_exportMatches -i ./dataset/matches/sfm_data.json -d ./dataset/matches -m ./dataset/matches/matches_filter.f.txt -o ./dataset/reconstruction/m
openMVG_main_SfM -i ./dataset/matches/sfm_data.json -m ./dataset/matches/ -o ./dataset/reconstruction/ -s INCREMENTAL --match_file ./dataset/matches/matches_filter.f.txt -a R0012927.jpg -b R0012928.jpg
```

I guess I'm missing some part, should I use incremental as SFM startegy ? or any other parameter ?
Would love to be able to get your results , thanks

**Comment by GenJiGu** [comment]
> Hi,
> 
> I just compiled the latest release of openMVG, and playing around with the library. First thanks for such a great tool, it's amazing !
> 
> I have generated the following dataset for testing purposes [dataset](https://github.com/monschine/entrada_min) Images are quite big as they are created with a Ricoh Theta Z1
> 
> I have followed the [instructions](https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/SfM/SfM.rst#notes-about-spherical-sfm) about the spherical sfm
> 
> Firstly I adapted a bit the code to the new conventions and namings, I created a bash file to execute it providing the input folder
> 
> ```
> cd $1
> 
> mkdir matches
> mkdir reconstruction
> mkdir reconstruction/m
> 
> #Initialize the scene (spherical camera model)
> openMVG_main_SfMInit_ImageListing -i $1 -o $1/matches -f 1 -c 7
> 
> #Compute of the features (you can add -n <THREAD_COUNT> to be faster)
> openMVG_main_ComputeFeatures -i $1/matches/sfm_data.json -o $1/matches -m AKAZE_FLOAT -p HIGH
> 
> #Compute a view pair list file
> openMVG_main_PairGenerator -i $1/matches/sfm_data.json -o $1/matches/pair_list.txt -m CONTIGUOUS --contiguous_count 2
> 
> #Compute the image matches (notice the angular mode, more adapted for spherical images Not accepted anymore as argument)
> openMVG_main_ComputeMatches -i $1/matches/sfm_data.json -o $1/matches/matches.f.txt --pair_list $1/matches/pair_list.txt
> 
> #Compute a pair list based on matches
> openMVG_main_ListMatchingPairs -i $1/matches/sfm_data.json -o $1/matches/match_pair_list.txt -E
> 
> #Export the matches to visualize
> openMVG_main_exportMatches -i $1/matches/sfm_data.json -d $1/matches -m $1/matches/matches.f.txt -o $1/reconstruction/m
> 
> #Compute of the camera motion and structure of the scene
> openMVG_main_SfM -i $1/matches/sfm_data.json -m $1/matches/ -o $1/reconstruction/ -s INCREMENTAL --match_file $1/matches/matches.f.txt -a $2 -b $3 --resection_method 0 --triangulation_method 3 --camera_model 5
> ```
> 
> Seems like most of the code just works fine and features are defined and matches found, but when I perform the SFM I get the next error
> 
> ```
> INFO: [sequential_SfM.cpp:495] Putative starting pair info:
> index:(2,3)
> view basename:(R0012887,R0012888)
> ERROR: [sequential_SfM.cpp:534]  /!\ Robust estimation failed to compute E for this pair: {2,3}
> ```
> 
> On the other hand I have manually executed all the relations from pano to pano using the openMVG_sample_multiview_robustEssential_spherical which by changing the value of D2R(4.0) as suggested [here](https://github.com/openMVG/openMVG/issues/2062#issuecomment-1123462270), and proved that the relations between panos are fine
> 
> Any hint on how to achieve a good SFM results would be most welcome.
> 
> Thanks in advance

excuse me. What should be filled in for 2 and 3?
