### ISSUE TITLE
memleak

### ISSUE THREAD

**Issue by BrentHuang** [openMVG/openMVG#2121]
memleak in file: src/openMVG/image/image_io.cpp
at func: Read_PNG_ImageHeader

should add: 
  png_destroy_info_struct(png_ptr, &info_ptr);
  png_destroy_read_struct(&png_ptr, nullptr, nullptr);

**Comment by pmoulon** [comment]
Thank you for sharing this, do you want propose a PR to fix the issue?

**Comment by BrentHuang** [comment]
Ok, I'm going to check more and submit them to you together.
