### ISSUE TITLE
loading features and descriptors

### ISSUE THREAD

**Issue by monschine** [openMVG/openMVG#2122]
Hi, 
I'm trying without succes to load features and descriptors to the robust spherical sample, instead of the images.
Any code hint on how to achieve that ?

Thanks in advance

**Comment by pmoulon** [comment]
I would use the same system as in SFM the Regions provider:
See here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeMatches.cpp#L173
Or else use directly the regions and regions loader from files that you know and open
```
std::map<IndexT, std::unique_ptr<features::Regions>> regions_perImage;
regions_perImage[0] = 
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/regions.hpp#L32
```

**Comment by monschine** [comment]
Hi, 

I added idL and idR as an argument to generate the feature and descriptor path 
```
  const std::string featFileL = idL + ".feat";
  const std::string descFileL = idL + ".desc";

  const std::string featFileR = idR + ".feat";
  const std::string descFileR = idR + ".desc";
```
But after trying multiple attempts of loading the regions :
```
using namespace openMVG::features;

  std::map<IndexT, std::unique_ptr<features::Regions>> regions_perImage;
  regions_perImage[0]->Load(featFileL, descFileL);
  regions_perImage[1]->Load(featFileR, descFileR);
```

I just get errors when executing ....

I have been able to load them separately by doing next 
```
 // Define a feature and a container of features
  using Feature_T = SIOPointFeature;
  using Feats_T = std::vector<Feature_T>;

  // Define a descriptor and a container of descriptors
  static const int DESC_LENGTH = 128;
  using Desc_T = Descriptor<float, DESC_LENGTH>;
  using Descs_T = std::vector<Desc_T, Eigen::aligned_allocator<Desc_T>>;

  Feats_T featsL;
  loadFeatsFromFile(featFileL, featsL);

  Feats_T featsR;
  loadFeatsFromFile(featFileR, featsR);

  Descs_T descsL;
  loadDescsFromBinFile(descFileL, descsL);
  
  Descs_T descsR;
  loadDescsFromBinFile(descFileR, descsR);
```

Any other hint  to get the features and descriptors loaded in the regions_perImage will be appreciated, I'm not really comfortable with c++

Thanks in advance
