### ISSUE TITLE
How to output the intrinsic matrix and visual sfm_data.bin.

### ISSUE THREAD

**Issue by bdxuyidong** [openMVG/openMVG#2128]
Hi, My camera is in the  database, but how can I output the intrinsic matrix? I want to check the result. And I also want to visual the data in sfm_data.bin, is there any way to do that? Thank you!

**Comment by pmoulon** [comment]
You can use the ConvertSfmDataFormat binary, and set as ouput a sfm_data.json file.
If you just want to see the intrinsics value just use the -I parameter

`openMVG_main_ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data_intrinsics.json -I -V`

**Comment by bdxuyidong** [comment]
Thanks a lot!!!!
