### ISSUE TITLE
cmake error: ‘SubsetParameterization’ is not a member of ‘ceres’

### ISSUE THREAD

**Issue by Hao4977** [openMVG/openMVG#2134]
I use WSL2 with ubuntu22.04.
Previous compiling steps are successful, but when I run this command `cmake --build . --target install`, I get these errors as below.

```
[ 63%] Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_BA_ceres.cpp.o
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp: In member function ‘virtual bool openMVG::sfm::Bundle_Adjustment_Ceres::Adjust(openMVG::sfm::SfM_Data&, const openMVG::sfm::Optimize_Options&)’:
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:282:16: error: ‘SubsetParameterization’ is not a member of ‘ceres’
  282 |         ceres::SubsetParameterization *subset_parameterization =
      |                ^~~~~~~~~~~~~~~~~~~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:282:40: error: ‘subset_parameterization’ was not declared in this scope
  282 |         ceres::SubsetParameterization *subset_parameterization =
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:283:15: error: expected type-specifier
  283 |           new ceres::SubsetParameterization(6, vec_constant_extrinsic);
      |               ^~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:284:17: error: ‘class ceres::Problem’ has no member named ‘SetParameterization’; did you mean ‘SetParameterLowerBound’?
  284 |         problem.SetParameterization(parameter_block, subset_parameterization);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 SetParameterLowerBound
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:312:20: error: ‘SubsetParameterization’ is not a member of ‘ceres’
  312 |             ceres::SubsetParameterization *subset_parameterization =
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:312:44: error: ‘subset_parameterization’ was not declared in this scope
  312 |             ceres::SubsetParameterization *subset_parameterization =
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:313:19: error: expected type-specifier
  313 |               new ceres::SubsetParameterization(
      |                   ^~~~~
/home/huhao/lib/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:315:21: error: ‘class ceres::Problem’ has no member named ‘SetParameterization’; did you mean ‘SetParameterLowerBound’?
  315 |             problem.SetParameterization(parameter_block, subset_parameterization);
      |                     ^~~~~~~~~~~~~~~~~~~
      |                     SetParameterLowerBound
gmake[2]: *** [openMVG/sfm/CMakeFiles/openMVG_sfm.dir/build.make:258: openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_BA_ceres.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:4839: openMVG/sfm/CMakeFiles/openMVG_sfm.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

How to solve it?
I would appreciate some help.

**Comment by pmoulon** [comment]
Are you using system or OpenMVG provided Ceres?
The info should be displayed at cmake configure time. OpenMVG cmake will says if he is using internal or external libs.

**Comment by Hao4977** [comment]
> Are you using system or OpenMVG provided Ceres? The info should be displayed at cmake configure time. OpenMVG cmake will says if he is using internal or external libs.

Thanks for your help!
I checked the configure info and found it is using external Ceres. 
Should I uninstall external Ceres.?

**Comment by pmoulon** [comment]
You are probably using a more recent version of Ceres. I though API would be compatible but maybe it changed. You can force using internal Ceres. You can clear your internal cmake cache comment this line https://github.com/openMVG/openMVG/blob/acc5a1c1571e4357928e453662180f98b59ccdc8/src/CMakeLists.txt#L304 and it should be ok.

**Comment by pmoulon** [comment]
See here "Note

[SubsetParameterization](http://ceres-solver.org/nnls_modeling.html?highlight=subset#_CPPv4N5ceres22SubsetParameterizationE) is deprecated. It will be removed in version 2.2.0 of Ceres Solver. Please use [SubsetManifold](http://ceres-solver.org/nnls_modeling.html?highlight=subset#_CPPv4N5ceres14SubsetManifoldE) instead."

Fell free to help us update our API and supports Ceres 2.2.0!

**Comment by Hao4977** [comment]
> You are probably using a more recent version of Ceres. I though API would be compatible but maybe it changed. You can force using internal Ceres. You can clear your internal cmake cache comment this line
> 
> https://github.com/openMVG/openMVG/blob/acc5a1c1571e4357928e453662180f98b59ccdc8/src/CMakeLists.txt#L304
> 
> and it should be ok.

It works.
Thanks again.
