### ISSUE TITLE
I want to get translation，how can I get it from center and rotation

### ISSUE THREAD

**Issue by TXYUU** [openMVG/openMVG#2141]
Thank you for the amazing work,I want to get the R and t,but center parameters I don't understand its meaning,how can I get the t?

**Comment by pmoulon** [comment]
`t = -RC`
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/geometry/pose3.hpp#L89

**Comment by TXYUU** [comment]
> `t = -RC` https://github.com/openMVG/openMVG/blob/develop/src/openMVG/geometry/pose3.hpp#L89

Thank you for your quick reply, does the t mean the translation between two camera pose?If so ,the numbers of translation should be (the numbers of camera pose -1),I don't know if I am wrong.

**Comment by TXYUU** [comment]
> `t = -RC` https://github.com/openMVG/openMVG/blob/develop/src/openMVG/geometry/pose3.hpp#L89

Thank you for your quick reply, does the t mean the translation between two camera pose?If so ,the numbers of translation should be (the numbers of camera pose -1),I don't know if I am wrong.

**Comment by pmoulon** [comment]
Each camera is having its absolute pose. They are not relative.
If the SfM process can localize all your camera, you will have a many translation as image in your dataset
