### ISSUE TITLE
recipe for target 'all' failed

### ISSUE THREAD

**Issue by Anonyme415** [openMVG/openMVG#2143]
In file included from /output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:50:0:
/usr/local/include/eigen3/Eigen/SparseCholesky:34:2: error: #error The SparseCholesky module has nothing to offer in MPL2 only mode
 #error The SparseCholesky module has nothing to offer in MPL2 only mode
  ^~~~~
In file included from /usr/local/include/eigen3/Eigen/SparseCholesky:39:0,
                 from /output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:50:
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:244:72: error: ‘AMDOrdering’ does not name a type; did you mean ‘COLAMDOrdering’?
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialLLT;
                                                                        ^~~~~~~~~~~
                                                                        COLAMDOrdering
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:244:83: error: expected ‘>’ before ‘<’ token
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialLLT;
                                                                                   ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:245:72: error: ‘AMDOrdering’ does not name a type; did you mean ‘COLAMDOrdering’?
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialLDLT;
                                                                        ^~~~~~~~~~~
                                                                        COLAMDOrdering
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:245:83: error: expected ‘>’ before ‘<’ token
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialLDLT;
                                                                                   ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:246:72: error: ‘AMDOrdering’ does not name a type; did you mean ‘COLAMDOrdering’?
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialCholesky;
                                                                        ^~~~~~~~~~~
                                                                        COLAMDOrdering
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:246:83: error: expected ‘>’ before ‘<’ token
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::Index> > class SimplicialCholesky;
                                                                                   ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:489:60: error: template argument 3 is invalid
     typedef internal::traits<SimplicialLDLT<MatrixType,UpLo> > LDLTTraits;
                                                            ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:489:62: error: template argument 1 is invalid
     typedef internal::traits<SimplicialLDLT<MatrixType,UpLo> > LDLTTraits;
                                                              ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:490:59: error: template argument 3 is invalid
     typedef internal::traits<SimplicialLLT<MatrixType,UpLo>  > LLTTraits;
                                                           ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:490:62: error: template argument 1 is invalid
     typedef internal::traits<SimplicialLLT<MatrixType,UpLo>  > LLTTraits;
                                                              ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h: In member function ‘void Eigen::SimplicialCholesky<_MatrixType, _UpLo, _Ordering>::_solve(const Eigen::MatrixBase<OtherDerived>&, Eigen::MatrixBase<OtherDerived>&) const’:
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:579:27: error: qualified-id in declaration before ‘(’ token
           LDLTTraits::getL(Base::m_matrix).solveInPlace(dest);
                           ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:581:26: error: qualified-id in declaration before ‘(’ token
           LLTTraits::getL(Base::m_matrix).solveInPlace(dest);
                          ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:590:27: error: qualified-id in declaration before ‘(’ token
           LDLTTraits::getU(Base::m_matrix).solveInPlace(dest);
                           ^
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:592:26: error: qualified-id in declaration before ‘(’ token
           LLTTraits::getU(Base::m_matrix).solveInPlace(dest);
                          ^
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc: In member function ‘ceres::internal::LinearSolver::Summary ceres::internal::DynamicSparseNormalCholeskySolver::SolveImplUsingEigen(ceres::internal::CompressedRowSparseMatrix*, double*)’:
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:132:53: error: template argument 3 is invalid
   Eigen::SimplicialLDLT<Eigen::SparseMatrix<double> > solver;
                                                     ^
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:139:10: error: request for member ‘analyzePattern’ in ‘solver’, which is of non-class type ‘int’
   solver.analyzePattern(lhs);
          ^~~~~~~~~~~~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:142:12: error: request for member ‘dumpMemory’ in ‘solver’, which is of non-class type ‘int’
     solver.dumpMemory(ss);
            ^~~~~~~~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:147:14: error: request for member ‘info’ in ‘solver’, which is of non-class type ‘int’
   if (solver.info() != Eigen::Success) {
              ^~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:153:10: error: request for member ‘factorize’ in ‘solver’, which is of non-class type ‘int’
   solver.factorize(lhs);
          ^~~~~~~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:155:14: error: request for member ‘info’ in ‘solver’, which is of non-class type ‘int’
   if (solver.info() != Eigen::Success) {
              ^~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:162:52: error: request for member ‘solve’ in ‘solver’, which is of non-class type ‘int’
   VectorRef(rhs_and_solution, lhs.cols()) = solver.solve(rhs);
                                                    ^~~~~
/output/openMVG/src/third_party/ceres-solver/internal/ceres/dynamic_sparse_normal_cholesky_solver.cc:164:14: error: request for member ‘info’ in ‘solver’, which is of non-class type ‘int’
   if (solver.info() != Eigen::Success) {
              ^~~~
third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/build.make:830: recipe for target 'third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/dynamic_sparse_normal_cholesky_solver.cc.o' failed
make[2]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/dynamic_sparse_normal_cholesky_solver.cc.o] Error 1
CMakeFiles/Makefile2:721: recipe for target 'third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/all' failed
make[1]: *** [third_party/ceres-solver/internal/ceres/CMakeFiles/openMVG_ceres.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pmoulon** [comment]
Can you tell us which version of Ceres and Eigen you are using, build is passing fine in our CI for internal and external build?

You can see the version printed when you run cmake for openMVG

**Comment by Anonyme415** [comment]
This is the version printed when i run cmake for openMVG.Is it the installation of Ceres and Eigen?
-- CEREAL: (internal)
-- EIGEN:  (external)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.37 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)

**Comment by pmoulon** [comment]
Can you check which version of Eigen you have?

**Comment by Anonyme415** [comment]
-- CEREAL: (internal)
-- EIGEN:  (external)
-- CERES: 2.1.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.9 (external)
-- LIBPNG: 1.6.37 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI:  (internal)
-- LEMON: 1.3 (internal)
Hello, I have successfully installed version 3.3.4 of eigen before, but it seems that there is no reference here.
#define EIGEN_WORLD_VERSION 3
#define EIGEN_MAJOR_VERSION 3
#define EIGEN_MINOR_VERSION 4

**Comment by pmoulon** [comment]
It seems that the trouble would come from this line coming for your external ceres
https://github.com/openMVG/openMVG/blob/798d082e38f08dbef7d9129a29060d73afdb29bd/src/third_party/ceres-solver/CMakeLists.txt#L205

For some reason it seems that your Ceres on your machine is not built with Eigen Sparse support.

Else it could be that this line is causing the issue in your build configuration (but I still think we have hit the sitaution cited above - ceres compiled without Eigen Sparse support) https://github.com/openMVG/openMVG/blob/798d082e38f08dbef7d9129a29060d73afdb29bd/src/CMakeLists.txt#L296

**Comment by ntdat017** [comment]
@Anonyme415, @pmoulon I met the same problem like OP, I solved by upgrade EIGEN version 3.3.4 to 3.4.0 (https://eigen.tuxfamily.org/index.php?title=Main_Page).

**Comment by pmoulon** [comment]
Great. Than you for confirming.
@Anonyme415 can you try, confirm and close the issue?

**Comment by Anonyme415** [comment]
I have tried this method and the problem has been solved. Thank. @ntdat017 @pmoulon
