### ISSUE TITLE
Where can I find openMVG_main_ConvertSfM_DataFormat file

### ISSUE THREAD

**Issue by ZhenyanSun** [openMVG/openMVG#2145]
Dear Team， 
thanks for your sharing.  I want to covert sfm_data.bin into json files, but I can not find the openMVG_main_ConvertSfM_DataFormat.bin file.

**Comment by ZhenyanSun** [comment]
> Dear Team， thanks for your sharing. I want to covert sfm_data.bin into json files, but I can not find the openMVG_main_ConvertSfM_DataFormat.bin file.

please ignore the stupid question，thanks

**Comment by pmoulon** [comment]
There is not stupid questions ;-)
Closing the thread and wishing you happy experiments with OpenMVG ;-)
