### ISSUE TITLE
Find spherical camera position with 3 known 3d points on a model

### ISSUE THREAD

**Issue by monschine** [openMVG/openMVG#2151]
Greetings,

I am seeking to discover the most efficient method for determining the position of an equirectangular camera, given three points within the image and their corresponding points within a 3D model. On one hand, I have real 3D points, and on the other, the points on the sphere.

One potential approach that comes to mind is to convert the real 3D points into a projection from a new point and then perform spherical robust estimation. Once the results are obtained, we could then scale them back to the original size using the initial values.

However, I believe there must be a more direct and elegant solution to this problem.

Thank you.

**Comment by monschine** [comment]
Actually I just made a quick synthetic testing dataset in blender.

![diagram](https://user-images.githubusercontent.com/9587968/214522684-8d44e33c-e478-4cb0-b754-290a54189a53.jpg)


so it's this simple cube in a cube with 3 camera positions, just to test the same values from multiples cameras.

The values of the 3D points are  :

```
A  = {
    x: -0.45,
    y: 0.45,
    z: 0.45
}

B  = {
    x: -0.45,
    y: 0.45,
    z: 0.75
}

C  = {
    x: -0.45,
    y: 0.00,
    z: 0.45
}
```
The corresponding features in the images are 

```
camera 1 
A = { x: 465, y: 534}
B = { x: 660, y: 530}
C = { x: 465, y: 765}

camera 2 
A = { x: 748, y: 464}
B = { x: 792, y: 469}
C = { x: 748, y: 569}

camera 3 
A = { x: 871, y: 685}
B = { x: 933, y: 606}
C = { x: 871, y: 853}
```


And here the images
camera 1
![camera1](https://user-images.githubusercontent.com/9587968/214522796-1a3c87d1-f11b-42e7-b0f2-fea0c7205749.png)

camera 2 
![camera2](https://user-images.githubusercontent.com/9587968/214522805-5ac87042-b82a-445f-b885-5fa4373896c9.png)

camera 3
![camera3](https://user-images.githubusercontent.com/9587968/214522807-d3a12d9a-2388-48c0-b69f-8668da613c62.png)

And finally the known camera positions for proving the results are :
```
camera1 = {
    x: 0.0,
    y: 0.7,
    z: 0.5
}

camera2 = {
    x: 0.5,
    y: 0.3,
    z: -0.5
}

camera3 = {
    x: -0.322723,
    y: 0.150384,
    z: 0.664474
}
```

Hopefully there is no issue with coordinates system, blender is switching the usage of Y Z, which I already modified in my values, but maybe still some sign issue.

Thanks

**Comment by pmoulon** [comment]
Hello,
The problem you want to solve is called `Absolute Camera Position`.
You can use for this the Absolute Camera Pose solver in OpenMVG.

By default, and an arbitrary oriented camera you need 3 points and their image correspondences -> That's why we call it P3P
- If your camera is upright, you can use 2 correspondences (3d and 2d) -> uP2P -> u for Upright

P3P (Nordberg being the more stable) -> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/multiview/solver_resection_p3p.hpp

Upright P2p -> https://github.com/openMVG/openMVG/blob/develop/src/openMVG/multiview/solver_resection_up2p_kukelova.hpp

For each of them you need to use the bearing vector:
- the ray from the camera center going through the pixel coordinate, to do so use Camera Intrinsics class -> camera(x) will provide them to you

-> Blender can have some axis difference with our coordinate system but you can easily test.

Maybe next week I can have some time to show you how to use the code to do what I said

**Comment by monschine** [comment]
Hi @pmoulon, thank for pointing out those solvers !
I will try to take a closer look and try to implement them with the dataset I have generated.
But of course any hint on how to implement the code will be most welcome !

Thanks and kind regards

**Comment by monschine** [comment]
Hi @pmoulon , any hint on the code would be most welcome.
A starting point, like data entry and what functions to call would probably be enough.
Thanks in advance

**Comment by monschine** [comment]
Hi @pmoulon  any hint on that topic ?

**Comment by monschine** [comment]
Hi @pmoulon  I finally found some time to tackle the issue, and already got some results.
The curious thing is that for some cameras I get good results but not for others

Also I'm trying with all the solvers available nordberg/kneip/ke/Kukelova

for camera 1 
	✓ Solution Kn 0 : -0.01 0.49 -0.51
	✓ Solution Ke 3 : -0.01 0.49 -0.51
	✓ Solution Ku 0 : -0.00 0.50 -0.50
	Ground Truth : 0.0 -0.7 0.5

for camera 2
	✓ Solution No 1 : -0.52 0.30 0.49
	✓ Solution Kn 1 : -0.52 0.30 0.49
	✓ Solution Ke 0 : -0.57 0.28 0.49
	✓ Solution Ku 0 : -0.53 0.30 0.50
	Ground Truth : 0.5 -0.3 -0.5

for camera 3
	✓ Solution No 0 : 0.32 0.67 -0.15
	✓ Solution Kn 0 : 0.32 0.67 -0.15
	✓ Solution Ke 3 : 0.32 0.67 -0.15
	✓ Solution Ku 0 : 0.33 0.66 -0.15
	Ground Truth : 0.322723 0.664474 0.150384

So while for camera 2 and 3 the solution seems ok , there's some gap in the camera 1, can you point me some method to improve that results ? I tried to test with more than 3 points but the solvers seems to be expecting only 3 points

Also how would you figure out which is the best solution from the results because I get multiple solution for each camera location.

About the code I'm using I just followed your instructions and came with something like this 

```
	// Create a spherical camera:
	cameras::Intrinsic_Spherical sphere_camera(pano_width, pano_height);

	// Set up the image points
	Vec2 img_point_A(465, 534);
	Vec2 img_point_B(660, 530);
	Vec2 img_point_C(465, 765);
	
	// Convert the image points to bearing vectors:

	Vec3 bearing_A = sphere_camera(img_point_A);
	Vec3 bearing_B = sphere_camera(img_point_B);
	Vec3 bearing_C = sphere_camera(img_point_C);

	// Set up the 3D points
	Eigen::Matrix<double, 3, 3> X; // 3D points
	X.col(0) = Vec3(-0.45, 0.45, 0.45);
	X.col(1) = Vec3(-0.45, 0.45, 0.75);
	X.col(2) = Vec3(-0.45, 0.00, 0.45);

	Eigen::Matrix<double, 3, 3> bearing_vectors; // image points in bearing vectors
	bearing_vectors.col(0) = Vec3(bearing_A);
	bearing_vectors.col(1) = Vec3(bearing_B);
	bearing_vectors.col(2) = Vec3(bearing_C);
	
	std::vector<Mat34> solutionsNo;

	// Run the P3P solver
	openMVG::euclidean_resection::P3PSolver_Nordberg::Solve(bearing_vectors, X, &solutionsNo);

	for (int i = 0; i < solutionsNo.size(); ++i) {
  		const auto& solution = solutionsNo[i];
		Vec3 translation = solution.block<3, 1>(0, 3);
		std::cout << "Solution No " << i << " : " << std::fixed << std::setprecision(2) << translation[0] << " " << translation[1] << " " << translation[2] << std::endl;
	}
``
`

Thanks in advance

**Comment by pmoulon** [comment]
Sorry got busy and did not got time to look back to your message.

Since we are using minimal solver, you just have the 4 possible solution but all of them are valid, you would need one additional point to evaluate which one is good.
I would advise you to have one more additional correspondence that would help you test the 4 solution and determine which one is good.
Adding 1 or 2 measurements to your setup could greatly help you improve your accuracy.

**Comment by monschine** [comment]
Thank you @pmoulon for your insightful suggestions on enhancing the solution. So, if I've understood correctly, the modification I need to implement in my code involves providing two additional points. Subsequently, I would perform the same computation using these different inputs. Finally, I would compare the results, identifying the common solution among the various combinations of the three-point groups. Is that correct?

**Comment by pmoulon** [comment]
Yes this is what I'm suggesting, to at least add one correspondence to help you make disambiguation.
