### ISSUE TITLE
Error while build develop branch with last version of ceres library

### ISSUE THREAD

**Issue by SmthFail** [openMVG/openMVG#2152]
Greetings!

I'm trying to build develop branch with last version of ceres library. Build fail with error.
```
 [ 69%] Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_BA_ceres.cpp.o
[ 69%] Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_colorization.cpp.o
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp: In member function 'virtual bool openMVG::sfm::Bundle_Adjustment_Ceres::Adjust(openMVG::sfm::SfM_Data&, const openMVG::sfm::Optimize_Options&)':
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:282:16: error: 'SubsetParameterization' is not a member of 'ceres'
  282 |         ceres::SubsetParameterization *subset_parameterization =
      |                ^~~~~~~~~~~~~~~~~~~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:282:40: error: 'subset_parameterization' was not declared in this scope
  282 |         ceres::SubsetParameterization *subset_parameterization =
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:283:15: error: expected type-specifier
  283 |           new ceres::SubsetParameterization(6, vec_constant_extrinsic);
      |               ^~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:284:17: error: 'class ceres::Problem' has no member named 'SetParameterization'; did you mean 'SetParameterLowerBound'?
  284 |         problem.SetParameterization(parameter_block, subset_parameterization);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 SetParameterLowerBound
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:312:20: error: 'SubsetParameterization' is not a member of 'ceres'
  312 |             ceres::SubsetParameterization *subset_parameterization =
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:312:44: error: 'subset_parameterization' was not declared in this scope
  312 |             ceres::SubsetParameterization *subset_parameterization =
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:313:19: error: expected type-specifier
  313 |               new ceres::SubsetParameterization(
      |                   ^~~~~
/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:315:21: error: 'class ceres::Problem' has no member named 'SetParameterization'; did you mean 'SetParameterLowerBound'?
  315 |             problem.SetParameterization(parameter_block, subset_parameterization);
      |                     ^~~~~~~~~~~~~~~~~~~
      |                     SetParameterLowerBound
[ 70%] Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_filters.cpp.o
[ 70%] Building CXX object openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_filters_frustum.cpp.o
make[2]: *** [openMVG/sfm/CMakeFiles/openMVG_sfm.dir/build.make:232: openMVG/sfm/CMakeFiles/openMVG_sfm.dir/sfm_data_BA_ceres.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2323: openMVG/sfm/CMakeFiles/openMVG_sfm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I'm build it in docker. Part of dockerfile with ceres and openmvg build:
```
RUN git clone https://ceres-solver.googlesource.com/ceres-solver --branch master  && \
    cd ceres-solver && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_DOCUMENTATION=ON \
          -DEIGENSPARSE=ON \
          -DEIGEN_INCLUDE_DIR_HINTS=/usr/local/include/eigen3 \
          -DEIGEN_INCLUDE_DIR=/usr/local/include/eigen3 \
          .. && \
    make -j4 && \
    make install && \
    cd .. && rm -rf build

RUN mkdir /opt/bin

RUN git clone --recursive https://github.com/openMVG/openMVG.git --branch develop;
RUN  mkdir openMVG_build && cd openMVG_build; \
  cmake -DCMAKE_BUILD_TYPE=RELEASE \
    -DTARGET_ARCHITECTURE=core \
    -DCMAKE_INSTALL_PREFIX="/opt" \
    -DOpenMVG_BUILD_TESTS=OFF \
    -DOpenMVG_BUILD_EXAMPLES=OFF \
    -DOpenMVG_BUILD_DOC=OFF \
    -DOpenMVG_BUILD_OPENGL_EXAMPLES=OFF \
    -DOpenMVG_USE_OPENCV=ON \
    -DOpenMVG_USE_OCVSIFT=OFF \
     ../openMVG/src; \
  make -j 4 && make install; \
  cp ../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt /opt/bin/; \
  cd .. && rm -rf openMVG_build

ENV PATH $PATH:/opt/bin
```

Any ideas how to fix it?

**Comment by pmoulon** [comment]
Hello. Either use the internal version of Ceres or an older one or even better help us make fix for the last API.

**Comment by SmthFail** [comment]
> Hello. Either use the internal version of Ceres or an older one or even better help us make fix for the last API.

The reason of using last version of ceres  - openmvs crash with "free(): invalid pointer" error when build even with a stable ceres 2.1.0, but works fine with develop version of it (in my test openMVG can be built with ceres 2.1.0).
May be i'll try to fix API, but honestly I'm not good in c++

**Comment by pmoulon** [comment]
Hello @SmthFail .
Could you please try https://github.com/openMVG/openMVG/tree/develop_ceres_manifold and see if it fixes your issue with external build?

**Comment by yanxke** [comment]
I tried the Docker build on https://github.com/openMVG/openMVG/tree/develop_ceres_manifold and the latest develop branch and both fail on

In file included from /opt/openMVG/src/openMVG/multiview/rotation_averaging_l1.cpp:37:0:
/usr/include/eigen3/Eigen/SparseCholesky:34:2: error: #error The SparseCholesky module has nothing to offer in MPL2 only mode
 #error The SparseCholesky module has nothing to offer in MPL2 only mode
  ^~~~~

In file included from /usr/include/eigen3/Eigen/SparseCholesky:37:0,
                 from /opt/openMVG/src/openMVG/multiview/rotation_averaging_l1.cpp:37:
/usr/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:266:72: error: 'AMDOrdering' does not name a type; did you mean 'COLAMDOrdering'?
 template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::StorageIndex> > class SimplicialLLT;
                                                                        ^~~~~~~~~~~
                                                                        COLAMDOrdering

Anyone gotten a successful Docker build?

**Comment by yanxke** [comment]
> I tried the Docker build on https://github.com/openMVG/openMVG/tree/develop_ceres_manifold and the latest develop branch and both fail on
> 
> In file included from /opt/openMVG/src/openMVG/multiview/rotation_averaging_l1.cpp:37:0: /usr/include/eigen3/Eigen/SparseCholesky:34:2: error: #error The SparseCholesky module has nothing to offer in MPL2 only mode #error The SparseCholesky module has nothing to offer in MPL2 only mode ^~~~~
> 
> In file included from /usr/include/eigen3/Eigen/SparseCholesky:37:0, from /opt/openMVG/src/openMVG/multiview/rotation_averaging_l1.cpp:37: /usr/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:266:72: error: 'AMDOrdering' does not name a type; did you mean 'COLAMDOrdering'? template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering > class SimplicialLLT; ^~~~~~~~~~~ COLAMDOrdering
> 
> Anyone gotten a successful Docker build?

See https://github.com/openMVG/openMVG/pull/2158

**Comment by pmoulon** [comment]
Thank for reporting your issue.
I think another user hit this issue and updating Eigen solved it.

**Comment by SmthFail** [comment]
@pmoulon Thank for fixing problem. Sorry for late answer, I haven't got enough time and finished test only 2 hours ago. Build work, but it seems a lot of problem if you build ceres with CUDA support. But i need check it carefully and may be open another issue or create pr. Should i close this issue?

**Comment by pmoulon** [comment]
Regarding Cuda it should not be an OpenMVG issue since it is related to Ceres build system. Maybe we can add an option to make the Cuda back end available via command line (but let's check first if there is speed improvement)

**Comment by SmthFail** [comment]
@pmoulon Ok. I'll test it may be in a week or two and then create a new issue or pr. When i tried last time to build ceres and openmvg with cuda it was some problems with openmvg cmake (it can't correctly find CUDA library and i wasn't fix all problems with a little of efforts). For now I think i can close this issue

**Comment by fratopa** [comment]
Hi, I found an easy fix. Commenting out the line `add_definitions(-DEIGEN_MPL2_ONLY)` in the CMakeLists.txt solves the problem. 
Googling what that option does it seem to be related to some part of eigen having different licenses, so if that matters to you this might not be an adequate solution.
