### ISSUE TITLE
WARNING: [E_ACRobust.hpp:89] Skip this pair. No intrinsic information: (x, y)

### ISSUE THREAD

**Issue by yanxke** [openMVG/openMVG#2164]
This happens sporadically on some of the images in a set of images I try to process.  They are all taken by the same camera and I already have the camera in the sensor size database.  What's the root cause of this error message and how do I fix it?

**Comment by pmoulon** [comment]
Hi, if the pair is skipped it seems that the images was not associated with a camera in the sensor database.
What is the output of your SfMInit_ImageListing.
It should say 
```
usable #File(s) listed in sfm_data: X
usable #Intrinsic(s) listed in sfm_data: Y
 ```

**Comment by yanxke** [comment]
```
listed #File(s): 5462
usable #File(s) listed in sfm_data: 5462
usable #Intrinsic(s) listed in sfm_data: 1

```

**Comment by pmoulon** [comment]
It seems all image are attached to a single data intrinsic. Can you look the sfm_data file a d see if all images are attached to the intrinsic_id == 0

**Comment by yanxke** [comment]
It seems like there are 5238 with id_intrinsic: 0 and 224 with id_intrinsic: 4294967295

**Comment by pmoulon** [comment]
The large number means that some images are not associated with any Intrinsics. So they have not been match with the sensor database.

**Comment by yanxke** [comment]
I'm not sure I understand this.  All of the images were taken by the same cell phone within a short amount of time with EXIF attached.  SfMInit_ImageListing didn't give any warnings about images not matching the sensor database.  What else could cause the intrinsics to be not associated?

**Comment by pmoulon** [comment]
Would you like to share one image that works and one that don't openmvg-team[AT]googlegroups.com with the entry you made to your sensor database so we could debug?

**Comment by yanxke** [comment]
Thanks for the offer!  I'll prepare some data and send it over.

**Comment by liyunfei0302** [comment]
So, has this issue been resolved? I'm encountering the same problem. I suspect it might be due to lighting conditions during object capture.
