### ISSUE TITLE
Getting Access Denied on VS 2022 when compiling openMVG solution

### ISSUE THREAD

**Issue by Jake-The-D0g** [openMVG/openMVG#2166]
Windows 10, CMake 3.26.0, Visual Studio 17 2022

I'm having a similar issue like that of #1667 where I have done everything up to the point that I just need to compile the the solution but I keep getting an access denied 

![image](https://user-images.githubusercontent.com/118870209/219274608-39aa242d-7d12-4a9e-8a8c-6d2d669dee95.png)

I'm very new to this stuff, but I did set the target to Release and debug and got the same results, is there a work around for this or is there a fix that I might have missed? I did see a fix for doing it in python but I don't really know where to even begin with that.

**Comment by pmoulon** [comment]
The error is because you are trying to run the project ALL_BUILD, which you cannot run. You need to select a project in your Visual Studio solution which you CAN run, one which generates an executable. To do this right click on the project which creates the executable and select “Set as Startup Project”.

By compiling all build it will build all libraries and binaries. Then go to your build folder and run the binaries from there or use the python script to run the binaries.

**Comment by Jake-The-D0g** [comment]
So I ended up selecting something like "openMVG_features" which I believe has a project in it, but I get another error

![image](https://user-images.githubusercontent.com/118870209/219432643-58ccac0f-d3fd-406b-bd3e-fb51764105c5.png)

**Comment by pmoulon** [comment]
Same here you are trying to run a librairie. Select all build and build. Then all binaries will be compiled

**Comment by pmoulon** [comment]
Also you will better to select release mode

**Comment by Jake-The-D0g** [comment]
So I right clicked all build and selected build and it gives me a message in the ouput

![image](https://user-images.githubusercontent.com/118870209/219487055-7d773fdc-4e47-4e39-9ea6-551270f80e92.png)

I tried to run again but I think I am not understanding where to right click for the "set as startup project"? What would that file type be?

**Comment by Jake-The-D0g** [comment]
I also switched the target to Release

**Comment by pmoulon** [comment]
Good so it seems that all the target has been compiled, go check the compile folder and you will have a folder with all the binaries and libraries compiled

**Comment by Jake-The-D0g** [comment]
Is the compile folder where I designated my build in cmake from the src? What type of file is created? Below I have the image of the build file after I generated what was configured in cmake. From there I opened the openmvg solution and selected build on all_build.

![image](https://user-images.githubusercontent.com/118870209/219557605-275265fa-8b60-49cc-88ca-7798c9aae328.png)

**Comment by pmoulon** [comment]
Binaries will be in the windows-AMD64 folder

**Comment by Jake-The-D0g** [comment]
So I see the libraries and .exe files, which I assume are the binaries. How do I go about displaying the windows? (apologies if these answers are very basic, I'm very new to this process)

**Comment by Jake-The-D0g** [comment]
I see the file that has all this in it but I am not seeing it in VS 2022

**Comment by pmoulon** [comment]
Openmvg is all about command line tools. See the doc. We have a python script that helps run all the binaries as a chain from an image folder

**Comment by Jake-The-D0g** [comment]
> Openmvg is all about command line tools. See the doc. We have a python script that helps run all the binaries as a chain from an image folder

Thank You! So every thing is fine on my end? Also can you post the link to the doc pls?

**Comment by pmoulon** [comment]
You can find the doc here https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo
