### ISSUE TITLE
Does not support the camera of iphone xr?

### ISSUE THREAD

**Issue by GISerCHAO** [openMVG/openMVG#2170]
I found the iPhone XR camera in the sensor_width_camera_database.txt file, but when I used my own iPhone XR photos as input, I got the error "ERROR: [sequential_SfM.cpp:110] Unable to choose an initial pair, since there is no defined intrinsic data. INFO: [sequential_SfM.cpp:173] Cannot find a valid initial pair - stop reconstruction." What could be the reason for this?

**Comment by pmoulon** [comment]
I would advise you to double check the exif of your image. And eventually print their value in OpenMVG so you can double check what is wrong (print the value of sModel here  https://github.com/openMVG/openMVG/blob/3b191277b5f60a9a4c6951dcefabcbf76b2505ec/src/openMVG/exif/sensor_width_database/ParseDatabase.hpp#L66)

**Comment by nanhaishiyounan** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/24801059/223904901-fe05394c-a508-4738-8575-709ab93c929e.png">
Same problem, solved?

**Comment by pmoulon** [comment]
Happy that you found a fix.
