### ISSUE TITLE
CMAKE_CXX_COMPILER coudn't be found

### ISSUE THREAD

**Issue by Jake-The-D0g** [openMVG/openMVG#2172]
Using the Linux development environment on a Chromebook.

The cmake version I installed is 3.18.4 (saying it's the latest)

When I try to compile I get this

![image](https://user-images.githubusercontent.com/118870209/223581152-79bc8c7e-8c39-4046-844a-8ad8705c3016.png)

**Comment by pmoulon** [comment]
Do you have gcc and g++ installed?

**Comment by Jake-The-D0g** [comment]
gcc

> Do you have gcc and g++ installed?

**Comment by pmoulon** [comment]
Gcc is a c compiler
You will need g++ to compile c++

**Comment by pmoulon** [comment]
Closing the issue. Feel free to share here later some reconstruction 😀
