### ISSUE TITLE
Image orientation is not properly removed internally

### ISSUE THREAD

**Issue by 4CJ7T** [openMVG/openMVG#2182]
Manually setting focal length properly sets the intrinsics.

When using OpenMVS I see two camera models when there should only be one.
The modules end up failing to process.

**Comment by pmoulon** [comment]
It is most likely because you have two focal groups in your OpenMVG scene. Check your initial sfmdata.josn and also the one after SFM by using the convert SFM data format binary to export your sfm_data.bin to a sfm_data.json.

Did you check how many images are in each focal groups?

**Comment by 4CJ7T** [comment]
If that is the case then OpenMVG2OpenMVS does not properly orient the images.

53/53
# Image orientation:
    26 Horizontal (normal)
     1 Rotate 270 CW
    15 Rotate 90 CW
    11 Rotate 180

**Comment by 4CJ7T** [comment]
https://user-images.githubusercontent.com/108303308/226818194-c02fe742-149e-42db-803b-c8bc43dcf163.mp4

**Comment by 4CJ7T** [comment]
Undistorted images are fine and intrinsics seem right but it still does not process correctly.
