### ISSUE TITLE
Issue loading in valid SFM data

### ISSUE THREAD

**Issue by ChrisRuff** [openMVG/openMVG#2187]
I'm trying to use OpenMVG as a library but am running into an issue with my configuration, most likely Eigen.
This is my code:
```cpp
std::cout << "Skipping SfM" << std::endl;
if(!openMVG::sfm::Load(this->sfm_data,
  paths::recon_dir / "sfm_data.json",
  openMVG::sfm::ESfM_Data(openMVG::sfm::ALL)))
{
  std::cout << "Could not load SfM data, re-running SfM" << std::endl;
  return runSFM(true);
}
std::cout << 
           sfm_data.structure.begin()->second.obs.at(0).x.x() << " " << 
           sfm_data.structure.begin()->second.obs.at(0).x.y() << std::endl;
			

return true;
```
Basically when stepping through the load function of the SFM data after a completed analysis provides correct results:
![Peek 2023-04-11 11-58](https://user-images.githubusercontent.com/46638807/231203837-b15654f3-8c0b-4307-ace7-0b02b580d5d8.gif)

But running the exact same code on the same data with the breakpoint on the return statement yields this:
![image](https://user-images.githubusercontent.com/46638807/231204689-2625de81-a48f-43f7-b082-2bae93118074.png)

I've noticed that the correct results are shown with this Eigen struct with 16 as the final template parameter:
![image](https://user-images.githubusercontent.com/46638807/231204032-b0a753da-e671-4af2-98df-6fc4ec55f1c1.png)
Whereas the invalid results have a different templated parameter on the eigen's plain_array
![image](https://user-images.githubusercontent.com/46638807/231205508-38db7551-ed85-46ef-93c3-384bc33f9a01.png)

In both cases the cout of the structure prints:
![image](https://user-images.githubusercontent.com/46638807/231204884-264548fe-0b22-4449-af61-e2d341f9e7f9.png)

Also worth noting that the json file does contain valid data:
```json
    "structure": [
        {
            "key": 24,
            "value": {
                "X": [
                    -0.035685525492854048,
                    -0.973418088548176,
                    1.5638754004963345
                ],
                "observations": [
                    {
                        "key": 0,
                        "value": {
                            "id_feat": 83,
                            "x": [
                                3293.06005859375,
                                759.1170043945313
                            ]
                        }
                    },
                    {
                        "key": 4,
                        "value": {
                            "id_feat": 33,
                            "x": [
                                3280.81005859375,
                                936.4739990234375
                            ]
                        }
                    },
                    {
                        "key": 6,
                        "value": {
                            "id_feat": 16165,
                            "x": [
                                3364.949951171875,
                                23.062700271606447
                            ]
                        }
                    },
                    {
                        "key": 12,
                        "value": {
                            "id_feat": 2,
                            "x": [
                                3058.25,
                                46.99359893798828
                            ]
                        }
                    }
                ]
            }
        },
```

Ive been struggling with this for quite some time and would love any help if possible. In terms of environment, I'm running arch linux, I've installed the latest develop and the rainbow trout release(both have this issue). I am using conan for other packages in my project and have forced openMVG and my project to use the same Eigen to no avail.

**Comment by ChrisRuff** [comment]
![image](https://user-images.githubusercontent.com/46638807/231218999-c2457b13-6b3b-4dc9-ba0f-6529f4be4486.png)
Just found that this will give me the x and y coordinates that I want. Not sure if this is a fix, more so a workaround so I wont close the issue

**Comment by pmoulon** [comment]
Sorry for the late answer,

Could be related to the compilation preprocessor being different between OpenMVG and your project.

Maybe call the same script for OptimizeForArchitecture in your code https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L121

**Comment by ChrisRuff** [comment]
No problem, I appreciate how active you are on this project.

Ill give that a try soon and see if that fixes the issue

**Comment by ChrisRuff** [comment]
No dice, I even tried the Conan package to create an isolated build environment hopefully. 

But that does lead me to another potential cause. In my cmake, I define this flag because without it, openMVG has a segfault in GroupSharedIntrinsics.

```
add_compile_definitions(EIGEN_DONT_VECTORIZE=1)
```
Could be a cause, but i cant run the program without it...

**Comment by ChrisRuff** [comment]
Looking back this was a mistake with another part of my code, which is quite embarrassing it slipped past me, originally I didn't want to copy over the options from openMVG, because of conflicting options that I had set. 

This code was responsible for that
```
foreach(openMVG_target OpenMVG::openMVG_stlplus OpenMVG::openMVG_easyexif OpenMVG::openMVG_fast OpenMVG::openMVG_camera OpenMVG::openMVG_exif OpenMVG::openMVG_features OpenMVG::openMVG_graph OpenMVG::openMVG_image OpenMVG::openMVG_linearProgramming OpenMVG::openMVG_lInftyComputerVision OpenMVG::openMVG_geodesy OpenMVG::openMVG_geometry OpenMVG::openMVG_matching OpenMVG::openMVG_kvld OpenMVG::openMVG_matching_image_collection OpenMVG::openMVG_multiview OpenMVG::openMVG_numeric OpenMVG::openMVG_robust_estimation OpenMVG::openMVG_system OpenMVG::openMVG_sfm OpenMVG::vlsift)
	get_target_property(compile_options ${openMVG_target} INTERFACE_COMPILE_OPTIONS)
	message(STATUS "Removing ${compile_options} from ${openMVG_target}")
	set_target_properties(${openMVG_target} PROPERTIES INTERFACE_COMPILE_OPTIONS "")
endforeach()
```

After reading your comment, I realized that this was probably the cause and deleted it, but at the same time added the call to OptimizeForArchitecture. Adding that call cause the error as well. I was able to fix it by removing the optimize call, as well as the for-each loop. I appreciate your help.
