### ISSUE TITLE
OpenMVG2OpenMVS | Mask path

### ISSUE THREAD

**Issue by 4CJ7T** [openMVG/openMVG#2192]
![image](https://user-images.githubusercontent.com/108303308/234497484-b825b607-033c-4fe9-9e70-d1133667b536.png)
Full path to image mask is being set instead of `"<undistorted_images_folder_name>\\image_name.mask.png"`.

**Comment by 4CJ7T** [comment]
@Sanheiii <3

**Comment by Sanheiii** [comment]
Not only the image.maskName, but also the image.name is written to an absolute path. This is not a complex problem and you can easily fix it.

**Comment by 4CJ7T** [comment]
That is weird. I might use stlplus::folder_part if I can not find what is causing that for imageName.

**Comment by 4CJ7T** [comment]
https://github.com/openMVG/openMVG/commit/0842de99c8a0e28d7fff40baaa628ba9c9c72cef

**Comment by abhimanyuchadha96** [comment]
@Sanheiii Can you elaborate on the issue?
Facing this at the moment:-
<img width="659" alt="Screenshot 2024-08-13 at 12 29 50 AM" src="https://github.com/user-attachments/assets/1bcb5df2-0889-40d6-a330-3ff33bc1793d">

**Comment by Sanheiii** [comment]
> @Sanheiii Can you elaborate on the issue? Facing this at the moment:- <img alt="Screenshot 2024-08-13 at 12 29 50 AM" width="659" src="https://private-user-images.githubusercontent.com/37940438/357318627-1bcb5df2-0889-40d6-a330-3ff33bc1793d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTg5MTMsIm5iZiI6MTcyMzU5ODYxMywicGF0aCI6Ii8zNzk0MDQzOC8zNTczMTg2MjctMWJjYjVkZjItMDg4OS00MGQ2LWEzMzAtM2ZmMzNiYzE3OTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAxMjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhN2FiOGUwMWM4NGFlYmU4M2FlMjlkZDY3NzI0MTU0ZTY3ODU4Mjc3NjE3NWViNjEyMzBhYjY4NTNiNmFkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9vkWfzQm9CoBT4s2YoUBYAvOINQ4E7fJ-30HqXSI4AI">

The path for the maskImage has already been written into the mvs file, so there is no need to pass the mask-path parameter.

**Comment by abhimanyuchadha96** [comment]
@Sanheiii I elaborated the issue in these two:-
https://github.com/openMVG/openMVG/issues/2348
https://github.com/cdcseacave/openMVS/issues/980
