### ISSUE TITLE
ComputeFeatures doesn't utilize many CPU cores fully

### ISSUE THREAD

**Issue by bouk** [openMVG/openMVG#2198]
Hi, I'm running openmvg in a pipeline on an EC2 c6a.48xlarge machine which has 192 cores. When looking at `htop` I can see that the cores spike up to full usage and then fall back to only one core being at 100% constantly, for a total load avg of only ~30% (htop screenshot below). I'm speculating that this is caused by [the `dynamic` openmp scheduling
](https://github.com/openMVG/openMVG/blob/b9024c3117f4df283bb58c6474ee2c224e6c884e/src/software/SfM/main_ComputeFeatures.cpp#L266) having a lot of overhead.

I'll do some testing using a different scheduling strategy but I just wanted to open this issue to track it

```
INFO: [main_ComputeFeatures.cpp:120]  You called :
/run/current-system/sw/bin/openMVG_main_ComputeFeatures
--input_file /root/output/sfm/matches/sfm_data.json
--outdir /root/output/sfm/matches
--describerMethod SIFT
--upright 0
--describerPreset HIGH
--force 0
--numThreads 0

INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 10%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 20%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 30%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 40%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 50%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 60%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 70%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 80%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 90%
INFO: [loggerprogress.hpp:79] [- EXTRACT FEATURES -] 100%
INFO: [main_ComputeFeatures.cpp:343] Task done in (s): 707
```

Htop constantly cycles between these three screens:

<img width="3008" alt="Screenshot 2023-05-16 at 12 47 19" src="https://github.com/openMVG/openMVG/assets/97820/aed1223b-751a-4cf0-9863-2c9910160b9f">
<img width="3008" alt="Screenshot 2023-05-16 at 12 47 21" src="https://github.com/openMVG/openMVG/assets/97820/7697dc26-8b78-4414-ab27-7edb058a894c">
<img width="3008" alt="Screenshot 2023-05-16 at 12 47 13" src="https://github.com/openMVG/openMVG/assets/97820/54946d03-d56d-4df1-8b8c-678bb7e20303">

**Comment by pmoulon** [comment]
Did you try to use -n 192 or another number?

**Comment by pmoulon** [comment]
Closing due to lack of feedback, feel free to reopen
