### ISSUE TITLE
Getting " Cannot find a valid initial pair" when working with video data

### ISSUE THREAD

**Issue by nebis-software** [openMVG/openMVG#2205]
Hi all,
   newbie here! I am trying to work with images extracted from a video. I extracted the frames with ffmpeg, and then I run:

` python SfM_GlobalPipeline.py  video_frames/   output
`
and I get the error:

```
ERROR: [sequential_SfM.cpp:110] Unable to choose an initial pair, since there is no defined intrinsic data.
INFO: [sequential_SfM.cpp:173] Cannot find a valid initial pair - stop reconstruction.
7. Colorize Structure
ERROR: [main_ComputeSfM_DataColor.cpp:69] The input SfM_Data file "output/reconstruction_sequential/sfm_data.bin" cannot be read.
```

From what I read in the docs it seems I am missing the camera information.... is it correct? if yes, how can i supply a "default" one?
Thanks!

**Comment by pmoulon** [comment]
Hi, you need to specify a valid initial focal length, see here https://github.com/openMVG/openMVG/issues/669#issuecomment-258584371

Just add a value with `-f X` in the openMVG_main_SfMInit_ImageListing line, with X being 1.2*max(width, height) as a value depending of your images

**Comment by nebis-software** [comment]
Works, thanks!
