### ISSUE TITLE
Question: I couldn't find the -v or --video_mode_matching option in the openMVG_main_ComputeMatches step as mentioned in the documentation.

### ISSUE THREAD

**Issue by anasel01** [openMVG/openMVG#2218]
Hello, I would like to inquire about the availability of the -v or --video_mode_matching option in the openMVG_main_ComputeMatches step. I have a series of images obtained from a video and I was interested in using the -v option, but I couldn't find it in the main_ComputeMatches.cpp file.

**Comment by pmoulon** [comment]
The option moved in this main_PairGenerator binary https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_PairGenerator.cpp#L39

For more flexibility we have now a temporary binary that can be used to generate a pair file, and then you compute ComputeMatches on it
