### ISSUE TITLE
color_harmonization

### ISSUE THREAD

**Issue by jkff00** [openMVG/openMVG#2223]
Hello!
Using only Gain and OFFSET to adjust the color will make the image become unclear, has it been considered to increase the gamma change and adjust the image color non-linearly?

**Comment by pmoulon** [comment]
Sorry for the late reply.
We used linear factor there as a demonstration of what can be done to have a optimal solution computed using Linear Programming.

Using more complex model could work but would be have to be optimized in a different way (Non Linear Optimization)

**Comment by pmoulon** [comment]
Feel free to see how to extend the model and how it fits your needs
