### ISSUE TITLE
[Question] Can some one explain the meanings of the variables in the `sfm_data.bin`

### ISSUE THREAD

**Issue by dinushazoomi** [openMVG/openMVG#2226]
Hi all, I am new to the openMVG and the process of SFM, Can someone briefly explain the words in the `structure` section of the `sfm_data.bin`, I converted it to the JSON format. Thanks in advance

```
"structure": [
        {
            "key": 1348,
            "value": {
                "X": [
                    0.3341199078677005,
                    -0.4791115477355175,
                    1.8397770462504429
                ],
                "observations": [
                    {
                        "key": 0,
                        "value": {
                            "id_feat": 2339,
                            "x": [
                                3323.739990234375,
                                657.6119995117188
                            ]
                        }

```

1. what is the `key: 1348`
2. what is the
```
 X: [
                    0.3341199078677005,
                    -0.4791115477355175,
                    1.8397770462504429
                ]
```
5. what is `observations`
6. what is `key: 0` in `observations`
7. what is `id_feat: 2339`
8. what is 
```
x: [
                                3323.739990234375,
                                657.6119995117188
                            ] `
```

Another side question,
Is there a way to convert `cloud_and_poses.ply` to JSON? or it includes the data in the `structure` section of the `sfm_data.bin`

**Comment by pmoulon** [comment]
A partial answer is available here https://github.com/openMVG/openMVG/wiki/OpenMVG-data-structures


Things are easier when you use OpenMVG API to read this file, so you dont have to interpret the field manually.
and here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp

> 1. what is the key: 1348
 This is the ID of a 3D point and its observations

> what is the X. [ ...]
 This is the 3D point coordinates

> what is observations
 This is the list of 2d observations of this 3D point

> what is key: 0 in observations
 This is the ViewID observing this 3d point (see views)

> what is id_feat: 2339
 This is the ID of the feature in the feature file, or the loaded feature in memory

> what is x
 This is the 2d observation (the position of the feature in the depicted view)

> Is there a way to convert cloud_and_poses.ply to JSON? or it includes the data in the structure section of the sfm_data.bin
 cloud_and_poses is exported from data stored in the sfm_data.bin see the exporter and converter SfmDataConverter binary

**Comment by dinushazoomi** [comment]
@pmoulon Thank you fro the answars

**Comment by pmoulon** [comment]
You're welcome!
