### ISSUE TITLE
Retrieve arbitrary 2D image locations in the 3D scene

### ISSUE THREAD

**Issue by ChrisRuff** [openMVG/openMVG#2228]
I'm sorry if this has been asked previously, but I'm curious if it's possible with openMVG to take a specific 2d location on an image and determine where it would be in 3D, even if it wasn't a distinct feature that was used in the analysis. I am aware that we can get nearby points from the sfm_data by iterating through the structure and attempting to find 2d points that are approximately in the same location but I need higher precision. 

I appreciate your time and any feedback.

**Comment by pmoulon** [comment]
Hello @ChrisRuff,
OpenMVG and most SfM package are Features based, so it means that if the 2D patch you are taking is large enough, maybe enough feature will be there to have a sparse 3D representation for you to use.

I think most of the approach that would work for your problem, would need to be hierarchical:
1- find the images that could be candidate for your input image (image search, i.e VLAD)
2- extract feature on demand for this neighborhood with `dense` SIFT settings and triangulate those correspondences using the know SfM structure
3- Localize your image, and then optimize locally

I think @tsattler would comment better by citing some of the work and presentation he made in various image localization workshops

**Comment by tsattler** [comment]
Why not do a dense reconstruction of the scene? It will still not provide a 3D point for each pixel (especially not for the sky), but if there is a corresponding point, it can be obtained by rendering depth maps.

**Comment by ChrisRuff** [comment]
I am using colmap for dense reconstruction, but I wasnt able to find a relationship between the densified 3D points and the specific 2D points that I was looking for.  That would probably be the ideal solution. 

I like your solution though @pmoulon. I have a vector of specific points that i'm looking for in each of my input images that I would like to have corresponding points in 3D, so I can set each of those points as features in my analysis and use the points that were able to be matched. 

If @tsattler had any more info about how he may approach that solution Id love to look into that, I don't currently grasp how I would go about that currently though.

**Comment by tsattler** [comment]
I was thinking that if you have a dense depth map per image and would like to know the 3D point for a pixel, you can simply look up the depth value and then compute the corresponding 3D point using the known intrinsic and extrinsic calibration of the camera.
