### ISSUE TITLE
No libs are created !!!

### ISSUE THREAD

**Issue by ChangyeGuo** [openMVG/openMVG#223]
I am trying to compile the libraries via VS 2010. But I'm troubled in the comments in the BUILD TEXT:
 "Adding following lines to your CMakeLists.txt should provide OpenMVG usable as static library:
 add_subdirectory(openMVG/src)
 include_directories(${OpenMVG_INCLUDES})
 target_link_libraries(target ${OpenMVG_LIBS})"
I don't know what exactly I should do. So when I compile them on visual studio, the libs such as flann_s.lib,vlsift.lib cannot be found. 
Dose any one meet the same case?

**Comment by pmoulon** [comment]
Hi @ChangyeGuo 

You can use openMVG as third_party in two ways:

1. Follow the way explained in the BUILD file:
include the whole openMVG directory in your project.
Normally the vlsift lib must be defined.
Ensure you have compiled them all, right click compile on the traget.
Check also they are on disk.
If they are on disk and not usable by cmake, it's perhaps it does have the directory in the library name.

2. Use openMVG with a FindOpenMVG.cmake (WIP)
I will add this way:
compile the lib, install it..
And use Find_module(OpenMVG)
It's a WIP feature: https://github.com/openMVG/openMVG/issues/222

Regards,

**Comment by ChangyeGuo** [comment]
Sorry for delayed answer. I have tried another approach to solve it. I am a primer to study this interest and thanks  Pmoulon.
