### ISSUE TITLE
The accuracy of 3D measurements based on OpenMVG 3D reconstruction

### ISSUE THREAD

**Issue by chathui** [openMVG/openMVG#2230]
Hello,

I am trying to measure real-world distances using OpenMVG. My input images have some radial distortion. I am wondering if OpenMVG has a built-in distortion correction to ensure the optimal reconstruction. 
Really appreciate any clarification.

Thanks in advance!
C.

**Comment by 4CJ7T** [comment]
Depending on the quality of your dataset you may want to rerun structure from motion using the previously found focal length.

**Comment by chathui** [comment]
Reply: "Depending on the quality of your dataset you may want to rerun structure from motion using the previously found focal length."

Thanks for your reply. So I think we rerun pipeline with sfm_data inside ./reconstruction_global , starting at step #2 of the pipeline

**Comment by pmoulon** [comment]
Yes OpenMVG provide different camera model that support distortion. The default one is having a radial 3 factors that should fit most of camera you can use. By comparison (Bundler when released was using a radial 1 model with a fixe principal point at the middle of the image. 

Regarding accuracy, there is various factors that comes into play:
- accuracy of your camera intrinsics
- accuracy of the camera extrinsics
- accuracy of the scene (triangulation)

Most of the time following rules on image capture and or pre calibration can help you get better accuracy than just have all the system guessing everything.

For maximum accuracy people are most of the time using (for surveys):
- gps rtk
- control points (know 3d location and 2d location)
OpenMVG provides partial implementation supports for those.

**Comment by pmoulon** [comment]
Closing but feel free to reopen if more questions
