### ISSUE TITLE
Point cloud size is much smaller then expected

### ISSUE THREAD

**Issue by maazraan** [openMVG/openMVG#2232]
i generated point cloud for a dataset using both opensfm and openmvg but the point cloud generated by openmvg is 100 times smaller then opensfm although the structure is same. How to correct the size scale of the pointcloud ?

**Comment by pmoulon** [comment]
Hello @maazraan SfM results are up to scale, or else you need to apply some knowledge about the scene or image positioning (ControlPoint, GPS).
Do you have such information?
Else you can quickly compute the average size of the camera positions, and rescale one reconstruction to scale the other one.
