### ISSUE TITLE
Removing GLFW dependency from default compilation

### ISSUE THREAD

**Issue by rperrot** [openMVG/openMVG#224]
Is-it possible to remove all stuff that need GLFW library in a default compilation mode ? 

Since openMVG core apps don't need it, it should be placed as optional, isn't it ?

**Comment by pmoulon** [comment]
GLFW is just used by the sample SfMViewer
https://github.com/openMVG/openMVG/blob/master/src/software/SfMViewer/CMakeLists.txt

The SfMViewer is just not build on APPLE target
https://github.com/openMVG/openMVG/blob/master/src/software/CMakeLists.txt

We could consider to make optional the compilation of this target with a cmake compilation flag:
OPENMVG_COMPILE_OPENGL_SAMPLE

**Comment by rperrot** [comment]
Yes I think it's a good idea to make it optional, since it removes a dependency for default compilation. 

(And the issue is not related to APPLE ;-), for once ... )

**Comment by fabiencastan** [comment]
+1

**Comment by pmoulon** [comment]
@rperrot :+1: 
@fabiencastan Done

BTW, it clearly show that we must maintain & update openGL sample in the future.

**Comment by rperrot** [comment]
> BTW, it clearly show that we must maintain & update openGL sample in the future.

Yes, and with more time, add webGL support to visualize output. (just a question of time !!!)

**Comment by pmoulon** [comment]
Yep, I still consider add it to the 0.8 version ;-)
https://github.com/openMVG/openMVG/pull/87
