### ISSUE TITLE
Unit of RMSE

### ISSUE THREAD

**Issue by maazraan** [openMVG/openMVG#2241]
I used gcps which are in UTM co-ordinate system and got the RMSE for a point cloud bundle adjused with 4 GCPs as 0.86. I want to know whats the unit of RMSE and also, if its in meters is there any method to reduce it to some extent.

**Comment by pmoulon** [comment]
RMSE at Bundle adjustment time is shared in pixel value. We report the fitting in meters only for rigid registration in the GCP GUI app.

Eventually share here the log you see so we can better help and provide feedback
