### ISSUE TITLE
How could I add new camera model like Pinhole_Intrinsic_Test

### ISSUE THREAD

**Issue by NewNameHard** [openMVG/openMVG#2252]
I want to add a new camera model for e_User_camera_model. But there are always an error which is
0x76C590E2 处(位于 openMVG.exe 中)有未经处理的异常: Microsoft C++ 异常: cereal::Exception，位于内存位置 0x00D8F090 处。0x76C590E2 处(位于 openMVG.exe 中)有未经处理的异常: Microsoft C++ 异常: cereal::Exception，位于内存位置 0x00D8F090 处。
I have written Camera_Pinhole_Test.hpp and Camera_Pinhole_Test_io.hpp, but I don't know how to fix this.

**Comment by pmoulon** [comment]
Seems like your camera model is not added in the serialization did you include it in cameras_io.hpp?

Be also sure to have the cereal register type and cereal register polymorphic right....

**Comment by NewNameHard** [comment]
Thank you for your response. I have solved this problem. I need to recompile the source code, but I forgot to do it.

**Comment by pmoulon** [comment]
Happy that it worked. Have fun with OpenMVG and don't hesitate to ask questions to the community
