### ISSUE TITLE
Understanding camera raw images 

### ISSUE THREAD

**Issue by airar-dev** [openMVG/openMVG#2263]
How are you? 

First of all, thank you for making such a good library.

I have a question about using openmvg.

Currently I am using Unity3d and openmvg to create a 

VPS app using Unity3d and openmvg.

But here I have a question about the camera raw image.

I am getting the camera raw image after fixing the unity ar mapping app in portrait mode to reconstruct the sfm.

 _Fix the app in portrait mode_
 
1. Mobile phone in portrait mode 

![0 (2)](https://github.com/openMVG/openMVG/assets/65946259/838d3fa1-a237-4e7f-a372-e993d741c409)

2.Tilting the phone towards the Landscapeleft to take a picture

![1 (1)](https://github.com/openMVG/openMVG/assets/65946259/dcd83da4-e5a8-4897-b82c-81e366a93167)

3. Shooting with the phone in portrait mode upside down

![2 (1)](https://github.com/openMVG/openMVG/assets/65946259/6b84360f-ef6f-4188-a3b6-784f88781011)

4. Phone tilted to landscaperight

![3 (1)](https://github.com/openMVG/openMVG/assets/65946259/1b4b5e1b-7bdb-4a31-a6ab-21505b3c1ff7)

All photos above are raw camera images.

The internal and external camera parameters are available in unity3d ar foundation.

In my case, what orientation should I fix the image in when reconstructing in openmvg?

Thanks for your work.

**Comment by pmoulon** [comment]
Orientation should not matter for OpenMVG, since we are using Scale Rotation Invariant features (SIFT). But from a practical viewpoint you would certainly prefer to use the orientation that make sense for the user.

**Comment by airar-dev** [comment]
Thank you for your response.

I used akaze.

I rotated the acquired camera pose values and

I generated the PLY by rotating the raw image in one direction.

This resulted in the data I was looking for. 

Thanks.
