### ISSUE TITLE
cuda related error!!

### ISSUE THREAD

**Issue by officeritwik11** [openMVG/openMVG#2266]
after `sudo make -j8 install` command

make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/build.make:348: libs/MVS/CMakeFiles/MVS.dir/PatchMatchCUDA.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:505: libs/MVS/CMakeFiles/MVS.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by pmoulon** [comment]
Seems like to be OpenMVS related and not OpenMVG.
