### ISSUE TITLE
Can there be a new release tag?

### ISSUE THREAD

**Issue by bmanga** [openMVG/openMVG#2278]
Hi, I think the changes to compile openMVG on non-x86 systems were merged sometime after the latest release (2.0).
Unfortunately this means that package managers (vcpkg in my case) that reference the latest release don't yet work with arm devices.

GIven that 2.0 was released in October 2021, is there a plan to create a new one soon?

**Comment by pmoulon** [comment]
Hi @bmanga, sure I wanted to create a new release since some time, just missing the time to do it. The holiday season will be a good time to create a new one!

**Comment by pmoulon** [comment]
@bmanga here you go https://github.com/openMVG/openMVG/releases/tag/v2.1

**Comment by bmanga** [comment]
Thanks a lot!
