### ISSUE TITLE
RootSIFT

### ISSUE THREAD

**Issue by sweeneychris** [openMVG/openMVG#228]
Line 35 of openMVG/src/patented/sift/SIFT.hpp

RootSIFT comprises of 2 steps: 1) L1 normalization. 2) Element-wise sqrt.

The current code is performing L2 normalization (which is not necessary since VLFeat returns unit-norm descriptors) instead of L2.

**Comment by pmoulon** [comment]
You mean that computing the sum is useless since it is equal to 1 ?

**Comment by sweeneychris** [comment]
Yes, this and the fact that it is not performing L1-normalization.

**Comment by pmoulon** [comment]
Skipping vlfeat L2 normalisation and Hysteresis threshold an option is so necessary :-(
https://github.com/openMVG/openMVG/blob/c4ffda0b755c79c507b0f4386195ba0f1c025135/src/patented/sift/vl/sift.c#L2085

**Comment by sweeneychris** [comment]
Sorry I think something has been lost in translation.... what exactly do you mean? The code you referenced ensures that descriptors are indeed unit norm (or zero), right?

The point still is that there is no L1 normalization performed in your rootSIFT implementation, which is a necessary step for RootSIFT to transfer to Hellinger distance

**Comment by pmoulon** [comment]
I mean the following:

    descriptor.sum() == descriptor->lpNorm<1>();

So as long I do:

    float sum = accumulate(descr, descr+128, 0.0f);
    for (int k=0;k<128;++k)
      out(k) = sqrt(descr[k]/sum));

all is ok.

It does the same thing as:

    const double l1_norm = descriptor->lpNorm<1>();
    *descriptor /= l1_norm;
    *descriptor = descriptor->array().sqrt();

Second point, I wonder if we need to keep the L2 normalisation and high value truncation done here:
https://github.com/sweeneychris/TheiaSfM/blob/8d12f4cfe0a65b74899965efbbeb3d3b94af7cc5/libraries/vlfeat/vl/sift.c#L1887

**Comment by sweeneychris** [comment]
I see, sorry for the confusion. I thought accumulate was related to your Accumulate but it is actually std::accumulate. All seems good then!

**Comment by pmoulon** [comment]
That's why we got confuse ;-)
BTW thanks for your worrying about looking if the code is doing the right thing!
I appreciate ;-)
