### ISSUE TITLE
Focal length in pixel calculation.

### ISSUE THREAD

**Issue by kundu03** [openMVG/openMVG#2282]
Good Morning @pmoulon, currently i am studying OPenMVG library and i came across a problem like what if my drone is not there in the database. Then, I came across your formula for focal_pixel = 1.2 * max(width,height). When i am testing the data for GoPro 10, focal_pixel by this formula is 4800 and the value calculated from the sensor_width given in database is 1153.9708080322662. So, I want to know does it make some problems in future or not.

**Comment by pmoulon** [comment]
Hi.
Do note that the formula is an approximation for an opening of 90 degree. A GoPro is a fish eye lens and so that's why you note a difference. See here https://github.com/openMVG/openMVG/issues/669#issuecomment-258584371

**Comment by kundu03** [comment]
Thank you @pmoulon

**Comment by kundu03** [comment]
Hi @pmoulon , i have one more doubt. Can you please tell how we can give custom keypoints so that we can have our required number of features.

**Comment by pmoulon** [comment]
Custom key point can be provided by filling .feat and match files

**Comment by kundu03** [comment]
Completed
