### ISSUE TITLE
Pixel coordinate system is not translated correctly to world coordinate system

### ISSUE THREAD

**Issue by Jiatutu** [openMVG/openMVG#2290]
I want to use the monograph method to assemble photos. First,I use the four-point coordinates of the photo to convert to world coordinates as follow:
1、The photo coordinates are：
```
std::vector<Vec2> images_points(4);
images_points[0] = Vec2(0, 0);               
images_points[1] = Vec2(cam->w(), 0);        
images_points[2] = Vec2(cam->w(), cam->h()); 
images_points[3] = Vec2(0, cam->h());      
```
2、The conversion method is as follows：
```
// image->cam
Vec2 camPoint = cam->remove_disto(cam->ima2cam(images_points[i]));
// cam->world
Vec3 axis = pose.rotation() * Vec3(camPoint.x(), camPoint.y(), 1.);
ground_points[i] = pose.translation() - axis * (pose.translation().z() / axis.z());
```
When the camera direction changes (or rotation), the result is not correct。

I want to know why the error occurred, doesn't the rotation matrix contain the camera orientation?

**Comment by pmoulon** [comment]
I'm not aware of the monograph method. Do you have any reference to share?
