### ISSUE TITLE
Focal Length in Pixels

### ISSUE THREAD

**Issue by abhimanyuchadha96** [openMVG/openMVG#2295]
Hi @pmoulon 

<img width="289" alt="Screenshot 2024-02-15 at 12 19 57 PM" src="https://github.com/openMVG/openMVG/assets/37940438/703e8e0c-d93d-4e10-92c8-15908b615d3c">

If we are following the formula mentioned [here](https://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata) then 
_max(wpix,hpix)_ = 3840
_focal_mm_ = 13
Then what is the value of _ccdw_mm_ ?

**Comment by pmoulon** [comment]
You have missing parameter to estimate it (cc'd width) but you can approximate the value by using this formula `fpix = 1.2 * max(w,h)` and use the -f option to supply it. What it does is just assume a given a given angular aperture

**Comment by abhimanyuchadha96** [comment]
As per the formula mentioned [here](https://github.com/openMVG/openMVG/issues/669#issuecomment-258584371) the assumption here is that the FOV is 45 degrees but that could easily vary, especially in the Ultrawide sensors of the new iPhones.
Is there any database which provides the width of these new sensors/cameras?

**Comment by pmoulon** [comment]
Unfortunately Apple does not share their ccd sensor width so a guess is better than nothing. You can also consider to make a SfM scene with nice coverage to auto calibrate your focal length from your guess.

**Comment by abhimanyuchadha96** [comment]
Oh, okay.
Thank you.
