### ISSUE TITLE
Error in Gcp and distortion in further registration

### ISSUE THREAD

**Issue by kundu03** [openMVG/openMVG#2299]
Hi @pmoulon , I am using openmvg to generate point cloud which is having good quality but when i try to mark gcp, the errors are really large and when i try to register gcp again to reduce the error, the error instead of reducing keeps on increasing exponentially. Theoritically, it should either reduce or remain constant because bundle adjustment is done after that but its happening opposite for me. Can you please tell?

**Comment by pmoulon** [comment]
Maybe your gcp does not triangulate correctly (not sure why). Did you check that they corresponds to the right same points in 3d?

**Comment by kundu03** [comment]
kundusagar468@gmail.com - This is my email ID. The dataset with me is confidential and hence I cannot share the link. If you can mail me, I'll share the dataset link, gcp coordinates.

**Comment by kundu03** [comment]
Hi @pmoulon,

I have observed few more things and have few doubts

1. My GCP coordinates are in UTM. I hope that should not be a problem
2. When i try to run dataset with GCP in UTM coordinates and without using "-P" in SFM or `geodesy_registration_to_gps_position` and try to register GCP, I am getting very less errors (with z being very less compare to x and y).
3. When i try to triangulate again, it is not running and showing 'control points can't be triangulated'. 
4.  When i am using "-P" / `geodesy_registration_to_gps_position` and try to register GCP, it is not running and showing 'control points can't be triangulated'. I have seen in other issues that people are able to register GCP even after using `geodesy_registration_to_gps_position`.

I am not able to conclude anything with my observations.
