### ISSUE TITLE
Colorize the point cloud

### ISSUE THREAD

**Issue by kundu03** [openMVG/openMVG#2303]
Hi @pmoulon , 

Can you please look at the error in 'main_ComputeSfM_DataColor' and tell me what could be the reason for this.

openMVG_main_ComputeSfM_DataColor: /usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:367: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<openMVG::image::Rgb<unsigned char>, -1, -1, 1, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = openMVG::image::Rgb<unsigned char>; Eigen::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.

I know the error is very rare but it will be difficult for me to understand the internal implementation of the 'main_ComputeSfM_DataColor' but you could get it very quickly. 

Thanks

**Comment by pmoulon** [comment]
It is most likely trying to access a pixel out of the image for an unknown reason. Do you can reproduce the error on a given dataset?

**Comment by kundu03** [comment]
Hi @pmoulon , you are correct. When i went through all the pixel values stored in structure inside sfm_data.json file, I saw pixel values crossing the dimension of the image. Can you please tell - What could be the reason for this and how to solve it?

**Comment by qingzhengzhuma** [comment]
> Hi @pmoulon , you are correct. When i went through all the pixel values stored in structure inside sfm_data.json file, I saw pixel values crossing the dimension of the image. Can you please tell - What could be the reason for this and how to solve it?

track your code in debug mode and figure out why, this will be faster to solve the problem.
