### ISSUE TITLE
about Union-Find feature track conflicts

### ISSUE THREAD

**Issue by nnop** [openMVG/openMVG#2306]
When using Union-Find to construct feature tracks, I feel it may be possible to introduce multiple different feature points in the same image, as shown in the figure below.：
![image](https://github.com/openMVG/openMVG/assets/23091984/35aaa54b-7a3c-4af2-88ec-ad0055e59773)

Would this be an issue?

**Comment by pmoulon** [comment]
See the code and paper about it. If it happens we deal with it https://github.com/openMVG/openMVG/blob/7fd19fc22419a35481d39d2946f77e1dc00df37c/src/openMVG/tracks/tracks.hpp#L123
