### ISSUE TITLE
How to create pipeline in visualstudio.

### ISSUE THREAD

**Issue by Runasia** [openMVG/openMVG#2307]
:)   Thank you for watching.
I want to create my  own pipeLine programe in visualstudio . and i just  Create a New Project in software ,
and i copy another openMVG_main_SfM_Localization code(just some#include and using namespace) in new 

then i debug it  and get some mistake like this 
![image](https://github.com/openMVG/openMVG/assets/39799280/680e7b63-f3f4-4473-9845-cc666a1506ca)

I think some libraries or references are missing ，So I have added them to my project based on the project properties and reference list of openMVG_main_SfM_Localization like this 
![image](https://github.com/openMVG/openMVG/assets/39799280/1461d34b-b383-4ab7-8ce4-142d9d5827b8)
![image](https://github.com/openMVG/openMVG/assets/39799280/e44082b8-c688-4901-b4c6-696e5b0aabf9)

But it still throws an error just like begin ....

**Comment by Runasia** [comment]
Because the interface is in Chinese, I will explain what I did. I right-clicked on the properties of the pipeline project that I created myself and made most of the content of the following three items the same as the properties of openMVG_main_SfM_Localization.

They are respectively "Configuration Properties -> General section," "C/C++ -> General -> Additional Include Directories," and "Linker -> Input -> Additional Dependencies."

And the project references (also similar to openMVG_main_SfM_Localization). just like the last picture .

**Comment by qingzhengzhuma** [comment]
use cmake will be easier. one option is to create your own pipeline in openMVG, another is use openMVG as thirdparty dependency via vcpkg or doing it yourself like #2292.

**Comment by Runasia** [comment]
thank you ~ ,let me try !  I will  write what happened afterwards .

> use cmake will be easier. one option is to create your own pipeline in openMVG, another is use openMVG as thirdparty dependency via vcpkg or doing it yourself like #2292.

**Comment by Runasia** [comment]
I get  success ！ even if  i  use cmake about change  cmakelists.txt first time ,  and it's work :-)
it's just need copy openMVG\src\software and change name, than change cmakelists in copy folder .
just change like this 

1 add_executable(openMVG_main_SfM_xx main_SfM_xx.cpp)  
2 target_link_libraries(openMVG_main_SfM_xx
3 set_property(TARGET openMVG_main_SfM_xx PROPERTY FOLDER OpenMVG/software)
4 install(TARGETS openMVG_main_SfM_xx DESTINATION bin/)
xx is project name 

and change cpp file name .

then use cmd  command 
 

`cmake -G "Visual Studio 16 2019" E:\fengmen\opmvgdate\openmvgbasic\openMVG\src`

  
in build directory .
