### ISSUE TITLE
ERROR: flag 'flagfile' was defined more than once

### ISSUE THREAD

**Issue by nvl0451** [openMVG/openMVG#2310]
Built on Mac OS with Xcode, getting this error when running openMVG_main_SfMInit_ImageListing

`ERROR: flag 'flagfile' was defined more than once (in files '/tmp/gflags-20230913-4867-1pubgdv/gflags-2.2.2/src/gflags.cc' and '/opt/concourse/worker/volumes/live/5ce6f7d8-5bf2-4e48-7a02-c2331fea922e/volume/gflags_1542388463840/work/src/gflags.cc').`

pls help

**Comment by nvl0451** [comment]
seemingly fixed by switching to master branch. why?

**Comment by pmoulon** [comment]
Are you using ceres internal or one on your machine?

**Comment by zachmizrachi** [comment]
I have this issue as well. It was not fixed by switching to master

**Comment by pmoulon** [comment]
@zachmizrachi same as shared before. Can you check if your OpenMVG is using the internal ceres or one pre installed on your machine (I believe this is the later).

**Comment by aapatni** [comment]
I also have this issue, but in a different context. This is using pycolmap and pandas together? OpenMVG and COLMAP are somewhat related^

```
Python 3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycolmap
>>> import pandas
ERROR: flag 'help' was defined more than once (in files '/Users/runner/work/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285.clean/src/gflags_reporting.cc' and '/opt/concourse/worker/volumes/live/5ce6f7d8-5bf2-4e48-7a02-c2331fea922e/volume/gflags_1542388463840/work/src/gflags_reporting.cc').
```

**Comment by pmoulon** [comment]
@aapatni you have a python issue. @zachmizrachi was having a c++ link issue.
