### ISSUE TITLE
The main_sfm_location  of camera orientation doubt.

### ISSUE THREAD

**Issue by Runasia** [openMVG/openMVG#2311]
I am back! :~) Good night!

I want to use normalized pixel coordinates and camera position to do some things. But I want a simple way to get started, which is to get the camera orientation.

I use main_sfm_location to get sfm_data_expanded to find the "rotation" R and "center" camera position. Based on the following formula, I find that the third row of R has a smaller Z value than the camera's location. However, most of my structure is in front of the camera position . That's mean my localization get mistake or anorther?

![image](https://github.com/openMVG/openMVG/assets/39799280/94544e01-5f9e-4584-827b-7327a49e9806)

and this is meshlab structure ,the blue one is Z
![image](https://github.com/openMVG/openMVG/assets/39799280/fd7ac8cc-a2f9-4cb0-92af-0fc3cf39216f)

this is sfm_data_expanded.json  ,  key :9 is location imag  it's intrinsic  and extrinsic
![image](https://github.com/openMVG/openMVG/assets/39799280/44b5c9c7-5da0-4b62-9b96-39096c080529)
![image](https://github.com/openMVG/openMVG/assets/39799280/bb6e0a15-2699-4d52-9abf-c0bdd26844b9)
![image](https://github.com/openMVG/openMVG/assets/39799280/7b160982-d561-4043-84fd-54165b5e4a33)

just like that;s , the oritantion [0.5,0.2060,0.837321] in world,  the center camera position [0.28397,-0.000519,1.33136],
i think oritantion's  Z should begger then position's Z  ...

pls! and thank you for reading

**Comment by Runasia** [comment]
I have find some plus ,  i use camera postion(center) + third row of R  get Z ,  using  similar approach get Y and X. like this 
![image](https://github.com/openMVG/openMVG/assets/39799280/effad5fb-74d3-4c86-9ea8-9def6ee02280)

i think z rotation should near direction with dense white spots ,  ,because i take picture 's oritention focuse building and similer with sfm input imag....

 need some advice, that's important for me.

have a nice day !

**Comment by Runasia** [comment]
I have made a simple mistake  in use  third row of R , i forget and think Mat3 was row-major order ,but true is column-major order。

**Comment by pmoulon** [comment]
Glad you found a solution.
