### ISSUE TITLE
Integrating openMVG and openMVS

### ISSUE THREAD

**Issue by Majid9287** [openMVG/openMVG#2313]
``I'm reaching out for assistance with integrating openMVG and openMVS  for creating 3D models from 2D images. Here's the issue I'm facing:

I've successfully installed openMVG at the path /opt/openmvs and openMVS at the path /opt/openmvg. The Docker image builds without any errors, but when I call the API, I encounter the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'opt/openmvg/bin/openMVG_main_SfMInit_ImageListing
`

**Comment by Runasia** [comment]
I'm new hand and maybe can't take good advise .

I find my "openMVG_main_SfMInit_ImageListing.exe" in \openMVG\build\Windows-AMD64-\Debug\openMVG_main_SfMInit_ImageListing.exe, i think my "build"(cmake generation in this) means yours"bin".

Can you check if the path exists after 'bin' has been removed or maybe  change path try again ？

have nice day ....
