### ISSUE TITLE
error in 59% about openMVG_sample_describe_and_match_GUI

### ISSUE THREAD

**Issue by Timemachine611** [openMVG/openMVG#2316]
[ 59%] Building HTML documentation with Sphinx
正在运行 Sphinx v5.0.2
WARNING: html_static_path 指向的 '_static' 不存在
加载 pickled环境... 完成
构建 [mo]： 0 个 po 文件的目标文件已过期
构建 [html]： 0 个源文件的目标文件已过期
更新环境: 已添加 0，0 已更改，0 已移除
查找当前已过期的文件... 没有找到
没有过期的目标文件。
构建 成功, 1 警告。

HTML 页面保存在 htmlDoc 目录。
[ 59%] Built target doc
[ 59%] Built target lib_CoinUtils
[ 59%] Built target lib_Osi
[ 59%] Built target lib_clp
[ 59%] Built target lib_OsiClpSolver
[ 59%] Built target openMVG_stlplus
[ 59%] Built target openMVG_ceres
[ 59%] Built target openMVG_easyexif
[ 59%] Built target openMVG_fast
[ 59%] Built target openMVG_exif
[ 59%] Built target openMVG_features
[ 59%] Built target openMVG_numeric
[ 59%] Built target openMVG_image
[ 59%] Built target openMVG_linearProgramming
[ 59%] Built target openMVG_system
[ 59%] Built target openMVG_multiview
[ 59%] Built target openMVG_lInftyComputerVision
[ 59%] Built target openMVG_geometry
[ 59%] Built target openMVG_matching
[ 59%] Built target openMVG_kvld
[ 59%] Built target openMVG_matching_image_collection
[ 59%] Built target openMVG_multiview_test_data
[ 59%] Built target openMVG_robust_estimation
[ 59%] Built target openMVG_sfm
[ 59%] Built target main_svgSample
[ 59%] Built target openMVG_sample_cameras_undistoBrown
[ 59%] Built target openMVG_sample_robust_estimation_Homography
[ 59%] Built target openMVG_sample_multiview_robustHomography
[ 59%] Built target openMVG_sample_multiview_robustHomography_guided
[ 59%] Built target openMVG_sample_multiview_robustFundamental
[ 59%] Built target openMVG_sample_multiview_robustFundamental_guided
[ 59%] Built target openMVG_sample_multiview_robustEssential
[ 59%] Built target openMVG_sample_multiview_robustEssential_spherical
[ 59%] Built target openMVG_sample_multiview_robustEssential_ba
[ 59%] Built target openMVG_main_exif_Parsing
[ 59%] Built target vlsift
[ 59%] Built target openMVG_sample_main_features_repeatability_dataset
[ 59%] Built target openMVG_sample_features_affine
[ 59%] Built target openMVG_sample_features_kvld
[ 59%] Built target openMVG_sample_features_siftPutative
[ 59%] Built target openMVG_sample_image_matching
[ 59%] Built target openMVG_sample_image_matching_gmsfilter
[ 59%] Automatic MOC for target openMVG_sample_describe_and_match_GUI
[ 59%] Built target openMVG_sample_describe_and_match_GUI_autogen
[ 59%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_sample_describe_and_match_GUI
/usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Widgets.so.5.15.2: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
collect2: error: ld returned 1 exit status
make[2]: *** [openMVG_Samples/describe_and_match_GUI/CMakeFiles/openMVG_sample_describe_and_match_GUI.dir/build.make:146：Linux-x86_64-RELEASE/openMVG_sample_describe_and_match_GUI] 错误 1
make[1]: *** [CMakeFiles/Makefile2:3534：openMVG_Samples/describe_and_match_GUI/CMakeFiles/openMVG_sample_describe_and_match_GUI.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by Timemachine611** [comment]
[ 59%] Building HTML documentation with Sphinx
正在运行 Sphinx v5.0.2
WARNING: html_static_path 指向的 '_static' 不存在
加载 pickled环境... 完成
构建 [mo]： 0 个 po 文件的目标文件已过期
构建 [html]： 0 个源文件的目标文件已过期
更新环境: 已添加 0，0 已更改，0 已移除
查找当前已过期的文件... 没有找到
没有过期的目标文件。
构建 成功, 1 警告。

HTML 页面保存在 htmlDoc 目录。
[ 59%] Built target doc
[ 59%] Built target lib_CoinUtils
[ 59%] Built target lib_Osi
[ 59%] Built target lib_clp
[ 59%] Built target lib_OsiClpSolver
[ 59%] Built target openMVG_stlplus
[ 59%] Built target openMVG_ceres
[ 59%] Built target openMVG_easyexif
[ 59%] Built target openMVG_fast
[ 59%] Built target openMVG_exif
[ 59%] Built target openMVG_features
[ 59%] Built target openMVG_numeric
[ 59%] Built target openMVG_image
[ 59%] Built target openMVG_linearProgramming
[ 59%] Built target openMVG_system
[ 59%] Built target openMVG_multiview
[ 59%] Built target openMVG_lInftyComputerVision
[ 59%] Built target openMVG_geometry
[ 59%] Built target openMVG_matching
[ 59%] Built target openMVG_kvld
[ 59%] Built target openMVG_matching_image_collection
[ 59%] Built target openMVG_multiview_test_data
[ 59%] Built target openMVG_robust_estimation
[ 59%] Built target openMVG_sfm
[ 59%] Built target main_svgSample
[ 59%] Built target openMVG_sample_cameras_undistoBrown
[ 59%] Built target openMVG_sample_robust_estimation_Homography
[ 59%] Built target openMVG_sample_multiview_robustHomography
[ 59%] Built target openMVG_sample_multiview_robustHomography_guided
[ 59%] Built target openMVG_sample_multiview_robustFundamental
[ 59%] Built target openMVG_sample_multiview_robustFundamental_guided
[ 59%] Built target openMVG_sample_multiview_robustEssential
[ 59%] Built target openMVG_sample_multiview_robustEssential_spherical
[ 59%] Built target openMVG_sample_multiview_robustEssential_ba
[ 59%] Built target openMVG_main_exif_Parsing
[ 59%] Built target vlsift
[ 59%] Built target openMVG_sample_main_features_repeatability_dataset
[ 59%] Built target openMVG_sample_features_affine
[ 59%] Built target openMVG_sample_features_kvld
[ 59%] Built target openMVG_sample_features_siftPutative
[ 59%] Built target openMVG_sample_image_matching
[ 59%] Built target openMVG_sample_image_matching_gmsfilter
[ 59%] Automatic MOC for target openMVG_sample_describe_and_match_GUI
[ 59%] Built target openMVG_sample_describe_and_match_GUI_autogen
[ 59%] Linking CXX executable ../../Linux-x86_64-RELEASE/openMVG_sample_describe_and_match_GUI
/usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13' /usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Widgets.so.5.15.2: undefined reference to std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/cxy/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
collect2: error: ld returned 1 exit status
make[2]: *** [openMVG_Samples/describe_and_match_GUI/CMakeFiles/openMVG_sample_describe_and_match_GUI.dir/build.make:146：Linux-x86_64-RELEASE/openMVG_sample_describe_and_match_GUI] error 1
make[1]: *** [CMakeFiles/Makefile2:3534：openMVG_Samples/describe_and_match_GUI/CMakeFiles/openMVG_sample_describe_and_match_GUI.dir/all] error 2
make: *** [Makefile:130：all] error 2

**Comment by pmoulon** [comment]
@rperrot maybe a mismatch between the computer for at and the computer you are using

**Comment by Timemachine611** [comment]
i found the problem, my anaconda's gcc have a clash with ubuntu's gcc.
i add the SET(CMAKE_PREFIX_PATH "/usr/lib/x86_64-linux-gnu/cmake") in Cmakelist.txt

**Comment by Timemachine611** [comment]
but another problem comes up in 62%...
[ 62%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/annotation_context.cpp.o
[ 62%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/arrows2d.cpp.o
[ 63%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/arrows2d_ext.cpp.o
[ 63%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/arrows3d.cpp.o
[ 63%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/arrows3d_ext.cpp.o
[ 63%] Building CXX object _deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/asset3d.cpp.o
In file included from /home/cxy/openMVG/openMVG_Build/_deps/rerun_sdk-src/src/rerun/archetypes/asset3d.cpp:4:0:
/home/cxy/openMVG/openMVG_Build/_deps/rerun_sdk-src/src/rerun/archetypes/asset3d.hpp:16:10: fatal error: filesystem: 没有那个文件或目录
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [_deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/build.make:128：_deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/src/rerun/archetypes/asset3d.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:3811：_deps/rerun_sdk-build/CMakeFiles/rerun_sdk.dir/all] 错误 2
make: *** [Makefile:130：all] error 2

**Comment by Timemachine611** [comment]
ok, my gcc version is too old, previous it's 7.5.0. just update your gcc above 8.0....
then also need to update your eigen version above 3.4.0, but MVS need under 3.4.0, which makes me annoying.
