### ISSUE TITLE
A question about loading image

### ISSUE THREAD

**Issue by Miuna26** [openMVG/openMVG#2317]
Why the image width and height exchanged ?
For example,images in folder are (3024,4032),but width and height in .json file are 4032 and 3024 respectively.And coordination in u-v system of feature points fits with what .json file do,but I need position in (3024,4032).

**Comment by pmoulon** [comment]
We load image without the JPEG orientation parameter. So if you want to use the JPEG orientation for your parameter flip the coordinate accordingly as a post process.

**Comment by Miuna26** [comment]
well，I get it.I'll try it,thanks for your help.
