### ISSUE TITLE
Stellar vs Global mode of construction

### ISSUE THREAD

**Issue by kundu03** [openMVG/openMVG#2319]
Hi @pmoulon ,
I have a dataset of a monument in which images are taken from drone and from the sides of monument also in order to ensure sides are also covered and i am processing the same dataset with global as well as stellar mode of construction but getting different results.

Global construction -

![Screenshot from 2024-04-23 18-48-19](https://github.com/openMVG/openMVG/assets/104849951/e5ed7f83-dc31-4eda-b06a-c5f4d347e6f7)

Stellar Construction -

[
![Screenshot from 2024-04-23 18-44-39](https://github.com/openMVG/openMVG/assets/104849951/bfc447ed-06a3-4132-8319-fb7e96d79449)
](url)

If you look at the two point clouds, you will notice that global work a little bit good and does not have any bad construction but the one with stellar has the monument plus a copy of monument constructed at its left side also because the camera positions are from the ground level.
Can you suggest how to improve this in stellar construction so that the left copy will not be created and it should have enough features side ways also. Thank you.

**Comment by pmoulon** [comment]
This is most likely due to some outlier image pair in the view graph.
Can you try to relaunch a stellar reconstruction on top of the existing one to see if using better intrinsic are helping. I.e just relaunch a stellar reconstruction but take the sfm_data.bin for your previous reconstruction.
