### ISSUE TITLE
Problem in Gcp registration

### ISSUE THREAD

**Issue by kundu03** [openMVG/openMVG#2324]
Hi @pmoulon ,

I have a dataset with images and 4 gcp's and i am trying to geo reference it using those gcps.

Here are the steps i am following :-

1. Constructing using stellar method.
2. Registering to Gps using geodesy_registration_to_gps_position
3. Marking Gcp using ui_openMVG_control_points_registration and saving it.
4. Changing local origin (because features and gcp are in utm coordinates with large values and to reduce error while calculating) using ChangeLocalOrigin
5. Registering with Gcps using ui_openMVG_control_points_registration

The Gcp errors are logged onto console and i noticed that the pixel error are around 2-3 pixels but the error in user units which is in meter are very large like approx 2-3 meter but they should be around 2-3 cm or may be 5-6 cm but not more than that.

In order to check any kind of error in dataset or gcps, i tried it processing using agisoft and open drone map (odm - which may use opensfm) for the same. There i am getting errors around 1-2 cm.

Can you suggest what could be the mistake in this or what should i try to decrease those errors.

**Comment by pmoulon** [comment]
Hello @kundu03 
Thank you for sharing your issue and the path you are using.
Did you try to compare the camera pose translation between agisoft and OpenMVG and see how far they are?

Also the error is reported in the unit of your gcp...

**Comment by kundu03** [comment]
Since Agisoft is closed source so we don't have access to these things what they actually uses and what are the intermediate things we are getting.

**Comment by pmoulon** [comment]
But they do allow you to export the camera position to some files.

**Comment by kundu03** [comment]
Ok i will try to export this and compare with each other and let you know.

**Comment by kundu03** [comment]
I exported the agisoft camera positions. Here is the link for which contains openmvg camera files with and without gcp registration and agisoft camera positions also. I am trying to understand what is the actual problem. If you get anything then please let me know.

https://drive.google.com/drive/folders/11HjAz9HZ6RKGnXQtXA31SN8aIlhso_5b?usp=sharing

**Comment by kundu03** [comment]
Hi @pmoulon ,
I am unable to conclude anything from this. If you get anything it will be really helpful.
I have tried changing different camera models and intrinsics and extrinsics refinement options but not get any reason for this.
