### ISSUE TITLE
Reconstruct mulitple sub-models from an image set?

### ISSUE THREAD

**Issue by lyb-tjnu** [openMVG/openMVG#2330]
First of all, thank all the developers for this great software. I have a UAV image set contains 100 images. The images were acquired over a water area. Image matching is very difficult for this data set. I cannot reconstruct a single model from all the 100 images. However, there are small subsets in which images are connected well. Can OpenMVG reconstruct models from these subsets?

**Comment by pmoulon** [comment]
Thank you for your kind words.
Today we dont build all sub component, we just build the largest one.
If you want reconstruct the subset you can just remove some pairs belonging to a reconstruction that has been done, so the next one will be built

**Comment by lyb-tjnu** [comment]
Thanks for your reply.
