### ISSUE TITLE
Can Triangulate2View used if the poses are known ?

### ISSUE THREAD

**Issue by alexs7** [openMVG/openMVG#2332]
@pmoulon 
Thanks for your work, 

Quick question, can [Triangulate2View](https://github.com/openMVG/openMVG/blob/6d6b1dd70bded094ba06024e481dd5a5c662dc83/src/openMVG/multiview/triangulation.cpp#L179) be used for triangulating bearing vectors of equirectangular images given I have the poses of the 360 images ?

The poses are in world coordinate system (they transform from camera space to world space). From looking at the code it seems that yes but I am not getting the results I should. The method `Triangulate2View` calculates the relative pose from P1 to P2, and uses the result to triangulate. 

For spherical images, I have seen the default triangulation method being used in `E_ACRobust_Angular.hpp` when `RelativePoseFromEssential` is called.

**Comment by alexs7** [comment]
Yes it can, my bearing vectors were wrong.. Closing issue.

**Comment by pmoulon** [comment]
Glad you found a solution to your problem! Have fun with OpenMVG!
