### ISSUE TITLE
openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp

### ISSUE THREAD

**Issue by waqarsqureshi** [openMVG/openMVG#2350]
Built envorinment: Windows WSL - Ubuntu 22.04

Error is building visualize_sfm_data.cpp

openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp

   76 |           rerun::archetypes::Transform3D(rerun::datatypes::TranslationAndMat3x3(
      |                                                            ^~~~~~~~~~~~~~~~~~~~
/home/waqar/reconstruction/openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp:96:57: error: no matching function for call to ‘rerun::archetypes::Image::Image(<brace-enclosed initializer list>, const Scalar*)’
   96 |                              img.GetMat().data()->data()));
      |                                                         ^
In file included from /home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun/archetypes.hpp:17,
                 from /home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun.hpp:4,
                 from /home/waqar/reconstruction/openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp::
/home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun/archetypes/image.hpp:222:9: note: candidate: ‘template<class T> rerun::archetypes::Image::Image(const T*, rerun::WidthHeight, rerun::datatypes::ColorModel)’
  222 |         Image(const T* elements, WidthHeight resolution, datatypes::ColorModel color_model)
      |         ^~~~~
/home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun/archetypes/image.hpp:222:9: note:   template argument deduction/substitution failed:
/home/waqar/reconstruction/openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp:96:57: note:   candidate expects 3 arguments, 2 provided
   96 |                              img.GetMat().data()->data()));
      |                                                         ^
In file included from /home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun/archetypes.hpp:17,
                 from /home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun.hpp:4,
                 from /home/waqar/reconstruction/openMVG/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp::
/home/waqar/reconstruction/openMVG_build/_deps/rerun_sdk-src/src/rerun/archetypes/image.hpp:209:9: note: candidate: ‘template<class T> rerun::archetypes::Image::Image(rerun::Collection<TElement>, rerun::WidthHeight, rerun::datatypes::ColorModel)’
  209 |         Image(Collection<T> elements, WidthHeight resolution, datatypes::ColorModel color_model)

**Comment by waqarsqureshi** [comment]
https://rerun.io/docs/reference/migration/migration-0-18
The rerun new release 3 days ago have changed the Image template.
I am now moving to older version, due to lazyness and changing the cmake in visualize sfm to use as follows:
FetchContent_Declare(rerun_sdk URL
    https://github.com/rerun-io/rerun/releases/download/0.17.0/rerun_cpp_sdk.zip)

**Comment by waqarsqureshi** [comment]
and add rerun older version
pip3 install rerun-sdk==0.17.0

**Comment by ioir123ju** [comment]
> https://rerun.io/docs/reference/migration/migration-0-18 3 天前重新运行的新版本已更改图像模板。由于懒惰，我现在正在转向旧版本，并在 visualize sfm 中更改 cmake 以使用，如下所示： FetchContent_Declare（rerun_sdk URL https://github.com/rerun-io/rerun/releases/download/0.17.0/rerun_cpp_sdk.zip)

I also encountered the same problem. How did you solve it? I didn’t understand it.

**Comment by Asherchi** [comment]
> and add rerun older version pip3 install rerun-sdk==0.17.0

after install the 0.17.0, do you need rebuild the project?

**Comment by pmoulon** [comment]
#2352 is showing how to fix the build issue with the updated rerun api.
