### ISSUE TITLE
Specify rerun-io version in visualize_sfm_data/CMakeLists.txt

### ISSUE THREAD

**Issue by LinkinPony** [openMVG/openMVG#2354]
In [src/openMVG_Samples/visualize_sfm_data/CMakeLists.txt](https://github.com/openMVG/openMVG/blob/1923faf0f2ee603d00e99bc26817daeba8e4c223/src/openMVG_Samples/visualize_sfm_data/CMakeLists.txt#L4), it uses latest `rerun-io`. However, there's a breaking change in [rerun-io v0.18.0](https://github.com/rerun-io/rerun/releases/tag/0.18.0) which discard `rerun::datatypes::TranslationAndMat3x3` used in [visualize_sfm_data.cpp](https://github.com/openMVG/openMVG/blob/1923faf0f2ee603d00e99bc26817daeba8e4c223/src/openMVG_Samples/visualize_sfm_data/visualize_sfm_data.cpp#L76).

Maybe should consider specifying rerun-io version or changing the usage of TranslationAndMat3x3

**Comment by pmoulon** [comment]
Thank you. Yes we will do. I believe there is even a PR to address this issue
