### ISSUE TITLE
[SfM] Use the new IO system

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#237]
**Use the new SfM_Data container as Input**

- [x] Update main_CreateList to generate the SfM_Data Views & Intrinsics,
- [x] Update main_computeMatches to use SfM_Data container as input,
- Update software directory to use the SfM_Data as input:
  - [x] read SfM_Data and convert it to old Intrinsic system to avoid regression (in a first draft).

- [x] Add a new binary that convert the lists.txt file to a SfM_Data file with the corresponding Views & Intrinsics data. => main_ConvertList.

- Export scenes using the new IO system
  - [x] Global SfM #249
  - [x] Incremental SfM #252

- Update the SfM_Output converter to fit the new IO system
  - [x] SfM_Viewer + add an option to load or not pictures
  - [X] main_openMVG2CMPMVS.cpp
  - [X] main_openMVG2MESHLAB.cpp
  - [x] main_openMVG2PMVS.cpp
  - [x] openMVG_main_computeMatches_OpenCV https://github.com/openMVG/openMVG/commit/96b3a1a6b6e20e68740eb346f3e8e9814258ffd6

- [x] Add a function to do generic image **un-**distortion using the new abstract camera system
  - [x] using disto/undisto functions with coordinates in the image plane(pixel) https://github.com/openMVG/openMVG/commit/4b2a8e49ad0871048a6e813b95c14ba1753e37e9

- [x] Add a conversion sfm_data.X (JSON<->XML<->BINARY) -> PLY | WIP https://github.com/openMVG/openMVG/commit/0a81ce9eeea99e5725f7ddcfee4114bc2b4a90a9

**Comment by fabiencastan** [comment]
As you are modifying all the file formats, is it possible to include the modifications to split into multiple files (which allows parallelization)?
We are relying on this PR at Mikros: https://github.com/openMVG/openMVG/pull/214.

**Comment by pmoulon** [comment]
Not yet, it will not be considered in the first move.
Since it will make too much things to handle at the same time.
But will be handle in the future for sure with a generic wrapper interface to provide the matches.

**Comment by pmoulon** [comment]
@fabiencastan As you see here https://github.com/openMVG/openMVG/blob/develop_newIO/src/software/globalSfM/main_GlobalSfM.cpp#L102 the matches provider is now abstract. So it's now easy to add your custom match loader (that load matched contained in multiple files) and run smoothly the SfM pipeline on it ;-)

**Comment by fabiencastan** [comment]
Thanks! I will look at it.
