### ISSUE TITLE
Problems to compile openMVG on Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by SimonSword** [openMVG/openMVG#2376]
When trying to compile the code as described in the BUILD.md [1], I receive the following CMake error DURING COMPILATION (which is not very usual):
```
[ 49%] Performing configure step for 'arrow_cpp'
[ 49%] Linking CXX executable ../../Linux-x86_64-Release/openMVG_sample_pano_converter
[ 49%] Built target openMVG_sample_pano_converter
CMake Error at /home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '--preset' 'ninja-release-minimal' '-DARROW_BOOST_USE_SHARED=OFF' '-DARROW_BUILD_SHARED=OFF' '-DARROW_BUILD_STATIC=ON' '-DARROW_CXXFLAGS=' '-DARROW_COMPUTE=OFF' '-DARROW_IPC=ON' '-DARROW_JEMALLOC=OFF' '-DARROW_MIMALLOC=ON' '-DARROW_USE_ASAN=' '-DARROW_USE_TSAN=OFF' '-DARROW_USE_UBSAN=OFF' '-DBOOST_SOURCE=BUNDLED' '-DCMAKE_INSTALL_PREFIX=/home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow' '-DCMAKE_INSTALL_LIBDIR=lib' '-DCMAKE_INSTALL_BINDIR=bin' '-Dxsimd_SOURCE=BUNDLED' '-DBOOST_SOURCE=BUNDLED' '-DARROW_BOOST_USE_SHARED=OFF' '-DCMAKE_TOOLCHAIN_FILE=' '-GUnix Makefiles' '-S' '/home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow/src/arrow_cpp/cpp' '-B' '/home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow/src/arrow_cpp-build'

  See also

    /home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-*.log


make[2]: *** [_deps/rerun_sdk-build/CMakeFiles/arrow_cpp.dir/build.make:95: arrow/src/arrow_cpp-stamp/arrow_cpp-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:3331: _deps/rerun_sdk-build/CMakeFiles/arrow_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 49%] Linking CXX executable ../../Linux-x86_64-Release/openMVG_sample_features_affine
[ 49%] Built target openMVG_sample_features_affine
[ 49%] Linking CXX static library ../../Linux-x86_64-Release/libopenMVG_geometry.a
[ 49%] Built target openMVG_geometry
```

The file `/home/ttz-dev-1/workspace/openmvg/openMVG_Build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-*.log` contains the following:
```
CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.28/Modules/FindThreads.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake_modules/ThirdpartyToolchain.cmake:1062 (find_package)
  CMakeLists.txt:546 (include)
```

Now, I already installed build-essentials, libboostthread and other stuff suggested by chatgpt, but the problem persists.

Any suggestions?

https://github.com/openMVG/openMVG/blob/develop/BUILD.md

**Comment by rfabbri** [comment]
Assuming your recent system should be using a recent  GCC, Arrow should not
even be testing for threads.

As a background:
- Arrow is fetched and built by the src/openMVG_Samples/visualize_sfm_data
- This is indirectly by these lines in visualize_sfm_data
FetchContent_Declare(rerun_sdk URL

https://github.com/rerun-io/rerun/releases/latest/download/rerun_cpp_sdk.zip
)
For that reason, I would think this sample should be off by default, it
gives much more chances of compilation errors when not every user will use
it I think.

You might  want these work-arounds:
- Disable OpenMVG_BUILD_EXAMPLES (perhaps should just
be OpenMVG_BUILD_EXAMPLES)
- You can also remove the line containing visualize_sfm_data from
 src/openMVG_Samples if you wish to build the other examples
- Harder: Modify arrow CMake
https://stackoverflow.com/questions/54587052/cmake-on-mac-could-not-find-threads-missing-threads-found
    - Likely need to do it indirectly via FindPackageHandleStandardArgs

Long term solution:
- Patch arrow/rerun upstream
- Include an internal arrow dependency in openMVG and maintain it
separately than upstream, in case everyone really wants to use
visualize_sfm_data.

--
Ricardo Fabbri
Professor of Computer Engineering
IPRJ/UERJ Nova Friburgo Graduate Program – CAPES 6
rfabbri.github.io

**Comment by SimonSword** [comment]
I opted for the easy solution and disabled OpenMVG_BUILD_EXAMPLES.

Thanks for the quick help!

**Comment by pmoulon** [comment]
You are welcome!
