### ISSUE TITLE
compile issue for newbie

### ISSUE THREAD

**Issue by jakeoung** [openMVG/openMVG#239]
Whenever I try to compile openMVG, I failed on Windows and Ubuntu.
Could you help me?

on Ubuntu,
Linking CXX static library libopenMVG_image.a
[ 78%] Built target openMVG_image
Scanning dependencies of target openMVG_lInftyComputerVision
[ 79%] Building CXX object openMVG/linearProgramming/lInfinityCV/CMakeFiles/openMVG_lInftyComputerVision.dir/resection_kernel.cpp.o
In file included from /home/jakeoung/usr/lib/mvg/openMVG/src/openMVG/linearProgramming/lInfinityCV/resection_kernel.cpp:8:0:
/home/jakeoung/usr/lib/mvg/openMVG/src/openMVG/linearProgramming/linearProgrammingOSI_X.hpp:10:37: fatal error: OsiClpSolverInterface.hpp: No such file or directory
 #include "OsiClpSolverInterface.hpp"

--------------------------
on Windows, in cmake-gui, the error messages are

The C compiler identification is MSVC 18.0.31101.0
The CXX compiler identification is MSVC 18.0.31101.0
Check for working C compiler using: Visual Studio 12 2013 Win64
Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 12 2013 Win64
Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
target changed from "" to "auto"
Detected CPU: sandy-bridge
Performing Test check_c_compiler_flag__arch_AVX
Performing Test check_c_compiler_flag__arch_AVX - Success
Performing Test check_cxx_compiler_flag__arch_AVX
Performing Test check_cxx_compiler_flag__arch_AVX - Success
Try OpenMP C flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Try OpenMP CXX flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Found OpenMP: /openmp  
Found OpenGL: opengl32  
Looking for include file pthread.h
Looking for include file pthread.h - not found
Found Threads: TRUE  
Using Win32 for window creation
Using WGL for context creation
-- Did not find MOSEK header
-- Did not find MOSEK library
Could not find mosek library on this machine.
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
Could NOT find Wget (missing:  WGET_EXECUTABLE) 
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE) 
Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of long long
Check size of long long - done
Looking for stdlib.h
Looking for stdlib.h - found
Found Eigen: D:/usr/lib/openMVG/src/third_party/eigen (found version "3.2.1") 
-- Found Eigen version 3.2.1: D:/usr/lib/openMVG/src/third_party/eigen
A library with BLAS API not found. Please specify library location.
LAPACK requires BLAS
-- Did not find LAPACK library, disabling LAPACK support.
-- Did not find BLAS library, disabling LAPACK support.
-- Building without SuiteSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Using minimal Glog substitute (library): miniglog
-- Using minimal Glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Creating configured Ceres config.h output directory: D:/usr/lib/openMVG_3/third_party/ceres-solver/config/ceres/internal
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
-- Do not build any example.
Install prefix: C:/Program Files/openMVG
Build type: Release
Building C bindings: OFF
Building python bindings: OFF
Building matlab bindings: OFF
Building CUDA library: OFF
Using OpenMP support: ON
Using MPI support: OFF
Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the documentation
CMake Error at CMakeLists.txt:248 (add_subdirectory):
  add_subdirectory given source "openMVG/src" which is not an existing
  directory.

CMake Error at CMakeLists.txt:250 (target_link_libraries):
  Cannot specify link libraries for target "target" which is not built by
  this project.

Configuring incomplete, errors occurred!
See also "D:/usr/lib/openMVG_3/CMakeFiles/CMakeOutput.log".
See also "D:/usr/lib/openMVG_3/CMakeFiles/CMakeError.log".

**Comment by pmoulon** [comment]
Hi,
It because you don't have update the git submodule.
As you see here https://github.com/openMVG/openMVG/blob/develop/BUILD there is some step to follow.
Like:
$ git submodule init
$ git submodule update

**Comment by jakeoung** [comment]
Thank you very much. After deleting lines related to static library, it worked fine on Ubuntu. But on Windows,


22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1361): error C2664: 'std::pair<float,float> std::make_pair<float,float>(_Ty1 &&,_Ty2 &&)' : cannot convert argument 2 from 'float' to 'float &&'
22>          with
22>          [
22>              _Ty1=float
22>  ,            _Ty2=float
22>          ]
22>          You cannot bind an lvalue to an rvalue reference
22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1363): error C2780: 'void svg::svgHisto::draw(const std::vector<packet_type,std::allocator<_Ty>> &,const std::pair<float,float> &,const std::string &,const float,const float)' : expects 5 arguments - 4 provided
22>          D:\usr\lib\mvg\openMVG\src\third_party/vectorGraphics/svgDrawer.hpp(190) : see declaration of 'svg::svgHisto::draw'
22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1369): error C2664: 'std::pair<float,float> std::make_pair<float,float>(_Ty1 &&,_Ty2 &&)' : cannot convert argument 2 from 'float' to 'float &&'
22>          with
22>          [
22>              _Ty1=float
22>  ,            _Ty2=float
22>          ]
22>          You cannot bind an lvalue to an rvalue reference
22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1371): error C2780: 'void svg::svgHisto::draw(const std::vector<packet_type,std::allocator<_Ty>> &,const std::pair<float,float> &,const std::string &,const float,const float)' : expects 5 arguments - 4 provided
22>          D:\usr\lib\mvg\openMVG\src\third_party/vectorGraphics/svgDrawer.hpp(190) : see declaration of 'svg::svgHisto::draw'
22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1904): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned long', possible loss of data
22>D:\usr\lib\mvg\openMVG\src\software\globalSfM\SfMGlobalEngine.cpp(1981): warning C4244: 'argument' : conversion from 'float' to 'int', possible loss of data
12>D:\usr\lib\mvg\openMVG\src\third_party\ceres-solver\include\ceres/types.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
23>------ Build started: Project: stlplus, Configuration: Release x64 ------

**Comment by pmoulon** [comment]
I'm aware of this visual studio issue on the master branch.

Just change the std::make_pair<float,float>(...) to std::make_pair(...)

BTW, it's fixed on the develop branch (the current WIP version).

**Comment by jakeoung** [comment]
Thank you, but I don't understand "Just change the std::make_pair(...) to std::make_pair(...)"

**Comment by pmoulon** [comment]
Sorry, Opps: change
std::make_pair<X,Y>(...) to std::make_pair(...)

**Comment by Meekohi** [comment]
Hey Pierre, is there anyway to have the Makefile double check that the user has the submodules installed correctly, and maybe emit a warning if not? Many people seem unfamiliar with them.

**Comment by pmoulon** [comment]
I think we can check if a directory exist of not. :+1:

**Comment by jakeoung** [comment]
Thank you very much. I got it! On Ubuntu in virtual box, actually, I have to build the directory that is not shared folder.

**Comment by jakeoung** [comment]
On Ubuntu, I got Invalid Instruction. For example,

jakeoung@rabat ~/temara/software/SfM $  ./openMVG_main_CreateList -i ~/win/Pictures/ -o ~/win/Pictures/result 
Illegal instruction

How to execute software on Ubuntu?

**Comment by pmoulon** [comment]
Have you tried to run the binary without parameter, in order to see if it run correctly?
Have you tried to run other binaries, does they display the same error?

**Comment by jakeoung** [comment]
Yes, other files also display the same error. Actually, I did not find release folder. Is it okay on Linux?

**Comment by pmoulon** [comment]
In linux there is not release folder, compilation mode is defined by the cmake configuration and it is set to release by default.
Perhaps you error was due to the modification you have tried here "After deleting lines related to static library"

**Comment by jakeoung** [comment]
If I add 
      add_subdirectory(openMVG/src)
      include_directories(${OpenMVG_INCLUDES})
      target_link_libraries(target ${OpenMVG_LIBS})
to CMakeLists.txt, then there is an error when compile.


CMake Error at CMakeLists.txt:248 (ADD_SUBDIRECTORY):
  add_subdirectory given source "openMVG/src" which is not an existing
  directory.


CMake Error at CMakeLists.txt:250 (TARGET_LINK_LIBRARIES):
  Cannot specify link libraries for target "target" which is not built by
  this project.

**Comment by pmoulon** [comment]
I don't understand what you mean by your last message.
But in order to compile OpenMVG, please do not modify the existing CMakelists.txt files.

**Comment by jakeoung** [comment]
Thank you so much for your replies. What I mean was that I just saw the following from https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD

------------------------------------
Using as library dependency in cmake
------------------------------------
Adding following lines to your CMakeLists.txt should provide OpenMVG usable as
static library:

 add_subdirectory(openMVG/src)
 include_directories(${OpenMVG_INCLUDES})
 target_link_libraries(target ${OpenMVG_LIBS})

Information about required dependencies, standalone build and platform 
specificity can be found below.

**Comment by pmoulon** [comment]
ok, I think "this part is deprecated" and I have not check it since a while.
But I hope that in the future we will have a clean installer and ready to use FindOpenMVG.cmake file.
It's more or less a WIP task https://github.com/openMVG/openMVG/issues/222

**Comment by jakeoung** [comment]
Okay, I hope it will be solved soon. Thanks.

**Comment by MarcoMazzo** [comment]
I'm sorry, i'm very newbie in compiling
I've windows10 64bit
installed Visual Studio community 2015
installed cmake 3.6
installed git, cloned the project with dependencies 
run cmake gui, filled path with src and a directory for build and when i press configure i select VS-14-2015 64bit. The error it give me is:

The C compiler identification is unknown
The CXX compiler identification is unknown
[CMakeFiles.zip](https://github.com/openMVG/openMVG/files/542245/CMakeFiles.zip)

[CMakeFiles.zip](https://github.com/openMVG/openMVG/files/542243/CMakeFiles.zip)

CMake Error at CMakeLists.txt:10 (PROJECT):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:10 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.





Configuring incomplete, errors occurred!
See also "C:/Users/Utente/openMVG_release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Utente/openMVG_release/CMakeFiles/CMakeError.log".

**Comment by pmoulon** [comment]
It seems that Cmake is unable to detect that you have visual studio installed.
Did you try to reboot and rerun cmake?
