### ISSUE TITLE
Add range constraint in global reconstruction for focal and radial distortion.

### ISSUE THREAD

**Issue by fabiencastan** [openMVG/openMVG#240]
We use the focal information from EXIF. This information is not precise but cannot be completly wrong. So the bundle should not be allowed to modify this value too much.

**Comment by pmoulon** [comment]
This could be performed by using the bound constraint of Ceres solver API.

**Comment by fabiencastan** [comment]
Bundler has an option for that:
https://www.cs.cornell.edu/~snavely/bundler/bundler-v0.4-manual.html#S7

**Comment by pmoulon** [comment]
Bundler do it with penalty terms, but coding it with bounds constraints will leads to more stable results and less intrusive weighting schemes.
