### ISSUE TITLE
computeMatches : Camera doesn't exist in the database

### ISSUE THREAD

**Issue by FlachyJoe** [openMVG/openMVG#243]
Hi,
my old site cam is not detected so I try to add it to the database but without success : 

openMVG_main_computeMatches output :
```
Camera "KONICA MINOLTA " model "DiMAGE Z5" doesn't exist in the database
PICT0092.JPG;2560;1920;KONICA MINOLTA ;DiMAGE Z5
```
sensor_database_detailed.csv :
```
...
Konica-Minolta;DiMAGE Z5;"1/2.5"" (~ 5.75 x 4.32 mm)";5.75;4.32;2579;1939
KONICA MINOLTA ;DiMAGE Z5;"1/2.5"" (~ 5.75 x 4.32 mm)";5.75;4.32;2579;1939
Konica-Minolta;DiMAGE Z6;"1/2.5"" (~ 5.75 x 4.32 mm)";5.75;4.32;2918;2194
...
```
Where is my mistake ?

Many thanks.

**Comment by Meekohi** [comment]
Issue #42 strikes again!

**Comment by Meekohi** [comment]
Aren't these supposed to be more like `CAMERA;MODEL;SENSORSIZE`, for example `Kodak;Kodak EasyShare Z5120;6.08`? Or are you talking about `lists.txt`?

You could add some debug logging to openMVG/src/openMVG_Samples/sensorWidthDatabase/ParseDatabase.hpp to get more information about why it is not finding a match.

**Comment by pmoulon** [comment]
Please use the following file for the camera database https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/cameraSensorWidth/cameraGenerated.txt file and not the sensor_database_detailed.csv file.
You will see that you camera is in and it should work.

**Comment by FlachyJoe** [comment]
I have no more success with this file.
I check it with openMVG_main_ParseDatabase it's due to the space !
Exif data is "KONICA MINOLTA " and if I change the space for a dot (and create the line in the database) it find well.

Starting and ending space are ignored but internal one never matches.

NB : the cameraGenerated.txt file is not copy to the output dir by the cmake make build process, as I didn't find it I pulled https://github.com/openMVG/CameraSensorSizeDatabase ...

**Comment by pmoulon** [comment]
Can you share on the mailing list on image in order to investigate?
openmvg-team[AT]googlegroups.com

The database to use is provided in OpenMVG itself here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/cameraSensorWidth/cameraGenerated.txt

The CameraSensorSizeDatabase is a copy for sharing with the community.

**Comment by FlachyJoe** [comment]
Find !
_src/openMVG_Samples/sensorWidthDatabase/datasheet.hpp_ line 25 :
```c++
    split( ds._brand, " ", vec_brand );
```
To solve :
trim right spaces, possibly replace inner spaces by dashes
