### ISSUE TITLE
cmake configuration error on OpenMVG

### ISSUE THREAD

**Issue by CXZ116** [openMVG/openMVG#244]
I configured the compiler from CmakeGUI (version 2.8.12) MSVC 11 64-bit. CMake configuration generates error messages as follows:
 
CMake Error at bundle_adjustment/CMakeLists.txt:3 (UNIT_TEST):
  Unknown CMake command "UNIT_TEST".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Please help me,

Thanks

David

**Comment by pmoulon** [comment]
Hi,
Could you provide the full CMAKE log starting from an empty output directory (File/DeleteCache)?

Thanks for the warning information.

**Comment by pmoulon** [comment]
@CXZ116 any news about my question?
