### ISSUE TITLE
How to set  camera parameters?

### ISSUE THREAD

**Issue by mojovski** [openMVG/openMVG#245]
I would like to process some examples from the  Strecha Dataset (http://cvlabwww.epfl.ch/data/multiview/denseMVS.html) but cant find a way to set the camera parameters accordingly.
The main issue is that the paramers include two focal lengthts (fx, fy) and image center coordinates, which are *not* the center of the images.
It means, that I have to set a camera matrix similar to this one 
![image](http://docs.opencv.org/trunk/_images/math/7cc828039da1b2c12555f09c86b260dcde5c998a.png)

Since I assume that the framework has already been tested on similar benchmarks, it would be great to see how it has been used practically. Maybe I miss something where to set these parameters?

Thank you very much in advance!

**Comment by pmoulon** [comment]
Hi,
This is a feature that will be available in the next release.
You can already test it in the develop branch.
See here: https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_CreateList.cpp#L74

Just use -k "2759.48;0;1520.69;0;2764.16;1006.81;0;0;1" for example on the main_CreateList binary.

**Comment by mojovski** [comment]
Great! 
Thank you very much!
