### ISSUE TITLE
[multiview] L1 Rotation averaging (Cholesky Factorization)

### ISSUE THREAD

**Issue by sweeneychris** [openMVG/openMVG#255]
https://github.com/openMVG/openMVG/blob/master/src/openMVG/multiview/rotation_averaging_l1.cpp#L129

You can use LLT instead of LDLT because the matrix you are solving is guaranteed to be positive definite.

**Comment by pmoulon** [comment]
Hi @sweeneychris , you're right, we can use LLT.
I have tried on many tiny scenes and LLT is working fine, I have not yet compared timing results, but LLT should be faster than LDLT.
Thanks for having pointing that.

**Comment by sweeneychris** [comment]
Sure thing. You may also want to consider using the sparse cholesky method for large scenes. It should give much better performance than the dense method.
