### ISSUE TITLE
Illegal exception in vagrant package

### ISSUE THREAD

**Issue by danylaksono** [openMVG/openMVG#258]
Hi, 

I am using ubuntu trusty on vagrant-virtualbox to run openMVG. I installed openMVG using [this script](https://github.com/pyp22/Photogrammetry/tree/master/openMVG/Linux/openMVG-installation). As far as I concerned, the make process went well. However, failure occurs during test, as follow:

Testing...
Running tests...
Test project /usr/local/src/openMVG/src/build
      Start  1: openMVG_test_bundle_adjustment
 1/51 Test  #1: openMVG_test_bundle_adjustment ...........................***Exception: Illegal 10.64 sec
      Start  2: openMVG_test_Camera_IO
 2/51 Test  #2: openMVG_test_Camera_IO ...................................***Exception: Illegal  0.57 sec
      Start  3: openMVG_test_exif_IO
 3/51 Test  #3: openMVG_test_exif_IO .....................................***Exception: Illegal  0.59 sec
      Start  4: openMVG_test_features
 4/51 Test  #4: openMVG_test_features ....................................***Exception: Illegal  0.56 sec
      Start  5: openMVG_graph_test_connectedComponent
 5/51 Test  #5: openMVG_graph_test_connectedComponent ....................   Passed    0.01 sec
      Start  6: openMVG_graph_test_triplet_finder
 6/51 Test  #6: openMVG_graph_test_triplet_finder ........................   Passed    0.02 sec
      Start  7: openMVG_test_image
 7/51 Test  #7: openMVG_test_image .......................................***Exception: Illegal  0.58 sec
      Start  8: openMVG_test_image_drawing
 8/51 Test  #8: openMVG_test_image_drawing ...............................***Exception: Illegal  0.56 sec
      Start  9: openMVG_test_image_io
 9/51 Test  #9: openMVG_test_image_io ....................................***Exception: Illegal  1.12 sec
      Start 10: openMVG_linearProgramming_test_linearProgramming
10/51 Test #10: openMVG_linearProgramming_test_linearProgramming .........***Exception: Illegal  0.57 sec
      Start 11: openMVG_lInftyCV_test_triangulation
11/51 Test #11: openMVG_lInftyCV_test_triangulation ......................***Exception: Illegal  0.61 sec
      Start 12: openMVG_lInftyCV_test_resection
12/51 Test #12: openMVG_lInftyCV_test_resection ..........................***Exception: Illegal  0.55 sec
      Start 13: openMVG_lInftyCV_test_resection_robust
13/51 Test #13: openMVG_lInftyCV_test_resection_robust ...................***Exception: Illegal  0.56 sec
      Start 14: openMVG_lInftyCV_test_global_translations_fromTriplets
14/51 Test #14: openMVG_lInftyCV_test_global_translations_fromTriplets ...***Exception: Illegal  0.56 sec
      Start 15: openMVG_lInftyCV_test_global_translations_fromTij
15/51 Test #15: openMVG_lInftyCV_test_global_translations_fromTij ........***Exception: Illegal  0.58 sec
      Start 16: openMVG_lInftyCV_test_tijsAndXis
16/51 Test #16: openMVG_lInftyCV_test_tijsAndXis .........................***Exception: Illegal  0.55 sec
      Start 17: openMVG_lInftyCV_test_tijsAndXis_outlier
17/51 Test #17: openMVG_lInftyCV_test_tijsAndXis_outlier .................***Exception: Illegal  0.56 sec
      Start 18: openMVG_test_rigid_transformation3D_srt
18/51 Test #18: openMVG_test_rigid_transformation3D_srt ..................***Exception: Illegal  0.61 sec
      Start 19: openMVG_test_half_space_intersection
19/51 Test #19: openMVG_test_half_space_intersection .....................***Exception: Illegal  0.54 sec
      Start 20: openMVG_test_frustum_intersection
20/51 Test #20: openMVG_test_frustum_intersection ........................***Exception: Illegal  0.56 sec
      Start 21: openMVG_test_matching
21/51 Test #21: openMVG_test_matching ....................................***Exception: Illegal  0.56 sec
      Start 22: openMVG_test_matching_filters
22/51 Test #22: openMVG_test_matching_filters ............................***Exception: Illegal  0.59 sec
      Start 23: openMVG_test_indMatch
23/51 Test #23: openMVG_test_indMatch ....................................   Passed    0.01 sec
      Start 24: openMVG_test_metric
24/51 Test #24: openMVG_test_metric ......................................***Exception: Illegal  0.57 sec
      Start 25: openMVG_test_Pair_Builder
25/51 Test #25: openMVG_test_Pair_Builder ................................   Passed    0.01 sec
      Start 26: openMVG_test_triangulation
26/51 Test #26: openMVG_test_triangulation ...............................***Exception: Illegal  0.57 sec
      Start 27: openMVG_test_triangulation_nview
27/51 Test #27: openMVG_test_triangulation_nview .........................***Exception: Illegal  0.60 sec
      Start 28: openMVG_test_solver_affine
28/51 Test #28: openMVG_test_solver_affine ...............................***Exception: Illegal  0.55 sec
      Start 29: openMVG_test_solver_fundamental_kernel
29/51 Test #29: openMVG_test_solver_fundamental_kernel ...................***Exception: Illegal  0.57 sec
      Start 30: openMVG_test_solver_essential_kernel
30/51 Test #30: openMVG_test_solver_essential_kernel .....................***Exception: Illegal  0.54 sec
      Start 31: openMVG_test_solver_homography_kernel
31/51 Test #31: openMVG_test_solver_homography_kernel ....................***Exception: Illegal  0.58 sec
      Start 32: openMVG_test_solver_essential_five_point
32/51 Test #32: openMVG_test_solver_essential_five_point .................***Exception: Illegal  0.56 sec
      Start 33: openMVG_test_solver_resection_kernel
33/51 Test #33: openMVG_test_solver_resection_kernel .....................***Exception: Illegal  0.56 sec
      Start 34: openMVG_test_solver_translation_knownRotation_kernel
34/51 Test #34: openMVG_test_solver_translation_knownRotation_kernel .....***Exception: Illegal  0.57 sec
      Start 35: openMVG_test_rotation_averaging
35/51 Test #35: openMVG_test_rotation_averaging ..........................***Exception: Illegal  0.57 sec
      Start 36: openMVG_test_translation_averaging
36/51 Test #36: openMVG_test_translation_averaging .......................***Exception: Illegal  0.56 sec
      Start 37: openMVG_test_numeric
37/51 Test #37: openMVG_test_numeric .....................................***Exception: Illegal  0.54 sec
      Start 38: openMVG_test_poly
38/51 Test #38: openMVG_test_poly ........................................***Exception: Illegal  0.59 sec
      Start 39: openMVG_test_lm
39/51 Test #39: openMVG_test_lm ..........................................***Exception: Illegal  0.58 sec
      Start 40: openMVG_test_rand_sampling
40/51 Test #40: openMVG_test_rand_sampling ...............................   Passed    0.01 sec
      Start 41: openMVG_test_robust_estimator_lineKernel
41/51 Test #41: openMVG_test_robust_estimator_lineKernel .................***Exception: Illegal  0.57 sec
      Start 42: openMVG_test_robust_estimator_MaxConsensus
42/51 Test #42: openMVG_test_robust_estimator_MaxConsensus ...............***Exception: Illegal  0.56 sec
      Start 43: openMVG_test_robust_estimator_Ransac
43/51 Test #43: openMVG_test_robust_estimator_Ransac .....................***Exception: Illegal  0.56 sec
      Start 44: openMVG_test_robust_estimator_ACRansac
44/51 Test #44: openMVG_test_robust_estimator_ACRansac ...................***Exception: Illegal  0.56 sec
      Start 45: openMVG_test_split
45/51 Test #45: openMVG_test_split .......................................   Passed    0.01 sec
      Start 46: openMVG_test_tracks
46/51 Test #46: openMVG_test_tracks ......................................***Exception: Illegal  0.56 sec
      Start 47: openMVG_test_global_quantile_gain_offset_alignment
47/51 Test #47: openMVG_test_global_quantile_gain_offset_alignment .......***Exception: Illegal  0.58 sec
      Start 48: openMVG_test_sfm_data_io
48/51 Test #48: openMVG_test_sfm_data_io .................................***Exception: Illegal  0.56 sec
      Start 49: openMVG_test_sfm_data_BA
49/51 Test #49: openMVG_test_sfm_data_BA .................................***Exception: Illegal  0.55 sec
      Start 50: openMVG_test_ParseDatabase
50/51 Test #50: openMVG_test_ParseDatabase ...............................***Exception: Illegal  0.57 sec
      Start 51: openMVG_test_SfMIOHelper
51/51 Test #51: openMVG_test_SfMIOHelper .................................***Exception: Illegal  0.55 sec

12% tests passed, 45 tests failed out of 51

I found similar issue in #28. I wonder if this has to do with virtual graphic driver in vagrant? If it help, this is the result from cat/proc/cpuinfo:

vagrant@vagrant-ubuntu-trusty-64:~/workdir$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
stepping        : 7
cpu MHz         : 0.000
cache size      : 6144 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips        : 1587.20
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
stepping        : 7
cpu MHz         : 0.000
cache size      : 6144 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips        : 1587.20
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

any help would be appreciated. Thanks

**Comment by pmoulon** [comment]
Can you tell me if you are using a 32 or a 64 bit ubuntu image?
If you are using a 32 bit version, error can be due to alignement issue that are now fixed in the develop_newIO branch.

**Comment by danylaksono** [comment]
Hi, 

I am using 64bit *ubuntu/trusty64* vagrantbox with virtualbox. However, I might have found the problem, which is caused by [virtualbox's lack of support for avx instruction](http://stackoverflow.com/questions/24543874/does-ubuntu-14-04-support-avx-extension). If that's true then it means that turning off avx during cmake will probably solve the problem. I'll do some more test and will close this issue for now. 

Thanks for your response.

**Comment by FreakTheMighty** [comment]
@danylaksono did turning off AVX solve the problem for you. I've been working setting up a docker build, and ran into what looks like the same problem when running it on my mac. That would seem to fit your guess, as docker on mac run on virtualbox.

I'd love to get a docker build that works on virtualbox, but I'm not sure of a clean way to support with and without AVX.

For reference, here is the docker build in question. https://hub.docker.com/r/freakthemighty/openmvg/

**Comment by pmoulon** [comment]
You can make some tweak here to set AVX to false.
https://github.com/openMVG/openMVG/blob/master/src/cmakeFindModules/OptimizeForArchitecture.cmake
You can certainly force by using in the cmake command line one of those:
https://github.com/openMVG/openMVG/blob/master/src/cmakeFindModules/OptimizeForArchitecture.cmake#L265
set(AVX_FOUND false)
set(XOP_FOUND false)
set(FMA4_FOUND false)
set(AVX2_FOUND false)

or directly use Vc_AVX_INTRINSICS_BROKEN that will put to false all the previous.

**Comment by FreakTheMighty** [comment]
@pmoulon thanks for the tip. Unfortunately, turning AVX off doesn't seem like a good option for the docker build. Too bad there is no way to turn AVX off at runtime. Its a bit hacky, but I could setup the docker build to perform two builds, with an without AVX. That way someone can choose which build to use at runtime.

**Comment by RemoteSensingFrank** [comment]
@pmoulon 
And I have the same problem and by the way I turn off the AVX off but it seems not solve my problem, by the way the test error is : 
Test project /home/wuwei/Git/openMVG_build
      Start  1: openMVG_test_Camera_IO
 1/76 Test  #1: openMVG_test_Camera_IO ...................................***Exception: Illegal  0.44 sec
      Start  2: openMVG_test_Camera_Pinhole
 2/76 Test  #2: openMVG_test_Camera_Pinhole ..............................***Exception: Illegal  0.31 sec
      Start  3: openMVG_test_Camera_Pinhole_Radial
 3/76 Test  #3: openMVG_test_Camera_Pinhole_Radial .......................***Exception: Illegal  0.26 sec
      Start  4: openMVG_test_Camera_Pinhole_Brown
 4/76 Test  #4: openMVG_test_Camera_Pinhole_Brown ........................***Exception: Illegal  0.20 sec
      Start  5: openMVG_test_Camera_Pinhole_Fisheye
 5/76 Test  #5: openMVG_test_Camera_Pinhole_Fisheye ......................***Exception: Illegal  0.36 sec
      Start  6: openMVG_test_Camera_Spherical
 6/76 Test  #6: openMVG_test_Camera_Spherical ............................***Exception: Illegal  0.23 sec
      Start  7: openMVG_test_Camera_Subset_Parametrization
 7/76 Test  #7: openMVG_test_Camera_Subset_Parametrization ...............***Exception: Illegal  0.23 sec
      Start  8: openMVG_test_exif_IO
 8/76 Test  #8: openMVG_test_exif_IO .....................................***Exception: Illegal  0.28 sec
      Start  9: openMVG_test_ParseDatabase
 9/76 Test  #9: openMVG_test_ParseDatabase ...............................***Exception: Illegal  0.21 sec
      Start 10: openMVG_test_features
10/76 Test #10: openMVG_test_features ....................................***Exception: Illegal  0.31 sec
      Start 11: openMVG_test_image_describer
11/76 Test #11: openMVG_test_image_describer .............................***Exception: Illegal  0.34 sec
      Start 12: openMVG_test_akaze
12/76 Test #12: openMVG_test_akaze .......................................***Exception: Illegal  0.23 sec
      Start 13: openMVG_test_mser
13/76 Test #13: openMVG_test_mser ........................................***Exception: Illegal  0.26 sec
      Start 14: openMVG_test_sift
14/76 Test #14: openMVG_test_sift ........................................***Exception: Illegal  0.30 sec
      Start 15: openMVG_test_tbmr
15/76 Test #15: openMVG_test_tbmr ........................................***Exception: Illegal  0.24 sec
      Start 16: openMVG_graph_test_connectedComponent
16/76 Test #16: openMVG_graph_test_connectedComponent ....................***Exception: Illegal  0.27 sec
      Start 17: openMVG_graph_test_triplet_finder
17/76 Test #17: openMVG_graph_test_triplet_finder ........................   Passed    0.00 sec
      Start 18: openMVG_test_image
18/76 Test #18: openMVG_test_image .......................................***Exception: Illegal  0.22 sec
      Start 19: openMVG_test_image_drawing
19/76 Test #19: openMVG_test_image_drawing ...............................***Exception: Illegal  0.22 sec
      Start 20: openMVG_test_image_integral
20/76 Test #20: openMVG_test_image_integral ..............................***Exception: Illegal  0.31 sec
      Start 21: openMVG_test_image_io
21/76 Test #21: openMVG_test_image_io ....................................***Exception: Illegal  0.27 sec
      Start 22: openMVG_test_image_filtering
22/76 Test #22: openMVG_test_image_filtering .............................***Exception: Illegal  0.31 sec
      Start 23: openMVG_test_image_resampling
23/76 Test #23: openMVG_test_image_resampling ............................***Exception: Illegal  0.34 sec
      Start 24: openMVG_test_linearProgramming
24/76 Test #24: openMVG_test_linearProgramming ...........................***Exception: Illegal  0.27 sec
      Start 25: openMVG_lInftyCV_test_triangulation
25/76 Test #25: openMVG_lInftyCV_test_triangulation ......................***Exception: Illegal  0.28 sec
      Start 26: openMVG_lInftyCV_test_resection
26/76 Test #26: openMVG_lInftyCV_test_resection ..........................***Exception: Illegal  0.32 sec
      Start 27: openMVG_lInftyCV_test_resection_robust
27/76 Test #27: openMVG_lInftyCV_test_resection_robust ...................***Exception: Illegal  0.35 sec
      Start 28: openMVG_lInftyCV_test_global_translations_fromTriplets
28/76 Test #28: openMVG_lInftyCV_test_global_translations_fromTriplets ...***Exception: Illegal  0.36 sec
      Start 29: openMVG_lInftyCV_test_global_translations_fromTij
29/76 Test #29: openMVG_lInftyCV_test_global_translations_fromTij ........***Exception: Illegal  0.31 sec
      Start 30: openMVG_lInftyCV_test_tijsAndXis
30/76 Test #30: openMVG_lInftyCV_test_tijsAndXis .........................***Exception: Illegal  0.35 sec
      Start 31: openMVG_lInftyCV_test_tijsAndXis_outlier
31/76 Test #31: openMVG_lInftyCV_test_tijsAndXis_outlier .................***Exception: Illegal  0.41 sec
      Start 32: openMVG_geodesy_test_geodesy
32/76 Test #32: openMVG_geodesy_test_geodesy .............................***Exception: Illegal  0.44 sec
      Start 33: openMVG_test_convex_hull
33/76 Test #33: openMVG_test_convex_hull .................................***Exception: Illegal  0.46 sec
      Start 34: openMVG_test_rigid_transformation3D_srt
34/76 Test #34: openMVG_test_rigid_transformation3D_srt ..................***Exception: Illegal  0.35 sec
      Start 35: openMVG_test_plane_estimation_kernel
35/76 Test #35: openMVG_test_plane_estimation_kernel .....................***Exception: Illegal  0.30 sec
      Start 36: openMVG_test_half_space_intersection
36/76 Test #36: openMVG_test_half_space_intersection .....................***Exception: Illegal  0.36 sec
      Start 37: openMVG_test_frustum_intersection
37/76 Test #37: openMVG_test_frustum_intersection ........................***Exception: Illegal  0.39 sec
      Start 38: openMVG_test_frustum_box_intersection
38/76 Test #38: openMVG_test_frustum_box_intersection ....................***Exception: Illegal  0.22 sec
      Start 39: openMVG_test_matching
39/76 Test #39: openMVG_test_matching ....................................***Exception: Illegal  0.20 sec
      Start 40: openMVG_test_matching_filters
40/76 Test #40: openMVG_test_matching_filters ............................***Exception: Illegal  0.19 sec
      Start 41: openMVG_test_indMatch
41/76 Test #41: openMVG_test_indMatch ....................................***Exception: Illegal  0.19 sec
      Start 42: openMVG_test_metric
42/76 Test #42: openMVG_test_metric ......................................***Exception: Illegal  0.18 sec
      Start 43: openMVG_test_Pair_Builder
43/76 Test #43: openMVG_test_Pair_Builder ................................***Exception: Illegal  0.21 sec
      Start 44: openMVG_test_triangulation
44/76 Test #44: openMVG_test_triangulation ...............................***Exception: Illegal  0.25 sec
      Start 45: openMVG_test_triangulation_nview
45/76 Test #45: openMVG_test_triangulation_nview .........................***Exception: Illegal  0.27 sec
      Start 46: openMVG_test_solver_affine
46/76 Test #46: openMVG_test_solver_affine ...............................***Exception: Illegal  0.23 sec
      Start 47: openMVG_test_solver_fundamental_kernel
47/76 Test #47: openMVG_test_solver_fundamental_kernel ...................***Exception: Illegal  0.26 sec
      Start 48: openMVG_test_solver_essential_kernel
48/76 Test #48: openMVG_test_solver_essential_kernel .....................***Exception: Illegal  0.37 sec
      Start 49: openMVG_test_solver_homography_kernel
49/76 Test #49: openMVG_test_solver_homography_kernel ....................***Exception: Illegal  0.22 sec
      Start 50: openMVG_test_solver_essential_five_point
50/76 Test #50: openMVG_test_solver_essential_five_point .................***Exception: Illegal  0.23 sec
      Start 51: openMVG_test_solver_resection_kernel
51/76 Test #51: openMVG_test_solver_resection_kernel .....................***Exception: Illegal  0.23 sec
      Start 52: openMVG_test_solver_translation_knownRotation_kernel
52/76 Test #52: openMVG_test_solver_translation_knownRotation_kernel .....***Exception: Illegal  0.20 sec
      Start 53: openMVG_test_rotation_averaging
53/76 Test #53: openMVG_test_rotation_averaging ..........................***Exception: Illegal  0.24 sec
      Start 54: openMVG_test_translation_averaging
54/76 Test #54: openMVG_test_translation_averaging .......................***Exception: Illegal  0.19 sec
      Start 55: openMVG_test_extract_columns
55/76 Test #55: openMVG_test_extract_columns .............................***Exception: Illegal  0.25 sec
      Start 56: openMVG_test_numeric
56/76 Test #56: openMVG_test_numeric .....................................***Exception: Illegal  0.22 sec
      Start 57: openMVG_test_poly
57/76 Test #57: openMVG_test_poly ........................................***Exception: Illegal  0.23 sec
      Start 58: openMVG_test_lm
58/76 Test #58: openMVG_test_lm ..........................................***Exception: Illegal  0.22 sec
      Start 59: openMVG_test_l1_solver
59/76 Test #59: openMVG_test_l1_solver ...................................***Exception: Illegal  0.23 sec
      Start 60: openMVG_test_rand_sampling
60/76 Test #60: openMVG_test_rand_sampling ...............................***Exception: Illegal  0.24 sec
      Start 61: openMVG_test_robust_estimator_lineKernel
61/76 Test #61: openMVG_test_robust_estimator_lineKernel .................***Exception: Illegal  0.22 sec
      Start 62: openMVG_test_robust_estimator_MaxConsensus
62/76 Test #62: openMVG_test_robust_estimator_MaxConsensus ...............***Exception: Illegal  0.24 sec
      Start 63: openMVG_test_robust_estimator_Ransac
63/76 Test #63: openMVG_test_robust_estimator_Ransac .....................***Exception: Illegal  0.26 sec
      Start 64: openMVG_test_robust_estimator_ACRansac
64/76 Test #64: openMVG_test_robust_estimator_ACRansac ...................***Exception: Illegal  0.25 sec
      Start 65: openMVG_test_tracks
65/76 Test #65: openMVG_test_tracks ......................................   Passed    0.00 sec
      Start 66: openMVG_test_global_quantile_gain_offset_alignment
66/76 Test #66: openMVG_test_global_quantile_gain_offset_alignment .......***Exception: Illegal  0.26 sec
      Start 67: openMVG_test_progress
67/76 Test #67: openMVG_test_progress ....................................***Exception: Illegal  0.24 sec
      Start 68: openMVG_test_sfm_data_io
68/76 Test #68: openMVG_test_sfm_data_io .................................***Exception: Illegal  0.25 sec
      Start 69: openMVG_test_sfm_data_BA
69/76 Test #69: openMVG_test_sfm_data_BA .................................***Exception: Illegal  0.24 sec
      Start 70: openMVG_test_sfm_data_utils
70/76 Test #70: openMVG_test_sfm_data_utils ..............................***Exception: Illegal  0.26 sec
      Start 71: openMVG_test_sfm_data_filters
71/76 Test #71: openMVG_test_sfm_data_filters ............................***Exception: Illegal  0.23 sec
      Start 72: openMVG_test_sfm_data_graph_utils
72/76 Test #72: openMVG_test_sfm_data_graph_utils ........................***Exception: Illegal  0.25 sec
      Start 73: openMVG_test_sequential_SfM
73/76 Test #73: openMVG_test_sequential_SfM ..............................***Exception: Illegal  0.27 sec
      Start 74: openMVG_test_global_SfM
74/76 Test #74: openMVG_test_global_SfM ..................................***Exception: Illegal  0.28 sec
      Start 75: openMVG_test_split
75/76 Test #75: openMVG_test_split .......................................***Exception: Illegal  0.25 sec
      Start 76: openMVG_test_dynamic_bitset
76/76 Test #76: openMVG_test_dynamic_bitset ..............................***Exception: Illegal  0.26 sec

and my cpu info is : 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Pentium(R) CPU 3560M @ 2.40GHz
stepping	: 3
microcode	: 0x17
cpu MHz		: 2400.000
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4788.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Pentium(R) CPU 3560M @ 2.40GHz
stepping	: 3
microcode	: 0x17
cpu MHz		: 2400.000
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4788.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
I wonder if it's wrong for me to turning the AVX off, I change the OptimizeForArchitecture.cmake as 
      #if(DEFINED Vc_AVX_INTRINSICS_BROKEN AND Vc_AVX_INTRINSICS_BROKEN)
      #   UserWarning("AVX disabled per default because of old/broken toolchain")
         set(_avx_broken false)
         set(_avx2_broken false)
         set(_fma4_broken false)
         set(_xop_broken false)
      #else()
      #      set(_avx_broken false)
      #      if(DEFINED Vc_FMA4_INTRINSICS_BROKEN AND Vc_FMA4_INTRINSICS_BROKEN)
      #         UserWarning("FMA4 disabled per default because of old/broken toolchain")
      #         set(_fma4_broken true)
      #      else()
      #         set(_fma4_broken false)
      #      endif()
      #      if(DEFINED Vc_XOP_INTRINSICS_BROKEN AND Vc_XOP_INTRINSICS_BROKEN)
      #         UserWarning("XOP disabled per default because of old/broken toolchain")
      #         set(_xop_broken true)
      #      else()
      #         set(_xop_broken false)
      #      endif()
      #      if(DEFINED Vc_AVX2_INTRINSICS_BROKEN AND Vc_AVX2_INTRINSICS_BROKEN)
      #         UserWarning("AVX2 disabled per default because of old/broken toolchain")
      #         set(_avx2_broken true)
      #      else()
      #         set(_avx2_broken false)
      #      endif()
      #   endif()

**Comment by pmoulon** [comment]
Seems like your virtualization env. does not like the AVX instruction.
You can try to add this to the cmake command line for compilation `-DTARGET_ARCHITECTURE=generic`
and try again.
It should be running ok with this setting.

**Comment by RemoteSensingFrank** [comment]
thanks a lot and all the test passed
