### ISSUE TITLE
[software/SfM] main_computeStructureFromKnownPoses

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#262]
Load a SfM_Data scene (Views|Intrinsics|Extrinsics) to estimate a valid scene Structure from pairwise noisy features correspondences:
- Allow to use GT camera position for structure estimation,
- Allow to stich back some correspondences that have been discarded.

From a series of pair:
 - compute valid geometric & photometric correspondences
 - link them as triplets (triangulation to assert local coherence)
 - fuse validated correspondences sets into tracks & a SfM_Data Structure/Landmarks
 - robust triangulation #261
 - Export the scene with the computed structure/Landmarks.

Pair can provide from:
- [x] pure camera visibility check (camera View frustum intersection) #257 
- [x] from previous pair selected by putative photometric matching or geometric estimation.

**Comment by mojovski** [comment]
Finally, I found time to have a look on this feature.
My first step is to generate a sfm_data.json file by my own.
However, I don't get how to set the polymorphic_id numbers. Is it something, what is set by cereal automatically?

ps: Random numbers don't work :8ball:

**Comment by pmoulon** [comment]
If you use the OpenMVG API to generate a SfM_Data scene with your data you just have use the Save function.
If you generate it by hand with a json library or in ascii, it's a bit dangerous..
You're right, cereal set the polymorphic_id numbers automatically, but I don't know how he do it. It's seems to be just increasing numbers.

**Comment by mojovski** [comment]
I just found it. But its hacky. I start with 2147483649, increment it on each view and use the incremented value for the id of the intrinsics. However, the method ./openMVG_main_ComputeStructureFromKnownPoses is not working yet. I will post here the results as soon as I have something valuable.

Thanks for your help! and of course the great framework :)

**Comment by mojovski** [comment]
As for the ids in the sfm_data.json: The hack still works, but I dont know if this approach is future-stable. I posted this question [here](http://stackoverflow.com/questions/31669896/how-to-create-manually-a-file-for-cereal-import) but it doesn't look like many people are interested in it. whatever...

I did some tests today with the **main_ComputeStructureFromKnownPoses** tool, **without** to apply BA as a final step.
Even if the trajectory of the cameras is quite accurate (used visual inertial slam system of super accuracy), the pure structure computation looks not soooo good.

Does anyone have an educated guess how I can improve this tuning/debugging the triangulation method from 
```
SfM_Data_Structure_Computation_Robust::robust_triangulation
```
?

**Comment by pmoulon** [comment]
Regarding the cereal Id problem I think it's better to ask the question here:
https://groups.google.com/forum/#!forum/cerealcpp

I think normally some houses must appear... Without knowing the images it's hard to say.
So if I understood well, here the steps you have performed:
- you have made your own sfm_data.json file with your views & intrinsics & poses
- you have used main_compute_features on it
- you have used main_ComputeStructureFromKnownPoses on the resulting features directory

**Comment by mojovski** [comment]
The process was as follows:
* generate my own sfm_data.json (correct!)
* apply main_ComputeFeatures (also correct! :) )
* apply main_ComputeMatches (geometry: epipolar check, )
* use main_ComputeStructureFromKnownPoses -f matches.e.txt ....

As for the images, here is a sample to get a feeling.
![gif](http://ibin.co/2ACco8Spkknz)

**Comment by pmoulon** [comment]
Thanks for the sharing and the additionnal explanation.
It would be better to continue this thread on the mailing list openmvg-team[AT]googlegroups.com
Have you tried to just do the process on a tiny sample.
I mean take your sfm_data.json, and keep only the 10 first view & poses.
and rerun.

You can also:
- use the fundamental pair matches rather the essential => matches.f.txt
- log your matches to see if they are good:
  - use main_ExportMatches
- try to export your camera frustra to see if they are looking in the right direction:
  - see main_ExportCameraFrustums in software/SfM directory.
- do not use the -f option on main_ComputeStructureFromKnownPoses [for a test] (it will take more time but will use all camera frustum that intersect)

**Comment by mojovski** [comment]
Assuming that my poses are wrong, I replaced the intrinsic data in sfm_data.json by the poses computed by main_GlobalSfM. This resulted however, that [triangulation class](https://github.com/openMVG/openMVG/blob/82ecbc44fd638956ca98c5621b35185c75db4dd9/src/openMVG/multiview/triangulation_nview.cpp#L145) returns large errors, which are filtered out by the [structure estimator](https://github.com/openMVG/openMVG/blob/bc0def639a2c8a0b5877baa863e3815bab83fd02/src/openMVG/sfm/pipelines/structure_from_known_poses/structure_estimator.cpp#L263)

Does this lead to the conclusion, that the issue is in the module?
@pmoulon , do you have successful results after using it ?

**Comment by pmoulon** [comment]
Hi,
Replacing only the intrinsic is not sufficient (but perhaps I have not well understood, perhaps your have replaced also your extrinsic). I mean if your poses are not sufficiently good, points triangulation will be bad.

I'm confident with the code, since it works fine on various scenes => you can run Build/software/SfM/tutorial_demo.py to be convinced you will see that the point cloud named robust.ply is looking fine.

In order to check if the problem is the poses accuracy can you try one or the two SfM pipeline on your dataset from scratch.

**Comment by mojovski** [comment]
sorry, meant of course the "extrinsics"...
