### ISSUE TITLE
Error in main_GlobalSfM

### ISSUE THREAD

**Issue by Rouen007** [openMVG/openMVG#263]
When I run openMVG_main_GlobalSfM in VS2010, It always break in SfMGlobalEngine.cpp's line 1356--"Histogram<float> histo(0.0f, *max_element(vec_errToIdentityPerTriplet.begin(), vec_errToIdentityPerTriplet.end()), 180)" and the compiler told me "Expression: vector iterator not dereferencable".(because vec_triplets.size() =0, but i have no idea why the size is zero)

**Comment by pmoulon** [comment]
It certainly a bug if the scene is empty.
Can you tell me which branch are you using?

Can you try on this dataset: https://github.com/openMVG/ImageDataset_SceauxCastle

**Comment by Rouen007** [comment]
Thank you very much. 
I used the database "kermit" in bundler, may be the too few correspondences lead this fail. 
Use the database you mentioned aboved, the software works well.

**Comment by pmoulon** [comment]
For dataset with few corresponding sift you can use the -p 0.01 option on main_computeMatches to have more sift per images.

**Comment by Rouen007** [comment]
Thank you very much!

2015-04-22



Ang Lu



发件人：Pierre Moulon <notifications@github.com>
发送时间：2015-04-21 22:30
主题：Re: [openMVG] Error in main_GlobalSfM (#263)
收件人："openMVG/openMVG"<openMVG@noreply.github.com>
抄送："Rouen007"<luang007@163.com>

For dataset with few corresponding sift you can use the -p 0.01 option on main_computeMatches to have more sift per images.

**Comment by Rouen007** [comment]
When I turn  -p 0.01 option on main_computeMatches  to enhance the number of correspondences, the error still exit. Can you tell me how could I judge the scene is empty or not?

**Comment by pmoulon** [comment]
I though that the process tell at the end that the scene contains 0 images.
But it seems that in your case on the Kermit dataset you got an error message in other part.
