### ISSUE TITLE
version header .h => .hpp

### ISSUE THREAD

**Issue by fabiencastan** [openMVG/openMVG#268]
All headers are .hpp, so it could be great to do the same for "version.hpp"
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/version.h

PS: openMVG uses MAJOR.MINOR.REVISION. I think that it's more clear and standard to use: MAJOR.MINOR.MICRO or PATCH.

**Comment by pmoulon** [comment]
It the same, just a variable name that is transparent for user.
Revision seems more explicit than micro (in the meaning).

You're right it should be renamed as .hpp

Note:
The major number should be increased whenever the API changes in an incompatible way.
The minor number should be increased whenever the API changes in a compatible way.
The revision/micro number should be increased whenever the implementation changes, while the API does not.
