### ISSUE TITLE
Ask about a introductory example

### ISSUE THREAD

**Issue by amiltonwong** [openMVG/openMVG#273]
Dear all,

I had installed openMVG successfully in my system, now I want to practice it. It'll be greatly helpful if a brief introductory example provided. Unfortunately, I only found a manul from "https://media.readthedocs.org/pdf/openmvg/latest/openmvg.pdf"
In fact, I just need the following several steps for doing a common SfM pipeline:

1. Where should I fill it the camera calibration information (fx,fy,cx,cy) ? 

2. The command example for feature extraction and feature description for input images

3. The command example for feature matching.

4. The command example for computing essential / fundamental matrix and using RANSEC 

5. The command example for optimization (e.g. BA)

6. Where can I get the output?

Could someone give me the answers for steps above using openMVG?

Thanks in advance!

Milton

**Comment by pmoulon** [comment]
Hi,

Please take a look to the ready to use script:
https://github.com/openMVG/openMVG/issues/64

And the extended doc:
http://openmvg.readthedocs.org/en/latest/software/SfM/SfM/

1) -> http://openmvg.readthedocs.org/en/latest/software/SfM/intrinsicGroups/
2-4) -> http://openmvg.readthedocs.org/en/latest/software/SfM/geometricMatches/
5-6) -> Incremental or Global SfM 
http://openmvg.readthedocs.org/en/latest/software/SfM/incrementalSfM/
http://openmvg.readthedocs.org/en/latest/software/SfM/globalSfM/

OpenMVG 0.8 is on the road and will be ready soon.

Regards,
Pierre

**Comment by amiltonwong** [comment]
Thanks Pierre for your quick response.

I'll practice it soon. A first further question comes to me is that:
In intrinsic groups setting, if I already know intrinsic camera matrix, what's the command to specify the intrinsic camera matrix as follows:
file_name; width_resolution;height_resolution;fx;0;cx;0;fy;cy;0;0;1
I know that I can specify the focal length by the following command:
$ openMVG_main_CreateList -f 2750(i.e in pixels) -i Dataset/images/ -o Dataset/matches/

Thanks~
Milton

**Comment by pmoulon** [comment]
Hi,
You can use the -f 2750 option and modify in the produced file the cx and cy value by hand with search and replace.

In the develop branch you can specify the entire K matrix with the -k option
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_CreateList.cpp#L74

But soon it will be overwritten by the coming 0.8 version in which you will be able to specify those information in a structured JSON file.

**Comment by pmoulon** [comment]
Please close the thread if the answer is ok for your.

**Comment by amiltonwong** [comment]
Thanks Pierre. I'll try it.
So a close this thread first.
