### ISSUE TITLE
Restart after crash

### ISSUE THREAD

**Issue by rperrot** [openMVG/openMVG#275]
Hi all, 

I have a simple request : 

- when reconstruction fail after initial pair choice, it could be interesting to ask again the user for a new pair instead of stopping the process. This can save some time on large reconstruction and be more user friendly.  

If it's not possible, could we save the geometric filtering result, like features and matching ? This could save some time too.

**Comment by pmoulon** [comment]
Hi @rperrot,

Choosing the initial pair is tricky and looping between failing pair could lead to a infinite loop in a sense...
But we can do something about it.

Regarding the "save the geometric filtering result, like features and matching" it already done in main_computeMatches.

**Comment by rperrot** [comment]
Maybe not an infinite loop if we remove the last one (if we prompt again, last pair was not a good choice), so at a certain time, it will end because the list of pair is always decreasing. 

And I think I forgot to activate an option in main_computeMatches ;-)

**Comment by pmoulon** [comment]
@rperrot This issue https://github.com/openMVG/openMVG/issues/399 will provide even a better answer to your request ;-)

**Comment by rperrot** [comment]
Excellent !
