### ISSUE TITLE
ask dataset download location for ACCV 2012 paper

### ISSUE THREAD

**Issue by amiltonwong** [openMVG/openMVG#284]
Hi, Pierre,

I am going to practice openMVG on dataset used in your ACCV 2012 paper "Adaptive Structure from Motion with a contrario model estimation". 
The South Building
https://www.dropbox.com/s/xe43mcs4xlfvy8h/2015-05-08_093219.jpg

I had searched it from Marc Pollefeys's website but couldn't find it. Would you point me to the download link for that dataset or share it?

Thanks in advance~

Milton

**Comment by pmoulon** [comment]
Hi,
This dataset was provided by Christopher Zach, but it's website is now away.

You should ask him the dataset (you will find his email here https://github.com/chzach/SSBA/tree/master/SSBA-4.0)

BTW, you can pratice openMVG on this tiny dataset
https://github.com/openMVG/ImageDataset_SceauxCastle
Or those one (High resolution) from Romuald Perrot
https://github.com/rperrot/ReconstructionDataSet

BTW, you can also use Strecha Mview datasets:
https://github.com/openMVG/SfM_quality_evaluation/tree/master/Benchmarking_Camera_Calibration_2008

Regards.

**Comment by amiltonwong** [comment]
Hi, Pierre,
Thank you very much. I'll practice it.

Best~

**Comment by pmoulon** [comment]
0.8 version will be ready on monday, and ready to use python script to launch the tool set will be available.

**Comment by amiltonwong** [comment]
Hi, Pierre,
Has 0.8 version already released?

**Comment by pmoulon** [comment]
It will be released today, in some hours.

**Comment by pmoulon** [comment]
Hi @amiltonwong 
OpenMVG 0.8 "Simulans" is out
https://github.com/openMVG/openMVG/releases/tag/v0.8
For any help:
http://openmvg.readthedocs.org/en/latest/software/SfM/SfM/
=> once you have done the compilation go in Build/software/SfM and launch
$ python tutorial_demo.py
and look to the exported files in tutorial_out

**Comment by amiltonwong** [comment]
Great!
Thanks Pierre :), I'll give it a try.
