### ISSUE TITLE
v0.8 build error

### ISSUE THREAD

**Issue by amiltonwong** [openMVG/openMVG#289]
Dear all,

I follow the following steps in which I had succeeded in building v0.7 : 

>> git clone --recursive https://github.com/openMVG/openMVG.git
>> cd openMVG
>> git submodule init
>> git submodule update
>> mkdir openMVG_Build && cd openMVG_Build
>> cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . ../src/
>> make

But for the recent v0.8 release, I come across the following build error at around 75% build progress:
 
make[2]: *** [openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole_Radial.dir/Camera_Pinhole_Radial_test.cpp.o] Error 1
make[1]: *** [openMVG/cameras/CMakeFiles/openMVG_test_Camera_Pinhole_Radial.dir/all] Error 2
make: *** [all] Error 2

Could someone give me some suggestions to fix it? 

Thanks in advance!
Milton

**Comment by pmoulon** [comment]
I have tried exactly the same command line as you and I got no problem.

Can you tell me which compiler are you using (compiler version)?
And give more description about the build error "full compiler log".
$ make
copy and share the result as a gist

I have tried on my side with:
gcc version 4.8.2 
VS 2013

**Comment by amiltonwong** [comment]
Hi, Pierre,

My system is Ubuntu 12.04 and gcc version is 4.6.3. I capture the build log as follows:
https://gist.github.com/amiltonwong/6ca5dbd1211be7aad8f3
After I switch to Ubuntu 14.04 and gcc version 4.8.2, I successfully build it now. 

=======================================================

As openMVG use some C++11 features you must have a c++11 ready compiler:
- Visual studio >= 2013
- GCC >= 4.7

=======================================================

Ah...., I had overlooked requirement for GCC version. Thanks for your quick reply.

Best~
Milton

**Comment by pmoulon** [comment]
:+1:
