### ISSUE TITLE
minor error in openMVG_main_SfMInit_ImageListing

### ISSUE THREAD

**Issue by amiltonwong** [openMVG/openMVG#290]
Hi, Pierre,

The following is my log on executing "python tutorial_demo.py"
https://gist.github.com/amiltonwong/1971c7e61877a7f30602

At line 10-11, listing those two text file are considered to be incorrect in openMVG_main_SfMInit_ImageListing. Although it doesn't have impact on the reconstruction result.

**Comment by pmoulon** [comment]
Hi @amiltonwong 
It's warning information, don't matter.
When non image files are parsed there is a message that is displayed (txt files)

**Comment by amiltonwong** [comment]
OK
