### ISSUE TITLE
[building-V0.8] Linux deps

### ISSUE THREAD

**Issue by pyp22** [openMVG/openMVG#294]
Hi guys,
Thanks for the new version :)

It might be relevant to precise to install python2 for the commands module (https://docs.python.org/2/library/commands.html) or comment in #import commands to be able to run the py scripts with python3.

PY

**Comment by pmoulon** [comment]
Hi @pyp22 

Thanks for the suggestion.
But, since we read "Deprecated since version 2.6: The commands module has been removed in Python 3. Use the subprocess module instead." I prefer to continue to use subprocess
