### ISSUE TITLE
[SfM] Obtain view pose thanks a function

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#296]
Add the following functions to SfM_Data:

- bool IsPoseAndIntrinsicDefined(const View * ) const;
  - return true if the view has defined intrinsic and pose data

- Pose3 GetPoseOrDie(const View*) const;
  - return the pose related to a view

Those functions allow to parse in an easiest way the valid Views.
```
For (v in : sfm_data.getViews())
{
 if (!sfm_data.IsPoseAndIntrinsicDefined(v))
   continue;
 const Pose3 view_pose = sfm_data.GetPoseOrDie(v);
 ...
}
``` 
Update function names from:
- getView -> GetViews
- getPoses -> GetPoses
- getIntrinsics -> GetIntrinsics
- getLandmarks -> GetLandmarks

**Comment by fabiencastan** [comment]
Why did you start using UpperCamelCase for functions?
It seems to me that it's not the rule in OpenMVG and it's not really standard.

**Comment by pmoulon** [comment]
It's WIP (develop), and for the moment there is no really standard.
The important is to have an API, no matter the naming convention.

**Comment by fabiencastan** [comment]
Yes, but openMVG mixes multiple rules which is difficult to manage.

Types use upper camel case but sometimes lower camel case. Same for functions.

**Comment by pmoulon** [comment]
You must admit that if you use an IDE with autocompletion, there is not so much difficulties...

BTW, let the time to the library to find it's own rules.
