### ISSUE TITLE
Use string keys instead of indexes in sfm_data.json

### ISSUE THREAD

**Issue by fabiencastan** [openMVG/openMVG#298]
Is it possible to use string keys instead of indexes as ID of the images?

We can generate a unique key using the "Serial Number" metadata + filename or "Serial Number" metadata + timestamp.

**Comment by pmoulon** [comment]
I prefer use integer based indexing that is the more generic and easy to manipulate.

**Comment by fabiencastan** [comment]
Could you explain a bit more your reasons?

Using string based indexing is a lot easier to read and manipulate for humans. The most important thing, is the file format that we manipulate a lot for debugging/analysing.

In the future, we would like to be able to merge reconstructions or to add new images into an existing reconstruction, etc. All thoses things are not possible if we use indexes.

**Comment by pmoulon** [comment]
The main argument I see is integer index allow constant size.
Using string index will force to use string everywhere and it's not a good idea.

The proposed file format is a first version that is working and allow new development that are going fast.

My opinion is that a file format is not here to perform debugging or analysis, it's to store and load data. Those debugging and analysis must be perform with algorithms on top of it.

You can see the merging step as:
- Adding a new image consists in looking for a new free index.
- Merging two scenes with more than one image consists in renaming some ids.

A compromise for your customized case could be to use a hash function that will generate an integer index from your customized unique string key.

BTW, a file format cannot convince all people, match all usage (look the number of image file format...).

So the important is to have a first initial version that allow fast development and see it's limit by improving the library.
Improving the code is a story of time.
