### ISSUE TITLE
Segmentation Fault while "make test"

### ISSUE THREAD

**Issue by wew2012** [openMVG/openMVG#30]
I met problems while compile and make test, which is similar to [this link](https://github.com/openMVG/openMVG/issues/4 "Segmentation Fault in SfMIncrementalEngine.cpp - [Win32]"). I add 
>set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3  -ffast-math -msse -msse2 -msse3") 

in ./src/CMakeLists.txt , and ``make``. Then I got the following errors:

>[ 85%] Built target openMVG_test_triangulation_nview
[ 85%] Built target openMVG_test_lm
[ 86%] Built target openMVG_test_numeric
[ 86%] Built target openMVG_test_poly
[ 86%] Built target openMVG_test_tracks
[ 86%] Built target openMVG_test_rand_sampling
[ 87%] Built target openMVG_test_robust_estimator_ACRansac
[ 87%] Built target openMVG_test_robust_estimator_LMeds
[ 88%] Built target openMVG_test_robust_estimator_MaxConsensus
[ 88%] Built target openMVG_test_robust_estimator_Ransac
[ 88%] Built target openMVG_test_robust_estimator_lineKernel
[ 89%] Building C object patented/sift/CMakeFiles/vlsift.dir/vl/generic.c.o
[ 89%] Building C object patented/sift/CMakeFiles/vlsift.dir/vl/imopv_sse2.c.o
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:21:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
In file included from /home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:28:0:
/usr/lib/gcc/i686-linux-gnu/4.6.1/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
In file included from /home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:34:0:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:21:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
In file included from /home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:34:0:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c: In function ‘_vl_imconvcol_vf_sse2’:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:81:14: error: ‘VSIZE’ undeclared (first use in this function)
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:81:14: note: each undeclared identifier is reported only once for each function it appears in
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:86:15: error: unknown type name ‘VTYPE’
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:87:9: error: unknown type name ‘VTYPE’
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c\:100:20: error: ‘VTYPE’ undeclared (first use in this function)
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c\:100:26: error: expected expression before ‘)’ token
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:111:24: error: expected expression before ‘)’ token
In file included from /home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:38:0:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c: At top level:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:21:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
In file included from /home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:38:0:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c: In function ‘_vl_imconvcol_vd_sse2’:
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:81:14: error: ‘VSIZE’ undeclared (first use in this function)
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:86:15: error: unknown type name ‘VTYPE’
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:87:9: error: unknown type name ‘VTYPE’
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:100:20: error: ‘VTYPE’ undeclared (first use in this function)
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:100:26: error: expected expression before ‘)’ token
/home/fd/softwares/SuiteSparse/openMVG/src/patented/sift/vl/imopv_sse2.c:111:24: error: expected expression before ‘)’ token
make[2]: *** [patented/sift/CMakeFiles/vlsift.dir/vl/imopv_sse2.c.o] Error 1
make[1]: *** [patented/sift/CMakeFiles/vlsift.dir/all] Error 2
make: *** [all] Error 2

Then, I type `make test` and get these errors:

>Running tests...
Test project /home/fd/softwares/SuiteSparse/openMVG_Build
      Start  1: openMVG_test_image
 1/25 Test  #1: openMVG_test_image ...........................   Passed    0.00 sec
      Start  2: openMVG_test_image_drawing
 2/25 Test  #2: openMVG_test_image_drawing ...................   Passed    0.00 sec
      Start  3: openMVG_test_image_io
 3/25 Test  #3: openMVG_test_image_io ........................   Passed    0.00 sec
      Start  4: openMVG_test_features
 4/25 Test  #4: openMVG_test_features ........................   Passed    0.00 sec
      Start  5: openMVG_test_matching
 5/25 Test  #5: openMVG_test_matching ........................   Passed    0.00 sec
      Start  6: openMVG_test_matching_filters
 6/25 Test  #6: openMVG_test_matching_filters ................   Passed    0.00 sec
      Start  7: openMVG_test_indMatch
 7/25 Test  #7: openMVG_test_indMatch ........................   Passed    0.00 sec
      Start  8: openMVG_test_triangulation
 8/25 Test  #8: openMVG_test_triangulation ...................   Passed    0.00 sec
      Start  9: openMVG_test_triangulation_nview
 9/25 Test  #9: openMVG_test_triangulation_nview .............***Exception: Other  0.00 sec
      Start 10: openMVG_test_solver_affine
10/25 Test #10: openMVG_test_solver_affine ...................   Passed    0.00 sec
      Start 11: openMVG_test_solver_fundamental_kernel
11/25 Test #11: openMVG_test_solver_fundamental_kernel .......   Passed    0.00 sec
      Start 12: openMVG_test_solver_essential_kernel
12/25 Test #12: openMVG_test_solver_essential_kernel .........   Passed    0.01 sec
      Start 13: openMVG_test_solver_homography_kernel
13/25 Test #13: openMVG_test_solver_homography_kernel ........   Passed    0.00 sec
      Start 14: openMVG_test_solver_essential_five_point
14/25 Test #14: openMVG_test_solver_essential_five_point .....   Passed    0.01 sec
      Start 15: openMVG_test_solver_resection_kernel
15/25 Test #15: openMVG_test_solver_resection_kernel .........   Passed    0.00 sec
      Start 16: openMVG_test_numeric
16/25 Test #16: openMVG_test_numeric .........................   Passed    0.00 sec
      Start 17: openMVG_test_poly
17/25 Test #17: openMVG_test_poly ............................   Passed    0.00 sec
      Start 18: openMVG_test_lm
18/25 Test #18: openMVG_test_lm ..............................   Passed    0.00 sec
      Start 19: openMVG_test_tracks
19/25 Test #19: openMVG_test_tracks ..........................   Passed    0.00 sec
      Start 20: openMVG_test_rand_sampling
20/25 Test #20: openMVG_test_rand_sampling ...................   Passed    0.00 sec
      Start 21: openMVG_test_robust_estimator_lineKernel
21/25 Test #21: openMVG_test_robust_estimator_lineKernel .....   Passed    0.00 sec
      Start 22: openMVG_test_robust_estimator_MaxConsensus
22/25 Test #22: openMVG_test_robust_estimator_MaxConsensus ...***Exception: Other  0.00 sec
      Start 23: openMVG_test_robust_estimator_Ransac
23/25 Test #23: openMVG_test_robust_estimator_Ransac .........***Exception: Other  0.00 sec
      Start 24: openMVG_test_robust_estimator_LMeds
24/25 Test #24: openMVG_test_robust_estimator_LMeds ..........***Exception: Other  0.00 sec
      Start 25: openMVG_test_robust_estimator_ACRansac
25/25 Test #25: openMVG_test_robust_estimator_ACRansac .......***Exception: Other  0.00 sec
>
>80% tests passed, 5 tests failed out of 25
>
>Total Test time (real) =   0.10 sec
>
>The following tests FAILED:
	  9 - openMVG_test_triangulation_nview (OTHER_FAULT)
	 22 - openMVG_test_robust_estimator_MaxConsensus (OTHER_FAULT)
	 23 - openMVG_test_robust_estimator_Ransac (OTHER_FAULT)
	 24 - openMVG_test_robust_estimator_LMeds (OTHER_FAULT)
	 25 - openMVG_test_robust_estimator_ACRansac (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8

Actually, I find a way to make my compile pass. I add:

>set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -msse -msse2 -msse3")

in `./src/CMakeLists.txt`. Then the compile can pass. However, make test have the same problem.

Environment:

>Ubuntu 11.10 x86
GNU GCC
gcc version 4.6.1 (Ubuntu/Linaro 4.6.1-9ubuntu3)

**Comment by pmoulon** [comment]
@wew2012 , @ORNis 
32 bit systems are now fully functional.
Tested on an ubuntu 32 bit virtual machine
