### ISSUE TITLE
[sfm] Extend BAF file format

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#304]
BAF is used to export data for third party BundleAdjusment issue
Add a file to link view id to view filename.

```
./openMVG_main_ConvertSfM_DataFormat -i /home/.../sfm_data.json -o /home/.../sfm_data.baf
```
will now exports sfm_data.baf and sfm_data_imgList.txt files.

sfm_data_imgList.txt file, log view filename and ids in order to establish a link between structure observations & the corresponding view
```
view_filename id_intrinsic id_pose
...
```

**Comment by fabiencastan** [comment]
What is this BAF file format used for?
Is it for OMVG or for an external software?

**Comment by pmoulon** [comment]
It's a pivot format for OpenSfM tutorial at CVPR15
http://www.kitware.com/cvpr2015-tutorial.html

The file format was made in the spirit of BAL http://grail.cs.washington.edu/projects/bal/.
But BAF is more flexible since it can used shared intrinsics.

**Comment by pmoulon** [comment]
Nope, I'm sorry, but it should be easy to add thanks to the new abstract SfM_Data_GT_Loader_Interface 
 https://github.com/openMVG/openMVG/blob/master/src/software/SfM/import/io_readGTInterface.hpp#L23 or just a single function.
