### ISSUE TITLE
Add sensor size in camera

### ISSUE THREAD

**Issue by eprana** [openMVG/openMVG#307]
When we import a reconstruction in a software (for example Maya), some parameters are needed to configure cameras, like sensor size. 
We have this information for reconstruction, so we can write it in the sfm_data.json file.

**Comment by pmoulon** [comment]
I prefer storing only the necessary data.
But as the view type is abstract you can create your custom view type in which you store the sensor size. So you will be able to have it in your output sfm_data.json file.

BTW, you can also can recover it back by checking the images exif and the database when needed.

**Comment by fabiencastan** [comment]
With opeMVG we are able to calibrate the camera and we retrieve the focal in pixels. But in our case, we would like to retrieve the real-world information of the camera: the focal in mm. The missing information is the film gate size in real-world unit.

It represents 2 integers per camera and will allow to have all the characteristics of the cameras, which is required for us to [load the reconstruction result in Maya](http://download.autodesk.com/global/docs/maya2014/en_us/index.html?url=files/View__Camera_settings.htm,topicNumber=d30e699517) but may be useful for many other use cases.

**Comment by pmoulon** [comment]
I did not understand fully your last point @fabiencastan.
But storing the camera sensor size can be done in a custom view type or your custom intrinsic camera type. You will have the information and you will be able to compute your final values.
