### ISSUE TITLE
CMakelists not getting installed while Building OpenMVG files

### ISSUE THREAD

**Issue by priyanshuchandra** [openMVG/openMVG#308]
I cloned the openMVG from git onto my laptop which runs on Ubuntu 14.04 and followed the linux instructions to build it on my machine. But after building, "openMVG_main_CreateList" is missing. I also referred to similar issue posted by rperrot ( link : https://github.com/openMVG/openMVG/issues/63 ) and tried to implement the solutions given but could not succeed. I specifically tried the following solution:
**********************************
"The doc is done for the develop branch.

So please consider checkout the develop branch.

$ git checkout -b develop remotes/origin/develop
$ git submodule init
$ git submodule update

=> comment the SfMViewer line in the appropriate CMakeLists.txt

and do cmake, make again.

**************************************************

But Still not able to build the CreateList file. What shall I do?

**Comment by pmoulon** [comment]
Hi,
It's normal that you did not see this binary appear, since it does not longer appear in the V0.8.X version. => replaced by SfMInit_ImageListing

Please refer to the exported python examples in your build directory:
_Build/software/SfM/ *.py that explains how to run the toolchain.

You will find here details about all the process binaries here:
http://openmvg.readthedocs.org/en/latest/software/SfM/SfM/
and the listing of the exported ready to use python scripts.

**Comment by pmoulon** [comment]
@priyanshuchandra  Any feedback ?

**Comment by priyanshuchandra** [comment]
Hello,

Yes. It worked. Thanks a lot!

Regards,
Priyanshu

On Fri, May 29, 2015 at 8:50 PM, Pierre Moulon <notifications@github.com>
wrote:

> @priyanshuchandra <https://github.com/priyanshuchandra> Any feedback ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openMVG/openMVG/issues/308#issuecomment-106844100>.
>



-- 
Priyanshu Chandra
Second year
Undergraduate Student (B.Tech)
Mathematics and Computing
Indian Institute of Technology, Guwahati

**Comment by pmoulon** [comment]
Thanks @priyanshuchandra 
TIp: Github issue is a ticket system, so when the provided answer was sufficient you can close the issue to show that the feedback was sufficient ;-)
See at bottom the "Close button" https://github.com/openMVG/openMVG/issues/308
