### ISSUE TITLE
Use openMVG as Third Party library

### ISSUE THREAD

**Issue by baritone** [openMVG/openMVG#314]
Dear Pierre, 

 I am trying to include openMVG as a third party library, I could find it with cmake, there is no problem. However, when I try to compile the code with openMVG hear, I got the following error

    In file included from /usr/local/include/openMVG/cameras/Camera_Pinhole.hpp:14:0,
                 from /usr/local/include/openMVG/cameras/cameras.hpp:12,
                 from /usr/local/include/openMVG/sfm/sfm_data.hpp:14,
                 from /usr/local/include/openMVG/sfm/sfm.hpp:16,
                 from /home/sflotron/foxel/git/Laboratory-of-Photogrammetry/openMVG_Rig  /openMVGRig_create_list/list_utils.cpp:53:
    /usr/local/include/openMVG/third_party/ceres/rotation.h:50:26: fatal error: glog/logging.h: Aucun   fichier ou dossier de ce type
     #include "glog/logging.h"
 
Is it a file that was missed during the installation procedure ? Or I should modify my CMakeLists.txt to find glog ?

**Comment by baritone** [comment]
Seems to be ok now on my computer. Thx !

**Comment by pmoulon** [comment]
Link to #222
