### ISSUE TITLE
OpenMVG ComputeMatches

### ISSUE THREAD

**Issue by priyanshuchandra** [openMVG/openMVG#315]
When I ran function openMVG ComputeMatches  on a set of 30 images. It seems like it has computed matches of random pairs of images. Like image 1 has been matched with 2, 3, 4. Image 2 has been matched with 2 and 3.  Then image 7 has been matched with 8, 10 and 21. I am unable to find the pattern even on reading the code of ComputeMatches.cpp. Can anyone help?

**Comment by pmoulon** [comment]
You can see the images pair that have be matched in the SVG matrix file in the output directory.
PutativeAdjacencyMatrix.svg => Show the image pairs index that have successfully have be matches by SIFT descriptor matching with distance ratio test,
GeometricAdjacencyMatrix.svg => Show the images pairs index that have successfully passed the robust model estimation test.


Some image pairs have disappear because at the end they do not share sufficient similar descriptor or that the image matches does not lead to a valid model estimation.

By default a exhaustive pair matching is performed (upper diagonal)
0-1-2-3
====
0-1
0-2
0-3
1-2
2-3

See here: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L278

**Comment by priyanshuchandra** [comment]
Okay, thanks! But where can I find the exact algorithm of distance ratio test and robust model estimation test?

**Comment by pmoulon** [comment]
Just go trough the code:
Image_collection matching (Descriptor matching):
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L237

Robust Model estimation:
ImageCollectionGeometricFilter (geometric filtering):
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L329

You will find here the code that is calling the matching & geometric filtering routines:
https://github.com/openMVG/openMVG/tree/master/src/openMVG/matching_image_collection

Distance Ratio: 
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/Matcher_Regions_AllInMemory.cpp#L135

Geometric filtering:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/GeometricFilter.hpp#L75

**Comment by pmoulon** [comment]
@priyanshuchandra Does the provided information was sufficient to close the issue?

**Comment by priyanshuchandra** [comment]
Not exactly! Actually, I want to understand the algorithm of Robust Model
Estimation (geometric filtering) properly, which I am not able to. Once, we
have calculated putative matches in the "map_PutativesMatches", what
exactly happens when we pass this in the function
"collectionGeomFilter.Filter" and "geometricFilter.Fit". Can you help me
out on this?

On Tue, Jun 2, 2015 at 2:28 PM, Pierre Moulon <notifications@github.com>
wrote:

> @priyanshuchandra <https://github.com/priyanshuchandra> Does the provided
> information was sufficient to close the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openMVG/openMVG/issues/315#issuecomment-107873621>.
>



-- 
Priyanshu Chandra
Second year
Undergraduate Student (B.Tech)
Mathematics and Computing
Indian Institute of Technology, Guwahati

**Comment by pmoulon** [comment]
Ok,
So putative matches is classical descriptor matching with the distance ratio filtering step (to remove too much repetitive matches).

The geometric filtering take the pair & the correspondences found by the putative matches steps and try to make the robust estimation of the given model (Homography, fundamental or essential matrix) according the user choice.

The robust estimation step is covered by ACRansac (A Contrario Ransac). It's a robust estimation method that allow to find a model and it's fitting accuracy. I use an upper bound of 4 pixels, so the variable precision can be in the [0 4] pixel range.

To known more about Acontrario ransac you can read the ACCV12 & ICCV13 paper:

Moulon Pierre, Monasse Pascal and Marlet Renaud. ACCV 2012. Adaptive Structure from Motion with a contrario model estimation.

Moulon Pierre, Monasse Pascal and Marlet Renaud. ICCV 2013. Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion. 

And finally  the paper that explain in detail the AContrario theory for model estimation. Moisan Lionel, Moulon Pierre and Monasse Pascal. IPOL 2012. Automatic Homographic Registration of a Pair of Images, with A Contrario Elimination of Outliers.

**Comment by priyanshuchandra** [comment]
Thanks! Helped to feel the intuitive idea behind it!. :) 
Now, I want to include open mvg library in my program. Like I am doing an experiment to run SFM over some images and I want to apply geometric filter and use its function from openMVG. How to go about it?
