### ISSUE TITLE
CVPR 2015 tutorial on OpenMVG

### ISSUE THREAD

**Issue by amiltonwong** [openMVG/openMVG#318]
It'll be soon to have CVPR 2015 tutorial on Open Source Structure-from-Motion (including OpenMVG) presented.
http://www.kitware.com/cvpr2015-tutorial.html

And @pmoulon is one of the speaker. Looking forward to your great tutorial :)

**Comment by pmoulon** [comment]
Looking forward to see you and discuss.
Thanks for the notification.
Perhaps you will be the winner of the Bepop drone ;), let the random choice decide ;)

**Comment by pmoulon** [comment]
Slides are available there http://midas3.kitware.com/midas/community/46

**Comment by amiltonwong** [comment]
@pmoulon . Thank you so much.
