### ISSUE TITLE
Problem running cmvs / pmvs2

### ISSUE THREAD

**Issue by nyholku** [openMVG/openMVG#319]
I've read all I can find but I'm still confused.

What is the relationship between all CMVS and PMSVS2?

Should I try to run both?

And how?

A complete run example would be great help for everyone starting out with openMVG/SfM/CMVS/PMSV2...

The usage is not clear to me, I run:

```
./openMVG_main_openMVG2PMVS -i sfm_data.json testdir
```

and this produces:

```
ls testdir/PMVS/
bundle.rd.out		models			vis.dat
centers-0000.ply	pmvs_options.txt	visualize
centers-all.ply		ske.dat
list.txt		txt
```

I then try to run:

```
./pmvs2  testdir/PMVS/ pmvs_options.txt
```

and this produces:

```

./pmvs2
/Volumes/MountainLion/Users/nyholku/testdir/PMVS
pmvs_options.txt
Unrecognizable option: 
```

So obviously I'm doing something wrong but can't figure it out...

**Comment by pmoulon** [comment]
Please consider to run
```
./pmvs2  testdir/PMVS/ pmvs_options.txt
```

**Comment by nyholku** [comment]
Ah! So trivial, now it works, thanks!

**Comment by tzumby** [comment]
@nyholku how did you make this work, I'm running into the same problem

**Comment by nyholku** [comment]
Sorry I don't recall.

**Comment by pmoulon** [comment]
I think it's path problem, you have to use the '/' at the end of the path
```
./pmvs2 /Volumes/MountainLion/Users/nyholku/testdir/PMVS/ pmvs_options.txt
```
As it is stated in the doc https://openmvg.readthedocs.org/en/latest/software/MVS/PMVS/

**Comment by tzumby** [comment]
This was trivial indeed :). Thanks a lot!
