### ISSUE TITLE
main_GlobalSfM assumes matches.e.txt

### ISSUE THREAD

**Issue by Meekohi** [openMVG/openMVG#321]
Is there a reason `main_GlobalSfM.cpp:113` assumes the matches file is `matches.e.txt` as opposed to `matches.f.txt`?

**Comment by pmoulon** [comment]
F means -> fundamental matrix filtered matches
E means -> essential matrix filtered matches
H means -> homography matrix filtered matches

Global SfM use the essential matrix filter matches since it need relative motion.
