### ISSUE TITLE
Sfm_data.json Intrinsic values disto_k3

### ISSUE THREAD

**Issue by priyanshuchandra** [openMVG/openMVG#323]
In SfM_data.json file, What exactly does the variable 'disto_k3' under the category 'Intrinsics' contain? Through what parameter of executable file "openMVG_main_SfMInit_ImageListing" does it take those values? 
And while running the executable file "openMVG_main_SfMInit_ImageListing"  what do we have to pass with parameter '-k'?

**Comment by pmoulon** [comment]
Please use the mailing list for generic question => openmvg-team[AT]googlegroups.com
Issue is for bug related problems.
disto_k3 contains the radial distortion coefficients. https://github.com/openMVG/openMVG/blob/master/src/openMVG/cameras/Camera_Pinhole_Radial.hpp#L157
By default these value are init by zeros, and will be refined at Bundle Adjustment.

As explain in the doc openMVG_main_SfMInit_ImageListing http://openmvg.readthedocs.org/en/latest/software/SfM/SfMInit_ImageListing/
-k is an option to specify the entire K calibration matrix if it is known.
By default EXIF metadata are read and use to setup an initial focal lenght.
