### ISSUE TITLE
SfM format from 0.7 to 0.8.1

### ISSUE THREAD

**Issue by rdiazgar** [openMVG/openMVG#326]
Hi,

I recently updated the code from 0.7 to 0.8.1 and realized some changes have been made to the way results are stored.

Is there a way to reuse the legacy format with the new version? For example, can I convert a model already built with version 0.7 into a 0.8.1 SfM_data format?

Thanks

Raúl

**Comment by pmoulon** [comment]
Hi @rdiazgar 
For the moment there is no SfM_Ouput converter, but only a lists.txt to a sfm_data.json converter (with views and intrinsics defined).
That means that the matches and features/descriptor files remains valid; so you can re-launch the Incremental of Global SfM on it.
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ConvertList.cpp#L38

Hoping it helps a bit.

**Comment by rdiazgar** [comment]
Hi,
Thanks for your reply.
