### ISSUE TITLE
FindImagesWithPossibleResection - 0-track candidates?

### ISSUE THREAD

**Issue by rdiazgar** [openMVG/openMVG#327]
Hi,

I just realized of a strange behavior in the incremental SfM pipeline. When looping for new candidate images to resection, if an image shares 0 tracks with the current model, it seems that it is still added in the vec_putative vector. Hence, even if there are no good candidate images to add, vec_putative vector is never empty (it's all zeros instead) and the best candidate has 0 matches, so it tries to resection all the remaining images regardless of having 0 tracks. That makes the incremental pipeline to call Bundle adjustment many times (as many times as images that can't be resectioned) for nothing.

A simple fix should be:

```
if (vec_trackIdForResection.size() > 0)
    vec_putative.push_back( make_pair(viewId, vec_trackIdForResection.size()));
```

Regards
Raul

**Comment by pmoulon** [comment]
Thanks @rdiazgar 
You're right, if a camera do not share any features with the existing structure we do not need to add it.
But if the camera have no connection to the 3D structure, the resection step will return false and the variable that tell if a BA have to run or not will be false:
- bImageAdded will be false https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L115 and so not Bundle Adjustment will run.

Can you check if when images with 0 tracks are added, this bImageAdded variable remains false?

**Comment by rdiazgar** [comment]
Here's a copy of the log trace that might explain this behaviour:

```
Looking for new images to resection : // own debug comment
Adding new images to resection :3645(0),  // own debug comment

-------------------------------
-- Resection of camera index: 3645
-------------------------------


 Tracks in: 3645
        2239
 #Reconstructed tracks:
        130057
 #Tracks Valid for resection:
        0

---------------------------------
--      BUNDLE ADJUSTMENT      --
---------------------------------
#Cams: 1512
#Intrinsics: 1
#Points3D: 130057
#measurements: 412836


... rest of BA trace... cost remains unchanged


Looking for new images to resection : // own debug comment
Adding new images to resection :3577(0),  // own debug comment

-------------------------------
-- Resection of camera index: 3577
-------------------------------


 Tracks in: 3577
        1454
 #Reconstructed tracks:
        130057
 #Tracks Valid for resection:
        0

---------------------------------
--      BUNDLE ADJUSTMENT      --
---------------------------------
#Cams: 1512
#Intrinsics: 1
#Points3D: 130057
#measurements: 412836

... rest of BA trace... cost remains unchanged


```

The first two comments were added by me for debugging purposes in FindImagesWithPossibleResection. In the example, image 3645 (with 0 tracks) is the only image in the next batch to be resectioned. After the resectioning is done, Bundle adjustment is called again with no improvement at all since nothing has changed. Then, image 3577 is selected as the only image in the next batch with similar results. This is done until all thsese 'hopeless' images have been tried to be resectioned.

**Comment by pmoulon** [comment]
Thanks for the deep looking.
I will try to investigate to see what is happening.

**Comment by pmoulon** [comment]
Hi @rdiazgar 
I have artificially created the problem by clear the number of track once a given number of camera have already been added, and in my case the BA is not launch.

Can you please share to me the complete SfM Log trace (from the initial pair, to the end of the process) by using a gist?

Please be sure you are using the last master or develop branch.

**Comment by rdiazgar** [comment]
Hi,

After updating to 0.8.1, I ran a small test and seemed to be working ok. Perhaps I had some issue with 0.7. 

In any case, when preparing the next batch of images, it makes sense not to add images with 0 tracks in the first place, right?

Regards,
Raúl

**Comment by pmoulon** [comment]
OpenMVG v1.0 will have a better Incremental SfM pipeline that will handle the "0tracks views" in a better way.
