### ISSUE TITLE
Minor problem in exporting to PMVS

### ISSUE THREAD

**Issue by rhiestan** [openMVG/openMVG#332]
I believe in this line is a small error:
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2PMVS.cpp#L289

iterObs->first is the view_id. However, if not all views have poses and intrinsics, they will not be exported to list.txt, meaning the index is incorrect. I think a similar technique like in other places is required to re-index the views (using map_cameratoIndex for example).

**Comment by pmoulon** [comment]
You are right.
I will fix that. And I must fix it for openMVG2CMPMVS too

**Comment by rhiestan** [comment]
Are you sure? I think openMVG2CMPMVS is correct.

**Comment by pmoulon** [comment]
I mean that I must use the same method to export the images.
Use a map<IndexT,IndexT> to map the Ids to the right value.

**Comment by rhiestan** [comment]
I believe this is not necessary. Both loops in main_openMVG2CMPMVS.cpp skip over views without poses and intrinsics, and the name increment is done correctly.

**Comment by pmoulon** [comment]
This must fix this minor problems. (develop branch)
Perhaps this minor problem can explain some strange clustering results in CMVS... (the only one software that use the bundler exported file).
Please close the issue if the code looks good to you.

**Comment by rhiestan** [comment]
I am not 100% sure this line is correct:
https://github.com/openMVG/openMVG/commit/b0324a2373f734395ce2b564f376c06623a66dbd#diff-1f8852739e4e275aeafb51b51b12f2d7R293

This line only works if all observations are referenced only from views with valid poses (i.e. is in map_viewIdToContiguous). If this is the case, the line is correct. Otherwise, a check would be necessary.
In my opinion the changes in the other files and methods do no harm, but also the old code worked fine.

Thanks for the quick fix!

**Comment by pmoulon** [comment]
Structure listed view ids are supposed to be all valid.

**Comment by rhiestan** [comment]
OK, thanks!
