### ISSUE TITLE
openMVG_main_GlobalSfM:  double free or corruption (fasttop)

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#340]
When running 'openMVG_main_GlobalSfM' from the included Python script and a relatively large input set (~6,000 images), I receive the following error at ~40% completion of relative rotation computation:

Error in `/home/insight/openMVG_Build/software/SfM/openMVG_main_GlobalSfM': double free or corruption (fasttop): 0x00007f018c01a9a0 ***

Compute_Relative_Rotations
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*********************

As such, the subsequent steps in the global SfM pipeline (colorize structure and structure from known poses steps) naturally fail.

Despite the error suggesting either an out of memory condition or a memory leak, I seem to have plenty of RAM free (~21GB used of 138GB).

Is this known behavior?  What steps can you recommend -- is it safe to restart the global process at the relative rotation stage or is the /matches directory now corrupted by the program exit?

**Comment by pmoulon** [comment]
duplicate=> see #341
