### ISSUE TITLE
openMVG_main_GlobalSfM:  double free or corruption (fasttop)

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#341]
When running 'openMVG_main_GlobalSfM' from the included Python script and a relatively large input set (~6,000 images), I receive the following error at ~40% completion of relative rotation computation:

Error in `/home/insight/openMVG_Build/software/SfM/openMVG_main_GlobalSfM': double free or corruption (fasttop): 0x00007f018c01a9a0 ***

Compute_Relative_Rotations
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*********************

As such, the subsequent steps in the global SfM pipeline (colorize tructure and structure from known poses steps) fails.

Despite the error suggesting either an out of memory condition or a memory leak, I have plenty of RAM free (~4.3GB used of 138GB).

Is this known behavior?  What steps can you recommend?

I have re-run main_GlobalSfM several times -- the program exits each time with a different % completed, ranging from 8%-40%.  Peak RAM is ~4.3GB of 128GB on the system, disk space is < 10%.

**Comment by pmoulon** [comment]
I @KevinCain 
Thanks for the feedback, I think this error is due to the multithread context.
Can you update the last develop branch version and run it again?
Please, tell me if the commit solve the problem with a message and closing the issue.

**Comment by KevinCain** [comment]
I switched to the 'develop' branch, pulled all commits to date via git, and recompiled.

'main_GlobalSfM' now proceeds past the 'Computer Relative Rotations' step where is consistently crashed when sourcing branch 'master'.

**Comment by pmoulon** [comment]
Thanks for the feedback and happy to see that the problem seems to be fixed!
