### ISSUE TITLE
CMAKE_MODULE_PATH isn't backed up in OpenMVGConfig.cmake

### ISSUE THREAD

**Issue by caymard** [openMVG/openMVG#345]
When using OpenMVG as a library we were unable to find any other libraries in CMake after finding OpenMVG. The only fix we found was to find OpenMVG after finding other libraries. I think I found the issue : this [line](https://github.com/openMVG/openMVG/blob/develop/src/cmakeFindModules/OpenMVGConfig.cmake.in#L39) of OpenMVGConfig.cmake should be at the end, to back up `CMAKE_MODULE_PATH` to its initial value.

**Comment by pmoulon** [comment]
Thanks @caymard 
Can you test it again with copy this line to 109 ?
SET(CALLERS_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})

**Comment by caymard** [comment]
Maybe `SET(CMAKE_MODULE_PATH ${CALLERS_CMAKE_MODULE_PATH})` you would say ?

I just moved line 39 at the end and it works.

**Comment by pmoulon** [comment]
@caymard The issue should now be fixed in the develop branch.
Can you check and close the issue?
