### ISSUE TITLE
CMake errors on Mac: "get_filename_component called with incorrect number of arguments"

### ISSUE THREAD

**Issue by maak** [openMVG/openMVG#348]
I downloaded and attempted to run cmake on the openMVG library, as directed in the BUILD file. I get a tone of errors similar to the following:

Performing Test OpenMP_FLAG_DETECTED
CMake Error at /Applications/CMake 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)

CMake version: 2.8-10
OS X version: 10.10.4

Has anybody else experienced this problem?

**Comment by pmoulon** [comment]
Have your tried to update your CMake?

@Meekohi , @rhiestan can perhaps also suggest some tips.

**Comment by Meekohi** [comment]
Hey @maak - I just downloaded the current master branch and compiled it on OSX with no issues.

```
 $ git clone --recursive https://github.com/openMVG/openMVG.git
 $ mkdir openMVG_Build
 $ cd openMVG_Build
 $ cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" . ../openMVG/src/
 $ xcodebuild -configuration Release
```

CMake 3.3.0
OSX 10.10.4

0. As @pmoulon said, I am guessing your version of CMake is too old. Get a 3.x version and try again. (maybe we should add Cmake 3.x as a requirement in the BUILD document)
1. Make sure you have all the dependencies installed.
2. The OpenMP warnings are normal -- Apple switched to the llvm compiler which does not support OpenMP (Actually I hear they are now supported again! Unfortunately I don't think that version is widely deployed yet)

**Comment by maak** [comment]
Thanks for the quick feedback guys. You are correct, the problem was associated with my cmake version.
