### ISSUE TITLE
Failed tests when configuring cmake

### ISSUE THREAD

**Issue by maak** [openMVG/openMVG#349]
I get a bunch of failed tests, mostly relating to OpenMP:
```
Try OpenMP CXX flag = [+Oopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-qsmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-mp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
```

A warning:
```
CERES FOUND
CMake Warning (dev) at third_party/lemon/CMakeLists.txt:4 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    LEMON_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.
```
And this (might be nothing, but it's red):
-- Did not find MOSEK header
-- Did not find MOSEK library

Has anyone else encountered this issue? I haven't explicitly installed OpenMP on my system.

OS: OS-X 10.10.4

**Comment by pmoulon** [comment]
Don't worry, you will be able to compile the library.
- OpenMP is not detected since it is not included in your clang.
The warning is related to cmake and it's not an error.
Mosek is an optional library that is not required.

You can do safely:
```
 $ xcodebuild -configuration Release
```

**Comment by pmoulon** [comment]
Do you have build correctly the library?

**Comment by maak** [comment]
Yes thank you for the guidance. I have successfully built the library. I left the issue open in case somebody fixes the tests one day. Feel free to close it if that is not something required by the project.

**Comment by pmoulon** [comment]
You must be aware that this message
```
ry OpenMP CXX flag = [+Oopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-qsmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-mp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
```
is displayed by CMAKE and not by OpenMVG ;-)

Since the other warning will be fixed soon I close the issue.
