### ISSUE TITLE
[converter] OpenMVG2MVE

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#355]
- [x] Make the exporter #351
- [x] install the binary at the right place
- [x] view thumbnails generation
  - must preserve the initial aspect ratio see https://github.com/simonfuhrmann/mve/blob/e3db7bc60ce93fe51702ba77ef480e151f927c23/libs/mve/image_tools.h#L1645

@simonfuhrmann => Does it is compulsory to have square 50x50 pixels thumbnail images?
I mean do we can just export the initial image reduced by a constant factor...

**Comment by simonfuhrmann** [comment]
Thumbnails are not necessary, however, strongly recommended as it makes browsing scenes in UMVE much more comfortable if you're looking for a specific view. 50x50 is more or less arbitrary, any other aspect ratio should be fine, too.

Here is an example how MVE creates square thumbnails: https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_tools.h#L1649

**Comment by pmoulon** [comment]
Thanks @simonfuhrmann I will try to handle that thumbnail generation next week.

**Comment by pmoulon** [comment]
- [ ] Fix export of invalid view (view without valid pose & intrinsic data)

**Comment by fabiencastan** [comment]
I don't find the commit associated to the latest exporter fix. Could you give me the link?

**Comment by pmoulon** [comment]
@fabiencastan Here the link

**Comment by fabiencastan** [comment]
Thanks!

**Comment by pmoulon** [comment]
Still a minor issue with view with missing pose. https://github.com/openMVG/openMVG/pull/402
