### ISSUE TITLE
[stl] Add a dynamic_bitset class

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#356]
Allow user to manipulate bitset where size is not known at compile time:
 - Since std::bitset<N> allows only to manipulate compile time known bitset a solution have to be added.
 - Add a very simple dynamic_bitset class to openMVG/stl.
- stl::dynamic_bitset will be modeled from std::bitset<N> and boost::bitset<,>

This addition enable to compute hamming distance between execution time size configured bitset.

**Comment by fabiencastan** [comment]
Like the header only: http://www.boost.org/doc/libs/1_58_0/libs/dynamic_bitset/dynamic_bitset.html

**Comment by pmoulon** [comment]
I know the boost one, and the implementation will rely on a mix between the one from boost and the one from the STL.
