### ISSUE TITLE
cereal build errors on HPC system using gcc 4.9.0

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#362]
When building the 'develop' branch from the latest git source using cmake 2.8 gcc 4.9.0, make reports the following errors from the compiler at 78% completion:

```
[ 78%] Built target ceres
[ 78%] Built target flann_cpp_s
[ 78%] Built target easyexif
[ 78%] Building CXX object openMVG/features/CMakeFiles/openMVG_features.dir/akaze/AKAZE.cpp.o
In file included from /usr/include/c++/4.3/type_traits:40,
                 from /home/cain/openMVG/src/dependencies/cereal/include/cereal/cereal.hpp:32,
                 from /home/cain/openMVG/src/openMVG/features/akaze/AKAZE.hpp:42,
                 from /home/cain/openMVG/src/openMVG/features/akaze/AKAZE.cpp:7:
/usr/include/c++/4.3/c++0x_warning.h:36:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
In file included from /home/cain/openMVG/src/dependencies/cereal/include/cereal/cereal.hpp:43,
                 from /home/cain/openMVG/src/openMVG/features/akaze/AKAZE.hpp:42,
                 from /home/cain/openMVG/src/openMVG/features/akaze/AKAZE.cpp:7:
/home/cain/openMVG/src/dependencies/cereal/include/cereal/details/traits.hpp:40:21: error: typeindex: No such file or directory
```
I've successfully compiled OpenMVG on several systems but the system in question here is a multi-user HPC cluster:  http://mesu-smn.dsi.upmc.fr/mediawiki/index.php5/Main_Page

**Comment by KevinCain** [comment]
From the above listing, I may be able to compile by manually inserting the -std=c++0x or -std=gnu++0x compiler options in each call.  However, since cmake generates cascading outputs for OpenMVG, the process of editing them manually would be tedious and inserting them globally via cmake may break the build for others if they pull my edits.

**Comment by pmoulon** [comment]
Hi @KevinCain ,
This is strange since compiler sypport for C++11 is checked with this cmake file https://github.com/openMVG/openMVG/blob/master/src/cmakeFindModules/CXX11.cmake

Can you check that on your HPC machine that C++11 is well detected (on the following line) ?
 - https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L68

**Comment by KevinCain** [comment]
Thanks @pmoulon, I see the cmake does *not* detect gcc 4.9.x on this system; my cmake output includes:

```
-- Checking for C++11 compiler
-- Checking for C++11 compiler - unavailable
```

I can confirm that the gcc module is loaded and that `which gcc` yields `/opt/dev/gcc/gcc-4.9.0/bin/gcc`; I further note this line in '/openMVG_build/CMakeFiles/CMakeCCompiler.cmake':

`SET(CMAKE_C_COMPILER "/usr/bin/gcc")`

How should I direct cmake to avoid the above mismatch?

**Comment by pmoulon** [comment]
I think you have many GCC setup on the machine and an old one is used by default.
```
export CC=path_of_gcc/gcc-version
export CXX=path_of_g++/g++-version
cmake ....
make
```
Seen here:
http://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake

**Comment by KevinCain** [comment]
Thanks, @pmoulon, for your characteristically helpful response -- even for a problem that does not relate to OpenMVG code, but simply my system environment.

I was able to successfully compile OpenMVG by explicitly passing compiler paths to cmake by exporting the CC and CXX variables, as you suggested.  However, I also needed to remove the git build path, so that cmake could regenerate all its output files from scratch.  For completeness, here was my attempt to apply update compiler paths from my existing cloned build folder:

```
cain@mesu1:~/openMVG_build> which gcc
/opt/dev/gcc/gcc-4.9.0/bin/gcc
cain@mesu1:~/openMVG_build> which g++
/opt/dev/gcc/gcc-4.9.0/bin/g++
cain@mesu1:~/openMVG_build> export CC=/opt/dev/gcc/gcc-4.9.0/bin/gcc
cain@mesu1:~/openMVG_build> export CXX=/opt/dev/gcc/gcc-4.9.0/bin/g++
cain@mesu1:~/openMVG_build> cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
-- Optimizing for the host architecture using -march=native
-- Checking for C++11 compiler
-- Checking for C++11 compiler - unavailable
```

Note above:  *Checking for C++11 compiler - unavailable*

Starting fresh by removing the source and build folders, @pmoulon's suggestion worked, as follows:

```
rm -r openMVG
rm -r openMVG_Build
module load cmake/2.8
module load gcc
which gcc
/opt/dev/gcc/gcc-4.9.0/bin/gcc
which g++
/opt/dev/gcc/gcc-4.9.0/bin/g++
export CC=/opt/dev/gcc/gcc-4.9.0/bin/gcc
export CXX=/opt/dev/gcc/gcc-4.9.0/bin/g++
git clone --recursive https://github.com/openMVG/openMVG.git
git checkout develop
git pull
mkdir openMVG_Build
cd openMVG_Build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
make
```

Thanks once again.

**Comment by KevinCain** [comment]
@pmoulon resolved my issue, which did not relate to OpenMVG but the environment I am installing into.

**Comment by pmoulon** [comment]
Thanks for the feedback ;-)
