### ISSUE TITLE
Building Error vlsfit.lib not found

### ISSUE THREAD

**Issue by msalman88** [openMVG/openMVG#366]
Hello

I was trying to build openMVG libraries for windows. 

I followed the same steps as mentioned in 
https://github.com/openMVG/openMVG/blob/master/BUILD

I am using microsoft visual studio 2015 from microsoft community. But I am still the  following errors.

![image](https://cloud.githubusercontent.com/assets/13850963/9329607/43121fec-45b3-11e5-8c93-16c6262547b5.png)

Thanks

**Comment by pmoulon** [comment]
On my side it compile right on visual studio 2013.

I think the problem comes from here:
https://github.com/openMVG/openMVG/blob/82ecbc44fd638956ca98c5621b35185c75db4dd9/src/nonFree/sift/vl/host.h#L323
Can you try to comment the depicted line in host.h to see if it solves your problem?

**Comment by msalman88** [comment]
Hi pmoulon 

I tried as you suggested but  now I am getting these errors..

![image](https://cloud.githubusercontent.com/assets/13850963/9330094/30be5370-45b7-11e5-95d2-dbaceffd1c6c.png)

**Comment by pmoulon** [comment]
Seems OsiCuts::const_iterator does not define a required operator (--).

**Comment by msalman88** [comment]
So what should be done to resolve this issue??

**Comment by pmoulon** [comment]
Implement the missing operator-- in the class OsiCuts::const_iterator

**Comment by msalman88** [comment]
Ok. I left the body of the operator -- blank and compiled it again. Now I have another issue:

Link 2001 and 2019 errors.
![image](https://cloud.githubusercontent.com/assets/13850963/9331316/07cce21c-45bf-11e5-90a1-eb264ebbfe60.png)




![image](https://cloud.githubusercontent.com/assets/13850963/9331342/3223b2e8-45bf-11e5-9a10-2934274cb688.png)

**Comment by pmoulon** [comment]
I will try to setup visual2015 on a computer and see if I have the same errors.

**Comment by pmoulon** [comment]
@msalman88 
Found a fix for your issue:
OsiCuts.hpp, line 77 change
```
typedef std::bidirectional_iterator_tag iterator_category;
```
to
```
typedef std::forward_iterator_tag iterator_category;
```

for host.h from vlfeat the fix is:
```
#if _MSC_VER < 1900
#define snprintf _snprintf
#endif
```

Curiously the compilation bug only occur in 32 bits mode and not in 64 bits!

**Comment by pmoulon** [comment]
Are you now able to build?

**Comment by msalman88** [comment]
Yes, I am trying now.

I started from begining and followed the steps you proposed in last message.

thanks

**Comment by msalman88** [comment]
I change the two files host.h and osicuts.hpp as you said.

After compiling the solution again, I am again getting errors as the fist image of this post. 

Any comments??

**Comment by pmoulon** [comment]
I have now pushed all the necessary fix.
Can you start from scratch just to be sure (the following line will checkout develop branch and update the submodule directly):
$ git clone --recursive https://github.com/openMVG/openMVG.git -b develop
cmake
build

Thanks.

**Comment by msalman88** [comment]
Thank you very much. It is working now.

**Comment by pmoulon** [comment]
I close the issue.
Thanks for your time & feedback.
