### ISSUE TITLE
What is the best way to add run-time libraries for OpenMVG?

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#368]
I’m using `LD_LIBRARY_PATH` to help `OpenMVG` find the right run-time libraries on a shared used HPC system.  My approach works, but I gather that the right way to supply additional libraries to the linker is via `rpath`.  However, I don’t want to add my arbitrary linker flags and system paths to `OpenMVG` `cmake` files that could break builds on other systems.

I’m open to suggestions for the best way to add run-time libraries for `OpenMVG`.

Here’s some explanation of how, and why, I’m using `LD_LIBRARY_PATH`:

To compile `OpenMVG`, I am using a version of `gcc` (4.9.0) that is more recent than is the default OS version on the HPC system ‘mesu’ (`gcc` 4.3.4?).  The `$LD_LIBRARY_PATH`, consulted on execution for any additional directories in which to search for dynamically linkable libraries, normally includes `/usr/lib64` on the HPC system I’m using, so it does not match the libraries required for the binaries I’ve compiled with `GCC-4.9.0` on mesu.

Here’s a specific example:  source code compiled and linked with `-fopenmp` will, at run-time, load the first `libgomp` it finds in the `LD_LIBRARY_PATH`.  In our case, the default mesu path (`/usr/lib64`) does not contain the dynamic libraries we need when using `GCC-4.9.0`.  As a result, running `OpenMPV` binaries gives errors, including this one:
```
/home/cain/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing:
/usr/lib64/libgomp.so.1: version `GOMP_4.0' not found
(required by /home/cain/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing)
```

While `/usr/lib64/libgomp.so.1` does exist, it doesn’t match `gcc 4.9.0`.  The matching libs are instead here:  `/opt/dev/gcc/gcc-4.9.0/lib64`.  I added these libraries from the most recent mesu gcc module:
`export LD_LIBRARY_PATH=/opt/dev/gcc/gcc-4.9.0/lib64:$LD_LIBRARY_PATH`

To make the above  `LD_LIBRARY_PATH` persistent for bash, I added the above export here:  `~/.bashrc`, although adding this export instruction in the the login terminal config file `~/.profile` would likely also work.

The above settings work -- I can run the OpenMVG binaries I’ve built (here:
`/home/cain/openMVG_Build/Linux-x86_64-RELEASE`) or use `ldd` to list the library dependencies for a given binary, e.g.:
```
cain@mesu0:~/openMVG_Build/software/SfM> ldd /home/cain/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_IncrementalSfM
        linux-vdso.so.1 =>  (0x00007ffff7ffe000)
        libpng12.so.0 => /usr/lib64/libpng12.so.0 (0x00007ffff7d96000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ffff7b7f000)
        libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007ffff795b000)
        libtiff.so.3 => /usr/lib64/libtiff.so.3 (0x00007ffff76ff000)
        liblapack.so.3 => /usr/lib64/liblapack.so.3 (0x00007ffff6e24000)
        libblas.so.3 => /usr/lib64/libblas.so.3 (0x00007ffff6bcb000)
        libgomp.so.1 => /opt/dev/gcc/gcc-4.9.0/lib64/libgomp.so.1 (0x00007ffff69b4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff6796000)
        libstdc++.so.6 => /opt/dev/gcc/gcc-4.9.0/lib64/libstdc++.so.6 (0x00007ffff647f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff6206000)
        libgcc_s.so.1 => /opt/dev/gcc/gcc-4.9.0/lib64/libgcc_s.so.1 (0x00007ffff5fee000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff5c72000)
        libgfortran.so.3 => /opt/dev/gcc/gcc-4.9.0/lib64/libgfortran.so.3 (0x00007ffff5952000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ffff5748000)
        /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
        libquadmath.so.0 => /opt/dev/gcc/gcc-4.9.0/lib64/libquadmath.so.0 (0x00007ffff550a000)
```

**Comment by pmoulon** [comment]
I think you have done the right job.
Perhaps @Meekohi or @cbalint13 will have some tips regarding your question.

**Comment by Meekohi** [comment]
Ha I'm definitely not an expert, but in terms of picking the correct library at _run-time_, I agree `LD_LIBRARY_PATH` is the only strategy I know of. The only thing I might suggest is that instead of setting the environment variable for your entire shell using `~/.bashrc` (prone to messing something up later on), you could just run commands with this prefixed, such as:

`LD_LIBRARY_PATH=/opt/dev/gcc/gcc-4.9.0/lib64:$LD_LIBRARY_PATH ./openMVG_main_ComputeMatches`

Which should modify the environment as needed, but just for the one command.

**Comment by KevinCain** [comment]
Thanks @Meekohi and @pmoulon for your review, and for the suggestion apply `LD_LIBRARY_PATH` locally rather than globally via `~/.bashrc`.  I agree that's safer.
