### ISSUE TITLE
Compilation error on Ubuntu14.04 virtualmachine

### ISSUE THREAD

**Issue by deepakdnathgit** [openMVG/openMVG#373]
Hi,

Need your help to solve the compilation problem:

fearless@fearless-VirtualBox:~/Development/external/openMVG/build$ sudo make install
[  3%] Built target lib_Osi
[ 15%] Built target lib_CoinUtils
[ 26%] Built target lib_clp
[ 26%] Built target lib_OsiClpSolver
[ 26%] Built target stlplus
[ 27%] Built target lemon
[ 37%] Built target jpeg
[ 46%] Built target tiff
[ 46%] Built target main_svgSample
[ 57%] Built target cxsparse
[ 83%] Built target ceres
[ 83%] Built target flann_cpp_s
[ 83%] Built target easyexif
[ 84%] Built target openMVG_features
[ 84%] Built target openMVG_numeric
[ 84%] Built target openMVG_image
[ 84%] Built target openMVG_lInftyComputerVision
[ 84%] Built target openMVG_kvld
[ 84%] Built target openMVG_matching_image_collection
[ 87%] Built target openMVG_multiview
[ 87%] Built target openMVG_multiview_test_data
[ 87%] Built target openMVG_system
[ 89%] Built target openMVG_sfm
[ 91%] Built target vlsift
Linking CXX executable openMVG_sample_siftPutative
/usr/bin/ld: cannot find -lzlib
collect2: error: ld returned 1 exit status
make[2]: *** [openMVG_Samples/siftPutativeMatches/openMVG_sample_siftPutative] Error 1
make[1]: *** [openMVG_Samples/siftPutativeMatches/CMakeFiles/openMVG_sample_siftPutative.dir/all] Error 2
make: *** [all] Error 2

However, zlib libraries are already installed:

zlib1g/trusty,now 1:1.2.8.dfsg-1ubuntu1 amd64 [installed]
zlib1g-dev/trusty,now 1:1.2.8.dfsg-1ubuntu1 amd64 [installed]
zlibc/trusty,now 0.9k-4.1 amd64 [installed]

**Comment by deepakdnathgit** [comment]
However that zlib libraries are installed:
-------------------
zlib1g/trusty,now 1:1.2.8.dfsg-1ubuntu1 amd64 [installed]
zlib1g-dev/trusty,now 1:1.2.8.dfsg-1ubuntu1 amd64 [installed]
zlibc/trusty,now 0.9k-4.1 amd64 [installed]

**Comment by deepakdnathgit** [comment]
Solved....

I think I had missing dependencies.
When I installed libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev
Things were okay. 

I have successfully compile it and examples are tested.

Thanks.

**Comment by pmoulon** [comment]
Glad to see that you find the information into the BUILD file.
I close the issue and wish you nice OpenMVG experiments.

**Comment by max0x** [comment]
You can also solve this problem by linking with -lz, instead of -lzlib. zlib is provided as libz.so in the Ubuntu distribution.
