### ISSUE TITLE
Trying to run sample pipeline of SfM

### ISSUE THREAD

**Issue by msalman88** [openMVG/openMVG#377]
Hello

I am try to run  pipeline of SfM.  First two steps are fine. There is a problem with 3rd step i.e.  openMVG_main_ComputeMatches

When I run this command, I am getting following error
![image](https://cloud.githubusercontent.com/assets/13850963/9465435/d2c12b50-4b2c-11e5-808d-2b0c183b3e28.png)

can you resolve this issue?

Thanks in advance.

**Comment by pmoulon** [comment]
Neato is a software from graphiz. http://www.graphviz.org/
It is used to show image relationship as graph images stored in the SVG file format.
It's optional, you can continue without it.

**Comment by msalman88** [comment]
Hi, I continued  to the next step but I got this.

![image](https://cloud.githubusercontent.com/assets/13850963/9465794/f99b8b3c-4b2f-11e5-8a08-7b9778476149.png)

At the end I nead a point cloud file.

**Comment by pmoulon** [comment]
It's because your image graph is empty
=> Connected component : 0 means that there is not essential matrices that have been validated so there is no point relationship between your images.
I recommend you to:
1. test this dataset:
https://github.com/openMVG/ImageDataset_SceauxCastle
2. move to your own in a second time.

**Comment by msalman88** [comment]
Hi 

I am using same database with 11 images. 

when I run first command I have to move the k.txt and readme.txt out of  folder as these were giving errors.

**Comment by pmoulon** [comment]
don't worry about those files. the message just says that .txt files cannot be opened as images and so they will no be used for the 3D reconstruction.

**Comment by msalman88** [comment]
my .ply file look like this if i open in text editor
![image](https://cloud.githubusercontent.com/assets/13850963/9466260/de40902c-4b33-11e5-9c5f-151cfb63db9e.png)

I could not see any file for point colud...

I am using following steps (Using the GlobalSfM pipeline)
https://events.ccc.de/camp/2015/wiki/Session:Photogrammetry

**Comment by pmoulon** [comment]
Can you run the python tutorial_demo in the Build/software/SfM
```
python tutorial_demo.py
```
If you have git in your path, it will download the Sceaux Castle image dataset and run the pipe.
Perhaps you have some old files that corrupt the computation when you have relaunch the process.

**Comment by pmoulon** [comment]
Any news?

**Comment by pmoulon** [comment]
Problem fixed with off discussion on the mailing-group
