### ISSUE TITLE
Trying to run sample pipeline of SfM for my database

### ISSUE THREAD

**Issue by msalman88** [openMVG/openMVG#381]
Hi
 I am trying to run SFM pipeline on my dataset , 

I got following error

![image](https://cloud.githubusercontent.com/assets/13850963/9578380/aadc4a40-4fe9-11e5-9a2b-6f8f4a4235a4.png)
 when I press   "ignore"
I got this. 

![image](https://cloud.githubusercontent.com/assets/13850963/9578389/cd48397c-4fe9-11e5-9cd1-3de60351c85b.png)

Is this a problem with visula studio or openMVG.?

If is it with opneMVG, how to resolve this.

I am running python pipleline as you suggested laste time. 

I cahnged input path to new database and also cahnaged following line

![image](https://cloud.githubusercontent.com/assets/13850963/9578439/5a1149a2-4fea-11e5-863d-a1bc8c374ccb.png)

Thanks in advance

**Comment by pmoulon** [comment]
Please use the following script: they have been written to be used without modification:
SfM_GlobalPipeline.py IMAGEDIR OUTPUTDIR
SfM_SequentialPipeline.py IMAGEDIR OUTPUTDIR

**Comment by msalman88** [comment]
The errors I get are:
<b>Warning & Error messages:
20150825_151726: Camera "SAMSUNG" model "SM-T530" doesn't exist in the database</b>

<b>There is no defined intrinsic data in order to compute an essential matrix for t
he initial pair.</b>

I could not find samsung galaxy tab in   sesor width text file.

**Comment by pmoulon** [comment]
It means that your camera model is not in the OpenMVG sensor width database.
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt

The sensor size is 2.8.

Please update the sensor width database by adding the following line:
Samsung;Samsung SM-T530;2.8

Or else, consider the focal to be approximately 1.2*max(w,h) and set it by using the -f X option on main_SfMInit_ImageListing.

**Comment by msalman88** [comment]
I run through command line and  after doing some computation it ask for x and y center. 

I was not getting this thing for sample images.
Thanks

**Comment by pmoulon** [comment]
There is no asking for x or y center. Can you make a screen copy of your window?

**Comment by msalman88** [comment]
Here is the snapshoot


![image](https://cloud.githubusercontent.com/assets/13850963/9601760/06dba54c-50a4-11e5-8328-a376ffc910bb.png)

**Comment by pmoulon** [comment]
Ok, I better understand.
Here you have to specify the first two images that will be used as a seed for the incremental reconstruction.
For example type 9 press ENTER then 10 press ENTER and the process will run.

The GlobalSfM pipeline have no seed, it uses all the images directly.

**Comment by msalman88** [comment]
ok let me try global 
thanks

**Comment by pmoulon** [comment]
Please try the sequential and the global so you will be able to compare.

**Comment by msalman88** [comment]
HI 

Thank you very much for your reply.
 
I want to know, can we controle the number of keypoint in point cloud. if so than how.


Thanks in advance

**Comment by pmoulon** [comment]
You control it the number of keypoints per image by using the preset parameter on main_ComputeMatches
-p NORMAL or -p HIGH or -p ULTRA

Having more or less keypoint per image will make the point cloud more or less dense.

**Comment by msalman88** [comment]
Hi

First of all, I would like to thank you for all your help.

I run the global pipeline with three different settingf i.e. normal, high and ultra and compare the results.

But I know I have new images with different sizes i.e. 640x480. I was try to run the same pipeline but it gives me following.

![image](https://cloud.githubusercontent.com/assets/13850963/9733143/50bc13d8-5629-11e5-846a-6939286d41a6.png)


How to resolve this issue.

Thank you very much in advance.

**Comment by pmoulon** [comment]
For all dataset two things to check:
-> Does the intrinsic analysis was good?
  -> Do you have set the intrinsic focal by hand, or does the automatic pipeline has setup it?
  -> check in the matches/sfm_data.json that there is valid intrinsic_id and that the filed intrinsics is not empty (bottom of the file)

-> Does there is matches between your input images of your dataset?
  -> go to the matches directory and open the file GeometricAdjacencyMatrix.svg => if there some blue dots it says that some image have some corresponding point that could be used for SfM
  -> if the file matches.e.txt is empty it shows that no robust essential matrix estimation has found a valid model

**Comment by msalman88** [comment]
Hi
I set the samsung model by hand as you suggested.

Now, we have original images and pipeline is working correlty over original images, But now we manually resized the images and ruuning again the same pipeline buy just changing the  image directly, but it is giving this error.

![image](https://cloud.githubusercontent.com/assets/13850963/9734842/9726e4ee-5636-11e5-934c-54f8db155873.png)

 Can you help me here?
Thanks

**Comment by pmoulon** [comment]
perhaps you caught a bug.
If the dataset is small please share it here
openmvg-team[AT]googlegroups.com
with your image & the matching dir
and tell me which git branch & commit id you are using.

**Comment by pmoulon** [comment]
Problem fixed with off discussion on the mailing-group
