### ISSUE TITLE
Setting photo/camera position?

### ISSUE THREAD

**Issue by srdjanarsic** [openMVG/openMVG#388]
Is it possible to specify camera position for each one photo. I have 36 images for full object loop. This is a one example: http://www.awssoft.com/3D-and-360-degree-product-view/example-3Dview.php

So, is it possible to set photos/camera position in order to get better 3D reconstruction, and what is a easiest way for this kind of sfm conversion.

Thanks,
Srdjan Arsic

**Comment by pmoulon** [comment]
It is possible to set known camera position in OpenMVG and use them.
OpenMVG use a SfM_Data container to store the data related to (camera parameters, camera poses, image description).

So the best for you can be to add a binary to OpenMVG that create an empty SfM_Data and fill it with 36 views, 36 poses and 36 cameras intrinsic (or one if camera intrinsic are shared).

Creating a view:
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L269
Creating an intrinsic:
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L260
Creating a pose:
sfm_data.poses[view->id_pose] = Pose3(R, -R.transpose()*t); // Pose3 => R|C

Then you save your SfM_Data to a json file.

The you compute the scene features/descriptor (mainComputeFeatures) & your generate the structure according the known camera poses:
see main_ComputeStructureFromKnownPoses

See here some tests made by another user:
https://github.com/openMVG/openMVG/issues/262#issuecomment-125641762

**Comment by srdjanarsic** [comment]
As, I am new to SFM and not familiar with openMVG, I will first go through docs and then try to make it using these guidelines.

Thank you very much

**Comment by pmoulon** [comment]
@srdjanarsic Can I close the issue?

**Comment by srdjanarsic** [comment]
Yes. As soon I finish the hardware, I will try to implement openMVG into my project. So we will be in touch.

**Comment by EthanGreen75** [comment]
Hello, Dr.pmoulon,
      If I only have the pitch, yaw, roll angle of each camera, can I still use this method to run SFM? I can't even get the accurate position of every camera.
     Can I transform the SFM result according to these angles?Like geo-referencing, I can get accurate gesture angles and inaccurate GPS data. 
     Thank u.

**Comment by pmoulon** [comment]
@EthanGreen75 
You can georegister according the angle deviation in each direction between the SfM reconstruction & your data.
Or you can compute a rigid similarity between your GPS position & camera poses.
