### ISSUE TITLE
Loading an existing recontruction

### ISSUE THREAD

**Issue by higerra** [openMVG/openMVG#391]
Hi, everyone
I'm trying to load an existing reconstruction result. I can see the camera information in sfm_data.json under reconstruction_global folder (for example, global sfm), but when I called openMVG::sfm::Load() function, it only read s_root_path. Also, when I tried to call openMVG::sfm::Save() to save the sfm_data.json just read, it was an empty json file, except s_root_path domain.

The code is fairly simple:
    openMVG::sfm::SfM_Data sfmdata;
    openMVG::sfm::ESfM_Data flags_part;
    string sfmdata_path = file_io.getDirectory()+"/output_sfm/reconstruction_global/robust.json";
    openMVG::sfm::Load(sfmdata, sfmdata_path, flags_part);
    openMVG::sfm::Save(sfmdata, file_io.getDirectory()+"/output_sfm/temp.ply", flags_part);

So did I miss something?
Thanks!

**Comment by pmoulon** [comment]
Hi, ESfM_Data is an enum.. with no default initialization
You can choose wich part you want to save/load.
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data_io.hpp#L17

Use ALL and it will load/save the contained information.
See here for an example where all the data are loaded.
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ConvertSfM_DataFormat.cpp#L52

**Comment by higerra** [comment]
OK, that works! Thanks a lot!
