### ISSUE TITLE
[SfM] Ground Control Points

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#398]
- [x] Consider GCP for Bundle Adjustment
  - fixed 3D points with a variable weight over the residual
- [x] Make the sfm_data PLY writer able to export GCP positions

**Comment by whuaegeanse** [comment]
This will be a good feature of OpenMVG. Is  this in developing?

**Comment by whuaegeanse** [comment]
There is a tool for geo registration in OpenMVG. What's the difference between them?
A new BA after geo registration?

**Comment by pmoulon** [comment]
There is already an interface:
https://openmvg.readthedocs.org/en/latest/software/ui/SfM/control_points_registration/GCP/

The GUI helps to put 3D points coordinates and view observation. For the moment the registration is  done only by least square. This new task will allow to perform BA with GCP constraints (So you're right, a new BA after geo registration that will use the GCP).

**Comment by pmoulon** [comment]
@whuaegeanse Now GCP can be used in a BA once the geo registration was done.
Default weight is set to 20
