### ISSUE TITLE
Segmentation Fault in SfMIncrementalEngine.cpp - [Win32]

### ISSUE THREAD

**Issue by donlk** [openMVG/openMVG#4]
Just pulled the latest code from the master branch, compiled it, and ran the following executables for the provided SceauxCastle imageset and its camera matrix:

openMVG_main_computeMatches <params>
openMVG_main_IncrementalSfM <params>
(repectively)

The first executable runs just fine, but the second one exits with a Segmentation fault.
Tracked down the error, and the problematic line:

SfMIncrementalEngine.cpp, line 448: _reconstructorData.map_Camera.insert(std::make_pair(J, SimpleCamera(_K, R2, t2)));

Tried the same procedure with the latest develper branch, and the problem persists, though it fails already when inserting the first index/camera pair to the map_Camera collection:

SfMIncrementalEngine.cpp, line 455: _reconstructorData.map_ACThreshold.insert(std::make_pair(I, errorMax));

Environment:
Ubuntu 13.04 x86
GNU GCC 4.7.3

**Comment by tntrung** [comment]
Hello, 

I have the problem when using openMVG_main_IncrementalSfM function as following:

====================================================================

Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track filtering : min occurence

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 818
 Images Id: 
0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
------------------
TrackLength, Occurrence
	2	529
	3	144
	4	72
	5	36
	6	22
	7	11
	8	3
	9	1

Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

----------------------------------------------------
SequentialSfMReconstructionEngine::ChooseInitialPair
----------------------------------------------------
 Pairs that have valid intrinsic and high support of points are displayed:
 Choose one pair manually by typing the two integer indexes
----------------------------------------------------

(21,27)		142 matches
(24,28)		119 matches
(23,29)		108 matches
(26,28)		95 matches
(24,26)		91 matches
(25,26)		89 matches
(0,30)		84 matches
(24,27)		80 matches
(13,27)		73 matches
(16,17)		73 matches

 type INITIAL pair ids: X enter Y enter
24
26

Putative starting pair is: (24,26)
Segmentation fault (core dumped)

==================================================

Do you have any solution for this?

Thanks.
Trung

**Comment by pmoulon** [comment]
Hi @tntrung 
It seems that the automatic choice of the initial pair have not found any valid pair.
Perhaps your images pair have a too tiny angle (too tiny baseline).

Have you tried the GlobalSfM pipeline on your dataset?
Have you tried to extract more feature per images (use HIGH present on main_ComputeFeatures)?

**Comment by tntrung** [comment]
Hi, 

All of pairs I tried have the same problem.

I tried also GlobalSfM and extracted features using latest version (I think so, since I just checkout from your github) of main_ComputeFeatures. The problem still happens.

Thanks
Trung

**Comment by pmoulon** [comment]
Can you test the tutorial_demo to see if the problem comes from OpenMVG or from your dataset?
Go in Build/software/SfM then run $ python tutorial_demo.py

**Comment by tntrung** [comment]
I will try tutorial_demo to see, but I am sure that the problem does not come from my dataset since it is OK when using VisualSFM or MVE.
