### ISSUE TITLE
3rdParties: flann

### ISSUE THREAD

**Issue by pyp22** [openMVG/openMVG#409]
Hi guys,
I remarked that flann 3rdparty compiling was producing a lib/pkgconfig/flann.pc. 

Isn't it conflicting with some Linux packaging distros that uses original flann for other things ?

cheers

ps : tnx fer newest v0.9 "Corydoras sterbai" :)

**Comment by pmoulon** [comment]
Hi @pyp22 
I think it does not create conflict if you export the OpenMVG install in a local directory.

**Comment by pyp22** [comment]
hmm not sure regarding PKG_CONFIG_PATH neither pkg-config mecanism when compiling something that needs flann. Depending of the distro you're using of course. (don't want to reactivate polemic about the use of /usr /usr/local /opt and so on)

Got to wait for some users feedback i think.

**Comment by pmoulon** [comment]
On my computer I use a local install where I installed openMVG in myWorkingPath/openMVG_Build/install_test/
And flann.pc is exported in myWorkingPath/openMVG_Build/install_test/lib/pkgconfig/. So I don't think it will create problems.
