### ISSUE TITLE
[bug] segmentation fault for ComputeStructureFromKnownPoses

### ISSUE THREAD

**Issue by simogasp** [openMVG/openMVG#416]
I'm having a segmentation fault when running `ComputeStructureFromKnownPoses`. Here is an example of the cout output when it occurs:
```
- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Compute frustum intersection
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
***Segmentation fault: 11
```

I suspected it is something related to OpenMP, ie some concurrency issues. Indeed when I ran it without OpenMP it works fine and the results seem to be ok. So I tried to isolate the problem, and apparently the problem is (obviously) in the "Per triplet tracks validation" part: if I disable OpenMP just in that part it works fine (I tried on a small and a very large dataset). I didn't have time to look further in the code though, I'll try to go deeper in the code in the next days.

**Comment by pmoulon** [comment]
Thanks @simogasp for the feedback.
From your message I also think it can be a parallelism error.
Strange fact: I notice that you have more stars than the 100%...

**Comment by simogasp** [comment]
Yes, that's what made me think of OpenMP as first suspect indeed

**Comment by simogasp** [comment]
I tested on ubuntu and it works fine, so I guess it must be some Clang bug/issue/restriction in implementing OpenMP.

**Comment by pmoulon** [comment]
In order to perform a full check you can try to modify the  omp parallel section to omp parallel for on a loop on the vector of triplets.

**Comment by pmoulon** [comment]
Can I close the issue?

**Comment by simogasp** [comment]
sorry i didn't have time to further investigate this. You can close it if you want, I will re-open it whenever I will have some news.

**Comment by pmoulon** [comment]
OK, thx
