### ISSUE TITLE
Data serialization - Data format {feature-request}

### ISSUE THREAD

**Issue by ORNis** [openMVG/openMVG#42]
Recent commits add some additional data formats. At the time being there are multiple formats in openMVG
- Camera files (one for simple pinhole camera model, another brown camera model)
- Image list files
- Camera database files

My suggestions to improve the situation goes in two directions
- Factorize all existing "formats". For example coupling the list of image files camera parameters files in a kind of global openMVG format
- Adopt a "standard" serialization format (JSON, XML...)

My preference goes to JSON because it's lightweight and flexible and in that sense it meets the requirements of openMVG. Moreover it offer a very good interoperability with other languages and potential services built on top of openMVG.

The major drawback of inclusion of a standard serialization format is that it could add another dependency to a third party library. In that sense it will lead to a less maintainable codebase. Another possibility should be to only adopt the JSON as a structure (instead of comma separated text) and perform I/O without an additional library.

Some light and modern JSON libraries
https://github.com/hjiang/jsonxx
https://github.com/sirikata/json-spirit (but depends on boost spirit...)
https://github.com/anhero/JsonBox
the three seem to be under MIT License.

**Comment by ORNis** [comment]
I think this could be close now...

**Comment by pmoulon** [comment]
You're right! @ORNis 
Now JSON/XML/BINARY input/output formats are natively supported thanks to the great cereal library.
