### ISSUE TITLE
SfM_GlobalPipeline.py error (images with not metadata)

### ISSUE THREAD

**Issue by edgarriba** [openMVG/openMVG#426]
Hi,

Got the following error when trying to run the SfM_GlobalPipeline python script

    5. Colorize Structure
    The input SfM_Data file "/home/eriba/Desktop/uav_reconstruction_openMVG/reconstruction_global/sfm_data.json" cannot be read.
    6. Structure from Known Poses (robust triangulation)
    Compute Structure from the provided poses
    The input SfM_Data file "/home/eriba/Desktop/uav_reconstruction_openMVG/reconstruction_global/sfm_data.json" cannot be read.
    The input SfM_Data file "/home/eriba/Desktop/uav_reconstruction_openMVG/reconstruction_global/robust.json" cannot be read.

Just following docs from here: http://openmvg.readthedocs.org/en/latest/software/SfM/GlobalSfM/#information-and-usage
     
     python SfM_GlobalPipeline.py /home/eriba/Desktop/uav_dataset /home/eriba/Desktop/uav_reconstruction_openMVG

Inside /uav_dataset there's only images in PNG format, /uav_reconstruction_openMVG empty dir.

**Comment by pmoulon** [comment]
Hi,
This is because EXIF metadata cannot be read in your PNG images, so the pixel focal length cannot be deduced.
If you know the focal length, you can specify it in SfM_InitImageListing with the -f option.
Here instruction to compute it:
http://openmvg.readthedocs.org/en/latest/software/SfM/SfMInit_ImageListing/#automatic-pixel-focal-computation-from-jpeg-exif-metadata
Else you can use a value like
```
1.2*max(w,h)
```

**Comment by edgarriba** [comment]
oh, thanks. Is there any way to run uncalibrated sfm?

**Comment by pmoulon** [comment]
Not yet.
Often the best solution is to use the trick 1.2*max(w,h).
1.2 can be reduced or put to a larger value depending if you known the larger of your FoV.

**Comment by edgarriba** [comment]
I know the intrinsics, was only curiosity. The fact is that I have noisy images where using TheiaSfM got good results with default parameters and no camera calibration. Just trying to achieve similar results with OpenMVG but no luck.

**Comment by pmoulon** [comment]
You must know that TheiaSfM use the trick I provide you (as VisualSfM do also).
https://github.com/sweeneychris/TheiaSfM/blob/b0680c6e20a2bf62b3ffde998735450c9525e549/applications/create_calibration_file_from_exif.cc#L81
https://github.com/sweeneychris/TheiaSfM/blob/b0680c6e20a2bf62b3ffde998735450c9525e549/docs/source/sfm.rst#L449

**Comment by edgarriba** [comment]
nice! just got similar results but needed to resample my dataset by half of the original size in addition to set the video matching mode to 0. 

Plus, got this error during color extraction

    Compute scene structure color
    0%   10   20   30   40   50   60   70   80   90   100%
     |----|----|----|----|----|----|----|----|----|----|
    openMVG_main_ComputeSfM_DataColor: /home/eriba/software/openMVG/src/third_party/eigen/Eigen/src/Core/DenseCoeffsBase.h:337: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<openMVG::image::Rgb<unsigned char>, -1, -1, 1, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = openMVG::image::Rgb<unsigned char>; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.

**Comment by pmoulon** [comment]
The last error can be due to the fact that a 3D point reprojection is not inside the image.

**Comment by edgarriba** [comment]
ok. Thanks!
