### ISSUE TITLE
openMVG_main_ColHarmonize example

### ISSUE THREAD

**Issue by lulu1315** [openMVG/openMVG#431]
hello
I'm trying to use openMVG_main_ColHarmonize but I'm not exactly sure on what it needs as input : 
I did a sequential pipeline so my results are in /whatever/MVG_seq with two dirs /matches and /reconstruction_sequential.
what should I use for -i and -m ?
thanks in advance
luc

**Comment by pmoulon** [comment]
Hi,
As explained in the command line help: https://github.com/openMVG/openMVG/blob/master/src/software/colorHarmonize/main_ColHarmonize.cpp#L47

So you must run:
1. Image listing
openMVG_main_SfMInit_ImageListing
2. Image description computation
openMVG_main_ComputeFeatures
3. Corresponding images and correspondences computation
openMVG_main_ComputeMatches
4. Color Harmonization
openMVG_main_ColHarmonize
-i with the input sfm_data.json file
-m the matching file matches.X.txt with X f/e/h depending of the constraint you will choose in ComputeMatches

**Comment by lulu1315** [comment]
ok . thanks a lot for that.
