### ISSUE TITLE
[registration] Scene registration from image's gps metadata

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#432]
Hi Dr Pierre MOULON, I am using openMVG to process UAV iamges which only have gps metadata. What I want to do is  making a absolute orientation for the result of free BA from openMVG. Is there  a solution for this ?
ps:
I have bulid  a project  to test the Similarity betweent image's poses from BA and their GPS info. But the result  is not good for the geometry of the registered landmarks is not the same as the original one.
Thanks in advance.

**Comment by pmoulon** [comment]
Hi,
Absolute orientation thanks to GPS camera position:
- I plan to implement this feature soon. But note that the registration quality will depends of your GPS position quality (often GPS measurements are not so accurate, I mean they may have a large noise).
1.First you have to choose your spatial referencing system.
I suppose that you have 3D point for your GPS position (perhaps in the ECEF coordinates system).

2. Once you have your Camera - 3D position correspondences: You compute the similarity between the camera center ant their known GPS position and apply the found transformation to the sfm_data (So camera orientation, poses & the scene will be in your absolute coordinates).

**Comment by whuaegeanse** [comment]
Hi Dr pmoulon , thanks  for your reply. I know  what you mean.

**Comment by whuaegeanse** [comment]
how about using ceres sovler to  optimization  the similarity between the camera center ant their known GPS position after get the initial value  of the similarity computed from  geometry::FindRTS.
Is geometry::FindRTS robust to get the initial value of the similarity when image's gps info with large noise?

**Comment by pmoulon** [comment]
Refinement of the RTS is already implemented see here:
https://github.com/openMVG/openMVG/blob/f0889f0a0024a211a7e5ed71794ad1926e545767/src/openMVG/geometry/rigid_transformation3D_srt.hpp#L170

**Comment by FreakTheMighty** [comment]
This will be a very cool feature :+1:

**Comment by whuaegeanse** [comment]
I have a try with the code from the project ui_openMVG_control_points_registration.
my code are writen as follow:
using namespace openMVG;
using namespace openMVG::cameras;
using namespace openMVG::sfm;

bool ReadImagePos(const std::string &strGPSFile, std::map<std::string, Vec3> &vec_images_gps )
{
	using namespace std;
	fstream file(strGPSFile, std::ios::in);
	if (!file.is_open())
	{
		return false;
	}

	vec_images_gps.clear();
	
	string strLine;
	while (std::getline(file, strLine))
	{
		std::stringstream oss(strLine);
		if (strLine.empty())
		{
			continue;
		}
		std::string strImageName;
		double dLon, dLat, dAlt;
		oss >> strImageName >> dLon >> dLat >> dAlt;
		Vec3 gps;
		gps(0) = dLon;
		gps(1) = dLat;
		gps(2) = dAlt;
		vec_images_gps[strImageName] = gps;
	}

	return true;
}

//
// Create the description of an input image dataset for OpenMVG toolsuite
// - Export a SfM_Data file with View & Intrinsic data
//
int main(int argc, char **argv)
{
  CmdLine cmd;

  std::string sSfM_Data_Filename_In = "E:\\测试影像-AerialPhotos\\1104-out\\reconstruction_global\\sfm_data.json";
  std::string sSfM_Data_Filename_Out = "E:\\测试影像-AerialPhotos\\1104-out\\reconstruction_global\\sfm_data_georegistered.json";
  std::string sGPS_Filename = "E:\\测试影像-AerialPhotos\\1104\\ImagePairs.txt.gps";

 /* cmd.add(make_option('i', sSfM_Data_Filename_In, "input_sfmdata_file"));
  cmd.add(make_option('o', sSfM_Data_Filename_Out, "output_sfmdata_file"));
  cmd.add(make_option('g', sGPS_Filename, "gps_file"));

  try {
      if (argc == 1) throw std::string("Invalid command line parameter.");
      cmd.process(argc, argv);
  } catch(const std::string& s) {
      std::cerr << "Usage: " << argv[0] << '\n'
      << "[-i|--input_sfmdata_file]\n"
	  << "[-o|--output_sfmdata_file]\n"
	  << "[-g]--gps_file \n" 
      << std::endl;

      std::cerr << s << std::endl;
      return EXIT_FAILURE;
  }*/

  if (!stlplus::file_exists(sSfM_Data_Filename_In))							  
  {
	  std::cerr << std::endl
		  << "The input SfM_Data file \"" << sSfM_Data_Filename_In << "\" is not existed." << std::endl;
  }

  if (!stlplus::file_exists(sGPS_Filename))
  {
	  std::cerr << std::endl
		  << "The input GPS file \"" << sGPS_Filename << "\" is not existed." << std::endl;
  }

  std::cout << " You called : " << std::endl
	  << "Usage: " << argv[0] << '\n'
	  << "[-i|--input_sfmdata_file]\n"
	  << "[-o|--output_sfmdata_file]\n"
	  << "[-g]--gps_file \n"
	  << std::endl;

  // Load GPS file


  // Load input SfM_Data scene
  SfM_Data sfm_data;
  if (!Load(sfm_data, sSfM_Data_Filename_In, ESfM_Data(ALL)))
  {
	  std::cerr << std::endl
		  << "The input SfM_Data file \"" << sSfM_Data_Filename_In << "\" cannot be read." << std::endl;
	  return EXIT_FAILURE;
  }

  std::map<std::string, Vec3> vec_iamge_gps;

  if (!ReadImagePos(sGPS_Filename, vec_iamge_gps))
  {
	  std::cerr << std::endl
		  << "The input GPS file \"" << sGPS_Filename << "\" cannot be read." << std::endl;
	  return EXIT_FAILURE;
  }

  int nIndex = 0;
  // two corrsponding points
  std::map<IndexT, Vec3> vec_control_points, vec_triangulated;
  for (Views::iterator iterP = sfm_data.views.begin();
	  iterP != sfm_data.views.end(); ++iterP)
  {
	
	  std::shared_ptr<View> &view = iterP->second;
	  if (vec_iamge_gps.find(stlplus::filename_part(view->s_Img_path)) != vec_iamge_gps.end())
	  {
		  geometry::Pose3 pose = sfm_data.GetPoseOrDie(view.get());
		  vec_triangulated[nIndex] = pose.center();
		  vec_control_points[nIndex] = vec_iamge_gps[stlplus::filename_part(view->s_Img_path)];	
		  ++nIndex;
	  }
  }
  
  // compute the similarity
  {
	  // data conversion to appropriate container
	  Mat x1(3, vec_control_points.size()),
		  x2(3, vec_control_points.size());
	  for (int i = 0; i < vec_control_points.size(); ++i)
	  {
		  x1.col(i) = vec_triangulated[i];
		  x2.col(i) = vec_control_points[i];
	  }

	  std::cout
		  << "Control points observation triangulations:\n"
		  << x1 << std::endl << std::endl
		  << "Control points coords:\n"
		  << x2 << std::endl << std::endl;

	  Vec3 t;
	  Mat3 R;
	  double S;
	  if (openMVG::geometry::FindRTS(x1, x2, &S, &t, &R))
	  {
		  Vec3 angleAxis;
		  ceres::RotationMatrixToAngleAxis(R.data(), angleAxis.data());
		  openMVG::geometry::Refine_RTS(x1, x2, &S, &t, &R);
		  std::cout << "Found transform:\n"
			  << " scale: " << S << "\n"
			  << " rotation:\n" << R << "\n"
			  << " translation: " << t.transpose() << std::endl;

		  
		  // Encode the transformation as a 3D Similarity tran  sformation matrix // S * R * X + t
		  const openMVG::geometry::Similarity3 sim(geometry::Pose3(R, -R.transpose()* t/S), S);

		  //--
		  // Apply the found transformation
		  //--

		  // Transform the landmark positions
		  for (Landmarks::iterator iterL = sfm_data.structure.begin();
			  iterL != sfm_data.structure.end(); ++iterL)
		  {
			  iterL->second.X = sim(iterL->second.X);
		  }

		  // Transform the camera positions
		  for (Poses::iterator iterP = sfm_data.poses.begin();
			  iterP != sfm_data.poses.end(); ++iterP)
		  {
			  geometry::Pose3 & pose = iterP->second;
			  pose = sim(pose);
		  }


		  double dMax = 0.0, dMin =100000000000000000.0;
		  int nMaxIndex = -1, nMinIndex = -1;
		  // Display some statistics:
		  std::stringstream os;
		  for (Views::const_iterator iterL = sfm_data.views.begin();
			  iterL != sfm_data.views.end(); ++iterL)
		  {
			  const IndexT CPIndex = iterL->first;

			  Vec3 vecError = sim(vec_triangulated[CPIndex]) - vec_control_points[CPIndex];
			  double dError = vecError.norm();

			  if (dMax<dError)
			  {
				  dMax = dError;
				  nMaxIndex = CPIndex;
			  }

			  if (dMin > dError)
			  {
				  dMin = dError;
				  nMinIndex = CPIndex;
			  }

			  os
				  << "CP index: " << CPIndex << "\n"
				  << "CP registration error: "
				  << dError << " user unit(s)" << "\n\n";
			 
		  }
		  os << "CP index: " << nMaxIndex << "\n" 
			  << "Max error:" << dMax << "\n"
			  << "CP index: " << nMinIndex << "\n"
			  << "Min error:" << dMin << "\n";
		  std::cout << os.str();
		  Save(sfm_data, sSfM_Data_Filename_Out, ESfM_Data(ALL));
		  Save(sfm_data,
			  stlplus::create_filespec(stlplus::folder_part(sSfM_Data_Filename_Out), stlplus::basename_part(sSfM_Data_Filename_Out), ".ply" ),
			  ESfM_Data(ALL));
	  }
  }
  return EXIT_SUCCESS;
}

**Comment by whuaegeanse** [comment]
the format of  image's gps metadata file is as follow:

**Comment by whuaegeanse** [comment]
DJI_0508.JPG 738089.7658 2567137.424 109.9
DJI_0509.JPG 738107.1478 2567137.792 109.8
DJI_0510.JPG 738130.4572 2567138.241 110
DJI_0511.JPG 738154.5233 2567138.722 110
DJI_0512.JPG 738178.7668 2567138.962 110
DJI_0513.JPG 738202.8051 2567139.401 110
DJI_0514.JPG 738227.5947 2567139.666 110
DJI_0515.JPG 738253.0194 2567140.442 110
DJI_0516.JPG 738278.1241 2567140.585 110
DJI_0517.JPG 738301.9298 2567140.972 109.8
DJI_0518.JPG 738327.5984 2567141.447 109.9
DJI_0519.JPG 738347.4234 2567141.58 109.8
DJI_0520.JPG 738363.1924 2567195.598 110.4
DJI_0521.JPG 738343.6965 2567195.006 109.7
DJI_0522.JPG 738318.3017 2567194.679 109.9
DJI_0523.JPG 738294.2188 2567194.362 109.9
DJI_0524.JPG 738246.2378 2567193.04 109.9
DJI_0525.JPG 738222.5044 2567193.122 110
DJI_0526.JPG 738198.5082 2567192.372 109.8
DJI_0527.JPG 738150.08 2567191.425 110.2
DJI_0528.JPG 738126.1675 2567191.317 109.9
DJI_0529.JPG 738080.089 2567190.989 109.9
DJI_0530.JPG 738089.0951 2567244.006 109.9
DJI_0531.JPG 738114.5151 2567244.354 109.9
DJI_0532.JPG 738139.8878 2567244.809 110
DJI_0533.JPG 738159.0862 2567245.135 110.1
DJI_0534.JPG 738186.1413 2567245.755 110
DJI_0535.JPG 738211.5815 2567246.082 109.9
DJI_0536.JPG 738232.0215 2567246.372 109.8
DJI_0537.JPG 738257.7978 2567246.861 110.1
DJI_0538.JPG 738281.8206 2567247.187 109.9
DJI_0539.JPG 738305.7147 2567247.554 110
DJI_0540.JPG 738329.8344 2567248.054 110
DJI_0541.JPG 738353.7527 2567248.335 110
DJI_0542.JPG 738358.4647 2567301.413 109.9
DJI_0543.JPG 738336.2779 2567301.255 109.9
DJI_0544.JPG 738288.8305 2567300.222 109.9
DJI_0545.JPG 738264.7425 2567299.883 110.1
DJI_0546.JPG 738240.8538 2567299.543 110.1
DJI_0547.JPG 738214.888 2567298.98 110.1
DJI_0548.JPG 738195.0366 2567298.912 109.9
DJI_0549.JPG 738170.2432 2567298.719 109.9
DJI_0550.JPG 738077.9013 2567296.676 109.9
DJI_0551.JPG 738077.4802 2567350.61 110.3
DJI_0552.JPG 738093.1694 2567350.381 109.8
DJI_0553.JPG 738141.3641 2567351.124 110.1
DJI_0554.JPG 738237.6145 2567352.58 110
DJI_0555.JPG 738262.8076 2567353.042 110
DJI_0556.JPG 738287.4296 2567353.442 109.9
DJI_0557.JPG 738312.094 2567353.861 110
DJI_0558.JPG 738336.0587 2567354.254 109.9
DJI_0559.JPG 738347.7949 2567407.703 109.9
DJI_0560.JPG 738328.8492 2567407.252 109.8
DJI_0561.JPG 738302.3848 2567406.733 109.8
DJI_0562.JPG 738278.359 2567406.253 110
DJI_0563.JPG 738254.1899 2567405.832 110
DJI_0564.JPG 738229.9289 2567405.647 110
DJI_0565.JPG 738205.8239 2567405.311 109.9
DJI_0566.JPG 738157.6848 2567404.483 110
DJI_0567.JPG 738133.9722 2567404.18 110
DJI_0568.JPG 738085.2669 2567403.164 109.9
DJI_0569.JPG 738108.1591 2567159.988 109.9
DJI_0570.JPG 738107.9529 2567181.075 109.9
DJI_0571.JPG 738107.638 2567205.045 109.9
DJI_0572.JPG 738107.209 2567229.028 109.9
DJI_0573.JPG 738106.7719 2567252.987 109.8
DJI_0574.JPG 738106.4768 2567276.96 110
DJI_0575.JPG 738106.1507 2567300.914 109.9
DJI_0576.JPG 738105.8958 2567324.691 110
DJI_0577.JPG 738105.612 2567348.671 110
DJI_0578.JPG 738105.1587 2567370.967 109.9
DJI_0579.JPG 738158.7351 2567356.611 109.7
DJI_0580.JPG 738159.5119 2567307.325 109.9
DJI_0581.JPG 738159.9905 2567288.256 109.9
DJI_0582.JPG 738160.2998 2567262.685 110.1
DJI_0583.JPG 738160.5884 2567236.988 110
DJI_0584.JPG 738161.1634 2567210.642 109.9
DJI_0585.JPG 738161.3614 2567186.695 110
DJI_0586.JPG 738161.7462 2567162.806 110
DJI_0587.JPG 738214.832 2567168.319 109.9
DJI_0588.JPG 738214.4069 2567192.405 110
DJI_0589.JPG 738214.0403 2567216.568 110.1
DJI_0590.JPG 738213.8395 2567240.509 110.1
DJI_0591.JPG 738213.3987 2567265.04 109.9
DJI_0592.JPG 738213.0605 2567283.517 110
DJI_0593.JPG 738212.5573 2567313.367 109.9
DJI_0594.JPG 738212.1731 2567331.339 109.9
DJI_0595.JPG 738211.8078 2567355.779 110
DJI_0596.JPG 738265.0369 2567373.81 110.3
DJI_0597.JPG 738265.1958 2567355.164 109.7
DJI_0598.JPG 738265.5867 2567329.662 109.9
DJI_0599.JPG 738265.8628 2567304.402 109.9
DJI_0600.JPG 738266.198 2567280.429 110
DJI_0601.JPG 738266.6386 2567256.624 110
DJI_0602.JPG 738266.9649 2567232.67 110
DJI_0603.JPG 738267.4725 2567208.771 110
DJI_0604.JPG 738267.8502 2567184.811 109.9
DJI_0605.JPG 738268.1138 2567161.93 109.8
DJI_0606.JPG 738321.2173 2567173.805 109.8
DJI_0607.JPG 738320.765 2567198.333 109.9
DJI_0608.JPG 738320.3385 2567223.025 110
DJI_0609.JPG 738319.493 2567267.855 110
DJI_0610.JPG 738319.0462 2567292.395 110
DJI_0611.JPG 738318.6493 2567316.841 110
DJI_0612.JPG 738318.3664 2567341.28 110
DJI_0613.JPG 738318.1181 2567360.349 110.1

**Comment by whuaegeanse** [comment]
I reproject the image's original gps coordinates to a projected spatial reference (epsg 4508 --a CGCS2000 projected coord system)
the format of image's gps metadata file is as follow:
DJI_0508.JPG 738089.7658 2567137.424 109.9
DJI_0509.JPG 738107.1478 2567137.792 109.8
DJI_0510.JPG 738130.4572 2567138.241 110
DJI_0511.JPG 738154.5233 2567138.722 110
DJI_0512.JPG 738178.7668 2567138.962 110
DJI_0513.JPG 738202.8051 2567139.401 110
DJI_0514.JPG 738227.5947 2567139.666 110
DJI_0515.JPG 738253.0194 2567140.442 110
DJI_0516.JPG 738278.1241 2567140.585 110
DJI_0517.JPG 738301.9298 2567140.972 109.8
DJI_0518.JPG 738327.5984 2567141.447 109.9
DJI_0519.JPG 738347.4234 2567141.58 109.8
DJI_0520.JPG 738363.1924 2567195.598 110.4
DJI_0521.JPG 738343.6965 2567195.006 109.7
DJI_0522.JPG 738318.3017 2567194.679 109.9
DJI_0523.JPG 738294.2188 2567194.362 109.9
DJI_0524.JPG 738246.2378 2567193.04 109.9
DJI_0525.JPG 738222.5044 2567193.122 110
DJI_0526.JPG 738198.5082 2567192.372 109.8
DJI_0527.JPG 738150.08 2567191.425 110.2
DJI_0528.JPG 738126.1675 2567191.317 109.9
DJI_0529.JPG 738080.089 2567190.989 109.9
DJI_0530.JPG 738089.0951 2567244.006 109.9
DJI_0531.JPG 738114.5151 2567244.354 109.9
DJI_0532.JPG 738139.8878 2567244.809 110
DJI_0533.JPG 738159.0862 2567245.135 110.1
DJI_0534.JPG 738186.1413 2567245.755 110
DJI_0535.JPG 738211.5815 2567246.082 109.9
DJI_0536.JPG 738232.0215 2567246.372 109.8
DJI_0537.JPG 738257.7978 2567246.861 110.1
DJI_0538.JPG 738281.8206 2567247.187 109.9
DJI_0539.JPG 738305.7147 2567247.554 110
DJI_0540.JPG 738329.8344 2567248.054 110
DJI_0541.JPG 738353.7527 2567248.335 110
DJI_0542.JPG 738358.4647 2567301.413 109.9
DJI_0543.JPG 738336.2779 2567301.255 109.9
DJI_0544.JPG 738288.8305 2567300.222 109.9
DJI_0545.JPG 738264.7425 2567299.883 110.1
DJI_0546.JPG 738240.8538 2567299.543 110.1
DJI_0547.JPG 738214.888 2567298.98 110.1
DJI_0548.JPG 738195.0366 2567298.912 109.9
DJI_0549.JPG 738170.2432 2567298.719 109.9
DJI_0550.JPG 738077.9013 2567296.676 109.9
DJI_0551.JPG 738077.4802 2567350.61 110.3
DJI_0552.JPG 738093.1694 2567350.381 109.8
DJI_0553.JPG 738141.3641 2567351.124 110.1
DJI_0554.JPG 738237.6145 2567352.58 110
DJI_0555.JPG 738262.8076 2567353.042 110
DJI_0556.JPG 738287.4296 2567353.442 109.9
DJI_0557.JPG 738312.094 2567353.861 110
DJI_0558.JPG 738336.0587 2567354.254 109.9
DJI_0559.JPG 738347.7949 2567407.703 109.9
DJI_0560.JPG 738328.8492 2567407.252 109.8
DJI_0561.JPG 738302.3848 2567406.733 109.8
DJI_0562.JPG 738278.359 2567406.253 110
DJI_0563.JPG 738254.1899 2567405.832 110
DJI_0564.JPG 738229.9289 2567405.647 110
DJI_0565.JPG 738205.8239 2567405.311 109.9
DJI_0566.JPG 738157.6848 2567404.483 110
DJI_0567.JPG 738133.9722 2567404.18 110
DJI_0568.JPG 738085.2669 2567403.164 109.9
DJI_0569.JPG 738108.1591 2567159.988 109.9
DJI_0570.JPG 738107.9529 2567181.075 109.9
DJI_0571.JPG 738107.638 2567205.045 109.9
DJI_0572.JPG 738107.209 2567229.028 109.9
DJI_0573.JPG 738106.7719 2567252.987 109.8
DJI_0574.JPG 738106.4768 2567276.96 110
DJI_0575.JPG 738106.1507 2567300.914 109.9
DJI_0576.JPG 738105.8958 2567324.691 110
DJI_0577.JPG 738105.612 2567348.671 110
DJI_0578.JPG 738105.1587 2567370.967 109.9
DJI_0579.JPG 738158.7351 2567356.611 109.7
DJI_0580.JPG 738159.5119 2567307.325 109.9
DJI_0581.JPG 738159.9905 2567288.256 109.9
DJI_0582.JPG 738160.2998 2567262.685 110.1
DJI_0583.JPG 738160.5884 2567236.988 110
DJI_0584.JPG 738161.1634 2567210.642 109.9
DJI_0585.JPG 738161.3614 2567186.695 110
DJI_0586.JPG 738161.7462 2567162.806 110
DJI_0587.JPG 738214.832 2567168.319 109.9
DJI_0588.JPG 738214.4069 2567192.405 110
DJI_0589.JPG 738214.0403 2567216.568 110.1
DJI_0590.JPG 738213.8395 2567240.509 110.1
DJI_0591.JPG 738213.3987 2567265.04 109.9
DJI_0592.JPG 738213.0605 2567283.517 110
DJI_0593.JPG 738212.5573 2567313.367 109.9
DJI_0594.JPG 738212.1731 2567331.339 109.9
DJI_0595.JPG 738211.8078 2567355.779 110
DJI_0596.JPG 738265.0369 2567373.81 110.3
DJI_0597.JPG 738265.1958 2567355.164 109.7
DJI_0598.JPG 738265.5867 2567329.662 109.9
DJI_0599.JPG 738265.8628 2567304.402 109.9
DJI_0600.JPG 738266.198 2567280.429 110
DJI_0601.JPG 738266.6386 2567256.624 110
DJI_0602.JPG 738266.9649 2567232.67 110
DJI_0603.JPG 738267.4725 2567208.771 110
DJI_0604.JPG 738267.8502 2567184.811 109.9
DJI_0605.JPG 738268.1138 2567161.93 109.8
DJI_0606.JPG 738321.2173 2567173.805 109.8
DJI_0607.JPG 738320.765 2567198.333 109.9
DJI_0608.JPG 738320.3385 2567223.025 110
DJI_0609.JPG 738319.493 2567267.855 110
DJI_0610.JPG 738319.0462 2567292.395 110
DJI_0611.JPG 738318.6493 2567316.841 110
DJI_0612.JPG 738318.3664 2567341.28 110
DJI_0613.JPG 738318.1181 2567360.349 110.1

**Comment by pmoulon** [comment]
Code seems ok.
What are the typical error range you obtained?

**Comment by EthanGreen75** [comment]
活捉大疆员工一只

**Comment by pmoulon** [comment]
@EthanGreen75 Please write in English...

**Comment by EthanGreen75** [comment]
@pmoulon Hello Dr Pierre MOULON, I am really sorry for the comments I wrote before. It's just a joke and please ignore it. And thank u very much for replying so quickly.
    I am really interested in the geo-registration of SFM. I also use the open-source and commercial software like VisualSFM and PHOTOSCAN and it provides the geo-registration by GPS. My aim is to transform the local coordinate into the real-world coordinate. In consideration of the accuracy of GPS, I wonder is there any other ways to decrease the noise? Like the angle of pitch and horizontal angle of the phone measure by the gradienter and electric compass when taking the photos? I know that there are also some noise of these devices, but maybe more data could refine the coordinates for better.
   Thank u so much!

**Comment by pmoulon** [comment]
Closing this thread.
I refer the readers to go there for more information about registration to GPS data
https://github.com/openMVG/openMVG/issues/547
