### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by FreakTheMighty** [openMVG/openMVG#435]
This may be very challanging, but I think its worth putting in backlog. It would be really great to have python bindings for parts of the openMVG API. I think a higher level language would allow more developers to contribute different CLI's and possibly a web interface.

**Comment by autosquid** [comment]
I came across this issue when searching  for OpenMVG python binding.

For high level binding, I think SWIG is really nice.

**Comment by simogasp** [comment]
With SWIG we could also generate, among others, Matlab bindings, which could be really useful as well. +1 :-)

**Comment by pmoulon** [comment]
Closing the issue since there is no more feedback since long time.
