### ISSUE TITLE
[Release] v1.0

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#438]
- [x] Prepare version numbering
- [x] Release log

**Comment by whuaegeanse** [comment]
V1.0 is released?? what are the features of this version?

**Comment by pmoulon** [comment]
Not yet this is a WIP ...
See here for the steps that have been done and the remaining ones
https://github.com/openMVG/openMVG/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Putative+V1.0%22
