### ISSUE TITLE
importing Mosek 6

### ISSUE THREAD

**Issue by hlzz** [openMVG/openMVG#439]
Hi,

I am trying to use Mosek 6 in openMVG. But when I compiled the program, the ‘make’ command gives me the following error:

Linking CXX static library ../../Darwin-x86_64-RELEASE/libopenMVG_linearProgrammingMSK.a
[ 81%] Built target openMVG_linearProgrammingMSK
[ 81%] Building CXX object openMVG/linearProgramming/CMakeFiles/openMVG_linearProgramming_test_linearProgramming.dir/linearProgramming_test.cpp.o
In file included from /Users/STW/Documents/Projects/openMVG/src/openMVG/linearProgramming/linearProgramming_test.cpp:14:
/Users/STW/Documents/Projects/openMVG/src/openMVG/linearProgramming/linearProgrammingOSI_X.hpp:284:9: error: 
      no member named 'getModelPtr' in 'OsiMskSolverInterface'
    si->getModelPtr()->setPerturbation(50);
    ~~  ^
/Users/STW/Documents/Projects/openMVG/src/openMVG/linearProgramming/linearProgrammingOSI_X.hpp:67:45: note: 
      in instantiation of member function
      'openMVG::linearProgramming::OSI_X_SolverWrapper<OsiMskSolverInterface>::solve'
      requested here
OSI_X_SolverWrapper<OsiMskSolverInterface>::OSI_X_SolverWrapper(int nbPar...
                                            ^
1 error generated.
make[2]: *** [openMVG/linearProgramming/CMakeFiles/openMVG_linearProgramming_test_linearProgramming.dir/linearProgramming_test.cpp.o] Error 1
make[1]: *** [openMVG/linearProgramming/CMakeFiles/openMVG_linearProgramming_test_linearProgramming.dir/all] Error 2
make: *** [all] Error 2

I’ve checked linearProgrammingOSI_X.hpp, it seems that OsiMskSolverInterface class doesn’t have a method called getModelPtr(), which is needed by bool OSI_X_SolverWrapper<SOLVERINTERFACE>::solve(). Also, the OsiMskSolverInterface.hpp is osi_clp is outdated since it is a Osi interface for Mosek 5.0, not 6. I’ve encountered this problem both under MacOS and linux. So how can I use Mosek 6 in openMVG? Thanks for your help.

**Comment by pmoulon** [comment]
Hi @hlzz 
Thanks for your feedback.

Do you especially need to use MOSEK?
Mosek is not compulsory, all the features will work with the existing solver (OSI CLP).
Did you already have made successful experiments?

If you really need to use MOSEK, I would recommend to update the existing wrapper to fit the new MOSEK API (V6 or v7) or use the V5.

PS: congrats for the release of your libvot library. I would love to test it in front of OpenMVG ;-)

**Comment by hlzz** [comment]
Hi @pmoulon ,

Thanks for your reply. I have successfully run the sfm pipeline with OSI_CLP. I just want to make sure that there is no easy way to directly use Mosek, thus I will try to integrate MOSEK 6 (or maybe 7) myself, since it supports more functionality regarding convex optimization, which is potentially useful for future extension. 

As for libvot library, thanks for noticing it. Actually I have plan to integrate it into the OpenMVG pipeline. The main obstacle is to convert different feature format but that should be easy to handle. In all, thanks for your great work.

**Comment by pmoulon** [comment]
Regarding MOSEK it's as you want, we can update the existing framework to work with more recent version.

For libvot we can make a new repository that use OpenMVG as a third party library and that will compute some image pair similarity that could be used later in the SfM process.
The different feature format could be handle easily by loading the OpenMVG one and convert them to your format ;-) or perhaps adapt your libvot to support OpenMVG regions. Let continuer discuss on this last point if you want in the coming days.

**Comment by hlzz** [comment]
Sorry for the late reply since I was a little busy these days. I notice that main_ComputeMatches is actually a very versatile and scalable interface. And it supports the input of a pre-defined pair_list. So I just need to make libvot support and reuse the features that openMVG are using. Then I guess the generation of similarity scores can be put after feature generation and before feature correspondence computation?

**Comment by pmoulon** [comment]
You're right.
You can read directly the produced files or use OpenMVG as a third party library and load the files with the OpenMVG interface.

The ideal process would be the following:
compute feature (OpenMVG)
compute simililarity pairs (libvot) => export a pair file (id of the corresponding best images)
compute matching (OpenMVG) that use the pair file.
