### ISSUE TITLE
Masking before SIFT

### ISSUE THREAD

**Issue by aph3xtwin** [openMVG/openMVG#440]
I saw masking-ability in the code of the OpenCV-feature-detecting but it is somewhat undocumented. Can you provide an example of how to run feature-detection while leaving out masked areas?

**Comment by pmoulon** [comment]
@aph3xtwin Sorry I didn't answer sooner.
You are right the masking is undocumented.
I plan to add a rule that will look if (in the 'image/match' directory):
- an "imagefilename"_mask.png exists,
- a global mask.png exists.

Any suggestion will be welcomed.

**Comment by ORNis** [comment]
One short note Pierre : About 2 month ago I tested the mask functionality you added  in v 0.8/ v 0.7 (if I remember well) with the same mechanism you describe above. I had some "random" issue when I used SIFT detector + mask (Akaze was fine). Sorry for the lack of precision, it was a kind of array overflow.

**Comment by pmoulon** [comment]
Thanks @ORNis 
Perhaps it was due to a pixel casting issue that try to sample a point out of the image.
Would be interesting if you can reproduce the problem in order to let me check.

**Comment by ORNis** [comment]
I think it's the issue you describe, as far as I can remember it was a Eigen error. So it's certainly related to openMVG::image. 
I checked and I still have the branch where I made this experiment, but unfortunatly I have removed the dataset. I will try to reproduce this ASAP.

**Comment by pmoulon** [comment]
@aph3xtwin The feature is done in the develop branch.
See here for the documentation: https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/ComputeFeatures.rst (chapter Use mask to filter keypoints/regions)
