### ISSUE TITLE
Focal length is missing

### ISSUE THREAD

**Issue by polto** [openMVG/openMVG#442]
Hi,

I installed a new camera app on my Android based camera and openMVG_main_SfMInit_ImageListing now return:
Warning & Error messages:
1449910115_000000: Focal length is missing.
for each image.

Images from the same camera but with another app are working.

I am trying to use OpenCamera on Android for it's very practical and configurable burst mode. But also because uses the camera compass and not only GPS.

Here is the output on image that is not recognized:
exiftool original_images/1449910115_000000.jpeg |grep -i length
Focal Length                    : 20.0 mm
Other Image Length              : 7320
MP Image Length                 : 69685
Focal Length                    : 20.0 mm

exiftool original_images/1449401000_000000.jpeg | grep -i length
Focal Length                    : 20.0 mm
Focal Length In 35mm Format     : 30 mm
Thumbnail Length                : 8474
MP Image Length                 : 79816
Focal Length                    : 20.0 mm (35 mm equivalent: 30.0 mm)

You can get non working images from http://doxel.org/doxel-viewer/upload/2015/12/12/14499165/db03d2adb3f8ee0bd72fdd2ccc1f7fb2/1449916530_000000/original_images/ 

Any help would be appreciated.
Best regards.

**Comment by pmoulon** [comment]
I found the problem.
The EXIF norm say "All IFD0 tags may also be present in IFD1, according to the standard."
But the actual used exif library does not consider this point.
Will look how to handle this.

**Comment by polto** [comment]
Many thanks ! I got some other images from another camera with a similar problem.

**Comment by pmoulon** [comment]
@polto  Tell me if the code pushed in the branch develop_exif solved your problem with your various image datasets.
I have tested on one image of your link and now it works fine. :+1:

**Comment by polto** [comment]
@pmoulon, thank you ! yes, it works !

**Comment by pmoulon** [comment]
I will merge it in the develop branch.

**Comment by pmoulon** [comment]
Merged https://github.com/openMVG/openMVG/commit/39b2ecf1f5412020aedee5b40a4d06acaf95b3a3
