### ISSUE TITLE
question on the meaning of extrinsic in sfm_data.json

### ISSUE THREAD

**Issue by autosquid** [openMVG/openMVG#445]
The sfm_data.json file as the output of reconstruction stores also the pose of cameras. What I do not understand is the meaning of centers in extrinsics, are they just the center of cameras in the global frame, or just the translation part in the projective function?
In other words, are they the ```t``` or ```C``` by with the symbols defined in : http://openmvg.readthedocs.org/en/latest/openMVG/cameras/cameras/ ?

**Comment by pmoulon** [comment]
@autosquid For the camera the camera center 'c' is stored.
