### ISSUE TITLE
OpenMVG for UAV image's quick mosaic 

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#447]
Is there a plan using OpenMVG for uav image's quick mosaic?
This would be a special application for OpenMVG. 
I have made an mosaic application based on gdal warp(extented to support the frame image's ortho rectification) for geo images(orth images of uav images). 
The key step to make a quick mosaic for uav images is to refine the initial poses which are contaminated with noise.

**Comment by pmoulon** [comment]
Hi @whuaegeanse 
What do you meed by quick mosaic (a large planar ortho image)?

In OpenMVG you have the tools to compute the homographies that links the different images.

**Comment by pmoulon** [comment]
@whuaegeanse Any feedback?

**Comment by whuaegeanse** [comment]
Sorry for that I forgot to reply. I want to make ortho images and mosaic them  together.
for the present I have finished to later step( rectify image and mosaic them together). The rest of work is to  use openmvg to match and make bundle adjustment. I think that making a big panorama image is the same way for just using different rectification model, after I use the app  called ICE(Image Composite Editor) from Microsoft Research.
While ICE is quicky, the result generated from is not measurable and may have a large distortion in  mountain area.

**Comment by pmoulon** [comment]
You can use OpenMVG easily to compute homography valid matches.
  - ComputeFeature 
  - ComputeMatches with "-g h" option. It will restrict geometric matches to homographies.

For BA you will have to add your own residual cost to force homography constraints.
Having a stitching pipeline in OpenMVG would be a great contribution.
