### ISSUE TITLE
openMVG camera model

### ISSUE THREAD

**Issue by lulu1315** [openMVG/openMVG#448]
hello 
I'm trying to change the camera model in openMVG_main_IncrementalSfM to avoid distortion.
I'm using -c 1 but when looking in the sfm_data.json I always have 
"polymorphic_name": "pinhole_radial_k3"
using -c 2 is the same.
looks like -c is not having any effect.
do I miss anything?
luc

**Comment by pmoulon** [comment]
Hi @lulu1315.
You Can choose the camera model only with the ImageListing process.
You Can rerun ImageListint with -c X and re run the Sfm binary (Incremental). X is the camera model of your choice. See the command line help.
You don t need to rerun the other one.

As said by the command line help -c on IncrementalSfm allow to Say if You want to refine camera intrinsic or not.

**Comment by lulu1315** [comment]
great.thank you Pierre
