### ISSUE TITLE
can't run openMVG

### ISSUE THREAD

**Issue by saimon86** [openMVG/openMVG#449]
Hi!
Recently I installedl openMVG in a virtual machine (virtualbox 5) with ubuntu 14.04. The file ".vdi" is located inside an external hd (exfat). For the installation of openMVG I used this tutorial:
https://travis-ci.org/openMVG/openMVG

The installation seems to be OK (there are no differences between the tutorial and my installation), BUT when I decide to run the first  sfm pipeline step:
"openMVG_main_SfMInit_ImageListing -d /home/user/Dev/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i /home/user/Dataset/ImageDataset_SceauxCastle/images -o /home/user/Dataset/ImageDataset_SceauxCastle/matches"

Ubuntu tell me "openMVG_main_SfMInit_ImageListing: command not found"

I know that probably is a stupid problem but I don't know what to do..Could someone help me?

Thank you

Simone

**Comment by ORNis** [comment]
Hi simone
The command is not in your PATH. just go into your OpenMVG build directory and type ‘sudo make install‘. It should do the job.
Regards,
Romain

**Comment by saimon86** [comment]
Thank you so much Romain! It works
But now there's a new problem! I have to build also the MVS part! (ahahahah...next days a new challenge awaiting me)
Thank you again...
Simone

**Comment by pmoulon** [comment]
For MVS, please do the same, if you have some troubles, feel free to ask questions.
