### ISSUE TITLE
openMVS----> building (problems with MESA and openMVS)

### ISSUE THREAD

**Issue by saimon86** [openMVG/openMVG#451]
Here I am!
Hi, I'm Simone
Now I'm building openMVS. 
At this step:
"#MESA (Required)
sudo apt-get install mesa-dev"

Ubuntu tells me "E: impossible to find mesa-dev package"
Mmmm.. I made some on line researches, probably the problem is related to the graphic card? 

Ubuntu is running on a VirtualMachine (VirtualBox5).
The VirtualMachine is installed on a MacBook Pro Retina (mid 2012), 2,6 GHz Intel Core i7.
Inside the Mac there are 2 graphic cards (intel HD Graphics 4000 and NVIDIA GeForce GT 650M)

So, in my situation I have to install both intel and nvidia graphic card drivers?

Thank's a lot

Simone

**Comment by saimon86** [comment]
..and these are the problems with openMVS:

1- CUDA
2- VCG
3 -- Configuring incomplete, errors occurred!
See also "/home/simone/openMVS_Build/CMakeFiles/CMakeOutput.log".

thank's a lot for helping me..

Simone



this is the code:

simone@simone-VirtualBox:~/openMVS_Build$ cmake . ../openMVS -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$main_path/vcglib" -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected version of GNU GCC: 48 (408)
CMake Warning (dev) at build/Utils.cmake:238 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CMAKE_COMPILER_IS_GNUCXX" will no longer be
  dereferenced when the policy is set to NEW.  Since the policy is not set
  the OLD behavior will be used.
Call Stack (most recent call first):
  build/Utils.cmake:378 (add_option)
  build/Utils.cmake:733 (optimize_default_compiler_settings)
  CMakeLists.txt:35 (ConfigCompilerAndLinker)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_HAS_CXX11_FLAG
-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
-- Performing Test HAVE_CXX_STD_C++11
-- Performing Test HAVE_CXX_STD_C++11 - Success
-- Performing Test HAVE_C_STD_C++11
-- Performing Test HAVE_C_STD_C++11 - Failed
-- Performing Test HAVE_CXX_W
-- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
-- Performing Test HAVE_C_W - Success
-- Performing Test HAVE_CXX_WALL
-- Performing Test HAVE_CXX_WALL - Success
-- Performing Test HAVE_C_WALL
-- Performing Test HAVE_C_WALL - Success
-- Performing Test HAVE_CXX_WERROR_ADDRESS
-- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
-- Performing Test HAVE_C_WERROR_ADDRESS
-- Performing Test HAVE_C_WERROR_ADDRESS - Success
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
-- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
-- Performing Test HAVE_CXX_WFORMAT
-- Performing Test HAVE_CXX_WFORMAT - Success
-- Performing Test HAVE_C_WFORMAT
-- Performing Test HAVE_C_WFORMAT - Success
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
-- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
-- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES
-- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WINIT_SELF
-- Performing Test HAVE_CXX_WINIT_SELF - Success
-- Performing Test HAVE_C_WINIT_SELF
-- Performing Test HAVE_C_WINIT_SELF - Success
-- Performing Test HAVE_CXX_WSIGN_PROMO
-- Performing Test HAVE_CXX_WSIGN_PROMO - Success
-- Performing Test HAVE_C_WSIGN_PROMO
-- Performing Test HAVE_C_WSIGN_PROMO - Failed
-- Performing Test HAVE_CXX_WNO_UNDEF
-- Performing Test HAVE_CXX_WNO_UNDEF - Success
-- Performing Test HAVE_C_WNO_UNDEF
-- Performing Test HAVE_C_WNO_UNDEF - Success
-- Performing Test HAVE_CXX_WNO_COMMENT
-- Performing Test HAVE_CXX_WNO_COMMENT - Success
-- Performing Test HAVE_C_WNO_COMMENT
-- Performing Test HAVE_C_WNO_COMMENT - Success
-- Performing Test HAVE_CXX_WNO_NARROWING
-- Performing Test HAVE_CXX_WNO_NARROWING - Success
-- Performing Test HAVE_C_WNO_NARROWING
-- Performing Test HAVE_C_WNO_NARROWING - Success
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES
-- Performing Test HAVE_CXX_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_C_WNO_ATTRIBUTES
-- Performing Test HAVE_C_WNO_ATTRIBUTES - Success
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE
-- Performing Test HAVE_CXX_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_C_WNO_ENUM_COMPARE
-- Performing Test HAVE_C_WNO_ENUM_COMPARE - Success
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS
-- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS - Success
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES - Failed
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES
-- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES - Success
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_CXX_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS
-- Performing Test HAVE_C_WNO_MISSING_FIELD_INITIALIZERS - Success
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAVE_C_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
-- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_CXX_FTEMPLATE_BACKTRACE_LIMIT_0 - Success
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0
-- Performing Test HAVE_C_FTEMPLATE_BACKTRACE_LIMIT_0 - Failed
-- Performing Test HAVE_CXX_WNO_LONG_LONG
-- Performing Test HAVE_CXX_WNO_LONG_LONG - Success
-- Performing Test HAVE_C_WNO_LONG_LONG
-- Performing Test HAVE_C_WNO_LONG_LONG - Success
-- Performing Test HAVE_CXX_PTHREAD
-- Performing Test HAVE_CXX_PTHREAD - Success
-- Performing Test HAVE_C_PTHREAD
-- Performing Test HAVE_C_PTHREAD - Success
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
-- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER
-- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
-- Performing Test HAVE_CXX_FROUNDING_MATH
-- Performing Test HAVE_CXX_FROUNDING_MATH - Success
-- Performing Test HAVE_C_FROUNDING_MATH
-- Performing Test HAVE_C_FROUNDING_MATH - Success
-- Performing Test HAVE_CXX_MSSE
-- Performing Test HAVE_CXX_MSSE - Success
-- Performing Test HAVE_C_MSSE
-- Performing Test HAVE_C_MSSE - Success
-- Performing Test HAVE_CXX_MSSE2
-- Performing Test HAVE_CXX_MSSE2 - Success
-- Performing Test HAVE_C_MSSE2
-- Performing Test HAVE_C_MSSE2 - Success
-- Performing Test HAVE_CXX_MSSE3
-- Performing Test HAVE_CXX_MSSE3 - Success
-- Performing Test HAVE_C_MSSE3
-- Performing Test HAVE_C_MSSE3 - Success
-- Performing Test HAVE_CXX_MSSSE3
-- Performing Test HAVE_CXX_MSSSE3 - Success
-- Performing Test HAVE_C_MSSSE3
-- Performing Test HAVE_C_MSSSE3 - Success
-- Performing Test HAVE_CXX_MSSE4_1
-- Performing Test HAVE_CXX_MSSE4_1 - Success
-- Performing Test HAVE_C_MSSE4_1
-- Performing Test HAVE_C_MSSE4_1 - Success
-- Performing Test HAVE_CXX_MSSE4_2
-- Performing Test HAVE_CXX_MSSE4_2 - Success
-- Performing Test HAVE_C_MSSE4_2
-- Performing Test HAVE_C_MSSE4_2 - Success
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS
-- Performing Test HAVE_CXX_FFUNCTION_SECTIONS - Success
-- Performing Test HAVE_C_FFUNCTION_SECTIONS
-- Performing Test HAVE_C_FFUNCTION_SECTIONS - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
-- Eigen 3.2.0 found (include: /usr/include/eigen3)
-- OpenCV 2.4.8 found (include: /usr/include/opencv;/usr/include;/usr/share/OpenCV/include)
-- CGAL found (include: /usr/include)
CMake Error at build/Utils.cmake:213 (message):
  VCG required, but not found: Please specify VCG directory using VCG_ROOT
  env.  variable
Call Stack (most recent call first):
  build/Modules/FindVCG.cmake:23 (package_report_not_found)
  libs/MVS/CMakeLists.txt:9 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/simone/openMVS_Build/CMakeFiles/CMakeOutput.log".

**Comment by pmoulon** [comment]
CUDA is not a problem. It's on optional dependency.
Regarding VCG you have to download it and set the VCG_ROOT variable to the directory.

Here the step by step command line https://github.com/OpenMVS/openMVS/wiki/Building#linux-compilation

**Comment by saimon86** [comment]
I'm sorry if you are loosing your time with my troubles.
I would like to use openMVG for my archaeological research and building this software is also a challenge for me...

I installed VCG using this code, following the same link that you gave me
#VCGLib (Required)
sudo apt-get install subversion
svn checkout svn://svn.code.sf.net/p/vcg/code/trunk/vcglib vcglib


My problem is that I don't know what to do with this peace of code:


Index: vcg/complex/algorithms/clean.h
===================================================================
--- vcg/complex/algorithms/clean.h  (revision 5553)
+++ vcg/complex/algorithms/clean.h  (working copy)
@@ -452,7 +452,7 @@
     return count_removed;
   }

-  static int SplitSelectedVertexOnEdgeMesh(MeshType& m)
+  static void SplitSelectedVertexOnEdgeMesh(MeshType& m)
   {
     tri::RequireCompactness(m);
     tri::UpdateFlags<MeshType>::VertexClearV(m);
Index: vcg/complex/algorithms/hole.h
===================================================================
--- vcg/complex/algorithms/hole.h   (revision 5553)
+++ vcg/complex/algorithms/hole.h   (working copy)
@@ -98,6 +98,7 @@
     ComputeQuality();
     ComputeAngle();
   }
+  virtual ~TrivialEar() {}

   /// Compute the angle of the two edges of the ear.
   // it tries to make the computation in a precision safe way.

**Comment by pmoulon** [comment]
The --- and +++ show where there is somes changes to do.
Compare the line and you will see some tiny difference (int void ...).

**Comment by saimon86** [comment]
ok! now I have understand!
using "ctrl+F" inside gedit I found immediately the peace of code...
thank you

In the first mail of this issue I asked you about this command:

cmake . ../openMVS -DCMAKE_BUILD_TYPE=RELEASE -DVCG_DIR="$main_path/vcglib" -DCERES_DIR="/usr/local/share/Ceres" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF


Ubuntu tells me:
-- Configuring incomplete, errors occurred!
See also "/home/simone/openMVS_Build/CMakeFiles/CMakeOutput.log".

**Comment by morgand536** [comment]
I have the same situation too.
I got errors of "Could Not find CUDA" and "VCG required" when i followed the steps of cmake for openMVS.

I have done the edits for clean.h & hole.h.

Anyone can help? Thanks!

**Comment by pmoulon** [comment]
Are you sure that the variable $main_path have been set to the right value?

**Comment by dxqxiaoqiang** [comment]
did you have solved your question  ? I meet with the same question as you . @saimon86

**Comment by gezabohus** [comment]
The problem is that the cmake command line explicitly says -DVCG_DIR="~/vcglib". Change that to your actual value.
