### ISSUE TITLE
[Documentation] option -c for openMVG_main_GlobalSfM

### ISSUE THREAD

**Issue by mad-de** [openMVG/openMVG#455]
Currently testing the extra options to include into the gui.
When calling openMVG_main_GlobalSfM with -c [1-3] this results in: "Unrecognized option -c"

The documentation however states, that such an option exists (http://openmvg.readthedocs.org/en/latest/software/SfM/GlobalSfM/). 

The source file is actually only catching:
  cmd.add( make_option('i', sSfM_Data_Filename, "input_file") );
  cmd.add( make_option('m', sMatchesDir, "matchdir") );
  cmd.add( make_option('o', sOutDir, "outdir") );
  cmd.add( make_option('r', iRotationAveragingMethod, "rotationAveraging") );
  cmd.add( make_option('t', iTranslationAveragingMethod, "translationAveraging") );
  cmd.add( make_option('f', bRefineIntrinsics, "refineIntrinsics") );

Catch it or remove it from the docs?

cheers!

**Comment by pmoulon** [comment]
Hi  @mad-de,
Thanks, you are right. I must update the doc... It was done due to a fast copy paste from the IncrementalSfM pipeline...
