### ISSUE TITLE
[sfm/pipelines/global] Reduce multithread overhead when computing relative triplet of translations

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#456]
- Use a vector per thread to store the computed triplet of relative translations.
-> It reduces a bit the critical sections size.

- make triplet - matches graph intersection test simpler

**Comment by igorti** [comment]
That seems to have fixed the issue when running many threads(8) on large datasets. GlobalSfM was crashing with Segmentation Fault, but works fine with your latest changes. Thanks!

**Comment by pmoulon** [comment]
@igorti Thanks for your feedback.
Happy to see that you tested the modification.
Any feedback is appreciated and valuable!
