### ISSUE TITLE
missing stlplus in CMakeLists.txt in src/OpenMVG/features

### ISSUE THREAD

**Issue by ThGravo** [openMVG/openMVG#458]
Last line should IMHO be:
UNIT_TEST(openMVG features "openMVG_features;stlplus")

not:
UNIT_TEST(openMVG features "openMVG_features")

This way I can build and run the tests successfully.

**Comment by pmoulon** [comment]
Thanks for the reporting.
Which platform and compiler are you using?

**Comment by ThGravo** [comment]
Gentoo 64bit with gcc 5.3.0

**Comment by pmoulon** [comment]
Should be fixed in develop branch.
