### ISSUE TITLE
problem with modified .json

### ISSUE THREAD

**Issue by lulu1315** [openMVG/openMVG#459]
hello
I'm trying to modify the sfm_data.json generated by openMVG to update resolutions in the file.
I'm using perl with the PERL:JSON module

but when I try to reuse it with openMVG_main_ExportUndistortedImages for example
I have this error.
rapidjson internal assertion failure: flags_ & kUintFlag

the new json file is correct in syntax but not 'exactly' identical
for ex : 
```
"views": [
        {
            "key": 0,
            "value": {
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "/",
                        "filename": "000118800_15821618907.jpg",
                        "width": 776,
                        "height": 1024,
                        "id_view": 0,
                        "id_intrinsic": 13,
                        "id_pose": 0
                    }
                }
            }
        }
```

becomes

```
  "views" : [
      {
         "value" : {
            "ptr_wrapper" : {
               "data" : {
                  "filename" : "000118800_15821618907.jpg",
                  "width" : "300",
                  "id_intrinsic" : 13,
                  "id_view" : 0,
                  "local_path" : "/",
                  "height" : "396",
                  "id_pose" : 0
               },
               "id" : 2147483649
            }
         },
         "key" : 0
      },
```

could this be the problem ?
thanks in advance
luc

**Comment by pmoulon** [comment]
Have you tried simply to do a search and replace thanks to a text editor:
"width": 776, => "width" : "300",
So no json parser will be need, only substring conversion.

**Comment by lulu1315** [comment]
well unfortunately I'm doing a lot of thing inside the json and found it more convenient to work this way..

**Comment by pmoulon** [comment]
ok,
I don't know why the json parser is not doing the right job when you exporting it back.

Way to do it could be:
- text parsing and replace (it can solve all your data conversion). With a simple script you can perform it.
- use OpenMVG library to read the json and you modify your value by using C++.

**Comment by lulu1315** [comment]
thank you.I will try that.

**Comment by pmoulon** [comment]
Can you close the issue once you have found a solution?

**Comment by lulu1315** [comment]
ok I got it . width and height came out  as a string "width" : "300".
force it as an int :  "width" : 300 and it works.thanks

**Comment by pmoulon** [comment]
Was happy you find it, I didn't notice it too.
Will you share some of your results of your reconstruction here or on G+ "#openmvg"?

**Comment by lulu1315** [comment]
as soon as I got something that works :)...

**Comment by pmoulon** [comment]
Don't hesitate to ask help on the mailing list openmvg-team[AT]googlegroups.com
