### ISSUE TITLE
[continuous integration] Setup an Appveyor CI

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#466]
Allow to perform continuous integration compilation on Visual Studio.
- run compilation with Visual Studio 2015
  - [x] x64
  - [x] x86

**Comment by pmoulon** [comment]
@rhiestan 
When you have compiled OpenMVG on minGW:
- what was the command line you have used?
- did you encounter some problems?

**Comment by pmoulon** [comment]
Note: Microsoft Visual Studio CTP1 have an internal compiler error on Eigen GeneralMatrixMatrix.h when EIGEN_HAS_OPENMP is ON.
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1096#c4
An update is then required

**Comment by rhiestan** [comment]
I haven't compiled OpenMVG separately with MinGW for a while, only within Regard3D. The last time I tried was pretty straightforward, no problems. My CMake-command looks something like this:
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_VERBOSE_MAKEFILE=FALSE -DMSYS=TRUE -DUSE_SSE2=TRUE -DTARGET_ARCHITECTURE="generic" -DZLIB_ROOT=$ZLIB_ROOT -DPNG_PNG_INCLUDE_DIR=$PNG_PNG_INCLUDE_DIR -DPNG_LIBRARY=$PNG_LIBRARY -DTIFF_INCLUDE_DIR=$TIFF_INCLUDE_DIR -DTIFF_LIBRARY=$TIFF_LIBRARY -DJPEG_INCLUDE_DIR=$JPEG_INCLUDE_DIR -DJPEG_LIBRARY=$JPEG_LIBRARY -DEIGEN3_INCLUDE_DIR=$EIGEN3_INCLUDE_DIR ../openMVG-0.9/src

Of course I set the library paths beforehand.
