### ISSUE TITLE
path of .feat files (bug or not documented?)

### ISSUE THREAD

**Issue by micheleAlberto** [openMVG/openMVG#472]
I used the following directory structure

images/ : a folder full of images in jpg format, images/*.jpg
data/ : 
data/*.feat  point feature files provided by openmvg
data/*.desc feature descriptor files provided by openmvg
data/sfm_data.json structure from motion data file
data/matches.f.txt matches file provided by openmvg
data/matches/matches.f.txt my matches file (that i would like to use instead of the former)

running
```
openMVG_main_IncrementalSfM -i data/sfm_data.json -m data/matches -o data/matches
```
result in a segmentation fault
Using gdb i verified that the coordinates of openMVG::features::PointFeature were not itnitialized ( wild, random floating point numbers that change each run) and this caused an error executing :
```
Vec2 feat = _features_provider->feats_per_view[I][i].coords().cast<double>();
```
in sequential_SfM.cpp in method AutomaticInitialPairChoice(..)

I found that in main_IncrementalSfM.cpp (line 123)
```
  // Features reading
  std::shared_ptr<Features_Provider> feats_provider = std::make_shared<Features_Provider>();
  if (!feats_provider->load(sfm_data, sMatchesDir, regions_type)) {
    std::cerr << std::endl
      << "Invalid features." << std::endl;
    return EXIT_FAILURE;
  }

```
Features are loaded from the directory of the matches, and not, as i would have expected, from a path relative to the sfm_data.json file. 

The relevant documentation :
```
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

Usage: openMVG_main_IncrementalSfM
[-i|--input_file] path to a SfM_Data scene
[-m|--matchdir] path to the matches that corresponds to the provided SfM_Data scene
[-o|--outdir] path where the output data will be stored
```

**Comment by pmoulon** [comment]
I @micheleAlberto ,
It's how OpenMVS has been designed. It loads features from the matchdir and not relative to the sfm_data path.
The directory structure look like
images
matches => place where initial sfm_data.json and features and matches are stored.
reconstruction => place where the sfm reconstruction files will be saved.

**Comment by micheleAlberto** [comment]
Ok , so it s a request for a line of documentation and some explicit error like "Missing feature file __something__.feat . Trust me : it can save hours.

**Comment by pmoulon** [comment]
I think that the develop branch reporting is better.
=> https://github.com/openMVG/openMVG/issues/454
Can you try it?

**Comment by micheleAlberto** [comment]
Ok , i' ll let you know

**Comment by micheleAlberto** [comment]
It prints 
```
Invalid feature files for the view: __something__.jpg
```

**Comment by pmoulon** [comment]
So a warning message is displayed.
Have you tried to use directly the python script that are provided in software/SfM?
https://openmvg.readthedocs.org/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo
=> Sequential or Global pipeline

**Comment by micheleAlberto** [comment]
yes , i did, no problem on that. 
I am working on the association (keypoint feature <-> tracks) problem but openmvg has no external file to describe tracks before sfm optimization so i compute my tracks and then export it as a chain of pairwise matches in matches.f.txt , and that is why i have a custom match file.
I see from other issues you are considering to rewrite the unordered tracking part to avoid using the union find algorithm of the lemon library. 
If you do i suggest to consider having an external file to decouple tracking from sfm optimization.
Something on the lines of : 
```
openMVG_main_UnorderedTracking -i data/sfm_data.json -m data -o data/tracks.txt
openMVG_main_IncrementalSfM -i data/sfm_data.json -t data/tracks.txt -o data
```
instead of 
```
openMVG_main_IncrementalSfM -i data/sfm_data.json -m data -o data
```

File tracks.txt store the same informations of STLMAPTracks and may be represented in two alternative formats indexed by track or by feature. 
```cpp
// Data structure to store a track: collection of {ImageId,FeatureId}
//  The corresponding image points with their imageId and FeatureId.
typedef std::map<size_t,size_t> submapTrack;
// A track is a collection of {trackId, submapTrack}
typedef std::map< size_t, submapTrack > STLMAPTracks;
```
In the former case each line of the file describe a track (the one i prefer):
```
<track_id> <image_id> <feat_id> <image_id> <feat_id> <image_id> <feat_id> ... \n
```
In the latter case:
```
<image_id> <feat_id> <track_id> \n
```
I am doing this sort of thing (in python) to observe tracks and their mistakes before structure from motion estimation and i could not find any structure from motion software that exposed this intermediate representation.

**Comment by pmoulon** [comment]
A fast way to integrate your format inside the existing pipeline is to modify it.
During IncrementalSfM if a data/tracks.txt exists you load yours.

BTW, if you export your own pairwise relationship, the tracks build by OpenMVG will be the same later on, so there is not problem.

We can also later to add an interface that will load tracks if they are existing.
As features & matches have some provider, tracks can be have a custom interface that could be customized.

OpenMVG pipeline remains high level to be as generic as possible.
Some pipelines need tracks as input, but some other can create the tracks during the process, that's why there is no track file as input.
