### ISSUE TITLE
CMake Error in Windows for OpenMVG_DIR

### ISSUE THREAD

**Issue by morgand536** [openMVG/openMVG#473]
I am trying to install OpenMVG + OpenMVS in Windows 10 + VS2013.
However, when i was in the last step of cmaking the openMVS, i got this error and i could not get rid of it:

_CMake Error at C:/openMVG/bin/install/share/openMVG/cmake/OpenMVGTargets.cmake:34 (message):
Some (but not all) targets in this export set were already defined.

Targets Defined: zlib

Targets not yet defined:
lib_CoinUtils;lib_Osi;lib_clp;lib_OsiClpSolver;stlplus;lemon;jpeg;png;tiff;cxsparse;ceres;flann_cpp_s;easyexif;openMVG_features;openMVG_image;openMVG_lInftyComputerVision;openMVG_matching;openMVG_kvld;openMVG_matching_image_collection;openMVG_multiview;openMVG_numeric;openMVG_system;openMVG_sfm;vlsift

Call Stack (most recent call first):
C:/openMVG/bin/install/share/openMVG/cmake/OpenMVGConfig.cmake:96 (INCLUDE)
apps/InterfaceOpenMVG/CMakeLists.txt:1 (FIND_PACKAGE)_

The configuring was incomplete and i could not generate the .sln.

**Comment by pmoulon** [comment]
Can you tell when you have the error?
-> When you run cmake for OpenMVS?

**Comment by pmoulon** [comment]
any feedback @morgand536

**Comment by morgand536** [comment]
Currently working on Linux build.
Will try again in next week in Windows and will let you know any issue.
Thanks. 😃

On Thu, Feb 25, 2016 at 6:17 PM, Pierre Moulon <notifications@github.com>
wrote:

> any feedback @morgand536 <https://github.com/morgand536>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openMVG/openMVG/issues/473#issuecomment-188706946>.
>



-- 
Cheers,
Morgan

**Comment by morgand536** [comment]
By the way I have another issue when i successfully built the openMVG alone:
I kept getting break point error when i try to run the UI Qt app:
`HEAP[ui_openMVG_control_points_registration.exe]: Invalid address specified to RtlFreeHeap( 00AB0000, 0262B920 )`
The app is still functional if i continue the break point.

**Comment by pmoulon** [comment]
Thanks for the feedback. Don't know if it's a QT related error or an OpenMVG one.
Perhaps it's worth investigating to run it in debug mode ...

**Comment by morgand536** [comment]
When i try to use debug mode Win32:

> HEAP[ui_openMVG_control_points_registration.exe]: Invalid address specified to RtlValidateHeap( 011F0000, 028B4160 )

**Comment by pmoulon** [comment]
Ok, it does not stop on any OpenMVG c++ line.

**Comment by morgand536** [comment]
I use Qt Open Source 4.8.6 in case you want to know.

**Comment by pmoulon** [comment]
Thanks for the feedback.
I think we don't have to worry about the error since the process is working if you continue.
