### ISSUE TITLE
[question] Using EXR / HDR as input files ? 

### ISSUE THREAD

**Issue by stephane-lb** [openMVG/openMVG#476]
Good afternoon everyone,

I would like to know if anyone made any tests to use EXR or other kind of HDR image to rebuild an asset ?
Is that something do able ? Or  does the main strategy should be to use one exposure, and then interpolate the texture ?

I think that would be really interesting, because you are working on fisheye camera, so why we should not get 3D environment map for example or to acquire material/BRDF from asset ?

Thanks for your replies,

Have a great day,

Stephane

**Comment by pmoulon** [comment]
Hi @stephane-lb 
OpenMVG supports only 8bit image as input.

But using tonemapped HDR/EXR images as input can help, since it will help to recover some feature point in dark and bright area.

So the workflow I would like to recommend would be:
- Capture your HDR images
- Tone mapped them and run SFM and compute your mesh
- Use an external software to project your HDR images on the mesh

**Comment by stephane-lb** [comment]
Hi @pmoulon ,

Thanks for replying, you completely confirmed what I was thinking thank you very much. By external software, are you suggesting Mari ? I read somewhere about something like MayaMVG, do you have project like MariMVG ?

I know that you are exploring reconstruction using fisheyes, do you think the setup could be used with LatLong/EnvMap ? 

( Just to clarify, sometimes we used 6 pictures to create an EnvMap - top, bottom, left, right, front, back - Do you think that would be enough to produce RGB EnvMap ? ) 

All the best,

Stephane

**Comment by autosquid** [comment]
@stephane-lb  Is it possible that a feature extract runs directly on HDR images performs better than first tone-mapping HDR to plain 8 bits images?

**Comment by stephane-lb** [comment]
@autosquid I don't know, that was my initial question, I supposed that by using HDR you might be able to find better / more interesting points ( specially in high/low intensity) ... 

@pmoulon do you think it would be hard to patch openMVG to be able to use EXR as input ? Do you know if the features extraction algorithm will support EXR ?

**Comment by pmoulon** [comment]
@autosquid @stephane-lb Academic paper lack of experience report about using HDR imagery to perform photogrammetry.

The particular thing that I see is that SIFT have been developed to run on 8 bit dynamic range and so perhaps some threshold are adapted for this range and not for a larger one.
But we can try to use 32 bits images for which we compress the 32 bit range to [0.0;1.0] in a linear manner, just to see if interesting new keypoints are detected or not.

@stephane-lb Adding support for EXR for OpenMVG would not be hard.
You have to add detect openEXR (+imlbase?) as third party library and write a new image_io module for EXR files. => https://github.com/openMVG/openMVG/blob/develop/src/openMVG/image/image_io.hpp#L16

**Comment by ORNis** [comment]
From my experience, in dense correlation phase, working with higher dynamic can improve the result... it could be helpful but the improvement is not dramatic. As @pmoulon stated tone mapping is a good way to get informations from highlights and dark areas, it can be critical in some configurations.

**Comment by stephane-lb** [comment]
@pmoulon Thanks to you I just discovered "Learning Covariant Feature Detectors", that looks to be a good answer to be able to use EXR. Could you confirm that please ?
