### ISSUE TITLE
OpenMVG should not require camera sensor width for SfM

### ISSUE THREAD

**Issue by Patola** [openMVG/openMVG#477]
I understand that OpenMVG intends to be as useable as possible, but really, besides streamlining the pipeline, I think it should include an algorithm for inferring the camera sensor width instead of explicitly requiring it to be provided or appended to the camera database. Many people use cellphone cameras or non-branded devices today to acquire the pictures and this data is difficult to obtain even for the most popular devices! Also, it is a whole subject that the person interested in using OpenMVG has to research before starting using the software, it's overwhelming and extremely dismotivating. Other software like 123D Catch and visualSfM do not require it.

**Comment by pmoulon** [comment]
@Patola 
The reason why I use the camera sensor width database is that when we have the knowledge of an accurate approximation of some data (focal length) it better to use it.

Some other softwares use approximate focal length, and it works often but not all the time.
For the moment I have made the choice to show to users that if a knowledge of your camera (mm focal length and camera sensor size) is important.
BTW, you can easily suppose a given lens opening and use this formula to compute the input focal length in pixels : 1.2*std::max(w,h)

See here to get the modification from an OpenMVG user: https://github.com/kaben/openMVG/commit/2b99f50f23c70c54afddac5b904e59f80925209f

See here some explanation about how to compute focal length from EXIF data:
https://github.com/pmoulon/osm-bundler/issues/14

Hoping it helps to understand the main motivation:
- show to curious people that precise focal length helps the process

**Comment by Patola** [comment]
That was a very comprehensive explanation. Thanks.

**Comment by pmoulon** [comment]
@kbellis the focal length stored in the exif data is in mm. The focal length for photogrammetry  is with another unit. You can depending of the field of view compute an approximation and specify this value by using the -f option to InitImageListing binary.  So using a focal value like 1.2 * max (width, height) will work most of the time.

**Comment by kbellis** [comment]
@pmoulon, the _sensor width_ was what the thread title above refers and was what the user is asked to provide when running openMVG that has been incorporated into Blue Marble Geographics' _Pixels to Points_ tool, and in particular, when the camera is unknown; i.e., not in the sensor_width_camera_database.

**Comment by kbellis** [comment]
Hello Pierre,
Please help me understand.
Does openMVG require the sensor width to be provided?
What should be done when the sensor width is unknown?
Thank you.
Kelly

**Comment by enzyme69** [comment]
@kbellis on app like Regard3D, we need to specify sensor width ....
