### ISSUE TITLE
problem of build OpenMVG on Windows with VS 2013

### ISSUE THREAD

**Issue by xialang2012** [openMVG/openMVG#480]
I built OpenMVG on Windows under https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD, but it showed the following errors:
![20160225155423](https://cloud.githubusercontent.com/assets/14291651/13313381/67d17ac4-dbd8-11e5-93d7-8043ad26c17b.png)

and below were some of the outputs:
>61>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
46>     Creating library C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_evalQuality.lib and object C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_evalQuality.exp
39>     Creating library C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ExportCameraFrustums.lib and object C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ExportCameraFrustums.exp
63>     Creating library C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ConvertList.lib and object C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ConvertList.exp
62>     Creating library C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ComputeStructureFromKnownPoses.lib and object C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ComputeStructureFromKnownPoses.exp
63>  openMVG_main_ConvertList.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_main_ConvertList.exe
46>  openMVG_main_evalQuality.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_main_evalQuality.exe
39>  openMVG_main_ExportCameraFrustums.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_main_ExportCameraFrustums.exe
56>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
54>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
45>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
57>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
59>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
60>     Creating library C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ComputeMatches.lib and object C:/Users/DELL/Desktop/ODM-depends/openMVG/build-win/Windows-AMD64-Release/Debug/openMVG_main_ComputeMatches.exp
62>  openMVG_main_ComputeStructureFromKnownPoses.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_main_ComputeStructureFromKnownPoses.exe
60>  openMVG_main_ComputeMatches.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_main_ComputeMatches.exe
55>  Generating Code...
55>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
58>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_image.lib'
64>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
64>  Building Custom Rule C:/Users/DELL/Desktop/ODM-depends/openMVG/src/CMakeLists.txt
64>  CMake does not need to re-run because C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\CMakeFiles\generate.stamp is up-to-date.
========== Build: 38 succeeded, 26 failed, 0 up-to-date, 0 skipped ==========

**Comment by pmoulon** [comment]
Can you check that the JPEG library that is used is the one from OpenMVG?
- right click on jpeg_std_error and go to declaration => Check it show a file contained in OpenMVG source folder.
It must open the file openMVG/src/third_party/jpeg/jpeglib.h

Can you share also the CMAKE output when you run configure from scratch?

**Comment by xialang2012** [comment]
Yes, the JPEG library used is not the openMVG/src/third_party/jpeg/jpeglib.h, I have changed it in Cmake OpenMVG_INCLUDE_DIRS to 
>C:\Users\DELL\Desktop\ODM-depends\openMVG\src\third_party\jpeg


But it also showed me some errors when I built the openMVG_image only, as below:

> 1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
> 2>------ Build started: Project: openMVG_numeric, Configuration: Debug x64 ------
> 2>  openMVG_numeric.vcxproj -> C:\Users\DELL\Desktop\ODM-depends\openMVG\build-win\Windows-AMD64-Release\Debug\openMVG_numeric.lib
> 3>------ Build started: Project: openMVG_image, Configuration: Debug x64 ------
> 3>  image_io.cpp
> 3>C:\Users\DELL\Desktop\ODM-depends\openMVG\src\openMVG/image/sample.hpp(351): warning C4244: 'return' : conversion from 'const openMVG::image::RealPixel<float>::real_type' to 'openMVG::image::RealPixel<float>::base_type', possible loss of data
> 3>C:\Users\DELL\Desktop\ODM-depends\openMVG\src\openMVG/image/image_filtering.hpp(291): warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss of data
> 3>C:\Users\DELL\Desktop\ODM-depends\openMVG\src\third_party\jpeg\jpeglib.h(25): fatal error C1083: Cannot open include file: 'jconfig.h': No such file or directory
> ========== Build: 2 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

The original (without revise jpeg path) Cmake output is as following 

> The C compiler identification is MSVC 18.0.31101.0
> The CXX compiler identification is MSVC 18.0.31101.0
> Check for working C compiler using: Visual Studio 12 2013 Win64
> Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
> Detecting C compiler ABI info
> Detecting C compiler ABI info - done
> Check for working CXX compiler using: Visual Studio 12 2013 Win64
> Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> target changed from "" to "auto"
> Detected: Vendor ID 'GenuineIntel'   CPU Family '6'  CPU Model '63'  CPU Flags  ''
> Detected CPU: sandy-bridge
> Performing Test check_c_compiler_flag__arch_AVX
> Performing Test check_c_compiler_flag__arch_AVX - Success
> Performing Test check_cxx_compiler_flag__arch_AVX
> Performing Test check_cxx_compiler_flag__arch_AVX - Success
> Checking for C++11 compiler
> Checking for C++11 compiler - available
> CMake Warning (dev) at cmakeFindModules/CXX11.cmake:21 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "MSVC" will no longer be dereferenced when the policy
>   is set to NEW.  Since the policy is not set the OLD behavior will be used.
> Call Stack (most recent call first):
>   CMakeLists.txt:104 (enable_cxx11)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> Looking for C++ include thread
> Looking for C++ include thread - found
> Looking for C++ include chrono
> Looking for C++ include chrono - found
> Try OpenMP C flag = [/openmp]
> Performing Test OpenMP_FLAG_DETECTED
> Performing Test OpenMP_FLAG_DETECTED - Success
> Try OpenMP CXX flag = [/openmp]
> Performing Test OpenMP_FLAG_DETECTED
> Performing Test OpenMP_FLAG_DETECTED - Success
> Found OpenMP: /openmp  
> -- Did not find MOSEK header
> -- Did not find MOSEK library
> Could not find mosek library on this machine.
> Eigen 3.2.4 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/third_party/eigen)
> Flann 1.8.4 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/third_party/flann/src/cpp/flann)
> CoinUtils 2.9.3 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/dependencies/osi_clp/CoinUtils/src)
> Clp 1.15.11 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/dependencies/osi_clp/Clp/src)
> Osi 0.106.10 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
> Lemon  found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/third_party/lemon/lemon)
> Found PythonInterp: C:/Python27/python.exe (found version "2.7.11") 
> Could NOT find Wget (missing:  WGET_EXECUTABLE) 
> Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
> Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE) 
> Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
> Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
> Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
> Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
> Looking for sys/types.h
> Looking for sys/types.h - found
> Looking for stdint.h
> Looking for stdint.h - found
> Looking for stddef.h
> Looking for stddef.h - found
> Check size of long long
> Check size of long long - done
> Looking for pthread.h
> Looking for pthread.h - not found
> Found Threads: TRUE  
> Eigen 3.2.4 found (include: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/third_party/eigen)
> -- Found Eigen version 3.2.4: C:/Users/DELL/Desktop/ODM-depends/openMVG/src/third_party/eigen
> 
>    ===============================================================
>    Disabling the use of Eigen as a sparse linear algebra library.
>    This does not affect the covariance estimation algorithm 
>    which can still use the EIGEN_SPARSE_QR algorithm.
>    ===============================================================
> 
> A library with BLAS API not found. Please specify library location.
> LAPACK requires BLAS
> -- Did not find LAPACK library, disabling LAPACK support.
> -- Did not find BLAS library, disabling LAPACK support.
> -- Building without SuiteSparse.
> -- Google Flags disabled; no tests or tools will be built!
> -- Compiling minimal glog substitute into Ceres.
> -- Using minimal glog substitute (include): internal/ceres/miniglog
> -- Building with OpenMP.
> Looking for C++ include unordered_map
> Looking for C++ include unordered_map - found
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
> Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
> -- Found unordered_map/set in std namespace.
> Looking for C++ include memory
> Looking for C++ include memory - found
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
> Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
> -- Found shared_ptr in std namespace using <memory> header.
> -- Building Ceres as a static library.
> Enabling CERES_NO_LAPACK in Ceres config.h
> Enabling CERES_NO_SUITESPARSE in Ceres config.h
> Enabling CERES_USE_OPENMP in Ceres config.h
> Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
> -- Do not build any example.
> CMake Warning (dev) at third_party/flann/CMakeLists.txt:18 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "MSVC" will no longer be dereferenced when the policy
>   is set to NEW.  Since the policy is not set the OLD behavior will be used.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at third_party/flann/CMakeLists.txt:22 (if):
>   Policy CMP0054 is not set: Only interpret if() arguments as variables or
>   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   Quoted variables like "MSVC" will no longer be dereferenced when the policy
>   is set to NEW.  Since the policy is not set the OLD behavior will be used.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> 
> Configured Eigen 3.2.4
> 
> Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
> Sphinx need to be installed to generate the documentation
> 
> 
> ** OpenMVG version: 0.8.1
> ** Build Shared libs: OFF
> ** Build OpenMVG tests: OFF
> ** Build OpenMVG documentation: ON
> ** Build OpenMVG samples applications: ON
> ** Build OpenMVG openGL examples: OFF
> ** Enable code coverage generation: OFF
> ** Enable OpenMP parallelization: ON
> ** Build OpenCV+OpenMVG samples programs: OFF
> ** Use OpenCV SIFT features: OFF
> 
> 
> EIGEN: 3.2.4 (internal)
> CERES: 1.10.0 (internal)
> FLANN: 1.8.4 (internal)
> LIBTIFF: 3.8.2 (external)
> LIBPNG:  (internal)
> LIBJPEG (external)
> CLP: 1.15.11 (internal)
> COINUTILS: 2.9.3 (internal)
> OSI: 0.106.10 (internal)
> LEMON: 1.3 (internal)
> 
> 
> Configuring done

**Comment by pmoulon** [comment]
Thanks for the reports @xialang2012 

From what I see even when you said that you started from a clean build (no previous cmake run), OpenMVG try to use an external LIBTIFF and JPEG library and not the included one.
That's why there is a compilation error, openMVG expect to have a given version of Libjpeg and your machine already contained another one.
I think you already have a libjpeg and a libtiff in your windows path.

You can try to force to use internal libraries by commenting those three lines in the main CMakeLists.txt file => openMVG/src/CMakeLists.txt
```
  FIND_PACKAGE(JPEG QUIET)
  FIND_PACKAGE(PNG QUIET)
  FIND_PACKAGE(TIFF QUIET)
```

**Comment by xialang2012** [comment]
@pmoulon Now, it works well. Thank you.
