### ISSUE TITLE
Errors about building openmvg on Windows

### ISSUE THREAD

**Issue by bigsheep2012** [openMVG/openMVG#481]
I follow the steps mentioned here : https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD

Environment: 
win7 x64 + vs2013 + opencv 2.4.11

It seems my errors about the image.lib is similar to this issue:

https://github.com/openMVG/openMVG/issues/480

and I got more cannot open *.lib errors. I have checked the  Windows-AMD64-Release/Debug/ folder and do not see these lib files mentioned in the errors.

And I got errors like this after I build the .sln:

1: Error	265	error LNK2019: unresolved external symbol "void __cdecl openMVG::P_From_KRt(class Eigen::Matrix<double,3,3,0,3,3> const &,class Eigen::Matrix<double,3,3,0,3,3> const &,class Eigen::Matrix<double,3,1,0,3,1> const &,class Eigen::Matrix<double,3,4,2,3,4> *)" (?P_From_KRt@openMVG@@YAXABV?$Matrix@N$02$02$0A@$02$02@Eigen@@0ABV?$Matrix@N$02$00$0A@$02$00@3@PAV?$Matrix@N$02$03$01$02$03@3@@Z) referenced in function "public: virtual class Eigen::Matrix<double,3,4,2,3,4> __thiscall openMVG::cameras::Pinhole_Intrinsic::get_projective_equivalent(class openMVG::geometry::Pose3 const &)const " (?get_projective_equivalent@Pinhole_Intrinsic@cameras@openMVG@@UBE?AV?$Matrix@N$02$03$01$02$03@Eigen@@ABVPose3@geometry@3@@Z)	E:\SFM_Documents\OpenMVG_src\openMVG\src\build\openMVG\matching_image_collection\Cascade_Hashing_Matcher_Regions_AllInMemory.obj	openMVG_matching_image_collection

2: Error	270	error LNK2001: unresolved external symbol "public: __thiscall openMVG::features::AKAZE::AKAZE(class openMVG::image::Image<unsigned char> const &,struct openMVG::features::AKAZEConfig const &)" (??0AKAZE@features@openMVG@@QAE@ABV?$Image@E@image@2@ABUAKAZEConfig@12@@Z)	E:\SFM_Documents\OpenMVG_src\openMVG\src\build\openMVG\matching_image_collection\Matcher_Regions_AllInMemory.obj	openMVG_matching_image_collection

3: Error	642	error LNK1104: cannot open file '..\..\Windows-AMD64 Release\Debug\openMVG_features.lib'	E:\SFM_Documents\OpenMVG_src\openMVG\src\build\software\SfM\LINK	openMVG_main_ConvertList

My cmake output:

Detected: Vendor ID 'GenuineIntel'   CPU Family '6'  CPU Model '60'  CPU Flags  ''
Detected CPU: haswell
Checking for C++11 compiler
Checking for C++11 compiler - available
CMake Warning (dev) at cmakeFindModules/CXX11.cmake:21 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:104 (enable_cxx11)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Did not find MOSEK header
-- Did not find MOSEK library
Could not find mosek library on this machine.
Eigen 3.2.4 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/third_party/eigen)
Flann 1.8.4 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/third_party/flann/src/cpp/flann)
CoinUtils 2.9.3 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.15.11 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/dependencies/osi_clp/Clp/src)
Osi 0.106.10 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
Lemon 1.3 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/third_party/lemon/lemon)
OpenCV ARCH: x86
OpenCV RUNTIME: vc12
OpenCV STATIC: OFF
Found OpenCV 2.4.11 in E:/opencv_v2/opencv/build/x86/vc12/lib
You might need to add E:\opencv_v2\opencv\build\x86\vc12\bin to your PATH to be able to run your applications.
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
Could NOT find Wget (missing:  WGET_EXECUTABLE) 
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE) 
Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
Eigen 3.2.4 found (include: E:/SFM_Documents/OpenMVG_src/openMVG/src/third_party/eigen)
-- Found Eigen version 3.2.4: E:/SFM_Documents/OpenMVG_src/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Building without LAPACK.
-- Building without SuiteSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
-- Found unordered_map/set in std namespace.
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
-- Build the examples.
CMake Warning (dev) at third_party/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Configured Eigen 3.2.4

Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the documentation

** OpenMVG version: 0.8.1
** Build Shared libs: OFF
** Build OpenMVG tests: OFF
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: ON
** Use OpenCV SIFT features: ON

EIGEN: 3.2.4 (internal)
CERES: 1.10.0 (internal)
FLANN: 1.8.4 (internal)
LIBTIFF:  (internal)
LIBPNG:  (internal)
LIBJPEG (internal)
CLP: 1.15.11 (internal)
COINUTILS: 2.9.3 (internal)
OSI: 0.106.10 (internal)
LEMON: 1.3 (internal)

Configuring done
Generating done

Best regards,
Lin

**Comment by pmoulon** [comment]
The first thing I see is that you are trying to build OpenMVG in x64 and using an external OpenCV compiled in x86.

So first, try to build OpenMVG without OpenCV support and then build with OpenCV support (only if you need it).

=> you can also try the develop branch
```
git checkout develop
git submodule init
git submodule update
=> redo cmake from scratch (removing old build files & cmake temp files) & build
```

**Comment by bigsheep2012** [comment]
Hi @pmoulon,

Thanks for your comments. I cancel the opencv choices and build it successfully.
