### ISSUE TITLE
the conversion of exterior orientation parameters between computer vision and photogrammetry

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#483]
While  in photogrammetry  the exterior parameters is (Rph|Xs, Ys, Zs) ,the exterior parameters of camera is [Rcv|t] in computer vision. There is a page about camera coordinate system.
[https://openmvg.readthedocs.org/en/latest/openMVG/cameras/cameras/]().
Both (Xs,Ys,Zs) and C=-Rcv't share the same meaning. But the rotation matrixes of them are different.
In my view, Rph = Rcv'*Rx(180)'. Is this formula correct?

**Comment by pmoulon** [comment]
It's a convention story.
The only difference between the notation you are introducing is the main camera looking axis.
In OpenMVG all camera depth are along the Z axis.
After you can do whatever you want: I mean change main camera axis if you need it.
The thing that I understand is that your Rx rotation change the camera main looking axis.

**Comment by whuaegeanse** [comment]
Rx means RotationAroundX. When using gps and imu info as the initial exterior parameters value, I am  confused with this conversion.

**Comment by pmoulon** [comment]
It depends of the original coordinates system of each of your sensor.
It's up to you to make a choice and choose one that fit your needs.

**Comment by whuaegeanse** [comment]
Thanks a lot. Both the gps and imu info are given in world system. I got it.

**Comment by pmoulon** [comment]
can we close the issue?
