### ISSUE TITLE
Is the  centralization of coordinates necessary for ui_openMVG_control_points_registration?

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#485]
I had reported an issue #432 about four months ago.
Recently,  I found the key to solve the problem. When I make a centralization for the gcps before registration and add the center coordinates after registration, the exported pointcloud seems fine. 
openMVG  use pixel coordinate in ba and other processing, which make it possible not suitable for the georegistration of the point clound when the gcps are big enough.

**Comment by pmoulon** [comment]
Normally the similarity computation must work whatever the coordinates system you are (I mean the translation must be estimated).

It's planned that BA will support some fix point (GCPs).
First a similarity registration will be performed and apply to the sfm scene, and then the BA will be run.
