### ISSUE TITLE
[graph] Largest CC nodes

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#486]
- Add a function that returns the nodes that are in the largest CC of an edge graph.
- Add a unit test.

**Comment by pmoulon** [comment]
+ORNis, +rperrot
Here some information, if we want to implement it ourself and so try to remove the lemon dependency:
1. we must detect articulation point
http://www.geeksforgeeks.org/articulation-points-or-cut-vertices-in-a-graph/
2. we must remove edge that connect articulation point to make some CC appear
3. for each CC check if it is biedge connected or not
http://www.geeksforgeeks.org/biconnectivity-in-a-graph/

**Comment by HUSTyanchao** [comment]
@pmoulon  I have a question, could you please help me ?
https://github.com/openMVG/openMVG/issues/487

**Comment by rperrot** [comment]
@pmoulon 

I'll have a look, reducing the number of dependencies of openMVG is always a good point (at least for compilation and maintenance purpose). 

If we can ensure same result with good performance it's also a good point ;-)

**Comment by pmoulon** [comment]
@rperrot Computing the MST will be also a required feature. (Minimum Spanning Tree)
See Kruskal http://www.geeksforgeeks.org/greedy-algorithms-set-2-kruskals-minimum-spanning-tree-mst/ or Prim http://www.geeksforgeeks.org/greedy-algorithms-set-5-prims-minimum-spanning-tree-mst-2/ or Boruvka http://www.geeksforgeeks.org/greedy-algorithms-set-9-boruvkas-algorithm/

**Comment by rperrot** [comment]
Ok. I'll have a look at it (we may need a good graph library in openMVG ;-) )

**Comment by pmoulon** [comment]
Move the topic about the new dev to https://github.com/openMVG/openMVG/issues/498
