### ISSUE TITLE
how to export the track infromation?

### ISSUE THREAD

**Issue by HUSTyanchao** [openMVG/openMVG#487]
how can  I get a list of views(images) the 3D point is visible in?
well when I finish the reconstruction I get the 3D points cloud and the camera parameters, but I can not find the information about every 3D point is visible in which images. If I can get it directly from the openMVG?

**Comment by pmoulon** [comment]
The information is exported in the sfm_data.json/bin file in the reconstruction folder.
For each 3Dpoint (landmark) the list of observations is available (it list the view in which the 3D point is visible, the feature id and the 2D position of the observation)

Look here how to go through the landmark and observations (i.e. to compute residuals)
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_report.hpp#L27
