### ISSUE TITLE
[build ]Compiling openMVG on NVIDIA Jetson TK1 (arm target)

### ISSUE THREAD

**Issue by polto** [openMVG/openMVG#488]
Hi !

I am trying to compile openMVG on NVIDIA Jetson TK1 embedded computer and make use of it's proprietary OpenCV extensions for GPU.

cmake -DOpenMVG_USE_OCVSIFT=ON -DOpenMVG_USE_OPENCV=ON . ../openMVG/src/

Even if I use those options, openMVG try to compile also it's own SIFT implementation and it result during "make" in this error:

> Scanning dependencies of target vlsift
> [ 49%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/generic.c.o
> [ 49%] Building C object nonFree/sift/CMakeFiles/vlsift.dir/vl/imopv_sse2.c.o
> /media/ubuntu/ed6746e6-6af4-40f4-80cf-51624865dfef/code/openMVG/src/nonFree/sift/vl/imopv_sse2.c:15:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
>  #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
>   ^
> /media/ubuntu/ed6746e6-6af4-40f4-80cf-51624865dfef/code/openMVG/src/nonFree/sift/vl/imopv_sse2.c:22:23: fatal error: emmintrin.h: No such file or directory
>  #include <emmintrin.h>
>                        ^
> compilation terminated.
> make[2]: *** [nonFree/sift/CMakeFiles/vlsift.dir/vl/imopv_sse2.c.o] Error 1
> make[1]: *** [nonFree/sift/CMakeFiles/vlsift.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> Linking CXX static library ../../../Linux-armv7l-Release/libopenMVG_kvld.a
> [ 49%] Built target openMVG_kvld
> Linking CXX static library ../../Linux-armv7l-Release/libopenMVG_multiview_test_data.a
> [ 49%] Built target openMVG_multiview_test_data
> Linking CXX static library ../../Linux-armv7l-Release/libopenMVG_matching.a
> [ 49%] Built target openMVG_matching
> make: *** [all] Error 2

I do not have SSE2, I have a GPU and I want to use GPU optimised SIFT implementation in openCV.

I just tried to comment the nonFree stuff. but "-lvlsift" strike back later ..

> [ 56%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/corrector.cc.o
> Scanning dependencies of target openMVG_lInftyComputerVision
> /usr/bin/ld: cannot find -lvlsift
> collect2: error: ld returned 1 exit status
> make[2]: *** [Linux-armv7l-Release/openMVG_sample_siftPutative] Error 1
> make[1]: *** [openMVG_Samples/siftPutativeMatches/CMakeFiles/openMVG_sample_siftPutative.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 56%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/covariance.cc.o
 
Is there any simple way to compile openMVG only with openCV's SIFT ?

**Comment by pmoulon** [comment]
Clean the cmake cache and try to add in the command cmake line -DVL_DISABLE_SSE2 and tell me if it works. If it's the case, I will manage SSE2 compiler support and add this preprocessor in the sift cmakelists file.

Note that OpenCV sift repeatability is worst that other SIFT implementation. It will provide satisfactory result but I think they will not be as good as the VLFEAT SIFT.

**Comment by polto** [comment]
Thank you @pmoulon for the quick answer.

so I completely removed openMVG_build directory and created it again.

>  cmake -DOpenMVG_USE_OCVSIFT=ON -DVL_DISABLE_SSE2=ON \
> -DOpenMVG_USE_OPENCV=ON . ../openMVG/src/

here I have a warning:

> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>   VL_DISABLE_SSE2

trying to compile:
> make

and it stops at the same place:

> /media/ubuntu/ed6746e6-6af4-40f4-80cf-51624865dfef/code/openMVG/src/nonFree/sift/vl/imopv_sse2.c:15:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
>  #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
>   ^
> /media/ubuntu/ed6746e6-6af4-40f4-80cf-51624865dfef/code/openMVG/src/nonFree/sift/vl/imopv_sse2.c:22:23: fatal error: emmintrin.h: No such file or directory
>  #include <emmintrin.h>
>                        ^
> compilation terminated.

**Comment by pmoulon** [comment]
Ok, can you try the build_arm branch please.

**Comment by polto** [comment]
thanks @pmoulon !

Now it pass the vlsift compilation but make an error here and die after libceres (83%).

> [ 57%] Building CXX object third_party/ceres-solver/internal/ceres/CMakeFiles/ceres.dir/coordinate_descent_minimizer.cc.o
> Linking CXX executable ../../Linux-armv7l-Release/openMVG_sample_siftPutative
> ../../Linux-armv7l-Release/libvlsift.a(host.c.o): In function `_vl_x86cpu_info_init':
> host.c:(.text+0xa): undefined reference to `_vl_cpuid'
> host.c:(.text+0x22): undefined reference to `_vl_cpuid'
> collect2: error: ld returned 1 exit status
> make[2]: *** [Linux-armv7l-Release/openMVG_sample_siftPutative] Error 1
> make[1]: *** [openMVG_Samples/siftPutativeMatches/CMakeFiles/openMVG_sample_siftPutative.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> 

regards,

**Comment by pmoulon** [comment]
Ok, so we will do that step by step ;-)
I think its because the arch is not used in the right way here https://github.com/openMVG/openMVG/blob/bc0def639a2c8a0b5877baa863e3815bab83fd02/src/nonFree/sift/vl/host.c#L358

The definition are here
https://github.com/openMVG/openMVG/blob/f0889f0a0024a211a7e5ed71794ad1926e545767/src/nonFree/sift/vl/host.h#L246

I don't know if we can find some forum thread about compiling vlfeat on arm targets ...

**Comment by polto** [comment]
It seems people were able to compile vlfeat on ARM.
At least debian have a package : https://packages.debian.org/search?arch=armhf&searchon=names&keywords=vlfeat

But my initial intention was to compile openMVG with OpenCV's SIFT optimized for GPU and not vlfeat.
Regards,

**Comment by ORNis** [comment]
Debian package follows some strict free software guidelines. So Vl_sift is not included since SIFT is patented.

**Comment by polto** [comment]
Thank you @ORNis , I was a bit surprised to see it in Debian. Now I understand.
How difficult would it be to compile openMVG without vlsift ?

**Comment by pmoulon** [comment]
@polto: Thanks to @MatXP, you can now compile vlfeat on arm platform (checked on a Raspberry Pi)

**Comment by polto** [comment]
@pmoulon , @MatXP,  thanks ! I will try it tonight and come back to you.

**Comment by polto** [comment]
@pmoulon , @MatXP,
I have successfully compiled and tested the build_arm branch.  
Thanks guys !

**Comment by pmoulon** [comment]
Impatient to see some reconstructions made on your ARM platform!

**Comment by pmoulon** [comment]
Will be merged to develop

**Comment by polto** [comment]
On the left ARM based robust.ply , on the right PC based final PMVS2 reconstruction.
![capture du 2016-03-25 12 45 04](https://cloud.githubusercontent.com/assets/46426/14043711/90dfb4f6-f287-11e5-8a25-509fd57f33d4.png)

vlsift performances are not that bad on Jetson TK1.

**Comment by pmoulon** [comment]
Thanks, FYI, soon I will make main_ComputeFeatures able to extract features on multiple image at the same time. But I have some doubt that it will be useful for embedded platform since they have small amount of RAM.
