### ISSUE TITLE
Bug accessing image scale space

### ISSUE THREAD

**Issue by li9uan** [openMVG/openMVG#489]
https://github.com/openMVG/openMVG/blob/f0889f0a0024a211a7e5ed71794ad1926e545767/src/openMVG/features/akaze/AKAZE.cpp#L284

"evolution_[options_.iNbOctave * p + q].Lhess;" --> "evolution_[options_.iNbSlicePerOctave * p + q].Lhess;"

The current version does not reveal the bug because iNbOctave=iNbSlicePerOctave=3

**Comment by pmoulon** [comment]
Thanks @li9uan 
@rperrot can you confirm this?

**Comment by rperrot** [comment]
I agree with this, it seems logical.

**Comment by pmoulon** [comment]
Thanks, will push a fix ;-)
=> Nice code review from @li9uan :+1:
