### ISSUE TITLE
Does resizing images impact on the results?

### ISSUE THREAD

**Issue by blackdeng** [openMVG/openMVG#494]
I have 23 images of 5184*3456 input into the incremental pipeline but it always stops when computing features. All commands use default parameters.

`1. Intrinsics analysis`
`You called :`
`utilities\WIN\openMVG_main_SfMInit_ImageListing`
`--imageDirectory D:\NERC\Forensic Project\Pictures1`
`--sensorWidthDatabase utilities\sensor_width_camera_database.txt`
`--outputDirectory D:\NERC\Forensic Project\Pictures1\outputs\matches`
`--focal -1`
`--intrinsics`
`--camera_model 3`
`--group_camera_model 1`
`- Image listing -`
`0%   10   20   30   40   50   60   70   80   90   100%`
`|----|----|----|----|----|----|----|----|----|----|`
`***************************************************`
`SfMInit_ImageListing report:`
`listed #File(s): 69`
`usable #File(s) listed in sfm_data: 23`

`2. Compute features`
`You called :`
`utilities\WIN\openMVG_main_ComputeFeatures`
`--input_file D:\NERC\Forensic Project\Pictures1\outputs\matches\sfm_data.json`
`--outdir D:\NERC\Forensic Project\Pictures1\outputs\matches`
`--describerMethod SIFT`
`--upright 0`
`--describerPreset NORMAL`
`--force 1`
`- EXTRACT FEATURES -`
`0%   10   20   30   40   50   60   70   80   90   100%`
`|----|----|----|----|----|----|----|----|----|----|`

At this point an error window pops up, saying that "openMVG_main_ComputeFeatures.exe has stopped working. A problem caused the program to stop working correctly, Please close the program."

I'm not sure why this happens but I tried resizing the images to 3000*2000 and it worked just fine. Although the generated point cloud looks ok but I don't know changing the input images resolution will harm the accuracy or not. By accuracy I only care about the relative positions of the points because I will scale the point cloud later on.

I have this concern because that OpenMVG uses camera sensor size to calculate the focal length in pixel using the equation: focal_pix = max(w_pix,h_pix) ∗ focal_mm / ccdw_mm. If I resize the input images the w_pix and h_pix will be changed, and the focal_pix will be changed consequently. I also don't know if there are any other parameters being affected by resizing the images.

**Comment by pmoulon** [comment]
I think your pc do not have enough ram to extract the feature on so large image.
If you resize image and keep original exif there will be no problem.
OpenMVG will read the real image size and update the focal lenght accordingly.
See here https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L202 image width and height are read from the image header.

Downsizing the image size decrease a bit the accuracy, but not too much (your downsizing ratio is not big).

**Comment by blackdeng** [comment]
Thanks for your quick reply.

I also want the option that when the CCD size is not available, I can compute the focal length in pixels (f_pix) myself and pass it to main_SfMInit_ImageListing with the '-f' parameter. So I found two ways to compute the f_pix:

- using EXIF.FocalPlaneXResolution as mentioned in this post [https://github.com/pmoulon/osm-bundler/issues/14](url)

- 1.2*max(w,h) as mentioned in this post [https://github.com/openMVG/openMVG/issues/381#issuecomment-136644890](url)

Will resizing impact the first method, as I'm not sure if resizing changes FocalPlaneXResolution? 

For the second method I guess I can just use the result calculated by the real w and h, but I do find the f_pix calculated by this method is quite different with the other two methods (the one use CCD size and the first bullet). There can be 2000 pixels difference. To be honest, the generated point cloud looks just fine using these different f_pix. So, what's the effect of wrong CCD size? The magic number 1.2 definitely relates to a wrong CCD size.

**Comment by blackdeng** [comment]
also, if I want to keep the accuracy after downsizing the images, is it the intrinsic matrix I need to change according to the new size? i.e., the [-k|–intrinsics] Kmatrix: “f;0;ppx;0;f;ppy;0;0;1” parameter of main_SfMInit_ImageListing?

**Comment by pmoulon** [comment]
In all the case you must use the real image size (the size of the image you are using) If you want to keep the accurate value you have computed by hand you can use the -k option.
Else the approximate focal length will be used and refined by the BA.

- 5184 for full res
- 3000 when you are using your reduced image

The magic number 1.2 relates to a given angle of field of view (1.2 correspond to a 45 degree of FOV). So if it's not the one used by your camera, the initial value is close to the original one, but not the exact one.

**Comment by pmoulon** [comment]
Does the additional explanation was meaningful for you?

**Comment by blackdeng** [comment]
Yes, thanks for clarify. 

So, in short, 

- as long as I compute focal length myself, I need the -f option for accuracy purposes;

- if I resize the image, I need the -k options to maintain accuracy. 

- If no -f or -k provided, it can also generate a proper result just with a bit loss of the accuracy;

- The number 1.2 estimates the focal length so there will be a bit loss of the accuracy, but close enough

Is that correct?

**Comment by pmoulon** [comment]
You're right.
Just a minor update on the second/third point:
- if I resize the image, I need the -k options to maintain accuracy.
 -> If you have resized the images while keeping the input EXIF data and if the camera is saved in the camera database, it will work (focal length in pixel is computed with the real image size). Do -k is not compulsory.

But as you said it could be worth it to implement focal length computation from FocalPlaneXResolution/FocalPlaneYResolution when they are provided in the EXIF data.

**Comment by blackdeng** [comment]
About the FocalPlaneXResolution, it normally has two numbers, for example, (5184000, 905). Both numbers are involved in the focal length calculation. However, I can see that the numbers are somehow related to the image width, as the first number is 1000 times of the width, so will the two numbers of the FocalPlaneXResolution change with the resized width?
