### ISSUE TITLE
Camera position - robust_essential_spherical sample

### ISSUE THREAD

**Issue by HackerHumor** [openMVG/openMVG#495]
Hi,

I am curious if I may be missing something. Is it possible to get the camera x,y,z position for both of the images using the essential matrix in the robust_essential_spherical sample? I understand that we do have the translation vector computed, but how can we get the actual x,y,z positions from that?

Any help would be really appreciated, Thanks!

**Comment by pmoulon** [comment]
Hi,
From the essential matrix you can compute {R,t}.
t = -RC => C = -R.transpose()*t
```
const Mat3 &R = Rs[index];
const Vec3 &t = ts[index];
const Vec3 C = - R.transpose()*t;
```

**Comment by pmoulon** [comment]
@HackerHumor Any feedback?
Please close the issue if the answer was self contained.
