### ISSUE TITLE
OpenMVG with MinGW & Eclipse Build

### ISSUE THREAD

**Issue by morgand536** [openMVG/openMVG#509]
Hi 
I am currently trying to build openMVG with MinGW & Eclipse Mars under Windows 10 environment.
However, I tried different method like MinGW & Unix Makefiles with Eclipse & Code Blocks, still I got errors when i try to build in the IDE.

When I use MinGW with Eclipse in CMake, errors shows during build:
![error210316](https://cloud.githubusercontent.com/assets/14993428/13914946/96cf7552-ef8c-11e5-9c9a-fe2e97ad32e8.PNG)

I have tried to Google "strdup was not declared in this scope eclipse" and tried to solve with Use -std=gnu++0x instead of -std=c++11, but it doesn't help.

Your input would be deeply appreciated. Thanks a lot!

**Comment by pmoulon** [comment]
Hi,
It's seems that some C++11 function are not found.
@rhiestan can perhaps provide some feedback
Here the command line used by him for MinGW compilation:
https://github.com/openMVG/openMVG/issues/466#issuecomment-177192957

**Comment by pmoulon** [comment]
Any news on that?

**Comment by morgand536** [comment]
MSYS seems work fine for me. Will update you if I have any issues.
Thanks. :D

On Tue, Apr 5, 2016 at 10:35 PM, Pierre Moulon <notifications@github.com>
wrote:

> Any news on that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/openMVG/openMVG/issues/509#issuecomment-205835818>
>



-- 
Cheers,
Morgan
