### ISSUE TITLE
Dataset to play : camera Ricoh

### ISSUE THREAD

**Issue by stephane-lb** [openMVG/openMVG#510]
Good Morning,

I found a Ricoh camera on saturday, and ask a friend to send some data to me. 
I am sure that you will like them ! http://vps.digital-lab.fr/ricoh.mp4

Ricoh is a small camera with 2 fisheyes lens to film in 360 x 180 : http://www.amazon.co.uk/gp/product/B014US3FQI?keywords=ricoh&qid=1458601243&ref_=sr_1_1&sr=8-1

Have a good day,

Stephane

**Comment by polto** [comment]
hi @stephane-lb ,

thanks to https://github.com/openMVG/openMVG/issues/621 Ricoh Theta S images are now working with OpenMVG.  Here is my first test.
![capture du 2017-02-20 12 14 57](https://cloud.githubusercontent.com/assets/46426/23123301/1f56f970-f768-11e6-87d9-1d6218d0c081.png)
regards

**Comment by pmoulon** [comment]
Happy to see that you give a try (@polto)
Since the dataset is not longer available I will close the issue.

@stephane-lb I will contact you soon to discuss about spherical camera.
