### ISSUE TITLE
[robust_estimation] RANSAC implementation does not use the usual selection criteria

### ISSUE THREAD

**Issue by devernay** [openMVG/openMVG#515]
@MrKepzie pointed this to me:
 https://github.com/openMVG/openMVG/blob/develop/src/openMVG/robust_estimation/robust_estimator_Ransac.hpp#L81
```
if (cost < best_cost) {
```

I believe RANSAC should pick the model with the highest *number* of inliers, not with the lowest cost. This is where the word "consensus" comes from. Reasoning on the cost means that a model with fewer inliers but a better cost is favored over a model with more inliers. This is wrong (RANSAC-wise).

**Comment by simogasp** [comment]
yes, good catch! 
Luckily it should not be much used in the pipelines, everything is A-RANSAC!

**Comment by pmoulon** [comment]
All is dependent of your template Scorer object.
By default we use https://github.com/openMVG/openMVG/blob/develop/src/openMVG/robust_estimation/score_evaluator.hpp that minimize (as you said) the model that leads to the lowest sum of errors according this formula:
```
cost += (residual < threshold) ? residual : threshold;
```
Ransac paper leads to maximize:
```
cost += (residual < threshold) ? 1 : 0;
```
I understand Consensus has having a generic selection criteria.
I want to remind as you can define your own Scorer function to perform the minimization you need.
 (inlier count).
Defining the cost as the negative count of inliers will be do what you want without modifying all the consensus methods.

**Comment by devernay** [comment]
I don't think RANSAC should ever use anything else than the number of inliers to measure the consensus, since the math in RANSAC is based on that... There is no advantage whatsoever in using the given cost instead of the number of inliers, and it may lead to making more iterations than RANSAC, since it may reject solutions that are better than the previous ones in terms of consensus (=# of inliers) but have a lower cost. Anything below the threshold in RANSAC is an inlier.

RANSAC *must* have:
```
if (inliers.size() > best_num_inliers) {
```
the cost value should not be used in RANSAC, only the number of inliers.

**Comment by pmoulon** [comment]
Change the Consensus criteria to inlier count rather than model cost.
- for MaxConsensus
- for Ransac

**Comment by pmoulon** [comment]
@devernay Modification have been done (develop branch)
