### ISSUE TITLE
[exif] Enhance sensor database with DJI cameras

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#516]

**Comment by pmoulon** [comment]
@rodrifra @igorti Develop branch now contains many DJI camera sensor size ;-)

**Comment by rodrifra** [comment]
Thank you very much @pmoulon. 
Those values appear to be the same as those in @igorti 's link, but according to https://en.wikipedia.org/wiki/Phantom_%28UAV%29 the Phantom uses a  Sony EXMOR R BSI 1/2.3" which means the sensor size is (according to www.photoreview.com.au/tips/buying/unravelling-sensor-sizes) 6.16, the value for the FC300x in the sensor database is 6.2. Which one is the right one?

**Comment by pmoulon** [comment]
You are right, I must set 6.16.
As BA will refine the Focal, I don't think it make a great change. But let's be as accurate as we can.
