### ISSUE TITLE
Ask for help to solve some error about buiding the openMVG_system progect

### ISSUE THREAD

**Issue by Duwenxiang** [openMVG/openMVG#523]
![building error](https://cloud.githubusercontent.com/assets/18410212/14513913/75db4836-021e-11e6-9792-7922a04b615b.png)
when I build the openMVG_system,some errors appear,like 'INTMAX_MAX:undeclared identifier',and Those errors are also showed in detail on the picture attached.Those error is related to the file ratio which is on the dic ...\Microsoft Visual Studio 12.0\VC\include. The ratio file is provided by VS2013,and is read-only file.I want to look for some hints about how to fix those error.

**Comment by pmoulon** [comment]
My first hint is that it can be related to system::Timer class of OpenMVG

I suggest two things:
try to add in openMVG/system/timer.cpp or hpp the following
```
// Needed for limit defines, like INTMAX_MAX, which is used by the std C++ library
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS
#endif
```
If it does not work try that:
see here: http://stackoverflow.com/questions/24798033/is-it-possible-to-use-stdchronoduration-with-rep-type-as-double-i-get-compi?rq=1

Here the two line you can try to modify the timer.hpp fine and write on top of it:
```
#undef HAVE_CXX11_CHRONO
```

Seems that chrono support in VS2013 is not very good.

=> BTW, there is not compilation problem with VS2015

**Comment by Duwenxiang** [comment]
Think you so much,pmoulon. I'm very glad that I have solved the problems that I mentioned before. Then,this issue can be closed.

**Comment by pmoulon** [comment]
you are welcome. I wish you a happy testing!
