### ISSUE TITLE
Using GlobalSFM  to reconstruct ground models from uav images, radial distortions are not well estimated

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#524]
When using GlobalSFM reconstruct ground models from uav images, I got a reconstruction result  the same as the papaer [http://ccwu.me/file/radial.pdf]. Is there any solution for the problem.
Thanks
PS:
I have a idea as follow
 Using Sequential SFM to make a  bundle adjustment for a small set of images, radial distortions k1 k2 k3 will estimated. Then using the estimated radial distortions fixed, do a global/sequential sfm for the total images.
How about this?
Thanks again.

**Comment by pmoulon** [comment]
Yes, it's a known problem, distortion coefficient & translation & rotation get mixed.

As explained in the paper there is 4 possible solutions for the problem:
1- Know the true distortion of the camera and use it and set it as fixed.
2- Change the flight path (use a two height flight, or use convergent views)
3- use GCP to make the ground model come back to something flat
4- use GCP and/or GPS position of the camera to constraint the BA and camera positions.

You suggest to use 1 (but with Incremental SfM you will not have any guarantee to have the right distortion computed.
The best if you can is to precalibrate your camera and use the value (just update the .json file intrinsic value and rerun ComputeMatches & the SfM method your want). When you re-run computeMatches photometric matches will be read and then robust geometric estimation will use your distortion coeff.

**Comment by whuaegeanse** [comment]
Thanks.
The first solution is available，but I can only have the distortion parameters for photogrammetry software not suitable for openMVG. How about adding a module in openMVG to support the distortion parameters.
The two or the thress solutions ara not available in some situation. But the last one maybe very useful for the gps position of the camera available from the exif.  Does it support in current openMVG?

**Comment by pmoulon** [comment]
What do you mean by not suitable for OpenMVG.
OpenMVG camera models can be Pinhole, Pinhole radial1, Pinhole radial3, Pinhole Brown (radial3 + tangential2). => Which camera model does your software is using?

GPS support is not yet available, but it is planned.

**Comment by whuaegeanse** [comment]
In photogrammetry, the distortion parameters are applied to the distorted coordinates. In other words,  undistorted coordinates are computed from distorted coordinates with no iteration, while distorted coordinates computed from undistorted coordinates with iteration.  openMVG and other computer vision software use the distortion parameters in a different way.

**Comment by whuaegeanse** [comment]
The camera  models are the same as OpenMVG, but the computation of the distortion parameters is different.  The distortion parameters are calibrated for photogrammetry softwares like Trimble Inpho.

**Comment by pmoulon** [comment]
What you can try for fun, is to undistord the image with Trimble Inpho.
And run OpenMVG SfM with a pinhole camera model with the focal found by InPho.
If your camera optic is fixed, you can run this pipe for all your sequences

**Comment by whuaegeanse** [comment]
Thanks.

**Comment by whuaegeanse** [comment]
Hi, Dr pmoulon . I have had the solution to this situation. Remove the distortion after feature extracted from images,  set the camera model as Pinhole ,and fix the intrinsic parameters in the following bundle adjustment.

**Comment by pmoulon** [comment]
If you does not update the features they will remains in the distorted image domain.

**Comment by whuaegeanse** [comment]
Thanks for your reply. Features have been updated and saved as *.feats files.
