### ISSUE TITLE
[camera] BrownModel: remove_disto function complexity

### ISSUE THREAD

**Issue by whuaegeanse** [openMVG/openMVG#526]
In the remove_disto function, distoFunction has been called twice every iteration.  
The  source code of remove_disto  is pasted as follow:

```
 virtual Vec2 add_disto( const Vec2 & p ) const
    {
      return ( p + distoFunction( params_, p ) );
    }

    /**
    * @brief Remove the distortion to a camera point (that is in normalized camera frame)
    * @param p Point with distortion
    * @return Point without distortion
    * @note numerical approximation based on
    * Heikkila J (2000) Geometric Camera Calibration Using Circular Control Points.
    * IEEE Trans. Pattern Anal. Mach. Intell., 22:1066-1077
    */
    virtual Vec2 remove_disto( const Vec2 & p ) const
    {
      const double epsilon = 1e-8; //criteria to stop the iteration
      Vec2 p_u = p;

      while( ( add_disto( p_u ) - p ).lpNorm<1>() > epsilon ) //manhattan distance between the two points
      {
        p_u = p - distoFunction( params_, p_u );
      }

      return p_u;
    }
```

Actually, the cost of  distoFunction is a little large, and we can use it just once in a iteration . We can modify the remove_disto function as follow:

```
virtual Vec2 remove_disto(const Vec2 & p) const
    {
        const double epsilon = 1e-8; //criteria to stop the iteration
        Vec2 p_u = p;

        Vec2 d = distoFunction(params_, p_u);
        while ((p_u + d - p).lpNorm<1>() > epsilon) //manhattan distance between the two points
        {
            p_u = p - d;
            d = distoFunction(params_, p_u);
        }

        return p_u;
    }
```

**Comment by pmoulon** [comment]
Thanks @whuaegeanse.
If I understand well your version can reduce the complexity up to 2 times.
Since distoFunction from add_disto will not be called at each iteration.

Can you confirm it?
Did you try your modification and see if the unit test are still ok?

**Comment by whuaegeanse** [comment]
I run the openMVG_test_Camera_Pinhole_Brown.exe and the output was presented as follow:

**Comment by pmoulon** [comment]
@whuaegeanse I was parsing the old issues and found yours. I have included your fix in the upcoming release ;-)
Thank you, you fix can certainly be applied for the Pinhole_Radial camera model. I wonder to see if it could be faster than the actually bisection method.
