### ISSUE TITLE
[multiview/sfm] RobustTriangulation

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#530]
Add support for 2 view tracks:
- will only check the chirality and the re-projection error

**Comment by simogasp** [comment]
Also as pointed out in #515
instead of choosing the model with the best reprojection error, you should choose the one maximizing the number of inliers
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data_triangulation.cpp#L281

**Comment by pmoulon** [comment]
It's a matter of choice, here I choose to keep a track if the seed was better than the other (kind of local optimization). But since the number of iteration will be so low, I think there is not so much difference between the two approach.
