### ISSUE TITLE
Global SFM problem

### ISSUE THREAD

**Issue by shuguohui** [openMVG/openMVG#532]
when I Run Global SFM,I find that some datasets got wrong result,like the link below,
https://raw.githubusercontent.com/shuguohui/openMVG/master/bbb.png

all the results have the Arc trend

**Comment by pmoulon** [comment]
This is a known problem see https://github.com/openMVG/openMVG/issues/524
Please calibrate your distortion first and use it or use a two height UAV flight.

**Comment by shuguohui** [comment]
the images have GPS tags,so how can i use the GPS tags?
can you tell me some papers that relevant to this problem? 

thanks

**Comment by pmoulon** [comment]
GPS pose registration or prior are not used yet but it's a feature that is planned for the next version.
Would you like to help on this?

Paper relevant to this problem: FYI: See Changchang Wu, "Critical Configurations for Radial Distortion Self- Calibration", CVPR 2014.

**Comment by shuguohui** [comment]
thank you very much, pmoulon !
I try this on my project first. if it's works well,it is my honour  to share code to OpenMVG

**Comment by pmoulon** [comment]
You're welcome, any feedback is of interest.
Additionally, I don't known which camera did you used (GoPro => wide angle or regular camera?)
If you are using a GoPro like, is better to select the camera model to be fish eye (-c 5 on openMVG_main_SfMInit_ImageListing)

**Comment by whuaegeanse** [comment]
Hi, pmoulon
I have finished a vision gps registration. Actually, with the help of gps info, we can  accelerate the process of image matching.

**Comment by pmoulon** [comment]
Would you like to work on a PR (Pull Request) for this?

**Comment by whuaegeanse** [comment]
Yes, It's my pleasure. In this weekend, I will make a PR for this.

**Comment by shuguohui** [comment]
hi whuaegeanse ,
is that means use GPS  euler distance to filter match-pair? those match-pair  distances larger than a threshold will be removed?

**Comment by pmoulon** [comment]
@shuguohui The GPS distance criteria for matching will be available for the next version.
But I'm not sure how we should use it.
As you said using a threshold is a bit strict since some pair will be removed despite they are of interest.
Perhaps using the K neighbor per view can be a better option.

-> Try with the distance threshold => give you some pair
-> Try with the K nearest view => merge to the previous pair list.

**Comment by shuguohui** [comment]
@pmoulon  in our project,we use Eulerian angle to filter match-pairs if  images have yaw/pitch/roll,this method can reduce an order of magnitude for matcing. 
but,only a few images have Eulerian angles, so in most cases, we first use vocabulary tree to detect candidate match-pairs.
so now we consider use GPS tag to accelerate the process of image matching.as we see,all the images from UAV have the GPS tags

**Comment by shuguohui** [comment]
use GPS tags in Gloal SFM,we also have finished a vision ,the SFM result is right,
but we extremely dependent on GPS  accuracy,because the weight of GPS is very high,
that is to say,the camera center is almost equal to GPS.

so i think this method is not very good,because as we see,we use only images in photoscan software,the SFM result is perfect.

**Comment by pmoulon** [comment]
This issue will help:
- (accelerate image matching) https://github.com/openMVG/openMVG/issues/550
- (rigid/BA GPS registration) https://github.com/openMVG/openMVG/issues/547
