### ISSUE TITLE
Iphone : Camera "Apple" model "iPhone 5s" doesn't exist in database

### ISSUE THREAD

**Issue by stephane-lb** [openMVG/openMVG#535]
Hi,

Just tried to make some 3D using my iPhone, and got this warning/error.
I would like to help, so let me know how to add this camera to the database ;-)

Have a great day,

Stephane

**Comment by pmoulon** [comment]
You can either add the camera sensor size to the database or use the -f option with the 1.2*max(w,h) value.
Adding this to the database should be sufficient:
```Apple iPhone 5S 4.89```

**Comment by stephane-lb** [comment]
Thanks Pierre

**Comment by pmoulon** [comment]
- [ ] Add Iphones sensor size to the database.

```
Apple iPhone 4S;4.57
Apple iPhone61;4.89
Apple iPad 3;4.54
Apple iPhone 3,1;4.74
Apple iPhone 4;4.74
Apple iPhone 5;4.57
Apple iPhone 5S;4.89
Apple iPhone 6;4.89
Apple iPhone 6 Plus;4.89
Apple iPhone3;4.74
Apple iPhone4;4.57
Apple iPhone3,1;4.74
Apple iPhone4,1;4.57
Apple iPhone4S;4.57
Apple iPhone5,1;4.57
Apple iPhone5,2;4.57
Apple iPhone5,3;4.57
Apple iPhone5,4;4.57
Apple iPhone6;4.89
Apple iPhone6,2;4.89
```

**Comment by stephane-lb** [comment]
Might have to update my version, but the good way was : 
```
Apple;iPhone 5s;4.89
```
I will check this week-end how the iPad mini and iPad pro are detected, and if I update for the new iPhone SE I will let you know.

Thanks.

Stephane

**Comment by pmoulon** [comment]
The format you explained was for previous OpenMVG version.
In v1.0 the new format is MAKER MODEL;SIZE ;-)
