### ISSUE TITLE
[cache system] Update Regions_Provider API

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#542]
Experimental features:
- perform some test in order to use a cache system for the Regions (feat/descriptors) data.
- [x] Update the Regions_Provider API to be the main virtual class,
- [x] Update the code that use the Regions_Provider class,
- [x] Add a Cached_Regions_Provider class that store only X regions in memory.
- [ ] Perform real condition test to see if in some place we need to reorder the pair to minimize the cache miss.

**Comment by pmoulon** [comment]
@mitjap Regarding your last comment about pair batching... I would be happy if you could test the regions_provider_cache interface.
You have just to tell the cache size when you run the ComputeMatches.
i.e ```-c 100``` tell that no more than 100 regions will be stored in memory at the same time.

Can you test this WIP feature with your 'big' dataset and tell me if it works?
The branch to use is develop_regions_provider_cache

**Comment by pmoulon** [comment]
I mean we can work on the two method (caching or batching).

The cache allow to be "transparent" for the whole OpenMVG code.
While the batching enable large scale matching, but will not improve some other piece of code where the memory can still be a problem (like in ComputeStructure from Known Poses).

**Comment by whuaegeanse** [comment]
This would be a great feature.

**Comment by pmoulon** [comment]
@whuaegeanse You can test the feature. The existing code is working.
Just checkout develop_regions_provider_cache and add the -c X option on ComputeMatches.
Any feedback on big reconstruction would be interesting.

**Comment by mitjap** [comment]
I will definitely give it a try. Thank you.

**Comment by whuaegeanse** [comment]
Hi, @pmoulon .
I have tested the new feature. The result of putative_matches with the -c X option  is the same as with the  no -c X option version . But the costs of the time of both are 417.32 seconds and  51.69 seconds respectively. For the process of  geometric_matches, the results are different, and the costs of the time of both are 312.804 seconds and 40.125 seconds.

**Comment by pmoulon** [comment]
@whuaegeanse 
Timing are different and this is normal, since in the cache mode some regions file are read many times from disk.
Regarding the geometric matches you seems to have very different timing.. since the putative matches file is the same...
