### ISSUE TITLE
Vastly different results for matches / reconstruct

### ISSUE THREAD

**Issue by mad-de** [openMVG/openMVG#544]
Hello @pmoulon. I'm having troubles with the matches / reconstruct part of the SfM workflow I'm using for my gui (https://github.com/open-anatomy/SfM_gui_for_openMVG/blob/master/src/software/SfM/workflow.py.in)
So although I'm using the same settings, I'm getting vastly different results concerning the reconstruction of the camera position and total amount of 3d points. I was hoping that you had an idea, how to track down where this different results come from, so that I can re-run this step more often to be able to chose the best computation.

I start with openMVG_main_ComputeMatches . Putative matches are the same, but the geometric matches files already differ by the amount of matches (+- 5).
I selected two images with -a and -b for openMVG_main_IncrementalSfM to have the same results here. But I'm not sure if there is a random factor there as well, as I can't really compare the output files. Do you have a hint for me there?

Robust triangulation seems to be the point in the workflow where reuslts differ most (see attached Screenshots) and by the amaount of computed 3d points (ranging between 9000 and 27000).
![screenshot from 2016-04-30 12-26-31](https://cloud.githubusercontent.com/assets/7095883/14935407/e5c02d9c-0ed0-11e6-8ed9-931ffb89ba56.png)
![screenshot from 2016-04-30 12-27-50](https://cloud.githubusercontent.com/assets/7095883/14935408/e792087a-0ed0-11e6-88ed-c7db74d908f9.png)

So my question would be, is there a way to track down, where these different results in the robust.ply come from (settings where the same for all outputs) and (ideally) how do I get the output to re-run them (and save them to different files) so that I can select the best one of them? 

Thanks for your help and best wishes,

Martin

**Comment by simogasp** [comment]
This is related to #537 
It should be fixed in the develop branch

**Comment by mad-de** [comment]
@simogasp thanks. I'll try it later.

**Comment by mad-de** [comment]
That seemed to have closed this issue completely.
