### ISSUE TITLE
Frustums and pointcloud scale issue 

### ISSUE THREAD

**Issue by luxigo** [openMVG/openMVG#546]
Hello Pierre,

Sometimes the points are at a much lesser depth than the related frustum plane (the camera position seems ok) and the entire pointcloud looks downscaled. Do you have an idea ? 

![capture d ecran de 2016-05-02 10 21 19](https://cloud.githubusercontent.com/assets/1018226/14951015/6a0b7e36-1056-11e6-80ca-05542ef87afe.png)

![capture d ecran de 2016-05-02 10 21 34](https://cloud.githubusercontent.com/assets/1018226/14951018/6e20f690-1056-11e6-873d-ba222f51fa20.png)

![capture d ecran de 2016-05-02 09 15 14](https://cloud.githubusercontent.com/assets/1018226/14951618/8fa874b0-105a-11e6-8e86-2ee3d1aae3da.png)

**Comment by pmoulon** [comment]
Hi @luxigo 
As you see the initial Bounding box of the cloud is very large, I think it's because there is some outlier points that are far from the camera position.
So Frustrum far planes are right. *Some points are far, so the far depth is large.*

If you want I can work on a function that clean far observations that can be considered as outlier points (from some statistics extracted from the depths per view). It will certainly improve your frustums.

**Comment by luxigo** [comment]
@pmoulon In the screen captures, the bounding box dimensions appears in the bottom left panel.

The bounding box for the point cloud is undersized (0.18 x 0.17 x 0.3) compared to the frustums bounding box (1.79 x 1.75 x 1.48). 

Also there is not a single point behind the frustum planes, all the points lie at the tip of the pyramid.

Maybe I could rescale the point cloud and shorten the frustums when I detect this.

It happens about once in 10.

90% of the time it works as expected, like in the screen captures below

![capture d ecran de 2016-05-02 13 57 51](https://cloud.githubusercontent.com/assets/1018226/14954049/54efb6f2-106f-11e6-86ee-b4b0b32a4899.png)

![capture d ecran de 2016-05-02 13 58 08](https://cloud.githubusercontent.com/assets/1018226/14954052/5a5dc660-106f-11e6-95ef-c44f6178d3f0.png)

**Comment by luxigo** [comment]
@pmoulon Maybe you are already removing outliers at some point after having generated the frustums ?  This could explain why sometimes the bounding box of the point cloud is smaller than the bounding box of the frustums.

**Comment by luxigo** [comment]
@pmoulon Do you generate the frustums using more points than those in robust.ply ?...

**Comment by pmoulon** [comment]
Frustums are computed on the input point cloud your provide (so the output of SfM sfm_data.json/bin)
So if you want the frustum that are adapted to the output of ComputeStructureFromKnownPoses you can recompute them at the end of the process.

**Comment by pmoulon** [comment]
Closing the issue since no more feedback from a long time.
