### ISSUE TITLE
[geodesy] Add a geodesy module to OpenMVG

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#547]
Will provide a basic coordinates for GPS registration.

**Add ability to read and use EXIF GPS data**
- [x] Add basic function to convert WGS84 lat,lon,alt from/to ECEF X,Y,Z value
- [x] Deal with EasxyExif uninitialized GPS (long,lat,alt) values (https://github.com/openMVG/openMVG/commit/f558720e37bb43fcfbbc32a034d93fc714b47487#commitcomment-17338526)
  - Enhance EasyExif library: 
    - Since 0 is a valid value, use a tag to mark the GPS value as uninitialized (infinity)
- [x] Add an unit test for checking existence and validity of GPS data
- [x] Add a sample to show how to parse GPS (lat, long, alt) EXIF metadata & compute XYZ positions & export the resulting positions as a PLY points file.

**Fix usage of large XYZ coordinates**
- [x] Fix SfM_Data PLY logging (force fixed notation and change the precision to fit float precision). Avoid quantification effect when data are registered (since they can have large value once they are in a geodesy coordinates system)

**Add a binary to perform the SfM_Data rigid registration to GPS metadata**

The registration is performed by computing a 3D similarity:
- [x] from all points
- [x] thanks to a robust estimation method, to be robust to outlier GPS measure.

Pose center positions can be read from:
- [x] image EXIF metadata
- [x] from the View pose priors

**Navigation prior**
- add a new view type with prior data
  - [x] translation
  - rotation -> this feature will be delayed since using many translation will align rotations too.
- [x] Implement the usage of navigation prior in the BA
  - [x] Add unit test to test BA with navigation prior

**Enhance image matching time**
- [x] Add a new binary that can generate a matching pair file for main_ComputeMatches.
  - Add a -G mode to use the GPS pose center prior and a neighbor value to limit the number of pair to compare for putative matches (particularly useful with UAV like scene that have a single height flight-plane).

**Documentation**
- [x] Add new documentation for the geodesy module

- [x] merge to main develop branch

**Comment by pmoulon** [comment]
Ex of the sample binary added  by https://github.com/openMVG/openMVG/commit/337980a4d2f33ce3b7dd049b5f5e0ff5406b7930 on the [SenseFly Quarry dataset](https://support.pix4d.com/hc/en-us/articles/202561419-Example-Datasets-Available-for-Download-Quarry#gsc.tab=0):
![quarry00](https://cloud.githubusercontent.com/assets/3235050/15244027/69fa4e8e-18ff-11e6-8c8f-c30cb4ff775d.png)
This tools allow to check the "UAV flight" path :+1:

**Comment by pmoulon** [comment]
Here the result of the actual results:
Show the GPS metadata position + the registration & a measure

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/15543088/c2656afc-2293-11e6-89ac-2ed780337189.png)

**Comment by pmoulon** [comment]
@ORNis @mitjap @morgand536 @rory @whuaegeanse => If you can test this feature I would be happy.
I have still to add a GPS/XYZ data file import (csv/txt file?) but the main feature is done.

**Comment by mitjap** [comment]
Awesome, will definitely test the new feature. If I checked correctly, at this moment you have implemented a rigid transformation to fit camera positions to exif GPS data. Do you plan to use GPS information when doing bundle adjustment with ceres?

**Comment by pmoulon** [comment]
@mitjap Yes I plan to use GPS prior for BA, still trying to figure out how I will implement it.
I think I will a new VIEW type by inheritance that will embed "navigation" prior (rotation/translation).

**Comment by json87** [comment]
hi, 
it is an useful tools. and when does these modules could be accessed? @pmoulon

**Comment by pmoulon** [comment]
Hi @json87 
Rigid registration is already available in the WIP develop_geodesy branch (but undocumented for the moment, but it just consist into running a binary: openMVG_main_geodesy_registration_to_gps_position)
Navigation prior will be implemented in the coming weeks.

**Comment by kafeiyin00** [comment]
hi,pmoulon,thanks for openning source of openmvg.
now, i use openmvg to handle the panoramic images. and i use the findSRT function to registrate the points to gps points to find the absolute position. because of the car route is just a line, so the transform is not a rigid transform.so i hope the next version you can add the gps information int BA to solve the problem

**Comment by pmoulon** [comment]
Hi @kafeiyin00 
Thanks for your feedback.
I will make a first draft soon in order to support GPS data in the BA.

As you will see in this thread https://groups.google.com/forum/#!topic/ceres-solver/WCW2T-l7Dmg since the magnitude of residuals is different between the image re-projection error and the GPS-cam distance the settings can be tricky.
BTW, I will make a first draft and then we will improve it.
Any dataset sharing for testing & evaluation would be a great contribution (even a tiny scene).

**Comment by kafeiyin00** [comment]
thank you @pmoulon

**Comment by pmoulon** [comment]
@kafeiyin00 Now rigid & non rigid registration can be performed.
[Here](https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst) the documentation.

**Comment by kafeiyin00** [comment]
great work! i will test it soon

**Comment by whuaegeanse** [comment]
Hi @pmoulon 
 It's exciting to see Navigation prior module is in above plan.  Does it all finished？

**Comment by pmoulon** [comment]
@whuaegeanse 
Yes, please check the doc [Here](https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst) the documentation.
Soon I will merge the branch "develop_geodesy" to the develop branch to have this feature in the next release.

**Comment by whuaegeanse** [comment]
@pmoulon  
Thanks. Great feature! 
BA will be accelerated because of this feature. I will test it soon.
Thanks again.

**Comment by whuaegeanse** [comment]
@pmoulon 
I have seen the module. 
Is there any solution to accelerate the process Global SFM with the help of navigation prior info?
How about to combine the navigation prior info with the relative rations to get initial values of tracks's landmarks and camera poses?

**Comment by pmoulon** [comment]
@whuaegeanse 

"Is there any solution to accelerate the process Global SFM with the help of navigation prior info?"
 - **Yes** -> See the example in the documentation ```openMVG_main_ListMatchingPairs  -G  -n 8``` is used to reduce the number of pair for image matching. It make the process faster since only 8 pair per view will be used.

"How about to combine the navigation prior info with the relative rotations to get initial values of tracks's landmarks and camera poses?"
  - You can think about skip the relative translations estimation and translation averaging step in GlobalSfM and configure directly the pose prior as pose center. Then, initialize the structure with the pairwise correspondences as tracks and perform a blind triangulation & BA with it. Feel free to test this possibility. (Note that results will be dependent of your prior accuracy).

**Comment by whuaegeanse** [comment]
@pmoulon 
Thanks.
I will try this in next week.
If each image has a  prior pose ,  the camera's pose can be replaced by the the prior pose.
With non rigid prior,  the poses of outliers  images should be computed from the inliers's poses with the help of  the relative rotations .After this step, the initial poses  and  the tracks can be got .

**Comment by sunmengmeng** [comment]
Hi, my images have no exif GPS data,so does it mean I can't use this module.

Now I have GPS txt file ,how can I use it to realize the same function?

**Comment by pmoulon** [comment]
You can either use a script to add your GPS data in the corresponding read EXIF field or modify the existing SfMImageListing binary to look for your corresponding GPS data in your text file.

**Comment by slembcke** [comment]
Just wanted to say that this is fantastic, and exactly what I needed. I've been trying to figure out how to use OpenMVP to increase the telemetry accuracy of an existing flight, and this looks like it might help me calculate exactly what I needed to know.

The OpenMVP code has been very nice to work with so far!

**Comment by pmoulon** [comment]
Thank you @slembcke for your enthusiasm!
I invite you to take a look to the step by step example provided here
Yes, please check the doc [Here](https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst) the documentation.

**Comment by slembcke** [comment]
Thanks. I was able to figure out some of that from just guessing and browsing around, but that's super helpful.

Are you interested in having more datasets for testing? I can probably give you some from our DJI flights that have GPS in the exif. They are sort of large though.

**Comment by pmoulon** [comment]
You can share your dataset (1 or 2) to openmvg-team[AT]googlegroups.com (a download link for example)
Will sun some expriment on it and make you a feedback.

**Comment by jpwhitney** [comment]
Hi,

> pmoulon commented on Nov 21
> Thank you @slembcke for your enthusiasm!
> I invite you to take a look to the step by step example provided here
> Yes, please check the doc [Here](https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst) the documentation.


This [link](https://github.com/openMVG/openMVG/blob/develop_geodesy/docs/sphinx/rst/software/Geodesy/geodesy.rst) no longer works.

Is there a step by step example elsewhere?

**Comment by pmoulon** [comment]
Since I have merged the modification in develop branch for future integration in the next release you can find the information [here](https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/Geodesy/geodesy.rst)

**Comment by jpwhitney** [comment]
Thanks, so far so good.  Found one small typo here at the beginning of the example.

> // Initialize the scene
> //  Pose prior for each view will be set thanks to the GPS data
> openMVG_main_SfMInit_ImageListing \
>   -P \
>   -d sensor_width_camera_database.txt \
>   -i /media/pierre/SenseFly/Quarry/geotagged-images/ \
>   -o /media/pierre/SenseFly/Quarry/quary_output/

I believe the -P is spurious, as when I run the above I get the message:

> Unrecognized option -P

**Comment by pmoulon** [comment]
Hi @jpwhitney 
-P must work since it is accessible here, this is q switch option
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_SfMInit_ImageListing.cpp#L144

**Comment by jpwhitney** [comment]
Sorry I think I have old code from the develop branch.  However upon attempts at recompilation I reach about 70% and it fails.

Currently I'm trying to get the windows compilation environment going so I can try there instead of Linux.

**Comment by pmoulon** [comment]
Which compilation error do you have on your Linux?
- build on for GCC and the CI is ok.
- build on windows must be ok too according the CI

**Comment by jpwhitney** [comment]
I have attached the exact steps taken to reproduce this problem:
[build_fail.txt](https://github.com/openMVG/openMVG/files/679941/build_fail.txt)

**Comment by rperrot** [comment]
Just a question. Did you update the submodules after updating the develop branch ? (I had similar issue around the same lines, updating the submodules solve the issue). 

Do a clean repository (i.e.: just after a clone) compiles fine ?

**Comment by jpwhitney** [comment]
@pmoulon 
Ubuntu 16.04.1 LTS
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

@rperrot I believe that it would compile fine, however I believe I need the develop branch to use the geodesy functions.  Also I go through the steps from a fresh git clone to compilation of the develop branch and if you look at the build_fail.txt file in my previous comment you will see the exact steps taken and should answer your first question.  I updated the submodules after cloning.  If I am doing something strange in that process please advise.
I tried to follow the directions of pmoulon in these comments on [this recent issue](https://github.com/openMVG/openMVG/issues/717).

> pmoulon commented 2 days ago
> Can you try the code that is in the develop branch?
> 
> git checkout develop
> git submodule init
> git submodule
> then rerun cmake and build from scratch

Here are the relevant command lines in the order I ran them, I know the log file is hard to look at:
```
$ cd openMVG/
$ git checkout develop
M	src/dependencies/cereal
M	src/dependencies/osi_clp
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
$ git submodule init
$ git submodule
+a248e3a55df07e71402de053ff3e3ce08bafc545 src/dependencies/cereal (v1.1.0-9-ga248e3a)
 eab31f228fd1872753c55fb438e3d88e51c0e9b2 src/dependencies/glfw (3.0.4)
+3630c6d4688567b5d78ddcb63537fa6293925be6 src/dependencies/osi_clp (3630c6d)
$ ls
appveyor.yml  BUILD         Dockerfile  license.libmv    logo       src
AUTHORS       COPYRIGHT.md  docs        license.openMVG  README.md
$ cd ..
$ mkdir openMVG_Build
$ cd openMVG_Build
$ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
```

What additional lines are you suggesting I run?

**Comment by pmoulon** [comment]
Do ```git submodule update``` rather than just ```git submodule```
my fault, I must update the other post ;-)

**Comment by jpwhitney** [comment]
Ohhh, okay, that makes sense now with what @rperrot was saying.  I'm still learning what all this stuff means.  Thanks guys!

**Comment by pmoulon** [comment]
@lixx2938 You will see that you can use GPS data as a non rigid prior for Bundle Adjustment in OpenMVG.
See [here](https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst) for some documentation.

**Comment by pmoulon** [comment]
@is03wlei, @lixx2938 You can use non rigid registration to GPS data. The prior can be used to reduce the pair to match, and during the BA. You can also perform a rigid alignment if you want.See the previous post for the doc.

**Comment by bistek** [comment]
Hi, I really would like to use (or test) this tool, but I cannot find it in the documentation or as a Meshroom node.

Thanks!

**Comment by pmoulon** [comment]
@bistek I can redirect you to the doc here https://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/
FYI: I will add soon a GPS dataset to here https://github.com/openMVG/Image_datasets with some instruction...
