### ISSUE TITLE
Consistently different number of poses, based on target volume

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#552]
What follows is strange (to me, at least) but is repeatable and may be just the kind of problem that @pmoulon is a savant at.

When I run the unmodified global script (using SIFT descriptors and the ‘master’ branch) on the "Chateau de Sceaux" set  (11 images), all views yield poses as [shown here](http://www.insightdigital.org/openMVG/SfMStructureFromKnownPoses_Report.html).

The invocation is:
`python ~/openMVG_Build/software/SfM/SfM_GlobalPipeline.py /home/kevin/source/castle/ ~/test`

An _identical_ invocation with a target path on any external drive will reliably yield only 10 poses for the 11 views, as [shown here](http://www.insightdigital.org/openMVG/SfMStructureFromKnownPoses_Report_remote.html).

That invocation is:
`python ~/openMVG_Build/software/SfM/SfM_GlobalPipeline.py /home/kevin/source/castle/ /media/kevin/MTTD_SSD_1/test
`

I’ve tried multiple external mounted volumes, each time with the same result; I’ve also tried many paths on the root volume and the result (poses for each view) is also consistent.

What could account for this?

It may be potentially interesting to note that specifying ‘AKAZE_MLDB’ or ‘AKAZE_FLOAT’ results in only 10 views, writing to the home directory or a remote volume.  Sequential SfM returns 11 views in both home and remote directories.

**Comment by pmoulon** [comment]
I don't think it's an issue related to disk directories but more on randomness (I think it's a combination of random sampling from the cascade hasher and from the robust estimation module, sometimes one image is rejected).

If you try to change
```
print ("3. Compute matches")
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-g", "e"] )
pMatches.wait()
```
to 
```
print ("3. Compute matches")
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-g", "e", "-n", "ANNL2"] )
pMatches.wait()
```
You will have 11 images all the time.

**Comment by whuaegeanse** [comment]
Global-SFM  needs a higher overlap  of images than Sequential-SFM in the processing of SFM(even with the same matching result).

**Comment by KevinCain** [comment]
@pmoulon, thanks for noting the "ANNL2" matching parameter.  I re-ran local/remote targets with your suggested flags and you're correct, the features match.

I expected global SfM to need greater correspondence than the sequential method, as @whuaegeanse pointed out.  I've also seen that the number of points, and therefore tracks, changes slightly with each run despite identical input.

But what prompted me to write was the consistency of global results over many runs -- local drive tests consistently resulted in all views yielding poses, but remote drives don't.

**Comment by pmoulon** [comment]
I understood your point.
The track count difference between runs is due to the randomness of robust estimation.
It's a kind of win-win, set more iterations will make results more stable, but will make the process slower.
