### ISSUE TITLE
[features] Add a SIFT implementation to OpenMVG

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#556]
**Extend the openMVG feature module with:**
- [x] A hierarchical gaussian scale space computation
- [x] A SIFT keypoint detection (Difference Of Gaussians)
- [x] A SIFT keypoint description (Squared grid of gradient orientation binning)
- [x] Update some binaries to use this new SIFT implementation as an option
- [x] merge to develop once tested by some other users

This implementation is based on:
Ives Rey Otero, and Mauricio Delbracio, Anatomy of the SIFT Method, Image Processing On Line, 4 (2014), pp. 370–396. http://dx.doi.org/10.5201/ipol.2014.82

Changes regarding original IPOL code are:
- The hierarchical scale space code can be run on it's own,
- Keypoint detection and description is split in two separate modules,
- the code can run per Octave (less memory consuming),
- some computation can be run in parallel.

Results are comparable to VLFEAT SIFT (looking to the repeatability with https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/features_repeatability/main_repeatability_dataset.cpp on https://github.com/openMVG/Features_Repeatability)

![sift_normal](https://cloud.githubusercontent.com/assets/3235050/15210744/04f82140-1838-11e6-99fa-183509a880c3.png)
![sift_high](https://cloud.githubusercontent.com/assets/3235050/15210743/04f41500-1838-11e6-970a-2240f71bb651.png)
![sift_ultra](https://cloud.githubusercontent.com/assets/3235050/15210745/04fca558-1838-11e6-9139-91f8e28b6199.png)

Thanks to @rperrot for his help to implement & test this new implementation.

**Comment by simogasp** [comment]
What is the advantage of using Anatomy? Speed performance?

**Comment by pmoulon** [comment]
1. Have a C++ code that is easy to read.
2. VLFEAT SIFT works fine, but is code is not easy to customize for your own need.
The idea here is to provide basic tools (gaussian scale computation, Sift Point localization, Sift description) that you can combine with other openMVG module for your own purpose.
