### ISSUE TITLE
Compiler Failure bug

### ISSUE THREAD

**Issue by thiirane** [openMVG/openMVG#558]
Hello I am trying to compile SFM.  It compile the individual libraries but when it came to 98 percent the compiler stopped.  Here is the error. 
![sfm error](https://cloud.githubusercontent.com/assets/10276935/15248034/ebf1ba36-18e5-11e6-8810-77033c48d6c3.JPG)

Please let me know if you cannot see this image.

**Comment by pmoulon** [comment]
Here some questions in order to figure out the problem you are facing:
- Which is your gcc version?
- Are you trying to build for a x86 or a x64 platform?
- Do you compile with multi-thread, I mean are you using ```make -j X```
  - if yes, have you tried build with a single thread ```make```

**Comment by thiirane** [comment]
How do you see the version of gcc?
I am compile on a virtual Linux machine (VMware Workstation) Ubuntu 14 x64
I used "make" only.

**Comment by pmoulon** [comment]
Do ```gcc -v```

Which ram size does your machine have?
```less /proc/meminfo```

We can test if the problem comes only from main_eval_Quality:
You can discard it's compilation from the cmake list and do make again.
To do so, you must comment line https://github.com/openMVG/openMVG/blob/master/src/software/SfM/CMakeLists.txt#L321 to https://github.com/openMVG/openMVG/blob/master/src/software/SfM/CMakeLists.txt#L331

**Comment by ORNis** [comment]
It looks like a RAM issue, I have the same when building packages on virtual machine. Try to increase RAM of your virtual machine or run make with less cores ( decrease the number of core used using  ̀make -j[number of core]`)

**Comment by thiirane** [comment]
Hi Thanks for your help with this.  I only have 4GB on this laptop so I would not be surprised if RAM is the issue. 
Here is the info on gcc version

![gcc-v](https://cloud.githubusercontent.com/assets/10276935/15248583/0405d686-18e9-11e6-9a1b-eda5cf39d306.JPG)



Here is the memory info

![meminfo](https://cloud.githubusercontent.com/assets/10276935/15248671/78078070-18e9-11e6-9bc9-42f4fe5aae3e.JPG)

**Comment by ORNis** [comment]
the ram of your virtual machine is not the RAM of your laptop here you have 88MB of free RAM!

**Comment by thiirane** [comment]
Yes.  I understand.  I increased the memory of the virtual machine to 2GB of the 4GB for the laptop.  I am running make now... Standby.

**Comment by ORNis** [comment]
@thiirane can you confirm it solves or not the problem? Thanks a lot.

**Comment by thiirane** [comment]
No I cannot confirm.  I tried to compile on my Laptop VMware ver 10 by increasing the memory to 2.8GB.  The Compiler was killed at the same point.  I then decided to abandon the laptop and work on my workstation.  My workstation has 12 cores and 25GB of memory I also have VMware ver 10 on this computer with 16GB memory.  When I tried to compile on this computer the compiler was killed at 90%. 
![workstation_compiler](https://cloud.githubusercontent.com/assets/10276935/15265558/830c52b8-1955-11e6-9650-c9e41658d0c4.JPG)
Here is the memory.  
![workstation_memory](https://cloud.githubusercontent.com/assets/10276935/15265572/e70c9a5c-1955-11e6-8b1b-9d9ed99250d2.JPG)

How much memory does this compiler need?

**Comment by ORNis** [comment]
what command did you use to build  openMVG ? ```make```,  ```make -j``` or ```make -j25``` ?

**Comment by thiirane** [comment]
SUCCESS finally.  I had to max out the ram memory of VMWare terminal at 3GB.  Then it completed the compile.  Thank you all for your help.   BTW I used "make"

**Comment by ORNis** [comment]
Thanks. Happy testing! @pmoulon I think you can close this.

**Comment by pmoulon** [comment]
I close the issue, it was a ram memory issue in the VM.
