### ISSUE TITLE
[build] compilation error (wrong opencv version)

### ISSUE THREAD

**Issue by rmsalinas** [openMVG/openMVG#561]
Ubuntu 14.04
opencv 2.4.8

cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_EXAMPLES=ON -DOpenMVG_USE_OPENCV=ON

Error:

[ 91%] Building CXX object software/SfM/CMakeFiles/openMVG_main_ComputeFeatures_OpenCV.dir/main_ComputeFeatures_OpenCV.cpp.o
/home/salinas/openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp: In member function ‘virtual bool AKAZE_OCV_Image_describer::Describe(const openMVG::image::Image<unsigned char>&, std::unique_ptr<openMVG::features::Regions>&, const openMVG::image::Image<unsigned char>*)’:
/home/salinas/openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:44: error: ‘cv::AKAZE’ has not been declared
     cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                            ^
/home/salinas/openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:62: error: ‘cv::AKAZE’ has not been declared
     cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                                              ^
/home/salinas/openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:94:16: error: ‘class cv::Feature2D’ has no member named ‘detectAndCompute’
     extractor->detectAndCompute(img, m_mask, vec_keypoints, m_desc);
                ^
make[2]: *** [software/SfM/CMakeFiles/openMVG_main_ComputeFeatures_OpenCV.dir/main_ComputeFeatures_OpenCV.cpp.o] Error 1
make[1]: *** [software/SfM/CMakeFiles/openMVG_main_ComputeFeatures_OpenCV.dir/all] Error 2

**Comment by pmoulon** [comment]
I think that AKAZE feature detector have been introduced only in OpenCV v3.0.
Since you are using opencv 2.4.8, that's why you have a compiler error.

Please note that OpenCV is an optional dependency, and so you can rebuild and use the project
```cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_EXAMPLES=ON ```
and it will run fine on your computer.

**Comment by pmoulon** [comment]
@rmsalinas Any feedback?

**Comment by rmsalinas** [comment]
It worked perfectly with opencv 3. Thanks a lot for your prompt response
El 24 may. 2016 5:49 p. m., Pierre Moulon <notifications@github.com> escribió:@rmsalinas Any feedback?

**Comment by pmoulon** [comment]
Thanks, Since the proble is solved I close the issue.
