### ISSUE TITLE
Can't run Color Harmonization

### ISSUE THREAD

**Issue by jbosch** [openMVG/openMVG#563]
I'm trying to run color harmonization over a set of images. I followed steps described in a previous issue: 
https://github.com/openMVG/openMVG/issues/431

I call the program like:
openMVG_main_ColHarmonize -i sfm_data.json -m ~/test_openmvg/matches.h.bin -o ~/test_openmvg/result

But I'm always getting the error: "Matches file is empty" even when I'm sure there are matches stored...
Any idea of what's wrong?

**Comment by pmoulon** [comment]
Hi @jbosch 
It should work, (It's certainly a path problem). Plese use complete path (I saw that for sfm_data.json you did not use the complete path)

I have just update a minimal dataset and the used command line on Github.
https://github.com/openMVG/Color_Harmonization_Image_Dataset

Here the result before:
![before](https://cloud.githubusercontent.com/assets/3235050/15575519/987a15ce-2353-11e6-86b7-fc6c869df6c0.png)

Here the result once the Harmonization is done:
![after](https://cloud.githubusercontent.com/assets/3235050/15575520/987d8ccc-2353-11e6-855c-9c4e3ac2ecd7.png)

**Comment by pmoulon** [comment]
@jbosch 
Since there is no activities since some time, I'm closing the issue.
Feel free to reopen, if you have any other questions.
