### ISSUE TITLE
Refine triangulated ground control points using ceres

### ISSUE THREAD

**Issue by mitjap** [openMVG/openMVG#564]
I recommend adding an option to refine triangulated GCPs with existing Bundle_Adjustment_Ceres. This way it would not ignore some camera paramters (radial distorsion). It would help us get more accurate transformation (RTS) and later to get accurate 3D errors (`actual_gcp - triangulated_gcp`) on GCPs after final BA

Current hack-ish solution is to use GCPs as structure and optimise only structure using flags.

Context: https://github.com/openMVG/openMVG/blob/722e4efb686904fe6e281d64c4625ab4119378db/src/software/ui/SfM/control_points_registration/mainLayout.cpp#L284

**Comment by mitjap** [comment]
Current hack:
```
    sfm_data.structure.swap(sfm_data.control_points);

    bundle_adjustment_obj.Adjust(sfm_data, openMVG::sfm::Optimize_Options(
        openMVG::cameras::Intrinsic_Parameter_Type::NONE,
        openMVG::sfm::Extrinsic_Parameter_Type::NONE,
        openMVG::sfm::Structure_Parameter_Type::ADJUST_ALL
    ));

    sfm_data.control_points.swap(sfm_data.structure);
```

**Comment by pmoulon** [comment]
Note:
In all case GCP will use the distortion, since the 3D point is projected and distorted to fit the image distortion (since the same reprojection error functor is used for structure & GCP points).

In order to use GCP you must tell to the BA framework to use them (be default it is set to false)
```
ba_object->Adjust(sfm_data,
    Optimize_Options(
      Intrinsic_Parameter_Type::ADJUST_ALL,
      Extrinsic_Parameter_Type::ADJUST_ALL,
      Structure_Parameter_Type::ADJUST_ALL,
      Control_Point_Parameter(20.0, true))) ); // A weight of 20 is used
```

Your idea about triangulated & true GCP is another way of seeing the problem that we could implement too.

**Comment by mitjap** [comment]
I understand that part on how to use GCP. My proposal is to do refined triangulation before we even compute and apply RTS transformation/similarity. This would make better approximation for ceres. 

Example where this could be used: https://github.com/openMVG/openMVG/blob/master/src/software/ui/SfM/control_points_registration/mainLayout.cpp#L284

After BA it'd be nice to see the 3D errors as part of the report.

This might be slightly off-topic:
Do you think it would be good to have 2 members for GCP data on Sfm_Data object; one for ground truth values and another one for actual values that best fit in the scene?
For example camera position is encoded in camera itself and GPS data (ground truth) is separately stored. While camera position is optimized and fits the scene as much as possible, GPS position is constant. 
This could also be the case for ground control points. One member could be for points that best fit the scene (triangulated GCPs) and another for ground truth data.

**Comment by whuaegeanse** [comment]
1. GCPs can be used to compute  "transformation/similarity" if we have more than 4 GCPS and their structure points(triangulated points from image points in views);
2. GCPs can be used to refine all parameters in the process of BA ; After computiing and applying RTS transformation/similarity, the GCPs can be used in BA to refine the result.

**Comment by pmoulon** [comment]
I'm closing this issue, since for the moment I will not consider refining GCP data.
But we imagine add a new binary that will refine GCP 3D data thanks to BA & the tricks you have used.
