### ISSUE TITLE
[geodesy] Enhance GCP BA usage robustness

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#565]
Fix the behavior seen by @mitjap.
https://github.com/openMVG/openMVG/commit/875a259c5185ed644d77dbc02618035888c3a17e#commitcomment-17665434
Using a GCP with no observation will make the actual code try to configure as constant a not existing parameter block => ceres will throw an exception.
- [x] detect this case and display a warning message to the user

- [x] Add an unit test to test scene registration via GCP.

**Comment by json87** [comment]
hi, how to use GCP BA , is there a example ? @pmoulon

**Comment by pmoulon** [comment]
Sorry for the late answer.
You must activate the usage of GCP in the BA engine with the weight of your choice.

See here how to do that https://github.com/openMVG/openMVG/commit/875a259c5185ed644d77dbc02618035888c3a17e#diff-29aac9ec66e71d8020199c4a7225eec6R341
