### ISSUE TITLE
openMVG_main_IncrementalSfM keep silent for long time

### ISSUE THREAD

**Issue by json87** [openMVG/openMVG#566]
hi, 
I have 390 UAV images and follow the basic pipeline for sfm. However, the incremental sfm tool openMVG_main_IncrementalSfM ofen fall into silient for a long time during operation of Triangulated 3D points. 

waiting for reply! thanks!

![qq 20160603100732](https://cloud.githubusercontent.com/assets/17582213/15766677/bb309a5e-2973-11e6-9e2e-2ba405c6a371.png)

**Comment by morgand536** [comment]
I have the same issue that my process stuck in Triangulated 3D points.
If I use lower resolution and less number of photos, the pipeline can be proceeded with this part.

**Comment by pmoulon** [comment]
I got some comments about a similar issue: always on windows.
Would be interesting to know if it's an infinite loop somewhere... or if it"s an algorithmic issue due to complexity (check if new 2 view triangulation can be performed).

@json87 Did you try the GlobalSfM on this dataset?
@morgand536, @json87 If you see the issue on a specific dataset it would be interesting to know where the program spend time (debugging?).
I think we can make this step faster by precomputing visible trackid per view (actually it's done on the fly, and I think this is this step that could be slow on some dataset).

**Comment by json87** [comment]
I have tested the dataset with GlobalSfM.  but an error occurs.  Invalidate matches file. 
After check source code,  I find that incremental sfm and global sfm use different match file, one needs match file with extension of .e.bin, the other .f.bin. is it ok to just rename the already generated match file name? @pmoulon

**Comment by pmoulon** [comment]
You can either rename the file. Or relaunch the main compute features with the -g e option to enable essential matrix filter for putative matches. Or run the python script on the same dir. 

-----Message d'origine-----
De : "json87" <notifications@github.com>
Envoyé : ‎03/‎06/‎2016 09:09
À : "openMVG/openMVG" <openMVG@noreply.github.com>
Cc : "Pierre Moulon" <pmoulon@gmail.com>; "Mention" <mention@noreply.github.com>
Objet : Re: [openMVG/openMVG] openMVG_main_IncrementalSfM keep silent forlong time (#566)

I have tested the dataset with GlobalSfM. but an error occurs. Invalidate matches file. 
After check source code, I find that incremental sfm and global sfm use different match file, one needs match file with extension of .e.bin, the other .f.bin. is it ok to just rename the already generated match file name? @pmoulon

**Comment by json87** [comment]
I have test the uav dataset with global sfm and everything goes well. 
![qq 20160603153201](https://cloud.githubusercontent.com/assets/17582213/15771893/5a357f1c-29a0-11e6-804f-d2886777ad38.png)

**Comment by json87** [comment]
@pmoulon 
![Uploading QQ截图20160603153135.png…]()

**Comment by json87** [comment]
@pmoulon 

![qq 20160603153135](https://cloud.githubusercontent.com/assets/17582213/15771961/e16d200c-29a0-11e6-80ba-c207dfb64524.png)

**Comment by json87** [comment]
hi, 
recently, I have updated my program to branch of develop_geodescy and re-processed a dataset with 34 uav images. the same error related to openMVG_main_IncrementalSfM occurs again. however, I have successfully processed this dataset with code from master. Then I think is it possible that some errors were introduced from branch of develop_geodescy. may it help to find the bug! @pmoulon

**Comment by XichaoTeng** [comment]
Hi,
I also run into the same problem. I have 42 UAV images, and the  openMVG_main_IncrementalSfM stuck in Triangulated 3D points with code from master. 
If I use the GlobalSfM on my dataset, the pipeline can be proceeded.

**Comment by pmoulon** [comment]
@XichaoTeng I would be curious to know if the problems remains in the case of a non multi thread process. Can you try to run it by setting openmp thread count to 1?
=> https://software.intel.com/en-us/node/528373

BTW, if you can run it in debug mode too and see where the program get stuck it would be worth it.

Are you on Linux or Windows? (I think you are on Windows)

**Comment by pmoulon** [comment]
Since there is no activities since some time, I'm closing the issue.
Feel free to reopen, if you have any other questions.

**Comment by laurent124** [comment]
Hello everyone,

I had the same exact issue as json87. The incremental method was stuck at the same step. I renamed the match file and used the global method and everything worked out.

For your information, I managed to process a set of more than 1200 pics. It took roughly 1h to reconstruct with the global method and about 12h for features and matches.

thanks a lot for this project !

**Comment by csp256** [comment]
How many features per image, and what type of features?

**Comment by laurent124** [comment]
not sure. where can you see that ? in the reconstruction report ? i can poste a pictrue of the result though

**Comment by pmoulon** [comment]
@laurent124 Are you using the last OpenMVG develop branch?
Which platform are you using (windows)?
FYI, default settings compute SIFT features.

**Comment by laurent124** [comment]
Hello Pierre,

Thank you for your post. I used the windows binaries of the release 1.0 that I downloaded on Friday. I went to the release tab. Maybe I should use other binaries.

I ran tests on a Windows 10 machine (i7 6700, 32 gb ram). I used the default setting for feature detection.

To be honest, I was happily surprised that openmvg was able to match 1200+ picture in a time comparable to photoscan. It then densified properly as well. I m using photogrammetry for coastal research and really appreciate open sofware as opposed to black box.

**Comment by pmoulon** [comment]
Hi @laurent124 ,
Thanks for your feedback.
Can you try the current develop branch version?
Here the recompiled version
[openMVG_main_IncrementalSfM.zip](https://github.com/openMVG/openMVG/files/454623/openMVG_main_IncrementalSfM.zip)

Cannot wait to see some screenshot of your reconstruction later on!

**Comment by csp256** [comment]
I've never run a reconstruction of that size before (12 hours is right on the boundary of how long I could be convinced to postpone using my laptop) so I crunched some numbers to prove to myself its viability.

1200 images is 719400 image pairs if you do exhaustive matching. If it took 12 hours, that implies 59950 per hour, or ~1000 per minute, or ~16.6 per second. Neglecting detection & extraction time, that is 60 ms per pair. Assuming your brute force matcher got 2 billion comparisons per second (what my naive GPU 128f sift matcher gets; I have not tested OpenMVG's CPU matching speed) and you enforced symmetric matches, that implies a bit under 7,900 features per image. 

So yes, it is in the bounds of credulity, even if the number of features is kinda smaller than I expected. 

But yes, please do share your reconstruction when you are done!

**Comment by laurent124** [comment]
Hello csp256,

I made a small [video](https://www.youtube.com/watch?v=V7TUjV004AY&feature=youtu.be) for you where you can watch the set.

I went through global 3D reconstruction and densified the cloud with resolution level of 3 (based on roughly 5000 pixel wide pictures). In all, it is more like 18 hours roughly of processing. I did not do the mesh though.

Thank you @pmoulon , I will try this and let you know.

**Comment by pmoulon** [comment]
Awesome! Thank you so much for the sharing. Your other youtube videos are also very cool!

**Comment by rennu** [comment]
@pmoulon Hi, I'm struggling with the same problem that OP had. I tried your precompiled development branch version (openMVG_main_IncrementalSfM.zip) on a windows 10 workstation and it worked better. However, on a windows 7 workstation the binary crashes right away ("Unhandled exception at 0x000000013F4D2380 in openMVG_main_IncrementalSfM.exe: 0xC000001D: Illegal Instruction").

I then tried to build the latest development branch version myself but now the binary crashes with message:

```
Trying to load a registered polymorphic type with an unregistered polymorphic cast.
Could not find a path to a base class (struct openMVG::cameras::IntrinsicBase) for type: class openMVG::cameras::Pinhole_Intrinsic_Radial_K3
Make sure you either serialize the base class at some point via cereal::base_class or cereal::virtual_base_class.
Alternatively, manually register the association with CEREAL_REGISTER_POLYMORPHIC_RELATION.

The input SfM_Data file "e:\openmvs\datasets\linna-incremental\matches\sfm_data.json" cannot be read.
```

Has something changed in the file format? What commit version of development branch did you use to build openMVG_main_IncrementalSfM.zip?

Thanks!

**Comment by pmoulon** [comment]
When you move from one branch to another, did you made ```git submodule init``` and ```git submodule update``` before building?

Regarding openMVG_main_IncrementalSfM.zip, I have use the current version on the develop branch at the date of the 5 sep. (So certainly this commit id https://github.com/openMVG/openMVG/commit/e791ba38d88bb290639915ef9c53cf4c47f83efc)

But I would like to recommend the actual develop branch. All the code that have been pushed in develop is mature and so you can use them safely.

**Comment by rennu** [comment]
Hi,

I did ```git clone --recursive -b develop https://github.com/openMVG/openMVG.git```, generated the visual studio project by using cmake-gui and built it as Release.

I built the development branch this morning and now it works.

**Comment by pmoulon** [comment]
@rennu Thank you for the feedback.
I fixed the error yesterday https://github.com/openMVG/openMVG/issues/664
