### ISSUE TITLE
Add iphone 6s plus in to sensor database failed

### ISSUE THREAD

**Issue by veolata** [openMVG/openMVG#568]
**First** 
already add below to the sensor db
"
Apple iPhone 4S;4.57
Apple iPad 3;4.54
Apple iPhone 3,1;4.74
Apple iPhone 4;4.74
Apple iPhone 5;4.57
Apple iPhone 5S;4.89
Apple iPhone 6;4.89
Apple iPhone 6 Plus;4.89
Apple iPhone 6s Plus;4.89
BenQ GH200;6.16
BenQ LM100;6.16
"
But still,
Warning & Error messages:
015606" model "iPhone 6s Plus" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
015611" model "iPhone 6s Plus" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
015614" model "iPhone 6s Plus" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
015618" model "iPhone 6s Plus" doesn't exist in the database
Please consider add your camera model and sensor width in the database.

**Second**
the other issue is the output of warning, it seems the start of the string 
015606"
is not complete,

**Third**
sensor database is really a good idea, 
by using which equipment? achieve less than mm accuracy? 

Many thanks!!

**Comment by pmoulon** [comment]
Thanks for your message.

Can you try with this following entry in the db?
```
iPhone 6 Plus;4.89
```

If it does not work, can you share a picture in order to debug it (thanks to the googlegroup)?

Using the database is to try to have the most precise pixel focal length, since have the best intrinsic parameter you have the best your camera orientation will be.

**Comment by autosquid** [comment]
@pmoulon  do you mean  ```iPhone 6s Plus;4.89 ?```

**Comment by veolata** [comment]
@pmoulon
Sorry, just read your reply. I have checked your assumption early, in sensor db, change
Apple iPhone 6s Plus;4.89
to
iPhone 6s Plus;4.89

but unfortunately, the error and warning result remains the same.
I have gmail you the image.

Many thanks!!

**Comment by pmoulon** [comment]
I have just tried with your image & ```iPhone 6s Plus;4.89``` and it works for me.
Be sure to have the s just after the 6

**Comment by veolata** [comment]
Strange, not works for me. I will check out the source, debug the code and then report the feedback.

**Comment by veolata** [comment]
iPhone 6s Plus;4.89 works fine

**Comment by pmoulon** [comment]
Fixed in the develop branch :dart: 
Thanks for your feedback!
