### ISSUE TITLE
can't open *.ply file in meshlab 

### ISSUE THREAD

**Issue by sc3sc3** [openMVG/openMVG#569]
the resulting *.ply files cannot be opened in meshlab
error: unexpected eof

on the other hand, they open fine in blender

**Comment by pmoulon** [comment]
They are working fine.
Have you check with different image datasets?

**Comment by sc3sc3** [comment]
i also have the issue running openMVG/openMVG_Build/software/SfM/tutorial_demo.py
i attached a ply created with this file
[colorized.ply.zip](https://github.com/openMVG/openMVG/files/299228/colorized.ply.zip)

**Comment by pmoulon** [comment]
Loading for Meshlab is ok for me.
Perhaps it's a "locale" issue (. vs. , for floating point number)
 ![snapshot00](https://cloud.githubusercontent.com/assets/3235050/15806162/a2b245f6-2b3d-11e6-8e4a-bafcab56259f.png)

**Comment by sc3sc3** [comment]
you are right
i replaced all . with ,
and they load fine :-)

thanks for your time
and your great software

**Comment by infrontoftheforest** [comment]
Another solution is to use `export LC_NUMERIC='en_US.UTF-8'` or `export LC_NUMERIC=C`. This changes your locale to use `.` instead of `,` for the decimal place separator.

**Comment by mserouar** [comment]
I still have an issue despite the fact that I'm in locale C as shown on the screenshot

![Screenshot_2020-10-06_13-16-09](https://user-images.githubusercontent.com/57948061/95221478-c3e7d880-07f7-11eb-87c1-43202ef63cd0.png)

With a kinda normal format if I open it with a txt editor :

> ply
format ascii 1.0
element vertex 505
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
-0.23949599266052246 0.030704999342560768 0.8162339925765991 146.0 187.0 67.0
-0.22694699466228485 0.04585849866271019 0.8528969883918762 142.0 179.0 63.0
...

I've also tried to manually replace . by ,

But nothing changed. Is this related to the missing 'element face' which is not provided in the ply file when I used SFM and exported from Meshroom ?
