### ISSUE TITLE
cannot compile with openMP on MAC OSX 10.11.5 with gcc or clang-omp

### ISSUE THREAD

**Issue by mrbemani** [openMVG/openMVG#570]
openMP works on windows, but sequential_sfm freezes....at somewhere in the triangulation step.

then I tried to compile it on mac without openMP, everything works find.

when I tried to compile it on mac with openMP:
I've tried gcc-5 and clang-omp. (installed via brew from source) they both failed to compile.

gcc-5 failed at: openMVG/src/dependencies/osi_clp/./CoinUtils/src/CoinSignal.hpp:103:19: typedef typeof(SIG_DFL) CoinSighandler_t;

which says error: ISO C++ forbids declaration of 'typeof' with no type

and clang-omp cannot pass the link part. which cannot link -lomp

ld: library not found for -lomp
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Darwin-x86_64-RELEASE/openMVG_sample_features_affine] Error 1
make[1]: *** [openMVG_Samples/features_affine_demo/CMakeFiles/openMVG_sample_features_affine.dir/all] Error 2

**Comment by mrbemani** [comment]
here is my cmake for clang-omp
cmake . ../openMVG/src/ -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER="/usr/local/bin/clang-omp" -DCMAKE_CXX_COMPILER="/usr/local/bin/clang-omp++"

and here is my cmake for gcc-5
cmake . ../openMVG/src/ -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER="/usr/local/bin/gcc-5" -DCMAKE_CXX_COMPILER="/usr/local/bin/g++-5"

**Comment by mrbemani** [comment]
with -DOpenMP_C_FLAGS="/usr/local/include/libiomp" and -DOpenMP_CXX_FLAGS="/usr/local/include/libiomp" still fail to link.

**Comment by pmoulon** [comment]
@rperrot Any though on this?

**Comment by rperrot** [comment]
@pmoulon We already talk about theses issues. 

The compilation on gcc may be fixed with something we already did with clang : 

```
   typedef void(*CoinSighandler_t)(int);
```

maybe the code should check osx instead of clang. 

But since @mrbemani is on osx, clang should be considered first. In the CMakeLists.txt, we must investigate the following line : (136)

```
        LIST(APPEND OPENMVG_LIBRARY_DEPENDENCIES omp)
```

@mrbemani , I'm using clang-omp 3.8 (from macports), I remember there was some trouble with linking on clang-omp 3.7, you should update to 3.8 if it's not the case now. My configure line is as follow : 

```
CC=clang-mp-3.8 CXX=clang++-mp-3.8 cmake . ../openMVG/src/
```

Using the develop code, the only issue on my computer is related to openMVG_main_openMVG2openMVS executable (that I disable).

**Comment by mrbemani** [comment]
Thanks!! clang 3.8 works like a charm!! I downloaded their prebuilt binary for mac from http://llvm.org/releases/download.html



i did get this error with opencv option on.
```
[ 93%] Built target openMVG_main_ComputeStructureFromKnownPoses
Scanning dependencies of target openMVG_main_ComputeFeatures_OpenCV
[ 93%] Building CXX object software/SfM/CMakeFiles/openMVG_main_ComputeFeatures_OpenCV.dir/main_ComputeFeatures_OpenCV.cpp.o
[ 93%] Linking CXX executable ../../Darwin-x86_64-RELEASE/openMVG_main_GlobalSfM
[ 93%] Built target openMVG_main_GlobalSfM
Scanning dependencies of target openMVG_main_ConvertSfM_DataFormat
[ 93%] Building CXX object software/SfM/CMakeFiles/openMVG_main_ConvertSfM_DataFormat.dir/main_ConvertSfM_DataFormat.cpp.o
openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:40: error: no member
      named 'AKAZE' in namespace 'cv'; did you mean simply 'AKAZE'?
    cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                       ^~~~~~~~~
                                       AKAZE
openMVG/src/openMVG/features/akaze/AKAZE.hpp:105:7: note: 'AKAZE' declared here
class AKAZE {
      ^
openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:58: error: no member
      named 'AKAZE' in namespace 'cv'; did you mean simply 'AKAZE'?
    cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                                         ^~~~~~~~~
                                                         AKAZE
openMVG/src/openMVG/features/akaze/AKAZE.hpp:105:7: note: 'AKAZE' declared here
class AKAZE {
      ^
openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:51: error: no member
      named 'create' in 'openMVG::features::AKAZE'
    cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                           ~~~~~~~^
openMVG/src/software/SfM/main_ComputeFeatures_OpenCV.cpp:93:69: error: no member
      named 'DESCRIPTOR_KAZE' in 'openMVG::features::AKAZE'
    cv::Ptr<cv::Feature2D> extractor = cv::AKAZE::create(cv::AKAZE::DESCRIPTOR_KAZE);
                                                             ~~~~~~~^
[ 94%] Linking CXX executable ../../Darwin-x86_64-RELEASE/openMVG_main_IncrementalSfM
[ 94%] Built target openMVG_main_IncrementalSfM
'''

----
btw, in the bundle adjustment step:

```
Structure estimation took (s): 20.104.
#landmark found: 38856
...Generating SfM_Report.html
Bundle adjustment...
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0606 11:40:30.692677 2033049600 preprocessor.cc:61] OpenMP support is not compiled into this binary; only options.num_threads = 1 is supported. Switching to single threaded mode.
W0606 11:40:30.693315 2033049600 preprocessor.cc:71] OpenMP support is not compiled into this binary; only options.num_linear_solver_threads=1 is supported. Switching to single threaded mode.
'''

**Comment by rperrot** [comment]
The warning is pretty strange, since openMP may be on by default on clang 3.8. Maybe the precompiled executable you download are configured without openmp. Last remark : I use the macports version and libomp is a dependency, make sure it comes with the binary you've download. 

Regarding the issue with AKAZE, this may be an issue related to the version of openCV.

**Comment by mrbemani** [comment]
homebrew/science/opencv: stable 2.4.13 (bottled), HEAD
Open source computer vision library
http://opencv.org/
/usr/local/Cellar/opencv/2.4.13 (284 files, 52.5M) *
  Built from source on 2016-06-05 at 04:07:26 with: --with-opengl --without-numpy --universal --with-java --with-vtk
From: https://github.com/Homebrew/homebrew-science/blob/master/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: jpeg ✔, libpng ✔, libtiff ✔
Recommended: eigen ✔, openexr ✔, homebrew/python/numpy ✔
Optional: gstreamer ✔, jasper ✔, libdc1394 ✘, openni ✔, qt ✔, tbb ✔, vtk ✔, ffmpeg ✔
==> Options

**Comment by mrbemani** [comment]
openmp is detected during cmake. and CPU usage shows 700% percent, which looks like openmp is working.

**Comment by mrbemani** [comment]
I guess the problem maybe caused by using my external preinstalled ceres-solver...I will try to compile it again using the internal one.

**Comment by autosquid** [comment]
what about upgrading to opencv3  @mrbemani  no such thing in opencv2 as you can see in https://github.com/Itseez/opencv/blob/2.4/modules/features2d/include/opencv2/features2d.hpp

**Comment by autosquid** [comment]
What's more, is `-DOpenMP_C_FLAGS` `-DOpenMP_C++_FLAGS` necessary? since we already got `findOpenMp` in cmake to handle this.

**Comment by rperrot** [comment]
@autosquid You're right, CMakeLists.txt handle this correctly. 

And it's also a really bad idea to modify the C_FLAGS or CXX_FLAGS.

**Comment by pmoulon** [comment]
@mrbemani What is your status on this issue?

**Comment by pmoulon** [comment]
Feel free to reopen, if you have any other questions.

**Comment by tanmayGIT** [comment]
Please have a look at : https://stackoverflow.com/a/50313990/3465857
