### ISSUE TITLE
Superfluous spaces in .ply files. 

### ISSUE THREAD

**Issue by rutgervandenberg** [openMVG/openMVG#571]
After running either the global or incremental pipeline the produced .ply files have extra spaces, causing import into Blender (and Meshlab for some files) to fail. 

Example (replaced space by _ for readability):  
> ...
> __0.66435_0.0636282_0.0691918_109_109_107
> 0.673188_0.0931779__0.069603_112_113_107
> ...

Running `sed 's/\s\+\$//g;s/^\s\+//g;s/\s\+/ /g'` fixes the file.

**Comment by pmoulon** [comment]
Thanks for the feedback.
Will fix that and will keep you updated.

**Comment by pmoulon** [comment]
Would you be kind to share a PLY file that was not read by your meshlab? =>openmvg-team[AT]googlegroups.com
I never experienced this problem before, despite I have loaded tons of point cloud.

**Comment by pmoulon** [comment]
@rutgervandenberg I have made a fix in the develop branch.
Can you try it?

**Comment by rutgervandenberg** [comment]
Sorry for the slow response, for some reason I didn't get a notification even though I'm subscribed. 

I have since figured out that meshlab import failing was a different issue; my locale settings caused comma's to be used as decimal marks while meshlab expected dots. Seems I accidentally fixed that problem in the file while trying to figure out why blender imports failed.

Going to try your fix now.

**Comment by pmoulon** [comment]
@rutgervandenberg Can I close this issue?
