### ISSUE TITLE
Crash in a 64bit CPU without SSE4.2 support

### ISSUE THREAD

**Issue by Oliver001** [openMVG/openMVG#572]
I find it crashed for the `__popcnt64` in src/openMVG/matching/metric_hamming.hpp.
The usage of `__popcnt64` show in [__popcnt16, __popcnt, __popcnt64](https://msdn.microsoft.com/en-us/library/windows/desktop/bb385231%28v=vs.140%29).

And [6447431](https://github.com/openMVG/openMVG/commit/64474312ec075075eaf5cb919d91eae4f0e45512) is my fix.

**Comment by pmoulon** [comment]
Thanks for the report.
Your fix are checking at runtime if the intrinsic related to the popcount is available.
Did you check that the unit test are still working fine?

**Comment by Oliver001** [comment]
Yeah, it's ok.
I just check it according to the _Remarks_ part in page [__popcnt16, __popcnt, __popcnt64](https://msdn.microsoft.com/en-us/library/windows/desktop/bb385231(v=vs.140)).

**Comment by pmoulon** [comment]
Checking the SSE4.2 support everytime we need it is perhaps a bit cumbersome.
Which type of CPU do you have?

Perhaps using an external cmake compilation in order to check it's support would be better in order to define a compilation preprocessor.

**Comment by Oliver001** [comment]
It looks like that we can just check once time, and check too many times cost CPU times. But how about build the code in one computer with SSE4.2, run it in another computer without SSE4.2?
The CPU which I am using now is Intel(R) Core(TM)2 Quad CPU  Q9550.

**Comment by pmoulon** [comment]
That's the delicate question about feature & integration (make a feature run smoothly on every computer). I prefer to see opensource project as a great opportunity to have a program configured & optimized for the user computer. It simplifies the integration process only on the compiler/configuration level and not on runtime evaluation.
In this case there is a missing configuration check for windows support of the popcnt64 instruction.
Else we must move the logic to another place.

**Comment by Oliver001** [comment]
I see, but I just don't know which tool or project can do that?

**Comment by pmoulon** [comment]
@Oliver001 I added a class to handle the detection of CPU intrinsic support
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/system/cpu_instruction_set.hpp
