### ISSUE TITLE
"reconstruction_sequential/robust.bin" cannot be read

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#573]
During the sequential pipeline's match culling by confidence, on a job with ~2,000 images I note that the process exits at ~70% complete with _"reconstruction_sequential/robust.bin" cannot be read._

Apparently 'robust.bin' wasn't written, but everything else in the pipeline is working normally.  Does this sound familiar to anyone?

I'm running a reconstruction now, so I haven't been able to duplicate the error and trace it.  All of the images have EXIF info linking them to a camera that exists in the sensor width database.

**Comment by pmoulon** [comment]
Hi @KevinCain 
I think it's because ComputeStructureFromKnownPoses failed and so the process that have tried to use its output display your error message => cannot be read.

perhaps a memory issue or a hidden bug.
What you can do is to relaunch the ComputeStructureFromKnownPoses process. (comment all previous call in the python script and see what is happening)

**Comment by parapapa1** [comment]
Hi i have a problem with the process,  i want to run by hand all the process with a dataset generated myself, in the openMVG_main_SfMInit_ImageListing step i obtained the error :  no order was found.   

I wanted to rule out a syntax error and execute the example of the blog for this part of the code, but i got the same results. 
Thank you very much for your attention and help

**Comment by pmoulon** [comment]
I don't know why you have this error, since this error message is not from openMVG.
Please be sure to use full pathes, in you example I don't see any ./ or /user/....or ~/

**Comment by parapapa1** [comment]
thank you for your help,   actually i'm running the code in the directory  "/openMVG_Build /Linux-x86_64-RELEASE"   i changed the instruction but the results are the same.  

$ openMVG_main_SfMInit_ImageListing -i /openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images -d /openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o /openMVG_Build/software/SfM/ImageDataset_SceauxCastle/matches


Previously i execute the code with the global  and sequential pipeline with success. but when i change the dataset, the program show me the error "robust.bin" cannot be read. and "sfm_data.bin" cannot be read. for this reason i decide execute the software step by step, i think that by this way the creating a sfm_data.json file that describe the used image dataset can solve this problem. 

Thank you  for your advices.

**Comment by pmoulon** [comment]
If the global and sequential pipeline was run with success it's sure it's a path problem when you do it by hand.

So if you are in the build dir (Linux-x86_64-RELEASE) the following should work. When you press tab you must see the directory list appear

$ openMVG_main_SfMInit_ImageListing -i ../software/SfM/ImageDataset_SceauxCastle/images -d ../../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o ../software/SfM/ImageDataset_SceauxCastle/matches

**Comment by parapapa1** [comment]
Thank you very much for your help, in this moment i am running the code with the middlebury's datasets.  if i need your help again i will contact to you.  thaks again

**Comment by pmoulon** [comment]
@parapapa1 Middlebury data are 2 view based datasets & so they are not done to be used in classic SfM. Classic SfM need many picture of the same scene.
Perhaps you can explain more about what your are trying to do?

**Comment by parapapa1** [comment]
my project of thesis consist in to do a evaluation of methods of 3D reconstructions form images multiview.  in this case i choice a middlebury dataset's  of the dino with 48 images.  my question is..  this case require a configuration of Kmatrix  or other important topic ?

**Comment by pmoulon** [comment]
Yes, any precise intrinsic information you can provide will make the results better.
You can configure the focal length value to a given value with the -k option on openMVG_main_SfMInit_ImageListing binary.
I ran successful reconstruction on those datasets.
Often, you can for poor textured object enhance the results of the SfM pipeline with extraction a high count of features per images (you can specify the option -p HIGH or -p ULTRA on main_ComputeFeatures in order to extract more feature than the default settings)

**Comment by parapapa1** [comment]
please, can you show me the form to obtain this values of kmatrix;   i have a problem with this process:

./openMVG_main_SfMInit_ImageListing -d /home/ubuntu/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i /home/ubuntu/Documentos/Multiview/gipuma/data/dinoRing/jpg/ -o /home/ubuntu/Documentos/Resultados_dino_sfm/matches/ -k Kmatrix: “3310.4;0;316.73;0;3310.4;200.55;0;0;1”
 You called : 
./openMVG_main_SfMInit_ImageListing
--imageDirectory /home/ubuntu/Documentos/Multiview/gipuma/data/dinoRing/jpg/
--sensorWidthDatabase /home/ubuntu/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/ubuntu/Documentos/Resultados_dino_sfm/matches/
--focal -1
--intrinsics Kmatrix:
--camera_model 3
--group_camera_model 1

 Missing ';' character

Invalid K matrix input
0: no se encontró la orden
316.73: no se encontró la orden
0: no se encontró la orden
3310.4: no se encontró la orden
200.55: no se encontró la orden
0: no se encontró la orden
0: no se encontró la orden
1”: no se encontró la orden

**Comment by pmoulon** [comment]
It's because you are using the option not as it must.
Just use -k "..."

Like that (you can skip the database, since it will not be used in your case)
```
./openMVG_main_SfMInit_ImageListing -i /home/ubuntu/Documentos/Multiview/gipuma/data/dinoRing/jpg/ -o /home/ubuntu/Documentos/Resultados_dino_sfm/matches/ -k “3310.4;0;316.73;0;3310.4;200.55;0;0;1”
```

**Comment by parapapa1** [comment]
[image: Imágenes integradas 2]


Thanks a lot ,   i hope talk to you about the results,  thank you very much
again

2016-07-16 6:50 GMT-05:00 Pierre Moulon <notifications@github.com>:
