### ISSUE TITLE
How to use SURF Image Descriptor?

### ISSUE THREAD

**Issue by shishirprao** [openMVG/openMVG#575]
Hi, I am new to openMVG and would like to know if there is anyway I could use SURF for describing the keypoints instead of using SIFT or AKAZE. 

Thanks in advance.

**Comment by pmoulon** [comment]
Hi @shishirprao 
Yes you can. You can either add you own feature detector/descriptor or use all the ones of OpenCV.
If you want to use the one of OpenCV_contrib, you have to compile opencv, opencv_contrib.
Then indicate to OpenMVG you want to use the OpenCV integration, and then modifiy https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures_OpenCV.cpp

You can have a look here about the OpenCV Sift integration: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures_OpenCV.cpp#L145

**Comment by shishirprao** [comment]
Thanks for letting me know. I am building OpenMVG(develop_sift_anatomy branch) in windows with OpenCV 3.1 + contrib. I'll try it once I'm done.

**Comment by pmoulon** [comment]
Any feedback?

**Comment by shishirprao** [comment]
I was able to compile it smoothly and I am using opencv sift feature as of now. I'll try changing the code to use surf in the coming days. But apart from that, I think there is a small mistake in the software -> SfM -> tutorial_demo.py. In line 85 (Colorize Structure process) reconstruction_dir value will be output_dir/reconstruction_global. But, sfm_data.bin file is present only in output_dir/reconstruction_sequential. I dunno if I'm wrong with the assessment. I got an error and here is what I did to get both global and sequential output.
1) changed line 79 to reconstruction_dir_global = os.path.join(output_dir,"reconstruction_global")
2) changed the output path in line 85 and 89 to "-o", os.path.join(reconstruction_dir_global,"robust.ply").

I hope that this helps. 
If I do get any problem in using SURF feature I'll approach. But as of now its working like charm. Thanks :)

**Comment by shishirprao** [comment]
I guess my assessment was wrong. For some reason, sfm_data.bin file is not being generated when performing global reconstruction. 

![image](https://cloud.githubusercontent.com/assets/19942680/16435447/b0862262-3d5b-11e6-8fe6-1cfc835accb0.png)

**Comment by pmoulon** [comment]
Hi @shishirprao 
There is no mistake in the tutorial demo.
The two sfm pipeline are launched (Sequential & Global) in order to show how to use them.

I don't know why you did not obtain a sfm_data.bin in the reconstruction_global folder, but normally you must have one.

**Comment by pmoulon** [comment]
Feel free to reopen, if you have any other questions.
