### ISSUE TITLE
neato not found

### ISSUE THREAD

**Issue by xialang2012** [openMVG/openMVG#576]
Hi,

I have download the release built by VS 2015, and when I run 
`openMVG_main_ComputeFeatures -i matches\sfm_data.json -o matches -n 32`
I showed me 

> `neato` Not internal or external commands...

What can I do to make it correct? Thanks.

**Comment by pmoulon** [comment]
Neato is not compulsory.
It's a component from Graphviz used in order to display image relationship graph.
See here to download it http://graphviz.org/Download.php
Be sure that graphviz is in the path, so OpenMVG will be able to use it (I think it's the default choice when you setup Graphviz)

**Comment by xialang2012** [comment]
Thank you for you response. Now it works well. But I still have some problems about it.
I have 55 pictures, and I used
`openMVG_main_SfMInit_ImageListing.exe -i inImg -d sensor_width_database\sensor_width_camera_database.txt -o matches`
to get the image list, then 
`openMVG_main_ComputeFeatures -i matches\sfm_data.json -o matches -n 32`
were used to get the features, and 
`openMVG_main_ComputeMatches -i matches\sfm_data.json -o matches`
were used to get the matches, but the this step only took a short time to finish.

> C:\Users\xialang2012\Desktop\ReleaseV1.0 Pangio kuhlii WindowsBinaries_VS2015>o
> enMVG_main_ComputeMatches -i matches\sfm_data.json -o matches
> 
>   You called :
> openMVG_main_ComputeMatches
> --input_file matches\sfm_data.json
> --out_dir matches
> Optional parameters:
> --force 0
> --ratio 0.8
> --geometric_model f
> --video_mode_matching -1
> --pair_list
> --nearest_matching_method AUTO
> --guided_matching 0
> 
> - Regions Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 
>  - PUTATIVE MATCHES -
> Use: exhaustive pairwise matching
> Using FAST_CASCADE_HASHING_L2 matcher
> Using the OPENMP thread interface
> 
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Task (Regions Matching) done in (s): 0.331414
> 
>  - Geometric filtering -
> 
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Task done in (s): 0.267414
> 
>  Export Adjacency Matrix of the pairwise's geometric matches

and finally, I used the 
`openMVG_main_GlobalSfM -i matches\sfm_data.json -m matches -o global`
to make it completed, but it showed me

> -----------------------------------------------------------
> Global Structure from Motion:
> -----------------------------------------------------------
> Open Source implementation of the paper:
> "Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure
> rom Motion."
> Pierre Moulon, Pascal Monasse and Renaud Marlet.  ICCV 2013.
> ------------------------------------------------------------
> 
> - Features Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> 
> Invalid matches file.

 I am wonder if I have made some mistake?

**Comment by pmoulon** [comment]
The GlobalSfM pipeline "openMVG_main_GlobalSfM" expect Essential Matrix filtered putative matches.
Just relaunch ComputeMatches by adding -g e
```
openMVG_main_ComputeMatches -i matches\sfm_data.json -o matches -g e
```
and then relaunch:
```
openMVG_main_GlobalSfM -i matches\sfm_data.json -m matches -o global
```
and it will works fine.

**Comment by xialang2012** [comment]
yeah, it works well now, thank you @pmoulon . 
One more question... How can I get a full size of the SfM data? I put the SfM result into the MeshLab, and the image is very small.

**Comment by pmoulon** [comment]
What do you mean by full size (Meshlab display only point cloud, it does not display images)?
- having a point cloud with more density?
- how to navigate in Meshlab to be closer to the scene?

**Comment by xialang2012** [comment]
It means have a point cloud with more density?

**Comment by pmoulon** [comment]
In order to have a more dense reconstruction point cloud you can extract more features per images at the Features extraction stage:
-> Use the -p option on openMVG_main_ComputeFeatures option is by default NORMAL. You can use HIGH or ULTRA to extract more points per images.
Please erase your previous matches directory (erase features & matches files), else the old one will be read and re-used.

Else if you are satisfied by the SfM stage and you want to compute a dense point cloud or a surface you have to connect the OpenMVG result to some third party tools. A lot of exporter exists: http://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

I recommend to play with OpenMVS https://github.com/cdcseacave/openMVS/wiki/Usage

Please close the issue when you think that I answered all your questions.

**Comment by xialang2012** [comment]
Thank you for you reply. It's done.
