### ISSUE TITLE
build shared library failed

### ISSUE THREAD

**Issue by jakexie** [openMVG/openMVG#577]
I want to use openMVG shared library in my program , but i get the following errors after i config the cmake option "BUILD_SHARED_LIBS". 

[ 95%] Built target openMVG_main_SfM_Localization
[ 96%] Built target openMVG_main_ColHarmonize
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::AKAZE::Do_Subpixel_Refinement(std::vector<openMVG::features::AKAZEKeypoint, std::allocator<openMVG::features::AKAZEKeypoint> >&) const'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::AKAZE::Compute_AKAZEScaleSpace()'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::LIOP::Liop_Descriptor_Extractor::Liop_Descriptor_Extractor()'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::AKAZE::Feature_Detection(std::vector<openMVG::features::AKAZEKeypoint, std::allocator<openMVG::features::AKAZEKeypoint> >&) const'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::LIOP::Liop_Descriptor_Extractor::extract(openMVG::image::Image<unsigned char> const&, openMVG::features::SIOPointFeature const&, float*)'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::AKAZE::AKAZE(openMVG::image::Image<unsigned char> const&, openMVG::features::AKAZEConfig const&)'
../../../../Linux-x86_64-RELEASE/libopenMVG_sfm.so.0.8: undefined reference to `openMVG::features::AKAZE::Compute_Main_Orientation(openMVG::features::AKAZEKeypoint&, openMVG::image::Image<float> const&, openMVG::image::Image<float> const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [Linux-x86_64-RELEASE/ui_openMVG_control_points_registration] Error 1
make[1]: *** [software/ui/SfM/control_points_registration/CMakeFiles/ui_openMVG_control_points_registration.dir/all] Error 2
make: *** [all] Error 2 

I would appreciate for that if someone can help me .

**Comment by pmoulon** [comment]
@jakexie 
Can you try to add
```
openMVG_features
```
to the list here https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/CMakeLists.txt#L20

**Comment by jakexie** [comment]
@pmoulon thank you , it's ok.
