### ISSUE TITLE
Submodules are missing

### ISSUE THREAD

**Issue by nkosindlela** [openMVG/openMVG#581]
Hi I'm new to this field while tying to build openMVG on Cmake I have the following error    "submodule(s) are missing, please update your repository" any help on how to solve this issue, thanks 

The C compiler identification is MSVC 19.0.23918.0
The CXX compiler identification is MSVC 19.0.23918.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done

_**CMake Error at CMakeLists.txt:81 (message):
  

   submodule(s) are missing, please update your repository:
    > git submodule update -i**_

Configuring incomplete, errors occurred!
See also "C:/Users/Samuel/Desktop/Open/openMVG-master/src/build/CMakeFiles/CMakeOutput.log".

**Comment by pmoulon** [comment]
No worries,
as explained in the https://github.com/openMVG/openMVG/blob/master/BUILD file.
You must do
```
git clone https://github.com/openMVG/openMVG.git
cd openMVG
git submodule init
git submodule update
```
Then you can perform cmake and build

**Comment by nkosindlela** [comment]
Thanks Pmoulon but Im a little bit lost I performed as per the build document, Do I have to do other pre-processing before I go to Cmake. i.e I have installed both Git and Cmake I am using Visual studio compiler

**Comment by nkosindlela** [comment]
now I got this error




$ git submodule update
Cloning into 'C:/Users/Samuel/openMVG/src/dependencies/cereal'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
fatal: clone of 'https://github.com/openMVG-thirdparty/cereal.git' into submodule path 'C:/Users/Samuel/openMVG/src/dependencies/cereal' failed

**Comment by pmoulon** [comment]
Since it explains that the remote hung up unexpectedly I think you have to try many time until it works.

The only pre-precessing is git cloning & submodule configuration.
Then you can go cmake & compile the configured solution under you Visual Studio.

**Comment by nkosindlela** [comment]
thanks Pmoulon, successful

**Comment by pmoulon** [comment]
Have fun ;-)
You can take a look to the doc while it will compile
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo
