### ISSUE TITLE
openMVG_main_openMVG2PMVS produces a flawed list.txt

### ISSUE THREAD

**Issue by kwmkwm** [openMVG/openMVG#582]
Hello,

When I run openMVG_main_openMVG2PMVS it produces a list.txt file that contains the original names of the image files used, rather than the filenames used in the visualize/ directory.  The listings also fail to include the visualize/ directory name.

Thank you.

**Comment by pmoulon** [comment]
This file is not used by pmvs but only required by cmvs (bundler like export).

**Comment by kwmkwm** [comment]
I think I understand my mistake now.  I misunderstood the tool chain.  Issue resolved.   Thank you.

**Comment by pmoulon** [comment]
you're welcome
