### ISSUE TITLE
[sfm/pipelines/global] Reduce memory usage (avoid feature copy for storing normalized coordinates) 

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#584]
We do not need to copy all the features to create a normalized feature cache, we can compute and use normalized features on the fly when we need them.

**Comment by mitjap** [comment]
I noticed that after this commit, number of tracks is significantly reduced.

**Comment by pmoulon** [comment]
Do you can share any comparison (before/after) on some dataset (3/4 datasets)?
Normaly this change must not have any bad effect.

I would think more that if a commit can have more effect than the one you depicted if would be this one
https://github.com/openMVG/openMVG/commit/5f75e143818b430962e120ecf9c525b658160e7a

**Comment by mitjap** [comment]
At this moment I have 2 datasets for comparison:
Comparison of number of tie points:
- 5 images: ~2.5k -> ~600
- 24 images: ~6.5k -> ~2.5k
- 3k images: ~5.5M -> 2.6M

Everything is the same except revert of this commit. I will take a closer look into the changes made to see what is the cause of it.

**Comment by pmoulon** [comment]
Thank you for your investigation.
Did you check if distortion is set to 0 in the input sfm_data.json file?

**Comment by mitjap** [comment]
It is.

**Comment by pmoulon** [comment]
Ok, so we must understand.
Perhaps there is a missing undistortion somewhere in the pipe, or an error.

**Comment by mitjap** [comment]
I looked for hours in the code with no progress. I think this part is beyond my understanding :D

**Comment by pmoulon** [comment]
if we don t understand by looking to the code, I think we will have to log some feature coordinates to see if they are identical before and after the change

**Comment by mitjap** [comment]
here is an example of result from small dataset (5 images) - before and after.


[cloud_and_poses_before_and_after.zip]
(https://github.com/openMVG/openMVG/files/601610/cloud_and_poses_before_and_after.zip)
[dataset.zip](https://github.com/openMVG/openMVG/files/601612/dataset.zip)
