### ISSUE TITLE
Compiling error in Windows using Visual Studio 2013

### ISSUE THREAD

**Issue by LingyuMa** [openMVG/openMVG#587]
I am compiling the source code in Windows using Visual Studio 2013 professional (64 bit), and it show me the following error:
'int openMVG::cameras::constexpr' : redefinition C:\openMVG\src\openMVG\cameras\Camera_Common.hpp	100	1	openMVG_matching_image_collection

**Comment by pmoulon** [comment]
You can use safely VS2015.
VS2013 can build OpenMVG, you must do a tiny trick and remove the constexpr

**Comment by LingyuMa** [comment]
I have downloaded vs 2015 (64 bit) and compile again. It shows me the following linking error:

jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function output_message
48>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format_message
48>jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_memory_mgr
48>tiff.lib(tif_getimage.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function TIFFRGBAImageOK
48>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
48>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
48>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function unixWarningHandler
48>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
48>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f
48>C:\openMVG_Build\Windows-AMD64-Release\Release\openMVG_sample_main_features_repeatability_dataset.exe : fatal error LNK1120: 8 unresolved externals
45>     Creating library C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_multiview_robustHomography.lib and object C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_multiview_robustHomography.exp
45>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
45>tiff.lib(tif_unix.obj) : warning LNK4217: locally defined symbol fprintf imported in function unixWarningHandler
45>tiff.lib(tif_dirinfo.obj) : warning LNK4049: locally defined symbol fprintf imported
45>tiff.lib(tif_fax3.obj) : warning LNK4217: locally defined symbol fprintf imported in function Fax3PrintDir
45>tiff.lib(tif_predict.obj) : warning LNK4049: locally defined symbol fprintf imported
45>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function output_message
45>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format_message
45>jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_memory_mgr
45>tiff.lib(tif_getimage.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function TIFFRGBAImageOK
45>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
45>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
45>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function unixWarningHandler
45>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
45>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f
45>C:\openMVG_Build\Windows-AMD64-Release\Release\openMVG_sample_multiview_robustHomography.exe : fatal error LNK1120: 8 unresolved externals
43>     Creating library C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_robustHomography_guided.lib and object C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_robustHomography_guided.exp
43>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
43>tiff.lib(tif_unix.obj) : warning LNK4217: locally defined symbol fprintf imported in function unixWarningHandler
43>tiff.lib(tif_dirinfo.obj) : warning LNK4049: locally defined symbol fprintf imported
43>tiff.lib(tif_fax3.obj) : warning LNK4217: locally defined symbol fprintf imported in function Fax3PrintDir
43>tiff.lib(tif_predict.obj) : warning LNK4049: locally defined symbol fprintf imported
43>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function output_message
43>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format_message
43>jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_memory_mgr
43>tiff.lib(tif_getimage.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function TIFFRGBAImageOK
43>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
43>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
43>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function unixWarningHandler
43>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
43>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f
43>C:\openMVG_Build\Windows-AMD64-Release\Release\openMVG_sample_robustHomography_guided.exe : fatal error LNK1120: 8 unresolved externals
44>     Creating library C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_robust_estimation_Homography.lib and object C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_robust_estimation_Homography.exp
44>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
47>     Creating library C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_features_kvld.lib and object C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_features_kvld.exp
47>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
44>tiff.lib(tif_unix.obj) : warning LNK4217: locally defined symbol fprintf imported in function unixWarningHandler
44>tiff.lib(tif_dirinfo.obj) : warning LNK4049: locally defined symbol fprintf imported
44>tiff.lib(tif_fax3.obj) : warning LNK4217: locally defined symbol fprintf imported in function Fax3PrintDir
44>tiff.lib(tif_predict.obj) : warning LNK4049: locally defined symbol fprintf imported
44>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function output_message
44>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format_message
44>jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_memory_mgr
44>tiff.lib(tif_getimage.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function TIFFRGBAImageOK
44>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
44>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
44>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function unixWarningHandler
44>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
44>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f
44>C:\openMVG_Build\Windows-AMD64-Release\Release\openMVG_sample_robust_estimation_Homography.exe : fatal error LNK1120: 8 unresolved externals
49>     Creating library C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_multiview_robustFundamental.lib and object C:/openMVG_Build/Windows-AMD64-Release/Release/openMVG_sample_multiview_robustFundamental.exp
49>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
47>tiff.lib(tif_unix.obj) : warning LNK4217: locally defined symbol fprintf imported in function unixWarningHandler
47>tiff.lib(tif_dirinfo.obj) : warning LNK4049: locally defined symbol fprintf imported
47>tiff.lib(tif_fax3.obj) : warning LNK4217: locally defined symbol fprintf imported in function Fax3PrintDir
47>tiff.lib(tif_predict.obj) : warning LNK4049: locally defined symbol fprintf imported
47>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function output_message
47>jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format_message
47>jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_memory_mgr
47>tiff.lib(tif_getimage.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function TIFFRGBAImageOK
47>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
47>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
47>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function unixWarningHandler
47>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
47>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f

Btw, I am using the develop branch.

**Comment by pmoulon** [comment]
Have you made a clean between VS2013 & VS2015 build?

The problem seems only a link error. Can you share your cmake report when you first run cmake with a fresh repo?

As you see here, develop branch compiles fine on VS2015 & VS2015 Win64 https://ci.appveyor.com/project/pmoulon/openmvg

**Comment by pmoulon** [comment]
Ok, I think it's because you have some jpeg & tiff libraries installed in your program files directory.
