### ISSUE TITLE
main_ComputeFeatures.exe crashed while computing features

### ISSUE THREAD

**Issue by TMwhuhan** [openMVG/openMVG#588]
I compiled OpenMVG in windows 7,without opencv. beside I don't know how to enable USE_OPENCV, and I can't find FindOpencv.cmake.

Anyway, It's finished successful. But the OPenMVG_main_ComputeFeatures.exe  crashed. It' works fine in ubuntu by the SfM_GlobalPipeline.py.  Can someone give me some advices? How to track the bug down？

**Comment by pmoulon** [comment]
Hi @TMwhuhan 

1. OpenCV is not required, you can use all OpenMVG features without using it.
BTW, if you want use it, you should download and compile OpenCV3 (or install it).
And then you add something like ```-DOpenCV_DIR="/PATH/github/itseez/opencv_Build"``` to the cmake openMVG command line

2. Windows crash for ComputeFeatures
-> It can a be a memory issue (did you used particular command line parameters?)
-> How much ram do you have, how large is your images?

**Comment by TMwhuhan** [comment]
thank you for reply~I will try again.

**Comment by pmoulon** [comment]
Any feedback to add?

**Comment by TMwhuhan** [comment]
No, I used the vs2015 and the code is work fine~ thank you for your working, it's great~ Is there a way to deal with big project, like airea photos taken by five lens. The width is 6000x4000, it took  much time in compute feature. Maby I should downscale the photo first, because the triangulation don't need too much Holmo points.

**Comment by pmoulon** [comment]
@TMwhuhan Yes, you can downscale the photos.
An upcoming version will be able to handle camera groups that are rigidly coupled & synchronized (it will help also to have something that run faster).
See here for the WIP: https://github.com/openMVG/openMVG/issues/580
