### ISSUE TITLE
ERROR：‘neato’ is not a valid command

### ISSUE THREAD

**Issue by wjy321114** [openMVG/openMVG#590]
I have build the program in Visual studio 2015 X64，and when I run the "SfM_GlobalPipeline.py" in Cygwin, there is something wrong in Step of openMVG_main_ComputeMatches.exe 
As far as I know,this error hapened in function "PairWiseMatchingToAdjacencyMatrixSVG"
How can I fix this problem?

![image](https://cloud.githubusercontent.com/assets/20318076/16756243/741717f6-4836-11e6-999e-dded392ebb11.png)

**Comment by pmoulon** [comment]
Hi Neato is an optional dependency used to display the image connection graph.
The process runs fine even you did not have install graphviz (neato)

**Comment by kschweikert** [comment]
even after installing graphviz, you need to set the PATH environment variable so it can find the graphviz executables. 
This video worked for me: https://www.youtube.com/watch?time_continue=122&v=q7PzqbKUm_4
except I set the system path variable to C:\Program Files (x86)\Graphviz2.38\bin\
