### ISSUE TITLE
Not detecting camera that is in the database - DJI FC

### ISSUE THREAD

**Issue by squeakus** [openMVG/openMVG#591]
Hi.
Thank you for making this amazing piece of software, I have just started using it but I have already generated amazing reconstructions from my datasets. Unfortunately I hit a problem with a particular set of photos where it couldn't parse the make out exif data. The make and model are DJI FC300X but it only found FC300X:

DJI_0400" model "FC300X" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_0401" model "FC300X" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
DJI_0402" model "FC300X" doesn't exist in the database

I am looking in the database:
/openMVG/src/openMVG/exif/sensor_width_database/ sensor_width_camera_database.txt

and it has worked with other datasets. It sounds very similar to [this](https://github.com/openMVG/openMVG/issues/243) 

but exiftool detects it correctly:
$ exiftool -make -model DJI_0400.JPG
Make                            : DJI
Camera Model Name               : FC300X

I fixed it by adding FC300X to the database but im not sure why it isn't picking up the DJI part.

**Comment by pmoulon** [comment]
Hi @squeakus 
As you see there I only use the camera model as key for the database https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L238
Some camera already embed in the camera maker name in the camera model, some does not...
BTW, I don't know why here the camera maker is not contained in your case 
=> https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt#L658

BTW, you found a fix.
Does the other reconstruction you performed correctly was made with the same drone?

**Comment by squeakus** [comment]
Hi Pierre,
No, the other reconstruction was done with a different camera. I simply added the line:
FC300X;6.16
to the database and it worked. It is a hack but the reconstruction worked perfectly after that. Thanks for your quick response.

**Comment by pmoulon** [comment]
Do you have other DJI dataset, in order to test if the "DJI" key is always missing or not...
If the DJI is always missing, it indicates I must update the DB as you have done (removing the DJI keywords)

**Comment by squeakus** [comment]
Hi Pierre, Unfortunately I do not and all images I found online have been touched up and resaved without the exif data. I will contact a colleague who also has one to see if I can get some additional images.

**Comment by jpwhitney** [comment]
I have recently acquired some drone footage taken with a DJI FC300X and when trying to process the images with a recently cloned and compiled openMVG, last week, I encounter the error "... model "FC300X"  doesn't exist in the database.  Please consider add your camera model...".
From this it appears that the DJI key is missing.  I have another sequence of photos taken with the same device that I could check, but I strongly suspect that this is also the case with that set.
Could it be that versions of DJI camera firmware differ in their handling of exif data, where some add DJI key and some do not?

**Comment by pmoulon** [comment]
That is possible that some DJI camera firmware does a different job.
Please consider in the database to have:
```
DJI FC300X;6.16
FC300X;6.16
```
So add the missing one to yours.

**Comment by pmoulon** [comment]
Does the proposed solution solved your problem?

**Comment by squeakus** [comment]
Hi Pierre,
I have tested it and yes it does. thanks for your help.
regards
Jonathan

**Comment by pmoulon** [comment]
So, you confirm the fact that depending of the DJI camera firmware you can have DJI FC300X or FC300X in the EXIF metadata.

**Comment by squeakus** [comment]
yes, with my phantom 3 professional it is just FC300X

**Comment by pmoulon** [comment]
Thank you.

**Comment by pmoulon** [comment]
Solved by https://github.com/openMVG/openMVG/commit/6ccdd80f08412050e83946a425c474aedfbfde2f

**Comment by Zuxin** [comment]
@pmoulon Hello,My camera is DJI FC230 in the EXIF metadata.I can't found it on database.Is there any way to get the width?

**Comment by architech-c** [comment]
My camera is DJI FC230 in the EXIF metadata. What's the sensor width? Any database with this info? @Zuxin did you get the width?
