### ISSUE TITLE
Is it possible to use CUDA to accelerate feature detection and matching in openMVG?

### ISSUE THREAD

**Issue by LingyuMa** [openMVG/openMVG#595]
I want to know if it is possible to use Cuda for feature detection and matching?

**Comment by pmoulon** [comment]
Hi @LingyuMa,
Since openMVG use on-disk saved features files (in the OpenMVG format), you can plug & use any feature detection method you can think about (CPU-GPU, cloud based computation...).
For example you can use OpenCV GPU feature modules, the SiftGPU,... or your own hybrid method.

Use the following in OpenMVG matching interfaces should be very easy to add:
http://answers.opencv.org/question/60691/error-on-cvcudadescriptormatcherknnmatch/

BTW, any contribution is welcomed, a generic K-nn GPU matcher would be a great addition!

**Comment by pmoulon** [comment]
@LingyuMa Does the answer is sufficient or do you need additional info?
- If the answer was sufficient, please close the issue.

**Comment by LingyuMa** [comment]
@pmoulon  Thank you for your answer, I'll try something to see how it works.

**Comment by mdaiter** [comment]
@LingyuMa I just integrated the GPU L2 matcher in my library. If you pull, you'll be able to test it out.

**Comment by LingyuMa** [comment]
Hi,

Could you please tell me what kind of matching algorithm you are using? Is this brute force matching or approximate k nearest neighbors based on randomized kd tree?

**Comment by mdaiter** [comment]
@LingyuMa this is brute force matching.

**Comment by jean59** [comment]
this is the ouput of testing SiftGPU on sceaux castle images, on ubuntu 18.04, and my desktop...
ça ne vaut pas le coup ;-)

##########################################################################
Shader not supported by your hardware!
Framebuffer object not supported!
GL_ARB_texture_rectangle not supported!
Switch from OpenGL to CUDA
NOTE: changing maximum texture dimension to 32768
IFTGPU
[GPU VENDOR]:	NVIDIA Corporation 1362MB
TEXTURE:	32768
[SiftGPU Language]:	CUDA
Image size :	1416x1064
Image loaded :	/home/jean/Téléchargements/openMVG/src/openMVG_Samples/imageData/SceauxCastle/100_7101.jpg
[Load Input Image]:	0.015
[Allocate Pyramid]:	1416x1064
[Allocate Pyramid]:	224MB
[Initialize Pyramid]:	0.067
[Build    Pyramid]:	0.01
<Gradient, DOG  >	0.005
<Get Keypoints  >	0.004
[Detect Keypoints]:	0.009
<Copy Grad/Orientation>	0
#Features:	3156
[Get Feature List]:	0.005
[Feature Orientations]:	0.003
#Features MO:	3651
[MultiO Feature List]:	0
[Download Keypoints]:	0
[Get Descriptor]:	0.016
[RUN SIFT]:	0.126

Image size :	1416x1064
Image loaded :	/home/jean/Téléchargements/openMVG/src/openMVG_Samples/imageData/SceauxCastle/100_7102.jpg
[Load Input Image]:	0.016
[Initialize Pyramid]:	0
[Build    Pyramid]:	0.013
<Gradient, DOG  >	0.004
<Get Keypoints  >	0.004
[Detect Keypoints]:	0.008
<Copy Grad/Orientation>	0
#Features:	3100
[Get Feature List]:	0.006
[Feature Orientations]:	0.002
#Features MO:	3600
[MultiO Feature List]:	0.001
[Download Keypoints]:	0
[Get Descriptor]:	0.016
[RUN SIFT]:	0.062

NOTE: changing maximum texture dimension to 32768
[SiftMatchGPU]: CUDA

1573 sift matches were found;
siftgpu::runsift() cost time=**0.390641**
##########################################################################
