### ISSUE TITLE
openMVG Debian compilation fails

### ISSUE THREAD

**Issue by DerekWilliamHunter** [openMVG/openMVG#597]
I'm following the BUILD instructions to compile openMVG on Debian but it fails with the attached errors. I'm a C programmer rather than a C++ programmer and I'm struggling to interpret the output. Can anyone help?

[out.txt](https://github.com/openMVG/openMVG/files/383733/out.txt)

Please let me know if I need to include any additional information.

**Comment by pmoulon** [comment]
Can you tell if you are building master or the develop branch?

**Comment by DerekWilliamHunter** [comment]
```
dwh@dhp78:~/source/openMVG$ git branch
* master
```

```
dwh@dhp78:~/source/openMVG$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pmoulon** [comment]
Can you try the develop branch?
```
git checkout develop
git submodule init
git submodule update
Then redo cmake and cmake from your build dir
```

**Comment by DerekWilliamHunter** [comment]
OK - I'll do that now...

**Comment by DerekWilliamHunter** [comment]
Did I do this correctly?

```
git checkout develop
git submodule init
git submodule update
cd openMVG_build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
make
```

It still failed :(

[out2.txt](https://github.com/openMVG/openMVG/files/383871/out2.txt)

**Comment by pmoulon** [comment]
Thank for the additional test, you performed it in the right way.
@rperrot Do you have an idea?

**Comment by pmoulon** [comment]
@DerekWilliamHunter Can you try to change this line   https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching/matching_interface.hpp#L29 to
```virtual ~ArrayMatcher() {};```
Or if it still make a compilation error to
```virtual ~ArrayMatcher() throw() {};```

**Comment by DerekWilliamHunter** [comment]
I made the first change and compilation went further but still failed...

[out3.txt](https://github.com/openMVG/openMVG/files/383902/out3.txt)

I included the 'throw()' and it still failed...

[out4.txt](https://github.com/openMVG/openMVG/files/383906/out4.txt)

**Comment by pmoulon** [comment]
Ok out3.txt went further.
Seems like the default destructor are not liked by your compiler.

So I think if we change the following from "= default" to "{}" it should fix your problem.
```
./src/openMVG/features/regions.hpp:  virtual ~Regions() = default ;
./src/openMVG/features/image_describer.hpp:  virtual ~Image_describer() = default ; 
./src/openMVG/matching/regions_matcher.hpp:  ~RegionsMatcher() = default ;
./src/openMVG/matching/matching_interface.hpp:  virtual ~ArrayMatcher() = default ;
./src/openMVG/color_harmonization/selection_fullFrame.hpp:  ~commonDataByPair_FullFrame() override = default ; 
./src/openMVG/color_harmonization/selection_matchedPoints.hpp:  ~commonDataByPair_MatchedPoints() override = default ; 
./src/openMVG/color_harmonization/selection_interface.hpp:  virtual ~commonDataByPair() = default ; 
./src/openMVG/color_harmonization/selection_VLDSegment.hpp:  ~commonDataByPair_VLDSegment() override = default ; 
./src/openMVG/matching_image_collection/Matcher.hpp:  virtual ~Matcher() = default ;
./src/openMVG/cameras/Camera_Intrinsics.hpp:  virtual ~IntrinsicBase() = default;
./src/openMVG/cameras/Camera_Pinhole.hpp:    virtual ~Pinhole_Intrinsic() override = default;
```
Do you want give a try to the solution I have proposed, or do you can wait that I make the modification and push a new branch to let you test?

**Comment by DerekWilliamHunter** [comment]
Could you make the change and push a new branch? I'm not confident enough with git to make changes myself. I will do some reading and practising now.

Thank you very much for your help!

**Comment by pmoulon** [comment]
I pushed some modification, let's try it
```
git fetch
git checkout develop_gcc_looser_throw_specifier
cd openMVG_build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
make
```

**Comment by DerekWilliamHunter** [comment]
To confirm the new branch after 'fetch' and 'checkout':

```
dwh@dhp78:~/source/openMVG$ git branch
  develop
* develop_gcc_looser_throw_specifier
  master
```

After 'cmake' and 'make':

[out5.txt](https://github.com/openMVG/openMVG/files/383995/out5.txt)

**Comment by pmoulon** [comment]
Thank you, we have some progress.
Did not understand why you have many error messages, while we don't have any...
Perhaps C++11 is not enabled in the right way for your compiler version.

I will ask some feedback from @rperrot on your error.

**Comment by DerekWilliamHunter** [comment]
I will check to see if I can upgrade my gcc version.
I might need to upgrade from Debian Wheezy to Debian Jessie

**Comment by pmoulon** [comment]
You can in the meantime create a virtual machine with Debian Jessie and test OpenMVG inside it ;-)

**Comment by rperrot** [comment]
Just a few precisions : 

full c++11 support is enabled since gcc 4.8.1 and in the details : 
- throw support is enabled in gcc 4.8 (to be more precise, the removal of throw)  
- default support is enabled in gcc 4.8 

So since you have gcc 4.7.2, you could not compile without modifying the code. 

@DerekWilliamHunter Just to be sure c++11 is requested, type make VERBOSE=1 and look if there exist an argument on a compilation line : "-std=c++11" (I just want to check if cmake correctly define c++11 on your environment)

**Comment by pmoulon** [comment]
Make me think that we must update this line to be coherent: https://github.com/openMVG/openMVG/blob/master/BUILD#L24
I will take care of that.

**Comment by pmoulon** [comment]
Since we know the reason of the build failure, and now that we have updated the build doc accordingly, I will close the issue.
Thank you @DerekWilliamHunter for your time and for your issue report :+1

**Comment by DerekWilliamHunter** [comment]
To confirm that this issue has been resolved: I upgraded my Debian system from Wheezy to Jessie and have successfully compiled openMVG with gcc 4.9.2

I will run the tests tomorrow. 

I would like to thank everyone for their help :)

**Comment by pmoulon** [comment]
You are welcome.
Dont hesitate to look to the Doc and ask questions.
Have fun.
