### ISSUE TITLE
Can OpenMVG be used for a SLAM like project?

### ISSUE THREAD

**Issue by hilman-dayo** [openMVG/openMVG#601]
I am new into 3D reconstruction. I have a project, in where by using a monocular camera that is mounted in front of a car, I want to construct the 3D view in front of it. It is kind of SLAM, but I don't need to record/save all the path that the car have been through (you can say that I want to localize the camera without all the mapping stuff). I just want a live update of the scene in front of the car in 3D. I have been using OpenCV, but it is not that focused on 3D reconstruction. 

Can this library achieves the things that I want to do? Thanks.

**Comment by pmoulon** [comment]
OpenMVG is not a SLAM library, there is some tools to implement a SLAM like tool.
But, since you want to consider only a tiny count of frame, you can use the existing SfM toolchains and use the matching in video mode to get things faster.
Don't hesitate to share to me some dataset that I can run for you and to continue the discussion there in order to let us better understand your needs.

**Comment by hilman-dayo** [comment]
I will ask more. For now, I am in the middle of installing the library and then, want to explore it a bit first.

**Comment by hilman-dayo** [comment]
Can I achieve something like this with this library?
https://www.youtube.com/watch?v=QqnInxq1g0w&t=1m31s

**Comment by pmoulon** [comment]
There is tools to build the 3D reconstruction (sparse point cloud + camera position) & there is a localization module to localize the camera inside an existing reconstruction.
There is also a sample that show how to track feature using the OpenCV Pyramidal optical flow (as it's certainly done in the video you shared)

You have some doc about SfM here http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/
Please note that there is ready to use python script that run all the tools for you on an image directory. Just be sure that you have valid intrinsic data (EXIF metadata), else you can provide the pixel focal length manually.

**Comment by pmoulon** [comment]
BTW, perhaps it can be interesting to review ORB/ORB2 slam librairies too for your project.

**Comment by pmoulon** [comment]
Feel free to reopen, if you have any other questions.
