### ISSUE TITLE
Problems of using PMVS2 with OpenMVG

### ISSUE THREAD

**Issue by hilman-dayo** [openMVG/openMVG#605]
These are the steps I've made:
Following the documentation, first, I've executed this command (I am inside `openMVG_Build/sofftware/SfM`):
  
     python SfM_SequentialPipeline.py ImageDataset_SceauxCastle/images/ testdir

Then, I've executed this (I've already copied the openMVG_main_openMVG2PMVS executable into `openMVG_Build/sofftware/SfM`): 

    ./openMVG_main_openMVG2PMVS -i testdir/matches/sfm_data.json -o testdir/

and then, after `cd` to the directory of my `pmvs2` executable, I've executed this:

    ./pmvs2 /home/hilmansfm/openMVG_Build/software/SfM/testdir/PMVS/ pmvs_options.txt

This is the output:

```
--------------------------------------------------
--- Summary of specified options ---
# of timages: 0 (range specification)
# of oimages: 0 (enumeration)
level: 1  csize: 2
threshold: 0.7  wsize: 7
minImageNum: 3  CPU: 8
useVisData: 1  sequence: -1
--------------------------------------------------
Reading images: 
done
adding seeds 
done
---- Initial: 0 secs ----
Total pass fail0 fail1 refinepatch: 0 0 0 0 0
Total pass fail0 fail1 refinepatch: -nan -nan -nan -nan -nan
Expanding patches...
---- EXPANSION: 0 secs ----
Total pass fail0 fail1 refinepatch: 0 0 0 0 0
Total pass fail0 fail1 refinepatch: -nan -nan -nan -nan -nan
FilterOutside
mainbody: 
Gain (ave/var): 0 0
0 -> 0 (-nan%)	0 secs
Filter Exact: 
0 -> 0 (-nan%)	0 secs
FilterNeighbor:	FilterGroups:	STATUS: 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 
Expanding patches...
---- EXPANSION: 0 secs ----
Total pass fail0 fail1 refinepatch: 0 0 0 0 0
Total pass fail0 fail1 refinepatch: -nan -nan -nan -nan -nan
FilterOutside
mainbody: 
Gain (ave/var): 0 0
0 -> 0 (-nan%)	0 secs
Filter Exact: 
0 -> 0 (-nan%)	0 secs
FilterNeighbor:	FilterGroups:	STATUS: 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 
Expanding patches...
---- EXPANSION: 0 secs ----
Total pass fail0 fail1 refinepatch: 0 0 0 0 0
Total pass fail0 fail1 refinepatch: -nan -nan -nan -nan -nan
FilterOutside
mainbody: 
Gain (ave/var): 0 0
0 -> 0 (-nan%)	0 secs
Filter Exact: 
0 -> 0 (-nan%)	0 secs
FilterNeighbor:	FilterGroups:	STATUS: 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 
---- Total: 0 secs ----
```

As you can see, there is something wrong. Have tried to open the outputted `.ply` file inside `PMVS/models` with meshlab but got zero (no 3D reconstruction at all). What is wrong? Since I am still new, I have a quite hard time trying to figure out the problems.

**Comment by pmoulon** [comment]
It seems that your PMVS2 scene is empty (no image)

Did you look to the output of OpenMVG for your dataset (Number of find camera in 3D #Pose X)?

Did you look to the file cloud_and_poses.ply in order to see the shape of the scene?

**Comment by hilman-dayo** [comment]
This is the output (about at the end part of it) when I've executed  `python SfM_SequentialPipeline.py ImageDataset_SceauxCastle/images/ testdir`


```
Structure estimation took (s): 0.66.
#landmark found: 4222
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 11
 #poses: 10
 #intrinsics: 1
 #tracks: 4222

```

And how to inspect the shape of the scene by looking at the file cloud_and_poses?

**Comment by pmoulon** [comment]
You must use a software like Meshlab or CloudCompare to see the cloud_an_poses.ply file.

**Comment by hilman-dayo** [comment]
I have opened the cloud_and_poses.ply file. This is the screenshot of it.
![screenshot 2016-08-11 12 36 04](https://cloud.githubusercontent.com/assets/16521877/17578134/4f39629e-5fc0-11e6-8007-6168b7685092.png)

Then, I have executed this command `./openMVG_main_openMVG2PMVS -i testdir/matches/sfm_data.json -o testdir/`

This is the contents of the `PMVS/pmvs_options.txt`file:

```
level 1
csize 2
threshold 0.7
wsize 7
minImageNum 3
CPU 8
setEdge 0
useBound 0
useVisData 1
sequence -1
maxAngle 10
quad 2.0
timages -1 0 0
oimages 0
```
./pmvs2 /home/hilmansfm/openMVG_Build/software/SfM/testdir/PMVS/ pmvs_options.txt
Also, inside the `PMVS/visualize` folder, there are no images at all. Is this normal? Could this be the source of the problem?

**Comment by pmoulon** [comment]
It's seems that there is a problem when you try to export the scene to PMVS.
Do you have some file generated in the output directory?
Can you share to me your sfm_data.bin file?

**Comment by hilman-dayo** [comment]
Inside the `SfM_SequentialPipeline.py` output directory, I have `matches` and `reconstruction_sequential` directories with tons of files in it. 

Inside the output of  `openMVG_main_openMVG2PMVS` directory, I have:

1. `models` directory
2. `txt` directory
3. `visualize` directory
4. `bundle.rd.out` file
5. `list.txt` file
6. `pmvs_options.txt` file
7. `vis.dat` file

Since I am also new in this, I am not sure ifthe  problem is with the OpenMVG, or the `PMVS2` software that I am using right now. But, following the tutorial [here](http://www.di.ens.fr/pmvs/documentation.html), I managed to build the 3D reconstruction of the hall (hall is a data provided with the `PMVS2` software).

**Comment by bryanphua** [comment]
Having the same issue may I know how u solved this

**Comment by hilman-dayo** [comment]
This is long ago, so, I can't remember. However, I think I can't managed to solve them. Sorry.
