### ISSUE TITLE
Ask for help about the coordinate system of the sparse point cloud obtained by the openMVG_main_GlobalSfM

### ISSUE THREAD

**Issue by Duwenxiang** [openMVG/openMVG#608]
dear pmoulon,I am a user of the OpenMVG.To be honest, OpenMVG is a good and useful system.When I use the openMVG_main_GlobalSfM software to get sparse piont cloud for several times, I find the World Coordinate System it used is different(the source images are the same). I want to know how to determine the coordinate system used in this software.I look forward to your reply.

**Comment by pmoulon** [comment]
Dear @Duwenxiang,
Thank you for your kind words about OpenMVG.

Regarding your question:
All SfM results are up to a scale of the reality, and so since random numbers are used for sampling and generating model hypothesis all run does not leads exactly to the same results.

If you want to have a given fix coordinates system you must use GCP (Ground Control Points, or GPS position for your images).

OpenMVG default camera settings will maintain (approximately) the first camera with (Z modeling depth, Y down, X right), since the BA can change this default initialization a bit.

![image](https://cloud.githubusercontent.com/assets/3235050/17699895/b6b4cba0-63c3-11e6-9f4b-a6afee93af2a.png)

**Comment by Duwenxiang** [comment]
Thank you very much for your reply. I'm very interested in this issue. Now, I have two other questions as the followed.
 The first one: I can't get the GPS information of the source images.  I want to have a fixed coordinates system. Would you like to give me some more detailed hints on how to use the GCP.
The second: 
If I have given a pixel coordinate on one or more images, is it possible to get the three-dimensional coordinate( on the World Coordinate System of the sparse point cloud) corresponding to this given pixel location? If it's possible, Could you give me some hints on how to get it.
Looking forward to your reply.

**Comment by pmoulon** [comment]
Regarding GCP: See the help http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

Regarding your second point, I did not understand exactly what you mean.
I think you ask to have the 3D coordinate corresponding for each pixel.
SfM produce sparse point cloud, if you want a more dense reconstruction you should connect OpenMVG results to some MVS software (http://openmvg.readthedocs.io/en/latest/software/MVS/MVS/)
BTW, here some explaination:
- From one pixel you can get only the direction of view (bearing vector).
- If you have two corresponding pixel you can compute a triangulation and obtain the 3D point.
- If you select a feature point that already have some 3D coordinates, you can obtain the information you want.

**Comment by Duwenxiang** [comment]
dear pmoulon. Think you very much.I have run the GCP GUI successfully.The QT libraries the OpenMVG used is QT4. Fortunately，I haved run it successfully using QT5.7.0(only add some  #include<header file >,as the picture followed)
![image](https://cloud.githubusercontent.com/assets/18410212/17810052/50aa67ac-664d-11e6-9182-6afc24bee418.png).I want to know when to run the GCP GUI. after 
openMVG_main_ComputeMatches or after openMVG_main_ComputeFeatures.

**Comment by pmoulon** [comment]
I advise you to run once you have your 3D scene.
So you can run it on an already computed scene, then add your GCP 3D data, and their 2D image visibility and then compute the rigid registration.

**Comment by Duwenxiang** [comment]
Think you so much for your help.The following question may be my last question.
![image](https://cloud.githubusercontent.com/assets/18410212/17812167/77f99bf6-6658-11e6-9ec4-954e3f66c50c.png). I want to know what factors affect the CP tringulation error and how to get results with small CP tringulation error.When I Perform the registration, 
a message ("Invalid triangulation") appear.I find that the  CP tringulation error is so big as the followed(two images and each with 3  Control points). 
![image](https://cloud.githubusercontent.com/assets/18410212/17812453/c148436a-6659-11e6-942b-47530ab53df2.png)

**Comment by pmoulon** [comment]
Are you sure you compute corresponding points (with the correct ID).

Even you clicked by hand the residual error should not be more than 4 or 2 pixels.

**Comment by Duwenxiang** [comment]
dear pmoulon.I  have done another several tests.But the residual error are also so big. I'm sure I compute corresponding points.I guess that the function (Vec3 Triangulation::compute(int iter) ) is possible to get a wrong position X (). I find this function is to get the  X using iterative weighted linear least squares method,and the default value of the  iter is 3. Can we make sure to get a correct result after three iterations. Can you give me some details about the algorithm ( about the function "Vec3 Triangulation::compute(int iter) const")

**Comment by pmoulon** [comment]
@Duwenxiang It's very strange that the triangulation does not lead to a small residual, the method you depicted is used in a lot of existing code without problem.
Can you share the dataset and your resulting sfm_data.json?
Perhaps the bearing angle are very small and so the triangulation is not good.

**Comment by Duwenxiang** [comment]
@pmoulon Yes,I can share my dataset and the sfm_data.json.Can you give me your personal email address.I can share the dataset to you but I don't want to open the dataset to other people recently.Yesterday, I also considered this factor(the bearing angle are  small).This may be related to the    residual error.

**Comment by pmoulon** [comment]
@Duwenxiang I would like to recommend to try this solution in a scene where you know that the bearing angle are not small. Small angles between bearing vectors lead to very unstable triangulation
