### ISSUE TITLE
Compilation error on Mint/Ubuntu 14.04

### ISSUE THREAD

**Issue by tw0023** [openMVG/openMVG#614]
Hi, I was trying to build openMVG on Mint/Ubuntu 14.04 platform but encountered some compilation errors, which seems to be related with gcc (4.7): 

/usr/include/c++/4.7/bits/stl_tree.h:130:12: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const unsigned int; _T2 = std::unique_ptr<openMVG::features::Regions>; std::pair<_T1, _T2> = std::pair<const unsigned int, std::unique_ptr<openMVG::features::Regions> >]’

/usr/include/c++/4.7/bits/stl_pair.h:119:17: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = openMVG::features::Regions; _Dp = std::default_delete<openMVG::features::Regions>; std::unique_ptr<_Tp, _Dp> = std::unique_ptr<openMVG::features::Regions>]’
In file included from /usr/include/c++/4.7/memory:86:0,

/usr/include/c++/4.7/bits/unique_ptr.h:262:7: error: declared here

Thanks in advance!

**Comment by pmoulon** [comment]
Since unique_ptr is supported from [GCC 4.4.7](https://users.dune-project.org/projects/main-wiki/wiki/C++11_feature_support_matrix) I have no idea yet.

@rperrot any idea?

**Comment by rperrot** [comment]
Just to make some investigations, could you give us more details : 
1) Could you give us a more complete message about the compilation (I want to know where is the error, is it openMVG or openMVG's dependencies related ?)
2) Which branch did you used ? 

@pmoulon First impression, maybe it's a STL related issue (c++11 is not fully supported on gcc, maybe a const or a ref issue).

**Comment by donlk** [comment]
Ran into this problem myself with GCC 4.7. Only GCC > 4.8 supports the fully range of c++11 features, and the move operations are quite messy. A number of alterations in regards to unique pointer handling need to be applied in OpenMVG to make it compatible.
[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53584](issue)

I think the posted issue is from the sfm_*_provider source files.

**Comment by pmoulon** [comment]
As said by @donlk:

Please update your GCC, some recent modification make OpenMVG require a GCC >=4.8
The build instruction where updated in the develop branch see here https://github.com/openMVG/openMVG/blob/develop/BUILD#L24

**Comment by tw0023** [comment]
Thanks for the replies! Using GCC-4.8 solved the problem
