### ISSUE TITLE
get the camera view direction

### ISSUE THREAD

**Issue by chuqiaodev** [openMVG/openMVG#616]
Hi @pmoulon,

Thank you very much for providing the open source. It is pretty nice and I made lots of beautiful 3D models through it. Currently I want to get the camera view direction (the direction camera facing to) from the outputs of the openMVG library (e.g. sfm_data.bin). I am not familiar with the 3D multi-view geometry, cloud you please teach me how to do that? Also if you have time cloud you tell me the definition of the coordinate system used in OpenMVG and how to make up the rotation matrix for each camera using the sfm_data.bin such as
{
            "key": 73,
            "value": {
                "rotation": [
                    [
                        -0.91350923442115894,
                        0.24239908802437118,
                        -0.32671633070941108
                    ],
                    [
                        -0.27046249682534534,
                        0.23804855523963567,
                        0.93283595726114787
                    ],
                    [
                        0.30389293581501392,
                        0.94051877571544262,
                        -0.15189969087676464
                    ]
                ],
                "center": [
                    2.2368926693694289,
                    0.74967088849495744,
                    0.49960611951658906
                ]
            }
        }

Thanks

**Comment by pmoulon** [comment]
Hi @chuqiaodev 
As you saw in the source code, each vector represent here the row of the rotation matrix.
https://github.com/openMVG/openMVG/blob/master/src/openMVG/geometry/pose3.hpp#L149

If you want the camera direction, you simply have to multiply the unit Z direction to the rotation matrix:

```const Vec3 lookingDir = R * Vec3(0,0,1);```
Then you draw this looking direction from the camera center C.

**Comment by chuqiaodev** [comment]
Hi @pmoulon,

Sorry for late reply. I really appreciate your kind and quick reply. Will close this issue.

**Comment by chuqiaodev** [comment]
Hi @pmoulon 

I use the way you show above to compute the camera direction. The test images are captured from a snake pattern with 65 pitch down angle. The reconstructed 3D model is promising, but the view direction I computed is not correct, e.g., the direction should face forward but the estimation face backward. Do you have sense why this happen?

Thanks very much.

**Comment by pmoulon** [comment]
Try ```const Vec3 lookingDir = R.transpose() * Vec3(0,0,1);```

**Comment by gesong1982** [comment]
This works! Thanks.

**Comment by chuqiaodev** [comment]
This time it works, thanks @pmoulon
