### ISSUE TITLE
Checking image projection alignment quality

### ISSUE THREAD

**Issue by KevinCain** [openMVG/openMVG#617]
I'm using OpenMVG's Meshlab [exporter](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2MESHLAB.cpp) to visualize camera projection on OpenMVG's reconstructions.

The undistorted camera image doesn't align very closely to point clouds from OpenMVG; here's an image from Meshlab in which an undistorted image from the [Sceaux](https://github.com/openMVG/ImageDataset_SceauxCastle) image set is projected on 'robust.ply':  [openmvg_meshlab_export](https://cloud.githubusercontent.com/assets/5424003/17986971/4144465a-6ad2-11e6-9050-449455418d8f.jpeg)

Here is a .zip file, if you would like to duplicate my test:
[Meshlab.zip](https://github.com/openMVG/openMVG/files/438117/Meshlab.zip)

This contains the source and undistorted images, and a Meshlab .mlp file 'OpenMVG-Meshlab-camera-example.mlp', which contains three projections of the same view for comparison:
- 9-original-image -- the source image projected on view 9 from the above data set
- 9-undistorted -- the undistorted image projected on view 9 from the above data set, with principal points at center of the images as written in the Meshlab exporter:  `<< " CenterPx=\"" << cam->w() / 2.0 << " " << cam->h() / 2.0 << "\""`
- 9-undistorted-matrixPP -- the same as the above, but using principal point offsets from intrinsic matrix K (as per Hartley & Zisserman), modified as:  `<< " CenterPx=\"" << K( 0, 2 ) << " " << K( 1, 2 ) << "\""`

The change in principal point values doesn't change the projection in Meshlab; Meshlab's camera handling is summarized [here](http://vcg.isti.cnr.it/~cignoni/newvcglib/html/shot.html).

What would you suggest to improve the visualization of these projections?

I assume that OpenMVG's internal projection must be more coherent (perhaps within a few pixels?) -- can someone demonstrate that this is the case?

**Comment by pmoulon** [comment]
Hi @KevinCain 
Sorry for the late answer.

The problem can comes:
- from the OpenMVG2Meshlab exporter (in the doc they said that " If a calibrated camera is used, then all the intrinsic parameters should be known in advance." So perhaps the exporter forgot to export some data).
- from Meshlab (perhaps the API support an center pixel and does not really use it later on)

Have you tried to shift the image to have the principal point becoming the center of the images?

-> You can also force OpenMVG to do not optimize the center of projection and keep w/2,h/2 by using "-f ADJUST_FOCAL_LENGTH|ADJUST_DISTORTION" on main_IncrementalSfM or main_GlobalSfM.
So the image center will left unchanged.
