### ISSUE TITLE
[exif] Add GIT2 camera to the sensor width database

### ISSUE THREAD

**Issue by pulquero** [openMVG/openMVG#620]
Please could you add the following sensor/camera to your database:

Sony Exmor R IMX206 (used in Gitup Git2 action camera amongst others)
Spec: http://www.sony.net/Products/SC-HP/new_pro/december_2013/imx206_e.html
diagonal 7.77mm (from spec)
width 6.216 mm (calculated)
height 4.662 mm (calculated)

**Comment by pmoulon** [comment]
I will consider to add this new camera to the sensor database.
In order to do so, can you please tell me the name that appears in the "Camera Model Name:" exif field?

Please tell me if you see "Sony Exmor R IMX206" or just "Exmor R IMX206"

**Comment by pulquero** [comment]
It shows the camera model name as GIT2.

**Comment by pmoulon** [comment]
Can you try a tiny scene with some images once you added GIT2;6.216 to the database file?
Just to check if the information is right.

**Comment by pmoulon** [comment]
@pulquero [Git2camera](http://www.gitup.com/gitup-action-camera/46-git2standard-packing-with-f28-435mm-16m-hfov-72-13g-lens.html) was not added to the sensor width database.
Feel free to perform some reconstruction and share the results here or on G+ ;-)

**Comment by pulquero** [comment]
Thanks
