### ISSUE TITLE
GCP UI with SfM Pipeline

### ISSUE THREAD

**Issue by morgand536** [openMVG/openMVG#624]
I have researched a bit for the GCP Qt UI and I found that the UI will modify the SfM_data.bin for the GCP registration.
Which part of the pipeline is the GCP supposed to be registered? 
And how the GCP will apply to the point cloud?

Thanks.

**Comment by pmoulon** [comment]
Hi @morgand536 
Cameras and the scene structure will be moved to best fit the GCP triangulation.
See here http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

**Comment by morgand536** [comment]
So if i want to do OpenMVG + OpenMVS with GCP,
I can arrange the pipeline like this?:
1. OpenMVG
2. GCP Registration
3. Straight to OpenMVS?

**Comment by pmoulon** [comment]
Right!
