### ISSUE TITLE
[ui_openMVG_control_points_registration] Feature request and bug

### ISSUE THREAD

**Issue by FlachyJoe** [openMVG/openMVG#627]
Hi,
F.R. :
can you please add the possibility to specify the project to open on the command line?
BUG :
If its path contains accent, the project file isn't opened and "Cannot open the provided sfm_data file." is returned (Debian with utf-8 file system).

Thanks.
Florian

**Comment by pmoulon** [comment]
Solution:
1. `can you please add the possibility to specify the project to open on the command line?`
Please use the interface
2. `If its path contains accent, the project file isn't opened and "Cannot open the provided sfm_data file." is returned (Debian with utf-8 file system).`
Feel free to update the code and make a PR. Or to use a path that does not have accent.
