### ISSUE TITLE
Is OpenMVG a good choice for multiple camera pose estimation?

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#628]
Hello, I'm currently working on an application where multiple cameras move simultaneously and the images captured are supposed to be used to compute relative poses between the cameras as they're in motion. The cameras are calibrated. As of now, I am doing the processing offline, using OpenCV's CPU based feature detection and matching algorithms and PNP; and I am looking for a more robust implementation as well as something preferably GPU accelerated to use it in real time. Would OpenMVG be a good option for this scenario? Thanks!

**Comment by pmoulon** [comment]
Hi @saihv 

- GPU acceleration:
  - There is not yet GPU things in OpenMVG, but you can easily plug OpenCV GPU algorithm in the pipelines if you need it.

- Multiple camera (rigid camera rig) 
  - As you will see it here https://github.com/openMVG/openMVG/issues/580 there is some work to deals with 'non central cameras'. What you want to perform is resection of non central cameras, you can perform it easily by using precalibrated camera in OpenMVG, generating the bearing vectors & then call the method of your choice thank to OpenGV.

Hoping it helps.
Looking forward continue the discussion.

**Comment by saihv** [comment]
Hi @pmoulon,

Thanks for the comment. I might have worded it wrong when I said 'simultaneously'; I am not using a rigidly coupled camera rig: in fact, the individual cameras can move however they want (let's say still under the constraint that there are common features between their images, and with synchronized image capture), and I am interested in the computing 6 DoF poses of the cameras as they are moving.

**Comment by pmoulon** [comment]
Ok, so you want to localize some camera into an existing scene:
You can take a look to this sample: http://openmvg.readthedocs.io/en/latest/software/localization/localization/

Soon it must be updated and be able to deal with your test case:
https://github.com/openMVG/openMVG/issues/618#issuecomment-247068865

**Comment by saihv** [comment]
Thanks a lot! I just started looking into the Localization sample, as well as the other matching/relative pose estimation samples in the code, the new update seems quite relevant to what I want to do. Just one last question: would this approach work with a metric point cloud, similar to the PNP problem, given a reconstruction scaled up to metric units, can we find the poses of the cameras in the same units?

**Comment by pmoulon** [comment]
Since the scene scale will be unchanged, the answer is yes, the camera pose will be absolute in the unit of the input scene.

**Comment by saihv** [comment]
Thank you for the information: I'll try to test some of my datasets with this framework. Closing this question.

**Comment by pmoulon** [comment]
@saihv Don't hesitate to ask more feedback if necessary at openmvg-team[AT]googlegroups.com
