### ISSUE TITLE
missing openMVG_main_CreateList, [OpenExif] Missing unistd.h header include for MacOs

### ISSUE THREAD

**Issue by rperrot** [openMVG/openMVG#63]
I managed to successfully compile openMVG but I can't find the openMVG_main_CreateList executable. 

here is the list of executable I found : 

> openMVG_main_IncrementalSfM
> openMVG_main_computeMatches
> openMVG_main_exportKeypoints
> openMVG_main_exportMatches
> openMVG_main_exportTracks
> openMVG_main_openMVG2MESHLAB
> openMVG_main_openMVG2PMVS

I didn't find main_CreateList in source file, does it has been committed to the repository or I missed something ?

**Comment by maak** [comment]
I'm looking at this example workflow for OpenMVG: http://blog.htmlfusion.com/openmvg/

The first step in it is to run openMVG_main_CreateList. I have checked out the develop branch, but I don't see this binary compiled. Has the binary been deprecated or renamed?

**Comment by fabiencastan** [comment]
Yes, openMVG_main_CreateList has been renamed into main_SfMInit_ImageListing.

Now the steps are:
1/ main_SfMInit_ImageListing
2/ main_ComputeFeatures
3/ main_ComputeMatches
4/ main_IncrementalSfM

**Comment by maak** [comment]
Excellent, thank you.

**Comment by pmoulon** [comment]
Notice that python file to launch the tools are exported in your build directory:
$ cd openMVG_Build/software/SfM
$ python tutorial_demo.py
$ python SfM_SequentialPipeline.py yourImageDir yourOutputDir
$ python SfM_GlobalPipeline.py yourImageDir yourOutputDir
