### ISSUE TITLE
problem with incrementalSFM

### ISSUE THREAD

**Issue by squeakus** [openMVG/openMVG#630]
Hi.
I have hit an issue when using incrementalSFM with BRISK and ORB over several datasets. I am comparing several keypoint detectors and they are all working fine for both global and sequential reconstruction, but when I do a sequential reconstruction for ORB or BRISK I get the following result:

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 0
 Images Id: 

------------------
TrackLength, Occurrence

It works fine for the global reconstruction and I checked the .feat files and they contain info. The one difference is that these two feature detectors use binary matching instead of ANNL2. Could that be causing it and is there anything else I should check for?

**Comment by pmoulon** [comment]
First it will be necessary to check that ComputeMatches is producing valid data:
 - Please check that there is a file matches.putative.bin is produced once the matching have been done.
 - I think there is no tracks, because your matches.f.txt is empty for an unknown reason.

- You can also check the adjacency matrix file GeometricAdjacencyMatrix.svg and the image connection graph geometric_matches.svg provide a nice representation of your data.

**Comment by squeakus** [comment]
I reran the code on a different machine with the same result. The is a matches.e.bin, matches.f.bin and a matches.putative.bin

There is no matches.f.txt file

There are connections in geometricAdjacencyMatrix graph but no connections in the geometric matches graph and the putative matches graph, it just has a bunch of unconnected nodes.

**Comment by pmoulon** [comment]
Do you can use the ExportMatches binary to see if the putative matches look correct or not?

**Comment by squeakus** [comment]
If I try it with any of the bin files including matches.putative.bin

I am running the following command:
openMVG_main_exportMatches -i brisk_opencv_matches/sfm_data.json -d
brisk_opencv_matches/ -i brisk_opencv_matches/matches.putative.bin -o
exported


I get:
failed to read 8 bytes from input stream: read 0

I guess that means they are empty. How is it the global reconstruction can
build a sparse cloud using empty matches?

**Comment by pmoulon** [comment]
If your putative match file is empty it's certainly that you got a problem at the binary descriptor copy or matching.

Can you try to see if the PointFeature are well generated using openMVG_main_exportKeypoints?

**Comment by squeakus** [comment]
It is hard to tell if they are well generated but there are definitely
points in the image (see attached). Thanks again for you help and prompt
response.

**Comment by pmoulon** [comment]
So maybe there is bug in the binary descriptor export or in the hamming matcher.
Can you try to put the ratio threshold to a large value and use force to recompute the matches?

```` -f 1 -r 1.2```

**Comment by squeakus** [comment]
It definitely found more matches, so maybe the binary descriptors need a
higher ratio. Why is it that the global reconstruction worked but the
sequential did not, does global reconstruction use a different matching
process?

**Comment by pmoulon** [comment]
Binary descriptor need a hihger ratio for sure.
Notice that globalSfM require a matches.e.bin/txt and SequentialSfM require a matches.f.bin/txt
Did you relaunch main_ComputeMatched witht the  -g e and then with -g f to recompute fundamental matches from your previously computed putative matches.

**Comment by squeakus** [comment]
Thank you so much for walking me through the reconstruction and explaining
it, it makes much more sense now. My script was actually recomputing a lot
of redundant matching, for both the global and sequential reconstructions.
It computed the matches, then the essential matches and then the
fundamental matches. I will change that in my code now. Thanks for the help!

**Comment by pmoulon** [comment]
You're welcome.
If you want you can also compute only Fundamental matches and then save the matches in matches.f.bin and matches.e.bin. GlobalSfM will be able to deal with fundamental matches too.

I think that you will have to make some experiments in order to tune the right value for the distance ratio -r option.

**Comment by squeakus** [comment]
okay I will try that out and do some more experimentation!
