### ISSUE TITLE
openMVG_main_openMVG2MVE2 faulting

### ISSUE THREAD

**Issue by nils-hamel** [openMVG/openMVG#631]
Hi Pierre,

Hope you're fine !

I had an issue using openMVG_main_openMVG2MVE2 : it crashed on a specific set of data displaying this creepy things (ubuntu 14.04) : 

*** longjmp causes uninitialized stack frame ***: openMVG_main_openMVG2MVE2 terminated

openMVG softwares were able to compute the geometry of the model that causes the crash without any problems. The images set seems ok then.

Do you have any idea that can cause such a crash (openMVG_main_openMVG2MVE2 works perfectly since then) ?

**Comment by pmoulon** [comment]
Hi @nils-hamel 

Do you can run it in debug mode in order to see where the potential bug comes from?

I did not got any particular problem recently with this binary.

**Comment by nils-hamel** [comment]
I finally figure it out : 

The problem comes from the images i'm using. At line 82 of the main_openMVG2CMPMVS.cpp code : 

` Image<RGBColor> image, image_ud;`

that indicates that only RGB images can be considered. Since I was using greyscale images, it conducted the code to crash.

**Comment by pmoulon** [comment]
Ok, I did not know if MVE support grayscale images.
You can try it, just change Image<RGBColor> to Image<unsigned char> for a fast test.

BTW, your test show that we can improve the error feedback ;-) at least in your test case

**Comment by nils-hamel** [comment]
:)
In the same way, I'm probably the only one who considers greyscale images in SfM pipelines in 2016 !

Nevertheless, converting the images in RGB solves every problems and is not a big deal.

**Comment by pmoulon** [comment]
@nils-hamel Within the develop branch you must have some error message displayed ;-)
The program display an error message if an image cannot be read or written and exit.
It will make diagnostic more easy than a longjmp error ;-)

Can you just check that it display you an error message when gray image are used, and that it still works when you are using RGB images?
Then you can close the issue :+1:

**Comment by nils-hamel** [comment]
@pmoulon I've got two errors while compiling the develop branch : 

`In file included from /media/dhlab-linux/lib/openMVG/src/openMVG/features/regions_factory.hpp:33:0,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/features/features.hpp:17,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/media/dhlab-linux/lib/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:100:3: error: expected constructor, destructor, or type conversion before ‘namespace’
   namespace cereal {                                         \
   ^
/media/dhlab-linux/lib/openMVG/src/openMVG/features/regions_factory.hpp:37:1: note: in expansion of macro ‘CEREAL_REGISTER_TYPE_WITH_NAME’
 CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Float_Regions, "AKAZE_Float_Regions");
 ^
In file included from /media/dhlab-linux/lib/openMVG/src/openMVG/image/image.hpp:29:0,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/features/akaze/AKAZE.hpp:35,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/features/image_describer_akaze.hpp:15,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/features/features.hpp:19,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /media/dhlab-linux/lib/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/media/dhlab-linux/lib/openMVG/src/openMVG/image/image_convolution.hpp:207:45: error: expected declaration before end of line
   #pragma omp parallel for schedule(dynamic)
                                             ^
`
Did I missed something ? (openMVG is usually very easy to compile)

**Comment by pmoulon** [comment]
Please update the submodule.
```
git submodule init
git submodule update
```
then redo cmake & make and it will run fines ;-)

**Comment by nils-hamel** [comment]
Oups ! Sorry :)

I tested the fix with RGB and grayscale images. It works in the first case and display : 

`Unable to read and write the image`

in the second - more gentle than longjmp error :)

So bug fixed ! Thanks

**Comment by pmoulon** [comment]
Thank you for the test & confirmation that now a clear error message is displayed :v:

**Comment by vholod** [comment]
Hi,
Thanks for your great work.

I also have the grayscale issue: I am working with gray scale images.
When I run 
>> openMVG_main_openMVG2MVE2 -i  /out_Incremental_Reconstruction/sfm_data.bin  -o outReconstruction_for_MVE

I get the following message:
Unable to read the input image as a RGB image

and no mve views are been created.
My question is: Did you manage to solve this issue or just I convert my image to RGB?

Many thanks,
