### ISSUE TITLE
ubuntu ppa needed

### ISSUE THREAD

**Issue by nitrofurano** [openMVG/openMVG#632]
where from can we find an ubuntu ppa with openmvg? thanks! :)

**Comment by ORNis** [comment]
OK, I can take care of this but not until a few weeks.
meanwhile openMVG is very straightforward to compile, don't be afraid and follow the instruction in the BUILD file.

**Comment by pmoulon** [comment]
I let @ORNis close this thread once he got some time to perform this task ;-)

**Comment by stephane-lb** [comment]
ArcheOS is ubuntu based do they have a PPA ?
