### ISSUE TITLE
Why my UI GCP tool cannot compute densifypointcloud ?

### ISSUE THREAD

**Issue by mitsubishisony** [openMVG/openMVG#633]
I have several UAV images. When I  compute densifypointcloud through openMVG+openMVS. It has a good result. Therefore, I use  GCP UI to add some GCP point(4~5 points) after openmvg progress. Then the openmvs cannot conpute the densifypointcloud. It shows 0 point after openmvs computation. It dose not make any ply file? What is the problem? 
BTW, when I use GCP UI to save the project. I modify the file name to any, the same result also overright the source file(sfm_data.bin). Why?

07:24:31 [App     ] Build date: Jul 12 2016, 12:02:31
07:24:31 [App     ] CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
07:24:31 [App     ] RAM: 15.89GB Physical Memory 128.00TB Virtual Memory
07:24:31 [App     ] OS: Windows 10+ x64
07:24:31 [App     ] SSE & AVX compatible CPU & OS detected
07:24:31 [App     ] Command line: D:\test\exercise\output\mvs_geo\scene_geo.mvs
07:24:31 [App     ] Scene loaded (160ms):
    7 images (4 calibrated) with a total of 45.78 MPixels (11.44 MPixels/image)
    2786 points, 0 vertices, 0 faces
07:24:31 [App     ] Preparing images for dense reconstruction completed: 7 images (323ms)
07:24:31 [App     ] Selecting images for dense reconstruction completed: 4 images (1ms)
07:24:32 [App     ] Reference image   0 paired with 2 views
07:24:32 [App     ] Reference image   1 paired with 3 views
07:24:34 [App     ] Reference image   2 paired with 3 views
07:24:35 [App     ] Reference image   3 paired with 2 views
07:24:40 [App     ] Depth map   0 filtered using 2 other images: 1996364/1996364 depths discarded (317ms)
07:24:40 [App     ] Depth map   3 filtered using 2 other images: 2519306/2519306 depths discarded (319ms)
07:24:41 [App     ] Depth map   2 filtered using 3 other images: 2335050/2335050 depths discarded (611ms)
07:24:41 [App     ] Depth map   1 filtered using 3 other images: 2249120/2249120 depths discarded (715ms)
07:24:49 [App     ] Depth-maps fused and filtered: 4 depth-maps, 9099840 depths, 0 points (0%%) (7s151ms)
07:24:49 [App     ] Densifying point-cloud completed: 0 points (18s176ms)
07:24:49 [App     ] Scene saved (1ms):
    7 images (4 calibrated)
    0 points, 0 vertices, 0 faces
07:24:49 [App     ] MEMORYINFO: {
07:24:49 [App     ]     PageFaultCount 467848
07:24:49 [App     ]     PeakWorkingSetSize 569.95MB
07:24:49 [App     ]     WorkingSetSize 138.64MB
07:24:49 [App     ]     QuotaPeakPagedPoolUsage 310.33KB
07:24:49 [App     ]     QuotaPagedPoolUsage 308.60KB
07:24:49 [App     ]     QuotaPeakNonPagedPoolUsage 25.97KB
07:24:49 [App     ]     QuotaNonPagedPoolUsage 21.59KB
07:24:49 [App     ]     PagefileUsage 208.00MB
07:24:49 [App     ]     PeakPagefileUsage 591.14MB
07:24:49 [App     ] } ENDINFO

**Comment by pmoulon** [comment]
Normally the input file must not be overwritten since you see here that I ask a path and use it to save the modified scene: https://github.com/openMVG/openMVG/blob/master/src/software/ui/SfM/control_points_registration/mainLayout.cpp#L89

Did you try to look at the registration result scene in a viewer?
To do so you can use main_ConvertSfM_DataFormat by setting as input the sfm_data.bin file and asking to produce an output file like sfm_data.ply 

For an unknow reason all camera depth are cleaned by OpenMVS, perhaps since depth are larger when the scene is registered to your GCP.
Once you checked that the scene is well registered, perhaps it would be valuable to open an OpenMVS issue.

**Comment by mitsubishisony** [comment]
Thanks for reply. I try to convert the sfm_data.bin file to ply file. The registration is work well. The ply file is shows:

Before Registration:
ply
format ascii 1.0
element vertex 6645
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
 0.00422358 -0.00145019   0.0528926 0 255 0
  0.451963 -0.0095177  0.0316263 0 255 0
   0.859444 -0.00296969   0.0343761 0 255 0
   1.25795 0.00972832  0.0378345 0 255 0
 0.168813 -0.430477   1.09806 255 255 255
 0.727493 -0.544852   1.20904 255 255 255
0.534126 0.547679 0.960416 255 255 255
 0.809692 -0.542868   1.20661 255 255 255
 0.174053 -0.771535   1.11756 255 255 255
 0.431114 -0.451336   1.15318 255 255 255
 0.912816 -0.921614   1.32534 255 255 255
...............

After Registration :
ply
format ascii 1.0
element vertex 6650
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
83.7101 48.1057 95.1847 0 255 0
91.9136 63.3377 93.7094 0 255 0
100.743 78.8991 89.7542 0 255 0
109.226 92.3147 84.4908 0 255 0
59.7329 63.4192 64.4109 255 255 255
65.9323  82.911 56.7324 255 255 255
96.4723 51.7319 49.8063 255 255 255
67.8394 85.1661 56.2194 255 255 255
51.1759 70.8928 68.1766 255 255 255
63.3734 71.8487  60.142 255 255 255
59.5266 94.7669 57.5238 255 255 255
77.7184 78.9585 51.9799 255 255 255
70.8218 91.2781 53.7649 255 255 255
 78.684  80.794 51.0776 255 255 255
89.7157 42.1862 53.3728 255 255 255
...........
The bin file(after registration)  is not work well with openMVS. The result is also has 0 point after DensifyPointCloud.

Why?

**Comment by pmoulon** [comment]
I suggest you to ask the question there: https://github.com/cdcseacave/openMVS/issues
Perhaps @cdcseacave will have an answer to provide.

**Comment by mitsubishisony** [comment]
THANKS.
What is theory of registration of GCP UI TOOL. Do you have some paper about it?

**Comment by pmoulon** [comment]
I don't have paper about it.
As mentioned in the doc a rigid transform between observation triangulate and known 3D coordinates is computed.
http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/

**Comment by mitsubishisony** [comment]
http://openmvg.readthedocs.io/en/latest/software/ui/SfM/control_points_registration/GCP/
The follow web site shows the picture sample.
Could you give me the picture sample and GCP point?

**Comment by zharvey-welltok** [comment]
@mitsubishisony FWIW I am brand new to CV and 3D reconstruction, SfM, etc.

I had *enormous* difficulty getting OpenMVS to compile, and then failed miserably getting the thing to even work. Even worse, the maintained of that project will immediately *close* any question/issue you create, likely without even trying to help you. At best, you'll get a 1-sentence answer from him that leaves you even more confused than you were before you created the issue.

I had instant success switching over to an openMVG/MVE pipeline. The community around MVE has (so far) proven to be very responsive and helpful. Just my 2 cents.

**Comment by pmoulon** [comment]
@zharvey-welltok I didn't understand the meaning of your message in the thread. Your message is not in relation with the topic.

@mitsubishisony I will try to compile you a tiny sample.

**Comment by pmoulon** [comment]
Since no feedback from @mitsubishisony I'm closing the issue.
