### ISSUE TITLE
Did openMVG can convert bin file to  .nvm or .psz file？

### ISSUE THREAD

**Issue by mitsubishisony** [openMVG/openMVG#634]
Did openMVG can convert bin file to  .nvm or .psz file？
There are file format of Photoscan and VisualSFM.

**Comment by pmoulon** [comment]
There is an export to NVM (in the develop branch)
https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_openMVG2NVM.cpp

There is no export to Photoscan format (feel free to contribute one ;-) )

**Comment by mitsubishisony** [comment]
@pmoulon 
Do you known any tools can export openMVS result(ply format) to DOM or DSM(tiff format)?

**Comment by pmoulon** [comment]
I think I can close the issue since I have provide an answer.
@mitsubishisony Sorry I did not known tools to export OpenMVS result to DOM.
