### ISSUE TITLE
[suggestion] Proposition of automated script of 3 steps sfm

### ISSUE THREAD

**Issue by rperrot** [openMVG/openMVG#64]
I made a first attempt of a script for doing three step (createList/matching/sfm) of openMVG. The script does not include every options but is used for easy and fast usage of openMVG.  

script is as bellow : 

```
#!/bin/sh
# @author Romuald Perrot <perrot.romuald@gmail.com>
# 
# this script is for easy use of OpenMVG
#
# usage : ./OpenMVG.sh image_dir output_dir 
#
# image_dir is the input directory where images are located 
# output_dir is where the project must be saved
# 
# if output_dir is not present script will create it 
# 

# indicate the openMVG binary directory (must be changed)
BIN=/Users/rperrot/Prog/Reconstruction/openMVG_Build/software/SfM/Release

# indicate the openMVG camera sensor width directory (must be changed)
CAMERA_SENSOR_WIDTH_DIRECTORY=/Users/rperrot/Prog/Reconstruction/openMVG/src/software/SfM/cameraSensorWidth

if  [ $# -ne 2 ]
	then
		echo "Usage ./OpenMVG.sh image_dir output_dir"
		exit 1
	fi

INPUT_DIR=$1
OUTPUT_DIR=$2
CAMERA_FILE_PARAM=$CAMERA_SENSOR_WIDTH_DIRECTORY/cameraGenerated.txt

echo "Using input dir  : \'$INPUT_DIR\'" 
echo "      output_dir : \'$OUTPUT_DIR\'"

# 1. Intrisics analysis 
${BIN}/openMVG_main_CreateList -i ${INPUT_DIR} -d $CAMERA_FILE_PARAM -o ${OUTPUT_DIR}/matches

# 2. Compute matches 
${BIN}/openMVG_main_computeMatches -i ${INPUT_DIR} -o ${OUTPUT_DIR}/matches

# 3. Do reconstruction
${BIN}/openMVG_main_IncrementalSfM -i ${INPUT_DIR} -m ${OUTPUT_DIR}/matches -o ${OUTPUT_DIR}/outReconstruction
```

As you can see, you need to adapt BIN and CAMERA_SENSOR_WIDTH_DIRECTORY variables for your system (maybe it can be generated by cmake ? ). 

Hope it helps.

**Comment by Meekohi** [comment]
Hey I just thought I'd follow up on this again with the script I am using which includes @pmoulon's CMVS-PMVS port: https://github.com/pmoulon/CMVS-PMVS 

I like to install everything in my home directory, but you can see what to change to make it work on your system. Note that I'm using a fixed known focal length, so I use `-e` with `computeMatches` to use the Essential Matrix. I also use `-d 0` to only calibrate focal length, which is probably not what you want to do. `-c 1` produces a color model.
`genOptions 0 1` means "use the full resolution images" and "make a patch for every pixel", see http://www.di.ens.fr/pmvs/documentation.html and the help for `genOptions` to see what else you can do.

```sh
~/openMVG_Build/software/SfM/Release/openMVG_main_CreateList -i 14iidnsyen8i2/images/ -o 14iidnsyen8i2/matches/ -f 3200
~/openMVG_Build/software/SfM/Release/openMVG_main_computeMatches -i 14iidnsyen8i2/images/ -o 14iidnsyen8i2/matches/ -e
~/openMVG_Build/software/SfM/Release/openMVG_main_IncrementalSfM -i 14iidnsyen8i2/images/ -m 14iidnsyen8i2/matches/ -o 14iidnsyen8i2/outReconstruction -d 0 -c 1


~/openMVG_Build/software/SfM/Release/openMVG_main_openMVG2PMVS -i 14iidnsyen8i2/outReconstruction/SfM_output/ -o 14iidnsyen8i2/outReconstruction/
cd 14iidnsyen8i2/outReconstruction
~/CMVS-PMVS/binariesWin-Linux/mac_osx_fat/cmvs PMVS/
~/CMVS-PMVS/binariesWin-Linux/mac_osx_fat/genOption PMVS/ 0 1
~/CMVS-PMVS/binariesWin-Linux/mac_osx_fat/pmvs2 pmvs/ option-0000
```

This produces some nice, fairly dense results. This dataset http://arqspin.com/s/3fmdy44ri0hbo produced this mesh:

![screenshot 2015-02-05 17 44 40](https://cloud.githubusercontent.com/assets/10985/6070924/c03f401e-ad5e-11e4-864a-dca298d9c1a7.png)

**Comment by pmoulon** [comment]
@vins31, @rperrot, script to launch tools from image listing to SfM with default settings are now available  in the SfM build directory. https://github.com/openMVG/openMVG/issues/280
