### ISSUE TITLE
Generating a complete 3D model and loading into Blender or similar

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#643]
I have a question about SfM pipelines (specifically OpenMVGs), but it involves MVS components. As I understand it, OpenMVG is compatible with [four MVS systems](http://openmvg.readthedocs.io/en/latest/software/MVS/MVS/):

1. CMPMVS
2. MVE
3. OpenMVS
4. PMVS/CMVS

Although this answer *does* involve OpenMVG and MVS, it doesn't really matter which MVS we're talking about here (I believe they're all more or less the same). Because of that, I'm going to arbitrarily pick OpenMVS when talking about the 3D reconstruction end of the pipeline, but I could just as well be talking about any of the other three above.

I am trying to take 360&deg; photos of an object, and then run those photos through OpenMVG (similar - if not exact - pipeline as what is in your `tutorial_demo.py` helper script) and then reconstruct a 3D model (complete with mesh, color and texture). I then want to be able to load that 3D model into a "model viewer" (I'm guessing *something* like Blender) so that I can move around the object and see it from any direction I choose. In this viewer, I would expect to also manipulate the object (scale it, maybe play with its colors, etc.).

My game plan is to use the following pipeline:

* OpenMVG
    * `openMVG_main_SfMInit_ImageListing`
    * `openMVG_main_ComputeFeatures`
    * `openMVG_main_ComputeMatches`
    * `openMVG_main_IncrementalSfM`
    * `openMVG_main_ComputeSfM_DataColor`
    * `openMVG_main_ComputeStructureFromKnownPoses`
* OpenMVS
    * `DensifyPointCloud`
    * `ReconstructMesh`
    * `TextureMesh`

Finally, my question: **Would an OpenMVG + OpenMVS pipeline accomplish this for me?** That is, would I be able to generate a 3D model of the object (again: mesh & color/texture)? If so, how would you recommend I view it? Could it be imported into Blender? Is there some other tool that is better suited to viewing/manipulating OpenMVG/OpenMVS-reconstructed scenes?

**Comment by pmoulon** [comment]
The pipeline steps is given in the python file:
- 	SfM_GlobalPipeline.py
- 	SfM_SequentialPipeline.py
You can skip openMVG_main_ComputeStructureFromKnownPoses and then run the OpenMVS related command.

By using OpenMVS you will have a textured mesh.
You can use Meshlab/CloudCompare or Blender to view it.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon 

For future onlookers who have the same question as me, it seems that OpenMVS will generate a PLY file as well as 1+ PNG files (textures). You can then use Blender's PLY reader to read the PLY and texture files into Blender.
