### ISSUE TITLE
The input SfM_Data file "sfm_data.bin" cannot be read

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#644]
I installed & built OpenMVG on a Linux (CentOS 7) machine by following the [build instructions](https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD). I then ran `tutorial_demo.py` and it looks like it succeeded.

I am now trying to convert the output of that `tutorial_demo.py` into something that can be imported/used by OpenMVS. So inside the `tutorial_out` directory, I ran:

```
mkdir openmvs_input
/path/to/openMVG_main_openMVG2openMVS -i tutorial_out/reconstruction_global/sfm_data.bin -d tutorial_out/reconstruction_global/ -o openmvs_input/scene.mvs
```

And here is the error/output I am receiving:

> The input SfM_Data file "tutorial_out/reconstruction_global/sfm_data.bin" cannot be read.

Any ideas where I'm going awry?

**Comment by pmoulon** [comment]
Did you tried to use full path to the sfm_data?
/home/users....

**Comment by zharvey-welltok** [comment]
Dang. Nope, that was it. Gonna go hide my head in shame for a little bit... (but thanks!)
