### ISSUE TITLE
Exporting outputs to MVE

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#645]
I ran OpenMVG's `tutorial_demo.py` and am now trying to export all of its outputs (castle model) into [MVE](https://github.com/simonfuhrmann/mve) for further processing & reconstruction.

It looks like MVE has a `makescene` tool that *may or may not* be capable of importing OpenMVG data, but I also see from OpenMVG's docs that there is a [`openMVG_main_openMVG2MVE `](https://openmvg.readthedocs.io/en/latest/software/MVS/MVE/) tool that may be capable of doing the same thing.

Can anyone weigh in as to which tool should be used under which circumstances?

**Comment by pmoulon** [comment]
Just take a look to the doc:
http://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon, so that doc and the binary's usage docs aren't exactly adding up, would you mind taking a quick look at something for me?

In the doc you linked above, the binary is `openMVG_main_openMVG2MVE`, but I only seem to have a tool called `openMVG_main_openMVG2MVE**2**`. Furthermore, the docs instruct you to pass in a JSON file for the `-i` argument to this tool. But after running the `tutorial_demo.py` script, the only JSON file I have is under `tutorial_out/matches` (which you've previously told me is not the correct file to use).

So, all in all, here's the command I went with:

    openMVG_main_openMVG2MVE2 -i tutorial_out/reconstruction_global/sfm_data.bin -o tutorial_out/mve_input/

Which yielded the following output:

```
Note:  this program writes output in MVE file format.
Creating directory:  tutorial_out/mve_input/MVE
Creating directory:  tutorial_out/mve_input/MVE/views
Writing bundle (11 cameras, 2939 features): to synth_0.out...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
```

**Does this look right to you?** As always, thank you!

**Comment by pmoulon** [comment]
Happy to see that you made progress on it.
OpenMVG sfm_data file can be saved and loaded in json, xml and bin. That's why you see sometimes json, or bin in the extension.

Regarding the texture, I think you have to add a material with the texture.

Perhaps @cogitas3d can provide insight about it.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon,

Although I'm definitely open to any answers inside this issue, I was really asking that last followup question to make sure there wasn't something in the `openMVG_main_openMVG2MVE2` tool that I needed to do in order to "activate" or export textures correctly.

I'll followup with the MVE folks as well. Thanks again (enormously!). I'm brand new to CV/SfM/recontructions and you have helped steer me past a lot of headaches, and I want you to know that I *sincerely* appreciate that.

**Comment by zharvey-welltok** [comment]
Hi @pmoulon, according to the folks over at MVS:

> The regular MVE pipeline only creates vertex colors and does not generate textures for the output mesh. Please have a look at this project if you're looking for high-quality textures: https://github.com/nmoehrle/mvs-texturing.

So my (final!) question here is: on your website you have a picture of the Chateau de Sceaux fully reconstructed with color & textures, right here:

http://imagine.enpc.fr/~moulonp/openMVG/SfM_Images/dense_Front.jpg

**How did you get the textures/colors generated for that image?** Did you *only* use OpenMVG, or did you use other tools as well (if so, which ones?) If it's the former, and you only used OpenMVG to generate that image, I guess I'm wondering why I need MVE (or any other processors beyond OpenVG) in the first place!

**Comment by pmoulon** [comment]
You can generate such a point cloud by using OpenMVG SfM pipeline with an ultra setting (for the keypoint extraction).
Or by then using PMVS on the computed scene.

OpenMVG provide SfM tools (sparse point cloud and camera poses) + some image localization tools (find the position of an image inside an existing reconstruction)

**Comment by SyedShaQutub** [comment]
Hello All,
Could someone help me with the tool openMVG_main_openMVG2MVE? I guess its missing from the current implementation! 
Does anyone have any idea about it?
