### ISSUE TITLE
the output  files of main_computematches is not valid   

### ISSUE THREAD

**Issue by TMwhuhan** [openMVG/openMVG#649]
the msg:
Optional parameters:
--force 0
--ratio 1.2
--geometric_model e
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
 - PUTATIVE MATCHES - 
	 PREVIOUS RESULTS LOADED; #pair: 136
 - Geometric filtering - 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0.00081455
 Export Adjacency Matrix of the pairwise's geometric matches

And the result file  "matches.putative.bin"  is large enough, but "matches.e.bin" is only 1KB. 
The msg of openMVG_main_GlobalSFM  is
- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0
Invalid input image graph for global SfM

what can I do to get the valid result?  Thanks~~

**Comment by pmoulon** [comment]
I think you does not have geometric matches since you have no valid intrinsic information for your images.
- Check the sfm_data.json file and see if you have a section intrinsics with valid data.

You can try to use the "-g f" option on main_ComputeMatches in order to filter the matches since this geometric filter does not need intrinsic data.

**Comment by TMwhuhan** [comment]
Thank you. Indeed I don't use the -d and -f in "openMVG_main_SfMInit_ImageListing". It's work,while GlobalSFM and IncrementalSfM could generate result.
![default](https://cloud.githubusercontent.com/assets/7644272/19256796/bb4a735e-8f9c-11e6-974e-ae294eb6baeb.PNG)

**Comment by pmoulon** [comment]
Happy to see that you have nice results now ;-)
