### ISSUE TITLE
openMVG_main_SfMInit_ImageListing options that I don't see covered in the docs

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#650]
Running `openMVG_main_SfMInit_ImageListing` without options produces the following usage documentation:

```
Usage: /home/vagrant/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
[-i|--imageDirectory]
[-d|--sensorWidthDatabase]
[-o|--outputDirectory]
[-f|--focal] (pixels)
[-k|--intrinsics] Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"
[-c|--camera_model] Camera model type:
	 1: Pinhole
	 2: Pinhole radial 1
	 3: Pinhole radial 3 (default)
	 4: Pinhole brown 2
	 5: Pinhole with a simple Fish-eye distortion
[-g|--group_camera_model]
	 0-> each view have it's own camera intrinsic parameters,
	 1-> (default) view can share some camera intrinsic parameters
```

I have several questions about these options that do not appear to be documented anywhere:

#### `sensorWidthDatabase`
I see that `tutorial_demo.py` uses a "sensor database" file located at `openMVG/src/exif/sensor_width_database/sensor_width_database.txt`.

**Should this default `sensor_width_database.txt` file *always* be used, or are there times when you would want to use a different one?** When would you ever want to generate your own custom database file, and why?

#### `focal`
**Is this simply the number of pixels in the camera that was used to take all the input images?** What if different cameras were used to take different images (from different angles)?

#### `intrinsics` and `group_camera_model`
**Is the format/structure of the `intrinsics` parameter documented anywhere?** The given example of `Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"` doesn't really help me out at all. Also, the existence of `group_camera_model` implies (to me) that the `intrinsics` option will be different depending on whether each image has its own camera intrinsic params, or whether all images share a single set of params.

#### `camera_model`
**Is there a way to auto-detect camera model type, perhaps via EXIF data?** Otherwise, is there any way to manually determine what type of model the camera is? I guess this question largely stems from the fact that I'm not a photographer (:-)) and I have no experience with photography. Perhaps camera model is obvious to anyone even moderately experienced w/ photography, but I'm struggling to figure out how I can determine which option to choose (`1 - 5`) for this option.

**Comment by pmoulon** [comment]
As I said in an previous post you can see more about the OpenMVG camera model there
http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/

- camera model
Most of the time Radial3 works fine.
The fisheye model is good for action camera images (like GoPro images).


- group camera model
This option allows to make the images coming from the same camera to share the same intrinsic camera parameter and so to enhance the stability of the results.

- Focal => see the documentation

**Comment by pmoulon** [comment]
Please close the issue if a valid answer was provided

**Comment by zharvey-welltok** [comment]
Hi @pmoulon sorry it took me so long to get back to this, I've been swamped with deadlines at work.

Your answer (above) definitely helps, but I still have some outstanding questions from the original post:

1.  Should the `openMVG/src/exif/sensor_width_database/sensor_width_database.txt` file always be used, or are there times when you would want to use a different one? Why?
2. The only definition for the **focal** option that I can find in the docs are: "*the focal distance (distance between focal and image plane)*", what is the unit of measurement here, for distance?
3. According to the docs you pointed me at, it looks like there are **three (3)** instrinsic parameters: scale factor, focal point and principal point. What is the format for a `K.txt` (intrinsic param) file? I need to construct my own.
4. Regarding `camera_model`, is there a rubric or "rule of thumb" that I can use that says: *When X, use Camera Model Y*? You've mentioned that Radial3 is good for *most* use cases, I'm looking to know *when to use the others*!
5. If I'm using `group_camera_model 0`, meaning that each view has it's own camera intrinsic parameters, then how do I tie each view/image to a different intrinsic param file (`K.txt`, etc.)?

Thanks again for any-and-all-input!

**Comment by pmoulon** [comment]
You can check the doc there https://github.com/openMVG/openMVG/blob/develop/docs/sphinx/rst/software/SfM/SfMInit_ImageListing.rst

1. It's preferable to use the database everytime.
2. Focal units there is in pixels (written in the sphinx doc).
3. K matrix is setup like that [f 0 ppx, 0 f ppy, 0 0 1] see http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/. The K option is only used when you want to specify the principal point position and the focal at the same time. So it's a kind of enhance -f option
4. It depends of your camera lens. If you use undistorted image you will prefer the classic camera pinhole without distortion. If you know that you have distortion it's preferable to use Radial3. If you camera is close to be a FishEye is better to use the FishEye camera model. SO using model 1 or 3 is often sufficient. Model 1 is a model similar to the one used in Bundler.
5. It's preferable to group the camera, so set this option to 1. Have many camera sharing some camera intrinsic parameter will make their estimation and refinement more stable. The tie between the image (the view) and the camera model and the used pose is defined in the VIEW. If you use -g 0 or -g 1 you will see a change in the camera_model id in the view (check the json).

Hoping those clarifications help you more.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon one last followup for the last question. You state:

> "The tie between the image (the view) and the camera model and the used pose is defined in the VIEW".

Do you mean that the image/view would have exif data that tied it to a camera mode/pose? Or do you mean I can create a file called `VIEW` and define the relations there? Thanks!

**Comment by pmoulon** [comment]
I mean that the View object is defining the relationship between the elements.
Please take a look to the json file to better understand:

Here two view that share the same camera parameter and that define two different pose (one per image).
The camera model data initial values can be build thanks to -f, -K or auto guess with the camera dabase + EXIF data.


```
{
    "sfm_data_version": "0.2",
    "root_path": "/home/pierre/Documents/ImageDataset_SceauxCastle/images",
    "views": [
        {
            "key": 0,
            "value": {
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "/",
                        "filename": "100_7100.JPG",
                        "width": 2832,
                        "height": 2128,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "/",
                        "filename": "100_7101.JPG",
                        "width": 2832,
                        "height": 2128,
                        "id_view": 1,
                        "id_intrinsic": 0,
                        "id_pose": 1
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "width": 2832,
                        "height": 2128,
                        "focal_length": 2881.2521269425101,
                        "principal_point": [
                            1416,
                            1064
                        ],
                        "disto_k3": [
                            0,
                            0,
                            0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}
```

**Comment by zharvey-welltok** [comment]
Makes sense - thanks again!

**Comment by pmoulon** [comment]
You're welcome.

**Comment by khouloud21** [comment]
hello Hello I am a beginner in the field of reconstruction, I have a question:
Where i can find the json file to check the parameters please

**Comment by pmoulon** [comment]
@khouloud21 Can you elaborate?
You can find the produced json file in the matches directory (it's the initial scene description).
Then after you run the SfM pipeline you obtain a sfm_data.bin file than you can convert back to JSON openMVG_main_ConvertSfM_DataFormat``

**Comment by khouloud21** [comment]
Thank you mr Pierre
please  step by step I am still beginner and the reconstruction in 3D is my
project of end of study ( :) )
What I ask is what I will do at the beginning and the commands I will make
the executed
Knowing that I have already installed openMVG, openMVS, OpenCV .. I have
everything necessary and I used a camera gopro hero 4 black
I add it to the database already in the .txt file that is in EXIF
1) is what I have to write a PYTHON file to declare input and output PATH
and reconstruction steps like (matching, feature ...)
I have a lot of questions I hope you can help me if you do not mind
thank you

2017-04-10 3:50 GMT+03:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
@khouloud21 Don't worry the community is here to help.

In order to use OpenMVG with ease I recommend first to learn to use it thanks to the existing python pipeline script.
See here:
https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo
I recommend to play first with this tiny dataset:
https://github.com/openMVG/ImageDataset_SceauxCastle

Using the pipeline is easy as running:
```
$ cd openMVG_Build/software/SfM/
$ python SfM_SequentialPipeline.py [full path image directory] [resulting directory]
$ python SfM_SequentialPipeline.py ~/home/user/data/ImageDataset_SceauxCastle/images ~/home/user/data/ImageDataset_SceauxCastle/Castle_Incremental_Reconstruction

$ python SfM_GlobalPipeline.py [full path image directory] [resulting directory]
```

Then you can start to play with your own images and understand how to use new camera model.

Regarding the usage of the GoPro I recommend to use the fisheye camera model for it and use a precalibrated camera intrinsic. You can use the camera in this configuration:
1. take some images of a nice textured scene -> run the python pipeline with the Fisheye camera model in order to perform an autocalibration of the camera distortion and adjust the focal length

2. Every time you want to process a new scene, you edit the sfm_data.json file and copy paste the calibrated camera intrinsic in order to use them for the ComputeMatches and SfM step. It will greatly enhance the initial match set and improve the SfM results.

**Comment by khouloud21** [comment]
I have already done the pictures of castles and it was very successful
To declare the model of my camera in the database I wrote the following line
HERO4 Black 5.75 (mm unit)?
1 / is it correct the focal value of my camera? Is it enough to declare the
camera model in this way ie when I put images taken by gopro, is it
automatically understood that it is the photos of gopro?
2 / do i have to write my own python file exp globelpiplinekhouloud.py? Or
I could use the old
3 / in the old python file I changed the options values like (-c, 5; -g, 1)
but I want to know the value of -f in the file it excist -f, 1?
4 / What is ANNL2?
[image: Images intégrées 1]

Thank you

2017-04-10 17:55 GMT+02:00 Pierre Moulon <notifications@github.com>:

**Comment by maryam04** [comment]
Hello , 

I'm working on the 3D reconstruction and i have some questions, it's about the options in the tutorial_out and Global_pipeline :

1. -f which value it takes ?

2. what's the meaning of [ "-n" , "ANNL2" ] ?

3. what's the meaning of [ , "-r", "0.8", "-g", "e" ] ?

4. "0.8", the value of what ?

Thank you :)

**Comment by pmoulon** [comment]
Hi @maryam04 
You can run the binary without options and a some help about the parameter and their meaning will be displayed:
```
Usage: openMVG_main_ComputeMatches
[-i|--input_file] a SfM_Data file
[-o|--out_dir path] output path where computed are stored

[Optional]
[-f|--force] Force to recompute data]
[-r|--ratio] Distance ratio to discard non meaningful matches
   0.8: (default).
[-g|--geometric_model]
  (pairwise correspondences filtering thanks to robust model estimation):
   f: (default) fundamental matrix,
   e: essential matrix,
   h: homography matrix.
[-v|--video_mode_matching]
  (sequence matching with an overlap of X images)
   X: with match 0 with (1->X), ...]
   2: will match 0 with (1,2), 1 with (2,3), ...
   3: will match 0 with (1,2,3), 1 with (2,3,4), ...
[-l]--pair_list] file
[-n|--nearest_matching_method]
  AUTO: auto choice from regions type,
  For Scalar based regions descriptor:
    BRUTEFORCEL2: L2 BruteForce matching,
    ANNL2: L2 Approximate Nearest Neighbor matching,
    CASCADEHASHINGL2: L2 Cascade Hashing matching.
    FASTCASCADEHASHINGL2: (default)
      L2 Cascade Hashing with precomputed hashed regions
     (faster than CASCADEHASHINGL2 but use more memory).
  For Binary based descriptor:
    BRUTEFORCEHAMMING: BruteForce Hamming matching.
[-m|--guided_matching]
  use the found model to improve the pairwise correspondences.[-c|--cache_size]
  Use a regions cache (only cache_size regions will be stored in memory)  If not used, all regions will be load in memory.
```

So to be concise:
- '-f' optional parameter to force the setup of a known pixel focal length
- '-r' Distance ratio use to filter out repetitive matches. If the distance of the two nearest neighbor look too similar the match is discarded. 
- '-g' Allow to choose the geometric filter to apply on the putative matches
- '-n' The nearest neighbor method to find putative matches

**Comment by maryam04** [comment]
Hello @pmoulon 
I'm truly thankful for your help

1. i'm facing a problem here, i'm using a GOPRO HERO4 black and for the options in python i cannot define  the values to use like "-r" which value takes ? else "-f"

2.  what's the Focal length of the GOPRO HERO4 black ?

3. And finally, how can i calibrate the K matrix ? and is it related to the file k.txt ?

regards
