### ISSUE TITLE
Invalid input image graph for global SfM

### ISSUE THREAD

**Issue by hotmeatballsoup** [openMVG/openMVG#656]
I have a collection of photos of an ugly yellow/green chair and I am trying to run them through an OpenMVG pipeline. I want to run them through:

* `openMVG_main_SfMInit_ImageListing`
* `openMVG_main_ComputeFeatures`
* `openMVG_main_ComputeMatches`
* `openMVG_main_GlobalSfM` **<= failing here**
* `openMVG_main_ComputeSfM_DataColor`
* `openMVG_main_ComputeStructureFromKnownPoses`

[Here is a gist that captures the output from each step.](https://gist.github.com/hotmeatballsoup/c5688cd9c759dbca87ae375c33bcf187)

Probably more important: [here is a repo with all the artifacts OpenMVG produced](https://github.com/hotmeatballsoup/3drecon-troubleshooting).

The end result was that Global SfM seems to have failed, and I'm not sure where/why. Right off the bat, there seems to be a problem with the images that I'm using, as `openMVG_main_SfMInit_ImageListing` doesn't seem to support them in the `sensor_width_camera_database.txt` file that I'm using:

```
Warning & Error messages:
image000" model "DSC-HX5V" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
```

etc. Can anyone spot where the problem could be, and why the output from the Global SfM step is:

```
CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0

Cardinal of nodes: 0
Cardinal of edges: 0

Invalid input image graph for global SfM
```

? Thanks!

**Comment by rperrot** [comment]
As suggested by the warning, the main issue is related to an unknown sensor width in our database. 

Could you give us more details about the camera used for your test ? (Brand and model), we have to look it's sensor width and add it to the sensor_width_camera_database.txt file. Once done, and supposing that your image gives enough coverage between frame, you should have 

Is it that model ? 

http://www.digicamdb.com/specs/sony_cybershot-dsc-hx5/

**Comment by rperrot** [comment]
I could successfully reconstruct something with your images. (using global pipeline and sift ultra)

<img width="595" alt="frame" src="https://cloud.githubusercontent.com/assets/6479700/19619263/4bad6efa-9863-11e6-9e61-cd450cbdda7d.png">

All you have to do is to edit the sensor_width_camera_database.txt file (located in src/openMVG/exif/sensor_width_database/) and add the following line : 
```
DSC-HX5V;5.90
```

**Comment by hotmeatballsoup** [comment]
Interesting! Thanks for gettingback to me @rperrot.

Honestly, I copied these photos from a (defunct) Java SfM library called `boofcv`:

Here's the original repo I copied the photos from:

[BoofCV Chair images](https://github.com/lessthanoptimal/BoofCV-Data/tree/master/example/sfm/chair)

As I'm writing this, I see you were able to edit the TXT file.

Just for my own edification, how did you know what to add to the sensor/database file?

I'm assuming you did something like:

* Inspected EXIF data on the images
* Found the make/model (`DSC-HX5V`) in that EXIF data somewhere
* Looked up the make/model online
* Somehow got the `5.90` value
* Added an entry to the database TXT in the format `<make>-<model>;<width>`
* ???

Am I close? If so, what EXIF data did you use to determine the make/model/width? Thanks again!

**Comment by hotmeatballsoup** [comment]
OK @rperrot so I added the entry to the database TXT and now those warning are now gone. So I deleted all the data/files generated by the last pipeline run and started over again. Check the gist out for output and (like I said) the warnings are gone (because `DSC-HX5V` is now listed inside the database TXT). However I am **still** getting the:

    Invalid input image graph for global SfM

message. Any ideas as to what's going wrong?

**Comment by rperrot** [comment]
Please clear all the folder previously generated before running again full openMVG pipeline.

**Comment by hotmeatballsoup** [comment]
Yep, I did. I deleted all the contents of the `chair/matches` directory as well as the `chair/reconstruction_global` directory. Then I re-ran the pipeline (I updated the gist so you can see all the commands I actually ran) and am still getting that error message after running Global SfM. Any ideas?

**Comment by rperrot** [comment]
Ok, I see.

Since your images are small, there are not enough features to compute the reconstruction. To increase the change to get more feature, please use -p ULTRA option on openMVG_main_ComputeFeatures executable (that's what I did). However please not that it should increase memory consumption (be careful with very large images).

**Comment by hotmeatballsoup** [comment]
Hey - I think that worked! **Thank you!** A few followup questions if you don't mind, because I'm *really* trying to learn/understand this stuff:

1. How did you know that Global SfM was failing because the images were too small? I'm curious to know from a debugging/troubleshooting perspective, in case this happens to me again. Is there a general rule of thumb where images under a certain size require `-p ULTRA`?
2. What command/tool/lib did you use to visualize the chair in your photo above? I have now ran the char images through: `ImageListing`, `ComputeFeaturs`, `ComputeMatches`, `GlobalSfM`, `ComputeSfM_DataColor` and finally `ComputeStructureFromKnownPoses`. Am I in a position to generate a similar image?

Thanks again for all the help with this!

**Comment by rperrot** [comment]
1 -> That's not only a question of size. Mainly detectors found corners in the images (that's too simplistic but enough to understand), if your images haven't enough texture, chance to get feature is low. You can have large image but if they contains large textureless areas, the place where feature could be extracted is small. Your images are 640x480, that can be enough but the chair is in 1/2 or 1/3 of the image. 

If you have enough time and memory, you could use -p ULTRA everywhere, you'll get the best results.  (that's what I always do, but time don't mind for me). 

2 -> I was taken on meshlab, In a near future, you'll get a basic WebGL exporter in openMVG (I hope), so you could visualize your result without any additional application. 

I use the colorized.ply file for visualization (that's the result of ComputeSfM_DataColor), you could have a denser mesh with robust_colorized.ply file (the result of ComputeStructureFromKnownPoses), but in a few cases. 

Finally, if you have python (branch 2.X not the 3.X one), you could avoid launching the executable one by one using the provided scripts (in your build directory : software/SfM/SfM_GlobalPipeline.py and SfM_SequentialPipeline.py)

**Comment by hotmeatballsoup** [comment]
Thank you - makes perfect sense! One last followup question (I promise!): what tool did you use to textract the brand, model & width info (`DSC`, `HX5V` and `5.90` respectively) out of the images?

**Comment by rperrot** [comment]
I didn't use anything. The infos are provided by openMVG (openMVG_main_SfMInit_ImageListing) that uses exif data stored in the images files. But if you really want it, any imaging software could give you this information (even preview on OS X). 

The 5.90 value is provided by the brand and can be retrieve in any serious camera database site (like the one in my first answer).

**Comment by hotmeatballsoup** [comment]
👍
