### ISSUE TITLE
Inferring camera poses via openMVG_main_ExportCameraFrustums's PLY output

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#658]
I have now successfully ran several sets of photos through your Global SfM pipeline, and then forwarded them on to MVE and mvs-texturing to reconstruct very real-looking 3D models of the content contained in the original photos. Nice!

I now have a need to run a very specific type of analysis on photos and was wondering if OpenMVG has the tools/capabilities to help me out. I need to take a set of photos as input, and for each photo, determine/calculate the position/location/orientation/pose of the camera at the time when the photo was taken.

I _believe_ this requires me to:
1. Run my photos through an SfM pipeline, which will produce a sparse point cloud of the content inside the photos; then
2. Run a different tool/lib on that sparse point cloud, and somehow determine where the camera was (inside that 3D cloud/model) at the time each photo was taken.

The idea is that once I have a 3D reconstructed model of the photos, I should be able to calculate where the camera was for one of the photos/images and view the 3D model from the same exact pose that it was in when it took that photo. So if I had originally used 30 photos to create my 3D reconstructed model, I should be able to determine where the camera was in all 30 of those photos.

**Is this possible?** Is this what `openMVG_main_ComputeStructureFromKnownPoses` is already doing?

**Comment by polto** [comment]
Hi @zharvey-welltok ,

openMVG_main_ComputeStructureFromKnownPoses is not meant for that. It is demonstrating an SfM with prior knowledge of the scene. So you can use it after openMVG_main_GlobalSfM to create a more robust reconstruction.

You can use openMVG_main_ExportCameraFrustums to export estimated camera poses.

Regards,

**Comment by zharvey-welltok** [comment]
Hi @polto - thanks for the lead on `openMVG_main_ExportCameraFrustums`; is there any documentation on it? I searched for it over at [Read the Docs](http://openmvg.readthedocs.io/en/latest/search/?q=openMVG_main_ExportCameraFrustums&check_keywords=yes&area=default#) but didn't see any.

Thanks again!

**Comment by pmoulon** [comment]
Camera poses information is saved in the sfm_data.bin/json file once SfM is done.

You can use the binary openMVG_main_ConvertSfM_DataFormat to convert from one format to another.
i.e:

```
openMVG_main_ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data.json -V -I -E
```

You will see in the file the extrinsics camera poses, the ID referenring to a pose id in each view.

There is also another module in OpenMVG that allow to localize an image inside an existing reconstruction:
See http://openmvg.readthedocs.io/en/latest/software/localization/localization/

**Comment by polto** [comment]
Thank you @pmoulon , I forgot about openMVG_main_ConvertSfM_DataFormat.
We use it to extract precise camera location to superpose the photo on the point-cloud. 
here is a small demo : https://ww3.doxel.org/gallery/cloud?s=57f91b81536d597a25df182f (the interface is work in progress...)

**Comment by zharvey-welltok** [comment]
Thanks to both @pmoulon and @polto - you have been *enormously* helpful here!

But then what is the difference between `openMVG_main_ExportCameraFrustums` and `openMVG_main_SfM_Localization`? It sounds like `ExportCmeraFrustrums` calculates camera pose for *each* input image/view, whereas `SfM_Localization` only calculates camera pose for one *single* image/view?

**Comment by pmoulon** [comment]
- openMVG_main_ExportCameraFrustums exports a visual representation of the camera poses and look direction for meshlab or cloudcompare.
- openMVG_main_SfM_Localization localizes a new image inside an existing reconstruction.

**Comment by zharvey-welltok** [comment]
Thanks! 👍
