### ISSUE TITLE
SfM_DataColor generates twice as many points when using sequential than global

### ISSUE THREAD

**Issue by squeakus** [openMVG/openMVG#659]
Hi,
My apologies as this is less an issue than a question. I noticed that when I do a sequential and a global reconstruction of the same dataset, the colorized result for the sequential matching has twice as many points as the global reconstruction. They are both working off the same matches and the robust point clouds generated by openMVG_main_ComputeStructureFromKnownPoses have an almost matching point count. It is just the colorised sequential result which has many more points. I have tested it on several different datasets with the same result. Why is this the case?

**Comment by pmoulon** [comment]
Hi, the way that tracks are selected in the sequential and the global sfm pipeline are different.
Sequential pipeline use all the track that have a lenght from 2 to n.
The Global SfM pipeline use all the tracks that have been validated per triplet and visible by at least 3 view.
So the factor 2 you are observing is just a coincidence, the ratio is dependent of the dataset.

openMVG_main_ComputeStructureFromKnownPoses also use tracks validated from 3 to n view (but the merged correspondences are here computed by guided matching).

**Comment by squeakus** [comment]
So does that mean it is a better result? Twice the amount of points is a significant amount!

**Comment by pmoulon** [comment]
More points does not mean more accurate.

For example on this paper I shown that using a global pipeline can provide a more accurate reconstruction (while having less points than some Sequential Pipeline). "Moulon Pierre, Monasse Pascal and Marlet Renaud. ICCV 2013. Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion."

BTW, having more points can help the BA to converge towards a better optimum for some scene or to estimate better camera intrinsics.

**Comment by squeakus** [comment]
I suppose better is a subjective word. I am reading your paper now. Thanks for your help!

**Comment by pmoulon** [comment]
Please close the issue if you got the answer to your question
