### ISSUE TITLE
Homogenous scene detection

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#661]
I'm wondering if OpenMVG has any tools that I might be able to use for what I'm (presently) calling "_homogenous scene detection_".

My app will be taking in a short video as its input, and using `ffmpeg` to split that video up into all its constituent frames. Each frame will become its own (likely) JPG file. The video may or may not contain different "scenes". For instance, the first 10 seconds might be footage of a statue outside, then the video might suddenly cutover to footage of a basement, etc. In this case we would have two scenes (outside/statue and basement), and I want to separate each scene so that I can independently run the frames/images for each scene through its own SfM pipeline.

To do this I need some way of iterating through each frame of a video, comparing it to the last frame, and making a determination as to whether or not they are similar enough, or _homogenous_. Meaning, they are frames depicting the same scene.

Does OpenMVG have any tools that might be able to assist with this? If not, any recommendations?

Thanks!

**Comment by pmoulon** [comment]
Hi @zharvey-welltok 

The best solution for your problem would be to compute the image graph connected component at the end of main_ComputeMatches and to export various matches.X.bin file.
Then you can launch SfM on each of the connected component and obtain your various scene reconstruction (statue, basement...)

I can help on making a tool like that available

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - interesting idea!

If I understand you right, is this what you're talking about (?) :

![v1](https://raw.githubusercontent.com/hotmeatballsoup/3drecon-troubleshooting/master/openmvg_newtool_1.0.png)

Or am I misunderstanding what you're proposing? Thanks again for the help with this!

**Comment by zharvey-welltok** [comment]
Hi @pmoulon - any thoughts here? If a new tool needs to be written for this, I'd be happy to help/contribute all that I can.

**Comment by pmoulon** [comment]
As I said you can modify the main_ComputeMatches to add an option to export the connected component of the final geometric matching in various files.

**Comment by pmoulon** [comment]
This PR will allow you to solve this issue: https://github.com/openMVG/openMVG/pull/1135
