### ISSUE TITLE
Working with main_ComputeMatches' outputs

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#662]
I see that `main_ComputeMatches` generates 1+ `matches.X.bin` files as its output.

1. How many of these files does it generate, and what are their names?
2. Can I use `main_ConvertSfM_DataFormat` to convert these BIN files into human-readable JSON?

Thanks!

**Comment by pmoulon** [comment]
1. for the moment 2:
  - matches.putatives.bin (the regions matches)
  - matches.e/h/f.bin (the geometric filtered matches)

2. Those files cannot be converted to JSON. They can be converted to ASCII if you change the .bin to .txt in the matches save function.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - a few followup questions (as usual):

1. Is there a way to specify ASCII/`.txt` as an argument to `main_ComputeMatches`?
2. If I specify ASCII/`.txt`, will downstream tools like `main_GlobalSfM` be able to read the `.txt` file and use it, or would I have to generate BIN files as well?

As always, thanks!

**Comment by zharvey-welltok** [comment]
FYI @pmoulon I forked this repo and will be testing out changes for a new argument to `main_ComputeMatches`. The new `-t` flag will save match info to ASCII TXT files *as well* as saving them to BIN files if it is used.

If you're interested in getting a sneek peak at the code changes, they are here:
https://github.com/hotmeatballsoup/openMVG/commit/e19cade62ecc4c491650407a93e27007d77bd660

Once I can confirm they work and am confident they don't break, I'll submit a PR.

**Comment by zharvey-welltok** [comment]
OK I ran my changes locally and it appears to be half-working. When I ran `main_ComputeMatches` with the `-t 1` argument, it produced all its normal output as well as a `matches.putative.txt` file. **However** it did not create a `matches.e.txt` like I was also expecting, so I'll have to dig into why.

One quick question about the format/structure of these TXT files. The `matches.putative.txt` file that was created has 49,000 rows in it (!!!) and starts with:

```
0 1
940
2335 2038
1925 2039
1926 2042
1197 2044
14 38
1198 40
2568 2667
```

From the `Save(...)` method I linked to earlier, it looks like these are the lines of code responsible for writing this TXT file:

```
const size_t I = cur_match.first.first ;
const size_t J = cur_match.first.second ; 
      
const std::vector<IndMatch> & pair_matches = cur_match.second ;
stream << I << " " << J << '\n' << pair_matches.size() << '\n';
copy(pair_matches.begin(), pair_matches.end(),
     std::ostream_iterator<IndMatch>(stream, "\n"));
```

However I'm unable to find a class/file called `PairWiseMatches` in the source.

**I guess I'm trying to figure how/where we determine "Image #1 contains, say, 50 matches against Image #2.** Any help/steering you can provide here?

Thanks!

**Comment by pmoulon** [comment]
- Regarding bin -> txt
    - you must perform change there https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L160 and there https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L343

- matches file format
pair index i.e. I J
number of matches for this pair
```index of feature in view I``` ```index of feature in view J```

- Know if some images share content
Use the openMVG API, load the matches and check if in the PairwiseMatches map there is an entry for your image pair.

    - for example this is what it is done in https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_exportMatches.cpp#L131

**Comment by zharvey-welltok** [comment]
Thanks for all the help @pmoulon. I'll give this all a try in the next week or so. Closing this issue since you have answered all my questions (and then some!). Thanks again.
