### ISSUE TITLE
Do you know any tools can convert the ply file to tif image or jpg image?

### ISSUE THREAD

**Issue by mitsubishisony** [openMVG/openMVG#663]
Do you know any tools can convert the ply file to tif image or jpg image?

**Comment by zharvey-welltok** [comment]
My understanding (I'm a newbie like you) is that a PLY file is a 3D model/mesh, containing point/coordinate and edge information about that 3D mesh. So if you wanted to convert the mesh to an image, my guess is you'd have to:

1. (Very possibly) convert the sparse point cloud that OpenMVG creates for you into a **dense** point cloud from, say, MVE (I've had enormous success with that tool so far)
2. Apply textures to the mesh (the mesh file is just that - edge and vertex info, no visible colors/textures/materials/etc.) with, say, mvs-texturing (I've also had great success with that tool so far)
3. Figure out which angle/pose you want to take the picture from (remember the mesh is in 3D, whereas your photo is 2D, so you need to place the camera somewhere). I have no idea how you would do this (figure out the math & programming configs to position the camera), so I'll let someone else from the community weigh-in there.
4. Take a 'photo' of the 3D model at the camera position/pose that you set in the step above. I *believe* there is an OpenMVG tool you can use for this (`openMVG_main_SfM_Localization `), but I've never used it.

HTH!

**Comment by pmoulon** [comment]
PLY are 3D data, so there is way to convert it to images.
BTW, you can use meshlab to save screenshot from the viewpoint of your choice.
