### ISSUE TITLE
How are input images/files sorted when being read in by various OpenMVG tools?

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#665]
I am processing a video (MP4) and selecting sample frames (images/JPG files) to use for SfM. I place these sample frames in a `samples/` directory.

I have a `samples/` directory with three files in it, named `frame2.jpg`, `frame20.jpg` and `frame24.jpg` respectively. **Chronologically-speaking**, `frame2` was a frame from earlier in the videothan `frame20`, and `frame20` occurred earlier than `frame24`, etc.

However, when I do a `ls -al` on that directory, the images are listed as follows:

```
-rw-rw-r--  1 myuser myuser       0 Nov  2 12:14 frame20.jpg
-rw-rw-r--  1 myuser myuser       0 Nov  2 12:14 frame24.jpg
-rw-rw-r--  1 myuser myuser       0 Nov  2 12:14 frame2.jpg
```

So, according to the OS, `frame20` is sorted first, then `frame24`, and finally `frame2`. And so it appears that these files are not listed in the order that they should be (again, chronologically).

I *believe* that, in order for SfM (Global or Incremental) to be accurate/correct, it needs to process the files in the correct order.

I am worried about a situation where, because of the way the files are named, OpenMVG will process these files out of order, and yield inaccurate results.

So I ask: **How do OpenMVG tools like `main_ComputeFeatures` or `openMVG_main_SfMInit_ImageListing` read image files from the file system? In my example above, what order would the frames be read in?**

Also, I assume the solution would be to rename the sample frames so that the OpenMVG can read them from the file system in the correct order (yes? no?)? So something like:

```
frame2.jpg -> rename to frame1.jpg
frame20.jpg -> rename to frame2.jpg
frame24.jpg -> rename to frame3.jpg
```

**Comment by polto** [comment]
@zharvey-welltok , I do not know OpenMVG internals, but the only tool that will make a list is openMVG_main_SfMInit_ImageListing, all other tools are reading sfm_data.json file provided by openMVG_main_SfMInit_ImageListing.

You may also try to split your video using "%05d" for naming files. For example : "ffmpeg -i input.mp4  output_%05d.jpg" This way files will be named output_00001.jpg, etc. Any software would list them in correct order from the file-system.

**Comment by zharvey-welltok** [comment]
Thanks @polto - yes I plan on using something similar to `%05d` to acheive the correct padding, based on the number of frames in the video.

I guess what I'm looking for clarification on is: will `openMVG_main_SfMInit_ImageListing` correctly list/process files if they are padded correctly? Meaning, if I have 100K frames, and they appear on the file system as:

```
frame000001.jpg
frame000002.jpg
frame000003.jpg
...
frame009999.jpg
frame010000.jpg
..
frame099999.jpg
frame100000.jpg
```

...then will `openMVG_main_SfMInit_ImageListing` read them in the correct order (`frame000001.jpg` to `frame100000.jpg`)?

**Comment by pmoulon** [comment]
```openMVG_main_SfMInit_ImageListing``` will use an alphabetical order sorting so yes the pose and viewid will be listed as 000001 to 100000

**Comment by zharvey-welltok** [comment]
👍 thanks to both! I figured this much but needed to confirm!
