### ISSUE TITLE
ComputeFeatures -n X segfault on develop_subposes branch

### ISSUE THREAD

**Issue by polto** [openMVG/openMVG#667]
Hi !
ComputeFeatures seems not to be able to compute features on more than one image at a time on the develop_subposes branch. It segfault if I specify -n X option.
Regards.

**Comment by polto** [comment]
Yes, I have tried with -n 2 , and the same machine is doing -n 8 with same images with develop branch.

**Comment by pmoulon** [comment]
Do you have a log before the segfault, or a segfault message that could be informative to provide?

When you change from one branch to another, did you perform ```submodule update -i```?

**Comment by polto** [comment]
Yes, I did executed `git submodule update -i`

I am sure to be on the develop_subposes, after making the list, if I try with the develop branch I have this (normal) error message : 
```
Trying to load an unregistered polymorphic type (pinhole_subpose).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.

The input file "sfm_data.json" cannot be read
```

Now let's try with develop_subposes branch and "-n 2" :

```
/usr/local/bin/openMVG_main_ComputeFeatures
--input_file sfm_data.json
--outdir ./matching
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 2


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*openMVG_main_ComputeFeatures: /data/src/openMVG/src/third_party/eigen/Eigen/src/Core/DenseCoeffsBase.h:337: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = unsigned char; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
Aborted (core dumped)
```
with more than -n2 it does not output any error. just the "Aborted (core dumped)".
-n1 is produce keypoints and descriptors. 

Best regards,

**Comment by pmoulon** [comment]
So to summarize:

First message arises because you tried to use a binary from the develop branch on a sfm_data generated by the develop_subposes branch.
```Trying to load an unregistered polymorphic type (pinhole_subpose).```

If you tried on a sfm_data file generated by the develop branch, it should run fine, or crash for a reason that we don't know yet on your machine.

When you are using the develop_subposes binary, you see that the serialization message is not longer a problem, but then it crash for an unknow reason.
The Eigen error make me think that it crash by trying to accessing a pixel outside the image. But since one thread it was working fine, I don't know what is happening yet.

Can you run it in debug with gdb in order to identify where is the crash location?

Regards

**Comment by polto** [comment]
I did not had time to check with gdb, but I successfully executed with -n 8 with 4 of the 26 channels.
will do more tests later.
Regards

**Comment by pmoulon** [comment]
Please do it later on in order to let us improve the project.
Thank you.

**Comment by pmoulon** [comment]
I'm closing the issue since https://github.com/openMVG/openMVG/issues/747 will certainly fix the issue you encountered.
