### ISSUE TITLE
Issues with reconstructing 3D object, not enough poses

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#668]
I'm trying to establish a 3D scanning setup similar to this one (http://4.bp.blogspot.com/-SYBWerS5iAg/UKfELRIXLNI/AAAAAAAAAr8/L3ZYDTOQdQ0/s1600/taung_sfm_serie_optimized.gif).

But I currently have only been successful in a small number of poses being recognized.  I have included a link to 2 of my datasets (https://drive.google.com/open?id=0B00OebuWphsVQnh0YTR4SC1QcWs
).

I can paint the molds any color or change the lighting if that would help.  I tried to make some distinguishing features with the red pain but it didn't seem to make any difference in the results.

Any idea how I can improve the results either in software setting or in taking better photos?

**Comment by pmoulon** [comment]
The failure can comes from:
- too much matches confusion between the background and the foreground (your object)
  - the mask function can help you
  - or your can change your acquisition setting to put in front a very white background

Too look if the problem comes from this you can log the matches as SVG files using the exportMatching binary.

I think I will be able to make some test on your dataset next week or the following one.

**Comment by jpwhitney** [comment]
Thanks for the advice, somewhat at the same time as you were posting this I was trying a slightly different setup.

While reading this http://opensourcephotogrammetry.blogspot.com/2012/11/taung-project.html, I noticed that there were lines on the surface that the object was sitting on.  I then took off the white cardboard base and used instead the bare wood surface.

Uploaded in the same google drive folder I shared earlier is the working set with the new background.  Thanks again for your part of this fantastic bit of software, and for being so available.

**Comment by pmoulon** [comment]
I have tried the two first dataset you send to me, and they are working like a charm when the HIGH preset is used for feature detection.

```SfM_SequentialPipeline path_to_image path_to_image_reconstruction```

Here the resulting point could once SfM was performed:

FLAT:
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/20034547/181cb8b2-a37f-11e6-882d-9d6eae59d6ba.png)

Cave:
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/20034549/24ee8318-a37f-11e6-997d-02ebc18a1abf.png)


On your last dataset "Working", we see that the depth of field of your camera was not sufficient to produce sharp content everywhere. You can improve your camera setting by using a tripod and configure nicely your camera to have a large depth of field and so improve your future 3D reconstruction & model. See [here](http://digital-photography-school.com/understanding-depth-field-beginners/)
