### ISSUE TITLE
How to compute focal length when images lack EXIF data?

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#669]
In a [previous question](https://github.com/openMVG/openMVG/issues/666) I was using `openMVG_main_SfMInit_ImageListing` without the `-f` argument. I was also using images that did not have focal length info in their EXIF data, and so the resulting `sfm_data.json` had (essentially) UINTMAX set for each view's `id_intrinsic` value.

In that question I was advised by @pmoulon to re-run `openMVG_main_SfMInit_ImageListing` with a focal length of `-f 1.2*1920 = -f 2304`.

I'm wondering what the two magic numbers (`1.2` and `1920`) came from, and how to derive them on other image sets in the future. Any ideas? Thanks in advance!

**Comment by polto** [comment]
@zharvey-welltok , 1920 was supposed to be the width of your sensor and 1.2µ sensor's pixel size.
You should be able to find both parameters from sensor documentation. 
Regards.

**Comment by zharvey-welltok** [comment]
Thanks @polto but how did @pmoulon know what my sensor was?!?

**Comment by pmoulon** [comment]
Here the explanation about the values:
- 1920 comes from max (width,height) for your dataset,
- 1.2 is a scaling_ratio coming from the FoV of your camera 
  - For example if we simulate a 45 degrees of viewing angle
     - the focal_ratio will be => 0.5/tan(0.5 * FoV) => 0.5/tan(0.5 * 45/180*3.14) => 1.2

Then according those you can approximate the focal length as focal_ratio * max(w,h) => 1.2 * 1920

This formula provides a good guess for SfM if your camera have a "classical fov" near than 45.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon, this is all starting to make sense! When you say:

> "*1920 comes from max (width,height) for your dataset*"

...do you mean that my `sfm_data.json` contained width/height information, and that's where you obtained the 1920 from?

**Comment by pmoulon** [comment]
You can either look to the max size from the JSON or just open the image properties and look to the image size.

**Comment by zharvey-welltok** [comment]
As always, thanks @pmoulon 👍

**Comment by pmoulon** [comment]
You're welcome, I'm happy to help and explain things.
Perhaps those information must be somehow expressed into the online sphinx documentation ...

**Comment by caomw** [comment]
good
