### ISSUE TITLE
What is the definition of extrinsics in sfm_data.bin

### ISSUE THREAD

**Issue by LingyuMa** [openMVG/openMVG#671]
Is the "rotation" defined as: from world frame to camera frame, or from camera frame to world frame?
Is the "center" defined as: the center of the world frame represented in camera frame, or the center of the camera represented in world frame?

I'm not sure what should be the correct extrinsic matrix to convert a 3D point to camera frame because of the above confusions.

**Comment by pmoulon** [comment]
I refer you to read http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/#pinhole-camera-model

x = P X
Where P = K[R|t]

**Comment by LingyuMa** [comment]
So center should mean C I guess:
then the extrinsic should be [R | -RC]
I got it, Thanks!
