### ISSUE TITLE
try to add dense mesh using cmvs after openMVG sequential sfm

### ISSUE THREAD

**Issue by jagadish482** [openMVG/openMVG#672]
> openMVG_main_openMVG2PMVS -i Dataset/outReconstruction/sfm_data.json -o Dataset/outReconstruction
>cmvs Dataset/outReconstruction/PMVS/ [MaxImageCountByCluster=100]
> cmvs Dataset/outReconstruction/PMVS/ 30
>genOption Dataset/outReconstruction/PMVS/
>Dataset/outReconstruction/pmvs.bat

i done like above for dense cloud. but i am getting error like below
error : 
(and also attached screenshot)
pmvs2
pmvs/
option-0000tflag is not valid: 0
![usingcmvs](https://cloud.githubusercontent.com/assets/23214629/20138149/ba09ca66-a6a4-11e6-9531-1d730c245cc0.PNG)

**Comment by pmoulon** [comment]
Please check that there is valid data exported in the visualize and txt directories.
