### ISSUE TITLE
try to add dense mesh PMVS for openMVG sequential_sfm

### ISSUE THREAD

**Issue by jagadish482** [openMVG/openMVG#673]
> openMVG_main_openMVG2PMVS -i Dataset/outReconstruction/sfm_data.json -o Dataset/outReconstruction
> pmvs Dataset/outReconstruction/PMVS/ pmvs_options.txt

i done like above for getting pmvs dense cloud. Here i got D:\jagadish_gitHub\openMVG_results\openMVG_statue\reconstruction_sequential\PMVS\models\options.txt.ply but in this file nothing is there

**Comment by pmoulon** [comment]
Does there is some images in the PMVS image directory?

**Comment by jagadish482** [comment]
afther this --> openMVG_main_openMVG2PMVS -i Dataset/outReconstruction/sfm_data.json -o Dataset/outReconstruction 
pmvs directory created but in that directory there is no image directory. i attached screenshot of pmvs directory sub folders
![capture](https://cloud.githubusercontent.com/assets/23214629/20164306/a1d1c37e-a729-11e6-865f-f686a0f20f31.PNG)

aftere this generation i run --> pmvs2 ./PMVS/ pmvs_options.txt
then ./PMVS/models directory some new files are generating but pmvs_options.txt.ply file doesn't have anything.
![capture1](https://cloud.githubusercontent.com/assets/23214629/20164337/143bee30-a72a-11e6-86a9-8bdef2edfd06.PNG)

please help me to solve this

**Comment by pmoulon** [comment]
Can you tell me if there is some images in the visualize folder and some camera exported into txt (txt files)?

**Comment by jagadish482** [comment]
>openMVG_main_openMVG2PMVS -i  D:\jagadish_gitHub\openMVG_results\openMVG_statue\matches\sfm_data.json -o D:\jagadish_gitHub\openMVG_results\openMVG_statue

after above there is images in visualize folder and no camera info in txt

**Comment by pmoulon** [comment]
If there is not camera in txt, it certainly means that the SfM was not running fine.
Did you check the result of the SfM by looking to the number of poses that have been computed (in the log or in the clouds_and_poses.PLY) ?

**Comment by jagadish482** [comment]
yeah i checked clouds_and_poses.ply output is coming but it is not efficient output.below i am sending sample image and also .ply file
![img_4842 - copy](https://cloud.githubusercontent.com/assets/23214629/20164807/9a2e6934-a72d-11e6-9783-dbd11b1453ff.JPG)

**Comment by pmoulon** [comment]
PLY file is missing.

**Comment by jagadish482** [comment]
it is not supporting while uploading

**Comment by jagadish482** [comment]
but i am sending screenshots of cloud_and_poses.ply and colorized.ply.

![capture3](https://cloud.githubusercontent.com/assets/23214629/20165052/ed9e8d68-a72f-11e6-8d04-62889ce0c0eb.PNG)
![capture4](https://cloud.githubusercontent.com/assets/23214629/20165053/f17ad77a-a72f-11e6-99af-159b1632447b.PNG)

please see this and help me

**Comment by pmoulon** [comment]
I understand your problem:
You was trying to exporting a file in witch there is not camera poses.
This file is used to describe the scene for matching D:\jagadish_gitHub\openMVG_results\openMVG_statue\matches\sfm_data.json

then you have different file generated for SfM => sfm_data.bin and robust.bin.
D:\jagadish_gitHub\openMVG_results\openMVG_statue\**reconstruction**\sfm_data.json

Please use one of this two with the openMVG2PMVS binary and then rerun PMVS.
It will run fines and you will obtain your point cloud.

So please rerun PVMS (since now you took a file with valid poses camera information).

**Comment by jagadish482** [comment]
i haven't seen any file sfm_data.json file in a reconstruction_sequential directory. i only find sfm_dat.bin and robust.bin files why it is not generated can you tell me

**Comment by pmoulon** [comment]
I was telling you to use the sfm_data.bin or robust.bin.
The json file is only produced in the matches directory and must be used on for the matching purpose.

**Comment by jagadish482** [comment]
>openMVG_main_openMVG2PMVS -i  D:\jagadish_gitHub\openMVG_results\openMVG_statue\reconstruction_sequential\robust.bin -o D:\jagadish_gitHub\openMVG_results\openMVG_statue

i run above then pmvs folder created in that imges and camera info are generated in visualize and txt folders after that i run 
>pmvs2 D:\jagadish_gitHub\openMVG_results\openMVG_statue\PMVS\ pmvs_options.txt
nothing is changed and pmvs/models directory no file generated
![capture5](https://cloud.githubusercontent.com/assets/23214629/20166631/22ccbb34-a73c-11e6-998a-33048462b1c6.PNG)

**Comment by jagadish482** [comment]
openMVG_main_openMVG2PMVS -i D:\jagadish_gitHub\openMVG_results\openMVG_statue\reconstruction_sequential\sfm_data.bin -o D:\jagadish_gitHub\openMVG_results\openMVG_statue
i run above then pmvs folder created in that imges and camera info are generated in visualize and txt folders after that i run

pmvs2 D:\jagadish_gitHub\openMVG_results\openMVG_statue\PMVS\ pmvs_options.txt
nothing is changed and pmvs/models directory no file generated

like above

**Comment by jagadish482** [comment]
i tried cmvs also like below but some files generated nothing is there in .ply files

![cmpvs](https://cloud.githubusercontent.com/assets/23214629/20172147/d834c54e-a759-11e6-8347-a1210ef02564.PNG)

output in PMVS folder directory

![cmvs1](https://cloud.githubusercontent.com/assets/23214629/20172172/f2887328-a759-11e6-8b16-b3d80321b8d7.PNG)

**Comment by jagadish482** [comment]
one more help from you can you send all sample images which you are used for 2d images to 3d model.
i will run this library on your images. and i compare difference output based on camera taking photos

**Comment by pmoulon** [comment]
You can play with this dataset:
https://github.com/openMVG/ImageDataset_SceauxCastle

**Comment by jagadish482** [comment]
ok i will try on this sample images.

**Comment by jagadish482** [comment]
thank you pmoulon for helping i got my problem now. i worked on your sample images the final pmvs output also got. 
 Actually the problem is when i am working on my own sample images the pmvs2.exe is stop working. but i don't know why it is stoping. 
![pmvs](https://cloud.githubusercontent.com/assets/23214629/20205171/b3359360-a7fc-11e6-8171-acd55eb61200.PNG)

please update your openMVG docs http://openmvg.readthedocs.io/en/latest/software/MVS/PMVS/
there you write sfm_data.json but for pmvs we have to give sfm_data.bin

**Comment by jagadish482** [comment]
can you send statue sample photos

**Comment by pmoulon** [comment]
You can compile PMVS2 in debug mode and investigate.

**Comment by jagadish482** [comment]
This part I already done...it showing some mvsc.dll  exception. I am not sure what exactly this error tomorrow I will inform you.

**Comment by jagadish482** [comment]
when i am applying >pmvs2 D:\jagadish_gitHub\openMVG_results\monument_result\PMVS\ pmvs_options.txt  three things happening those are

1. 
![pmvs1](https://cloud.githubusercontent.com/assets/23214629/20254815/cbb1c34c-aa5d-11e6-9a22-f4380897da00.PNG)

when i run pmvs2 in cmd it is running like above. by this no ouptut is generating in models directory even though visualize and txt contains images and .txt files. why it is like that i am not able to understand


2.
 when i run pmvs2 in cmd it is running like below
![pmvs2](https://cloud.githubusercontent.com/assets/23214629/20255127/42a14354-aa60-11e6-9e8f-7e7ad55340ab.PNG)

after that i debug the program then visual studio showing like below
![pmvs3](https://cloud.githubusercontent.com/assets/23214629/20255245/fed3a756-aa60-11e6-9bcf-4f77810fbf24.PNG)

after i click on Break. it showing like below

![pmvs4](https://cloud.githubusercontent.com/assets/23214629/20255256/16e291d6-aa61-11e6-9784-1707a9bc69ed.PNG)

so please help me to solve this

3.
when i run pmvs2 in cmd it runnin succefully and it generated ouput in model directory

Actually for some sample images case one is happening, for some sample images case two is happening, for some sample images case three is happening but i am not understanding why it is like that.


And also please tell me how to get mesh structure

**Comment by pmoulon** [comment]
If you want a mesh I would like to recommend you to use the MVE or OpenMVS software.
Those two solutions integrates densification, surface computation and texture reprojection.
