### ISSUE TITLE
Rebuilding OpenMVG after making code changes

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#675]
To install + build OpenMVG on an Ubuntu box, I run:

```
cd ~
git clone --recursive https://github.com/openMVG/openMVG.git
mkdir openMVG_Build
cd openMVG_Build
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
make
```

This install binaries under: `/home/myuser/openMVG_Build/Linux-x86_64-RELEASE/`.

I would like to now make some code changes to OpenMVG and test them out. After I make those changes, how do I rebuilt OpenMVG so that the changes are reflected in the binaries living under `/home/vagrant/openMVG_Build/Linux-x86_64-RELEASE/`?

Can I just re-run:

```
cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
make
```

Or do I have to delete the existing binaries first, do other cleanup, etc.?

**Comment by pmoulon** [comment]
You must edit your code and then run make.
cmake must be done once

When your are going to develop new code it s preferable to take the develop branch
git checkout develop
git submodule init
git submodule update
cmake ...
make...

**Comment by zharvey-welltok** [comment]
Great, thanks @pmoulon 👍
