### ISSUE TITLE
AKAZE for non-blurry images?

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#677]
I've been told `AKAZE_FLOAT` works better than `SIFT` as a describer method for `ComputeFeatures` when the images/views are blurry.

**But what about when there is no blur?** Does `AKAZE_FLOAT` still outperform `SIFT`, or is `SIFT` more perfomant with clear images?

**Comment by csp256** [comment]
Looks like AKAZE_FLOAT is called MSURF (modified SURF) in the original AKAZE implementation and references "CenSurE: Center Surround Extremas for Realtime Feature Detection and Matching". Make what you will of the results in that paper; you should just try both and see which works better.

**Comment by zharvey-welltok** [comment]
Thanks @csp256 but [that paper](http://snorriheim.dnsdojo.com/doku/lib/exe/fetch.php/en:engineering:slam:cslam:censure.pdf) doesn't mention the word "blur" in it a single time. I'm not opposed to reading it, but don't want to commit to doing so unless I have a high degree of confidence it will address my question.

Like you said, I could of course try both over a large dataset of various image collections, but was hoping a veteran community member/contributor might know a "rule of thumb" here off the top of their head. Thanks again for the paper reference - looks interesting!

**Comment by pmoulon** [comment]
You can find some experiments there:
Quantitative Comparison of Feature Matchers Implemented in OpenCV3
http://vision.fe.uni-lj.si/cvww2016/proceedings/papers/04.pdf

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - I took a look at that last night, and if I'm reading/understanding it correctly, it *sounds* like `AKAZE_FLOAT` is more accurate (albeit a little slower) than `SIFT` for **both** blurry and non-blurry image sets, correct? Thanks again!

**Comment by pmoulon** [comment]
Right, from my experiments is that in a general manner AKAZE features are:
- a bit less accurate localization,
- working better on blurry images.

**Comment by zharvey-welltok** [comment]
Awesome - thanks! 👍
