### ISSUE TITLE
List of supported intrinsic parameters

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#678]
Where can I find a list of all the intrinsic parameters supported by OpenMVG? From [this page in the docs](http://openmvg.readthedocs.io/en/latest/openMVG/sfm/sfm/?highlight=intrinsic):

```
struct SfM_Data
{
  /// Considered views
  Views views;

  /// Considered poses (indexed by view.id_pose)
  Poses poses;

  /// Considered camera intrinsics (indexed by view.id_cam)
  Intrinsics intrinsics;

  /// Structure (3D points with their 2D observations)
  Landmarks structure;

  // ...
}
```

But when I search for a file called `Intrinsics` in this GitHub repo, I don't see any. Any ideas?

**Comment by pmoulon** [comment]
The current list of camera model that are supported are listed by the help of main_SfMInit_ImageListing
1: Pinhole
2: Pinhole radial 1
3: Pinhole radial 3 (default)
4: Pinhole brown 2
5: Pinhole with a simple Fish-eye distortion

All those camera models are defined in openMVG/cameras

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon but I *think* you might be misunderstanding me!

I assume that camera model (pinhole, fish-eye, etc.) is only **one (1)** intrinsic parameter that OpenMVG supports/uses.

For instance in the code snippet above (in my original question) you see:

    Intrinsics intrinsics;

I assume this `Intrinsics` object is a class somewhere in OpenMVG source code, no?

Either way, I'm intterested in understanding what **all** the intrinsic parameters are, not *just* camera model. Make sense? Thanks again!

**Comment by pmoulon** [comment]
You can take a look to the code in order to understand the number of parameter for each camera model:

1: Pinhole => **3** parameters (focal, principal point x, principal point y)
2: Pinhole radial 1 => **4** params (focal, principal point x, principal point y, one radial distortion factor)
3: Pinhole radial 3 (default)  => **6** params (focal, principal point x, principal point y, 3 radial distortion factors)
4: Pinhole brown 2 => **8** params (focal, principal point x, principal point y, 5 distortion factors (3radial+2 tangential))
5: Pinhole with a simple Fish-eye distortion  => **7** params (focal, principal point x, principal point y, 4 distortion factors)

Most of the time providing guess for the focal and principal_point is sufficient, BA will estimate the others.

FYI: here some explanation about the pinhole camera model: http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon, as I'm getting deeper into this, a lot more things are starting to make sense.

A few quick followup questions if you don't mind:

1. My *understanding* is that **focal length** (which often seems to be referred to as just "focal") is the distance from the camera to the image plane. **But wouldn't this distance change depending on *where* on the image plane we're measuring?!?** For example, the distance from the camera to the center of the image plane might be, say, 5.0 units. But the distance from the camera to the edge/perimeter of the image plane might be, say, 5.25 units. So what does OpenMVG consider to be the focal length (as the `-f` argument to `ImageListing`)?
2. I'm having a tough time understanding the concept of the *principal point*. I assume its the point, on the image plane, where some "*principal*" resides. **But what is the *principal*?** Is it just the center of the image?
3. When you say: "*Most of the time providing guess for the focal and principal_point is sufficient...*", are you talking about the `-k` (intrinsic) argument to `ImageListing`?
4. When you say "*...BA will estimate the others.*", what is "BA"?

Thanks, as always :-)

**Comment by pmoulon** [comment]
1. -f is the focal for intrinsics is defined in pixels. In the EXIF it is defined in mm.
2. this is the common name, principal point, point where all the ray pass through. Sometimes is the center of the image, but since the optics and sensor are not perfectly aligned it can move a bit by some offset. This refinement is done by the BA => Bundle adjustment (non linear adjusment of the parameter to reduce the residual error of the 3D projection to the image observations)
3. -k is a way to providing the principal point and the focal lenght as input to the software, while f only control the focal.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon :

1. Regarding principal point, can there be more than one of them, or just one principal? If you can, please take a look at [the photos in my sample repo](https://github.com/hotmeatballsoup/3drecon-troubleshooting/tree/master/basementtoy/frames). **What might be a principal point in that image set, and why?**
2. Regarding the `-k` option, are principal point and focal length the *only* two inputs I can specify with `-k`, or does it allow one to specify the other (camera model-based) intrinsic parameters? For instance, the Pinhole Radial 3 camera model has 6 intrinsic parameters: focal, principal-x, principal-y and then 3 radial distortion factors. Could I specify these radial distortion factors with `-k`?

**Comment by pmoulon** [comment]
1. Using a principal point at the center of the image is fine for your image. There is always one principal point. Some camera implementation use 2 (one for the optics, and one for the image sensor but it does not improve so much the results at my sense)
2. -k is only useful to set the focal and the principal poin, if you want to configure radial parameters you must edit the generated sfm_data.json. There is some work on making a more configurable tool that allow to have a deep settings of the parameters thanks to some regular expression, but it's work in progress (https://github.com/hcjghr/openMVG/commit/16cd01a81da0c768d3fe9d2a9308c7431149091f @hcjghr)

**Comment by khouloud21** [comment]
hello can anyone help me plz :
I typed the command $ openMVG_main_SfMInit_ImageListing -i [] -d [] -o [] but an error message appears as follows "the input directory dosen't exist"
Images / home / hp / openMVG_Build / software / SfM / ImageDataset_sceauxCastle / images)

**Comment by pmoulon** [comment]
You can drag and drop the folder from your GUI to the command line and you will be sure to not do a mistake in the Image folder path.

**Comment by khouloud21** [comment]
Hello ,
i did exactly the same way what you tould me and it didn't work
despite the path is correct and i've changed the camera model to 5 but when
i run it gaves me the previous configuration as it shows the image down
below
i hope you can help me to go through this  ...
[image: Images intégrées 1]

2017-04-11 20:12 GMT+02:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
Please use the online github interface to add images, else it does not work.

**Comment by khouloud21** [comment]
But I want to use my own pictures or you want to say that I have to put my
photos that are taken by GOPRO online on the github and I use the download
link which is in a python file

2017-04-11 20:50 GMT+02:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
No I mean, you wrote "t shows the image down
below" but as you see here the image does not appear https://github.com/openMVG/openMVG/issues/678#issuecomment-293363449

**Comment by khouloud21** [comment]
~/openMVG_Build/Linux-x86_64-RELEASE$ ./openMVG_main_SfMInit_ImageListing -d /home/hp/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_databasetxt -i home/hp/openMVG_Build/software/SfM/Chauffage/images -o home/hp/openMVG_Build/software/SfM/Chauffage/matches
 You called : 
./openMVG_main_SfMInit_ImageListing
--imageDirectory home/hp/openMVG_Build/software/SfM/Chauffage/images
--sensorWidthDatabase /home/hp/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_databasetxt
--outputDirectory home/hp/openMVG_Build/software/SfM/Chauffage/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

The input directory doesn't exist

**Comment by pmoulon** [comment]
a '/' is missing before home in the -i and -o option
a '.' is missing before txt

Please run:

`~/openMVG_Build/Linux-x86_64-RELEASE$ ./openMVG_main_SfMInit_ImageListing -d /home/hp/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i /home/hp/openMVG_Build/software/SfM/Chauffage/images -o /home/hp/openMVG_Build/software/SfM/Chauffage/matches`

**Comment by khouloud21** [comment]
i'm trully thankful for your help, i corrected the mistakes and launched the command and that's the result :

./openMVG_main_SfMInit_ImageListing
--imageDirectory /home/hp/openMVG_Build/software/SfM/Chauffage/images
--sensorWidthDatabase /home/hp/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/hp/openMVG_Build/software/SfM/Chauffage/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

SfMInit_ImageListing report:
listed #File(s): 53
usable #File(s) listed in sfm_data: 53
usable #Intrinsic(s) listed in sfm_data: 0



Aéfter that, i opened the Json file and that's the result  : i cannot found the intrinseque parametres WHYYY ???  : ( i used 53 images and i obtained 2 VIEWS, i will put it down below so you can see the camera parametres )

SfMInit_ImageListing report:
listed #File(s): 53
usable #File(s) listed in sfm_data: 53
usable #Intrinsic(s) listed in sfm_data: 0

{
            "key": 50,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483699,
                    "data": {
                        "local_path": "",
                        "filename": "062.JPG",
                        "width": 3000,
                        "height": 2250,
                        "id_view": 50,
                        "id_intrinsic": 4294967295,
                        "id_pose": 50
                    }
                }
            }
        },
        {
            "key": 51,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483700,
                    "data": {
                        "local_path": "",
                        "filename": "063.JPG",
                        "width": 3000,
                        "height": 2250,
                        "id_view": 51,
                        "id_intrinsic": 4294967295,
                        "id_pose": 51
                    }
                }
            }
        },
        {
            "key": 52,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483701,
                    "data": {
                        "local_path": "",
                        "filename": "064.JPG",
                        "width": 3000,
                        "height": 2250,
                        "id_view": 52,
                        "id_intrinsic": 4294967295,
                        "id_pose": 52
                    }
                }
            }
        }
    ],
    "intrinsics": [],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

**Comment by pmoulon** [comment]
If your camera is not recognized in the camera database you must have a message at the SfMInit_ImageListing stage.
If your images does not have any exif information, you must set manually the pixel focal length by using the -f option on the binary. You can set -f X.
With X = 1.1 * max(w,h)
