### ISSUE TITLE
Plane detection

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#679]
Does OpenMVG have any tools that would aid in "plane detection", that is, detection of flat surfaces in a set of input images (or reconstructed sparse point cloud)?

**Comment by pmoulon** [comment]
There is on dedicated tool.
You can detect some by using the Homography filter on main_ComputeMatches (homography is a planar relationship between two images). It will help you to detect corresponding point that can be part of 3D planar point cloud.

If you want to detect planes in point cloud I would like you to look to PCL library

**Comment by zharvey-welltok** [comment]
Awesome thanks for the reference! I will check it out!
