### ISSUE TITLE
ComputeMatches pair list

### ISSUE THREAD

**Issue by Jhfelectric** [openMVG/openMVG#680]
Hello,
What would be the input format of the 'pair_list' file, parameter of openMVG_main_ComputeMatches ?

I have followed the source code, and as far as I can understand (not a c++ geek), the file should list image view ids (or keys ? - from sfm_data.json file), 2 images per line.

i.e. 
1 2
2 3
3 4
etc...

When I do this, the program tells me the first image is out of range, showing I: huge number, J:2, N:97.
Can you explain further ?

Thanks for your time and the hard work,
Julien

**Comment by pmoulon** [comment]
You done it right (you must use the image view ids),
Have you checked  with just the first entry in a tiny file like
```
1 2
2 3
```
then add your whole file again and check the number inside, perhaps there is a space error at reading time... and so it read a too large number

**Comment by Jhfelectric** [comment]
Bonjour Pierre,
Thanks for the hints but that didn't do the trick.
The output I get is always the same:

 - PUTATIVE MATCHES -
Use: user defined pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
loadPairs: Invalid input file. Image out of range. I: 4610973848766301775 J:2 N:97

But never the same number for I.
Julien

PS: working on Windows 10

**Comment by Jhfelectric** [comment]
As to make sure, the ID to use in the matching file is the "id_view" from this sfm_data.json sample:
```
        {
            "key": 1,
            "value": {
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "\\",
                        "filename": "102.jpg",
                        "width": 2592,
                        "height": 1944,
                        "id_view": 1,
                        "id_intrinsic": 0,
                        "id_pose": 1
                    }
                }
            }
        },
```
Correct ?
Thanks.

**Comment by pmoulon** [comment]
Correct,
Can you share your pair list file, I would try to run in debug to understand what is happening...

**Comment by Jhfelectric** [comment]
[matching.txt](https://github.com/openMVG/openMVG/files/593501/matching.txt)

File is attached here in.
My guess is that the line 

`    oss >> I;`

gives a different result depending on the machine's architecture (no ?).

![image](https://cloud.githubusercontent.com/assets/12148725/20330772/09736a26-abdc-11e6-99df-d439bb4451aa.png)

Thanks

**Comment by pmoulon** [comment]
I took a look at your file and I have the same problem as you.
By looking deeper I think the problem comes from the file encoding.
It seems that you file is encoding in UTF8 and it creates a problem at reading time.
When I put the file to "UTF8 without BOM" or "ANSI" format with notepad++ all is working as expected.

Fix:
Please, can you try to encode you file to ANSI and try again?

**Comment by Jhfelectric** [comment]
Yes, that did the trick !

Merci Pierre, now I can move on :)

**Comment by pmoulon** [comment]
De rien 👍
