### ISSUE TITLE
Scene skew correction possible?

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#681]
Using similar data sets as mentioned here https://github.com/openMVG/openMVG/issues/668
I am obtaining sets with significant scene skew.  Is it possible to remove this somehow early on in the pipeline?

**Comment by pmoulon** [comment]
Can you explain what do you understand by scene skew?
Do you can share a screenshot or a dataset?

**Comment by jpwhitney** [comment]
Yes, thanks, I suppose my question was rather unclear.  Using a setup like this: 
![makeshift-photo_lab](https://cloud.githubusercontent.com/assets/17804207/20420045/8b849056-ad0f-11e6-8ac2-e20a86c0c1ab.jpg)
 I have taken multiple photos and have reconstructed both a sparse pointcloud and using OpenMVS a dense pointcloud and mesh.  I have attached one image of the skew and resulting topdown projection:
![scene_skew](https://cloud.githubusercontent.com/assets/17804207/20420050/97a97496-ad0f-11e6-9e50-ccf01ea6139f.jpg)

And after manually adjusting the coordinate reference frame have fixed the skew and loading the image into R with the raster package (inset image) have a result like this: 
![deskewed](https://cloud.githubusercontent.com/assets/17804207/20420058/b1bd04f6-ad0f-11e6-8d28-eef206960355.jpg)

The desired end result is something like this: 
![top](https://cloud.githubusercontent.com/assets/17804207/20420067/c1261964-ad0f-11e6-8afb-702b55392ff9.jpg)

A top down projection of the scene with color or grayscale representing height.

The problem I have is that this process is manual, I would like to have the z-axis already in the correct position, vertical.  While I have obtained sufficient results like this I would like to minimize the error.  It seems that a programmatic solution would be more accurate in aligning the z-axis to the vertical, rather than manually fixing the skew.

Is this possible without too much trouble?

**Comment by pmoulon** [comment]
I think you can use an ICP algorithm to fit your scene to the model you want to compare.
It will be hard to have something perfect to guess your basis plane that define the coordinate system.
Or else we can try to add a binary to try to fit a plane to the scene and rotate the scene in order to make the place orthogonal to Y up.

**Comment by pmoulon** [comment]
@jpwhitney Can you close the issue if you have all the answer to your questions?

**Comment by pmoulon** [comment]
Closed due to inactivity.

**Comment by jpwhitney** [comment]
Sorry I didn't notice.  Yes you did answer my questions, thank you.
