### ISSUE TITLE
Adjusting scale and rotation of point clouds

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#682]
I have a 3D recon pipeline that consists of ffmpeg, OpenMVG, MVE and mvs-texturing. I've been able to use this pipeline now to reconstruct several scenes recorded from my smart phone - exciting!

At the end of my pipeline, after mvs-texturing has ran and produced a textured mesh (OBJ/MTL files) I load them into Blender to view the final model. In every case, I need to zoom way in on the model and then rotate it significantly in order to view it upright.

I'm wondering why Blender is initially loading my models to be so tiny and rotated so strangely, and am wondering if there's anything I can supply to my OpenMVG commands to correct it.

On the zoom issue, I'm wondering if I can specify a better *scale factor* argument to `ImageListing` somehow. And for the rotation issue, I see there is a `-u` (upright) argument that `ComputeFeatures` takes. Might any of these help me?

If so, how would I provide `ImageListing` with a custom scale factor?

If not, then do you have any suggestions as to where the model might be getting bad transformation (scale/rotation) data from?

Thanks!

**Comment by whuaegeanse** [comment]
Three is a small mount of points which are far away from the main points cloud.  This situation can be caused by wrong matched points in the stage of ba and  dense matching. View the result of OpenMVG before Using MVE to make sure there are wrong matched points. Actually, you can delete the wrong matched points before the next process stage.

**Comment by zharvey-welltok** [comment]
Thanks @whuaegeanse - it sounds like you're saying that the reason why the model is so tiny in Blender is that there are actually points that are very far away from the main point cloud, yes? And that removing them would cause the model to appear larger when first loaded?

Any idea as to *how* I can view the results of OpenMVG, prior to sending them on to MVE? When I use `ComputeStructureFromKnownPoses`, I specify its out as a `/recon` directory, and inside that directory I see a lot of files, namely:

* A bunch of `XXX_Resection.ply` files
* `cloud_and_poses.ply`
* `colorized.ply`
* `initialPair.ply`
* **`robust.ply`** -> I *believe* this is the final output, but not 100% certain...
* `sfm_data.bin`

The final tool that I run in my OpenMVG pipeline is `xyz`, and a sample command I use is:

    openMVG_main_ComputeStructureFromKnownPoses -i path/to/sfm_data.bin -m path/to/matches -o path/to/recon/robust.ply

...as well as others. Which file(s) contain the "results" of `openMVG_main_ComputeStructureFromKnownPoses`, I assume its `robust.ply`? More importantly, **how do I view these results in OpenMVG?**

Also, if your theory is correct and I'm able to remove the points that are far away, and this fixes the scale/zoom issue that I described above, I still have the rotation issue to deal with...any thoughts there?

Thanks again!

**Comment by csp256** [comment]
Regarding scale, one of the simpler methods I have heard suggested is to compute the median value along each axis. This corresponds to a point. Translate your geometry so this point is at the origin. 

Now, for each axis, compute the median value to the left and to the right. (corresponding to the boundaries between the middle half and the outer quartiles) Take the maximum of these 3 values. Apply a constant scaling factor to your geometry which is equal to the reciprocal of that maximum. 

You are now guaranteed that at least 50% (and quite probably more) of your geometry falls within the biunit cube. You can (and maybe even should) tweak this so instead of ignoring the outer quartiles you ignore the outer octiles or some other fraction.

For rotation, I have heard similar methods proposed, using instead some robust concept of variance around the median of your geometry. But, you can probably use prior information from your phone (accelerometer or just orientation providing a notion of "up") to greater effect in this special case. 

You are still going to need to do some sanity checking, but these approaches should at least get rid of the "where the heck is my imported model??" problem.

**Comment by zharvey-welltok** [comment]
Hi @csp256 those are some very interesting ideas - thank you!

A few followup questions if you don't mind. First, when you say "*compute the median value along each axis*", what exactly do you mean? Can you provide a simple example?

Thanks again!

**Comment by csp256** [comment]
Ignore the 3d structure and only look at the coordinates of one axis as if they are were an unordered set of numbers. Compute the median of this set. 

This is more robust than just computing the mean, because it is reasonably insensitive to outliers.

**Comment by zharvey-welltok** [comment]
OK thanks again @csp256 - I feel like I'm missing something here though!

So let's take the x-axis for example (please excuse this horrid drawing):

![x-axis](https://i.imgsafe.org/df610050d2.png)

This axis has 10 values, 0-9. So it *sounds* like you're suggesting I take the median of these:

    median([0,9]) = (0 + 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9) / 10 = 45 / 10 = 4.5

So our x-axis "median" value is `4.5`. Several posts above your first sentence was:

> "*Regarding scale, one of the simpler methods I have heard suggested is to compute the median value along each axis. This corresponds to a point. Translate your geometry so this point is at the origin.*"

So now I've computed the median for one of the three axes (x-axis), although I would imagine it would be the same value for all 3 (median of x = median of y = median of z = 4.5). This gives us the (x,y,z) point of `(4.5, 4.5, 4.5)`.

So then you say to "*Translate your geometry so this point is at the origin.*" So to me, this means that if my point cloud has a vertex that *was* at, say, `(0, 1, 0)`, then we apply the previous transformation to it, and that point now becomes `(4.5, 5.5, 4.5)`.

Two questions here:

1. Am I understanding this correctly? If not, where am I going awry?; and
2. How do I know how many values each axis has?

Sorry to be so dense here, just a total newbie trying to make sense of this stuff. Thanks again enormously!

**Comment by pmoulon** [comment]
You can collect the X value of the structure (the 3dpoint cloud) in a vector and then use this function from openMVG https://github.com/openMVG/openMVG/blob/master/src/openMVG/numeric/numeric.h#L574

**Comment by csp256** [comment]
I am suggesting a programmatic solution. Are you a programmer? My advice might be useless unless you are. 

That is the formula for the mean, not the median. The median is when you sort the data and find the middle value.

The median of {-1, 3, 1, 10000000, 2} is 2. The mean is 2000001. 

So find the median of the x coordinates. Find the median of the y coordinates. Find the median of the z coordinates. Label these a, b, and c respectively. For every vertex v with coordinates vx, vy, vz let its new coordinates be vx-a, vy-b, vz-c. 

This will place some point (that is kinda close to what a human would call the "center" of the object) at the origin. Now, to scale it:

Sort the x values (well, the new coordinates). Find the value which is 10% of the way into this list of sorted x values, and the value which is 90% of the way into this list. Call these mx and Mx. Do the same thing with y and z to find my, My, mz, and Mz.

Find the maximum of mx, Mx, my, My, mz, and Mz. Call this value MAX. Multiply every coordinate for every vertex (which have all previously been translated) by the reciprocal of MAX, aka 1.0 / MAX. The result is that >= 80% of the geometry is contained within the biunit cube around the origin.

This technique places no bound on how far out geometry may be, but will place most of the geometry within a reasonable volume.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - when you say:

> "*You can collect the X value of the structure (the 3dpoint cloud) in a vector...*"

...do you mean, for all points in the cloud, obtain their x-components, and place all those x values inside a vector?

So, let's pretend I have a point cloud with 3 points in it:

* (1,4,200)
* (5,60,35)
* (12,100,402)

Then the vector would consist of [1,5,12], yes? Thanks!

**Comment by zharvey-welltok** [comment]
Thanks @csp256 - sorry, I was reading the word "median" but my mind kept thinking *mean*. Yes I know what a median is (doh!) and yes I'm a developer. I've just been living in the enterprise/business world for the past decade and am rusty on a lot of my math from school.

Thanks for explaining this to me - I'll give it a shot in the next few days!

**Comment by zharvey-welltok** [comment]
Hi @pmoulon and @csp256 - just a quick update:

I re-ran `ComputeFeatures` with the upright flag (`-u 1`), and then kept running my model through my typical pipeline (OpenMVG -> MVE -> mvs-texturing -> Blender). I did this hoping that the upright flag might prompt the model to load right-side up in Blender. However when I imported the final textured mesh (OBJ file) into Blender, I see it is still upside down.

So I ask: is the purpose of this upright flag to help correct rotation issue like what I'm seeing, or does it do something else entirely different. Any suggestions as to what I can do (with OpenMVG at least) to make sure models loading into Blender always appear right-side up?

**Comment by pmoulon** [comment]
Hi,

The ```-u 1``` option will not help to solve your model rotation issue.
This mode is intended to avoid the rotation estimation of the features and so it works better when you don't need rotation invariance for matching (like having a camera on a car, bike).
It can works also around object if your do not change the orientation of your camera during the shooting session.

If you are in this setting you can use the ```-u 1``` and the process will be a bit faster (since SIFT rotation invariance compute from 1 to 4 descriptor per keypoints).

**Comment by zharvey-welltok** [comment]
Makes sense, thanks @pmoulon - understood about the `-u 1` option.

But, if that doesn't solve my rotation issue, any idea what would?

I think either your suggestion to use `minMaxMeanMedian` or @csp256 's suggestion to programmatically change the point scaling (see above) will help solve the scaling issue, though admittedly I haven't tried either yet.

But I have no idea how to solve this rotation issue, and its an important aspect to my project. Essentially, if I can run a set of images through OpenMVG->MVE->mvs-texturing, and load the resulting model into Blender and have it displayed with correct location/rotation/scaling values, then I can continue doing further processing/analysis on the models. But if the models *don't* display correctly, I can't process them at all. Any ideas how to solve the rotation issue? As always, thank you!

**Comment by pmoulon** [comment]
For the rotation issue, you must choose which is your reference image, compute the orientation of the camera Up axis (Y), if it is not up, you must flip the scene.

**Comment by zharvey-welltok** [comment]
Thanks @pmoulon - regarding Up axis orientation:

* If the reference image is taken "upright" (meaning the top of the image goes straight up into the sky, and the bottom of the image is the ground), then wouldn't the Up axis orientation always be `(0,1,0)`?; and
* If the reference image was taken by rotating the camera 90&deg; clockwise (so that now the sky is on the right, and the ground is on the left), wouldn't the Up axis orientation be `(1,0,0)`? I'm just asking these questions to confirm I understand what you mean by "*...compute the orientation of the camera Up axis...*"

Then, after I've computed the orientation of the camera Up axis, how do I actually use that computation to adjust `sfm_data.bin` (or any other files OpenMVG works with) so that the final point cloud generated by OpenMVG is rotated correctly? Are there command-line tools for this?

**Comment by zharvey-welltok** [comment]
Any thoughts @pmoulon ?

**Comment by pmoulon** [comment]
There is not command line tool yet, but we can add a new one if you want.

**Comment by jiangjiayao** [comment]
Hello @zharvey-welltok , were you able to figure out how to correct the rotation issue? Thanks!

**Comment by caokui1221** [comment]
Hello @jiangjiayao , have you solve this problem? Thanks!

**Comment by jiangjiayao** [comment]
@caokui1221 sorry i have not
