### ISSUE TITLE
Where to find the OpenMVG GUI (for visualizing point clouds)?

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/openMVG#684]
My current OpenMVG pipeline consists of:

1. `openMVG_main_SfMInit_ImageListing`; then
2. `openMVG_main_ComputeFeatures`; then
3. `openMVG_main_ComputeMatches`; then
4. `openMVG_main_IncrementalSfM`; then
5. `openMVG_main_ComputeSfM_DataColor`; then finally
6. `openMVG_main_ComputeStructureFromKnownPoses`

Furthermore, that final command (`openMVG_main_ComputeStructureFromKnownPoses`), is invoked via:

    openMVG_main_ComputeStructureFromKnownPoses -i path/to/sfm_data.bin -m path/to/matches -o path/to/robust.ply

According to [the docs](http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/), there are tools to visualize the point clouds generated by OpenMVG. However, after combing the docs over, I can't actually find a GUI that actually does this. I *do* see a GUI for Ground Control Points Registration, but I don't think that's what I'm looking for.

Throughout the docs and these GitHub issues, I see lots of screenshots, seemingly taken from an OpenMVG GUI, that look like this:

![openmvg-gui](https://cloud.githubusercontent.com/assets/3235050/20034651/23ee724a-a382-11e6-92f9-610e0e2c925c.png)

So I ask, it seems that the final output from my OpenMVG pipeline is a `robust.ply` file. I **assume** this PLY file is a sparse point cloud (yes?).

**How can I view this point cloud in the OpenMVG GUI?** Thanks!

**Comment by pmoulon** [comment]
In order to view PLY file you can use MESHLAB or CLOUDCOMPARE.
The screenshot you show was taken with MESHLAB (we recognize the brackground gradient).

PS: note that openMVG_main_ComputeStructureFromKnownPoses is optional.
You can stop the process at 5

**Comment by zharvey-welltok** [comment]
👍
