### ISSUE TITLE
openMVG_main_ComputeSfM_DataColor core dump

### ISSUE THREAD

**Issue by eokeeffe** [openMVG/openMVG#685]
Heya, I'm testing some changes to the OpenCV based descriptors.
Everything is running really well, only during the colorization I'm getting a core dump error.
I've added the error below.

openMVG_main_ComputeSfM_DataColor: /home/username/Modelling/openMVG/src/third_party/eigen/Eigen/src/Core/DenseCoeffsBase.h:337: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<openMVG::image::Rgb<unsigned char>, -1, -1, 1, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = openMVG::image::Rgb<unsigned char>; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
Aborted (core dumped)

Any idea what could be happening?

System Info
Ubuntu 16.04
OpenCV 3.1
latest update in OpenMVG

**Comment by pmoulon** [comment]
Seems like trying to access to a pixel outside the image domain.

**Comment by pmoulon** [comment]
@eokeeffe Did you tried on various dataset?

**Comment by eokeeffe** [comment]
I've tried this on a few dataset, getting the same results.
When I use the regular SIFT/AKAZE or OpenCV versions it works 100% of the time.
With my OpenCV program this seems to happen quite regularly.

Could this be caused by a very large number of points&descriptors being extracted?

**Comment by pmoulon** [comment]
Can you check in debug mode when it happens and check the pixel position?
I think it can be related to a point too close to the image border.
It would be valuable to understand what is happening.

**Comment by jingzibelieve** [comment]
neato不是内部或外部命令，也不是可运行的程序或批处理文件，what it  means?

**Comment by pmoulon** [comment]
It s a warning message saying you does not have graphviz installed in your path.
Install graphviz and you will see this message disappear

**Comment by jingzibelieve** [comment]
![image](https://cloud.githubusercontent.com/assets/15321725/20692541/a3687518-b613-11e6-9194-19bdce783aad.png)  when I run the command "openMVG_main_SfMInit_ImageListing -i [] -d [] -o []"

**Comment by pmoulon** [comment]
@jingzibelieve please create a new issue since it does not relate to the existing one.

**Comment by pmoulon** [comment]
@eokeeffe Any feedback?

Seems like the problem comes from your implementation and so perhaps from some wrong point positions that you send to OpenMVG.
