### ISSUE TITLE
openMVG_main_ComputeFeatures

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#689]
![image](https://cloud.githubusercontent.com/assets/15321725/20693147/61ab075e-b617-11e6-8892-740c5038e5c5.png)
when I run the command 'openMVG_main_ComputeFeatures.exe',error occurs

**Comment by pmoulon** [comment]
Did you tried to compile and run the unit test?
Can you check in debug mode to know where it crash?

**Comment by jingzibelieve** [comment]
Yes,I want to test the code
when I run the code in VS2015 ,it is no problem.But I run the code in dos,it prompts error

**Comment by pmoulon** [comment]
ok, its perhaps due to a lack of the VS 2015 redistributable files on your computer.
https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by jingzibelieve** [comment]
Thank you very much , I will try.

**Comment by jingzibelieve** [comment]
![image](https://cloud.githubusercontent.com/assets/15321725/20694716/21fa97b8-b622-11e6-9f0c-11a8dd890e3b.png)
![image](https://cloud.githubusercontent.com/assets/15321725/20694729/39955638-b622-11e6-96a2-e65a2d2eb17a.png)
According to the http://openmvg.readthedocs.io/en/latest/software/SfM/GlobalSfM/ ,the program does not generate matches.e.txt or matches.e.bin in addition to matches.f.bin

**Comment by pmoulon** [comment]
the x in matches.x depends on the geometric filter you choose at the ComputeMatches step.
f=> fundamental matrix filter=> -g f (default) is used for SequentialSfM
e => essential matrix filter => -g e is used for GlobalSfM
h=> homography matrix filter => -g h (not used for the moment,but you can rename the file from matches.h.bin to matches.f.bin if you need)

txt files was produced by old version of openMVG and keep for compatibility, new OpenMVG version produce more compact file (bin).

I advise you to run the exported python script that are in build/software/SfM, the scripts takes image dir and an output dir and will run all the toolchain for you.

**Comment by pmoulon** [comment]
@jingzibelieve Do you can close the issue if a valid answer was provided?
