### ISSUE TITLE
DensifyPointCloud.exe error

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#691]
![image](https://cloud.githubusercontent.com/assets/15321725/20783939/1a887f0c-b7d2-11e6-95b2-5c7d00136f76.png)
How to solve this problem？ @pmoulon

**Comment by pmoulon** [comment]
Please check that the OpenMVS exporter worked well (check that there is the undistorted image computed).
Then DensifyPointCloud is not a OpenMVG binary so I will not provide support on it.

**Comment by silenceofcode** [comment]
helllo  do you resolution this  question?i have the same question with you . @jingzibelieve

**Comment by jingzibelieve** [comment]
Yes，I have solved the problem @silenceofcode

**Comment by silenceofcode** [comment]
can you help solve this question ?? i have no idea to solve it   best wish to you . @jingzibelieve

**Comment by silenceofcode** [comment]
teacher    i try my best to solve it but not successful,can  you tell me how to solve it ? thanks

**Comment by silenceofcode** [comment]
@jingzibelieve

**Comment by jingzibelieve** [comment]
You send me your error message,I haven't done this for a long time @silenceofcode

**Comment by silenceofcode** [comment]
teacher thank you for you responsed soon 
my error message is [io] unknown image format ,the same as it https://github.com/cdcseacave/openMVS/issues/158    ;my qq number is 2538868891 ，i hope you can teach me by qq tool.
best wish to you
