### ISSUE TITLE
openMVG_main_openMVG2openMVS.exe

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#692]
![image](https://cloud.githubusercontent.com/assets/15321725/20855307/f4cc46b6-b936-11e6-8ab3-7b52602ac859.png)
After running this command does not generate undistorted_images.Why there is no pictures.

**Comment by pmoulon** [comment]
Cannot say without seeing the argument you provided.
Did you check that you SfM scene was nice (the clouds and poses ply file)?

**Comment by jingzibelieve** [comment]
I modify the source code, directly to the parameters in the program.Before I have not changed, the parameters are as follows:**openMVG_main_openMVG2openMVS.exe  -i  D:\openMVS\DataSet\out_global_reconstruction\sfm_data.bin -d D:\openMVS\DataSet\out_reconstruction -o D:\openMVS\DataSet\out_reconstruction\scene.mvs**,there is such a mistake.

**Comment by jingzibelieve** [comment]
![image](https://cloud.githubusercontent.com/assets/15321725/20871014/cfebda8c-bacb-11e6-8fb2-f50b205c0ef1.png)
