### ISSUE TITLE
openMVG_main_SfMInit_ImageListing will fail when too many images?

### ISSUE THREAD

**Issue by HUSTyanchao** [openMVG/openMVG#696]
I have more than 2000 images, and I use openMVG_main_SfMInit_ImageListing but fail and get these:

    terminate called after throwing an instance of 'std::length_error'
    what():  basic_string::resize
    Aborted (core dumped)
And I find that it is in the exif read function the error happened.

**Comment by pmoulon** [comment]
@HUSTyanchao Thank you for your feedback.
Seems like it crash on a specific image.
Can you have a look to see on which image it crash in order to make me look with your image what is happening?

**Comment by HUSTyanchao** [comment]
yes, it carshed on specific images. I remove these images, it works fine. I have send these failed images to you gmail address. Please help me to have a look.

**Comment by pmoulon** [comment]
I made a push in develop #697
It must fix the issue you encountered.
```
git checkout develop
git submodule init
git submodule update
=> redo cmake and build and tell me if everything is running fine.
```

**Comment by HUSTyanchao** [comment]
it works fine now. thank you for your help.

**Comment by pmoulon** [comment]
You're welcome.
