### ISSUE TITLE
How to Use main_IncrementalSfM.cpp

### ISSUE THREAD

**Issue by slila** [openMVG/openMVG#698]
I'm trying to work with the IncrementalSFM function, but i don't know how to run it with my data images?

**Comment by pmoulon** [comment]
You can use the exported python script:
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

Simply run the python scripts on your image directory. You can run SfM_SequentialPipeline.py or SfM_GlobalPipeline.py.

**Comment by slila** [comment]
Hi;
I was able to execute all the steps of the steps of the SfM until the exopt of the result of SfM with openMVG_main_openMVG2PMVS. I installed pmvs-2 in order to view the points cloud but I do not know exactly how I will proceed.
Could you orient me to arrive at the visualization of the points?

Thank you

**Comment by jpwhitney** [comment]
You can use Cloud Compare or MeshLab to open the .ply files.

**Comment by pmoulon** [comment]
@slila  PMVS2 allow you to compute a dense point but not to see it. As said by @jpwhitney you can use Cloud Compare or Meshlab to open the produced PLY files.

Here the help about PMVS2 connection and usage https://openmvg.readthedocs.io/en/latest/software/MVS/PMVS/

**Comment by slila** [comment]
Thank your answer.

After running this instruction
./pmvs2 ~/espaces/travail/out_Incremental_Reconstruction/scene/PMVS/pmvs_options.txt
what i should have as result or modification in my PMVS file?
Because it did not give any error. 

To see more clearly that what i had for each step 

./openMVG_main_SfMInit_ImageListing
--sensorWidthDatabase /espaces/travail/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory : /espaces/travail/reconstruction_sequential/matches
--focal 1
--intrinsics 
--camera_model 3
--group_camera_model 1
- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
SfMInit_ImageListing report:
listed #File(s): 2
usable #File(s) listed in sfm_data: 2

./openMVG_main_ComputeFeatures
--input_file /espaces/travail/reconstruction_sequential/matches/sfm_data.json
--outdir /espaces/travail/reconstruction_sequential/matches/
--describerMethod AKAZE_FLOAT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0
- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Task done in (s): 0

./openMVG_main_ComputeMatches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0
- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
 - PUTATIVE MATCHES - 
	 PREVIOUS RESULTS LOADED; #pair: 1
 - Geometric filtering - 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0.033
 Export Adjacency Matrix of the pairwise's geometric matches

Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).
- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building
Track filtering
Track export to internal struct
Track stats
------------------
-- Tracks Stats --
 Tracks number: 447
 Images Id: 
0, 1, 
------------------
TrackLength, Occurrence
	2	447
A-Contrario initial pair residual: 0.715558
Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 447
 #residuals: 1788
 Initial RMSE: 0.0950125
 Final RMSE: 0.0906326
 Time (s): 0.0236049
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	441
	-- Residual min:	4.85654e-08
	-- Residual median:	0.00380493
	-- Residual max:	 0.650681
	-- Residual mean:	 0.0602663
=========================
 MSE Residual InitialPair Inlier: 0.0602663
=========================
-------------------------------
-- Structure from Motion (statistics):
-- #Camera calibrated: 2 from 2 input images.
-- #Tracks, #3D points: 441
-------------------------------
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	441
	-- Residual min:	4.85654e-08
	-- Residual median:	0.00380493
	-- Residual max:	 0.650681
	-- Residual mean:	 0.0602663
Histogram of residuals:
0	|	1210
0.0651	|	268
0.13	|	121
0.195	|	75
0.26	|	32
0.325	|	28
0.39	|	14
0.455	|	10
0.521	|	4
0.586	|	1
0.651
 Total Ac-Sfm took (s): 0.242
...Generating SfM_Report.html
...Export SfM_Data to disk.

Compute scene structure color
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|


openMVG_main_openMVG2openMVS
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Scene saved to OpenMVS interface format:
2 images (2 calibrated)
441 Landmarks

./pmvs2 ~/espaces/travail/out_Incremental_Reconstruction/scene/PMVS/pmvs_options.txt

**Comment by pmoulon** [comment]
@slila If you want have some benefit to do some 3D from images you must use more than two images.
Try a least 3 or 4 images.

One more tip, if you use AKAZE_FLOAT you can have better features matches by using -n ANNL2 on main_ComputeMatches.

**Comment by slila** [comment]
Hi

First I want to thank you for your help and your answers to all my
questions.
I would like to know if there is a way to execute the
*main_IncrementalSfM.cpp* function by following the same steps as the
execution of *SfM_SequentialPipeline.py.*

Best regards
Lila

2017-01-06 6:24 GMT+01:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
If I understand well you want to run all the steps that are run in SfM_SequentialPipeline.py in a single binary.

If you want to do that you have to make a new C++ main that embed all the code of the ran binaries.
I would advise you to keep the running toolchain and create you the calling script that fit your needs.

**Comment by slila** [comment]
Hi dear Pierre

I'm trying to create a GUI with Qt creator to execute the
main_IncrementalSfm steps. But I can not find any way out. Can you help me
with an issue.
 Thank you for your help and your time.

Sincerly yours
Lila

2017-01-17 0:52 GMT+01:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
For this purpose you have to use OpenMVG as a third-party library
Follow the steps here (explaining how to install and use OpenMVG in an external project)
https://github.com/openMVG/openMVG/blob/master/BUILD#L127

You can take a look to the GUI made here
http://www.regard3d.org/index.php/download
https://sourceforge.net/projects/regard3d/files/

**Comment by slila** [comment]
Hi
I couldn't solve my problem with the GUI. I would like to create the interface on Qt creator but I do not know how to integrate the functions of openMVG that I used.
I would also like to know if there is a possibility to execute the SfM_SequentialPipeline.py file from c ++.

thank you so much

**Comment by slila** [comment]
Hi;
I would like to know if there is a condition to be taken into account when taking pictures, because, when I use the images of a castle that exist in openMVG, the incremental SfM runs well and gives a good result. On the other hand, when I use images that I have taken on other objects, the points cloud does not really represent the form of the object considered and sometimes it does not create the .ply and .bin files and this blocks me.

Thank you for your response in advance

**Comment by pmoulon** [comment]
1. You must check if some valid intrinsic data have been set for your image.
Check the log of SfM_Init_ImageListing.
Did some message appeared about some missing image in the camera sensor database?

2. If the intrinsic are ok, perhaps your image connection graph is empty and so no SFM can be done (check the *.svg file in the matching folder to see the graph and the matching adjacency matrix)

**Comment by slila** [comment]
What did you mean by valid intrinsic data, is it this list given after executing openMVG_main_SfMInit_ImageListing :
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1
for this case i didn't specify the focal, that i didn't know which is the good value to take into account for the focal. I tryed to give some values from the "sensor_width_camera_database.txt" like 3500. 
Could you confirm me how and from wich file can i get the focal value. if it's from "sensor_width_camera_database.txt" which colomn correspond to the this values.

Thank you

**Comment by pmoulon** [comment]
Can you share the log once you run:
```
openMVG_main_SfMInit_ImageListing :
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1
```

1. If you don't got some message like "Error: unknown camera model", you are all set and you must check you image matching graph

2. If you got some message "Error: unknown camera model"
Your camera model is not in the camera sensor database and you must add it.
Note that the file sensor_width_camera_database.txt store the camera sensor width (it must be some mm and not a value larger like 3500).

I think you try to set directly the focal value in pixels, if you want do so use the option ```-f 3500```

**Comment by slila** [comment]
Do you mean by log the all the results after the image listing, compute feautues and compute matches steps?

**Comment by slila** [comment]
and i didn't have this error message

**Comment by pmoulon** [comment]
Ok, but since you put 3500 in the camera database, the computed focal length in pixels must be wrong.
Take a look at its value in the sfm_data.json file (look for the word focal)

**Comment by slila** [comment]
so how can i choose the appropriate focal value in pixel?

**Comment by pmoulon** [comment]
You can do either a or b:
a. update the camera sensor database with the right ccd sensor size
or use
b. use the ```-f 3500``` option

**Comment by slila** [comment]
But why 3500 if you said that it gives wrong focal length in pixel? That what i can't understand.

**Comment by pmoulon** [comment]
I don't know your image size.
You can provide a approximate focal length by using this rules : ```f = 1.1 * max(imageW, image H)```
I tought that the 3500 value you was speaking about was your calibrated focal length.
