### ISSUE TITLE
lack of camera model in the database

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#700]
![image](https://cloud.githubusercontent.com/assets/15321725/21090914/dfc83ede-c07d-11e6-9842-c819b1f4a27a.png)
![image](https://cloud.githubusercontent.com/assets/15321725/21090901/d0f81870-c07d-11e6-8862-c694459f7095.png)
When there is no camera model in the database, if I add in the database, and then run it can be successful?

**Comment by rperrot** [comment]
>>> When there is no camera model in the database, if I add in the database, and then run it can be successful?

Yes. 

Is-it a phone camera ? (Xiaomi mi-4c) ?

**Comment by jingzibelieve** [comment]
Thanks! @rperrot
