### ISSUE TITLE
openMVG_main_IncrementalSFM.exe error

### ISSUE THREAD

**Issue by jingzibelieve** [openMVG/openMVG#702]
![image](https://cloud.githubusercontent.com/assets/15321725/21126062/10520e8e-c125-11e6-857d-692617e6eb41.png)
Why is there no problem running openMVG all the commands on my machine? But in my colleague's machine running this command but manually enter the initial pair of coordinates.

**Comment by pmoulon** [comment]
Are you sure you copied the camera sensor database from your machine to your colleague's one?

**Comment by jingzibelieve** [comment]
I know this mistake, my colleagues put his data set on the Chinese directory, and then change to the English directory, the results of this process leads to information related to the camera not to look at the details in the image, the  program can not identify  the camera  type of the picture.
Thanks!@ @ @pmoulon

**Comment by pmoulon** [comment]
Can you close the issue?
