### ISSUE TITLE
Eigen install path problem

### ISSUE THREAD

**Issue by HUSTyanchao** [openMVG/openMVG#704]
I would like to install openMVG on server and I do not have administrative privileges. When I build the openMVG with CMAKE_INSTALL_PREFIX like : 
cmake -D OpenCV_DIR=/data1/NLPRMNT/public/opencv3/share/OpenCV 
-D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/data1/NLPRMNT/yanchaochao/local
 . ../openMVG/src/

**Then make, it is okay. Then I do make install, I get an error:**

CMake Error at third_party/eigen/Eigen/cmake_install.cmake:44 (file):
  file cannot create directory:
  /usr/local/include/openMVG/third_party/eigen/Eigen.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  third_party/eigen/cmake_install.cmake:37 (include)
  third_party/cmake_install.cmake:69 (include)
  cmake_install.cmake:84 (include)

make: *** [install] Error 1

So I check third_party/eigen/Eigen/cmake_install.cmake file at line 44:
file(INSTALL DESTINATION "/usr/local/include/openMVG/third_party/eigen/Eigen" TYPE FILE FILES

**Is this a bug or something？It should not be in the /usr/local/.**

**Comment by pmoulon** [comment]
Are you using master or develop branch?

**Comment by HUSTyanchao** [comment]
develop branch

**Comment by pmoulon** [comment]
Seems like CMAKE_INSTALL_PREFIX is not correctly transferred to Eigen (internal).
This is strange since you saw that here the install path is set https://github.com/openMVG/openMVG/blob/master/src/third_party/CMakeLists.txt#L105

Can you take a more in depth look to it again?

**Comment by HUSTyanchao** [comment]
I add a MESSAGE sentence to print the information below line 105 like this:

##
# Install Header only libraries if necessary
##
if (DEFINED OpenMVG_USE_INTERNAL_EIGEN)
  #Configure Eigen install
  set(EIGEN_INCLUDE_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/include/openMVG/third_party/eigen)
  message(${EIGEN_INCLUDE_INSTALL_DIR})
  add_subdirectory(eigen)
endif() 


And it seems that it is correctly transferred to Eigen. But there are some error message:

   /data1/NLPRMNT/yanchaochao/local/include/openMVG/third_party/eigen
   abort: repository /data1/NLPRMNT/yanchaochao/sfm/openMVG/src not found!
   abort: repository /data1/NLPRMNT/yanchaochao/sfm/openMVG/src not found!
   --
   -- Configured Eigen 3.2.8
   --

Could you please tell me how do you generate the third_party/eigen/Eigen/cmake_install.cmake file ?

**Comment by pmoulon** [comment]
Can you check when you run cmake if you have this message:
```EIGEN: 3.2.8 (internal)```

**Comment by HUSTyanchao** [comment]
Yes I have.


-- EIGEN: 3.2.8 (internal)
-- CERES: 1.11.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 3.9.4 (external)
-- LIBPNG: 1.2.49 (external)
-- LIBJPEG (external)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done

**Comment by pmoulon** [comment]
This is strange can you try again in a empty build directory with your command line
```
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/data1/NLPRMNT/yanchaochao/local ../openMVG/src/
make 
make install
```

**Comment by HUSTyanchao** [comment]
this time it is correct!

third_party/eigen/Eigen/cmake_install.cmake file at line 37:
FILE(INSTALL DESTINATION "/data1/NLPRMNT/yanchaochao/local/include/openMVG/third_party/eigen/Eigen" TYPE FILE FILES

**Comment by pmoulon** [comment]
Since the path is now correct I think the installation will run fine.
