### ISSUE TITLE
how to reconstruct BRISK point cloud using openMVG

### ISSUE THREAD

**Issue by HUSTyanchao** [openMVG/openMVG#706]
@pmoulon 
I would like to reconstruct point cloud from BRISK feature. Here is the planned pipeline:

1. Reconstruct point cloud using the OpenCV SIFT feature. Then we will get the pose of all cameras.

2. Extract BRISK feature points and descriptors. I have modified the main_ComputeFeatures_OpenCV.cpp file to do this.
3. Reconstruct point cloud with BRISK descriptors using the provided main_ComputeStructureFromKnownPoses.cpp.

Will this reconstruct BRISK point cloud successfully? Could anyone give me some advises? Thanks a lot!

**Comment by pmoulon** [comment]
Hi,
In order to do what you want you must run ComputeStructureFromKnownPoses with the SFM_data file computed with the SIFT, then you give the directory where the brisk feature was computed as the match folder and it should run smoothly.

**Comment by HUSTyanchao** [comment]
Thank you for your reply. Now I am trying to make it!
