### ISSUE TITLE
Adding camera - sfm_data.json cannot be read

### ISSUE THREAD

**Issue by blup-Blupon** [openMVG/openMVG#707]
Hi !

I have tried both the 4 steps SfM and the python pipeline on a set of three pictures taken with a cellphone camera.

I had issues, looking like ones already solved here [https://github.com/openMVG/openMVG/issues/559](url) and here [https://github.com/openMVG/openMVG/issues/426](url)

I tried adding my camera to the .txt dedicated file with the focal length (2.8 cm -> Nokia Lumia 720) but didn't look like working, I actually had a look at the files associated with the Castle example to see where the camera caracteristics were, couldn't find those, neither could I find the Castle pictures camera lense of the pictures informations back in the openMVG .txt file for lenses. That led me not to know how to add a camera, nor to understand how this information was taken into account when using the python SfM pipeline to obtain the Castle example .ply result file.

Finally, I tried using the -f option in the first step of the 4 steps SfM process, trying it with a 1.2 focal value, still had the "[...] /matches/sfm_data.json/" cannot be read." issue at the final step.

If anyone could tell me how to properly edit the .txt file to add my camera/manually tell the software the camera parameter during the 4 steps SfM so that I can compute .ply output files with personal sets of images, I would be grateful.

Thanks ! (and thanks again for the nice piece of software you developed, coming from a French research student :D)

**Comment by pmoulon** [comment]
Hi,

Thank you for your message.

1; In the database file you must add the camera sensor witdh size (and not the focal length), so 4.0 according this wesite
=> Nokia Lumia 720 =>1/3.6" sensor size => https://en.wikipedia.org/wiki/Image_sensor_format

2. If you use the -f option you must configure X as following
X = 1.2 * max(w,h)

Option 1 will provide a more accurate pixel focal length; option 2 can be sufficient for a fast test.

Hoping my answer help you.
Keep me updated of your progress.

Bonne reconstruction ;-)

**Comment by blup-Blupon** [comment]
Hi ! 

Thanks for your very quick and nice answer. Still can't figure it out though. Here is what I've tried.

**_Adding sensor to the Database_**

I added these lines at the end of sensors_width_database.txt (which is located in /openMVG and not /openMVG_build) : 

`Nokia;4.0`
`Lumia 720;4.0`
`Nokia 720;4.0`
`Nokia Lumia 720;4.0`

Then tried the global pipeline:

`python SfM_GlobalPipeline.py [full path image directory] [resulting directory]`

Here are selected parts of the shell output:

**1.  Intrinsics analysis**

got a "Focal length is missing" warning & error for each image

**2. Compute features**

didn't notice anything worrying

**3.  Compute matches**

`sh: 1: neato: not found`

**4. Do Global reconstruction**

`CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0`
`Cardinal of nodes: 0`
`Cardinal of edges: 0`
`Invalid input image graph for global SfM`

**5. Colorize Structure**

 /sfm_data.bin" cannot be read.

**6. Structure from Known Poses (robust triangulation)**

sfm_data.bin" cannot be read.
robust.bin" cannot be read.

**_Using -f option_**

I then tried the step by step SfM, starting with

`openMVG_main_SfMInit_ImageListing -d ~/.../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i ~/.../Images/ -o ~/.../Images/reconstruction/matches/ -f 4.0`

went on with

`openMVG_main_ComputeFeatures`

and 

`openMVG_main_ComputeMatches`

then read the following shell output : 

`Invalid regions files for the view:`




Thanks again for the previous answer, and sorry to bother you with that issue again ! 

I did try reading this post [https://github.com/openMVG/ImageDataset_SceauxCastle/issues/2](url)
but I couldn't solve my difficulties with it.

(Joyeux Noël ^^)

**Comment by pmoulon** [comment]
Using option -f X must work.
You did not have used it in the right way.
You tried -f 4.0 but you must put X = 1.2 * max(w,h)  with w and h the width or heigth of the images.
Be sure to start from an empty directory to do not reuse previously computed data.

According the warning message it seems that OpenMVG cannot read the focal length from the EXIF value. So using the -f option will work, you must juste specify the right value.

Joyeux Noël

**Comment by pmoulon** [comment]
@blup-Blupon Any feedback?

**Comment by blup-Blupon** [comment]
Hi again ! Thanks for not forgetting me, I didn't forget openMVG either =).

# Pipeline & adding camera parameters

> According the warning message it seems that OpenMVG cannot read the focal length from the EXIF value.

So `Nokia 720;4.0` in the camera database file will never work to fix the global pipeline ? And does that mean that if I try with a more common camera the focal length will be available in the EXIF information ?

One of the main objectives of my research project would be to implement openMVG on a small robot using a Raspberry Pi camera.

# neato: not found

Solved the issue by installing graphviz... I guess I'm to blame on that one.

# Step by step SfM

I think I managed using -f option properly by typing

`openMVG_main_SfMInit_ImageListing -i ~/Images/.../images -d ~/.../openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -o ~/Images/.../reconstruction/ -f 1958.4` 

with 1958.4 = 1.2 * max(h,w) in pixels.

But then at the GlobalSfM step, got the warning/error `Invalid matches file.`

Part of the ComputeMatches was : 

`Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list 
--nearest_matching_method AUTO
--guided_matching 0

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES - 
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 0.057

 - Geometric filtering - 

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0`

## Attempt to solve step by step SfM

Googled the previous warning of GlobalSfM and found this post [https://github.com/openMVG/openMVG/issues/576](url)

I therefore tried `openMVG_main_ComputeMatches -i matches\sfm_data.json -o matches -g e
` as you advised someone else.
 
But then I got stuck again at the GlobalSfM step with the following error/warning:

`CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0

Cardinal of nodes: 0
Cardinal of edges: 0

Invalid input image graph for global SfM`

Not enough pictures perhaps ? Too heavy pictures (several Mo each) ? 


Thanks again for following this issue !

**Comment by pmoulon** [comment]
Would you be ok to share the dataset on openmvg-team[AT]googlegroups.com or privately to me?
I wonder if you start again from scratch you will have the issue again.

I know that the -g e or the default option is a bit confusing, but a good way to remember is the following:
-g f (default option of computematches) => Sequential SfM
-g e (not the default option of computematches)=> Global SfM

You can also rename the file from matches.X.bin to other name.
But the global idea is that Global SfM is using relative poses as input and so it must received the essential matrix filtered graph & correspondences.

**Comment by pmoulon** [comment]
@blup-Blupon Any feedback?

**Comment by blup-Blupon** [comment]
@pmoulon I've actually managed to make openMVG work and create a robust_colorized.ply on a set of pictures taken by a camera which already was in the database, I still have to run tests to make my next questions relevant & useful. In any case, I won't have any problem sharing the dataset with you eventually, if I can't manage to solve my issues. Thanks for the attention you give to my issues :-) 

FYI: I suspected non sufficient amount of pictures because I was initially using 3 pictures of a quite regular single-colour cup, which was later described as a very bad example by my teacher (no easy landmark)

**Comment by pmoulon** [comment]
ok, You're right, rich texture environment works better since it's more easy to find corresponding points between the images.

Please close the issue if your got the answer to your initial thread topic.

**Comment by blup-Blupon** [comment]
Well the initial issue being adding a camera to the database, it's not really answered.
Could it be possible to edit the global pipeline code to hardcode a focal length value ?

The final objective would be to use one type of RasPi camera on a robot anyway.

Since I've recently moved to ubuntu (from debian) and the step by step SfM somehow isn't working anymore (although the pipelines are), it would be a relief to be able to do this.

I'm sending a set of pictures taken by my cell camera to the email address you suggested. Those are pictures of an object I managed to get a .ply from with a camera already in the database.

Again, thanks for your interest (and nice PhD thesis !).

**Comment by pmoulon** [comment]
Hi,

1. Without sharing an image of your Lumia I cannot tell you exactly what you can do to add the image to the sensor database?
I will investigate with the image your sent.
I got some Lumia image in the past without any field FOCAL LENGTH and so you can't invent the focal in this case.

2. Hardcode the focal length
- No need to hardcode the value, you have to use the -f option that is made to deal with this case (when you have no idea about the mm focal length or if you already know the accurate pixels focal length) on SfMInit_ImageListing

3. Thank you for your kind words about my PhD thesis.

**Comment by blup-Blupon** [comment]
1) I sent you pictures on openmvg-team AT googlegroups.com from an @crans.org email address on the 26th of January. With those pictures I managed to make the step by step SfM work partially (thanks to this post [https://github.com/openMVG/openMVG/issues/404](url) and this post [https://github.com/openMVG/openMVG/issues/586](url) ). Partially meaning I eventually didn't get robust.ply and colorized.ply and I don't know why.

2) A professor actually suggested we could have access to devices which would allow us to accurately measure the focal length of any device in order to complete this project.

**Comment by pmoulon** [comment]
1. Made a test on your picture. Its was I though about, the focal length EXIF tag is missing.
BTW, the program tell it in the command line =>
```WP_20170110_015: Focal length is missing.```

2. After doing providing a focal length by using the -f option, and tweak a bit the feature detector in order to detect more matching pairs I was able to obtain decent results. See screenshot.
If your professor can provide you the calibrated focal length you will just have to provide it to the SfM toolchain with this -f option.

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/22400921/fdb6c65e-e5c1-11e6-83b5-e710fe42218f.png)

Here the changes I made:
- using the -f option to provide an approximate pixel focal length for your images
- use the AKAZE_FLOAT feature detector that works better than SIFT on blurry images, I use there also the HIGH preset in order to extract more features per images
- use the ANNL2 features matcher that provide better accuracy than the default cascade hasher method.

```
print ("1. Intrinsics analysis")
pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-f", "1795.2"] )
pIntrisics.wait()

print ("2. Compute features")
pFeatures = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-m", "AKAZE_FLOAT", "-p", "HIGH"] )
pFeatures.wait()

print ("3. Compute matches")
pMatches = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-g", "e", "-n", "ANNL2"] )
pMatches.wait()
```

Another screenshot (top view)
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/22400940/a374df22-e5c2-11e6-8f1a-392dfc2312c0.png)

**Comment by blup-Blupon** [comment]
Hi ! Thanks for your answer. I did as you told (AKAZE_FLOAT, ULTRA instead of HIGH, ANNL2), I got a satisfying uncolored result in "cloud_and_poses.ply", but again, I don't have any colored result (like the "robust_colorized.ply" I previously got. How can I manage this ? Anyway, we more or less answered my initial question, so I'm going to close the issue.

**Comment by pmoulon** [comment]
I don't know why you did not obtained the robust_colorized point cloud.
BTW, the robust step is an extra step that is not required, I mean you have already the geometry of the scene after running the SfM pipeline.
