### ISSUE TITLE
a problem about saving sfm_data.json

### ISSUE THREAD

**Issue by kealennieh** [openMVG/openMVG#717]
Hi,
    I've got a problem about saving sfm_data file. I've builded OpenMVG project in VS2015 under windows 10. 

 Subsequently, following the "tutorial_demo.py", I created a project in VS2015 to complete the first step, which is "1. Intrinsics analysis". The code used in my project is from the file "**openMVG-master\src\software\SfM\main_SfMInit_ImageListing.cpp**". At the same time, I used the image data "**ImageDataset_SceauxCastle**".

 When I used the same parameters as file "**tutorial_demo.py**" does, to run my project, a problem appeared. VS2015 displays a c++ exception happens, and I realize the break point is on function "`static const Derived *downcast (const void *dptr, std::type_info const &baseInfo)`", which is in file "**cereal\details\polymorphic_impl.hpp**". I spent a lot of time to work it out, but unfortunately it's in vain. I truly need your help. Thanks a lot.

**Comment by pmoulon** [comment]
Can you try the code that is in the develop branch?
```
git checkout develop
git submodule init
git submodule
```
then rerun cmake and build from scratch

**Comment by pmoulon** [comment]
@kealennieh Any news?

**Comment by kealennieh** [comment]
Sorry for no response. It's been unavailable these days. Indeed, I compiled the develop branch yesterday and it worked that problem out.  

Subsequently, I created a VS program to test  **main_SfMInit_ImageListing.cpp** and **main_ComputeFeatures.cpp**, and the result was good. However, I'm still a little bit worried about the rest of codes, since it displayed collapse of **openMVG_test_matching** when I compiled the test parts. 

Anyway, thanks for offering such great help, and I'll keep track of your work.

**Comment by pmoulon** [comment]
Thanks for your feedback. It's hard to have a code that is working fine on all platform.

I did not understand your point about the displayed collapse...
You can take a look to the ready to use python script that are exported in build/software/SfM.
Those script allow to run the entire pipeline easily on your image dataset.

Please close the issue when you think it is solved.
