### ISSUE TITLE
Add HONOR 5x cam

### ISSUE THREAD

**Issue by SimoneNascivera** [openMVG/openMVG#724]
I tried for several hours to insert my honor 5x cam sensor, detected as HUAWEI KIW-L21, but even if I add it to CameraGenerated.txt with "HUAWEI;HUAWEI KIW-L21;22" the software doesnt recognise it.
Can you add it to the main database?
Thank you, Simone
PS: I attach a photo made with it
![img_20170108_155905_001_cover](https://cloud.githubusercontent.com/assets/24991240/21751538/271aacee-d5c9-11e6-8bdd-8c3bacb5f8eb.jpg)

**Comment by pmoulon** [comment]
@SimoneNascivera 
You must add in the file
```
KIW-L21;4.69
```
The sensor size is not 22, I think it's more around 4.69

**Comment by pmoulon** [comment]
@SimoneNascivera Any feedback?

**Comment by SimoneNascivera** [comment]
Sorry my late answer it worked perfectly

Il 10 gen 2017 01:42, "Pierre Moulon" <notifications@github.com> ha scritto:

**Comment by pmoulon** [comment]
Since the proposed solution worked fine, I'm closing the issue.

**Comment by SimoneNascivera** [comment]
Perfect thank you

Il 10 gen 2017 21:32, "Pierre Moulon" <notifications@github.com> ha scritto:
