### ISSUE TITLE
Any special requirement for camera positions？

### ISSUE THREAD

**Issue by MEGA728** [openMVG/openMVG#726]
If I want to reconstruct something with one camera using Global/Incremental SFM, is there any special requirement for camera positions, like don't move the camera along a straight line?

Thanks!

**Comment by pmoulon** [comment]
There is not special requirement for the camera motion, the advantage of SfM over VO is that we can handle arbitrary camera motion.
You must avoid rotating motion and prefer to do motion that introduce parallax (move between each shoot).

Often the best is to use "The Walk-around Method". So take picture when you turn around your object

**Comment by MEGA728** [comment]
Very helpful ! Thanks
