### ISSUE TITLE
retroreflective targets

### ISSUE THREAD

**Issue by danlugli** [openMVG/openMVG#732]
Hi,
Is it possible to use openMVG to reconstruct the 3D coordinates of a set of retroreflective targets?
These are black stickers with a very bright circular dot, 5mm diameter.
I would like to have only these targets processed, excluding the texture of the surface where they are sticked to.
Thank you in advance

Daniele Lugli

**Comment by jpwhitney** [comment]
It seems like if you preprocessed the images so that only the retroreflective dots were present and then used those images with openMVG, you could get the relative coordinates of each dot.

Maybe there is a better way to do it, but with my limited experience using software like this and reading the docs I could understand, that's what I would try.

I'm picturing that after the preprocessing (mask or contrast) you could then treat your images as synthetic data.

**Comment by danlugli** [comment]
Sure. I already shoot use a flash to have good images of the dots, with aperture completely closed and minimum shutter compatible with the flash synchronization. What I get are images where the dots are clearly visible and all the rest is almost black -- but not  completely. Some faint details are still there, and they are recognized.
Using a mask would require a lot of time-consuming work by hand.

**Comment by pmoulon** [comment]
Hi @danlugli,

The actual pipeline is working with feature correspondences that are established automatically since there is a descriptor (SIFT, ...) that is linked to each feature. In your case (white dots) all the features will have the same descriptor and so we will not be able to establish the correspondences.

Unless you program your own detector (that can rely on MSER) you will have to do the labeling by hand. The labeling and matching can be done by using the GCP GUI.

Since your case is particular perhaps see a typical image you have to process would help us to understand your need.

Most of the time classic photogrammetry target use printed tag in order to have an ID attached to each detected feature.
i.e 
![image](https://cloud.githubusercontent.com/assets/3235050/22002623/b4b8c182-dc4d-11e6-9b12-b9d1ea2e9c7d.png)

**Comment by pmoulon** [comment]
@danlugli 
I would advise to launch a discussion with @MEGA728 https://github.com/openMVG/openMVG/issues/720#issuecomment-270051526 since its seems able to find correspondences between reflective target and feed OpenMVG accordingly.

**Comment by MEGA728** [comment]
Considering your case, one possible way is to pre-calculate the correspondence of white dots, write the matches into matches.f/e.txt. and then you can use openMVG_main_IncrementalSfM or openMVG_main_GlobalSfM. BTW, you will also need *.feat and  sfm_data.json as input.

**Comment by danlugli** [comment]
@pmoulon 
From your answer I think I must have misunderstood something basic about openMVG.
My idea was that, thanks to "RANSAC a contrario", openMVG was able to find matches between features even if these were not distinguishable, as in the case of white dots.
This is not true?

@MEGA728 
How do you pre-calculate the correspondence?

**Comment by MEGA728** [comment]
you may have to develop your own algorithm for that

**Comment by pmoulon** [comment]
@danlugli 
ACRansac is working on a set of previously putative correspondences. It's a robust geometric model estimator, it's not a descriptor matcher.

You can try by linking a point to all other and see what is happening to see if the method is able to recover the most plausible geometric model from this set of matches.

**Comment by danlugli** [comment]
@MEGA728 
Did you develop your own algorithm? Is it avaliable under some condition or at a fee?

@pmoulon 
Listen Pierre, I have an idea for this. Please read on and let me know if it looks feasible to you.

(In what follows I speak of essential matrix because we have a good approximation of the intrinsic calibration K from EXIF data, but things should not be too different for the fundamental matrix).

The essential matrix E (3x3, rank 2) can be determined by a linear system of m >= 8 equations in 9 unknowns which are the entries of E:
r_i ^T e = 0, with
r_i = [x'_i x_i,  x'_i y_i,  x'_i,  y'_i x_i, y'_i y_i, y'_i, x_i,  y_i, 1]^T,
x_i, y_i, x'_i, y'_i are the homogeneous coordinates (z_i, z'_i = 1) of the two image points in the i-th correspondence, normalized by premultiplication times K^(-1),
and e =[E_11, E_12, ... E_33]^T is the column vector containing the unknown entries of E.

If all the m >= 8 correspondences are good, the matrix M (mx9) of the system has 8 non-null and 1 null singular value. The right singular vector corresponding to this null singular value is the solution e (to a scale factor).

Now what if we have just ONE good correspondence? The matrix M is now just 1x9 and has 1 non-null and 8 null singular values. The solution can be expressed as a linear combination of the 8 right singular vectors corresponding to the null singular values; say:
e = k_1 V_1 + ... + k_8 * V_8
where V_i are the columns of the right matrix V in the SVD decomposition M (1x9) = U (1x9) . W (9x9)  . V^T (9x9). V_i are orthonormal.

This gives a way to rapidly evaluate any new putative correspondence. I build the r vector for the correspondence to be tested and verify whether
r - (r . V_1) V_1 - ... - (r . V_8) V_8 = 0 (null vector)
to a tolerance. If it is not, the new correspondence is not compatible with the first one, and can be safely discarded.

Once I have TWO presumably good correspondences, the whole process can be repeated with a 2x9 M matrix having 2 non-null and 7 null singular values, allowing me to verify a third putative correspondence, and so on until I gather 8 presumably good correspondences and can build the essential matrix. If I am not able to find any new good correspondence, probably the initial correspondence was wrong, and I should try with a new one.

This should be really faster than picking a large number of sets of 8 random matches and trying to build an essential matrix for each of them. It should be effective when the features per image are not too many, as in my case of a handful of white dots. It is probably not so effective when the features are thousands per image.

Do you think it is worth trying to write code for this stuff?

**Comment by MEGA728** [comment]
The algorithm is based on the geometric relationship of points, so it is not generic.

**Comment by danlugli** [comment]
@MEGA728 
So it depends on how the dots are laid out on the surface? It could not work with a random layout of dots?

**Comment by MEGA728** [comment]
That's right. However you can get the correspondence of a random layout of dots with the help of intrinsics and extrinsics. But it would be quite complicated.

**Comment by pmoulon** [comment]
I think that we can handle your case (if features are mostly planar by using some geometric constraints between the dots) https://ilab.cs.ucsb.edu/tma/12/papers/ISMAR2012_WS-TMA_Paper_YujiOyamada.pdf

Else if you have some texture between your reflective dots you can try to use OpenMVG KVLD implementation to try to find the corresponding points.

@rperrot worked on an implementation of the Oyamada random dot pattern matching that we will be able to release in the coming months (but we saw some trouble about the large rotation invariance).

**Comment by danlugli** [comment]
@pmoulon 
Unluckily the dots are distributed on a surface which is far from planar.
The features between dots are mostly due to dirt on an otherwise almost textureless surface, so they are scarce and unreliable.
The ideal solution would be to use the dots only. As an alternative, some more structured figures, eg something like coded targets, could be added.

**Comment by pmoulon** [comment]
As I said to you can still can manually label your target and match them using the GCP UI.
Perhaps you can take a look if there is some academic references about un-structured reflective target matching.

**Comment by danlugli** [comment]
Manually labelling the many targets would be a nightmare for a human being :)

For what concerns matching of unstructured features, I have reached this 2002 paper by Moisan and Stival: http://www.math-info.univ-paris5.fr/~moisan/papers/CMLA2002-11.pdf

By the way, re-reading my message of this morning I now see that the idea I presented there cannot work. I have therefore deleted the second part of the message. Sorry.

**Comment by pmoulon** [comment]
Moisan made an interesting extension that could perhaps fit your needs http://www.math-info.univ-paris5.fr/~moisan/astre/
I did not know if it could be extended to your purpose, since in your case you will have less white label.

**Comment by pmoulon** [comment]
@danlugli Can you close the issue since we have investigate together for your problem.

1. Use reflective target is possible in OpenMVG is you can create a descriptor to match them or if you associate them as control points.

2. Using reflective target without association is a hard problem.

**Comment by danlugli** [comment]
OK I'm going to close the issue.

Excuse me for not having replied to your message of 19 Jan
I also followed the link and it is interesting indeed, but I don't think it could be useful to my purpose.
Thank you for your time and your kindness & my best regards

Daniele

**Comment by pmoulon** [comment]
@danlugli You're welcome, it's a pleasure to discuss with the community.
No worries, I was just going through the issue and asking back if there is something to do.
