### ISSUE TITLE
Using pre-calculated correspondences to create a putative-match file 

### ISSUE THREAD

**Issue by MEGA728** [openMVG/openMVG#734]
I have pre-calculated the correspondences of some points, but with lots of false matches. So it may not be a good idea to write them into matches.e.txt. What if I write them into matches.putative.txt? In which step of the SfM pipeline can I use this matches.putative.txt?

Btw, R and T of each camera pose have already been calculated by using coded points.

Thanks in advance!

**Comment by pmoulon** [comment]
Features and matches worked in the following format:

For each image you must have a IMAGE_BASENAME.feat file
It describe every detected point in the image
```
x y scale orientation
...
```
In your case put orientation to 0 and scale to 4 for example (to give a size to the keypoint if we draw it)

Then you can fill a matches.X.txt file that tell which the corresponding feature index for the pairs

```
0 1
3
2 5
3 6
68 23
```

this file tells that there is 3 correspondences between image 0 and 3 and the corresponding line index of the feature file. If you have many pair just concat them in the matches file:

```
0 1
3
2 5
3 6
68 23
1 2
23
....
```

You could write your matches.putative.txt use the exportMatches binary to check the data and correspondences.
Then you can launch main_ComputeMatches and it will load your matches and compute the Fundamental matrix (default) or the essential matrix if you provide the ```-f e``` option.
Then you launch the SfM pipeline of your choice.

There is no way to preload existing relative camera poses for the SfM pipeline. Except for the ComputeStructureFromKnowCameraPoses (but this binary requires to have keypoint descritors).

**Comment by MEGA728** [comment]
Hi @pmoulon ,

I tried to use matches.putative.txt as input of main_ComputeMatches, the outcome was as follows:

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Invalid regions files for the view: C:\Users\abc\Desktop\\IMG_0000.JPG
****
Invalid regions.


I use epipolar line to get the putative matches of points, so I don't have .desc files. The files available for input are sfm_data.json, matches.putative.txt and .feat files. How can I get matches.f.txt from them?

**Comment by pmoulon** [comment]
It seems that the file IMG_0000.feat that must be in the same dir as the sfm_data.json is missing or not read correctly. Can you drop me one of your generated feat file?

**Comment by MEGA728** [comment]
The file IMG_0000.feat is in the same dir as the sfm_data.json. 

I changed .feat into .txt so that I can upload it.
[IMG_0000.txt](https://github.com/openMVG/openMVG/files/718362/IMG_0000.txt)

**Comment by pmoulon** [comment]
On my computer the file is well parsed.
So its perhaps a path issue.

Can you drop my the entire directory in which you have your sfm_data.json, the *.feat and the matches.putative.txt file?
You can zip it.

**Comment by MEGA728** [comment]
All of the input files are as follows:
[input.zip](https://github.com/openMVG/openMVG/files/718571/input.zip)

**Comment by pmoulon** [comment]
I forgot to mention that you must store *.desc file too (to simulate a descriptor for each keypoint).
The descriptors will not be used since your provide a matche file, so you can push data with no meaning inside it.
Just push the number of descriptors your store and the SIFT like descriptor some empty SIFT like descriptor in binary inside the *.desc file. So X times the number of features per images you push 128 zero value.

You can use this function a function like that to do it
```
/// Write descriptors to file (in binary mode)
template<typename DescriptorsT >
inline bool saveDescsToBinFile(
  const std::string & sfileNameDescs,
  size_t nbFeats)
{
  using VALUE = typename DescriptorsT::value_type;

  std::ofstream file(sfileNameDescs.c_str(), std::ios::out | std::ios::binary);
  if (!file.is_open())
    return false;
  //Write the number of descriptor
  const std::size_t cardDesc = nbFeats;
  file.write((const char*) &cardDesc,  sizeof(std::size_t));
  for (typename DescriptorsT::const_iterator iter = vec_desc.begin();
    iter != vec_desc.end(); ++iter) {
   for (int i=0; i <128: ++i)
   {
    unsigned char x = 0;
    file.write((const char*) &x,
      sizeof(typename VALUE::bin_type));
   }
  }
  const bool bOk = file.good();
  file.close();
  return bOk;
```

**Comment by MEGA728** [comment]
I tried the function you gave me for several times, but I couldn't get it to work. My code is as follows:

int main()
{
	std::string fileNameDescs;
	size_t nbFeats;

	fileNameDescs = "C:\\Users\\abc\\Desktop\\IMG_0000.desc";
	nbFeats = 15;

	saveDescsToBinFile(fileNameDescs, nbFeats);

	return 0;
}

Can you please point out where did I do wrong?

**Comment by pmoulon** [comment]
Sorry I did not try to compile it (notice that saveDescsToBinFile is a template function).
BTW, here is a working version for your case


#include <iostream>
#include <string>
#include <fstream>

```
/// Write descriptors to file (in binary mode)
/// HERE EXPORT ZERO LIKE SIFT DESCRIPTOR
inline bool saveDescsToBinFile(
  const std::string & sfileNameDescs,
  size_t nbFeats)
{
  std::ofstream file(sfileNameDescs.c_str(), std::ios::out | std::ios::binary);
  if (!file.is_open())
    return false;
  //Write the number of descriptor
  const std::size_t cardDesc = nbFeats;
  file.write((const char*) &cardDesc,  sizeof(std::size_t));
  for (int j=0; j < nbFeats; ++j) {
   for (int i=0; i <128; ++i)
   {
    unsigned char x = 0;
    file.write((const char*) &x,
      sizeof(unsigned char));
   }
  }
  const bool bOk = file.good();
  file.close();
  return bOk;
}

int main()
{
	std::string fileNameDescs;
	size_t nbFeats;

	fileNameDescs = "./IMG_0000.desc";
	nbFeats = 15;

	saveDescsToBinFile(fileNameDescs, nbFeats);

	return 0;
}
```

**Comment by MEGA728** [comment]
Thanks Pierre! This version can create *.desc files. However I am not sure whether the *.desc files created are correct or not. Because when I run main_ComputeMatches, it outputs an empty matches.f.txt, and the geometric_matches.svg is like this:
![1](https://cloud.githubusercontent.com/assets/24884634/22200369/c6d135ce-e199-11e6-8448-02e8cd0adc0f.png)

Can you please take a look into it? I upload my input files, including the newly created *.desc files.
[input.zip](https://github.com/openMVG/openMVG/files/723297/input.zip)

**Comment by pmoulon** [comment]
As the output is "not connection" between the image I think that the relative solver always return that it does not find a valid model.

Moreover I think that using so few correspondences (15) make this test fails
https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching_image_collection/F_ACRobust.hpp#L85
I'm expecting to have vec_inliers.size() > KernelType::MINIMUM_SAMPLES *2.5 => so more than 17 valid matches. I have this test in order to ensure that the found model hypothesis have some point correspondences support.

**Comment by MEGA728** [comment]
In my case, there may not be more than 17 valid matches between most pairs of photos. Can I delete this “if (vec_inliers.size() > KernelType::MINIMUM_SAMPLES *2.5)” in order to make it work?

**Comment by pmoulon** [comment]
Feel free to comment or modify the code for your testing purpose.
By removing the line, you will be able to see if you have a solution as output

**Comment by MEGA728** [comment]
Thanks! One question: How does main_ComputeMatches get correct matches and remove wrong matches from matches.putative.txt? Can you please show me the method or maybe the reference to it?

**Comment by pmoulon** [comment]
It computes input photometric putative matches (SIFT or other descriptor matches) and then use a robust model estimator.
Since the model estimator can be template you can filter the match with estimating Homography, Fundamental, Essential matrix.
The robust estimator is ACRansac (http://www.ipol.im/pub/art/2016/147/).

Here the calling of the interface for an image collection (collection of pairwise correspondence to filter)
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L402

Then ACRansac implementation is here
https://github.com/openMVG/openMVG/blob/master/src/openMVG/robust_estimation/robust_estimator_ACRansac.hpp#L14

**Comment by MEGA728** [comment]
I removed the line "if (vec_inliers.size() > KernelType::MINIMUM_SAMPLES *2.5)" and got a matches.f.txt.
But it's like this:
0 1
0
0 2
0
0 3
0
0 4
0
0 5
0
...

Is there any other place I should modify in order to get correct matches from matches.putative.txt (under the circumstance of less than 17 matches) ?

**Comment by pmoulon** [comment]
I think I reject all the matches hypothesis in the ACRansac function, since I detect that the model is not stable enough.
I will try to look on my side when I will have some time (next week).

**Comment by MEGA728** [comment]
Thanks :)

**Comment by wguo68** [comment]
It is still not clear to me? What are the steps and how to edit needed files?

**Comment by MEGA728** [comment]
@pmoulon 
Still waiting for your answer. Please take a look at my question when you have time. Thanks!

**Comment by Jhfelectric** [comment]
Hi,
Sorry to come in this discussion with a side-related question : my matches files are all in binary (.bin). How do I get the same as readable text, did I miss something obvious here ? And btw, using a .bin file, extractMatches doesn't work...
Thanks for your help.
Julien

**Comment by pmoulon** [comment]
Hi,
There is no direct way to convert bin matches to txt matches (you need to call yourself the existing API function):

What do you mean by exportMatches does not work, it does not export pair with no matches?
See here https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_exportMatches.cpp#L166; So it means in your case that you don't have any pair with matches.

If you are using the essential matrix filter please be sure to have valid intrinsic data configured for your images.

**Comment by Jhfelectric** [comment]
Bonjour Pierre,
Thank you for your quick reply. The application says "Invalid matches file"
whatever file I put as an input.
Julien

**Comment by pmoulon** [comment]
Bonjour Julien,
You can use this function to convert some read matches to txt https://github.com/openMVG/openMVG/blob/master/src/openMVG/matching/indMatch_utils.hpp#L79

**Comment by Jhfelectric** [comment]
Merci !
