### ISSUE TITLE
Using openMVG with uncalibrated cameras

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#735]
Hi, the tutorials all hint at the sfm with completely calibrated cameras that need to have both intrinsic and extrinsic information, is there some provision/ alternative to attempt the same with uncalibrated cameras? I have come across self calibration but I am unsure as to how it all fits into this picture with OpenMVG, can someone help me out please.

**Comment by pmoulon** [comment]
Hi,
The SfM tutorial need only the intrinsic information (mostly the focal length in pixels). 
Note that the goal of SfM is mostly to obtain the extrinsic information.

You can use uncalibrated image in openMVG. Either by using only some images with intrinsic and let the incremental pipeline find the intrinsic of the remaining images by robust pose resection, or by providing an initial guess to the chain.

Here how to provide the initial guess for the pixel focal length:

If all your images have the same size you can use the ```-f X``` option on SfMInit_ImageListing
With ```X = 1.2 * max(w,h)```

It will provide a rough initial guess for the pixel focal length that the BA will be able to refine.

**Comment by naveenjafer** [comment]
Hi, 
     I am a little confused with the exact usage of the "Computer structure from motion" component, its requirements includes a "internal + external camera calibration". Is this an optional step for the scenario where I have additional camera external calibration? I can obtain internal information from the EXIF data of my images of a 3D object in sequence, I understood the steps till incremental SFM. Sorry for the inconvenience, I would be very grateful if you can correct me if I am doing something the wrong way. TIA

**Comment by pmoulon** [comment]
SfM consists in computing camera motion and the 3D structure that corresponds to matches point across an image collection.
It takes as input only the camera intrinsics (focal length) and image matches (often by image pairs).

"Computer structure from known poses" finds the 3D structure that is valid when no given matches are provided as input. See here for the algorithm I use  http://openmvg.readthedocs.io/en/latest/software/SfM/ComputeStructureFromKnownPoses/

OpenMVG can solve the SfM with two different pipelines:
- the incremental approach,
- the global approach.

Then you can use the results of the SfM step to try to enhance the point cloud by using "Computer structure from known poses" 

Hoping that this is more clear.

So if you have uncalibrated cameras (no intrinsic data) I suggest you to use the incremental SfM pipeline with a focal guess computed as I suggested to you.

**Comment by naveenjafer** [comment]
@pmoulon Thank you so much for taking time out. This explained the procedure and I have a good idea of how to go about with this! Thank you for the awesome package! Cheers! I'll get back in touch if I run into troubles :)
