### ISSUE TITLE
Using GCP to improve sparse reconstruction robustness

### ISSUE THREAD

**Issue by roby23** [openMVG/openMVG#737]
Is it possible to use GCP in some way during the incremental or global reconstruction to improve the reconstruction result? 
As I know for now I can only use them after the reconstruction to georeference the point cloud

**Comment by pmoulon** [comment]
GCP and GPS priors can be used in the SfM pipeline (mostly during BA)
See (here for the GCP residual used for BA)[https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L353].

**Comment by roby23** [comment]
Yes I saw it. I tried to enable the GCP in the bundle adjustment of the incremental SfM
[https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L1208](url)

with

`Control_Point_Parameter(20.0, true)`

but an assertion fails because it looks for poses that are not computed yet (they are not in the map_poses)
[https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L379](url)
[https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/internal/ceres/problem_impl.cc#L89](url)

I also tried to check the 	existence of the pose in map_poses, but then I get other errors at 

`// Set the 3D point as FIXED (it's a valid GCP)
problem.SetParameterBlockConstant(gcp_landmark_it.second.X.data());`

**Comment by pmoulon** [comment]
In order to be used the observations of the GCP must be visible by a camera that have a 3D pose.

If you can, please share your matching folder and the sfm_data file that embed the GCP. (you can remove the .desc to have a lighter archive).

**Comment by roby23** [comment]
Ah ok, I looked better at the BA and where it is used. I found out that in the UI GCP tool it refines also the extrinsics ant the structure. And this is what I was searching for. 
I could not use GCP and GPS priors at the same time during the reconstruction because they have different heights, the GCP have geodetic height, the priors have ellipsoid height. So I was getting very bad results fixing both parameters during BA.

Thanks for the help

**Comment by pmoulon** [comment]
Do you consider that this thread have answer to all your questions?
If this is the case, please close it.

For sure if all the data are in the same data it will work better.
Why do not consider convert your GCP 3D coordinates to the GPS datum (ECEF)?

**Comment by roby23** [comment]
I will try converting the coordinates to ECEF.
I close the issue

Thanks
