### ISSUE TITLE
Using the SFM application in c++

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#742]
Hi, is there any way to use the SFM application API in c++? I am looking at options to build a c++ application. Apart from making a command line call to invoke the API and messing around with forks and everything, is there a cleaner way? TIA

**Comment by pmoulon** [comment]
Every OpenMVG code can be used as a third party library.
see https://github.com/openMVG/openMVG/blob/master/BUILD#L127

As you can see here, the software are just a wrapper to call the openMVG libraries
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/CMakeLists.txt#L92

**Comment by naveenjafer** [comment]
@pmoulon Hi, I have followed the instructions as per the link as provided by you, I am attempting to understand a few aspects of how I can use this as a third party library. I have linked the openMVG project as a 3rd party lib and the cmakeLists file of my new project is as follows

```
cmake_minimum_required(VERSION 2.8)
project (hello)
find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
add_executable(hello helloworld.cpp)
target_link_libraries(hello ${OPENMVG_LIBRARIES}) 
```

I have built the project with a "cmake -DOpenMVG_DIR:STRING="/home/naveen/Software/openMVG_Build/openMVG_install/share/openMVG/cmake" -DCMAKE_BUILD_TYPE=RELEASE . ../helloworld" and it works fine

Running a make after this step results in a multitude of errors when I try to include one of the hpp files in the following fashion "#include "openMVG/sfm/sfm.hpp"
The program is as simple as this

```
#include<iostream>
#include "openMVG/sfm/sfm.hpp"

int main(int argc, char *argv[]){
   std::cout << "Hello World2!" << std::endl;
   return 0;
}
```
The starting of the error is this

[100%] Building CXX object CMakeFiles/hello.dir/helloworld.cpp.o
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /home/naveen/Software/openMVG_Build/openMVG_install/include/openMVG/types.hpp:12,
                 from /home/naveen/Software/openMVG_Build/openMVG_install/include/openMVG/sfm/sfm.hpp:10,
                 from /home/naveen/Desktop/cmake_tuts/exploringBB/extras/cmake/helloworld/helloworld.cpp:2:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.


I am very new to cmake and make, is this how it is to be done? Any help will be greatly appreciated. TIA

**Comment by naveenjafer** [comment]
My current objective is to build a sample application that would be able to combine 2 or more tasks from the SFM application. Say for example, my objective is to combine Compute Features and Compute Matches, my idea is to write another file that technically redoes the implementation of the respective cpp files of both the functions. Later on, depending on my requirements, I will modify the parts of the single combined cpp file.

**Comment by jkerfs** [comment]
This error just means that you are not using C++11, try adding the following to your CMakeLists.txt (right after the project line):
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

**Comment by naveenjafer** [comment]
@jkerfs Thank you! It works now! Regarding the objective that I have mentioned about, would this be the right way to approach it?

**Comment by naveenjafer** [comment]
@pmoulon for a start, I am trying to create a replica of main_SFMInit_ImageListing.cpp. I have just copied the contents of this file into helloworld.cpp. I run into the following error.
```

[100%] Building CXX object CMakeFiles/hello.dir/helloworld.cpp.o
Linking CXX executable hello
CMakeFiles/hello.dir/helloworld.cpp.o: In function `openMVG::exif::Exif_IO_EasyExif::open(std::string const&)':
helloworld.cpp:(.text._ZN7openMVG4exif16Exif_IO_EasyExif4openERKSs[_ZN7openMVG4exif16Exif_IO_EasyExif4openERKSs]+0xd0): undefined reference to `easyexif::EXIFInfo::parseFrom(unsigned char const*, unsigned int)'
CMakeFiles/hello.dir/helloworld.cpp.o: In function `easyexif::EXIFInfo::EXIFInfo()':
helloworld.cpp:(.text._ZN8easyexif8EXIFInfoC2Ev[_ZN8easyexif8EXIFInfoC5Ev]+0x70): undefined reference to `easyexif::EXIFInfo::clear()'
collect2: error: ld returned 1 exit status
make[2]: *** [hello] Error 1
make[1]: *** [CMakeFiles/hello.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by naveenjafer** [comment]
The main_IncrementalSFM.cpp file ran without any issues when i copied its contents and ran it as an application from my application. The EXIF_IO_EasyExif seems to be creating the issue. I also referred to another implementation Regard3D to check if they have made use of the exif reader from openMVG as a 3rd party, but they havent, so I am unable to understand what could be causing the issue. Could it be something to do with how "exif.h" has been included in the exif_IO_EasyExif.hpp file?

**Comment by naveenjafer** [comment]
Incremental SFM, GlobalSFM and Compute Matches have ran without any issues.

ComputeFeatures and ImageListing are the ones that run into issues. The error for computeFeatures is as follows
```
Linking CXX executable computeFeatures
CMakeFiles/computeFeatures.dir/computeFeatures.cpp.o: In function `openMVG::features::SIFT_Image_describer::~SIFT_Image_describer()':
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describerD2Ev[_ZN7openMVG8features20SIFT_Image_describerD5Ev]+0xc): undefined reference to `vl_destructor'
CMakeFiles/computeFeatures.dir/computeFeatures.cpp.o: In function `openMVG::features::SIFT_Image_describer::~SIFT_Image_describer()':
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describerD0Ev[_ZN7openMVG8features20SIFT_Image_describerD0Ev]+0xc): undefined reference to `vl_destructor'
CMakeFiles/computeFeatures.dir/computeFeatures.cpp.o: In function `openMVG::features::SIFT_Image_describer::Describe(openMVG::image::Image<unsigned char> const&, std::unique_ptr<openMVG::features::Regions, std::default_delete<openMVG::features::Regions> >&, openMVG::image::Image<unsigned char> const*)':
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x71): undefined reference to `vl_sift_new'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0xcc): undefined reference to `vl_sift_process_first_octave'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x140): undefined reference to `vl_sift_detect'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x153): undefined reference to `vl_sift_update_gradient'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x1ee): undefined reference to `vl_sift_calc_keypoint_descriptor'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x365): undefined reference to `vl_sift_process_next_octave'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x375): undefined reference to `vl_sift_delete'
computeFeatures.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x510): undefined reference to `vl_sift_calc_keypoint_orientations'
CMakeFiles/computeFeatures.dir/computeFeatures.cpp.o: In function `main':
computeFeatures.cpp:(.text.startup+0x8df): undefined reference to `vl_constructor'
CMakeFiles/computeFeatures.dir/computeFeatures.cpp.o: In function `openMVG::features::SIFT_Image_describer* cereal::access::construct<openMVG::features::SIFT_Image_describer>()':
computeFeatures.cpp:(.text._ZN6cereal6access9constructIN7openMVG8features20SIFT_Image_describerEEEPT_v[_ZN6cereal6access9constructIN7openMVG8features20SIFT_Image_describerEEEPT_v]+0x46): undefined reference to `vl_constructor'
collect2: error: ld returned 1 exit status
make[3]: *** [computeFeatures] Error 1
make[2]: *** [CMakeFiles/computeFeatures.dir/all] Error 2
make[1]: *** [CMakeFiles/computeFeatures.dir/rule] Error 2
make: *** [computeFeatures] Error 2
```

**Comment by jkerfs** [comment]
It looks like you have some linking problems.  Take a look at https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/software/SfM/CMakeLists.txt.

To use easyexif, vl_feat, etc you need to list those in the `TARGET_LINK_LIBRARIES` for each executable.   Make sure that for each example you are compiling match the corresponding entry in the CMakeLists.txt mentioned above.

**Comment by naveenjafer** [comment]
@jkerfs I thought so too, but by doing this `target_link_libraries(matchFeatures ${OPENMVG_LIBRARIES})` wont it link it to all the libraries in the lib folder of the openMVG_install. That folder contains the libeasyexif.a and libvlsift.a . In case this is not getting linked, then how do I go about linking it?

**Comment by naveenjafer** [comment]
@jkerfs Oh! I manually added it, the linking now works, all the components run without issues. I am still curious as to why the other libraries did not get linked.

**Comment by jkerfs** [comment]
It is actually a design choice to not automatically include the third party libraries.  Some users may not want to compile the third party libraries or the libraries are not compatible with their system.  Additionally, people may want to use alternate versions of the third party libraries from those included in openMVG.

It also keeps the compiled binaries smaller if non-essential libraries are not included.

Best of luck with you project.

**Comment by naveenjafer** [comment]
@jkerfs oh! Will keep that in mind.  Thanks you! :+1:

**Comment by naveenjafer** [comment]
@pmoulon I was using gcc 4.8.4 and everything had worked fine, had to upgrade it to 4.9 to use json with the project that is using openMVG and I am running into Segmentation Fault in each of the sfm pipeline components. I removed the cache and ran cmake too. Any idea as to what might be causing this?

**Comment by pmoulon** [comment]
Since you have update your compiler, please recompile from scratch OpenMVG in order to avoid conflict with the old libraries.
