### ISSUE TITLE
openMVG_main_ComputeFeatures with multi cores gives different results at each execution

### ISSUE THREAD

**Issue by roby23** [openMVG/openMVG#746]
Using openMVG_main_ComputeFeatures with -n option greater than 1 gives different results at each execution.
I tried many times with -n 1 and the resulting .feat and .desc files have the same size from one execution to another.
If I use for example -n 8 the first 8 .feat and .desc files have almost always different sizes and sometimes also other files

I compiled OpenMVG with VS2015 on Win7

![features](https://cloud.githubusercontent.com/assets/25249606/22295175/463d3a10-e316-11e6-81fe-52028ea40eb9.png)

**Comment by pmoulon** [comment]
Hi, Thanks for telling it.
Strange to see that it happens only on the first chunk of images that are processed.
@mitjap Can you have a look again on it?

**Comment by roby23** [comment]
Yes, but sometimes it happens also on some other images later. Let's say it's more stable after the first -n images processed

**Comment by roby23** [comment]
I think I found the problem. Just move the declaration of imageGray inside the parallel for and it works.

https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L241

to 

https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L280

**Comment by pmoulon** [comment]
Perhaps we can also add this to the openMP clause ```private(imageGray)```
This way we specifies that each thread should have its own instance of the variable.

Seems like the bug is due to a merge done to fast by myself... https://github.com/openMVG/openMVG/commit/4074ae0735028fac140fea85e95b4df6c1214eb6#diff-31e8d4fb05c8c87d50a2bf57a2f3e191

**Comment by roby23** [comment]
Good, putting imageGray in the private clause solves the problem.

I'm not an expert of OpenMP, is there a difference between using the private clause and declaring imageGray inside the loop?

**Comment by pmoulon** [comment]
The diff is about the memory allocation.

If you set the image inside the loop, each time you try to extract feature you allocate a new image.

If you use the openmp private close, each thread will have its own image that will be reused. So if many image have the same size you will minimize the memory allocation (reuse the previously allocated memory).

Thanks for having tested the private clause. Will make a commit to the develop branch soon.

**Comment by pmoulon** [comment]
Will be fixed by #747
