### ISSUE TITLE
Add OpenCV version requirement to CMakeLists.txt

### ISSUE THREAD

**Issue by jkerfs** [openMVG/openMVG#750]
Since the AKAZE detector require OpenCV 3+ (see https://github.com/openMVG/openMVG/issues/561), does it make sense to add the OpenCV version requirement to `src/CMakeLists.txt`?  Otherwise the error messages are somewhat cryptic, and it is not obvious that the OpenCV version is incorrect.

Here are two possible ways to do it:
<pre><code>
...
if (OpenMVG_USE_OPENCV)
  FIND_PACKAGE( OpenCV <b>3.0.0 QUIET</b> )
  if (NOT OpenCV_FOUND)
    message(STATUS "OpenCV was not found. Disabling OpenCV support.")
...
</pre></code>

<pre><code>
...
if (OpenMVG_USE_OPENCV)
  FIND_PACKAGE( OpenCV)
  if (NOT OpenCV_FOUND OR <b>OpenCV_VERSION VERSION_LESS "3.0.0"</b>)
    message(STATUS "OpenCV was not found. Disabling OpenCV support.")
...
</pre></code>

**Comment by pmoulon** [comment]
Hi @jkerfs 
Thank you for the report and the suggestions.
You're right the warning about the version could be a good idea.

PS: Please note also that OpenMVG have its own AKAZE version.
