### ISSUE TITLE
Issue with OPENMVG_STD_UNORDERED_MAP

### ISSUE THREAD

**Issue by bchretien** [openMVG/openMVG#753]
In `src/openMVG/types.hpp`, `OPENMVG_STD_UNORDERED_MAP` is defined for clang, thus changing the actual type used for `Hash_Map` (`std::unordered_map` instead of `std::map`). As a result, if one compiles openMVG with gcc, installs it, and later compiles a program that depends on openMVG with clang, linking will fail since some symbols will not be found (methods with `Hash_Map` parameters for instance).

If that compile-time branching is unavoidable (a `std::map` Cereal serialization bug was mentioned in the commits), we should set this definition in CMake, and export it to the CMake configuration files. That way, programs depending on openMVG will automatically have `-DOPENMVG_STD_UNORDERED_MAP` when relevant. `types.hpp` would need to be adapted (`#ifdef OPENMVG_STD_UNORDERED_MAP` rather than `#ifdef __clang__`).

**Comment by pmoulon** [comment]
Hi @bchretien 
Thank you for your message.
I'm aware of this issue, and it would be nice if we can work on it.

The OPENMVG_STD_UNORDERED_MAP seems a nice alternative to solve the issue.
Feel free to make some investigation on your side and do a PR with your working solution.

**Comment by bchretien** [comment]
I made a patch for this issue, see PR #755.

**Comment by simogasp** [comment]
If I may jump in the discussion, we are struggling as well with the propagation of the preprocessor definitions when omvg is used as third party. There are 2 solutions that come to my mind (but I don't know if they are the best or others better exist):

Sol1: "forget about cmake" :-)
* get rid of all `add_definitions( -DXXX)`
* let cmake generate a `config.h` file containing all the definitions 
  * here is an example I made for cctags [config.hpp.in](https://github.com/alicevision/CCTag/blob/develop/cmake/config.hpp.in), `#cmakedefine` will automatically replace the definition with `#define` or nothing (more here https://cmake.org/cmake/help/v3.2/command/configure_file.html?highlight=cmakedefine)
  * note the generation is done everytime cmake is invoke, so it can dynamically change the file with the modifications that are made to the omvg code
* include this config file in every file having an `#ifdef`
* the `config.h` must be installed along with all the other omvg files, and possibly it can be further used in the main application if necessary.
The advantage of this solution is that it does not depend on cmake (beside the generation part), ie once omvg is installed it can be used as 3rd party in a application whether or not cmake is the building system of the destination application. Of course it requires to modify all the sources containing the `#ifdef` to include the config file.

Sol2: "do it the cmake way" :-)
* get rid of all `add_definitions( -DXXX)`
* **for each target** (ie each omvg module) carefully specify the preprocessor definitions and their scope using [`target_compile_definition()`](https://cmake.org/cmake/help/v3.0/command/target_compile_definitions.html) which is the proper way to do it
  * PUBLIC are those definitions like `OPENMVG_STD_UNORDERED_MAP` that must propagated and that affect hpp files
  * PRIVATE are those that are only used in cpp files (maybe not the most accurate definition but kind of a rule of thumb) and don't need to be propagated.
* doing that, it automagically adds the definitions in the generated `ConfigOpenMVG.cmake` file and everything works in the main application just importing omvg with the usual `find_package()`
This solution requires a bit of careful writing in all the concerned CMakeLists, and then, for omvg maintainers/developers/contributors a careful work of maintenance to assure that the scopes are still correct etc etc. And being "pure cmake" it will work only if the destination application uses cmake.

@fabiencastan @yann-lty

**Comment by bchretien** [comment]
@simogasp: :+1: My patch is a quick fix following solution 2, since this minimizes non-CMake code changes. As you said, it could be enhanced with a finer control of the definition dependencies. If I'm not mistaken though, `target_compile_definition()` was not available with CMake 2.6 (which is the minimum required version of CMake at the moment), so we would need to use the old way to tackle this (or bump the minimum required CMake version).

Solution 1 is quite straightforward if all OpenMVG targets can share the same set of public definitions (i.e. we do not have `target_A` with `-DFOO` and `target_B` without it).

**Comment by simogasp** [comment]
> was not available with CMake 2.6

Yes sorry, i forgot that the version is still < 3.0 so sol2 is not doable (I don't think it's smart to reinvent the wheel writing cmake code that is already in recent versions :-)

> Solution 1 is quite straightforward if all OpenMVG targets can share the same set of public definitions (i.e. we do not have target_A with -DFOO and target_B without it).

It's true but it would be quite strange to have this kind of twisted requirements for a library where the targets are dependent on each other, or at least i cannot find a practical example. In omvg, for example, `since add_definitions()` is used, it means that all targets are already using the same definitions.

**Comment by bchretien** [comment]
> It's true but it would be quite strange to have this kind of twisted requirements for a library where the targets are dependent on each other, or at least i cannot find a practical example.

Absolutely, this is the only possible (yet improbable) issue that comes to mind with that approach. Since there are lots of executables in the project, some of them might rely on shared header-only code with specific compile-time definitions, although I doubt it.

> In omvg, for example, since add_definitions() is used, it means that all targets are already using the same definitions.

If nothing else is used, that settles it then :)

**Comment by simogasp** [comment]
Actually there are some definitions that are not directly used in the code but rather enable features of the compiler, like eg
```cmake
if (WIN32)
  add_definitions(-DNOMINMAX)
  add_definitions(-DVC_EXTRALEAN)
  add_definitions(-D_USE_MATH_DEFINES)
  if (MSVC)
    add_definitions(/bigobj)
```
or
```cmake
add_definitions(--coverage -fprofile-arcs -ftest-coverage)
```
so i guess those must stay

**Comment by pmoulon** [comment]
Solved by https://github.com/openMVG/openMVG/commit/7b23dea66f9f7841d64c05c9f001f83f235b37b4
