### ISSUE TITLE
[Visual Studio 2015] Error Code MSB3491: The specified path is too long, 260 characters problem

### ISSUE THREAD

**Issue by wystnphux** [openMVG/openMVG#754]
Hello,

this is an error code which I get, trying to build openMVG on Windows 7 with CMake and Visual Studio 2015.

> Error	MSB3491	Could not write lines to file "openMVG_sample_multiview_robustFundamental_guided.dir\Release\openMVG_.7A079DAC.tlog\openMVG_sample_multiview_robustFundamental_guided.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	openMVG_sample_multiview_robustFundamental_guided	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets	312	

There are some more of these. Actually I don't know where to start to fix this issue.
Maybe someone more experienced does have a hint on this.

I will provide further information if needed; but at the moment I don't know which information would be useful.

Kind regards

**Comment by pmoulon** [comment]
Try to compile the project in a simpler path like ```C:/dev/openMVG_Build``` to see if it solves the issue.

**Comment by wystnphux** [comment]
Thank you very much for your fast reply! This resolved the issue.
