### ISSUE TITLE
Does OpenMVG uses orientation angles as priors for SfM?

### ISSUE THREAD

**Issue by pogilon** [openMVG/openMVG#765]
If orientation information is also available with the GPS location, can OpenMVG use orientation angles as priors for SfM?

**Comment by pmoulon** [comment]
Not yet, but we can work on this feature together.

1. a quick temporary solution (if your rotation are accurate) can consist in directly provide the global rotation to the global SfM pipeline.

**Comment by pmoulon** [comment]
Close due to inactivity.
