### ISSUE TITLE
Is it possible to ignore the "Z" component when computing the matching list based on GPS? (openMVG_main_ListMatchingPairs)

### ISSUE THREAD

**Issue by pogilon** [openMVG/openMVG#767]
Many times, the GPS information is not very reliable in the "Z" component and a matching list based on the "X" and "Y" coordinates are desired. Is it possible to do this in OpenMVG? If not, do you have any recommendations about how to make this changes? or is this feature coming soon? Thank you!

**Comment by pmoulon** [comment]
The curent API currently allow to do what you want (thanks to @hcjghr)

Just use the ```[-W|--prior_weigths] \"x;y;z;\"``` command line option on SfMInit_ImageListing binary.
```-W 1;1;0``` will do the thick for your need :smile: 

https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_SfMInit_ImageListing.cpp#L168

PS:
Here the doc to the GPS prior usage
https://github.com/openMVG/openMVG/blob/master/docs/sphinx/rst/software/Geodesy/geodesy.rst

**Comment by pmoulon** [comment]
@pogilon Any feedback?

**Comment by pmoulon** [comment]
@pogilon Any feedback?

**Comment by pogilon** [comment]
Thank you!

**Comment by pogilon** [comment]
@pmoulon  this weight set, is it applied currently on the ECEF coordinate system, **right?** However, the Z axis is not the height axis, which is where I would be interested in providing a lower W value. Do you have any recommendations? Thanks!

**Comment by pmoulon** [comment]
You can apply a transform of your coordinate system in order to have the main direction align to the Z axis.
Plane going through your camera ECEF trajectory align to have Z = 1.
