### ISSUE TITLE
How can I export matches into another platform?

### ISSUE THREAD

**Issue by pogilon** [openMVG/openMVG#768]
Hello, I would like to import the matches computed by openMVG into another framework. How are the matches stored? Thank you!

**Comment by pmoulon** [comment]
Since I answered to this many time, I think I have to document it somewhere ;-)

See here for the last time I explained it 
https://github.com/openMVG/openMVG/issues/734#issuecomment-273678782

Stay tuned... for the complete documentation

**Comment by pmoulon** [comment]
@pogilon Any feedback?

**Comment by pogilon** [comment]
Thank you so much! I will let you know soon!

**Comment by pmoulon** [comment]
Close due to inactivity. Feel free to re-open.
