### ISSUE TITLE
Compilation with example fails on mac

### ISSUE THREAD

**Issue by siddharthsrivastava** [openMVG/openMVG#769]
While compiling openMVG with examples on Mac OSX Sierra, the compilation fails with the error

> /3dmodel/openMVG/openMVG/src/software/SfM/InterfaceMVS.h:84:23: error: member reference
>       base type 'unsigned long' is not a structure or union
>         const_cast<_Tp&>(obj).serialize(a, 0);

> /3dmodel/openMVG/openMVG/src/software/SfM/InterfaceMVS.h:89:5: error: member reference
>       base type 'unsigned long' is not a structure or union
>         obj.serialize(a, 0);

How can this be fixed ?

**Comment by pmoulon** [comment]
@siddharthsrivastava We are aware of this issue see [here](https://github.com/openMVG/openMVG/issues/713),

The fix you can use consist in uncomment this line https://github.com/openMVG/openMVG/blob/master/src/software/SfM/InterfaceMVS.h#L154 and everything will run fine.

**Comment by siddharthsrivastava** [comment]
@pmoulon thanks, it goes ahead, but results in another error

> /3dmodel/openMVG/openMVG/src/dependencies/cereal/include/cereal/external/rapidjson/document.h:108:32: error:
>       reference to 'random_access_iterator_tag' is ambiguous
>     typedef std::iterator<std::random_access_iterator_tag,ValueType> BaseType;
>                                ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note:
>       candidate found by name lookup is 'std::__1::random_access_iterator_tag'
> struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
>                              ^
> /opt/local/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
>     struct random_access_iterator_tag;

**Comment by pmoulon** [comment]
Never encounter this error before, => seems like related to QT.

@rperrot Any idea?

**Comment by rperrot** [comment]
Can you tell us more about the part of the library that fail to compile ? (the library itself, a specific sample ?)

Can you tell us your version of Qt and if you use the internal clang (ie: shipped with xcode), or a macports one ?

**Comment by siddharthsrivastava** [comment]
@rperrot  I am using Clang version shipped with XCode. The clang version is

> Apple LLVM version 8.0.0 (clang-800.0.42.1)
> Target: x86_64-apple-darwin16.3.0
> Thread model: posix
> InstalledDir: 
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

The Qt version is (executed qmake -v)

> QMake version 2.01a
> Using Qt version 4.8.2 in /opt/local/lib

I used the openMVG version from master.

The problem comes while compiling Qt related components. A part of the error logs is as follows (I guess the problem is with Qt version as the logs say, I am not sure, but I am upgrading it to Qt 5.x)
I have a few questions while I proceed with this (or in case you have some other suggestions)
1. Is there any recommended Qt version for openMVG
2. Can I direct openMVG to use custom path for Qt

> [100%] Building CXX object software/ui/SfM/control_points_registration/CMakeFiles/ui_openMVG_control_points_registration.dir/GraphicsMainWindow.cpp.o
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.cpp:7:
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.hpp:9:
> In file included from /opt/local/include/QtGui/QtGui:3:
> In file included from /opt/local/include/QtCore/QtCore:3:
> In file included from /opt/local/include/QtCore/qalgorithms.h:45:
> /opt/local/include/QtCore/qglobal.h:331:6: warning: "This version of Mac OS X is unsupported" [-W#warnings]
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/main.cpp:7:
> In file included from /opt/local/include/QtGui/QApplication:1:
> In file included from /opt/local/include/QtGui/qapplication.h:45:
> In file included from /opt/local/include/QtCore/qcoreapplication.h:45:
> In file included from /opt/local/include/QtCore/qobject.h:47:
> In file included from /opt/local/include/QtCore/qobjectdefs.h:45:
> In file included from /opt/local/include/QtCore/qnamespace.h:45:
> /opt/local/include/QtCore/qglobal.h:331:6: warning: "This version of Mac OS X is unsupported" [-W#warnings]
> #    warning "This version of Mac OS X is unsupported"
>      ^
> #    warning "This version of Mac OS X is unsupported"
>      ^
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/GraphicsMainWindow.cpp:7:
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/GraphicsMainWindow.hpp:10:
> In file included from /opt/local/include/QtGui/QMainWindow:1:
> In file included from /opt/local/include/QtGui/qmainwindow.h:45:
> In file included from /opt/local/include/QtGui/qwidget.h:45:
> In file included from /opt/local/include/QtGui/qwindowdefs.h:45:
> In file included from /opt/local/include/QtCore/qobjectdefs.h:45:
> In file included from /opt/local/include/QtCore/qnamespace.h:45:
> /opt/local/include/QtCore/qglobal.h:331:6: warning: "This version of Mac OS X is unsupported" [-W#warnings]
> #    warning "This version of Mac OS X is unsupported"
>      ^
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.cpp:7:
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.hpp:9:
> In file included from /opt/local/include/QtGui/QtGui:3:
> In file included from /opt/local/include/QtCore/QtCore:7:
> In file included from /opt/local/include/QtCore/qcache.h:45:
> In file included from /opt/local/include/QtCore/qhash.h:48:
> /opt/local/include/QtCore/qlist.h:184:22: error: reference to 'random_access_iterator_tag' is ambiguous
>         typedef std::random_access_iterator_tag  iterator_category;
>                      ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note:
>       candidate found by name lookup is 'std::__1::random_access_iterator_tag'
> struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
>                              ^
> /opt/local/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
>     struct random_access_iterator_tag;
>            ^
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.cpp:7:
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/mainLayout.hpp:9:
> In file included from /opt/local/include/QtGui/QtGui:3:
> In file included from /opt/local/include/QtCore/QtCore:7:
> In file included from /opt/local/include/QtCore/qcache.h:45:
> In file included from /opt/local/include/QtCore/qhash.h:48:
> /opt/local/include/QtCore/qlist.h:231:22: error: reference to 'random_access_iterator_tag' is ambiguous
>         typedef std::random_access_iterator_tag  iterator_category;
>                      ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note:
>       candidate found by name lookup is 'std::__1::random_access_iterator_tag'
> struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
>                              ^
> /opt/local/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
>     struct random_access_iterator_tag;
>            ^
> In file included from Documents/3dmodel/openMVG/openMVG/src/software/ui/SfM/control_points_registration/main.cpp:7:
> In file included from /opt/local/include/QtGui/QApplication:1:
> In file included from /opt/local/include/QtGui/qapplication.h:45:
> In file included from /opt/local/include/QtCore/qcoreapplication.h:45:
> In file included from /opt/local/include/QtCore/qobject.h:50:
> /opt/local/include/QtCore/qlist.h:184:22: error: reference to 'random_access_iterator_tag' is ambiguous
>         typedef std::random_access_iterator_tag  iterator_category;
>                      ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note:
>       candidate found by name lookup is 'std::__1::random_access_iterator_tag'
> struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
>                              ^
> /opt/local/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
>     struct random_access_iterator_tag;

**Comment by siddharthsrivastava** [comment]
For now, I have been able to build it without using Qt. I will report back with latest version of Qt.

**Comment by rperrot** [comment]
@siddharthsrivastava I use Qt > 5.5 on osx. Never tried using macports versions and with version < 5.5. 

"Can I direct openMVG to use custom path for Qt"

You can specify the correct path using Qt5Widgets_DIR variable (cmake -DQt5Widgets_DIR=...)

**Comment by antochny** [comment]
Hi everybody, trying to compile on OSX Sierra as well I got an error :
`CompileC /Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/Objects-normal/x86_64/Camera_Pinhole_Radial_test.o openMVG/cameras/Camera_Pinhole_Radial_test.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/anthony/openMVG/src
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=135 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Release\" -DOPENMVG_USE_SSE -DOPENMVG_USE_CXX11 -DHAVE_CXX11_THREAD -DHAVE_CXX11_CHRONO -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.10 -Wno-sign-conversion -I/Users/anthony/openMVG_Build/Darwin-x86_64-RELEASE/Release/include -I/Users/anthony/openMVG/src/third_party/eigen -I/Users/anthony/openMVG/src -I/Users/anthony/openMVG/src/third_party/jpeg -I/Users/anthony/openMVG_Build/third_party/jpeg/config -I/Users/anthony/openMVG/src/third_party/png -I/Users/anthony/openMVG/src/third_party/zlib -I/Users/anthony/openMVG_Build/third_party/png/config -I/Users/anthony/openMVG/src/third_party/tiff -I/Users/anthony/openMVG_Build/third_party/tiff -I/Users/anthony/openMVG/src/third_party -I/Users/anthony/openMVG/src/dependencies -I/Users/anthony/openMVG/src/dependencies/cereal/include -I/Users/anthony/openMVG/src/third_party/lemon -I/Users/anthony/openMVG_Build/third_party/lemon -I/Users/anthony/openMVG/src/third_party/ceres-solver/include -I/Users/anthony/openMVG/src/third_party/ceres-solver/internal/ceres/miniglog -I/Users/anthony/openMVG_Build/third_party/ceres-solver/config -I/Users/anthony/openMVG/src/third_party/flann/src/cpp -I/Users/anthony/openMVG/src/dependencies/osi_clp/CoinUtils/src -I/Users/anthony/openMVG/src/dependencies/osi_clp/Clp/src -I/Users/anthony/openMVG/src/dependencies/osi_clp/Clp/src/OsiClp -I/Users/anthony/openMVG/src/dependencies/osi_clp/Osi/src/Osi -I/Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/DerivedSources/x86_64 -I/Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/anthony/openMVG_Build/Darwin-x86_64-RELEASE/Release -march=core-avx-i -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-xop -mno-fma4 -mno-avx2 --std=c++11 -MMD -MT dependencies -MF /Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/Objects-normal/x86_64/Camera_Pinhole_Radial_test.d --serialize-diagnostics /Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/Objects-normal/x86_64/Camera_Pinhole_Radial_test.dia -c /Users/anthony/openMVG/src/openMVG/cameras/Camera_Pinhole_Radial_test.cpp -o /Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/Objects-normal/x86_64/Camera_Pinhole_Radial_test.o
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Pinhole_Radial_test.cpp:8:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/cameras.hpp:11:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Intrinsics.hpp:16:
In file included from /Users/anthony/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:39:
/Users/anthony/openMVG/src/dependencies/cereal/include/cereal/details/polymorphic_impl.hpp:226:61: error: chosen constructor is
      explicit in copy-initialization
          auto & derivedMap = baseMap.insert( lb, {baseKey, {}} )->second;
                                                            ^~
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Pinhole_Radial_test.cpp:8:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/cameras.hpp:11:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Intrinsics.hpp:12:
In file included from /Users/anthony/openMVG/src/openMVG/geometry/pose3.hpp:10:
In file included from /Users/anthony/openMVG/src/openMVG/multiview/projection.hpp:31:
In file included from /Users/anthony/openMVG/src/openMVG/numeric/numeric.h:40:
In file included from /Users/anthony/openMVG/src/third_party/eigen/Eigen/SparseCore:9:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:838:14: note: constructor
      declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Pinhole_Radial_test.cpp:8:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/cameras.hpp:11:
In file included from /Users/anthony/openMVG/src/openMVG/cameras/Camera_Intrinsics.hpp:12:
In file included from /Users/anthony/openMVG/src/openMVG/geometry/pose3.hpp:10:
In file included from /Users/anthony/openMVG/src/openMVG/multiview/projection.hpp:31:
In file included from /Users/anthony/openMVG/src/openMVG/numeric/numeric.h:35:
In file included from /Users/anthony/openMVG/src/third_party/eigen/Eigen/Core:28:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/complex:247:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:131:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:626:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:262:37: note: passing
      argument to parameter '__y' here
    pair(const _T1& __x, const _T2& __y)
                                    ^
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/anthony/openMVG_Build/openMVG/cameras/openMVG.build/Release/openMVG_test_Camera_Pinhole_Radial.build/Objects-normal/x86_64/Camera_Pinhole_Radial_test.o openMVG/cameras/Camera_Pinhole_Radial_test.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

**Comment by stephane-lb** [comment]
Works well using brew and qt5.
