### ISSUE TITLE
[software/SfM] openMVG_main_ExportUndistortedImages.exe not working with gray images

### ISSUE THREAD

**Issue by iskandervito** [openMVG/openMVG#773]
Dear

The openMVG_main_ExportUndistortedImages.exe is only working with RGB images. Looking at the code
line  118: if (ReadImage( srcImage.c_str(), &image)), it makes an assumption that the image is an RGB (by definition the image variable is defined in line 79 as an RGB  Image<RGBColor> image, image_ud;

I have gray scale image (only one band in my jpeg file). I tried to use this function but it runs without an exit code and no undistorted images are outputted.
Can you please fix this issue
Thanks

Iskander

**Comment by pmoulon** [comment]
You can checkout and use the develop branch.
I have implemented and test the feature you requested.
