### ISSUE TITLE
Compiling OpenGV

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#777]
Hi,

I have downloaded openGV and ran CMake for VisualStudio 2015.

When compiling I was getting
"Command line error D8021: invalid numeric argument '/Wextra'"

I changed the following command line option from
 /bigobj -Wextra -Wwrite-strings -Wno-unused-parameter -fno-strict-aliasing 

to 
 /bigobj

and it compiles.

is this Ok or will this create some problems elsewhere ?

Regards,

Alan

**Comment by pmoulon** [comment]
Alan, it will not create problem.

BTW, I would advise you to use my FORK and this branch:
https://github.com/pmoulon/opengv/tree/develop_boostless

I made some minor changes that ease compilation and setup of the library.
