### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#778]
Hi,

I have downloaded openGV and ran CMake for VisualStudio 2015.

When compiling I was getting
"Command line error D8021: invalid numeric argument '/Wextra'"

I changed the following command line option from
 /bigobj -Wextra -Wwrite-strings -Wno-unused-parameter -fno-strict-aliasing 

to 
 /bigobj

and it compiles.

is this Ok or will this create some problems elsewhere ?

Regards,

Alan

**Comment by pmoulon** [comment]
You can change the compilation preprocessor, it will not create problems.

BTW, I would advise you to use the OpenGV fork I made that make OpenGV simpler to compile and install (check branch develop_boostless):
https://github.com/pmoulon/opengv/tree/develop_boostless
