### ISSUE TITLE
Support of non central cameras (rigidly coupled cameras)

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#780]
Hi,

I would like to experiment with this feature.
1. Will have three cameras on an ROV that have approximate relative orientation information.

The discussion makes this sound reasonably straight forward.
1. I downloaded OpenGV but don't understand who I use this.
2. Pierre has supplied source for a new OpenMVG_SfMImageListing function
-  https://github.com/openMVG/OpenMVG_SfMImageListing_Elphel_Camera/blob/master/main.cpp#L138

However I am in the dark on how this is called and what the openGV library does.

Is it possible to call OpenMVG_SfMImageListing so that it can handle imagery collected from three cameras (solve 3 sets of Intrinsics)  ? The options seem to be either solve for the same camera or treat each image has having its own Intrinsics to solve ?

Regards,

Alan

**Comment by pmoulon** [comment]
Hi @bigakoz 
I would like to recommend you to see how are the results by using the classic OpenMVG pipeline and then try to use the subposes toolchain to see how it improves the results.

As I tell to you in another thread, OpenGV is solved to compute solve multiple view camera constraints between rigid group of cameras.

Default OpenMVG_SfMImageListing set shared or no shared intrinsic parameter.

The subpose branch add a known sub_pose to camera intrinsic and so for your case, you have to define 3 camera intrinsic and say that some view (images) share the same pose ids. Sorry for the lack of documentation. Will try to improve it when I will find some time.
