### ISSUE TITLE
Is there a way to avoid rotation and/or translation averaging ?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#782]
Hi Pierre,

Excellent job. Yesterday i compile the 75 "projects" on visual studio.....no error at all. congratulation.

I try to reconstruct a person, lets call him, "phil", as it is the name of his dataset on the web. 
The dataset contains 19 images and the cam go around Phil.  I got the dataset here: http://files.neonascent.net/phil-seq-pattern.zip

During the global reconstruction the 1st graph is produced...and it seems very good.
![goodgrpah](https://cloud.githubusercontent.com/assets/10100540/22839309/24a3122a-efc9-11e6-9dc6-a6d16d998d43.png)

After i get treatment of the global_sfm i have  only 4 nodes left, as shown in this graph 
![badgraph](https://cloud.githubusercontent.com/assets/10100540/22839428/a99df6b6-efc9-11e6-8f8a-a2de6c75e47d.png)

Then, PMVS received the file visdata containing the biggest connected graph:

VISDATA
4
0 3 1 2 3
1 3 0 2 3
2 3 0 1 3
3 3 0 1 2

I guess there is an issue with global rotation averaging or the global translation averaging for small dataset.

Is there a way to not execute the rot averaging or the trans averaging ?

For me this issue is the same as this one :https://github.com/openMVG/openMVG/issues/586

Thank you for you attention

**Comment by alvaro562003** [comment]
Actually, this is not the same issue as the #586.
I installed the patch https://gist.githubusercontent.com/pmoulon/4874ce4af910a3392e80e8af54b2d967/raw/82828d477eff54331411d4c8a61f893f7435cc73/gistfile1.txt
and the problem stays....unfortunately.

**Comment by pmoulon** [comment]
Global SfM is working with triplet or translation in order to ensure stability of the results (the chain use cycle in order to ensure consistency). As you saw the graph once cut in piece, only show you element that contained triplets ;-)

So if you have a loopy graph with only one to one relationship you must try the Sequential SfM pipeline that will provide better results for such type of graph.

**Comment by pmoulon** [comment]
Here the reconstruction I obtained (by using SIFT in HIGH mode ```-p HIGH``` on ComputeFeatures) with the Incremental/Sequential SfM toolchain:

![snapshot00](https://cloud.githubusercontent.com/assets/3235050/22919192/a4377c16-f28e-11e6-998b-3e17dcfaf35c.png)
![snapshot01](https://cloud.githubusercontent.com/assets/3235050/22919191/a434f54a-f28e-11e6-9b1d-c87c59d87450.png)

**Comment by alvaro562003** [comment]
Thank you for you reply. I tried with sequential on friday but did not get result as good as your.
I will try again.
i guess that : more triplets mean more overlap ?

**Comment by pmoulon** [comment]
Note that to enhance the chance of overlap between picture I ask the pipeline (ComputeFeatures) to compute more feature per images.

> more triplets mean more overlap ?
You're right.
