### ISSUE TITLE
Compiling in Fedora 25?

### ISSUE THREAD

**Issue by Patricus93** [openMVG/openMVG#785]
Good evening,

Having been a long time windows user, I am moving away and begging to look for open source software for geo-science applications. I would like to give openMVG a try. Following the build document, I can not get passed the external library setup. In fedora, none of the listed items are being found in the repositories. Is this ubuntu only?

**Comment by pmoulon** [comment]
Hi @Patricus93 OpenMVG can compile on any system, I have used on Fedora last year without trouble.
As you can see there is even some package https://copr.fedorainfracloud.org/coprs/sgielkens/Photogrammetry/package/openMVG/

Can you tell me which problem did you meet?
You must install a C++ compiler (GCC, G++), libpng-devel, libjpeg-devel, libtiff-devel and you will be ready to go.

**Comment by pmoulon** [comment]
@Patricus93 Any feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity.
