### ISSUE TITLE
Understanding where the SfM_Data Save function is located

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#786]
I am trying to understand the part where the data is being saved to the sfm_data.bin file. There is a function definition in sfm_data_io.hpp "bool Save(const SfM_Data & sfm_data, const std::string & filename, ESfM_Data flags_part);"
that handles the same. I am trying to access this, as I need to remove custom points of my choice from the structure points that are being saved in the bin file. Where is the implementation of this file? I searched the entire project repo but am turning up empty. Could you please point me to it. TIA.

**Comment by pmoulon** [comment]
You look for this function
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_io_cereal.cpp#L220

Please also note that you can use the main_ConvertSfMData binary (there is customizable output).

**Comment by naveenjafer** [comment]
This was really very convenient! Thank you!

**Comment by danielunifim55** [comment]
Hello @pmoulon! I am relatively new in C++ and I am working on a code to generate orthomosaics of aerial images taken by drone. I recently find openMVG and I am starting by using the code in main_SfMInit_ImageListing.cpp as a first part of the pipeline


. Nevertheless, I am getting an error of "application.exe stop working" when sfm_data.json is being created.

If I go to my output folder I find an empty json file. Would you mind to help me with this? I hope these images describe my problem. Thank you!![i1_prob](https://user-images.githubusercontent.com/9341801/44817217-63aef300-abaa-11e8-804b-6751056c4d3b.png)
![i2_prob](https://user-images.githubusercontent.com/9341801/44817218-63aef300-abaa-11e8-9d0e-f382179c8792.png)
