### ISSUE TITLE
Understanding the global reference coordinate system.

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#788]
This is not specifically related to any issue, its only to better my understanding.I am trying to understand a little bit more about the coordinate system for the structure computed at the end of Global SFM. Assuming the cameras perform an approximate planar motion around my object of interest in a 360 deg fashion. I am interested in understanding which of x,y,z axes would be approximately parallel to the axis of rotation of the cameras around my object of interest. After experimenting with a few different datasets, once it resulted in the X axis and once it was the Y. Does it always necessarily always have to be one of the primary axes? And is this orientation in the reference system a random process depending on the scenario?

**Comment by pmoulon** [comment]
Since the bundle adjustment in free to move the camera arbitrary the scene can be in a 'random' orientation depending of the scene you are using.

BTW, since your are moving in a planar motion you can compute a plane from the camera center position and rotate the scene to be in your coordinate system of your choice.

**Comment by naveenjafer** [comment]
Hi, I had one more query, the extrinsics of the camera that is generated in the file has the "center" of the camera pose with respect to the global reference system right? In accordance with the terminology used here http://ksimek.github.io/2012/08/22/extrinsic/ is the rotation the "Rc, the rotation matrix describing the camera's orientation with respect to the world coordinate"? Needed a confirmation once, do other tools like openMVS read the Camera extrinsics or do they read the camera pose and process further to generate the camera extrinsics by using the methods described in the link? Yeah the above comment helped :) Thank you.

**Comment by pmoulon** [comment]
The camera system is as you said, the camera center is storing the global world camera position, and the camera rotation ("is in the world coordinate too"), direction of looking of the camera.

Please be aware that OpenMVG provide a lot of exporter for many MVS solution, so it's really easy to use see all the main_OpenMVG2X like
 https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_openMVG2openMVS.cpp
