### ISSUE TITLE
"Invalid input image graph for global SfM" with heavily matched data set.

### ISSUE THREAD

**Issue by hheijnen** [openMVG/openMVG#789]
My matching graph looks as follows:

<img width="239" alt="screen shot 2017-02-18 at 21 52 50" src="https://cloud.githubusercontent.com/assets/7135626/23097142/ab1aa014-f624-11e6-923b-3be9d7ba9e54.png">

- It is made from 45 images with a lot of overlap. 
- Features extracted at ULTRA high AKAZE FLOAT.
- Matched to an essential matrix.
- Large matches database `-rw-rw-r-- 1 ubuntu ubuntu 123468977 Feb 18 21:21 matches.putative.bin`

Yet, when running 
`/opt/openMVG/bin/openMVG_main_GlobalSfM -i images/sfm_data.json -m matches/ -o model/` 
, I receive the error
`Invalid input image graph for global SfM`
and I am not sure what to do in order to avoid this. Can anyone see right away that I am doing something terribly wrong here?

**Comment by pmoulon** [comment]
Hi @hheijnen 
You are almost there.
Notice that yout have a file matches.f.bin, it consists of the putatives matches (matches.putative.bin) that have been filtered by robust **f**undamental matrices estimation.
Fundamental matrices estimation is the default behavior of ```main_ComputeMatches```

GlobalSfM requires the putative graph to be filtered by an essential matrix filter. To do so, just relaunch ```main_ComputeMatches``` and add ```-g e```.
It will produce the matches.e.bin file that ```openMVG_main_GlobalSfM``` is expecting.
And then, relaunch the GlobalSfM binary

Notice this fact for the ```-g X``` option:
- ```-g f``` => default bahavior => fundamental matrices
- ```-g e``` => essential matrices
- ```-g h``` => homography matrices (for planar scenes or rotating only motion ) => can produce nice matches if you photograph a wall from many viewpoint, or if you want to write an image panorama sticher

**Comment by hheijnen** [comment]
Thank you for the quick and kind response!

But, actually, that is what I did. And it created the file 
`-rw-rw-r-- 1 ubuntu ubuntu         9 Feb 18 21:21 matches.e.bin`

9 bytes though...

**Comment by pmoulon** [comment]
Since your essential graph is empty, I think it's because you have no valid intrinsic data that have been setup at the ```SfMInit_ImageListing``` stage.

Please open your sfm_data.json file and check for the field ```intrinsics``` it will certainly be empty in your case.
When you ran ```SfMInit_ImageListing```, the log displayed you some message , perhaps "camera not in database".

Here for example the ouput on https://github.com/openMVG/ImageDataset_SceauxCastle dataset:
```
SfMInit_ImageListing report:
listed #File(s): 13
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
```

You note that it says that there is one intrinsic that have been defined. Here one intrinsic have been defined and shared between the 11 images.

Note that if all your image have the same size, you can configure your intrinsic with a default starting pixel focal length by using the option -f X
X depicts the value of the focal length in pixels => like 1.1 * max(imageWidth, imageHeight)

Hoping it helps.
Don't hesitate to share your image dataset or your json file if you need more help.

**Comment by hheijnen** [comment]
Setting an estimate of the focal length when running the image listing did the trick! Thank you for your concern.

**Comment by pmoulon** [comment]
@hheijnen you're welcome.
Don't hesitate to share some reconstruction results here, on G+ with the openmvg hastag or in https://openmvg.slack.com

**Comment by fatolin** [comment]
Hi Pierre @pmoulon ;
I get the same error. I don't have a matched photo. Could this be the problem? 

> openMVG/aaa/matches/ -i aaa/matches/sfm_data.json -o aaa/matches/ -g e -f 1 -n ANNL2 -r .8
> You called :
> openMVG_main_ComputeMatches
> --input_file /home/terte/openMVG/aaa/matches/sfm_data.json
> --out_dir /home/terte/openMVG/aaa/matches/
> Optional parameters:
> --force 1
> --ratio 0.8
> --geometric_model e
> --video_mode_matching -1
> --pair_list /home/terte/openMVG/aaa/matches/
> --nearest_matching_method ANNL2
> --guided_matching 0
> --cache_size unlimited
> 
> Regions Loading -
> 0% 10 20 30 40 50 60 70 80 90 100%
> |----|----|----|----|----|----|----|----|----|----|
> PUTATIVE MATCHES -
> Use: user defined pairwise matching
> Using ANN_L2 matcher
> Using the OPENMP thread interface
> 
> Matching -
> 0% 10 20 30 40 50 60 70 80 90 100%
> |----|----|----|----|----|----|----|----|----|----|
> Task (Regions Matching) done in (s): 0
> 
> Geometric filtering -
> 0% 10 20 30 40 50 60 70 80 90 100%
> |----|----|----|----|----|----|----|----|----|----|
> Task done in (s): 0Export Adjacency Matrix of the pairwise's geometric matches 

```
terte@terte:~/openMVG$ openMVG_main_GlobalSfM -i /home/terte/openMVG/aaa/matches/sfm_data.json -m /home/terte/openMVG/aaa/matches/ -o /home/terte/openMVG/aaa/out_global

Features Loading -
0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|
CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0
Invalid input image graph for global SfM
```

**Comment by pmoulon** [comment]
@fatolin --pair_list should point to a txt file, not a folder `/home/terte/openMVG/aaa/matches/`
I think you try to use an existing pair list generated by you or an OpenMVG process.

**Comment by fatolin** [comment]
it started matching right now, thank you pierre @pmoulon . I will return to you once the matching process is finished.

**Comment by fatolin** [comment]
The matching process is done. I encountered a failure in the global SFM step. What's the reason? @pmoulon . Thank you for your concern.

> 
> Triplets filtering based on composition error on unit cycles
> #Triplets before: 1367
> #Triplets after: 1305
> 
>  #Edges removed by triplet inference: 15
> 
> CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 1
> Connected component of size: 138
> reorder_program.cc:146 Block ordering stats:  flops: 8334 lnz  : 1036 anz  : 817
> block_sparse_matrix.cc:80 Allocating values array with 97776 bytes.
> block_sparse_matrix.cc:80 Allocating values array with 9936 bytes.
> compressed_row_sparse_matrix.cc:169 # of rows: 414 # of columns: 414 max_num_nonzeros: 7353. Allocating 89896
> 
> CHOLMOD version 3.0.11, May 4, 2016: Symbolic Analysis: status: OK
>   Architecture: Linux
>     sizeof(int):      4
>     sizeof(SuiteSparse_long):  8
>     sizeof(void *):   8
>     sizeof(double):   8
>     sizeof(Int):      4 (CHOLMOD's basic integer)
>     sizeof(BLAS_INT): 4 (integer used in the BLAS)
>   Results from most recent analysis:
>     Cholesky flop count: 2.0436e+05
>     Nonzeros in L:       8856
>   memory blocks in use:           7
>   memory in use (MB):           0.0
>   peak memory usage (MB):       0.1
>   maxrank:    update/downdate rank:   8
>   supernodal control: 1 40 (supernodal if flops/lnz >= 40)
>   nmethods:   number of ordering methods to try: 1
>     method 0: natural
>         flop count: 2.0436e+05
>         nnz(L):     8856
>   OK
> block_sparse_matrix.cc:80 Allocating values array with 9936 bytes.
> block_sparse_matrix.cc:80 Allocating values array with 9936 bytes.
> block_sparse_matrix.cc:80 Allocating values array with 9936 bytes.
> block_sparse_matrix.cc:80 Allocating values array with 9936 bytes.
> Found #global_rotations: 138
> Timing: 0 seconds
> 
> Relative/Global degree rotations residual errors {0,109.394}:
> 0	|	684
> 5.47	|	0
> 10.9	|	0
> 16.4	|	0
> 21.9	|	0
> 27.3	|	0
> 32.8	|	0
> 38.3	|	1
> 43.8	|	0
> 49.2	|	0
> 54.7	|	0
> 60.2	|	0
> 65.6	|	0
> 71.1	|	0
> 76.6	|	0
> 82	|	0
> 87.5	|	0
> 93	|	1
> 98.5	|	0
> 104	|	7
> 109
> 
> 
> Relative/Global degree rotations residual errors {0,5}:
> 0	|	422
> 0.25	|	128
> 0.5	|	46
> 0.75	|	33
> 1	|	22
> 1.25	|	12
> 1.5	|	11
> 1.75	|	8
> 2	|	1
> 2.25	|	0
> 2.5	|	0
> 2.75	|	1
> 3	|	0
> 3.25	|	0
> 3.5	|	0
> 3.75	|	0
> 4	|	0
> 4.25	|	0
> 4.5	|	0
> 4.75	|	0
> 5
> 
> 
> Statistics about global rotation evaluation:
> 
> 	 min: 0.000523571
> 	 mean: 1.77786
> 	 median: 0.179553
> 	 max: 109.394
> 
> -------------------------------
>  Relative translations computation: 
> -------------------------------
> #Triplets: 1703
> 
> Relative translations computation (edge coverage algorithm)
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> TRIPLET COVERAGE TIMING:
> -------------------------------
> -- #Relative triplet of translations estimates: 0 computed from 1703 triplets.
> -- resulting in 0 translations estimation.
> -- time to compute triplets of relative translations: 174 seconds.
> -------------------------------
> 
> CleanGraph_KeepLargestBiEdge_Nodes():: => connected Component: 0
> 
> -------------------------------
>  Global translations computation: 
>    - Ready to compute 0 global translations.
>      from #relative translations: 0
> GlobalSfM:: Translation Averaging failure!
