### ISSUE TITLE
Incorrect match from camera database

### ISSUE THREAD

**Issue by john-davies** [openMVG/openMVG#794]
I'm getting an incorrect match from the camera database even though my camera is present. Putting some temporary debug in main_SfMInit_ImageListing.cpp:

```
      // Create the image entry in the list file
      {
        Datasheet datasheet;
        if ( getInfo( sCamModel, vec_database, datasheet ))
        {
          // The camera model was found in the database so we can compute it's approximated focal length
          const double ccdw = datasheet.sensorSize_;
          focal = std::max ( width, height ) * exifReader->getFocal() / ccdw;

std::cout << "Exif camera type: " << sCamModel << "\n";
std::cout << "Database camera type: " << datasheet.model_ << ", Sensor size: " << datasheet.sensorSize_ << "\n";
std::cout << "Width: " << width << ", Height: " << height << ", Focal length: " << exifReader->getFocal() << "\n";
std::cout << "Focal length ( pixels ): " << focal << "\n";

        }
        else
        {
          error_report_stream
            << stlplus::basename_part(sImageFilename)
            << "\" model \"" << sCamModel << "\" doesn't exist in the database" << "\n"
            << "Please consider add your camera model and sensor width in the database." << "\n";
        }
      }
```
then I get:

```
Exif camera type: Canon DIGITAL IXUS 70
Database camera type: Canon EOS 700D, Sensor size: 22.3
Width: 3072, Height: 2304, Focal length: 5.8
Focal length ( pixels ): 798.996
```
i.e. my IXUS 70 is being reported as a 700D ( yeah, I wish! )
I think that the problem is in the following function in database.hpp:

`bool operator==(const Datasheet& rhs) const`

in these lines:

```
          // Check that substring containing the camera digit model is corresponding
          if (sub_has_digit && this_model.find(rhs_sub_model) != std::string::npos)
          {
            return true; // substring that contains digit got a match
          }
```
Here the "70" digit substring extracted from "Canon DIGITAL IXUS 70" is being found in "Canon EOS 700D" thus matching the wrong camera type.

I think that the substring containing the digit model needs to be extracted from both strings and compared rather than just checking if the "rhs_sub_model" digit string is present in the "this_model" string.

For the moment I've worked around the issue by creating a custom "sensor_width_camera_database.txt" file with just my two cameras in it.

If you think that my suggestion to fix is OK then I'll try creating a pull request.

**Comment by pmoulon** [comment]
Hi @john-davies 
Thank you for the bug report.
I think we must add your camera type to the unit test and fix it:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/ParseDatabase_test.cpp

Feel free to make a PR to the develop branch.
Please also be aware that the digit thing was introduced to this purpose https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/datasheet.hpp#L37 but we can perhaps greatly simplify the code and let the users update the database if there is not a perfect match.

**Comment by john-davies** [comment]
Thanks, the comment about the digits was useful. I have created a pull request with the fix and two extra test cases.

As regards cameras missing from the database then what about adding an extra command line option to openMVG_main_SfMInit_ImageListing where the user could specify the sensor width rather than having to update the database?

**Comment by pmoulon** [comment]
@john-davies We can imagine plenty of scenario. The hard part is if you have a dataset with multiple camera type and so you want to specify various sensor_width. Perhaps we could imagine a interactive mode that ask the sensor_size to the user... or have a default fallback that will initialize a default "approximate" focal length.

**Comment by john-davies** [comment]
OK, thanks. Some suggestions:

### Add a command line option to specify camera sensor width

For example: --sensor-width "Nikon D3100;23.1"

It should be possible to add several "--sensor-width ..." options to cope with the case where the dataset has multiple camera types

### Add a command line option for an interactive mode

- If this option is set and one or more cameras are not found in the database then the user is prompted to supply the sensor width
- if the option is not set and one or more cameras are not found in the database then an approximate focal length is used ( note that I am not sure how this would be calculated )

### Priority order 

I suggest that the following priority order is used for selecting the sensor width:

1. Command line option "--sensor-width"

2. sensor_width_camera_database.txt file

3. User entered / approximate focal length

**Comment by pmoulon** [comment]
@john-davies  Sorry for my late answer 

Can you please open a new Issue with your last comment?

- I will close the issue, since the problem have been fixed by https://github.com/openMVG/openMVG/commit/3381472959cf4ac3d8af7ba71c1935710dda4b84
