### ISSUE TITLE
What should I do to investigate on the crash of openMVG_main_ComputeStructureFromKnownPoses installed today?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#796]
Hello Pierre,

I launched global sfm and the program "openMVG_main_ComputeStructureFromKnownPoses" stopped. All the other program before and after seem to run correctly.

I installed it today on a windows 8.1 with visual studio 15 on i5 Xeon. I get the code from with followings command:

- git clone https://github.com/openMVG/openMVG.git
- git submodule update -i
- git checkout -b develop remotes/origin/develop
- git submodule init
- git submodule update

What should i do to investigate on the problem ?

I installed 2 weeks ago, using the same process, OpenMVG on my laptop(i7), on the same dataset and it works perfectly.

Thank you

**Comment by alvaro562003** [comment]
Hi,
This morning i copy the code compile on i5 in my laptop(i7) there is the same crash.

**Comment by alvaro562003** [comment]
To clarify my question. Is there a mode verbose or trace ?

**Comment by rperrot** [comment]
unfortunately openMVG don't provide such tool. You have to use the debugger of VS (having compiled in DEBUG mode)

Is you scene correctly computed ? (the colonized.ply is correct) Is you dataset large (a memory issue ?). Is it possible to share the dataset to make some tests on our environment ? 

Note : you can clone the repository and switch to the develop branch in one line : 
```
git clone --recursive https://github.com/openMVG/openMVG.git -b develop 
```

**Comment by pmoulon** [comment]
As @rperrot said, I'm afraid that you must go to the debugging step :-(

Please note also that the step openMVG_main_ComputeStructureFromKnownPoses, is an optional step. You can already rely on the result of the SfM pipeline (Incremental or Global) and use the produced sfm_data.bin for third party usage.

ComputeStructureFromKnownPoses is a binary that shows how to estimate the structure and the image matches that best fit the camera geometry (the known input camera poses).

As @rperrot, don't hesitate to share data in order to help us to understand what is going on.

**Comment by alvaro562003** [comment]
Hello,
Thank you for you reply. Indeed i noticed that the step was optional as the program continues despite the crash.
I Create a debug version of OpenMVG. "Unfortunately" the debug version does not crash.
The Non debug version crash after these screen message:
 
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 11
 #poses: 10
 #intrinsics: 1
 #tracks: 0

Compute frustum intersection
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*******************************************

Is the problem coming from #tracks = 0 ?
Regards

**Comment by alvaro562003** [comment]
By the way, the dataset is "Sceaux castle"...not so big
The computer has 12.5GB of 16GB of memory available

**Comment by alvaro562003** [comment]
The colorized file has 2357 points and seems to be correct.

**Comment by alvaro562003** [comment]
how to i set OMP_NUM_THREADS to 1.
in the Cmake for ALL programs or there is a "chirurgical" way  ?

**Comment by pmoulon** [comment]
in the command line before running your binary.
Or add ```omp_set_num_threads(1);``` in the c++ code of the binary "openMVG_main_ComputeStructureFromKnownPoses"

Just an additional question, does running openMVG_main_ComputeStructureFromKnownPoses is compulsory for you or not? (I mean it's only an option to run and use its output). The scene camera position will not change, so it does not really impact much the following dense multiple view stereo you can do later on

**Comment by alvaro562003** [comment]
it means openMVG_main_ComputeStructureFromKnownPoses gives not extra precision on the dense reconstruction. right

**Comment by pmoulon** [comment]
It does not by default.
It can if the option [-b|--bundle_adjustment] is turn to on.

This binary is more used in the case where you have precise known camera position but unknown image correspondences. So in the Python SfM pipelines it is used more to demonstrate how to use it it rather than improving the accuracy.

**Comment by alvaro562003** [comment]
in the dos windows i type set OMP_NUM_THREADS=1.
Check with  echo %OMP_NUM_THREADS% --->1
and then launch the script

---->> still the same crash

**Comment by alvaro562003** [comment]
i use the command :
    pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BINDEBUG , "openMVG_main_ComputeStructureFromKnownPoses"),  "-i", os.path.join(reconstruction_dir , "sfm_data.bin"), "-m", matches_dir, "-o", os.path.join(reconstruction_dir,"robust.ply"), "-b"] )

**Comment by alvaro562003** [comment]
with or without "-b" ...still crash

**Comment by alvaro562003** [comment]
The part of code provoking the crash is:
 if (sMatchFile.empty() && sPairFile.empty())
  {
	  // no provided pair, use camera frustum intersection
    pairs = BuildPairsFromFrustumsIntersections(sfm_data);   <-----inside
  }

**Comment by alvaro562003** [comment]
deeper inside it is in the file sfm_data_filter_frustum.cpp
objects.back() = frustum_perView.at(viewIds[j]);

**Comment by pmoulon** [comment]
Thank for the deeper look, seems like I try to get a frustum for a non existing view.
In your case you have a image that have not pose
```
#views: 11
#poses: 10
```
Can you share me your sfm_data.bin file?

**Comment by pmoulon** [comment]
@bchretien seems like in case of missing view we can have a bug ;-)

**Comment by alvaro562003** [comment]
I will do it tomorrow morning.
Cheers

**Comment by alvaro562003** [comment]
Hi there,
This morning i try one time withhout crash. The second time i reproduced the problem. The enclosure is the zip of sfm_data.bin.

The 1st time i installed and used OpenMVG it was on February 9th. There was not this problem on the early Feb version.
So it could be eventually a regression that happened between 9th feb and 20th feb.
Good luck
[sfm_data.zip](https://github.com/openMVG/openMVG/files/795742/sfm_data.zip)

**Comment by pmoulon** [comment]
Thank you,
I tried on Linux with your file and everything is running fine:

```openMVG_main_ComputeStructureFromKnownPoses -i path/sfm_data.bin -m path/matches/ -o path/toto.bin```
![snapshot00](https://cloud.githubusercontent.com/assets/3235050/23249074/c7faf112-f9a2-11e6-93d9-a53e67930418.png)
[Result_ComputeStructureFromKnownPoses.zip](https://github.com/openMVG/openMVG/files/795784/Result_ComputeStructureFromKnownPoses.zip)

Will try to test on visual studio next week

**Comment by alvaro562003** [comment]
I take from my laptop that i download on th 9th of Feb to compile in the same condition on ec2 as the version of the 20th feb. There is the same problem.

So it is not the question of regression i forementionned. 
Sorry for the misleading info.

**Comment by alvaro562003** [comment]
FYI, I am using the following configuration of aws/ec2 server:

1. Microsoft Windows Server 2012 R2 Base
2. g2.large (8cpu)
3. visual studio 2015

**Comment by bchretien** [comment]
@pmoulon I see, we'll need to add this case to the test suite then.

**Comment by pmoulon** [comment]
@alvaro562003 I just saw that the scene you send me have 11 valid poses, but the scene on which you have a problem seems to have only 10 valid poses.
Can you double check you gave me the right sfm_data.bin file?

Please be sure that you gave me the sfm_data.bin file from your aws instance on which you saw the problem.

**Comment by alvaro562003** [comment]
Hello,
In the zip there are 2 sfm_bin. I hope it will be helpful.
[sfm_data.zip](https://github.com/openMVG/openMVG/files/797311/sfm_data.zip)

**Comment by alvaro562003** [comment]
In the version compiled this morning when executing the code on ec2 i can not reproduce the crash.
Despites my efforts, I tried it 10 times at least.

In the early version,  i can still reproduced the crash.

On my (i7)laptop executing the code of the (i5)Ec2 i can easily reproduced the crash. Enclosed are the sfm_data.bin of 2 crashes 

[sfm_data_bin_on_i7Laptop.zip](https://github.com/openMVG/openMVG/files/797384/sfm_data_bin_on_i7Laptop.zip)

**Comment by pmoulon** [comment]
I tried on Linux the two scenes you gave me and everything went running smoothly.
I will try on VS soon.

**Comment by alvaro562003** [comment]
thanks

**Comment by pmoulon** [comment]
Did not found the time to test on a windows machine?
I advise you to stop at Incremental or Global SfM stage during this time.
