### ISSUE TITLE
How to do SFM if I just know some landmarks on facial images?

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#800]
For example if I have 6 landmarks (eye corner ,mouth corners ... )on each images
The SIFT feature detection and matching can't work for facial images. But We can use other libs to detect facial landmarks. How to use mvg to do SFM and then 3d reconstruction?

Can I only use bundle adjustment without any initialization of 3d points and camera poses to do SFM? OpenMVG is hard to use to me.

**Comment by rperrot** [comment]
I fink 6 landmarks is really too low for correct 3d reconstruction. 

You may use the standard pipelines (python files located in build/software/SfM/) to do the whole SfM pipeline.

**Comment by pmoulon** [comment]
Please use the thread #799 for your question and state there your question.

>How to use mvg to do 3d reconstruction
See the documentation: https://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

> OpenMVG is hard to use to me
The community is here to help you.

Note that SfM require to compute geometric constraint between images. Those estimation requires point correspondences, and often 6 point is a bit small. The main reason is that when we estimate a model the minimal solver requires 5/7/8 points. Then we need to check the validity of the geometric model on some other points to ensure its validity.

**Comment by pmoulon** [comment]
@wguo68 Any feedback?

**Comment by wguo68** [comment]
Thank you. If there are more internal landmarks on a face and a few face frontal images. Is it okay. I don't know how to do this suppose I have detected the landmarks using other librarys.

**Comment by pmoulon** [comment]
You have an explanation here about the file format:
