### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#804]
./openMVG_main_SfMInit_ImageListing -d /home/d/dev/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt -i //home/d/usr/OpenMVG_yang/images -o /home/d/usr/OpenMVG_yang/matches
 You called : 
./openMVG_main_SfMInit_ImageListing
--imageDirectory //home/d/usr/OpenMVG_yang/images
--sensorWidthDatabase /home/d/dev/openMVG/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/d/usr/OpenMVG_yang/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

SfMInit_ImageListing report:
listed #File(s): 0
usable #File(s) listed in sfm_data: 0
usable #Intrinsic(s) listed in sfm_data: 0
d@d-System-Product-Name:~/dev/openMVG/openMVG_Build/Linux-x86_64-RELEASE$

**Comment by rjanvier** [comment]
Hi.
Maybe the output of `ls /home/d/usr/OpenMVG_yang/images` could help us.
Thanks.

**Comment by wguo68** [comment]
yes. I forget to pu image to the dir.

**Comment by rjanvier** [comment]
Fine! Could you please close the issue?

**Comment by wguo68** [comment]
how to close? thanks
