### ISSUE TITLE
"There is no defined intrinsic data in order to ..." solved

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#805]
I execute this command : ./openMVG_main_IncrementalSfM -i /home/d/usr/OpenMVG_yang/matches/sfm_data.json -m /home/d/usr/OpenMVG_yang/matches/ -o /home/d/usr/OpenMVG_yang/out_Incremental_Reconstruction/

What is the problem?

-- Tracks Stats --
 Tracks number: 801
 Images Id: 
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 
------------------
TrackLength, Occurrence
	2	518
	3	139
	4	73
	5	29
	6	15
	7	15
	8	9
	9	1
	13	2

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.

**Comment by rjanvier** [comment]
Could you please give me the output of  your `./openMVG_main_SfMInit_ImageListing`

**Comment by wguo68** [comment]
I fixed this problem by give a focal length -f 586.3 .Thanks.

**Comment by rjanvier** [comment]
Please open another issue and do not change the title next Time. Thank you.
