### ISSUE TITLE
how to use calibrated cameras to achieve a point cloud? no feature descriptor involved

### ISSUE THREAD

**Issue by Zenguang** [openMVG/openMVG#808]
Hi guys
  I am dealing with indoor 3d reconstruction and glad to have this openMVG lib.My problem is that it is possible to only use geometric matches (like F matrix , epipolar constraint) to get correspondences in pipeline of sfm,without photometric matches(like SIFT match) correspondences.
  Since i have well calibrated two cameras in Matlab Stereo Camera Calibrator toolbox,individual intrinsic Matrix and [R|T] relation between them are available now.
  what i am supposed to do next with openMVG libs? any suggestions plz. 

Thanks in advance.

Zeng

**Comment by rperrot** [comment]
I don't understand your sentence : 

"that it is possible to only use geometric matches (like F matrix , epipolar constraint) to get correspondences in pipeline of sfm,without photometric matches(like SIFT match) correspondences." 

openMVG uses SIFT by default to get correspondences.

**Comment by Zenguang** [comment]
hi rperrot:
sorry for your confusion . I mean there are 2 ways that we can locate correspondences between a pair of stereo images：
1. Mentioned in openmvg，features(SIFT descriptor) can be detected and the optimization algorithm(RANSAC) is used to refine the matching results，i refer this way as photometric matches；  
2. In the MVG bible，this correspondence can also be found with the help of  F matrix or epipolar constraint. so i refer this way as geometric matches；  
now i “have to” use geometric matches and choose OPENMVG to implement it. HOWEVER the openMVG uses first solution. what should i do now with openmvg code？

**Comment by pmoulon** [comment]
@Zenguang 
Can you tell me if you want to do single stereo reconstruction or you want to do SfM with multiple pose of your stereo vision camera?

From my understanding you refer the matching step as the following:
1. **For a scene with unknown geometry** => From the image your compute the SIFT keypoints, match them to obtain the photometric matches then you filter them by performing a robust model estimation. The model can be one of these  Homography, Fundamental,Essential matrix. So at the end you have "geometric coherent matches".

2. **For a scene with known geometry** => You can perform what I call guided matching, I mean use the relative pose to compute a fundamental matrix and keep only the meaningful correspondences that fit inside the epipolar line neighborhood. Correspondences can be either sparse of dense. For the sparse case you use SIFT or any other feature detection and descriptor framework, for the dense method often, images are stereo rectified and then dense matching is computed (OpenMVG does not implement the later).

See here for rectification http://www.ipol.im/pub/art/2011/m_qer/
Global matching for stereo vision http://dev.ipol.im/~facciolo/mgm/

You will find here a sample that illustrate all of these matching methods:
https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_fundamental_guided/robust_fundamental_guided.cpp

**Comment by pmoulon** [comment]
@Zenguang Any feedback?

**Comment by pmoulon** [comment]
Closed due to inactivity
