### ISSUE TITLE
How can I resize a larger image to the small one?

### ISSUE THREAD

**Issue by haopo2005** [openMVG/openMVG#809]
Hi,
How can I resize  larger images to the small one?
I think the function openmvg::image::resize  cant make image smaller. It's different from opencv's resize.

**Comment by pmoulon** [comment]
image::resize resize only the container.
If you want to resize the pixel content you have to use image::GenericRessample or iamge::Warp

**Comment by pmoulon** [comment]
@haopo2005 Any feedback?

**Comment by haopo2005** [comment]
Sorry for delay,
thanks again.
