### ISSUE TITLE
OpenMVG Pipe Line & Reconstruction using image sequence

### ISSUE THREAD

**Issue by ghost** [openMVG/openMVG#81]
I check the online documentation about the pipe line and samples.
I am still confused.
Do you know how can I create a 3D model from a sequence of images(more than 2) using openMVG?

Best regards,
Tyler

**Comment by fansays** [comment]
@pmoulon Thank you for your detailed answer. I'm a tiro in this field so I want to ask if there's any 3d reconstruction sample (C++) using OpenMVG as a reference?

**Comment by pmoulon** [comment]
@fansays OpenMVG is made in C++.
There is some Python scripts that just allow to launch more easily the command line tools.
It's more easy to use first the provided python scripts for which you just have to specify an input image dir and an output dir.
Once you master that you can play and have more control on the pipeline by using directly the binaries.
