### ISSUE TITLE
openMVG2openMVS fails silently if output cannot be written

### ISSUE THREAD

**Issue by mardy** [openMVG/openMVG#810]
If the openMVG2openMVS tool is given a directory as output (or `directory/file.mvs` where `directory` does not exist) the conversion starts and apparently proceeds normally, but no file gets created.

I would suggest that the tool should create any missing subdirectories and in any case fail immediately if the output file cannot be written.

**Comment by rperrot** [comment]
That's an interesting idea. You said that is fails silently ? (@pmoulon at least we should say that the .mvs file could not be created)

Perhaps a first solution is to look if directory exists then prompt the user for an action ?

**Comment by pmoulon** [comment]
Yep often I check the validity of input arguments but it seems there I forgot ;-)

**Comment by silenceofcode** [comment]
hello   when i do DensifyPointCloud in OPENMVS , it always dispaly unknow image format.what should i do ?just as

**Comment by pmoulon** [comment]
Seens related to OPENMVS and not OpenMVG.
Can you check that you can read the exported images thanks to your system image viewer?

**Comment by pmoulon** [comment]
Failure is now handled: https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_openMVG2openMVS.cpp#L43
