### ISSUE TITLE
Obtaining covariance of pose estimates

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#811]
Is it possible to obtain the pose covariance data from the different kinds of estimations that are performed, such as from the Ceres solver that does multi-view pose estimation for SfM, and the P3P solver (which eventually uses Ceres for BA) that's being used in image localization against a given map etc.? Thank you!

**Comment by pmoulon** [comment]
1. You can modify the OpenMVG bundle adjustment ceres interface to compute the covariance and output it. The covariance computation is not done yet, but it should be relatively easy to implement. Feel free to contribute on it. See http://ceres-solver.org/nnls_solving.html?highlight=covariance#covariance-estimation

**Comment by saihv** [comment]
@pmoulon, thanks for the link! I am working on trying to implement it. Closing this question for now.
