### ISSUE TITLE
DNL not supported Error 

### ISSUE THREAD

**Issue by resindraburiza** [openMVG/openMVG#812]
I have a dataset that when try to export it to openMVS, it give Empty "JPEG image (DNL not supported)" error. Some of the image in the database was not used for the reconstruction as shown in SFM report (72 poses from 182 images). What is actually this error about? Could it be the one cause it? 
And also when I try to export it to CMPMVS format, it gave no error but the CMPMVS folder created by it only give the .ini file. Inside the .ini file, it says that the number of images is zero. Why is it so?
Thank you very much.

**Comment by pmoulon** [comment]
@resindraburiza 
Can you check that all your input images are valid?
This type of message "DNL" seems to appear when you try to read an invalid JPEG file.

Regarding the openMVG2CMPMVS, I think about the same thing, please check that you have used as input a valid sfm_data.bin file that contains some valid camera poses. Seems like you have used a pose empty sfm_data file since there is no exported images.

**Comment by resindraburiza** [comment]
Thank you very much for your answer. I've gone through every of my images file one by one and all of my images is valid. Actually I've also try other SfM software using the same images and the other software did not have any error with my images. 

About the openMVG2CMPMVS, in [here ](https://openmvg.readthedocs.io/en/latest/software/MVS/CMPMVS/) it says the input must be sfm_data.json. When I use sfm_data.bin, the DNL error will appear again.  Is there maybe any file should I attach to give you more insight? Thank you very much.

**Comment by pmoulon** [comment]
If the SfM process ran fine, images should be exported.
May I ask you to share to me your image dataset and your sfm_data.bin to me on openmvg-team[AT]googlegroups.com?

Can you tell me:
- on which platform do you run OpenMVG?
- which branch are you using (master/develop)?
- did you compiled and ran all the unit test ok?

**Comment by resindraburiza** [comment]
I finally figured out the problem. It because the images I am using is only 1 dimension of depth where the usual RGB images have 3 dimension of depth (I use only G channel in my application). Because of this, the DNL error appears.
