### ISSUE TITLE
Building failiure on VS2013

### ISSUE THREAD

**Issue by billy-antoine** [openMVG/openMVG#813]
Hi,

First of all congratulation for your amazing work. 
I would like to use openMVG in order to compare its SfM results with the one available in openCV.
However, I can't manage to build it...

I used CMake-GUI to generate the project files and **Visual Studio 2013** to build the libs.
When I open the generated solution and build the ALL_BUILD project (with **Release** as compilation mode and as **Administrator**) I get three main errors. The first one comes from metric_hamming.hpp:

`Erreur	1377	error C2061: erreur de syntaxe : identificateur 'uint64_t' C:\openmvg\openMVG\src\openMVG\matching\metric_hamming.hpp	91	1	openMVG_sample_image_matching
`

The second one seems to be from Cameras_Common_command_line_helper.hpp:

`Erreur	692	error C2676: '|' binaire : 'openMVG::cameras::Intrinsic_Parameter_Type' ne définit pas cet opérateur ou une conversion vers un type acceptable pour l'opérateur prédéfini	C:\openmvg\openMVG\src\openMVG\cameras\Cameras_Common_command_line_helper.hpp	44	1	openMVG_main_GlobalSfM
`
And The last one tells me that it can not find some libs:

`Erreur	330	error LNK1181: impossible d'ouvrir le fichier en entrée '..\..\Windows-AMD64-\Release\openMVG_sfm.lib'	C:\openmvg\openMVG\build\software\SfM\LINK	openMVG_main_ComputeSfM_DataColor
`

Finally, 42 projects have failed to be correctly generated (31 managed to make it).
Could someone help me ..?

Thanks,

**Comment by pmoulon** [comment]
Hi @billy-antoine 

1. As you will see [here](https://github.com/openMVG/openMVG/blob/master/BUILD#L23) VS2015 is required to build OpenMVG. So if you can please install and use VS2015.

2. If you cannot install VS2015, you can use an OpenMVG fork that have a VS2013 compatibility [here](https://github.com/modriplanetdoo/openMVG/tree/dev-geo). This Fork should be close to OpenMVG v1.1.

Please tell me how the compilation goes once you have chosen the solution 1 or 2.
Looking forward to guide you, once OpenMVG will be compiled ;-)

**Comment by billy-antoine** [comment]
Hi @pmoulon,

I had the same problems with the given fork, so I installed VS2015 and get the following errors list:

![image](https://cloud.githubusercontent.com/assets/14361230/23648414/e8d6c1a0-031a-11e7-96c6-b34273a925d0.png)

Here are the libs generated in the Release directory:

![image](https://cloud.githubusercontent.com/assets/14361230/23650233/b2df37c4-0321-11e7-9a74-1164739d8c16.png)

As you can see, the main ones are missing. Did I do something wrong ?

Thank you for your answer,

**Comment by billy-antoine** [comment]
Hi @pmoulon ,
Thank you for your answer, I did not notice the version requirements... Unfortunately it seems that I have the same issues with the given fork. 
I will try to get VS2015 and build it again. I won't hesitate to ask for your help if needed, thank you !

**Comment by billy-antoine** [comment]
It works ! Merci beaucoup ;)
