### ISSUE TITLE
Build errors when tried to install the latest openMVG

### ISSUE THREAD

**Issue by anup-mohan** [openMVG/openMVG#815]
Hi,

I am following the build instruction for OpenMVG in Windows. CMAKE runs successfully for me, but when I try to build the solution in Visual Studio, I get the following error:

Error	C2899	typename cannot be used outside a template declaration	openMVG_matching_image_collection	Camera_Common.hpp	98

The same error exists for projects other than openMVG_matching_image_collection.

Kindly help in resolving this issue.

Thanks

**Comment by pmoulon** [comment]
Hi,
Which Visual Studio version are you using?

**Comment by anup-mohan** [comment]
Thanks for the quick response.

I am using the following version:

Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL

Thanks

**Comment by pmoulon** [comment]
Try to remove the typename keyword on line 98,99,106,107 and it should be ok.
This is strange, since the build on the Visual Studio CI is ok. (see https://ci.appveyor.com/project/pmoulon/openmvg/history)

**Comment by anup-mohan** [comment]
Hi,

The "typename" error went away, thanks. But I get the following unresolved external symbol errors:

LNK2019	unresolved external symbol __iob_func referenced in function output_message	openMVG_main_ColHarmonize
LNK2019	unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f	openMVG_main_ColHarmonize
LNK2019	unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f	openMVG_main_ColHarmonize
LNK2019	unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler	openMVG_main_ColHarmonize
LNK2019	unresolved external symbol __imp___iob_func referenced in function unixWarningHandler	openMVG_main_ColHarmonize

The same error is repeated for different functions.

Kindly help in resolving the issue.

Thanks
Anup

**Comment by pmoulon** [comment]
Here it a link error now.
It seems to comes from the TIFF library.
Did you use the provided internal TIFF library or did you specify your own?

**Comment by anup-mohan** [comment]
I believe I am using the provided internal TIFF library, as I didn't specify any library during the installation process.

Thanks

**Comment by pmoulon** [comment]
Can you check if you have ```-- LIBTIFF: (internal)``` written in your cmake config log?

**Comment by anup-mohan** [comment]
Hi,

Thanks for the tip on the TIFF library. Apparently, OpenMVG was using the libraries from Anaconda installed in my computer. Once I removed Anaconda, everything works fine, even the typename issue is resolved.

Thanks for your help.

**Comment by pmoulon** [comment]
Since the problem was identified:

- useless typename keyword in C++11 for a specific part
- TIFF (use a invalid external TIFF library) and a solution was found (force to use the internal TIFF library).

Please, can you close the issue?
