### ISSUE TITLE
How to compute the euler angle from openMVG_sample_multiview_robustEssential_spherical

### ISSUE THREAD

**Issue by haopo2005** [openMVG/openMVG#816]
Hi,
I'd like to compute the euler angle from openMVG_sample_multiview_robustEssential_spherical.
For now, I have got the essential matrix between spherical panorama successfully.
Can anyone help me to confirm the following manner to compute the euler angle yaw,pitch and roll?

1.
call  
`openMVG::MotionFromEssential(E, &Rs, &ts) `
to get the rotation matrix

2.
I think the openmvg follows the xzy coordinate order. 
openMVG::Vec3 MultipleViewReconstruction::RotationToEulerAngles(const openMVG::Mat3& rotation)
{
    float roll, pitch, yaw;
	if(rotation(0,1) < 1.0)
	{
	    if(rotation(1,1) > -1.0)
	    {
	        LOGD("case one");
	        yaw = asin(-rotation(0,1));//z
			roll = atan2(rotation(2,1), rotation(1,1));//x
			pitch = atan2(rotation(0,2), rotation(0,0));//y
	    }else
	    {
	        LOGD("case two");
	        yaw = M_PI/2;
			roll = -atan2(-rotation(2,0), rotation(2,2));
			pitch = 0;
	    }
	}else
	{
	     LOGD("case three");
	     yaw = -M_PI/2;
		 roll = atan2(-rotation(2,0), rotation(2,2));
		 pitch = 0;
	}
	return openMVG::Vec3(yaw, pitch, roll);
}
yaw  corresponds to the z axis, ranges from -PI/2 to PI/2
roll corresponds to the x axis, ranges from -PI to PI
pitch corresponds to the y axis, ranges from -PI to PI

And the following pdf is the algorithm to compute the euler angle
[EulerAngles.pdf](https://github.com/openMVG/openMVG/files/830864/EulerAngles.pdf)

**Comment by pmoulon** [comment]
What about using the exiting function ``` Vec3 euler_angles = rot.eulerAngles(0, 1, 2);``` of Eigen that must do the job
https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#gac3d90b12b21e1aaa2a9de9b0e45e6b7c

**Comment by haopo2005** [comment]
The Eigen function may be good, but each of the three parameters 0,1,2 represents the respective rotation axis x,y,z. For now, which integer order I should follow?
If openmvg follows the xzy coordinate order, then it's 0,2,1
If openmvg follows the xyz coordinate order, then it's 0,1,2

**Comment by pmoulon** [comment]
OpenMVG by default will have Y up.
After you have to choose the axis according your convention.

**Comment by haopo2005** [comment]
thanks, I thinks it's zyx.
![Uploading coor.png…]()
