### ISSUE TITLE
Input Directory

### ISSUE THREAD

**Issue by Stav2se** [openMVG/openMVG#817]
Hi @pmoulon, I start trying the openMVG with git bash but it comes with a small error when I try to run the Image Listing. Please see below:
```
_**_$ openMVG_main_SfMInit_ImageListing -d c/"Program Files"/openMVG/share/openMVG/sensor_width_camera_database.txt -i c/Users/stouse/Desktop/Estnor2_Rev5 -o c/Users/stouse/Desktop/Eastnor_OpenMVG
 You called :
C:\Program Files\openMVG\bin\openMVG_main_SfMInit_ImageListing.exe
--imageDirectory c/Users/stouse/Desktop/Estnor2_Rev5
--sensorWidthDatabase c/Program Files/openMVG/share/openMVG/sensor_width_camera_database.txt
--outputDirectory c/Users/stouse/Desktop/Eastnor_OpenMVG
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

The input directory doesn't exist_**_
```
By using the python pypeline it worked fine and created the matches, but when I try to run it from the command line comes with the above error. What step am I missing?

Many thanks, Stavros

**Comment by pmoulon** [comment]
Did you try to do the following to check if your path is correct?
```
ls c/Users/stouse/Desktop/Estnor2_Rev5
```

**Comment by Stav2se** [comment]
I just did and it seems the path to be fine. I have added the following as a path: PATH="$PATH;C:\Program Files\openMVG\bin"
Is that correct?

**Comment by rperrot** [comment]
The issue is not relative to the bin part but to the input/output directory : 

c/Users/stouse/Desktop/Estnor2_Rev5

it seems that there's a missing ":" (i.e. c:\ instead of c/)

**Comment by pmoulon** [comment]
@Stav2se Does your problem is now solved?

**Comment by Stav2se** [comment]
Hi @pmoulon, sorry for the late reply. I will test it shortly and come back to you.

**Comment by Stav2se** [comment]
Hi @pmoulon, this time it doesn't come with any error anymore but every time I enter the command it comes with > instead of $ and it looks like is doing something but no process is coming up. Sorry for being so useless with it :(

**Comment by pmoulon** [comment]
If you have a > it because it think that your command line is not complete and have not launch the app. I and @rperrot  advise you to use the python script so it will be easier to use.

**Comment by Stav2se** [comment]
Hi @pmoulon that helped but still came up with a error at the end.

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.

The input SfM_Data file "C:/Users/stouse/Desktop/Eastnor_OpenMVG\reconstruction_sequential/sfm_data.bin" cann                                                ot be read.
Compute Structure from the provided poses

The input SfM_Data file "C:/Users/stouse/Desktop/Eastnor_OpenMVG\reconstruction_sequential/sfm_data.bin" cann                                                ot be read.

The input SfM_Data file "C:/Users/stouse/Desktop/Eastnor_OpenMVG\reconstruction_sequential/robust.bin" cannot                                                 be read.
('Using input dir  : ', 'C:/Users/stouse/Desktop/Estnor2_Rev5')
('      output_dir : ', 'C:/Users/stouse/Desktop/Eastnor_OpenMVG')
1. Intrinsics analysis
2. Compute features
3. Compute matches
4. Do Sequential/Incremental reconstruction
5. Colorize Structure
6. Structure from Known Poses (robust triangulation)

**Comment by pmoulon** [comment]
Since a focal is not configured by OpenMVG for your image dataset you can force a default approximate focal value by adding the option `-f max(w,h)*1.1`

So look to your image size, compute the approximate focal length and modify the python script to add the `,"-f", "YOUR VALUE"` to the command line with SfMInit_ImageListing.

**Comment by Stav2se** [comment]
Hi @pmoulon, I think everything is now complete. What are the next steps to export into meshlab? or which is the main mesh file? Thank you in advance :)

**Comment by pmoulon** [comment]
The meshlab export will only show you the camera position and the point cloud.
If you want to compute a dense output (point cloud or mesh you have to use 3rd party projects, OpenMVG provider exporter for various projects).

See here https://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

**Comment by pmoulon** [comment]
You can open the produced point clouds in Meshlab to see the camera path and the structure. Look for some PLY files in the output folder (you can open them in Meshlab).
