### ISSUE TITLE
openMVG compute features stops working randomly

### ISSUE THREAD

**Issue by anup-mohan** [openMVG/openMVG#819]
Hi,

<img width="908" alt="computefeatureerror" src="https://cloud.githubusercontent.com/assets/3931869/23805244/190bcbf0-058b-11e7-9a7f-983b15c2a2c3.png">

When I try to run openMVGComputeFeatures.exe with arguments, the executable stops randomly. The error message that I receive is attached. The error goes away when I restart the computer or sometimes when I run the executable again. But the error keeps showing up randomly. The problem may not be with the dataset as the error keeps showing (and works) for the different set of images. The commands that I use are the following:

1)  openMVG_main_SfMInit_ImageListing.exe -i  folder_img -d file_sensor -c 3 -g 0 -o folder_tmp

2) openMVG_main_ComputeFeatures.exe -i json_file -f 0 -p HIGH -o folder_tmp

I am facing the issue on Windows 10 systems and have the latest version of openMVG. 

Kindly help in debugging and resolving this issue. 

Thanks

**Comment by pmoulon** [comment]
Thank you for your report.

I would suggest to check that it's not related to a memory allocation error:
Did you can try to run many time the algorithm without the -p HIGH option to see if you still have the problem?
Note: Since you are running with the -f 0 option, everytime it will load existing features and compute the missing one.

If you still have the crash, we will need to run in debug mode and see the cause of the error.

**Comment by anup-mohan** [comment]
Hi,

Sorry for the delay, was checking with different datasets. I still face the same issue. Now I do have a dataset which compute features does not work consistently. I went into the debug mode and found where the error occurs:

main_computeFeatures.cpp: Ln 266

The debugger stops in sift.c: Ln 1487

And I get the following error msg:

<img width="389" alt="openmvg_debugerror" src="https://cloud.githubusercontent.com/assets/3931869/24015770/cd000cf6-0a5f-11e7-8ace-3fa2c3e2071b.png">

Can you please suggest on how to proceed from here?

Thanks

**Comment by pmoulon** [comment]
Ok, seems like a bug in VLFEAT SIFT library.

I would recommend you to use the OpenMVG SIFT based implementation by using the option `-m SIFT_ANATOMY` on main_ComputeMatches, since I don't know of to solve the VLFEAT sift issue by known (since I cannot reproduce it on my side).

**Comment by anup-mohan** [comment]
Hi,

I tried SIFT_ANATOMY as you suggested but it does not generate feature (.feat) or descriptor (.desc) files for any of the datasets. Here is the command I use:

openMVG_main_ComputeFeatures.exe -i json_file -m SIFT_ANATOMY -o folder_tmp

Are there any issues with the command I use?

Thanks
Anup

**Comment by pmoulon** [comment]
The command line looks ok. Can you try with `-f 1`?

**Comment by anup-mohan** [comment]
Hi,

I tried with the new option but it didn't work. The command is as follows:
openMVG_main_ComputeFeatures.exe -i json_file -f 1 -m SIFT_ANATOMY -o folder_tmp

I also tried debugging and got an exception at:

main_computeFeatures.cpp: Ln 227

The debugger stops in polymorphic_impl.hpp: Ln 172

And I get the following error msg:

<img width="389" alt="openmvg_debugerror2" src="https://cloud.githubusercontent.com/assets/3931869/24059420/7409c3b4-0b25-11e7-969d-368af811a0b4.png">

**Comment by pmoulon** [comment]
Can you try with the develop branch please?
This issue is fixed there.
