### ISSUE TITLE
AKAZE : unresolved external symbol

### ISSUE THREAD

**Issue by billy-antoine** [openMVG/openMVG#820]
Hi,

I successfully built the libraries with VS2015: [url](https://github.com/openMVG/openMVG/issues/813) and played with the generated examples that work _like a charm_. I tried then to build an external project including the previously created lib files and it seems that I have an issue with the **openMVG_features.lib**. 

This piece of code does not raise any error:
```
#define _USE_MATH_DEFINES

#include "openMVG/image/image.hpp"
//#include "openMVG/features/features.hpp"

#include <iostream>

using namespace openMVG;
using namespace openMVG::image;

int main()
{
	Image<unsigned char> img;
	std::cout << img.IsRowMajor << std::endl;
	return 0;
}
```

An error however occures if I remove the commented line:

> #include "openMVG/features/features.hpp"

Here is the given output:

> LNK2001	symbole externe non résolu "public: __thiscall openMVG::features::AKAZE::AKAZE(class openMVG::image::Image<unsigned char> const &,struct openMVG::features::AKAZEConfig const &)" (??0AKAZE@features@openMVG@@QAE@ABV?$Image@E@image@2@ABUAKAZEConfig@12@@Z)

I added the required Eigen library using the NuGet tool from VS.
What should I do ?

Thank you in advance

**Comment by pmoulon** [comment]
What is your cmake file for your new project?

AKAZE symbol should be in openMVG_features.

Did you made your cmake this way:
https://github.com/openMVG/openMVG/blob/master/BUILD#L142

**Comment by billy-antoine** [comment]
Hi, 
I did not create any cmake file in my project. I built it from visual studio and linked the libraries using

> Configuration Properties > Linker > Input > Additional Dependencies

(as I did in order to install other third part libraries such as openCV)

**Comment by pmoulon** [comment]
If you include openMVG_features you also need to include openMVG_image library.

Please prefer the cmake way since all the library and include path will be usable.
See the BUILD line I told you

**Comment by pmoulon** [comment]
@billy-antoine Any progress?

**Comment by billy-antoine** [comment]
Hi,

Sorry, I spent the month doing something else... I'll try **next week** and keep you informed,
thank you again for your attention.

**Comment by pmoulon** [comment]
@billy-antoine Any feedback?
I'm closing the issue and feel free to reopen if needed.
