### ISSUE TITLE
Polymorphic ID

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#821]
I am trying to understand the working of ComputeFeatures in SFM. I have the following queries

1) What is the polymorphic_ID in sfm_data.json? What is the "id" inside ptr_wrapper in the same.
2) What is the image_describer.json file there for? How/Why is the ploymorphic_id of the image_describer object the same as the ptr_wrapper id of the first view in sfm_data.json and why is the polymorphic ID of the regions_type the ptr_wrapper id of the second view in sfm_data.json. 
3) What are region types? 

Any pointers will be helpful. TIA

**Comment by naveenjafer** [comment]
@pmoulon  could you kindly help with this when you are relatively free? :)

**Comment by rperrot** [comment]
Sorry for your the late reply, I try to answer some of your questions, maybe without the precision @pmoulon can provide but I'll try to give you some hints to understand theses things.

1) polymorphic_ID is a number created by the library we use for serialization (cereal), it is its internal way to deal with smart pointers. That's not a choice of openMVG, and you may not touch it at all (but you can ignore it for your own processing)

2) The image describer is a way to store information about how description was made on the input image (SIFT, AKAZE, ...) this is a convenient file used for latter process (for ex, it's important to know the size of the descriptors for matching). 

3) The region type is a synonym of description (more or less), it's a transparent class used to store a description region (it contains position and description vector). 

Hope it's clear enough for your understanding.

**Comment by naveenjafer** [comment]
@rperrot Yes thank you for helping with that. :) Things have become clearer now.

**Comment by pmoulon** [comment]
@naveenjafer Can you close the issue?
