### ISSUE TITLE
Question : How to add the right value (manufacturer, model, width) in sensor_width_camera_database.txt file ?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#824]
Hello Pierre,

I took some photos with a samsung galaxy S7 edge. I checked if this model was in sensor_width_camera_database.txt. It was not there. 

Could you please tell if the process below is correct ?
1) I opened a picture with "analogexif". Here is what i saw :

![exif](https://cloud.githubusercontent.com/assets/10100540/24094565/929dc95c-0d59-11e7-81d6-99e2bbb537ab.png)

2) Based on the 2 fields "Camera manufacturer" name and "Camera model", i add a line starting with "Samsung SM-G935F;"

3)Then, using the value of the field "Aperture" = f/1.7 i fecthed on this site: http://www.digicamdb.com/sensor-sizes/ the width for 1.7

![exif](https://cloud.githubusercontent.com/assets/10100540/24094964/49098734-0d5b-11e7-947e-97401e539254.png)

4) I ended the line with the value 7.53 

Is it correct ? 
Could you share with us your own method ?

Cheers,
Al

**Comment by pmoulon** [comment]
Hi @alvaro562003 

Please note that the aperture is related to the lens and not to the sensor size.

According here:
http://www.gsmarena.com/samsung_galaxy_s7_edge-7945.php
According the found value of the sensor size:  1/2.5" => it gives a sensor size of 5.76 mm.

So please consider to use the value 5.76 for this camera inside the sensor width camera database.

**Comment by alvaro562003** [comment]
Thank you,
But sorry for my ignorance, But how to go from 1/2.5" sensor size to 5.76 mm ?

**Comment by pmoulon** [comment]
Sorry I forgot this link: https://en.wikipedia.org/wiki/Image_sensor_format#Table_of_sensor_formats_and_sizes

**Comment by alvaro562003** [comment]
thank you, i spent so much time doing calculation
