### ISSUE TITLE
hello  when i use DensifyPointCloud in openmvs it always display  [IO]error unknown image format ,what should i do  can you  help me ?

### ISSUE THREAD

**Issue by silenceofcode** [openMVG/openMVG#826]

**Comment by pmoulon** [comment]
1. check that you can read the OpenMVG exported images
2. check that you have used the right path for the export
3. check that OpenMVS is compiled correctly and that it can read the provided images

**Comment by silenceofcode** [comment]
thanks for you respond soon @pmoulon 
i think my openmvs is not compiled correctly ,i had build it for many times ,but it is also error .can you give me a file how to build openmvs correctly for details.
best wish to you!!

**Comment by pmoulon** [comment]
Are you on windows, linux?

**Comment by silenceofcode** [comment]
thanks for you respond soon @pmoulon
i am on windows,i find the file common.h can not find  #define _USE_JPG .if i add #define  _USE_JPG to file ,it display error can not find file  jpeglib.h , this error in file ImageJPG.cpp .
best wish to you .

**Comment by silenceofcode** [comment]
my dear teacher @pmoulon 
i try my best way to solve this issue,but i am faild .i dont know how to deal with it  .can you help me?
best wish to you .

**Comment by pmoulon** [comment]
Did you try the things I told you:
- check that you can read the OpenMVG exported images (iamges that are written when you called openMVG2OPENMVS?)
- check that you have used the right path for the export
- check that OpenMVS is compiled correctly and that it can read the provided images

**Comment by silenceofcode** [comment]
dear teacher 
first the images were written thought  openMVG2OPENMVS and its can be read by openmvg i test
scoend the expot path was right its here the path .
 the OpenMVS can not read images the style of ("JPG","TIFF","PNG"),i think the OpenMVS wo not compiled correctly because i can not find the lib to support JPG .can you give me a file how to buidl openmvs  ?
best wish to you teacher.  
input path
OPENMVG
ImageListing     -i D:\Reslute\Data -d D:\openMVS\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camera_database.txt -o D:\Reslute\ImageListing           
ComputeFeatures  -i D:\Reslute\ImageListing\sfm_data.json -o D:\Reslute\ComputeMatches -m SIFT
ComputeMatches   -i D:\Reslute\ImageListing\sfm_data.json -o D:\Reslute\ComputeMatches  
IncrementalSfM   -i D:\Reslute\ImageListing\sfm_data.json -m D:\Reslute\ComputeMatches   -o D:\Reslute\IncrementalSfM
DataColor        -i D:\Reslute\IncrementalSfM\sfm_data.bin -o D:\Reslute\DataColor\sfm_data_color.ply
StructureFromKnownPoses -i D:\Reslute\IncrementalSfM\sfm_data.bin  -m D:\Reslute\ComputeMatches  -o D:\Reslute\StructureFromKnownPoses\robustFitting.json
DataColor        -i D:\Reslute\StructureFromKnownPoses\robustFitting.json   -o  D:\Reslute\DataColor\robust_colorized.ply
openMVG2openMVS  -i D:\Reslute\IncrementalSfM\sfm_data.bin -o D:\Reslute\openMVG2openMVS\scene.mvs -d D:\Reslute\openMVG2openMVS
openMVG2NVM      -i D:\Reslute\IncrementalSfM\sfm_data.bin  -o D:\Reslute\openMVG2NVM
OPENMVS          
DensifyPointCloud          -i D:\Reslute\openMVG2openMVS\scene.mvs   -o D:\Reslute\DensifyPointCloud\scene_dense.mvs
InterfaceVisualSFM         -i D:\Reslute\openMVG2NVM\scene.nvm       -o D:\Reslute\InterfaceVisualSFM\scene_dense.mvs

**Comment by silenceofcode** [comment]
dear teacher @pmoulon 
 i think i have find the reason ,i have solve the issue ;
thanks very much.

**Comment by pmoulon** [comment]
It would be nice if you can share the reason so if someone else have the same problem he will be able to solve it too ;-)

Please close the issue once your have shared your solution to the problem.

**Comment by silenceofcode** [comment]
dear teacher @pmoulon
 when i use ReconstructMesh in OpenMVS it always display error message.


10:14:27 [App     ] Build date: Mar 28 2017, 09:57:00
10:14:27 [App     ] CPU: Intel(R) Xeon(R) CPU E31220 @ 3.10GHz
10:14:27 [App     ] RAM: 15.96GB Physical Memory 8.00TB Virtual Memory
10:14:27 [App     ] OS: Windows 7 (SP1) x64
10:14:27 [App     ] SSE & AVX compatible CPU & OS detected
10:14:27 [App     ] Command line: -i D:\Reslute\DensifyPointCloud\scene_dense.mvs -o D:\Reslute\ReconstructMesh\scene_dense.mvs
10:14:28 [App     ] Scene loaded (987ms):
	5 images (5 calibrated) with a total of 6.27 MPixels (1.25 MPixels/image)
	300350 points, 0 vertices, 0 faces
what should i do ? if i had errors in previous steps?
best wish to you  !  @pmoulon

**Comment by silenceofcode** [comment]
dear teacher @pmoulon 
this address storage my files  i used  https://wetransfer.com/downloads/7f50573d349534ab7e89f35e251536bf20170328024905/88d829
best wish  to you !!

**Comment by pmoulon** [comment]
Thank for the sharing but not that I need the input image too in order to test on my side and try to help you.

**Comment by VTTroy** [comment]
Hey man, I have the same error as u had and i cant find the solution...
So how did u solve the image format err...?
Hope ur answer :100: 
Best wishes!

**Comment by pmoulon** [comment]
You can check if openMVG and openMVS are using the same image IO library.
