### ISSUE TITLE
Reuse results from ComputeFeatures?

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#828]
Is it possible to reuse results from compute features with new attempt at image matching?

I ran the ComputeFeatures on images without a connected graph and I would like to try to reuse the computed features but with new connected image sets.

Does that seem possible?

**Comment by pmoulon** [comment]
If I understand well you want match this images with an enhanced image dataset.
If it's the case:
- Just copy the *.feat and *.desc file to the new matching folder and so they will not be computed again.
tips: You can used symbolic links to avoid to perform a hard copy.

**Comment by jpwhitney** [comment]
@pmoulon Yes this is essentially what I was going to try.  Thanks for confirming that this is the way to avoid recomputation.
