### ISSUE TITLE
undefined reference of clear

### ISSUE THREAD

**Issue by RemoteSensingFrank** [openMVG/openMVG#829]
Hi 
 I can compile the code well in linux and the sample works well, but when I use openMVG as library in my program it occured the error:
/usr/local/include/openMVG/third_party/easyexif/exif.h:147：对‘easyexif::EXIFInfo::clear()’ undefined reference 

my code is :

#include <iostream>
#include <memory>

//#include"openMVG/image/image.hpp"
#include "openMVG/exif/exif_IO_EasyExif.hpp"

using namespace openMVG::exif;

int main() {
    std::string sInputImage = "/home/wuwei/UAVData/1/Img/DSC01681.JPG";
    std::unique_ptr<Exif_IO> exif_io( new Exif_IO_EasyExif( sInputImage ) );

    //std::cout << "width : " << exif_io->getWidth() << std::endl;
    //std::cout << "height : " << exif_io->getHeight() << std::endl;
    //std::cout << "focal : " << exif_io->getFocal() << std::endl;
    //std::cout << "brand : " << exif_io->getBrand() << std::endl;
    //std::cout << "model : " << exif_io->getModel() << std::endl;

    return 0;
}
I compile the code as the instruction in build file and make install in /usr/local/

**Comment by rperrot** [comment]
This is related to a missing link flag (easyexif)

how do you compile ? By hand, using an IDE, using a cmake file ?

**Comment by RemoteSensingFrank** [comment]
compile by cmake  just as the build file

**Comment by RemoteSensingFrank** [comment]
compile by cmake  follow the build file

**Comment by rperrot** [comment]
@pmoulon does this can be considered as an issue ? (easyexif not considered as an export target in findopenmvg.cmake ?)

**Comment by pmoulon** [comment]
The library is in the exported target
https://github.com/openMVG/openMVG/blob/master/src/third_party/easyexif/CMakeLists.txt#L20
 but not inside the OPENMVG_LIBRARIES cmake variable.

So, @RemoteSensingFrank if you want to use it, just include the library in your cmake file. Adding `easyexif ` just beside `${OPENMVG_LIBRARIES }` should do the trick.

**Comment by RemoteSensingFrank** [comment]
Thanks for your help. I find that I do not add library in my cmake file. 
I changed my cmakelist like :

cmake_minimum_required(VERSION 3.6)
project(openMVGDemo)

set(CMAKE_CXX_STANDARD 11)
set(SOURCE_FILES main.cpp)

#gdal include and linrary files set(GDAL_LIBRARY "/usr/local/lib/libgdal.so")
set(GDAL_INCLUDE "/usr/local/include/")
set(SIFT_LIBRARY "/usr/local/lib/libvlsift.a")

#openMVG find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})

include_directories(${GDAL_INCLUDE})

add_executable(openMVGDemo ${SOURCE_FILES})
target_link_libraries(openMVGDemo ${OPENMVG_LIBRARIES})
target_link_libraries(openMVGDemo ${GDAL_LIBRARY})
target_link_libraries(openMVGDemo ${SIFT_LIBRARY})

And then it works well!:D


在 2017年03月24日 07:02, Pierre Moulon 写道:

**Comment by RemoteSensingFrank** [comment]
Thanks it's the lib problem in my cmakelist and i solved it already.


在 2017年03月24日 00:10, Romuald Perrot 写道:
