### ISSUE TITLE
[software/ui] Add an adjacency matches viewer

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#831]
Add a QT application that allow to view the adjacency matrix and navigate to see every pair matches:
- It does more or less the same job as openMVG_main_exportMatches but it allow you to navigate in the adjacency matrix.

**Here the view once a project have be opened (sfm_data.X and a matches.X.Y files):**

![adjacencymatrix_viewer_0](https://cloud.githubusercontent.com/assets/3235050/24334905/db61301a-1273-11e7-9483-b8dc19eff407.png)

**A closer view, pair index are shown (zoom in thanks to the slider or the mouse wheel):**

![adjacencymatrix_viewer_1](https://cloud.githubusercontent.com/assets/3235050/24334906/db629518-1273-11e7-9055-81779122cbf2.png)

**If you zoom more the pair id, the number of matches starts to appear:**

![adjacencymatrix_viewer_2](https://cloud.githubusercontent.com/assets/3235050/24334909/db632c12-1273-11e7-9a75-22a8c9fdb63a.png)

**By clicking on a pair you can see the images and the matches:**

![adjacencymatrix_viewer_3](https://cloud.githubusercontent.com/assets/3235050/24334907/db62b02a-1273-11e7-8c1e-6acf674c84b5.png)

**You can view various pair instance at the same time:**
![adjacencymatrix_viewer_4](https://cloud.githubusercontent.com/assets/3235050/24334908/db631ee8-1273-11e7-961a-6cad64970145.png)

**Comment by rperrot** [comment]
Impressive !

**Comment by pmoulon** [comment]
Will be even more impressive when we will be able to add an additional graph based view ;-)
