### ISSUE TITLE
[cameras] Add a spherical camera model

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#832]
- Add a spherical camera model (can be used with full sphere panorama) :honeybee:,
- Handle this new camera model in the Bundle Adjustment framework,
- Enhance the multiview_robust_essential_spherical sample to use the new defined interface.

**Comment by Dorothy-2016** [comment]
Can I use some spherical images to test the spherical camera model directly? or I need to modify something to test? because when I run this program which have spherical camera model but  it doesn't acquire the right effect?why?

**Comment by pmoulon** [comment]
You need to run this sample (develop branch):
https://github.com/openMVG/openMVG/tree/develop/src/openMVG_Samples/multiview_robust_essential_spherical

Only relative pose and BA is implemented by now in the sample.
- relative pose use 2 image,
- BA can support any number of image.
Extending the Incremental SfM to use this camera model is easy but have not been done yet.

**Comment by Dorothy-2016** [comment]
Thanks for your reply! I have run this sample,yes,I can get the two images' relative pose,but how can I understand this, if I have a lot of images,can I use this sample to get the camera position by calculate every two images one by one?

**Comment by Dorothy-2016** [comment]
like image1 and image2,then image2 and image3,image3 and image4......

**Comment by pmoulon** [comment]
I mean that you can check that the sample is working for some of your pair.
And then you can update the Incremental SfM pipeline to work with the spherical camera model.

**Comment by Dorothy-2016** [comment]
OK,thank you very much！

**Comment by yuyou** [comment]
Hi

I have a similar case where only limited or very few spherical images are captured at different locations. What would be the right approach to take, if localisation (relative pose estimation) is the only task to all those images, say less than 10, 5-6 frames?  Should I modify the robust_essential_ spherical to add more frames to the tiny_scene?

**Comment by yuyou** [comment]
Hi

I am trying to test the new spherical camera mode by making local changes to the `sequential_SfM.cpp` mainly.  For instance, I made some changes to the lines like:
`const Pinhole_Intrinsic * cam_I = dynamic_cast<const Pinhole_Intrinsic*>(iterIntrinsic_I->second.get())
`
to:
`const IntrinsicBase * cam_I = dynamic_cast<const IntrinsicBase*>(iterIntrinsic_I->second.get());
`
and use `static_cast` later to deal with normal Pinhole camera and spherical camera, respectively. For example,

`static_cast<const Pinhole_Intrinsic*>(cam_I)`

Also I added a new function to support the robust relative pose estimation in `sfm_robust_model_estimate.cpp` from your great example `robust_essential_sphercial.cpp`.

So far this approach worked for me, till a problem surfaced. It is the function `AngleBetweenRay`.  I always got very small values (e.g. `0.76`), less than the `fRequired_min_angle` value  (`2`  and `3` in the code). Is it normal to spherical coordinates? or should a different approach to be used? 

The following is the output of the function "`MakeInitialPair3D`":

```
A-Contrario initial pair residual: 0.917663

Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 1136
 #residuals: 4544
 Initial RMSE: 112.956
 Final RMSE: 13.0366
 Time (s): 24.633

=========================
 MSE Residual InitialPair Inlier: -1
=========================
```

My purpose is to do camera pose estimation with spherical images.  Any suggestion towards the task would be very appreciated.

**Comment by pmoulon** [comment]
@yuyou AngleBetweenRay is not ideal for Spherical camera.
You can adapt it in order to use https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/openMVG/multiview/solver_essential_spherical.cpp#L72 => With Model = Mat3::Identity() and x1 and x2 computed as  
```const Vec3 ray1 = ( pose1.rotation().transpose() * intrinsic1->operator()( x1 ) ).normalized();
  const Vec3 ray2 = ( pose2.rotation().transpose() * intrinsic2->operator()( x2 ) ).normalized();
```

Or you can make a new function that consider the 3d point and the two camera.
This new function will have only one version and so be more generic.
