### ISSUE TITLE
How to open sfm_data.bin on mac 

### ISSUE THREAD

**Issue by mbuffier** [openMVG/openMVG#834]
Hi everyone, 

I run the Global sfm on my own images and I obtained a good point cloud when I read it in meshlab. However, I don't manage to open the sfm_data.bin to obtain the poses and landmarks from the global sfm algorithm. (when I try to dezip it, it transforms into a .cpgz) 

Would it be possible to have some hints on how to open this .bin on mac ? (I already tried most of the thinks I found on line and i'm on mac Sierra) Or does someone already have had this issue ? 

Thank you for your answer :) 

Maud

**Comment by pmoulon** [comment]
Hi Maud,

There is a tool called openMVG_main_ConvertSfMDataFormat that allow you to convert and extract the part your want from binary to XML or JSON (by default it will export everything).

I.E for some special usage, for example you can export only the camera poses to have a compact JSON output.

**Comment by mbuffier** [comment]
Hi pmoulon, 

Thank for your answer and for your work, it's great !! 

Maud

**Comment by pmoulon** [comment]
Hi @mbuffier 
Please close the issue if you got the desired answer.
Don't hesitate to open new issue if you need help.
