### ISSUE TITLE
Take ownership of the "openmvg" snap

### ISSUE THREAD

**Issue by mardy** [openMVG/openMVG#836]
Hi!
At the moment, the "openmvg" name is registered in the snap store under my name. Given that I'm not active on openmvg development, which also happens to be rather fast-paced, I think it's better if someone from the openmvg team takes care of updating the package. I can also do it from time to time, but anyway it's preferrable if the ultimate ownership belongs to you.

I'd suggest that you create an account in the snap store for your team; then, when being logged in with that account, visit https://myapps.developer.ubuntu.com/dev/click-apps/register-name/ and claim the "openmvg" name. You can add a link to this bug in the comment, so that the reviewers will understand that we all agree on the ownership switch.

Then, from https://myapps.developer.ubuntu.com/dev/click-apps/, click on the "openmvg" app and in the "collaborators" page you can add any e-mail address you like. Feel free to add my address mardy@users.sourceforge.net as well, if you'd like me to help with the uploads.

**Comment by pmoulon** [comment]
Thank you @mardy will do that during the coming week.

**Comment by pmoulon** [comment]
@mardy I claim the project, I'm waiting the feedback from the moderators. I will keep you updated.

**Comment by pmoulon** [comment]
@mardy I still does not have news about the ownership claims. Do you think I still have to wait?

**Comment by mardy** [comment]
On 04/28/2017 02:00 AM, Pierre Moulon wrote:
> @mardy <https://github.com/mardy> I still does not have news about the
> ownership claims. Do you think I still have to wait?

I'm not sure. Please try filing the claim again, and see if you get some
error while doing that. If anything, this will act as a "ping" to those
responsible :-)


-- 
http://blog.mardy.it <- geek in un lingua international!

**Comment by noise** [comment]
@pmoulon sorry for the delay, I just transferred the existing snap to your account, maintaining the build/release history. Let me know if you encounter any issues.
