### ISSUE TITLE
openMVG_main_ConvertSfMDataFormat doesn't find files 

### ISSUE THREAD

**Issue by mbuffier** [openMVG/openMVG#838]
Hi, 

I'm trying to use the openMVG_main_ConvertSfMDataFormat after the global pipeline tutorial. 

I've added that to the end of the file : 

print ("6. Store the data as JSON file")
pChange = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ConvertSfMDataFormat"),  "-i", reconstruction_dir+"/sfm_data.bin", "-o", os.path.join(reconstruction_dir,"sfm_data.json")] )
pChange.wait()

I have created before the sfm_data.json in the reconstruction_dir. 

however I obtained : 

6. Store the data as JSON file
Traceback (most recent call last):
  File "SfM_PoseEstimation.py", line 79, in <module>
    pChange = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ConvertSfMDataFormat"),  "-i", reconstruction_dir+"/sfm_data.bin", "-o", os.path.join(reconstruction_dir,"sfm_data.json")] )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Would you have any indications why ? 

Thanks again for your help, 

Maud

**Comment by pmoulon** [comment]
There is a missing `_` in the binary name ;-)
=> `openMVG_main_ConvertSfMDataFormat` to `openMVG_main_ConvertSfM_DataFormat`

Please try the following
```
print ("6. Store the data as JSON file")
pChange = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ConvertSfM_DataFormat"), "-i", os.path.join(reconstruction_dir,"sfm_data.bin"), "-o", reconstruction_dir+"/sfm_data.json"] )
pChange.wait()
```

**Comment by mbuffier** [comment]
So sorry about that..
Thank anyway !!

**Comment by pmoulon** [comment]
No worries 😄
