### ISSUE TITLE
warning C4267: 'argument': conversion from 'size_t'

### ISSUE THREAD

**Issue by zwn** [openMVG/openMVG#844]
I am compiling using win7+msvc2015 64bit. With this setup `size_t` is 64bit number but `IndexT` is `uint32_t`. This causes a lot of warning about possible loss of data when `size_t` is assigned into `IndexT`. The responsible warning is [C4267](https://msdn.microsoft.com/en-us/library/6kck0s93.aspx)

Are you aware of the issue? What is the best strategy to deal with it? I could find 4 places where the warning is turned of using a pragma directive. There is so many such messages emitted that it makes the compiler output almost useless.

I see 3 possible ways to go:
 - One way to go could be disabling the warning from cmake for the whole project but it somehow does not feel right since the assignment really does drop data and it would be turned off for everything - not just the `IndexT` type where it might be ok.
 - So another way could be making the IndexT into a proper type and add some operator overloads with explicit type cast inside but that might be a lot of work and some other problems might be uncovered along the way. 
 - Making the IndexT be 64bit value would probably unnecessarily increase memory usage (?) but it would be really simple and the result would be correct.

**Comment by pmoulon** [comment]
Hi @zwn 
I'm aware of this issue.

IndexT should remains a `uint32_t`. If you look to the branch called develop, I think there is already less warnings than in master.
The proper way would be to check the type everywhere and do the appropriate casting everywhere (static_cast<>) but as you said it can introduce some side effect (unit test can help to see if we made something wrong).

BTW, notice that many of those C4267 are from the ceres-solver library.

So:
1. Can you take a look at the develop branch and tell us if there is less warning than before?
Then we can decide which way to go (global pragma or careful handling of every warning).

Thanks.

**Comment by zwn** [comment]
Actually, I was compiling branch develop already, since I didn't want to report something that is possibly fixed. Sorry for not mentioning it right away. I cannot tell if there is less warnings since I don't have a base line.

I have also noticed that many of the warnings come from the third party libraries.

**Comment by pmoulon** [comment]
What about using the cmake pragma things only for the third party libraries and see how many left there is for OpenMVG core ;-)?

**Comment by zwn** [comment]
Actually, part of this is already there, see 

https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/CMakeLists.txt#L556

where it says:

```
  # Disable warning about int64 to int32 conversion. Disabling
  # this warning may not be correct; needs investigation.
  # TODO(keir): Investigate these warnings in more detail.
  add_definitions("/wd4244")
```

I'll add another one and report back.

**Comment by pmoulon** [comment]
You can certainly add `add_definitions("/wd4244")` here for a fast first check:
https://github.com/openMVG/openMVG/blob/master/src/third_party/CMakeLists.txt

**Comment by zwn** [comment]
With added `add_definitions("/wd4267")` ceres compiles almost without warnings. Where do you think would be a proper place to keep this long term?

The only remaining warning one comes from cxsparse headers:

```
1>R:\openMVG\src\third_party\cxsparse\Include\cs.h(561): warning C4190: 'cs_cl_house' has C-linkage specified, but returns UDT 'std::complex<double>' which is incompatible with C
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\complex(846): note: see declaration of 'std::complex<double>'
```

Looking at the code, the warning seems correct - extern C function returns C++ type. However according to [cxsparse/CMakeLists.txt#L13](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/third_party/cxsparse/CMakeLists.txt#L13) NCOMPLEX should be defined and the offending code should not evaluate. Oh, the trouble is that NCOMPLEX is defined only when cxsparse is compiled but not when code including the file is compiled.

**Comment by zwn** [comment]
Adding the following line to [src/third_party/cxsparse/CMakeLists.txt#L16](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/third_party/cxsparse/CMakeLists.txt#L16) fixes even the last warning from compiling cxspare and ceres solver.

```
SET_TARGET_PROPERTIES(cxsparse PROPERTIES INTERFACE_COMPILE_DEFINITIONS NCOMPLEX)
```

What would be the proper way to integrate these changes into openmvg? I'd like to prepare PR.

**Comment by pmoulon** [comment]
Hi,
Your change must do a similar stuff as https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/third_party/cxsparse/CMakeLists.txt#L13

Your version is better according the new recent CMAKE interface.

Can you check that your change still works by removing the add_definitions and just use your set_target_properties?

In order to do PR you must follow this:
- fork the repo
- start to work on a new branch starting from develop
- make a PR from your branch to OpenMVG develop

New code is merged in master only when a new version is released.
So every work in progress feature start from develop and are merged to develop until a new version has been validated and so be ready to be pushed to master.

**Comment by zwn** [comment]
Ok, I'll do PR just for the set_target_properties first. I was not sure if the PR should be against openmvg or against some upstream repo.

In the meantime, can you advice me on how to best integrate the add_definitions to ceres solver?

**Comment by pmoulon** [comment]
Thanks,

For Ceres I think we must keep the existing and try avoid to change it.
https://github.com/openMVG/openMVG/blob/master/src/third_party/ceres-solver/CMakeLists.txt#L545

But you can suggest the change to the upstream repo:
https://github.com/ceres-solver/ceres-solver

**Comment by zwn** [comment]
The PR for cxsparse is #847.

**Comment by zwn** [comment]
The PR for ceres is #848. Hopefully implemented this way it can be merged here. I might later suggest the change upstream but right now I don't have the bandwidth.

**Comment by zwn** [comment]
I see that there are no warnings explicitly enabled in builds using gcc - cmake implementation of msvc enables /W3 by default but there is not such thing for gcc (as far as I could find). So unless some warnings are explicitly enabled like in flann or lemon (like with -Wall), the default warning level of gcc is used, which is not very strict.

That helps to explain that there are 1685 instance of the word *warning* [in build log on appveyor](https://ci.appveyor.com/project/pmoulon/openmvg/build/job/rp95dku0dx52ffdr) and that does not even build the whole thing, while there are no warnings on travis.

**Comment by pmoulon** [comment]
Closing since it was handled by https://github.com/openMVG/openMVG/pull/852
