### ISSUE TITLE
AVX2 detected, but not applied

### ISSUE THREAD

**Issue by zwn** [openMVG/openMVG#846]
When building on win7 with msvc2015 32bit, I get this warning from eigen:

> .\eigen\src\core\arch\avx\packetmath.h(251): warning C4752: found Intel(R) Advanced Vector Extensions; consider using /arch:AVX

Checking the properties inside msvc reveals that /arch:SSE2 is set. The processor is [i5-4210U](https://ark.intel.com/products/81016/Intel-Core-i5-4210U-Processor-3M-Cache-up-to-2_70-GHz), Haswell, which supports AVX2.

Checking CMakeCache.txt I see I have `USE_AVX2:BOOL=TRUE` so the AVX2 support is detected, but not applied to the build.

The problem is probably somewhere in [src/cmakeFindModules/OptimizeForArchitecture.cmake](https://github.com/openMVG/openMVG/blob/master/src/cmakeFindModules/OptimizeForArchitecture.cmake) but my cmake fu is not up to this.

**Comment by pmoulon** [comment]
Thank for the update.
Seems like we can update the OptimizeForArchitecture in order to activate AVX option to the compiler.
We certainly must do some stuff here https://github.com/openMVG/openMVG/blob/master/src/cmakeFindModules/OptimizeForArchitecture.cmake#L357

**Comment by zwn** [comment]
I'll take a look. I wanted to know more about cmake anyway :wink:

**Comment by zwn** [comment]
Is there some benchmark included that would show a major benefit from using AVX? I'd use that to verify that not only the warning is gone but that we actually have the benefits.

**Comment by pmoulon** [comment]
I don't have a benchmark in the way you think to it but perhaps you can use the unit test to test that.

Here the option that come into my mind:
1. Run the unit test with and without your options. See if the timing is really different.
2. Run a SfM reconstruction on a medium size dataset => run the build/software/SfM/tutorial_demo.py see if the timing are really different.
3. Build your own benchmark and contribute it back to OpenMVG ;-)

**Comment by zwn** [comment]
So the problem is not in [src/cmakeFindModules/OptimizeForArchitecture.cmake#L357](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/cmakeFindModules/OptimizeForArchitecture.cmake#L357) but in [src/CMakeLists.txt#L96](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/CMakeLists.txt#L96) where SSE2 is set for MSVC regardless.

Just removing the overriding lines results in `/arch:AVX`. It would be actually better if it resulted in `/arch:AVX2` but that is not aticipated in OptimizeForArchitecture.cmake.

**Comment by zwn** [comment]
I have found `metric_avx2.hpp` that can be compiled with msvc2015 but the unit test `matching` does not cover it. It seems that the reason is that the avx2 implementation is singled out for 128 bytes descriptors that are not tested by the unit test. Is that correct?

What version of msvc is to be supported by openmvg? Based on appveyor I guess 2015. In that case the optimization flags can be updated quite a bit since both 32bit and 64bit support `/arch:AVX2`.

I see there is also a separate define `OPENMVG_USE_AVX2` that somewhat complicates things. OptimizeForArchitecture sets generic defines of the type `__AVX2__`. Can we use that instead so that the work for detecting when to set which defines is not duplicated?

**Comment by pmoulon** [comment]
You are right the AVX2 metric is not yet unit tested. I made some external check to assert that it works as it must.

The reason that the function is not yet unit tested is that:
1.  I want to work on add a function to test SSE, SSE2, AVX, AVX2 support at runtime.
2. According the function we will be able to test the AVX support and so test or not the metric in the unit test.
3. I need also to extend the metric_avx2 to support any vector dimension.

- OpenMVG require MSVC2015.
I think the flag /arch:AVX2 will only allow the compiler to vectorize some code that we do not do by hand. I don't know how Eigen is checking the intrinsic support.

**Comment by pmoulon** [comment]
@zwn Can we close the issue, since now the AVX metric is unit tested and that we have a class to check CPU intrinsic support at runtime?
See https://github.com/openMVG/openMVG/issues/855

**Comment by zwn** [comment]
@pmoulon The problem is [src/CMakeLists.txt#L96](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/CMakeLists.txt#L96) where SSE is set unconditionally. 

I wanted to fix that but run into other problems, like #866, that make it really hard for me to work on OpenMVG. I either keep multiple build trees corresponding to multiple branches and run out of disk space or I keep rebuilding after each checkout and I run out of time I have to work on the fix :worried: 

However, I think that just removing the lines [src/CMakeLists.txt#L94-L99](https://github.com/openMVG/openMVG/blob/f5ecb48a75f5ea2126930f559e6920fe2251baf9/src/CMakeLists.txt#L94-L99) is the fix required but I lack the space/time to test it.

**Comment by pmoulon** [comment]
@zwn The problem you spotted is now fixed ;-)
I tested on Visual Studio 2015 in x86 and x64 compilation. AVX, AVX2 detection is now supported and send accordingly to the Visual Studio compiler.
