### ISSUE TITLE
Remove using namespace std from header file

### ISSUE THREAD

**Issue by Brunni** [openMVG/openMVG#849]
Hi all,

I think it is a bad practice, that progress.hpp contains "using namespace std;"
This is propagated into the callers code which is maybe not what he wants.

Regards
Michael

**Comment by pmoulon** [comment]
Hi @Brunni 
It have been already fixed for the next WIP release
https://github.com/openMVG/openMVG/blob/develop/src/third_party/progress/progress.hpp

Looking forward you other comments
