### ISSUE TITLE
The RandR library and headers were not found (on Ubuntu)

### ISSUE THREAD

**Issue by dereks** [openMVG/openMVG#85]
derek@toshiba:~/github.com/openMVG_Build$ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
[...snip...]
-- Found Threads: TRUE  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.1.2") 
-- Using X11 for window creation
-- Using GLX for context creation
CMake Error at dependencies/glfw/CMakeLists.txt:204 (message):
  The RandR library and headers were not found

-- Configuring incomplete, errors occurred!
derek@toshiba:~/github.com/openMVG_Build$ 

Now what?

**Comment by Adhithiyan03** [comment]
What if I am running it in a server/docker without sudo accesss??
