### ISSUE TITLE
[matching] L2 AVX2metric

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#855]
- [x] add unit test of L2_AVX for uint8_t and float
- [x] rewrite the function in order to use only AVX2 code

Matching experiment on this dataset https://github.com/openMVG/ImageDataset_SceauxCastle
- BruteForce (metric L2_Vectorized - 1thread) **1m.27s**
- BruteForce (new L2 AVX2- 1thread) **14.7s**

- BruteForce (metric L2_Vectorized - 8thread) **22.2s**
- BruteForce (new L2 AVX2- 8thread) **4.3s**

Speed up:
- 1-> 8 thread => *4
- non AVX -> AVX metric => *5.5

The new metric is 5 time faster in average than the L2_Vectorized

For the previous work see https://github.com/openMVG/openMVG/issues/761

**Comment by pmoulon** [comment]
@zwn I add a tiny unit test.
It's not a benchmark but at least on PC that have AVX2 capabilities there is not a unit test for it!

**Comment by zwn** [comment]
:+1: Can the avx2 metric now be used also for other sizes except 128?

**Comment by pmoulon** [comment]
Not yet but we can easily update it to support AVX2 instruction on valid memory block (% SIMD chunck size) and then perform the rest with classic (a-b)*(a-b).

Do you want take the lead on update them to support any size (uint8_t and float version)?

**Comment by zwn** [comment]
I am sorry, I know almost nothing about AVX2 so that would most likely not be effective use of my time (unless it is really easy to pick up). However, I'd be happy to help with something else.

**Comment by pmoulon** [comment]
You does not need to touch any existing AVX code, in order to change the size support you need to change the loop size %32 (uint8_t) or %16 (float).

In which dimension and type are you interested?

**Comment by pmoulon** [comment]
Now merged to develop
