### ISSUE TITLE
[Question] How does the incremental bundle adjustment step work?

### ISSUE THREAD

**Issue by MaXL130** [openMVG/openMVG#858]
Hi everyone, 

I've got a "small" question regarding the bundle adjustment (BA) step when adding new images to the reconstruction process.

As far as I understood BA does minimize the squared reprojection error by optimizing the camera parameters and the reconstructed 3D positions.

![image](https://cloud.githubusercontent.com/assets/26429337/24828646/c5aac40a-1c61-11e7-911e-0477138e159d.png)

(Ref: https://en.wikipedia.org/wiki/Bundle_adjustment)

So far, so good. I now have initialized the process with two images, and I have a configuration that fits this initial imagepair. Now the next set of points/the new image comes in. How is inserted in the current configuration and then optimized?

I am having a hard time finding literature, that gives some examples and/or (pseudo-)code, so if you can recommend any, that would be very helpful, too.

**Comment by pmoulon** [comment]
Hi @MaXL130 

Bascally you start from a 3d seed (the initial pair at start and then the reconstruction) on which you will add new camera iteratively.
For each new image you compute the corresponding 2D-3D feature and then perform a robust camera absolute camera estimation (resection -> P3P). Then you new camera is in the absolute coordinate of your scene and so you can triangulate new points, perform a BA and continue the process.

You will see [here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L112) the initial 3d reconstruction (the initial pair) and then the loop that add image and perform BAs.

I invite you to read [1] to understand the Incremental SfM pipeline:
Moulon Pierre, Monasse Pascal and Marlet Renaud. ACCV 2012.
[Adaptive Structure from Motion with a contrario model estimation.](http://hal.archives-ouvertes.fr/index.php?halsid=1n2qdqiv2a0l5eq7qpos9us752&view_this_doc=hal-00769266&version=1)

I invite you to read [2] to understand the Global SfM pipeline:
[2] Moulon Pierre, Monasse Pascal and Marlet Renaud. ICCV 2013.
[Global Fusion of Relative Motions for Robust, Accurate and Scalable Structure from Motion.](http://imagine.enpc.fr/~moulonp/publis/iccv2013/index.html)

**Comment by pmoulon** [comment]
PS: you have pseudo code in [1] or [here](http://openmvg.readthedocs.io/en/latest/software/SfM/IncrementalSfM/)

**Comment by MaXL130** [comment]
Thanks for your answer, I did already skim over your papers, should have read them more carefully tho '-.-

What do you mean by "compute the corresponding 2D-3D feature"? Finding the fitting feature in the new image, that  matches the already reconstructed 3D point?

**Comment by pmoulon** [comment]
In order to find the new camera position you must find 2D-3D correspondences.
Since your know the 2D feature index of all 3D points you can easily find the corresponding matching point that support some 3D point.

**Comment by MaXL130** [comment]
I think we are talking about the same thing. Just to clarify:

3D point has been computed using some 2D points, that are descibed by features. One of them is "feature A". 
When adding a new camera position, I match the 2D features of the new image to the features, that correspond to the already estimated 3D points, so in my example I am searching for a 2D point in the new image, that matches "feature A".

Am I right?

I hope that this was somewhat understandable...

**Comment by pmoulon** [comment]
You right.

Often feature matches are already available before starting the 3D process.
You compute tracks by fusing 2d-2d matches and so you know the image visibility for each track (putative 3D points).

See Moulon Pierre and Monasse Pascal. CVMP 2012.
[Unordered feature tracking made fast and easy.](http://hal.archives-ouvertes.fr/index.php?halsid=ggdarhl8cv1j6ohq2073eok8q3&view_this_doc=hal-00769267&version=1)

If you are in video mode "very small baseline" like you can use feature tracking (see KTL feature tracking).

**Comment by MaXL130** [comment]
I read through everything and I got it now.

Thanks again for your fast support, it's really helpful 👍
