### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by hcjghr** [openMVG/openMVG#860]
Hi,

Today I noticed that I can't build the library anymore. I get this error:

[ 97%] Building CXX object software/ui/SfM/adjacency_matrix_viewer/CMakeFiles/ui_openMVG_MatchesViewer.dir/matchingpairgraphicsview.cpp.o
/home/klemen/workspace/ANU/OpenMVG_VSSLAM/code_vsslam_2/src/software/ui/SfM/adjacency_matrix_viewer/matchingpairgraphicsview.cpp: In member function ‘virtual void MatchingPairGraphicsView::mousePressEvent(QMouseEvent*)’:
/home/klemen/workspace/ANU/OpenMVG_VSSLAM/code_vsslam_2/src/software/ui/SfM/adjacency_matrix_viewer/matchingpairgraphicsview.cpp:89:19: error: ‘fromStdString’ is not a member of ‘QByteArray’
         svg->load(QByteArray::fromStdString(svg_string));

Any suggestions?

Thanks

**Comment by hcjghr** [comment]
I figured out that the problem was that I was using too old QT. Installing the QT 5.8 solved the errors. Probably this requirement should be added somewhere (sorry if it already is and I just overlooked it).

Cheers

**Comment by pmoulon** [comment]
You're right QT5 is required for this binary
https://github.com/openMVG/openMVG/blob/develop/src/software/ui/SfM/adjacency_matrix_viewer/CMakeLists.txt#L8

About the requirement I though that the cmake will be able to deal to discover if Qt5 or Qt4 is used.

**Comment by hcjghr** [comment]
The QT has to be actually newer than 5.4 as that function was introduced in that version. I was testing with 5.2 and it wasnt working.

**Comment by pmoulon** [comment]
Thanks. We will need to put this info somewhere in the BUILD file doc

**Comment by pmoulon** [comment]
@hcjghr I updated the doc there https://github.com/openMVG/openMVG/commit/4dbe8d2111aba21ffd2b9c3856053265bece443a
