### ISSUE TITLE
Can openmvg out put bundle file?

### ISSUE THREAD

**Issue by assbben** [openMVG/openMVG#864]
I can get bundle file when using opensfm,and what is bundle file in openmvg?

**Comment by pmoulon** [comment]
You can obtain the bundle output file by running `openMVG_main_openMVG2PMVS` on the sfm_data.bin file produced by OpenMVG.

**Comment by assbben** [comment]
OK, I'll try it

**Comment by pmoulon** [comment]
Please close the issue when you have tested it ;-)
