### ISSUE TITLE
Size of compiled binaries

### ISSUE THREAD

**Issue by zwn** [openMVG/openMVG#866]
I am checking my build tree and I have some observations.

I see executables like `openMVG_test_features.exe` with the size of about 67kB. I also see lots of executables like `openMVG_test_global_SfM.exe` that are several MB in size and in addition to that also exp and lib files are generated adding more MB.

Why do some executables have exp and lib files?

Why are some executables huge and some really small? Is it because linking in part of ceres makes them big? I see ceres.lib is around 30MB.

BTW: just switching between `develop` and `develop_visual_studio_alignment32bit` takes tens of minutes to recompile :worried:. In times like these I miss python :wink:

**Comment by zwn** [comment]
Using dumpbin it seem all exported symbols come from cereal. Checking its source it seems it contains unconditional `__declspec(dllexport)` marking everything as _used_, thus included in the final binary.

```
#ifdef _MSC_VER
#   define CEREAL_DLL_EXPORT __declspec(dllexport)
#   define CEREAL_USED
#else // clang or gcc
#   define CEREAL_DLL_EXPORT
#   define CEREAL_USED __attribute__ ((__used__))
#endif 
```

My guess is that only executables linking to cereal have __.exp__ and __.lib__ files generated.

**Comment by zwn** [comment]
And judging from the comment it is there on purpose:
```
//! Prevent link optimization from removing non-referenced static objects
/*! Especially for polymorphic support, we create static objects which
    may not ever be explicitly referenced.  Most linkers will detect this
    and remove the code causing various unpleasant runtime errors.  These
    macros, adopted from Boost (see force_include.hpp) prevent this
    (C) Copyright 2002 Robert Ramey - http://www.rrsd.com .
    Use, modification and distribution is subject to the Boost Software
    License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
    http://www.boost.org/LICENSE_1_0.txt) */
```

**Comment by pmoulon** [comment]
You're right cereal and ceres have some drawback (it involves many things at compile times).
Perhaps we can tweak cereal or use some preprocessor to make it lighter at linking time...

Do you have any idea?

PS: We know that OpenMVG is quite slow to compile, but since it use some template based code it hard to compress compilation time. Template guarantee a lot of expressivity and offer a lot of very interesting things and that why we are using them.

**Comment by zwn** [comment]
As I noted in https://github.com/openMVG/openMVG/issues/846#issuecomment-296548270 due to the large build tree and/or slow compile times, openMVG is hard for me to use and/or improve. I understand the trade off you made with templates, however I would rather go for compilation speed and forgo some possible optimizations expression templates have to offer.

As for ideas what could be tried - precompiled headers are certainly one to test. In theory it should allow to compile the template definitions only once and subsequently use them in every cpp file. However, I am not sure if the long compile times come from parsing the templates or from instantiating them. The effect on build tree size would be obviously minimal.

I think one of the things making the build slower and build tree larger are the test executables. The build is by default static and there are a lot of tests (which is great BTW). Having the tests link to dynamic libraries should make them much smaller and maybe even faster to compile. I am not sure if this is supported out of the box or not.

Oh, the way I measure build tree size and compile time is to build all tests.

**Comment by pmoulon** [comment]
You can try to use dynamic libraries with this option (`BUILD_SHARED_LIBS ON`):
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L75

**Comment by zwn** [comment]
I did a quick test on the current develop branch and I get a bunch of errors like this:
```
5>------ Build started: Project: openMVG_matching, Configuration: Debug x64 ------
5>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_features.lib'
6>------ Build started: Project: openMVG_test_matching, Configuration: Debug x64 ------
6>LINK : fatal error LNK1104: cannot open file '..\..\Windows-AMD64-Release\Debug\openMVG_matching.lib'
```
I see that openMVG_matching is built as dll but the test is looking to link against the lib for exported symbols. However, there are no exported symbols from the dll. 

So I guess I am out of luck on windows :worried:

**Comment by pmoulon** [comment]
There is some cpp files for openMVG_matching and openMVG_features so they must not be empty
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/CMakeLists.txt#L12
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching/CMakeLists.txt#L11

I did not know if the problem is coming from the cmake cache (or visual studio cache) when you change the config from static to non static.

**Comment by zwn** [comment]
Oh sure there are cpp files (the dll is created). But there are no `__declspec(dllexport)` markers. Nothing is exported by default on windows, so no *.lib file for linking is created. When I search for dllexport I get only third_party dir.

BTW: I have created a fresh build tree for this so nothing is stale.

**Comment by bjornpiltz** [comment]
BUILD_SHARED_LIBS doesn't work on Windows. We should make that clear. It would take quite a bit of work to make openMVG compile into DLLs on Windows.

**Comment by pmoulon** [comment]
@bjornpiltz You're right, It would be nice to make this option available on unix platforms.
