### ISSUE TITLE
coordinate problem

### ISSUE THREAD

**Issue by RemoteSensingFrank** [openMVG/openMVG#867]
Hi!
    I have a problem with coordiante system. I use openMVG to process my UAV data, and for each image, there is a GPS data contained  latitude , longitude and altitude. I processed like:

> // Initialize the scene
//  Pose prior for each view will be set thanks to the GPS data
openMVG_main_SfMInit_ImageListing \
  -P \
  -d sensor_width_camera_database.txt \
  -i /media/pierre/SenseFly/Quarry/geotagged-images/ \
  -o /media/pierre/SenseFly/Quarry/quary_output/
thread_count=8
openMVG_main_ComputeFeatures \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches \
  -n $thread_count
// Limit the number of pairs that will be used for matching
// -> limit to pose neighborhood thanks to the pose center prior location
openMVG_main_ListMatchingPairs \
  -G \
  -n 8 \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches/pair_list.txt
openMVG_main_ComputeMatches \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -l /media/pierre/SenseFly/Quarry/quary_output/matches/pair_list.txt \
  -g e \
  -o /media/pierre/SenseFly/Quarry/quary_output/matches/
openMVG_main_GlobalSfM \
  -P \
  -i /media/pierre/SenseFly/Quarry/quary_output/sfm_data.json \
  -m /media/pierre/SenseFly/Quarry/quary_output/matches/ \
  -o /media/pierre/SenseFly/Quarry/quary_output/global_reconstruction

and at last I trans the ply data to UTM projection coordiante system, but the result cannnot matched with google eadth in map, I don't understand that what the GPS in the program means, do they means the position of the camera?

**Comment by pmoulon** [comment]
lat,lon,alt are converted to XYZ convention is the ECEF coordinate system by default.
So you have to convert back the camera position to your convention afterwards.

**Comment by RemoteSensingFrank** [comment]
thanks I solve the problem by using the local coordiante system and the trans the local coordiante system to ECEF and UTM at last
