### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by learnccode** [openMVG/openMVG#868]
When I compile the openMVG using the vs2015 commuity as the build file but there are some problem:

> 2>H:\openMVG\openMVG\src\openMVG/cameras/Camera_Common.hpp(98): error C2899:cannot use the type name outside the template declaration
2>H:\openMVG\openMVG\src\openMVG/cameras/Camera_Common.hpp(99): error C2899: cannot use the type name outside the template declaration
2>H:\openMVG\openMVG\src\openMVG/cameras/Camera_Common.hpp(106): error C2899: cannot use the type name outside the template declaration
2>H:\openMVG\openMVG\src\openMVG/cameras/Camera_Common.hpp(107): error C2899: cannot use the type name outside the template declaration

the error occured in this code : 
inline constexpr Intrinsic_Parameter_Type
operator|(Intrinsic_Parameter_Type x, Intrinsic_Parameter_Type y)
{
  return static_cast<Intrinsic_Parameter_Type>
    (static_cast<typename std::underlying_type<Intrinsic_Parameter_Type>::type>(x)|
     static_cast<typename std::underlying_type<Intrinsic_Parameter_Type>::type>(y));
}

inline constexpr Intrinsic_Parameter_Type
operator&(Intrinsic_Parameter_Type x, Intrinsic_Parameter_Type y)
{
  return static_cast<Intrinsic_Parameter_Type>
    (static_cast<typename std::underlying_type<Intrinsic_Parameter_Type>::type>(x) &
     static_cast<typename std::underlying_type<Intrinsic_Parameter_Type>::type>(y));
}

**Comment by pmoulon** [comment]
You can use the develop branch or look to the fix here:
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/cameras/Camera_Common.hpp#L101

You must remove the typename in front of std::underlying_type

**Comment by pmoulon** [comment]
@learnccode  Any feedback?
