### ISSUE TITLE
OpenMVG run very slow in Windows

### ISSUE THREAD

**Issue by robin32205** [openMVG/openMVG#870]
hi,
I had tried to run OpenMVG in my laptop (Windows 10 with 8G ram), however, the speed at ComputeFeatures, ComputeMatches and IncrementalSfM are all very low comparing with linux version. Although all the cores are running 100% (i7-5500 2.4GHz, 4 cores), and using momery is unnormally high (about 1G which can't be believed). Was I missing something here? thank you!

**Comment by pmoulon** [comment]
Hi @robin32205,
her some questions:

- Are you using the same machine to run your Linux and Windows experiment?
- Are you sure you have built in Release mode on Windows?
- I remember that in the past I saw a difference in memory allocation size on the VLFEAT size (SIFT extraction). Can you elaborate about your memory problem (can you tell at which step it is happening)?

**Comment by robin32205** [comment]
hi @pmoulon 
Yes, you are right, i find out that I am under debug mode, thank you!

**Comment by pmoulon** [comment]
@robin32205 Please can you close the issue?

**Comment by robin32205** [comment]
Hi Moulon,

Sorry that I have another little question about the sequential model.

I find out that I always get different sequence from each computation, although that all the input images and parameters are the same and with the same computer just in different time (even I use the -a and -b to fix the initial pair in the Incremental SfM).

I am very curious about that, because I think that the result of a computer should be always the same at the totally same situation.

could you please tell me why?


BR

Robin


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年4月18日 上午 12:00
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


@robin32205<https://github.com/robin32205> Please can you close the issue?

**Comment by pmoulon** [comment]
Variability of the result is due to:
1. some randomness in the process (random number generator).
  - you can fix that by using a fix seed. I plan to work on that soon.
2. Threading -> openMP scheduling for some loop does not guarantee that operations are done in the same order.
  - here we have to see how OpenMP scheduling is set for every parallel for

**Comment by robin32205** [comment]
I see!! thank you so much!

**Comment by robin32205** [comment]
Hello Moulon,


Sorry to disturb you again. I have some technical problem within the algorithm, might I ask you some question here?


I am using your OpenMVG with OpenMVS to build up a 3D model, I have a question about these two algorithm:

Is the function "ComputeStructureFromKnownPoses" in OpenMVG similar to "DensifyPointCloud" in OpenMVS?

I wonder that if we already get the 3d points and the relative info between each views, why we still need to process the step in OpenMVS to get the depth maps and then reform the 3d points output again?  Is these two part doing the different thing or part of them is the same?

And then, I find out that in each scanning case, with the same input images and same parameters, the results are always different. Is that possible to get the same result based on the same inputs? if it is possible, how can I do to achieve that? (I could not find the random assumption within your code...)

if you can help me with these question, that will be very great! thank you very much~

Best regards,

Robin

**Comment by pmoulon** [comment]
Hi @robin32205,

OpenMVG's `ComputeStructureFromKnownPoses` and OpenMVS's `DensifyPointCloud` does not perform exactly the same thing, but in a sense they both computing a point cloud.

If you want have something faster you can see the thing this way.

1. Does not use  `ComputeStructureFromKnownPoses` and rely on `DensifyPointCloud` to compute a dense point cloud.

2. If the output from OpenMVS SfM (Global/SfM) is sufficiently dense you can ask OpenMVS to directly mesh your OpenMVG point cloud and so avoid the step DensifyPointCloud. Then you call refine mesh in order to enhance the found geometry.
-> As you will see here we wrote that DensePointCloud computation can be optional https://github.com/cdcseacave/openMVS/wiki/Usage#dense-point-cloud-reconstruction-optional

> And then, I find out that in each scanning case, with the same input images and same parameters, the results are always different. Is that possible to get the same result based on the same inputs? if it is possible, how can I do to achieve that? (I could not find the random assumption within your code...)

- Can you explain about which step are you talking?

  - The SfM process is relying on robust estimation of geometrical model. Those robust estimation rely on a variant of RANSAC that use some random number generation in order to select some sample data.
  The generation of the random_number are now guarantee to be the same between different run on a same computer in the develop branch thanks to the initialization of the random_seed for every random generator.

Regards,
Pierre

**Comment by robin32205** [comment]
Hi Pierre,


thank you so much for your kindly reply and explain~

and what I find the began of difference is beginning from the matching step (and the feature result in .feat file will in different order of priority after every feature computation, here I use is the AKAZE_FLOAT), RANSAC is in the step of Incremental SfM, is that right?


thank you again for your reply!

BR

Robin

________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月7日 下午 11:02
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


Hi @robin32205<https://github.com/robin32205>,

OpenMVG's ComputeStructureFromKnownPoses and OpenMVS's DensifyPointCloud does not perform exactly the same thing, but in a sense they both computing a point cloud.

If you want have something faster you can see the thing this way.

  1.  Does not use ComputeStructureFromKnownPoses and rely on DensifyPointCloud to compute a dense point cloud.

  2.  If the output from OpenMVS SfM (Global/SfM) is sufficiently dense you can ask OpenMVS to directly mesh your OpenMVG point cloud and so avoid the step DensifyPointCloud. Then you call refine mesh in order to enhance the found geometry.
-> As you will see here we wrote that DensePointCloud computation can be optional https://github.com/cdcseacave/openMVS/wiki/Usage#dense-point-cloud-reconstruction-optional

And then, I find out that in each scanning case, with the same input images and same parameters, the results are always different. Is that possible to get the same result based on the same inputs? if it is possible, how can I do to achieve that? (I could not find the random assumption within your code...)

  *   Can you explain about which step are you talking?

     *   The SfM process is relying on robust estimation of geometrical model. Those robust estimation rely on a variant of RANSAC that use some random number generation in order to select some sample data.
The generation of the random_number are now guarantee to be the same between different run on a same computer in the develop branch thanks to the initialization of the random_seed for every random generator.

Regards,
Pierre

**Comment by pmoulon** [comment]
Which branch are you using?

RANSAC is used for feature matching filtering (ComputeMatches) and for relative model estimation (SfM).

**Comment by robin32205** [comment]
hi Pierre,


I use sNearestMatchingMethod == "AUTO" with ESSENTIAL_MATRIX.

so if the RANSAC is used, the result will be random?


BR

Robin

________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月11日 上午 08:08
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


Which branch are you using?

RANSAC is used for feature matching filtering (ComputeMatches) and for relative model estimation (SfM).

**Comment by pmoulon** [comment]
For the master branch for every run you can observe a tiny change between every run.
For the develop branch you will have the same results.

**Comment by robin32205** [comment]
oh i get it! thank you so much.


best regards

________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月11日 上午 10:25
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


For the master branch for every run you can observe a tiny change between every run.
For the develop branch you will have the same results.

**Comment by pmoulon** [comment]
Now the master branch is ok, since the version 1.2 was released yesterday ;-)

**Comment by robin32205** [comment]
oh~ happy to hear that~ thank you~ :D


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月13日 上午 01:57
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


Now the master branch is ok, since the version 1.2 was released yesterday ;-)

**Comment by robin32205** [comment]
Hello Pierre,


I have a little question about your sequential SfM. If I may put my two cents in, colorized points data seem not be extracted into each resection result within sequential Sfm until colorizeTracks function in ComputeSfM_DataColor.cpp. Is that possible to colorize it in each resection results?


BR


Robin

________________________________
寄件者: 陳 韋帆 <robin32205@hotmail.com>
寄件日期: 2017年7月13日 上午 10:55
收件者: openMVG/openMVG
主旨: RE: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


oh~ happy to hear that~ thank you~ :D


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月13日 上午 01:57
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


Now the master branch is ok, since the version 1.2 was released yesterday ;-)

**Comment by pmoulon** [comment]
You can easily add this functionality in the sequential engine.
Just edit and call the colorize function there
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140

**Comment by robin32205** [comment]
Dear Pierre,


Sorry I don't notice that you have new version these days, I will check that! but in v1.1, this function seems not save with color.

Anyway, I will try your new master-piece! thanks a lot!!


BR


Robin


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月27日 上午 04:55
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


You can easily add this functionality in the sequential engine.
Just edit and call the colorize function there
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140

[https://avatars3.githubusercontent.com/u/3512104?v=3&s=400]<https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140>

openMVG/sequential_SfM.cpp at master - GitHub<https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140>
github.com
openMVG - open Multiple View Geometry library. Basis for 3D computer vision and Structure from Motion.

**Comment by robin32205** [comment]
Dear Pierre,


I am trying your version 1.2 with list of matching pairs, but I get two problems below:


  1.  when doing collectionMatcher->Match in main_ComputeMatches.cpp, it take more time (from about 10 sec. to 150 sec.). is that normal?
  2.  when I converting OpenMVG to sfm.json to scene.mvs, OpenMVS will fail from beginning (DensifyPointCloud), had you tested this part, or just I missing somethings?

thank you again!

BR

Robin

________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年7月27日 上午 04:55
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


You can easily add this functionality in the sequential engine.
Just edit and call the colorize function there
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140

[https://avatars3.githubusercontent.com/u/3512104?v=3&s=400]<https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140>

openMVG/sequential_SfM.cpp at master - GitHub<https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L140>
github.com
openMVG - open Multiple View Geometry library. Basis for 3D computer vision and Structure from Motion.

**Comment by pmoulon** [comment]
1. Are you sure that the process is running in multithread mode?

2. It should work. Can you show the message that DensifyPointCloud is displaying?

**Comment by robin32205** [comment]
Hi Pierre,


I think during the process of Regions Matching do not use the all threads, but multithread always works well in other processes.

when I only replace the OpenMVG2OpenMVS.exe to old version, and then it work well. I believe that maybe i missing something in that, i will check again!


thanks for your help,


Robin


________________________________
寄件者: Pierre Moulon <notifications@github.com>
寄件日期: 2017年8月3日 上午 06:44
收件者: openMVG/openMVG
副本: robin32205; Mention
主旨: Re: [openMVG/openMVG] OpenMVG run very slow in Windows (#870)


  1.  Are you sure that the process is running in multithread mode?

  2.  It should work. Can you show the message that DensifyPointCloud is displaying?

**Comment by pmoulon** [comment]
- Please check which regions Matcher is used and if "Using the OPENMP thread interface" is printed.

- Please note that OpenMVG export a MVS project compatible with the updated OpenMVS project file.
  - Perhaps you did not update your OpenMVS repository since some months, weeks.

**Comment by robin32205** [comment]
Hi Pierre,
thank you for your kindly reply, i have a small question about OpenMVG. Actually, I want to build a pipeline similar to Qlone but based on OpenMVG. Does it has chance to use OpenMVG (photogrammetry) to reconstruct model by using smaller photo resolution and incremental SfM and achieve almost real time computation? Because I think that the class "SequentialSfMReconstructionEngine" seems only can be proceed when all the matching procedure are finished, is that true?
thank you again~

BTW, this kind of question should be opened in the Issues? I do not understand the routine here..   ^^""

best regards,
Robin

**Comment by pmoulon** [comment]
Hi @robin32205 
1- You see that Qlone is using a pattern. From this pattern they infer the camera poses and the scale of the object.
2- If you are doing such a pattern such the pose inference and motion averaging can be fast. You will still have to perform the feature matching and filtering -> this step is quite time extensive, but it can be done offline.
3- If you have global poses and matches (from the pattern) you can make SfM only on those points or make a motion averaging + a BA based on this information. It should be very very fast.

4- I can help you to build a prototype that will use 4 markers.

I also think that opening a new issue would be nice.
You can use a title like `How to build a real time pattern based 3d reconstruction system?`
