### ISSUE TITLE
I am not familiar with python. Is there a single C++  file for the whole pipeline to do SFM using OpenMVG?

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#875]
I am also tried of those command option.  Is Anyone has a single C++  file for the whole pipeline to do SFM using OpenMVG?   I mean given a list images and go through the whole SFM pipeline to output sfm result and there is need to read and write  SM_data files in the process.  
Thanks.

**Comment by pmoulon** [comment]
Not yet, sone user have done it on their own.
OpenMVG is made to be flexible and so having many binaries articulated around the spine file (sfm_data.json) allow the users to be able to customize any step of the process.

Having the whole pipeline in a single C++ file would let the user to have less control on each steps and so loose some flexibility.

I can make one, one day, but you must let me some time.
