### ISSUE TITLE
Question: is sfm_data.bin always present  and  robust.bin optional ?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#876]
Hello,
Using the incrementalSFM on the same image-dataset but with different configurations for the descriptors (SIFT or AKAZE), (HIGH or ULTRA), i noticed that one time robust.bin was inexistent.
So i continue the reconstruction with sfm_data.bin and it works.

Question: are there some conditions under which robust.bin is absent or is it a bug ?
I was wondering if it is the same case as https://github.com/openMVG/openMVG/issues/573 (KevinCain part only)

Thanks

**Comment by pmoulon** [comment]
Hi,
The robust.bin in here to show that you can compute some structure if you know only the camera position and you have some features and descriptors (no matches).

You can safely used the sfm_data.bin for the reconstruction.

I don't know why the robust.bin is not there, certainly the binary ComputeStructureFromKnownPoses did not work in a special configuration. Can you identify which combination did not worked?

**Comment by alvaro562003** [comment]
i will check if i can reproduce the absence of robust.bin with an image-dataset less personnal.
