### ISSUE TITLE
Install path while using openMVG as third party lib

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#887]
I noticed something today while building my project using openMVG as a third party library as described here https://github.com/openMVG/openMVG/blob/master/BUILD. I had used the DCMAKE_INSTALL_PREFIX path and created a openMVG_install directory. When setting the "DOpenMVG_DIR:STRING" I have given the path to the install directory that I created(Not the one in /usr/local/". But during the logs generated during cmake the Log is as follows

"-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.1.0
-- Installed in: /usr/local
" 

Shouldnt the install path be the path that I have passed in the DOpenMVG_DIR? I Have it installed both locally in a separate directory and one has been installed in /usr/local/ by default. Am i missing something here?

I am also a little doubtful about what is searched for when one specifies this "find_package(OpenMVG REQUIRED)". Where does this search for the package?

The OpenMVGConfig.cmake file is the one that generates the output "-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.1.0
-- Installed in: /usr/local
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
" on cmake. What I do not get is why the OpenMVGConfig.cmake in /usr/local/share/OpenMVG is being referenced even after I have set "DOpenMVG_DIR:STRING" to a different install of my choice, I have deleted the build directory and tried, its not an issue of cache.

**Comment by rperrot** [comment]
It looks that you already installed it in /usr/local and the find_openMVG look in this path in priority. 

@pmoulon Maybe we have an issue in the order the path are searched ?

**Comment by naveenjafer** [comment]
@rperrot The error turned out to be an issue with the path name being given( one character was missing), once I put in some checks to check if the Directory exists in cmake, I got to know this issue. Its fixed now.
