### ISSUE TITLE
Limiting size in main_ComputeFeatures

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#888]
Hello,

I am processing imagery from a very high resolution camera (8000 x 4300 pixels) and I end up with roughly 50,000 features after running main_ComputeFeatures.

I end up with only  a fraction of these for the actual bundle adjustment after running  main_ComputMatches. I would estimate roughly 5%.

I think the shear size of the Features is creating memory issues when running main_ComputMatches and occasionally it will crash out.

Is there a way of limiting the number of features detected ?
Is there an algorithm I could write that could decimate the features file based on the best features ?
Not sure how this would work.

Regards,

Alan

**Comment by pmoulon** [comment]
You can limit the number of file loaded in memory but it will make the process a bit slower by using the Regions cache.

See `--cache-size X ` on 'main_ComputeMatches' https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeMatches.cpp#L128

Else there no practical way to reduce the number of features in the existing API.
But you can easily limit the number of octaves or the number of features by tweaking the image_describer.

You can:
- process your dataset on reduced images and then use the known geometry to triangulate only the valid tracks and perform the BA -> ComputeStructureFromKnowPoses.

You can:
- reduce the number of octaves:
https://github.com/openMVG/openMVG/blob/master/src/nonFree/sift/SIFT_describer.hpp#L52
- crop the detected regions array to a given number to a given value (16000 features).... in the image_describer
- Keep only the keypoints that belong to the largest octaves (features that are used for preemptive matching in VSFM paper)

There is not a lot of literature about reducing the number of features in the images:
Quad-networks: unsupervised learning to rank for interest point detection. CVPR 2017
paper link: http://people.inf.ethz.ch/sattlert/publications/Savinov2017CVPR.pdf

Predicting matchability. CVPR 2014
http://www.cv-foundation.org/openaccess/content_cvpr_2014/papers/Hartmann_Predicting_Matchability_2014_CVPR_paper.pdf

**Comment by bigakoz** [comment]
Thanks Pierre,

I will try cropping/resize in the regions array.

  void Resize(int maximum)
   {
       if (maximum && vec_feats_.size() > maximum)
       {
           vec_feats_.resize(maximum);
           vec_descs_.resize(maximum);
       }
   }

I will have to work out how to view/sort the octave size I assume in the 
descriptor.

BTW,  I have been asked to process some data from a company called 
SpookFish ( https://www.spookfish.com/).

They have developed high resolution cameras and mount multiple cameras 
on an aircraft (I will look at opengv again). This allows them to 
acquire imagery at high altitude 10

They are having trouble processing the imagery with various software 
they have trialed. I suspect their main problem was they were missing 
EXIF information in the imagery and their camera wasn't in the database 
(no CCD info).

I am doing this as an academic exercise (as part of my thesis). I can 
process some of the data and the results are excellent. I just need to 
sort out this memory issue caused by excessive features and should have  
a good solution for them.

What should I advise them if they want to use this software commercially ?

Alan

**Comment by pmoulon** [comment]
Thank you for your explanation.

Here some more comment:

- You can use your resize trick. Since feature are ordered by increasing scale you can take the first X or the last X.

- You can also make a fast image matching at a tiny image resolution, then use the find pair indexes at high resolution in order to limit the complexity.

- FYI, there is one OpenMVG branch called develop_subposes in which I have made some modification in order to support non central cameras.

- regarding the excessive feature, I really think that a 2 step matching approach should do the trick. One to prune a lot of pair and the other to obtain accurate matches only on the interesting pair.

- if you have GPS data you can also prune a lot of pairs based on the neighborhood.

- About using OpenMVG commercially, for sure you can => The MPL2 license authorize it. See [here](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))
  - They must:
     - Include the OpenMVG Copyright/License files in their EULA
     - Disclose Source of the modified files - (in case of bug fix)
     - Include Original - Explain which version of OpenMVG they are using
     - Any code around OpenMVG can be kept under the license of their choice and they don't need to share it.

MPL2 is a very interesting license since:
- it is not contaminating:
  - allow to people to use the library file and write external proprietary code
- if force to share back to the community any bug fix in order to help to improve the project for anyone.

**Comment by bigakoz** [comment]
Thanks Pierre
It is better to trim the features from the front I assume. Large scale is better ?
I don't know about fast image matching etc. From your second point. Where can I read up about this?
Alan




Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Pierre Moulon <notifications@github.com> Date: 25/04/2017  12:51  (GMT+08:00) To: openMVG/openMVG <openMVG@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Author <author@noreply.github.com> Subject: Re: [openMVG/openMVG] Limiting size in main_ComputeFeatures (#888) 
Thank you for your explanation.
Here some more comment:


You can use your resize trick. Since feature are ordered by increasing scale you can take the first X or the last X.


You can also make a fast image matching at a tiny image resolution, then use the find pair indexes at high resolution in order to limit the complexity.


FYI, there is one OpenMVG branch called develop_subposes in which I have made some modification in order to support non central cameras.


regarding the excessive feature, I really think that a 2 step matching approach should do the trick. One to prune a lot of pair and the other to obtain accurate matches only on the interesting pair.


if you have GPS data you can also prune a lot of pairs based on the neighborhood.


About using OpenMVG commercially, for sure you can => The MPL2 license authorize it. See here

They must:

Include the OpenMVG Copyright/License files in their EULA
Disclose Source of the modified files - (in case of bug fix)
Include Original - Explain which version of OpenMVG they are using
Any code around OpenMVG can be kept under the license of their choice and they don't need to share it.





MPL2 is a very interesting license since:

it is not contaminating:

allow to people to use the library file and write external proprietary code


if force to share back to the community any bug fix in order to help to improve the project for anyone.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openMVG/openMVG","title":"openMVG/openMVG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openMVG/openMVG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmoulon in #888: Thank you for your explanation.\r\n\r\nHere some more comment:\r\n\r\n- You can use your resize trick. Since feature are ordered by increasing scale you can take the first X or the last X.\r\n\r\n- You can also make a fast image matching at a tiny image resolution, then use the find pair indexes at high resolution in order to limit the complexity.\r\n\r\n- FYI, there is one OpenMVG branch called develop_subposes in which I have made some modification in order to support non central cameras.\r\n\r\n- regarding the excessive feature, I really think that a 2 step matching approach should do the trick. One to prune a lot of pair and the other to obtain accurate matches only on the interesting pair.\r\n\r\n- if you have GPS data you can also prune a lot of pairs based on the neighborhood.\r\n\r\n- About using OpenMVG commercially, for sure you can =\u003e The MPL2 license authorize it. See [here](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))\r\n  - They must:\r\n     - Include the OpenMVG Copyright/License files in their EULA\r\n     - Disclose Source of the modified files - (in case of bug fix)\r\n     - Include Original - Explain which version of OpenMVG they are using\r\n     - Any code around OpenMVG can be kept under the license of their choice and they don't need to share it.\r\n\r\nMPL2 is a very interesting license since:\r\n- it is not contaminating:\r\n  - allow to people to use the library file and write external proprietary code\r\n- if force to share back to the community any bug fix in order to help to improve the project for anyone.\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/openMVG/openMVG/issues/888#issuecomment-296905303"}}}

**Comment by pmoulon** [comment]
If you want keep large scale feature yes you have to delete feature at the start.

For the second point, I have no ref. See if just like working at a downscale resolution in order to select image pair for the higher level -> like any multi resolution approach

**Comment by bigakoz** [comment]
Thanks
I will see if I can work it out


Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Pierre Moulon <notifications@github.com> Date: 25/04/2017  13:05  (GMT+08:00) To: openMVG/openMVG <openMVG@noreply.github.com> Cc: bigakoz <alan.buchanan@ashrock.net>, Author <author@noreply.github.com> Subject: Re: [openMVG/openMVG] Limiting size in main_ComputeFeatures (#888) 
If you want keep large scale feature yes you have to delete feature at the start.
For the second point, I have no ref. See if just like working at a downscale resolution in order to select image pair for the higher level -> like any multi resolution approach

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openMVG/openMVG","title":"openMVG/openMVG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openMVG/openMVG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmoulon in #888: If you want keep large scale feature yes you have to delete feature at the start.\r\n\r\nFor the second point, I have no ref. See if just like working at a downscale resolution in order to select image pair for the higher level -\u003e like any multi resolution approach"}],"action":{"name":"View Issue","url":"https://github.com/openMVG/openMVG/issues/888#issuecomment-296908719"}}}

**Comment by pmoulon** [comment]
Closed due to inactivity
