### ISSUE TITLE
Applying Refraction

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#889]
Hello,

I am looking at Imagery that was collected from a flying height of 10,000'.

I would like to apply a refraction correction in the processing. The equation for this is relatively simple.

Is this something you could possibly implement in your processing pipeline ?

As a stop gap method I intend writing a small program that will correct the feature keypoints prior to calling the bundle adjustment but is not the ideal solution as I have to asssume the same flying height for all image points. It should really be applied in the BA using the estimated height of the camera and model point in case the ground has large height differences over the model.

Any suggestions ?

Alan

**Comment by pmoulon** [comment]
The best would be to rectify all your images before launching the processing pipeline.

You can take a look to `main_ExportUndistortedImages` https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ExportUndistortedImages.cpp

**Comment by bigakoz** [comment]
Pierre,

Refraction on oblique imagery requires using the pose angles so i am looking at doing this in the bundle adjustment (apply to observations prior to adjustment).  I may even look at solving for the refraction coefficent in the adjustment which should be possible with ground control. Sometime in the future !

I would then undistort the imagery as well.

I am making progress on this and will share back to the group once I come up with a neat solution.

**Comment by pmoulon** [comment]
Hi @bigakoz 
You can extend a camera model to incorporate the new parameter and let BA estimate it.

Feel free to discuss about your progress and put some references here.

**Comment by csp256** [comment]
I've considered this problem before Bigakoz, but never seriously. (was taking pictures of items under glass at the Rijksmuseum and wanted to recreate them)

Let me know if you get a solution that works to your satisfaction, I would love to read it. (should be publishable too, right?)

**Comment by pmoulon** [comment]
Closed due to inactivity.
