### ISSUE TITLE
compile error on  VS2015 and windows10 

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#890]
The errors are  : 

jpeg.lib(jerror.c.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function output_message
4>tiff.lib(tif_unix.obj) : error LNK2001: unresolved external symbol __imp___iob_func
4>jpeg.lib(jerror.c.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function format_message
4>tiff.lib(tif_getimage.obj) : error LNK2001: unresolved external symbol __imp_sprintf
4>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf

**Comment by pmoulon** [comment]
Can you be more explicit and tell when this error happens?

Everything must compile fine. It run fine for me in Visual Studio2015, windows 15 in 32 and 64 bit

**Comment by wguo68** [comment]
My vs2015 may have some problem due to my test for this problem(http://www.kind-of-works.com/CODE_matching.html).  I am installing and uninstalling vs2010 ,vs2013 and vs2015.

**Comment by wguo68** [comment]
I reinstalled vs2015 and the error is still there:

18>jpeg.lib(jerror.c.obj) : warning LNK4217: locally defined symbol fprintf imported in function output_message
18>tiff.lib(tif_unix.obj) : warning LNK4049: locally defined symbol fprintf imported
18>tiff.lib(tif_dirinfo.obj) : warning LNK4049: locally defined symbol fprintf imported
18>tiff.lib(tif_fax3.obj) : warning LNK4049: locally defined symbol fprintf imported
18>jpeg.lib(jerror.c.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function output_message
18>tiff.lib(tif_unix.obj) : error LNK2001: unresolved external symbol __imp___iob_func
18>jpeg.lib(jerror.c.obj) : error LNK2019: unresolved external symbol __imp_sprintf referenced in function format_message
18>tiff.lib(tif_getimage.obj) : error LNK2001: unresolved external symbol __imp_sprintf
18>tiff.lib(tif_codec.obj) : error LNK2001: unresolved external symbol __imp_sprintf
18>jpeg.lib(jmemmgr.c.obj) : error LNK2019: unresolved external symbol __imp_sscanf referenced in function jinit_memory_mgr
18>tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler
18>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f
18>tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f
18>E:\dev\openMVG_vs2015\Windows-AMD64-\Debug\openMVG_sample_pano_converter.exe : fatal error LNK1120: 6 unresolved externals

**Comment by wguo68** [comment]
The build is very slow on windows 10 and VS2015 and occupy o lot of disk.
I doubt the compile error may be caused by installed anaconda. So I uninstalled the  anaconda and now there are no  any error. The building process has not finished.
