### ISSUE TITLE
Given Poses add observations to Landmark

### ISSUE THREAD

**Issue by prakruti** [openMVG/openMVG#893]
Hi @pmoulon 

Thank you for OpenMVG. I am using the library for a project where I already have the 3D points (without triangulations), camera poses and images and I would like to create a mesh using OpenMVS. 
Since the .json file was more intelligible my current approach is to 

Add "observations" to each 3D point "X" - I plan to do this by creating a Frustum for each view and projecting it back into the image giving me the 2D x. 

Convert from OpenMVG to OpenMVS format and let OpenMVS do its thing. 

My question is 
1. Do I need "id_feat" or can it be a random value? As I have not triangulated these points they do not have an associated feature location / track.
2. How does OpenMVG make the connection about which view the observation came from? In the .json file I can see that this is done using the "key". But the Observation class has only two fields - x and id_feat.
3. Is there any easier way to achieve this?

Thank you!

**Comment by pmoulon** [comment]
Hi @prakruti 
1. You're right in your case id_feat will be useless. These field is use to map feature index in *.feat file. This field is not used during the OpenMVG2OpenMVS export.

2. You will see here that `Landmark` store the 3d position and its view observations. `Observations` is a map that associated its 2d projection for each view that see this point.

So for example if you have a point XX seen by image view 1 and 2 you will have something like:
```
Landmark landmark;
landmark.X = XX;
landmark.obs[1].x = Project XX in view 1
landmark.obs[2].x = Project XX in view 2
```

So in your case you can created a truncated frustum for each view and then test if a 3d point X is visible. If the point is visible you add the view visibility and the 2d point projection.

**Comment by pmoulon** [comment]
Or you can set you  `View`, `Intrinsic` and known camera `Pose` and let `ComputeStructureFromKnowPoses` figure out for you the 3d tracks.

The pipeline would be in this case:
1. set your sfm_data.json (view, intrinsic, pose)
2. compute your features for this sfm_data.json
3. run `ComputeStructureFromKnowPoses` (it will look for corresponding points along the epipolar lines and robustly triangulate the valid correspondences)

**Comment by prakruti** [comment]
Hello
Thanks! I am actually trying out a quick test in Python by editing the sfm_data.json file directly.
I have generated an sfm_data.bin file by running it through the global reconstruction pipeline. As a sanity check I am doing the following 

For a landmark X, and an observation x of the landmark occurring in a view. I project it into the camera, if it exceeds the image bounds - it is not visible. 

This doesn't account for the 3D points actually occluding each other though. Will this cause a problem later on?

**Comment by pmoulon** [comment]
Sorry for the late reply. It should be ok.

**Comment by pmoulon** [comment]
@prakruti Any new feedback?
Can you close the issue?

**Comment by prakruti** [comment]
Yep thank you @pmoulon . The augmenting views method worked. I am considering parallelize it because cycling through all cameras and all points takes a very long time when done naively. If you have any suggestions on that front, it would be great to know!

Thank you for your help!

**Comment by pmoulon** [comment]
For sure you can parallelize.
If you want to minimize the critical section you can feed one structure per thread and merge the results

**Comment by baymin182** [comment]
Hi, I want to make use of the parameters in sfm_data.json to project 3D points into 2d points.I use of the I use the standard formula, but I got a wrong answer. Can you help me?
