### ISSUE TITLE
Merging GPU-based ORB features into OpenMVG

### ISSUE THREAD

**Issue by mdaiter** [openMVG/openMVG#895]
The primary purpose of this "issue" is to list and triage specific features for the merging of ORB (OpenCV-based) into OpenMVG.

For the immediate future, I suggest that we iterate through merging the following files from my `custom` repository:

- [ ] `src/openMVG/features/orb/` (self-contained directory holding most abstractions away from directly using the OpenCV bindings).
- [ ] `src/openMVG/features/image_describer_orb.hpp`. This file serves as the "glue" between the self-contained ORB directory and OpenMVG. I'd like another set of eyes specifically on this file before it becomes merged into OpenMVG to see if we can potentially condense some of the repeated code. I've attempted to keep this file in the style of how previous files were implemented.
- [ ] `src/openMVG/features/features.hpp`. This file just adds some of the includes necessary to reveal ORB on a global scale.
- [ ] `src/software/SfM/main_ComputeFeatures.cpp`. The merge of this file will add support for the binary form of ORB features.

**Comment by pmoulon** [comment]
KORAL will be considered first
