### ISSUE TITLE
query on pose from line algorithms.

### ISSUE THREAD

**Issue by autosquid** [openMVG/openMVG#897]
Hi, are there any  pose from line algorithms such RPnL provided? and if there's any plan on this?

**Comment by pmoulon** [comment]
Feel free to help on this.

There is also this interesting paper:
[Robust and Accurate Line- and/or Point-Based Pose Estimation without Manhattan Assumptions](http://imagine.enpc.fr/~marletr/publi/ECCV-2016-Salaun-et-al.pdf) (ECCV16)

**Comment by autosquid** [comment]
Thanks, I am looking into the two papers you mentioned, and will give them a try in days.

**Comment by pmoulon** [comment]
Thanks you feedback will be really valuable.
It would be nice to consider also some line computer vision paper references there:
https://github.com/openMVG/awesome_3DReconstruction_list

To you want to start to collect the most interesting paper about handling lines for SfM?

**Comment by autosquid** [comment]
aha, I have collected a few related papers. I suppose I can tidy them up and make a RP when ready.
