### ISSUE TITLE
Computing ground point from Camera solution

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#898]
Pierre,

I have a simple problem that I can't work out.

I have a solution that uses oblique imagery and I want to compute the ground coverage of each photograph so I can check the overlap. I am using ECEF coordinates.

From the solution I can get the following.
1. 	const Mat3 R = pose.rotation();
2.	const Vec3 t1 = pose.center();
3.	Vec3 lla = ecef_to_lla(t1(0), t1(1),t1(2));
4. Vec3 enh     - I  convert to E,N,H in another function
5.  I calculate the rotation matrix to go from rotations around ECEF to the Local coordiante system
		  Mat3 Rm;
		  Rm(0, 0) = -sin(lla(1)); Rm(0, 1) = cos(lla(1)); Rm(0, 2) = 0;
		  Rm(1, 0) = -sin(lla(0))*cos(lla(1)); Rm(1, 1) = -sin(lla(0))*sin(lla(1)); Rm(1, 2) = cos(lla(0));
		  Rm(2, 0) = cos(lla(0))*cos(lla(1)); Rm(2, 1) = cos(lla(0))*sin(lla(1)); Rm(2, 2) = sin(lla(0));
		  const Mat3 R2 = R *Rm;  // i.e. Rm

So to calculate the principal point on the ground I have tried this.
Vec3  ray
ray(0) = 0;
ray(1) = 0;
ray(2)  = 10000*0.3048    // 10000 ft in metres

Vec3 ground;
ground = R2*ray;
ground += enh;

Unfortunately this doesn't seem to work.

Any ideas on where I am going wrong ?

Cheers,

Alan

**Comment by pmoulon** [comment]
I don't have any experience about that.
If you have camera poses determined you can certainly compute the intersection of the camera frustum with the ground plane.

**Comment by whuaegeanse** [comment]
compute the outline of the images, then you can compute the overlap of the images.
The method to compute the outline of the image is using  Collinear Condition Equation.When you  know the DEM of ground and the pose of the image, you can compute the outline of each image. And you can compute the intersection of the images.

**Comment by bigakoz** [comment]
Thanks for the response.

My method for converting from a ECEF based coordinate system to a Local system was correct.

I got myself confused with the rotations for the ground point but have managed to stumble my way through.
