### ISSUE TITLE
Installing Debug and Release Builds

### ISSUE THREAD

**Issue by MaXL130** [openMVG/openMVG#905]
Hi openMVG-Team,

I've got a question regarding different build configurations in Visual Studio. I am trying to set up both Debug and Release configurations, but I am facing the issue, that when I build openMVG both in Release and Debug Configuration, I am getting an Debug-Level mismatch.

As far as I could trace down the problem, it seems like openMVG does not differ between Debug and Release Libraries when installing. It just overwrites the already existing files?

How do I face this issue? Should I create two seperate installs, by setting a new prefix? Is there a configuration step in CMake that I missed?

I already noticed, that in your Build-Instruction, there is only the Release Build mentioned. Did I  get something wrong regarding setting up Visual Studio  projects, so that  I can build using Debug configuration, but at the same time use the release build of openMVG?

**Comment by zwn** [comment]
While I don't have a definite answer, I think there is some impedance mismatch between cmake and visual studio - both think they are responsible for setting the active build configuration.

See for example https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L60-L61 where it creates directory with the **cmake default build configuration** in its name (Release in this case) and inside are directories based on **selected/active msvc build configuration**.

I guess the save way is to create a separate build tree for each configuration using cmake. There you can also set a different CMAKE_INSTALL_PREFIX.

**Comment by MaXL130** [comment]
Thanks for your advice. I did two seperate builds and installs, and tried to link my application to one of them, depending on the configuration I want to achieve.

Sadly, there are still some odd things happening. When linking against the Release-install .lib-files, I am able to build my application just fine.

When I link against the Debug configuration, I am getting (and this is completly new) a runtimeLibrary mismatch between my application and the ceres-debug.lib file. So that's what I am currently working on.

One important thing though: It seems like the easyexif.lib is not added to the linker configuration, when using the default CMakeList.txt from the repo. I am currently adding it manually, as it's works for me, for now. I did not yet look into the source of this problem (maybe some bug in the CMake files?), but it's also possible that I messed up somehow.

Would someone mind to validate the problem that I get? (Missing easyexif.lib)

**Comment by pmoulon** [comment]
Hi @MaXL130 
`easyexif` library is exported as a target but not as a OpenMVG library (since it is a third_party library).

So if you link a target to `easyexif` along to `${OpenMVG_LIBRARIES}`, normally the library must be found and usable.

If you want to use release and debug version you have to use two different build and install directories (to ensure no overlap since visual studio and cmake target is not really related).

**Comment by MaXL130** [comment]
Hi @pmoulon 
thats it, thanks, it is finally working! 👍
