### ISSUE TITLE
question: tools to extract pictures from video to feed openMVG_main_SfMInit_ImageListing?

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#906]
Hello,
 Does openMVG contains a binary to extract the pictures from video ? I haven't see one and there is no  option relative to video in openMVG_main_SfMInit_ImageListing.

If you confirm that there is no such tools in openMVG, what tool(s) do you use. ?

Regards

**Comment by jpwhitney** [comment]
ffmpeg works quite well for image extraction from video.

From https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video

-vframes option
Output a single frame from the video into an image file:

ffmpeg -i input.flv -ss 00:00:14.435 -vframes 1 out.png
This example will seek to the position of 0h:0m:14sec:435msec and output one frame (-vframes 1) from that position into a PNG file.

fps video filter
Output one image every second, named out1.png, out2.png, out3.png, etc.

ffmpeg -i input.flv -vf fps=1 out%d.png
Output one image every minute, named img001.jpg, img002.jpg, img003.jpg, etc. The %03d dictates that the ordinal number of each output image will be formatted using 3 digits.

ffmpeg -i myvideo.avi -vf fps=1/60 img%03d.jpg
Output one image every ten minutes:

ffmpeg -i test.flv -vf fps=1/600 thumb%04d.bmp
select video filter
Output one image for every I-frame:

ffmpeg -i input.flv -vf "select='eq(pict_type,PICT_TYPE_I)'" -vsync vfr thumb%04d.png

**Comment by pmoulon** [comment]
Thanks @jpwhitney 

When you are using video you can:
1. use ffmpeg to extract the frame (depending of your speed motion you have to find the right fps)
2. specify the focal (pixels)
3. (optional) you can use the `-v X` option on `main_ComputeMatches` it will match images only on a given overlap and will make the matching faster (but you can loose some loop closure.)

**Comment by alvaro562003** [comment]
thanks @jpwhitney & pmoulon

To install ffmpeg on a windows PC  i  followed the good instructions here: http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/

i run "ffmpeg -i IMG_2112.mov  -vf fps=1/6 img%03d.jpg"  it works very well.

However, there is no more metadata on extracted pictures. 

Is there an alternative tool maintaining the video metadata ?
thanks

**Comment by pmoulon** [comment]
You can use exiftool to insert EXIF metadada

**Comment by alvaro562003** [comment]
thank you pmoulon.

I found the solution of my problem.
Coming with ffmpeg there is another bin called  ffprobe....and it do the job

**Comment by pmoulon** [comment]
Feel free to close the issue ;-)

**Comment by alvaro562003** [comment]
done

**Comment by alvaro562003** [comment]
Indeed, ffmpeg is a powerfull tool
thank for the info
