### ISSUE TITLE
merge two models in openmvg

### ISSUE THREAD

**Issue by ywjia** [openMVG/openMVG#910]
For a same object, I've build two models (i.e., mesh + texture) using openmvg / openmvs, one from a set of aerial photos (S1), and the other from a set of ground-level photos (S2). S1 and S2 have no common images but certainly contain overlapping areas. All the images contain GPS data, but they may not be very reliable.

What are the proper steps for merging them into one single model?

I looked into the discussions in #612 "What is the ideal procedure to merge scenes". The issue there seems to be the same but I could not figure out the exact steps. 

In #612, pmoulon gave 3 suggestions, as below:
(1) take the whole data-set (S1 + S2) and recompute matches & SfM.
(2) register each scene with the GCP.
(3) register each scene using GPS coordinates (by using the binary develop_geodesy).

I tried (1) and got the error message "reference image # has no good images in view" for all the images in S2. The resultant model is basically same as that from S1.

For (2) and (3), I can build the models from the same reference point (see the discussions in #822 "use of GPS info in openMVG"). I can also use GCPs to transform the 3D points in S2 model to the S1 coordinate system. I can then merge the densified point clouds together, but fail to generate the a single mesh. So, what are the exact steps to generate one single model (mesh + texture) to incorporate the images in both S1 and S2? 

Thanks.

**Comment by pmoulon** [comment]
Sorry for the late answer.

Can you please elaborate for (1):
- I think you have this message in OpenMVS and not in OpenMVS
- Did you use GPS non rigid registration for SfM in this case?

**Comment by ywjia** [comment]
@pmoulon Thanks for the reply. I will pose it on OpenMVS as well.

For (1), I did use GPS non-rigid registration in the process, as below. 
Please let me know if I missed anything.

(1) pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"), "-P", "-W", "1.0;1.0;1.0", "-i", input_dir, "-o", matches_dir, "-d", camera_file_params] )

(2) pMatchingPairs = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ListMatchingPairs"),  "-G", "-n", "16", "-i", matches_dir+"/sfm_data.json", "-o", matches_dir+"/pair_list.txt"] )

(3) pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_IncrementalSfM"),  "-P", "-i", matches_dir+"/sfm_data.json", "-m", matches_dir, "-o", reconstruction_dir] )

**Comment by pmoulon** [comment]
Your command line looks good.
