### ISSUE TITLE
openMVG processing of UAV images to create orthomosaic and digital elevation model

### ISSUE THREAD

**Issue by jpwhitney** [openMVG/openMVG#914]
It seems that openMVG is a very powerful set of libraries and features for automated image analysis and reconstruction and would be ideal to make orthomosaics and DEMs.

Can openMVG be configured to create an orthorectified panorama similar to this algorithm [Quasi-Orthorectified Panorama Generation Based on Affine Model from Terrain UAV Images](https://link.springer.com/chapter/10.1007/978-3-662-45646-0_39)?

Also can openMVG be configured to generate a DEM (Digital elevation model) using UAV photos similar to this process outlined here [Generation of accurate digital elevation models from UAV acquired low percentage overlapping images](http://www.tandfonline.com/doi/full/10.1080/01431161.2017.1285085)?

If so I believe openMVG would become even more widely used.  From my understanding of the capabilities of openMVG it seems that adding these features would require some extension of the current capabilities, but perhaps it has already been done and I am just unaware of the options.

**Comment by pmoulon** [comment]
Hi @jpwhitney 
For sure I would be happy to find collaborator (@igorti) to work on implementing similar approaches as the paper you depicted.

OpenMVG provides a lot of basis tool that are used in those paper.
Feel free to try to gather people to work on a given thematic:
- implementing a new pipeline for UAV:
  - generation of orthomosaics
  - generation of DEM

**Comment by mrgloom** [comment]
What is the status of this?

Maybe some external tools (like [openMVS](https://github.com/cdcseacave/openMVS) ?) can be used to build orthophoto and DEM (preferably georeferenced (geoTiff) ).

**Comment by pmoulon** [comment]
The status is that any help to develop some tools related to this is welcomed.

**Comment by jpwhitney** [comment]
I'm really a novice at trying to implement something like this but I think with guidance I could eventually figure it out.  If  [@igorti](https://github.com/igorti) or someone else could take the lead on this I'm more than willing to help with specific tasks.  But initially I would need to have the process spelled out to me.

I'm not sure where to begin with the new UAV pipeline.  @pmoulon any suggestions?

**Comment by igorti** [comment]
@jpwhitney I think that on the openMVG side most of the features you might need should be in place. Have you seen [this example from documentation](https://openmvg.readthedocs.io/en/latest/software/Geodesy/geodesy/#for-sfm-to-xyz-gps-registration)? It shows all steps you need to take in order to restore camera positions and create sparse point cloud.

After that you'll need to do dense reconstruction, meshing, texturing and finally generate orthophoto and dem. I believe you can achieve this with openMVS or MVE+MVS Texturing + orthophoto module from OpenDroneMap. openMVG provides tools to convert its outputs to both openMVS and MVE.

Also, check OpenDroneMap project that has complete pipeline for UAV imagery(although it uses OpenSFM instead of openMVG)

**Comment by mrgloom** [comment]
Can it be done directly from point cloud? something like [direct orthophoto generation from color point clouds of complex scenes](http://www.uav-g.org/Presentations/UAVg_presentation_Skarlatos.pdf)
It will be staightforward to project point cloud to plane, but how to determine plane for orthographic projection?

After we obtain orthomap we can obtain reprojected and georeferenced tiff using `gdal` only thing we should know is affine transform from pixel to gps (also not sure how to obtain it from point cloud).

Also each point from OpenVMG output should be represented as (r, g, b, lat, lon, alt) ?

**Comment by pmoulon** [comment]
Since the answer to the question are provided,I'm closing this issue.
