### ISSUE TITLE
Issues with using Develop branch of openMVG as third party.

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#915]
I have been using the master branch as a third party library in a few machines and it works fine as expected. I recently started using the develop version and I am facing into this warning during cmake and an error ultimately during the make.

Cmake Output
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
** Enable OpenMP parallelization: ON
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.1.0
-- Installed in: /home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- Required CFLAGS: -DOPENMVG_USE_OPENMP
-- ----
-- Build type: Release
-- USING CXXFLAGS = ' -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = '  '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Code taken from Git branch: master
-- Requested component: MPFR
-- Requested component: GMP
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.3") 
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:78 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "openMVG" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done

```
The error on the make is
```

In file included from /home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/include/openMVG/third_party/lemon/lemon/list_graph.h:26:0,
                 from /home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/include/openMVG/third_party/lemon/lemon/dfs.h:26,
                 from /home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/include/openMVG/third_party/lemon/lemon/connectivity.h:22,
                 from /home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/include/openMVG/graph/graph.hpp:12,
                 from /home/naveen/Desktop/cmake_tuts/exploringBB/extras/cmake/helloworld/matchFeatures.cpp:27,
                 from /home/naveen/Desktop/cmake_tuts/exploringBB/extras/cmake/helloworld/openMVG.cpp:3:
/home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/include/openMVG/third_party/lemon/lemon/core.h:25:26: fatal error: lemon/config.h: No such file or directory
 #include <lemon/config.h>
```
I never used to receive this warning during cmake of threads earlier.

Also Something strange that I noticed was that the "/home/naveen/Software/openMVGDev/build-openMVGDev/openMVG_install/share/lemon/cmake/LEMONConfig.cmake" file has a typo? It has a libemon.a instead of liblemon.a, but this same typo was also present in the master branch, fixing the typo did not help either.

@pmoulon Any pointers on the same?

**Comment by naveenjafer** [comment]
This is the output of my cmake when linked with the master branch. The Cmake warning, is not present in this, though my project files that use openMVG as third party are the very same.
```

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
** Enable OpenMP parallelization: ON
The cmake module path - 
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.1.0
-- Installed in: /home/naveen/Software/openMVG_Build3/openMVG_install_2
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- ----
-- Build type: Release
-- USING CXXFLAGS = ' -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = '  '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Code taken from Git branch: master
-- Requested component: MPFR
-- Requested component: GMP
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/naveen/Desktop/cmake_tuts/exploringBB/extras/cmake/openMVGDev_Build
```

**Comment by pmoulon** [comment]
Thanks @naveenjafer 
We are aware of this issue, I have to work on it soon (see [here](https://github.com/openMVG/openMVG/issues/907#issuecomment-300145619))

Please for the moment do
```
find_package(Threads) 
find_package(openMVG)
target_link_libraries(myproject ${OPENMVG_LIBRARIES})
```

**Comment by naveenjafer** [comment]
@pmoulon The issue with lemon.config is still persistent, isnt there any workaround to that?

**Comment by naveenjafer** [comment]
Could the typo here, be causing an issue? But fixing this typo and rebuilding openMVG has also not fixed the issue though.
```

SET(LEMON_INCLUDE_DIR "@CMAKE_INSTALL_PREFIX@/include" CACHE PATH "LEMON include directory")
SET(LEMON_INCLUDE_DIRS "${LEMON_INCLUDE_DIR}")

IF(UNIX)
  SET(LEMON_LIB_NAME "libemon.a")
ELSEIF(WIN32)
  SET(LEMON_LIB_NAME "lemon.lib")
ENDIF(UNIX)

SET(LEMON_LIBRARY "@CMAKE_INSTALL_PREFIX@/lib/${LEMON_LIB_NAME}" CACHE FILEPATH "LEMON library")
SET(LEMON_LIBRARIES "${LEMON_LIBRARY}")

MARK_AS_ADVANCED(LEMON_LIBRARY LEMON_INCLUDE_DIR)

```

**Comment by rperrot** [comment]
@naveenjafer Did you remove the build directory before rebuilding ? (maybe your value was cached and not modified)

**Comment by naveenjafer** [comment]
@rperrot yes, I have done it, I always clean the Folder before rebuilding.

**Comment by naveenjafer** [comment]
The issue is with lemon in my case, and in another machine that I tried, the error is occurring with the eigen package(The config file not found error). The library files are all in place. Not sure what is still causing this issue.

**Comment by rperrot** [comment]
The issue with lemon seems related to a generated file that may have not been exported. 

What is your version of cmake (in both cases : develop and master branch) ?

**Comment by naveenjafer** [comment]
@rperrot I thought the cmake version would be the same across my machine, it is 3.5.1 when I run cmake --version

**Comment by rperrot** [comment]
That's strange since the config.h is exported : 

https://github.com/openMVG/openMVG/blob/master/src/third_party/lemon/lemon/CMakeLists.txt#L76

Can you check that the file really exists in your install directory ?

**Comment by naveenjafer** [comment]
Yes, it is present in the location as expected, and the contents are
#define LEMON_VERSION "1.3"
#define LEMON_HAVE_LONG_LONG 1
/* #undef LEMON_HAVE_LP */
/* #undef LEMON_HAVE_MIP */
/* #undef LEMON_HAVE_GLPK */
/* #undef LEMON_HAVE_CPLEX */
/* #undef LEMON_HAVE_SOPLEX */
/* #undef LEMON_HAVE_CLP */
/* #undef LEMON_HAVE_CBC */
/* #undef LEMON_DEFAULT_LP */
/* #undef LEMON_DEFAULT_MIP */
#define LEMON_USE_PTHREAD 1
/* #undef LEMON_USE_WIN32_THREADS */

**Comment by rperrot** [comment]
Well, this could be related to a missing include_directory in the exported .cmake : 

you show us something like that : 

> SET(LEMON_INCLUDE_DIR "@CMAKE_INSTALL_PREFIX@/include" CACHE PATH "LEMON include directory")
> SET(LEMON_INCLUDE_DIRS "${LEMON_INCLUDE_DIR}")

it seems that the config.h is not present in that configuration. (the path should also include include/openMVG/third_party/) 

I check if I got the same issue on my computer and I come to you soon.

**Comment by rperrot** [comment]
Note : your issue seams strange because lemon may haven't be changed between master and develop branch ... (the CMakeLists looks like the same)

**Comment by naveenjafer** [comment]
@rperrot Yes, lemon version has not changed, its still 1.3 in both. And the Cmake files are the same, I just verified that.

**Comment by naveenjafer** [comment]
@rperrot I have another doubt When running cmake on the master branch of openMVG, I get these
-- EIGEN: 3.2.8 (internal)
-- CERES: 1.12.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.6 (external)
-- LIBPNG: 1.2.54 (external)
-- LIBJPEG (external)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)

There is another project of mine that needed ceres and it was installed, when I built the master branch the last time it worked properly, this time I am getting issues with Ceres, as it is using this external version that is installed globally, how do I force it to use the internal version that comes with openMVG?

This is the error that I am getting
```
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::SolveCholesky(cs_di_sparse*, cs_di_symbolic*, double*)':
cxsparse.cc:(.text+0x56): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x63): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x77): undefined reference to `cs_di_chol'
cxsparse.cc:(.text+0x93): undefined reference to `cs_di_ipvec'
cxsparse.cc:(.text+0x9f): undefined reference to `cs_di_lsolve'
cxsparse.cc:(.text+0xab): undefined reference to `cs_di_ltsolve'
cxsparse.cc:(.text+0xbd): undefined reference to `cs_di_pvec'
cxsparse.cc:(.text+0xc5): undefined reference to `cs_di_nfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::BlockAnalyzeCholesky(cs_di_sparse*, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&)':
cxsparse.cc:(.text+0x1e8): undefined reference to `cs_di_amd'
cxsparse.cc:(.text+0x26a): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x2a6): undefined reference to `cs_di_calloc'
cxsparse.cc:(.text+0x2b6): undefined reference to `cs_di_pinv'
cxsparse.cc:(.text+0x2c6): undefined reference to `cs_di_symperm'
cxsparse.cc:(.text+0x2d3): undefined reference to `cs_di_etree'
cxsparse.cc:(.text+0x2e2): undefined reference to `cs_di_post'
cxsparse.cc:(.text+0x2f6): undefined reference to `cs_di_counts'
cxsparse.cc:(.text+0x301): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x309): undefined reference to `cs_di_spfree'
cxsparse.cc:(.text+0x319): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x32b): undefined reference to `cs_di_cumsum'
cxsparse.cc:(.text+0x33d): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x3bc): undefined reference to `cs_di_sfree'
```

**Comment by rperrot** [comment]
I've just compiled and installed using develop branch. I can't reproduce your cmake warning. But I've got something interesting : 

in the openMVGConfig.cmake I can see that in the OPENMVG_INCLUDE_DIRS the lemon directory pointed is not the install dir but the build dir. So the issue may be here. 

Have a look at the line starting with (that's line 90 in my file but it may be different in your) : 

SET(OPENMVG_INCLUDE_DIRS 

and check if the lemon include is related to the build or to the install directory (that may be the issue).

**Comment by rperrot** [comment]
@pmoulon 

I think there's an issue. in the OpenMVGConfig.cmake.in we've got that : 

`SET(OPENMVG_INCLUDE_DIRS "@OpenMVG_INCLUDE_DIRS@")`

**Comment by naveenjafer** [comment]
The lemon is fine, its pointing to both.
/home/rajas/Desktop/NaveenOpenMVGDev/openMVG_build/install/include/openMVG/third_party/lemon;/home/rajas/Desktop/2NaveenOpenMVGDev/openMVG_Build/openMVG/third_party/lemon

**Comment by naveenjafer** [comment]
@rperrot This is how it is even in the master branch. SET(OPENMVG_INCLUDE_DIRS "@OpenMVG_INCLUDE_DIRS@")

**Comment by naveenjafer** [comment]
@rperrot Any advice on how to fix the above issue with the ceres would be really helpful.

**Comment by rperrot** [comment]
> The lemon is fine 

No there's an issue, they point to the build directory not the install one (see my previous post for pmoulon)

> Any advice on how to fix the above issue with the ceres would be really helpful.

Conflicts with two versions of the same library is almost always a headache (Qt may conflict with libjpeg also), this maybe more ceres and cmake related that openMVG related. 

Perhaps you have to rewrite your CMakeLists to force some inclusion/linking.

**Comment by pmoulon** [comment]
You can force to use internal ceres by commenting some lines:
Comment this line [here](https://github.com/openMVG/openMVG/blob/develop/src/CMakeLists.txt#L258) and do a fresh cmake

**Comment by pmoulon** [comment]
Hi @naveenjafer 
I fix other problems there https://github.com/openMVG/openMVG/issues/917

Did you finally got something working?

**Comment by naveenjafer** [comment]
@pmoulon I got to fix the issue with eigen in one of the machines, and now both the machines are running into issues with lemon in both the dev and master version builds. There is only one lemon version 1.3. I get the same error.

**Comment by naveenjafer** [comment]
@pmoulon I tried it again on a clean installation, things are working fine now :) Thanks a lot.
