### ISSUE TITLE
Is there a C/C++ implementation of Non Rigid SfM 

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#919]
Thanks

**Comment by rperrot** [comment]
In openMVG, not now, but you can bring your skills to add it to openMVG. 

Every contribution is welcome !

**Comment by pmoulon** [comment]
You can do some bibliography search and help us to enhance the https://github.com/openMVG/awesome_3DReconstruction_list for the category (non rigid sfm)

You can start from here https://github.com/vrabaud/sfm_toolbox (matlab)
