### ISSUE TITLE
build error - Windows 10, VS2015

### ISSUE THREAD

**Issue by lab3d** [openMVG/openMVG#921]
Hello, I am trying to build the repository but having hard time with CMake. I am following the instructions from [here](https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD) but CMake GUI is giving me this error. Please help me.
![cmake](https://cloud.githubusercontent.com/assets/28770663/26185125/f134c036-3bc3-11e7-8117-124e5f20cb65.JPG)

Here is log file message generated by cmake:
-------------------------------------------------------------------------------------------------
The system is: Windows - 10.0.14393 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:41 PM.
Project "E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdC\.\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdC.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
Done Building Project "E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.67

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "E:/openMVG/build/CMakeFiles/3.8.0-rc3/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:42 PM.
Project "E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdCXX\.\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "E:\openMVG\build\CMakeFiles\3.8.0-rc3\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.61

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "E:/openMVG/build/CMakeFiles/3.8.0-rc3/CompilerIdCXX/CompilerIdCXX.exe"

Determining if the C compiler works passed with the following output:
Change Dir: E:/openMVG/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_dc7e7.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:43 PM.

Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_dc7e7.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_dc7e7.dir\Debug\".

  Creating directory "E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_dc7e7.dir\Debug\cmTC_dc7e7.tlog\".

InitializeBuildStatus:

  Creating "cmTC_dc7e7.dir\Debug\cmTC_dc7e7.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dc7e7.dir\Debug\\" /Fd"cmTC_dc7e7.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue E:\openMVG\build\CMakeFiles\CMakeTmp\testCCompiler.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_dc7e7.dir\Debug\\" /Fd"cmTC_dc7e7.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue E:\openMVG\build\CMakeFiles\CMakeTmp\testCCompiler.c

  

  testCCompiler.c

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_dc7e7.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_dc7e7.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_dc7e7.lib" /MACHINE:X64   /machine:x64 cmTC_dc7e7.dir\Debug\testCCompiler.obj

  cmTC_dc7e7.vcxproj -> E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_dc7e7.exe

FinalizeBuildStatus:

  Deleting file "cmTC_dc7e7.dir\Debug\cmTC_dc7e7.tlog\unsuccessfulbuild".

  Touching "cmTC_dc7e7.dir\Debug\cmTC_dc7e7.tlog\cmTC_dc7e7.lastbuildstate".

Done Building Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_dc7e7.vcxproj" (default targets).

Build succeeded.

    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.88

Detecting C compiler ABI info compiled with the following output:
Change Dir: E:/openMVG/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_4ff4a.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:44 PM.

Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_4ff4a.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_4ff4a.dir\Debug\".

  Creating directory "E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_4ff4a.dir\Debug\cmTC_4ff4a.tlog\".

InitializeBuildStatus:

  Creating "cmTC_4ff4a.dir\Debug\cmTC_4ff4a.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4ff4a.dir\Debug\\" /Fd"cmTC_4ff4a.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.8\Modules\CMakeCCompilerABI.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4ff4a.dir\Debug\\" /Fd"cmTC_4ff4a.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.8\Modules\CMakeCCompilerABI.c"

  

  CMakeCCompilerABI.c

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_4ff4a.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_4ff4a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_4ff4a.lib" /MACHINE:X64   /machine:x64 cmTC_4ff4a.dir\Debug\CMakeCCompilerABI.obj

  cmTC_4ff4a.vcxproj -> E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_4ff4a.exe

FinalizeBuildStatus:

  Deleting file "cmTC_4ff4a.dir\Debug\cmTC_4ff4a.tlog\unsuccessfulbuild".

  Touching "cmTC_4ff4a.dir\Debug\cmTC_4ff4a.tlog\cmTC_4ff4a.lastbuildstate".

Done Building Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_4ff4a.vcxproj" (default targets).

Build succeeded.

    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.70

Determining if the CXX compiler works passed with the following output:
Change Dir: E:/openMVG/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_80867.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:45 PM.

Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_80867.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_80867.dir\Debug\".

  Creating directory "E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_80867.dir\Debug\cmTC_80867.tlog\".

InitializeBuildStatus:

  Creating "cmTC_80867.dir\Debug\cmTC_80867.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_80867.dir\Debug\\" /Fd"cmTC_80867.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue E:\openMVG\build\CMakeFiles\CMakeTmp\testCXXCompiler.cxx

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_80867.dir\Debug\\" /Fd"cmTC_80867.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue E:\openMVG\build\CMakeFiles\CMakeTmp\testCXXCompiler.cxx

  

  testCXXCompiler.cxx

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_80867.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_80867.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_80867.lib" /MACHINE:X64   /machine:x64 cmTC_80867.dir\Debug\testCXXCompiler.obj

  cmTC_80867.vcxproj -> E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_80867.exe

FinalizeBuildStatus:

  Deleting file "cmTC_80867.dir\Debug\cmTC_80867.tlog\unsuccessfulbuild".

  Touching "cmTC_80867.dir\Debug\cmTC_80867.tlog\cmTC_80867.lastbuildstate".

Done Building Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_80867.vcxproj" (default targets).

Build succeeded.

    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.86

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: E:/openMVG/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_d89be.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:46 PM.

Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_d89be.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_d89be.dir\Debug\".

  Creating directory "E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_d89be.dir\Debug\cmTC_d89be.tlog\".

InitializeBuildStatus:

  Creating "cmTC_d89be.dir\Debug\cmTC_d89be.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d89be.dir\Debug\\" /Fd"cmTC_d89be.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.8\Modules\CMakeCXXCompilerABI.cpp"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d89be.dir\Debug\\" /Fd"cmTC_d89be.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.8\Modules\CMakeCXXCompilerABI.cpp"

  

  CMakeCXXCompilerABI.cpp

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_d89be.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_d89be.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_d89be.lib" /MACHINE:X64   /machine:x64 cmTC_d89be.dir\Debug\CMakeCXXCompilerABI.obj

  cmTC_d89be.vcxproj -> E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_d89be.exe

FinalizeBuildStatus:

  Deleting file "cmTC_d89be.dir\Debug\cmTC_d89be.tlog\unsuccessfulbuild".

  Touching "cmTC_d89be.dir\Debug\cmTC_d89be.tlog\cmTC_d89be.lastbuildstate".

Done Building Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_d89be.vcxproj" (default targets).

Build succeeded.

    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.77

Detecting CXX [] compiler features compiled with the following output:
Change Dir: E:/openMVG/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_bc287.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/18/2017 12:15:47 PM.

Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_bc287.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_bc287.dir\Debug\".

  Creating directory "E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_bc287.dir\Debug\cmTC_bc287.tlog\".

InitializeBuildStatus:

  Creating "cmTC_bc287.dir\Debug\cmTC_bc287.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bc287.dir\Debug\\" /Fd"cmTC_bc287.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue E:\openMVG\build\CMakeFiles\feature_tests.cxx

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bc287.dir\Debug\\" /Fd"cmTC_bc287.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue E:\openMVG\build\CMakeFiles\feature_tests.cxx

  

  feature_tests.cxx

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_bc287.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_bc287.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/openMVG/build/CMakeFiles/CMakeTmp/Debug/cmTC_bc287.lib" /MACHINE:X64   /machine:x64 cmTC_bc287.dir\Debug\feature_tests.obj

  cmTC_bc287.vcxproj -> E:\openMVG\build\CMakeFiles\CMakeTmp\Debug\cmTC_bc287.exe

FinalizeBuildStatus:

  Deleting file "cmTC_bc287.dir\Debug\cmTC_bc287.tlog\unsuccessfulbuild".

  Touching "cmTC_bc287.dir\Debug\cmTC_bc287.tlog\cmTC_bc287.lastbuildstate".

Done Building Project "E:\openMVG\build\CMakeFiles\CMakeTmp\cmTC_bc287.vcxproj" (default targets).

Build succeeded.

    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.85

    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:1cxx_alias_templates
    Feature record: CXX_FEATURE:1cxx_alignas
    Feature record: CXX_FEATURE:1cxx_alignof
    Feature record: CXX_FEATURE:1cxx_attributes
    Feature record: CXX_FEATURE:1cxx_attribute_deprecated
    Feature record: CXX_FEATURE:1cxx_auto_type
    Feature record: CXX_FEATURE:1cxx_binary_literals
    Feature record: CXX_FEATURE:1cxx_constexpr
    Feature record: CXX_FEATURE:1cxx_contextual_conversions
    Feature record: CXX_FEATURE:1cxx_decltype
    Feature record: CXX_FEATURE:1cxx_decltype_auto
    Feature record: CXX_FEATURE:1cxx_default_function_template_args
    Feature record: CXX_FEATURE:1cxx_defaulted_functions
    Feature record: CXX_FEATURE:1cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:1cxx_delegating_constructors
    Feature record: CXX_FEATURE:1cxx_deleted_functions
    Feature record: CXX_FEATURE:1cxx_digit_separators
    Feature record: CXX_FEATURE:1cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:1cxx_explicit_conversions
    Feature record: CXX_FEATURE:1cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:1cxx_extern_templates
    Feature record: CXX_FEATURE:1cxx_final
    Feature record: CXX_FEATURE:1cxx_func_identifier
    Feature record: CXX_FEATURE:1cxx_generalized_initializers
    Feature record: CXX_FEATURE:1cxx_generic_lambdas
    Feature record: CXX_FEATURE:1cxx_inheriting_constructors
    Feature record: CXX_FEATURE:1cxx_inline_namespaces
    Feature record: CXX_FEATURE:1cxx_lambdas
    Feature record: CXX_FEATURE:1cxx_lambda_init_captures
    Feature record: CXX_FEATURE:1cxx_local_type_template_args
    Feature record: CXX_FEATURE:1cxx_long_long_type
    Feature record: CXX_FEATURE:1cxx_noexcept
    Feature record: CXX_FEATURE:1cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:1cxx_nullptr
    Feature record: CXX_FEATURE:1cxx_override
    Feature record: CXX_FEATURE:1cxx_range_for
    Feature record: CXX_FEATURE:1cxx_raw_string_literals
    Feature record: CXX_FEATURE:1cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:1cxx_return_type_deduction
    Feature record: CXX_FEATURE:1cxx_right_angle_brackets
    Feature record: CXX_FEATURE:1cxx_rvalue_references
    Feature record: CXX_FEATURE:1cxx_sizeof_member
    Feature record: CXX_FEATURE:1cxx_static_assert
    Feature record: CXX_FEATURE:1cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:1cxx_thread_local
    Feature record: CXX_FEATURE:1cxx_trailing_return_types
    Feature record: CXX_FEATURE:1cxx_unicode_literals
    Feature record: CXX_FEATURE:1cxx_uniform_initialization
    Feature record: CXX_FEATURE:1cxx_unrestricted_unions
    Feature record: CXX_FEATURE:1cxx_user_literals
    Feature record: CXX_FEATURE:1cxx_variable_templates
    Feature record: CXX_FEATURE:1cxx_variadic_macros
    Feature record: CXX_FEATURE:1cxx_variadic_templates

**Comment by lab3d** [comment]
Here is output from cmake gui

The C compiler identification is MSVC 19.0.24213.1
The CXX compiler identification is MSVC 19.0.24213.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:82 (message):
  

   submodule(s) are missing, please update your repository:
    > git submodule update -i



Configuring incomplete, errors occurred!
See also "E:/openMVG/build/CMakeFiles/CMakeOutput.log".

---------------------------------------------------------------------------------

I also tried the > git submodule update -i command in the openMVG directory but Cmake still gives me the same error.

**Comment by pmoulon** [comment]
Did you checkout openMVG by using git?
Or did you use the Dowload ZIP function from github?

Windows build is ok, it's already tested on the cloud for every new commit.

You can perhaps compare your cmake log to the one of the virtual machine that was used for this build:
https://ci.appveyor.com/project/pmoulon/openmvg/build/1.0.473/job/rb92th2jmfxjqabf

**Comment by lab3d** [comment]
I tried with both by downloading as ZIP first and then by using git. Both gave me same error.

**Comment by pmoulon** [comment]
Ok, the git clone is preferable.

Did you was able to compile even a very simple c++ project with cmake previously?

**Comment by lab3d** [comment]
Yes I have compiled OpenCV previously.

**Comment by pmoulon** [comment]
Can you try with the develop branch?

**Comment by lab3d** [comment]
Thank you for your help. Now I am trying to build it using cmake via cmd and it seems to work. The build is in process  now.
