### ISSUE TITLE
[core] enhance reproducibility - random_generator seed

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#922]
Enhance reproducibility by using the same random number generation between consecutive run:
- [x] Initialize all internal random generator with a default seed:
  - [x] for all robust estimators
  - [x] for the cascade hashing (Hash projection matrix)
- [x] Generate random number in a thread safe manner (one generator per thread)

Misc.
- [x] get rid of every rand() -> used only in the unit test

- [x] merge to develop

**Comment by hugbed** [comment]
I have removed calls to C-style rand() in [this commit](https://github.com/hugbed/openMVG/commit/8c8c6066fd16d60598090cd7230b113a8bbd15cf).

I also have some suggestions for `UniformSample` function about the template types used in [this commit](https://github.com/hugbed/openMVG/commit/8c8c6066fd16d60598090cd7230b113a8bbd15cf) as mentionned [here](https://github.com/openMVG/openMVG/commit/615ec2edef445405558a743ec87c7743f9000a78#commitcomment-22232754)

**Comment by pmoulon** [comment]
Thanks Hugo. I will try to merge them soon.

**Comment by pmoulon** [comment]
Thanks @hugbed 
Merged by https://github.com/openMVG/openMVG/commit/2c652190a70e1bb41251caecc46e67e80e4daa01
