### ISSUE TITLE
make fall in loop?

### ISSUE THREAD

**Issue by Monk-Liu** [openMVG/openMVG#927]
Hei, I am just trying build openMVG. So I followed the [build](https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD). 
However, when I run make,  the make process will be stucked at [98%], give some warning like this

         warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]

and the process will restart from [98%] after several seconds,  and give the same warning. So the make process falls in the loop that restart and  give the same waring..........do yo know what is wrong with that?

**Comment by rperrot** [comment]
Some questions to ensure issue tracking : 
- What branch are you using ? 
- What is your system (Win/Unix/mac) 
- What are your versions of the toolchain used to build (mainly the compiler)

Please note that compilation may take long time (this is taken into account and largely reduced in recent develop commits)

**Comment by pmoulon** [comment]
@Monk-Liu 
Please, share also the cmake output it can be useful to understand your compilation settings.

**Comment by pmoulon** [comment]
@Monk-Liu Any feedback?

**Comment by pmoulon** [comment]
I'm closing the issue since no feedback was provided.
