### ISSUE TITLE
Robust estimation changing with different runs- Incremental SFM

### ISSUE THREAD

**Issue by naveenjafer** [openMVG/openMVG#928]
I am facing issues with running openMVG on the very same dataset of images when run multiple times to test its reliability. I am forcefully setting the initial pairs to simplify the scenario. One of the runs did not work and many other runs did work.

One of the runs
-------------------------------
-- Robust Essential matrix: <1,3> images: 20120919_055937.jpg,20120919_060722.jpg
-- Threshold: 3.52023
-- Resection status: OK
-- Nb points used for robust Essential matrix estimation: 113
-- Nb points validated by robust estimation: 34
-- % points validated: 0.300885

One of the other runs of the very same dataset with same initial pair specified in the Incremental SFM.

-------------------------------
-- Robust Essential matrix: <1,3> images: 20120919_055937.jpg,20120919_060722.jpg
-- Threshold: 4.66345
-- Resection status: OK
-- Nb points used for robust Essential matrix estimation: 113
-- Nb points validated by robust estimation: 113
-- % points validated: 1
-------------------------------

The first one failed in reconstruction and the second one passed. Can someone tell me why?

**Comment by pmoulon** [comment]
Please consider to use the develop branch.

You can also test this WIP branch https://github.com/openMVG/openMVG/tree/develop_random_number_reproducibility

It must help to ensure you will have the same result for various run.
