### ISSUE TITLE
OpenMVG SfM pipelines in 4th step(openMVG_main_IncrementalSfM)

### ISSUE THREAD

**Issue by Suhyeon4780** [openMVG/openMVG#933]
Hello, 

After I successfully finished installing OpenMVG, I was trying to follow process of OpenMVG SfM pipelines. (https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines)
I think I'm missing something, because I just could get 'Reconstruction_Report.html' file after calling 'openMVG_main_IncrementalSfM'. 

this is what I did for each step, I'm surly think I did wrong... 
Can you tell me any mistake in this process, please? 
( I used openMVG_Samples' pictures(2 pictures) whose name are 100_7101.jpg, 100_7102.jpg(SeauxCastle))

-----------------------------------------------------------------------------------------------------------------
C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_SfMInit_ImageListing -d C:\Users\user\Desktop\git\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camer a_database.txt -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\SceauxCastle -o C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
 You called :
openMVG_main_SfMInit_ImageListing
--imageDirectory C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\SceauxCastle
--sensorWidthDatabase C:\Users\user\Desktop\git\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camera_database.txt
--outputDirectory C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
K.txt: Unkown image file format.
Readme.txt: Unkown image file format.

SfMInit_ImageListing report:
listed #File(s): 4
usable #File(s) listed in sfm_data: 2
usable #Intrinsic(s) listed in sfm_data: 0

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_ComputeFeatures -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json -o C:\Use rs\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
 You called :
openMVG_main_ComputeFeatures
--input_file C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json
--outdir C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 17.1397

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_ComputeMatches -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json -o C:\User s\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
 You called :
openMVG_main_ComputeMatches
--input_file C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json
--out_dir C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 3.98859

 - Geometric filtering -

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 8.98952

 Export Adjacency Matrix of the pairwise's geometric matches

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_IncrementalSfM -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json -m C:\User s\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3 -o C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\out_Incremental_Reconstruction3 -a 100_7101.jpg -b 100_7102.jpg
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 959
 Images Id:
0, 1,
------------------
TrackLength, Occurrence
        2       959

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ

-----------------------------------------------------------------------------------------------------------------

I notice that the other people's result have more result after 
------------------
TrackLength, Occurrence
        2       959
this code.. 
In addition, I just could get 'Reconstruction_Report.html' file in 'out_Incremental_Reconstruction3' folder
Did I do correctly these process? If not, what should I add some step?

 

and I did the other way to do same process after seeing this issue 'https://github.com/openMVG/openMVG/issues/805'

-----------------------------------------------------------------------------------------------------------------
C:\Users\user
λ cd C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_SfMInit_ImageListing -d C:\Users\user\Desktop\git\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camer a_database.txt -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\SceauxCastle -o C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
 You called :
openMVG_main_SfMInit_ImageListing
--imageDirectory C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\SceauxCastle
--sensorWidthDatabase C:\Users\user\Desktop\git\openMVG\src\openMVG\exif\sensor_width_database\sensor_width_camera_database.txt
--outputDirectory C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
K.txt: Unkown image file format.
Readme.txt: Unkown image file format.

SfMInit_ImageListing report:
listed #File(s): 4
usable #File(s) listed in sfm_data: 2
usable #Intrinsic(s) listed in sfm_data: 0

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_ComputeFeatures -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4\sfm_data.json -o C:\Use rs\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
 You called :
openMVG_main_ComputeFeatures
--input_file C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4\sfm_data.json
--outdir C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0

- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 20.7335

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_ComputeMatches -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4\sfm_data.json -o C:\User s\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
 You called :
openMVG_main_ComputeMatches
--input_file C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4\sfm_data.json
--out_dir C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 4.07888

 - Geometric filtering -

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 9.04891

 Export Adjacency Matrix of the pairwise's geometric matches

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_IncrementalSfM -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4\sfm_data.json -m C:\User s\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches4 -o C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\out_Incremental_Reconstruction4 -f 1557.6
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).

WARNING: Unknow KEY: 1557.6

- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 929
 Images Id:
0, 1,
------------------
TrackLength, Occurrence
        2       929

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.

C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ
-----------------------------------------------------------------------------------------------------------------

I added '-f 1557.6' (1.1 * max(imageW(1416), image H(1064))) end of  'openMVG_main_IncrementalSfM -i Dataset/matches/sfm_data.json -m Dataset/matches/ -o Dataset/out_Incremental_Reconstruction/'

but I got this error message 'There is no defined intrinsic data in order to compute an essential matrix for the initial pair.' and  I also only got 'Reconstruction_Report.html' file 

I can't find the way to solve this problem. should I put -a 100_7101.jpg -b 100_7102.jpg?? and do I have something to add?

Please I need your advice. Thank you

**Comment by pmoulon** [comment]
1. Please consider to build in Release mode (switch to Release under your Visual Studio)

2. I generally advise people to test first the script `tutorial_demo`

3. You see in the log of openMVG_main_SfMInit_ImageListing `usable #Intrinsic(s) listed in sfm_data: 0`. It means that no exif data or no camera sensor data have been extracted for the sensor camera db. -> In this case you can specify the pixel focal length (see `-f X`, Use X = max(w,h) * 1.2).
 - Can you try with the picture there https://github.com/openMVG/ImageDataset_SceauxCastle?

**Comment by Suhyeon4780** [comment]
Thank you for your help.

but, I have some question when I tried second step that you advised.

I used 'tutorial_demo' with ImageDataset_SceauxCastle pictures. but, I'd like to use my pictures that I want reconstruction.
 how to change the input picture?? Can I just change the source code of 'tutorial_demo.py'?
or Do I have more something to add in the source code?

this is a part of source code.
input_eval_dir = os.path.dirname(os.path.abspath(__file__)) + "/ImageDataset_SceauxCastle"
# Checkout an OpenMVG image dataset with Git
if not os.path.exists(input_eval_dir):
  pImageDataCheckout = subprocess.Popen([ "git", "clone", "https://github.com/openMVG/ImageDataset_SceauxCastle.git" ])
  pImageDataCheckout.wait()

output_eval_dir = os.path.join(get_parent_dir(input_eval_dir), "tutorial_out")

**Comment by pmoulon** [comment]
In order to use your picture, feel free to use prepared script:

- openMVG_Build/software/SfM/SfM_SequentialPipeline.py
- openMVG_Build/software/SfM/SfM_GlobalPipeline.py

To use them simply run:
```
$ cd openMVG_Build/software/SfM/
$ python SfM_SequentialPipeline.py [full path image directory] [resulting directory]
-> i.e. $ python SfM_SequentialPipeline.py ~/home/user/data/ImageDataset_SceauxCastle/images ~/home/user/data/ImageDataset_SceauxCastle/Castle_Incremental_Reconstruction
$ python SfM_GlobalPipeline.py [full path image directory] [resulting directory]
```

**Comment by Suhyeon4780** [comment]
Hello, I also got some problem while trying process that you told me.
Can u please check it? 

I used Windows 7
cd C:\Users\user\Desktop\git\test6\software\SfM 
SfM_SequentialPipeline.py C:\Users\user\Desktop\input_images C:\Users\user\Desktop\sequential_test 

I typed like this followed the role (python SfM_SequentialPipeline.py [full path image directory] [resulting directory])
but, I got this error message..
maybe it has problem with 5. Colorize Structure. but, I not sure why it didn't work... 

This is the result that I tried.

C:\Users\user
λ cd C:\Users\user\Desktop\git\test6\software\SfM

C:\Users\user\Desktop\git\test6\software\SfM
λ SfM_SequentialPipeline.py C:\Users\user\Desktop\input_images C:\Users\user\Desktop\sequential_test
('Using input dir  : ', 'C:\\Users\\user\\Desktop\\input_images')
('      output_dir : ', 'C:\\Users\\user\\Desktop\\sequential_test')
1. Intrinsics analysis
 You called :
C:/Users/user/Desktop/git/test6/Windows-AMD64-Release/Release\openMVG_main_SfMInit_ImageListing
--imageDirectory C:\Users\user\Desktop\input_images
--sensorWidthDatabase C:/Users/user/Desktop/git/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database\sensor_width_camera_database.txt
--outputDirectory C:\Users\user\Desktop\sequential_test\matches
--focal -1
--intrinsics
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
1" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
10" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
11" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
12" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
13" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
14" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
15" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
16" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
17" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
2" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
3" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
3.txt: Unkown image file format.
4" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
5" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
6" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
7" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
8" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
9" model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.


SfMInit_ImageListing report:
listed #File(s): 18
usable #File(s) listed in sfm_data: 17
usable #Intrinsic(s) listed in sfm_data: 0
2. Compute features
 You called :
C:/Users/user/Desktop/git/test6/Windows-AMD64-Release/Release\openMVG_main_ComputeFeatures
--input_file C:\Users\user\Desktop\sequential_test\matches/sfm_data.json
--outdir C:\Users\user\Desktop\sequential_test\matches
--describerMethod SIFT
--upright 0
--describerPreset NORMAL
--force 0
--numThreads 0


- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 99.6343
3. Compute matches
 You called :
C:/Users/user/Desktop/git/test6/Windows-AMD64-Release/Release\openMVG_main_ComputeMatches
--input_file C:\Users\user\Desktop\sequential_test\matches/sfm_data.json
--out_dir C:\Users\user\Desktop\sequential_test\matches
Optional parameters:
--force 0
--ratio 0.8
--geometric_model f
--video_mode_matching -1
--pair_list
--nearest_matching_method AUTO
--guided_matching 0
--cache_size unlimited

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

 - PUTATIVE MATCHES -
Use: exhaustive pairwise matching
Using FAST_CASCADE_HASHING_L2 matcher
Using the OPENMP thread interface

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task (Regions Matching) done in (s): 1.03021
'neato'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

 - Geometric filtering -

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Task done in (s): 0.857649

 Export Adjacency Matrix of the pairwise's geometric matches
'neato'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
4. Do Sequential/Incremental reconstruction
Sequential/Incremental reconstruction
 Perform incremental SfM (Initial Pair Essential + Resection).


- Features Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Track building

Track filtering

Track export to internal struct

Track stats
------------------
-- Tracks Stats --
 Tracks number: 1552
 Images Id:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
------------------
TrackLength, Occurrence
        2       1348
        3       192
        4       12

There is no defined intrinsic data in order to compute an essential matrix for the initial pair.
5. Colorize Structure

The input SfM_Data file "C:\Users\user\Desktop\sequential_test\reconstruction_sequential/sfm_data.bin" cannot be read.
6. Structure from Known Poses (robust triangulation)
Compute Structure from the provided poses

The input SfM_Data file "C:\Users\user\Desktop\sequential_test\reconstruction_sequential/sfm_data.bin" cannot be read.

The input SfM_Data file "C:\Users\user\Desktop\sequential_test\reconstruction_sequential/robust.bin" cannot be read.

**Comment by pmoulon** [comment]
Hi @Suhyeon4780 

By looking to the log we clearly see that your camera model is not registered in the camera sensor database.
```
model "SM-A310N0" doesn't exist in the database
Please consider add your camera model and sensor width in the database.
```

It means that for the next step of the pipeline there is not valid intrinsic data to use to start a reconstruction, and so OpenMVG is unable to compute a initial relative pose to start a 3d reconstruction.

You can solve this problem in various ways:
1. Provide a accurate focal length;
- If you know your camera calibration, you can use the -f X option on `main_SfMInit_ImageListing`. X must be your focal length value in pixels.
- If you don't know, you can provide a default focal value approximation by using the -f X option. Just set X as equal to 1.2 * max(w,h).
2. You can add your camera sensor size to the database:
- add `SM-A310N0;6.28` to the camera database -> `C:/Users/user/Desktop/git/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database\sensor_width_camera_database.txt`

**Comment by pmoulon** [comment]
Closed due to inactivity.
