### ISSUE TITLE
[software] Add support of match file triangulation in ComputeStructureFromKnownPoses

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#936]
ComputeStructureFromKnownPoses is able to compute a structure from a known camera geometry.
Putative matches was computed by guided matching along the epipolar line.

Following the request in https://github.com/openMVG/openMVG/issues/900, a new triangulation mode is added:
- a direct robust triangulation of the tracks built from a match file.

Consequence on the API:
- make SfM_Data_Structure_Computation_Blind and SfM_Data_Structure_Computation_Robust robust to tracks that contain observation of points that belong to a view that do not have intrinsic or pose data
- make SfM_Data_Structure_Computation_Robust::min_required_length an accessible API parameter

**Comment by pmoulon** [comment]
@appyhand I finally take the time to implement your request:
- provide a way to directly robustly triangulate the tracks built from a match file.

Here the way to access to the feature:
```
openMVG_main_ComputeStructureFromKnownPoses 
--direct_triangulation 
-i => your sfm_data.bin/json/xml that contains views, intrinsic and poses
-m => the path where your *.feat and *.desc are stored
-f  => your match file (i.e matches.f.txt)
-o => your output file (i.e sfm_data_triangulation.bin), a ply file will be written too
```

For example on the https://github.com/openMVG/ImageDataset_SceauxCastle dataset I obtain the following:
- direct_triangulation -> 6620 3D points (here tracks that have at least two observations are accepted)
- guided based matches -> 4707 3D points (here only tracks that have a length >= 3 are accepted)

**Comment by appyhand** [comment]
Thanks @pmoulon I will try this today and get back to you.

**Comment by appyhand** [comment]
Direct triangulation works as expected on the few scenes I tried today : the number of tracks and 3D points obtained with direct triangulation is close to what I get with sequential sfm and much higher than guided matching.
Very helpful, thanks !

**Comment by pmoulon** [comment]
Thanks for your feedback!
Will see to merge it to the develop branch to have this new feature included in the next release.

Feel free to help for developing new features or proposing new `nice/must to have` feature.

**Comment by pmoulon** [comment]
@appyhand Merged to develop. It will be available by default in the next release.

**Comment by appyhand** [comment]
@pmoulon, direct triangulation tested ok on develop branch with reference dataset.

**Comment by pmoulon** [comment]
Thx for the testing. Appreciated!
