### ISSUE TITLE
main_ComputeFeatures.cpp

### ISSUE THREAD

**Issue by zhaoziyi006** [openMVG/openMVG#938]
Hi,

I'm a new programmer. I have a silly question. 

How can I run main_ComputeFeatures.cpp separately? What is the input of the .cpp? How do I configure this so that it can run? Do I need to run it in cmd?

Thanks

**Comment by zhaoziyi006** [comment]
Should I just input:  C:\Users\Ziyi\Desktop\openmvg_exe\software\SfM>$ openMVG_main_ComputeFeatures -i [C:\Users\Ziyi\Desktop\sfm_data.json] -o [C:\Users\Ziyi\Desktop\]?

**Comment by shuguohui** [comment]
first run openMVG_main_SfMInit_ImageListing
then run openMVG_main_ComputeFeatures

**Comment by zhaoziyi006** [comment]
Yes, I already have json file. I just run the main_computeFeature separately. My confusion is about the commanding line. Should I type "openMVG_main_ComputeFeatures -i [C:\Users\Ziyi\Desktop\sfm_data.json] -o [C:\Users\Ziyi\Desktop]?" in the cmd?

**Comment by pmoulon** [comment]
Hi @zhaoziyi006 
I advise you to read the doc there: http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines

OpenMVG ship ready to use python script that launch the different tools for your on your image directory.
See here:
http://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

-i always must point to the sfm_data file once the `main_SfMInit_ImageListing` step have been completed

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 
Thank you for your reply. 
Here is my case. I have a set of images and when I input them in SFM, it says the main_computeFeatures.exe doesn't work. However, the sfm_data.json file is already produced by  main_SfMInit_ImageListing.exe. So I just want to look into the main_computeFeatures.cpp to find out why they are broken.
I've tested some other images. They work well, but this set of images can not work.

Thanks!

**Comment by zhaoziyi006** [comment]
My question is that now that I have json file, how can I debug?
I know I should input "$ openMVG_main_ComputeMatches -i [..\matches\sfm_data.json] -o [...\matches]" as a commanding line. But is this complete? Do I need to input some other things before this?

**Comment by pmoulon** [comment]
You can use some existing binaries to debug:
see `openMVG_main_exportKeypoints` in order to plot the detected keypoint per image
see `openMVG_main_exportMatches` in order to see the putative or geometric filtered matches per pair.

You can also check that you have some valid intrinsic camera data in your json file

**Comment by zhaoziyi006** [comment]
{
    "sfm_data_version": "0.3",
    "root_path": "C:/Users/Ziyi/Desktop/James_new",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00850.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 0,
                        "id_intrinsic": 4294967295,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00851.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 1,
                        "id_intrinsic": 4294967295,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00852.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 2,
                        "id_intrinsic": 4294967295,
                        "id_pose": 2
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483652,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00853.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 3,
                        "id_intrinsic": 4294967295,
                        "id_pose": 3
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00854.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 4,
                        "id_intrinsic": 4294967295,
                        "id_pose": 4
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483654,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00855.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 5,
                        "id_intrinsic": 4294967295,
                        "id_pose": 5
                    }
                }
            }
        }
    ],
    "intrinsics": [],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

**Comment by zhaoziyi006** [comment]
{
    "sfm_data_version": "0.3",
    "root_path": "C:/Users/Ziyi/Desktop/James_new",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00850.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 0,
                        "id_intrinsic": 4294967295,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00851.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 1,
                        "id_intrinsic": 4294967295,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00852.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 2,
                        "id_intrinsic": 4294967295,
                        "id_pose": 2
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483652,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00853.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 3,
                        "id_intrinsic": 4294967295,
                        "id_pose": 3
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00854.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 4,
                        "id_intrinsic": 4294967295,
                        "id_pose": 4
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483654,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00855.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 5,
                        "id_intrinsic": 4294967295,
                        "id_pose": 5
                    }
                }
            }
        }
    ],
    "intrinsics": [],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

**Comment by zhaoziyi006** [comment]
This is the json file. I have tested it but it still doesn't work.
Could you help me try with the main_ComputeFeature.exe? Thank you so much!!

**Comment by pmoulon** [comment]
1. You see that you don't have any intrinsic data initialized. I would advise you to rerun openMVG_main_SfMInit_ImageListing with the option `-f 7200` (1.2 * max(w,h) to provide a approximate pixel focal length to the pipeline)

2. Can you tell me why you think that main_ComputeFeature is not working?
You can see if there is some *.feat file produced on your disk
You must expect to see DSC00850.feat, DSC00850.desc, DSC*.feat... in your output directory.

Can you share the log of main_ComputeFeature run with the option `-f 1` in order to force computation?

**Comment by zhaoziyi006** [comment]
{
    "sfm_data_version": "0.3",
    "root_path": "C:/Users/Ziyi/Desktop/James_new",
    "views": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483649,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00850.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 0,
                        "id_intrinsic": 0,
                        "id_pose": 0
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483650,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00851.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 1,
                        "id_intrinsic": 1,
                        "id_pose": 1
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483651,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00852.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 2,
                        "id_intrinsic": 2,
                        "id_pose": 2
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483652,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00853.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 3,
                        "id_intrinsic": 3,
                        "id_pose": 3
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483653,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00854.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 4,
                        "id_intrinsic": 4,
                        "id_pose": 4
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1073741824,
                "ptr_wrapper": {
                    "id": 2147483654,
                    "data": {
                        "local_path": "",
                        "filename": "DSC00855.JPG",
                        "width": 6000,
                        "height": 4000,
                        "id_view": 5,
                        "id_intrinsic": 5,
                        "id_pose": 5
                    }
                }
            }
        }
    ],
    "intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483655,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483656,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483657,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483658,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483659,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483660,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 4085.1063829787236,
                        "principal_point": [
                            3000.0,
                            2000.0
                        ],
                        "disto_k3": [
                            0.0,
                            0.0,
                            0.0
                        ]
                    }
                }
            }
        }
    ],
    "extrinsics": [],
    "structure": [],
    "control_points": []
}

**Comment by zhaoziyi006** [comment]
<img width="707" alt="capture" src="https://cloud.githubusercontent.com/assets/18297042/26662734/0a4692bc-4654-11e7-8a5d-ffb50a69259e.PNG">

**Comment by zhaoziyi006** [comment]
I'm sorry. This is the json file. There are only image_describer and sfm_data two files in the folder. There is no .feat and  .desc file. However, when I ran other set of images, there existed .feat and .desc files.

**Comment by pmoulon** [comment]
So, here my observations:
- You are not using the default SIFT,
- You are not using the default parameter.

Since you said previously:
> I've tested some other images. They work well, but this set of images can not work.

Can you tell me if you have used exactly the same configuration `-p HIGH`, `-m SIFT_ANATOMY`?

- Can you try to rerun with removing the additional option`-p HIGH`, `-m SIFT_ANATOMY`?

From there we will try to understand. (if this dataset have a larger resolution than your previous one it can be a memory reason).

Else to track the problem you can compile in debug and use visual to track where it crash.

**Comment by zhaoziyi006** [comment]
Hi @pmoulon ,
I tried to rerun with removing the additional option-p HIGH, -m SIFT_ANATOMY? It still has the problem. Below is my screenshot on this. 
For previous images, I also run with these options. They work fine.

**Comment by zhaoziyi006** [comment]
<img width="393" alt="capture" src="https://cloud.githubusercontent.com/assets/18297042/26691038/aab5673a-46c9-11e7-9589-dce5c9d28e24.PNG">
<img width="875" alt="capture1" src="https://cloud.githubusercontent.com/assets/18297042/26691037/aab4fca0-46c9-11e7-9b71-4fbdb44d0cb7.PNG">

**Comment by pmoulon** [comment]
Ok, so it can comes from your image.
- Did you previous image dataset got the same image resolution?
- Do you can run this process in debug in order to understand where the crash is happening and why?
- Do you can share me one picture of your dataset in order to let me try to on windows?
- Do you are using a x86 or x64 binary?

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 
The image is too big to attach here. Do you have an email address so I can send you?

The previous images are smaller than these.
How can I run this process in debug? I'm a new programmer in this. 
I input this below in cmd?
C:\Users\user\Desktop\git\test5_2\Windows-AMD64-Release\Debug
λ openMVG_main_ComputeFeatures -i C:\Users\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3\sfm_data.json -o C:\Use rs\user\Desktop\git\openMVG\src\openMVG_Samples\imageData\matches3

Thank you very much!

**Comment by pmoulon** [comment]
You can send it here: openMVG-team@googlegroups.com

For the debugging you can run the debug mode from visual studio or try to launch the process have you done, wait that it crash and then hit the debug button on the prompted window.

**Comment by zhaoziyi006** [comment]
Thank you. I already send  the images to you. The email name is "Issues 938 images".

**Comment by pmoulon** [comment]
Thx, I got it, I will try to test it soon and provide feedback to you.

**Comment by zhaoziyi006** [comment]
Thank you!

**Comment by pmoulon** [comment]
I tested on VStudio 2015 (Release mode) OpenMVG develop branch.
I don't have problems (memory consumption jump up to 1.8G for the feature extraction).

![capture](https://cloud.githubusercontent.com/assets/3235050/26711178/735a4dba-4713-11e7-9be7-87323b0a37fd.png)

See here (top view capture of the produced reconstruction)

Can you try the develop branch?
Did the process crash in debug mode too?

**Comment by zhaoziyi006** [comment]
![image](https://cloud.githubusercontent.com/assets/18297042/26740060/21f0eaf8-47a2-11e7-84bb-bdee7f252157.png)

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 
When I run debug mode, it can not create the directory. Do you think  I run the debug code in the right way?
Thank you!

**Comment by pmoulon** [comment]
Did you made a typo on the input file. I see `fm_data.json` -> perhaps it must be `sfm_data.json`.
Also when you call the bianry you don't need the []
just use
`-i C:\Users\Ziyi\Desktop\match\sfm_data.json -o C:\Users\Ziyi\Desktop\match`

**Comment by zhaoziyi006** [comment]
![image](https://cloud.githubusercontent.com/assets/18297042/26740911/70183a62-47a5-11e7-8eff-fc572942859b.png)

**Comment by zhaoziyi006** [comment]
Hi I corrected the typo. It still can not create directory?

**Comment by zhaoziyi006** [comment]
So in this step, it only requires json file right?

**Comment by pmoulon** [comment]
You're right, only the input json file and the output dir are required.

Strange that it tells that the output dir is not existing.
I mean we are sure that the dir is valid since it contains the json file we give to the `-i` option.

Please remove the '[' ']' in your parameters.

**Comment by zhaoziyi006** [comment]
![image](https://cloud.githubusercontent.com/assets/18297042/26741493/9a7e8020-47a7-11e7-9e97-b4a3fdd7036c.png)

**Comment by zhaoziyi006** [comment]
This time it works!
However, it crashes in debug mode when I use the same set of images I sent you yesterday. Here is the bug.
Thanks!

**Comment by pmoulon** [comment]
Now you will be able to track the bug by yourself and try also with the SIFT_ANATOMY to see if it fails at a similar step...

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 

I ran it using develop branch openMVG. It still has the problem. However, when I used SIFT_ANATOMY and NORMAL sift ,it broke down  at different place.

Another strange thing is that the sfm_data.json produced by SIFT_ANATOMY is different from previous. In intrinsics, it only has 'key 0' but no 'key 1'.....'key5'.  Is this normal? When I produced the sfm_data.json , it comes out warning: Unknown image format. Does this matter?

Thanks!

**Comment by zhaoziyi006** [comment]
Hi @pmoulon

I ran it using develop branch openMVG. It still has the problem. However, when I used SIFT_ANATOMY and NORMAL sift ,it broke down at different place.

Another strange thing is that the sfm_data.json produced by sfmImagelist is different from previous. In intrinsics, it only has 'key 0' but no 'key 1'.....'key5'. Is this normal? When I produced the sfm_data.json , it comes out warning: Unknown image format. Does this matter?

Thanks!

**Comment by pmoulon** [comment]
If you have only on key in the intrinsic is because you are sharing the intrinsic between many view. It's not a problem. You can see that for each view your id_intrinsic will be equal to 0 in your json file.

If `Unknown image format` appears, it must tell you for which file is it (certainly a txt file in the image directory). It's not a problem (by default OpenMVG supports png, tiff, jpeg and pnm files).

**Comment by zhaoziyi006** [comment]
Hi @pmoulon ,

I'm debugging now and I know the line it broke down but I still don't understand why. I plan to use another laptop to have a try to see if it is the problem with my laptop.
And the strange thing is that when I try with normal feature and SIFT features, it breaks at different part.
![image](https://user-images.githubusercontent.com/18297042/27014148-867b0c40-4ec0-11e7-9724-29e0987ba8d8.png)

**Comment by zhaoziyi006** [comment]
Another thing is that it breaks at different line when I use the same code. So it is way hard to track the error.
Like this time, it broke at a new line. It seems like to be a memory issue.
![image](https://user-images.githubusercontent.com/18297042/27014484-c3323440-4ec7-11e7-8be2-5d228b0daa49.png)

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 

I wonder it is because there are too many feature points in those images. Is there an option in Imagelisting that I can reduce the number of feature points?
Another question is that when I try to test the openMVG_main_SftInit_ImageListing on another laptop, it doesn't produce sfm_data.json. But there is no error in the prompt window. Have you ever had such problems before?

Thanks!

**Comment by pmoulon** [comment]
> I wonder it is because there are too many feature points in those images. Is there an option in Imagelisting that I can reduce the number of feature points?
- you can reduce the image size (batch resize of all your image)

> Another question is that when I try to test the openMVG_main_SftInit_ImageListing on another laptop, it doesn't produce sfm_data.json. But there is no error in the prompt window. Have you ever had such problems before?
- I never encountered that. Does the process is closed without crashing?

**Comment by zhaoziyi006** [comment]
Yes, it closed without crashing and no sfm_data.json is produced.

**Comment by zhaoziyi006** [comment]
I guess it is due to the number of feature points but I'm not sure. Could you tell me whether there is a file recording the features of an image?
The good news is that when I resize the image, it can run.

**Comment by zhaoziyi006** [comment]
Hi @pmoulon 
Thank you so much for your help. I think it is due to the large number of feature points. 
One last question: do you have any advice on how to solve this when we encounter an image containing too many feature points?

Thanks!

**Comment by pmoulon** [comment]
First of all can we summarize the details about the computer and the settings your are using:
- 32/64 bits
- which compiler? (seems like you are using VisualStudio)
- how much ram your computer is having?
- which OpenMVG branch are you using (master, develop)?
- can you share the output of the cmake when you run configure for the first time (in order to understand if your are using all internal module of OpenMVG or if your configuration use some external modules)?

Since I was able to process your image without trouble on my windows computer, I think it can be related to a memory reason.

- Finally did you see the memory near to be full when you see a crash?

**Comment by zhaoziyi006** [comment]
My computer is 64bits, Visual studio 2015 community, 8GB RAM. I'm using develop branch. I use all the internal modules (I have checked once)

When  I run those images, it took about 1.8G RAM and crashed. However, when I resized the images, it worked fine. It took about 0.7G RAM for the resized images.

**Comment by pmoulon** [comment]
Are you sure you compiled OpenMVG in 64bit (x64 in visual studio)?

Using more that 1.8G of RAM must not make the process crash.

**Comment by zhaoziyi006** [comment]
Oh my laptop is 64bit but I compiled it using x32 in VS

**Comment by pmoulon** [comment]
Please select Visual Studio Win64 in CMake when you configure for the first time and everything will run fine ;-)

**Comment by zhaoziyi006** [comment]
OK, I'll try that. Thank you!

Could you explain it briefly why when I select x64, it will run fine?
Thanks again!

**Comment by pmoulon** [comment]
A win32/x86 application have a dedicated space for memory allocation that is smaller than x64 application.

See [here](https://www.viva64.com/en/k/0036/) for a ref.

**Comment by zhaoziyi006** [comment]
Thank you!

**Comment by pmoulon** [comment]
You're welcome, please close the issue once you have verified that compiling and running the x64 binary is working. Feel free to ask more questions if you need too ;-)

**Comment by zhaoziyi006** [comment]
OK, I will! Thanks!
