### ISSUE TITLE
errors when including openMVG as third library

### ISSUE THREAD

**Issue by logmove** [openMVG/openMVG#944]
Hi, 
I can compile the openMVG following the guideline in BUILD, and can also run the tutorial_demo.py successfully. However, when I write a simple .cpp to include the library, it reports lots of errors. 
This is my .cpp
`#include "openMVG/numeric/numeric.h"
int main(){
    return 0;
}`
This is my CMAKE  
`CMAKE_MINIMUM_REQUIRED( VERSION 2.8 )
PROJECT( sfm )
SET( CMAKE_CXX_COMPILER "gcc")
find_package(OpenMVG REQUIRED)
include_directories(${OPENMVG_INCLUDE_DIRS})
add_executable(main main.cpp)
TARGET_LINK_LIBRARIES(main ${OPENMVG_LIBRARIES})`

CMAKE can find the package, but many errors arise when compiling
![image](https://user-images.githubusercontent.com/29305317/26975026-a7d45cf0-4d50-11e7-8cf3-4e4435acee90.png)

Can any one help? Thanks.

**Comment by pmoulon** [comment]
This is strange since `Vec` is defined here https://github.com/openMVG/openMVG/blob/master/src/openMVG/numeric/numeric.h#L140

Can you check that the cmake variable `${OPENMVG_INCLUDE_DIRS}` contains the Eigen include dir?

**Comment by logmove** [comment]
Thanks for your reply. `${OPENMVG_INCLUDE_DIRS}` is correct. 
It raise a "expected nested-name-specifier" error below; I think it might be because my gcc can not compile C++11. But the version of my gcc is 4.8.4 which is higher than required in BUILD.
![image](https://user-images.githubusercontent.com/29305317/26978851-7996e31c-4d5f-11e7-90e0-ed59e19ebf5c.png)

**Comment by logmove** [comment]
It is because of c++11. I add a line of "add_definitions(-std=c++11)" into cmake and it works.

**Comment by pmoulon** [comment]
You can also use the cmake way to configure c++11 support:
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```
