### ISSUE TITLE
"src" path is wrong in cmake parameters (BUILD file)

### ISSUE THREAD

**Issue by biesseck** [openMVG/openMVG#947]
I found a small error when trying to compile openMVG because "src" path is wrong in cmake parameters at lines 58, 60, 68, 72, 113 and 115. If terminal is pointing to "openMVG_Build" folder then cmake should find source files in "../src" instead of "../openMVG/src".

As I understand those lines should be written as:
58: $ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../src/
60: $ cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . ../src/
68:     . ../src/
72: $ cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE . ../src/
113: $ cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Xcode" . ../src/
115: $ cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON -G "Xcode" . ../src/

I hope this helps!

**Comment by pmoulon** [comment]
I never put the build folder in the openMVG folder.
```
$ git clone --recursive https://github.com/openMVG/openMVG.git
$ mkdir openMVG_Build
$ cd openMVG_Build
$ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
```

so at the end I have
```
openMVG # the checkout folder (in which you have ./src)
openMVG_Build # the build folder
```

**Comment by biesseck** [comment]
Yes, you're right, I'm sorry. My eyes didn't see the "cd .." command, that is it!

**Comment by pmoulon** [comment]
No problem we appreciate that people provide feedback ;-)
