### ISSUE TITLE
Sony X1000V focal 

### ISSUE THREAD

**Issue by vixxtor** [openMVG/openMVG#948]
Hello,

Sorry for a (probably) stupid question. I am trying to compute the focal length in pixels to use in OpenMVG with still frames from a Sony X1000V ( https://www.cnet.com/products/sony-4k-action-cam/specs/ ) 1920x1080 video.

The formula, as quoted here ( http://openmvg.readthedocs.io/en/latest/software/SfM/SfMInit_ImageListing/ ) is:

focalpix = max(wpix,hpix)*focalmm/ccdwmm

Now:
wpix=1920
hpix=1080
focalmm=? Is it 2.8mm (because it has F2.8, or is it  f = 21.8 mm (120°))?
ccdwmm=? the sensor is 1/2.3", so is it 6.17mm*4.55mm

if focalmm=2.8, then focalpix=1920*2.8/6.17=871
if focalmm=21.8, then focalpix=6783

With focalpix=6783 the results were pretty bad, but maybe I have set something wrong. 

I have obtained better results with 2304 or 2112 (1920x1.2 or 1920x1.1, empirically recommended by somebody on a different thread).

Now I'm also trying with 871 and keep you updated.

**Comment by pmoulon** [comment]
Hi @vixxtor,
There is no stupid question ;-)

Thanks you for your investigation and report about that.

The sensor of your camera have a size of 1/2.3". So, It's sensor width size is probably 6.17 mm.
I'm not sure about the focal of your lens, since the datasheet say "Min Focal Length 2.8 mm".
So you will have `focalpix = max(wpix,hpix)*focalmm/ccdwmm = 1920 * 2.8 / 6.17 = 871`

Often you can also compute an approximate focal length following this rules:
`focalpix = max(wpix, hpix) * 1.2 = 1920 * 1.2 = 2304`

Since we don't know really the used focal length, I think it explain why a focal guess worked better than the manual computation (because we used a wrong focal, I mean it's not the focal that the camera was using during your shooting).

The other point is that those camera have often a very particular lens (that have very short focal length.) So often is often better to calibrate the camera first with an initial guess and then use the found parameter on any new scene you are processing. (You can edit and update the value in the sfm_data.json file ;-) )

PS: Later on we can check if the FishEye camera model can better fit your camera lens or not.

**Comment by vixxtor** [comment]
Hi, 
In the end, -f 2304 is the best. 871 gave some crappy results, with huge spikes completely out of context. 

This is the script that I am running:
#0. Intrinsics analysis
	/usr/local/bin/openMVG_main_SfMInit_ImageListing -i /home/victor/small -o /home/victor/smallw/matches -d /usr/local/share/openMVG/sensor_width_camera_database.txt -f 2304
#1. Compute features
	/usr/local/bin/openMVG_main_ComputeFeatures -i /home/victor/smallw/matches/sfm_data.json -o /home/victor/smallw/matches -m SIFT -n 16 -p HIGH
#2. Compute matches
	/usr/local/bin/openMVG_main_ComputeMatches -i /home/victor/smallw/matches/sfm_data.json -o /home/victor/smallw/matches
#3. Incremental reconstruction
	/usr/local/bin/openMVG_main_IncrementalSfM -i /home/victor/smallw/matches/sfm_data.json -m /home/victor/smallw/matches -o /home/victor/smallw/reconstruction_sequential
#4. Colorize Structure
	/usr/local/bin/openMVG_main_ComputeSfM_DataColor -i /home/victor/smallw/reconstruction_sequential/sfm_data.bin -o /home/victor/smallw/reconstruction_sequential/colorized.ply
#5. Structure from Known Poses
	/usr/local/bin/openMVG_main_ComputeStructureFromKnownPoses -i /home/victor/smallw/reconstruction_sequential/sfm_data.bin -m /home/victor/smallw/matches -f /home/victor/smallw/matches/matches.f.bin -o /home/victor/smallw/reconstruction_sequential/robust.bin
#6. Colorized robust triangulation
	/usr/local/bin/openMVG_main_ComputeSfM_DataColor -i /home/victor/smallw/reconstruction_sequential/robust.bin -o /home/victor/smallw/reconstruction_sequential/robust_colorized.ply
#7. Export to openMVS
	/usr/local/bin/openMVG_main_openMVG2openMVS -i /home/victor/smallw/reconstruction_sequential/sfm_data.bin -o /home/victor/smallw/mvs/scene.mvs -d /home/victor/smallw/mvs
#8. Densify point cloud
	/usr/local/bin/OpenMVS/DensifyPointCloud scene.mvs -w /home/victor/smallw/mvs
#9. Reconstruct the mesh
	/usr/local/bin/OpenMVS/ReconstructMesh scene_dense.mvs -w /home/victor/smallw/mvs
#10. Refine the mesh
	/usr/local/bin/OpenMVS/RefineMesh scene_dense_mesh.mvs -w /home/victor/smallw/mvs
#11. Texture the mesh
	/usr/local/bin/OpenMVS/TextureMesh scene_dense_mesh_refine.mvs -w /home/victor/smallw/mvs

Would there be anything that I can improve in order to get better results? Like something else instead of SIFT for example? Which are the settings for maximum rendering quality?

P.S. The camera is an obvious fisheye, with 120 angle (with stabilization) and 170 degrees without stabilization. But -c5 didn't help in any obvious way. Maybe I should set some other parameters too?

Thanks,
Victor

**Comment by vixxtor** [comment]
P.P.S. I have setup a dedicated machine just for testing openMVG/MVS. So if you want, I can even give you direct access to it if you want to test for real what I am getting from those images.

**Comment by vixxtor** [comment]
Just to give you an idea, this is what I'm getting with f 2304:
![screenshot at 2017-06-15 22-45-47](https://user-images.githubusercontent.com/7295475/27198806-7883e81e-521c-11e7-80b0-3825d9868d98.png)

**Comment by vixxtor** [comment]
And this is with f 2112 (a little better). In both cases, the floor - a plain tiled floor - looks very wavy, but the main object (the shoe itself) was pretty much alright.
![screenshot at 2017-06-15 22-47-29](https://user-images.githubusercontent.com/7295475/27198878-b7b3ba8c-521c-11e7-88dd-e315f2e6c547.png)

**Comment by pmoulon** [comment]
I assume the floor is not really textured.

**Comment by csp256** [comment]
> There is no stupid question ;-)

Is that a challenge?

**Comment by pmoulon** [comment]
Did you try on some other objects?
