### ISSUE TITLE
how to compute normalized gradient of BA? 

### ISSUE THREAD

**Issue by shuguohui** [openMVG/openMVG#955]
these days,i am implementing the Distributed Bundle Adjustment from this paper :
"A Consensus-Based Framework for Distributed Bundle Adjustment",
the author said that : Convergence is achieved once the magnitude of the normalized gradient
of  BA formulation is less than 1.0e-3,
but i don't known how to  normalize the  gradient of BA? is it mean normalized the data like pba code( function NormalizeDataD and NormalizeDataF)?
can somebody help me?

**Comment by pmoulon** [comment]
Hi,
I would like be able to help but before digging inside the paper...
Did you tried to ask the authors?

**Comment by pmoulon** [comment]
Closed due to inactivity.
@shuguohui any comments?
