### ISSUE TITLE
openMVG::image::ReadImage() slower when using from external code

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#956]
I am trying to use openMVG as a base for my own external code, so I have installed and specified openMVG as a third party dependency in my project. As part of this, when I am trying to read in an image, I notice that it takes much longer from external code such as this. For instance, this simple code:

```
#include "openMVG/image/image.hpp"
#include "openMVG/system/timer.hpp"

using namespace openMVG;
using namespace openMVG::image;

int main(int argc, char **argv)
{
  Image<unsigned char> imageGray;
  const std::string imageFile = "/home/sai/Desktop/UT_SIFT/baseline1.jpg";
  system::Timer timer;
  if (!ReadImage(imageFile.c_str(), &imageGray))
    std::cout << "Unable to read image" << std::endl;
  std::cout << "Read operation took: " << timer.elapsedMs() << "  ms" << std::endl;    
  return 0;
}
```

tells me that the image reading operation is taking around 800 ms. On the other hand, if I put a timer around ReadImage() in openMVG's native ComputeFeatures.cpp code, I see that the image reading takes only 15-20 ms there. Out of curiosity, I replicated the entire ComputeFeatures code as an external file: and everything works the same except for ReadImage(), which still takes way longer than it should. What could be the reason for this difference when using openMVG as a third party library?

**Comment by pmoulon** [comment]
Did you check if you compiled everything in release mode?

Did you check which JPG library is used for both cases?

@rperrot Any ideas on this?

**Comment by saihv** [comment]
Yes, openMVG was compiled in Release. I was using it on linux, so I believe there's no image library conflicts as I only have the default libraries installed: but just in case, is there a way to check that?

**Comment by pmoulon** [comment]
Using `ldd YOURBINARY`

**Comment by rperrot** [comment]
I think it's related to the usage of the external lib instead of the compiled one (or inverse). On OS X I got sometimes link issues, I suggest using ldd as @pmoulon said to identify which library is used.

**Comment by saihv** [comment]
I checked with ldd, and both my binary and openMVG's binary link to the same jpeg library (libjpeg).

**Comment by saihv** [comment]
Sorry, I just checked and my code wasn't in Release. I thought specifying CMAKE_BUILD_TYPE=Release only for openMVG would be sufficient, but I had to specify it for my code as well, and that fixed the problem. Thanks for the help!

**Comment by pmoulon** [comment]
Was about to say the same ;-)
"Did your new project is compiled in RELEASE?"
=> Cmake default mode is not release.
Be sure to use that in your project cmake command line `-DCMAKE_BUILD_TYPE=RELEASE`
