### ISSUE TITLE
Unable to run ComputeStructureFromKnownPoses when using custom feature matches

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#958]
Hi,

I've built a feature matcher and wanted to integrate it with openMVG. The matcher provides unfiltered matches and writes to a `matches.putative.txt` file, which is then read by openMVG's `ComputeMatches` binary for geometric filtering. It seems to work and output a `matches.f.bin` file that is read by `IncrementalSfM`. `IncrementalSfM` outputs a histogram of track lengths which seems right, and also outputs that all input images were successfully calibrated (full output [here](https://gist.github.com/ssampang/83f42bb7f51063dd80576f0ac598415b)).

The problem arises with `ComputeStructureFromKnownPoses`, which seems to have trouble reading the data from the previous stages (output [here](https://gist.github.com/ssampang/53de073c2c9c0208d79c7a62b031fd88)). Contrast this to running `ComputeStructureFromKnownPoses` after using openMVG's `ComputeMatches` for feature matching (output [here](https://gist.github.com/ssampang/fb96e515fdb187ee7e95d6c6d1aaeac5)).

Any clues on what I'm doing wrong?

**Comment by pmoulon** [comment]
I would suggest to you to use the `exportMatches` binary in order to see how your matches looks.

**Comment by ssampang** [comment]
Could you clarify how I would use the svg outputs of `exportMatches`? My understanding is that each svg file represents a pair of images that had matches, and that the verification needed would be to visualize these matches and see if there was anything obviously wrong. Is there another binary that can do the visualization? No problem if there isn't - I can create a python script. I just wanted to ask before doing the work :) 

I've actually already verified that the output of my code looks ok by visualizing the matches between a sample pair of images. Furthermore, the total # of matches that my code produces is in the same ballpark as what's produced by openMVG's computeMatches. The same can be said for the list of filtered matches between the two matching algorithms (ie. customMatcher->openMVG filtering produces a similar number of total matches as openMVG matcher ->openMVG filtering). 

Finally, the histogram of feature tracks that IncrementalSfM outputs seems to indicate that the matches are valid. Is it possible for IncrementalSfM to show a histogram that seems correct and also output that it successfully calibrated all input images if the matches were incorrect?

**Comment by ssampang** [comment]
Made some headway on this problem - I have two versions of my matcher. One reads all .desc files in a directory using boost, while the other takes the sfm_data.json file as input and reads the images in the ascending order of their "keys". In both cases, the algorithm computes the feature matches of the descriptor file that was read last against all previous descriptor files.

The openMVG pipeline works when my matcher reads files the first way, but ComputeStructureFromKnownPoses fails when my matcher reads files in the second way. I've confirmed that in both ways, my matcher outputs the same number of image pairs. One difference I've noticed is that my matcher outputs about 50k fewer matches with the first method.

**Comment by ssampang** [comment]
@pmoulon Could you help me understand how match pairs are decided? Given an image pair (I,J), how is it decided whether the matches file contains matches for (I,J) or whether it contains matches for (J,I)? I see in `src/openMVG/matching_image_collection/Pair_Builder.hpp` there exists a `exhaustivePairs` function which does a simple loop:
```
  for (IndexT I = 0; I < static_cast<IndexT>(N); ++I)
    for (IndexT J = I+1; J < static_cast<IndexT>(N); ++J)
      pairs.insert(std::make_pair(I,J));
``` 
However, the matches file that I see from openMVG contains pairs (I,J) where I>J. I am using exhaustive matching btw.

**Comment by ssampang** [comment]
I can now confirm that changing the order that my matcher reads the files in (and thus sets up the pairwise matches) allows me to run the rest of the openMVG pipeline successfully (using the results of my feature matcher). It could still be a suboptimal set of pairs though (since the order of the pairs ie. (I,J) or (J,I) seems to affect the openMVG pipeline somehow), so it would be great if you could offer insight on how I should be setting up the pairs Pierre :)

**Comment by pmoulon** [comment]
@ssampang I think that most of the pair we are using are in increasing order => I < J
But OpenMVG normally is order agnostic to the pair order, I mean you can provide any pair index and then the image_collection_matcher will deal with it.

> However, the matches file that I see from openMVG contains pairs (I,J) where I>J. I am using exhaustive matching btw.
It's strange that you see that some pairs have been swapped. Are you sure that it's not due to your changes in the library.

I noted that you speak about some implementation your made yourself in order to use boost to read your data. I hope that you have used the existing abstraction over the various data provider ;-)

**Comment by ssampang** [comment]
Sorry for the delay Pierre.

I ran a quick experiment to verify my hypothesis. I changed line 30 of `src/openMVG/matching_image_collection/Pair_builder.hpp` from `pairs.insert({I,J});` to `pairs.insert({J,I});`, and ran `software/SfM/SfM_SequentialPipeline.py` on a set of images. This seems to result in a few differences, but I'd like to point out the two main ones: This is the diff of output of `ComputeStructureFromKnownPoses`:
Normal ({I,J}):
```Structure estimation took (s): 13.

#landmark found: 57424
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 147
 #poses: 147
 #intrinsics: 1
 #tracks: 57424```

Swapped ({J,I}):
```Structure estimation took (s): 3.

#landmark found: 0
...Generating SfM_Report.html
Found a sfm_data scene with:
 #views: 147
 #poses: 147
 #intrinsics: 1
 #tracks: 0```

Additionally, the resulting robust.bin and robust.ply files are far smaller when the pair orders are swapped. These symptoms are pretty much identical to those I was facing when using my custom feature matcher. 

Would you say this was a valid test? Im not sure if this interferes with other areas of the code, but it doesn't seem to. I think it'd be faster for you to try and reproduce this with a test set of your own, but let me know if that doesn't work.

**Comment by ssampang** [comment]
Just confirmed that I get the same results on the `develop` branch

**Comment by ssampang** [comment]
@pmoulon have you had time to look into this? :)

**Comment by pmoulon** [comment]
Not yet. I got some vacation recently ;-)

I will try check that during the week.

**Comment by ssampang** [comment]
have a good vacation 🙌

**Comment by pmoulon** [comment]
Closing due to lack of feedback. Feel free to reopen
