### ISSUE TITLE
Potential bug when parallelizing ComputeFeatures

### ISSUE THREAD

**Issue by ssampang** [openMVG/openMVG#959]
Hi,

I've tried my best to verify that this isn't an issue with my own code or anything by downloading a fresh copy of openMVG and using it to double check. Whenever I run `ComputeFeatures` with the `-n`parameter, I noticed that the descriptors (`.desc`) files for some images contained the exact same descriptors ie. `diff 1.desc 10.desc` produced no output. Consequently, `ComputeMatches` would generate a long list of feature matches between images that were matching identical features. This seemed to be completely resolved when I omitted the `-n` parameter. 

I'm running openMVG on a c4.4xlarge isntance on AWS, and I was using AKAZE_MLDB descriptors with the NORMAL setting. Please let me know if you need additional details, or if I'm making a mistake :)

**Comment by pmoulon** [comment]
Thank you for your additional test.
Are you sure you have used the develop branch?

Did you have the same behavior with SIFT?

**Comment by ssampang** [comment]
I was testing on the master branch. I've confirmed that this is still a problem when using SIFT on the master branch, but is not a problem when using SIFT on the develop branch. I'm running into issues testing with AKAZE_MLDB on the develop branch.

**Comment by pmoulon** [comment]
In order to better understand whats going on can you try also with AKAZE_FLOAT and SIFT_ANATOMY (develop branch)?

**Comment by ssampang** [comment]
SIFT_ANATOMY seems to work (valid feature descriptors), but AKAZE_FLOAT errors out like AKAZE_MLDB. Specifically, I'm getting a `cereal::Exception` and a core dump.

**Comment by pmoulon** [comment]
Do you have more explicit `cereal` message (I mean often the exception message is reported)?
Did it happens in your code or when you launch the `ComputeFeatures` binary?

**Comment by ssampang** [comment]
I called: 
```
~/openmvg/build/Linux-x86_64-Release/openMVG_main_ComputeFeatures -i testJob/scratch/matches/sfm_data.json -o testJob/scratch/matches/ -m AKAZE_FLOAT -p NORMAL -f 1 -n 4
```
Output:
```
 You called : 
/home/ubuntu/openmvg/build/Linux-x86_64-Release/openMVG_main_ComputeFeatures
--input_file testJob/scratch/matches/sfm_data.json
--outdir testJob/scratch/matches/
--describerMethod AKAZE_FLOAT
--upright 0
--describerPreset NORMAL
--force 1
--numThreads 4

terminate called after throwing an instance of 'cereal::Exception'
  what():  Trying to save an unregistered polymorphic type (openMVG::features::AKAZE_Image_describer_SURF).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.
Aborted (core dumped)
```

**Comment by pmoulon** [comment]
This is a bug that can be fixed this way:
Add
```
CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Image_describer_SURF, "AKAZE_Image_describer_SURF");
CEREAL_REGISTER_POLYMORPHIC_RELATION(openMVG::features::Image_describer, openMVG::features::AKAZE_Image_describer_SURF)

CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Image_describer_MLDB, "AKAZE_Image_describer_MLDB");
CEREAL_REGISTER_POLYMORPHIC_RELATION(openMVG::features::Image_describer, openMVG::features::AKAZE_Image_describer_MLDB)
```
in https://github.com/openMVG/openMVG/blob/develop/src/openMVG/features/image_describer_akaze_io.hpp#L34

I will push the fix to develop in the coming days.

**Comment by ssampang** [comment]
That fixes it. Thanks!

**Comment by pmoulon** [comment]
Fixed by https://github.com/openMVG/openMVG/issues/963
