### ISSUE TITLE
ViewPrior  unregistered polymorphic type error

### ISSUE THREAD

**Issue by hcjghr** [openMVG/openMVG#960]
Hi,

Using the latest code from the develop branch I have noticed an error (Trying to save an unregistered polymorphic type (openMVG::sfm::ViewPriors)) when trying to use GPS priors. 

Simpliest way to reproduce it, is to replace line 399 in main_SfMInit_ImageListing.cpp with:

const std::pair<bool, Vec3> gps_info = std::make_pair<bool, Vec3>(true,Vec3(2,2,2));

In this way we impose a gps prior regardless of the image information. Running that results in:

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
terminate called after throwing an instance of 'cereal::Exception'
  what():  Trying to save an unregistered polymorphic type (openMVG::sfm::ViewPriors).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.
Aborted (core dumped)

Cheers,
Klemen

**Comment by rjanvier** [comment]
Hello,
I fixed it in a local branch, I will make the PR tomorrow, if you can wait.

**Comment by hcjghr** [comment]
Hi,

is it possible to point me to the problem so I can fix it for myself in the meantime (I completely understand you dont have time to do a PR immediately). If it would take too much time of course I can wait.

cheers,
Klemen

**Comment by pmoulon** [comment]
Hi @hcjghr, thank you for your feedback.
It's certainly related to a missing `#include <openMVG/sfm/sfm_view_priors_io.hpp>` here https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_io.cpp

**Comment by rjanvier** [comment]
Sorry Klemen,  day off yesterday, so I had no access to my computer. the PR is here #965.

**Comment by pmoulon** [comment]
The PR have been merged to develop ;-)

**Comment by hcjghr** [comment]
Thanks @rjanvier and @pmoulon!

**Comment by pmoulon** [comment]
You're welcome
