### ISSUE TITLE
Problems with SfM reconstruction of 'simulated' environments

### ISSUE THREAD

**Issue by saihv** [openMVG/openMVG#971]
I have recently been working with adapting SfM reconstruction and localization for image datasets from a simulator (Unreal Engine), and I have been encountering some peculiar problems with it. For example, I captured these two very simple images and ran them through openMVG's sequential SfM pipeline. 

![screenshot from 2017-07-06 21-18-25](https://user-images.githubusercontent.com/2274262/27940694-d39b9d3e-6291-11e7-9468-44810f385c5f.png)

The intrinsics were provided beforehand, and it looks like detection and matching works fine: as you can see in the image below, the matches seem to adhere to a decent geometric model without too many obvious outliers. 

![screenshot from 2017-07-06 21-22-54](https://user-images.githubusercontent.com/2274262/27940700-dad36118-6291-11e7-9264-3ab499cfd895.png)

But when I finally perform reconstruction, the point cloud comes out looking off. I can identify the main structure, yet there are so many points dispersed in the Z direction. But the camera viewpoints are still localized properly within this badly triangulated scene. 

![screenshot from 2017-07-06 21-11-07](https://user-images.githubusercontent.com/2274262/27940703-e03e4f1e-6291-11e7-973b-d89fd6e31b0a.png)

One thing I first wondered about was whether the repetitive structure (because of the simulator's textures) was the problem, but I don't know if there is a good way of finding that out. Because it is a simulator, I can easily 'improve' the environment, but it would be helpful to find out what's causing the problem so I can avoid it. Is there any way to dig deeper into this to find the issue? I'm attaching the two source images to this post if anyone is interested in taking a look further. Thanks!

[UnrealImages.zip](https://github.com/openMVG/openMVG/files/1129824/UnrealImages.zip)

**Comment by pmoulon** [comment]
Hi @saihv 
Thank you for the illustration in your issue ticket.

You're right the bad triangulation are certainly due to bad correspondences (repetitive structure).

For a fast test in order to limit the number of false matches along the epipolar line you can try this:
1. launch ComputeMatches with `-g h` in order to constraint the match to be on a plane
2. rename matches.h.txt to matches.f.txt
3. launch your IncrementalSfM

PS: Please, can you provide the focal length you have used for your experiments?

I would love to have a tool to pick a 3d point and see it's projection in the images ;-)
-> Any help to build such a tool would be nice ;-)

**Comment by saihv** [comment]
@pmoulon: Thanks for the answer: your trick with the homography constraint works! Now the reconstruction is almost perfectly on a plane, but with less number of points than the original one: so it's definitely false matches that are causing the dispersion. By the way, the focal length was 1280 pixels.

And yes, a tool to check 3d-2D correspondences would be really useful for debugging. Perhaps a simple python GUI that can displays both the 3D points and one image; and then based on which one's clicked, the BIN file can be parsed to find the corresponding 2D point: and then it can be displayed on the image.

**Comment by pmoulon** [comment]
Can we close this issue?

**Comment by saihv** [comment]
Yes, thank you for the help.

**Comment by pmoulon** [comment]
You're welcome
