### ISSUE TITLE
Installing SuiteSparse

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#976]
Pierre,

The link to the installation instructions seems to be down.

Anyway I am working on generating statistics from the bundle adjustment. This involves extracting information from the covariance matrix.

After contacting Sameer at Ceres he advises that I need to use SUITESPARSE.

I am having trouble installing Suitesparse. I click SuiteSparse and Lapack in CMake but it doesn't find theses libraries.

I downloaded Lapack but these is no place to point to these directories.

I suspect i may need to compile separately and re-link ceres with Cmake.

Is this correct or is there something i am missing (again).

I am using Windows (unfortunately) as I am sure the Linux install would do this all automatically.

Regards,

Alan.

**Comment by pmoulon** [comment]
You can certainly start from here: http://sylvain.duchene.im/how-to-build-ceres-under-windows/

For sure on Linux it will be more easy (you can use a Linux Virtual Machine in your Windows env)

**Comment by bigakoz** [comment]
Pierre,

I found a script on the Ceres forum that made the process reasonably painless in windows.

 https://github.com/andy-held/bfsCeres
