### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#978]
Pierre,

I have recently completed processing of a large data set of aerial photography with openMVG with excellent results.

I have been contacted by a large company that specializes in Lidar acquisition and processing. They are interested in adding photogrammetric processing to add to their products line. They have large computer resources (over 1000 cores) and cloud based storage.

Are there any licensing issues associated with using your software. Obviously my plan is to generate income from this.

I understand that the GPL licensing requires that I share back to openMVG any software changes that are made.

At this stage the only additions I am planning.
1. Replace all the file IO with a relation database.
2. Add full geodetic transformations to accommadate different datums and projections.
3. Full statistics on the solution
4. Add a normalization program to transform from ECEF to a simplified coordinate system that solves an issue with openMVE only using floats (24 bit resolution limit on numbers).
5. True orthophoto generation.
6. Make the processing an online web application.

I am happy share all this (apart from the web application is it will be done by others)

Please advise of anything I need to do to comply with your licensing requirements.

Regards,

Alan

**Comment by rjanvier** [comment]
Hello Allan. OpenMVG is not GPL, it's MPL2.  it's more permissive.
2. is already WIP on my side. I have some change to submit to bootsrap this, but I'm waiting the merge some of the changes proposed by @hcjghr before. 
I have some code to make 5. happen too, mainly thanks to the work on MVS already done by @rperrot but no ETA for this now.

**Comment by bigakoz** [comment]
Ok

As regards to geodetic conversion. I have a complete geodetic libray that I can share.

I am a geodetic surveyor have had this for years and happy for others to use

**Comment by rjanvier** [comment]
Nice. Originally,  I though to rely on proj4. Maybe we could keep in touch for that because my knowledge of geodesy should not be as good as yours.

**Comment by pmoulon** [comment]
As said by @rjanvier OpenMVG is MPL2 licensed.
You can see on Github the summary about the permissions and limitations around this licence
https://github.com/openMVG/openMVG/blob/master/LICENSE

You can use it in a commercial context without trouble and I would be happy with it.
If you meet trouble about the SIFT patent (depending of the country of your customer), you can safely use AKAZE or write or use another alternative.

For sure we would be happy to collaborate or provide feedback on the 6 points you have listed.

As a summary, any package distribution you will make must have attached the OpenMVG license file and tell which OpenMVG version are you using and you are free to develop any new code around OpenMVG with the license of your choice.

**Comment by mrgloom** [comment]
@bigakoz Looks like your additions related to the tasks mentioned here: https://github.com/openMVG/openMVG/issues/914

**Comment by pmoulon** [comment]
@bigakoz Any progress on your project?

**Comment by jpwhitney** [comment]
> Ok
> 
> As regards to geodetic conversion. I have a complete geodetic libray that I can share.
> 
> I am a geodetic surveyor have had this for years and happy for others to use

If you could send that to me I would be very grateful.

**Comment by BigAloz** [comment]
whats your email
