### ISSUE TITLE
What is the recommended eigen version?

### ISSUE THREAD

**Issue by FuchtelJockel** [openMVG/openMVG#980]
If I use eigen 3.3.4:
<code>/usr/include/ceres/jet.h:251:3: error: requested alignment is less than minimum alignment of 32 for type 'Eigen::Matrix<double, 16, 1, kAlignHint>'
  alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;</code>
If I use eigen 3.2.10:
<code>/usr/include/eigen3/Eigen/src/Core/DenseBase.h:496:7: error: static_assert failed
      "THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CALLED_FOR_DENSE_OBJECTS"
      EIGEN_STATIC_ASSERT((internal::is_same<Dest,void>::value),THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CAL...
</code>

**Comment by pmoulon** [comment]
Actual internal version is Eigen 3.3.1.
Si this version should work fine.

**Comment by pmoulon** [comment]
Any feedback?

**Comment by FuchtelJockel** [comment]
gcc 7.1.1 works but 
clang 4.0.1 still reports:
<code>
/usr/include/ceres/jet.h:251:3: error: requested alignment is less than minimum alignment of 32 for type 'Eigen::Matrix<double, 16, 1, kAlignHint>'
  alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;
</code>
gcc fails now at:
<code>
/home/alexander/Dokumente/Build/openMVG/src/openMVG/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:381:98: Fehler: »OPENMVG_SFM_WEBGL_SRC_PATH« wurde in diesem Gültigkeitsbereich nicht definiert
   const std::string inputFilename1 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_SRC_PATH ) + inputFolder , inputName );
/home/alexander/Dokumente/Build/openMVG/src/openMVG/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:381:98: Anmerkung: empfohlene Alternative: »OPENMVG_SFM_SFM_VIEW_HPP«
   const std::string inputFilename1 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_SRC_PATH ) + inputFolder , inputName );
/home/alexander/Dokumente/Build/openMVG/src/openMVG/src/software/SfMWebGLViewer/openMVG_main_openMVG2WebGL.cpp:382:98: Fehler: »OPENMVG_SFM_WEBGL_INSTALL_SHARED_PATH« wurde in diesem Gültigkeitsbereich nicht definiert
   const std::string inputFilename2 = stlplus::create_filespec( stlplus::folder_append_separator( OPENMVG_SFM_WEBGL_INSTALL_SHARED_PATH ) +  inputFolder , inputName );
</code>

**Comment by pmoulon** [comment]
> OPENMVG_SFM_WEBGL_SRC_PATH

As you see the variable is defined there:
https://github.com/openMVG/openMVG/search?utf8=%E2%9C%93&q=OPENMVG_SFM_WEBGL_SRC_PATH&type=

The thing is that compilation is working in the CI (travis) so perhaps there is a missing include path in your case.

> kAlignHint
We can certainly understand what's going on on asking to the ceres-solver mailing list.

**Comment by FuchtelJockel** [comment]
Got it working
Had some include paths messed up in my PKGBUILD file.
Thanks for your help.

**Comment by bchretien** [comment]
> If I use eigen 3.2.10:
> /usr/include/eigen3/Eigen/src/Core/DenseBase.h:496:7: error: static_assert failed "THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CALLED_FOR_DENSE_OBJECTS" EIGEN_STATIC_ASSERT((internal::is_same<Dest,void>::value),THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CAL...

This can be fixed by replacing `Eigen::EigenBase` by `Eigen::DenseBase` in `InterfaceMVS.h` (cf. [this](https://stackoverflow.com/questions/23544049/compile-time-error-from-eigen-the-eval-evalto-function-should-never-be-called-f)).
