### ISSUE TITLE
unable to do cmake-gui configure 

### ISSUE THREAD

**Issue by qtnext** [openMVG/openMVG#981]
Hi,

I am trying to compile the last version 1.2  on Windows 10, msvc2015 x64. When I open cmake-gui and click on configure I have the following error: 
"CMake Error at cameras/CMakeLists.txt:3 (UNIT_TEST):
  Unknown CMake command "UNIT_TEST".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it."

Do I missed something ?

Best regards

**Comment by pmoulon** [comment]
Thanks for your feedback.

Strange that you got this error since the main CMakeLists.txt already defined the 
 `cmake_minimum_required` to 3.1 https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L8

Can you tell me if you used the https://github.com/openMVG/openMVG/blob/master/src/ as the path for cmake-gui?

**Comment by qtnext** [comment]
the most important error seems :""CMake Error at cameras/CMakeLists.txt:3 (UNIT_TEST):
Unknown CMake command "UNIT_TEST"."
It don't works if I set source code path with  https://github.com/openMVG/openMVG/blob/master/src/ 
I have CMake Error: The source directory " https:/github.com/openMVG/openMVG/blob/master/src" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by pmoulon** [comment]
Sorry, I mean the corresponding path stored on your disk (the place when you have checkout OpenMVG).

**Comment by qtnext** [comment]
I have tryed and I have the same issue.

**Comment by pmoulon** [comment]
Did you clean the cache between you different try?

**Comment by qtnext** [comment]
Yes I have clean the cache and I have the following issue 
 CMake Error at CMakeLists.txt:100 (message):
  

   submodule(s) are missing, please update your repository:
    > git submodule update -i

**Comment by pmoulon** [comment]
Please do as said in the BUILD file https://github.com/openMVG/openMVG/blob/master/BUILD.md

See the `getting the sources` part

You must do
```
$ git submodule init
$ git submodule update
```

**Comment by qtnext** [comment]
it works if I clone the git  and do the two commands :)
