### ISSUE TITLE
Build Error: "error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type"

### ISSUE THREAD

**Issue by Haelium** [openMVG/openMVG#985]
Keep getting these errors when I try to compile:
"error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type"

Building using MS Visual Studio 2015 on Windows 10 targeting Win64
Building from Master branch

Full build output below:
[OpenMVG_BuildOutput.txt](https://github.com/openMVG/openMVG/files/1150393/OpenMVG_BuildOutput.txt)

Any help with this is greatly appreciated.

**Comment by pmoulon** [comment]
Thank you for the report.
Please consider the develop branch where the problem have been fixed.
See https://github.com/openMVG/openMVG/issues/979

I will merge it to master in some days and release a new minor version
