### ISSUE TITLE
openMVG_main_IncrementalSfM/GlobalSfM crashes

### ISSUE THREAD

**Issue by FuchtelJockel** [openMVG/openMVG#986]
After compiling it successful with gcc 7.1.1
openMVG_main_IncrementalSfM/GlobalSfM crashes every time after "Automatic selection of an initial pair" or "Relative pose computation"

Arch Linux 64bit
AMD FX-8350
openMVG master
Eigen 3.3.1
ceres-solver 1.12

Log:
[openMVG_main_IncrementalSfM.log.txt](https://github.com/openMVG/openMVG/files/1150998/openMVG_main_IncrementalSfM.log.txt)
[openMVG_main_GlobalSfM.log.txt](https://github.com/openMVG/openMVG/files/1151005/openMVG_main_GlobalSfM.log.txt)

**Comment by pmoulon** [comment]
Can make a run in debug and run gdb inorder to have the problematic line?

Or else can you share me your dataset (I need only the matches directory).
(ps: you can remove the *.desc in the archive you share to me in order to make a tinier archive)

**Comment by FuchtelJockel** [comment]
I used the SceauxCastle from your repo
[matches.zip](https://github.com/openMVG/openMVG/files/1151891/matches.zip)
The only thing I was able to get from gdb was the backtrace:
[(gdb) bt.txt](https://github.com/openMVG/openMVG/files/1152075/gdb.bt.txt)

**Comment by pmoulon** [comment]
Thank you. Seems like it crash in Ceres.

Can you tell me if you are using the internal or an external ceres?

**Comment by FuchtelJockel** [comment]
I compiled ceres-solver from the AUR because it always worked and I guess it's external then.

**Comment by FuchtelJockel** [comment]
I have definitely used the external version because it works with the internal one.

**Comment by pmoulon** [comment]
When you launch cmake you must have a report that show you if OpenMVG is using internal or external version.

i.e:
```
-- EIGEN: 3.3.1 (internal)
-- CERES: 1.12.0 (external)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF: 4.0.7 (external)
-- LIBPNG: 1.6.29 (external)
-- LIBJPEG (external)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: 0.107.8 (internal)
-- LEMON: 1.3 (internal)
```

With this setup on my computer everything is working nice.
I wonder if your problem could be related to a different version of Eigen used for Ceres and OpenMVG.

Can you check that the same Eigen version is used?

**Comment by FuchtelJockel** [comment]
I recompiled everything from ground up and it still doesn't work with my external ceres version.
I just use the internal version that works.

**Comment by pmoulon** [comment]
Can we close the issue?

**Comment by FuchtelJockel** [comment]
Yes
