### ISSUE TITLE
Error on the execution of openMVG_main_ColHarmonize

### ISSUE THREAD

**Issue by alvaro562003** [openMVG/openMVG#988]
Hello,

I took some pictures outside of a statue and of course there was the sun!!!
On the pictures, the color of the statue change according to my relative position. So i try to harmonize the color.

I found some information on:
1) http://openmvg.readthedocs.io/en/latest/software/colorHarmonization/color/
2) https://github.com/openMVG/Color_Harmonization_Image_Dataset
3) https://github.com/openMVG/openMVG/issues/431

So i tested the command:
openMVG_main_ColHarmonize i sfm_data.json -m matches.f.bin -o "\\tmp\\output" 
But i have the error message:

> One of the required directory is not a valid directory
> Something goes wrong in the process
> 
Of course, i triple checked  the existence of the directory  "\tmp\output"

Q 1:  (As i need to understand what i do) What do openMVG_main_ComputeSfM_DataColor compare to openMVG_main_ColHarmonize?

Q 2: Regarding the "-m" parameter should i use "matches.f.bin" or  ""matches.f.txt"?
By the way, in the working directory i find "matches.f.bin"  but  no trace of matches.f.txt.
Previously i set openMVG_main_ComputeMatches with the option  "-g f"

I have other questions, they will come later.

**Comment by alvaro562003** [comment]
Hello,
I found the reason of the error. I change "-m matches.f.bin" by "-m .\matches.f.bin"

**Comment by alvaro562003** [comment]
Hello,  

It works well and produces the images in the output directory.
I didn't pay enough attention to the fact that "Choose your reference image:" was a question!!!!

And now what should i do with the images in the output directory ?

**Comment by pmoulon** [comment]
You must take a look to the produced files and see the corrected images.

**Comment by alvaro562003** [comment]
Yes they seem correct...but it is simply a banana on a table:-)
I will use a bigger dataset in the next days. Actualy, i was not so happy with the color of a 3D object, it is why i am willing to integrate this "color harmonisation" features in the process.
I will give you my opinion after have tested it on my real dataset.

Now how can i integrate these harmonized images in the rest of the process ? 
For the moment, i see 2 option:
1)Should i simply copy them over the original ones  ?
2) Or copy them in the right directory after executing openMVG_main_openMVG2PMVS ?

**Comment by pmoulon** [comment]
You you can copy over the original ones.

`Note: be sure to make a copy of your original images before hand ;-)`

**Comment by alvaro562003** [comment]
I protected the original images :-)
It works very well on dataset of +40 images.
Thanks again
