### ISSUE TITLE
Compiling error C3016

### ISSUE THREAD

**Issue by Eybor** [openMVG/openMVG#992]
Hello,

I am currently trying to compile OpenMVG with visual studio 2015. 

The compilation of [this file](https://github.com/openMVG/openMVG/blob/master/src/software/SfM/clustering/domSetLibrary/domset.cc) fails with error C3016. Indicating that types used in a loop parallelized thanks to OpenMP must be signed.  I changed the for loops at lines 440, 457 and 471, using the macro for_parallel defined in the file and it works now.

**Comment by pmoulon** [comment]
Please use the develop branch. The compilation bug have been fixed there.
