### ISSUE TITLE
Windows installation contains absolute paths.

### ISSUE THREAD

**Issue by bjornpiltz** [openMVG/openMVG#993]
After installing OpenMVG on Windows `OpenMVGConfig.cmake` sets `OPENMVG_INCLUDE_DIR` to the absolute path where it was just installed. This prohibits deploying the installation to other machines. Ceres manages to work around this as follows:
```cmake
  # Build the absolute root install directory as a relative path
  # (determined when Ceres was configured & built) from the current
  # install directory for this this file.  This allows for the install
  # tree to be relocated, after Ceres was built, outside of CMake.
  get_filename_component(CURRENT_ROOT_INSTALL_DIR
    ${CERES_CURRENT_CONFIG_DIR}/../
    ABSOLUTE)
  set(CERES_INCLUDE_DIR "${CURRENT_ROOT_INSTALL_DIR}/include")
  list(APPEND CERES_INCLUDE_DIRS ${CERES_INCLUDE_DIR})
```

This affects `OPENMVG_INCLUDE_DIRS` in `OpenMVGConfig.cmake` as well as the `INTERFACE_LINK_LIBRARIES` property of target `openMVG_image` in `OpenMVGTargets.cmake`.

**Comment by bjornpiltz** [comment]
Here is probably the solution to the problem with `INTERFACE_LINK_LIBRARIES`:
https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#creating-relocatable-packages

**Comment by rperrot** [comment]
Yes, relocable using generator expression should give the good link. However I'm a little bit scared about dependencies. 

This could also help us : 

https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

(especially in the cmake.in file : 

```
# Compute paths
get_filename_component(FOOBAR_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(FOOBAR_INCLUDE_DIRS "@CONF_INCLUDE_DIRS@")

```

**Comment by bjornpiltz** [comment]
The `INTERFACE_LINK_LIBRARIES` issue might be a bit trickier, since the dependencies can be external. The `OPENMVG_INCLUDE_DIRS` should be easy enough, though. I think the following should do it:

```diff
 # set the include directories for OpenMVG (itself) and all (potentially optional)
 # dependencies with which OpenMVG was compiled.
-set(OPENMVG_INCLUDE_DIRS "@OpenMVG_INCLUDE_DIRS@")
+set(OPENMVG_INCLUDE_DIRS "${CURRENT_ROOT_INSTALL_DIR}/include;${CURRENT_ROOT_INSTALL_DIR}/include/openMVG_dependencies"
 # set the compile flags for OpenMVG.
 set(OPENMVG_CFLAGS "@OpenMVG_CFLAGS@")```

It seems wrong to pass on `OpenMVG_INCLUDE_DIRS` in the first place since it contains many references (FLANN, lemon) which are internal to OpenMVG and of no interest to the user.
