### ISSUE TITLE
4K video for reconstruction

### ISSUE THREAD

**Issue by Ntweat** [openMVG/openMVG#995]
Hi

I am trying to reconstruct 3D shapes from videos, by uncompressing video into frames and then using those frames as inputs. 
To estimate the focal length I am using f = 1.2*max(w,h)
The system works fine for normal videos (1920 x 1080 ) the flow works fine, but when I use the same flow for 4K videos (3840 x 2160 ) The flow fails. The sparse cloud for 4K comes out very flat with a lot of missing points.
 For dense reconstruction I am using openMVS, it works fine when using normal vidoes but fails when I use 4K. 
I think the problem is that the sparse cloud is not good for 4K.  

Any suggestions on how to fix it?

**Comment by pmoulon** [comment]
Hi,
Did you check the pairwise correspondences?
- for that you can look to export them using main_exportMatches in order to understand if the matching is ok or  not

Did you check the look of the pairwise graph?
- if you have graphviz on your computer some graph are logged in the match directory. See the file geometric_matches.svg`

Using large resolution images makes sometimes the SIFT matching confuse.

**Comment by Ntweat** [comment]
@pmoulon 

I will check and get back to you.
Thank you

**Comment by pmoulon** [comment]
Can you tell me which SfM pipeline did you used?

**Comment by Ntweat** [comment]
Global SfM
I haven't been able to check, but : 
1. For 10 to 15 images it produced no model
2. For 30-45 images it produced flat model
3. For 65+ images it made a proper model 

by my experience with SD images even with 10 images it makes the model

**Comment by pmoulon** [comment]
For a fast test can you check if it's working with the Incremental/Sequential pipeline?

- GlobalSfM is not robust yet to all the configuration...

**Comment by Ntweat** [comment]
Hi

I finally understood why 4K images area bad idea for camera pose estimation. You are never going to get the same trackable features, everytime you extract features you will get different features. 

With that being said, I want to run openMVG on scaled down image but when I pass it to openMVS I want to pass the original 4K images. 
Is there any way to do this?
What parameters would need to be changed?

One solution I found is to export NVM file from openMVG and import it into openMVS with new images.
But I think I will need to edit the NVM file (for principle point). I tried looking for documentation for NVM but could not find any.

**Comment by pmoulon** [comment]
You can do this.

- So first process the scene with your reduced image size dataset.
- Then export the scene as json (use openMVG_main_ConvertSfM_DataFormat).
- change the root_path to point to your original image
- rescale the focal and principal point field for every intrinsic (you have to multiply by the inverse of the downsampling ratio)
- use openMVG_main_openMVG2openMVS with this updated file

**Comment by Ntweat** [comment]
I will try it and get back!
Thank you!!

**Comment by Ntweat** [comment]
Hi 
will I have to change anything else? ?
In the structure?

**Comment by pmoulon** [comment]
Nope.

**Comment by Ntweat** [comment]
Thanks
am working on it :)
