### ISSUE TITLE
Question: Absolute scale in point cloud

### ISSUE THREAD

**Issue by treyfortmuller** [openMVG/openMVG#996]
I am utilizing OpenMVG with a calibrated camera and known camera poses (I have intrinsic and extrinsic parameters with respect to a world coordinate system that I defined). Because I have the translation of the camera in world units (let's say in inches for example), I figure that I should be able to reconstruct a point cloud to scale in inches as well. What is the best way to go about achieving this (some high level ideas would suffice)? Is there a way to programmatically access the coordinates of points in the outputted point cloud with respect to some origin I define? How is the origin of the point cloud defined by default?

**Comment by pmoulon** [comment]
You have many possibilities:

1. Setup your camera configuration in a sfm_data.json file and triangulated the matches.
you will have to:
- write a tiny program that create a sfm_data.json file from your data
- compute features thanks to OpenMVG (ComputeFeatures)
- compute matches thanks to OpenMVG (ComputeMatches)
- triangulate your matches thanks to OpenMVG (ComputeStructureFromKnownPoses)
Then your 3d points will be in your coordinates system.

2. Perform a regular calibration with the OpenMVG tools and force some view to use your know positions (ViewPriors). It will allow to register your scene to your know camera position.

3. programmatically access the coordinates of points in the outputted point cloud.
You can export your sfm_data.bin scene to JSON, XML or PLY and then read the 3d point coordinates.
Use ConvertSfM_DataFormat to convert from .bin to .xml, .json, .ply.

4. Default coordinates system
The default coordinates system should be somewhere around (0,0,0) but it can drift a bit due to BA.
You can easily fix your coordinates system by using the registration tools from OpenMVG (ViewPriors or EXIF GPS data). See https://github.com/openMVG/openMVG/blob/master/src/software/Geodesy/registration_to_exif_gps_position.cpp
You can modify this binary to load your position for each camera and let the sample do the registration for you. Using only the camera centers must be ok.

**Comment by treyfortmuller** [comment]
Hi @pmoulon thank you so much for the thorough response and awesome library. I've tried implementing bullet point number 1. 

**write a tiny program that create a sfm_data.json file from your data**

Right now I have a small python script calling `openMVG_main_SfMInit_ImageListing` with my known camera intrinsics like so:
```
print("INIT IMAGE LISTING")
pIntrisics = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),
                               "-i", input_dir,
                               "-o", matches_dir,
                               "-d", camera_file_params,
                               "-k", "650;0;240;0;650;360;0;0;1"])
pIntrisics.wait()
```
Then I go edit the generated `sfm_data.json` by hand to add the extrinsics for each view because as far as I know OpenMVG doesn't support a way to add extrinsics to the `sfm_data.json` from a function call. In the future I will write a small python script to add the extrinsic parameters to the `sfm_data.json` automatically but wanted to make sure the rest of the pipeline worked for me first (perhaps I could contribute to the binary for json creation to allow for extrinsics to be added).

**compute features thanks to OpenMVG (ComputeFeatures)**
**compute matches thanks to OpenMVG (ComputeMatches)**

Done and done:
```
print("COMPUTE SIFT FEATURES")
pFeatures = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),
                              "-i", matches_dir + "/sfm_data.json",
                              "-o", matches_dir,
                              "-m", "SIFT",
                              "-f", "1",
                              "-p", "ULTRA"])  # NORMAL, HIGH, ULTRA (high recommended for global pipeline)
pFeatures.wait()

print("COMPUTE MATCHES")
pMatches = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeMatches"),
                             "-i", matches_dir + "/sfm_data.json",
                             "-o", matches_dir,
                             "-r", "0.8",  # nearest neighbor distance ratio (0.8 recommended for global pipeline)
                             "-g", "e",
                             "-f", "1"])
pMatches.wait()
```
**triangulate your matches thanks to OpenMVG (ComputeStructureFromKnownPoses) then your 3D points will be in your coordinates system.**
I call `openMVG_main_ComputeStructureFromKnownPoses` on my `sfm_data.json` file:

```
print("STRUCTURE FROM KNOWN POSES")
pRecons = subprocess.Popen([os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeStructureFromKnownPoses"),
                            "-i", matches_dir + "/sfm_data.json",
                            "-m", matches_dir,
                            "-o", os.path.join(reconstruction_dir, "robust.ply"),
                            "-b", "ON",  # perform a bundle adjustment on this data
                            "-r", "4.0"])  # maximum pixel reprojection error to use for triangulation (4.0 default)
pRecons.wait()
```
This however leads to no landmarks being found and `robust.ply` has no points in it. Here is the output of `openMVG_main_ComputeStructureFromKnownPoses`:

```
STRUCTURE FROM KNOWN POSES
Compute Structure from the provided poses

- Regions Loading -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Loaded a sfm_data scene with:
 #views: 4
 #poses: 4
 #intrinsics: 1
 #tracks: 0
=============================================================
Robust triangulation of the tracks
 - Triangulation of guided epipolar geometry matches
=============================================================

Compute frustum intersection
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Compute pairwise fundamental guided matching:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Per triplet tracks validation (discard spurious correspondences):
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************
***************************************
*
*
Tracks to structure conversion:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

Structure estimation took (s): 0.

#landmark found: 0
...Generating SfM_Report.html
Bundle adjustment...

Bundle Adjustment statistics (approximated RMSE):
 #views: 4
 #poses: 0
 #intrinsics: 1
 #tracks: 0
 #residuals: 0
 Initial RMSE: -nan
 Final RMSE: -nan
 Time (s): 1.8578e-05

Found a sfm_data scene with:
 #views: 4
 #poses: 0
 #intrinsics: 1
 #tracks: 0
```
I think this issue is arising from me entering my extrinsic parameters incorrectly. In the docs I could not find any specification for how the extrinsics should be expressed in the `sfm_data.json` file.  More specifically, how are the rotation matrices defined?

I wrote a python script to calculate the cartesian coordinates of my camera's center and rotation matrix for each frame. Here is it's output:
```
----- FRAME: 0 -----
COORDS: 
[  7.5      12.99038   0.     ]
ROT_MTX: 
[[ 0.5     -0.86603  0.     ]
 [ 0.86603  0.5      0.     ]
 [ 0.       0.       1.     ]]


----- FRAME: 1 -----
COORDS: 
[  2.60472  14.77212   0.     ]
ROT_MTX: 
[[ 0.17365 -0.98481  0.     ]
 [ 0.98481  0.17365  0.     ]
 [ 0.       0.       1.     ]]


----- FRAME: 2 -----
COORDS: 
[ -2.60472  14.77212   0.     ]
ROT_MTX: 
[[-0.17365 -0.98481  0.     ]
 [ 0.98481 -0.17365  0.     ]
 [ 0.       0.       1.     ]]


----- FRAME: 3 -----
COORDS: 
[ -7.5      12.99038   0.     ]
ROT_MTX: 
[[-0.5     -0.86603  0.     ]
 [ 0.86603 -0.5      0.     ]
 [ 0.       0.       1.     ]]

```
And here is my `sfm_data.json` file. I entered the columns of the rotation matrix in each entry of "rotation," is that correct? By the way, I learned the format of the `sfm_data.json` for the extrinsics from #412 where another user added his own json file, I couldn't find those details in the docs.

[sfm_data.json.zip](https://github.com/openMVG/openMVG/files/1181379/sfm_data.json.zip)

Lastly, I couldn't find any mention of the "structure" or "control_points" entries in the json file in the docs, what is their purpose? After I am deeper into my project I would be happy to contribute to the docs to make a task similar to what I am trying to accomplish a little more obvious.

Thank you so much for the support.

**Comment by treyfortmuller** [comment]
@rperrot @pmoulon any hints on this topic?

**Comment by rperrot** [comment]
@treyfortmuller Sorry that's another question, It would be better to open a new thread (with corresponding title). 

I think the main issue is that you have 0 track as stated by the line : 

> - Regions Loading -
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> ***************************************************
> Loaded a sfm_data scene with:
>  #views: 4
>  #poses: 4
>  #intrinsics: 1
>  **#tracks: 0**

**Comment by treyfortmuller** [comment]
Got it, will do.
