### ISSUE TITLE
Different use case for points filtering?

### ISSUE THREAD

**Issue by bkjohnson** [openMVG/openMVG#997]
I've read all of the comments on #987 as well as #863 but I'm still a little confused.  I've been trying to use `openMVG_main_PointsFiltering` but with no success, and I'm not sure if it's because my use case isn't traditional or if I'm just not using the right factor or something.  Here is a sample of the kind of positions I'm working with.  It was made with the global SfM process:

![image](https://user-images.githubusercontent.com/2008881/28503243-bbf7fd8c-6fc8-11e7-9795-5e699feb4d40.png)

Here is the OpenMVS result minus the mesh refinement (the potted plant is the subject):
![image](https://user-images.githubusercontent.com/2008881/28503211-c6aad3ea-6fc7-11e7-85ec-8f42f0ea2185.png)

Since I'm encircling the subject and it is at a much smaller scale than landscape photos taken from a drone, is it even possible to filter out the background in this case?  In my head I'm imagining that the camera positions create a virtual "cylinder" around the subject and any point outside of that cylinder gets discarded, but no matter what factor I give to `PointsFiltering` I always get the same output and my `.ply` file remains empty:

```shell

-----------------------------------------------------------
Filter Structure based on statistics computed per view    :
-----------------------------------------------------------

#point depth filter: 0 measurements removed
MIN MEDIAN DEPTH VALUE = 1.79769e+308
```

**Comment by pmoulon** [comment]
Can you provide me your sfm_data.bin in order to let me give a look?

**Comment by bkjohnson** [comment]
Sure thing.  I uploaded it [here](https://drive.google.com/open?id=0BzgawcWmRt2nVVF3NkZOSGltczQ)

**Comment by pmoulon** [comment]
Launching with the default arguments give me:
```
-----------------------------------------------------------
Filter Structure based on statistics computed per view    :
-----------------------------------------------------------

#point depth filter: 1 measurements removed
MIN MEDIAN DEPTH VALUE = 0.011042
```

When I tried with `-f 1.2` I obtain this point cloud and this message:

```
-----------------------------------------------------------
Filter Structure based on statistics computed per view    :
-----------------------------------------------------------
#point depth filter: 6589 measurements removed
MIN MEDIAN DEPTH VALUE = 0.011042
```

![test_f_2 100](https://user-images.githubusercontent.com/3235050/28504150-803f0e18-6fc6-11e7-9fe2-5e361a8380bf.png)

Can you provide me more detail about your configuration (Linux, Windows)?
- it seems that in your case the median value is not computed... -> Are you sure you pointed the sfm_data.bin file and not the sfm_data.json file?

**Comment by bkjohnson** [comment]
I'm using Linux, but now I suppose it's my own fault.  I was following the code [here](https://github.com/openMVG/openMVG/blob/6ce820b2844a98941a5d2543050f4e278a323800/src/software/SfM/SfM_GlobalPipeline.py.in#L66) so I ended up using the json instead of the bin file.  I guess I should've paid more attention to the comments that specified the bin file, my apologies.  

I'll try using the .bin once I get home tonight and see if I can get the filtering to properly work.

**Comment by pmoulon** [comment]
Perhaps the best way to deal with such case of usage would be to add in the binary a safe guard to say that the scene is empty and so that nothing can be computed...

Keep me updated when you will use the .bin?

**Comment by bkjohnson** [comment]
I just tried PointsFiltering using the .bin with an `-f` of 1.2 and this is what I got:

```

-----------------------------------------------------------
Filter Structure based on statistics computed per view    :
-----------------------------------------------------------

#point depth filter: 25954 measurements removed
MIN MEDIAN DEPTH VALUE = 0.0442586
```

![image](https://user-images.githubusercontent.com/2008881/28600767-d7c3e924-7179-11e7-84e8-7ca0ab575540.png)


Clearly a lot of points got filtered out but in this case it was too many, so I need to adjust the value.  However, let's say that I find an ideal value that works for this particular set of images.  How do I know it will work for other images?  Maybe the camera was held further away from the subject, maybe the subject is larger, etc.

**Comment by pmoulon** [comment]
For the moment you will need to adjust the value. Since the scene is up to a scale of the reality, every scene will need a different threshold.
I mean there is magic algorithm that will guess that the scene must be clamped at this depth in order to remove the point of the foreground automatically.

Note: You can also limit the mesh size in OpenMVS (you can edit the mesh in meshlab and send it back to RefineMesh and or TextureMesh)

**Comment by pmoulon** [comment]
@bkjohnson Can you close the issue since we have investigate on it and found some solution for it?

**Comment by bkjohnson** [comment]
Yeah, no problem.

**Comment by pmoulon** [comment]
Just found that: http://www.mdpi.com/2313-433X/3/3/39/htm
