### ISSUE TITLE
Global mask not used in features

### ISSUE THREAD

**Issue by MatillaMartin** [openMVG/openMVG#998]
Global mask (mask.png) is not used for feature computation, but local mask (im0_mask.png) is.

To reproduce:
- Folder with 2 images `im0.png`, `im1.png`, and 2 masks: `im0_mask.png`, `mask.png` (same mask pattern on local and global)
- Call ComputeFeatures and exportKeypoints on ULTRA and 4 threads
- Note how only `im0.png` features are masked, whilst `im1.png` has features all over the image

**Comment by pmoulon** [comment]
Hi @MatillaMartin 

Note that the mask.png must be in the output directory:
https://github.com/openMVG/openMVG/blob/master/src/software/SfM/main_ComputeFeatures.cpp#L249
so something like `X/matches`
_mask.png must be in the image directory.

@rjanvier did you remember why we chose this convention?
- global mask in the output directory
- per image mask in the input image directory

@MatillaMartin Can you check if the global mask filtering is working if you move your mask.png to the matches directory? (Please don't forget to force the feature computation `-f 1`)

**Comment by MatillaMartin** [comment]
Oh I see! I put the `mask.png` in the input directory, seems to make more sense..

I will move it to confirm.

**Comment by MatillaMartin** [comment]
Ok confirmed, global mask works if placed in the output folder.

Personally this is not too convenient, because I create a new output folder for each "experiment". This would mean that the script should create the folders, and move the global mask.

Wouldn't it be better to place the mask in the input folder, next to the images? As convention the images cannot be named "mask.png", but thats seems to be reasonable.

**Comment by MatillaMartin** [comment]
Maybe a more complex name, such as `global_mask.png` to make sure there are no name clashes

**Comment by pmoulon** [comment]
@rjanvier Did you remember why we wanted the global mask.png to be in the matches directory rather than in the input image directory?

We can also think about using a command line option to specify the mask filename and so the user can use a file at various location if he wants.

**Comment by rjanvier** [comment]
Unfortunately I do not Pierre, I never use global mask (only test it when I made the commit) and I always though I put this mechanism in the image directory like individual ones... so I agree it makes more sense to put global mask with images. For the naming convention, it's up to you guys, I have no problem with mask.png.

**Comment by pmoulon** [comment]
@MatillaMartin @rjanvier Now the global mask.png is read from the image directory.
I added a robust detection of the mask loading. So now if a mask is on disk and it cannot be read a message is displayed and the feature extraction stops. See #1005
