### ISSUE TITLE
[features] AKAZE feature extraction -> mask filtering bug

### ISSUE THREAD

**Issue by MatillaMartin** [openMVG/openMVG#999]
Computing features with: AKAZE_FLOAT and -n 1, HIGH and ULTRA. A mask is being used.
I get many features at 0,0:

`<circle cx="652.311" cy="37.0453" r="4" stroke="yellow" stroke-width="2" fill="none"/>'`
`<circle cx="0" cy="0" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="0" cy="0" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="0" cy="0" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="0" cy="0" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="1228.22" cy="110.211" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="0" cy="0" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="947.377" cy="129.573" r="4" stroke="yellow" stroke-width="2" fill="none"/>`
`<circle cx="938.788" cy="158.116" r="4" stroke="yellow" stroke-width="2" fill="none"/>`

**Comment by pmoulon** [comment]
Can you share the problematic image and mask here in order to let us investigate?

**Comment by MatillaMartin** [comment]
Find the image, mask and features [here](https://drive.google.com/open?id=0B0veyExidBA2OWt1UURfQUJjZkE)

**Comment by rperrot** [comment]
@pmoulon Is the issue related to the mask usage ? 
@MatillaMartin Did you have the same issue without the mask ?

**Comment by MatillaMartin** [comment]
@rperrot No, without the mask there are no features at 0,0.

**Comment by MatillaMartin** [comment]
@rperrot It happens with both local and global masks

**Comment by rperrot** [comment]
Ok, thank you, using global or local mask doesn't change anything to the feature extraction (code know it's a mask, not if it's a local or a global one). But your information is precious : it's mask related ! 

Thank you, we'll investigate as soon as possible.

**Comment by pmoulon** [comment]
@MatillaMartin 
Thank you for the feedback :+1: .
After investigation it was obviously a bug :bug: that is now fixed on the develop branch!

**Comment by pmoulon** [comment]
Please, can you:
- check check if the fix is working for you?
   -  It must since I checked with your image and mask
- close the issue if the bug is fixed ;-)

**Comment by pmoulon** [comment]
@MatillaMartin Any Feedback?
